### ISSUE TITLE
Feedback on Tutorial: Start Using SAP HANA, express edition

### ISSUE THREAD

**Issue by jacobtan89** [SAPDocuments/Tutorials#1027]
**XSA_DEV & XSA_SHINE has been deactivated.**
Error when running the command line in 2b. & 2c.
Error Line: " * 10: authentication failed SQLSTATE: 28000 "

**Error Source:**
**2. Change the passwords of all XSA users:** 
...
b. Change the
hdbsql -u XSA_DEV –p HXEHana1 –d SystemDB
c. Change the XSA_SHINE user password. Enter:
hdbsql -u XSA_SHINE –p HXEHana1 –d SystemDB
...

**Workaround:**
- Login via HANA Studio / Eclipse
- Open XSA_DEV & XSA_SHINE User, Activate, Change Password

**Demographics:**
- Installed VM
- Server + Application

**Comment by stealth70mde** [comment]
Another one in the Getting started documentation:

Page 11: Change the SSFS Master Keys - Step 2.
2. Re-encrypt the master key of the instance SSFS:
RSEC_SSFS_DATAPATH=/usr/sap/HXE/SYS/global/hdb/security/ssfs
RSEC_SSFS_KEYPATH=/usr/sap/HXE/SYS/global/hdb/security/ssfs rsecssfx changekey $(rsecssfx generatekey -getPlainValueToConsole)

I think this should read:
export RSEC_SSFS_DATAPATH=/usr/sap/HXE/SYS/global/hdb/security/ssfs
export RSEC_SSFS_KEYPATH=/usr/sap/HXE/SYS/global/hdb/security/ssfs 
rsecssfx changekey $(rsecssfx generatekey -getPlainValueToConsole)

Same goes to Step 4.

**Comment by carlsoane** [comment]
Thanks jacobtan889 and stealth70mde for your findings.

jacobtan89:  The xsa_dev and xsa_shine users have unfortunately expired. This issue will be addressed in the next release of the VM.

stealth70mde: We'll address the formatting error and add the Export statements. 

Thanks,


Carl
