### ISSUE TITLE
Feedback on Tutorial: Start Using SAP HANA, express edition

### ISSUE THREAD

**Issue by shirishr** [SAPDocuments/Tutorials#1030]
Opened "hxexsa.ova" with VMWare Workstation 12 player.
Followed steps in "http://go.sap.com/developer/tutorials/hxe-ua-getting-started-vm.html"
upto the step:

a. Change the XSA_ADMIN user password. Enter:
hdbsql -u XSA_ADMIN -p HXEHana1 -d SystemDB

Steps beyond this fail:
Follow the prompts to update the default password.
b. Change the XSA_DEV user password. Enter:
hdbsql -u XSA_DEV -p HXEHana1 -d SystemDB
Follow the prompts to update the default password.
c. Change the XSA_SHINE user password. Enter:
hdbsql -u XSA_SHINE -p HXEHana1 -d SystemDB
Follow the prompts to update the default password.

Any thoughts / advice on these steps?

**Comment by carlsoane** [comment]
Hello shirishr:

The xsa_dev user password has expired. You just need to use system to update xsa_dev's password. Then you login as xsa_dev's using this new password and you will be prompted to change the password again. Enter a second new xsa_dev password and you will be fine.

From the command line, the sequence would be:

hdbsql -u system -p <system password> -d SystemDB "alter user xsa_dev password <xsa_dev_temporary_password>"

Then login as xsa_dev and change the password again.

hdbsql -u xsa_dev -p <password you just created for xsa_dev> -d SystemDB

This will drop you into interactive hdbsql. Once in that tool, enter:

alter user xsa_dev password <new xsa_dev password>


Do the same for the xsa_shine user if you are interested in accessing that user as well.

**Comment by shirishr** [comment]
For some strange reason it is not accepting my password for user SYSTEM.

The amount of time I have spent on getting this instance of HANA up and running...I am discourage to experiment further.


Bye for now,
Shirish


________________________________

**Comment by carlsoane** [comment]
Hello shirishr:

My answer was modified by the github editor. I had used tags around the password term causing the editor to strip them. My answer should have read as follows:

hdbsql -u system -p SYSTEM_PWD -d SystemDB "alter user xsa_dev password XSA_DEV_PWD1"

hdbsql -u xsa_dev -p XSA_DEV_PWD1 -d SystemDB

This will drop you into interactive hdbsql. Once in here enter

alter user xsa_dev password XSA_DEV_PWD2

Then quit the interactive tool. 

Replace everywhere where I have all caps with the corresponding passwords that you have chosen. You will need to alter the password twice on xsa_dev: once when system alters it ( and thereby unexpires the xsa_dev user and a second time when xsa_dev logs in for the first time himself and is required to change his password.) 

Sorry for the confusion. 

Carl

**Comment by shirishr** [comment]
Carl,


How do I reset password for SYSTEM?

I can only login as "hxeadm" at this point.

After logging in as hxeadm, when I issue su SYSTEM I get an error


su: user SYSTEM does not exist


Another thing I noticed is that Host name appears to be hxehost.localdomain.com. I could have sworn that it was plain hxehost before. My browser history  shows I did connect to WebIDE via https://hxehost:50037


Strange?


Bye for now,
Shirish


________________________________

**Comment by carlsoane** [comment]
Hello Shirish:

System can reset his own password:

hdbsql -u system -p SYSTEM_ORIGINAL_PWD -d SystemDB "alter user system password SYSTEM_PWD_NEW"

If this is the first time you've logged in with system, the SYSTEM_ORIGINAL_PWD is HXEHana1.

The short hostname is hxehost. The fully qualified domain name is hxehost.localdomain.com. 

If you have modified the /etc/hosts file on the computer from which you are connecting to hxehost to map the virtual machine's  ip address to hxehost, that will allow you to connect with https://hxehost:50037. 

Regards,

Carl

**Comment by shirishr** [comment]
Carl,


Thank you so much.

I will give it a try.


Bye for now,
Shirish


________________________________
