### ISSUE TITLE
Tutorial xsa-sqlscript-cube: Misleading description, wrong positioned screenshots, missing screenshot

### ISSUE THREAD

**Issue by pfefferf** [SAPDocuments/Tutorials#1054]
Tutorial [xsa-sqlscript-cube](https://github.com/SAPDocuments/Tutorials/tree/master/tutorials/xsa-sqlscript-cube) has several issues:

1) The description says that a view is created with a star join. No star join is used. In addition the description ("Purchase Orders with Currency Conversion") for the view lets assume that a currency conversion is done, but no such conversion is done. There is just a calculated column "ConvGrossAmount" created which gets the value of column GrossAmount w/o additional changes. Also the input parameter created to specify a target currency is never used again.

2) Wrong positioned screenshots: Beginning with step 4 the screenshots are wrong. The screenshot of step 4 belongs still to step 3. All further screenshots have to be moved to one step before.

3) Missing screenshot: For the last step (step 18) the screenshot is missing to be able to compare the output (according to the text "For an initial test make sure your output looks similar to the following:" in the tutorial).

**Comment by ccmehil** [comment]
Sorry about that, we are working to update it now to match to the upcoming SPS12 release as well.
