### ISSUE TITLE
Feedback on Tutorial: Installing Binary

### ISSUE THREAD

**Issue by ThomasHornschuh** [SAPDocuments/Tutorials#1058]
Hi, 
I tried installation on an Amazon EC2 instance on an AMI Image with SLES "SAP Edition" provided by SUSE.
HANA installation runs fine, I wa able to connect to it with Eclipse.
But XSA made problem, I was not able to login into WebIDE. After the Login Screen I got either "permission denied" or  an empty screen stating "Welcome to XSUAA".

Unfortunatley I cant reproduce anymore, because the AMI Images from SUSE has a serious bug that it panics afters the first reboot and is unusable. So I had to restart from scratch.

Hope you provide HANA Express in SAP Cloud Appliance Library one day....

**Comment by ccmehil** [comment]
You should be able to find it under "Solutions" there already.

**Comment by ThomasHornschuh** [comment]
Thanks for the hint. I tried it today. Unfortunately it is even worse. HANA itself runs, I can connect with HANA Studio, I can use SAP HANA Cockpit. But the WebIDE connection is not possible.
There is no tutorial adapted for CAL, so I need to find out  everything. Currently I'm blocked by triing to use the xs commands as described in the binary installer tutorial. But xs login ends wih a prompt API_URL>. Not idea what to enter here. 
My goal is to try out XSA, but no way so far..

I start to get frustrated....

**Comment by ccmehil** [comment]
To find where WebIDE is running - if you run the "xs apps" command (command line) you should see a list of apps and URL's and the WebIDE should show with the port number that it is running on.

**Comment by ThomasHornschuh** [comment]
xs apps complains "No API endpoint targeted. Use 'xs login' or 'xs api' to target an endpoint."

**Comment by ccmehil** [comment]
xs login -a http://<hostname>:30030 -s DEV -u USERNAME -p PASSWORD

**Comment by ccmehil** [comment]
xs login -a http://hostname:30030

**Comment by ThomasHornschuh** [comment]
`xs login -a http://vhcalhxedb:30030 -s DEV -u XSA_ADMIN -p xxxxx

API_URL: http://vhcalhxedb:30030
Could not connect to controller on http://vhcalhxedb:30030
Trying https...

Exception in thread "main" java.lang.IllegalStateException: Client instance has been closed.
        at jersey.repackaged.com.google.common.base.Preconditions.checkState(Preconditions.java:149)
        at org.glassfish.jersey.client.JerseyClient.checkNotClosed(JerseyClient.java:178)
        at org.glassfish.jersey.client.JerseyWebTarget.checkNotClosed(JerseyWebTarget.java:139)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:150)
        at org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:59)
        at com.sap.xs2rt.core.rest.client.RestResource.getWebTarget(RestResource.java:499)
        at com.sap.xs2rt.core.rest.client.RestResource.method(RestResource.java:459)
        at com.sap.xs2rt.core.rest.client.RestResource.get(RestResource.java:235)
        at com.sap.xs2rt.core.generated.rest.resource.client.InfoClient.getInfo(InfoClient.java:64)
        at com.sap.xs2rt.client.impl.operations.TargetOperations.getControllerInfo(TargetOperations.java:100)
        at com.sap.xs2rt.client.impl.command.Login.connect(Login.java:475)
        at com.sap.xs2rt.client.impl.command.Login.connect(Login.java:504)
        at com.sap.xs2rt.client.impl.command.Login.run(Login.java:201)
        at com.sap.xs2rt.client.impl.Main.main(Main.java:271)
`

**Comment by rleibbrandt** [comment]
Hello Thomas

Thank you for your patience.    Do you have access to the AWS console, so you can look at the EC2 instance you created?

I'd like you to review the security group assigned to your image, and check out the inbound TCP rules for that security group.   

There should be a rule  right under SSH for ports 30013 - 3XXXX.    What is the latter part of the range?

If it is 30013, could you change it to 31016, please, and let me know if the behavior changes>

**Comment by ThomasHornschuh** [comment]
Hi,
I checked the rules and it is 30013-30016.  In addition I did my test with Web IDE login and also SAP HANA studio from a second EC2 instance running Windows and be located in the same VPC as the HANA express system. I also ensured that all traffic is allowed inside the security group/VPC.
Also the java stackdump reported above happens locally on the HANA Express system.

I used Google Chrome as Web Browser for accessing WebIDE, because I avoid any trouble with IE security configration. I know also from own UI5 devlopments and using WebIDE on HCP that it works well. 
So I think I did everything right. And because the HANA Express instance was installed over the SAP CAL frontend there was nearly no room for mistakes. If you like I have also no problem to send you login data into my setup. My EMail address maintained in my GitHub account.

**Comment by rleibbrandt** [comment]
Hey Thomas

It's been a while since I've checked in - my apologies for that - I should have asked you to post this in the community forum rather than here, which is meant for feedback on the documentation and tutorials - my fault!   

We've identified some issues users need to be aware of with the CAL deployment, and have documented a way to address these [here](https://blogs.sap.com/2016/11/03/running-sap-hana-express-in-cal-by-the-sap-hana-academy/).

The most important items - the XSA_DEV user needs to be activated, and the API endpoint for XSA needs to be set.    This is described in the video's linked to the blog.

We've also updated the port ranges that CAL opens by default.

**Comment by Wenzork** [comment]
I do have exact the same issue as the TO. Is there any solution yet? I'm hosting an HXE 1.0 SP12 on SLES (VM)....

**Comment by ccmehil** [comment]
Is this still an issue?

**Comment by ThomasHornschuh** [comment]
Hi Graig, 
we are using HXE for a project or students work on, they will continue with the project in May. Latest then we will check it again. In case I have time in between, I will try to install a new  VM based on CAL and check if the problems have been solved in the meantime.
