### ISSUE TITLE
Feedback on Tutorial: SAP HCP predictive services, Access your predictive demo data set using an OData services from a REST client

### ISSUE THREAD

**Issue by vipalma** [SAPDocuments/Tutorials#1063]
The service is Unavailable when i try to access the URL

https://trial<HCP_ID>trial.hanatrial.ondemand.com/public/timeseries/odata/timeseries.xsodata

**Comment by adadouche** [comment]
Hi "vipalma",

Your url should include you HCP account identifier.

If you do use the "Run" button you should be ok, as this will generate the url with your hcp account identifier.

Let me know if this fix your issue.

Thanks

@bdel

**Comment by adadouche** [comment]
Hi "vipalma",

Have you been able to solve the URL issue ased on my previous feedback?
I will consider this issue as solved, but if not feel free to reopen it.

Thanks

@bdel
