### ISSUE TITLE
Feedback on Tutorial: Configure SAP HANA, express edition Security

### ISSUE THREAD

**Issue by AnnieSuantak** [SAPDocuments/Tutorials#1065]
Hi,

I've tried to set up SAP HANA Express Edition using the VM image method. I was able to have everything set up, including the XS engine and Web IDE running on my browser. However, I followed the tutorial: http://go.sap.com/developer/tutorials/hxe-ua-configure-security.html, which is listed as the next step after starting to use HXE. I got stuck at the point where I change the SSFS master keys. I am denied permission to edit the global.ini file. I proceed to the next steps after that step and I am even able to change the root key. However, I am now locked out of the XS login. In my VM terminal, when I try xs login, it says the UAA authentication has failed. On my browser where the Web IDE login screen was formerly present, it now says "A login is required but the uaa configuration is broken or missing". I am now unable to proceed with using Web IDE. How do I go back to the previous working state that my system was in, before I started configuring the HXE security? Is there a way to reverse this current locked-out state?

Thanks,

**Comment by edacostacegb** [comment]
Hello 

I was faced to the same problem. 
As I did not find any solution yet, I have rebuild the VM.

Best regards

Emmanuel

**Comment by ccmehil** [comment]
If you are working with the VM I'd recommend the "snapshot" feature after each step until you have it up and running.

**Comment by edacostacegb** [comment]
The Security tutorial does not work. 
I used https://blogs.sap.com/2016/10/21/managing-encryption-keys-sap-hana-express-sap-hana-academy/ also and I have the following error when trying connect to xs (xs login)

Authentication failed. UAA at https://hxehost:30032/uaa-security is not up.

regards

Emmanuel

**Comment by edacostacegb** [comment]
The Security tutorial does not work. 
I used https://blogs.sap.com/2016/10/21/managing-encryption-keys-sap-hana-express-sap-hana-academy/ also and I have the following error when trying connect to xs (xs login)

Authentication failed. UAA at https://hxehost:30032/uaa-security is not up.

Any solution ?

regards

Emmanuel

**Comment by AnnieSuantak** [comment]
@ccmehil Using snapshots can get me back to a previous working state. However, I am also curious about why permission to edit .ini files is denied. "sudo" does not work.
