### ISSUE TITLE
Feedback on Tutorial: Asynchronous Non-Blocking I/O

### ISSUE THREAD

**Issue by edacostacegb** [SAPDocuments/Tutorials#1071]
Hello,

I am trying this tutorial xsa-node-async on Hana Express. I have copied the needed files from GitHub and I have no error when building.
When I launch the application dev602/web, and display the /exerciseAsync, the websocket connection close.

Can you help ?

**Comment by ccmehil** [comment]
Sounds like a possible network issue, however without more details or logs it's hard to say.

**Comment by edacostacegb** [comment]
Where can I find the logs in the HXE system ?

**Comment by edacostacegb** [comment]
I have the following error in the chrome dev tool:

VM1231:35 WebSocket connection to 'wss://hxehost:51004/node/excAsync' failed: Connection closed before receiving a handshake response

**Comment by ccmehil** [comment]
Are you on the same machine as the server or connecting to it from a different machine? Is your Firewall in that case allowing the 51004 port traffic though?

**Comment by edacostacegb** [comment]
I am using a vm on my machine.
VM Ip = 192.168.100.174
VM host = 192.168.100.69

I have no problem with 
https://hxehost:51004/node/
https://hxehost:51004/node/dummy
https://hxehost:51004/node/dummy2

regards

**Comment by ccmehil** [comment]
I'm trying to reproduce the error and having no luck (which I guess is good).

**Comment by ccmehil** [comment]
Just to eliminate the possibility can you double check that there is no firewall or anything on the machine that might be stopping it - I know the others are working but just in case.

**Comment by ccmehil** [comment]
I'm not 100% sure but I think you have to apply those security settings.
