### ISSUE TITLE
Feedback on Tutorial: Text Bundles

### ISSUE THREAD

**Issue by edacostacegb** [SAPDocuments/Tutorials#1073]
Hello 

I have two problems about the packages.
1 - In package.json, you use the command latest but it doesn't work in the VM. I have to enter the version provided by the Build debugger.

2 - About accept-language-parser package:
npm ERR! 404 no such package available : accept-language-parser
npm ERR! 404 
npm ERR! 404 'accept-language-parser' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'js'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Regards

Emmanuel

**Comment by ccmehil** [comment]
https://www.npmjs.com/package/accept-language-parser
