### ISSUE TITLE
Feedback on Tutorial: Configure SAP HANA, express edition Security

### ISSUE THREAD

**Issue by edacostacegb** [SAPDocuments/Tutorials#1086]
The Security tutorial does not work. 
I used https://blogs.sap.com/2016/10/21/managing-encryption-keys-sap-hana-express-sap-hana-academy/ also and I have the following error when trying connect to xs (xs login)

Authentication failed. UAA at https://hxehost:30032/uaa-security is not up.

Any solution ?

regards

Emmanuel

**Comment by maxnuf** [comment]
Related: https://answers.sap.com/questions/27365/uaa-security-is-not-up-on-hana-express.html
Current tutorial has`Server Only`  vm in mind. The `Server + applications` vm has `SAPXSUAASAML` PSE with `CERTIFICATE_USAGE = OWN` stored in `PSE_CERTIFICATES` table.

**Comment by JCurrie27** [comment]
Hello: Have you tried configuring security using SAP HANA 2.0, express edition? The security functionality was completely redesigned and streamlined in version 2.0. If you are installing the 2.0 virtual machine package, follow the 2.0 security tutorial at:
http://www.sap.com/developer/tutorials/hxe-ua-configure-security.html
Hope this helps,
John Currie
