### ISSUE TITLE
Feedback on Tutorial: Start Using SAP HANA, express edition

### ISSUE THREAD

**Issue by amolguptasap** [SAPDocuments/Tutorials#1109]
http://go.sap.com/developer/tutorials/hxe-ua-getting-started-vm.html
or the guide accompanying the SAP Hana Express suggests recording ip using /sbin/ifconfig and then using url
http:<ip>:8000
to access the XSEngine.

In my case IP was showing as 127.0.0.1 and
http://127.0.0.1:8000
did not show the expected details.

**Comment by ccmehil** [comment]
add a -a to the command to see "all" network devices.
