### ISSUE TITLE
Feedback on Tutorial: Getting Started with SAP HANA, express edition (Binary Installer Method)

### ISSUE THREAD

**Issue by jpenninkhof** [SAPDocuments/Tutorials#1110]
In the section in which the system user is being disabled, it might be better to copy the system user from the security cockpit instead of creating a new one from the command line. The user that is being created still misses a bunch of authorisations, and when you deactivate your system user straight after that, you may end-up with a system that can't be used for what it's intended for.

**Comment by ccmehil** [comment]
Excellent point thank you!
