### ISSUE TITLE
Feedback on Tutorial: Start Using SAP HANA, express edition

### ISSUE THREAD

**Issue by Taryck** [SAPDocuments/Tutorials#1115]
How to change keyboard layout ?
Because it's very difficult to input password when kayboard layout is not the expected one !!!

**Comment by JCurrie27** [comment]
Hello: In the Q&A section of the SAP HANA, express edition community page (http://www.sap.com/developer/topics/sap-hana-express.community.html), there is a post covering this issue:
https://answers.sap.com/questions/69981/sap-hana-express-edition-keyboard-layout.html
Hope this helps,
John Currie
