### ISSUE TITLE
Feedback on Tutorial: SAP HANA XS Classic, Access your first data in a SAP HANA XSC Application

### ISSUE THREAD

**Issue by wizbongre** [SAPDocuments/Tutorials#1119]
At the top of the revised code for the mylibrary.xsjs file, the characters "js" appear, which stop the app running.  The WebIDE editor flags this as an error but it may not be obvious to all that this is a typo in the tutorial content.

**Comment by ccmehil** [comment]
Thanks, deploying a correction now!
