### ISSUE TITLE
Feedback on Tutorial: Configure SAP HANA, express edition Security

### ISSUE THREAD

**Issue by ruikeiti** [SAPDocuments/Tutorials#1120]
Hi,
I have a problem using the image because I need to configure a Static IP and the user didn't have ROOT permission.
Could you help me with this issue.
Thanks and best regards,
Rui Keiti Kikumatsu

**Comment by kranz** [comment]
You can "sudo yast2" and configure IP as static. I didi it and it worked well. Anyway things got bad at the end of the step "Change the root key", and still do not know why. 
Can you please share if you are able to complete all the steps and obtain a working system?

**Comment by JCurrie27** [comment]
The "Change the root key" procedure changed significantly from SAP HANA, express edition 1.0 to SAP HANA, express edition 2.0.

Are you still experiencing security configuration issues in 2.0? The latest 2.0 tutorials for the VM package are:

- [Installing SAP HANA 2.0, express edition (Virtual Machine Method)](http://www.sap.com/developer/tutorials/hxe-ua-installing-vm-image.html)

- [Start Using SAP HANA 2.0, express edition (Virtual Machine Method)](http://www.sap.com/developer/tutorials/hxe-ua-getting-started-vm.html)

- [Configure SAP HANA 2.0, express edition Security](http://www.sap.com/developer/tutorials/hxe-ua-configure-security.html)

Hope this helps,
John C.
