### ISSUE TITLE
Feedback on Tutorial: End-to-End Weather App Scenario Part 5

### ISSUE THREAD

**Issue by imeiliasantoso** [SAPDocuments/Tutorials#1127]
I got error 404
I followed all instruction..
Could you help me?

**Comment by imeiliasantoso** [comment]
It`s 404 error...i tried so many time but it just doesnt work!

**Comment by sonaliddesai** [comment]
It seems it is not able to find the servlet. Please check your web.xml for Servlet and Servlet Mapping configuration. Also stop the server, Publish/deploy your service and then restart and check.

Let me know if it still does not work.

**Comment by jonathanbaker7** [comment]
I am closing this report, because there have been no responses for 60 days.  If there are any additional issues, please reopen the report.  Thank you!
