### ISSUE TITLE
Feedback on Tutorial: SAP HCP predictive services, Enable, deploy and configure the SAP HCP predictive services

### ISSUE THREAD

**Issue by imeiliasantoso** [SAPDocuments/Tutorials#1129]
Hi!
Do you know why at step 15, I got "HTTP Status 403 - Access to the requested resource has been denied" ?
Thank you.

**Comment by adadouche** [comment]
Hi, 

did you assign the C4PA-User and C4PA-Admin roles to your user?


Thanks

@bdel

**Comment by imeiliasantoso** [comment]
Thank you! It works now :)

**Comment by adadouche** [comment]
You are welcome!
