### ISSUE TITLE
Feedback on Tutorial: Start Using SAP HANA, express edition

### ISSUE THREAD

**Issue by mszczechows** [SAPDocuments/Tutorials#1130]
After HDB start process is failed:
FAIL: process hdbpreprocessor HDB Preprocessor not running
What can I do?

**Comment by ccmehil** [comment]
Run the command "HDB start" to start your system after logging in as hxeadm

**Comment by mszczechows** [comment]
ccmehil - the issue occurs after HDB start, I wanted to start it manually but the process is failed all the time.

**Comment by ccmehil** [comment]
Are you on a VM, binary or cloud based version? Server Only or Server+Applications? How much memory does your system have? You should check the preprocessor log file although most likely the issue a lack of memory.

**Comment by mszczechows** [comment]
VM; Server+Appication, 4GB for VM Base Memory (8GB whole system). I've also tried with 6GB of Base Memory and same Result. Any other ideas?

**Comment by ccmehil** [comment]
Well considering the Server+Application requires a minimum of 16GB your problem is kind of clear - you need more memory.

**Comment by mszczechows** [comment]
Thanks for info, just server option need less memory?

**Comment by ccmehil** [comment]
Server only requires 8GB minimum
