### ISSUE TITLE
Feedback on Tutorial: Start Using SAP HANA, express edition

### ISSUE THREAD

**Issue by mszczechows** [SAPDocuments/Tutorials#1131]
Everything worked until changin password for xsa_admin:
* -10709: Connection failed (RTE:[89006] System call 'connect' failed, rc=111:Connection refused (localhost30015)

**Comment by JCurrie27** [comment]
Hello: Have you tried this in version 2.0? The password change procedure has been redesigned in SAP HANA 2.0, express edition. If you're installing the 2.0 virtual machine package, follow the 2.0 tutorial here:

http://www.sap.com/developer/tutorials/hxe-ua-getting-started-vm.html


### Change the Default Password for SYSTEM User

Changing the default SYSTEM user password can help secure your system.

1. From the command prompt, change the SYSTEM password for `SystemDB`:  
    ```
    hdbsql -i 90 -d SystemDB -u SYSTEM -p HXEHana1
    ```

    Follow the command prompts to update the password. Exit `hdbsql`:
    ```
    \q
    ```

### Change the Default Passwords for Other Users

1. Change the `XSA_ADMIN` user password for `SystemDB`:
    ```
    hdbsql -i 90 -d SystemDB -u XSA_ADMIN -p HXEHana1
    ```

    Follow the command prompts to update the password. Exit `hdbsql`:
    ```
    \q
    ```

2. Change the `XSA_DEV` password for `SystemDB`.
    ```
    hdbsql -i 90 -d SystemDB -u XSA_DEV -p HXEHana1
    ```

    Follow the command prompts to update the password. Exit `hdbsql`:
    ```
    \q
    ```

3. Change the `XSA_SHINE` password for `SystemDB`.
    ```
    hdbsql -i 90 -d SystemDB -u XSA_SHINE -p HXEHana1
    ```

    Follow the command prompts to update the password. Exit `hdbsql`:
    ```
    \q
    ```

Hope this helps,
John Currie
