### ISSUE TITLE
Feedback on Tutorial: SAP HCP predictive services, Visualize your predictive demo data set

### ISSUE THREAD

**Issue by imeiliasantoso** [SAPDocuments/Tutorials#1132]
Hi! do you know why at the end it is not showing anything?
Thank you

**Comment by imeiliasantoso** [comment]
From the console, it is written that :  
https://webidetesting9924299-pxxxxxx0trial.dispatcher.hanatrial.ondemand.com/resources/sap-ui-core.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by adadouche** [comment]
hi,

where you able to run the application from the previous tutorial http://go.sap.com/developer/tutorials/hcpps-sapui5-configure-application.html?

I just want to check is this si a copy paste issue from the this tutorial or if there is an issue in the way the SAPUI5 was created.

Can you share your  neo-app.json file?

thanks

@bdel

**Comment by imeiliasantoso** [comment]
http://go.sap.com/developer/tutorials/hcpps-sapui5-configure-application.html
this part works.

here is my neo-app.json

{
  "welcomeFile": "/webapp/index.html",
  "routes": [
    {
      "path": "/resources",
      "target": {
        "type": "service",
        "name": "sapui5",
        "entryPath": "/resources"
      },
      "description": "SAPUI5 Resources"
    },
    {
      "path": "/test-resources",
      "target": {
        "type": "service",
        "name": "sapui5",
        "entryPath": "/test-resources"
      },
      "description": "SAPUI5 Test Resources"
   },
   {
      "path": "/HCPOData",
      "target": {
        "type": "destination",
        "name": "HCPOData"
      },
      "description": "HCPOData destination"
   },
   {
      "path": "/HCPps",
      "target": {
        "type": "destination",
        "name": "HCPps"
      },
      "description": "HCPps destination"
    }
  ],
  "sendWelcomeFileRedirect": true
}

**Comment by adadouche** [comment]
this is really weird.

Can yo send me your manifest.json as well.

I just redid the steps and it works fine on my side.

thanks

**Comment by imeiliasantoso** [comment]
It was 404 and I changed the src at index.html
Before it was src= "../../resources/sap-ui-core.js"
Now 404 is disappeared but it is still not showing.

 <script id="sap-ui-bootstrap"
			src="https://openui5.hana.ondemand.com/resources/sap-ui-core.js"
			data-sap-ui-libs="sap.m"
			data-sap-ui-theme="sap_bluecrystal"
			data-sap-ui-compatVersion="edge"
			data-sap-ui-resourceroots='{"hcpimeilia": ""}'>
		</script>


Here is my manifest.json
{
	"_version": "1.1.0",
	"sap.app": {
		"_version": "1.1.0",
		"id": "hcpimeilia",
		"type": "application",
		"i18n": "i18n/i18n.properties",
		"applicationVersion": {
			"version": "1.0.0"
		},
		"title": "{{appTitle}}",
		"description": "{{appDescription}}",
		"sourceTemplate": {
			"id": "ui5template.basicSAPUI5ApplicationProject",
			"version": "1.32.0"
		}
	},

	"sap.ui": {
		"_version": "1.1.0",
		"technology": "UI5",
		"icons": {
			"icon": "",
			"favIcon": "",
			"phone": "",
			"phone@2": "",
			"tablet": "",
			"tablet@2": ""
		},
		"deviceTypes": {
			"desktop": true,
			"tablet": true,
			"phone": true
		},
		"supportedThemes": [
			"sap_hcb",
			"sap_bluecrystal"
		]
	},

	"sap.ui5": {
		"_version": "1.1.0",
		"rootView": {
			"viewName": "hcpimeilia.view.View1",
			"type": "XML"
		},
		"dependencies": {
			"minUI5Version": "1.30.0",
			"libs": {
				"sap.ui.core": {},
				"sap.m": {},
				"sap.ui.layout": {}
			}
		},
		"contentDensities": {
			"compact": true,
			"cozy": true
		},
		"models": {
			"i18n": {
				"type": "sap.ui.model.resource.ResourceModel",
				"settings": {
					"bundleName": "hcpimeilia.i18n.i18n"
				}
			}
		},
		"resources": {
			"css": [{
				"uri": "css/style.css"
			}]
		}
	}
}

**Comment by adadouche** [comment]
Hi,

I think I know what happened. When you created your project you named your view View1 instead of demo.
And my code refers to demo not View1.

so to fix it you should update the index.html and replace 

sap.ui.getCore().attachInit(function() {
  sap.ui.getCore().setModel(new sap.ui.model.json.JSONModel());
  new sap.m.Shell({
    app: new sap.ui.view({
      height : "100%",
      viewName: "demo.view.demo",
      type: sap.ui.core.mvc.ViewType.XML
    })
  }).placeAt("content");
});

by

sap.ui.getCore().attachInit(function() {
  sap.ui.getCore().setModel(new sap.ui.model.json.JSONModel());
  new sap.m.Shell({
    app: new sap.ui.view({
      height : "100%",
      viewName: "demo.view.View1",
      type: sap.ui.core.mvc.ViewType.XML
    })
  }).placeAt("content");
});

unless you used a different namespace too.

Regards

@bdel

**Comment by adadouche** [comment]
Hi,

Have you been able to fix your issue?

Regards

@bdel

**Comment by akula86** [comment]
No response - closing
