### ISSUE TITLE
End-to-End Weather App Scenario Part 10- Data does not show up

### ISSUE THREAD

**Issue by tmfhq** [SAPDocuments/Tutorials#1144]
I followed the structure step by step but the data does not show up.
<img width="875" alt="screen shot 2016-11-06 at 7 54 42 pm" src="https://cloud.githubusercontent.com/assets/18152540/20060195/597e8c20-a4d0-11e6-83d1-56a2884ef68d.png">

**Comment by tmfhq** [comment]
This is the URL of the weather: http://api.openweathermap.org/data/2.5/weather?id=6324729,108410,5969423&APPID=3d2b7d1bc16249808dd097add354d60f

**Comment by adadouche** [comment]
Hi tmfhq,

Sorry for the late reply but I didn't receive the notification that this issue was assigned to me.

Can you share your code so I can have a look and try to replicate identify the issue?

Thanks and again sorry for the reply.

@bdel

**Comment by jonathanbaker7** [comment]
Since there has been no feedback, I'm closing the issue.
