### ISSUE TITLE
Feedback on Tutorial: Create an SAP HANA Cloud Platform destination pointing to an SAP Gateway

### ISSUE THREAD

**Issue by qmacro** [SAPDocuments/Tutorials#1153]
Nice tutorial. But in Step 3, perhaps it would be better to tell the student to use a more "appropriate" value for the `WebIDEUsage` parameter in the destination. 

`odata_gen` is for generic OData services, and you end up having to specify the path info to the full service (as described in Step 6 of [Tutorial 4](http://go.sap.com/developer/tutorials/teched-2016-4.html)).

As this is an ABAP stack Gateway-powered OData backend, `odata_abap` is more appropriate, as then the destination will appear in the Service Catalog and the `GWDEMO` service can be selected from the list that appears, rather than have to be entered (`/sap/opu/odata/IWBEP/GWDEMO`).

**Comment by akula86** [comment]
Good point. Updated the tutorial to use the odata_abap for WebIDEUsage. Commit: https://github.com/SAPDocuments/Tutorials/commit/96f33a10bdef09efafca866f9546bd50a17e413a
