### ISSUE TITLE
Feedback on Tutorial: Build an SAP Fiori UX app with SAP Gateway data

### ISSUE THREAD

**Issue by qmacro** [SAPDocuments/Tutorials#1154]
Nice tutorial. Related to #1153 - the selection of the actual `GWDEMO` OData service is slightly cumbersome owing to the less than ideal selection of `odata_gen` for `WebIDEUsage` in Step 3 of [Tutorial 3](http://go.sap.com/developer/tutorials/teched-2016-3.html).

**Comment by akula86** [comment]
Updated to use odata_abap. Commit: https://github.com/SAPDocuments/Tutorials/commit/96f33a10bdef09efafca866f9546bd50a17e413a
