### ISSUE TITLE
Feedback on Tutorial: Configure SAP HANA, express edition Security

### ISSUE THREAD

**Issue by kranz** [SAPDocuments/Tutorials#1156]
I followed all the steps indicated. Everything seems to go ok, no errors after executing commands... but at the end of the job nothing works anymore. 
As an ecample, if I use the command line ad launch "xs apps", instead of the list of apps with their current status I get this

FAILED to communicate with XS Controller:
Error executing request GET https://hxehost:30030/v2/spaces/577a0098-282f-4dc3-9bb3-9e47d8591cd0: java.net.ConnectException: errno: 111 (Connection refused), error: Connection refused (local port 52327 to address 127.0.0.1 (localhost), remote port 30030 to address 127.0.0.2 (hxehost.webdev.local))

This is the third time I restart from scratch, i.e. re-deploy the downloaded .ova template.
The only thing I do in addition to the instructions is using yast2 to reconfigure IP as static.

**Comment by siliconchris1973** [comment]
Hi Kranz, I'm not 100% sure if this will solve your problem, but:

I created a second ethane interface in vmware fusion (like player for mac) and had this one assigned a static Ip from within yast.
I added this same static IP in /etc/hosts on both my mac and within the vm and 
restarted networking.

All went smooth from there. 

Please try and feel free to get in contact with me if the error persists,

**Comment by kranz** [comment]
Thank you very much Chris for following up.
I am not sure I understand your deploy settings:

1) Do you have 1 or 2 active NICs?
2) When you say "I added this same static IP...", what do you mean by "this same"?
3) if you have two virtual NICS, SLES shoul be configured with eth0 and eth1: do you have eth0 set for DHCP and eth1 set for static IP?

There are too many important things that I do not know about this setup, and applying "monkey patch" methods to system configuration soon reaches its limit....

**Comment by siliconchris1973** [comment]
Hi.

I will try to explain my setup in more detail

I use VMWare Fusion on my Mac.
I configured the HXE VM with two virtual Ethernet interfaces. 
The first one (eth0 in Linux) is configured for automatic bridging in the vm settings and set to dhcp in yast.
The second (eth1 in Linux) is set to private network in the vm settings and set to static in yast 

This static ip is added to /etc/hosts in Linux and on my mac with the hostname of the Linux machine.

Hope that brings a bit more clarity.

If not, don't hesitate to ask,


Chris

Don't judge the code
Judge the vision
---------------------------

Christian Günther
Mobile: +49 1511 2240942
Twitter: @siliconchris
