### ISSUE TITLE
Feedback on Tutorial: Start Using SAP HANA, express edition: eth0 does not have Inet4

### ISSUE THREAD

**Issue by MartinZiehl** [SAPDocuments/Tutorials#1157]
Hello, 
I just downloaded the express edition and have imported the ova file. 
Password is changed, HDB info gives reasonable results. 
However the ipcofig does not give a IP address for my machine, only a v6 address on MAC 00:0C:29:24:54:47

Do I have to translate it manually to v4 or is there something missing in the SUSE? 

Best regards
Martin

**Comment by kranz** [comment]
By default the vm is configured for DHCP, so you have to deploy your vm in a network where there is a DHCP server.
Otherwise you can set up SUSE networking for a static IP address. You do this by using "sudo yast" at the command line

**Comment by MartinZiehl** [comment]
Thank you for the hint. I was logged on only via wifi so eht0 was not getting packages.
