### ISSUE TITLE
Feedback on Tutorial: Build an app from an SAP Web IDE template

### ISSUE THREAD

**Issue by Carlex84** [SAPDocuments/Tutorials#1159]
Message appear when I using /V3/Northwind/Northwind.svc
![image](https://cloud.githubusercontent.com/assets/19333381/20320247/f8ceea2e-ab4f-11e6-82ac-89a4170a5d55.png)
![image](https://cloud.githubusercontent.com/assets/19333381/20320316/3cc55236-ab50-11e6-9498-3cf66a6b70c6.png)

**Comment by akula86** [comment]
A ticket is open to investigate HCP/Web IDE interface with the Northwind OData service.

**Comment by Carlex84** [comment]
Thanks, today is working again
