### ISSUE TITLE
Feedback on Tutorial: Configure SAP HANA, express edition Security

### ISSUE THREAD

**Issue by sieburga** [SAPDocuments/Tutorials#1160]
Please update the tutorial:

1) The instruction in section "Change the SSFS Master Keys" for step 4. "Re-encrypt the system PKI SSFS" is incorrect. the variables DATAPATH and KEYPATH must be set to the proper directory - as stated in the PDF tutorial, but there the "export" statement is missing.
export RSEC_SSFS_DATAPATH=/usr/sap/HXE/SYS/global/security/rsecssfs/data
export RSEC_SSFS_KEYPATH=/usr/sap/HXE/SYS/global/security/rsecssfs/key

2) Please do not change the Root Keys for HANA Express VMs with DB+Apps (hxexsa).
"You should NOT generate a new root key for the DPAPI service as there is a PEM certificate in the database encrypted with the current key", 
Change the rootkey only if following views are empty in the SystemDB: "SYS"."P_DPAPI_KEY_" and "PUBLIC"."CREDENTIALS".
Explanation is here: https://answers.sap.com/questions/27365/uaa-security-is-not-up-on-hana-express.html

**Comment by JCurrie27** [comment]
Thanks for your feedback. This tutorial was updated with the release of SAP HANA, express edition 2.0:

- [Configure SAP HANA 2.0, express edition Security](http://www.sap.com/developer/tutorials/hxe-ua-configure-security.html)
