### ISSUE TITLE
Feedback on Tutorial: Download and Run the Default YaaS Storefront

### ISSUE THREAD

**Issue by ericjohnson1980** [SAPDocuments/Tutorials#1161]
Does anybody encounter the following error when executing _sudo nam install_ in the code folder after cloning?

95238 silly install printInstalled
95239 warn caas-demo-store@0.0.1 No repository field.
95240 verbose If you need help, you may report this error at:
95240 verbose     <https://github.com/npm/npm/issues>
95241 warn caas-demo-store@0.0.1 license should be a valid SPDX license expression
95242 verbose If you need help, you may report this error at:
95242 verbose     <https://github.com/npm/npm/issues>
95243 verbose stack Error: phantomjs-prebuilt@2.1.13 install: `node install.js`
95243 verbose stack Exit status 1
95243 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
95243 verbose stack     at emitTwo (events.js:106:13)
95243 verbose stack     at EventEmitter.emit (events.js:191:7)
95243 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
95243 verbose stack     at emitTwo (events.js:106:13)
95243 verbose stack     at ChildProcess.emit (events.js:191:7)
95243 verbose stack     at maybeClose (internal/child_process.js:885:16)
95243 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
95244 verbose pkgid phantomjs-prebuilt@2.1.13
95245 verbose cwd /Users/i061339/Downloads/YaaS/yaas-storefront
95246 error Darwin 15.6.0
95247 error argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "install"
95248 error node v7.1.0
95249 error npm  v3.10.9
95250 error code ELIFECYCLE
95251 error phantomjs-prebuilt@2.1.13 install: `node install.js`
95251 error Exit status 1
95252 error Failed at the phantomjs-prebuilt@2.1.13 install script 'node install.js'.
95252 error Make sure you have the latest version of node.js and npm installed.
95252 error If you do, this is most likely a problem with the phantomjs-prebuilt package,
95252 error not with npm itself.
95252 error Tell the author that this fails on your system:
95252 error     node install.js
95252 error You can get information on how to open an issue for this project with:
95252 error     npm bugs phantomjs-prebuilt
95252 error Or if that isn't available, you can get their info via:
95252 error     npm owner ls phantomjs-prebuilt
95252 error There is likely additional logging output above.
95253 verbose exit [ 1, true ]

**Comment by thecodester** [comment]
Thank you for your feedback. As this is a full year old, I am closing the issue. 

If you still have questions, feel free to reopen the issue.
