### ISSUE TITLE
Feedback on Tutorial: Start Using SAP HANA, express edition

### ISSUE THREAD

**Issue by nathan-sg** [SAPDocuments/Tutorials#1166]
Hi , 
I used VMWare player and run the hana express . I recorded my ip and put in to my hosts file. Now my VM with SUSE Linux how to run a browser ? I'm kind of stuck here. I don't think any browser is installed in the VM Image. 

May I know hw to execute this step 

1. Check that the XSEngine is running. From your VM desktop, open a browser and enter:
http://<ip address of VM>:8000

regards
Senthil Nathan

**Comment by ccmehil** [comment]
You would run the browser and edit the host file on your own machine not in the VM itself.

**Comment by ccmehil** [comment]
Did that work for you?
