### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by KOLLOMI** [SAPDocuments/Tutorials#1205]
Hi,

could you please give me an advice how I can get the cockpit-admin-web app? I downloaded the Hana Express Edition VM (server + application) but the  cockpit-admin-web app is not available. Or is there another way to set the proxy settings for XSA?

Thanks.

BR,
  Jürgen

**Comment by JCurrie27** [comment]
Hello Jurgen:  Is cockpit-admin-web-app showing 'started' as documented in [Start Using SAP HANA 2.0, express edition (Virtual Machine Method)](http://www.sap.com/developer/tutorials/hxe-ua-getting-started-vm.html)?

_8.Go back to your VM. Check that the application **`cockpit-admin-web-app`** shows **STARTED** in the list of XSA applications and has 1/1 instances.

Make a note of the URL for `cockpit-admin-web-app`._

![hxe_xsa_cockpit](https://cloud.githubusercontent.com/assets/20800154/21855179/6fbf96fc-d7eb-11e6-869c-da4d181df644.PNG)


>_**Tip**: The command **`xs apps | grep cockpit-admin-web-app`** returns the `cockpit-admin-web-app` row only._


If it is not started, did you follow the Troubleshooting procedure [SAP HANA XS Applications Run Error](http://www.sap.com/developer/how-tos/2016/09/hxe-ua-troubleshooting.html)? 

Did you try stopping and restarting the DB?

Enter:  
    ```
    HDB stop && HDB start
    ```
>**Note**: After restarting, allow sufficient time for all services to start running before proceeding.

Hope this helps,
John C.
