### ISSUE TITLE
Troubles with HDB Daemon

### ISSUE THREAD

**Issue by sigmadigital** [SAPDocuments/Tutorials#1207]
Hi!

I am experiencing some problems with the VM installation method. After importing and booting the VM, when I atempt to run `HDB stop && HDB start` my VM returns the following error:

`14.12.2016 12:54:11
StartWait
FAIL: process hdbdeamon HDB Daemon not running`

I attached a print of the error in my VM. Any help appreciated :3
![captura de tela 42](https://cloud.githubusercontent.com/assets/7178504/21182911/94a97af6-c1ec-11e6-9f10-62a909212c32.png)

Thanks in advance.
J.V

**Comment by i825908** [comment]
Could you please download the latest HXE2 patch1 and try again? If you still hit issues, please let us know. Thank you!

**Comment by sigmadigital** [comment]
Okay, I will try. Thanks for the answer! If I find any issue I report to you!
J.V.
