### ISSUE TITLE
Installing SAP HANA 2.0, express edition (Binary Installer Method)

### ISSUE THREAD

**Issue by adietri** [SAPDocuments/Tutorials#1209]
Hi,
step XSA installation fails unfortunately. Nevertheless the system is running and can be used to a certain extend (installing certificate, PAL, R), but I guess XSA stuff would fail partially.

System Data: 2 Core processor, 16 GB RAM
SLES upgraded to 12.1, several Java 8 version tried (finally Oracle jdk-8u112 x64) and still the installation of the Express 2.0 edition fails with almost the same error (product installer), which came up already with the previous 1.0 express edition.
https://answers.sap.com/questions/35745/hana-hxe-express-edition-binary-installation-error.html

Please find attached part of install log and the output of xs logs deploy-service --all.

[hdblcm.log.txt](https://github.com/SAPDocuments/Tutorials/files/656737/hdblcm.log.txt)
[hdbmodify_addlocalroles.log.txt](https://github.com/SAPDocuments/Tutorials/files/656738/hdbmodify_addlocalroles.log.txt)
[xs_log.txt](https://github.com/SAPDocuments/Tutorials/files/656739/xs_log.txt)

Thanks for help and kind regards,

Axel

**Comment by i825908** [comment]
We are still working with installer team on this issue. Thanks for your patience.

**Comment by adietri** [comment]
having a hostname with 3 dots in will solve the installation problem.
