### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by BrandtSA** [SAPDocuments/Tutorials#1223]
Good day. I was able to change the SYSTEM password for SystemDB but get error - "* 10: authentication failed SQLSTATE: 28000" when I trie to change the other users passwords. Please help.

**Comment by JCurrie27** [comment]
Hello: The password change functionality was updated in the third week of December -- the now system prompts you for a new password during the initial login, and updates the passwords for all required users. 

Are you still experiencing this issue using the latest installation package?

Hope this helps,
John C.
