### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by D030096** [SAPDocuments/Tutorials#1224]
The part "(Optionl) Install SAP Enterprise Architecture Designer ..." seems not to be correctly documented for HANA Express 2 because:
1) the file XSACHANAEAD00_0.ZIP is not conteined in the mentioned directroy but in the subdirectory "XSA_CONTENT_10"
2) command to install is "xs install XSACHANAEAD00_0.ZIP ..." (ZIP must be in capital letters)
3) the installation failed during deployment with this feedback in the command line:

Unexpected error: Error detecting MTA major schema version_ Error while parsing YAML string:
_schema-version "2.0.0"
ID: com.sap.hana.eadesigner.ext
extends: com.sap.hana.eadesigner

modules:
  - name: eadesigner-backend
  properties:
    ADMIN_PASSWORD: <i put in my pw here>

while parsing a block collection
  in 'string', line 6, column 3:
        - name: eadesigner-backend
        ^
expected <block end>, but found Key
  in 'string', line 7, column 3:
        properties:
        ^

**Comment by PSivakum** [comment]
I have the same issue. Tried so many variations (also opened) another thread for the same issue without looking into this.  Same error stuck w/o any resolutions

**Comment by xiaoyun59** [comment]
Can you attach your mtaext file?
The indentation (number of spaces) is very important in that file.

**Comment by JCurrie27** [comment]
As xiaoyun59 mentions, spacing problems in mtaext will cause the issue you reported. In the mtaext file, it's vital that you add 2 spaces in front of ‘properties’ and 4 spaces in front of ‘ADMIN_PASSWORD’. 

Here's the spacing recommendation information from the tutorial [Installing SAP HANA 2.0, express edition (Virtual Machine Method)](http://www.sap.com/developer/tutorials/hxe-ua-installing-vm-image.html)

1. Log in as `hxeadm`.

2. Create a text file, copy the following content to it, replacing the variable <tempPwd> with your choice of a temporary administrator password for the first login, and save it as `firstTime.mtaext`:

    ```
    _schema-version: "2.0.0"
    ID: com.sap.hana.eadesigner.ext
    extends: com.sap.hana.eadesigner

    modules:
      - name: eadesigner-backend
      properties:
         ADMIN_PASSWORD: <tempPwd>
    ```    

    >**Note**: Make sure that properties and ADMIN_PASSWORD are indented with spaces (not tab). **There are two spaces in front of `properties`. There are four spaces in front of `ADMIN_PASSWORD`**.

    >**Note**: If you do not specify this temporary password file in your installation command, the installation will proceed normally, but you will not be able to log into SAP EA Designer. We recommend that your temporary password should contain 8 or more characters including a mix of numbers and uppercase and lowercase letters. Once installation is complete, you should delete this file.

Hope this helps,
John C.

**Comment by JCurrie27** [comment]
EA Designer installer pathnames and filenames have been updated in [Start Using SAP HANA 2.0, express edition (Virtual Machine Method)](http://www.sap.com/developer/tutorials/hxe-ua-getting-started-vm.html).
-John C.

**Comment by PSivakum** [comment]
I did attach the file. did u see and get it?

Thanks
