### ISSUE TITLE
Getting Started HANAexpress VM - Installing Clients

### ISSUE THREAD

**Issue by grahamrobbo** [SAPDocuments/Tutorials#1232]
The documentation in the "Getting Started" file for installing XS CLI client assumes the user is running a Linux client. There is no allowance for Windows clients.

**Comment by JCurrie27** [comment]
Hello Graham: Thanks for your feedback. The client documentation was updated on 1/06/2017 to emphasize Windows versus Linux: 
http://www.sap.com/developer/how-tos/2016/12/hxe-ua-howto-installing-clients.html

Hope this helps,
John C.
