### ISSUE TITLE
Getting Started HANAexpress VM - Connect to HXE using JDBC

### ISSUE THREAD

**Issue by grahamrobbo** [SAPDocuments/Tutorials#1233]
The link to the [Connect to HXE using JDBC](http://www.sap.com/developer/how-tos/hxe-connect-hxe-using-jdbc.html) doesn't work.
![image](https://cloud.githubusercontent.com/assets/1305633/21583450/62905d62-d0d5-11e6-83d0-9806e5ceddba.png)

**Comment by grahamrobbo** [comment]
Link for [connecting using Python](http://www.sap.com/developer/how-tos/hxe-python-connection.html) doesn't work either.

**Comment by JCurrie27** [comment]
Hi Graham - Can you provide the URLs of the page (or pages) you were visiting where you noticed these broken links?

**Comment by aplata-sap** [comment]
Was this on the How to Install SAP HANA 2.0, express edition Clients page? If so, the links have been fixed.

**Comment by aplata-sap** [comment]
Commenting to close the issue, as there hasn't been any activity. If the issue was here: [http://www.sap.com/developer/how-tos/2016/12/hxe-ua-howto-installing-clients.html](http://www.sap.com/developer/how-tos/2016/12/hxe-ua-howto-installing-clients.html), the links have been fixed.
