### ISSUE TITLE
Installing SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by trondstroemme** [SAPDocuments/Tutorials#1234]
Why insisting on an outdated version of the VMware player? Version 12.1 seems to be the current one - I cannot even find 7.1 on the wmware site for downloading. In addition, all your vmware links are to the vmware.com site - not to the specific download pages for each product. This is confusing and frankly a bit "daft".

**Comment by JCurrie27** [comment]
The supported hypervisors, and the download links, have been updated.

> http://www.sap.com/developer/tutorials/hxe-ua-installing-vm-image.html

Rgds, 
John C.
