### ISSUE TITLE
Installing SAP HANA 2.0, express edition (Binary Installer Method)

### ISSUE THREAD

**Issue by biship** [SAPDocuments/Tutorials#1235]
The install of the HANA 2.0 binaries on RHEL 7.2 Developer Edition requires compat-sap-c++, which is not available in any repo unless you purchase a RHEL for SAP HANA Subscription (which doesn't come with the dev edition).  (repo rhel-sap-for-rhel-7-server-rpms is not avail for dev edition).
OSS note 2338763 might have the solution... but it's not released.
HANA 1.0 didn't require compat-sap-c++.
Any plans to work with Red Hat to fix this?

`https://access.redhat.com/solutions/2334521`

@JCurrie27 @rudi.leibbrandt

**Comment by JCurrie27** [comment]
Hello: In the Q&A section of the express edition website (http://go.sap.com/developer/topics/sap-hana-express.html), there's a post covering this issue:
https://answers.sap.com/questions/81318/will-it-be-possible-to-install-hana-20-express-on-1.html

Hope this helps,
John Currrie

**Comment by biship** [comment]
ok, well I worked it out (using a Scientific Linux rpm) and my RHEL 7.3 is running HANA 2.0 beautifully.
I guess this page needs an update for 2.0:
[http://www.sap.com/developer/how-tos/2016/09/hxe-ua-version.html](url)
Thanks John.
