### ISSUE TITLE
End-to-End Weather App Scenario Part 4

### ISSUE THREAD

**Issue by i306513** [SAPDocuments/Tutorials#1236]
Hi,
At step 5 (Maven Build), I am facing compilation error,
saying "package javax.servlet does not exist"
I have been successful Part 1 - 3.

Kindly suggest where I should check and how to correct it?

regards,
Shinichi
[compilation error log.txt](https://github.com/SAPDocuments/Tutorials/files/688860/compilation.error.log.txt)

**Comment by i825908** [comment]
This question has been passed to the author of the series. We will get back to you as soon as there is any further information. Thanks for your patience.

**Comment by Peter42** [comment]
Hi Shinichi,

I tried to reproduce your error.
Is it possible, that you missed out step 3?
> 3. Copy the entire content from the [pom.xml](https://raw.githubusercontent.com/SAP/cloud-weatherapp/ebd8817f9842a6fc3cbae213d69b024762a7d30f/pom.xml) file from GitHub and use it to replace the existing content in your project.


Best Regards,
Philipp

**Comment by jonathanbaker7** [comment]
Since I haven't heard a response, I am closing this ticket.  Please re-open it if you are still having problems.
