### ISSUE TITLE
HANA Express - SHINE install mtaext file

### ISSUE THREAD

**Issue by grahamrobbo** [SAPDocuments/Tutorials#1238]
The JDBC port numbers in the SHINE mtaext file are incorrect on the HEX machine image. 

The file is located at
`/usr/sap/HXE/home/HANA_EXPRESS_20/DATA_UNITS/HCO_HANA_SHINE/sap-xsac-shine-1.2.2-XSACSHINE02_2.mtaext`

Port numbers for both CrossSchemeSys & CrossSchemaSysBi should be `39013` rather than `30015`. IMO it will save new users much frustration installing SHINE is if the VM image has this correct so all they need to change is the username/password.

**Comment by JCurrie27** [comment]
Thanks Graham. The development team is investigating this SHINE issue. 
-John Currie

**Comment by i825908** [comment]
The port requirement will be documented. Thank you!

**Comment by JCurrie27** [comment]
The SHINE section of the [Start Using SAP HANA 2.0, express edition (Virtual Machine Method)](http://www.sap.com/developer/tutorials/hxe-ua-getting-started-vm.html) tutorial has been updated with port number 39013. (Similar change to the binary installation tutorial expected 1/12/2017.)
