### ISSUE TITLE
Not able to login as XSA_ADMIN (Running Hana Express 2.0 on AWS)

### ISSUE THREAD

**Issue by aj-code-synch** [SAPDocuments/Tutorials#1244]
Hello,
    I have been having issues while trying to login as XSA_ADMIN. I am logged in as hxeadm and trying to run following command :
`xs login -s DEV -u XSA_ADMIN -p *******` 
at API URL prompt I am giving the URL for my system which is public DNS of AWS box. Same URL:8090 gives me the webpage which says XS services are running. 

After inputting the API_URL I get following error :
`FAILED: Could not connect to controller on http://XXXXXX.compute-1.amazonaws.com:30030/
        errno: 111 (Connection refused), error: Connection refused (local port 48952 to address YYYYY (XXXXX.compute-1.amazonaws.com), remote port 30030 to address YYYY (XXXXX.compute-1.amazonaws.com))
`

XXXXX -> static IP of AWS box
YYYYY -> internal IP on AWS

I have checked the rules and port 30030 is open same as all the ports(eg 8090) .

**Comment by carlsoane** [comment]
Is your server installed as instance 00 or instance 90? The default for HANA, express edition is 90. If that is the case, can you try using port 39030 instead of 30030?

**Comment by aj-code-synch** [comment]
I am using HANA Express 2.0 and default instance is 90. I will give 39030 a try in a bit. But when I put API_URL without any port after xs login command its being defaulted to 30030 by HANA it self, that makes me think it should be 30030 only. I will still give it a try and let you know how it goes :) Thanks !

**Comment by aj-code-synch** [comment]
when I tried by specifying 39030 port at API_URL prompt it gave me a SSL connection error. 

```
`Could not connect to controller on http://XXXXXX.compute-1.amazonaws.com:39030
Trying https...

FAILED: SSL connection error (supposedly untrusted connection, check the certificates)'
```

I have opened up the ports as per [blog](https://blogs.sap.com/2016/11/20/installing-hana-express-on-aws-detailed-walkthrough/comment-page-1/#comment-359270). I  opened up all the ports just for sake of it and it did not help either. I may have to go via SAP CAL route which is significantly costlier than my EC2 instance that I am using. Or may be give Hana Express 1.0 another try.

**Comment by carlsoane** [comment]
I am doing some more research on this internally. I think one of our testers may have encountered a similar error and worked around it by renaming the HANA system to use the public ip address of your AWS virtual machine. I believe they used the hdblcm rename_system command and entered the ip address as the new system name. Unfortunately, I need to confer with that engineer. I will try to do so tomorrow and get back to you.

**Comment by aj-code-synch** [comment]
I made some progress on this. Actually, I went back to Hana Express 1.0 and the installed everything following the manual. Most of it went ok. But accessing services is still fickle. Sometimes access is still denied for XSA_ADMIN login but eventually, I get in. The WebIde is still out of reach!  I think that has more to do with user provisioning than access to actual URLs. Is there a security manual which I can follow for user roles/creation? I can get in with SYSTEM user via eclipse and do some user provisioning. I must say it has been a learning experience (on linux/cloud set up if not on SAP HANA front :) )

**Comment by carlsoane** [comment]
Regarding webide, can you try logging in to the webide using XSA_DEV. And when you do so, do it in a new incognito window in Chrome to be sure that you don't pick up any cached settings. XSA_DEV has permissions for webide that XSA_ADMIN does not have.

**Comment by aj-code-synch** [comment]
I did a binary installation and it did not create the XSA_DEV user. I created another user by copying SYSTEM user and added developer roles (7 of them I believe). There were no webide specific roles. I found a blog by Thomas Jung where he talks about new patches on SP12 which deals with this issue. I will give it a try next.

**Comment by carlsoane** [comment]
Did you run the hxe_optimize script during the binary install. That creates the xsa_dev user.

**Comment by aj-code-synch** [comment]
I haven't run that script yet. I will try that again once I get back to work.

**Comment by aj-code-synch** [comment]
Finally some success !! I ran the script and was able to get into webide via xsa_dev. I do have one question about the webide though. I may be getting these mixed up. When I do to hxehost:53075 it takes me to a xs login page. When I login using xsa_dev I get an empty workspace folder.  On the link hxehost:8000/sap/hana/ide/editor/ I get more options like creating package/content folders etc. 

Whats the difference between these two pages and whats the purpose or 53075 port link ? 

hxehost:53075 
![image](https://cloud.githubusercontent.com/assets/11687892/22070763/bed7d6a6-dd62-11e6-9a70-f34c40101fbe.png)

hxehost:8000/sap/hana/ide/editor
![image](https://cloud.githubusercontent.com/assets/11687892/22070797/e42aa6cc-dd62-11e6-8d4a-87225933053c.png)

**Comment by carlsoane** [comment]
Hello aj-code-synch:

the 8000 editor shows you the ide for XS classic. The 53075 editor shows you the editor for xs advanced. Here's an article explaining the differences and why we have both: http://sapinsider.wispubs.com/Assets/Articles/2016/April/SPI-A-New-Development-Platform-for-Native-SAP-HANA-Applications

Regards,

Carl

**Comment by aj-code-synch** [comment]
Thanks ! That explains a lot !

**Comment by talalemam** [comment]
Hi
i have HANA express edition virtual machine , when I'm trying to set the API with port 39030 , receiving ssl error. please check snapshot , please i need support 
![xs](https://cloud.githubusercontent.com/assets/26650372/24292649/4b6e57f6-109f-11e7-90d8-6a20fc10c8d2.PNG)

**Comment by talalemam** [comment]
aj-code-synch

which script you ran ?

**Comment by Lsubatin** [comment]
@talalemam , for your error, have you tried adding--skip-ssl-validation ? It's not the ideal scenario but may work

**Comment by Lsubatin** [comment]
Closing issue based on lack of response. please post technical questions in the community Q&A
