### ISSUE TITLE
End-to-End Weather App Scenario Part 8

### ISSUE THREAD

**Issue by i306513** [SAPDocuments/Tutorials#1246]
Hi, at step6, the given URL throws the following error.
"HTTP Status 500 - Servlet.init() for servlet CXFServlet threw exception"

I have followed the exactly same steps as described,
I am not sure where to check and how I can fix the issue. Please help.

regards,
Shinichi
[Error report.zip](https://github.com/SAPDocuments/Tutorials/files/703577/Error.report.zip)

**Comment by jonathanbaker7** [comment]
Does this change only happen at Step 8?  Until that point, the web application is working correctly?

**Comment by jonathanbaker7** [comment]
Since I haven't heard a response, I am closing this ticket.  Please re-open it if you are still having problems.
