### ISSUE TITLE
SAP HANA XS Advanced, Connecting to the WebIDE to begin development

### ISSUE THREAD

**Issue by rleibbrandt** [SAPDocuments/Tutorials#1247]
Hi Craig 

Could we change this paragraph so HXE users do not get confused about the reference to the server landing page for now?

I'm busy building a doc with an assessment of what we need to improve for HXE, and think actually having a server landing page is something we should think of - your thoughts?

R

**Comment by Lsubatin** [comment]
Hi, Rudi! I'm stepping in here as I'm updating those tutorials. I'm a little lost on what paragraph you mean and I agree a server landing page like the CAL instances have would really help.
