### ISSUE TITLE
Configure SAP HANA 2.0, express edition Security

### ISSUE THREAD

**Issue by plazzer** [SAPDocuments/Tutorials#1248]
Hi experts,
I've finally managed to get this going, I'm using it to run this [PAL example](https://github.com/saphanaacademy/PAL/blob/master/Code%20Snippets/PAL%20122%20Classification%20-%20Gradient%20Boosting%20Model.sql) but I'm getting an insufficient privilege error. Is there a way that I can get around this, or grant myself full admin privileges?

**Comment by YiqingLingSAP** [comment]
Hi,

Can you provide more details. Which statement gives error, and which user is running the SQL?

**Comment by plazzer** [comment]
Ok, I was using a system user role from this [example](http://www.sap.com/developer/how-tos/2016/09/hxe-howto-eclipse.html). I believe system roles don't have access to the PAL functionality, I will close this issue.
