### ISSUE TITLE
SAP HANA XS Advanced, Creating an HTML5 Module

### ISSUE THREAD

**Issue by wizbongre** [SAPDocuments/Tutorials#1268]
From the "SAP HANA XS Advanced, Creating an HTML5 Module" page if you try to click on the prerequisite link to "SAP HANA XS Advanced Connect to Web IDE and clone Git Repository" (url is http://www.sap.com/developer/tutorials/xsa-clone-repository-git.html) then you get a page not found error.

**Comment by Lsubatin** [comment]
Thanks for letting us know! This has been solved. Cheers!
