### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by jurgenm** [SAPDocuments/Tutorials#1272]
I installed HXE on a Mac (16GB) using Virtualbox. Everything works fine, but I'm not able to change the resolution from 640x480 to anything higher. All other options are greyed out. Running a command like "HDB info" is then pointless since a part of the displayed information is not visible. 

I tried to install the Virtualbox Guest Additions, but can't get it done. While your tutorial was very helpful and detailed to get everything else nicely going, in terms of Virtualbox there is a big gap.

I'm sure I'm not the only one using a Mac using Virtualbox (since this is free compared to VMware on Mac), some guidance for OpenSuse on Virtualbox will be probably much appreciated.

**Comment by tai-le** [comment]
You can login to the VM through xterm, Putty, or other utils.  You can resize xterm, Putty, etc window to the size you want.

You can find the VM IP address in the VM login console (wait and press enter if you don't see it).
