### ISSUE TITLE
React JS - Examine child to parent communication

### ISSUE THREAD

**Issue by htammen** [SAPDocuments/Tutorials#1273]
Thank you for this great blog. It gave me a very quick introduction to React.

Between steps 7 and 8 you missed the description of the dialog box enhancement including referencing react-bootstrap.js

**Comment by jonathanbaker7** [comment]
Can you provide some additional details?  

This tutorial does not use react-boostrap.js.  It uses the bootstrap methods directly, and so it doesn't need the rewritten library.

Were you looking for more information on react-bootstrap?  Or was this about something else?

**Comment by jonathanbaker7** [comment]
I see the problem now.  The old code automatically pulled in the react-bootstrap code, but now it's not there anymore.  This caused the tutorial to break.  

I added in the CDN repository for react-bootstrap (although it's a couple of minor releases back, it is the version that matches.)  This should fix the problem.  Thanks! #
