### ISSUE TITLE
Installing SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by sedacrivity** [SAPDocuments/Tutorials#1274]
Trying to Install this was not a 'great experience' ... to say the least - some comments:
 
(1) It would be great if you could add in some info on how to set the keyboard to "non-qwerty" ... not the whole world is using a qwerty keyboard ....  

(2) What a 'pain' to get the password changed into something 'usefull' ... after attempting for the 5th time to enter a password which was 'acceptable' ... using QWERTY settings on my AZERTY keyboard ... I was about to throw the whole thing through the window ...

(3) Tried to change the keyboard settings using 'sudo yast2 keyboard' ... waited for ever to have yast2 do 'something' and exit ... and in the end didn't work apparently ... still QWERTY

(4) Tried to reboot the system ... after a long waiting time ... I end up in 'Grub GNU' and a command prompt and nothing more to do ... dead system ... over and out ...

Now that was 'fun' ...

**Comment by carlsoane** [comment]
Hello sedacrivity:

I am sorry you've had a bad experience. Are you encountering the problems with the keyboard layout from a remote ssh client or on the VM's terminal? I followed the same steps as you with sudo yast2 and was able to change from a US English keyboard to a German keyboard on the VM. I have seen problems using different ssh clients, however. And those have their own configuration requirements for keyboards that would overwrite the host keyboard settings.

Regarding the passwords: thank you for the feedback. We chose to use standard Unix password creation rules to err on the side of security.

Regards,

Carl

**Comment by sedacrivity** [comment]
Hi Carl,

Sorry for the late response ... thanks for coming back with more details ... 
I was using the VM terminal ... 

Kr,

Steven

**Comment by JCurrie27** [comment]
There have been some updates to the tutorial "Start Using SAP HANA 2.0, express edition (Virtual Machine Method)" addressing these items.

https://www.sap.com/developer/tutorials/hxe-ua-getting-started-vm.html

- Step 2: Startup: Change Default Password now contains more information on password requirements

- Step  6: (Optional) Change Keyboard Layout is a new step containing info on changing from the default US QWERTY layout.
