### ISSUE TITLE
SAP HANA XS Advanced, Connecting to the WebIDE and cloning a Git Repository to begin development

### ISSUE THREAD

**Issue by alundesap** [SAPDocuments/Tutorials#1310]
Between Steps 3 and 4 you need to go through the create an MTA project and then export and then commit it to GIT and then connect it to your remote GIT and then push the stub project into the remote GIT and then delete the exiting local project, before you can GIT -> Clone Repository and have anything meaningful.

**Comment by Lsubatin** [comment]
Hi, Andrew, you can stage all changes and commit them into Git. You will see the mta file after you clone the repository. Then you can stage the mta descriptor and project.json files that were created automatically, commit and push.  I'll add this step in the next pull request. Thanks a lot for reviewing and commenting!

**Comment by alundesap** [comment]
Yep.  Main main point was that the directions don't mention having to use the new MTA project wizard first.

My team (Startup.Focus) is evaluating the use of HXE for our needs and so I'm interested in the supporting materials that the developer community is providing and how well they align.

That's why I'm being a bit nit-picky.  ;)
