### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Binary Installer Method)

### ISSUE THREAD

**Issue by phillip-lam** [SAPDocuments/Tutorials#1316]
The format for  line
    properties:
 in firstTime.mtaext is wrong.    The correct one is:

![capture](https://cloud.githubusercontent.com/assets/25232891/22566734/2095028e-e95b-11e6-8dd9-786e801a1e8d.PNG)

**Comment by JCurrie27** [comment]
The spacing recommendations for firstTime.mtaext have been updated in the VM and binary tutorials. Closing github issue.
