### ISSUE TITLE
Inserting OData query options into your SAPUI5 app

### ISSUE THREAD

**Issue by PankiS** [SAPDocuments/Tutorials#1317]
point 8:

// inserted function to filter master list
this._oView.attachAfterRendering(function() {

    // create the filter for UnitsInStock
    var sPath1 = "UnitsInStock";
    var sOperator1 = "GT";
    var sValue1 = "0";
    var oFilter1 = new sap.ui.model.Filter(sPath1, sOperator1, sValue1);

    // get the list items binding
    var oBinding = this.byId("list").getBinding("items");

    //Apply filter(s)
    oBinding.filter(oFilter1);
});

not work. After Run project, not open lauchpad.

**Comment by adadouche** [comment]
Hi PankiS,

Can yo share the code of your Master.view.xml file?
Also you can use the Developer Tools from your browser to debug the code by pressing F12.

Let us know

Thanks

@bdel

**Comment by PankiS** [comment]
Hi Abel,

thank You for Your e-mail.

OnInit code:

onInit: function() {
// keeps the filter and search state
this._oListFilterState = {
aFilter: [
new sap.ui.model.Filter("STATUS", sap.ui.model.FilterOperator.EQ, "ANGL"),
new sap.ui.model.Filter("STATUS", sap.ui.model.FilterOperator.EQ, "BEAR"),
new sap.ui.model.Filter("STATUS", sap.ui.model.FilterOperator.EQ, "CLAR"),
new sap.ui.model.Filter("STATUS", sap.ui.model.FilterOperator.EQ, "REJE")
],
aSearch: []
};
// Control state model
var oList = this.byId("list");
var oViewModel = new JSONModel({
isFilterBarVisible: false,
filterBarLabel: "",
delay: 0,
// filters: this._oListFilterState.aFilter,
// filters : [new sap.ui.model.Filter("Bpartner", sap.ui.model.FilterOperator.EQ, "5000076093")],
title: this.getResourceBundle().getText("masterTitleCount", [0]),
noDataText: this.getResourceBundle().getText("masterListNoDataWithFilterOrSearchText"), //masterListNoDataText"),
sortBy: "BESCHREIBUNG",
groupBy: "None"
}),
// Put down master list's original value for busy indicator delay,
// so it can be restored later on. Busy handling on the master list is
// taken care of by the master list itself.
iOriginalBusyDelay = oList.getBusyIndicatorDelay();
this._oList = oList;
// var oBinding = oList.getBinding("items");
// oBinding.filter([], "Application");
this.setModel(oViewModel, "masterView");
// Make sure, busy indication is showing immediately so there is no
// break after the busy indication for loading the view's meta data is
// ended (see promise 'oWhenMetadataIsLoaded' in AppController)
oList.attachEventOnce("updateFinished", function() {
// Restore original busy indicator delay for the list
oViewModel.setProperty("/delay", iOriginalBusyDelay);
});
this.getView().addEventDelegate({
onBeforeFirstShow: function() {
this.getOwnerComponent().oListSelector.setBoundMasterList(oList);
}.bind(this)
});
this.getRouter().getRoute("master").attachPatternMatched(this._onMasterMatched, this);
this.getRouter().attachBypassed(this.onBypassed, this);
// inserted function to filter master list
this._oView.attachAfterRendering(function() {
// get the list items binding
var oBinding = this.byId("list").getBinding("items");
// Apply filter(s)
oBinding.filter(this._oListFilterState);
});
},

In Developer Tools I had error: "Unable to get property 'attachAfterRendering' of undefined or null reference" BR Sergey

>Понедельник,  6 февраля 2017, 11:30 +03:00 от Abdel Dadouche <notifications@github.com>:
>
>Hi PankiS,
>Can yo share the code of your Master.view.xml file?
>Also you can use the Developer Tools from your browser to debug the code by pressing F12.
>Let us know
>Thanks
>@bdel
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С уважением, Сергей Панкин (pankis@mail.ru)

**Comment by adadouche** [comment]
Hi,

Think you forgot to apply step 7:
To sort by the product name and exclude products that are out of stock, insert the lines below to create a variable with a reference to the view.

// get the view for filtering
this._oView = this.getView();

You can add this code at the end of the onIint function.

Regards

@bdel

**Comment by adadouche** [comment]
the image link is broken for step 7 which can explain the confusion also.

I will fix the image as well.

@bdel

**Comment by PankiS** [comment]
Dear Abel,

Thank You. I was deleted it row, after previous test. Now, I restored it.
But Filter not work. Open full list anymore.

Very interesting detail: If I wrote not exist field in filter, FIORI receive error from Odata. 

BR Sergey

>Вторник,  7 февраля 2017, 16:22 +03:00 от Abdel Dadouche <notifications@github.com>:
>
>Hi,
>Think you forgot to apply step 7:
>To sort by the product name and exclude products that are out of stock, insert the lines below to create a variable with a reference to the view.
>// get the view for filtering
>this._oView = this.getView();
>You can add this code at the end of the onIint function.
>Regards
>@bdel
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С уважением, Сергей Панкин (pankis@mail.ru)

**Comment by PankiS** [comment]
Dear Abel,

I had view this image :-)

BR Sergey

>Вторник,  7 февраля 2017, 16:26 +03:00 от Abdel Dadouche <notifications@github.com>:
>
>the image link is broken for step 7 which can explain the confusion also.
>I will fix the image as well.
>@bdel
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С уважением, Сергей Панкин (pankis@mail.ru)

**Comment by adadouche** [comment]
can you provide the new error message?

Thanks

**Comment by PankiS** [comment]
Dear Abdel,

very strange errors:

2017-02-07 16:48:40 Wrong parameters defined for filter. -  
2017-02-07 16:48:43 Service returned messages for entities that were not requested. This might lead to wrong message processing and loss of messages -  
2017-02-07 16:48:43 The following problem occurred: HTTP request failed404,Not Found,{"error":{"code":"/IWBEP/CM_MGW_RT/020","message":{"lang":"de","value":"Ressource für Segment \"WorkList\" nicht gefunden."},"innererror":{"transactionid":"5899019CAFC70980E100804C9EE21535","timestamp":"","Error_Resolution":{"SAP_Transaction":"","SAP_Note":"See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)"},"errordetails":[{"code":"/IWBEP/CX_MGW_BUSI_EXCEPTION","message":"Ressource für Segment \"WorkList\" nicht gefunden","propertyref":"","severity":"error","target":""}]}}} -  

BR Sergey

>Вторник,  7 февраля 2017, 16:33 +03:00 от Abdel Dadouche <notifications@github.com>:
>
>can you provide the new error message?
>Thanks
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С уважением, Сергей Панкин (pankis@mail.ru)

**Comment by adadouche** [comment]
I think you have a typo in your code as well.
In the code you sent, you are missing a semicolon on your JSONModel initialization (it was a comma).

	var oViewModel = new JSONModel({
		isFilterBarVisible: false,
		filterBarLabel: "",
		delay: 0,
		// filters: this._oListFilterState.aFilter,
		// filters : [new sap.ui.model.Filter("Bpartner",
		// sap.ui.model.FilterOperator.EQ, "5000076093")],
		title: this.getResourceBundle().getText("masterTitleCount", [0]),
		noDataText: this.getResourceBundle().getText("masterListNoDataWithFilterOrSearchText"), // masterListNoDataText"),
		sortBy: "BESCHREIBUNG",
		groupBy: "None"
	});
// Put down master list's original value for busy indicator delay,

@bdel

**Comment by PankiS** [comment]
Dear Abdel,

made:

// Control state model
var oList = this.byId("list");
var oViewModel = new JSONModel({
isFilterBarVisible: false,
filterBarLabel: "",
delay: 0,
title: this.getResourceBundle().getText("masterTitleCount", [0]),
noDataText: this.getResourceBundle().getText("masterListNoDataText"),
sortBy: "BESCHREIBUNG",
groupBy: "None"
});
// Put down master list's original value for busy indicator delay,
// so it can be restored later on. Busy handling on the master list is
// taken care of by the master list itself.
var iOriginalBusyDelay = oList.getBusyIndicatorDelay();

But. It's not help. Same errors.

BR Sergey Вторник,  7 февраля 2017, 17:08 +03:00 от Abdel Dadouche <notifications@github.com>:
>
>I think you have a typo in your code as well.
>In the code you sent, you are missing a semicolon on your JSONModel initialization (it was a comma).
>var oViewModel = new JSONModel({
	isFilterBarVisible: false,
	filterBarLabel: "",
	delay: 0,
	// filters: this._oListFilterState.aFilter,
	// filters : [new sap.ui.model.Filter("Bpartner",
	// sap.ui.model.FilterOperator.EQ, "5000076093")],
	title: this.getResourceBundle().getText("masterTitleCount", [0]),
	noDataText: this.getResourceBundle().getText("masterListNoDataWithFilterOrSearchText"), // masterListNoDataText"),
	sortBy: "BESCHREIBUNG",
	groupBy: "None"
});
>// Put down master list's original value for busy indicator delay,
>@bdel
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С уважением, Сергей Панкин (pankis@mail.ru)
