### ISSUE TITLE
How to create an SAP HANA Developer Edition in the Cloud

### ISSUE THREAD

**Issue by ReshmaCS** [SAPDocuments/Tutorials#1341]
Hi, We have got an instance for SAP HANA Develop Edition in the cloud (Running on AWS).

I tried to launch the HANA instance using http://XXX.XXX.XXX.XXX as mentioned in the Getting Started Guide. But we don't get anything. Our intention is to launch SAP Web IDE for HANA to develop XSA applications. 

My question is:
Does the SAP HANA Developer Edition 1, SPS12 come with the services required for WebIDE and XSA? I tried to list out all the xs apps/ services as mentioned in the openSAP Course for SAP HANA/ SPS12, but I get only the below listed. I don't see any of the services like hrtt, webide etc.

when we do a xs apps (we have two space - PROD and SAP. PROD is empty. SAP has the below)
deploy-service
component-registry-db
component-registry
product-installer

and for xs services, we get the below:
hdi-container
hdi-schema
uaa
deploy-service-ss
deploy-service-database
alm-uaa
product-installer-database

Could you please let us know why we aren't able to see Web IDE and hrtt tools?

Regards
Reshma

**Comment by ReshmaCS** [comment]
For the above issue, do we need to get SAP HANA Express instead of SAP HANA Developer edition? 

This would be the first HANA instance in our landscape and we would like to get started on the latest technologies. By reading online and taking the openSAP course, I understand XS Advanced is the way forward. 

Please advise.

**Comment by ccmehil** [comment]
The existing SPS12 Developer Edition would be fine for XSA as well or you can switch to the newer HXE (Express Edition) as well.

For SPS12 Developer Edition try putting the :8000 on the end of the URL perhaps the internal port redirection for traffic on port 80 to 8000 is not working. The port for the Web IDE is 53075
