### ISSUE TITLE
SAP HCP predictive services, Test the "Data Set" HCP predictive services using a REST client

### ISSUE THREAD

**Issue by pavanmulpur** [SAPDocuments/Tutorials#1343]
Hi,

I've completed this tutorial but I didn't understand what I learnt here. What did I learn in this tutorial is the big question I have. This tutorial only teaches in a mechanical way what steps have to be done to test the data set. But no where does it say after each step, "now this is what you have learnt." By doing this step you will be able to do the following or by doing this step this is what you will accomplish"
Such messages have to be mentioned. The objective of this tutorial is not set clearly. 
Request the authors to clearly lay down the goals of each tutorial as to what I'll be learning after the completion of each tutorial. And after completion of each tutorial it should state "This is what you have learned in this tutorial". 

Thank you.

Regards,

Pavan.

**Comment by adadouche** [comment]
Hi Pava,

Thanks for your feedback.

The tutorial format is not something we can change, and we only have a section at the beginning to explain the intent of the tutorial.

I'm currently refreshing this series with new data sets and some additional content.

I will keep this remark in mind.
@bdel
