### ISSUE TITLE
Unable to see "Clone Repository" - SAP HCP predictive services, Configure a SAPUI5 application from the project template

### ISSUE THREAD

**Issue by pavanmulpur** [SAPDocuments/Tutorials#1344]
Hi Abdel Dadouche,

I am working on the tutorial SAP HCP predictive services, Configure a SAPUI5 application from the project template  from the link http://www.sap.com/developer/tutorials/hcpps-sapui5-configure-application.html.
At step 6  of this tutorial "Click on the Edit Application button HTML5 Applications timeseriesdemo next to the hcppredictiveservicesdemo" when I click on the "Edit Application" icon I do not see the Clone repository prompting me to enter my HCP credentials.
![2 unable to view clone repository](https://cloud.githubusercontent.com/assets/25876045/23116407/63db046c-f770-11e6-8c91-b05dd806823b.PNG)

The below image shows the screen that I see when I click on the edit icon in HTML5 Applications.
![unable to view clone repository](https://cloud.githubusercontent.com/assets/25876045/23116372/3a841266-f770-11e6-8f8e-60566d7f6149.PNG)

I am stuck here. Can you  please explain me what to do to move ahead further in this tutorial.

Thank you.
Regards,

Pavan.

**Comment by adadouche** [comment]
Hi,
Sorry for the lag. 

I have update the tutorial series and I removed the Git part as it was always confusing for people starting developing with the Web IDE. I will most likely develop a new series/how to's around Git and the Web IDE later on.

Now, I just start the Web IDE and start the dev directly.

Thanks
