### ISSUE TITLE
Unable to create a new binding in DataSource bindings

### ISSUE THREAD

**Issue by pavanmulpur** [SAPDocuments/Tutorials#1349]
[Unable to create a new binding.docx](https://github.com/SAPDocuments/Tutorials/files/795266/Unable.to.create.a.new.binding.docx)

Hi All,

I am working on this tutorial "SAP HCP predictive services, Enable, deploy and configure the SAP HCP predictive services" and am stuck at one place in step 9(http://www.sap.com/developer/tutorials/hcpps-ps-configure.html).
When I go to create a new database binding I am getting an error message saying Enter an existing database user name for the user HCPPSTRIAL. When I try with the user HCCPSTRIAL I am getting the message "Credentials are not valid". Please refer to page 2 of the attached word document for screen shots.
For both the users I am using Welcome16 as the password. 
Can you please let me know what is the correct user name and password to be used. 

Thank you.

Regards,

Pavan.

**Comment by adadouche** [comment]
Hi,

In [Setup a HANA user account](https://www.sap.com/developer/tutorials/hcpps-hana-create-user.html), the user to be created is PSTRIAL and the password is Welcome17Welcome17.

In the past I used HCPPSTRIAL, but as HANA Cloud Platform was re branded and the password policy for SAP HANA got stronger I had to update this part.

I have updated the screenshot and found a reference to HCPPSTRIAL in hcpps-ps-configure that I updated by PSTRIAL.

Regards 

@bdel
