### ISSUE TITLE
Good tutorial - Few Suggestions to improve - Time Series Forecasting with SAP HANA APL (Automated Predictive Library)

### ISSUE THREAD

**Issue by pavanmulpur** [SAPDocuments/Tutorials#1350]
Hi team,

Thank you for this tutorial. I was able to do all the steps in this tutorial without any issues. But I would like to give few suggestions to make these tutorials better assuming that many of the users are new to Predictive Analytics, Time Series and such other terms.
1. It would be great if you can add few lines explaining about the data that we are going to work with in the tutorial. What are these fields, what is the purpose of this data, what are we going to predict, How is the time series forecasting helpful in forecasting and what are we going to forecast with the data in this tutorial. 
Answering these questions will really help the learners develop a much more interest in these tutorials. 
2. It would be good to add few lines as to how the wrapper procedure works and what its purpose is.

3. In step 8 the results have been given, but it would be great if you could explain and interpret these results with the original data that was used to arrive at these results.  
Its mentioned that "The result table will contain 3 columns: the date, the signal with the training data if any and the predictive (kts_1)." 
But in the output that I got and in the screen shot that you have shown the 3 columsn that I see are Date Cash and kts_1. I do not see Signal and kts_1. I do not see any Signal column. Is the cash column the Signal column? What does it signify? What is the column kts_1? What do I interpret from this column? 
It would be really great if you can answer all these questions in your updated version of this tutorial.

Thank you.

Regards,

Pavan.

**Comment by adadouche** [comment]
Hi pavanmulpur,

I'm currently refreshing this tutorial series and adding new ones for the other APL functions available.

Regarding the wrapper procedure, this is a temporary fix as one of the HANA delivery unit is currently not available on trial anymore, which forced me to use the "root"/"hard coded" way of calling an AFL function.

I will check the description again and adapt if needed.

thanks for your feedback.

@bdel

**Comment by adadouche** [comment]
tutorial refreshed
