### ISSUE TITLE
Internet of Things (IoT) Connecting your TI SensorTag to IoT Services

### ISSUE THREAD

**Issue by MarioDBianchi** [SAPDocuments/Tutorials#1352]
Hi I had issues to publish data to the IOT cloud using the Sensortag example, it resulted the timestamp format of the example is using a number, while the cloud backend is expecting a date format.

Using the original Sensortag example I am getting all code 400 return code, if I change the "time" variable to a format similar to "2016-11-15T08:45:37.930Z" it starts working OK and returning 200 OK code.

I am running the example from a Raspberry 3

OUTPUT FROM THE ORIGINAL EXAMPLE

*********************************************
 To stop press both buttons on the SensorTag
*********************************************
Device Name = SensorTag 2.0
System ID = 24:71:89:00:00:be:af:05
Serial Number = N.A.
Firmware Rev = 1.30 (May 23 2016)
Hardware Rev = PCB 1.2/1.3
Software Revision = PCB 1.2/1.3
Manufacturer = Texas Instruments
Sending Data: 24:71:89:00:00:be:af:05 undefined undefined
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":1488073429632}]}
Sending Data to server
Sending Data: 24:71:89:00:00:be:af:05 undefined undefined
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":1488073429813}]}
Sending Data to server
REQUEST END: 400
REQUEST END: 400
Sending Data: 24:71:89:00:00:be:af:05 -40.0 0.0
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":1488073439796,"temperature":"-40.0","humidity":"0.0"}]}
Sending Data to server
Sending Data: 24:71:89:00:00:be:af:05 29.9 51.7
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":1488073439880,"temperature":"29.9","humidity":"51.7"}]}
Sending Data to server
REQUEST END: 400
REQUEST END: 400
Sending Data: 24:71:89:00:00:be:af:05 29.9 51.7
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":1488073449806,"temperature":"29.9","humidity":"51.7"}]}
Sending Data to server
Sending Data: 24:71:89:00:00:be:af:05 30.0 52.1
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":1488073449887,"temperature":"30.0","humidity":"52.1"}]}
Sending Data to server
REQUEST END: 400
REQUEST END: 400

OUTPUT WITH THE CORRECTED TIMESTAMP FORMAT:
First 2 request still fail due the wrong message format (missing values), but from there on it works OK
Notice the difference in the timestamp value and compare with the example above.

*********************************************
 To stop press both buttons on the SensorTag
*********************************************
Device Name = SensorTag 2.0
System ID = 24:71:89:00:00:be:af:05
Serial Number = N.A.
Firmware Rev = 1.30 (May 23 2016)
Hardware Rev = PCB 1.2/1.3
Software Revision = PCB 1.2/1.3
Manufacturer = Texas Instruments
Sending Data: 24:71:89:00:00:be:af:05 undefined undefined
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":"2016-11-15T08:45:37.930Z"}]}
Sending Data to server
Sending Data: 24:71:89:00:00:be:af:05 undefined undefined
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":"2016-11-15T08:45:37.930Z"}]}
Sending Data to server
REQUEST END: 400
REQUEST END: 400
Sending Data: 24:71:89:00:00:be:af:05 -40.0 0.0
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":"2016-11-15T08:45:37.930Z","Temperature":"-40.0","Humidity":"0.0"}]}
Sending Data to server
Sending Data: 24:71:89:00:00:be:af:05 -40.0 0.0
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":"2016-11-15T08:45:37.930Z","Temperature":"-40.0","Humidity":"0.0"}]}
Sending Data to server
REQUEST END: 200
REQUEST END: 200
Sending Data: 24:71:89:00:00:be:af:05 30.1 49.7
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":"2016-11-15T08:45:37.930Z","Temperature":"30.1","Humidity":"49.7"}]}
Sending Data to server
Sending Data: 24:71:89:00:00:be:af:05 30.1 49.7
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":"2016-11-15T08:45:37.930Z","Temperature":"30.1","Humidity":"49.7"}]}
Sending Data to server
REQUEST END: 200
REQUEST END: 200
Sending Data: 24:71:89:00:00:be:af:05 30.1 49.6
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":"2016-11-15T08:45:37.930Z","Temperature":"30.1","Humidity":"49.6"}]}
Sending Data to server
Sending Data: 24:71:89:00:00:be:af:05 30.1 49.6
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":"2016-11-15T08:45:37.930Z","Temperature":"30.1","Humidity":"49.6"}]}
Sending Data to server
REQUEST END: 200
REQUEST END: 200
Sending Data: 24:71:89:00:00:be:af:05 30.1 49.4
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":"2016-11-15T08:45:37.930Z","Temperature":"30.1","Humidity":"49.4"}]}
Sending Data to server
Sending Data: 24:71:89:00:00:be:af:05 30.1 49.4
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":"2016-11-15T08:45:37.930Z","Temperature":"30.1","Humidity":"49.4"}]}
Sending Data to server
REQUEST END: 200
REQUEST END: 200
Sending Data: 24:71:89:00:00:be:af:05 30.1 49.3
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":"2016-11-15T08:45:37.930Z","Temperature":"30.1","Humidity":"49.3"}]}
Sending Data to server
Sending Data: 24:71:89:00:00:be:af:05 30.1 49.3
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":"2016-11-15T08:45:37.930Z","Temperature":"30.1","Humidity":"49.3"}]}
Sending Data to server
REQUEST END: 200
REQUEST END: 200
Sending Data: 24:71:89:00:00:be:af:05 30.1 49.2
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":"2016-11-15T08:45:37.930Z","Temperature":"30.1","Humidity":"49.2"}]}
Sending Data to server
Sending Data: 24:71:89:00:00:be:af:05 30.1 49.2
Data: {"mode":"sync","messageType":"9c6d51b59ee68e067a7a","messages":[{"timestamp":"2016-11-15T08:45:37.930Z","Temperature":"30.1","Humidity":"49.2"}]}
Sending Data to server
^Cpi@raspberrypi:~ $ sudo nano readTags.js
pi@raspberrypi:~ $ node readTags.js
If not yet activated, then press the power button.
Connect Device and Execute Sensors
Enabling sensors:
        enableIRTemperatureSensor
        enableHumidity

**Comment by ccmehil** [comment]
That might be a difference in regional settings and system type. I was using Node JS on a MacBook Air with German regional settings.
