### ISSUE TITLE
Internet of Things (IoT) Setup SAP HANA XS (On-premise or stand-alone server)

### ISSUE THREAD

**Issue by fiberhead** [SAPDocuments/Tutorials#1367]
Hallo,
I have a problem with my package struture in the Workbench Editor. 
First is Content --> gbi-student-005 --> Raspberry --> mydata.hdbdd with:
namespace gbi-student-005.Raspberry;
But that don't work. It says that - is an unexpected token.
Hope you can help.

**Comment by ccmehil** [comment]
The '-' may be the problem.
