### ISSUE TITLE
SAP Cloud Platform predictive services, Import a predictive demo dataset in your SAP HANA

### ISSUE THREAD

**Issue by MadhaviMallepally** [SAPDocuments/Tutorials#1375]
Hi

Thanks for nice tutorial.
Please check the links for data sets (Cashflow,Census are not accessible)
Unable to proceed with that data as its giving not found error.

Thanks,
Madhavi

**Comment by adadouche** [comment]
Hi,

Thanks for the feedback. I just fixed the links.

Thanks

@bdel
