### ISSUE TITLE
SAPUI5 - Add a list to the view - CSS fix still required?

### ISSUE THREAD

**Issue by nilsobermiller2** [SAPDocuments/Tutorials#1377]
Is the fix in /webapp/css/style.css (mentioned at http://www.sap.com/developer/tutorials/sapui5-webide-add-list.html > 2.) still required? If I add the code snippet to style.css my app is missing the title bar and I can't scroll the list. If I just leave style.css empty the app seems to work fine. I'm using SAP Web IDE innovation version, maybe the behavior is different than with "standard" SAP Web IDE. 
BR Nils

**Comment by jonathanbaker7** [comment]
That's an interesting problem.  The entire sample runs correctly on the standard WebIDE version (I tested it about 30 seconds ago).

It's possible that the innovation version is using a new release of SAP UI5.  If so, the CSS problem may have been fixed, or just changed.  The CSS for UI5 is not guaranteed to remain constant, and so this fix was only temporary for our tutorial.  

Just to verify, however, I took the CSS out of the sample.  It works without it.  So I'll remove it from our build copy and push out the change as soon as possible.

Thanks, good catch!

If you find any other problems, feel free to reopen this case.
