### ISSUE TITLE
SAPUI5 - Setup the DataSource in the local application - Minor Typo

### ISSUE THREAD

**Issue by nilsobermiller2** [SAPDocuments/Tutorials#1378]
Two minor typos at http://www.sap.com/developer/tutorials/sapui5-webide-setup-datasource.html > Details > Define the Data source:
_applicaitons_ should be changed to _applications_
and
_applicaiton_ to _application_

**Comment by jonathanbaker7** [comment]
Good catch!  I had to look at that for a second.  I'll fix that and add it to the production stream.
