### ISSUE TITLE
SAP HANA XS Classic, Develop your first SAP HANA XSC Application

### ISSUE THREAD

**Issue by arilehtola** [SAPDocuments/Tutorials#1381]
hello, 

c/p from tutorial page:

"**Couple of more steps before we hit the editor
You’ll need to click on the “Admin Cockpit” first to trigger the authorizations you will need going forward**."

Those links dont work for my account but says 404-error. Neither of them. I have my database up & running

TypeDatabaseDatabase System
HANA MDC (<trial>)
Version1.00.122.04.1478575636Bindings0 availableParametersXS EngineEMBEDDEDWeb AccessENABLEDScript ServerDISABLEDDP ServerDISABLED

Any idea what I have missed?

thanks

ari

**Comment by ccmehil** [comment]
Did you click the admin and then also give your user all the permissions?

**Comment by arilehtola** [comment]
hi,

Maybe you refer to locally installed  SAP Hana Express environment? My question was for cloud based WEB IDE at https://account.hanatrial.ondemand.com/cockpit#/acc[...............] I was playing with. There I'm not able to access those links

![404](https://cloud.githubusercontent.com/assets/26133045/23646978/2640f032-031c-11e7-83a1-d49aeca8509d.JPG)
![capture](https://cloud.githubusercontent.com/assets/26133045/23646977/263f534e-031c-11e7-8dd5-d94443cff3e9.JPG)

I dont know how I could administrate my cloud account permissions?

However, I managed to set up local HANA express 1.2 environment Hypervisor-version where web ide works and I can go forward with tutorials. Anyhow it would be nice to get cloud enviromnment working as well.

Thanks, Ari

**Comment by ccmehil** [comment]
For the "Cloud" environment you need to first click the "SAP HANA Cockpit" that will assign permissions then go to the security area and assign your user the appropriate rights listed in the tutorials.

**Comment by arilehtola** [comment]
hi,

yep, "click the "SAP HANA Cockpit" is the problem as it does not respond. My connection works normally othhervise,,,but I keep on trying every now and then, maybe some "maintenance" is going on...

regards, ari
