### ISSUE TITLE
SAP Cloud Platform predictive services, Expose your predictive demo dataset as HANA XS OData services

### ISSUE THREAD

**Issue by JohnHeutmekers** [SAPDocuments/Tutorials#1383]
Small text inconsistency:

![image](https://cloud.githubusercontent.com/assets/11091864/23511917/259157b4-ff5f-11e6-8b5d-00bdc0a7ded8.png)

**Comment by adadouche** [comment]
Hi,

Thanks for raising this mistake. This will be updated in the next commit.

Feel free to continue posting your feedback as this help us improve our content.

@bdel

**Comment by adadouche** [comment]
Hi,
The change is live now. 
Thanks
