### ISSUE TITLE
SAP Cloud Platform predictive services, Test the "Forecast" SAP Cloud Platform predictive service from a REST client

### ISSUE THREAD

**Issue by JohnHeutmekers** [SAPDocuments/Tutorials#1384]
Typo:

![image](https://cloud.githubusercontent.com/assets/11091864/23515581/d89ea13a-ff6a-11e6-8efc-c4b4cd277d43.png)

**Comment by adadouche** [comment]
Hi,

Thanks for raising this mistake. This will be updated in the next commit.

Feel free to continue posting your feedback as this help us improve our content.

@bdel

**Comment by adadouche** [comment]
Hi,
The change is live now. 
Thanks
