### ISSUE TITLE
Testing API Business Hub APIs with Curl

### ISSUE THREAD

**Issue by vsilverman** [SAPDocuments/Tutorials#1400]
https://www.sap.com/developer/tutorials/hcp-abh-test-locally.html

After going to above URL and testing those API locally you should get the following result:
![image](https://cloud.githubusercontent.com/assets/2159948/23582163/1a0ec478-00d9-11e7-8930-fabc4194af6c.png)

**Comment by mhassett92** [comment]
We are working on adding validation to all the tutorials. Even if you are not seeing the done checks, you can still work on the tutorial. This tutorial does not yet have auto-validation so the done's are not recording progress, and therefore it is OK that you are not seeing them.
