### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by s0000241042** [SAPDocuments/Tutorials#1401]
hello 
can anyone help me in implementing? best with Team viewer. Am blocked with link to hana studio.
and the xsa_admin password and authorization.

 [hana express.docx](https://github.com/SAPDocuments/Tutorials/files/820596/hana.express.docx)
many thanks
Nick Scherer

**Comment by ccmehil** [comment]
In your screenshot you did not give the name of the Tenant, if you select "SYSTEM database" it will connect.
