### ISSUE TITLE
SAP HANA XS Advanced, Creating an HTML5 Module

### ISSUE THREAD

**Issue by lnryan** [SAPDocuments/Tutorials#1405]
I followed this guide on Hana Express 2.0 and the login policy killed my API_URL. I haven't been able to get it set back to what it was even after restarting. 

FAILED: Could not connect to controller on http://hxehost:30030
errno: 111 (Connection refused)

Then when trying to restore original HXE 2.0 settings for `https://hxehost:39030` error is "FAILED: SSL connection error (supposedly untrusted connection, check the certifications)

**Comment by tonyZhou2014** [comment]
I have pinged XSA colleagues and they might reply you.

**Comment by carlsoane** [comment]
Hello Inryan:

Can you try the following please (replacing the password with yours):
`xs login -u xsa_admin -p YOUR_PASSWORD_HERE -a https://hxehost:39030 --cacert /hana/shared/HXE/xs/controller_data/controller/ssl-pub/router/default.root.crt.pem`

You can also try connecting using the xs client without ssl validation if this is a system without any sensitive data. To do that, use the following command:

`xs login -u xsa_admin -p YOUR_PASSWORD_HERE -a  https://hxehost:39030 --skip-ssl-validation`

Regards,

Carl
