### ISSUE TITLE
Installing SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by danyloveselyi** [SAPDocuments/Tutorials#1406]
Windows + VirtualBox - can not import downloaded ova file, Linux + VirtualBox - can import downloaded ova file

**Comment by tonyZhou2014** [comment]
That should not happen. You might try again on Windows VirtualBox. If problem still exists, please provide the exact version you have downloaded.

**Comment by danyloveselyi** [comment]
![virtualbox_issue](https://cloud.githubusercontent.com/assets/3958969/23789198/093929fe-057a-11e7-8beb-ebbeba01b527.png)

screenshot was attached

**Comment by danyloveselyi** [comment]
Installed last VirtualBox version - 5.1.16 r113841 (Qt5.6.2) and it works!  
tonyZhou2014 thanks!
