### ISSUE TITLE
SAP HANA XS Advanced, Connecting to the WebIDE and cloning a Git Repository to begin development

### ISSUE THREAD

**Issue by jglander** [SAPDocuments/Tutorials#1409]
Hi,

I installed the HANA express edition according to your description (e.g. I executed this as my last page https://www.sap.com/developer/how-tos/2016/09/hxe-howto-tutorialprep.html ).

But now in "Step 5: Configure the Space for the repository" I don't see the DEV space which I should select as project setting. 
I can only see SAP as space and I'm confused what to do now. What might be the reason why I don't see the DEV space? Or should I just continue with SAP space instead of DEV?

Thank you for your help.
Regards, Jens

**Comment by i831123** [comment]
Hi Jens,

The Default for XSA Space is SAP. Please continue the configuration with this option. DEV space mentioned in our tutorials in an additional space incase the user would like to create and use. 

Best Wishes,
Vidya Mandapudy
