### ISSUE TITLE
SAP HANA, express edition, in Google Cloud Platform Launcher

### ISSUE THREAD

**Issue by JesseVent** [SAPDocuments/Tutorials#1410]
Hi,
I've followed these instructions but i am unable to use any xs commands in the shell.. The next steps tutorial uses xs and hdbsql, but I can only run hdbsql commands.

Also unable to connect to HANA Studio/eclipse with any details i've setup on Google Cloud Platform using the launcher

Thanks

**Comment by i831123** [comment]
Hi Jesse,

What are the instructions you are following to install Hana Express Edition on Google cloud. Could you please provide the link? If your installation has HANA serveronly, then there wont be any XS applications to accesses. For connecting to HANA Studio, you might have to check and open the ports. 

Best Wishes,
Vidya Mandapudy

**Comment by JesseVent** [comment]
Hi Vidya, 
Following these tutorials:
https://cloud.google.com/sap/
https://blogs.sap.com/2017/03/09/getting-started-with-sap-hana-express-on-the-google-cloud-platform-by-the-sap-hana-academy/
Then the next steps tutorial 
https://www.sap.com/developer/how-tos/2016/09/hxe-howto-tutorialprep.html

I can successfully get the XS running page when accessing with the port 8090 but when using command line and trying xs login it returns a message saying  it doesn't recognise any xs commands. Which means can't actually access web development workbench or anything.

Thanks
-Jesse

**Comment by i831123** [comment]
Hi Jesse,
As sap hana academy link specify (second one), we are only supporting HANA database server image on google cloud now.  It does not have a full image with XS advanced capabilities. The full image is planned for future releases. 
Many Thanks,
Vidya Mandapudy
