### ISSUE TITLE
End-to-End Weather App Scenario Part1

### ISSUE THREAD

**Issue by rvrkj** [SAPDocuments/Tutorials#1416]
I have been trying to do this project but got stuck here every time I tried (https://www.dropbox.com/s/vmxx0v1woobnjum/Screenshot%202017-03-15%2019.25.54.png?dl=0). I have followed all the required steps as mentioned over there 
(https://www.sap.com/developer/tutorials/hcp-java-weatherapp-part1.html ) 
Please look into the error I have got.
Thanks!

**Comment by jonathanbaker7** [comment]
Posted bug in contribution:  https://github.com/SAPDocuments/Tutorials-Contribution/issues/1756.  Will report back when that bug is resolved.

**Comment by jonathanbaker7** [comment]
The WeatherApp code is about to be End of Lifed, so I'm closing all bugs around it.  Please let me know if you have a similar error in the latest Java tutorials around SAP Cloud Platform.
