### ISSUE TITLE
SAP HANA XS Classic, Access your first data in a SAP HANA XSC Application

### ISSUE THREAD

**Issue by teejay-tarun** [SAPDocuments/Tutorials#1421]
mydata_import.hdbti has a  typo. filename should be sample_book_list.csv.

import	= 	[ 
    			{ 
					cdstable  =	"codejam.data::mydata.Book";
					file = "codejam.data:sample_book_list.csv"; 	     
					header = false;		
    			} 
     		];

**Comment by ccmehil** [comment]
Thank you, fixed.
