### ISSUE TITLE
HANA Express Edition - SocketTimeoutException -  8 vCPS Cores and 50 GB Memory

### ISSUE THREAD

**Issue by mtgran** [SAPDocuments/Tutorials#1423]
Hi Lucia,

thanks for the detailed [installation guide](https://www.sap.com/developer/tutorials/hxe-gcp-install-hana-express-edition.html). I run into an TimeoutException issue during the installation: 

- **ERR    java.net.SocketTimeoutException: Read timed out (local port 48270 to address 127.0.0.1 (localhost), remote port 51005 to address 127.0.0.1 (localhost))**

```
Grant permisssions to XSA_SHINE...
Login to XSA services...
Start job-scheduler broker service...
Install XSAC_SHINE SHINE...

Running installation in org "HANAExpress" / space "SAP" as XSA_ADMIN...
Upload into container starts...

Installation failed.
ERR    java.net.SocketTimeoutException: Read timed out (local port 48270 to address 127.0.0.1 (localhost), remote port 51005 to address 127.0.0.1 (localhost))

```

All the installation steps were followed. The installation was made with 8 vCPS Cores and 50 GB Memory in Google Cloud Platform

Here the installation [protocol](https://gist.github.com/mtgran/70ae83b88cae05aad01f853372d350c3).

Any idea what to do?

Thanks in advance,
M.

**Comment by i825908** [comment]
From the look of the installation log, SHINE installation failed.  You can manually rerun HANA_EXPRESS_20/install_shine.sh”. 
There is newer release of HXE, maybe give the latest version a try?
Thank you!
