### ISSUE TITLE
Working with Tables and Views using Apache Zeppelin

### ISSUE THREAD

**Issue by NicoZeilfelder** [SAPDocuments/Tutorials#1426]
Hey guys,

if I run the following statement it accures an error message.

1   %vora
2   show tables

error: spark.vora interpreter not found

I would appreciate it, iy you could help me. 

Best Regards,
Nico

**Comment by adadouche** [comment]
Hi @NicoZeilfelder ,

I will check with my colleague, but I think the "%vora" keyword has now been replaced by %jdbc.
I had that issue, and just replaced the %vora by %jdbc and it worked.

REgards

@bdel

**Comment by adadouche** [comment]
Hi,

Just found out that as there are multiple "installation" type, you might not be running one with the "SAP HANA Vora Zeppelin Interpreter" on yours.

Can you check section 2.7 of https://help.sap.com/http.svc/rc/f09ec811fe634f588647c342cac84c38/1.3/en-US/SAP_HANA_Vora_Installation_Admin_Guide_1.3_en.pdf?

Thanks

@bdel

**Comment by NicoZeilfelder** [comment]
Hi Abdel,

 

thanks but it doesn't work either.

 

Error message:

class java.sql.SQLException
org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:231)
org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:176)
org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
java.sql.DriverManager.getConnection(DriverManager.java:664)
java.sql.DriverManager.getConnection(DriverManager.java:208)
org.apache.zeppelin.jdbc.JDBCInterpreter.getConnection(JDBCInterpreter.java:222)
org.apache.zeppelin.jdbc.JDBCInterpreter.getStatement(JDBCInterpreter.java:233)
org.apache.zeppelin.jdbc.JDBCInterpreter.executeSql(JDBCInterpreter.java:292)
org.apache.zeppelin.jdbc.JDBCInterpreter.interpret(JDBCInterpreter.java:396)
org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:94)
org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:341)
org.apache.zeppelin.scheduler.Job.run(Job.java:176)
org.apache.zeppelin.scheduler.ParallelScheduler$JobRunner.run(ParallelScheduler.java:162)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:812)

 

Regards,

Nico


 

Gesendet: Donnerstag, 23. März 2017 um 18:07 Uhr
Von: "Abdel Dadouche" <notifications@github.com>
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: NicoZeilfelder <n.zeilfelder@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Working with Tables and Views using Apache Zeppelin (#1426)


Hi @NicoZeilfelder ,

I will check with my colleague, but I think the "%vora" keyword has now been replaced by %jdbc.
I had that issue, and just replaced the %vora by %jdbc and it worked.

REgards

@bdel

**Comment by adadouche** [comment]
Ok, I guess that the setup on the CAL and VM version are not the same. :-(

Can you try with %spark.vora instead of %jdbc?

I don't have a CAL vm image right now so it may take me some time to get back to you if the suggestion doesn't work.

Thanks

@bdel

**Comment by NicoZeilfelder** [comment]
Doesn't work neither.

 

I beleive the bug is in my architecture. I only followed the steps of the tutorial on how to set up vora and zeppelin.

 

I'Il talk to some colleagues.

 

BR,

Nico

**Comment by adadouche** [comment]
HI,

Have you managed to get it running? 

By the way, you also have a SQL Editor in the Vora Tools to run SQL.

@bdel

**Comment by NicoZeilfelder** [comment]
Yes a colleague of mine fixed it. I shut the engines down with 'Power Off' and was not able to start them again. So we disabled the OVA-file and integrated it again. Now every statement work, but you have to use %jdbc instead of %vora in front of every SQL statement.

best regards,
nico

**Comment by adadouche** [comment]
Thanks for your feedback, have fun with Vora and let us know if you faced any news issues with our tutorials!

**Comment by mokhast1** [comment]
HI


i can not make connection to sap 
 

    On Monday, April 3, 2017 9:57 AM, Abdel Dadouche <notifications@github.com> wrote:
 

 Thanks for your feedback, have fun with Vora and let us know if you faced any news issues with our tutorials!—
