### ISSUE TITLE
Setup your trial SAP HANA MDC instance

### ISSUE THREAD

**Issue by mehdimj** [SAPDocuments/Tutorials#1428]
Hey @adadouche, I need some feedback/input about the following please: 

**When clicking on new (DB/Schema) I can see a different form than the one displayed on the tutorial.**

![image](https://cloud.githubusercontent.com/assets/5819192/24212626/548fc012-0f06-11e7-8132-c85f69435901.png)

**Once the DB is created I have the following options:**

![image](https://cloud.githubusercontent.com/assets/5819192/24212676/8038f0c6-0f06-11e7-96a5-2b79baafef83.png)

The latter is also different on what we have in the tutorial.

Thanks

**Comment by adadouche** [comment]
Hi @mehdimj,

I think you missed to select "Database System" as "HANA MDC (< trial >)" instead of "HANA (<shared>).

You will have to delete the current one and create a new one.

I also recommend you to stick to the name provided ("mdc"), as I used this in the following tutorials.

Regards

@bdel

**Comment by adadouche** [comment]
Hi @mehdimj,

Did you manage to fix your issue based on my previous comment?

Let me know if I can close this issue.

Regards

@bdel

**Comment by mehdimj** [comment]
Hello @adadouche 

Thanks for the feedback, I can't see the option HANA MDC <trial>. All the options I have are 3 times the: HANA (<shared>).

Thanks :)

**Comment by mehdimj** [comment]
@adadouche 

I noticed that it isn't available on the non-trial account. I went to the trial account and found it there.
My bad !

Merci

**Comment by adadouche** [comment]
No worries.

On the non trial account, you will need to purchase a DBaaS subscription I think to get access to a HANA MDC instance.

The"shared" is there by default because some of the services requires that to store their application metadata.

In the predictive service scenario, it requires to consume your data thus the need of a DBaaS.

Thanks sending us your feedback.

@bdel
