### ISSUE TITLE
SAP HANA XS Advanced, Creating a Node.js Module

### ISSUE THREAD

**Issue by MKT123** [SAPDocuments/Tutorials#1473]
Hi... I am looking to start with "hello world" Node Js program in SAP HANA web IDE.
But I dont see the option N**ew -->  Node.js**.
![27669-untitled](https://cloud.githubusercontent.com/assets/25396361/24481333/94d238a6-14b7-11e7-993b-03366277e598.png)

From the project context menu, choose  **New -->  Node.js** Module , and follow the wizard steps to enter the module properties.

I have attached the screenshot of what i see in my SAP web IDE. Appreciate if experts can assist in this. Thanks

**Comment by Lsubatin** [comment]
Hi! Is that an MTA project?
