### ISSUE TITLE
Installing the SAP Cloud Platform for iOS SDK

### ISSUE THREAD

**Issue by andreasschlosser** [SAPDocuments/Tutorials#1481]
The screenshot is not reflecting the latest SDK GA packaging.

People should simply drag&drop the whole thing into their Applications folder, using the shortcut that we placed in the DMG

If they want they can then also go into /Tools/ProxyGenerator and drag&drop the tool (+resource folder) into /usr/local/bin, using the shortcut we placed in the DMG

Thanks
Andreas

**Comment by akula86** [comment]
Commit: https://github.com/SAPDocuments/Tutorials/pull/1638/commits/87c3acb5f0f20d0f095a6878eb6ca5657038598f
