### ISSUE TITLE
SAP HANA, express edition, in Google Cloud Platform Launcher

### ISSUE THREAD

**Issue by iolalog** [SAPDocuments/Tutorials#1483]
Hi guys

Thanks for providing a tutorial! I also watched the video tutorial at this location that was very useful: https://blogs.sap.com/2017/03/09/getting-started-with-sap-hana-express-on-the-google-cloud-platform-by-the-sap-hana-academy/

The problem however is that XSA isn't installed in the pre-configured Hana VM in Google Cloud as far as I can tell. The tutorials seems to indicate it is, and when I go to the <IP address>:8090 it says that the "XSEngine is up and running!", but the XS CLI commands doesn't work. The comments at this page seems to confirm XSA isn't installed in the Hana VM in Google Cloud: https://blogs.sap.com/2017/03/13/how-to-consume-sap-hana-express-edition-on-google-cloud-platorm/

If so, that is a pitty, as it's very quick and smooth to set it up. A few questions:
1. Is there a tutorial for installing XSA later?
2. Will the Google VM be amended with XSA soon?
3. If not, will a new VM with XSA be added to Google?

Thanks for any assistance you can provide!

Olav

**Comment by Lsubatin** [comment]
1. There is no tutorial, you can try sending the hxexsa.tgz into the VM, and do the following to install XSA in your HANA Express on Google Cloud Platform:

As root:

cd <<installer directory>>
tar -xvzf hxexsa.tgz
chmod -R 777 ./HANA_EXPRESS_20/
/hana/shared/HXE/hdblcm/hdblcm --component_medium=<<extract directory>>/HANA_EXPRESS_20/

This will launch the the lcm, choose the "update components" option and then "xs".

You will need to add more RAM, CPU and disk space before you proceed with installation.

2. No
2. Yes

**Comment by aj-code-synch** [comment]
I tried the manual installation of XSA on google cloud but it fails. Before this point everything was INFO message. 

`16:22:42.065 - ERR : Update of SAP HANA Express Edition components failed.

16:22:42.123 - INFO: Summary of critical errors

16:22:42.065 - ERR :   Update of SAP HANA Express Edition components failed.

16:22:38.791 - ERR :     Installation of XS Advanced components failed

16:21:45.325 - ERR :       Installation of XS Services 1 failed

16:22:11.009 - ERR :       Installation of SAPUI5 FESV2 XSA 1 - SAPUI5 SDK 1.38 failed

16:22:38.790 - ERR :       Installation of SAP HANA Cockpit failed
`

Another thing to notice is that the df command shows my current directory is full. I chose 120GB to begin with but google partitions the disk as per following output. 
`
hxeadm@hxe-project-hxe2-vm:/usr/sap/HXE/HDB90> df

Filesystem     1K-blocks     Used Available Use% Mounted on

devtmpfs        13371380        0  13371380   0% /dev

tmpfs           13377044        0  13377044   0% /dev/shm

tmpfs           13377044     9908  13367136   1% /run

tmpfs           13377044        0  13377044   0% /sys/fs/cgroup

/dev/sda1       37020300 35003692    113056 100% /

tmpfs            2675412        0   2675412   0% /run/user/490

tmpfs            2675412        0   2675412   0% /run/user/1004

tmpfs            2675412        0   2675412   0% /run/user/1005
`

**Comment by Lsubatin** [comment]
Adding disk space to the VM does not mean that the operating system sees the new space and extends the partitions (that happens in some other operating systems but not in SUSE). df -h is probably showing that in a more clear way.   Also, this  is for issues related to tutorial contents and not technical issues, please go the community  ( https://answers.sap.com/index.html ) for technical support.

**Comment by bizintelligence** [comment]
Hi,

You should not be promoting upgrade or installation of XS Advanced or other applications if GCP instance is not the right option. In other words, the instance should not be available on GCP if it's template doesn't have all the applications. Most of the tutorials & SAP HANA academy videos (2.0 SP2) talk about the features that is only available in XS Advanced or other applications. This seems to be purely sales focused strategy. I have given up on cloud options for now. Frustrated !!!

Sincerely
Angad

**Comment by Lsubatin** [comment]
Hi, Angad, 

If you are looking for XS Advanced you could install it on cloud providers manually and following the instructions on the binary installation guide or tutorial. Enhancing the existing GCP instance requires some additional steps and deeper understanding of the requirements, and that is not promoted or documented anywhere because we cannot assume everyone has this deeper understanding (e.g., what it takes to actually enhance the disk space as in the case above).  The upgrades are for existing installations and the addition of XS Advanced to a server-only option is only linked to the Virtual Machine installation, but you will need  at least 16GB RAM on the host of the VM. Where do you see the promotion of this scenario?

As an alternative to the binary installer guides, there's a documented piece to install XS Advanced on a cloud provider starting from here: https://www.sap.com/developer/tutorials/hxe-azure-open-suse.html

Best,
Lucia.
