### ISSUE TITLE
CONNECTION SET UP

### ISSUE THREAD

**Issue by mokhast1** [SAPDocuments/Tutorials#1484]
HI CNA YOU PLEASE HELP ME WITH CONNECTION SET UP

**Comment by adadouche** [comment]
HI CAN YOU PLEASE SHARE A DESCRIPTION OF YOUR PROBLEM?

Just kidding, can you be more specific on your issue?

Which tutorial you are refering too and which step?

Thanks

@bdel

**Comment by adadouche** [comment]
no answer received so far, closing the issue.
