### ISSUE TITLE
Developing and deploying a basic Java application on SAP Cloud Platform

### ISSUE THREAD

**Issue by Sunny-dlxg** [SAPDocuments/Tutorials#1485]
Dear akula86,
thank you very much for providing the step-by-step tutorial above and other ones. I am having difficulty to save the tutorial in a pdf-file because of the interactive step-x which cannot be expanded all at once prior to saving. Thank you for a reply.
Kind Regards,
Sunny

**Comment by akula86** [comment]
Sunny,

Thank you for your note. We will be adding additional interactive features to the tutorials in the next few months, so we were not planning on exporting them in PDF. If you do need to have the procedure available offline, you can export a PDF of .md file from the GitHub repo. The rendering won't be perfect, (you will lose step titles and see custom markdown symbols) but you will get the procedures and images. If you open the link below (as an example) you can export or print the file as a PDF:
<https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/hcp-java-weatherapp-part1/hcp-java-weatherapp-part1.md>

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
