### ISSUE TITLE
TouchID integration with SAP IdP

### ISSUE THREAD

**Issue by amit1agrawal** [SAPDocuments/Tutorials#1486]
Hi Robin,
Can you please share details of integrating TouchID with SAP IdP service using SAML 2.0 or oAuth protocol or Basic Authentication.

Regards,
Amit

**Comment by akula86** [comment]
@qualiture - please review

**Comment by qualiture** [comment]
Hi Amit,

I have planned to write a tutorial covering the `FUIPasscodeCreateController`, `FUIPasscodeInputController` and `FUIPasscodeChangeController` which help enable Touch ID for application authentication. 

I'll update once done

**Comment by qualiture** [comment]
Hi @amit1agrawal,

The TouchID part is now integrated in the generated onboarding flow in the SDK Assistant generated application.

The TouchID part is separate from integrating SAP IdP with SAP Cloud Platform (you link IdP with SCP, and in your app definition you simply state which authentication mechanism you want to use, SAML or OAuth). 

Using TouchID or Passcode can be configured in your app definition's Client Policy feature (it is enabled by default)

If this answers your question, you may close this issue

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by amit1agrawal** [comment]
Thanks, @qualiture for an update.
I will check the new APIs and use them to perform TouchID based authentication.
However, I am little busy now so it might take some time. 
Meanwhile, the issue can be closed (which is already done).
