### ISSUE TITLE
SCP SDK for iOS : HTTP 503: Service Unavailable

### ISSUE THREAD

**Issue by edacostacegb** [SAPDocuments/Tutorials#1488]
Hello

I have followed the steps of the tutorial for Creating an App using Assistant until step 6.
When I try to select the demo application in the "Use Existing" tab, I have a 503 error.

![2017-04-04 7 59 12](https://cloud.githubusercontent.com/assets/22927641/24635139/a259a096-190c-11e7-9bdb-abefab328f6b.png)

I have checked the mobile service in my trial account. I have access to the service and to the admin cockpit.

![2017-04-04 8 03 51](https://cloud.githubusercontent.com/assets/22927641/24635253/49e4b364-190d-11e7-9711-68fccef7b49a.png)

But when I enter the link for the service directly in a web browser, i have a service unavailable error too.
![2017-04-04 8 01 30](https://cloud.githubusercontent.com/assets/22927641/24635218/11535a50-190d-11e7-93d8-f118696046a6.png)

Could you help ?

Regards

Emmanuel Da Costa

**Comment by edacostacegb** [comment]
Hello

I have followed the following tutorials but I am blocked.

https://www.sap.com/developer/groups/ios-sdk-setup.html
https://www.sap.com/developer/tutorials/fiori-ios-hcpms-sdk-assistant.html

Cloud you help ?

Regards

Emmanuel Da Costa

**Comment by qualiture** [comment]
Hi @edacostacegb,

Apologies for not replying earlier (this issue log is actually meant for issues with the tutorials itself, and not the tools or products it covers. SAP Community would be the better place to ask these kind of questions, and make sure to tag your question with `SAP Cloud Platform SDK for iOS` 👍 )

Anyway, while we're here, it seems the service link is incorrect: it should be in the form `https://hcpms-s0016713422trial.hanatrial.ondemand.com` (note it starts with `hcpms-` and not `hcpmsadmin-`)

Hope this helps!
