### ISSUE TITLE
Enhancing the persistence layer for multi-tenency

### ISSUE THREAD

**Issue by hockinm** [SAPDocuments/Tutorials#1491]
Excellent tutorial series until this point where it becomes non-specific, ambiguous, lacking detail to the same level as other steps and difficult to follow. Why no code samples where they have been provided to this point....????

**Comment by Lsubatin** [comment]
Hi, Hockinm, what tutorial and specific point are you referring to? Thanks

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
