### ISSUE TITLE
SAP UI5 - Create an empty UI5 Web IDE project

### ISSUE THREAD

**Issue by PeterDaRibeira** [SAPDocuments/Tutorials#1494]
Poor 

Test of OData service fails with version 3 not supported.

**Comment by smilingsun** [comment]
Same here.

Also, why ``SAPUI Master Detail Kapsel Application`` deprecated?

**Comment by thecodester** [comment]
Issue closed since a year has elapsed since it was opened. If the issue is still relevant, please reopen the issue or open a new one.
