### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by murmelsson** [SAPDocuments/Tutorials#1496]
Hello,

2 suggestions for improvement:

1. Probably at the beginning of step 2, you could advise people how to change their keyboard layout (since not everyone has the provided default English(US) keyboard, and so e.g. the character '-' may not be input correctly, and so on. The spell is:
`sudo yast2 keyboard`
Then use arrow keys and tab keys to setup the keyboard appropriately.

2. In my VM (running on VMWare Player on Windows 10), there is no scrollbar or window resize possibilities, so it may be difficult to confirm that on running 
`HDB info` we can see that all the needed services are running. A workaround is this:
`HDB info > hdbinfo.txt`
`vi hdbinfo.txt`  (then use e.g. `:q` to exit from vi, since many people will not know that and could be stuck inside vi :) ).

Hope these are useful suggestions. Have a nice day and best regards,
-dylan drummond

**Comment by Lsubatin** [comment]
Thank youvery much for the input, Dylan!
