### ISSUE TITLE
Installing SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by EmilZyet** [SAPDocuments/Tutorials#1572]
Hi,
    I was following your instruction to install HANA 2.0 Express version. Everything was working fine, only when I tried to access webide/xsa, every time I ran into an authorization request error  as shown following:
![auth_re](https://cloud.githubusercontent.com/assets/24440609/24758949/21559c0a-1ae4-11e7-92a4-299a0b84bb26.PNG)
Do you know this issue already?  Could you please help me to figure out how to fix it? Thanks!

**Comment by Lsubatin** [comment]
Hi, is that with XSA_DEV user? Have you checked if the user has the proper role collections?

**Comment by Lsubatin** [comment]
Closing due to lack of response
