### ISSUE TITLE
Tutorial fiori-ios-hcpms-offline-odata-implementation: Wrong instance/method for offline store closing

### ISSUE THREAD

**Issue by pfefferf** [SAPDocuments/Tutorials#1574]
In tutorial https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/fiori-ios-hcpms-offline-odata-implementation/fiori-ios-hcpms-offline-odata-implementation.md (https://www.sap.com/developer/tutorials/fiori-ios-hcpms-offline-odata-implementation.html) in step 9 it is mentioned that the "closeStore" method of the self reference for instances of class ESPMContainerDataAccess has to be used to close the offline store.

Correct method is "close" of the service (OfflineODataProvider) instance within that class (self.service.close()).

**Comment by akula86** [comment]
@qualiture please review
