### ISSUE TITLE
Tutorial fiori-ios-hcpms-offline-odata-errorhandling: Missing usage of defined functions startScheduledUpload/stopScheduledUpload

### ISSUE THREAD

**Issue by pfefferf** [SAPDocuments/Tutorials#1575]
The defined methods startScheduledUpload/stopScheduledUpload are never used in tutorial 
https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/fiori-ios-hcpms-offline-odata-errorhandling/fiori-ios-hcpms-offline-odata-errorhandling.md

**Comment by akula86** [comment]
@qualiture please review
