### ISSUE TITLE
Tutorial fiori-ios-hcpms-secure-keystore/fiori-ios-hcpms-secure-keystore: Several issues

### ISSUE THREAD

**Issue by pfefferf** [SAPDocuments/Tutorials#1576]
In tutorial
https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/fiori-ios-hcpms-secure-keystore/fiori-ios-hcpms-secure-keystore.md
there are several issues.

Step 3:
- SAPCommon has to be imported to be able to use the Logger in step 4.

Step 4:
- Name parameter for Logger.shared wrong (Logger.shared(withName ... -> Logger.shared(named ...)

Step 7:
- SAPURLSession has not init function with a parameter urlSessionDelegate. The init function with parameter "delegate" needs to be used. That all is in sync, the class KeystoreAuthenticator has to implement protocol SAPURLSessionDelegate instead of URLSessionTaskDelegate (like described in step 4).

Step 12:
- The task delegation logic for the SAPURLSession has to be changed according to the requirements for protocol SAPURLSessionDelegate.

**Comment by akula86** [comment]
@qualiture - please review
