### ISSUE TITLE
Continuous Integration (CI) Best Practices with SAP: Introduction and Navigator

### ISSUE THREAD

**Issue by FransMetselaar** [SAPDocuments/Tutorials#1578]
Hello all,

I'm quite new in the DevOps environment but realy interested in creating one or more pipelines for a SAP environment. I'm currentlty working with SAP Solution Manager 7.2 and was thinking in this direction for solving my pipeline requirement.

But ready this Continuous Integration Best Practices I'm wondering if I'm at the right move. The reason for my doubt is that the Best Practice is not mention SAP Solution Manager and SAP Solution Manager is positioned as a enabler for DevOps.

So I'm litle bit confused.

Kind regards
Frans Metselaar

**Comment by akula86** [comment]
forwarded to @wolframK

**Comment by wolframK** [comment]
Hi Frans,

indeed, the integration of Change Management (CM) and CI practices is still an open point. We are currently working on a proposal which we hope to publish within the next months. Roughly speaking, the proposal will go into the following direction:
The leading process to bring new changes into production will be Change Management using Solution Manager. So if you e.g. use a classical 3-stage ABAP landscape resp. 3-stage account landscape in SAP CP (Dev/QA/Prod), you follow the usual qualification and release processes. The CI process will be used for quality assurance of the changes before they reach your Dev system, so you continuously integrate your non-ABAP code before it is handed over to the CM process.
DevOps is a wide field. What are your concrete requirements? Maybe I will be able to give you more concrete hints.

Best regards,
Wolfram

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
