### ISSUE TITLE
Add API Business Hub API to a UI5 Application

### ISSUE THREAD

**Issue by S0012042148** [SAPDocuments/Tutorials#1621]
Fiori application is not allowing me to use hard coded URL path.

![capture](https://cloud.githubusercontent.com/assets/27668823/25081743/0a5d032e-2301-11e7-9540-415a2a95add3.PNG)

How is it allowing for you?

Thanks!
Bhaskar

**Comment by mhassett92** [comment]
Hi Bhaskar,
I apologize for the long delay. Theses "errors" are really just warnings that Fiori best practices are not being followed. For this tutorial, it is ok to ignore these errors. When creating a production application, you would want to use Destinations in SAP Cloud Platform to better manage your APIs/URLs.

Let me know if you have additional questions. 

Meredith
