### ISSUE TITLE
Adding Grunt Plugins (TypeScript) in SAP Web IDE

### ISSUE THREAD

**Issue by alexanderchan** [SAPDocuments/Tutorials#1630]
- The prepackaged version of the .zip include the wrong version of devDependencies, should be: or perhaps "~1.3.x"

```json
    "devDependencies": {
        "@sap/grunt-sapui5-bestpractice-build": "1.3.17"
    }
```

These are more general comments and not on the documentation, hopefully you can either forward these suggestions on or point me to the correct place to log them.

- TypeScript is great and a good example of how we can use other features, however I really hope TypeScript will be adopted long term the editor can provide live feedback on type definitions in the future

- The build can't be run again if there are type errors.  Restarting webide solves this but I have even tried adding grunt to the dependencies and it still fails

![image](https://cloud.githubusercontent.com/assets/1864372/25248575/fd3a048a-25cb-11e7-80ef-f2ca90beea1e.png)

- The build process needs to have a --watch task so that it runs faster and on changes, bonus points for including the option for a live reload like browser-sync does and even more bonus points for finding a way to maintain state the same way that hot-reloading works

**Comment by avizov** [comment]
Hi,
We are updating our source code and the tutorials that devDependencies will be suggested with "^" symbol.  
Thanks,
Alex

**Comment by thecodester** [comment]
@alexanderchan I had forwarded this comments on to development group when you first wrote and they are aware of them. For now, they have no updates/comments.

I will close the issue but if you need/want more information, please let me know.
