### ISSUE TITLE
[404 error] Import a series of predictive demo dataset

### ISSUE THREAD

**Issue by salico** [SAPDocuments/Tutorials#1636]
Hello. I'm one of the SAP tutorials fan in Japan.

I cannot access the links to dataset files.
404 error is displayed.
As I can access the files inside github, please fix the problem.

Thank you very much for your contribution to this site.

**Comment by adadouche** [comment]
Hi @salico 

Thanks for your feedback.

I have fixed the link but this may be just temporary as this breaking some publication/legal rules that I will have to adhere too in the near term.

Regards

@bdel.
