### ISSUE TITLE
Working with Tables and Views using Apache Zeppelin

### ISSUE THREAD

**Issue by amitabak** [SAPDocuments/Tutorials#1640]
0_DATA: 3 first scripts run fine but then I got the following error:
spark.vora interpreter not found

**Comment by adadouche** [comment]
Hi,
Which Vora flavor (CAL, OVA...) and version are you using?
Thanks

@bdel

**Comment by amitabak** [comment]
SAP_HANA_Vora_developer_edition_1.3.ova

**Comment by Sygyzmundovych** [comment]
Please check if you are getting this error with the newest dev. edition. Thanks.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
