### ISSUE TITLE
SAP HANA XS Advanced, Connecting to the WebIDE and cloning a Git Repository to begin development

### ISSUE THREAD

**Issue by ivanmir** [SAPDocuments/Tutorials#1649]
The URL for WebIDE may vary from system to system.
One should run "xs app webide -urls' instead to obtain the correct URL avoiding usage of IP addresses and port mistakes.

**Comment by Lsubatin** [comment]
Hi, Ivan,

Thank you for the feedback. The tutorial in reference does not aim at a specific hostname or IP (IP would not work, actually). Where do you see a reference to a specific hostname?

Thanks,

Lucia Subatin.

**Comment by ivanmir** [comment]
HANA setup may vary and you might end-up with either port assignment for each service or hostname for each service (similar to what we have on SCP). In the case the setup is for port setup you are correct. The HANA XSA will assign port 53075 for WebIDE. But that may not be the case always. In a Cloud Foundry setup such as XSA it is wise to always check the URL that has been assigned to the WebIDE before trying to access it. That's why I mentioned this here. Apparently there is an implicit assumption that services will be assigned ports rather than names.
If it is a prerequisite that this howto will use a predefined server where port 53075 is expected you are correct. All I am saying is that the right way to find out which is the URL is by issuing the xs cli command mentioned above and this will work regardless of the system setup you have (be it the pre-installed image on Azure, Amazon or an on-premise installation).

**Comment by Lsubatin** [comment]
I'll take you are suggesting to add instructions to find out the Web IDE URL.
