### ISSUE TITLE
Device registration

### ISSUE THREAD

**Issue by rosshigh** [SAPDocuments/Tutorials#1650]
I doing to tutorial on iOS SDK, registering a device on HCP.  Everything appears to be correct but I get a 503 - Service unavailable when I run the program  Where might I look for the problem?

Thanks

**Comment by qualiture** [comment]
Hi @rosshigh ,

A 503 error might indicate a temporary outage of SAP Cloud Platform mobile services -- does the error still persists?

**Comment by rosshigh** [comment]
I tried it over the course of a week with the same result.  However, I just recreated everything from scratch and it worked!  Excellent, thank you for responding.

**Comment by qualiture** [comment]
Issue may be closed

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
