### ISSUE TITLE
mta builder not available / di-builder not available.  HXE1.0 XSA WebIDE

### ISSUE THREAD

**Issue by aj-code-synch** [SAPDocuments/Tutorials#1651]
Hello,

     I am running HANA Express 1.0 on AWS. I was following the tinyworld sample application blog.
While building the HDB module I am getting the error which says "hdi-builder is not available for workspace workspaceXXXXXXXX ". If I build the whole project I get error "mtabuilder is not available for workspace"
 I followed The comments on the blog but could not resolve the issue. So far I have done the following:

1. xs apps command tells me that all the apps including di-core are running under space SAP. I have tried to restart the di-core. 
2. I have set the dev space to SAP. I have assigned my user XSA_DEV the SpaceDeveloper for same space. 
3. I have rebuilt the app 3-4 times from scratch to make sure di-builder gets redeployed. 
4. I have tried restarting HDB and rebuilding the app. 

Any idea what the next steps should be?

**Comment by Lsubatin** [comment]
Hi, Anuj,

I suggest you post questions in the Community Q&A so that you can get support from the community. This repo is to provide feedback on the tutorials. In the meantime, I would suggest you use the development or DEV space (not sure what the default was in SPS12) or go into HANA 2.0 SPS01 if possible.

Regards,
Lucía Subatin.

**Comment by aj-code-synch** [comment]
Thanks Lucia. I have posted the question on QnA as well. I understand this is not the right place.  Just to respond to your comment about DEV space, post installation there was no DEV_SPACE parameter on di-core, since xs apps was showing SAP as space where all the apps were running I ended up setting it to SAP via command line. I will wait for the community at QnA to respond to the query!

**Comment by Lsubatin** [comment]
Closing this and following up in Q&A

**Comment by jmalla** [comment]
Hi Anuj - Did you ever resolve this issue?  I just spun up the HANA Express edition on AWS and running into the same issue on the build.  I did all of the same issues you had listed and still can't build it.  I created a question - https://answers.sap.com/questions/264342/hana-express-builder-mtabuilder-is-not-available-f.html.

Thanks,
Jay
