### ISSUE TITLE
Logging and tracing in SAP Cloud Platform mobile service for development and operations

### ISSUE THREAD

**Issue by pdominique** [SAPDocuments/Tutorials#1654]
I couldn't find **Log Settings** in the SAP Cloud Platform Cockpit so I went to the Mobile Services and Operations and found the the **Log Settings** under **Settings**. There's also no **Trace** column in these settings but an **Event Logs** column.

**Comment by qualiture** [comment]
Hi @pdominique,

It seems SAPCPms has been changed significantly the last weeks -- I will add it to my todo list to update the tutorial

**Comment by thecodester** [comment]
Issue closed since a year has elapsed since it was opened. If the issue is still relevant, please reopen the issue or open a new one.
