### ISSUE TITLE
Step 10: Implement the Login view logic

### ISSUE THREAD

**Issue by MovingBitsGroupRoth** [SAPDocuments/Tutorials#1657]
I'am getting "An unknown error occured". What code do I have to add to debug the problem mor deeper?

@IBAction func onLoginPress(_ sender: UIButton) {
    SAPcpms.shared.register(userId: hcpUserId.text!, password: hcpPassword.text!) {
        (success: Bool, msg: String) in
        if (success) {
            DispatchQueue.main.async {
                let viewController:UIViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "Navigation") as UIViewController!
                self.present(viewController, animated: true, completion: nil)
            }
        } else {
            OperationQueue.main.addOperation {
                let alert = UIAlertController(title: "Error", message: msg, preferredStyle: UIAlertControllerStyle.alert)
                alert.addAction(UIAlertAction(title: "OK", style: UIAlertActionStyle.default, handler: nil))
                self.present(alert, animated: true, completion: nil)
            }
        }
    }
}

**Comment by qualiture** [comment]
Hi @MovingBitsGroupRoth,

Which tutorial does it reference to?

**Comment by MovingBitsGroupRoth** [comment]
This tutorial:
https://www.sap.com/developer/tutorials/fiori-ios-hcpms-device-registration.html

**Comment by qualiture** [comment]
Hi @MovingBitsGroupRoth, one thing you can try is to set the root logger level to `debug` -- this should provide more info on what's happening inside the SDK API's

Chiming in @jpenninkhof too as he's the original author of this tutorial

**Comment by jpenninkhof** [comment]
In that section a service call is being made to SCP to register the device. It seems that this call is failing. You could try to step through the register function using the debugger to see you what's going on and why this call fails.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
