### ISSUE TITLE
Verify whether your application has been registered

### ISSUE THREAD

**Issue by robypag** [SAPDocuments/Tutorials#1659]
Hi there,
I believe there's something "wrong" in the isRegistered function, regarding the endpoint for the "serviceRoot" URL.
Accordingly to the tutorial, this would be pointing to the Application ID and - by providing the X-SMP-APPCID token in the request header, we shall get an acknowledgement or a denial message like "Application Connection is not found".

However, regardless the Application Connection ID, the serviceRoot URL (at least in my case) always return a **404 - The requested resource does not exist**

I tried also by faking the very same request via Postman - and getting the same result.

It might be something related to my application, but a similar URL is not even listed in the API reference for the application that we can get from the Mobile Service Cockpit...

Any hint?

**Comment by qualiture** [comment]
Hi @robypag,

I believe this is related to https://answers.sap.com/questions/188752/fiori-for-ios-service-root-url-not-found.html? Did that solve your issue?

**Comment by robypag** [comment]
Hello Robin,
Yes, it was.
Sorry for "pushing" that, I was eager to get it working :)

Thanks for the reply anyway, shall I close this?

Regards,
Roberto.

Il giorno 03 mag 2017, alle ore 18:07, Robin van het Hof <notifications@github.com> ha scritto:

Hi @robypag,

I believe this is related to https://answers.sap.com/questions/188752/fiori-for-ios-service-root-url-not-found.html? Did that solve your issue?
