### ISSUE TITLE
Build a basic Swift app with Xcode

### ISSUE THREAD

**Issue by SurelyPlus** [SAPDocuments/Tutorials#1669]
step 13: Do you mean the Table View Controller (2nd view) instead of Navigation Controller?

**Comment by qualiture** [comment]
Hi @SurelyPlus,

You're right -- will fix this. Thanks for noticing!

**Comment by qualiture** [comment]
Fixed in commit https://github.com/SAPDocuments/Tutorials/pull/1670/commits/2c333991c4fa2aa94e80536cd5f2541dcd91afdd
