### ISSUE TITLE
Using ABAP with the SAP API Business Hub

### ISSUE THREAD

**Issue by MarcusSchiffer** [SAPDocuments/Tutorials#1676]
Hi,

nice Tutorial.
I was however struggling with the ABAP Code. I was trying to use the SAP Clea Image Classification API and can not get the parameter "files" into the request. The ABAP demo code also does not include the settings for submitting the request body.
Could you provide a corresponding example ?

**Comment by meeximum** [comment]
Having the some troubles tried it with http client multipart, but it's too complex!

**Comment by mhassett92** [comment]
I am not familiar enough with ABAP to know how to set the request body. @Lsubatin , would you have an example of how to do a POST with ABAP?

I will reach out to the API team to see if they have a sample as well.

**Comment by mhassett92** [comment]
There are now examples on the API Hub showing how to do a post body with ABAP. Please review the documentation and re-open if you are still having issues!
