### ISSUE TITLE
Error on Installing SAP HANA 2.0, express edition (Binary Installer Method)

### ISSUE THREAD

**Issue by lixam** [SAPDocuments/Tutorials#1677]
Hi,

on that tutorial it says in step 4 "tar -xvzf <download_path>/tgz.tgz" but that must be sds.tgz!
That is a bit confusing.
<img width="1036" alt="bildschirmfoto 2017-05-05 um 12 11 22" src="https://cloud.githubusercontent.com/assets/2399392/25741662/fe1b232c-318b-11e7-8bfa-19e57863720b.png">

Felix

**Comment by i825908** [comment]
Thanks for pointing out this typo. Our doc team will fix it.

Thank you!
