### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by bimburg** [SAPDocuments/Tutorials#1681]
Can I change the IP address the VM gets installed under?  Right now it looks like it selects one from DNS but I wanted to use a static ip.

**Comment by adadouche** [comment]
Hi,
As long as you get the host file properly configured then there should be no problem.
Anyway, we encourage you to use the hostname all over by configuring the host file from the client side.
Regards

@bdel
