### ISSUE TITLE
Implement Fiori for iOS controls

### ISSUE THREAD

**Issue by rosshigh** [SAPDocuments/Tutorials#1683]
Is the code for the tutorial projects available?

**Comment by qualiture** [comment]
Hi @rosshigh,

For now, the code for the tutorial projects is not available online. I'm not sure if we could manage to do so -- not sure about legal aspects of generated code etc -- but as I obviously see the benefits, I will discuss this.

**Comment by thecodester** [comment]
Currently, we provide code snippets but do not provide full code projects, for legal reasons. We are looking at ways to provide such projects.
