### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by jenswachtel** [SAPDocuments/Tutorials#1685]
I just downloaded the latest version server + applications virtual machine using Virtualbox.
Using this tutorial, I am unfortunately unable to change the password with the VM.
It always results in 
hxehost login: hxeadm
Password: HXEHana1
=> Request to change password, typed in a new one

Authentication Failure

I am well aware of a strong password and I tried various combinations including your example password. It does not accept any password and will return to the login screen.

Using VirtualBox 5.1.10, I checked network settings (bridged) etc. The box however runs with 8192MB. 

Thanks for your help

**Comment by Chris-Huston** [comment]
@jenswachtel 

Will you confirm that you are re-entering the current ("HXEHana1") password when prompted for?

(current) UNIX password:

If your provided new password does not satisfy the HXE password policy you will be told why, for instance a password that is too short will get the message "BAD PASSWORD: it is Way too short Authentication token manipulatin error"

![password - hxe](https://cloud.githubusercontent.com/assets/20958565/26167164/ded2c070-3aea-11e7-8c3e-d93d91f7a7bb.PNG)

**Comment by jenswachtel** [comment]
Thanks for your quick response!
It doesn't even matter, if I would use a too short password it returns the same error. (see screenshot).
I downloaded all these packages just today, so everything is latest version.
As mentioned I am using Virtualbox.

<img width="646" alt="screen shot 2017-05-17 at 20 00 37" src="https://cloud.githubusercontent.com/assets/9703013/26168813/c93b5604-3b3b-11e7-9981-dd50d52a7763.png">

Thanks,
Jens

**Comment by Chris-Huston** [comment]
Jens,

Just want make sure you have re-entered the "current" password again (secod time) BEFORE adding your entering your new password.

The result you are getting is the same behavorior I get if I attempt to put in any password at the "(current) UNIX password:" prompt except the original HXE password "HXEHana1".

**Comment by jenswachtel** [comment]
That is embarrassing. I am so sorry. I never had to re-type an old password again in order to enter a new one. My brain did not recognise the "(current)" part.

Thanks for your quick help!
