### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by pdominique** [SAPDocuments/Tutorials#1697]
Here are 2 notes you could add to the tutorial:

- you have to select **My Certificates** in Keychain Access to be able to select the .p12 format when you export the certificate (http://stackoverflow.com/a/19502944)
- if you don't have the **Notification User** role, you won't see the **Send** button in the **Push Desk**. It's such a bad UX decision! (https://help.hana.ondemand.com/hana_cloud_platform_mobile_services/frameset.htm?97ea643e884149fabb21a61024c9113c.html)

Thanks for the tutorial!

**Comment by miffels** [comment]
Hi @pdominique,

To which tutorial are you referring? Could you provide a link, please?

Thank you,
Michael

**Comment by qualiture** [comment]
Hi @pdominique I assume you are referring to iOS SDK tutorial https://www.sap.com/developer/tutorials/fiori-ios-hcpms-push-notifications.html ?

Thanks for pointing this out, will amend

**Comment by pdominique** [comment]
Yes @qualiture, that's the tutorial I'm referring to.
