### ISSUE TITLE
Device registration

### ISSUE THREAD

**Issue by Lukaris** [SAPDocuments/Tutorials#1699]
I don't know, what I am doing wrong.. I followed all the necessary steps in this tutorial.. however, I always get following response string:

statusCode should be 201, but is 200
`responseString = <!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no"><meta http-equiv="pragma" content="no-cache" /></head><body style="background-color:#FFFFFF" onload="var url=window.location.hash;if(url&&0!==url.length){var anchorCookie='oucrsrocgqmfiokgttizrbffw_anchor=&quot;'+encodeURIComponent(url)+'&quot;';document.cookie=anchorCookie}document.forms[0].submit()"><p><script language="javascript">document.write("Please wait ...");</script></p><noscript><p>Note: Your browser does not support JavaScript or it is turned off. Press the button to proceed.</p></noscript><form method="post" action="https://accounts.sap.com/saml2/idp/sso/accounts.sap.com"><input type="hidden" name="SAMLRequest" value="PEF1dGhuUmVxdWVzdCB4bWxucz0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIiB4bWxuczpuczI9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iIHhtbG5zOm5zMz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyIgeG1sbnM6bnM0PSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGVuYyMiIEFzc2VydGlvbkNvbnN1bWVyU2VydmljZVVSTD0iaHR0cHM6Ly9oY3Btcy1zMDAwMTgyODQ2NnRyaWFsLmhhbmF0cmlhbC5vbmRlbWFuZC5jb20vb2RhdGEvYXBwbGljYXRpb25zL3Y0L2NvbS5zYXAudHV0b3JpYWwuZGVtb2FwcC5EZW1vL0Nvbm5lY3Rpb25zIiBEZXN0aW5hdGlvbj0iaHR0cHM6Ly9hY2NvdW50cy5zYXAuY29tL3NhbWwyL2lkcC9zc28vYWNjb3VudHMuc2FwLmNvbSIgRm9yY2VBdXRobj0iZmFsc2UiIElEPSJTMDYzMGUxZDctOTZmOS00NDUyLWJiNGItYzc4M2NjYzBlMjQ4LVphRjJIYnhveG5oSmcuM0ZpOGM5eklkS3ZUNEJOajhDbzVOMU1aQk9CMm8iIElzc3VlSW5zdGFudD0iMjAxNy0wNS0yMlQyMzoxMDo0NS44NzdaIiBWZXJzaW9uPSIyLjAiPjxuczI6SXNzdWVyPmh0dHBzOi8vbnd0cmlhbC5vbmRlbWFuZC5jb208L25zMjpJc3N1ZXI+PGRzOlNpZ25hdHVyZSB4bWxuczpkcz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyI+PGRzOlNpZ25lZEluZm8+PGRzOkNhbm9uaWNhbGl6YXRpb25NZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz48ZHM6U2lnbmF0dXJlTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI3JzYS1zaGExIi8+PGRzOlJlZmVyZW5jZSBVUkk9IiNTMDYzMGUxZDctOTZmOS00NDUyLWJiNGItYzc4M2NjYzBlMjQ4LVphRjJIYnhveG5oSmcuM0ZpOGM5eklkS3ZUNEJOajhDbzVOMU1aQk9CMm8iPjxkczpUcmFuc2Zvcm1zPjxkczpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjZW52ZWxvcGVkLXNpZ25hdHVyZSIvPjxkczpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz48L2RzOlRyYW5zZm9ybXM+PGRzOkRpZ2VzdE1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNzaGExIi8+PGRzOkRpZ2VzdFZhbHVlPnEzd2FQNWVLdDlxN0JUUmVRRHA2MEt6d2lJVT08L2RzOkRpZ2VzdFZhbHVlPjwvZHM6UmVmZXJlbmNlPjwvZHM6U2lnbmVkSW5mbz48ZHM6U2lnbmF0dXJlVmFsdWU+SldQZm9HSVRnWlBCc21QY3pUTnlDUERBbmFTNEI1M1lROTlyTThWV3BrL1FPTkVVODF6VG9tSmtLWHVGQk43ZnFBbWVPbXZVVWVGNTNXMUpzK3A4akVadW5DL1lEK0p4eE1YZ0hSWkFPRFJuWWxRUTE2UWFSNFZOek5xcHVXZVArSk9CaEEvWmJiVlFBbHlsQUw5ZXo3eWFSNmova2pNZ0xITWVtNG5FYUNmK1FrUWpEOHZhZnQwakdWbDI3Mk1oRVkybk1qTW5mNmdja1BIS3VFWDVqTHVIb0g2MmxibktvN1JkZnR2YzE5OExzNG9UTnNqMjk0V1dFTHVxUWtjdThCblo2WlpUd1Rtd1pvczBtOTQ2b1lUNDZvYTNIa3RZUGZWWEtrSjVSY2M0a3NxQXJORXdzWTNRR1l1ZTYrQzZEZEc4V2tDL2lhWWIvcWdKL3dxOFdRPT08L2RzOlNpZ25hdHVyZVZhbHVlPjwvZHM6U2lnbmF0dXJlPjwvQXV0aG5SZXF1ZXN0Pg=="/><input type="hidden" name="RelayState" value="oucrsrocgqmfiokgttizrbffw"/><noscript><input type="submit" value="Continue"/></noscript></form></body></html>
`

**Comment by SamiLechner** [comment]
Hi 

can you please let me know what tutorial you are doing and on which step you are facing the challange.
Thanks Sami

**Comment by Lukaris** [comment]
[https://www.sap.com/developer/tutorials/fiori-ios-hcpms-device-registration.html](url)

with step 16 it happens

I am using Basic Authentication.  however get the 200 error...   
(does it mean, we have still to send a "GET" after the "POST" ?  if yes..  than the coding is missing in this tutorial).

**Comment by miffels** [comment]
@jpenninkhof If I am not mistaken, this would be a tutorial of yours. Would you mind taking a look?

Thanks,
Michael

**Comment by jpenninkhof** [comment]
Tutorial is not available anymore. Suggest to close this issue.
