### ISSUE TITLE
Run and Test a Project in SAP HANA Smart Data Streaming

### ISSUE THREAD

**Issue by jgamezoj** [SAPDocuments/Tutorials#1701]
Hello,
thanks for your contribution on this topic. 
The file **machinedata.csv** is no longer active. Could you please re-upload? or re-activate the link to the file?
Thank you and kind regards

**Comment by akula86** [comment]
Make sure you right-click on the link in step 4 and select **Save Link/Taget As...** - I just tried it at it works fine. @jdwoot

**Comment by jgamezoj** [comment]
Thanks for your reply. I tried what you suggested but the download cannot be made (with IE). I tried with Google Chrome and it throws error "no file". I also tried giving the file other names/extensions without success. Is there another way I can get the file?...
Thanks.
J.

**Comment by jgamezoj** [comment]
It does not work with IE and Chrome. With Firefox it does!
Best
J.

**Comment by jgamezoj** [comment]
I tried that in IE and Chrome and did not work. I am able to download a .cvs file in Firefox but it is the html content from the site and not the actual information. It is not working for me. Is there any other way I can get the correct file for the exercise?
Thank you.
J.

**Comment by jdwoot** [comment]
I'm a bit perplexed why that isn't working.  I've tried it from several browsers and it works.  Try this: see if you can get to the source file on github directly: https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/sds-event-stream-playback/machinedata.csv 

If you can,  then right click on the "Raw" button to see if you can save the file.  If not, click on the Raw button to view the file in plain text and copy and paste it into a text file.  Let me know if that works.  We'll have to get to the bottom of this.

**Comment by jgamezoj** [comment]
I downloaded the file by right-clicking on the "Raw" button. It worked just fine! Thank you!

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
