### ISSUE TITLE
SAP HANA XS Advanced, Creating an HTML5 Module

### ISSUE THREAD

**Issue by elango1s** [SAPDocuments/Tutorials#1731]
Add the UAA service as a dependent resource - step 3 
The value for 'Type' (substep 2) should have been 'com.sap.xs.ua-space'

Create the UAA service for your application - step 4 (when using HANA Express with HANA 2)
The xs login should be: 'xs login -a https://<Fully Qualified hostname>:39030 -o HANAExpress -s development -u XSA_DEV'

**Comment by Lsubatin** [comment]
Hi, elango1s, than you for the feedback but that type is incorrect. Also, the instance number will depend on the instance number you have chosen. I will add yet another note, though.
Thanks,

Lucia.
