### ISSUE TITLE
SAP HANA XS Advanced, Creating an HDI Module

### ISSUE THREAD

**Issue by elango1s** [SAPDocuments/Tutorials#1732]
many namespace issues
some silly omissions - though this helped understand the error logs upon compile

**Comment by Lsubatin** [comment]
Hi, elango1s, I am not clear on what you are trying to provide as feedback. Can you please elaborate?

**Comment by elango1s** [comment]
all naming like 'PurchaseOrder.Header' does not compile and instead requires the full path like 'hana2.db.data::PurchaseOrder.Header'. I am using HANA Express with version 2 SP1...
This applies to all tables, roles, sequence, synonms etc.

**Comment by Lsubatin** [comment]
Hi, Elangovan Subbiah,
  
You are missing a configuration. Please open a question in the community for help, 

I suggest you compiled all your issues into a single place (yes, the tutorials for SPS11 will work on SPS11 and have some differences with HANA 2.0 SPS1, we are working on updating them).

I would also suggest you kept a kind tone when asking for help. I'm closing this and any other issue that is related to support as they belong in the Q&A. 

Kind regards,

Lucia Subatin.
