### ISSUE TITLE
Web Sockets within Node.js SAP HANA applications

### ISSUE THREAD

**Issue by elango1s** [SAPDocuments/Tutorials#1735]
build of js failed, possible cannot find package 'ws'. I am using HANA Express v2 SP1. The folder/pacakge ws does not exist in node_modules! 
***************************************************
npm ERR! node v6.9.3
npm ERR! npm v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: ws@latest
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.1.1, 0.8.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'js'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR! /hana/shared/HXE/xs/app_working/hxehost/executionroot/d623bd4c-15ba-4a46-8055-8ebdaa2bd674/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/sap.nodejs/builds/build-286301302963528668/js/npm-debug.log
13:16:07 (DIBuild) Build of /hana_2/js failed.
13:16:07 (Builder) Check console logs for details
13:16:07 (Builder) Build of /hana_2/js failed.
***************************************************

**Comment by ccmehil** [comment]
Have you installed the 'ws' package for Node?

**Comment by elango1s** [comment]
i installed the hana express 2.0 and did not install anything else outside that. I see ws is definitely not installed in node_modules.
is there an sap version of ws? can you help point the right direction to download and install?

**Comment by ccmehil** [comment]
Typically it should not be needed but you can try the 'npm install ws -g'
