### ISSUE TITLE
Creating a Graphical Calculation View

### ISSUE THREAD

**Issue by elango1s** [SAPDocuments/Tutorials#1736]
One can only create a project 'dev602' with a HANA DB module called 'db'; which means the namespace should be 'dev602.db.data'. And this is what is shown as images in the tutorial.
Where as the downloaded files from git is showing a namespace of 'dev602.data'!!
Hence unable to build the HDI for db...

**Comment by Lsubatin** [comment]
Elangovan Subbiah, 

The tutorial instructs you on where the file needs to be imported so you do not have that issue.  We appreciate productive feedback delivered in a kind way. 

As suggested in one of the other issues you opened, please open a question in the Community Q&A if you need support figuring the directory structure out.

Regards,

Lucía Subatin.
