### ISSUE TITLE
SAP HANA, express edition, extract installation files and execute script

### ISSUE THREAD

**Issue by ssathyas** [SAPDocuments/Tutorials#1738]
This does not work. This only installs the server. The XSA does not get installed. I think the parameters are missing or The script file needs to be changed. See at the bottom of this log. Even though I selected all, on the parameter is saying no and my Hana install is successful but the LCM and other components don't get installed. 

Component [all]: all

Enter local host name [sshxe]: sshxe

Enter SAP HANA system ID [HXE]: HXE

Enter HANA instance number [90]: 00

Password must be at least 8 characters in length.  It must contain at least
1 uppercase letter, 1 lowercase letter, and 1 number.  Special characters
are allowed, except \ (backslash), " (double quotes), and ` (backtick).

Enter HDB master password:
Confirm "HDB master" password:

Do you need to use proxy server to access the internet? (Y/N): n

SAP HANA Interactive Education, or SHINE, is a demo application that makes
it easy to learn how to build applications on SAP HANA Extended Application
Services Advanced Model.
Install SHINE? (Y/N) : y

The SAP HANA smart data streaming option processes high-velocity, high-volume
event streams in real time, allowing you to filter, aggregate, and enrich raw
data before committing it to your database.
Install SAP HANA Smart Data Streaming? (Y/N) : y

##############################################################################
# Summary before execution                                                   #
##############################################################################
HANA, express edition installer : /home/srini/HANA_EXPRESS_20
  Component(s) to install       : HANA server, Application Function Library, and Extended Services + apps (XSA)
  Host name                     : sshxe
  HANA system ID                : HXE
  HANA instance number          : 00
  Master password               : ********
  Proxy host                    : N/A
  Proxy port                    : N/A
  Hosts with no proxy           : N/A
  Install SHINE                 : Yes
  Install SDS                   : Yes

Proceed with installation? (Y/N) : y
Installing HDB server...

SAP HANA Lifecycle Management - SAP HANA Express Edition 2.00.010.00.1491294693
*******************************************************************************
Start reading from input channel...
... Done.

Summary before execution:
=========================

SAP HANA Express Edition System Installation
   Installation Parameters
      Remote Execution: ssh
      Use single master password for all users, created during installation: Yes
      Database Isolation: low
      Installation Path: /hana/shared
      Local Host Name: sshxe
      SAP HANA System ID: HXE
      Instance Number: 00
      Local Host Worker Group: default
      System Usage: development
      Location of Data Volumes: /hana/shared/data/HXE
      Location of Log Volumes: /hana/shared/log/HXE
      Directory containing custom configurations: /home/srini/HANA_EXPRESS_20/DATA_UNITS/HDB_SERVER_LINUX_X86_64/configurations/custom
      Certificate Host Names: sshxe -> sshxe
      System Administrator Home Directory: /usr/sap/HXE/home
      System Administrator Login Shell: /bin/bash
      System Administrator User ID: 1001
      ID of User Group (sapsys): 79
      Restart system after machine reboot?: Yes
      Inter Service Communication Mode: ssl
   Software Components
      SAP HANA Database
         Install version 2.00.010.00.1491294693
         Location: /home/srini/HANA_EXPRESS_20/DATA_UNITS/HDB_SERVER_LINUX_X86_64/server
      SAP HANA AFL (incl.PAL,BFL,OFL,HIE)
         Install version 2.00.010.0000.1491308763
         Location: /home/srini/HANA_EXPRESS_20/DATA_UNITS/HDB_AFL_LINUX_X86_64/packages
      SAP HANA Database Client
         Do not install
      SAP HANA Smart Data Streaming
         Do not install
      SAP HANA XS Advanced Runtime
         Do not install

Finally this is the log where the install stops 

SAP HANA Lifecycle Management - Update Repository 2.1.25
********************************************************

Start reading from input channel...
... Done.
Importing delivery units...
Importing delivery unit HDC_SYS_ADMIN
Importing delivery unit HANA_SYS_ADMIN
Update Repository done
Log file written to '/var/tmp/hdb_HXE_UpdateRepository_2017-06-03_04.37.16/hdbupdrep.log' on host 'sshxe'.
Enable statistics server...
* 10: authentication failed SQLSTATE: 28000

Failed to enable statistics server.

**Comment by YiqingLing** [comment]
It looks you are installing the server-only version. With server-only version, XSA will not be installed.

**Comment by tai-le** [comment]
> Enable statistics server...
> 10: authentication failed SQLSTATE: 28000
> Failed to enable statistics server.

What special character(s), if any, do you have in the password?

Are you able to login to the HANA server through hdbsql after the failure? Login to "sshxe" as "hxeadm" and run:

hdbsql -i 90 -d SystemDB -u SYSTEM -p <password>
