### ISSUE TITLE
Build an app from an SAP Web IDE template

### ISSUE THREAD

**Issue by PeterDaRibeira** [SAPDocuments/Tutorials#1739]
Hi 

Thanks for the tutorial. I'm however experiencing a 404 error when running it. It is not finding cordova.js pease assist.

Regards
Peter

**Comment by akula86** [comment]
Peter,

I just ran through the tutorial and the app built and ran correctly. I suggest you go through it again, and make sure of two things: 1) use the SAPUI5 Master Detail Kapsel Template, and 2) when running the app, select the index.html and click the Run button.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
