### ISSUE TITLE
Deploy an JCo / RFC based on-premise extension using SAP HANA Cloud Connector

### ISSUE THREAD

**Issue by d039043** [SAPDocuments/Tutorials#1758]
Hi There,
I am trying to follow the instructions in this [tutorial](https://www.sap.com/germany/developer/tutorials/hcp-scc-onpremise-extension-jco-rfc.html).
In step 3: it states Go to D:/sap_hcp_scc/ using the Windows Explorer and rename file dest_sflight.jcoDestination to dest_sflight.

In my car I am on a Mac and unable to find the above files! Where can I find those files? Do I need to download something except the flight WAR file?
Thanks.

**Comment by Peter42** [comment]
Hi,
this file is not on your local machine. It is located on the AWS Windows system.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
