### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by jjmiquel** [SAPDocuments/Tutorials#1760]
Hi there,
I have problems with the step 5. I press Y but after a very long time HDB daemon dose not start.
I downloaded the VMware Workstation 12 Player and the hxexsa.ova file.
"Cannot find running HANA server."
>HDB start
"FAIL: process hdbdaemon HDB Daemon not running"

**Comment by Lsubatin** [comment]
Hi, please use the Q&A (https://answers.sap.com/index.html) for this kind of issue as this is for issues related to the tutorials, not technical problems.  This is a common error with many probable root causes, so I suggest you browse the existing posts before you post your own. Lastly, the following information helps troubleshooting: your computer's technical characteristics (**remember you need at least 16GB RAM to run the XSA image** and you might also want to check free disk space) and the errors in the tracefiles as the error message you are posting does not say much.  Cheers!
