### ISSUE TITLE
Build an app from an SAP Web IDE template

### ISSUE THREAD

**Issue by mikeyfreake** [SAPDocuments/Tutorials#1761]
Hey,

Looks like the Kapsel applications are deprecated. I'm not sure what will be replacing these for hybrid app development, but wanted to let you know since I guess this makes the tutorial out of date.

Cheers,
Mike

**Comment by mhassett92** [comment]
Hi Mike,

We are aware that the Kapsel template is deprecated, and are actively working on creating a new template. In the meantime, you can use the SAP Fiori Master-Detail Application template to complete the tutorials. There might be minor field name differences, but the overall function is the same and you are able to complete all tutorials in the series using this template.

Thanks!
Meredith
