### ISSUE TITLE
Create an ABAP project in Eclipse

### ISSUE THREAD

**Issue by ericvancurler** [SAPDocuments/Tutorials#1765]
While the tutorial seems straightforward after downloading eclipse and installing the ABAP plugin an error occurs (tried on different computers) while trying to create a new ABAP project.  "c:\users\user\AppData\Roaming\SAP\Common" does not point to a SAP GUI configuration file.  How do I correct this?

**Comment by Lsubatin** [comment]
Is SAP GUI installed on your computer?
