### ISSUE TITLE
Installing the SAP Cloud Platform for iOS SDK

### ISSUE THREAD

**Issue by mohiteveer** [SAPDocuments/Tutorials#1766]
Team,
This is regarding Step 1->3 : Folder Tools contain scripts to generate OData proxy classes manually
Open the folder Tools > ProxyGenerator. Drag the executable sapcpsdk-proxygenerator and folder sapcpsdk-resources to the UsrLocalBin folder (which is a symbolic link to your /usr/local/bin folder) so you can call the proxy generator from any location:

I get the following error:
The operation can’t be completed because the original item for “UsrLocalBin” can’t be found.

Please suggest next steps.
I changed the visibility settings to see hidden files but I can't see the 'bin' folder under local.
Do I have to create one?

**Comment by qualiture** [comment]
Hi @mohiteveer, it could be a permission problem. Can you check the permissions?

In the screenshot below, you can see `robin` is the owner of the `bin` directory (and belong to the `admin` group). If your machine is locked down, it could be different. Can you check?

<img width="1235" alt="screen shot 2017-06-23 at 20 34 07" src="https://user-images.githubusercontent.com/7068851/27495802-b9906b60-5853-11e7-8277-cf7384220d1f.png">

**Comment by mohiteveer** [comment]
Hi! Qualiture,
Thank you for responding.  I checked the permissions and also logged in as ROOT but its the same result. There is no /usr/local/bin folder.

So here's the history..I unboxed my Mac mini, setup my account, installed Xcode 8.3.3 and then downloaded the SAP Cloud Platform SDK for iOS (Xcode 8.3) 1.0 SP02 PL05 and started following the tutorial. That's when I came to step 3 and could not find the /usr/local/bin folder. What am I missing?

Here's the output of the above commands you asked for...
![screen shot 2017-06-24 at 1 25 33 pm](https://user-images.githubusercontent.com/29659014/27506877-a9a0f322-58e0-11e7-8862-36fc865071a6.png)

At the same time, there is a note on the SAP tutorial that says "If you plan to use the SDK Assistant tool, you can skip this tutorial. The SDK Assistant will set the correct SDK configuration and references in the generated Xcode project". I know that's the easier way but then I will never know what went wrong in this process.

Appreciate your help. Looking forward to your comments.
-Veer.

**Comment by mohiteveer** [comment]
Qualiture,
Hi!

I created a folder bin using ROOT login and am continuing the install process. Hope this is what you would have suggested as well.
![screen shot 2017-06-24 at 2 02 51 pm](https://user-images.githubusercontent.com/29659014/27507108-0b7d0f86-58e6-11e7-909b-c1ccb5f6550c.png)

**Comment by qualiture** [comment]
Hi @mohiteveer, did it work creating the `bin` folder manually?

**Comment by mohiteveer** [comment]
Qualiture,
Good Morning!

Yes, I was able to proceed with the tutorial after creating the bin folder manually.
Side note: it would help updating the tutorial with some of these tips....eg: installing the sdk via user having admin rights, creating a folder via root, et. I know these might be obvious plays but for the beginner (people like me) it makes our lives easier.
Thank you again and have a great day.  With your consent, I would like to close the issue.

**Comment by mohiteveer** [comment]
thanks for all the help. Issue closed.
