### ISSUE TITLE
Add API Business Hub API to a UI5 Application

### ISSUE THREAD

**Issue by leedorian** [SAPDocuments/Tutorials#1768]
Got MXLHTTPREQUEST ERROR : Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'https://www.sap.com' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
While sending request, still not working.

**Comment by mhassett92** [comment]
There are 2 solutions for this issue. One is permanent and one is temporary.

The temporary (read: faster) option is to use a plugin on Chrome to disable the CORs requirements. You can use something as the "Allow-Control-Allow-Origin: *" plugin. In Safari, you can disable the CORs requirements through the Developer tools.

The more permanent solution is to use API Management or Destinations. Both of these tools (available through the SAP Cloud Platform) while manage the CORs requirements for you and will pass the proper header. There are other tutorials for constructing a Destination in SAP Cloud Platform that should help you. 

Let me know if you have additional questions.
