### ISSUE TITLE
Tutorial Page ci-best-practices-xsa.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [SAPDocuments/Tutorials#1771]
Tutorial issue found: [https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/ci-best-practices-xsa/ci-best-practices-xsa.md](https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/ci-best-practices-xsa/ci-best-practices-xsa.md) contains invalid primary tag.
Your tutorial was not created. Please double-check primary tag property.

Each tutorial md-file shall have primary tag provided above. Example:
\-\-\-
title: Text Bundles within Node.js SAP HANA applications
description: Working with text bundles in Node.js
primary_tag: products>sap\-hana
tags: [ tutorial>intermediate\, products>sap\-hana\, products>sap\-hana\-\-express\-edition ]
\-\-\-

 Affected server: PROD

**Comment by wolframK** [comment]
Was already fixed 2 weeks ago.

Thanks,
Wolfram
