### ISSUE TITLE
Deploy a Micro Service Built on YaaS on the SAP Cloud Platform

### ISSUE THREAD

**Issue by joeybronner** [SAPDocuments/Tutorials#1775]
[URL of the tutorial](https://www.sap.com/developer/tutorials/yaas-deploy-run-microservice-cloud.html)

Hi, 

In the step 3, the package called "**HCP, STARTER EDITION FOR CLOUD FOUNDRY SERVICES (BETA)**" is not available in the list of packages (worlwide (beta) selected in the right top corner dropdown list).

Can you please help me or update the tutorial if something has changed?

Thank you in advance, 
Joey

**Comment by thecodester** [comment]
Issue closed since a year has elapsed since it was opened. If the issue is still relevant, please reopen the issue or open a new one.
