### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Binary Installer Method)

### ISSUE THREAD

**Issue by sanjDod** [SAPDocuments/Tutorials#1777]
Hello,
I am trying to install HXE at a new project, but unable to proceed. 
I followed the video (https://www.sap.com/assetdetail/2016/09/eccafc12-8a7c-0010-82c7-eda71af511fa.html) posted on SAP Hana XE install and also followed every single step, requirements, but nothing seem to work. 
During installation beginning, I went with default parameters:

HANA, express edition installer root directory [/home/testhana/HANA_EXPRESS_20]: 
Enter component to install:
   server - HANA server + Application Function Library
   all    - HANA server, Application Function Library, Extended Services + apps (XSA)
Component [all]: 

Enter local host name [testhana]: 

Enter SAP HANA system ID [HXE]: 

Enter HANA instance number [90]: 

Password must be at least 8 characters in length.  It must contain at least
1 uppercase letter, 1 lowercase letter, and 1 number.  Special characters
are allowed, except \ (backslash), " (double quotes), and ` (backtick).

Enter HDB master password: 
Confirm "HDB master" password: 

Do you need to use proxy server to access the internet? (Y/N): N

SAP HANA Interactive Education, or SHINE, is a demo application that makes
it easy to learn how to build applications on SAP HANA Extended Application
Services Advanced Model.
Install SHINE? (Y/N) : Y

SAP EA Designer lets you capture, analyze, and present your organization's
landscapes, strategies, requirements, processes, data, and other artifacts
in a shared environment.
Install SAP EA Designer? (Y/N) : Y

The SAP HANA smart data streaming option processes high-velocity, high-volume
event streams in real time, allowing you to filter, aggregate, and enrich raw
data before committing it to your database.
Install SAP HANA Smart Data Streaming? (Y/N) : Y

##############################################################################
# Summary before execution                                                   #
##############################################################################
HANA, express edition installer : /home/testhana/HANA_EXPRESS_20
  Component(s) to install       : HANA server, Application Function Library, and Extended Services + apps (XSA)
  Host name                     : testhana
  HANA system ID                : HXE
  HANA instance number          : 90
  Master password               : ********
  Proxy host                    : N/A
  Proxy port                    : N/A
  Hosts with no proxy           : N/A
  Install SHINE                 : Yes
  Install SAP EA Designer       : Yes
  Install SDS                   : Yes

Proceed with installation? (Y/N) : Y
Installing HDB server...

It seems install fails when it is installing XSA components. Here's the error message:
SAP HANA Express Edition
   Update Parameters
      SAP HANA System ID: HXE
      Location of SAP HANA Express Edition Installation Medium: /home/testhana/HANA_EXPRESS_20
      Remote Execution: ssh
      Update Execution Mode: standard
      Database User Name: SYSTEM
      XS Advanced App Working Path: /hana/shared/HXE/xs/app_working
      Customer Organization Name: HANAExpress
      XS Advanced Admin User: XSA_ADMIN
      Customer Space Name: development
      Routing Mode: ports
      Run Applications in SAP Space with Separate OS User (y/n): No
      Run Applications in Customer Space with Separate OS User (y/n): No
      XS Advanced Components: all
      Do not start the selected XS Advanced components after installation: none
   Software Components
      SAP HANA AFL (incl.PAL,BFL,OFL,HIE)
         Version 2.00.010.0000.1491308763 , do not update
      SAP HANA Database
         Version 2.00.010.00.1491294693 , do not update
      SAP HANA Database Client
         Do not install
      SAP HANA Smart Data Streaming
         Do not install
      SAP HANA XS Advanced Runtime
         Install version 1.0.55.288028
         Location: /home/testhana/HANA_EXPRESS_20/DATA_UNITS/XSA_RT_10_LINUX_X86_64/packages
   XS Advanced Components
      SAP HANA Cockpit
         Install version 2.002.5
         Location: /home/testhana/HANA_EXPRESS_20/DATA_UNITS/HANA_COCKPIT_20/XSACCOCKPIT02_5.zip
      SAP HANA tools for accessing catalog content, data preview, SQL console, etc.
         Install version 2.001.3
         Location: /home/testhana/HANA_EXPRESS_20/DATA_UNITS/XSAC_HRTT_20/XSACHRTT01_3.zip
      XS Monitoring 1
         Install version 1.004.0
         Location: /home/testhana/HANA_EXPRESS_20/DATA_UNITS/XSA_CONTENT_10/XSACMONITORING04_0.ZIP
      Develop and run portal services for custome apps on XSA
         Install version 1.001.0
         Location: /home/testhana/HANA_EXPRESS_20/DATA_UNITS/XSA_CONTENT_10/XSACPORTALSEt line 47: [03] Loading Hana-Service-Broker configuration. (broker/userconfig.json) 
          Output line 49: [03] Insecure HANA JDBC connection for HANA Broker Rename is configured!
          Output line 50: [03] Loading Hana-Service-Broker credentials. DBID :3234d4ff-3f9c-a746-ac9a-80706b2a96f8
          Output line 55: [07] Creating organization 'HANAExpress'
          Output line 56: [07] Creating space 'development' 
          Output line 57: [07] Creating space 'SAP' 
          Output line 73: [12] Uploading the HANA JDBC driver runtime v1
          Output line 74: [19] Uploading the Tomcat 8 runtime
          Output line 75: [17] Uploading the SAP JVM 8 JRE runtime
          Output line 76: [15] Uploading the Node.js 4 runtime
          Output line 77: [16] Uploading the Node.js 6 runtime
          Output line 78: [22] Creating UAA security Hana-Service-Broker
          Output line 79: [18] Uploading the SAP JVM 8 runtime
          Output line 80: [20] Uploading the TomEE 1.7 runtime
          Output line 81: [21] Creating Hana-Service-Broker
          Output line 82: [13] Uploading the HANA JDBC driver runtime v2
          Output line 83: [10] Uploading Node.js buildpack
          Output line 84: [09] Uploading Java buildpack
          Output line 87: [24] Creating Instance-Manager-Broker
          Output line 93: [27] Creating application auditlog-db
          Output line 94: [27] Creating service auditlog-db-container
          Output line 95: [27] Uploading files for application auditlog-db
          Output line 101: [27]   6/28/17 3:49:07.828 PM [STG/1] OUT   Downloading Node.js...
          Output line 102: [27]   6/28/17 3:49:07.960 PM [STG/1] OUT   Unpacking Node.js archive...
          Output line 104: [27]   6/28/17 3:49:07.971 PM [STG/1] OUT   Copying SSL CA certificates...
          Output line 106: [28] Creating application auditlog-server
          Output line 107: [28] Creating service auditlog-sbss
          Output line 108: [28] Uploading files for application auditlog-server
          Output line 121: [29] Creating application auditlog-broker
          Output line 122: [29] Uploading files for application auditlog-broker
          Output line 128: [29]   6/28/17 3:49:29.727 PM [STG/1] OUT   Downloading Node.js...
          Output line 129: [29]   6/28/17 3:49:29.810 PM [STG/1] OUT   Unpacking Node.js archive...
          Output line 131: [29]   6/28/17 3:49:29.818 PM [STG/1] OUT   Copying SSL CA certificates...
          Output line 132: [29] Creating audit-log Hana-Service-Broker
          Output line 134: [30] Creating application deploy-service
          Output line 135: [30] Creating  service deploy-service-auditlog
          Output line 136: [30] Creating service deploy-service-ss
          Output line 137: [30] Creating service deploy-service-database
          Output line 138: [30] Creating service deploy-service-uaa
          Output line 139: [30] Uploading files for application deploy-service
          Output line 142: [30] com.sap.xs2rt.installation.util.InstallationException: Installing the Deploy Service application failed: Staging of app "deploy-service" failed
          Output line 193: com.sap.xs2rt.installation.util.InstallationException: Installing the Deploy Service application failed: Staging of app "deploy-service" failed
Update of SAP HANA Express Edition components failed.
  Error occurred while executing Update SAP HANA Express Edition System and Components.

I would really appreciate some help. Please advise, thanks!

SanJ

**Comment by MaryTQi** [comment]
Hi SanJ,

To assist with the diagnosis, could you share the logs if this environment is still available? The logs are located in the /var/tmp directory and begin with "hdb".

In addition, information on the operating system version as well as the HXE version would be helpful. The HANA Express version information can be found in the file "/usr/sap/HXE/SYS/global/hdb/hxe_info.txt".

Regards,
Mary

**Comment by ccmehil** [comment]
While you are gathering the logs quick question - how much memory does the machine have?

**Comment by Lsubatin** [comment]
Closing after lack of response
