### ISSUE TITLE
Predictive Analytics Using Application Function Modeler

### ISSUE THREAD

**Issue by viki9698** [SAPDocuments/Tutorials#1779]
Hi, why when execute this flow graph, it throws a exception as **"SAP DBTech JDBC: [2048]: column store error: "DEVUSER"."AFL::autoarima": line 10 col 1 (at pos 546): column store error: search table error:  [2629] executor: plan terminated internally after being inactive for too long "**

**Comment by aplata-sap** [comment]
Hi There,

Can you provide more information? Which SAP HANA, express edition installation are you using, what version of HANA studio, and which version of the PAL scheme data are you using?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
