### ISSUE TITLE
Modules within Node.js SAP HANA applications

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Tutorials#1783]
Hi Team,

How do I get the option to create Node.js applications through my trial WebIDE?  Is that possible?

I just created a question for this:
https://answers.sap.com/questions/252339/nodejs-in-webide-for-hana-trial-account.html

Thanks,
Jay

**Comment by ccmehil** [comment]
Through the Cloud Foundry version of SAP Cloud Platform or through SAP HANA express edition or your own SAP HANA system are the only options currently for XSA.

**Comment by jmalla** [comment]
Thanks Craig.  I am exploring the Cloud Foundry version - but I think we cannot use the webIDE to create a NodeJS module - that's only possible on the HANA express or another HANA instance (e.g. AWS or Azure) according to the response to my article - https://answers.sap.com/questions/252339/nodejs-in-webide-for-hana-trial-account.html?childToView=251465#answer-251465.  So does SAP have plans so that webIDE on the trial account can be used to develop NodeJS directly instead of going the Eclipse route?
