### ISSUE TITLE
Consume a Basic OData Service

### ISSUE THREAD

**Issue by lnryan** [SAPDocuments/Tutorials#1789]
Please include information about what the referenced SHINE components in the Exercise do. It's one thing to provide prepared examples, but this appears to create dependencies on assets in the SHINE Exercise packages which isn't a stable approach for someone trying to create a 'real' application following these tutorials. If this is just a naming convention then it would be helpful to highlight that these names are not actually for external resources; however when i tried to rename the shine components with local names it still tried to fetch them from the sapui5 endpoint

Also please can you provide an updated version for 2.0?

Thanks

**Comment by Lsubatin** [comment]
This has been updated
