### ISSUE TITLE
Implement Offline OData in your application

### ISSUE THREAD

**Issue by andreasschlosser** [SAPDocuments/Tutorials#1792]
In step 6 - change init() event hook

It should just read `serviceRoot: Constants.appUrl` as the constant is a URL already

The offlineParameters.customHeaders = ["X-SMP-APPID": Constants.appId] is not wrong, but not needed in recent SDK versions - that was only required in the early adopter release version and fixed by now.

On a side note, this would typically be called the 'initializer', not 'event hook' - so maybe simply say "Change the initializer"?

**Comment by qualiture** [comment]
Thanks Andreas, will fix!

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
