### ISSUE TITLE
Add API Business Hub API to a UI5 Application

### ISSUE THREAD

**Issue by jsgebo** [SAPDocuments/Tutorials#1796]
Hi,
in step 2 you refer to the User Information service, it is now named "User Management".
Please update accordingly.

Thanks,
Jeff

**Comment by mhassett92** [comment]
Hi Jeff, 

SuccessFactors recently updated their API packaging. I have made the updates to the tutorials that reference that API package to fit the new package. If you clear your cache, you should find step 2 has been updated. 

Thank you,
Meredith
