### ISSUE TITLE
AngularJS - Add the AngularJS JavaScript

### ISSUE THREAD

**Issue by sharathmg6** [SAPDocuments/Tutorials#1798]
Very interesting. 

We have an Angular JS application developed by a contractor on Atom Editor. 

It would be great if we can get some guidance from your team on undertaking the task of importing it into Web IDE and continue its development. 

I look froward to your response. 

Regards,
Sharath
mail: sharathmg6@gmail.com

**Comment by jonathanbaker7** [comment]
Please ask this question in the SAP Questions and Answers (Q&A) forum:  https://www.sap.com/community/about/questions-and-answers.html.
