### ISSUE TITLE
An Open Data Protocol (OData) primer for developers

### ISSUE THREAD

**Issue by Alexandre-Lara** [SAPDocuments/Tutorials#1804]
Hi Guys,

Your tutorial is really really good. But I think there's an error at this link because it doens't working:
 
**http://services.odata.org/V2/Northwind/Northwind.svc/Products$format=json&$top=2&$orderby=ProductName\ desc>**

Maybe we need to change for this one:

**http://services.odata.org/V2/Northwind/Northwind.svc/Products?$format=json&$top=3&$orderby=ProductName%20desc**

Thank you very much, 
Regards

**Comment by akula86** [comment]
Thanks for pointing this out. Link updated: https://github.com/SAPDocuments/Tutorials/commit/fe396be2c510d7a1c242fba2e191a4963cd0dfaa
