### ISSUE TITLE
Internet of Things (IoT) made easy: Java Script File Missing

### ISSUE THREAD

**Issue by pritamrc** [SAPDocuments/Tutorials#1805]
Hi
I am unable to download the text file for Java Script aligned to the training (Internet of Things (IoT) made easy)
Can somebody please help me with the file so that i can move forward.

Thanks and Regards
Pritam Roy Chowdhury

**Comment by pritamrc** [comment]
Hi
can someone plz help me.

**Comment by Sygyzmundovych** [comment]
Sorry, to reply just now. This was the tutorial used only on computers during TechEd 2016 conference, where the file was locally available.
To find the code you might want checking https://www.hackster.io/sap-se/weather-station-data-from-tessel-2-via-http-58c3e3
Regards.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
