### ISSUE TITLE
HANA Express Edition - Execute the Installation script and finish setup

### ISSUE THREAD

**Issue by andychoi** [SAPDocuments/Tutorials#1807]
Everything works fine, except chkconfig

I got error like below to install HANA EE 2.0

`Installation of SAP HANA Express Edition System failed.
  Installation of SAP HANA Database failed
    Installation failed
      error installing
        Cannot create system
          installsapinit.sh FAILED
            Starting external program /hana/shared/HXE/global/hdb/saphostagent_setup/installsapinit.sh
              Command line is: /hana/shared/HXE/global/hdb/saphostagent_setup/installsapinit.sh
              Output line 1: /hana/shared/HXE/global/hdb/saphostagent_setup/installsapinit.sh: 206: /hana/shared/HXE/global/hdb/saphostagent_setup/installsapinit.sh: chkconfig: not found
              Program terminated with exit code 5
`

Any workaround? alias chkconfig='sysv-rc-conf' seems like not working.

**Comment by Lsubatin** [comment]
Hi, Andy. what happens if you _sudo alias chkconfig='sysv-rc-conf'_ and then test chkconfig ?

**Comment by andychoi** [comment]
if I test by running "chkconfig", it shows SysV Runlevel Config screen.
/hana/shared/HXE/global/hdb/saphostagent_setup/installsapinit.sh has several chkconfig, and syntax is different from sysv-rc-conf. 
I am not sure if I have to correct installsapinit.sh script.

**Comment by adadouche** [comment]
Hi, I faced this issue and it seems that Ubuntu 16.04  is missing the chkconfig script, and even the alias didn't work for me.
I had to get a version of that script from here: https://uni.edu/~prefect/devel/chkconfig/index.shtml 
then it worked for me.

We should raise that to the team and make sure they adapt the setup script for ubuntu.
@bdel

**Comment by Lsubatin** [comment]
When I had this issue, I repeated the alias as root, ran the chkconfig manually, it shows the initial sysv-rc-conf screen and started the installation again without problems in Ubuntu 16.04LTS. Please note that SPS02 will not work on this installation.
