### ISSUE TITLE
SSLv2_method error during installation on Ubuntu

### ISSUE THREAD

**Issue by andychoi** [SAPDocuments/Tutorials#1808]
SSLv2_method has been removed from OpenSSL libraries, resulting in the 
following fault during installation:

`    Cannot load Net::HTTPS (distcompat): Can't load '/install/HANA_EXPRESS_20/DATA_UNITS/HDB_SERVER_LINUX_X86_64/instruntime/distcompat/SSLeay.so' for module Net::SSLeay: /install/HANA_EXPRESS_20/DATA_UNITS/HDB_SERVER_LINUX_X86_64/instruntime/distcompat/SSLeay.so: undefined symbol: SSLv2_method at DynaLoader.pm line 193.`

Any idea to fix it?

**Comment by andychoi** [comment]
Per https://stackoverflow.com/questions/8206546/ubuntu-and-undefined-symbol-for-sslv2-method

> The Ubuntu people build OpenSSL without SSLv2 support because the protocol has known security issues. So that's why you can't find SSLv2_method in their library even though you can find it when you compile the library yourself.

**Comment by andychoi** [comment]
I did rebuild openssl using this script https://gist.github.com/bmaupin/8caca3a1e8c3c5686141 
But still having the same problem.

**Comment by Lsubatin** [comment]
Hi, Andy. That's what I meant with that this setup won't work for SPS02. We'll be looking into it but cannot provide you with an estimate for resolution.

**Comment by Lsubatin** [comment]
Tutorials with fix for this issue are now updated to:

- Core database (or server-only flavor): https://www.sap.com/developer/tutorials/hxe-gcp-ubuntu-db.html
- Database server + XS Advanced applications: https://www.sap.com/developer/tutorials/hxe-gcp-ubuntu-xsa.html
