### ISSUE TITLE
SAPUI5 - Display List Element Details

### ISSUE THREAD

**Issue by Alexandre-Lara** [SAPDocuments/Tutorials#1810]
Hi guys, 

I'm hear again to take some notes. I guess the line  below has an error:
Open the **webapp/view/View1.controller.js** file, and modify the handleListItemPress event to the Controller.extend method:

Maybe, you may change to this one:

**webapp/controller/View1.controller.js**

Regards,
Alexandre

**Comment by mhassett92** [comment]
Hi Alexandre,

Thank you for bringing this to our attention. I apologize for the delay in getting back to you on this! The file path name has been resolved.

Thank you,
Meredith
