### ISSUE TITLE
SAPUI5 - Setup the DataSource in the local application

### ISSUE THREAD

**Issue by Alexandre-Lara** [SAPDocuments/Tutorials#1811]
Hi guys, whats up ?
I've already told that, but seems good to say again, yours tutorials is awesome !
I think I've found an error at this line:
**/V3/Northwind/Northwind.svc**

When you test the connection, it says: " OData version not supported".  I've corrected this changing
**V3** to **V2**.

Thank You for all,

**Comment by mhassett92** [comment]
Hi Alexandre!

Again, apologies for the delay here. I am not the best at checking issues 😨 . This has been resolved to show that you should still be using V2.

Thanks!
Meredith
