### ISSUE TITLE
Create an ABAP project in Eclipse

### ISSUE THREAD

**Issue by EmiimE** [SAPDocuments/Tutorials#1813]
Hi,
I am going to start learning ABAP, but I faced a problem, When I want to create a new project, after clicking on New ABAP project I need to select a connection , but there is no connection in my list, if I want to create new connection I also need to enter Client number User name an Password bu I dont have these Infos.
Which logon data should be used?
Please advise what should I do in this case.
Best regards,
Iman

**Comment by Lsubatin** [comment]
Hi, Iman, 
You need to get an instance to work with. There are some trial editions that run on cloud platforms, which you can deploy as described here: https://www.sap.com/developer/tutorials/aoh-setup-cal-instance.html 

Cheers,

Lucia

**Comment by EmiimE** [comment]
Thanks a lot for the support!
