### ISSUE TITLE
Change Point Detection ML service with SAPUI5

### ISSUE THREAD

**Issue by yiran-thomas** [SAPDocuments/Tutorials#1817]
Hi Dadouche,

Thanks for your tutorial,there is an error message raised after i run it by your guide.

When i click the button "Execute Service",there is an error message as following:
![issue](https://user-images.githubusercontent.com/18117251/29479392-84bd24be-84a4-11e7-92b1-13a2fd478e5f.png)

Could you please help to hava a look? 
Thank you very much.

Best Regards
Thomas

**Comment by adadouche** [comment]
fixed: https://github.com/SAPDocuments/Tutorials/commit/d2f947517012906b5bb3a0f4af72f32f70deb724
