### ISSUE TITLE
Tutorial: Configuring Eclipse with SAP Cloud Platform Tools for Java

### ISSUE THREAD

**Issue by ulfakerlind** [SAPDocuments/Tutorials#1824]
After downloading package Java Web and unzipping

When selecting the Server Runtime Environment, it does not show under Preferences > Server > SAP.

When adding manually via the search option for the Server Runtime  Environments dialogue:
The name for the server runtime environment shows up as .archive and type: Apache Tomcat 8.5 if using the Java Web Tomcat 8
Or normal Java Web, error message says: no new server runtime environments found

**Comment by thecodester** [comment]
Thank you for your feedback. Because of the amount of time that has elapsed, we are closing the issue.  

If you still have questions, feel free to create a new issue.
