### ISSUE TITLE
Intro to SAP HANA Spatial: Polygons

### ISSUE THREAD

**Issue by kannankumar** [SAPDocuments/Tutorials#1828]
In Step 7 the tutorial mentions: 
_"To check if a point is within a given disk you use the **ST_Boundary()** method to define the circle around an area of a particular distance from a central point."_

whereas the correct method seems to be **ST_Buffer()** as shown in the example just below it.
<img src="https://www.sap.com/developer/tutorials/hana-spatial-intro3-polygon/_jcr_content.github-proxy.file/spatial0308.jpg" />

**Comment by adadouche** [comment]
Hi @kannankumar,

Thanks for raising this to our attention.

Actually, the proper instruction should be:
To check if a point is within a given disk you use the ST_Within() method to define the circle around an area of a particular distance from a central point.

I'll update the description.

Thanks again
