### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by badalpras** [SAPDocuments/Tutorials#1829]
I'm a newbie to linux, please give more details on extracting  hxexsa.tgz  in application folder as sudo is not recognized unless PATH is set

Thanks
Prasad Badal

**Comment by Lsubatin** [comment]
Hi, Prasad. I need more specifics. What are you trying to do? Can you take a screenshot of the error?

**Comment by badalpras** [comment]
Lucia :never mind i was able to install the VM hxexsa and dont need to install the applications separately
 thanks
Prasad Badal

**Comment by Lsubatin** [comment]
Great. Have a good one!
