### ISSUE TITLE
Send the CPU usage data to SAP IoT Application Enablement

### ISSUE THREAD

**Issue by soypalmo** [SAPDocuments/Tutorials#1830]
Hi,
Under section "Send the CPU usage data to SAP IoT Application Enablement", step 2, the script has an id that represents the message type. Where can I get that message type from?
Thanks,
Leonardo.

**Comment by Sygyzmundovych** [comment]
Hi Leonardo. Sorry for delay replying. The only variables you needed to update were device-id and its auth token. It was mentioned in the step 3. I updated a tutorial to hopefully make it more clear. Regards. -Vitaliy
