### ISSUE TITLE
HANA Express Edition - Install Dependencies for Ubuntu on Google Cloud Platform

### ISSUE THREAD

**Issue by entmike** [SAPDocuments/Tutorials#1831]
I know that the doc currently says 'Update for HANA 2.0 SPS02 pending', but maybe someone can help.

The install fails with the following message:

![image](https://user-images.githubusercontent.com/174348/29690242-c93a4022-88eb-11e7-99fe-394e184801fb.png)

I tried re-compiling openssl, which in Ubuntu, doesn't have sslv2 enabled.  It appeared to recompile just fine however I still get this error, so perhaps I'm barking up the wrong tree, or I simply don't know what I'm doing.

Any help would be.... helpful.  Thanks!

**Comment by Lsubatin** [comment]
Hi, Mike, that error is exactly why the update is pending. I will let you know once we have an answer, HXE team is working on that.

**Comment by entmike** [comment]
Awesome, thanks.  And thanks for the 'unofficial' support for installing on Ubuntu!  This lowers the cost of running something without worrying over SLES costs for sandboxes.  My tinkering is all by myself and don't want to pay for cloud or SLES to play around.  HXE and Ubuntu is great for this!

**Comment by Lsubatin** [comment]
While that gets fixed, have you tried this? https://blogs.sap.com/2017/05/22/setting-up-your-free-sap-hana-express-edition-on-ms-azure-on-opensuse/ 

Requires less dependencies and sounds like opensuse may also be a fit

**Comment by entmike** [comment]
You are right... Not sure why I didn't think about opensuse.  That's actually where I'm running a NW 7.5 mini system anyway.  Good point!  Thanks for the suggestion, I'll try this, if I can manage to reserve enough RAM during the installation period.  (My hypervisor host has 32GB total only.)  I can manage to run HXE+Apps in 12GB from the .OVA template, however installation seems to need quite a bit more prior to optimization.

**Comment by entmike** [comment]
Just to report back, I was able to install this successfully using opensuse without any hassle at all.  Thanks for pointing me to an easier solution.  I am up and running without needing SLES now.  Thank you!

**Comment by Lsubatin** [comment]
That's great news, Mike! Thanks a lot for the update.

**Comment by michelde** [comment]
@Lsubatin : Have you heard something about the fix for ssl or will there be a fix at any time?

**Comment by Lsubatin** [comment]
@michelde perfect timing, I released this today:  https://goo.gl/AM1u8o
