### ISSUE TITLE
Add API Business Hub API to a UI5 Application

### ISSUE THREAD

**Issue by AndreasMuno** [SAPDocuments/Tutorials#1832]
Hi Meredith and Jim, maybe it was just me, but in step 3, "Use the API in your application" I stumbled over  two code error messages after inserting the API code, 
- for line > console.log(this.responseText); // I got error ESLint(no-console)  
- for line >  xhr.open("GET", <URL>) // I got ESLint(sap-no hardcoded-url).
Once I entered a comment line using "/* ... */" above each of these errors, the code error messages went away. 
Maybe you'd like to mention that when you re-edit tutorial. 
Thank you.

**Comment by mhassett92** [comment]
Hi Andreas,
These are Fiori warnings for violated Fiori Best Practices. They are not functional error. For training purposes, you can ignore them, but when developing production applications with UI5, it is best to follow Fiori best practices. 

To resolve these:
For the first one, you can remove the console statement as it is just for debugging purposes to help you understand the data.
For the second one, you can make the URL a destination in you SAP Cloud Platform and change the url to the destination by updating your manifest file and replacing the url with the destination path specified.

Again these are best practices issues, so your code should run just fine without making the modifications.

Let me know if you have additional questions or concerns.

Thanks!
Meredith
