### ISSUE TITLE
The turorial does not work with hana_trial account

### ISSUE THREAD

**Issue by ehwg** [SAPDocuments/Tutorials#184]
Hi, when I try this on my hanatrial account only with 
@Schema: 'd022276'
I can create a table. otherwise I get the error:

Error while activating /d022276trial/d022276/tutorial/first_table.hdbdd:
[d022276trial.d022276.tutorial:first_table.hdbdd] Could not generate CDS artifact "d022276trial.d022276.tutorial::first_table.Book" to schema "d022276" because index server configuration switch "view_activation_for_hcp" is set. In this mode only generation to schema "_SYS_BIC" is allowed.

Hence I change it to  @Schema: 'd022276'.
When I try now to import data I get the error:

Error while activating /d022276trial/d022276/tutorial/mydata_import.hdbti:
[d022276trial.d022276.tutorial:mydata_import.hdbti] Schema could not be resolved for public synonym. Check that the target table exists.

Is there a tutorial available on how to do this on hanatrial. 
Best regards
Eckard.

**Comment by ehwg** [comment]
More issues. I continue without adding data to the table but when trying to add roles I now get the issue:
[12:24:10] Missing privileges for Uri: /sap/hana/xs/dt/base/OData/CatalogAndRepositoryRoles.xsodata/CatalogAndRepositoryRoles?$top=1000&$orderby=length(NAME)%20asc&$filter=MODE%20eq%20%27DT%27

**Comment by ccmehil** [comment]
Did you create a HANA MDC or a HANA XS Shared instance?

**Comment by ehwg** [comment]
Hi Craig,

That bug was with the HANA xs version. The issue was with the different schemas.

Best regards
Eckard.
