### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by pasedlar** [SAPDocuments/Tutorials#1844]
I am confused on step 16 (Step 16: Optional Configuration: Install SAP Enterprise Architecture Designer (Server + Applications Virtual Machine Only)).  I located the eadesigner.tgz on my laptop, but I can't figure out how to get the file to my Virtual Machine directory.  Also, the command seems to be missing a step??  If I can somehow get the file to my Virtual Machine, it seems that I need to extract it.  How and where do I do this?

It is frustrating...  the steps up to step 16 are very detail, and with screen shots.  Step 16 seems to assume the user knows everything.  I need more detail please.

**Comment by jaysid95** [comment]
You should login as the hxeadm OS user and then download/sftp the files from your laptop. Extract the files and navigate into the HANA_EXPRESS_20 folder and you will find an installer file with the extension ***.sh. Run it and that will install ea designer.

**Comment by JCurrie27** [comment]
We've expanded and simplified the EA designer installation instructions. The procedure now shows you how to download the EA Designer installer from inside the VM, using the built-in (command line) download manager utility. Hope this helps.
