### ISSUE TITLE
SAP HANA, express edition, in Google Cloud Platform Launcher

### ISSUE THREAD

**Issue by joej** [SAPDocuments/Tutorials#1845]
I'm getting a bit peeved. Short version: Really? you don't bundle the client tools, which appear to be needed. And, you don't make it VERY easy to find these darned tools.

This is ridiculous: fix your "tutorial" and stop making the client tools nearly impossible to download to a cloud instance

* Your google cloud VM image does *not* include the client. 
* These instructions suggests, somehow, magically, the client software will be in my local PC's "downloads" folder ... but provide *no* instruction how to get to a download page to actually make that happen.
* Youtube videos with outdated download links; find community forums (with outdated download links).
* SAP Store will send a link (48 hours) to download the client archives ... but no command-line, linux client -- on SUSE linux -- can download any of the links. Yes, its authentication + cookies, so a browser is needed.  Yet another hurdle for a command-line VM instance/tutorial.

**Comment by joej** [comment]
Wow -- SUSE linux. Nope.

I think its time to delete this gcloud VM and manually install the SAP HANA Express into an n1-highmem ubuntu instance. 

I managed to download the client package from the sap store, then wait for the long upload to gcloud VM. I've unziped the already-compressed tar.gz archive. But, again: little to no docs.

**Comment by Lsubatin** [comment]
Hi, Joe Judge, 

Step 5 of said tutorial says you will find the client packages in the Downloads folder and specifies the two commands to get to them. There is then a screenshot of the files in the virtual machine. As you say, htey cannot be magically in your computer. They are on the virtual machine.

Maybe I can help if you tell me what you need the clients for.  That step is optional.  

A word of warning, unfortunately the Ubuntu version will not work with SPS02). The current only alternative that is documented for a free OS is: https://blogs.sap.com/2017/05/22/setting-up-your-free-sap-hana-express-edition-on-ms-azure-on-opensuse/
