### ISSUE TITLE
Onboarding a computer as the IoT thing

### ISSUE THREAD

**Issue by cgeronasso** [SAPDocuments/Tutorials#1847]
Hi, the link you provided https://sap-iotaeexplore.iot-sap.cfapps.eu10.hana.ondemand.com/launchpage/#Shell-home
is not working, there is another one?

Tks!

**Comment by Sygyzmundovych** [comment]
This link was available only to participants of SAP Leonardo event plus some SAP colleagues. We are working on another one to make available publicly. Please stay tuned. Regards. -Vitaliy
