### ISSUE TITLE
Installing SAP HANA 2.0, express edition (Binary Installer Method)

### ISSUE THREAD

**Issue by elikane** [SAPDocuments/Tutorials#1852]
I have logged in, but nowhere is there a link tot he download manager.  The instructions just show an image of the links - I cannot seem to locate the link anywhere else on the site.

Please let me know where to obtain the download manager for Linux..

Thanks,

Eli

**Comment by jaysid95** [comment]
After you register, you will see a link to the Download Manager.

![capture](https://user-images.githubusercontent.com/5432247/30392132-b9275b2c-9870-11e7-8f77-72431f38d43d.PNG)
