### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Binary Installer Method)

### ISSUE THREAD

**Issue by entmike** [SAPDocuments/Tutorials#1854]
SDI is now available, and while I got it working with some guesswork, a guide on installing SDI and configuring the DP Agent would be helpful for others, I think.

Thanks!

**Comment by JCurrie27** [comment]
Thanks for your feedback. SDI installation and configuration steps will be available in an upcoming revision of the "Start Using SAP HANA 2.0, express edition (Binary Installer Method) tutorial".

In the meantime, the SDI information is present in the PDF you can access via download manager, and also in online format on the SAP Help Portal at: https://help.sap.com/viewer/32c9e0c8afba4c87814e61d6a1141280/2.0.02/en-US/a347f9eb3fc444faa56b5caee9e9c010.html
