### ISSUE TITLE
Create an application definition

### ISSUE THREAD

**Issue by tran1013** [SAPDocuments/Tutorials#1855]
Hi,

I'm a working student at SAP and currently I'm using for my first time the SAP iOS SDK and I would like to mention a little mistake.

On the "Create an application definition" page step 3, the application id in the table should be "com.sap.tutorial.demoapp.Demo" and not "com.sap.tutorial.demoapp". At least I wasn't able to login with my credentials if the ".Demo" is missing.

Best regards,

Duc

**Comment by thecodester** [comment]
Thank you for your feedback. Because of the amount of time that has elapsed, we are closing the issue.  

If you still have questions, feel free to create a new issue.
