### ISSUE TITLE
SAPUI5 User Interface

### ISSUE THREAD

**Issue by spencef1** [SAPDocuments/Tutorials#1856]
Hello,
Great tutorials, I really like the new format.
I would like to point out a small code issue here:
},{
 "source" : "/(.*)",
 "localDir" : "resources",
 "authenticationType" : "xsuaa",
 "replace" : {
   "pathSuffixes" : ["index.html", "odataTest.html"],
   "vars" : ["ui5liburl"]
   }
} <-- this one is missing.
Thanks!

**Comment by Lsubatin** [comment]
Thank you very much for your feedback! In which tutorial are you seeing this?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
