### ISSUE TITLE
Installing SAP HANA 2.0, express edition (Binary Installer Method)

### ISSUE THREAD

**Issue by spencef1** [SAPDocuments/Tutorials#1857]
Hello,
Great tutorial!
I just wanted to point out that I had to install libtool as part of the dependencies.
I installed it using SUSE linux default build on AWS Ireland.
sudo zypper install libtool
It might be useful for someone using the same AWS build/image (suse sles12-sp2)
Best regards

**Comment by Lsubatin** [comment]
Hi! thanks for the feedback. Just in case, you are using the binary installer for SPS02, correct?

Cheers,

Lucía.

**Comment by spencef1** [comment]
Hi Lucía,
Thanks for your message. Yes, I'm using binary installer for SPS02.
It would be also good to mention in the tutorial that the host must be able to resolve its FQDN as a pre-requisite as well. The installation failed because of that as well.
Cheers,
Felipe

**Comment by JCurrie27** [comment]
Thanks for your feedback. We are improving the tutorials and will take your comments into consideration when updating this installation tutorial.
