### ISSUE TITLE
SAP HANA XS Advanced, Creating an OData Service with Create Operation and XSJS Exit

### ISSUE THREAD

**Issue by kgorin8** [SAPDocuments/Tutorials#1859]
Hello.

The tutorial would benefit to have a section explainig how "param" object get created from ODATA requests.

Otherwise good job.

Best regard,
K

**Comment by Lsubatin** [comment]
Hi, Kirill,

Thank you very much for the feedback. I'll add a reference to how this is consumed in this tutorial: https://www.sap.com/developer/tutorials/xsa-sapui5-consume.html 

Good point.

Best,

Lucía.
