### ISSUE TITLE
SAPUI5 - Enable Routing

### ISSUE THREAD

**Issue by mkaufmann66** [SAPDocuments/Tutorials#1867]
I tried this step several times but it does not work. At step 8 the system does not recognize "View1" (it is not in the dropdown also it exists under folder Views ) . Even adding the view name in the code editor does not suceed. It seems manifest.json does not "see" the view at all.

Regards,
Michael

**Comment by mhassett92** [comment]
Hi Michael,

Did you changed the namespace of the app when creating? This would mean that your manifest file is looking in the incorrect area when trying to find the view. Do you mind sharing your namespace?

Thank you!
Meredith

**Comment by mkaufmann66** [comment]
Hi Meredith,

unfortunately I "lost" my developments as I did this on the SCP of my former employee. As I changed job I do not have access any longer. 
Will go for a trial account and do the tutorial from scratch again.
Thanks for replying anyway !

Regards,
Michael
