### ISSUE TITLE
Build an app from an SAP Web IDE template

### ISSUE THREAD

**Issue by gpetrich** [SAPDocuments/Tutorials#1870]
Step 11: Testing the connection

The test returns "OData version 3 is not supported."

![image](https://user-images.githubusercontent.com/22320503/30852496-3bb6d94c-a2ac-11e7-9443-cbe0a6f73fbd.png)

**Comment by gpetrich** [comment]
Fixed.

The correct Path is "/V2/...", different from the one in the tutorial screen shot :(

**Comment by mhassett92** [comment]
The screenshots were out of date on this tutorial; however the code snippet provided had the correct version. I have updated the tutorial screenshots to reflect the correct version to prevent further confusion.

Thanks!
