### ISSUE TITLE
Getting Started with SAP Cloud Platform Rapid Application Development by Mendix

### ISSUE THREAD

**Issue by jandevriesmendix** [SAPDocuments/Tutorials#1873]
https://www.sap.com/developer/tutorials/mendix-onboarding.html
At step 6 it says "business modeler". This is the wrong term. It's either "Mendix Desktop Modeler" or just "Desktop Modeler".

**Comment by thecodester** [comment]
Thanks for the comment. The term "business modeler" is being used by SAP as part of the SAP Cloud Platform Rapid Application Development by Mendix solution.
