### ISSUE TITLE
Topic Detection ML service with SAPUI5

### ISSUE THREAD

**Issue by deepanigi** [SAPDocuments/Tutorials#1874]
You have written an interesting article on SAPUI5 with machine learning.I am facing the issue with the same.

[https://www.sap.com/developer/tutorials/ml-fs-sapui5-topic-detection.html]

I have followed the same steps as you have mentioned.I am using the attached txt file /zip of this text file for uploading.

I get this error in console 
![error](https://user-images.githubusercontent.com/31543067/30959805-8a36cc30-a441-11e7-941e-5a71012a2b26.JPG)

Error on screen 
`Error 400 : {
"_id": "2275d8b0-d719-4264-8da6-44a923e03557", 
"error": "Invalid request", 
"error_description": "At least 1 missing parameter in \"option\" field : ['numTopics', 'numTopicsPerDoc', 'numKeywordsPerTopic']", 
"processed_time": "Thu, 28 Sep 2017 09:39:28 GMT", 
"request": {
"files": null, 
"options": {}, 
"tenantName": "imgclassif-tech-user", 
"texts": []
}, 
"status": "FAILED", 
"status_code": 400, 
"tenantName": "imgclassif-tech-user"
}`

![error2](https://user-images.githubusercontent.com/31543067/30959905-cfe2dc92-a441-11e7-8f1c-f00ed368f54d.JPG)

What might be the issue

[topics_ml.txt](https://github.com/SAPDocuments/Tutorials/files/1340270/topics_ml.txt)

**Comment by deepanigi** [comment]
I tried again to follow this time attached is my zip used to attach.But i am getting status code 500 error as mentioned below.

```
Error 500 : {
"_id": "9e4ae786-4a0b-4d42-9e8b-66f75b4cfebc", 
"error": "An internal error occurred", 
"error_description": "", 
"processed_time": "Thu, 28 Sep 2017 10:14:55 GMT", 
"request": {
"files": [
"Ml.zip"
], 
"options": {
"numFeatures": 23, 
"numKeywordsPerTopic": 12, 
"numTopics": 2, 
"numTopicsPerDoc": 3
}, 
"tenantName": "imgclassif-tech-user", 
"texts": []
}, 
"status": "FAILED", 
"status_code": 500, 
"tenantName": "imgclassif-tech-user"
}
```
![error3](https://user-images.githubusercontent.com/31543067/30961599-fcc1e78a-a446-11e7-9f3d-18116818d100.JPG)

[Ml.zip](https://github.com/SAPDocuments/Tutorials/files/1340455/Ml.zip)

**Comment by adadouche** [comment]
Hi,

I think I understand your issue.

You can only extract 1 topic when you pass 2 input files. In your screenshot you are using 2 as the number of topic to be detected, which means that you need at least 3 input files.


If you

**Comment by adadouche** [comment]
I have also update the content with the solution code.

**Comment by adadouche** [comment]
closing the issue.
