### ISSUE TITLE
S/4HANA ABAP Extensibility -  - Creating the UI for a Custom Business Object (Bonus Plan)

### ISSUE THREAD

**Issue by voicedmendor** [SAPDocuments/Tutorials#1876]
Hi

I see the below in my system.
![image](https://user-images.githubusercontent.com/7389692/31188687-5800cfb8-a8fb-11e7-82da-a9b6b269312e.png)

I don't see the UI Generation option as shown below.

![image](https://user-images.githubusercontent.com/7389692/31188704-6a82899c-a8fb-11e7-9182-97dc519a0815.png)

https://www.sap.com/developer/tutorials/abap-extensibility-cbo-ui-generation.html

Thanks.

**Comment by Liebherr** [comment]
Hi voicedmendor,
is your system an on premise system?
The mentioned tutorial is valid for cloud systems only. In on premise you have to build the UI on your own, i assume that's why you even see some more technical information for the service.
Regards
Ulrike
