### ISSUE TITLE
Step 2: Enable SAP Web IDE and Service: SAP Web IDE - Overview

### ISSUE THREAD

**Issue by jonasohana** [SAPDocuments/Tutorials#1879]
Created new SAP Cloud account. 
Step 2 Enable SAP Web IDE - 
  Expected result to see 'Enabled' or 'Not Enabled'
  Actual result 'Enabled' or 'Not Enabled' not displayed on any services listed

Step 3 Service: SAP Web IDE
  Expected result to see 'Open SAP Web IDE' link next to 'Documentation' link 
  Actual result only 'Documentation' link displayed

Note: only Services listed on left nav

**Comment by mhassett92** [comment]
Hello,

Are you using the Trial version of the SAP Cloud Platform? If not, has your company purchased the Web IDE services as part of their SAP Cloud Platform?

Thanks!
Meredith

**Comment by jonasohana** [comment]
Trail version 
Paul


Sent from Yahoo Mail for iPhone


On Sunday, November 5, 2017, 1:03 AM, Meredith Hassett <notifications@github.com> wrote:


Hello,

Are you using the Trial version of the SAP Cloud Platform? If not, has your company purchased the Web IDE services as part of their SAP Cloud Platform?

Thanks!
Meredith

**Comment by mhassett92** [comment]
Can you send a screenshot of what the SAP Cloud Platform and Services page looks like for you?

**Comment by mhassett92** [comment]
There is a chance you were looking at the services catalog. To be able to use the services, you must go into the Trial account. To do this, select Regions > Neo Trial > Services.

I am going to close this issue. If this does not resolve your issue, feel free to re-open this ticket with additional information, including screenshots.

Thank you!
Meredith
