### ISSUE TITLE
AngularJS - Boostrap Forms

### ISSUE THREAD

**Issue by kgorin8** [SAPDocuments/Tutorials#1880]
Link to next tutorial points to /tutorials.html

**Comment by jonathanbaker7** [comment]
@akula86 - this came during a major links modification last spring.  Do you want me to revert this and put it back?

https://github.com/SAPDocuments/Tutorials/commit/e56b84f9d82ebe47d8338b3644817cdbbc1553a5#diff-c02712824dde678effbe0c2cb246c6d1

**Comment by thecodester** [comment]
Fixed link https://github.com/SAPDocuments/Tutorials/commit/17a9f3ff56b35911f56623cb4250a667fd03bbed
