### ISSUE TITLE
CI Best Practices Guide: SAPUI5/SAP Fiori on ABAP Front-End Server

### ISSUE THREAD

**Issue by TheGreenToaster** [SAPDocuments/Tutorials#1961]
This is great stuff! Thanks for the tutorial! 

Has there been any thought around writing this as a grunt task in the grunt-openui5 repo?
I was able to take this code and tweek it a bit to get the bit so that the build client spun up a connect server to serve the zip file to the frontend server.

The main hurtle I can think of is saving a password in the config would probably not be ideal.

Thanks again!

**Comment by TheGreenToaster** [comment]
@wolframK :)

**Comment by wolframK** [comment]
Thank you very much for your feedback.
Personanally, I think it is a good idea to bring this to the grunt-openui5 repo, but I have to delegate the decision to the responsible people.
@matz3 @RandomByte
What do you think?

@TheGreenToaster

**Comment by TheGreenToaster** [comment]
@wolframK I laid it out [here](https://github.com/TheGreenToaster/grunt-openui5). Would be very interested in your feedback :)

**Comment by wolframK** [comment]
Hi @TheGreenToaster

could you please open a pull request for your change. We will then dicuss this internally.

Thanks,
Wolfram

**Comment by RandomByte** [comment]
As discussed [here](https://github.com/SAP/grunt-openui5/pull/63), it looks like the ABAP upload process is being reworked at the moment. An easier interface is planned and with that probably a new grunt task.

We will therefore not add this soon-to-be-deprecated task to one of our repositories.
