### ISSUE TITLE
Machine Learning services for images

### ISSUE THREAD

**Issue by pavanmulpur** [SAPDocuments/Tutorials#1963]
Hi Akula, Adadouche,

I've completed this tutorial on "Machine Learning services for images" from the link https://www.sap.com/developer/tutorials/ml-fs-api-hub-image.html. 
While I appreciate that you have clearly stated what the student will learn under the section "YOU will learn." 
_**You will learn
In this tutorial, you will learn where to find and test the SAP Leonardo Machine Learning Functional Services published on the SAP API Business Hub that consumes images content.**_

It would be great if you can also state what is the purpose of finding and testing the SAP Leonardo Learning Functional Services. What happens after I select the image? I am not clear as to why I have done this tutorial. It would be nice to post two more sections saying " At the end of this tutorial you should have learnt how to ...." 
Section 2 - The purpose of this tutorial is .....

Thank you.

Regards,

Pavan.

**Comment by adadouche** [comment]
Hi @pavanmulpur,

I have recently added some content while executing the tutorial.

The "you will learn" section of a tutorial is used to briefly explain "what" you will achieve in the tutorial not the "why".  
A "tutorial group" may define a larger goal and gives you somehow the "why", but not necessarily.

The "why", or the "purpose" as you call it, is more something you will find in a blog, not in a tutorial.
The tutorial is here to explain you how to implement a feature or a series of features.

For this example, the description states:
**Discover the SAP Leonardo Machine Learning Functional Service consuming images content on the SAP API Business Hub**

I have the same in SAPUI5 or Java, which explains how to implement the service, not why as these services could be used by service agent looking for a product reference or a machine to identify the bucket an item should be stored in.

Thanks
