### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by murmelsson** [SAPDocuments/Tutorials#1964]
Hello,

if someone wants to change their keyboard, then they have to do so as root. But the root password is not specified, so Step 7 is impossible.

Unless you use the trickery of e.g. sudo -u root /bin/bash to get a shell as the root user. But not everyone finds out such magic spells, so it would be good to explain to the Tutorial-users.

**Comment by tai-le** [comment]
"hxeadm" user in the VM has sudo permission.  You can run all root commands via "sudo <command>".

**Comment by murmelsson** [comment]
aha... looks like i just forgot whatever password I had specified for user=hxeadm. Oops, sorry about that. I'll close this issue.
