### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by DannyCosta1** [SAPDocuments/Tutorials#1967]
I have downloaded and imported the HANA Server + Applications VM in VMWare Workstations 12.
I am just starting the HANA + Applications VM and typing in hxeadm, password is supposed to be HXEHana1.
I can guarantee that is not the password.  I have typed it in so many times I know it isn't my bad keyboard skills!
Can you let me know what the correct password is, and update the web page too so others can continue with the training?

**Comment by Lsubatin** [comment]
Hi, Danny, 

The password is:

HXEHana1

There is no final dot. The keyboard, however, has a default English layout that may not be the same as yours. Have you tried typing the password instead of the username so that it is visible and you can make sure that _HXEHana1_ is actually being typed in?

Cheers,

Lucia.

**Comment by DannyCosta1** [comment]
Thanks for your reply Lucia.

I am not typing the password with a dot, and yes I have double and tripled checked that my typing isn’t bad.  I can certainly guarantee that the password isn’t HXEHana1

The password worked for the Server only VM.  It’s only the password in the Server + Applications VM which is not accepting HXEHana1

 

 

Danny

**Comment by Lsubatin** [comment]
Hi, Danny, 
Unless you have changed it, the password for the hxexsa.ova VM is still HXEHana1

I'm talking about this:

![image](https://user-images.githubusercontent.com/24896969/31721493-e7cf6222-b3ef-11e7-802f-dae3924dffc0.png)

Have you tried importing a fresh image?

**Comment by tai-le** [comment]
Danny,

The VM has US English keyboard layout.  If have different keyboard, what you type on the VM (VM console on hypervisor) and on other applications can be different.  In this situation, I suggest you use SSH client (like PuTTY) to login to the VM.  Boot up the VM, wait and press enter until you see the VM IP address.  Login to this IP via SSH client.

-Tai

**Comment by Lsubatin** [comment]
Timeout on this one. Some instructions have been incorporated in the VM tutorials to instruct on changing keyboard layouts.
