### ISSUE TITLE
Getting Started with SAP Cloud Platform Rapid Application Development by Mendix

### ISSUE THREAD

**Issue by peter42csontos** [SAPDocuments/Tutorials#1969]
Dear Colleagues,

Regarding the last sentence in the document: "You build apps using the business modeler, which is an application installed on your desktop. If you don’t have the modeler, install it by going to the app store." - When I go to the Mendix app store and start downloading, I realize it is a Windows .exe file. It would've been much nicer to learn that macOS is not supported much earlier, saving the whole hassle of going through all previous points.

Thanks and best regards,
Peter Csontos
SAP

**Comment by thecodester** [comment]
I have added a note at the start of the tutorial and in the prerequisites section. Should be visible by end of the week.
