### ISSUE TITLE
Root password on GCP for Hana Xs advanced

### ISSUE THREAD

**Issue by ahmedkhan29789** [SAPDocuments/Tutorials#1970]
Hello guys,
I got stuck on 2 points after installing GCP successfully
1. I don't have my root password, i have my master password but it's not working as root password.
2. While creating a project , i am not getting the option for creating node.js file, Also on building my project after .hdi its failing with npm error.

**Comment by Lsubatin** [comment]
Hi again, Ahmed,

 As I said on LinkedIn, the GCP VMs do not have a root password. You should not be using root but sudo instead. hxeadm is not a sudoer so start a fresh SSH console with your Google ID and that user can do sudo. If you still want to become root, from your Google ID you can do sudo su -.  I also repeat that this access should not be needed for the tutorial series you are doing.

As for the second questions, please elaborate on the errors in the Q&A: https://answers.sap.com/index.html

**Comment by ahmedkhan29789** [comment]
Hi Lucia,

Thanks for the clarification but i am getting npm error when trying to
build my db folder, Also in my web IDE , I am not getting option to create
a node.js module.

So i was trying to install node.js into my cloud system and then it was
asking for root password.

**Comment by ahmedkhan29789** [comment]
All the error I am getting because of my order sequence file, Looking deeply I found there must be some syntax issue which  was not able to capture, Please see screenshot to exactly understand the error of namespace in .hdbsequence file.
![image](https://user-images.githubusercontent.com/22063881/31729896-0315149c-b44e-11e7-9785-a303cc3ec8b8.png)
