### ISSUE TITLE
Test the "Dataset" service

### ISSUE THREAD

**Issue by beaunicolas** [SAPDocuments/Tutorials#1986]
Hello,

There is an error on the url for Step 3, registration details for a variable : _C4PAURL/api/analytics/dataset/ID/variables/1_  The request works with _C4PAURL/api/analytics/dataset/ID/variable/1_ without the "s" 

Thanks a lot for this tutorial !

Nicolas

**Comment by adadouche** [comment]
Fix and now should now be live.
