### ISSUE TITLE
Connect to GitHub and create an MTA application

### ISSUE THREAD

**Issue by yramamurthy** [SAPDocuments/Tutorials#1998]
Your validation logic seem to have problem. following content doesnt seem to get validated at all!!

ID: teched2017
_schema-version: '2.0'
version: 0.0.1

**Comment by Lsubatin** [comment]
The server was taken down outside TechEd hours which would explain that. If you were at TechEd you could get a scan by any of the experts (hopefully, you did). That content is correct.
