### ISSUE TITLE
Creating an app using the SAP Cloud Platform SDK for iOS Assistant

### ISSUE THREAD

**Issue by SudarshanRaju** [SAPDocuments/Tutorials#1999]
I have tried creating project using IOS Assistant. Go the below error..

<img width="508" alt="screen shot 2017-10-28 at 3 10 33 pm" src="https://user-images.githubusercontent.com/33187056/32138981-5e6fd056-bbf2-11e7-8a1f-5590a0e43e6e.png">

**Comment by qualiture** [comment]
Hi @SudarshanRaju,

This is strange... Are you creating an app with the tutorial's `com.sap.edm.sampleservice` OData service, or are you using a different endpoint?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
