### ISSUE TITLE
Create a Database Module

### ISSUE THREAD

**Issue by boloramji** [SAPDocuments/Tutorials#2000]
Question: After the last Step, where you get BuildDB successful, should we not get the data filled with two rows of ID and TEXT? I see as No Data in the bottom window. I would have expected to see those three rows added to the APPROVAL_STATUS  table. Can you please add a screenshot how your screen look like? or please add a step  to navigate to show the table data?

**Comment by Lsubatin** [comment]
Hi! That is covered in the next step in that mission: https://www.sap.com/developer/tutorials/xsa-e2e-db-explorer.html
