### ISSUE TITLE
Creating a project in SAP Web IDE and importing it into GitHub

### ISSUE THREAD

**Issue by lancecm** [SAPDocuments/Tutorials#2001]
Hi,
When I was importing the local project to the GitHub, it told me

> "Push request failed"
> Details: https://github.com/lancecm/SAPUI5.git: 302 Found

I was wondering why it showed this message.
My authentication information is correct.

**Comment by mhassett92** [comment]
Hi,

Were you able to successfully pull into Web IDE? ie. do you have the README.md file in your Web IDE project folder?

Thanks!
Meredith

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
