### ISSUE TITLE
Worst practices?

### ISSUE THREAD

**Issue by AntoniBertel** [SAPDocuments/Tutorials#2007]
Hi guys,

Why did you call folder with sources as 'test_modules' and pushed 'node_modules' into the repository?
I'm a big fan of SAP tutorials, but this is not good ...

**Comment by thecodester** [comment]
Fixed with https://github.com/SAPDocuments/Tutorials/pull/2008

**Comment by AntoniBertel** [comment]
@thecodester, looks much better. Thanks.
