### ISSUE TITLE
SAP Cloud Platform IoT for Neo: Sending messages from TI SensorTag device

### ISSUE THREAD

**Issue by BjoernKorioth** [SAPDocuments/Tutorials#2012]
Hi,

when I try running the node.js, I get the following error:

> module.js:544
>     throw err;
>     ^
> 
> Error: Cannot find module 'sensortag'
>     at Function.Module._resolveFilename (module.js:542:15)
>     at Function.Module._load (module.js:472:25)
>     at Module.require (module.js:585:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\dev\IoT_dev\IoT_test\WebContent\readTags.js:8:17)
>     at Module._compile (module.js:641:30)
>     at Object.Module._extensions..js (module.js:652:10)
>     at Module.load (module.js:560:32)
>     at tryModuleLoad (module.js:503:12)
>     at Function.Module._load (module.js:495:3)

I think it is still necessary to get additional libraries for the sensor tag, right?

Cheers
Björn

**Comment by ccmehil** [comment]
Sorry about that, for some reason the "pre-req" is not linked:

[https://www.sap.com/developer/how-tos/2016/09/iot-tisensortag.html](https://www.sap.com/developer/how-tos/2016/09/iot-tisensortag.html
)
