### ISSUE TITLE
End-to-End Weather App Scenario Part 7

### ISSUE THREAD

**Issue by Scot2806** [SAPDocuments/Tutorials#2013]
Hello,
@akula86

I managed to follow the tutorial till step 7. But here I'm locked on the following messages
- The type List is not generic; it cannot be parameterized with arguments <FavoriteCity>
- "the method getentitymanagerfactory() is undefined for the type entitymanager"

I manage to solve the first one replacing
import com.sun.xml.bind.v2.schemagen.xmlschema.List;
by 
import java.util.List;

But if you have an hint to solve the second one, it would be approciated
Thanks
Stephane

**Comment by thecodester** [comment]
These tutorials will be retired, and replaced with new ones, hopefully for SAP TechEd.
