### ISSUE TITLE
Mobile Project generation failed: Creating an app using the SAP Cloud Platform SDK for iOS Assistant

### ISSUE THREAD

**Issue by bnotions-fahad** [SAPDocuments/Tutorials#2014]
At the step with regard to creating the iOS project it fails and states "Unable to download metadata for connection: com.sap.edm.sampleservice. Please select the metadata from your file system."

**Comment by bnotions-fahad** [comment]
Fixed by deleting sample application I setup through tutorials in portal and used assistant to generate sample application.

**Comment by thecodester** [comment]
Marking as closed.

**Comment by qualiture** [comment]
Hi @bnotions-fahad,

Sometimes this 'error' occurs if the SDK Assistant is not able to retrieve the metadata from the OData service directly. For future reference, and in the rare cases this happens (http request timed out for instance) you could also download the metadata, store it locally and upload it to the assistant:

1. In Safari, browse to the URL for your service, and append `/$metadata` to the end, for instance `http://services.odata.org/V2/Northwind/Northwind.svc/$metadata`
2. From the menu, select **File > Save as...** and save the file locally with format **Page Source**
3. In the SDK Assistant where the pop up says "_Unable to download metadata for connection: <your service>. Please select the metadata from your file system._" upload the just saved file. The project should then be generated successfully.
