### ISSUE TITLE
SAP Cloud Platform IoT for Neo: Configuring the device for environmental sensors data

### ISSUE THREAD

**Issue by 20piyushjain** [SAPDocuments/Tutorials#2015]
Getting 400 message in step 6 "The message doesn't conform to the given message type".

**Comment by Sygyzmundovych** [comment]
Check for typos in message type and in the message you are trying to post.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
