### ISSUE TITLE
ABC Analysis with SAP HANA PAL

### ISSUE THREAD

**Issue by evsorochinsky** [SAPDocuments/Tutorials#2022]
Hello.
There is error at step 7:
> java.sql.SQLWarning: wrong number or types of parameters in call: Column mismatch happened at "TUTORIAL_PREDICTIVE.PAL_ABC_CALCULATE": Declared type "NVARCHAR(80)"  of attribute "SOMEOBJECT" not same as assigned type "NVARCHAR(11)"

**Comment by adadouche** [comment]
Hi @evsorochinsky 

I have tried to reproduce the problem using the SAP Cloud Platform HANA MDC instance (Version1.00.122.08.1490178281) without success.

Which environment are you using?

I have updated step 5 and now the V_ABC_INPUT definition for the "SOMEOBJECT" field is casted into a NVARCHAR(80) (as it was by default casted as NVARCHAR(11) by SAP HANA).


Hope this helps.

Thanks

**Comment by adadouche** [comment]
Hi @evsorochinsky,

Any feedback? If not I'll close this issue in 7 days.

Thanks

@bdel

**Comment by adadouche** [comment]
no response, so I close the issue
