### ISSUE TITLE
Consume the API Proxy in SAP Web IDE

### ISSUE THREAD

**Issue by mkaufmann66** [SAPDocuments/Tutorials#2023]
![2017-11-12 18_16_35-sap web ide](https://user-images.githubusercontent.com/21082771/32701451-700cf2f4-c7d6-11e7-9b6c-8cb820d66cf5.png)

Unable to get metadata when subsrcibing to product in WebIDE.

Regards,
Michael

**Comment by ivanfemia** [comment]
Michael,

make sure your end point in the destination is
https://**<puser>trial**-trial.apim1.hanatrial.ondemand.com:443

wait 5 miniutes and retry

Ivan

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
