### ISSUE TITLE
Install SAP HANA 2.0, express edition on Red Hat Enterprise Linux (Server only)

### ISSUE THREAD

**Issue by syu8** [SAPDocuments/Tutorials#2034]
Hi Abdel, in step 2, "the Scalable File System Add-On (XFS)........." is the default file system of RHEL 7, so it's no longer a separate item in the RHEL for SAP HANA channel. Would you please remove it?

**Comment by adadouche** [comment]
Thanks for your feedback.

These instructions are from the SAP HANA (the big one) installation guide. 

So if you don't mind I'll double check with the doc owner to make sure we are aligned and fix it in both location to avoid inconsistencies.

@bdel

**Comment by adadouche** [comment]
Thanks for your patience.

I have updated both:
https://www.sap.com/developer/tutorials/hxe-rhel-server-core-local.html with  https://github.com/SAPDocuments/Tutorials/commit/97b844bba88ce7347f533275221f17b298b9dddd 
and
https://www.sap.com/developer/tutorials/hxe-rhel-server-apps-local.html with https://github.com/SAPDocuments/Tutorials/commit/e7e8126fffebb4994d0bb1244a3bdf174504d253

**Comment by nikitazernov** [comment]
Hello everyone! Links mentioned by @adadouche are broken.

**Comment by adadouche** [comment]
Hi @nikitazernov 

I guess you are facing this issue from the [HXE product age](https://developers.sap.com/topics/sap-hana-express.html).

To make the story short, the mentioned tutorials were deprecated and removed from the [HXE product age](https://developers.sap.com/topics/sap-hana-express.html). 

However, for an unknown reason the links reappeared on the [HXE product age](https://developers.sap.com/topics/sap-hana-express.html). 

The RedHat steps are now part of the following groups: 

- [Install SAP HANA, express edition on a Native Linux Machine](https://developers.sap.com/group.hxe-install-binary.html)
- [Install SAP HANA, express edition on a Native Linux Machine (with SAP HANA XS Advanced)](https://developers.sap.com/group.hxe-install-binary-xsa.html)

  with the [Machine Requirements](https://developers.sap.com/tutorials/hxe-ua-getting-started-binary.html) tutorials.

If something is not working properly, you can reach to @JCurrie27 (the author of the tutorial).

Regards

**Comment by xochilpili** [comment]
I have installed many times HANA Express on RHEL 7.6 (Maipo), got several & different errors, but finally here's an installation process that works out of the box :+1: 
### Requirements

1. Machine requirements for SAP HANA Express. [Requirements here](https://developers.sap.com/topics/sap-hana-express.html)
2. Fresh Install of RHEL 7.6 (Maipo)

### Rhel 7.6 (Maipo) & Repos Configuration:
```
subscribe-manager register <- will ask for your credentials
subscribe-manager list --available --all
subscribe-manager attach --pool=(ID Pool Group)
subscribe-manager repos --disable "*" 
subscribe-manager repos --enable="rhel-sap-hana-for-rhel-7-server-rpms" --enable="rhel-7-server-rpms"
hostnamectl set-hostname my_hana.mydomain <-- very important 
```

### Rhel 7.6 (Maipo) & HANA Express Requirements: 

```
yum groups mark convert
yum -y groupinstall base
yum -y install compat-sap-c++-6 tuned-profiles-sap-hana 
tuned-adm profile sap-hana-vmware <-- if you're in VMware infrastructure
yum -y update
sed -i 's/^SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
sed -i 's/^SELINUX=permissive/SELINUX=disabled/g' /etc/sysconfig/selinux
systemctl disable firewalld
reboot
```

### HANA Express Installation & Requirements:
```
mkdir ~/downloads && cd ~/downloads
wget https://tools.hana.ondemand.com/additional/sapjvm-8.1.051-linux-x64.rpm <--- check for cookie
yum -y install ~/downloads/sapjvm-8.1.051-linux-x64.rpm
update-alternatives --install "/usr/bin/java" "java" "/usr/java/sapjvm_8_latest/bin/java" 1
update-alternatives --set java /usr/java/sapjvm_8_latest/bin/java
java -version <--- display java version "1.8.0_192" <--- in my case
```

HXEDownloaderManger (DM Linux) can be downloaded from here after a free registration form: https://www.sap.com/cmp/ft/crm-xu16-dat-hddedft/index.html

### HANA Express Preparation for install :

```
mkdir -p /opt/hxe/installer
cd ~/downloads <-- assume that HXEDownloadManager_linux.bin is in this directory
chmod +x HXEDownloadManager_linux.bin <- execution permissions
./HXEDownloadManager_linux.bin linuxx86_64 installer -d /opt/hxe/ hxe.tgz hxexsa.tgz clients_linux_x86_64.tgz apl.tgz
```

### HANA Express Installation : 
```
cd /opt/hxe/
tar xzf hxe.tgz -C installer/
tar xzf hxexsa.tgz -C installer/
tar xzf apl.tgz -C installer/
cd installer/
./setup_hxe.sh <--- continue with prompted options
```

### Check Installation 
```
su -l hxeadm
xs-admin-login
xs apps
HDB info | grep "/hana/shared/${INSTANCE}/xs/router" <-- change instance for HXE or what ever you used in prompt options
```

### Collect Garbage & Free Mem : 
```
su -l hxeadm
hxe_gc.sh 
free -g -t  
```

### Omitted in process:
1. Rhel 7.6 Subscription & Registration Process.
2. Networking configuration.

**Comment by JCurrie27** [comment]
Hi @xochilpili - could you post your installation process -- and your unresolved installation issues, in the Questions and Answers community? ([https://answers.sap.com/questions/ask.html](https://answers.sap.com/questions/ask.html)) When prompted for a primary tag, search for "express" and choose SAP HANA, express edition.
