### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by axelfontaine** [SAPDocuments/Tutorials#2038]
This is missing instructions on how to log in to the actual database once it is up.

```
hxeadm@36c59c56cb91:/usr/sap/HXE/HDB90> hdbsql -i 90 -u SYSTEM -p HXEHana1 -n localhost:39013
Single Sign-On authentication failed
hxeadm@36c59c56cb91:/usr/sap/HXE/HDB90> hdbsql -i 90 -u hxeadm -p HXEHana1 -n localhost:39013
Single Sign-On authentication failed
```

This is what I got. I am sure I am not the only one stuck here.

**Comment by aplata-sap** [comment]
Hi there,

To log in to the system database use: 

_hdbsql -i 90 -d systemdb -u SYSTEM -p HXEHana1_

and to log on to the tenant database use:

_hdbsql -i 90 -d HXE -u SYSTEM -p HXEHana1_

Does that resolve the issue?

**Comment by axelfontaine** [comment]
Hmmm interesting... that certainly works. (probably a good idea to add that to the documentation page to validate the installation)

And so does connection via JDBC on Linux with the URL jdbc:sap://localhost:39013/?databaseName=HXE

But connecting with the very same URL to an identical container started with the same docker-compose config, but this time on a Windows host, fails with:

```
Caused by: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: Cannot connect to jdbc:sap://localhost:39013/ [Cannot connect to host 172.19.0.11:39041 [Connection timed out: connect], -813.].
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:126)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:203)
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:50)
	at com.sap.db.jdbc.Driver._connect(Driver.java:1402)
	at com.sap.db.jdbc.Driver.connect(Driver.java:1062)
```

Note the different port numbers. Also note that connecting inside that same container using hdbsql does work. Any clue what could be going on?

**Comment by aplata-sap** [comment]
The ports are different for Docker installations. Try this:

jdbc:sap://_<ip _address>_:39041/databaseName=HXE

for tenant database, and 

jdbc:sap://_<ip _address>_:39017/databaseName=systemdb

for system database.

**Comment by axelfontaine** [comment]
Great! That did it! Note that the databaseName part of the URL is unnecessary when using the other port.

It is still weird that `jdbc:sap://localhost:39013/?databaseName=HXE` worked on a Linux host, but not on a Windows host..

Either way, consider adding this info to the docs to save someone else the trouble and frustration. Thanks for your help!

**Comment by aplata-sap** [comment]
We'll add this to the docs. Thanks for your patience and feedback!
