### ISSUE TITLE
Add a map display to your app

### ISSUE THREAD

**Issue by guillaumeko** [SAPDocuments/Tutorials#2039]
Hi,

In the tutorial: "Add a map display to your app", you provide a setup for the Destination. But it doesn't work: 

Failure reason: "peer not authenticated".

Are you sure ye don't need to provide a google map API key somewhere ? If yes, how please ?

Thanks a lot

**Comment by thecodester** [comment]
Thank you for your feedback. Because of the amount of time that has elapsed, we are closing the issue.  

If you still have questions, feel free to create a new issue.
