### ISSUE TITLE
Image Classification ML service with SAPUI5

### ISSUE THREAD

**Issue by SK-2014** [SAPDocuments/Tutorials#2044]
Hi,
This blog was very useful.
I am new to machine learning and hence wanted to know on below query.
For image classification, in api.sap.com (https://api.sap.com/shell/discover/contentpackage/SAPLeonardoMLFunctionalServices/api/image_classification_api) we do find UI5 generated code on clicking on post method -> /inference_sync.
So where do we use it in this particular UI5 example? in some of the machine learning blogs, its mentioned that we can make use of the code available.
Any thoughts on it would be appreciated.
Regards,
SK

**Comment by adadouche** [comment]
Hi,

The generated code snippet on the api.sap.com is not always "easy" to integrate.

In this particular example (Image Classification), you have to pass the image content to the service in a multi part form data object, but there is no example about how to do that.

If you look at Java, you can find a working code example for that in: https://www.sap.com/uk/developer/tutorials/ml-fs-java-img-classification.html

The SAPUI5 snippet is supposed to be used in a controller, but there no details about how to get the image data. 

This is why I wrote the following tutorial: https://www.sap.com/uk/developer/tutorials/ml-fs-sapui5-img-classification.html 

Have you tried it? A few people are having issue there too with the SAPUI5 FileUploader controller which is not working the same as for me.

If not, can you give a try and let me know if it works for you?

On the api.sap.com web site you have the ability to submit feedback (there is a button on the top right area for that). It will send an email to admin.apibusinesshub@sap.com.

Regards

**Comment by adadouche** [comment]
Hi @SK-2014,

I hope you did find your way into the provided content. I'll close this issue for now, but feel free to open a new one if you have any other questions.

Thanks
