### ISSUE TITLE
Setup SAP HANA, express edition, in Amazon Web Services or Microsoft Azure using SAP Cloud Appliance Library

### ISSUE THREAD

**Issue by svenkohlhaas** [SAPDocuments/Tutorials#2048]
Under "Step 4: Connect to your machine using SSH" the command "ssh ssh -i /path/my-key-pair.pem root@vhcalhxedb" is listed, this should be "ssh -i /path/my-key-pair.pem root@vhcalhxedb". Would someone please fix this?

**Comment by Lsubatin** [comment]
Thanks, Sven! It's fixed now.
