### ISSUE TITLE
Installing SAP HANA 2.0, express edition (Binary Installer Method)

### ISSUE THREAD

**Issue by rgtripathi** [SAPDocuments/Tutorials#2049]
On https://www.sap.com/developer/tutorials/hxe-ua-installing-binary.html, it is implied that apparently, only SUSE Linux should be used against SAP HANA 2.0 Express Edition. However, checking up a url within the HANA Express pages on sap.com (https://www.sap.com/india/developer/topics/sap-hana-express.product-detail.html#product-detail) implies that even RedHat Linux 7.2/7.3 are certified.

If RedHat is certified, should the above tutorial URL not be updated to reflect that as a platform choice too?

**Comment by aplata-sap** [comment]
Hi there,

We have the update in the pipeline. Thanks for the feedback!

**Comment by JCurrie27** [comment]
The tutorial https://www.sap.com/developer/tutorials/hxe-ua-installing-binary.html was updated on December 18. Thanks for your feedback - closing this issue.
