### ISSUE TITLE
Start Using SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by luto65** [SAPDocuments/Tutorials#2050]
For your information today I’ve tried it out and step 21 is failing due to inappropriate access rights of the files in 

/hana/shared/HXE/global/hdb/custom/config/lexicon/lang
 
What happens is that by executing 

tar -xvzf additional_lang.tgz -C /hana/shared/HXE/global/hdb/custom/config/lexicon
 
Many error messages appear due to not enough privilege to write in that folder.
 
The fix was easy:

chmod +w /hana/shared/HXE/global/hdb/custom/config/lexicon/*.*
 
and then the
 
tar -xvzf additional_lang.tgz -C /hana/shared/HXE/global/hdb/custom/config/lexicon
 
works fine.

**Comment by JCurrie27** [comment]
Thanks for this feedback. The development team is looking at ways to relax the permissions requirements of these files, so the extra command may not be needed in the next release of the software. We'll keep you posted.

**Comment by JCurrie27** [comment]
Hello luto65 - We've researched the permissions issue, and development recommended a new permissions change step, and updates to the file extraction step. Please see Step 21, points 3 and 4 -- we've updated this information. Thanks so much for bringing this to our attention. Closing this GitHub issue.
