### ISSUE TITLE
SAP HANA, express edition, in Google Cloud Platform Launcher

### ISSUE THREAD

**Issue by artemiollin** [SAPDocuments/Tutorials#2058]
"The next page will allow you to modify the default configuration for the Cloud Virtual Machine." - mention is takes 2-3 minutes for the next page to load.

**Comment by Lsubatin** [comment]
What's the feedback here? That GCP's pages took too long to load for you?

**Comment by artemiollin** [comment]
Yes, the page has been loading for more that 2 minutes.

**Comment by Lsubatin** [comment]
Loads almost instantly for me. GCP has a feedback button on the top right corner in case you're interested in letting them know.
