### ISSUE TITLE
Sign up for a free trial account on SAP Cloud Platform

### ISSUE THREAD

**Issue by maroueneboubakri** [SAPDocuments/Tutorials#2062]
Why all those complications, it took me one hour to get into a job description page   !

**Comment by thecodester** [comment]
Can you explain more specifically what problems you ran into?

Are you talking about this tutorial?
https://www.sap.com/developer/tutorials/hcp-create-trial-account.html

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
