### ISSUE TITLE
Image Classification ML service with SAPUI5

### ISSUE THREAD

**Issue by mohkakkar** [SAPDocuments/Tutorials#2063]
Hi, 

I followed all the steps. I see that the code in Step-11 have error and while testing the application i always get a blank page.

Regards,
Mohit Kakkar

**Comment by adadouche** [comment]
Hi,

Can you tell me at what line is the error in the JavaScript Controller?

Thanks

**Comment by mohkakkar** [comment]
Hi Abdel,

Thanks for a quick response.

Please see the attached file containing the error screenshot. I followed all the steps correctly but I always get a blank page when I hit run. Not sure if this is because of this error.

Thanks and Regards,
Mohit Kakkar
Tel/Direct: +1 470 434 7737 | Mobile: +91 9654569420
mohkakkar@Deloitte.com<mailto:mohkakkar@Deloitte.com> | www.deloitte.com<http://www.deloitte.com/>
[cid:image001.jpg@01D2AE2E.5D7A7200]

**Comment by adadouche** [comment]
Hi,

Your last message doesn't contain any screenshot. Can you upload the image again?

Thanks

**Comment by mohkakkar** [comment]
![image](https://user-images.githubusercontent.com/34342651/33756856-646ecd18-dc1d-11e7-909e-2995fb24a941.png)

**Comment by adadouche** [comment]
Hi, no this error is not related.

Your Web IDE is configured to use LF instead of CR/LF as line delimiter.

When you run your application, can you then press F12 to start the browser developer tools.
Then have a look at the console tab, where your error should be displayed.

Regards

**Comment by mohkakkar** [comment]
Hi Abdel, 

Please find the console tab screenshot.
![image](https://user-images.githubusercontent.com/34342651/33757295-89cdb428-dc1f-11e7-95c8-44ebaf056935.png)

**Comment by adadouche** [comment]
Hi,

it seems that you are missing the demo.view.xml under Workspace > sapui5ml-imageclassifier > webapp > view as described in Step 10.

**Comment by mohkakkar** [comment]
Hi Abdel, 

I have the demo.view.xml under Workspace > sapui5ml-imageclassifier > webapp > view as described in Step 10. Please see the screenshot below.

![image](https://user-images.githubusercontent.com/34342651/33758764-affed428-dc25-11e7-8d3d-83ff597dd650.png)

**Comment by adadouche** [comment]
Then this means that you haven't updated the index.html as described in step 7:

```JavaScript
data-sap-ui-resourceroots='{"demosapui5ml-imageclassifier": "", "sapui5ml": ""}'
```

**Comment by mohkakkar** [comment]
I did update that. Please find the screenshot below.
![image](https://user-images.githubusercontent.com/34342651/33761507-3de3dee2-dc2f-11e7-855a-ca09b9eae651.png)

**Comment by adadouche** [comment]
Then did you change your manifest.json file? Especially the rootView which should be like this:

```
		"rootView": {
			"viewName": "demosapui5ml-imageclassifier.view.demo",
			"type": "XML"
		}
```

In your case it might look like this:
```
		"rootView": {
			"viewName": "demosapui5ml.view.demo",
			"type": "XML"
		}
```
which is not correct

**Comment by adadouche** [comment]
can you check the network tab one you refresh the page and see which URL is used to load the demo.view.xml?

**Comment by mohkakkar** [comment]
Thanks, Abdel!
Changing the manifest.json worked. Thankyou for the help. This issue can be closed.
