### ISSUE TITLE
Getting Started with SAP Cloud Platform Rapid Application Development by Mendix

### ISSUE THREAD

**Issue by Adam-Dupaski** [SAPDocuments/Tutorials#2064]
Hi, I am a technical writer at Mendix. Was having a look at this tutorial and noticed the use of "business modeler." This is an outdated Mendix term. Mendix has the Mendix Desktop Modeler and the Mendix Web Modeler. In this case, the document should state either “Mendix Desktop Modeler” or just “Desktop Modeler.” Please note the capitalization.
Thanks.

**Comment by thecodester** [comment]
Fixed https://github.com/SAPDocuments/Tutorials/commit/b0e274926f90e77a079604414d77f6f6e94312a3
