### ISSUE TITLE
product-installer-ui for HXE on GCP

### ISSUE THREAD

**Issue by fableh** [SAPDocuments/Tutorials#2082]
Hi all,

little question i want to try out to enable the "Poduct Installer UI" in my HXE on GCP.
Yesterday i´ve installes this manually via: 

`xs install XSACALMPIUI12_3-80002271.ZIP`

If i check the apps via: `xs apps`
I see the "product-intsaller-ui":

![image](https://user-images.githubusercontent.com/13249857/33884548-6d56d80a-df40-11e7-97d2-f98b963827d0.png)

But if i enter the URL i got no response:
![image](https://user-images.githubusercontent.com/13249857/33884615-abd05de0-df40-11e7-9d73-dbde085fdfc6.png)

any tip would be great ;o)

cheers,
fabian

**Comment by JoiceHuiziLiu** [comment]
Hi Fabian,

Could you please check if you can access https://hxehost:51043 for your cockpit-admin-web-app application?

Otherwise, can refer to the step 4 in this link?
https://www.sap.com/developer/tutorials/hxe-gcp-getting-started-launcher.html

If any more issues, please let me know.

Best regards,
Joice

**Comment by Lsubatin** [comment]
Hey, Fabian, this is not really an issue with the tutorial so I'm closing it for statistical purposes but you know you still have my attention. 

The service is stopped according to your screenshot (it should say STARTED  1/1). It started automatically for me, so you could try restarting it. You can also check on the logs, maybe something went wrong? 

 I tried the same installation on one of my launcher GCP machines and did not have any problems. I did need to enable the port in the firewall rules on GCP (i was getting the same error you were getting), this may be different for your instance but it's worth checking.

**Comment by fableh** [comment]
Hey @Lsubatin,

the trick with changing the firewall rules works.
I´am now able to access all my apps.

thx and br,
fabian
