### ISSUE TITLE
Building freestyle IoT application TEMPLATE

### ISSUE THREAD

**Issue by paollasr** [SAPDocuments/Tutorials#2083]
I cant find the Template to Build the Freestyle App at the WebIDE. 
At the SAPUI5 Versions (SAP 1.50 /1.44/1.38) does not contain this template used on the tutorial.
Is there any other possibilities to get the OData from my ThingModel?
Can I get a OData link from the messages generated from my device?

Thanks a lot,
Paola

**Comment by Sygyzmundovych** [comment]
Hi Paola. Sorry for delay responding. Could you please check and reply if you still have this problem with the tutorial?

**Comment by Sygyzmundovych** [comment]
Closing as I haven't heard back if the issue persists.
