### ISSUE TITLE
Getting Started with SAP Cloud Platform Rapid Application Development by Mendix

### ISSUE THREAD

**Issue by lutraki-yavan** [SAPDocuments/Tutorials#2087]
Hi,
1. The tag "SAPUI5" is not related to this tutorial, there's no UI5 development in SAP RAD by Mendix.
2. The screenshot of creating a new app should be updated (the SAP tab in the Mendix portal was changed to "SAP Apps").
3. Also the "SAP Starter App" was changed to "SAP Blank".
Thanks,
Michal.

**Comment by thecodester** [comment]
Updated https://github.com/SAPDocuments/Tutorials/commit/c7a4178a3d2a5cdc41b700f4e1f8203aba70f2a7
