### ISSUE TITLE
Display database content and run SQL queries

### ISSUE THREAD

**Issue by jaimewhite999** [SAPDocuments/Tutorials#2088]
I am having issue while entering a database table in eclipse.  I followed the needed steps outlined in this link tutorial.

https://www.sap.com/developer/tutorials/abap-display-data-queries.html

STEP 2: Select a database table

I entered snwd_so_inv_item in the search field.
No result.

Why ?? 

I read <The NetWeaver Enterprise Procurement Model – An Introduction>'s document.
https://www.sap.com/documents/2012/09/2a404253-5b7c-0010-82c7-eda71af511fa.html
I generated EPM by ABAP transaction SEPM_DG.
And, I added role 'SAP_BC_EPM_DEMO' to my user profile.

But still there is no result for snwd_so_inv_item.

In SE11, I can see the table "snwd_so_inv_item".

Why can't  I  use the database table "snwd_so_inv_item" in eclipse ?

Appreciate your help.

Thanks.

**Comment by thecodester** [comment]
@olgadolinskaja Can you take a look?

**Comment by olgadolinskaja** [comment]
Are you sure, that you execute the search with"Run ABAP Development Object as ABAP Application in SAPGUI" (ALt + F8)? Please double check. Which AS ABAP release and which ABAP Development Tools version do you use?

Best regards,
Olga.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by eliasjsj** [comment]
Hello! I´m having the same issue. And I´m sure that I´m executing the search right (Alt + F8). 
My SAP_BASIS is 731 SP level 0018.
My Eclipse version is 2018-12 with the ABAP ADT tools for this version.

**Comment by thecodester** [comment]
@olgadolinskaja Any ideas?

**Comment by olgadolinskaja** [comment]
Hi! 
the tutorial is actually SAP NetWeaver 7.5-based. Data Preview in ADT is available with NetWeaver 7.4, that's why you don't get it with NetWeaver 7.31

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue.

If you still have questions, feel free to reopen the issue.
