### ISSUE TITLE
Generate sensor data

### ISSUE THREAD

**Issue by harmueller** [SAPDocuments/Tutorials#2089]
Connecting the output port with the inport is somewhat cumbersome. I initially thought it is not working but you need to precisely place the mouse on a rather narrow spot to successfully complete this step.

**Comment by thecodester** [comment]
@schneidertho  Can you respond?

**Comment by schneidertho** [comment]
Hi Harald, 
I have made the description a bit more detailed (https://github.com/SAPDocuments/Tutorials/pull/2097). I have also submitted the feedback to the development team to take into consideration for the SAP Data Hub Pipeline Modeler backlog.
Cheers
Thorsten
