### ISSUE TITLE
SAP HANA express edition product details

### ISSUE THREAD

**Issue by axelfontaine** [SAPDocuments/Tutorials#2090]
First of all apologies if this is the wrong repo to suggest this.

On the https://www.sap.com/developer/topics/sap-hana-express.product-detail.html#product-detail page, it may be worth mentioning for your users that if they want to evolve their schema Flyway now comes with first-class SAP HANA Express 2.0 database migration support. See https://flywaydb.org/documentation/database/saphana

What do you think?

**Comment by Lsubatin** [comment]
Hi, Axel, thanks for the suggestion. We do not do advertising in our tutorials  but it's good to know.

**Comment by axelfontaine** [comment]
@Lsubatin I just thought it'd suggest it since you have a section for Hibernate and this could be interesting for your users as Flyway's schema evolution capabilities completes the set of tools they need. Also SAP HANA is fully supported in the open source community edition.
