### ISSUE TITLE
Image classification Failed to resolve API Key variable request.header.apikey error

### ISSUE THREAD

**Issue by rosshigh** [SAPDocuments/Tutorials#2091]
I'm using the Image Classification ML service with SAPUI5 tutorial as a basis and I (with the help of the author and others) was able to get it to work.  However if I change anything, I sometimes get this error:

`{"fault":{"faultstring":"Failed to resolve API Key variable request.header.apikey","detail":{"errorcode":"steps.oauth.v2.FailedToResolveAPIKey"}}}`

It's an odd error because if I look in the request header, the APIKey is there.  In fact the request and response headers look identical to those in a version of the app that works.  

`Accept:application/json

Accept-Encoding:gzip, deflate, br

Accept-Language:en-US,en;q=0.9

APIKey:NoLmFbJTQ97e0v8gwAmEDIsl0YcujSh9

Connection:keep-alive

Content-Length:69841
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryAQV2kpFwR91sHkDx
Cookie:JTENANTSESSIONID_7b1b1837-b36b-42de-b045-c9c3780d9766=Dr9kzWc5QrVE%2FmpV1TIq%2BQexA3B5KCjPbQENl4%2BMGKI%3D; JTENANTSESSIONID_s0009700438trial=fE8L84Zxldr6mF7gcKi47WGhsL7wOuAJKmkqLRc9Wfw%3D; BIGipServer~jpaas_folder~dispatcher.hanatrial.ondemand.com=!1ZLihuxCLDi9W8awDhtcRsHHmTA76GrUYzrLGWDH00WK0eS754Kcz1BX6R9T2roBuCHGE5nibjazBTI=; JSESSIONID=1A2F1D2A1964C6B9CA173360CD90E57FF617874FBBD45C2A7F76DB2FBD3477B4
DNT:1
Host:webidetesting2286254-s0009700438trial.dispatcher.hanatrial.ondemand.com
Origin:https://webidetesting2286254-s0009700438trial.dispatcher.hanatrial.ondemand.com
Referer:https://webidetesting2286254-s0009700438trial.dispatcher.hanatrial.ondemand.com/webapp/index.html?hc_orionpath=%2Fs0009700438trial%24S0009700438-OrionContent%2FImageClassfier&origional-url=index.html&sap-ui-appCacheBuster=..%2F&sap-ui-xx-componentPreload=off
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
`

The only things I changed was the model name (made sure I updated everywhere) and I deleted the extra XHR code in the controller.

Any ideas?

Thanks,

Ross

**Comment by rosshigh** [comment]
I found this bit of code in the other tutorials in the series and added it.  Not sure if it was the solution but it's working now:

`	"headerWhiteList": [
		"APIKey"
	]
`

**Comment by adadouche** [comment]
Hi,
Yes this is usually the issue. SAPUI5 will block any "unconventional" header, this is why you have to add it to the white list (it took me a few days to found that trick ;-))
