### ISSUE TITLE
Create an API Proxy

### ISSUE THREAD

**Issue by flazanha** [SAPDocuments/Tutorials#2093]
Step 7.:
  Not possible create using "Link API Provider"  with  flag check , is necessary disable this option .

   The option Create doesn´t work form ES5 SAP System

**Comment by mhassett92** [comment]
Have thorough re-testing with the ES5 systems, I have not seen this behavior. The Create option still works with the Link API Provider flag checked. Make sure to use the Discover option with the API Provider selected. Unselecting the Link API Provider check will remove all the benefits of linking the Provider, such as authentication and catalog service information.

I am going to close this ticket. If you have more information on this scenario, you may re-open or create a new one.
