### ISSUE TITLE
List Report Floorplan

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2100]
Swift compiler error in Step 5 
override func prepare
        supplierProductsView.entity = try self.myServiceClass.service.suppliers(query: query)[0]

MyPrefixSuppliersDetailViewController.swift:397:60: Value of type 'MyPrefixMyServiceClass<OnlineODataProvider>' has no member 'service'

What are other ways to execute above SupplierProducts query?

**Comment by vsenn** [comment]
changed to 
supplierProductsView.entity = try self.myServiceClass.executeQuery(query).entityList().first()
and it works just fine

**Comment by dailystore** [comment]
Hi Vsenn,

In my case, I found there is no implementation for myServiceClass
Value of type 'SuppliersDetailViewController' has no member 'myServiceClass'

I also cannot find it in the tutorial, I would be grateful if you can share your guideline?
https://www.sap.com/developer/tutorials/fiori-ios-scpms-floorplan.html
Thanks.

**Comment by vsenn** [comment]
dailystory, 
`myServiceClass` is just a main data service proxy class of `DataService<Provider>` in your `Proxy Classes\public` folder it could be named `service` or anything not correlated with OData Entities' names. Proxy names are generated by SCP SDK and dependent on the previous tutor you came from :)

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
