### ISSUE TITLE
List Report Floorplan

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2101]
Swift compiler error in Step 5:
override func prepare
     let currentEntity = self.selectedEntity as? ...

MyPrefixSuppliersDetailViewController.swift:387:37: Value of type 'MyPrefixSuppliersDetailViewController' has no member 'selectedEntity'

**Comment by vsenn** [comment]
Changed to 
let currentEntity = self.entity as? MyPrefixSupplier
works just ok, w/ Warning

**Comment by dailystore** [comment]
In my case,

Changed to
let currentEntity = self.entity as? Supplier
should work

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
