### ISSUE TITLE
Implement Barcode Scanner

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2102]
Application is not building et all. Looks like some mess(/spell) w/ filteredBarcodes & scannedBarcodes.
These two var-s not defined and weirdly used. 
Barcode part in List Report Floorplan also not fully implemented nor working.

**Comment by qualiture** [comment]
For some reason, the class fields were missing from the tutorial.

If you add these to the table view controller class, it should work:

```swift
var searchController: FUISearchController?
var scannedBarcodes: [String] = []
var filteredBarcodes: [String] = []
var isFiltered: Bool = false
```

Fixed in pull request https://github.com/SAPDocuments/Tutorials/pull/2185

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
