### ISSUE TITLE
Create a Destination on SAP Cloud Platform

### ISSUE THREAD

**Issue by stetze** [SAPDocuments/Tutorials#2116]
I am lost because the link to the "next step" is missing on the page:
https://www.sap.com/developer/tutorials/hcp-create-destination.html

I came to this site by clicke "next step" on the very beginning of this tutorial series at:
https://www.sap.com/developer/tutorials/sapui5-webide-open-webide.html

**Comment by thecodester** [comment]
Thank you for your feedback. Because of the amount of time that has elapsed, we are closing the issue.  

If you still have questions, feel free to create a new issue.
