### ISSUE TITLE
Send the CPU usage data to SAP IoT Application Enablement

### ISSUE THREAD

**Issue by kadalivenu** [SAPDocuments/Tutorials#2117]
Hi Vitaliy Rudnytskiy,

Many thanks for the explanation. However I am getting bellow error.

Values to post:  1.6 1514145054
Payload to post:  {"mode":"sync","messageType":"dc88bf65edae02a05da7","messages":[{"cpu_usage":1.6,"cpu_type":"generic","_time":1514145054}]}
500 {"msg":"Processing 1 message(s) received from device [FA74E0CC59A14E43BB84DE4C92B775CF] failed"}

What may be the reason? Could you please help me in resolving this issue?

Best regrads,
Venu.

**Comment by Sygyzmundovych** [comment]
Hi Venu. Error 500 means internal server error, and maybe temporarily or may be caused but improperly formatted calls. Do you still have this issue?

**Comment by Sygyzmundovych** [comment]
Closing as I haven't heard back if the issue persists.
