### ISSUE TITLE
Implementing labels using the i18n (internationalization) features of SAPUI5

### ISSUE THREAD

**Issue by raz-korn** [SAPDocuments/Tutorials#2118]
SAP Web IDE has integrated tools to handle i18n: https://help.sap.com/viewer/825270ffffe74d9f988a0f0066ad59f0/CF/en-US/f0fd022170a241caab35d8e742436bcf.html - towards the bottom, a section called "Managing i18n Strings".

**Comment by thecodester** [comment]
Thank you for your feedback. Because of the amount of time that has elapsed, we are closing the issue.  

If you still have questions, feel free to create a new issue.
