### ISSUE TITLE
Onboarding a computer as the IoT thing

### ISSUE THREAD

**Issue by schecaza** [SAPDocuments/Tutorials#2121]
Hi Vitaliy Rudnytskiy,

In Step 5 "Add your computer as a new thing", modeller show a different account number from a2667617c , and this can not be selected in order to complete the step 5.

Regards.

**Comment by DanielS12345** [comment]
if I choose "SAP Cloud Platform IOT Service for Neo Environment" as Provider it works fine for me with account number from a2667617c

**Comment by Sygyzmundovych** [comment]
Hi Daniel. Sorry for the inconveniences. System has been upgraded and we need to update descriptions in tutorials.
