### ISSUE TITLE
Tutorial Page : ci-best-practices-xsa needs updating to match Jenkins changes

### ISSUE THREAD

**Issue by jasper07** [SAPDocuments/Tutorials#2125]
I am currently working my way through the tutorial with a brand new install of Jenkins.

I have noticed various issues when following the tutorial with the latest version of Jenkins

3.2 Installing Node.js on the Jenkins Slave Machine
----
.. Manage Jenkins > Manage Plugins > Available. Select Node.js Plugin
Plugin now renamed to "NodeJS Plugin"

6.1 Creating a Jenkins CI Build Job
----
3. Continue the configuration and enter the following:
quite a few of the config options have prerequisites plugins which aren't highlighted or tech has changed
eg
missing from out of the box 

Restrict where this project can be run 
Label Expression

Build Environment
Delete workspace before build starts | selected   -> ** Plugin needs installing first
Global passwords | selected -> ** appears to have been deprecated in favour of credentials
Mask password parameters | selected -> * * Plugin needs installing first

also if the tutorial could be updated to use the SAP/jenkins-library as i am guessing this is now or will be the best practice, not to mention Blue Ocean is a lot more developer friendly

docker would be nice also, easier way to manage the different NodeJS versions

cheers
JSP

**Comment by wolframK** [comment]
Hi JSP,

sorry for the very late reply.
Thank you very much for your very helpful comments. We will update the guide as soon as possible.
Of course, the guide is still a little bit behind the newest technology, we have based the tutorial on a Jenkins 1.6 version.
But the intention of the guide is to give you an idea on how to implement the CI processes on a CI server in general. Porting the ideas to Jenkins 2 with all the nice features should  not be too hard.
Docker is a very interesting topic. Not yet clear how this exactly will look like, but we will for sure move in this direction. 

Thnaks,
Wolfram

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
