### ISSUE TITLE
Updating SAP HANA, express edition (Virtual Machine)

### ISSUE THREAD

**Issue by 6of5** [SAPDocuments/Tutorials#2126]
Hi Folks,

I tried to follow the described steps to update my HANA 2.0 Express Edition  SP2 02 Revision 21 (flavor vm, server + apps), as proposed by @Lsubatin (here [https://answers.sap.com/answers/390796/view.html](https://answers.sap.com/answers/390796/view.html). Unfortuately the descibed steps do not work out for me.

Following issues:

1. there is no HXECheckUpdate_linux.bin available on my vm. Ok, this seems no issue, as it says I have then to download the files via the normal Download Manager. I did that, but
2.  download hxexsa.tgz, copied the tgz file in Downloads folder and extract the archiv, but there is no file hxe_upgrade.sh available in folder HANA_EXPRESS_20

Please see attached screenshot
![extractedfiles](https://user-images.githubusercontent.com/1450890/34626644-e37ce080-f25d-11e7-8104-1010fb0359e2.PNG)

Did I miss something?

Many Thanks in advance, BR, HP

**Comment by tai-le** [comment]
You also need to download and extract hxe.tgz to same directory.

**Comment by 6of5** [comment]
thx for the hint, the update did now run successfully. Close issue. Perhaps I will make PR to improve information in this tutorial
