### ISSUE TITLE
Working with Hierarchies using Apache Zeppelin

### ISSUE THREAD

**Issue by bjohnson-volume** [SAPDocuments/Tutorials#2156]
Hi on your tutorial is it possible to have the code display as a gist so I can copy and paste it. Right now all the code in the zeppelin screen shots are images and it is not big enough for me to read.

I have to zoom in on each of them individually. 
https://www.sap.com/developer/tutorials/vora-cal-zeppelin2.html

**Comment by Sygyzmundovych** [comment]
Hello. Vora dev edition on CAL has been recently discontinued, but I hope you can keep using OVA version and its tutorials https://www.sap.com/developer/tutorials/vora-ova-zeppelin2.html
All codes should be available within preinstalled Zeppelin notebooks, therefore no GitHub gists are provided.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
