### ISSUE TITLE
Enable, deploy and configure the SAP Predictive services

### ISSUE THREAD

**Issue by michael-a-zhang** [SAPDocuments/Tutorials#2173]
Hi,

I'm following the steps mentioned in this tutorial "Enable, deploy and configure the SAP Predictive services" <https://www.sap.com/developer/tutorials/hcpps-ps-configure.html>, and have encountered the below issue on Step 3 "Configure the data source binding".  When entered the Custom Logon details for the new binding using database user "PSTRIAL", error "Invalid username or password" was shown.  Binding was successfully created when entered "SYSTEM" as the database user, but then the Data Source Bindings created has the Custom Logon shown as "PSTRIAL".  

May I ask why I'm not able to create the binding using "PSTRIAL" as the Custom Logon Database User as per the instruction?  While on the other hand, was able to create the binding using "SYSTEM" as the Custom Logon Database User, but the Custom Logon was shown as "PSTRIAL" for the binding that was created?

Thanks & regards,
Michael

**Comment by adadouche** [comment]
Hi @michael-a-zhang,

The data source binding creation form in place caused me some trouble in the past, especially when you have auto completion or if you do copy paste.

I couldn't find any solution but to simply type in the username and password manually, and then press the tab button which seemed to worked properly.

If I do copy/paste, I usually then add a space character which I immediately remove, just to make sure that if there is any "press" event associated with the field.

What matters here is that the list displaying the default binding show that your custom login is PSTRIAL and not SYSTEM.

To verify that all is fine, you should start the application and follow the "Verify the setup" step.
The PSTRIAL user schema should now have a set of tables if you go back to the Catalog in the SAP HANA Web Workbench.

Let me know if you can resume your progress.

**Comment by adadouche** [comment]
No news, closing the issue. feel free to reopen if needed.
