### ISSUE TITLE
Read SAP Mobile Secure configuration data

### ISSUE THREAD

**Issue by agiguere** [SAPDocuments/Tutorials#2183]
in my trial account I don't have App & Device Management under Mobiles

I only have Development and Operations

**Comment by qualiture** [comment]
Hmmm, it seems they have removed it from the trial account :(

I'll try to find out if there is a workaround. I'll update once I know more

Apologies for the inconvenience

**Comment by qualiture** [comment]
Hi @agiguere,

The response I got was:

> We'll not develop app & device management as a separate service further. The relevant app management services will become part of the single mobile services offering under the 'dev & ops' umbrella.
>
> For the configuration stuff - this is already included in Mobile Services dev & ops. You have a default test domain created and you can also use the dev & ops Cockpit to supply custom configuration parameters on top of the default configuration.
>
> https://help.sap.com/viewer/38dbd9fbb49240f3b4d954e92335e670/Cloud/en-US/49031a21f5734e8e85cbafbe9549b164.html

Hope this helps!

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
