### ISSUE TITLE
Build an app from an SAP Web IDE template

### ISSUE THREAD

**Issue by ivanfemia** [SAPDocuments/Tutorials#2184]
Tutorial refers to the Kapsel templates that are [deprecated](https://blogs.sap.com/2017/06/20/deprecation-of-dedicated-kapsel-templates-for-sap-web-ide-hybrid-app-toolkit/)

This tutorial, even if was updated on 12/12/2017, does not provide the new procedure to create a WebIDE app to be mobilized using the Kapsel plugin.

**Comment by mhassett92** [comment]
In the blog you mention, they state that the Fiori Master Detail template is a suitable alternative. The steps are almost exactly the same for both templates. Please use this while we work on updating the tutorial.

**Comment by ivanfemia** [comment]
Thank you Meredith.
I already figured out, I just reported because someone else in the community will face the same.

**Comment by mhassett92** [comment]
I have updated the wording in the tutorial to reflect the new template option to hopefully remove confustion. 

The hope is that the users will use the tutorials to learn and not just to copy-paste code. We will work on updating the screenshots, but this is more time consuming. Thank you for bringing it to our attention!
