### ISSUE TITLE
Image links BROKEN!

### ISSUE THREAD

**Issue by Danniemite** [SAPDocuments/Tutorials#2186]
https://www.sap.com/developer/tutorials/abap-dev-adt-create-new-structure.html

All image links are broken.

**Comment by thecodester** [comment]
Please try again, or refresh the page. Let me know if the images are still missing.

**Comment by Danniemite** [comment]
They still do.

![sap-missing-images](https://user-images.githubusercontent.com/26408046/35036378-769684d8-fb74-11e7-9cfa-8527de0803fa.jpg)

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved and the images are displaying, so I am closing the issue. 

If you still have questions or problems with the images, feel free to reopen the issue.

**Comment by thecodester** [comment]
I see them!!??

![image](https://user-images.githubusercontent.com/11659786/55472467-d8e91780-5614-11e9-87a6-628e83dcac7b.png)
