### ISSUE TITLE
SAP HANA XS Advanced, import tables and large datasets

### ISSUE THREAD

**Issue by dakoller** [SAPDocuments/Tutorials#2192]
...feedback from trying this with a HANA Express + Apps on my Macbook:

- Hint would be helpful that you should create a new project before.
- Build process reported to be successful, but: 
- I could not find the tables in the database explorer because I was not sure where I'd find the tables.

**Comment by Lsubatin** [comment]
Hi Daniel, thanks for the feedback. Were you trying to import the data without following the prerequisites in the tutorial?

**Comment by dakoller** [comment]
...you are right, i missed the prerequisites link before starting.
