### ISSUE TITLE
AngularJS as a Front End - Getting Started

### ISSUE THREAD

**Issue by paidTrainee27** [SAPDocuments/Tutorials#2193]
Hi,
I just wanted to ask if I can upload(register) such an application over fiori launchpad/cloud PORTAL.

**Comment by jonathanbaker7** [comment]
Sure.  The Fiori Launchpad can use any application, not just ones written in UI5.  So any framework would work.

The easiest way to do this is to add the URL to an Angular application to a Launchpad tile.  You can also set up the Angular application to respond to Launchpad data requests, which make the tile "dynamic".

Take a look at this link in our SAP help system:  [Setting up Launchpad Content](https://help.sap.com/viewer/a7b390faab1140c087b8926571e942b7/7.52.1/en-US/f9b0ccce0766442ca8237eee23494f17.html) for more information
