### ISSUE TITLE
Image Classification ML service with SAPUI5

### ISSUE THREAD

**Issue by MayZinH** [SAPDocuments/Tutorials#2195]
Hi,

I'm trying to consume image classification API and performed everything the same as the tutorial steps you provided. But when I run the index.html file there is nothing shown up on the web page. I've checked the link also, it run with .index.html. The console result is as below... Please let me know what should I check or what did I miss. Thanks!

![console](https://user-images.githubusercontent.com/35556200/35147088-3f98102a-fd48-11e7-8ea5-272421d060eb.png)

**Comment by adadouche** [comment]
Hi @MayZinH 

Thanks for submitting your issue. Apparently you are missing the view named demo.view.xml in the webapps/view directory or the controller named demo.controller.js in the webapps/controller directory.

You can check the solution on GIT here : https://github.com/SAPDocuments/Tutorials/tree/master/tutorials/ml-fs-sapui5-img-classification/sapui5ml-imageclassifier 

Let me know if this helped.

Thanks

**Comment by MayZinH** [comment]
Hi, 

Thank you for your respond. I’ve updated the name on below files and it’s working now.

Demo.controller file in line 9
As tutorial: return Controller.extend("sapui5ml.controller.demo", {

Updated: return Controller.extend("Demosapui5ml-imageclassifier.controller.Demo", {

demo.view file in line 2 
As tutorial: 
xmlns:custom="http://schemas.sap.com/sapui5/extension/sap.ui.core.CustomData/1" controllerName="sapui5ml.controller.demo"

updated:
xmlns:custom="http://schemas.sap.com/sapui5/extension/sap.ui.core.CustomData/1" controllerName="Demosapui5ml-imageclassifier.controller.Demo"

and provide UI link as below in demo.json:
https://sandbox.api.sap.com/ml/imageclassifier/inference_sync

**Comment by adadouche** [comment]
Hi,

I see now, you have used "Demo" and not "demo" for your namespace and your view name.

Technically, you could also have used:

```
return Controller.extend("sapui5ml.controller.Demo", {
```
and 
```
controllerName="sapui5ml.controller.Demo"
```
Regarding the sandbox link, you might have missed the destination configuration step 4 and in step 8.
The use of a destination is important to avoid CSRF when deploying the application live.

Glad to hear that you manged to make it run in the end.

Regards
