### ISSUE TITLE
Create a Destination on SAP Cloud Platform

### ISSUE THREAD

**Issue by aleksanderlech1970** [SAPDocuments/Tutorials#2202]
hi,
there is no next step after Step 6: Check the Additional Property settings
verification went well, but what is the next?

greetings 
Olek

**Comment by Vest** [comment]
Can you please give the screenshot of the settings you entered and the error message?

**Comment by jonathanbaker7** [comment]
@aleksanderlech1970, I'm not sure what you are discussing.  Once this tutorial is complete, the destination is set up.

This tutorial is meant to be part of a chain of tutorials (it's part of several series) so it's not meant to be used independently.  If you are looking for more content, let me know by re-opening this bug and I'll see what we can find for you.
