### ISSUE TITLE
Create an API Provider System

### ISSUE THREAD

**Issue by amysy** [SAPDocuments/Tutorials#2203]
Hello Meredith,
I'm not able to save API Step 6. ES4 is retired so I created my API with ES5 Gateway.
Kindly let me know if the port is 443 is same and also when I test catalog link it's not able to load with the path and service URL. 

Looking forward to your input.

TIA.

**Comment by amysy** [comment]
Hi Meredith, 

I could test and save the API. Just had to create a new destination with the new gateway info. This fixed the issue. Please update the documentation likewise. 

Closing the issue now no further action from your side is needed. 
FYI - Troubleshooting steps.
Create a new destination with new gateway info i.e. ES5. This helps to assure your connection URL is good and working before going ahead with the API Provider creation.
Provide ES 5 related connection details for CATALOG URL and test. This should work.

**Comment by mhassett92** [comment]
Hi ,
Thank you for bringing this to my attention. I will make sure the documentation is updated to reflect the use of ES5 system.
Thanks!
Meredith
