### ISSUE TITLE
Building freestyle IoT application

### ISSUE THREAD

**Issue by mbiwer** [SAPDocuments/Tutorials#2204]
Hi all,
I just tried to do the tutorial. But I'm stuck at the step to create a new project with the "New Freestyle IoT Application". First of all, there is no more data source called "Freestyle IoT: Things OData Service". And the Property Set "sap.iotaeexplore.computeriotdevice:generic_computer" is also no more available but "sap.iotaehandson2.computeriotdevice:generic_computer" seems to be the right one now. But regardless of which Service I choose from the three available options, the "Next" Button is always disabled so I cant' continue with the wizard!

Best regards,
Michael

![2018-01-26_13-46-00](https://user-images.githubusercontent.com/35839469/35440671-ad5e321c-02a0-11e8-804c-254cee0267fa.png)

**Comment by Sygyzmundovych** [comment]
Sorry for the inconvenience, but indeed because of some issue all these updates were not made in the tutorial. The tutorial should be updated now with the correct descriptions.
