### ISSUE TITLE
SAP HANA XS Advanced, Connecting to SAP Web IDE and cloning a Git Repository to begin development

### ISSUE THREAD

**Issue by lnryan** [SAPDocuments/Tutorials#2208]
We persistently face issues where cloning becomes impossible due to errors like this:
![image](https://user-images.githubusercontent.com/7268332/35553082-4c855f06-058e-11e8-842d-32fdcd40647c.png)

![image](https://user-images.githubusercontent.com/7268332/35553130-7e8321b4-058e-11e8-84e1-35e0c1bca5fa.png)

Please can you include troubleshooting guidance. We have had to scrap entire Hana Express instances and start over because of this. We have seen it in Hana 2.0 SP 0,1 & 2

**Comment by thecodester** [comment]
@urini @Paolaufer Can you have a look?

**Comment by Lsubatin** [comment]
HI @lnryan , can you please send us the output of the following CLI commands right after it fails?

-  xs app di-core
-  xs app di-runner
And also:
 free -g

Please throw the commands right after the failure happens so we can capture backend crashes if that was the case. Also, what are the logs for webide saying?

**Comment by lnryan** [comment]
Hello,
Here's the output of the requested commands (from `SAP`) space. I'm not seeing anything useful in them. let me know if you need something else. Thanks.

### `xs app di-core`
![image](https://user-images.githubusercontent.com/7268332/35779177-ca39d414-09c0-11e8-96cc-d0468cbf962c.png)

### `xs app di-runner`
![image](https://user-images.githubusercontent.com/7268332/35779188-ee34727a-09c0-11e8-8e00-e0e9d6788925.png)

### `free -g`
![image](https://user-images.githubusercontent.com/7268332/35779199-06b8d46c-09c1-11e8-98da-ce0f7e56f44d.png)

### `xs logs webide`
```
hxeadm@sid-hxe:/usr/sap/HXE/HDB90> xs logs webide

Connected, tailing logs for app "webide"...
2/4/18 3:36:52.000 PM [RTR] OUT    195.128.10.106 - - to vhcalhxedb:53075 "GET /watt/resources/sap/watt/ideplatform/che/plugin/chebackend/featuretoggle/UnSupportedFeatures.json HTTP/1.1" 200 sent 510 in 4 by 00O-48693b5a-dede-48a6-993d-457fd703a82c
2/4/18 3:36:53.000 PM [RTR] OUT    195.128.10.106 - - to vhcalhxedb:53075 "GET /watt/resources/sap/watt/ideplatform/che/plugin/chebackend/featuretoggle/UnSupportedFeatures.json HTTP/1.1" 200 sent 510 in 3 by 00O-48693b5a-dede-48a6-993d-457fd703a82c
2/4/18 3:36:53.000 PM [RTR] OUT    195.128.10.106 - - to vhcalhxedb:53075 "GET /watt/resources/sap/watt/ideplatform/che/plugin/chebackend/featuretoggle/UnSupportedFeatures.json HTTP/1.1" 200 sent 510 in 3 by 00O-48693b5a-dede-48a6-993d-457fd703a82c
2/4/18 3:36:54.000 PM [RTR] OUT    195.128.10.106 - - to vhcalhxedb:53075 "GET /watt/resources/sap/watt/ideplatform/che/plugin/chebackend/featuretoggle/UnSupportedFeatures.json HTTP/1.1" 200 sent 510 in 4 by 00O-48693b5a-dede-48a6-993d-457fd703a82c
2/4/18 3:37:06.000 PM [RTR] OUT    195.128.10.106 - - to vhcalhxedb:53075 "POST /che/project/workspacekjiumgcorw2moc85/import/snics?async=true&force=true HTTP/1.1" 202 sent 80 in 210 by 00O-48693b5a-dede-48a6-993d-457fd703a82c
2/4/18 3:37:08.000 PM [RTR] OUT    195.128.10.106 - - to vhcalhxedb:53075 "GET /che/async/workspacekjiumgcorw2moc85/83 HTTP/1.1" 202 sent 106 in 52 by 00O-48693b5a-dede-48a6-993d-457fd703a82c
2/4/18 3:37:09.000 PM [RTR] OUT    195.128.10.106 - - to vhcalhxedb:53075 "GET /che/async/workspacekjiumgcorw2moc85/83 HTTP/1.1" 500 sent 68 in 39 by 00O-48693b5a-dede-48a6-993d-457fd703a82c
```

**Comment by Lsubatin** [comment]
Hi, Lindsay, 
I know similar issues are solved by upgrading the version of Web IDE. You can find the instructions to do that here: https://www.sap.com/developer/tutorials/hxe-ua-updating-binary.html 

If that does not work, please post this information in full in the Q&A: https://answers.sap.com/index.html  . Even though we try to help with this kind of problems, these GitHub issues are about tutorials and not meant for support. 

In the Q&A, please use the tags for sap web ide and sap hana express so that it gets visibility from the teams that can help further.

Best, 

Lucia.
