### ISSUE TITLE
Getting started with the SAP API Business Hub

### ISSUE THREAD

**Issue by VLearn4life** [SAPDocuments/Tutorials#2210]
In the page https://www.sap.com/developer/tutorials/hcp-abh-getting-started.html we have under Step 2 the following statement.

"Select the SAP API Business Hub service. If it is not already enabled, do so on the service page." 

Where do one get to enable the service?

**Comment by mhassett92** [comment]
When you click on the service tile, you should see a Not Enabled status (grey icon). Underneath the status should be a button that says "Enable". Click that button and wait for the status to change to the green Enabled status.

**Comment by VLearn4life** [comment]
Hi,
I cannot see any such thing. Please see the screen shot below

![image](https://user-images.githubusercontent.com/35959812/35608258-4bc77036-067e-11e8-98f9-8648fb4d1e41.png)

**Comment by VLearn4life** [comment]
Waiting for help to resolve this

**Comment by mhassett92** [comment]
You need to be in your trial account to access the services. You are currently just looking at the catalog. To get to your account, go back to the main page and select "Go to Neo Trial" and enable the service inside your account.
