### ISSUE TITLE
SAP HANA XS Advanced, Creating an HDI Module - Deploy Issues (MTA)

### ISSUE THREAD

**Issue by lnryan** [SAPDocuments/Tutorials#2214]
Hello,

We have modelled an HDI module on the access roles in this tutorial and used it with a Java oData service (with the `@oData.Publish` annotation). All goes well during development, but when we try to deploy the two modules together, the Java service throws an error that the user lacks the privilege `CDS_ANNOTATION_VALUES`.

Even when we apply this permission to all the deployment container users in eclipse we still get the error. Is there any tutorial or additional information on how to configure the connection between the HDI module and the oData Service in an MTA application? or troubleshoot connection issues to the deployed HDI module

Also, please could you consider providing a tutorial for creating and deploying oData v4 Java module?

Thanks.

👇 error.
```
###4E1151317BB4402EAF0BDF2E23F5AFDD##snics-odata#com.sap.gateway.v4.rt.cds.util.CDSRuntimeProviderFactory########http-bio-127.0.0.1-50287-exec-10#PLAIN#/snics.snicsdb._.PartnerMonitoring/Partner#/java/odata/v4/snics.snicsdb._.PartnerMonitoring/Partner##
2/4/18 2:44:22.102 PM [APP/1-0] ERR    Error while initializing RuntimeProvider#
2/4/18 2:44:22.102 PM [APP/1-0] ERR
2/4/18 2:44:22.102 PM [APP/1-0] ERR    java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: CDS_ANNOTATION_VALUES
2/4/18 2:44:22.102 PM [APP/1-0] ERR    	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
2/4/18 2:44:22.102 PM [APP/1-0] ERR    	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
2/4/18 2:44:22.102 PM [APP/1-0] ERR    	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
```

**Comment by Lsubatin** [comment]
Hi, Lindsay, 

This also belongs in the Q&A so it can get support from a broader audience. Unfortunately, I have not encountered this before.

The way to provide permissions to the HDI container technical users is described in that same tutorial, in the last two steps. I would suggest you add those there instead of via eclipse. 

I have the Java module on my bucket list :)

Best, 
Lucia.

**Comment by lnryan** [comment]
Hi @Lsubatin - Unfortunately the response is not so great. I have about 3 ignored questions on Q&A. It seems that the tutorials are much better supported than the documentation - which is why I asked if there is any tutorial that actually covers the permissions needed to deploy any of these.

It's not very helpful to have tutorials that show you how to develop something that fails when you deploy.
