### ISSUE TITLE
Basic Authentication and Secure Key Store

### ISSUE THREAD

**Issue by nileshkum** [SAPDocuments/Tutorials#2215]
While adding the metod 
```
public func authenticate() {
    let sapcpmsObserver = SAPcpmsObserver(applicationID: Constants.appId)
    urlSession = SAPURLSession(delegate: self)
    urlSession.register(sapcpmsObserver)
    var request = URLRequest(url: Constants.appUrl)
    request.httpMethod = "GET"

    let dataTask = urlSession.dataTask(with: request) { (data, response, error) in
        self.logger.info("OK")
    }
    dataTask.resume()
}
```
I am getting Error:

![screen shot 2018-02-05 at 1 34 34 am](https://user-images.githubusercontent.com/26800287/35781794-c2992f9e-0a14-11e8-9741-80369cd42bbf.png)

**Comment by qualiture** [comment]
Hi @nileshkum,

This tutorial was written for 1.x version of the SDK. The 2.x version does not generate the `Constants` class (which contained `appId` and `appUrl`) anymore.

Although the secure keystore part is still relevant, I have to investigate whether the authentication part is still relevant, now the 2.x version provides the complete Onboarding flow.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
