### ISSUE TITLE
Image Classification ML service with SAPUI5

### ISSUE THREAD

**Issue by georgkoester** [SAPDocuments/Tutorials#2216]
Hi, I found that the information on the howto [Image Classification ML service with SAPUI5](https://www.sap.com/developer/tutorials/ml-fs-sapui5-img-classification.html) differs in screenshot and the table concerning destination config:
![screen shot 2018-02-05 at 3 48 51 pm](https://user-images.githubusercontent.com/1372406/35810544-6271ec46-0a8c-11e8-99c9-e920536fb331.png)
Best,
Georg

**Comment by adadouche** [comment]
Thanks for your feedback.

I have updated the screenshots for the tutorials where this destinations was used
(https://github.com/SAPDocuments/Tutorials/commit/a405834771509a41ed4ce8c0d5989d54dc4ce29c).

**Comment by georgkoester** [comment]
Thanks!
