### ISSUE TITLE
Create a simple application using Hibernate on SAP HANA

### ISSUE THREAD

**Issue by jeremy76520** [SAPDocuments/Tutorials#2218]
Hello, What changes I have to do comparing with this tutorial if I want to deploy my java app in SCP with a link made by Hibernate to SAP hana also base in SCP ?

**Comment by adadouche** [comment]
Hi @jeremy76520,

If I had to deploy this application to the SAP Cloud Platform, I would most likely use the following group of tutorials: [Create a web app in Java using Eclipse](https://www.sap.com/developer/groups/cp-middle-java-1.html).

The series uses JPA and not Hibernate, but I'm sure you'll be able to find that you can most likely replace one by the other.

Regards

@bdel
