### ISSUE TITLE
Step 2: Enable SAP Translation Hub in the SDK Assistant

### ISSUE THREAD

**Issue by goubin510** [SAPDocuments/Tutorials#2220]
Hi (again),

I found a bug when I entered the url into my SDK assistant.
instead of : 
**https://saptranslation-<your_trial_account_user>trial.hanatrial.ondemand.com/translationhub/api/v1**
I used : **https://saptranslation-<your_trial_account_user>trial.hanatrial.ondemand.com/**

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue.

If you still have questions, feel free to reopen the issue.
