### ISSUE TITLE
Build an SAP Fiori UX app with SAP Gateway data

### ISSUE THREAD

**Issue by JensHaley** [SAPDocuments/Tutorials#2221]
Hi there,

since the GW demo system ES4 was replaced by ES5 the last validation step does not work any longer.
(Otherwise replacing 4 by 5 is not a big deal)

Otherwise fine!

I wonder if you can also connect to other Fiori Reference Apps this way, for example, to the ODATA service for the shop app. I tried, but could not connect. Any ideas if this is possible using the GW demo system?

Thanks,
Jens

**Comment by mhassett92** [comment]
Hi Jen,

Thanks for letting us know! I have updated the validation to reflect the ES5 system data. Let me know if you can complete the tutorial now. 

Which Shop App are you interested in? You should be able to replicate this behavior for other OData services, but there might be a couple settings that need to be changed. 

Thanks!
Meredith
