### ISSUE TITLE
Step 8: Implement the copied code

### ISSUE THREAD

**Issue by goubin510** [SAPDocuments/Tutorials#2222]
Hi (again),

I fund another mistake in the tuto : **Using the SAP Fiori Mentor app**
(https://www.sap.com/developer/tutorials/fiori-ios-scpms-mentor.html)

I'm not using an Ipad so the mistake could come from here, but anyway...
I wanted to go through step 8, but I couldn't find : 
**Open the file ProductCategoriesMasterTableDelegate.swift under Demo > TableDelegates > MasterTableDelegates.**
But I found : **ProductCategories.storyboard under Demo > ViewControllers > ProductCategories**

in this controller I found the function I was suppose to replace but then step 9 where I changed the content of the previous code pasted.

But now when I compile the code it's fine but the app crash whenever I try to show the product categorie's

help ? :D

**Comment by qualiture** [comment]
It seems the tutorial was written with the v1.x version of the SDK, you should use the `ProductCategoriesMasterViewController.swift`file instead

The code in the tutorial also isn't optimised for the v2.x version, but should work just fine otherwise.. what error do you get upon crashing?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue.

If you still have questions, feel free to reopen the issue.
