### ISSUE TITLE
SAP HANA, express edition, in Google Cloud Platform Launcher (Database + XS Advanced)

### ISSUE THREAD

**Issue by Sushma1000** [SAPDocuments/Tutorials#2225]
Hi Lucia,
Thanks for detailed tutorial. Followed all steps but unable to connect to https://hxehost:39030/
As suggested, added external ip address to hosts file. Where i went wrong?

**Comment by Lsubatin** [comment]
Hi, What error do you get? What happens if you ping the external IP? And if you ping hxehost?
On the SSH console, can you share the results of the following commands as hxeadm?
>  ./HDB info
>  xs a

Cheers,
Lucia.

**Comment by Sushma1000** [comment]
Received error message, "This site can't be reached" on chrome browser. 
On SSH console, 
![image](https://user-images.githubusercontent.com/35324279/36063023-76bdb85a-0e9d-11e8-9eee-1b8d9ae8819d.png)

https://ssh.cloud.google.com/projects/maximal-marking-194604/zones/us-central1-f/instances/my-hana-xsa-vm?authuser=0&hl=en_US&projectNumber=920581637590

**Comment by Lsubatin** [comment]
Please perform the ping from the same machine from which you cannot access, like your laptop.

**Comment by Sushma1000** [comment]
![image](https://user-images.githubusercontent.com/35324279/36064032-069d9ff0-0eab-11e8-89e1-2a0b4df7a529.png)

**Comment by Lsubatin** [comment]
What about the other questions?

**Comment by Sushma1000** [comment]
Thanks Lucia, issue resolved.
Regards,
Sushma
