### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by kgorin8** [SAPDocuments/Tutorials#2226]
Hello.

Why is this https://www.sap.com/developer/progress.html not working?

**Comment by thecodester** [comment]
What seems to be the problem? Remember, you need to be logged in.

P.S.: Nice cat

**Comment by kgorin8** [comment]
I don't see any progress. Assuming I need to complete tutorials from here https://www.sap.com/developer/tutorial-navigator.html

**Comment by thecodester** [comment]
Yes. You can start with the tutorials currently in the AppSpace: https://www.sap.com/developer/app-space.html. We will be expanding the capabilities in the near future.

**Comment by kgorin8** [comment]
K, thanks
