### ISSUE TITLE
Installing SAP HANA, express edition with Docker - create hxeadm and sapsys

### ISSUE THREAD

**Issue by lbe** [SAPDocuments/Tutorials#2230]
After reading between the lines and back and forth a bit, I realized that I needed to create group sapsys and user hxeadm on my docker host server.

I am running on Debian 9 Stretch, so I used the commands

addgroup -GID 79 sapsys
adduser -UID 12000 -GID 79 hxeadm

These commands will work on Debian derived distributions but will vary for other linux distributions.

Cheers,

lbe

**Comment by andychoi** [comment]
For CentOS,
$ sudo groupadd --gid 79 sapsys
$ sudo useradd --uid 12000 --gid 79 hxeadm

**Comment by JCurrie27** [comment]
@andychoi - Thanks for the CentOS information here. I recommend adding these CentOS **addgroup** and **useradd** commands to a post on the Community (https://www.sap.com/developer/topics/sap-hana-express.community.html#community), if it's not posted already.
