### ISSUE TITLE
Installing SAP HANA, express edition with Docker - log into database

### ISSUE THREAD

**Issue by lbe** [SAPDocuments/Tutorials#2231]
As a HANA neophyte, it took me a while to determine the correct meaning of:

>You can log into the system database with the following command:
>hdbsql -i 90 -d <system_database> -u SYSTEM -p <password>
>
>You can log into your tenant database with the following command:
>hdbsql -i 90 -d <tenant_database> -u SYSTEM -p <password>

After a bit of trial and error and searching and cussing, I realized the following:
* <system_datase> = SYSTEMDB
* <password> = Password set in master_password file
* <tenant_database> = HXE

Additionally, I struggled while trying to connect HANA Studio to the HANA XE instance.  It took a bunch of searching to find a reference in blog showing to container name : port (i.e HXE:39017).  This worked to get me connected to the tenant, but I could not connect to the SYSTEMDB even though the reference indicated that SYSTEMDB:39041 in the tenant container name worked for them.

**Comment by aplata-sap** [comment]
Hi there,

Following step 7B in this tutorial: https://www.sap.com/developer/tutorials/hxe-howto-eclipse.html 

Systemdb should be SYSTEMDB:39017
and Tenantdb should be HXE:39041
