### ISSUE TITLE
Installing SAP HANA, express edition with Docker - persistence and restart

### ISSUE THREAD

**Issue by lbe** [SAPDocuments/Tutorials#2232]
Once I got the docker container with HANA XE up and running and finished a minimal amount of testing (creating a schema and some tables), I shut the container down using the docker stop command.  On the console where I issued the initial docker run ... command, I observed:

>Received signal: TERM
>Removing trap for signal EXIT ...
>Ignoring signals: QUIT INT TERM HUP ...
>Stopping HANA ...
>Initiating hard stop ...
>
>14.02.2018 05:48:41
>Stop
>OK
>Waiting for shutdown procedure to finish ...

However, I am not unable to get the container to stay up starting it with the docker start ... command.  It appears that I do have persistence date in the data and logs directory of my /hana/mounts directory.

What is the processing for starting up the container and restoring data from the persistence data?

Thanks!

lbe

**Comment by aplata-sap** [comment]
Hi there,

To start and restore from persistence data, create the container on the same mounts.
