### ISSUE TITLE
Translate a Java app: Can this be done through an API call?

### ISSUE THREAD

**Issue by akashSri92** [SAPDocuments/Tutorials#2235]
I have a use case in my project where we need the translated i18n.properties file for locales, like : 
i18n_de.properties

**Comment by thecodester** [comment]
@ianarm Can you look at this?

**Comment by ianarm** [comment]
Hi @akashSri92. Translating files using an API call is currently not supported, but it is something that we're working on. The 'translate' API in SAP Translation Hub requires you to add the individual texts that you want to translate to the request payload.
Best,
Ian

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue.

If you still have questions, feel free to reopen the issue.
