### ISSUE TITLE
Grunt Build in SAP Web IDE

### ISSUE THREAD

**Issue by pedrolopezbiedma** [SAPDocuments/Tutorials#2236]
I'm trying to use the grunt-sapui5-bestpractice-build to uglify ( mangle + remove comments ) my code but I'm not able do to it:

Since I haven't found any documentation about which parameters could have this plugin, I'm combining it with the grunt-contrib-uglify which I know that do have the uglify + mangle functionality.

When building my application, it seems that the grunt-sapui5-bestpractice-build already has "hide" a uglify task because is ignoring the one that I'm defining.

Would you have any documentation about the grunt-sapui5-bestpractice-build plugin? If not, could you help me performing this?

Thank in advance,
Pedro.

**Comment by thecodester** [comment]
This is the answer that I received:

The best practice is not extensible. So you cannot just add a task "uglify", for example: 
grunt.registerTask('default', [
        'uglify',
        'lint',
        'clean',
        'build'
    ]);

You may be able to add tasks w/o the best practice, not sure:
    grunt.loadNpmTasks('grunt-contrib-uglify');

If you want to follow up, I would open up a conversation in the community: https://answers.sap.com/questions/ask.html

Specifically you can contact Alex Avizov (https://people.sap.com/alex.avizov) or Yuval Morad (https://people.sap.com/yuval.morad).

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue.

If you still have questions, feel free to reopen the issue.
