### ISSUE TITLE
Add SAP HANA XSA Tutorial which explains how to create SAP Fiori Launchpad

### ISSUE THREAD

**Issue by seVladimirs** [SAPDocuments/Tutorials#2238]
The title should be self-explaining - would be nice to have the tutorial on SAP XSA Fiori Launchpad. Initial request I found here - https://answers.sap.com/questions/414917/can-someone-make-a-tutorial-for-adding-an-app-to-f.html 

If you agree, I can try to spend a little bit of my time in preparing the first draft.

**Comment by Lsubatin** [comment]
Hi, 

Although I can't commit into any dates as of now, I'll add this to my bucket list, I've seen some other requests for this.

Best, 
Lucia.

**Comment by ahmedkhan29789** [comment]
To create and configure FIORI Launchpad in HANA XSA i found a very concrete answer in this [blog](https://blogs.sap.com/2017/04/24/fiori-launchpad-in-sap-hana-2.0-sp01/) 

Now after setting up my FIORI Launchpad, I am trying to find a blog which would explain more how to add existing web applications to FIORI Launchpad
