### ISSUE TITLE
SAP HANA XS Advanced, create a user-provided anonymous service for SAP HANA database Schemas

### ISSUE THREAD

**Issue by lnryan** [SAPDocuments/Tutorials#2242]
Console Image in Step 3 is too small and illegible. Clicking on it doesn't open the link for zoom. Please can you make it legible?

**Comment by Lsubatin** [comment]
Hi Lindsey,

 Thanks for the feedback. I will take this into account for an update I am actually working on. In the meantime, if you right click on the image and choose open in new tab you may get a bigger picture. All it shows is the result of the xs cups command execution. 

best, 

Lucia.
