### ISSUE TITLE
Building freestyle IoT application

### ISSUE THREAD

**Issue by kuldeepdave** [SAPDocuments/Tutorials#2244]
Hi Vitaliy Rudnytskiy,

Thanks for the tutorial, However, I require some help in the following steps:

1) While executing the step 6 i.e customize the list of things, I am not receiving the dialog "A template will be created from selected control…" after entering the  /Things entity set in Query Designer for "ThingList Element">properties.

2) I am also not able to find the "Actions" for  higher element "ThingList" , so that I can enter the "Row select" details in Action configuration dialog. On My screen just "Properties" and "Event" tab is reflecting instead for Properties and Actions, as you mentioned in tutorials.

![image](https://user-images.githubusercontent.com/36690338/36538237-9c59158c-17f8-11e8-8d97-780ea39731f1.png)

Kindly let me know is I am going wrong in any steps!

regards
K. Dave

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
