### ISSUE TITLE
Set up SAP Data Hub, developer edition

### ISSUE THREAD

**Issue by ryw** [SAPDocuments/Tutorials#2246]
Trying to build docker image for Data Hub developer edition

`docker build --build-arg VORA_USERNAME=vora --build-arg VORA_PASSWORD=9ntRqRcjykG3sNaponV]7JNaKJ-h~ --tag datahub .`

Get this output no matter what username + password I provide:

```
Sending build context to Docker daemon   9.47MB
Sending build context to Docker daemon  876.9MB
Step 1/19 : FROM docker.io/debian:8.7
Get https://registry-1.docker.io/v2/library/debian/manifests/8.7: unauthorized: incorrect username or password
```

**Comment by thecodester** [comment]
@schneidertho Can you take a look at this?

**Comment by schneidertho** [comment]
Ry, 

Seems we have missed your question. Please apologize.

To the problem: this has nothing to do with the password that you provide in the build command (this password is only used much later)

The build command fails during the very first step when trying to pull a public repository from docker.io. This is strange. I never have seen this happening for the developer edition.

Which environment are you in (Windows, Linux, Mac)? Can you please run a **docker pull docker.io/debian:8.7** and let me know what happens.

Thanks
Thorsten 

@thecodester, @Sygyzmundovych

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue.

If you still have questions, feel free to reopen the issue.
