### ISSUE TITLE
SAP HANA XS Advanced, Creating a Node.js Module

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Tutorials#2247]
I think there may be an issue with the xso editor/validator.   When I cut and paste the purchaseOrder.xsodata - in the HANA Express 2.0 SPS2 (updated with the latest from HANA Express downloads)

`service {
    "PurchaseOrder.Header"
	  as "POHeader" navigates ("Items" as "POItem");

	"PurchaseOrder.Item"
	  as "POItem";

	association "Items" principal  "POHeader"("PURCHASEORDERID")
	multiplicity "1" dependent "POItem"("PURCHASEORDERID") multiplicity "*";
}
`
I get the error: 
XSODataValidator: {"i18nKey":"syntaxCheckAnnotationErrorMessage","arg":"\"PurchaseOrder.Header\""}

![issue with xsodata](https://user-images.githubusercontent.com/7725180/36637205-cd1f30f4-198b-11e8-9c15-85cbd0723e7b.png)

I am not sure why the issue is but if I add the namespace :: to the entity names, then the error goes away - so it seems the validator is looking for the namespace which seems like a bug in the XSODataValidator.

![issue with xsodata no error if namespace](https://user-images.githubusercontent.com/7725180/36637229-753f161e-198c-11e8-96d4-8db31ca248ad.png)

Have you seen this issue?

Regards,
Jay

**Comment by Lsubatin** [comment]
HI, Jay,  You can ignore that warning, the odata should build and work just the same, I had already reported this as I also think is a bug in the editor.

**Comment by jmalla** [comment]
Thanks Lucia!

**Comment by noorshaikh** [comment]
Hi ,
with the above I am having the below issue.  Appreciate your help to fix it. 

![Capture](https://user-images.githubusercontent.com/8439888/128790272-dafa0949-abef-402d-9e37-c20cc2b28086.PNG)
