### ISSUE TITLE
Build and run a hybrid app with SAP Web IDE and Hybrid App Toolkit

### ISSUE THREAD

**Issue by strawherotk** [SAPDocuments/Tutorials#2248]
Hello,

During this [tutorial](https://www.sap.com/developer/tutorials/hcpms-webide-hybrid-build.html), I can see how we run SAPUI5 app in native mobile app simulator.
But I still don't know how to covert the app using Cordova as [marketed in the tutorial series](https://www.sap.com/developer/groups/mobile-app-4.html). Instead, after completing this last tutorial in the series, the next series is Building ui5 labels, which is nothing to do with Cordova & native app deployment.

Looking for your support!
Thank you,
Victor.

**Comment by thecodester** [comment]
Thank you for your feedback. Because of the amount of time that has elapsed, we are closing the issue.  

If you still have questions, feel free to create a new issue.
