### ISSUE TITLE
Creating a new viz extension project

### ISSUE THREAD

**Issue by Deepti21456** [SAPDocuments/Tutorials#2251]
I am trying to develop login page in Visualization extension project.How can i achieve this.

**Comment by Sygyzmundovych** [comment]
Hi @Deepti21456 Could you please elaborate a bit more on what you are trying to achieve and with what SAP product? Thank you.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
