### ISSUE TITLE
Build an SAP Fiori UX app with SAP Gateway data

### ISSUE THREAD

**Issue by Bassbiene** [SAPDocuments/Tutorials#2254]
https://www.sap.com/developer/tutorials/teched-2016-4.html

I am trying to follow the tutorial group "Build an SAP Fiori app that consumes OData services, external mapping APIs and supports multiple languages."
Everything works fine until tutorial "Build an SAP Fiori UX app with SAP Gateway data". There my alpha-numerical string is not accepted. I checked, but I seem to miss my mistakes.
In the next tutorial "https://www.sap.com/developer/tutorials/teched-2016-5.html" I get 28 errors when pushing.

When deploying I don't get the option to navigate to the active version. And finally my app cannot be run from the Cloud Platform Cockpit. I get "HTTP Status 404 - Not Found" when clicking on my link "https://te2016-p2000134653trial.dispatcher.hanatrial.ondemand.com".

Can you please help me to fix the errors, so I can continue following the rest of the tutorial group?

**Comment by mhassett92** [comment]
Hi, this tutorial was updated to use the ES5 gateway service. Did you use sapes4 or sapes5? Your errors seem to indicate you are using the deprecated ES4 service.

**Comment by Bassbiene** [comment]
I tried again and made sure to select the ES5 gateway service. I still get the error. Which Browser should I use? Should I use the SAP WEB IDE Full-Stack instead of the "normal" one?
![app](https://user-images.githubusercontent.com/22747908/38236004-6be51cb4-3712-11e8-9c4b-4adaaac55853.PNG)
![tutorial](https://user-images.githubusercontent.com/22747908/38236050-8f19a254-3712-11e8-9c3b-39aac82c41c8.PNG)

**Comment by Gene5** [comment]
Hello mhassett92,

Is it possible to receive the complete code of this tutorial? I'm getting errors.

Regards,

Gene5

**Comment by mhassett92** [comment]
For the Baleda validation issue - after more detailed investigation, it looks like these key values are not static anymore. Please enter the following value as this is the "correct" answer: 0050568C901D1ED893B59409515780FA . We will be changing the validation rule in the future.

As for the errors - can you share a little bit more? When you followed along with the template, did you choose standalone or App for Fiori Launchpad? (Do you have an index.html file?) We try to avoid giving away the completed code as we want our developers to learn how to use the tools and software.

**Comment by Gene5** [comment]
Hi mhassett92,

Thank you for helping me. 
My Fiori App is not working at step 15 of the tutorial https://www.sap.com/developer/tutorials/teched-2016-6.html

According to this step I have to placed the following code:

---------------------

### <IconTabFilter id="iconTabBarFilter2" icon="sap-icon://map" text="{i18n>itf2Title}" tooltip="{i18n>detailIconTabBarAttachments}">
				<content>
					**<core:Fragment fragmentName="com.test.teched.view.Map" type="XML"/>**
						</content>
					</IconTabFilter>_
---------------------
![image](https://user-images.githubusercontent.com/38948053/39617517-5986831a-4f80-11e8-8066-838e1c048c4f.png)

When I use this line of code, my Fiori App is not working!

Hopefully you can help me with this problem, so that I can see the Google Maps API working in my Fiori App.

//Regards,

Gene5

**Comment by mhassett92** [comment]
Gene5, Please open another issue as you are not reporting the same issues here, and I would like to continue to help Angela with her issue. Also, when reporting issues please include errors you are seeing and well as code snippets from your application. 
Thank you,
Meredith

**Comment by Bassbiene** [comment]
Hi Meredith,

after your last post I have opened https://www.sap.com/developer/tutorials/teched-2016-4.html, opened step 18 and posted your alpha-numeric string. It still says that my response is invalid :-D Could it be that is is not working, because I have not gone through the other steps again?

![image](https://user-images.githubusercontent.com/22747908/39741820-984b9d6a-529b-11e8-9e12-aba398756164.png)

As you have already identified, that there is a small problem with the validation, it would be okay for me if you closed the ticket. Thanks for your time and effort!

**Comment by mhassett92** [comment]
Hi Angela, Are there trailing or starting space from the copied answer? The validation system is extremely strict :) Unfortunately, I can't force the validation from my side. If it is still causing problems, I will update the rule on Monday and you should be able to get credit then. Sorry about all the trouble!
Thanks,
Meredith

**Comment by mhassett92** [comment]
The validation rule has been updated - closing this now. Please re-open if you are still having issues!
