### ISSUE TITLE
SAPUI5 - Display List Element Details

### ISSUE THREAD

**Issue by goubin510** [SAPDocuments/Tutorials#2258]
Does those tutorials present the bests practices ? or just the dirtiest way to get things done ? cause copy pasting code without any explanation is the best way to get people giving up... this one is brand new and already out of date... is this being done by interns ?

**Comment by thecodester** [comment]
The tutorials are provided to offer a quick view of new technologies and new features, and the priority is to make it easy and fast to learn, understand and see the benefits of the technologies. If there is something wrong or out of date, please let us know and we can adjust the tutorial.

P.S.: The tutorial was first published in June 2016. The date shown is the most recent update; we continuously make updates to the tutorials.

**Comment by jonathanbaker7** [comment]
This tutorial is actually quite old, and it's probably overdue for a refresh.   But it still works, and so we are leaving it in place.  

It's purpose was to get users up and running on SAP UI5 quickly, and also to provide a comparison between different technologies (Angular, React, and UI5).  It's not meant as a best practice, so don't use it as "this is the best way", but more of "this is a fast way to get this part up and running".

Oh, and our interns are great.  They are all very careful, and highly qualified, and their tutorials are pretty good.  As Bill Gates once said, “Be nice to nerds. Chances are you’ll end up working for one.”

If you have other questions, or any suggestions for updating this tutorial, please re-open this bug or start a new one.
