### ISSUE TITLE
Create an API Proxy

### ISSUE THREAD

**Issue by bcschaich** [SAPDocuments/Tutorials#2260]
On  Step 6: Discover the services when pressing the button I get this error:

while trying to invoke the method org.apache.olingo.odata2.api.edm.EdmEntitySet.getEntityType() of a null object loaded from local variable 'entitySet' [Request ID: 1a134d2d-6d8f-4bff-a6e3-d5bcad7ada62]

Anybody knows what happened?

**Comment by mhassett92** [comment]
Hi, looking at this tutorial, I noticed it was originally a ES_. Are you using the ES5 endpoint? The screenshots do show ES4, but that system has been sun-setted.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue.

If you still have questions, feel free to reopen the issue.
