### ISSUE TITLE
How to prepare HANA, express edition environment for tutorials

### ISSUE THREAD

**Issue by ceerix** [SAPDocuments/Tutorials#2261]
[quote]
Step 1: Review system configuration
Review default system configuration for HANA, express edition:
[unquote]
I would like review the system configuration BUT which command is necessary? 

[quote]
Step 2: Create user
% hdbsql -i 90 -n localhost:39013 -u SYSTEM -p <SYSTEM user password>  "CREATE USER WORKSHOP_01 PASSWORD <password> NO FORCE_FIRST_PASSWORD_CHANGE SET PARAMETER XS_RC_XS_CONTROLLER_USER = 'XS_CONTROLLER_USER' , XS_RC_DEVX_DEVELOPER = 'DEVX_DEVELOPER', XS_RC_XS_AUTHORIZATION_ADMIN = 'XS_AUTHORIZATION_ADMIN'"
[unquote]

Is it possible to Copy&Paste from Windows host into the Linux terminal? If yes, how?

**Comment by Lsubatin** [comment]
HI,

I am not sure what version you are trying to install but you do not need to execute that SQL statement in the latest versions.

Also, it is not possible to copy and paste straight into VMware for example. You can use a program such as PuTTY which will allow you to connect to the terminal, copy and paste (using the right click). However, unless you are using SPS12, that step should not be necessary.

Could you please tell us how you got there?

Thanks, 

Lucia.

PS: In the future, the proper forum to get support from the community is answers.sap.com

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
