### ISSUE TITLE
Import your SAP Build project into SAP Web IDE

### ISSUE THREAD

**Issue by michal-keidar** [SAPDocuments/Tutorials#2262]
I think more details should be provided on the destinations, for example that the "SAP Web IDE Plugin" destination is only required for the old SAP Web IDE (it's not required for Web IDE Full-Stack). And the UI5 destinations are only required when creating a smart app (are they really required for this tutorial?).
More details on the destinations can be found in Build's documentation:
https://sap.github.io/BUILD_User_Assistance/build/external/4be99e779fcb4ff9a8e5179b74bd72cc.html
Also I just tried this tutorial and when running the app I got an error (metadata not found), which makes sense since there's no service.. How did the preview work? I guess the "testFLPServiceMockServer.html" file should be selected?

**Comment by thecodester** [comment]
Thank you for your feedback. Because of the amount of time that has elapsed, we are closing the issue.  

If you still have questions, feel free to create a new issue.
