### ISSUE TITLE
Change from mock server to live OData service

### ISSUE THREAD

**Issue by lutraki-yavan** [SAPDocuments/Tutorials#2263]
3 updates (that I noticed):
- There's no server.init anymore in the Component.js
- In the manifest.json there's no "main" data source
- In the Detail controller, no "expand" property in the oParams variable

Thanks

**Comment by mhassett92** [comment]
Hi Michal,

Apologies for the long delay in getting back to you on this. I ran into a bunch of issues with BUILD, and have finally been able to work past them. I have updated the tutorial to reflect the differences you pointed out as well as the new changes that need to be made for this tutorial to work. Let me know if you are still having issues! 

Thank you!
Meredith
