### ISSUE TITLE
Prepare to create workflows in SAP Cloud Platform

### ISSUE THREAD

**Issue by AstridHerbst** [SAPDocuments/Tutorials#2264]
Curious to see how this comment will reach me.

**Comment by thecodester** [comment]
@AstridHerbst It's a little weird that you would get a notification for an issue you wrote :-) 

First, if someone else wrote a comment for you, I would assign it to you and you would be notified. Second, any comments or actions on the issue you would get a notification, like right now.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue.

If you still have questions, feel free to reopen the issue.
