### ISSUE TITLE
Getting started with SAP Cloud Platform Rapid Application Development by Mendix

### ISSUE THREAD

**Issue by Adam-Dupaski** [SAPDocuments/Tutorials#2265]
Hello, I am a technical writer at Mendix. The screenshot in step 6 needs to be updated for the correct name of the SAP Blank app:
![image](https://user-images.githubusercontent.com/20336433/37290170-c9b9ae94-260b-11e8-8219-5242970430f6.png)
Thank you.

**Comment by thecodester** [comment]
I have updated the image, though it appears in Step 5, no? 

There is a server cache for a week, so it might be that it won;t update for up to a week. If you still see the issue, feel free to reopen the issue.
