### ISSUE TITLE
Image Similarity Scoring ML service with SAPUI5

### ISSUE THREAD

**Issue by Alexandre-Lara** [SAPDocuments/Tutorials#2272]
Hi guys, 

I hope you're doing fine. I came here to report a problem that is happening in the current Image Similarity Scoring ML tutorial. The relative Leonardo APIs changed the JSON response model/pattern.
What I had to change in the projet to get it working:

At onPressScoreSimilarity function: data.similarityScoring -> data.predictions
At onPressExtractFeatures function: data.feature_vector_list -> data.predictions

I'm open to any question you have about this, 

Kindly regards, 
Alexandre

**Comment by adadouche** [comment]
good catch! Thanks

The API has changed despite the fact that the doc still reflect the old format.

I'll send a note to the PO to update the doc on the API Hub, and I will commit and push the tutorial change as well.

Thanks again
