### ISSUE TITLE
Install SAP HANA, express edition on Ubuntu on Google Cloud Platform (Core Database)

### ISSUE THREAD

**Issue by cocopapagal** [SAPDocuments/Tutorials#2273]
Very good tutorial! Great job!

Thank you very much!

One question please: did you succeed to map your HXE internal IP to the external one provided be google cloud platform?

In my case all HXE services are running on the internal IP, therefore i cannot access them externally.

Thank you once more!

**Comment by Lsubatin** [comment]
Hi there, What do you mean by "ervices are running on the internal IP, therefore i cannot access them externally."?

Did you configure the firewall? Which services/ports cannot you access externally? Have you checked this https://blogs.sap.com/2018/02/24/troubleshooting-connection-problems-for-hana-express/ ?

**Comment by cocopapagal** [comment]
Hi Lucia,
you are fully right! Thank you very much and sorry for wasting your time.
Indeed, firewall port exception was my problem. 

You are the best!
