### ISSUE TITLE
Installing SAP HANA, express edition with Docker - Step 2 Download the SAP HANA, express edition Image from the Docker Library

### ISSUE THREAD

**Issue by gsgxnet** [SAPDocuments/Tutorials#2277]
both the search at and later the pull from **Docker Library** need an Docker account and logins. 

`docker login` to pull image:
```
Login with your Docker ID to push and pull images from Docker Hub. If you dont have a Docker ID, head over to https://hub.docker.com to create one.
Username: <user>
Password: <password>
Login Succeeded
```

might be helpful to include these steps into the tutorial

**Comment by aplata-sap** [comment]
I'll add a step to log into Docker. Thanks!

**Comment by JCurrie27** [comment]
Documentation updated - closing issue.
