### ISSUE TITLE
Topic Detection ML service with SAPUI5

### ISSUE THREAD

**Issue by 76lara** [SAPDocuments/Tutorials#2281]
Hi,

I have followed the exercise, but when I have to test the application I just got an error message 405. Could you create a GIT link with the version of your code for me to clone it?

I have compared my code with the one in the GIF repository and they are the same. Could you guide on what I can check next?

Thanks so much:

Luis Lara.

**Comment by adadouche** [comment]
Hi,

Sorry I missed this issue.

405 usually means that you are trying to use a HTTP method not supported by the endpoint service. For example you are using a GET when only POST is supported.


The solution code is available [here](https://github.com/SAPDocuments/Tutorials/tree/master/tutorials/ml-fs-sapui5-topic-detection/sapui5ml-topicdetection).

You might be having a similar prolem to [issue 1864](https://github.com/SAPDocuments/Tutorials/issues/1864).

I think you have missed to add the following section to your manifest file as described in step 9:
"demo": {
  "type": "sap.ui.model.json.JSONModel",
  "preload": true,
  "uri": "model/demo.json"
}
Can you check and let me know?

Thanks 

@bdel

**Comment by adadouche** [comment]
Any updates? I'll close this, but feel free to reopen.
