### ISSUE TITLE
Catalog tile is not available .

### ISSUE THREAD

**Issue by mahaksharma** [SAPDocuments/Tutorials#2282]
How to complete step5

**Comment by mahaksharma** [comment]
I got up with 403-Forbidden (sever cannot fulfill request).How to resolve this error?

**Comment by thecodester** [comment]
Which tutorial is this about? Can you enter a link to it?

**Comment by mahaksharma** [comment]
Is there any authentication failure occurence in Step 10.I'm not able to access SAP cloud platform when running app on simulator.

**Comment by mahaksharma** [comment]
The SAP Geofence app tutorial(https://www.sap.com/india/developer/tutorials/fiori-ios-scpms-geolocation.html)

**Comment by qualiture** [comment]
@mahaksharma 

Which credentials did you specify here? You should login with the SYSTEM user.

Also, make sure you have assigned the proper authorisations as outlined in step 4

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue.

If you still have questions, feel free to reopen the issue.
