### ISSUE TITLE
Connect to OData service on Neo using SAP S/4HANA Cloud SDK

### ISSUE THREAD

**Issue by niklas1375** [SAPDocuments/Tutorials#2284]
Since lombok 1.16.20 there's a problem with the deserialization of the answer from the OData service (see https://github.com/rzwitserloot/lombok/issues/1563). Hence this implementation will throw an error.

**Comment by thecodester** [comment]
@019a Olga, can you take a look at this?

**Comment by niklas1375** [comment]
I managed to create a workaround but it's not pretty. You have to use the JsonDeserializer annotation, create an internal class for this and write your own Constructor with the Builder annotation (for reference see the linked issue). 
I know that the error is not your fault but I thought you'd like to know.

**Comment by 019a** [comment]
Thank you for the feedback and for bringing this to our attention! In the latest version of the tutorial, available from https://blogs.sap.com/2017/05/21/step-4-with-sap-s4hana-cloud-sdk-calling-an-odata-service/, we no longer use Lombok directly but propose to use the Java virtual data model (VDM) of the SAP S/4HANA Cloud SDK. Thus, the issue does not occur there.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue.

If you still have questions, feel free to reopen the issue.
