### ISSUE TITLE
Build a geofencing app

### ISSUE THREAD

**Issue by palakagarwal15** [SAPDocuments/Tutorials#2285]
Authentication failure in step 10 in simulator.
Please specify the credentials that need to be entered by giving example

**Comment by qualiture** [comment]
Hi @palakagarwal15 

You need to login with your SAP Cloud Platform credentials (same you used in Step 1)

**Comment by palakagarwal15** [comment]
after entering the credentials. I am being authenticated and thereafter an "http status 404 - not found" error is received in the red block.

**Comment by qualiture** [comment]
Where do you get the 404 error from? The authentication, or the retrieval of the OData service?

Can you check whether your HANA MDC is still running, and you can access your OData service?

**Comment by palakagarwal15** [comment]
HANA MDC is still running but for OData Service, my xml was not created(I dont know why), so i asked my friend to create it for me from his id. Thereafter i used that xml file in my project.. Will that affect?? 404 error is after logging the page and then a blue dialog is shown "You are being authenticated" and thereafter "404 error is found"

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue.

If you still have questions, feel free to reopen the issue.
