### ISSUE TITLE
HTTP Status 404 not found

### ISSUE THREAD

**Issue by mahaksharma** [SAPDocuments/Tutorials#2288]
After completing step 9 and adding my sap cloud platform credentials in step 10 i'm receiving http status 404 not found.

**Comment by thecodester** [comment]
What tutorial is this about? 

P.S.: The automatically generated title lets us know what tutorial you are referring to. If you change, we won;t know. If you want to add to it, that is fine.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue.

If you still have questions, feel free to reopen the issue.
