### ISSUE TITLE
Build an SAP Fiori UX app with SAP Gateway data - Error validating step

### ISSUE THREAD

**Issue by dirugadr** [SAPDocuments/Tutorials#2289]
Hello,
I'm having an issue with "Step 18: Confirm your app looks like the example" from Build an SAP Fiori UX app with SAP Gateway data tutorial (https://www.sap.com/developer/tutorials/teched-2016-4.html) The alpha-numeric string copied is the right one, but the validation fails. Please see attached images.
Thanks,
Adrian

![capture_2](https://user-images.githubusercontent.com/16107164/37778204-1de82e8c-2dc8-11e8-8fbb-f53fc79cfab9.PNG)
![capture_1](https://user-images.githubusercontent.com/16107164/37778205-1e2a0834-2dc8-11e8-8d94-9d224f2a4c44.PNG)

**Comment by mhassett92** [comment]
Hello,
It looks like the validation had not been updated for the new ES5 service. I have updated the rules, and you should soon be able to successfully submit the step. Let me know if it works for you now!
Thank you!

**Comment by dirugadr** [comment]
Hello,
I'm afraid it's still failing:

This is the code for the partner contact:


And this is the response when I paste it and validate it in step 18 of the
tutorial:

Regards,
Adrian

**Comment by mhassett92** [comment]
Hi Adrian, The code is not showing up. The ID does look wrong based on the backend I am looking at. Can you reshare your code for that? Also can you include the URL of the partner contact? You can find it on the network tab on the Developer Tools pane. Thanks! Meredith

**Comment by dirugadr** [comment]
Hi,
Below you'll find the images:

![image](https://user-images.githubusercontent.com/16107164/38262952-06389a3e-3745-11e8-8655-1ff45456aabc.png)

Failed when I pasted it and tried to validate it:
![image 1](https://user-images.githubusercontent.com/16107164/38262988-1ec378da-3745-11e8-868d-1c296de1f713.png)

The URL of the partner contact is: https://webidetesting6955112-p252106trial.dispatcher.hanatrial.ondemand.com/webapp/index.html?hc_orionpath=%2Fp252106trial%24P252106-OrionContent%2Fte2016&origional-url=index.html&sap-ui-appCacheBuster=..%2F..%2F&sap-ui-xx-componentPreload=off#/BusinessPartnerCollection/0050568C901D1ED88DDC58E998A0A0FA

Regards,

**Comment by mhassett92** [comment]
Apologies for not getting back sooner on this. After more detailed investigation, it looks like these key values are not static anymore. Please enter the following value as this is the "correct" answer: 0050568C901D1ED893B59409515780FA

We will be changing the validation rule in the future.

Thank you!
Meredith
