### ISSUE TITLE
Commit your project to Git and deploy to the cloud - Error 404

### ISSUE THREAD

**Issue by dirugadr** [SAPDocuments/Tutorials#2290]
Hi,
After I completed all the steps of tutorial "Commit your project to Git and deploy to the cloud" (https://www.sap.com/developer/tutorials/teched-2016-5.html), I'm having an error "HTTP Status 404 not found" when I open the URL of my web app (Step 18: Open the active version of your app). If I try it from the web ide env, it runs without issues. Please see attached images.

![capture_3](https://user-images.githubusercontent.com/16107164/37781698-fb12a47a-2dcf-11e8-8292-ea07bcbfc9f1.PNG)
![capture_1](https://user-images.githubusercontent.com/16107164/37781700-fb5f807e-2dcf-11e8-937d-d9f51ab0966c.PNG)
![capture_2](https://user-images.githubusercontent.com/16107164/37781702-fba58808-2dcf-11e8-92e5-02804aca6012.PNG)

**Comment by jonathanbaker7** [comment]
OK.  So (and you probably already know this) there are two different URL's.  The one in the first image works, the one in the third image doesn't.

Step 18 says "In the Successfully Deployed confirmation dialog".    Is that where you got the URL that creates the 404-not found?

**Comment by dirugadr** [comment]
Hi,
Yes, this is correct. The error happens when I try to open the URL:
https://te2016-p252106trial.dispatcher.hanatrial.ondemand.com

![image](https://user-images.githubusercontent.com/16107164/37913759-043f219e-30ec-11e8-9943-c03847d2c7db.png)

Thank you

**Comment by jonathanbaker7** [comment]
OK, I'm not sure how you are getting there, but I think I have an idea.

The URL from the link above is from the SAP Cloud console.  But, in the tutorial, it's using a link from the dialog box (the one that deploys the application) which is inside the WebIDE application.

Have you tried deploying this from inside the WebIDE?  The dialog box should look like this one:

![image](https://user-images.githubusercontent.com/3226389/37988264-778ab31a-31ce-11e8-8e97-3607e1d563c0.png)

Let me know.  Thanks!

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue.

If you still have questions, feel free to reopen the issue.
