### ISSUE TITLE
Topic Detection ML service with SAPUI5

### ISSUE THREAD

**Issue by 76lara** [SAPDocuments/Tutorials#2291]
Hi,

I have followed the instructions for this blog, but when I finally test the application, I just got an error message 405.

Best Regards:

Luis Lara

**Comment by adadouche** [comment]
Hi @76lara ,

Can you open your browser developer tools and inspect the "/inference_sync" request there?
You can filter to keep only XHR requests.

The method should be a POST as documented in the SAP API Business hub : https://api.sap.com/shell/discover/contentpackage/SAPLeonardoMLFunctionalServices/api/topic_detection_api

Thanks

@bdel

**Comment by 76lara** [comment]
Hi,

There is an issue loading the resources:

**sap-ui-core.js Failed to load resource: the server responded with a status of 404 (Not Found)
send @ jquery-dbg.js:9203
/webapp/undefinedjs/piwik.js Failed to load resource: the server responded with a status of 404 (Not Found)**
privacy.js:8 Uncaught TypeError: swa.jQuery is not a function
    at privacy.js:8
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:908 deviceready has not fired after 5 seconds.
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:901 Channel not fired: onPluginsReady
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:901 Channel not fired: onCordovaReady
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Battery
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Camera
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Contacts
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Device
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Compass
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Accelerometer
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Notification
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for File
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for FileTransfer
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Geolocation
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Globalization
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Media
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Capture
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for NetworkStatus
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for SplashScreen
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for StatusBar
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Vibration
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for AppPreferences
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for AppUpdate
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for AuthProxy
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for BarcodeScanner
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for CacheManager
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for EncryptedStorage
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for i18n
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for InAppBrowser
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Logging
3sap-ui-core.js Failed to load resource: the server responded with a status of 404 (Not Found)
send @ jquery-dbg.js:9203
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for MAFLogonCoreCDVPluginJS
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for OData
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for SMPPushPlugin
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for toolbar
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for E2ETrace
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Calendar
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for VoiceRecording
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/cordova.js:868 adding proxy for Printer
**/ml/topicdetection/inference_sync Failed to load resource: the server responded with a status of 405 (Method Not Allowed)**
webide-p1940400351trial.dispatcher.hanatrial.ondemand.com/plugins/pluginrepository/hybrid/cordovafacade/plugins/cordova-plugin-file/www/browser/Preparing.js:170 Persistent fs quota granted

**Comment by adadouche** [comment]
Hi @76lara 

Thanks for your prompt response. Can you switch to the ***Network*** tab, and then inspect the request?

This is an example with Chrome:
![image](https://user-images.githubusercontent.com/1446764/37898096-332ebedc-30e8-11e8-960a-55cec8f3e3eb.png)

**Comment by 76lara** [comment]
Hi.

Thanks for your response.

The call is returning the message 503 (Service Not Available).








Best Regards:

Luis Lara.


2018-03-26 20:24 GMT+11:00 Abdel Dadouche <notifications@github.com>:

**Comment by adadouche** [comment]
Hi @76lara,

I'm back from paternity leave which explains the delay in my response.

Just wanted to check if you managed to fix the issue.

If not let's try to continue the investigation together.

503 usually means that something is not properly defined with the destination either on the SAP Cloud Platform Cockpit or within the manifest.json.

I can see from the previous log that you are trying to build an hybrid app (using Cordova). 
Can you try with a simple SAPUI5 application where the Hybrid App Toolkit is disabled?
Alternatively, can you try to download the solution files and import them as is in your WebIDE.

Thanks

@bdel

**Comment by adadouche** [comment]
Any updates? I'll close this, but feel free to reopen.
