### ISSUE TITLE
Use a message broker

### ISSUE THREAD

**Issue by wingedRuslan** [SAPDocuments/Tutorials#2292]
SAP DataHub -- Use a message broker

Followed all the steps in the tutorial, but unsuccessfully 

The created pipeline is dead:

Message
test.myFirstPipeline.Kafka Consumer: kafka: error while consuming sensordata/-1: zk: node does not exist

What can be the problem?

Many thanks in advance

**Comment by thecodester** [comment]
@schneidertho Thorsten, can you respond?

**Comment by schneidertho** [comment]
Hi. Sorry for the very late reply. 2 months is definitely too late. We clearly missed to see your question earlier. 

To the point: typically that message indicates that the pipeline cannot reach Kafka (it is either not running, not running in the same network etc.)

Did you pull the kafka image as described in the tutorial and did you start a container based on that image in the same Docker network you run the developer edition container in?

In general, https://blogs.sap.com/2017/12/06/sap-data-hub-developer-edition/ is IMO a better place for questions. We typically respond there within a couple of days. But again apologies that we did not see your question earlier.

Best regards
Thorsten

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
