### ISSUE TITLE
Building freestyle IoT application

### ISSUE THREAD

**Issue by patrickfontdean** [SAPDocuments/Tutorials#2293]
Hi there, been looking at the "Building a Freestyle IoT App", and looks like the Web IDE is subtly different in a few ways from what's shown in the tutorial (could just be me... or some setting... or using Chrome instead of IE... I don't know!)

e.g. Step 6, when entering the list of /Things, I don't get any "expand associations" option, but I can see properties in the properties dropdown.

Last part of Step 6, when setting up the "Refresh action, the dropdown icon is subtly different (three vertical dots in my WebIDE, Stacked Squares, and to get to what the documentation describes, had to go via "wire to action" which matches the screenshot given...

Additionally, should there be some mapping of data to the IoT Sensor graphic? From the tutorial it looks as if it just 'knows' which sensor it's looking at, and what value to graph, though in my experience it's rarely that simple - hey, maybe this tool is amazing and does just know, but I suspect not!

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
