### ISSUE TITLE
Installing SAP HANA 2.0, express edition (Binary Installer Method)

### ISSUE THREAD

**Issue by amitabak** [SAPDocuments/Tutorials#2296]
Link to relevant JAM group as to post questions etc ? 
Not clear if we can tryout Dynamic Tiering and Hadoop integration using the express edition

**Comment by aptk001** [comment]
You can find the feature scope description here: [https://help.sap.com/viewer/32e387b229ec4ec0bbfdcd200af0ac5b/2.0.02/en-US](https://help.sap.com/viewer/32e387b229ec4ec0bbfdcd200af0ac5b/2.0.02/en-US). Dynamic tiering isn't available in HXE.

To post questions, use the community section of the HANA express page: [https://www.sap.com/developer/topics/sap-hana-express.community.html](https://www.sap.com/developer/topics/sap-hana-express.community.html)

**Comment by JCurrie27** [comment]
Closing issue.
