### ISSUE TITLE
SAP HANA XS Advanced, Creating an HDI Module

### ISSUE THREAD

**Issue by Reshandre** [SAPDocuments/Tutorials#2297]
You need to correct

SEQUENCE  "HANA_2_SPS1.db.Data::orderId"
INCREMENT BY 1 START WITH 200000000
MINVALUE 1 MAXVALUE 2999999999
NO CYCLE
RESET BY
SELECT IFNULL(MAX(PURCHASEORDERID), 0)+1
FROM "HANA_2_SPS1.db.Data::PurchaseOrder.Header"

**Comment by Lsubatin** [comment]
The tutorial explicitly instructs you to avoid namespaces. Thank you for the suggestion, though.
