### ISSUE TITLE
SAP HANA XS Advanced - Clone and run SHINE applications

### ISSUE THREAD

**Issue by ShushantaMohapatra** [SAPDocuments/Tutorials#2299]
Hello Lucia,

Your tutorial helped me a lot. Thank you very much for detailed step.

I am stuck at the last step of running index.html. I have updated the version in mta.yaml as suggested by command xs mtas in CLI.
![image](https://user-images.githubusercontent.com/38055025/38279637-cfa8292e-37be-11e8-99aa-5a9613193430.png)

Configuration in mta.yaml 
![image](https://user-images.githubusercontent.com/38055025/38279683-fc76f390-37be-11e8-9ff3-22b8c01f80bf.png)

Still I am getting error stating below.
Parameters of the configuration resource sapui5-provider in the mta.yaml file do not match any deployed MTA module. Make sure that the referenced MTA is deployed, and that the parameters match its properties.

Could you please help.

Thanks and Regards,
Shushanta Mohapatra

**Comment by Lsubatin** [comment]
Hey, the first screenshot is showing the MTA version for the di-builder (which is way higher than the current versions of SAPUI5). 

 You need to check the version for an mta called like the provider-id (com.sap.ui5.dist.sapui5 .. etc). Also, this kind of question. 

Cheers, 

Lucia.
