### ISSUE TITLE
Set up SAP Data Hub, developer edition

### ISSUE THREAD

**Issue by ansgarmax** [SAPDocuments/Tutorials#2303]
The User Credentials should be set up with your Docker ID and Password. 
This worked out for me:
docker logout
Create Docke Account and LookUp your ID (not same as ur mailaccount).
docker login (with your Docker Cred)

Insert your Docker Cred in the DataHub Dev Docker File under "VORA USERNAME" etc.

**Comment by thecodester** [comment]
@schneidertho Can you address this issue?

**Comment by schneidertho** [comment]
The VORA username is completely independent from any user on Docker.  You don't have to have a "matching" Docker user for the VORA username / password

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
