### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by Teslade** [SAPDocuments/Tutorials#2306]
Hi Currie, I'm Alan Liu, thanks for the valuable tutorial! I follow the guide and seems that there are something missing in the command:
in Step 6, it should be _sudo docker exec -it -u  **`<sidadm>`**  <container_name> bash_
example: _sudo docker exec -it -u hxeadm express_edition bash_

Regards,
Alan

**Comment by JCurrie27** [comment]
Assigning to Adrian for investigation and follow-up.

**Comment by aplata-sap** [comment]
Hi there,

You actually don't need the _-u_ in the command, as once you log in to the container, you're automatically logged in as _hxeadm_. We'll be updating the documentation to reflect this with the next release.

Thanks!
