### ISSUE TITLE
Create an Xcode project with SDK Assistant

### ISSUE THREAD

**Issue by Hoofer2018** [SAPDocuments/Tutorials#2307]
Dear Robin

Thank you for creating a comprehensive set of introductory tutorials for "Fiori fo IOS SDK"

I am currently going through https://www.sap.com/developer/tutorials/fiori-ios-scpms-deliveryapp-part2.html, however it seems as if I do not have  access to the oData service provided:

https://sapdevsdd27584c4.us2.hana.ondemand.com/codejam/wwdc/services/DeliveryService.xsodata

I do have a SAP trial account. When running the application I get error:

DataServiceError: Error 500 - Service exception 414 - user is forced to change password.

Please advise how I can get access to the  sample oData service. 

Thanks in advance

Mike

**Comment by qualiture** [comment]
Hi @Hoofer2018,

I have contacted the responsible for the service. I'll let you know once available again

**Comment by qualiture** [comment]
Hi @Hoofer2018,

The password has been reset, you should be able to access it again :)

**Comment by Hoofer2018** [comment]
Dear Robin

Thanks for completing - application has been created successfully, and these are a great introduction for Fiori for IOS. 

FYI needed to make small adjustment using Xcode 9.2 in Step 20 of tutorial https://www.sap.com/developer/tutorials/fiori-ios-scpms-create-demo-app.html

and needed to do a couple of small changes in the "TableDetailController.swift" to get the demo working

let currentEntity = self.selectedEntity as? PackagesType

was replace with: let currentEntity = self.entity as? PackagesType 

and

trackingInfoView.entities = try self.deliveryService.service.deliveryStatus(query: query)

was replaced with:

trackingInfoView.entities = try self.deliveryService.fetchDeliveryStatus(matching: query)

Thanks again.

Mike
