### ISSUE TITLE
Create sales order app with SAP Cloud Platform Rapid Application Development by Mendix

### ISSUE THREAD

**Issue by MarkvanMents** [SAPDocuments/Tutorials#2308]
![sap - create sales order - step 6](https://user-images.githubusercontent.com/35492184/38682258-e9d15f48-3e6a-11e8-9be8-886b390bdca9.png)

A couple of issues with step 6:

Point 1 reads like we are adding an activity to a microflow called **Get List** when we are actually adding an activity of **Get List** to the microflow **ACT_...**

The URL we want to execute is not **.../$metadata** but **.../SalesOrder**

**Comment by lutraki-yavan** [comment]
Hi Mark, I will fix it, thanks

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue.

If you still have questions, feel free to reopen the issue.
