### ISSUE TITLE
Enhancing the persistence layer for multi-tenency

### ISSUE THREAD

**Issue by BiertzM** [SAPDocuments/Tutorials#2310]
Hello there,
I got an issue here that the Favorite City Service can't be found...

HTTP Status 500 - No Resource class com.sap.hana.cloud.samples.weatherapp.api.FavoriteCityService can be found

May you help me out here? Since I can't figure out how to solve this.

Thanks in advance.

**Comment by thecodester** [comment]
Thank you for your feedback. Because of the amount of time that has elapsed, we are closing the issue.  

If you still have questions, feel free to create a new issue.
