### ISSUE TITLE
Info on what trial to use missing

### ISSUE THREAD

**Issue by Jennylundbergs** [SAPDocuments/Tutorials#2317]
In the tutorial: Image Classification with SAP Leonardo Machine Learning Foundation in SAPUI5 Step 3: Access the SAP Cloud Platform Cockpit. It's not obvious that you should use the NEO trial account. Would be good to get this clarified. 

Kind Regards / Jenny

**Comment by adadouche** [comment]
I have added the Neo reference in most tutorial I own, along with the direct url to the Neo Cockpit
Committed change 
: https://github.com/SAPDocuments/Tutorials/commit/f59e7ea5065cfd8c0d1db32c85acc24226c639d4
