### ISSUE TITLE
Installing and Configuring the Streaming Studio Plugin

### ISSUE THREAD

**Issue by vliu715** [SAPDocuments/Tutorials#2333]
Hi,
I installed hana express & streaming analytics on Google cloud.  Everything seems working except hana studio is unable to connect to port 39026.  The service "esps:hxehost:39026" failed to login server.  "esp" does not work, either.

The tcp port 39026 is in Google cloud default network firewall setting; however, I am unable to detect port 39026 is listening (not sure the command I used correct or not).

Please advise.  Thank you!
Vivian

**Comment by Lsubatin** [comment]
Hi, 

These questions belong in the Questions & Answers (https://answers.sap.com/index.html ). There are more people monitoring there and we can ask the specialists to respond there.

Thanks, 

Lucia.

**Comment by JCurrie27** [comment]
Hi vliu715 - many thanks if you could move your question to the Q&A board as Lucia suggests. Closing this issue.
