### ISSUE TITLE
SAP HANA XS Advanced - Clone and run SHINE applications

### ISSUE THREAD

**Issue by KlausZeuch** [SAPDocuments/Tutorials#2334]
Great tutorial, unfortunately step 5 (build core-db module) fails in Hana 2 Express SPS03 at GCP with 

Deploying "src/models/spatial/REGION_PRODUCT.hdbcalculationview"...     Error: com.sap.hana.di.role: Could not create the role definition in the database [8254541]       at "src/roles/admin.hdbrole" (0:0)      Error: com.sap.hana.di.role: "TRIGGER": invalid schema privilege [8254524]        at "src/roles/admin.hdbrole" (0:0)    Error: com.sap.hana.di.role: Deploying "src/roles/admin.hdbrole"... failed [8212145]      at "src/roles/admin.hdbrole" (0:0)

**Comment by Lsubatin** [comment]
Hi, Klaus, 

I tried to reproduce the problem on the same setting but have been unable to. Can you please add the details to the Q&A ( https://answers.sap.com/index.html ) so I can point the SHINE team to it? These issues are not meant for support.

Thanks, 
Lucia,
