### ISSUE TITLE
Create an account on the Gateway Demo system

### ISSUE THREAD

**Issue by cschuff** [SAPDocuments/Tutorials#2338]
Can't create an account. No from shows up. Just getting the busy indicator...

https://register.sapdevcenter.com/SUPSignForms/

<img width="747" alt="bildschirmfoto 2018-05-08 um 11 39 53" src="https://user-images.githubusercontent.com/194434/39750096-a640591a-52b4-11e8-9c26-0305f592b819.png">

**Comment by jonathanbaker7** [comment]
Thanks for reporting this.

The Gateway registration system hung over the weekend, but it is now up and working.  We are looking in to the problem, to figure out why it stopped just decided to hang.  (Why do these issues always happen on the weekends?)

If anyone has this problem in the future, please report it to rac_support@sap.com.  That is the alias for tracking any issues with the Gateway server, so they will respond to the problem ASAP.

I'm going to close this, as it's back up and running properly.  If you are still having problems, just reopen this and we will get in touch right away.

Thanks!

**Comment by akgustin** [comment]
The email address race_support@sap.com does not seem to work

**Comment by thecodester** [comment]
Jonathan wrote this email address:  rac_support@sap.com (without e)
