### ISSUE TITLE
Building freestyle IoT application

### ISSUE THREAD

**Issue by svenkevs** [SAPDocuments/Tutorials#2345]
Hi,

The end of the tutorial does not refer to the next tutorial in the program: https://www.sap.com/developer/tutorials/iotae-api-postman.html

**Comment by marcuscbehrens** [comment]
Yes, the postman part is optional.

We will deprecate this tutorial once our free trial is available - hence i will not change this right now.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
