### ISSUE TITLE
Multi Cloud to Full Stack

### ISSUE THREAD

**Issue by tobiashofmann** [SAPDocuments/Tutorials#2350]
Hi,

The tutorial for activating the SAP Web IDE Full Stack version contains images that show the old multi cloud name. Can you please update the screenshots? 

The text of the tutorial is already updated with commit bbbd84467fa7c0a27ac80e6fe20db0d4da3d6e11 

Tutorial: webide-multi-cloud/
Example image: https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/webide-multi-cloud/5.png

**Comment by mhassett92** [comment]
Hi Tobias,
Thanks for pointing that out. The screenshots have been updated!
Thank you,
Meredith
