### ISSUE TITLE
Setup SAP HANA, express edition, on Amazon Web Services - XS Advanced Application

### ISSUE THREAD

**Issue by modosteve** [SAPDocuments/Tutorials#2353]
Any updates on HANA setup for AWS?

**Comment by Lsubatin** [comment]
Hi, the preconfigured image is still not available. You can try the manual setup for now: https://www.sap.com/canada/developer/groups/hxe-install-binary-xsa.html

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
