### ISSUE TITLE
Create custom iOS app with SDK Assistant

### ISSUE THREAD

**Issue by renetweb** [SAPDocuments/Tutorials#2354]
HI
Love it !
Awesome tutorial - followed it step by step, super easy to do - very clear.
If I could shamelessly add an ask ! - it would be great if there was a follow up tutorial, that showed how you could ad the 'detail' navigation, i.e click on a customer and navigate to a detail controller.
Thank you.

**Comment by qualiture** [comment]
Hi @renetweb,

Great suggestion, and something that's been asked for regularly ;-)

The generated application is somewhat of a limited entity browser, as it currently ignores any navigation links -- i.e. the OData `expand` etc.

Something along the lines of what you may looking for is in https://www.sap.com/developer/tutorials/fiori-ios-scpms-create-demo-app.html, where clicking on a Package will navigate to it's related Delivery Status entities, displayed using a FUITimeLine control

Hope this helps!

Best,
Robin

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
