### ISSUE TITLE
SAP HANA XS Advanced, Creating an HTML5 Module

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2356]
Hi! 
Validation in last step doesn't work for me. I suppose the right answer is 
>The button fades away
>
But all\any answer shows Incorrect message.

**Comment by thecodester** [comment]
No answer was created in the rules file. @Lsubatin Can you fix?

**Comment by Lsubatin** [comment]
Hi, Thanks for pointing this out. It is fixed now.
Best, 
Lucia.
