### ISSUE TITLE
"How many services are available under Mobile Services?" doesn't list valid answer

### ISSUE THREAD

**Issue by carstenhag** [SAPDocuments/Tutorials#2357]
https://www.sap.com/developer/tutorials/fiori-ios-hcpms-setup.html

On https://account.hanatrial.ondemand.com/ there is only one service under Mobile Services.

This tutorial is really infuriating.

![bildschirmfoto 2018-05-22 um 14 41 55](https://user-images.githubusercontent.com/3776997/40362964-59c12d7e-5dce-11e8-94ef-388facbe41d5.png)

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
