### ISSUE TITLE
Compile and run a native Android app on SAP Cloud Platform

### ISSUE THREAD

**Issue by Tjarliman** [SAPDocuments/Tutorials#2360]
Thanks for this Tutorial. This is a really good one.

But I have an issue when trying to Make Project after copying the "main" folder from GiftHub.
You can see detail of the error below.

I hope you are able to give some suggestion to me to avoid those errors.

Is it because I am using the latest SMP SDK ? some of the .jar files are missing and replace by .aar files.
also is it because I just updated the Android Studio to a new one ?

![image](https://user-images.githubusercontent.com/39553318/40417207-cc3ced64-5eb1-11e8-90be-c21ae91e66cb.png)

THanks
Tjarliman

**Comment by thecodester** [comment]
Thank you for your feedback. Because of the amount of time that has elapsed, we are closing the issue.  

If you still have questions, feel free to create a new issue.
