### ISSUE TITLE
Create a Fiori for iOS app in 45 minutes

### ISSUE THREAD

**Issue by 20140277** [SAPDocuments/Tutorials#2361]
I don' have the same storyboard and architecture like TableDelegates/DetailTableDelegates/PackagesTypeDetailTableDelegate.swift.

One question: Which version of SAP Cloud Platform SDK for iOS Assistant are you using ?
I'm running on the version 9.3 of the SDK and the result is different from yours.

**Comment by qualiture** [comment]
Hi @20140277,

I wrote this particular tutorial specifically for the attendees of the Apple WWDC 2017 conference in June last year, using the 1.0 version of the SDK. In that first release, the generated app contained the mentioned `ZzzTableDelegate.swift` files.

When the 2.0 version of the SDK was rolled out just before SAP TechEd Vegas last year, I made an updated (and extended) version of this tutorial.

This tutorial group consist of the following tutorials:

 * [Create an application definition](https://www.sap.com/developer/tutorials/fiori-ios-scpms-deliveryapp-part1.html)
 * [Create an Xcode project with SDK Assistant](https://www.sap.com/developer/tutorials/fiori-ios-scpms-deliveryapp-part2.html)
 * [Implement a new Table View Controller](https://www.sap.com/developer/tutorials/fiori-ios-scpms-deliveryapp-part3.html)
 * [Using the SAP Fiori for iOS Mentor app](https://www.sap.com/developer/tutorials/fiori-ios-scpms-deliveryapp-part4.html)
 * [Implement the Fiori Timeline cell control](https://www.sap.com/developer/tutorials/fiori-ios-scpms-deliveryapp-part5.html)
 * [Enable the app for Offline OData](https://www.sap.com/developer/tutorials/fiori-ios-scpms-deliveryapp-part6.html) **(added for TechEd)**
 * [Manage and monitor your app on SAP Cloud Platform Mobile Services](https://www.sap.com/developer/tutorials/fiori-ios-scpms-deliveryapp-part7.html) **(added for TechEd)** 
 * [Change log settings and examine application logs](https://www.sap.com/developer/tutorials/fiori-ios-scpms-deliveryapp-part8.html) **(added for TechEd)**

I will update the tutorial so it follows the 2.0 style. In the meantime, you could use the above mentioned tutorials.

Hope this helps!

**Comment by 20140277** [comment]
thanks a lot !

**Comment by 20140277** [comment]
Can I find somewhere the git project that provide the code of the full suite of tutorial you just recommended me ? I would like to take it as a correction because issues occurred when I tried to follow the tutorial's steps.

**Comment by qualiture** [comment]
Unfortunately, for legal reasons we cannot provide full projects at this time...

What issues did you run into specifically?

**Comment by 20140277** [comment]
Hi ! 

I followed the tutorial till the "Implement the Fiori Timeline cell control" part and when I run the app it gets stuck when I click on the new link "Show Tracking Info..."  the app crashes and I get this issue : 

2018-05-25 10:28:58.692862+0200 testDeliveries[1533:23137] -[UISplitViewControllerClassicImpl _collapseSecondaryViewController:ontoPrimaryViewController:]: When collapsing for size class adaptation, secondary (detail) view controller has a navigation controller without any children, so ignoring it and not collapsing secondary on top of primary. SplitViewController is <UISplitViewControllerClassicImpl: 0x7fda1e45aa80>, primary is <UINavigationController: 0x7fda1e91b200>, secondary is <UINavigationController: 0x7fda1e856400>
2018-05-25 10:29:27.493910+0200 testDeliveries[1533:23137] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2018-05-25 10:29:27.504465+0200 testDeliveries[1533:23137] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
2018-05-25 10:30:43.047277+0200 testDeliveries[1533:30362] Received XPC error Connection interrupted for message type 3 kCFNetworkAgentXPCMessageTypePACQuery
2018-05-25 10:30:43.048300+0200 testDeliveries[1533:30362] Received XPC error Connection invalid for message type 3 kCFNetworkAgentXPCMessageTypePACQuery
Could not cast value of type 'UITableViewController' (0x111725310) to 'testDeliveries.TrackingInfoViewController' (0x10ad35038).
2018-05-25 10:30:53.573849+0200 testDeliveries[1533:23137] Could not cast value of type 'UITableViewController' (0x111725310) to 'testDeliveries.TrackingInfoViewController' (0x10ad35038).
(lldb) 


![sans titre](https://user-images.githubusercontent.com/23191651/40534990-1891289a-6008-11e8-8a22-237aec5c58a1.png)

**Comment by qualiture** [comment]
In your logs I see this message:

`Could not cast value of type 'UITableViewController' (0x111725310) to 'testDeliveries.TrackingInfoViewController'`

At the end of tutorial step 17, can you check you have done the following:

> Switch to the **Storyboard** and select the **Tracking Info Table View**. In the **Identity inspector**, set the **Custom Class** to `TrackingInfoViewController`:

**Comment by 20140277** [comment]
Yes I did it. The only thing that is different from the tutorial is the amount of navigation controller: my Assistant created an additional navigation controller by default that you can see on the screenshot below. Do you think this could be the reason of my issue ?
![sans titre](https://user-images.githubusercontent.com/23191651/40536173-8e6fbd6c-600b-11e8-8de9-d45c632cf236.png)

**Comment by 20140277** [comment]
Oh you were right sorry. I only set the Custom Class to TrackinInfoViewController in the table view cell instead of the whole Tracking info Scene. Now it works properly !
Thank you so much for your help !

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
