### ISSUE TITLE
Onboarding a computer as the IoT thing - Account in step 5 and HTTP 401 error

### ISSUE THREAD

**Issue by masahiroo** [SAPDocuments/Tutorials#2363]
Hi Vitaliy Rudnytskiy,

In Step 5 "Add your computer as a new thing" of "Onboarding a computer as the IoT thing", Account number is different from a2667617c and it is s0003605838trial. I proceeded as it was.

In Step 3 "Update the code and run the program" of "Send the CPU usage data to SAP IoT Application Enablement", I updated deviceid and authtoken variables in the script code but didn't change hostiotmms (the value is 'iotmmsa2667617c.hana.ondemand.com').

Then I run the script with phthon and I got the following error message. My laptop is not hindered by a corporate proxy by using mobile phone hot spot.

Access to the requested resource is not authorized (HTTP 401)

Regards,
Masahiro Obata

**Comment by svenkevs** [comment]
I'm having the same issue. Changing the host name to iotmmss0003605838trial.hana.ondemand.com does not help.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
