### ISSUE TITLE
Onboarding a computer as the IoT thing

### ISSUE THREAD

**Issue by svenkevs** [SAPDocuments/Tutorials#2364]
It's mentioned the security token is showed only once. But there is a connectivity information button where yo ucan find thing/device ID & Token, it's between the thing type and disconnect button. You can see for all things (not just the one you created).

![image](https://user-images.githubusercontent.com/33825694/40483956-31cae2e6-5f5a-11e8-8086-8f89b1611198.png)

**Comment by thecodester** [comment]
@marcuscbehrens can you respond?

**Comment by marcuscbehrens** [comment]
Interesting - that's a new feature I did not know.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
