### ISSUE TITLE
Change xxxTrial account back to a2667617c

### ISSUE THREAD

**Issue by monokizsolt** [SAPDocuments/Tutorials#2368]
Can I somehow change back the default user to a2667617c? Things need to be linked to that account in order to work. People are experimenting and always changing it to their own trial account.

**Comment by thecodester** [comment]
Which tutorial are you referring to?

**Comment by monokizsolt** [comment]
Onboarding a computer as the IoT thing

**Comment by Sygyzmundovych** [comment]
Hi @monokizsolt. The setup is checked weekly by @marcuscbehrens. Hopefully it was fixed and you were able to finish tutorials in the meantime.

**Comment by GalbiatiL** [comment]
Hi @Sygyzmundovych , I'm sorry, but I'm unable to complete your tutorial https://developers.sap.com/tutorials/iotae-comp-thingmodeler0.html .
Instead  of a2667617c the system show me the user p1942131186trial. I'm not sure, but I think this is the reason to give back ther error "Access to the requested resource is not authorized (HTTP 401)", while I'm sending the cpu data from my pc

thanks in advance

**Comment by marcuscbehrens** [comment]
Someone put in his trial account.

I fixed it and put a2667617c back in.

Please try again.

**Comment by GalbiatiL** [comment]
Hi @marcuscbehrens , Thanks for your answer. 
Unfortunatly someone put in another wrong value "I801786trial"

luca

**Comment by marcuscbehrens** [comment]
I fixed it again …

**Comment by GalbiatiL** [comment]
Hi @marcuscbehrens thanks! i complete the second second part of the tutorial. But now, I've some problem with this one https://developers.sap.com/tutorials/iotae-comp-buildappmc0.html
Something doesn't work and in the step 6 I can't find the action

Could you help me again?

thanks
luca

**Comment by marcuscbehrens** [comment]
What was called Actions in the past is now called “Events” and you should look for “Wire to Action”
