### ISSUE TITLE
Installing SAP HANA, express edition Server + Apps, with Docker

### ISSUE THREAD

**Issue by pdominique** [SAPDocuments/Tutorials#2369]
Hi,

On the SAP HANA Express Edition home page the flowchart shows Linux, Mac and Windows icons for the Docker option but in the tutorial it is clearly stated Docker for Windows/Mac is **not** supported:

> This installation does not support Docker for Windows or Docker for Mac.

Is there any plan to support Docker for Windows/Mac in the future?

Cheers,
Pierre

**Comment by JCurrie27** [comment]
Assigning question to Adrian (who is out for U.S. Memorial Day holiday today).

**Comment by aplata-sap** [comment]
We will be correcting the flowchart. Unfortunately, I do not know of any plans to support Docker for Windows or Mac.
