### ISSUE TITLE
SAP HANA XS Advanced, Creating a Node.js Module

### ISSUE THREAD

**Issue by teejaytarun** [SAPDocuments/Tutorials#2370]
I have following section for nodejs module in my mta.yaml but it doesn't work.
App Build is successful but can't run xsjs file. Running on  xsjs port directly  index.xsjs it says unauthorized. Running on web module port it says file not found.

  - name: core_xsjs
    type: nodejs
    path: core_xsjs
    provides:
      - name: core_xsjs_api
        properties:
          url: '${default-url}'
      - name: ''
    requires:
      - name: UAA-service
      - name: hdi_db
      - name: db

**Comment by Lsubatin** [comment]
Hi, Teejay,

The yaml looks fine but what you are describing could be either the folder structure or the routing. The call to the index.xsjs saying unauthorized is expected as your end point is now the web module. So you should be calling the same URl as the index.html but with index.xsjs, provided that the routing is configured properly.

 Please create a question in the Q&A (answers.sap.com) including screenshots of the routing configuration, the folder structure, the web module URL and how the same URL with the proper folder structure fails. You would not believe how much screenshots help up help you.

Best, 
Lucia.
