### ISSUE TITLE
SAP HANA XS Advanced, Creating a Node.js Module

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2371]
Hi! It seems that validation in this tutorial also missed. Following code 
`  - name: core_xsjs
    type: nodejs
    path: core_xsjs
    provides:
      - name: core_xsjs_api
        properties:
          url: '${default-url}'
    requires:
      - name: UAA-service
      - name: hdi_db
      - name: db`
validated as incorrect. 
I've also tried old Node.js module naming `js` instead of `core_xsjs` which is still on some screenshots. 
It could be my mistake in this case, please kindly advice.
Thanks.

**Comment by Lsubatin** [comment]
Hi, thanks for bringing this into attention. It is being worked on. Your response should be validating correctly (regardless of the name of the js module).

**Comment by vsenn** [comment]
Yes, it validates now. Thank you.
