### ISSUE TITLE
Onboarding a computer as the IoT thing

### ISSUE THREAD

**Issue by jlliao** [SAPDocuments/Tutorials#2373]
I am not able to change the account name to a2667617c, since it requires userid, password and host.

**Comment by thecodester** [comment]
@marcuscbehrens can you respond?

**Comment by marcuscbehrens** [comment]
I put in the right account name and everything else to make creation of things work again. If one person puts in their trial account this breaks the tutorial for everyone else. I usually check this once a day but was out of office the last 2 weeks. Please try again.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
