### ISSUE TITLE
Import the dataset in your SAP HANA instance

### ISSUE THREAD

**Issue by simonnyc** [SAPDocuments/Tutorials#2374]
Hi, 

Great tutorials. A minor observation or typo. 
Please note that under (Import the dataset in your SAP HANA instance) under Step 11: Granting roles, 

call _SYS_REPO.GRANT_ACTIVATED_ROLE ('public.aa.movielens.**hdb**::user','MOVIELENS_USER');

**hdb** should be **service** as below... 

call _SYS_REPO.GRANT_ACTIVATED_ROLE ('public.aa.movielens.**service**::user','MOVIELENS_USER');

Thank you for a great detailed tutorial job.

**Comment by adadouche** [comment]
Thanks for your feedback.

Actually hdb is the right package, but the step explaining the role creation used the wrong path.

Fixed in commit  [b5e9e7c](https://github.com/SAPDocuments/Tutorials/commit/b5e9e7c13772821603ab1e5e3a5e351861243c7f)

**Comment by simonnyc** [comment]
oh ok..Thank you 
    On Tuesday, May 29, 2018, 9:05:51 AM EDT, Abdel Dadouche <notifications@github.com> wrote:  
 
 
Thanks for your feedback.

Actually hdb is the right package, but the step explaining the role creation used the wrong path.

Fixed in commit b5e9e7c

**Comment by adadouche** [comment]
no worries, you are welcome.
