### ISSUE TITLE
Analyze the MovieLens dataset

### ISSUE THREAD

**Issue by simonnyc** [SAPDocuments/Tutorials#2375]
Please note that there is a typo in Step 2: Links - (Check missing values) as follow: 

LINKSLINKS should be LINKS
LINKSMOVIES should be MOVIES

Therefore, 

select count(1)
from "MOVIELENS"."public.aa.movielens.hdb::data.LINKSLINKS" l
where not exists (select 1 from "MOVIELENS"."public.aa.movielens.hdb::data.LINKSMOVIES" m where l."MOVIEID" = m."MOVIEID")
UNION ALL
select count(1)
from "MOVIELENS"."public.aa.movielens.hdb::data.LINKSMOVIES" m
where not exists (select 1 from "MOVIELENS"."public.aa.movielens.hdb::data.LINKSLINKS" l where l."MOVIEID" = m."MOVIEID");

== Should be ==

select count(1)
from "MOVIELENS"."public.aa.movielens.hdb::data.LINKS" l
where not exists (select 1 from "MOVIELENS"."public.aa.movielens.hdb::data.MOVIES" m where l."MOVIEID" = m."MOVIEID")
UNION ALL
select count(1)
from "MOVIELENS"."public.aa.movielens.hdb::data.MOVIES" m
where not exists (select 1 from "MOVIELENS"."public.aa.movielens.hdb::data.LINKS" l where l."MOVIEID" = m."MOVIEID");

**Comment by adadouche** [comment]
Thanks for your feedback.

It was a copy/replace all mistake from me.

Fixed in commit  [b5e9e7c](https://github.com/SAPDocuments/Tutorials/commit/b5e9e7c13772821603ab1e5e3a5e351861243c7f)

**Comment by simonnyc** [comment]
Hi Abdel, Yes, agreed..  quick copy/paste will cause that. On the other hand, I am really enjoying the tutorials. They are really done very well. very details...
Just curious, are there any plans to have tutorials for image or video processing (CNN or RNN) using hana as backend?  I am curious to know how hana can handle matrix reduction and transformation processing, creating deep CNN/RNN with multiple hidden nodes and grid search for large values for hyper-parameters?   I will be more than happy to collaborate as I have MS in Data Analytics also known as MS Data Science and I have been working in SAP for since 2008...   but I still have a lot to learn:) 
Please let me know and thank you again for great tutorials.



    On Tuesday, May 29, 2018, 9:04:57 AM EDT, Abdel Dadouche <notifications@github.com> wrote:  
 
 
Thanks for your feedback.

It was a copy/replace all mistake from me.

Fixed in commit b5e9e7c

**Comment by adadouche** [comment]
Hi @simonnyc,

CNN, DNN and RNN algorithms are not part of the SAP HANA roadmap as of today.

As an alternative, you can leverage the SAP HANA EML library which allows you to consume TensorFlow model from SAP HANA.

Please check the following blog I wrote recently: [Machine Learning in a Box (week 8) : SAP HANA EML and TensorFlow Integration](https://blogs.sap.com/2018/05/14/machine-learning-in-a-box-week-8-sap-hana-eml-and-tensorflow-integration)

Hope this helps

**Comment by simonnyc** [comment]
Hi Abdel,
Sure, I will check ML in a box HANA/TF blog. 
Thank you again    

   On Wednesday, May 30, 2018, 6:49:12 AM EDT, Abdel Dadouche <notifications@github.com> wrote: 
 
 
Hi @simonnyc,

CNN, DNN and RNN algorithms are not part of the SAP HANA roadmap as of today.

As an alternative, you can leverage the SAP HANA EML library which allows you to consume TensorFlow model from SAP HANA.

Please check the following blog I wrote recently: Machine Learning in a Box (week 8) : SAP HANA EML and TensorFlow Integration

Hope this helps
