### ISSUE TITLE
Image Similarity Scoring with SAP Leonardo Machine Learning Foundation in SAPUI5

### ISSUE THREAD

**Issue by 20140277** [SAPDocuments/Tutorials#2380]
Hi ! I have followed the entire tutorial but the app does not work in the end.
The app launches, I can get image features and display them but when I press the Score Similarity button nothing happens. 
When I added the destination and tried the connection I had this message :
![image](https://user-images.githubusercontent.com/23191651/40731049-82a75b38-6430-11e8-8d6c-2ba19ab79e50.png)
Maybe this is the reason why it doesn't work.

Could you help me with my issue please ?

**Comment by adadouche** [comment]
Hi @20140277 ,

Yes, the destination is the issue.

Apparently the Sandbox having some issues now, as I can't reach it either.

I have the following error message: Failure reason: "peer not authenticated"

So for the moment I don't have a solution to propose. We just need to wait.

PS: Thanks to you I also found a glitch in another tutorial where the sandbox url wasn't correct which I will update.

**Comment by 20140277** [comment]
okay I'll just wait then.. thank you for your help !

**Comment by adadouche** [comment]
Hi,

I just found a dirty workaround.

in the model.json file, replace the "/ml" in the usrls by "https://sandbox.api.sap.com/ml".

The demo.json should now look like:

`json
{
	"url_featureextraction" : "https://sandbox.api.sap.com/ml/featureextraction/inference_sync",
	"url_similarityscoring" : "https://sandbox.api.sap.com/ml/similarityscoring/inference_sync",
	"APIKey":"2ddSBnNEGkDvfuxAQERA6SBWrn7iXS6V"
}
` 

The drawback here is that you won't be able the application if you deploy it as an HTML app in your account (because of CORS not being allowed).

Hope this unlock you for now.

**Comment by adadouche** [comment]
Hi @20140277 ,

The destination is working now. 

Have fun and thanks for taking the time to submit your feedback
