### ISSUE TITLE
Start SAP HANA, express edition Server

### ISSUE THREAD

**Issue by RobWaywellSAP** [SAPDocuments/Tutorials#2381]
The password rules for the hxeadm user password are ridiculous and extremely disruptive to the user experience.

**Comment by JCurrie27** [comment]
Hi Rob - I've passed your feedback on to PM. Closing issue.

**Comment by JCurrie27** [comment]
Rob - we confirmed that the hxeadm user password rules are the same as for HANA. For example, HANA studio has the same rules for a new user: [https://blogs.sap.com/2013/05/15/hana-password-security/](https://blogs.sap.com/2013/05/15/hana-password-security/)

**Comment by RobWaywellSAP** [comment]
Hi John,

Thanks for following up, but the restriction on using passwords that include a dictionary word as part of the password is not  a HANA restriction. Both skimming and searching the blog, I do not see any mention of a restriction on dictionary words being part of a HANA password. Of course the product documentation would be the definitive source, rather than a blog. Note that I also happen to have upgraded or reinstalled 3 separate HANA systems on Monsoon VM’s since the SPS03 release. I can guarantee you that HANA does not impose a limitation on using passwords that include a dictionary word as part of the password.

Robert Waywell, MBA
SAP HANA Product Management
SAP | 445 Wes Graham Way | Waterloo, ON N2L 6R2
T +1-519-883-6226, M +1-519-574-2353
