### ISSUE TITLE
Create an SAP Cloud Platform destination pointing to an SAP Gateway

### ISSUE THREAD

**Issue by larochka** [SAPDocuments/Tutorials#2384]
HI there,

I've started a tutorial on https://www.sap.com/developer/groups/te2016-sapui5.html.

I create an account on the Gateway Demo system as per the steps here:
https://www.sap.com/developer/tutorials/gateway-demo-signup.html. When in the last step I put in the URL https://sapes5.sapdevcenter.com/sap/bc/gui/sap/its/webgui?sap-client=002&sap-language=EN to verify. It fails to verify. Ok, I left it for now.

Then I created a destination pointing to the SAP Gateway as per instructions here: https://www.sap.com/developer/tutorials/teched-2016-3.html. When I test the connection, this is what I get: Connection to "SAP_Gateway" established. Response returned: "307: Temporary Redirect"

Then started building the app as per the steps here:
https://www.sap.com/developer/tutorials/teched-2016-4.html

In the step 17 when I launch the app I get the following:

Sorry, a technical error occurred! Please try again later.
 {
 "message": "HTTP request failed",
 "headers": [],
 "statusCode": 504,
 "statusText": "Gateway Timeout",
 "responseText": "HTTP Status 504 - Socket connection timed out for host https://sapes5.sapdevcenter.com. Reason: Read timed out (local port 33351 to address 10.117.12.196 (vsa3718601.nwtrial.od.sap.biz), remote port 8080 to address 10.117.18.16 (sgw-a1s-03-int.od.sap.biz))
 "
 }

My question is: Is there any point trying to make this work? I've started doing it from scratch again, and spent now over a day, trying to figure out what is wrong. Is the tutorial documentation updated?

Can anybody help? Please?

**Comment by larochka** [comment]
HI there,

I've started a tutorial on https://www.sap.com/developer/groups/te2016-sapui5.html.

I create an account on the Gateway Demo system as per the steps here:
https://www.sap.com/developer/tutorials/gateway-demo-signup.html. When in the last step I put in the URL **https://sapes5.sapdevcenter.com/sap/bc/gui/sap/its/webgui?sap-client=002&sap-language=EN** to verify. It fails to verify. Ok, I left it for now.

Then I created a destination pointing to the SAP Gateway as per instructions here: https://www.sap.com/developer/tutorials/teched-2016-3.html. When I test the connection, this is what I get: **Connection to "SAP_Gateway" established. Response returned: "307: Temporary Redirect"**

Then  started building the app as per the steps here:
https://www.sap.com/developer/tutorials/teched-2016-4.html

In the step 17 when I launch the app I get the following:    

Sorry, a technical error occurred! Please try again later.
\{
	"message": "HTTP request failed",
	"headers": [],
	"statusCode": 504,
	"statusText": "Gateway Timeout",
	"responseText": "HTTP Status 504 - Socket connection timed out for host https://sapes5.sapdevcenter.com. Reason: Read timed out (local port 33351 to address 10.117.12.196 (vsa3718601.nwtrial.od.sap.biz), remote port 8080 to address 10.117.18.16 (sgw-a1s-03-int.od.sap.biz))
"
}

My question is: Is there any point trying to make this work?  I've started doing it from scratch again, and spent now over a day, trying to figure out what is wrong. Is the tutorial documentation updated?

Can anybody help? Please?

**Comment by larochka** [comment]
Update: I did not proceed with the tutorial last week. 
This morning I still could not do any of the above, but I tried changing the destination to the one specified in this blog https://blogs.sap.com/2017/12/05/new-sap-gateway-demo-system-available/.

Then I deployed the app as per the steps in https://blogs.sap.com/2017/12/05/new-sap-gateway-demo-system-available/.

I was not able to access the active version of the deployed app, so I tried accessing the Sap Gateway logs as per another blog: https://blogs.sap.com/2018/02/01/how-to-access-the-sap-gateway-error-log-as-a-ui-developer/

The error I was getting was: /IWBEP/CM_MGW_RT004, I redeployed the app and it worked. I can access the deployed version but still no success Running the app via SAP Web IDE

**Comment by mhassett92** [comment]
Hi,
This appears to be an issue with the Gateway server. There was an outage with SAP Cloud Platform destinations last week. My recommendation would be continue working on other activities and we will update you when the service is back online. When the service is back up, you can verify your progress for these steps. 
Thank you!
Meredith

**Comment by larochka** [comment]
Thanks Meredith.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by rjayasa** [comment]
Hi Meredith,

I am having the same error when run the application as per the last step in 
started building the app tutorial.
https://www.sap.com/developer/tutorials/teched-2016-4.html

In the step 17 when I launch the app I get the following:

Sorry, a technical error occurred! Please try again later.
{
"message": "HTTP request failed",
"headers": [],
"statusCode": 504,
"statusText": "Gateway Timeout",
"responseText": "HTTP Status 504 - Socket connection timed out for host https://sapes5.sapdevcenter.com. Reason: Read timed out (local port 33351 to address 10.117.12.196 (vsa3718601.nwtrial.od.sap.biz), remote port 8080 to address 10.117.18.16 (sgw-a1s-03-int.od.sap.biz))
"
}

Is the gateway server down?

Thanks,
Jay
