### ISSUE TITLE
Use HDBSQL as a SQL query tool with SAP HANA, express edition

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2385]
Hi! 
It is worth to mention that usr/sap folder is not created on macOS due to Apple System Integrity Protection https://support.apple.com/en-us/HT204899
So mac users will use their local folders for hdbclient tools.

**Comment by adadouche** [comment]
Hi @vsenn,

In step, it is mentioned that the path might be different from the one listed after, as users are free (or constrained) to use a different folder.

I'm happy to list the default value for mac, but the support article reference is probably more appropriate in the following tutorial: [Installing SAP HANA HDB Client (Mac)](https://www.sap.com/developer/tutorials/hxe-ua-install-hdb-client-mac.html).

Best Regards
