### ISSUE TITLE
Import CSV into SAP HANA, express edition using the SAP HANA Tools for Eclipse

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2386]
Comma (,) should be selected during import instead of Semi colon (;) as wrongly stated in the tutorial.

**Comment by adadouche** [comment]
Thanks for your feedback!
Fixed in commit [Fixing issue #2386](https://github.com/SAPDocuments/Tutorials/commit/666aefed5425d411df0de99b78d418a9863bcdea)
