### ISSUE TITLE
Installing SAP HANA, express edition Server + Apps, with Docker

### ISSUE THREAD

**Issue by KPouianou** [SAPDocuments/Tutorials#2389]
I'm trying to use the Docker image for _SAP HANA, express edition (database and application services)_ on an AWS instance that runs _SUSE Linux Enterprise Server 12 SP1 x86_64 (64-bit) Configured for SAP Cloud Appliance Library (SAPCAL)_

I successfully followed the steps up to this point, however when trying to _run_ (or start) the container, I'm getting the following error:

> starting container process caused "process_linux.go:357: container init caused \"open /proc/sys/net/ipv4/ip_local_port_range: no such file or directory\""

Is this an OS/kernel issue? I already tried the "run" command with the "--privileged" flag, but still --sysctl net.ipv4.ip_local_port_range='40000 60999' seems to not be working as intended. Any clues?

**Comment by aplata-sap** [comment]
Hi there,

Can you try the run command and omit the following line: _--sysctl net.ipv4.ip_local_port_range='40000 60999'_

**Comment by KPouianou** [comment]
Thanks - that seems to work, although I am still unable to run the container. The run command fails with the following message:

> StartService
> OK
> OK
> Starting instance using: /usr/sap/HXE/SYS/exe/hdb/sapcontrol -prot NI_HTTP -nr 90 -function StartWait 2700 2
> 
> 05.06.2018 07:41:13
> Start
> OK
> 
> 05.06.2018 07:41:55
> StartWait
> FAIL: process hdbxsexecagent HDB XS Execution Agent not running

**Comment by tai-le** [comment]
You need different port range for database and services Docker image.  Please try "docker run" command with `--sysctl net.ipv4.ip_local_port_range='60000 65535'`

If this doesn't work, run:
`sudo sysctl -w net.ipv4.ip_local_port_range='60000 65535'`

**Comment by KPouianou** [comment]
Thanks, I did add the port range with 

> sudo sysctl -w net.ipv4.ip_local_port_range='60000 65535'

however that does not solve the aforementioned problem, which is

>  FAIL: process hdbxsexecagent HDB XS Execution Agent not running

**Comment by tai-le** [comment]
What kind of the storage driver are you using in Docker?  Can you run this and post the output?

`sudo docker info | grep -i storage`

**Comment by KPouianou** [comment]
After running an info command, here's the info relevant to the storage:

> Storage Driver: devicemapper
>  Pool Name: docker-3:1-524962-pool
>  Pool Blocksize: 65.54kB
>  Base Device Size: 53.69GB
>  Backing Filesystem: xfs
>  Data file: /dev/loop0
>  Metadata file: /dev/loop1
>  Data Space Used: 25.67GB
>  Data Space Total: 107.4GB
>  Data Space Available: 81.71GB
>  Metadata Space Used: 14.32MB
>  Metadata Space Total: 2.147GB
>  Metadata Space Available: 2.133GB
>  Thin Pool Minimum Free Space: 10.74GB
>  Udev Sync Supported: true
>  Deferred Removal Enabled: false
>  Deferred Deletion Enabled: false
>  Deferred Deleted Device Count: 0
>  Data loop file: /var/lib/docker/devicemapper/devicemapper/data
>  Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
>  Library Version: 1.03.01 (2015-05-15)
> ...
> ...
> WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
>          Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
> WARNING: No swap limit support
> WARNING: No kernel memory limit support

I've also set `DOCKER_OPTS="-s devicemapper --storage-opt dm.basesize=50G"` as described in the tutorial.

**Comment by tai-le** [comment]
When you said "...Configured for SAP Cloud Appliance Library (SAPCAL)", do you have applications running on host machine that already use the ports?

I don't have problem starting the container on SUSE Linux Enterprise Server 12 SP1.  Can you post the full "docker run" command?

**Comment by KPouianou** [comment]
Ports are don't look like an issue at face value. Running `sudo lsof -nP | grep LISTEN` results in

> sshd      1871            root    3u     IPv4              17550      0t0        TCP *:22 (LISTEN)
> sshd      1871            root    4u     IPv6              17552      0t0        TCP *:22 (LISTEN)

The full run command I'm using is:

> sudo docker run -p 39013:39013 -p 39015:39015 -p 39041-39045:39041-39045 -p 1128-1129:1128-1129 -p 59013-59014:59013-59014  -p 39030-39033:39030-39033 -p 51000-51060:51000-51060  -p 53075:53075  \
> -v /data/hxe:/hana/mounts \
> --ulimit nofile=1048576:1048576 \
> --sysctl kernel.shmmax=1073741824 \
> --sysctl kernel.shmmni=524288 \
> --sysctl kernel.shmall=8388608 \
> --name hxe_container \
> store/saplabs/hanaexpressxsa:2.00.030.00.20180403.2 \
> --agree-to-sap-license \
> --passwords-url file:///hana/mounts/credentials.json

**Comment by phillparkinson** [comment]
Following this thread as I have exactly the same issue as @KPouianou 
documented here: 
https://answers.sap.com/questions/539188/hxe-server-apps-on-docker-not-able-to-start-contai.html

**Comment by KPouianou** [comment]
I tried the aforementioned steps, and indeed HXE failed to start with the same error (`process hdbxsexecagent HDB XS Execution Agent not running`). Looking in the trace folder (/usr/sap/HXE/HDB90/hxehost/trace), there's a lot of files in there - which one would you need in particular?

**Comment by tai-le** [comment]
Look at xsexeagent.*

But before you do that, can you retry "sudo docker run ..." command with "-h hxehost" option?  I just noticed option this is missing in the doc.

`sudo docker run -h hxehost ...`

**Comment by JCurrie27** [comment]
Closing this issue as the discussion has moved to the Answers section of the Developer Community. Please see the discussion at [https://answers.sap.com/questions/539188/hxe-server-apps-on-docker-not-able-to-start-contai.html?childToView=541558](https://answers.sap.com/questions/539188/hxe-server-apps-on-docker-not-able-to-start-contai.html?childToView=541558)
