### ISSUE TITLE
Create OAuth communication system and user

### ISSUE THREAD

**Issue by yogerana2308** [SAPDocuments/Tutorials#2390]
Hi Merve,

Thanks for a great tutorial!!
On Step 12 of this tutorial, I am getting a error while saving Communication system. 

Error**: No entity in with MODE SVP in client 390 found** 
[Comm_Error.pdf](https://github.com/SAPDocuments/Tutorials/files/2068017/Comm_Error.pdf)

Could you please help me fix this issue.

**Comment by thecodester** [comment]
@mervey45 Can you address this question?

**Comment by mervey45** [comment]
Hi Yogerana2308, 

please open a ticket on following component: BC-SRV-APS-COM
and describe your problem in detail.

Thank you for your understanding, 

Regards, 
Merve

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
