### ISSUE TITLE
How to download and install the HANA Eclipse plugin

### ISSUE THREAD

**Issue by DavidUM** [SAPDocuments/Tutorials#2393]
Dear Colleague,

At step 7A, we'd better consider more cases in following sentence.
"Instance number: 90 (or 00 for SAP HANA 1.0, express edition installations)"
Because a person who install HANA express edition in his local linux machine can use another number.
So we can make more generous guide like
"Instance number: 90 (or 00 for SAP HANA 1.0, express edition installations
or any number you selected during HANA express edition installations)"

Thank you

**Comment by aplata-sap** [comment]
Hi There,

That suggestion certainly makes sense. We'll look into adding it in an upcoming update.

Thanks!

**Comment by JCurrie27** [comment]
The tutorial has been updated. Closing issue.
