### ISSUE TITLE
SAP HANA XS Advanced - Clone and run SHINE applications

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2397]
Hi! Can not validate running SHINE services in Step 4. My input recognised as Invalid response.
shine-uaa                                  xsuaa           default      
shine-scheduler                            jobscheduler    default      
shine-auditlog                             auditlog        free

**Comment by Lsubatin** [comment]
This should have been fixed in the last update of the rules file, pushing it again just in case.
