### ISSUE TITLE
Add a map display to your app

### ISSUE THREAD

**Issue by nadinexyz** [SAPDocuments/Tutorials#2403]
I am currently trying on the tutorial. Unfortunately, the link to the previous one is missing before the "Commit your project to Git and deploy to the cloud" tutorial.
Where can I find the previous instructions?

Thank you!

**Comment by mhassett92** [comment]
Hello,
You can find the previous step here: [Commit your project to Git and deploy to the cloud](https://www.sap.com/developer/tutorials/teched-2016-5.html)
Thank you!
Meredith
