### ISSUE TITLE
How to send REST notifications using OAuth?

### ISSUE THREAD

**Issue by kedeggel** [SAPDocuments/Tutorials#2404]
I've found that it is also possible to send push notifications with REST, and I have to authenticate with basic auth. But in my app I use OAuth and I'd like to send push notification from my iOS device to others. Is it possible to use OAuth to authenticate? I've tried the following approach:

```
let urlRequest = try! URLRequest(url: "https://hcpms-pXXXtrial.hanatrial.ondemand.com/restnotification/application/APPID", method: .post)
        let body: [String : Any] = [
            "alert": "This is a Push Message",
            "badge": 1
            ]

        let data = try! JSONSerialization.data(withJSONObject: body, options: [])

        let uploadTask = onboardingContext.sapURLSession.uploadTask(with: urlRequest, from: data) { (data, urlResponse, error) in
            // DO SOMETHING
        }

        uploadTask.resume()
```

I get the following error: `OAuth2Error.tokenRejected: The newly acquired or refreshed token got rejected`.

**Comment by thecodester** [comment]
Which tutorial are you talking about?

**Comment by kedeggel** [comment]
[How to config and consume Push Notification from SAP Mobile Services （Part2)](https://blogs.sap.com/2017/06/09/how-to-enable-push-notifications-%EF%BC%88part2/)
