### ISSUE TITLE
Import your TechEd BUILD project into SAP Web IDE

### ISSUE THREAD

**Issue by 69cmg** [SAPDocuments/Tutorials#2406]
Hi.

After importing the Build project to SAP Web IDE, although I can start the project (run it as web application), I get an error "Request failed", with the following details:
"\{
	"requestUri": "/here/goes/your/serviceUrl/local/$metadata?sap-language=EN",
	"statusCode": 404,
	"statusText": "Not Found",
	"headers": [],
	"body": "HTTP Status 404 - Not Found"
}"

After checking the connection for all destinations imported a few steps above, none of the destinations replied OK:
- Connection to "BUILD_Production" established. Response returned: "404: Not Found"
- Connection to "sapui5-private" established. Response returned: "401: Unauthorized"
- Connection to "sapui5-private-build" established. Response returned: "401: Unauthorized"
- Connection to "Web_IDE_PLUGIN" established. Response returned: "301: Moved Permanently"

Hope will get a positive reply soon.

Best regards,
thank you, 
Marius

**Comment by 69cmg** [comment]
I have now figured out where is this coming from. It's defined in manifest.json file, on the Data Sources Tab. 
![capture](https://user-images.githubusercontent.com/23642545/41349646-35fd84f8-6f19-11e8-91a1-e4a8f4792492.PNG)

**Comment by sharathmg** [comment]
Run the application using the Mock Server. Since we dont have any service available, thsi sample url throws an error. Even in the Build tool, we use Mock data. So right click on project, Run configurations -> and select - a new web application and check run with mock data OR run the application on mockserver.

**Comment by StErMi** [comment]
@69cmg as I already said on [Twitter](https://twitter.com/StErMi/status/1030385793590861824) I think they made a mistake. In the first steps, you have to run the index web app with mock data. You're going to configure the oData destination only in the latest step.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
