### ISSUE TITLE
Analyze the MovieLens dataset - Step 5: Movies - Get the genre count per movie

### ISSUE THREAD

**Issue by nahorgebre** [SAPDocuments/Tutorials#2409]
The question asked at the end of the tutorial is: Which movie has 10 genres associated?

If the SQL script written in the tutorials get executed, you connot see which movie has 10 genres associated.
To get the needed information you have to execute the SQL script using 'DESC'.

SELECT
    "MOVIEID"
  , "TITLE"
  , OCCURRENCES_REGEXPR('[|]' IN GENRES) + 1 "GENRE_COUNT"
  , "GENRES"
FROM "MOVIELENS"."public.aa.movielens.hdb::data.MOVIES"
ORDER BY "GENRE_COUNT" **_DESC_**;

I suspect that is due to the limitation of the maximum displayable lines.
The result table has a maximum of 1000 lines. And if we use '_**ASC**_' we find a movie with only one genre on line 1000.

![capture](https://user-images.githubusercontent.com/33464885/41469909-55dc21c0-70af-11e8-9d48-b728bf35e132.JPG)

**Comment by adadouche** [comment]
Hi  @nahorgebre,

Thanks for your feedback.

In the instructions, it mentions:

> Using the above SQL statement, and changing the **order by** direction from **ASC** to **DESC**, provide an answer to the question below then click on Validate.

So, everything is detailed correctly here.

Best regards
