### ISSUE TITLE
SAP HANA APL - Step 2: Run Recommendation APL function

### ISSUE THREAD

**Issue by nahorgebre** [SAPDocuments/Tutorials#2410]
The SQL statement has two quotes too much.

SET SCHEMA "MOVIELENS";
SET SESSION 'APL_CACHE_SCHEMA' = '`MOVIELENS_USER`';

Improvement:

SET SESSION 'APL_CACHE_SCHEMA' = 'MOVIELENS_USER';

Best regards

**Comment by adadouche** [comment]
Thanks for you feedback @nahorgebre 
This issue is now [fixed](https://github.com/SAPDocuments/Tutorials/commit/1ce6a77bf88e7a95187386fc26a4c6259c6d98b3)
