### ISSUE TITLE
Configuring Eclipse with SAP Cloud Platform Tools for Java

### ISSUE THREAD

**Issue by raikals** [SAPDocuments/Tutorials#2411]
This tutorial is out of date at step 18. Sap -> Java Web???

**Comment by thecodester** [comment]
Thanks for the feedback. Checking on the tutorial and will respond soon.

**Comment by KevinMuessig** [comment]
Hey Jim could you check this out?

**Comment by thecodester** [comment]
@KevinMuessig What needs to be done here?

**Comment by thecodester** [comment]
@jonathanbaker7 This seems to be the intro tutorial for the Java weather app tutorial that we are discontinuing. Should this tutorial be removed?

**Comment by thecodester** [comment]
These tutorials were removed.
