### ISSUE TITLE
Getting Started with the SAP Web IDE Multi-Cloud Version (Trial)

### ISSUE THREAD

**Issue by lutraki-yavan** [SAPDocuments/Tutorials#2413]
Please change Multi-Cloud to Full-Stack 10x

**Comment by thecodester** [comment]
@jhornik Can you update the tutorial?

**Comment by jhornik** [comment]
Yes, I'll take care of it. @thecodester: Please send me the folder name in QA, thanks.

**Comment by thecodester** [comment]
It's this tutorial: https://www.sap.com/developer/tutorials/webide-innovation-beta.html

**Comment by jhornik** [comment]
Thanks.

**Comment by jhornik** [comment]
The changes have been published.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

NOTE: The images may take a few days to be updated.
