### ISSUE TITLE
Use Jupyter Notebook with SAP HANA, express edition

### ISSUE THREAD

**Issue by sarahESL** [SAPDocuments/Tutorials#2420]
Repo suggested for python packages ```'https://download.opensuse.org/repositories/devel:/languages:/python/SLE_12_SP2/devel:languages:python.repo``` is no longer available. I have tried using ```https://download.opensuse.org/repositories/devel:/languages:/python/SLE_12_SP3/devel:languages:python.repo``` repo, but it looks like it is missing ```python-devel``` package, so I cannot proceed forward to install Jupyter on my HANA XS. Would appreciate update on the tutorial docs or at least hints to solve this problem.

**Comment by adadouche** [comment]
Hi @sarahESL,

My initial goal was to make this tutorial as easy as possible and avoid downloading the SDK and the associated patches or registering your system.

But apparently the https://download.opensuse.org site is not keeping historical versions.

Therefore your only option, if you haven't found one yet, is probably to:
 - download the SUSE SDK DVD locally from [https://download.suse.com/index.jsp](https://download.suse.com/index.jsp)
 - then add it as a local repo with a command like 
`zypper addrepo iso:/?iso=/path/to/iso1.iso disk1`
 - install `python-devel`
 - apply the relevant patches `python-devel` from [https://download.suse.com/patch/finder/](https://download.suse.com/patch/finder/)

I'll try to update the SUSE part in the coming weeks.

As another alternative, you can also install it on your local PC and remotely connect to your HXE instance as well.

**Comment by sarahESL** [comment]
Thanks for your response. Although the suggested command for adding the iso as repo does not work (error: URI or .repo required). I used "zypper ar -c -t yast "iso:/?iso=/path/to/image/SLE-12-SP2-Server-DVD-x86_64-GM-DVD1.iso" "repo_name" ``` instead and it worked. However, it still says "Package found python-devel not found"!

**Comment by sarahESL** [comment]
I solved the issue: the image I was using was not the SDK! SDKs can be downloaded from https://download.suse.com/Download?buildid=g3e7P21X6Lw~

**Comment by adadouche** [comment]
fixed in commit : https://github.com/SAPDocuments/Tutorials/commit/8d797a1ad7cb09ccb3eced6d2d5c91f2fe04c077
