### ISSUE TITLE
Implement the Register Dataset services

### ISSUE THREAD

**Issue by alamo77** [SAPDocuments/Tutorials#2422]
When push REGISTER DATASET I have the following error: 

![image](https://user-images.githubusercontent.com/39528749/41794189-ef10780c-7634-11e8-90f1-1f4e294ea466.png
![image](https://user-images.githubusercontent.com/39528749/41794203-ff91a57a-7634-11e8-8257-ec601a7f2027.png)
)
Please help!!

**Comment by adadouche** [comment]
Hi @alamo77 

Usually this error is linked to the fact that the CENSUS table doesn't exists in the PSDEMO schema as described in the [Configure SAP Predictive Service](https://www.sap.com/developer/groups/ps-configure.html) group at the [Import a series of predictive demo dataset](https://www.sap.com/developer/tutorials/hcpps-hana-dataset-import.html).

Can you check if you completed the  [Import a series of predictive demo dataset](https://www.sap.com/developer/tutorials/hcpps-hana-dataset-import.html)?

Thanks

**Comment by alamo77** [comment]
It's works!!

Thanks a lot!
