### ISSUE TITLE
SAP HANA XS Advanced - Web Sockets within Node.js SAP HANA applications

### ISSUE THREAD

**Issue by incata** [SAPDocuments/Tutorials#2427]
Hi, thanks for tutorial, but anyway as non node.js guy i found it very confusing,
there is no information about what we shall put into server.js and how it redirect to index.js file

i also found one major details even more confusing:

in chatServer.js you define server like this:
var wss = new WebSocketServer({ server: server, path: "/node/chatServer" });

and "/node/chatServer" its ok, in index.html of frontend app you including path
var connection = new sap.ui.core.ws.WebSocket('/node/chatServer');
and its still ok, but then you passes as server variable in index.js:
app.use("/node/chat", require("./routes/chatServer")(server));

and "/node/chat" is not used and mentioned anywhere, i guess it should be "/node/chatServer"?

can you also provide information(or just code) of mta.yaml configuration?

also it would be nice if you would upload to git all files from project related to this tutorial...

I've searched for any related issues and avoided creating a duplicate issue.

Reproducible in:
version:
Node.js version(s): 4.8.4
WS version 1.1.1
express 4.15
OS version(s): HANA express SPS 2.0 revision 23

Steps to reproduce:
complete tutorial https://www.sap.com/developer/tutorials/xsa-node-websockets.html
Expected result:
connection to websocket server

Actual result:
WebSocket connection to 'wss://***:/' failed: Connection closed before receiving a handshake response

**Comment by thecodester** [comment]
I will leave for @Lsubatin to answer the technical questions. But what did you mean "I cant find here any example related to tutorial structure"?

**Comment by incata** [comment]
sry, forget about this line

**Comment by incata** [comment]
is anybody here? really the full project including server.js file will be enough to solve this problem...

**Comment by Lsubatin** [comment]
Hi, Incata, 
It should be chatServer if that is what the js module is called within the routes:


`/*eslint-env node, es6 */   "use strict";       module.exports = (app, server) => {               app.use("/node",   require("./routes/myNode")());               app.use("/node/excAsync",   require("./routes/exerciseAsync")(server));               app.use("/node/JavaScriptBasics",   require("./routes/JavaScriptBasics")());                          app.use("/node/textBundle",   require("./routes/textBundle")());                      app.use("/node/excel",   require("./routes/excel")());               app.use("/node/xml",   require("./routes/xml")());                   app.use("/node/zip",   require("./routes/zip")());                                 app.use("/node/chat", require("./routes/chatServer")(server));                };`
--

index.js:

/*eslint no-console: 0, no-unused-vars: 0, no-undef:0*/
/*eslint-env node, es6 */

"use strict";
var https = require("https");
var xsenv = require("@sap/xsenv");
var port = process.env.PORT || 3000;
var server = require("http").createServer();
https.globalAgent.options.ca = xsenv.loadCertificates();
global.__base = __dirname + "/";

//Initialize Express App for XSA UAA and HDBEXT Middleware
var passport = require("passport");
var xssec = require("@sap/xssec");
var xsHDBConn = require("@sap/hdbext");
var express = require("express");

//logging
var logging = require("@sap/logging");
var appContext = logging.createAppContext();

//Initialize Express App for XS UAA and HDBEXT Middleware
var app = express();

passport.use("JWT", new xssec.JWTStrategy(xsenv.getServices({
	uaa: {
		tag: "xsuaa"
	}
}).uaa));
app.use(logging.expressMiddleware(appContext));
app.use(passport.initialize());
var hanaOptions = xsenv.getServices({
	hana: {
		tag: "hana"
	}
});
//hanaOptions.hana.rowsWithMetadata = true;
app.use(
	passport.authenticate("JWT", {
		session: false
	}),
	xsHDBConn.middleware(hanaOptions.hana)
);

//Setup Routes
var router = require("./router")(app, server);

//Start the Server 
server.on("request", app);
server.listen(port, function() {
	console.info(`HTTP Server: ${server.address().port}`);
});


 These files will only work as they are if you have completed the dependencies.  I am in the process of updating these so they do not depend on so many previous tutorials.

Cheers, 
Lucia.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
