### ISSUE TITLE
Set up SAP Data Hub, developer edition

### ISSUE THREAD

**Issue by entmike** [SAPDocuments/Tutorials#2429]
It would also help if you call out an alternative docker run command in the case  you are running Data Hub Developer Edition from within a separate Linux server/VM and not on same workstation as you'll be using the browser.  This worked for me (simply remove the 127.0.0.1: parts)

` sudo docker run -ti --publish 8090:8090 --publish 8998:8998 --publish 9225:9225 --publish 50070:50070 --name datahub --hostname datahub --network dev-net datahub run --agree-to-sap-license --hdfs --livy`

**Comment by schneidertho** [comment]
Hi Mike, 
thanks for the feedback. I have added a short explanation to our FAQs (https://blogs.sap.com/2017/12/06/faqs-for-sap-data-hub-developer-edition/). We will also add an alternative command to the tutorial itself.
BR
Thorsten

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
