### ISSUE TITLE
Configure the TensorFlow integration (SAP HANA EML) with SAP HANA, express edition

### ISSUE THREAD

**Issue by bknl** [SAPDocuments/Tutorials#2430]
Hi, I have a few suggestions for improvement to the EML/TensorFlow Serving integration tutorial.

Minor thing: Outdated graphics for the technical architecture (was wrong in our initial official documentation, wrong labeling of the TensorFlow Modelserver in the graphics). For the updated one, see

https://help.sap.com/viewer/ab6b04eb12d3452aa904d5823416a065/2.0.03/en-US/b82fc9aea9bd4a6b8109ece15b67b83a.html

Bigger thing: The tutorial states that no prebuilt TMS binaries exist for RPM-based distributions (SLES12 and Redhat in particular).  This is wrong. SAP delivers prebuilt binaries on all supported HANA platforms.
See

https://help.sap.com/viewer/ab6b04eb12d3452aa904d5823416a065/2.0.03/en-US/811e04e89078469e87cd28f222779f97.html

If these are sufficient for the purposes of the tutorial, then the cumbersome and timeconsuming "built TensorFlow Serving from source" (i.e. Step 5) can be replaced by a simple

"Download correct RPM from Google Drive. rpm -i <rpm-package>"

Lastly, for operational systems at least, we recommend to keep two separate user roles for administering the landscape of TMSs and model deployments (EML_ADMIN) and calling the models in code (EML_USER). The permissions as given in the tutorial will work but would be too broad for normal application usage.

**Comment by adadouche** [comment]
@bknl 

Thanks for your feedback, as per our email discussion, I will wait for clarification on the usage of the pre-built binaries and the associated support statement in the documentation along with the delivery/download location.

I will definitely update the diagram, and consider the HANA database user split in the next update.

Regards

**Comment by adadouche** [comment]
addressed architecture diagram and user creation is commit: https://github.com/SAPDocuments/Tutorials/commit/1b95f12008345c355f95524415902f0be6c56263

**Comment by bknl** [comment]
I have worked with the Google team and the yesterday evening merged my
security changes to the main repository. So in the near future you can just
point them to the prebuilt Google binaries.  When we've updated our
documentation acordingly, I'll notify you.

  Regards,

    Burkhard

https://github.com/tensorflow/serving/commit/9e960b37607da80b8c4c06754e0873c71ae1cd2f

Am Do., 12. Juli 2018 um 09:30 Uhr schrieb Abdel Dadouche <
notifications@github.com>:

**Comment by adadouche** [comment]
@bknl 

Thanks for letting me know. 

However, the prebuilt Google binaries are only available for Ubuntu / Debian distro not for SLES nor RHEL. Therferoe the "full" compile is and will remain needed.

Let me know if this issue can be closed now.

Best Regards

**Comment by adadouche** [comment]
Hi @bknl 

I'll close this issue for now. Let me know if you want to further discuss it.
