### ISSUE TITLE
Build an SAP Fiori UX app with SAP Gateway data

### ISSUE THREAD

**Issue by adenista** [SAPDocuments/Tutorials#2432]
I'm trying to follow along this tutorial and am getting stuck in step 5. The screen on the tutorial only shows project name as required but in my WebIDE session, I am required to enter the title and namespace as well.  Then in step 6, I can't enter or select anything for the system under the service catalog. I am log in with my S id in both my WebIDE as well as Netweaver Gateway ES5 account in another browser tab.

Thank you in advance for any help.

Jose P

**Comment by VivekRajKM** [comment]
Hi Adenista,
Validate if you have provided the connections part in SAP Cloud Platform Cockpit ?
Connections are defined there so as to populate in Step 6 here. 

Cheers,
Vivek.

**Comment by mhassett92** [comment]
Also make sure to refresh your Web IDE after defining a new destination in the SAP Cloud Platform Cockpit as the Web IDE does cache this file.

For more info on creating a destination, follow this tutorial: [Create a destination for the Gateway services](https://www.sap.com/developer/tutorials/teched-2016-3.html)

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
