### ISSUE TITLE
Grunt Build in SAP Web IDE

### ISSUE THREAD

**Issue by kathiewright** [SAPDocuments/Tutorials#2439]
I am running into the local grunt file error in a HTML5 module created in an MTA project.  Any ideas on how that can be fixed?  There is no Build option in the context menu for the module.

**Comment by thecodester** [comment]
@jhornik Can you help Kathie?

**Comment by jhornik** [comment]
Hi @kathiewright - can you provide more details and maybe a screen shot? Can you describe where exactly you right-clicked to get the context menu?

Regards,
Julia

**Comment by avizov** [comment]
Hi,
We are not supporting an explicit build of the HTML5 module. It's supported on MTA build level only, as a build of entire MTA application. 
Thanks,
Alex

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
