### ISSUE TITLE
Create an account on the Gateway Demo system: Step 7

### ISSUE THREAD

**Issue by indeabap** [SAPDocuments/Tutorials#2441]
Tutorial https://www.sap.com/developer/tutorials/gateway-demo-signup.html

Progressed to step 7: 'Enter the URL of the SAP Easy Access page below and click Validate' 
1. I copied in the URL: https://sapes5.sapdevcenter.com/sap/bc/gui/sap/its/webgui
2. Clicked validate but get 'Invalid response. Please try again'

What is the correct URL to paste to validate and complete the tutorial?

I've successfully logged into the SAP Gateway Web GUI ES5 and url displayed is https://sapes5.sapdevcenter.com/sap/bc/gui/sap/its/webgui

**Comment by jonathanbaker7** [comment]
The URL can be shortened to:  https://sapes5.sapdevcenter.com (and will redirect).  

To answer the bug, however, this was an issue with the server, which is now resolved.  I just checked, and the link works fine.  Let me know if you have any further issues!
