### ISSUE TITLE
Configure Android Studio for mobile development

### ISSUE THREAD

**Issue by faisalahmedansari20** [SAPDocuments/Tutorials#2445]
Hi,

I am getting error while installing **SMP3SDKInstaller_3_16_0_win** it is giving me following exception 
![image](https://user-images.githubusercontent.com/23935309/42628652-624f07ac-85ee-11e8-8f77-04a653dcc0f6.png) .
 I am installing it on windows 10 which has  16 gb ram , and 64 bit OS. Please help

**Comment by qmacro** [comment]
Assigning Kevin as a mobile resource on this.

**Comment by KevinMuessig** [comment]
Hi @faisalahmedansari20 
let me setup a windows machine on my Mac and let me try to reproduce the issue you have.
I will get back to you as soon as possible.

Thanks

**Comment by jarjarbentley** [comment]
@flyingfish162  can you look at this?

**Comment by zhangyanning** [comment]
@jarjarbentley , this is a SMP Native SDK issue instead of Cloud Android SDK, correct? i will find someone from SMP Native SDK team to take a look this.

**Comment by jarjarbentley** [comment]
> @jarjarbentley , this is a SMP Native SDK issue instead of Cloud Android SDK, correct? i will find someone from SMP Native SDK team to take a look this.

Ok.  please let me know when complete or we can assign to a new person.

**Comment by MichaelCzcz** [comment]
@zhangyanning Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
