### ISSUE TITLE
SAP HANA XS Advanced - Consume the OData service in a basic HTML5 module

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2453]
Hi Lucia!
I'm not able to pass this tutorial with an issue related to SAPUI5 micro-service configuration.
By some reason "sapui5_sb" is always resolving into "localhost" instead of "hxehost" and I'm constantly getting #ERROR#/AppController/Dispatcher################PLAIN##Error occurred, Cannot proxy application requests...Error: connect ECONNREFUSED 127.0.0.1:61721# on execution.

I have tried to change ui5 type from org.cloudfoundry.managed-service to configuration with provider-id 'com.sap.ui5.dist.sapui5-dist-xsa.XSAC_UI5_FESV3:sapui5_fesv3' but the result is the same, it resolving to 127.0.0.1 and ECONNREFUSED on the web module start.

Do you have any ideas how to fix this?

**Comment by thecodester** [comment]
@Lsubatin Can you address or close? Thanks

**Comment by Lsubatin** [comment]
This path has changed a couple of times since then. Closing
