### ISSUE TITLE
How to create an SAP HANA Developer Edition in the Cloud

### ISSUE THREAD

**Issue by I1eoThe0ne** [SAPDocuments/Tutorials#2457]
Thanks for the tutorial.

We followed the tutorial and now need to activate SLES 12.1.

This solution does not work:
/usr/sbin/registercloudguest --force-new
src: https://www.suse.com/de-de/support/kb/doc/?id=7022311

How to do it?

**Comment by Lsubatin** [comment]
Sorry about the delay for this. The recommended channel for support is answers.sap.com. 

Hopefully you have found how to activate Suse by now. You can also get HXE running on openSUSE or Ubuntu.
