### ISSUE TITLE
SAP DataHub Developer trial Edition to download

### ISSUE THREAD

**Issue by rsarathy101** [SAPDocuments/Tutorials#2458]
How do I download the trial version ? I come to this link, and there is no download link.

https://www.sap.com/developer/trials-downloads/additional-downloads/sap-data-hub-developer-edition-1-4-15004.html

**Comment by thecodester** [comment]
There is a link at the bottom, in blue - SAP Data Hub, developer edition 1.4. This seems to start a wizard.

@kulkarniamogh Can you also comment?

**Comment by kulkarniamogh** [comment]
Hello, 

Yes, you need to be logged in, in order to download the developer edition. Once you click that link, it will take you to a page where you can either log in or create an account. The download process will then follow after logging in.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
