### ISSUE TITLE
Consume the API Proxy in SAP Web IDE

### ISSUE THREAD

**Issue by nithish-p** [SAPDocuments/Tutorials#2459]
Hi I am trying to consume API from destination APIM_DevPortal_Trial - Destination to API Developer Portal with hostname https://SXXXXXXXXtrial.apim1.hanatrial.ondemand.com:443 and basic auth with SAP CP credentials
as in tutorial [](https://www.sap.com/developer/tutorials/hcp-apim-webide-int.html).

After selecting the API Product, system was prompting a pop up for Authentication. I tried with ES4 demo system credentials as well as SAP CP trail account credentials,but returned with error "API Authentication Type not supported".

When I checked the developer portal in the API Managemnt, I did see an application was created and was subscribed to entered webide project.

Please assist.

Thanks!

**Comment by mhassett92** [comment]
Please make sure to create an ES5 demo system account. ES4 has been deprecated and all URLs for that service will throw errors. Let me know if you are still seeing this issue when you upgrade your Gateway system!

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
