### ISSUE TITLE
SAP HANA XS Advanced - Clone and run SHINE applications

### ISSUE THREAD

**Issue by rehan1** [SAPDocuments/Tutorials#2460]
I followed the steps outlined in the [tutorial ](https://www.sap.com/developer/tutorials/xsa-ml-e2e-access-shine.html) for building SHINE but i get a build error that i'm unable to troubleshoot. Would anyone know what i am missing?

![image](https://user-images.githubusercontent.com/8646924/42956754-cbd5289a-8b4e-11e8-8ed3-9be00974c3a8.png)

Thanks
Rehan

**Comment by Lsubatin** [comment]
Hi, Rehan, 

Please refer to this:  https://answers.sap.com/questions/557906/i-could-not-build-the-database-module-in-web-ide-a.html 

Cheers, 

Lucia.

**Comment by rehan1** [comment]
Thank you for the quick response. That resolved the issue!
