### ISSUE TITLE
SAP HANA XS Advanced, Creating an HTML5 Module - Solution for "no builder" problem.

### ISSUE THREAD

**Issue by devnieL** [SAPDocuments/Tutorials#2462]
Hello,

I was following this tutorial until I got stuck on the building because of an error :

> (Builder) Could not start the build because no builder is installed in your space (development)

The solution was to active the **di-space-enablement-ui** on the SAP space, access it and enable the building for the "development" space.

Thanks

**Comment by Lsubatin** [comment]
Hi, Daniel, 

Thank you for letting us know. This solution is documented in the Q&A and is not related to this specific tutorial, so closing the issue.

Best, 

Lucia.
