### ISSUE TITLE
SAP HANA XS Advanced, Creating a Simple OData Service

### ISSUE THREAD

**Issue by venkataanil58** [SAPDocuments/Tutorials#2469]
Hi Team,

I am able to perform the Filter Operations by using the XSOData, But I am not able to perform the search Operation.  
Note: We are consuming this xsodata via odata service.
Eg: test.xsodata/Entity?search='free search'
OData Service : Enitity?search='free search'

Thanks and Regards,
Venkata Anil

**Comment by Lsubatin** [comment]
This was answered in the community, search is OData V4 and xsjs provides OData V2.
