### ISSUE TITLE
Configure the TensorFlow integration (SAP HANA EML) with SAP HANA, express edition

### ISSUE THREAD

**Issue by Victorsoukhov** [SAPDocuments/Tutorials#2475]
Hello!
Very detailed and good tutorial!
Helps me a lot with installation of TFS on Redhat.

Thank you very much!!!
Victor Soukhov. Nornickel, Moscow, Russia.

**Comment by thecodester** [comment]
Thanks for the feedback. And nice work, @adadouche.
