### ISSUE TITLE
Logging tutorials seem outdated, unable to figure out manual logging

### ISSUE THREAD

**Issue by carstenhag** [SAPDocuments/Tutorials#2481]
These are the tutorials I'm referring to: https://www.sap.com/developer/tutorial-navigator/mobile-interactive-tutorials/logger/native-ios.html

I tried to implement some logging into my app, and am trying out this functionality. All messages get printed out to the console, but sadly none show up on the Mobile Service for Development and Operations.

I'm pretty sure my issue is just that I'm creating logs, but not uploading them. My understanding is, that I have to manually run executeLogs(), which seems rather weird. Logging tools like firebase or crashlytics automatically handle this, so it doesn't clutter my app.

Anyway, I looked at the tutorials. (Download the advanced project to repro). They use an `Authenticator.swift` class, with hardcoded provider URL. They authenticate everything from inside the first ViewController. 

This is not what the generated apps with 2.+ SDK do. They authenticate, to my understanding, in the `configuredWelcomeScreenStep()` method in `OnboardingManager.swift`.

In `AppDelegate.swift` there is this method that uploads logs after startup (but as they always seem to be cleared after closing the app, my own logs are never uploaded).

```swift
    func onboarded(onboardingContext: OnboardingContext) {
        self.configureOData(onboardingContext.sapURLSession, onboardingContext.authenticationURL!)
        self.setRootViewController()

        self.uploadLogs(onboardingContext.sapURLSession, onboardingContext.sapcpmsSettingsParameters!)

        self.registerForRemoteNotification(onboardingContext.sapURLSession, onboardingContext.sapcpmsSettingsParameters!)
    }
```

There is also this method, that actually uploads the logs.
```swift
    // This function is invoked on every application start, but you can reuse it to manually triger the logupload.
    private func uploadLogs(_ urlSession: SAPURLSession, _ settingsParameters: SAPcpmsSettingsParameters) {
```

Unfortunately, I have no clue where to get the necessary parameters for `SAPcpmsLogUploader.uploadLogs()`.

I have tried to store urlSession and the settingsParameters as variables inside AppDelegate, so I could access them from my Views, but that didn't quite work. Probably did something wrong there.

It really seems to me that the tutorials are from an outdated SDK version.

----

Could you please tell me how manually uploading logs works? If there is a way to do this automatically, I'd appreciate that too.

**Comment by KevinMuessig** [comment]
Hi @carstenhag,

The updated tutorial will be online soon, we’re working on bringing them up to date at the moment. 
Let me put together a simple example for you.

**Comment by KevinMuessig** [comment]
Hi @carstenhag 
We recommend to build in a functionality for the user to manually upload the logs to the cloud for the support team to look into the issues occurred.
To actually receive logs on the cloud side you have to activate this functionality and optionally define rules there.

You can read about this in the official documentation:
[
https://help.sap.com/doc/978e4f6c968c4cc5a30f9d324aa4b1d7/Latest/en-US/Documents/Frameworks/SAPFoundation/Log%20Upload.html](url)

The parameters actually are:

- sapURLSession which is your URLSession object
- settingsParameters which are of type SAPcpmsSettingsParameters

**SAPcpmsSettingsParameters**

> Structure to hold SAPcpms settings metadata. E.g. on which host can be found the given application by applicationID. Extra information could be store for the device and user specific settings.

Means that you can find those information inside your mobile services account under the correlating application configuration you've created.

Does this help you? If not let me know.
