### ISSUE TITLE
<content>     <core:Fragment fragmentName="com.test.teched.view.Map" type="XML" /> </content>

### ISSUE THREAD

**Issue by EvgeniiMarch** [SAPDocuments/Tutorials#2482]
Hi
A problem appears after step 16 where we put this code
<content>
    <core:Fragment fragmentName="com.test.teched.view.Map" type="XML" />
</content>

App runs with white screen and nothing happens further. Even though we change manifest file in step 17 the problem is stayed.

**Comment by thecodester** [comment]
You are referring to this tutorial?

https://www.sap.com/developer/tutorials/teched-2016-6.html

**Comment by EvgeniiMarch** [comment]
Yes, this tutorial is with bug on 16th step. I tried it twice, and I had to skip this step.
After that I found out that [next](https://www.sap.com/developer/tutorials/teched-2016-7.html)  tutorial doesn't work with "NoAuthentification" in destinations area in SCP.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
