### ISSUE TITLE
Build an SAP Fiori UX app with SAP Gateway data

### ISSUE THREAD

**Issue by VivekRajKM** [SAPDocuments/Tutorials#2486]
When tried create a new project template from SAP WebIDE, after Step 10 am unable to proceed for loading the project template. 
Would you please guide me through if any mistake ?

Cheers,
Vivek.
![ui5 resource not loaded into project template](https://user-images.githubusercontent.com/17874349/43517435-921f88a2-9580-11e8-8669-a2d856ddeea8.JPG)

**Comment by mhassett92** [comment]
Hi Vivek,

Are you using an older version of UI5? The error messages suggests that you may not be using the latest release of UI5 which is 1.56. Also, please be sure to be using the Web IDE Full Stack, as the standard Web IDE is no longer being maintained.

Let me know if either of this solve the issue!

Thank you,
Meredith

**Comment by VivekRajKM** [comment]
@mhassett92 : I am using a WebIDE full stack and still I am unable to load the resource. Also do we need to have eclipse in the system even for webIDE ?

**Comment by VivekRajKM** [comment]
@mhassett92 While creating the project template, I did select the 1.56 version template in webIDE full stack, even then I am unable to load the resource and plugin. Any advice or steps ?

**Comment by VivekRajKM** [comment]
Also I tried enabling all the plug-ins available in the webIDE. It still gives me the error for not loading the resource. 

![plugins enabled](https://user-images.githubusercontent.com/17874349/43585221-7b9f8500-965c-11e8-8fa3-c539e12354d2.JPG)
![template error after enabling all plugin](https://user-images.githubusercontent.com/17874349/43585222-7bd935e8-965c-11e8-97eb-0139506656ac.JPG)

**Comment by VivekRajKM** [comment]
@mhassett92 Is this resolved ? Or any workaround if available please.

**Comment by VivekRajKM** [comment]
@mhassett92 Is it administrative permission with roles ? Do drop by some leads please ?

**Comment by mhassett92** [comment]
Hi Vivek,
Apologies for not getting back sooner, but this one has me stumped. I am going to reach out the product team to see if we can dig deeper. In the meantime to help us troubleshoot some more, can you open the Web IDE console and share if there is anything in the logs? The console can be found by clicking this icon in the lower right side of the screen.
![screen shot 2018-08-06 at 4 38 45 pm](https://user-images.githubusercontent.com/1703983/43746162-74d52f84-9997-11e8-9275-52319bfe6a5a.png)

Thank you and apologies,
Meredith

**Comment by VivekRajKM** [comment]
@mhassett92 :) Thanks for getting back on this. I tried and even before loading template, console gives the exact error highlighted by you. Also, there are empty folders created on the workspace where the normal expectation would be rollback on any failure in loading the template. 

Attaching image for your reference. 
![console validation failure](https://user-images.githubusercontent.com/17874349/43765411-c751250c-9a27-11e8-9968-3f28eda7b3f6.JPG)

**Comment by VivekRajKM** [comment]
@mhassett92 Any updates? We are in real tight deadlines for building an app. Kindly revert back.

**Comment by VivekRajKM** [comment]
Adding to that we might have another directory to check. 

> 'sap.watt.saptoolsets.ui5.project.ui5template' plugin

![plugin error 2](https://user-images.githubusercontent.com/17874349/43948363-8ad74dec-9c82-11e8-90d1-d93cf7913a7a.JPG)

Note: This is when I load a UI5 template from the project template path.

**Comment by VivekRajKM** [comment]
One more hunch is these happens for all trial accounts. Developer edition of WebIDE is all safe and is able to create templates from there.

**Comment by VivekRajKM** [comment]
Any updates?  Resolved or any point I am missing ?

**Comment by VivekRajKM** [comment]
@mhassett92 Any updates ?

**Comment by VivekRajKM** [comment]
@mhassett92 Any updates ?

**Comment by VivekRajKM** [comment]
@mhassett92 @thecodester This issue has been resolved, thanks for the support.

**Comment by PriyadharshiniArul** [comment]
> Hi, I have the same problem. How did you solve it?

**Comment by PriyadharshiniArul** [comment]
@VivekRajKM  Hi, I have the same problem, How did you solve it?
