### ISSUE TITLE
Commit your project to Git and deploy to the cloud

### ISSUE THREAD

**Issue by rjayasa** [SAPDocuments/Tutorials#2487]
Hi there,
When i run the step 18 as per tutorial, i am getting this error.
Sorry, a technical error occurred! Please try again later.
\{
	"message": "HTTP request failed",
	"headers": [],
	"statusCode": 504,
	"statusText": "Gateway Timeout",
	"responseText": "HTTP Status 504 - An internal application error occurred.\nRequest: 1666868938 i849974trial:te2016"
}

Is the related to this error i submitted earlier.
Sorry, a technical error occurred! Please try again later.
\{
	"message": "HTTP request failed",
	"headers": [],
	"statusCode": 504,
	"statusText": "Gateway Timeout",
	"responseText": "HTTP Status 504 - Socket connection timed out for host https://sapes5.sapdevcenter.com. Reason: Read timed out (local port 37081 to address 10.117.12.64 (vsa4345860.nwtrial.od.sap.biz), remote port 8080 to address 10.117.18.16 (sgw-a1s-03-int.od.sap.biz))"
}

**Comment by mhassett92** [comment]
This is an issue with the Gateway service. We are looking into how it can be resolved. Thank you for your patience!

**Comment by mhassett92** [comment]
The BusinessPartnerCollection is down. If you would like to continue with the tutorials, please redo the template wizard and utilize one of the other collections for the Object Collection and Line Item Collection.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
