### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by rjayasa** [SAPDocuments/Tutorials#2491]
Hi there,

I am having the error when run the application as per the last step in
started building the app tutorial.
https://www.sap.com/developer/tutorials/teched-2016-4.html

In the step 17 when I launch the app I get the following:

Sorry, a technical error occurred! Please try again later.
{
"message": "HTTP request failed",
"headers": [],
"statusCode": 504,
"statusText": "Gateway Timeout",
"responseText": "HTTP Status 504 - Socket connection timed out for host https://sapes5.sapdevcenter.com. Reason: Read timed out (local port 33351 to address 10.117.12.196 (vsa3718601.nwtrial.od.sap.biz), remote port 8080 to address 10.117.18.16 (sgw-a1s-03-int.od.sap.biz))
"
}

Is the gateway server down?

Thanks,
Jay

**Comment by qmacro** [comment]
Hi Jay - I've been using ES5 with no issue this week, for what it's worth. I've also just tried accessing the GWDEMO service (referenced in the tutorial you're following) and I can access it fine, both directly, and via the connectivity service (destination + neo-app.json route). Are you still seeing the issue at your end?

**Comment by qmacro** [comment]
Closing, assuming issue no longer being experienced. Please feel free to re-open if that's not the case. Thanks.
