### ISSUE TITLE
Deploy your app to Fiori Launchpad

### ISSUE THREAD

**Issue by romer9** [SAPDocuments/Tutorials#2492]
Hi,

Appears there are steps missing between the first course and this course. I did figure out some of the missing steps. I am still unable to import the App into the WEB IDE (Full Stack) as I get the following error: "The application does not have an active version".  Additional direction would be appreciated.

Thanks!

**Comment by mhassett92** [comment]
You must first deploy you application to the SAP Cloud Platform. Make sure when doing so to check that it is activated. 
![image](https://user-images.githubusercontent.com/1703983/43745760-604802aa-9995-11e8-80ff-7f0af5fcc1c2.png)

After deploying to the SAP Cloud Platform, you can register the app to the Fiori Launchpad.

**Comment by romer9** [comment]
Hi Meredith,





________________________________

**Comment by romer9** [comment]
Hi Meredith,


Note that I am in the SAP Web IDE Full applications. I am unable to deploy because I do not have an active version. Note the results from 'File --> Import  --> Application from SAP Cloud Platform.


[cid:8bc0fe72-0818-4a40-be08-4df36b6fa1a1]


________________________________

**Comment by mhassett92** [comment]
Did you mean to attach some images in your latest comment? If so, I am unable to see them. If you are importing the project from BUILD, you need to follow the steps in the tutorial that indicate it should be created via the New Project from Template option. BUILD projects are not directly compatible with SAP Cloud Platform.

**Comment by romer9** [comment]
Hi,


Yes, there should have been a screen shot. What is 'BUILD'? I have followed the steps in  the tutorial.


Thanks


________________________________

**Comment by mhassett92** [comment]
Can you please attach the screenshots? No where in this tutorial series should you be using the File > Import option.

**Comment by romer9** [comment]
Hi,


Have attached a Word document with the the screen shot. You can see that my other Apps have loaded and the 'jjjllotteryapp' will not load because it does not have an active version. I tried the option of File > Import to see if that would resolve the problem.


Thanks


________________________________

**Comment by thecodester** [comment]
@rbrainey can you handle this?

**Comment by rbrainey** [comment]
No. I'm going to remove Meredith and myself and assign it to one of our SCP topic owners.

**Comment by IObert** [comment]
Hi @romer9,

Unfortunately, GitHub removes all attachments from the email before it converts it to a response.
Can you please upload the file directly [here](https://github.com/SAPDocuments/Tutorials/issues/2492)

**Comment by romer9** [comment]
Hi Marius,

Thank you for your response. Unfortunately I do not have the screen shots/attachments any more. I encountered this challenge (issue) a year ago. Since then I have moved on.

Regards,
Jerome
________________________________

**Comment by IObert** [comment]
Hi Jerome,

sorry that we didn't get back to you earlier. I'll close this issue then
