### ISSUE TITLE
Image Similarity Scoring example with SAPUI5

### ISSUE THREAD

**Issue by Abhishekachal** [SAPDocuments/Tutorials#2495]
Hi
I am facing Issue with the Image Similarity Scoring example.
I have put the code as given https://www.sap.com/developer/tutorials/ml-fs-sapui5-img-similarityscoring.html
The code works only till getting the images.
Once I try to do a score compare , it some how goes into some loop.
![image scoring](https://user-images.githubusercontent.com/14941528/43649333-6608f458-972c-11e8-9fad-01e265adf56b.PNG)

**Comment by adadouche** [comment]
Hi @Abhishekachal

Can you open the browser dev tools and inspect the console for exceptions?

Thanks

**Comment by adadouche** [comment]
Hi @Abhishekachal 

Any feedback on this issue?

Hi @kawaiipooptato,

Apparently the service has been renamed on the SAP API Business Hub. Are you using the API endpoint from the tutorial or from the SAP API Business Hub?

Thanks

**Comment by adadouche** [comment]
Fixed in [af4c7b8](https://github.com/SAPDocuments/Tutorials/commit/af4c7b87d88b718af0ff812cbb828abaa1cd11fd).
