### ISSUE TITLE
Build an SAP Fiori UX app with SAP Gateway data

### ISSUE THREAD

**Issue by vedvish** [SAPDocuments/Tutorials#2496]
Hi,

I have come to the step 4 of the tutorial - Build an SAP Fiori UX app with SAP Gateway data, without any issues. However, I am stuck at step 4.6 which asks to "Select the data connection" wherein i am unable to find any destination in the pull down list for the service catalog which, ideally, should have displayed the destination which i had successfully set-up as per the step 3 - Create an SAP Cloud Platform destination pointing to an SAP Gateway.

![capture](https://user-images.githubusercontent.com/42071382/43652587-3f8039a4-9763-11e8-976d-0f03409e31e5.PNG)

![image](https://user-images.githubusercontent.com/42071382/43652781-c67aac82-9763-11e8-993f-392c37779b91.png)

What might be the reason for this?

Best Rgds
Vish

**Comment by vedvishwa** [comment]
Is cloud connector set-up also required for this exercise?

**Comment by mhassett92** [comment]
Alway remember to refresh your SAP Web IDE when creating new destinations as the SAP Web IDE does cache this information. When you refresh, are you able to see the destination?

**Comment by mhassett92** [comment]
Another potential issue may arise from your WebIDEUsage property which should be set to odata_abap, not odata_sap.

**Comment by vedvish** [comment]
Voila! I just overcame the issue with your suggestions: It has to be odata_abap, not odata_sap. Thanks for this.
I have another issue in the same step 4. I have successfully completed all the instructions of the step, but i am not getting the output in the end when i run the project/app in the ide. 
My project looks like this:
![image](https://user-images.githubusercontent.com/42071382/44032342-709fc1b2-9f24-11e8-9c2e-234d265c46e8.png)
I get the below message when i run the app:
![image](https://user-images.githubusercontent.com/42071382/44032646-6dccdc8a-9f25-11e8-900c-01b7695bf70e.png)

Any suggestions to overcome this?

Best Regs,
Vish

**Comment by mhassett92** [comment]
This is related to an issue with the BusinessPartnerCollection from the ES5 service. I would recommend using a different entity in the template wizard while we are investigating why that collection is down. All others seem to be working fine! (ie ProductCollection works)

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
