### ISSUE TITLE
Create a Thing Model and Bind to Device

### ISSUE THREAD

**Issue by monokizsolt** [SAPDocuments/Tutorials#2503]
Hi,

I am trying to create a thing but I'm stuck as nothing shows up on the list when I click to select my device. 

![image](https://user-images.githubusercontent.com/37185573/43770469-c224f4d6-9a3c-11e8-9643-c037f1970de9.png)

My device in the cockpit:
![image](https://user-images.githubusercontent.com/37185573/43770519-eb176842-9a3c-11e8-87c2-6402a024faf7.png)

I was able to send data to my device and it works as intended. 

Any help is appreciated,
Zsolt Monoki

**Comment by thecodester** [comment]
@marcuscbehrens Can you help Zsolt?

**Comment by monokizsolt** [comment]
Thank you @marcuscbehrens ! Issue was fixed as of today with your solution. Best Regards, Zsolt

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
