### ISSUE TITLE
Consume an OData Service with Create Option

### ISSUE THREAD

**Issue by git-ashish** [SAPDocuments/Tutorials#2507]
For tutorial https://www.sap.com/developer/tutorials/xsa-sapui5-consume.html :-
 
Getting an error on execution of final step. The error is an Alert with a message - 'Error while executing a DB query'

From my observation, there is a user.xsjs service which is being referenced in Step 2: Copy the OData create service. But I could not find its content or guidance on creation of this file. 

```
service {
	"UserData.User" as "Users"
	create using
	"user.xsjs:usersCreateMethod.xsjslib::usersCreate";
}
```
Any insights will be helpful.

Thanks.

**Comment by Lsubatin** [comment]
Hi, Ashish,
The creation of that service is done here: https://sap.com/developer/tutorials/xsa-xsodata-create.html 

As I commented in the other issue, I'm working in rebuilding the dependencies as they get everyone lost.
Best, 
Lucia.

**Comment by git-ashish** [comment]
Hi Lucia,

Thanks for the pointer but that tutorial unfortunately doesn't solve the dependency.
There is this code in usersCreateMethod.xsjslib - 

`$.import("user.xsjs", "session");
var SESSIONINFO = $.user.xsjs.session;
`
But there is no mention of **user.xsjs** service code. Where can I get it from?

Thanks for you help!

**Comment by macott** [comment]
Hi Ashish,
The "user.xsjs" is not referring to the xsjs file.
It is about the location of  session.xsjslib file.

You can see session.xsjslib is under /user/xsjs directory.
https://github.com/SAP/com.sap.openSAP.hana5.example/tree/master/user-js/lib/user/xsjs

**Comment by git-ashish** [comment]
Thanks for the details and the Github link to the folder, Makoto. From what I remember, this folder dependency was missing in the referenced tutorial and hence the confusion. Thanks for sorting it out.
