### ISSUE TITLE
SAP HANA XS Advanced - Modules within Node.js SAP HANA applications

### ISSUE THREAD

**Issue by git-ashish** [SAPDocuments/Tutorials#2509]
There are missing dependencies in package.json which fails the nodejs service build. These dependencies are being referenced in file utils/initialize.js -  

1. @sap/xssec
2. @sap/hdbext
3. @sap/logging

So, I've used the latest version in the build as 

`
"@sap/xssec": "latest",
"@sap/hdbext": "latest",
"@sap/logging": "latest",
`

**Comment by Lsubatin** [comment]
I cannot figure out which tutorial this is about, it's probably related to prerequisites for that  tutorial.

**Comment by git-ashish** [comment]
@Lsubatin These dependencies can be seen at [Step 6](https://developers.sap.com/india/tutorials/xsa-node-modules.html#9d477cd4-c790-40f5-ad41-cbe765d13855). The prerequisites tutorial doesn't make a reference to these dependencies either.

**Comment by Kyrill996** [comment]
I got the same issue doing the same tutorial and also the previous prerequisited tutorial.
Thank you @git-ashish , your solution helped!
