### ISSUE TITLE
Add a Database to Your Business Application

### ISSUE THREAD

**Issue by BiggiKi** [SAPDocuments/Tutorials#2513]
Step 8: By double-clicking the file, the Annotation Modeler does not open. You have to switch to the tab section below (see screenshot). 
![cecilia annotation](https://user-images.githubusercontent.com/42264799/43946160-c53c6bdc-9c84-11e8-9902-a7c0e7994a26.PNG)

**Comment by qmacro** [comment]
Thanks @BiggiKi - I've addressed this with more explicit instructions.
