### ISSUE TITLE
Adding Grunt Plugins (TypeScript) in SAP Web IDE

### ISSUE THREAD

**Issue by bamajap** [SAPDocuments/Tutorials#2514]
I get the following Web IDE build error when I run through the subject tutorial:

>  Running "cleanTs" task
>  Warning: Path must be a string. Received undefined� Use --force to continue.
>
>  Aborted due to warnings.
> [ERROR] Failed to build module grunt_tutorial_ui.

I have it integrated in with a basic MTA project as an HTML5 module (grunt_tutorial_ui).  I get the same error when I try it as a stand-alone project too.

For the stand-alone attempt, I have tried running the command to clean my npm cache, but that does not correct this issue.  The option to clean the npm cache is not available on the project as an MTA module, so I cannot try it from that project.

Please advise...

**Comment by thecodester** [comment]
@michal-keidar  Can you help here?

**Comment by michal-keidar** [comment]
Not really... It's hard to assist this way, more details are needed. I recommend to open a ticket.
As the reporter is an SAP employee, here are the instructions:
https://wiki.wdf.sap.corp/wiki/display/webapptoolkit/How+to+report+Web+IDE+bugs+or+Usability+Issues

**Comment by bamajap** [comment]
This is not a bug with the IDE, so there is no bug to report.  However, this does appear to be a problem with the tutorial code.  All I'm hoping is that someone with more knowledge on this topic than myself would take this code, import it into SAP Web IDE as a stand-alone project (or MTA module) and build it to see the build error I described above, and (hopefully) deliver a solution for the tutorial.  This just leads to confusion when the tutorial code will not build nor run as described in the tutorial.

I should mention that I was able to get around the error by commenting out the cleanTs task code from the Gruntfile.js and commenting out the cleanTs task from the default grunt task.  When I did that, I got a successful build and was able to at least get the web page to display.

**Comment by jhornik** [comment]
@bamajap We are removing this tutorial as the issues there cannot currently be solved. Sorry for any inconvenience.
If you have any further questions, please be in touch with [Asaf Bruner](asaf.bruner@sap.com)

**Comment by bamajap** [comment]
Understood, no worries.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
