### ISSUE TITLE
Analyze countries and continents

### ISSUE THREAD

**Issue by hearmonster** [SAPDocuments/Tutorials#2515]
The GEOTECH schema is a non-default schema to my knowledge - it certainly does not come pre-deployed on an AWS HANA Express instance!
What are the steps for obtaining the data from, please?

**Comment by Sygyzmundovych** [comment]
Hello. These schemas and data loaded into tables were made specifically for hands-on exercises during SAPPHIRENOW2018.

If you are interested in similar exercises I would suggest checking blogs https://blogs.sap.com/tag/geospatial-tuesday/

Regards.
