### ISSUE TITLE
Image Similarity Scoring example with SAPUI5 ISSUE

### ISSUE THREAD

**Issue by I815766** [SAPDocuments/Tutorials#2516]
Hi,
I'm experimenting an issue testing the App Image Similarity Scoring.

I click on 'Get Image Features'. Then I select two images. But after this, the screen remains in busy state for ever.

When I look into the browser console, I see the following:

![image](https://user-images.githubusercontent.com/42304617/43995901-4fc7119e-9d8e-11e8-8104-032d7a9e621e.png)

This issue start happening today. I was testing the App last week and it worked. I have not touched or updated the project since then.

What could have happened?

Awaiting your comments.

Kind Regards,

Pablo

**Comment by adadouche** [comment]
Hi @I815766 

Apparently the service has been renamed on the SAP API Business Hub. I can see that you are using the API endpoint from the tutorial and not from the SAP API Business Hub?

Can you use the one provided in SAP API Business Hub? I'll update the tutorials.
Thanks

**Comment by adadouche** [comment]
Fixed in [af4c7b8](https://github.com/SAPDocuments/Tutorials/commit/af4c7b87d88b718af0ff812cbb828abaa1cd11fd).
