### ISSUE TITLE
[Question] Where is the best place to ask usability questions related to SAP Web IDE?

### ISSUE THREAD

**Issue by bamajap** [SAPDocuments/Tutorials#2521]
I'm not sure if this is the best place for my Web IDE usability questions or not, so if not here, can anyone direct me to the best place to ask my questions?

Thanks in advance!

**Comment by thecodester** [comment]
The best place would SAP Questions & Answers @ https://answers.sap.com.

**Comment by thecodester** [comment]
@jhornik Are there any other places to ask SAP Web IDE questions?

**Comment by jhornik** [comment]
@michal-keidar Please advise, thanks.

**Comment by michal-keidar** [comment]
SAP Questions & Answers @ https://answers.sap.com. or email us at sapwebide@sap.com

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
