### ISSUE TITLE
Problem running HANA Express Edition Docker image "Cannot initialize persistence"

### ISSUE THREAD

**Issue by geledek** [SAPDocuments/Tutorials#2526]
OS: MacOS High Sierra 10.13.6 (17G65)
Command

`docker run -p 39013:39013 -p 39017:39017 -p 39041-39045:39041-39045 -p 1128-1129:1128-1129 -p 59013-59014:59013-59014 -v /Users/abc/Projects/hana_express:/hana/mounts \
--ulimit nofile=1048576:1048576 \
--sysctl kernel.shmmax=1073741824 \
--sysctl net.ipv4.ip_local_port_range='40000 60999' \
--sysctl kernel.shmmni=524288 \
--sysctl kernel.shmall=8388608 \
--name express_edition \
store/saplabs/hanaexpress:2.00.031.00.20180712.1 \
--passwords-url https://api.myjson.com/bins/abc \
--agree-to-sap-license`

The full log attached

`SAP HANA Lifecycle Management - HdbContainer 2.3.48
***************************************************

Start reading from input channel...
... Done.
Initializing persistence...
Installing initial topology
  hdbnsutil: creating persistence ...
Executing SAP HANA instance failed!
  Cannot initialize persistence
    Cannot create initial topology
      Starting external program /hana/shared/HXE/HDB90/exe/hdbnsutil
        Command line is: /hana/shared/HXE/HDB90/exe/hdbnsutil -initTopology --no_initial_tenant --set_user_system_pw
        Output line 1: Setting password for SYSTEMDB:
        Output line 2: setting password for user SYSTEM:
        Output line 3: reenter password for user SYSTEM:
        Output line 4: password accepted.
        Output line 5: nameserver 7e2f5a37eed1:39001 not responding.
        Output line 6: creating persistence ...
        Output line 7: assign failed with persistence startup error. exception  1: no.2000004  (Basis/IO/FileAccess/impl/FileDescriptors.cpp:334)
        Output line 8:     Cannot open file ""<root>/datavolume_0000.dat" ((closed, mode= RW, access= rw-rw-r--, flags= DIRECT|LOCK), factory= (root= "/hana/mounts/data/mnt00001/hdb00001/" (access= rw-rw-r--, flags= AUTOCREATE_DIRECTORY, usage= DATA, fs= UNKNOWN (fuse.osxfs), config= (async_write_submit_active=on,async_write_submit_blocks=all,async_read_submit=on,num_submit_queues=1,num_completion_queues=1,size_kernel_io_queue=512,max_parallel_io_requests=64,min_submit_batch_size=16,max_submit_batch_size=64))", rc=22: Invalid argument
        Output line 9: exception throw location:
        Output line 10:  1: 0x00007f351820e1b1 in FileAccess::normalizePath(ltt::basic_string<char, ltt::char_traits<char>, ltt::integer_constant<64> > const&, ltt::basic_string<char, ltt::char_traits<char>, ltt::integer_constant<64> >&)+0x81a0 (libhdbbasis.so)
        Output line 11:  2: 0x00007f351820e758 in FileAccess::normalizePath(ltt::basic_string<char, ltt::char_traits<char>, ltt::integer_constant<64> > const&, ltt::basic_string<char, ltt::char_traits<char>, ltt::integer_constant<64> >&)+0x8744 (libhdbbasis.so)
        Output line 12:  3: 0x00007f3518fb5fbf in ltt::operator<<(ltt::exception&, ltt::message_argument<PageAccess::Converter::Type> const&)+0x45b (libhdbdataaccess.so)
        Output line 13:  4: 0x00007f3518fb65dd in ltt::operator<<(ltt::exception&, ltt::message_argument<PageAccess::Converter::Type> const&)+0xa79 (libhdbdataaccess.so)
        Output line 14:  5: 0x00007f3518f92dfe in PageAccess::DataVolumePartition::collectAndCheckPages(unsigned long&, unsigned long&, unsigned long*, unsigned long&, unsigned long*, unsigned long&, unsigned long*, ltt::vector<PageAccess::PhysPageNo>*, unsigned long&, unsigned long*, ltt::vector<PageAccess::PhysPageNo>*) const+0x6dca (libhdbdataaccess.so)
        Output line 15:  6: 0x00007f3518f94c65 in PageAccess::DataVolumePartition::createInstance(ltt::allocator&, Configuration::ConfigurationHandler&, Diagnose::StatisticsData const*, PageAccess::ExtendedDataVolumePartitionInfo const&, bool, bool)+0x161 (libhdbdataaccess.so)
        Output line 16:  7: 0x00007f3518fba036 in PageAccess::DataVolumeSPI::collectAndCheckPages(unsigned long&, unsigned long&, unsigned long*, unsigned long&, unsigned long*, unsigned long&, unsigned long*, ltt::vector<PageAccess::PhysPageNo>*, unsigned long&, unsigned long*, ltt::vector<PageAccess::PhysPageNo>*) const+0xf2 (libhdbdataaccess.so)
        Output line 17:  8: 0x00007f3518fbace1 in PageAccess::DataVolumeSPI::createInstance(ltt::allocator&, Configuration::ConfigurationHandler&, Diagnose::StatisticsData const*, PageAccess::PageIO const&, PageAccess::ExtendedDataVolumeInfo const&)+0x270 (libhdbdataaccess.so)
        Output line 18:  9: 0x00007f3519016807 in PageAccess::PageIO::createInstance(ltt::allocator&, Configuration::ConfigurationHandler&, Diagnose::StatisticsData const*, PageAccess::ExtendedDataVolumeInfo const&)+0x1d3 (libhdbdataaccess.so)
        Output line 19: 10: 0x00007f3518ca7e83 in DataAccess::PersistenceManagerSPI::initNVMProvider()+0x2320 (libhdbdataaccess.so)
        Output line 20: 11: 0x00007f3518cade4e in DataAccess::PersistenceManager::finishDataRecovery()+0x77a (libhdbdataaccess.so)
        Output line 21: 12: 0x00007f3518c6484b in DataAccess::PersistenceManager::create(ltt::refcounted_handle<DataAccess::PersistenceConfiguration> const&)+0x7 (libhdbdataaccess.so)
        Output line 22: 13: 0x00007f3521221fa0 in PersistenceLayer::PersistenceSystem::initialize(NameServer::ServiceStartInfo const&, bool, PersistenceLayer::PERSISTENCE_MODE)+0x630 (libhdbpersistence.so)
        Output line 23: 14: 0x00007f3521269f13 in PersistenceLayer::PersistenceFactory::initPersistence(PersistenceLayer::PERSISTENCE_MODE, DataAccess::TransactionCallback*, NameServer::ServiceStartInfo&, ltt::refcounted_handle<TransactionManager::TransactionControlBlockFactory>&, bool, ltt::smartptr_handle<DataAccess::DisasterRecoverySecondaryCallback>&, bool)+0x5a0 (libhdbpersistence.so)
        Output line 24: 15: 0x00007f35159cd904 in PersistenceController::startup(PersistenceLayer::PERSISTENCE_MODE, NameServer::ServiceStartInfo*, bool, DataAccess::TablePreloadWriteCallback*, DataAccess::TablePreloadReadCallback*, Backup::RecoverCbc_Federation*)+0x2b50 (libhdblogger.so)
        Output line 25: 16: 0x00007f3520a289af in NameServer::Topology::initPersistence(NameServer::ServiceStartInfo&, bool, bool, TREX_ERROR::TRexError*, bool, ltt_adp::basic_string<char, ltt::char_traits<char>, ltt::integral_constant<bool, true> >, NameServer::ServiceStartInfo::RequestAction)+0x23b (libhdbns.so)
        Output line 26: 17: 0x00007f3520a2a2f3 in NameServer::Topology::initPersistence(bool, bool, TREX_ERROR::TRexError*, bool, ltt_adp::basic_string<char, ltt::char_traits<char>, ltt::integral_constant<bool, true> >, NameServer::ServiceStartInfo::RequestAction)+0xb0 (libhdbns.so)
        Output line 27: 18: 0x0000556a636dc0d5 in NameServer::TObjectVector<ltt_adp::basic_string<char, ltt::char_traits<char>, ltt::integral_constant<bool, true> > >::erase(ltt_adp::basic_string<char, ltt::char_traits<char>, ltt::integral_constant<bool, true> >*)+0x8441 (hdbnsutil)
        Output line 28: 19: 0x0000556a636e054e in NameServer::TObjectVector<ltt_adp::basic_string<char, ltt::char_traits<char>, ltt::integral_constant<bool, true> > >::erase(ltt_adp::basic_string<char, ltt::char_traits<char>, ltt::integral_constant<bool, true> >*)+0xc8ba (hdbnsutil)
        Output line 29: 20: 0x0000556a636cc0e2 in <no symbol>+0x0 (hdbnsutil)
        Output line 30: 21: 0x00007f3518352026 in mainInitialPhase+0x712 (libhdbbasis.so)
        Output line 31: 22: 0x00007f35166d36d5 in __libc_start_main+0xf1 (libc.so.6)
        Output line 32: 23: 0x0000556a636ce185 in <no symbol>+0x0 (hdbnsutil)
        Output line 33:
        Output line 34:  stopping service...
        Output line 35: error: Unknown persistence layer error
        Output line 36: failed. trace file nameserver_7e2f5a37eed1.00000.000.trc may contain more error details.
        Program terminated with exit code 2
      /hana/shared/HXE/HDB90/exe/hdbnsutil call failed

Log file written to '/var/tmp/HdbContainer_init_persistence_2018-08-16_08.47.09.log' on host '7e2f5a37eed1'.
Log files copied to '/hana/mounts/trace/7e2f5a37eed1' on host '7e2f5a37eed1'.`

**Comment by songrui01** [comment]
Hi geledek,

From official website, Mac has not been addressed to support.
https://www.sap.com/developer/tutorials/hxe-ua-install-using-docker.html
https://store.docker.com/images/sap-hana-express-edition-incl-application-services/plans/6e81dee1-5032-4e3a-b227-80175d70eeb5?tab=instructions

SAP HANA, express edition for Docker has been tested on the following Linux operating system versions:

Linux OS	OS Version	Docker Editions
Ubuntu	17.04 (Zesty Zapus)	Community, Enterprise
openSUSE	openSUSE Leap	Enterprise
CentOS	7 (Core)	Community, Enterprise
Debian	9 (Stretch)	Community
Fedora	28 (Server Edition)	Community
Suse    12.2/12.3  Community

**Comment by geledek** [comment]
@songrui01 Thanks for the reply.
I guess you are right. The same page also clearly stated that

**> This installation does not support Docker for Windows or Docker for Mac.**

How could I miss that? 

However, I thought it is worth investigating how to make HANA Express Edition works on Windows and MacOS via Docker, for the benefit of individual developers.

In addition, I am curious to know *why* it doesn't work on Windows and MacOS?

**Comment by henriquemattos** [comment]
The funny thing is that if you don't mount the persistence volume it works fine on macOS. Downside is that you stop the container and you loose all the data.

The alternative for me will be to create a script to deploy the sample data after container is up, since my goal is to develop XSA applications independently of data(base).
