### ISSUE TITLE
Install SAP NetWeaver in openSUSE

### ISSUE THREAD

**Issue by carweb99** [SAPDocuments/Tutorials#2528]
The documentation in some of the steps is not clear. 
For example when extracting the rar archive it says 

"All files must be stored in the same folder. As this is a multipart archive, you only need to start the extraction process for the first file sap_netweaver_as_abap_750_sp02_ase_dev_edition.part1.rar – the other files will be extracted automatically."

What does "All files must be stored in the same folder" means? Should the be extracted without subdirectories so all files is stored in one map and not in the structure they archived in !!

On mac there is no winrar that extracts all rar files. If you extract each rar file in same catalog it complains that files exists. 

Also strange is that all rar files seems to have same files in the 
server/tar/x86_64 

The extraction rar files maybe seems to be an easy step but it would be good if this step could be explained more exact

**Comment by thecodester** [comment]
@bjwo Can you address?

**Comment by bjwo** [comment]
@carweb99 Thank you for your question. Unfortunately, I don't use a mac, but I was told that you can use the "[Unarchiver](https://theunarchiver.com/)" tool to extract rar archives on mac.

All downloaded files should be stored in the same folder, then you can start the extraction process for the multipart archive.

Kind regards
Björn

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
