### ISSUE TITLE
Create an ABAP package

### ISSUE THREAD

**Issue by igorkompas** [SAPDocuments/Tutorials#2529]
Hello, 

I get following error when trying to create new ABAP package from eclipse. From SAP it works fine. 
I am using SAP ABAP developer edition (installed on SUSE). 

![image](https://user-images.githubusercontent.com/42439421/44206989-dc01c700-a15b-11e8-829b-32e067961ad4.png)

**Comment by larshp** [comment]
https://blogs.sap.com/2018/09/06/demystifying-eclipse-interaction-with-abap/ might help

**Comment by julieplummer20** [comment]
Hi Igor, A few basics first.
1. What version of Eclipse and Java do you have? Have you updated (Help > Install new... > Site =  https://tools.hana.ondemand.com/photon ).
2. Lars' link shows the exact error you reported, along with a load of possible solutions. Have you tried them - if so, how far did you get? 
3. Have you tried creating a different type of object in package $tmp (local - won't be transported) - eg an ABAP Class or ABAP Program (= report)? Can you provide a screenshot of that?
4. In parallel: If you're a member of SAP Community, have you tried asking the question there? I'm not trying to dump work on others' desks:  A lot of the members there (in the ABAP Dev area) are not involved with GitHub: [SAP Community](https://www.sap.com/community/topic/abap/all-content.html). If you include the tag #ABAP_Trial, I'll get notified and will follow the issue:
![askquestion](https://user-images.githubusercontent.com/22739917/45486890-f760f180-b75c-11e8-8081-880a5e2f4743.png). 

Let me know how you get on.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
