### ISSUE TITLE
Import your TechEd BUILD project into SAP Web IDE

### ISSUE THREAD

**Issue by StErMi** [SAPDocuments/Tutorials#2530]
First problem: import it from the WebIDE. When I try to create the project importing it as a Build template I get this prompt:

![image](https://user-images.githubusercontent.com/146166/44214815-496c2280-a171-11e8-849e-42046c9f3cd1.png)

I type my email/password used for the BUILD's login but it asks me again (I'm correctly logging on it on the private session with no cookie/login active).

So I tried to import the project from the ZIP archive I've downloaded from the BUILD (as suggested by your tutorial).

When I try to run the web application I get this error:

![image](https://user-images.githubusercontent.com/146166/44214861-630d6a00-a171-11e8-8a8e-085a16171e6f.png)

Could you please help me?

**Comment by StErMi** [comment]
Yes when I followed the next steps I understood that they made a mistake https://twitter.com/StErMi/status/1030386660700303360

**Comment by thecodester** [comment]
@StErMi Are you OK now?

**Comment by StErMi** [comment]
@thecodester I'm ok but you have to change the tutorial because if you follow the twitter link you're asking the user to run the oData index when oData is not configured yet ;)

**Comment by mhassett92** [comment]
Hi all,
Thanks for bringing this to my attention! This is a result of a change in the code generation when importing the BUILD project. An older version of the code preset the mock service for you. I have updated the directions and screenshots to reflect the new path to get a running app. Once you run as "testFLPServiceMockService.html", the 404 error should be resolved as well.
Let me know if you have any additional questions!

Thank you,
Meredith
