### ISSUE TITLE
SAP HANA XS Advanced - Cross-container access

### ISSUE THREAD

**Issue by entmike** [SAPDocuments/Tutorials#2531]
Would it be possible to get a similar tutorial but for a use case where we have an HDI container that needs to point to a non-HDI DB?  (For instance, a schema that is managed in an ABAP app or Classic XS or just created in HDBSQL?)

**Comment by Lsubatin** [comment]
Hi, Mike, 
Is this what you are looking for? https://www.sap.com/developer/tutorials/xsa-create-user-provided-anonymous-service.html 
Cheers, 
Lucia

**Comment by entmike** [comment]
Yes, thank you!  It's working.
