### ISSUE TITLE
Secure your application with XSUAA

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2533]
Thank you Abdel for this great up to the point security tutorial.
It would be helpful to add prerequisite to the MovieLens tutorial for those who came up to this link from the search.

**Comment by vsenn** [comment]
I came to your security tutorial from the Google search :-) Anyway, thank you for your great work on this topic and others in ML area! 
We can close this particular one as this is just a feedback/enchantment not an issue.

**Comment by adadouche** [comment]
Thanks for taking the time to share your feedback
