### ISSUE TITLE
Setup your SAP HANA, express edition, instance

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2534]
Hi Lucia!

There is an issue with validation for the ping hxehost host (Step 4).

I can't pass it with the correct response from my macOS machine:
PING hxehost (192.168.0.17): 56 data bytes
64 bytes from 192.168.0.17: icmp_seq=0 ttl=64 time=1.419 ms
64 bytes from 192.168.0.17: icmp_seq=1 ttl=64 time=1.503 ms

I know that Windows machines provide different response and use 32 bytes packets, that could cause the validation issue. Appreciate if you check it. Thanks!

**Comment by nimbusgeek** [comment]
I can't get past the hxe.yaml file. Did you have any issues with that? Maybe I can catch up to you and see if I  can replicate your error.

**Comment by Lsubatin** [comment]
Hi, Not sure what this tutorial this is about. 

The second comment by nimbusgeek refers to the GKE tutorial which sounds like another (out of 16) possible deployments.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
