### ISSUE TITLE
onInit function paste code 

### ISSUE THREAD

**Issue by sharathmg** [SAPDocuments/Tutorials#2537]
Inspite of making the changes to the binding from `				"path": "Parts",
				"parameters": {
					"entitySet": "Sets"
				}`, it says, invalid response. Not sure why?

**Comment by rayatus** [comment]
same issue #2545

**Comment by thecodester** [comment]
Which tutorial is this related to?

**Comment by sharathmg** [comment]
Its for the activity to be completed for the TechEd pass. In the step 9, where the controller for detail view is to manipulated for the live odata service.. the onInit code pasted is not accepted in any form.

**Comment by thecodester** [comment]
Can you refresh page and try again?

**Comment by sharathmg** [comment]
Hi Daniel, 

It works. Thanks.
