### ISSUE TITLE
Change from a mock server to live OData service for TechEd

### ISSUE THREAD

**Issue by sharathmg** [SAPDocuments/Tutorials#2538]
Error while pasting the onInit code. I checked multiple times and tried with full function definition.. still throws an error - Inspite of change to the binding parameters. Am I missing something?

**Comment by Akshaykumar26** [comment]
Same issue. Did you find any resolution yet?

**Comment by rayatus** [comment]
same issue as #2545

**Comment by sharathmg** [comment]
**Waiting**

**Comment by thecodester** [comment]
Can you refresh the tutorial page and try to validate again?
