### ISSUE TITLE
Use HDBSQL as a SQL query tool with SAP HANA, express edition

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2539]
Hi Abdel,
Shouldn't the first 3 options \i-I \input validate to true? They are, as per documentation, but step validation fails. Thank you, Valery

**Comment by adadouche** [comment]
Hi,

As per the [doc](https://help.sap.com/viewer/6b94445c94ae495c83a19646e7c3fd56/2.0.03/en-US/c24d054bbb571014b253ac5d6943b5bd.html) only one option can be use to import SQL statements from a batch file.

Regards

**Comment by adadouche** [comment]
I have adjusted to single choice to avoid confusion
