### ISSUE TITLE
Import an Association Rules Sample Dataset

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2540]
Hi Abdel!
I found that HANA 2.0 SPS03 (at least starting from revision 2.00.031) requires
`;` in the `FIELD DELIMITED BY ';'` to be escaped i.e. `FIELD DELIMITED BY '\;'`.
As I remember this wasn't the case in previous revisions.  But now the IMPORT code in the tutorial fails on this. With the escape symbol `\` it works as designed.
Valery

**Comment by adadouche** [comment]
Thanks for your feedback.

Can you tell me which tool you are using to run the SQL Statement? HDBSQL? Have you tried with another one?

This is a really weird behavior change. I'll need to check with engineering is this is on purpose or a bug.

Thanks

**Comment by vsenn** [comment]
I use SQL Console in the HANA Express WebIDE via Chrome browser. Didn't try with other SQL client though.

**Comment by adadouche** [comment]
Hi @vsenn 

Have you had a chance to get it to work?

Thanks

**Comment by vsenn** [comment]
Hi Abdel! I'm using escape symbol in `FIELD DELIMITED BY '\;' ` having no issues with it. We can close it till somebody report the same.

**Comment by adadouche** [comment]
Thanks. Closing the issue for now.
