### ISSUE TITLE
Change from a mock server to live OData service for TechEd

### ISSUE THREAD

**Issue by nnitjfjd** [SAPDocuments/Tutorials#2543]
Its impossible to validate the onInit fucntion after following the tutorial.
It does not explain from where to where to code extract needs to be copied. 

have tried:
onInit: function () {..code..
function () {..code..
{..code...
...

[1472700396090_S1.controller.txt](https://github.com/SAPDocuments/Tutorials/files/2298135/1472700396090_S1.controller.txt)

**Comment by rayatus** [comment]
same issue as #2545

**Comment by thecodester** [comment]
Can you refresh page and try again?

**Comment by glenndav** [comment]
Same issue. Not resolved.  I'm using:

onInit: function () {
this.oRouter = sap.ui.core.UIComponent.getRouterFor(this);
this.oRouter.getTarget("1472700396090_S1").attachDisplay(jQuery.proxy(this.handleRouteMatched, this));
var oView = this.getView();
oView.addEventDelegate({
onBeforeShow: function () {
if (sap.ui.Device.system.phone) {
var oPage = oView.getContent()[0];
if (oPage.getShowNavButton && !oPage.getShowNavButton()) {
oPage.setShowNavButton(true);
oPage.attachNavButtonPress(function () {
this.oRouter.navTo("1472700396089_S0", {}, true);
}.bind(this));
}
}
}.bind(this)
});

**Comment by rayatus** [comment]
I think you are using a wrong init function so there's not a problem of the validator.

**Comment by glenndav** [comment]
I grabbed the function from 1472700396090_S1.controller.js after var aFinalFilters
I also just compared this init function to the ones posted elsewhere on these threads (#2545) and it matches. Can you double check? Thanks.

**Comment by rayatus** [comment]
In your code, for instance, there's no the following sentence:

self.oBindingParameters['sap_IconTabBar_Page_0-content-sap_chart_ColumnChart-1473793038493'] = {
			"path": "Parts",
			"parameters": {
				"entitySet": "Sets"
			}
		};

**Comment by glenndav** [comment]
Thank you! I didn't realize that the function went down that far... I was just using the formatting and not the actual brackets.
