### ISSUE TITLE
Create an SAP Build prototype

### ISSUE THREAD

**Issue by thisispaco** [SAPDocuments/Tutorials#2546]
This is what i see on Step 11: Change the theme

**DEFAULT THEMES**
SAP Belize
SAP Belize High Contrast Black
SAP Belize High Contrast White
SAP Belize Plus
SAP Blue Crystal (deprecated)
SAP High Contrast Black

**Comment by mhassett92** [comment]
BUILD enables you to utilize all Fiori themes. If you do not have a question, I am going to close this issue.

Thank you!
Meredith
