### ISSUE TITLE
Error with Datahub installation - Error Message "no matching manifest for unknown in the manifest list entries"

### ISSUE THREAD

**Issue by simoncht** [SAPDocuments/Tutorials#2548]
Hi all, 

I am trying to install and setup the developer edition of SAP Datahub and I am stuck at Step 3 in the installation process. Here is the link for your reference where I need to build the Docker image https://www.sap.com/developer/tutorials/datahub-docker-setup.html

When I set into Step 3, below is the error message that I encounter. Has anyone seen this before and know of a workaround? 
![image](https://user-images.githubusercontent.com/26563742/44307409-788aca00-a3e5-11e8-885e-f0885e79f90b.png)

Thank you in advance for your assistance.

**Comment by simoncht** [comment]
hi all, 

i've fixed it and it was noob error as i am not fimillar with Docker. I switched it from Windows to Linux. Screenshot attached. 

![image](https://user-images.githubusercontent.com/26563742/44308428-22278680-a3f9-11e8-9672-99da886a150f.png)

**Comment by schneidertho** [comment]
Hi, 
I have added a short paragraph to the troubleshooting/FAQ page in case other developers face the same problem (https://blogs.sap.com/2017/12/06/faqs-for-sap-data-hub-developer-edition/)
Best regards
Thorsten

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
