### ISSUE TITLE
SAP HANA XS Advanced - Consume the OData service in a basic HTML5 module

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Tutorials#2549]
Hi Lucia,

We finally have a stable HANA Express 2.0 SP3 system that we can develop on.  We spun up an instane on the Google Cloud which was launched in August so it's the most recent.  This is much more stable than the AWS HANA Express 2.0 SP2 system that we had to upgrade to SP3 but still have lots of issues.
However, now when we build the web application, we get the error:
**(MessageBus) Web socket 'wss://hxehost:53075/che/ws/u4phd' is not available: 1006** 

We are not sure how to address this.  The other modules in the tutorial are working fine but this is a strange issue.
![web index html application not starting console error](https://user-images.githubusercontent.com/7725180/44325509-da5f2a00-a40d-11e8-8ef9-1fd59cbe3644.png)
![web index html application not starting](https://user-images.githubusercontent.com/7725180/44325510-da5f2a00-a40d-11e8-823c-3430b4d5751d.png)

Regards,
Jay

**Comment by Lsubatin** [comment]
Hi, Jay, 

I saw your question in the Q&A where this belongs. Maybe someone else in the community can assist with that short level of detail.  

Regards, 

Lucia.

**Comment by jmalla** [comment]
Hi Lucia,
Yes - it's working now after your recommendation for the di-core and di-runner memory increase and also the https://hxehost:53075/watt/index.html?settings=ignore option.
Thanks for your help - we really appreciate it!  We are now able to prepare for our demo without any build environment issues.
Regards,
Jay
