### ISSUE TITLE
Error with Datahub installation - Error starting userland proxy: Bind for 127.0.0.1:8998 failed: port is already allocated

### ISSUE THREAD

**Issue by simoncht** [SAPDocuments/Tutorials#2550]
Hi all, 

When stepped into [Step 4 ](https://www.sap.com/developer/tutorials/datahub-docker-setup.html)of the Datahub Docker setup, I encounter the above error message when i copied and pasted this command
 `docker run -ti --publish 127.0.0.1:8090:8090 --publish 127.0.0.1:8998:8998 --publish 127.0.0.1:9225:9225 --publish 127.0.0.1:50070:50070 --name datahub --hostname datahub --network dev-net datahub run --agree-to-sap-license --hdfs --livy ` 

I have reset Docker to factory default multiple times and still no luck. Any pointers? I have also attached the screenshot for your reference.

![image](https://user-images.githubusercontent.com/26563742/44325028-d88f7800-a49a-11e8-9823-8f08fb20d643.png)

On a different note, I think I have installed it correctly with no error and this screenshot proves it.

![image](https://user-images.githubusercontent.com/26563742/44325725-ea721a80-a49c-11e8-8cf6-55a518b3e298.png)

**Comment by douglasmaltby** [comment]
You might try:
- just removing Livy from your Docker run command by removing the "--publish 127.0.0.1:8998:8998" and "--livy"  to start SDH without Livy. It's not necessary to explore SDH, Vora, HDFS tutorials with the Dev Edition. 

- docker rm datahub and re-running your docker run command

- publishing to a different port like --publish 8998:10000 (or vice versa, can't recall)

- look at this issue (resolved) to change Docker container type from linux to Windows: https://github.com/SAPDocuments/Tutorials/issues/2548

- consult the SDH Dev Ed FAQ here, particularly for Docker-Toolbox, which is similar to how Docker for Windows works by spinning up a VM behind the scenes:  https://blogs.sap.com/2017/12/06/faqs-for-sap-data-hub-developer-edition/

- rebuild your SDH image: docker build --tag datahub:1.4 .

I use Docker for Mac and below is the docker run command successful for me with SDH1.4. I do recall initially having an issue running with livy (may have been on SDH 1.3), and don't think I did anything to resolve it, it just worked next time. That said, I haven't explored using Livy yet (REST interface for interacting with Apache Spark).

docker run -ti --publish 8090:8090 --publish 8998:8998 --publish 9225:9225 --publish 50070:50070 --name datahub --hostname datahub --network dev-net datahub:1.4 run --agree-to-sap-license --hdfs --livy

![sdh14_running_status_loop](https://user-images.githubusercontent.com/19276339/44328058-c0176180-a48a-11e8-817a-b2d514d1a5ab.png)

Hope that helps!
Doug

**Comment by simoncht** [comment]
I'm beginning to love this community and thank you Doug!

Here is what I did:
1. Removed Livy from Docker run command by removing the "--publish 127.0.0.1:8998:8998" and "--livy" to start SDH without Livy. 

2. docker rm datahub and re-running docker run command 

I'm going to ignore Livy for now till we need it and attached is my progress. 

![image](https://user-images.githubusercontent.com/26563742/44330152-a46f8380-a4a9-11e8-8ff8-4401c24cec4c.png)

**Comment by simoncht** [comment]
Closing issue. Thank once again @douglasmaltby

**Comment by douglasmaltby** [comment]
You're welcome @	simoncht! 

I don't "work here", though. I'm just another SAP data geek, on vacation in Vietnam, passing the time doing some self-learning tutorials (SCP, API management, ML/PAL/APL, Fiori, etc.) and encountering other issues in these tutorials. I just happened to see your SDH issue come though and have some experience with it...glad it worked out. Good luck!

**Comment by simoncht** [comment]
@douglasmaltby Thanks once again and enjoy your holiday in Vietnam.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
