### ISSUE TITLE
Configure your SAPUI5 HTML Module

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2552]
Step 12 has some issues w/ validation. Following code didn't validate to TRUE. 
- name: html
  type: html5
  path: html
  requires:
    - name: js_api
      group: destinations
      properties:
        name: movielens_api
        url: '~{url}'
        timeout: 3000000

**Comment by adadouche** [comment]
Hi @vsenn 

Thanks for this feedback, I think this is an indentation/element order issue. I'll check what I can do to avoid that.

**Comment by adadouche** [comment]
Fixed it in commit [cc961ad](https://github.com/SAPDocuments/Tutorials/commit/cc961addf0ccaa754bafe242c167545acf9348a8)
