### ISSUE TITLE
Display from the XS OData service

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2553]
There is an error in Step 4 code for `collaborative.view.xml` & `contentbased.view.xml`.  It is a rudiment prefix `odata_` in XML fragments that raise errors in the App Log like `no such file or directory, stat '***/app/resources/webapp/fragment/xsodata/odata_ratings_detailed.fragment.xml'# and disables opening the recommendations UI.` I see you removed `odata_`prefix in Step 3 for `collaborative.fragment.xml`, `contenbased.fragment.xml` and `ratings_detailed.fragment.xml`. When it fixed, App works as designed.
P.S.
Special thank you for such a huge code snippets! You may post them as floorplans in Fiori already :)

**Comment by adadouche** [comment]
Thanks for catching this one!

Fixed it in commit [789cfac](https://github.com/SAPDocuments/Tutorials/commit/789cfacb974a948d0d89e8b93c61b3a0f0698c91)
