### ISSUE TITLE
Execute the Recommendations algorithm

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2554]
Step 3 miss a Validation/Done button at the end, which make it impossible to make tutorial a complete. Could you please add it? Thanks!

**Comment by adadouche** [comment]
Hi @vsenn 

Thanks for your feedback.

This is fixed in the following commit [1936d3c](https://github.com/SAPDocuments/Tutorials/commit/aa0505882eb97c8083e98f1192929e61b098b516 )
