### ISSUE TITLE
Create an SAP Build prototype

### ISSUE THREAD

**Issue by Hexkbr27** [SAPDocuments/Tutorials#2555]
the drag and drop of control "table" doesn't work, stuck at step 5: Add a table
https://www.sap.com/developer/tutorials/build-create-prototype.html

**Comment by mhassett92** [comment]
If you are still having issues with the drag and drop interface, you can always use the Add feature in the properties pane on the right hand side. Click on the page/section you want to add the table to, go to the Content list in the Children section, find the Table in the dropdown, and click Add.

![screen shot 2018-08-21 at 9 42 57 am](https://user-images.githubusercontent.com/1703983/44416158-091cf380-a527-11e8-811d-235c48d05fc2.png)

Let me know if you are still having issues. 

Thank you!
Meredith
