### ISSUE TITLE
Change from a mock server to live OData service for TechEd

### ISSUE THREAD

**Issue by boda1985** [SAPDocuments/Tutorials#2556]
Hi,

Step 5, Validate data source seems to have an issue. I have quadruple checked that I followed all previous steps exactly and completely reset and tried the steps again multiple times. The validation still wont except my input. Will you please validate that the step requesting the navigation property element is functioning properly. I have complete all of the previous tasks in this mission to be able to be entered into the drawing for tickets for TECHED 2018. 

Please take a look. thank you!

**Comment by ramitmittal** [comment]
I have the same problem.

**Comment by thecodester** [comment]
@boda1985 Can you direct message me in the SAP Community with what you are entering? [If you need, follow me and I will follow you back so you can send message.]

**Comment by boda1985** [comment]
sure, i just followed you.

**Comment by boda1985** [comment]
ok i followed you on SCN now

**Comment by boda1985** [comment]
I still don’t see a way to message you directly on SCN. Is there another way for me to share it with you?

**Comment by thecodester** [comment]
Did you get my message to you? If so, you didn't get a way to answer me? Just trying to figure out how that works.

**Comment by mhassett92** [comment]
Hi @boda1985 ! After chatting with Daniel about the problem you are seeing, it appears that the import of the Odata XML is different from the intended format. It seems to have mixed up some of the properties. Since you are private messaging Daniel, @thecodester can you privately share the correct property order?

Thank you!

**Comment by mhassett92** [comment]
@ramitmittal if you are also having this issue, please private message me via the community the value you are trying to enter. If it is correct but in the wrong order, I will share the correct value.

Thank you!
Meredith Hassett

**Comment by glenndav** [comment]
After trial and error, I determined that the proper order of the values within the string needs to be: 
Parts
Relationship
FromRole
ToRole

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue -- sorry for the confusion

If you still have questions, feel free to reopen the issue.
