### ISSUE TITLE
Deploy HANA Express database on Google Kubernetes cluster

### ISSUE THREAD

**Issue by nimbusgeek** [SAPDocuments/Tutorials#2557]
I got an error when creating the hxe.yaml file stating "error: error converting YAML to JSON: yaml: line 8: found character that cannot start any token" and I know it's not my password because my password starts with a letter which is an allowed utf-8 character. I tried changing the characters in the password but I think it's part of the code in the example (I left the defaults to maintain the privacy of my data).

Here are the first few lines of the example. We are looking at line 8 specifically:

kind: ConfigMap
apiVersion: v1
metadata:
  creationTimestamp: 2018-01-18T19:14:38Z
  name: hxe-pass
data:
  password.json: |+
    {"master_password" : "HXEHana1"}
`---`
kind: PersistentVolume
apiVersion: v1
metadata:
  name: persistent-vol-hxe
  labels:
    type: local

**Comment by Lsubatin** [comment]
Hi, 

This kind of question belongs in the Q&A (answers.sap.com).

However, it is working for me with passwords that do not have a special character that needs escaping. If you really need to have a special character there, I would suggest other methods of setting the password  including creating the file yourself as opposed to having the ConfigMap create it.

In any case, it is recommended that you only use the initial password for the setup and then change the passwords for each of the users, so the password you set there should be temporary.

Regards, 
Lucia.

**Comment by nimbusgeek** [comment]
Thanks for the quick turnaround. I'll play with the password some more.

Regards,
