### ISSUE TITLE
SAP HANA XS Advanced, Creating a Node.js Module

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Tutorials#2558]
Hi Team,

I found another typo as i am going through the tutorials - the name is incorrect (but the screenshot is correct - it has core-xsjs-backend):
name: **core-backend**
url: ~{url}
forwardAuthToken: true

This should be:
name: **core-xsjs-backend**
url: ~{url}
forwardAuthToken: true

Regards,
Jay

**Comment by Lsubatin** [comment]
Hi, Jay, 
Your observation is correct, I'll modified it in the next update. Thank you for pointing it out.
Regards, 
Lucia.
