### ISSUE TITLE
Install SAP NetWeaver in openSUSE - Installation of NPL failed, please check logifiles in /tmp/sapinst_instdir for possible root cause.

### ISSUE THREAD

**Issue by i813380** [SAPDocuments/Tutorials#2562]
Thank you for this [tutorial](https://www.sap.com/developer/tutorials/cp-s4-ext-install-nw.html);  I'm running into a problem on step 4 with the NetWeaver install.  Screenshot and logs attached: [Archive.zip](https://github.com/SAPDocuments/Tutorials/files/2306464/Archive.zip)

![image](https://user-images.githubusercontent.com/15381286/44404973-2dc49b80-a526-11e8-89c8-303d0654ba5f.png)

**Comment by i813380** [comment]
I see this error message: 

TRACE      2018-08-20 16:15:28.063 (root/sapinst)
syb_start_db_server_reset_sa_password: 00:0000:00000:00000:2018/08/20 16:15:28.05 kernel  There is no valid license for ASE server product. Installation date is not found or installation grace period has expired. Server will not boot.

But the link in Step 2 for updating the license is outdated.   Am I supposed to recreate the dbexe.tgz.aa archive?  Or is there a way to rerun the install against the already extracted install scripts?

**Comment by i813380** [comment]
Update - looking at the install.sh script, it checks for a file 'SYBASE_ASE_TD.lic' in the install directory.  If you copy and rename the new license from the link in step 2 (SYBASE_ASE_TestDrive.lic) to the server/TAR/x86_64 directory, it now appears to work.

![image](https://user-images.githubusercontent.com/15381286/44410428-594d8300-a532-11e8-896d-4053eaccbef7.png)

![image](https://user-images.githubusercontent.com/15381286/44410512-8b5ee500-a532-11e8-85df-c967da44da34.png)

**Comment by i813380** [comment]
Sadness - now I fail on next step, Step 5.  

![image](https://user-images.githubusercontent.com/15381286/44411674-180aa280-a535-11e8-8271-24a5bca2a93b.png)

[startsap.trc.zip](https://github.com/SAPDocuments/Tutorials/files/2306970/startsap.trc.zip)

**Comment by i813380** [comment]
Restored snapshot and ran with license file, all now looks good. 

```
Checking syb Database
Database is running
-------------------------------------------
Starting Startup Agent sapstartsrv
OK
Instance Service on host vhcalnplci started
-------------------------------------------
starting SAP Instance ASCS01
Startup-Log is written to /home/npladm/startsap_ASCS01.log
-------------------------------------------
/usr/sap/NPL/ASCS01/exe/sapcontrol -prot NI_HTTP -nr 01 -function Start
Instance on host vhcalnplci started
Starting Startup Agent sapstartsrv
OK
Instance Service on host vhcalnplci started
-------------------------------------------
starting SAP Instance D00
Startup-Log is written to /home/npladm/startsap_D00.log
-------------------------------------------
/usr/sap/NPL/D00/exe/sapcontrol -prot NI_HTTP -nr 00 -function Start
Instance on host vhcalnplci started
Installation of NPL successful
 
vhcalnplci:/media/sf_NW_Extract/sap_netweaver_as_abap_750_sp02_ase_dev_edition_part1 # su -l npladm
vhcalnplci:npladm 2> startsap ALL
Checking syb Database
Database is running
-------------------------------------------
Starting Startup Agent sapstartsrv
OK
Instance Service on host vhcalnplci started
-------------------------------------------
starting SAP Instance ASCS01
Startup-Log is written to /home/npladm/startsap_ASCS01.log
-------------------------------------------
/usr/sap/NPL/ASCS01/exe/sapcontrol -prot NI_HTTP -nr 01 -function Start
Instance on host vhcalnplci started
Starting Startup Agent sapstartsrv
OK
Instance Service on host vhcalnplci started
-------------------------------------------
starting SAP Instance D00
Startup-Log is written to /home/npladm/startsap_D00.log
-------------------------------------------
/usr/sap/NPL/D00/exe/sapcontrol -prot NI_HTTP -nr 00 -function Start
Instance on host vhcalnplci started

vhcalnplci:npladm 4> sapcontrol -nr 00 -function GetProcessList

21.08.2018 12:48:48
GetProcessList
OK
name, description, dispstatus, textstatus, starttime, elapsedtime, pid
igswd_mt, IGS Watchdog, GREEN, Running, 2018 08 21 12:46:42, 0:02:06, 14678
disp+work, Dispatcher, GREEN, Running, 2018 08 21 12:46:42, 0:02:06, 14677
gwrd, Gateway, GREEN, Running, 2018 08 21 12:46:48, 0:02:00, 14704
icman, ICM, GREEN, Running, 2018 08 21 12:46:48, 0:02:00, 14705
vhcalnplci:npladm 5> 
```

**Comment by thecodester** [comment]
@bjwo Are you aware of this issue?

Thank you for your feedback. We haven't heard from you in the past 30 days, and it looks like the issue is resolved, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
