### ISSUE TITLE
SAPUI5 - Open the SAP Web IDE in SAP Cloud Platform

### ISSUE THREAD

**Issue by michal-keidar** [SAPDocuments/Tutorials#2565]
Hi,
As the "old" SAP Web IDE will be deprecated by end of 2018, this tutorial should be removed or adapted to Web IDE Full-Stack (though I think there's already a tutorial enabling Web IDE Full-Stack).
Thanks,
Michal.

**Comment by jonathanbaker7** [comment]
Agreed.  This is in the process of being rewritten, and will be removed once the new tutorials are finished.

**Comment by rbrainey** [comment]
I'm unclear on the exact turorial referenced: https://developers.sap.com/tutorials/sapui5-webide-create-project.html is current and https://developers.sap.com/tutorials/sapui5-webide-part1-create-project.html has been removed -- is it safe to close this, or are we talking about another tutorial that is still visible?

**Comment by thecodester** [comment]
@michal-keidar I will close this issue. If there still is a problem, feel free to reopen and add an explanation. Thanks.
