### ISSUE TITLE
Change from a mock server to live OData service for TechEd - Validate data source

### ISSUE THREAD

**Issue by thisispaco** [SAPDocuments/Tutorials#2568]
I'm having a problem with the validation of the data source. 

I've validated this before you solved the issue with the validation of the initialization function but now its not working :

<NavigationProperty Name="PartOf" Relationship="715e5fc8a397998f103ac4ec.ToysPartOfParts" FromRole="FromRole_ToysPartOfParts" ToRole="ToRole_ToysPartOfParts"/>

**Comment by thecodester** [comment]
Can you explain what is happening? Once you validate, it should not let you validate again and you maintain your "Done". I validated last week, before any changes, and my validation still appears.

**Comment by thisispaco** [comment]
Now it works, thank you!

**Comment by thecodester** [comment]
Good to hear :-)
