### ISSUE TITLE
Sign up for a free trial account on SAP Cloud Platform

### ISSUE THREAD

**Issue by htammen** [SAPDocuments/Tutorials#2570]
HI,
I would like to participate in the SAP Teched 2018 mission contest but cannot validate my for a long time existing SCP cockpit URL which is: https://account.hanatrial.ondemand.com/cockpit/#/acc/p001984trial/accountdashboard
I get the error "Invalid response. Please try again"

Will my participation make the way into the lottery box despite of this error?

Regards Helmut

**Comment by thecodester** [comment]
The only thing that is weird to me is the p users I think are usually 10 digits long, and in the URL it is only 6

**Comment by thecodester** [comment]
I didn't notice the extra slash ... I would suspect that is the issue.

**Comment by qmacro** [comment]
I don't think it is - as noted above, my URL doesn't pass the validation either.
