### ISSUE TITLE
Set up SAP HANA database on SAP Cloud Platform

### ISSUE THREAD

**Issue by htammen** [SAPDocuments/Tutorials#2572]
Hi,
I followed this tutorial by Bjoern Woppmann and got stuck at step 4. At bullet point 5. the tutorial asks me to add a new Cloud System but this menu option is not available for me.
The difference between my environment and the tutorial is that i used Eclipse Oxygen with the plugins from https://tools.hana.ondemand.com/oxygen and the tutorial uses Eclipse Neon.
How can I add a Cloud System in Eclipse Oxygen?

Regards Helmut

**Comment by adadouche** [comment]
Hi

Unfortunately this feature was removed with plugin in Oxygen.

Only the Neon plugin have this feature.

I personally have multiple Eclipse installations to overcome this differences.

**Comment by htammen** [comment]
Ah, thanks @adadouche. I think I will carry on in the cloud.
