### ISSUE TITLE
Code with SAPUI5

### ISSUE THREAD

**Issue by migsmagdangal** [SAPDocuments/Tutorials#2575]
On Step 6: Remove the column, the instruction directs us to look for the <m:columns> control. However, in our IDE, there's no such tagging. They're all **without** _m:_ .

**Comment by mhassett92** [comment]
the `m:` is how UI5 includes namespaces, when m is generally sap.m. Sometimes it is not the default namespace, and sometimes it is. Since the m:'s are not present, that means it is the default namespace for the application. m:column and column are most likely the same control.
