### ISSUE TITLE
Import your TechEd BUILD project into SAP Web IDE

### ISSUE THREAD

**Issue by raz-korn** [SAPDocuments/Tutorials#2577]
SAP Web IDE full-stack version is the recommended SAP Web IDE version. SAP Web IDE tutorials should be updated to reflect this.

**Comment by mhassett92** [comment]
Hi Raz,

We are working on converting them with the help of Michal. I will defer to @thecodester on whether or not we plan on maintaining old event content, or if tutorials like this should be deprecated.

Thanks!
Meredith

**Comment by thecodester** [comment]
We have removed this tutorial.

**Comment by thecodester** [comment]
@raz-korn Are you referring to this group of tutorials? Is this issue still relevant?
