### ISSUE TITLE
Build an SAP Fiori UX app with SAP Gateway data

### ISSUE THREAD

**Issue by SindhuSaravanan** [SAPDocuments/Tutorials#2579]
Hi,

I tried to perform this tutorial but received an authentication failure (for Netweaver application server ES5/002) in step 6 of the exercise. When I entered by P-user ID and password, the system did not accept it.

Please help to resolve this issue.

Regards,

SIndhu

**Comment by thecodester** [comment]
Can you rpovie link to the tutorial you are referring to?

**Comment by mhassett92** [comment]
Make sure you are using the credentials you created when you signed up for the SAP Gateway service. These may be different then the ones you have your SAP Cloud Platform account.
