### ISSUE TITLE
SAP HANA XS Advanced - Modules within Node.js SAP HANA applications - XSA Messaging Service

### ISSUE THREAD

**Issue by git-ashish** [SAPDocuments/Tutorials#2584]
Hello,

Could you please provide a tutorial about how to set up and use the XSA Messaging service?
A guide/tutorial like you have provided for many other examples would be very helpful.

Thanks!

**Comment by Lsubatin** [comment]
Hi, 
Thanks for the suggestion. That is an interesting scenario. 

I do have a huge wishlist to fulfill so cannot commit on a time right now, but let's see what we can do.

Best, 

Lucia.

**Comment by git-ashish** [comment]
Thanks for the response @Lsubatin and will look forward to any solution to this scenario.

But as we are developing something which needs to use the Messaging Service and the service being a part of the offering in XSA, could you please point to some helpful documents which show its usage?

There are docs in the sap portal which list details about the service itself but nothing about how it can be implemented in a nodejs environment. 

We have made several attempts to create and bing the service from mta.yaml. Although the service gets created, the build fails with an error saying 'service not found' for the module which **requires** it. This service can then be manually bound with apps from the Cockpit. 
A crucial missing piece is the **type** of resource for 'messaging-service'. Currently, we mention the type as **org.cloudfoundry.managed-service** but when mentioning it as a **requires** resource for a nodejs module, this results in a build error. Any help in this regard would be very much appreciated.

Here is how we are defining the resource:

```
  - name: msg-service-one
    type: org.cloudfoundry.managed-service
    parameters:
      service: messaging-service
      service-plan: free
```
Thanks!

**Comment by Lsubatin** [comment]
Hi, Ashish, I haven't tried this from an MTA from webide, have you tried type org.cloudfoundry.existing-service ?

**Comment by git-ashish** [comment]
Thanks for the reply, Lucia. Yes, we have tried org.cloudfoundry.existing-service but it gives the same error.
`service msg-service-one not found`
