### ISSUE TITLE
SAP HANA XS Advanced, import tables and large datasets

### ISSUE THREAD

**Issue by seansilvestri** [SAPDocuments/Tutorials#2589]
The images are not visible (links are broken)

**Comment by thecodester** [comment]
There is a problem with the Web server -- we are working on a fix. Sorry for the missing images.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
