### ISSUE TITLE
Create your own Fiori Launchpad

### ISSUE THREAD

**Issue by cknitterscheidt** [SAPDocuments/Tutorials#2591]
Hi!

I followed the tutorial and it worked so far despite most of the screenshots not loading on your website. I have the fiori Launchpad, but while I see the drop down for the SAPUI5 version will the system not let me choose anything else than Innovation. When I click custom does it simply flip back to Innovation...

**Comment by mhassett92** [comment]
Hi there! It looks like you no longer need to update the version of SAPUI5 on the Fiori Launchpad, so please ignore that step and continue. Sorry for the delay!

Thank you,
Meredith
