### ISSUE TITLE
when trying to follow this pre-teched-2018-webide-git

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#2594]
i keep getting logon errors in the "Fetch from Upstream" step. 

Logging out, clearing the cache, and trying with different usernames like S-id, github id, etc. doesn't work.

**Comment by mhassett92** [comment]
Can you share some more details? What is the exact error you are seeing? Are you logging in with your SAP Cloud Platform credentials? Did the repo you input already have code in it?

**Comment by greg2git** [comment]
it doesn't look like it's going to be resolved any time soon, so i will just close it.
