### ISSUE TITLE
New HTML5 modules - Failed to open in browser - HANA XSA unresponsive

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Tutorials#2598]
Hi Team,

We are able to create and build our XSA applications on Google Cloud HANA 2.0 SP3.  Most things are running smoothly.  However, now we notice that if we create a new HTML5 module and then build and run this, the application says it's running but when bringing this up in the browser, we see that the application is not hit at all - so we cannot to a tail on the log for this HTML5 web app.  So it looks like the system is not running smoothly again and we are trying to figure out how to get to the bottom of this.

We think it's an issue with the di-core or di-runner crashing.  However, we restarted the system and also restarted both the di-core and di-runner.  We are not sure where else to look.

Even just following this tutorial again - I created jayTest MTA app and the web module for HTML5.  Build works fine.  But when I run:

Application is running - with the link as:
https://hxehost:51058/index.html

However, when the link is brought up in the browser, the application does not respond and it times out.
We did a tail for logging for the app:
hxeadm@hxehost:/usr/sap/HXE/HDB90> xs logs JAY-xvq92zc3fw8hg7h2-jayTest-web

We also did a tail for the di-core:
hxeadm@hxehost:/usr/sap/HXE/HDB90> xs logs di-core

and also di-runner:
hxeadm@hxehost:/usr/sap/HXE/HDB90> xs logs di-runner

So it seems after the system is running for a while, it just stops running nicely and we are unable to figure out how to resolve this.  We even did a HDB stop and HDB start.  So we are not sure how to resolve this issue.  It seems that there is a memory leak with one of the HANA services that causes it to crash or not respond but we do not know where to look.  

![html5 module not loading in browser](https://user-images.githubusercontent.com/7725180/44876150-0de35500-ac55-11e8-8b01-fb25779d17fa.png)
![tailing logs di_core di_runner html5](https://user-images.githubusercontent.com/7725180/44876162-120f7280-ac55-11e8-92a2-83c7c441f4ae.png)

![xs apps in sap space](https://user-images.githubusercontent.com/7725180/44876395-d9bc6400-ac55-11e8-80b4-ad01cb61fdc7.png)

Thanks,
Jay

**Comment by Lsubatin** [comment]
Hey, Jay, just a note that will hopefully save time... 

There is no need to restart the entire system and I would treat that as the ultimate solution. You can look at logs from the CLI using xs logs <<app>>. You can restart any app using xs restart and the entire XSA can be restarted with command XSA restart from the server. 

I'm curious about which port was not open by default as that should be fixed. What is the web module getting assigned?

Thanks, 
Lucia.
