### ISSUE TITLE
Send Data with MQTT

### ISSUE THREAD

**Issue by MarcusSchiffer** [SAPDocuments/Tutorials#2599]
How can we make the example work in a corporate environment with proxy and proxy auth ?
Examples that work only from private computers in a home network are useless.

**Comment by thecodester** [comment]
@iwonahahn Can you help here?

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
