### ISSUE TITLE
Code with SAPUI5

### ISSUE THREAD

**Issue by p1941925975trial** [SAPDocuments/Tutorials#2600]
When I try to run my application as web application, the FLP opens with the first tile being the "Inventory Dashboard". When I click on it, I get an error "Request failed":

Request failed
\{
	"requestUri": "/here/goes/your/serviceUrl/local/$metadata?sap-language=DE",
	"statusCode": 404,
	"statusText": "Not Found",
	"headers": [],
	"body": "HTTP Status 404 - Not Found"
}

**Comment by mhassett92** [comment]
Please note that you need to run the application with the testFLPServiceMockServer.html file as the set-up has changed. If you run the testFLPService.html, you will see this issue.
