### ISSUE TITLE
Enable SAP Cloud Platform Internet of Things for Cloud Foundry

### ISSUE THREAD

**Issue by jeGit** [SAPDocuments/Tutorials#2602]
HELP. 
This tutorial is no longer working with the current SAP trial services. I'm unable to provision an IoT trial as described in this tutorial.
Could someone please let me know, how to get an IoT trial?

Tia,
Jens

**Comment by iwonahahn** [comment]
Hi Jens,

Thank you for your feedback. Public Trial is currently not available for the IoT service on Cloud Foundry. Therefore we mention in our tutorial, that you have to purchase a license for the SAP Cloud Platform Internet of Things Service. It is planned to offer trial access to the SAP Cloud Platform Internet of Things for the Cloud Foundry environment. Please stay tuned until this is available.

Thank you and best regards,
Iwona

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
