### ISSUE TITLE
Change from a mock server to live OData service for TechEd

### ISSUE THREAD

**Issue by AbhijitNilegaonkar** [SAPDocuments/Tutorials#2607]
Step 6

>>>Comment out server.init() on line 14 by adding 2 forward slashes (//) to the beginning of the line.

Unfortunately there is nothing like server.init() on line 14 when I check my code. What am I missing? I would appreciate any help. I am trying to find out if I am the only one with this problem or there are others seeing this as well. Any pointers would be helpful.

**Comment by AbhijitNilegaonkar** [comment]
@mhassett92

**Comment by AbhijitNilegaonkar** [comment]
@mhassett92 thanks but not sure if i understand. This issue I am facing is from the topic of 2018 pre teched challenge. Let me know if I am missing anything. Your help is appreciated.

This could be found under Bullet 9 of the Challenge 
9. Change from a Mock Server to Live OData Service for TechEd
   Then Open the Step 6
     >>6. Change the component file. You will find the line 
               >>Comment out server.init() on line 14 by adding 2 forward slashes (//) to the beginning of the line.

**Comment by AbhijitNilegaonkar** [comment]
![image](https://user-images.githubusercontent.com/19243918/45136478-eff08580-b169-11e8-969b-cd519120efc1.png)

**Comment by AbhijitNilegaonkar** [comment]
[component_dot_js.pdf](https://github.com/SAPDocuments/Tutorials/files/2355544/component_dot_js.pdf)

**Comment by mhassett92** [comment]
Whoops, looks like an old instruction crept into this tutorial. Please ignore that instruction. There may have been a merge error and it ended up back in the tutorial. I am removing that line.

**Comment by AbhijitNilegaonkar** [comment]
Thanks for the clarification. This can be closed.
