### ISSUE TITLE
Change from a mock server to live OData service for TechEd

### ISSUE THREAD

**Issue by AbhijitNilegaonkar** [SAPDocuments/Tutorials#2608]
Step 8 

Notsure why I am getting an error in the controller 1472700396090_S1.controller.js

![image](https://user-images.githubusercontent.com/19243918/45004599-b37b2900-afb3-11e8-952f-02febc8b875a.png)

I do not remember making any changes which would cause this. What am I missing?
I would appreciate any help. Thank you.

**Comment by mhassett92** [comment]
SAP Web IDE also shows Best Practices "errors" as a red X.There is nothing to resolve; just something to keep in mind when developing productive apps.
