### ISSUE TITLE
Create an SAP Build prototype

### ISSUE THREAD

**Issue by poonamassudani** [SAPDocuments/Tutorials#2609]
I am facing issue in the last step 'Share Your app'
I have created the prototype and copied the link . But is is showing error when trying to validate.

Below is the link I created for my prototype

https://standard.build.me/prototype-editors/api/public/v2/prototypes/5b8e217895059701035a1493/snapshots/latest/artifacts/index.html#/1472700396089_S0

**Comment by mhassett92** [comment]
The shared prototype appears to be working from my end, so please try to validate again. It may have been a glitch with the system. Let me know if it is still not validating!
