### ISSUE TITLE
Build and Deploy Streaming Lite Project

### ISSUE THREAD

**Issue by mbenetti** [SAPDocuments/Tutorials#2610]
Hi 
I am having a problem to deploy the streaming project

pi@raspberry:~ $ $HOME/install/bin/streamingproject --ccx $HOME/freezer_monitoring_lite.ccx --command-port 9230
/lib/ld-linux-armhf.so.3: No such file or directory

That is my error. What could be?

**Comment by thecodester** [comment]
@gpinar Can you help here?

**Comment by mbenetti** [comment]
Thanks! that helped yes. Anyway, I just realize that all over the tutorial there are random spaces in the command lines, you don't realize till the end of the exercise. 
So far I took the "Get to start with data streaming" cloud and with express edition but the problem starts in the freezer_lite tutorials.

Thank you for the help!

**Comment by RobWaywellSAP** [comment]
I'm not seeing extra spaces when I look at the tutorial on the Developer page at https://www.sap.com/developer/tutorials/hsa-streaming-lite-freezer-monitoring-part3.html

That may or may not matter. 

The error you are getting is a file not found error, so the first thing we need to do is verify if the files referenced in that command line are in those locations:

1) Does the $HOME environment variable point to "/home/pi"?
2) Is Streaming Lite installed in the "/home/pi/install"  directory?
3) Is the streamingproject executable in the "/home/pi/install/bin" directory?
4) Is the freezer_monitoring_lite.ccx file in the "/home/pi" directory?

**Comment by mbenetti** [comment]
Hello Rob

Thank you for your email. Sorry for the late respond, I was on holidays.

In the previous step https://www.sap.com/developer/tutorials/hsa-streaming-lite-freezer-monitoring-part2.html

When you configure the streaming $HOME, in the code there is  one space after the symbol “=” , this  later produce and error on step 2 of the 3rd part,  when you run the project.


[cid:image001.jpg@01D44E72.BF154EF0]

The error in setting  the environment  is not evident till you are at the end of the 3rd  step. Never the less is a good tutorial and I finished already. Great job! I know how much time and energy takes to build the tutorials,

I want to focus now  in send data to a HANA EXPRESS running in the company from the inside and the outside of the building . Can you recommend to me a tutorial to follow? I am having problems to set up the Web Streaming Services, the HE crashed and I stop trying.  There is another way to send data from the outside to a HANA Express DB than SWS?

De: RobWaywellSAP [mailto:notifications@github.com]
Enviado el: jueves, 13 de septiembre de 2018 09:57 p. m.
Para: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
CC: mbenetti <mbenetti@hotmail.es>; Author <author@noreply.github.com>
Asunto: Re: [SAPDocuments/Tutorials] Build and Deploy Streaming Lite Project (#2610)


I'm not seeing extra spaces when I look at the tutorial on the Developer page at https://www.sap.com/developer/tutorials/hsa-streaming-lite-freezer-monitoring-part3.html<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.sap.com%2Fdeveloper%2Ftutorials%2Fhsa-streaming-lite-freezer-monitoring-part3.html&data=02%7C01%7C%7C3fec8d45bd9a40d7c4fe08d619b3143e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636724654253749773&sdata=Txw6eZ70G9NMlLoDXQRCTbVzAR0J2tOvi%2F5F1Gj4wzk%3D&reserved=0>

That may or may not matter.

The error you are getting is a file not found error, so the first thing we need to do is verify if the files referenced in that command line are in those locations:

  1.  Does the $HOME environment variable point to "/home/pi"?
  2.  Is Streaming Lite installed in the "/home/pi/install" directory?
  3.  Is the streamingproject executable in the "/home/pi/install/bin" directory?
  4.  Is the freezer_monitoring_lite.ccx file in the "/home/pi" directory?

**Comment by RobWaywellSAP** [comment]
We should probably start a separate thread to talk about the adapters and/or the issue you had configuring the WSP/SWS. 

As a starting point for the adapters, you can take a look at the [SAP HANA Streaming Analytics: Adapters Guide](https://help.sap.com/viewer/52acc1f6b1d7428caab280d193c820f6/2.0.03/en-US)

**Comment by thecodester** [comment]
Can we close this issue?

**Comment by mbenetti** [comment]
Yes of course, thank you for your support.

Best regards

MB
