### ISSUE TITLE
Create Your First ABAP Console Application

### ISSUE THREAD

**Issue by sharmavivek73** [SAPDocuments/Tutorials#2611]
Hi Merve,

I cannot find option ABAP Cloud Project option in Eclipse IDE. It looks like that I am missing some software installation in Eclipse for SAP Cloud Platform.

**Comment by larshp** [comment]
Hi,
See comment on https://blogs.sap.com/2018/09/05/sap-cloud-platform-abap-environment-is-live/ from Karl Kessler, 

"the plugins will be released on September 13th on the tools home page.

The plugins are already available on Service Marketplace."

**Comment by mervey45** [comment]
Hi sharmavivek73, 

you need the latest version of Eclipse Oxygen (4.7) and also the latest link for ADT, which will be available on 13th September on the tools home page. As larshp already mentioned, the plugins are already available on Service Marketplace.

Thank you.

Best regards, 
Merve

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
