### ISSUE TITLE
Google App Engine Setup

### ISSUE THREAD

**Issue by sumit-kundu** [SAPDocuments/Tutorials#2613]
Step2 : 'Development' menu option is not appearing. Not sure if GCP has changed its menu, but I managed to create a source code repository just by searching 'repository'. 
Do you think this step can be updated?

Regards,
Sumit

**Comment by thecodester** [comment]
@Lsubatin Do you know who could help us with this tutorial?

**Comment by Lsubatin** [comment]
It would be useful to know what the URL of the tutorial is. We have a couple of different GCP/AppEngine tutotrials. Thanks!

**Comment by sumit-kundu** [comment]
Here is the tutorial I am following.
https://www.sap.com/developer/tutorials/gae-setup.html

**Comment by sumit-kundu** [comment]
Hello Lucia,

Sorry about the late reply.
Here is the tutorial link I was following.
https://developers.sap.com/tutorials/gae-setup.html

BTW, I do not find the github link where I used to browse the issues
reported. A lot has changed in SAP tutorial navigators.

Regards,
Sumit

**Comment by thecodester** [comment]
We are working on restoring the feedback link. Sorry about that.

**Comment by Lsubatin** [comment]
Flagging this tutorial for deletion.
