### ISSUE TITLE
Error while importing a BUILD project prototype into SAP Web IDE

### ISSUE THREAD

**Issue by VivekRajKM** [SAPDocuments/Tutorials#2615]
Error message with 'Request failed: Unauthorized URI'. 
![build import](https://user-images.githubusercontent.com/17874349/45123362-80c16400-b15e-11e8-803b-7bbbeb1cafd8.JPG)

**Comment by mhassett92** [comment]
Make sure you are logging in with your EMAIL Address and BUILD password (this may be different than your SAP Cloud Platform password). If you continue to see issues, you can use the alternative directions to download the ZIP from Build.

**Comment by mhassett92** [comment]
Did you enable both the Build Service in SAP Cloud Platform and the Build Feature in SAP Web IDE?

**Comment by VivekRajKM** [comment]
Yes I did have them enabled.

**Comment by VivekRajKM** [comment]
Tried clearing cache, alternate browsers, yet unable to import the project.

**Comment by VivekRajKM** [comment]
Could you validate if the destination setting for SAP UI5 is any different ?
![sapui5 destination](https://user-images.githubusercontent.com/17874349/45216661-49a39d80-b299-11e8-8b97-7c999155a853.JPG)

**Comment by VivekRajKM** [comment]
@mhassett92 Any hints or comments please ?

**Comment by mhassett92** [comment]
Vivek,
There seems to be an issue with your trial account as this is the not the first time you have issues with a template. I think the best option would be to create a new account with a new email address if that is possible. While this is not ideal, this is the quickest way to resolve the issue. I am trying to see why your account rejects the templates, but its not clear to us on our side so not sure when it will be resolved.

Thank you and apologies,
Meredith

**Comment by VivekRajKM** [comment]
@mhassett92 Thanks Meredith. I did try creating a trial account via different email address, but I face error over import. I am giving up on this. Thanks Meredith. 

![error](https://user-images.githubusercontent.com/17874349/45481029-654bef80-b742-11e8-8b61-83c7a80ce77a.JPG)

**Comment by VivekRajKM** [comment]
Hello @mhassett92  Meredith, this issue has been resolved. Thanks for the support.
