### ISSUE TITLE
User Experience - Portal does not appear in Services

### ISSUE THREAD

**Issue by dezijan** [SAPDocuments/Tutorials#2616]
I feel like I'm missing something obvious, but I am not seeing it. 

I've followed the "Sign up for a free trial account om SAP Cloud Platform". No issues there. I've done those same steps now, creating two different ids. When I get to the "Create your own Fiori Launchpad", I perform Step 1: Go to Services. When I search or filter for Fiori, I do not see the Portal (enabled) under User Experience. I do not see Portal at all. 

What obvious thing am I missing here? 
![9-5-2018 3-22-48 pm](https://user-images.githubusercontent.com/28067370/45124580-b2670a80-b11f-11e8-8265-0a951a470a9a.jpg)

**Comment by mhassett92** [comment]
There must have been an update to the descriptor text to remove Fiori. If you search for Portal, you will see the service. Please update your search.

**Comment by mhassett92** [comment]
You will need to enable the service to use it. Once you click on the tile, you will see a button to enable.

As I am an SAP employee, I may have access to beta services as well (I haven't looked into it), so there might be a difference in our accesses. Nothing to worry about!

**Comment by dezijan** [comment]
That seems to have done the trick. Thanks very much!

I was able to complete and register for the drawing, yet the dashboard doesn't show I completed step #2, even though the detail for #2 shoes that I did. Hope that doesn't exclude me from the drawing. 

![9-6-2018 3-11-23 pm](https://user-images.githubusercontent.com/28067370/45187935-4cde5100-b1e7-11e8-85e4-4de861b26ff0.jpg)
![9-6-2018 3-12-14 pm](https://user-images.githubusercontent.com/28067370/45187939-51a30500-b1e7-11e8-8932-ba5563e9fb1d.jpg)

Thanks again for your assistance.

**Comment by mhassett92** [comment]
This is probably due to a change I made to the tutorial. I will put in a new step, which should force the validation through and you will see a green check. Please let me know when you complete step 7 (will push through shortly) if the bubble 2 turns green.

**Comment by mhassett92** [comment]
We are aware of this issue and working to resolve it ASAP!

**Comment by mhassett92** [comment]
This issue is now resolved!

**Comment by dezijan** [comment]
Success! Thanks again for your help. Anything else I need to do to qualify for the drawing? 
![9-7-2018 11-08-30 am](https://user-images.githubusercontent.com/28067370/45235662-743c2900-b28e-11e8-8068-7fc5aa05c59d.jpg)

**Comment by mhassett92** [comment]
Did you fill out the form at the end of step 10? That's the only other thing you need to be eligible.
