### ISSUE TITLE
Create Your First ABAP Console Application

### ISSUE THREAD

**Issue by Sushma1000** [SAPDocuments/Tutorials#2617]
Hi,
I started eclipse after some time and followed the steps mentioned below:
I couldn't find ABAP Cloud Project. Is there a prerequisite before we get here?
Screenshot attached for reference.
![abap console application](https://user-images.githubusercontent.com/35324279/45131536-fa7f3f00-b1aa-11e8-9a35-2f8b4344dd28.jpg)

Step 1: Open ABAP cloud project
Open Eclipse, select File > New > Other > ABAP Cloud Project, then click Next.

**Comment by thecodester** [comment]
@mervey45 Can you help here?

**Comment by larshp** [comment]
Get the plugin from https://launchpad.support.sap.com/#/softwarecenter/template/products/%20_APP=00200682500000001943&_EVENT=DISPHIER&HEADER=Y&FUNCTIONBAR=N&EVENT=TREE&NE=NAVIGATE&ENR=73555000100200009431&V=MAINT&TA=ACTUAL&PAGE=SEARCH/SAP%20ABAP%20IN%20ECLIPSE%202.96

also see #2611, the update site is not updated yet

**Comment by Sushma1000** [comment]
Thanks!
Regards,
