### ISSUE TITLE
PreTeched 2018: Deploy your app to Fiori Launchpad

### ISSUE THREAD

**Issue by AbhijitNilegaonkar** [SAPDocuments/Tutorials#2618]
I am getting an Error on Stage 10 Step 7. Any help is appreciated. Thank you.

Stage 10.  Deploy your App to Fiori Launchpad
Step 7 View your Launchpad App

I get an Error it says. The App could not be launched please try again later. Not sure if this related to previous errors I have posted in separate threads. 

Some Observations:
1.  I guess the Stage 9 is not done correctly due to the other issues posted separately  
2.  When I run the App locally I get no data.

**Comment by mhassett92** [comment]
Can you please share the exact error you are seeing to help troubleshoot further?

**Comment by AbhijitNilegaonkar** [comment]
Meredith, Now the error is gone. I can launch the app but it says no data. I am going to try couple of things you suggested and see if it helps.
![no data](https://user-images.githubusercontent.com/19243918/45197804-ccd8db00-b228-11e8-84ec-22ee043436f1.PNG)

**Comment by AbhijitNilegaonkar** [comment]
Meredith ,

>>change the version for SAPUI5 back to Innovation

Unfortunately This did not help fix this problem. I guess the data binding is lost somehow. Not sure what to try next.

**Comment by AbhijitNilegaonkar** [comment]
Meredith, I created a fourth app again today. This time checking each step which step breaks it. I noticed that as soon as we switch to ODataServices it breaks. Fixing the ToysSets to Sets and Partof to Parts doesn't fix it.  IF your app is working can you share your S1 Controller, S0 View and component.js if that's possible?
Also wondering have there been any successful app submissions recently by other users. Just curious if it is only me who is having this issue. Thanks.

**Comment by mhassett92** [comment]
I cannot share the code since these are public and this is an ongoing coding challenge.

Are you connecting to the odata service we provide? What is the error you are seeing at that step? You will need to deploy the app once you change over to the live service. It will no longer work with FLP Mock Service file.

**Comment by mhassett92** [comment]
Glad to hear things are working! The name does not matter so long as you have all green checkmarks on the mission page and have filled out the registration form at the end. Good luck!
