### ISSUE TITLE
Change from a mock server to live OData service for TechEd

### ISSUE THREAD

**Issue by manqobanqobi** [SAPDocuments/Tutorials#2622]
Battling on step 5, any assist appreciated.

**Comment by chandrababu431** [comment]
Hi Meredith,

I'm also unable to validate the Navigationproperty, as it is getting invalid when I copy paste the Navigationproperty line. Can you please look into it and help/suggest in clearing this step.

Thanks,
Chandrababu

**Comment by mhassett92** [comment]
Can you share the order of the properties in the Nav Property? We have been seeing some issues with the metadata coming in in a different order un-expectantly.

**Comment by chandrababu431** [comment]
Hi @mhassett92 

Please find as below. Please let me know if it is not exactly what you have asked about to share.

	<NavigationProperty Name="PartOf" Relationship="89fb160c099c2fbe104db861.ToysPartOfParts" FromRole="FromRole_ToysPartOfParts"
					ToRole="ToRole_ToysPartOfParts"/>

Thanks,
Chandrababu

**Comment by mhassett92** [comment]
I believe you are using the incorrect metadata file. Did you create a new OData service using the destination provided in the previous tutorial? You should be using the metadata.xml file from the te2018lotteryapp folder under localservice.

**Comment by manqobanqobi** [comment]
Hi @mhassett92 i've created according to the tutorial and the xml file has 20lines max of code from the localservice folder

**Comment by mhassett92** [comment]
Do you have a te2018lotteryapp folder in the localservice folder?

**Comment by manqobanqobi** [comment]
yes i do

**Comment by chandrababu431** [comment]
Hey @mhassett92 

Can you please check this attachement.. I  guess, I'm using te2018lotteryapp only.

![image](https://user-images.githubusercontent.com/20707977/45229739-5699ae80-b2e4-11e8-9ab5-ca9f9d4ed04f.png)

Thanks,
Chandrababu

**Comment by manqobanqobi** [comment]
![screenshot 2018-09-07 17 56 14](https://user-images.githubusercontent.com/43050931/45229898-7e2e4e00-b2c7-11e8-92a5-2600e8fca00d.png)

**Comment by mhassett92** [comment]
Yes, so in the 2nd screenshot, you need the nav property from the sets type. Due to the current formatting, you cannot see it in there, but it is.

**Comment by chandrababu431** [comment]
Hi @mhassett92 ,

I'm not getting to whom you  are addressing above comment. 

Can you please share the latest metadata xml file. So that I will replace with the latest and will execute the xml file.

Please help me in this step, I was unable to complete this step due to invalid Nav Property.


[metadata_chandrababu1.txt](https://github.com/SAPDocuments/Tutorials/files/2361821/metadata_chandrababu1.txt)


Many Thanks in advance

Regards
Chandrababu

**Comment by mhassett92** [comment]
The XML in @manqobanqobi 's screenshot is the correct one. @chandrababu431 you are looking at the incorrect one. Please follow the directions and use the metadata.xml file in the te2018lotteryapp folder. I will not share code here as this is an active contest and these issues are public.

**Comment by manqobanqobi** [comment]
yeah your right it's all about syntax

**Comment by manqobanqobi** [comment]
thank you, as i continue

**Comment by manqobanqobi** [comment]
done

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
