### ISSUE TITLE
Series Data services on the API Business Hub

### ISSUE THREAD

**Issue by AbhijitNilegaonkar** [SAPDocuments/Tutorials#2625]
On step3 when I Execute the example I get below message. IT appears that this API is no longer available. I would like to request to update the Tutorial accordingly. Thanks. 

 {
  "code": "Service_Unavailable",
  "message": "This API is no longer available and replaced by SAP Predictive service - Business Services, Outliers Service"
}
Response h

**Comment by adadouche** [comment]
Hi @AbhijitNilegaonkar 

Let me check that, as there has been some API changes recently. The endpoint might have change.

I'll get back to you soon.

@bdel

**Comment by adadouche** [comment]
Hi @AbhijitNilegaonkar 

I was recently informed that the Time Series Changepoint Detection API has been finally decommissioned. Therefore, I will decommission this tutorial as well.

I'm sorry about the inconvenience,

Best Regards

Abdel
