### ISSUE TITLE
Installing SAP HANA, express edition Server + Apps, with Docker

### ISSUE THREAD

**Issue by colinjoy** [SAPDocuments/Tutorials#2629]
On the [overview page](https://www.sap.com/developer/topics/sap-hana-express.html) the diagram suggests that the docker variant is available for all platforms (Linux, Windows and Mac). However the detailed [install instructions](https://www.sap.com/developer/tutorials/hxe-ua-install-using-docker-xsa.html) explicitly mention that Windows and Mac are not supported:

> This installation does not support Docker for Windows or Docker for Mac

Either the diagram or the disclaimer needs to be updated to reflect the actual platform support.

**Comment by JCurrie27** [comment]
Assigning this issue to Adrian for investigation.

**Comment by aplata-sap** [comment]
Hi there, 

Sorry for the confusion. The docker installation is not supported for Docker for Windows or Docker for Mac. We have an update to the diagram in the works.
