### ISSUE TITLE
SAP HANA, express edition, in Google Cloud Platform Launcher (Database + XS Advanced)

### ISSUE THREAD

**Issue by normanmerten** [SAPDocuments/Tutorials#2633]
Hi,
in step 7 you have to install the sa..tgz but there is no file like sa.tgz. So you have to install hsa.tgz
cd /Downloads
tar -xvzf hsa.tgz

and 

sudo ./HANA_EXPRESS_20/install_hsa.sh

Kind regards,

Norman

**Comment by Lsubatin** [comment]
Thanks for bringing this up. It will be addressed in the next update.
