### ISSUE TITLE
Set up SAP Data Hub, trial edition

### ISSUE THREAD

**Issue by AbhijitNilegaonkar** [SAPDocuments/Tutorials#2640]
Step 3 Create solution instance
Issue 1. When I am at this step I get the following error. I did keep the recommended settings but it already says I have exceeded the quota? What am I missing?

![image](https://user-images.githubusercontent.com/19243918/45602669-c0ead700-b9e7-11e8-9262-9918d618040a.png)

![image](https://user-images.githubusercontent.com/19243918/45602659-897c2a80-b9e7-11e8-970c-4c5f019ee741.png)

Issue 2. Also I cannot access anything using the URL 

https://vhcalhxedb:51076/

Issue 3: There are cost estimates on this page. This is very confusing if this is a free trial. I am not sure if I am going to be charged for using this trial. 

This is the current state of quotas
I have only one project so far

![image](https://user-images.githubusercontent.com/19243918/45602782-a9145280-b9e9-11e8-9ca4-0df770c536ad.png)

I would appreciate your help. Thank you.

**Comment by thecodester** [comment]
@kulkarniamogh Can you help here?

**Comment by kulkarniamogh** [comment]
Hello @AbhijitNilegaonkar 

I will try to answer the issues in a slightly different order to make the explanation more fluent.

**Issue 3 :** 

Yes the trial is free from SAP but you have to bear the infrastructure expenses. Please refer to the FAQ page regarding Solution Types and Charging Model [here](https://blogs.sap.com/2016/08/23/faq-solution-types-and-charging-model/).

Below is a relevant answer from the FAQ page :

> You don’t need a SAP CAL subscription package and a Product license to run free solutions but still need an account with a supported infrastructure provider (Amazon Web Services or Azure) at your own expense.

**Issue 1 :**

This issue might occur if you own a GCP Free Tier account as it has certain restrictions with respect to the amount of resources you can utilize. Datahub requires more resources than what is offered to a GCP Free Tier account and to spin up an instance, you might need to upgrade your account.

**Issue 2 :**

The URL is only accessible after you enter the IP addresses in the hosts file. This step can be done after you are able to spin up an instance successfully. As you have encountered errors in the deployment part, this step is bound to fail.

Please let me know if you still have any questions.

Regards,
Amogh K

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
