### ISSUE TITLE
CRUD Master-Detail App tutorial - service setup issue

### ISSUE THREAD

**Issue by andreasfinkelmeyer** [SAPDocuments/Tutorials#2647]
I'm trying to follow the "Create a CRUD Master-Detail App" tutorial (https://www.sap.com/developer/tutorials/cp-webide-create-crud-app-template.html), but I am getting stuck on step 8. I have setup the  MobileServicesSampleData destination as described in step 3*, and I can select it in step 7, but when I try to test it as described in step 8, I get a red "undefined undefined" response under the "Data Connection" heading (where it says "Please enter the relative URL ..." at first).  I see no further information and the "Next" button remains disabled.

*When checking this availability of the destination connection on the  Destinations screen, I do get a 200 OK response.

**Comment by thecodester** [comment]
@VinoGandhiM Can you help here?

**Comment by VinoGandhiM** [comment]
@andreasfinkelmeyer can you please share a screenshot of the error?

**Comment by andreasfinkelmeyer** [comment]
@VinoGandhiM sure

as described, I can select the service/destination:
![sap_webide_template1](https://user-images.githubusercontent.com/32262057/45812581-182ec700-bcc8-11e8-8cdf-9995059da21f.PNG)

but after entering the forward slash in the "Relative URL" field and clicking Test, I get this:
![sap_webide_template2](https://user-images.githubusercontent.com/32262057/45812582-182ec700-bcc8-11e8-8298-76bbd173bf60.PNG)

**Comment by VinoGandhiM** [comment]
@andreasfinkelmeyer thanks. 
@lnoenssap can you help with this issue?

**Comment by lnoenssap** [comment]
Hi @andreasfinkelmeyer , can you show me the URL of the data service defined in the destination?

**Comment by thecodester** [comment]
@lnoenssap Is this issue still relevant?

**Comment by lnoenssap** [comment]
Sorry, lost track of this one. In most cases, the problem is with the configuration of the destination. But, I am aware of a bug preventing the usage of long destination names. Maybe this is the case here. 
@andreasfinkelmeyer: can you please try using a shorter name (eg. mssampledata) ? Meanwhile, we are working on a fix that should be going live by end of this month.

**Comment by lnoenssap** [comment]
The bug with the long destination names is fixed, by truncating the name. So, this should work now.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by camilo2312** [comment]
I present the same problem, because it does not allow me to test the connection, implement the solution that was raised about the name and now I have a 404 error and I do not know what it could be

somebody help me please

**Comment by thecodester** [comment]
@VinoGandhiM Can you help here?

**Comment by VinoGandhiM** [comment]
@lnoenssap can you help here?

**Comment by lnoenssap** [comment]
Hi @camilo2312 , please let me know on which environment you are facing this problem. Is it on the trial landscape, as used in the tutorial ?
