### ISSUE TITLE
Expose a Standard Core Data Service for ABAP Environment

### ISSUE THREAD

**Issue by akhil-agarwal** [SAPDocuments/Tutorials#2651]
Step 7 has incorrect screenshots. (The same as that for Step 8).

**Comment by thecodester** [comment]
@mervey45 Can you update?

**Comment by thecodester** [comment]
@mervey45 @niloofar-naseri Can you respond?

**Comment by niloofar-naseri** [comment]
@akhil-agarwal could you please review? The new updates are there, since october.

**Comment by mervey45** [comment]
@akhil-agarwal  I think it should be already updated. As I see it is from 20th September.
