### ISSUE TITLE
Set DB Build target for Standalone XSA Install

### ISSUE THREAD

**Issue by wilchemh** [SAPDocuments/Tutorials#2657]
We have xsa installed as a standalone instance on comodity hardware.  How do a configure the webIDE build target so that hdb MTA are built on my HANA Dev instance.  

I currenlty have a space enabled and a simple (tinyworld cds) project that succssfullys builds, but I have no Idea where the table is being built.  When I go into database explorer I don't see any HDI that exist. 

From the database explorer I am able to add a connection to my MultiTenant HANA Database, but I dont see how to set it as the build target..

**Comment by thecodester** [comment]
Which tutorial is this about?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
