### ISSUE TITLE
Series Data services on the API Business Hub

### ISSUE THREAD

**Issue by adamcharvat1** [SAPDocuments/Tutorials#2658]
[Decommissioned] Time Series Changepoint Detection API

{
  "code": "Service_Unavailable",
  "message": "This API is no longer available and replaced by SAP Predictive service - Business Services, Outliers Service"
}

**Comment by adadouche** [comment]
HI @adamcharvat1 

I was recently informed that the Time Series Changepoint Detection API has been finally  decommissioned. Therefore, I will decommission this tutorial as well.

I'm sorry about the inconvenience,

Best Regards

Abdel

**Comment by adadouche** [comment]
I have removed the Time Series Changepoint Detection API example and replaced it with Image Feature Extraction
