### ISSUE TITLE
Set up SAP Data Hub, developer edition

### ISSUE THREAD

**Issue by tatiana237** [SAPDocuments/Tutorials#2673]
Hi,
I've already installed the SAP Data Hub, developer edition. I'm about to build my first pipeline. I have executed the pipeline. unfortunately, the generated data is not visible on the terminal, although the pipeline has the status Running.
thanks for the answer

**Comment by thecodester** [comment]
@anishgupta85 @schneidertho Can you help here?

**Comment by anishgupta85** [comment]
Hi Tatiana,
Would it be possible to share the Scenario which you are using so that I could get an idea and then provide the relevant recommendation.
Thanks,
Anish

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
