### ISSUE TITLE
SAP HANA XS Advanced, Creating an HTML5 Module

### ISSUE THREAD

**Issue by salahchakchouki** [SAPDocuments/Tutorials#2680]
Not really  an issue, but just a small note to let you know that using the Space Enablement page to create the builder environment did not work for me until I opened it in incognito mode.
it might spare people a few minutes
Thank you for the quality turorials - very helpful :1st_place_medal:

**Comment by Lsubatin** [comment]
Hi! Thanks for the feedback. 

The space enablement tool should be used as XSA_ADMIN, so it makes sense that you need to alternate between normal and incognito mode. 

Was the space not enabled at all or did it "disappear" after a while?

Cheers, 
Lucia.

**Comment by salahchakchouki** [comment]
Hi Lucia
I can't say for certain because it was the first time I needed to access
In all cases the service was stopped.
That's probably a setting in the appliance available on the GCP marketplace
Regards
Salah

**Comment by Lsubatin** [comment]
Thanks, Salah. The space should be enabled by default, but I have reported that already. 

Thanks, 

Lucia.
