### ISSUE TITLE
Topic Detection ML service with SAPUI5

### ISSUE THREAD

**Issue by ptharso** [SAPDocuments/Tutorials#2705]
When i upload only a text file i received a Error 400 Undefined....How can resolve this?

**Comment by adadouche** [comment]
Hi @ptharso,

Can you provide the full error message and the request payload sent from your browser.
YOu can get that from the browser "developer" tools on the network tab.

Regards

Abdel

**Comment by ptharso** [comment]
I understood nothing....

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by adadouche** [comment]
Hi @ptharso 

Sorry for the delayed response, but this is TechEd season and I'm flying all over these days.

When using your browser, you can start the "developer tools" by pressing F12, then you can check the "Network tab" to analyze each and every network request.
There is a search facility as well to locate the topic detection request.

Regards

**Comment by choas** [comment]
@ptharso,
uploading only one text file should result to this error message:
> Invalid request: This service requires at least 2 files or 1 archive

To verify this, you could replace in the /webapp/controller/demo.controller.js file at line 61 `error_description` to `error.message`

**Comment by adadouche** [comment]
Hi @ptharso & @choas 

I just refreshed the tutorial to reflect some of the service change and tried to make the code a bit simpler

Thanks
