### ISSUE TITLE
problem with IoT Tutorial

### ISSUE THREAD

**Issue by GalbiatiL** [SAPDocuments/Tutorials#2758]
Dear all,
I have a problem with the tuturial Tutorials/tutorials/iotae-comp-buildappmc0/iotae-comp-buildappmc0.md .
It's all ok until the step 6, where in my develop I'm unable to find the action described in step 6.
Again, I can't run my develop.

I understand that the version of SAP IoT Application is different from the tutorial to now and I find all the object described in the tutorial, but from the step 6 something is not working.

thanks in advance

**Comment by thecodester** [comment]
This has been resolved. https://github.com/SAPDocuments/Tutorials/pull/2782
