### ISSUE TITLE
Call an External API

### ISSUE THREAD

**Issue by lucasborin** [SAPDocuments/Tutorials#2772]
Tutorial: https://developers.sap.com/netherlands/tutorials/abap-environment-external-api.html

How can I create the ZSAP_COM_0276 ?

**Comment by thecodester** [comment]
@julieplummer20 Can you help here?

**Comment by julieplummer20** [comment]
Hi Lucas, Am not in the office today due to illness . Will look into it as soon as I get back. 
One question : Were you on a TechEd system? If not, can you please provide SID, sub account name, space for the system? If ZSAP_COM_0276 is not available, I may be able to provide details of how to create it. 
BR Julie.

**Comment by lucasborin** [comment]
Hi Julie,

No, I'm not on a TechEd system. I have my own global account. 

SID: GSLOGBR
SubAccount: IE
Space: dev

BR Lucas.

**Comment by lucasborin** [comment]
Hi Julie, 

May I have access to TechEd AppSpace? I'm an SAP employee. 

BR Lucas

**Comment by julieplummer20** [comment]
Hi Lucas, I have contacted the team - I'll be in touch.
Best wishes Julie.

**Comment by julieplummer20** [comment]
Hi Lucas, The TechEd team are restricting access to the TechEd system itself. They had created a copy, which I was working on, but it has now been deleted (!). My manager is trying to set up a new copy system asap.
You should be able to access an internal system, and there you can see whether the relevant objects have been created. However, currently the relevant apps have not been assigned to developer users. I will send you an internal email with access to the system and let you know as soon as the relevant roles/ authorizations have been assigned. If you hear nothing by Tuesday next week, feel free to email me.
Best wishes, Julie.

**Comment by julieplummer20** [comment]
This issue can be closed. I will provide the info to Lucas by email as soon as it is available.

**Comment by julieplummer20** [comment]
Hi Lucas, Sorry, it will take longer to set up the new system. I will let you know when we get the new system.
