### ISSUE TITLE
Download and Prepare App for Cloud Foundry Deployment

### ISSUE THREAD

**Issue by tw4dl** [SAPDocuments/Tutorials#2774]
Enter the value of the name parameter that exists already in the manifest.yml in the field below and choose Validate.

==> choose "Submit Answer"

**Comment by thecodester** [comment]
Do you have a question?

**Comment by qmacro** [comment]
I'm guessing @tw4dl means that the text after "choose" should be changed, as the button no longer says "Validate" in the new tutorial pages, but "Submit Answer". I'll address this. Thanks for the heads up, @tw4dl !

**Comment by qmacro** [comment]
Fixed via PR #2786
