### ISSUE TITLE
Create a low-fidelity SAP Build prototype

### ISSUE THREAD

**Issue by tw4dl** [SAPDocuments/Tutorials#2775]
Before you can drag and drop images to the prototype, a step is missed to create a new prototype

**Comment by rbrainey** [comment]
Max, would you update the flow description in the tutorial?  Thanks,

**Comment by maxstreifeneder** [comment]
There's more to adjust, will do that beginning next week

**Comment by thecodester** [comment]
@maxstreifeneder  Any update?

**Comment by IObert** [comment]
Closing the issue as we decided to remove the tutorial. Sorry for the inconvenience!
