### ISSUE TITLE
SAP HANA, express edition, in Google Cloud Platform Launcher (Database + XS Advanced)

### ISSUE THREAD

**Issue by kmsenthilvel** [SAPDocuments/Tutorials#2776]
tar -xvzf sa.tgz not possible because of missing sa.tgz file 

also https://hxehost:53075 returns eror as "forbidden"

**Comment by Lsubatin** [comment]
If Web IDE shows forbidden, you are probably using XSA_ADMIN to log in. The session is persisted across browser windows.

The sa file might be hsa.tgz, you can use command ls -la to check the name. Thanks for pointing it out, I'll correct it.
