### ISSUE TITLE
Create a CRUD Master-Detail App

### ISSUE THREAD

**Issue by prm2205** [SAPDocuments/Tutorials#2780]
"/" in relative Url is not working 
I am not able to connect with odata service

**Comment by thecodester** [comment]
@VinoGandhiM Can you help here?

**Comment by lnoenssap** [comment]
Hi @prm2205 , is this issue still relevant?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by Eviloux** [comment]
Hello, i have the same error. and is not the longer of destination name i have check. 
![image](https://user-images.githubusercontent.com/44774088/56658375-cb1a3580-669a-11e9-9e0c-828fa499147d.png)

**Comment by thecodester** [comment]
@lnoenssap Can you assist?

**Comment by lnoenssap** [comment]
> Hello, i have the same error. and is not the longer of destination name i have check.
> ![image](https://user-images.githubusercontent.com/44774088/56658375-cb1a3580-669a-11e9-9e0c-828fa499147d.png)

Hi @Eviloux ,

Can you check your destination settings and re-enter the credentials ? I had similar issues when my credentials were not up-to-date.

Thanks,
Ludo
