### ISSUE TITLE
Add Data to Your OData Service

### ISSUE THREAD

**Issue by vivekprabhu1** [SAPDocuments/Tutorials#2784]
I am doing the Tutorial - "Add Data to Your OData Service". I went to Database Explorer and added the Database from the pop up but when I go the the Tables in the added Database, I am not getting any Tables. As per tutorial, MY_APP_PRODUCTS should have been generated.

![image](https://user-images.githubusercontent.com/42771934/48704936-debdfd80-ec1d-11e8-9870-47d960324411.png)

**Comment by qmacro** [comment]
Hi @vivekprabhu1 - thanks for commenting. The issues in this repo are mainly for problems with the tutorial content itself (markdown, flow, images, prose, etc). May I please point you in the direction of our [SAP Community Q&A](https://answers.sap.com/index.html) for your question? That way also others might benefit from the question and also the answers and conversation. Thank you!
