### ISSUE TITLE
Create an SAPUI5 Purchase Order App

### ISSUE THREAD

**Issue by lechnerc77** [SAPDocuments/Tutorials#2788]
Step 3: Test the connected OData service
Currently(?) the WebIDE Full Stack creates non-matching entries in the `manifest.json` and `neo-app.json` file for the destination of the OData Service. 
The hint "_In case this request fails, there has been a issue while creating the destination in the Neo environment. Please make go back to the previous tutorial to make sure the destination is set up correctly_" should be enhanced with an additonal cross-check for this source of error. I attached corresponding screenshots [Mismatch.pdf](https://github.com/SAPDocuments/Tutorials/files/2598683/Mismatch.pdf)

**Comment by lechnerc77** [comment]
Addendum: In the screenshot of the corrected `neo-app.json` the `entryPath` is also relevant for a successful  connection to the OData service

**Comment by IObert** [comment]
Hi @lechnerc77,

many thanks for this detailed report. You're right, there seems to be an issue with the Web IDE. I added a note and I'll forward this issue to the dev team.
