### ISSUE TITLE
Connect to Microsoft Graph

### ISSUE THREAD

**Issue by lechnerc77** [SAPDocuments/Tutorials#2789]
Step 1: Register app in Microsoft Application Registration Portal

This step conatins the remark: "_You (and the users of your application) can revoke the given permissions at https://myapps.microsoft.com_". However, when hitting this URL I get redirected to https://account.activedirectory.windowsazure.com/r#/applications and I do not get an option to revoke my permissions.
In my case (I do not know if this differs in case of private or professional accounts) I can revoke my permissions when going to https://account.live.com/consent/Manage. This should be added to the remark.

**Comment by IObert** [comment]
You're right @lechnerc77, the links doesn't work for personal accounts
Thanks!
