### ISSUE TITLE
React JS - Add REST OData retrieval

### ISSUE THREAD

**Issue by renatovilasboas** [SAPDocuments/Tutorials#2794]
The route does not works, i fix it using the direct link : 

var odataUrl = "https://services.odata.org/V3/Northwind/Northwind.svc/";

and finally works.

**Comment by jonathanbaker7** [comment]
If you have to use the entire URL, and you can't get the short version to work, it means the destination isn't set up correctly in SAP Cloud Platform.  

Now, in theory, using the direct route would make more sense.  But, the browsers have a security measure called "same origin".  This policy prevents any script inside the page from reaching out to a third party website (something with a different host name).  Hence the "same origin".  [Read more about it here](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy).

In SAP Cloud Platform, the destination provides a way to work around this browser security.  A destination is really just a pass-through.  The browser calls a URL in cloud platform, and that URL tells cloud platform to send out the request to a third party server.  The browser thinks it is only communicating with a single host, so it has no problem.

The tutorial is built around this destination system.  If your destination isn't set up correctly, our URL won't work.  You can go around it by using the full hostname, and telling the browser to ignore the same origin policy, but that's not a great solution for production systems.

Let me know if you have any other questions.

**Comment by renatovilasboas** [comment]
> If you have to use the entire URL, and you can't get the short version to work, it means the destination isn't set up correctly in SAP Cloud Platform.
> 
> Now, in theory, using the direct route would make more sense. But, the browsers have a security measure called "same origin". This policy prevents any script inside the page from reaching out to a third party website (something with a different host name). Hence the "same origin". [Read more about it here](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy).
> 
> In SAP Cloud Platform, the destination provides a way to work around this browser security. A destination is really just a pass-through. The browser calls a URL in cloud platform, and that URL tells cloud platform to send out the request to a third party server. The browser thinks it is only communicating with a single host, so it has no problem.
> 
> The tutorial is built around this destination system. If your destination isn't set up correctly, our URL won't work. You can go around it by using the full hostname, and telling the browser to ignore the same origin policy, but that's not a great solution for production systems.
> 
> Let me know if you have any other questions.

Hi, unfortunately i follow exactly the instructions passed in tutorial, when i used the test, the connection works fine, but when the page request anything works, is there another way to test ?

**Comment by jonathanbaker7** [comment]
The best way to test is to use Google Chrome as a browser.  When you get to the point in the tutorial where it isn't working, right click on the page and choose `inspect`.  Then click on the `console` tab, and look for lines in red.  Those error messages will tell you what is going on.

Feel free to post those lines here, if you are having trouble decoding them.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
