### ISSUE TITLE
Add a Web Dynpro ABAP App to Your Launchpad Page

### ISSUE THREAD

**Issue by Alexander-Boehm** [SAPDocuments/Tutorials#2796]
Hello, 

thank you for you guide! It is a great entry point for the first steps when getting Backend Ressourced embedded into the SCP.

I tried to follow your guide to embedd a nwbc login page for an SRM system into the SCP launchpad as a test. I configured the Destinations in the SCP Subaccount as good as I could for the backend system and also configured the Cloud connector to get this testcase up and running. But I get always the error that is is now possible to get accessed.

![image](https://user-images.githubusercontent.com/45234847/48845742-962d4e00-ed9d-11e8-9655-c3804164a036.png)

Maybe I´m missing some steps in the backend:

* How is the service exposed to the SCP? I only know OData access from another App and was thinking what has to be done in the Backend System to make it available in the SCP?
* How can I configure the access to Apps located in the SAP Backend System as there is also the App-Ressource search functionality which doesn´t provide results as when switching to the Backend Tab?
* Where can I find detailed information regarding the Parametrisation of an Webdynpro App in the SCP?
There is only one example in the tutorial more information would be great to get your own stuff working?

Any help is really appreciated.

BR 

Alexander

**Comment by idosun** [comment]
Hey,

What do you mean by "nwbc login page" ? The NWBC is used to render the the WD ABAP/SAP GUI in the cloud portal. To read more about this capability and how to configure it follow this documentation: 
[Working with Backend Apps](https://help.sap.com/viewer/69d450542ffa47e789f122a79ea2ab7b/Cloud/en-US/347e744c023a4d9781bf1285f7ddd92c.html)

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue.

If you still have questions, feel free to reopen the issue.
