### ISSUE TITLE
Add labels and a new field to your app

### ISSUE THREAD

**Issue by Danish-Adeel** [SAPDocuments/Tutorials#2801]
this tutorial seems outdated because now things are different as compared to this tutorial

**Comment by qmacro** [comment]
Can you please supply information as to which tutorial this is? Thanks.

**Comment by thecodester** [comment]
I assumed https://developers.sap.com/austria/tutorials/hcp-webide-add-labels-field.html

**Comment by qmacro** [comment]
Thats only one tutorial :-) @Danish-Adeel can you please elaborate?

**Comment by Danish-Adeel** [comment]
https://github.com/SAPDocuments/Tutorials/issues/2801
The issue in it is that I cant find unitsinstock in Detail.view.xml

**Comment by qmacro** [comment]
This is indeed a little bit outdated. I checked the [source group](https://developers.sap.com/austria/group.mobile-app-1.html) (where the app was created) and the Kapsel-related template doesn't exist any more. @KevinMuessig is looking at the mobile tutorials as a whole, with deprecation in mind, so I will assign this to him for comment. In the meantime, thanks for the heads-up.

**Comment by qmacro** [comment]
@jarjarbentley can you please deal here - I've checked out the tutorial and the group it is in (https://developers.sap.com/group.mobile-app-2.html) which refers to (as an implicit and hard prerequisite) "mobile group 1" which I'm guessing is https://developers.sap.com/group.mobile-app-1.html (and @thecodester concurs with that guess). This prerequisite group contains a tutorial that gets the reader to build a mobile app via the HAT and Kapsel, an app which is essential for this tutorial here. 

But I suspect there are some items deprecated here, esp. when I see this notice in the Web IDE relating to the HAT:

![screen shot 2019-01-30 at 07 59 37](https://user-images.githubusercontent.com/73068/51966701-1985b280-2465-11e9-82ea-b82f713c47a6.png)

Passing this over to you as mobile subject expert - this may need deprecating.

Thanks!

**Comment by thecodester** [comment]
@jarjarbentley  Any updates?

**Comment by jarjarbentley** [comment]
Sorry guys. Not sure how I missed this. I’ll pull it up this afternoon

Cheers,

Josh Bentley
SAP Developer Relations
Cloud & Mobile Evangelist

On Feb 25, 2019, at 6:11 AM, Daniel Wroblewski <notifications@github.com<mailto:notifications@github.com>> wrote:


@jarjarbentley<https://github.com/jarjarbentley> Any updates?

**Comment by thecodester** [comment]
@jarjarbentley Can this issue be closed?

**Comment by jarjarbentley** [comment]
Yes, we need to deprecate and close this issue.
