### ISSUE TITLE
Basic Authentication and Secure Key Store

### ISSUE THREAD

**Issue by AnikaJain** [SAPDocuments/Tutorials#2803]
Hey, I am using SAP CP SDK for iOS version 3.0. I can't find BasicAuthViewController.swift file in the project. Can you tell me where it can be found  or else I have to create?

**Comment by qualiture** [comment]
Hi @AnikaJain,

I'm really sorry, but I believe this tutorial is no longer valid... Looking at the screenshots, it does not seem to use the Onboarding flow which was introduced in v2 of the SDK. And now with v3, the on boarding has been changed significantly as well.

The current basic authentication on boarding flow already incorporates some storage of credentials, making this tutorial void...

If you want to implement the `SecureKeyValueStore` for other purposes, just follow the basic steps outlined in steps 4, 5, 6 and 10

@KevinMuessig, can you maybe have a second look at this tutorial? Looks like it's void now and should be removed

**Comment by AnikaJain** [comment]
I have followed the tutorial till the step 10. But from these steps how can I access the user credentials and store them locally? Can you tell what extra function or steps are needed to do it?

**Comment by KevinMuessig** [comment]
Hi @AnikaJain,

do you have the link to the tutorial you're trying to go through?

Thanks

**Comment by KevinMuessig** [comment]
We decided to take it offline for now because it is outdated. I will update the tutorial as soon as possible. Let me give you a solution in the meantime. I will answer you as soon as possible.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
