### ISSUE TITLE
Debug Your Java App

### ISSUE THREAD

**Issue by ericrosfelder** [SAPDocuments/Tutorials#2804]
It's not possible to validate de "step 1"  in the page : https://developers.sap.com/tutorials/cp-cf-java-debug.html.

The checkmark could not be green and so you can't have 100%.

**Comment by maxstreifeneder** [comment]
Hi @ericrosfelder , 

could you please describe your problem again? Step 1 doesn't have any validation.  And could you also please retry validating the steps anyway? All validations work for me so far. 

Cheers,
Maxi

**Comment by ericrosfelder** [comment]
Hi @maxstreifeneder ,

Exact, step 1 doesn't have any validation but step 1 taken into account for the overall rating.

So I have 67% because I can just validate step 2 and step 3.

**Comment by maxstreifeneder** [comment]
@thecodester Could you please have a look at this problem? eric is right, I was able to reproduce the problem. 

![image](https://user-images.githubusercontent.com/36535298/49699218-c2830000-fbce-11e8-85fb-eb0ec31b1be0.png)

![image](https://user-images.githubusercontent.com/36535298/49699349-55706a00-fbd0-11e8-8c69-ef948ba65a8c.png)

**Comment by thecodester** [comment]
The rules file has no correct answer specified, so the question did not get created :-(

Do you know what the answer should be?
Whose tutorial is this?

**Comment by maxstreifeneder** [comment]
issue should be fixed
