### ISSUE TITLE
Add a Database to Your Business Application

### ISSUE THREAD

**Issue by ericrosfelder** [SAPDocuments/Tutorials#2805]
When you do the first step of https://developers.sap.com/tutorials/cp-apm-03-add-database.html, it's not possible to build the db.

We got an error : 
`Error: Version incompatibility for the "com.sap.hana.di.cds" build plugin: "2.0.2.0" (installed) is incompatible with "2.0.30.0" (requested by .hdiconfig file or used in previous deployment) [8210507]     at "src/gen/CATALOGSERVICE_AUTHORS.hdbcds" (0:0)`

----

I found how to correct this problem
- Edit the **db/src/.hdiconfig** file. Note : you must show hidden file to see it.
- Change the line `"plugin_version": "2.0.30.0",` by `"plugin_version": "2.0.2.0",`

**Comment by Chuergo** [comment]
Thanks for raising this issue. We have added the fix to the tutorial (as an interim solution), but we are working on a more permanent fix that doesn't involve manually updating versions. As soon as it is released, we'll update the tutorial again.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by Apfohlmann** [comment]
Thank you for your help@boghyon.

Have you completed the two previous tasks listed in the tutorial group? https://developers.sap.com/group.cp-apm-full-stack-app.html

**Comment by boghyon** [comment]
@Apfohlmann Yes, I did. I was doing the mentioned tutorials sequentially one by one.

**Comment by Apfohlmann** [comment]
@boghyon can you provide any additional information? Do you get the same error message as mentioned above?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
