### ISSUE TITLE
Install the Optional SAP HANA Automated Predictive Library Package for SAP HANA, express edition

### ISSUE THREAD

**Issue by mavesura** [SAPDocuments/Tutorials#2809]
Cannot being able to run the install_apl.sh script.. 

We need to run as root and don't have access to root

**Comment by i067268** [comment]
@mavesura 
do you mean,  you can not run the install_apl.sh script because you don't have root permission, and this script need run as root, right?

**Comment by adadouche** [comment]
Hi @mavesura 

do you have sudo rights ? I mean that you should get access to the hxeadm user, which by default have sudo rights.

Regards
@bdel

**Comment by adadouche** [comment]
Hi @mavesura 

Have you been able to complete the APL installation?

Thanks

@adadouche

**Comment by adadouche** [comment]
Hi @mavesura ,

I hope that "no news is good news". I'll close this issue for now, but feel free to reopen if the issue is not solved.

Thanks
@
