### ISSUE TITLE
Build a mobile app from an SAP Web IDE template

### ISSUE THREAD

**Issue by VivekRajKM** [SAPDocuments/Tutorials#2810]
@lpareek Thanks for the excellent step-by-step guide. Kudos!

Feedback: Interested in knowing about completing the mission. Usually a 'Completed' button is available with the previous ones, but it wasn't available with this tutorial though. 

Kind regards,
Vivek.

**Comment by thecodester** [comment]
@KevinMuessig I know this isn't yours but it is classified among the mobile tutorials

**Comment by VivekRajKM** [comment]
@thecodester @KevinMuessig Guys, would like to re-iterate that the issue is on the tutorial hosted page, where we are unable to get the completion status. 

Cheers,
Vivek

**Comment by thecodester** [comment]
I see. We have only added this capability to follow your progress on the newer tutorials and haven't yet added it to the older ones. I will check to see if we can get this done quicker.

**Comment by VivekRajKM** [comment]
Much thanks @thecodester :)

**Comment by KevinMuessig** [comment]
Hi @VivekRajKM, is the issue still there?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
