### ISSUE TITLE
Create an SAPUI5 Purchase Order App

### ISSUE THREAD

**Issue by chillamcherla** [SAPDocuments/Tutorials#2812]
could you let us when where to add the code from step 5.3 

"Add the form controls with the associated layout information." is to the MainView.view.xml file ?

**Comment by qmacro** [comment]
Add it here, where indicated. 

<img width="670" alt="screen shot 2018-11-28 at 15 39 12" src="https://user-images.githubusercontent.com/73068/49144648-e66b5980-f323-11e8-9e3f-54255fb66424.png">
