### ISSUE TITLE
Installing SAP HANA Streaming Analytics for SAP HANA, Express Edition

### ISSUE THREAD

**Issue by krodyrobi** [SAPDocuments/Tutorials#2817]
`./HXEDownloadManager_linux.bin linuxx86_64 installer hsa.tgz`
Java virtual machine version 1.6.0 is too low, require 1.8 or higher.

CAL image: SAP HANA, Express Edition Publisher: SAP SE Update: 67

Any ideas on how to update java as no package managers are installed.

**Comment by krodyrobi** [comment]
Tried:
- finding java versions on disk -> empty folders for different versions 
- finding a rpm package for SLES 12 SP 1 of openjdk -> nothing
- tried adding java jdk 1.8.0 tar.gz and updating envs and alternatives -> still uses 1.6
```
sudo update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_191/bin/java 9999

HXEDownloadManager_linux.bin linuxx86_64 installer hsa.tgz
Java virtual machine version 1.6.0 is too low, require 1.8 or higher.

which java
/usr/bin/java

/usr/bin/java -version
java version "1.8.0_191"

```

**Comment by krodyrobi** [comment]
Managed to fake the java version and got the downloader to run, but when Installing the package I get an incompatible version :)

```
Connecting to download server...

SAP HANA, express edition version: 2.00.033.00.20180925.2

Downloading "SAP HANA streaming analytics"...
hsa.tgz : 100%
Concatenate download files to /root/Downloads/hsa.tgz...
/root/Downloads/hsa.tgz created.
Verify /root/Downloads/hsa.tgz file checksum...
/root/Downloads/hsa.tgz file checksum is OK.

####

./install_hsa.sh
Enter SAP HANA system ID [HXE]:

Cannot install SAP HANA streaming analytics.  This SAP HANA streaming analytics version is not compatible with your installed HANA, express edition version
```

**Comment by darkalex2004** [comment]
Hi,

I am looking into this issue, I just want to know the version of your HXE , could you please show me your hxe_info.txt file content.
cat /hana/shared/HXE/global/hdb/hxe_info.txt

Thanks

**Comment by darkalex2004** [comment]
also please cat /usr/sap/HXE/SYS/global/hdb/hxe_info.txt

**Comment by krodyrobi** [comment]
Unfortunately the machine was destroyed and now the new machine has a lower version initially it was 
2.00.033.00.20180925.2, either way the java version is still 1.6


```
sid-hxe:~ # cat /hana/shared/HXE/global/hdb/hxe_info.txt
[hxe_version]
HANA, express edition=2.00.031.00.20180712.1
#
HDB_AFL=2.00.031.00
HDB_LCM=2.00.031.00
HDB_SERVER=2.00.031.00
#
XSA_RT=1.0.85
XSAC_COCKPIT=2.6.7
XSAC_HRTT=2.5.65
XSAC_MESS_SRV=1.3.4
XSAC_SAP_WEB_IDE=4.3.2
XSAC_PORTAL_SERV=1.13.4
XSAC_SERVICES=1.6.7
XSAC_UI5_FESV3=1.44.36
XSAC_UI5_FESV4=1.52.14
XSAC_XSA_COCKPIT=1.1.7
#
XSAC_SHINE=1.5.3
[hxe_installation]
INSTALL_TYPE=Binary
INSTALL_DATE=Thu Aug  2 14:55:02 UTC 2018



sid-hxe:~ # cat /usr/sap/HXE/SYS/global/hdb/hxe_info.txt
[hxe_version]
HANA, express edition=2.00.031.00.20180712.1
#
HDB_AFL=2.00.031.00
HDB_LCM=2.00.031.00
HDB_SERVER=2.00.031.00
#
XSA_RT=1.0.85
XSAC_COCKPIT=2.6.7
XSAC_HRTT=2.5.65
XSAC_MESS_SRV=1.3.4
XSAC_SAP_WEB_IDE=4.3.2
XSAC_PORTAL_SERV=1.13.4
XSAC_SERVICES=1.6.7
XSAC_UI5_FESV3=1.44.36
XSAC_UI5_FESV4=1.52.14
XSAC_XSA_COCKPIT=1.1.7
#
XSAC_SHINE=1.5.3
[hxe_installation]
INSTALL_TYPE=Binary
INSTALL_DATE=Thu Aug  2 14:55:02 UTC 2018
```

**Comment by krodyrobi** [comment]
Correction the download manager is reporting another version than the files!

**Comment by krodyrobi** [comment]
For some reason if I run the download as root or as hxeadm the versions detected are different.

**Comment by darkalex2004** [comment]
Hi krodyrobi , 

I have checked that if we use root to run downloadmanager will download the latest version of hxe and other optional components , this is what we expected. 
So if you have installed HXE , you should use hxeadm to run dm.

for the java installation issue , I wonder if you can  download a binary manually from oracle website , and install it manually.

Thanks

**Comment by krodyrobi** [comment]
I've done that but not knowing the implications of licensing would make it difficult to pick a version just for a download script.

Thank you for looking into it.

Also I got to the point where it is asking me for 2 passwords 1 for %adm% and 1 for SYSTEM, from the docs I saw it should be the password from CAL when the setup occured but haven't been able to use this for both of them.

I managed to pass the first one with the CAL password but it didn't seem to work for SYSTEM as well, something to do with not being able to SystemDB any ideas on what that could be?

**Comment by krodyrobi** [comment]
Any ideas on why I can't connect using the installer but can directly from hdbsql


```
sid-hxe:/usr/sap/HXE/home/Downloads/HANA_EXPRESS_20 # ./install_hsa.sh
Enter SAP HANA system ID [HXE]:

Enter HANA instance number [90]:

Enter local host name [sid-hxe]:

Enter System administrator (hxeadm) password :

Enter System database user (SYSTEM) password :


* 10: authentication failed SQLSTATE: 28000

Cannot login to "SystemDB" database with "SYSTEM" user.
Please check if password is correct.



sid-hxe:/usr/sap/HXE/HDB90/exe # ./hdbsql -i 90 -d systemdb -u SYSTEM
Password:

Welcome to the SAP HANA Database interactive terminal.

Type:  \h for help with commands
       \q to quit

hdbsql SYSTEMDB=>



hxeadm@sid-hxe:/usr/sap/HXE/HDB90/exe> ./hdbsql -i 90 -d systemdb -u SYSTEM     Password:

Welcome to the SAP HANA Database interactive terminal.

Type:  \h for help with commands
       \q to quit

hdbsql SYSTEMDB=>

```

**Comment by krodyrobi** [comment]
For instance in the install script there is a check for the SYSTEM password
that ends up in the following command to be ran
```
su -l hxeadm -c '/usr/sap/HXE/HDB90/exe/hdbsql -A -x "\c -i 90 -d SystemDB -u SYSTEM -p PASSWORD"'
```

What is weird is that the same command but from inside hdbsql works.

```
./hdbsql -i 90 -d systemdb -u SYSTEM
Password: PASSWORD

Welcome to the SAP HANA Database interactive terminal.

Type:  \h for help with commands
       \q to quit

hdbsql SYSTEMDB=> \c -i 90 -d SystemDB -u SYSTEM -p PASSWORD
Connected to HXE@localhost:39013
hdbsql SYSTEMDB=> \di
Connection closed
hdbsql=> \c -i 90 -d SystemDB -u SYSTEM -p PASSWORD
Connected to HXE@localhost:39013
hdbsql SYSTEMDB=>
```

**Comment by krodyrobi** [comment]
I don't understand why the password from the cli doesn't work but if I'm inside hdbsql or let it prompt for the password it works, this is stopping the download script of SDS.

```
sid-hxe:/usr/sap/HXE/HDB90/exe # ./hdbsql -d SystemDB -i 90 -u SYSTEM -p PASSWORD                                                                                     sK
* 10: authentication failed SQLSTATE: 28000



sid-hxe:/usr/sap/HXE/HDB90/exe # ./hdbsql

Welcome to the SAP HANA Database interactive terminal.

Type:  \h for help with commands
       \q to quit

hdbsql=> \c -d SystemDB -i 90 -u SYSTEM -p PASSWORD
Connected to HXE@localhost:39013
hdbsql SYSTEMDB=>



sid-hxe:/usr/sap/HXE/HDB90/exe # ./hdbsql -d SystemDB -i 90 -u SYSTEM
Password: PASSWORD

Welcome to the SAP HANA Database interactive terminal.

Type:  \h for help with commands
       \q to quit

hdbsql SYSTEMDB=>
```

**Comment by krodyrobi** [comment]
Even though SAP CAL permits $,# chars in the password the installer doesn't treat them well.

**Comment by krodyrobi** [comment]
Changing the password of CAL to something without special characters brought me closer but still no cigar.

```
##############################################################################
# Summary before execution                                                   #
##############################################################################
HANA, express edition installer          : /usr/sap/HXE/home/Downloads/HANA_EXPR                                                   ESS_20
  Component(s) to install                : client,streaming
  HANA system ID                         : HXE
  HANA instance number                   : 90
  Host name                              : sid-hxe
  System administrator (hxeadm) password : ********
  SystemDB database pasword (SYSTEM)     : ********
  Tenant database to add streaming       : HXE
  Tenant database password (SYSTEM)      : ********

Proceed with installation? (Y/N) : Y



Collecting garbage...
Collect garbage on "hdbnameserver"...
Shrink resource container memory on "hdbnameserver"...
Collect garbage on "hdbindexserver"...
Shrink resource container memory on "hdbindexserver"...
Collect garbage on "hdbcompileserver"...
Shrink resource container memory on "hdbcompileserver"...
Collect garbage on "hdbdiserver"...
Shrink resource container memory on "hdbdiserver"...
Collect garbage on "hdbwebdispatcher"...
Shrink resource container memory on "hdbwebdispatcher"...

Total in use HANA processes heap memory (MB)
============================================
Before collection : 2664
After  collection : 2379

Free and used memory in the system
==================================
Before collection
-------------------------------------------------------------------------
             total       used       free     shared    buffers     cached
Mem:           58G        37G        20G        68M        35M        20G
-/+ buffers/cache:        16G        41G
Swap:          23G         0B        23G
After  collection
-------------------------------------------------------------------------
             total       used       free     shared    buffers     cached
Mem:           58G        34G        23G        68M        35M        20G
-/+ buffers/cache:        13G        44G
Swap:          23G         0B        23G

Install HDB Client, SAP HANA streaming analytics...


SAP HANA Lifecycle Management - SAP HANA Database 2.3.48.0
**********************************************************


Running in batch mode
  Host name 'sid-hxe' is not part of the system

Log file written to '/var/tmp/hdb_HXE_hdblcm_update_2018-12-04_11.09.38/hdblcm.l                                                   og' on host 'sid-hxe'.

Failed to install HDB Client and/or SAP HANA streaming analytics...
```

```
SELECT CLIENT_HOST FROM M_CONNECTIONS WHERE CONNECTION_ID = CURRENT_CONNECTION;
sid-hxe
```

If i choose instead of the default sid-hxe   -> vhcalhxedb the localhost in /etc/hosts it seems to work, but why?

**Comment by JCurrie27** [comment]
I'm not sure if this helps with your particular installation scenario, but the documentation for the SAP HANA, express edition for the 1) [preconfigured virtual machine](https://developers.sap.com/tutorials/hxe-ua-getting-started-vm-xsa.html) and 2) [binary installer](https://developers.sap.com/tutorials/hxe-ua-installing-binary-xsa.html) installation scenarios provides these guidelines for the express edition master password:

Note:
SAP HANA, express edition requires a very strong password – even stronger than other editions of SAP HANA. Your password must comply with these rules:
•At least 8 characters
•At least 1 uppercase letter
•At least 1 lowercase letter
•At least 1 number
•Can contain special characters, but not backtick, $ (dollar sign), \ (backslash), ' (single quote), or " (double quotes)
•Cannot contain simplistic or systematic values, like strings in ascending or descending numerical or alphabetical order

**Comment by krodyrobi** [comment]
https://ip:51046/  should open the admin ui from outside the vm, but it redirects in the outside browser to vhcalhxedb which doesn't have a meaning outside the vm.
Any ideas?

**Comment by krodyrobi** [comment]
Yep but the CAL creation guidelines don't specify the same restrictions with regards to the master password.
It is counter intuitive when CAL provides a fully packaged solution that uses the master password for users without documenting this in the image specs, like separate restrictions for them, users might not know those HANA specifics.

Thank you for your assistance.

**Comment by JCurrie27** [comment]
Have you tried asking this question on the [CAL community Q&A page](https://answers.sap.com/tags/67837800100800004473)? There are HXE/CAL questions somewhat similar to this on on the CAL page. If you have any remaining configuration problems, I recommend closing this GitHub issue and posting a question to the CAL community, as your question will have higher community visibility.

**Comment by JCurrie27** [comment]
Password-related clarifications have been made to the document: [https://caldocs.hana.ondemand.com/caldocs/help/Getting_started_HANA_Express.pdf](https://caldocs.hana.ondemand.com/caldocs/help/Getting_started_HANA_Express.pdf)
