### ISSUE TITLE
Download a SQL client and connect to your instance (SAP HANA, express edition, server-only)

### ISSUE THREAD

**Issue by isoubelet** [SAPDocuments/Tutorials#2822]
Hi @Lsubatin 
Really great and well explained articles, thanks.
Writing you since I am facing a challenge for which I was not able to find a solution on forums: I do need a driver compiled with JDK8 since the app connecting to Hana runs on that version of the virtual machine.
When I tried to use ngdbc.jar, VM said that was compiled with a more resent version (JVM9).

So, question: Is it possible to get older official versions of ngdbc.jar?

Many thanks!

**Comment by Lsubatin** [comment]
Hi @isoubelet ,

Sorry about the late response. This kind of feedback is about tutorials and your question will probably get a better response if asked in answers.sap.com.

You can get the earlier versions from the marketplace, I used "HANA clients" and there they are: https://launchpad.support.sap.com/#/softwarecenter/search/hana%2520client

You may also be able to get them through earlier versions of the Eclipse plugin (aka HANA Studio).

Best, 
Lucia.

**Comment by isoubelet** [comment]
Hi @Lsubatin,
That's great, thanks for answering!

Regards
