### ISSUE TITLE
SAP Image Classification Machine Learning Issue

### ISSUE THREAD

**Issue by AbhiPrama** [SAPDocuments/Tutorials#2824]
How do I display the pictures when I upload a zip file?? The code provided does not allow to display the images.
Also while using upload with XHR when I import multiple images only the first image is displayed. The carousel is not enabled.

**Comment by adadouche** [comment]
Hi @AbhiPrama 

I just released a new version of the tutorial which show how to get the images from a zip.

To make it short you have to use JSZip to uncompress the zip and generate the local blob urls.

here is the URL for reference https://developers.sap.com/tutorials/ml-fs-sapui5-img-classification.html

Have fun
