### ISSUE TITLE
React JS - Add the React JavaScript

### ISSUE THREAD

**Issue by pinakipatrapro** [SAPDocuments/Tutorials#2830]
Hi,
If, i understand correctly react build crunches all the files which really boosts the app performance?
How do we build the react app in webide? 
In future will there be any npm based ui5 library available for react?
BR
Pinaki

**Comment by jonathanbaker7** [comment]
The tutorial was written to show how you could use any of the front-end libraries (Angular, React, UI5) with our new API based ecosystem.  It's not a comprehensive guide to using React in WebIDE.

I don't think you can build React in WebIDE, but you wouldn't do that anyway.  WebIDE is for developing and prototyping.  You should use a Continuous Integration/Deployment (CI/CD) server for both testing and compilation for downstream usage.  

I don't think there are any UI5 libraries that will separate out UI5 components in to React directly.  Several independent authors have created some components that match UI5.  But, UI5 is also a complete framework, which is not compatible with React directly.  So you would only be able to use small parts (like the controls) with React, not the whole thing.  

If you have other questions about using UI5 with React, I suggest going to the SAP Q&A site and asking there.  The UI5 teams can answer those questions in much more detail.
