### ISSUE TITLE
SAPUI5 - Open the SAP Web IDE in SAP Cloud Platform stuck in 0%

### ISSUE THREAD

**Issue by RahmaniKhalil** [SAPDocuments/Tutorials#2833]
Hello,
In the **Create App from Prototype with SAP Web IDE** tutorial, the 2nd step : **SAPUI5 - Open the SAP Web IDE in SAP Cloud Platform** get stuck in 0ù even after I have completed ! Do you have an idea on how to fix this issue ?
regards,
Khalil

**Comment by RahmaniKhalil** [comment]
![screen_issue](https://user-images.githubusercontent.com/25709752/49297656-9f17d100-f4bb-11e8-8527-84ec8fac4fa6.png)

**Comment by thecodester** [comment]
I have fixed the tutorial so you can now track your progress

@jonathanbaker7  I added DONE buttons but you should add a real validation.
