### ISSUE TITLE
SAP Cloud Platform Cloud Connector setup for secure on-premise connectivity

### ISSUE THREAD

**Issue by WilbertKarremans** [SAPDocuments/Tutorials#2834]
I am trying to setup SAP Cloud connector.
The documentation informs me to specify Landscape host, but in my installation of the cloud connector I don't see that field.
Furthermore it is not clear to me what I have to specify in the field Subaccount.

**Comment by JensHaley** [comment]
The UI of the Cloud Connector changed, apologies that this is not yet reflected in this tutorial.

The following tutorial describes how to connect your Cloud Connector with SAP Cloud Platform and with your ABAP system in more detail:
https://developers.sap.com/tutorials/cp-connectivity-create-secure-tunnel.html

We are currently re-organizing the Cloud Connector tutorials and will probably soon remove the one that still refers to an old Cloud Connector version.

**Comment by JensHaley** [comment]
@WilbertKarremans : Did this solve your issue? If so I'd like to close this issue. - Thanks

**Comment by WilbertKarremans** [comment]
Yes, please close it. Many thanks!

Wilbert

**Comment by thecodester** [comment]
@WilbertKarremans For next time, if the issue you opened is resolved, you can close it yourself. Thanks for the feedback.
