### ISSUE TITLE
Installing SAP HANA, express edition Server + Apps, with Docker

### ISSUE THREAD

**Issue by jgoldgh** [SAPDocuments/Tutorials#2835]
On step 7 of the tutorial and in the Docker instructions you've got this line;'

"The hxehost IP address is private to the installation. In order for applications to access hxehost, add the hxehost IP address to your machine’s hostname map. The hostname map is your machine’s /etc/hosts file. You must edit /etc/hosts if you want to access any XS Advanced applications or use HANA Cockpit from your machine."

I'm trying to run this on my local machine. Is the hxehost IP address my local machine's address? I have know idea what address to use.  If you could explain this a bit more that would be helpful.

Thanks

**Comment by songrui01** [comment]
The machine ip wihch docker was installed, such as 
cat /etc/hosts
your_machine_ip hxehost

If you want access XSA applications with windows machines, update file C:\Windows\System32\drivers\etc\hosts also.

**Comment by cocopapagal** [comment]
Hi guys,

the instructions posted on docker site or https://developers.sap.com/tutorials/hxe-ua-install-using-docker-xsa.html
are simply not working. 

For not beeing a linux guy, I have tried it for hours without success.

The result is always **_FAIL: process hdbdaemon HDB Daemon not running_**
Even on forums they are complaining about this 
![2018-12-14 09_52_55-hxa advanced container error](https://user-images.githubusercontent.com/30435440/49993100-21a59380-ff86-11e8-8c46-2fed68d36c9c.png)
and the solution is not very clear
https://answers.sap.com/questions/539188/hxe-server-apps-on-docker-not-able-to-start-contai.html

Would be great if someone would be nice to do a revision of the tutorials.

Have a nice day!

**Comment by songrui01** [comment]
1.  first, This installation does not support Docker for Windows or Docker for Mac.
https://github.com/SAPDocuments/Tutorials/issues/2526#issuecomment-413741610

2 .Fow HXE docker full image: hanaexpressxsa, we recommend the devicemapper storage driver .
https://docs.docker.com/storage/storagedriver/select-storage-driver/#docker-ee-and-cs-engine
https://github.com/SAPDocuments/Tutorials/issues/2234#issuecomment-434910484

**Comment by cocopapagal** [comment]
Thank you for answering me songrui01.

1 - Yes, I am running Docker CE 18.09 on Ubuntu 18.04.1 LTS.

2 - Beeing a rooky in Linux world, took me some time to find out that graphdriver for devicemapper is not anymore supported in Docker 18.09.(Deprecated but missing :) )
[#452](https://github.com/docker/for-linux/issues/452#issue-367208644)
I think that I have to downgrade my Docker in order to solve this.

Thank you




![image](https://user-images.githubusercontent.com/30435440/50081534-08ebe680-01ef-11e9-925f-efc486894833.png)
![image](https://user-images.githubusercontent.com/30435440/50082046-413ff480-01f0-11e9-8461-7340c2d1ee3e.png)

**Comment by JCurrie27** [comment]
Just an update that the engineering team is developing an alternative solution for a storage device, since devicemapper was deprecated. This solution is in the testing phase and should available soon. The Docker tutorial will be updated when the workaround is available.
