### ISSUE TITLE
SAP HANA XS Advanced - Cross-container access

### ISSUE THREAD

**Issue by entmike** [SAPDocuments/Tutorials#2841]
Hello,

I finally was able to work through this and follow the tutorial pretty well.  What I am not clear on is how can I define a `service-name` for the `consumed-db` that may have a different name?  For instance the example in the tutorial uses the build-time service name which would look like `RHOWLES-9skqv35et1oio3vg-SflightExample-hdi_db_sflight` however at deploy time, will be `hdi_db_sflight`.  We develop in a `DEVELOPMENT` space and deploy in a `DEPLOY` space, so I do not think I will have visibility during development to make reference to `hdi_db_sflight`.

Sample YAML of my consuming Project:

```(yaml)
ID: SflightCrossContainerExample
_schema-version: '2.0'
version: 0.0.1

modules:
 - name: db_sflight_cc_example
   type: hdb
   path: db_sflight_cc_example
   requires:
    - name: hdi_db_sflight_cc_example
      properties:
        TARGET_CONTAINER: '~{hdi-container-name}'
    - name: consumed-md-container
      group: SERVICE_REPLACEMENTS
      properties:
        key: consumed-db
        service: '~{consumed-service-name}'

resources:
 - name: hdi_db_sflight_cc_example
   parameters:
      config:
         schema: SFLIGHT_CC_EXAMPLE
   properties:
      hdi-container-name: ${service-name}
   type: com.sap.xs.hdi-container

 - name: consumed-md-container
   type: org.cloudfoundry.existing-service
   parameters:
      service-name: RHOWLES-9skqv35et1oio3vg-SflightExample-hdi_db_sflight
   properties:
      consumed-service-name: '${service-name}'
```

**Comment by entmike** [comment]
Closed.  Got answer.

**Comment by Chathia** [comment]
@entmike Could you please share the answer? I'm also in the similar project scenario., where we need to manually change the "service-name" each time post testing..

**Comment by entmike** [comment]
Hi, @Chathia - Check here: https://answers.sap.com/questions/699133/how-to-change-service-name-at-deploy-time-for-cros.html

**Comment by Chathia** [comment]
@entmike Thank you!!
