### ISSUE TITLE
Explore the Generated App and OData Service

### ISSUE THREAD

**Issue by vsenn** [SAPDocuments/Tutorials#2844]
HI! Screenshots in this tutorial are not available/links broken. Can you please check/fix that?
Best, Valery

**Comment by thecodester** [comment]
Do you mean this one: https://developers.sap.com/tutorials/fiori-ios-scpms-teched18-03.html ? I see the images for this one.

**Comment by vsenn** [comment]
Yes, iPhone XR screens loaded now. Don't know what was the issue. Let's close it.
