### ISSUE TITLE
Call IoT Application Enablement service APIs with Postman

### ISSUE THREAD

**Issue by ebenavides** [SAPDocuments/Tutorials#2846]
Hi,
Can't log on!
Login onto https://sap-iotaehandson2.iot-sap.cfapps.eu10.hana.ondemand.com/appcore-conf/Configuration with credentials provided in first tutorials. 
Error message says: "Sorry, we could not authenticate you. Try again."

**Comment by thecodester** [comment]
@banurekhabalaji Can you help here?

**Comment by ebenavides** [comment]
User: P002365
Thank you, I'll be waiting for your assistance.
