### ISSUE TITLE
Call IoT Application Enablement service APIs with Postman

### ISSUE THREAD

**Issue by Murixum1102** [SAPDocuments/Tutorials#2848]
Hello, I was following this tutorial.

Is the x-csrf-token fetch, still valid? I get no response on Postman. Thank you.

**Comment by thecodester** [comment]
@banurekhabalaji Can you help here?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
