### ISSUE TITLE
Continuous Integration (CI) Best Practices with SAP – Pipeline Suggestions

### ISSUE THREAD

**Issue by binpath** [SAPDocuments/Tutorials#2853]
Hi, 
Images are down in the site.
[ci-best-practices-pipelines](https://developers.sap.com/mena-ar/tutorials/ci-best-practices-pipelines.html)

**Comment by thecodester** [comment]
Thanks for letting us know. We're working on it ...

**Comment by thecodester** [comment]
The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
