### ISSUE TITLE
Install the Optional SAP HANA Interactive Education Package for SAP HANA, express edition

### ISSUE THREAD

**Issue by bcschaich** [SAPDocuments/Tutorials#2858]
Horrible experience. Installed it and now? What do you think what a customer does with this? Drop the whole thing!

**Comment by Lsubatin** [comment]
Can you please clarify what the feedback is about? The experience of installing SHINE was horrible and/or you are wondering what to do with SHINE?

**Comment by Lsubatin** [comment]
No response and no productive feedback we can extract form this. Closing this.
