### ISSUE TITLE
Optional SAP HANA Smart Data Integration Package for SAP HANA, express edition

### ISSUE THREAD

**Issue by r3ptar** [SAPDocuments/Tutorials#2862]
I recieve this error when trying to download the package

> HXEDownloadManager_linux.bin linuxx86_64 vm sdi.tgz
> which: no java in (/usr/sap/HXE/HDB90/exe/krb5/bin:/usr/sap/HXE/HDB90/exe/krb5/sbin:/usr/sap/HXE/HDB90/hxehost:/usr/sap/HXE/HDB90:/usr/sap/HXE/HDB90/exe:/usr/sap/HXE/HDB90/exe/mdc:/usr/sap/HXE/HDB90/exe/Python/bin:/usr/sap/HXE/HDB90/exe/dat_bin_dir:/usr/sap/HXE/home:/usr/sap/HXE/home/bin:/usr/local/bin:/usr/bin:/bin:/usr/games)
> Select HANA, express edition version 2.00.033.00.20180925.2 ...
> Connecting to download server...
> Cannot connect to download server to get the options.  Check your Internet connection or specify proxy server with --ph and --pp options.

Does the express edition not come with java installed? I've checked my firewall and I'm not blocking any traffic from the server

**Comment by JCurrie27** [comment]
The Download Manager requires JRE 8 or higher. Please see the software/hardware requirements in the [Pre-Installation Tasks](https://developers.sap.com/tutorials/hxe-ua-installing-vm-image.html) tutorial.

**Comment by r3ptar** [comment]
So just to confirm. Java is not included in the VM out of the box? How am I suppose to get the installer to the server? Using ftp?

**Comment by r3ptar** [comment]
Yes that's the tutorial I am using and I am receiving that error message after running the command ssh'd into my VM. That's why I'm so confused because it's so early into the instructions to be having problems

**Comment by lin1161** [comment]
Hi r3ptar, 
"which: no java in (/usr/sap/HXE/HDB90/exe/krb5/bin:/usr/sap/HXE/HDB90/exe/krb5/sbin:/usr/sap/HXE/HDB90/hxehost:/usr/sap/HXE/HDB90:/usr/sap/HXE/HDB90/exe:/usr/sap/HXE/HDB90/exe/mdc:/usr/sap/HXE/HDB90/exe/Python/bin:/usr/sap/HXE/HDB90/exe/dat_bin_dir:/usr/sap/HXE/home:/usr/sap/HXE/home/bin:/usr/local/bin:/usr/bin:/bin:/usr/games)"
This message is just a warning, you can ignore it.
The real issue should be your VM can not connect to the download server, Please check your VM internet access. 
You can specify the proxy server host and port like "HXEDownloadManager_linux.bin linuxx86_64 vm sdi.tgz --ph proxy.domain --pp proxy.port"  [replace the proxy.domain to your proxy server name, and proxy.port to your proxy port]

**Comment by r3ptar** [comment]
I can ping outside, but nothing seems to be resolving with DNS. Is there a way reconfigure DNS or is the server not suppose to hostnames?

**Comment by r3ptar** [comment]
We can close this out. My coworker is an idiot and didn't configure a default gateway or DNS settings.

**Comment by MayankTuteja** [comment]
Hi r3ptar,
I am facing exact the same issue while downloading sdi.tgz inside vm.
Could you please guide me with the gateway configuration and DNS settings.
Thanks in advance.
