### ISSUE TITLE
Creating basic/interface views in Open Core Data Services

### ISSUE THREAD

**Issue by petrosy** [SAPDocuments/Tutorials#2864]
Please provide more comments on why you select the CDS annotations you do. Otherwise its nice and concise

**Comment by thecodester** [comment]
@D037411 Jerome, can respond to this issue?

**Comment by D037411** [comment]
Dear Petrosy, could you please  kindly provide us with  more  information such as the annotation you are refering to and what you would explicitly love to know.
Best regards
Jérôme Monteu Nana

**Comment by petrosy** [comment]
Hi Jérôme,

Thanks for taking an interest. I guess as this is all very new to me .. I was kind of interested on why one chooses the annotation one does over another when setting up ones CDS component. I guess there are things that are clearly obvious once you know but until then some of it is a bit vague... It's been a while so I have forgotten what I was originally interested in. 

Sorry for the my vague response...

Regards
Petros
