### ISSUE TITLE
Take a Tour of the SAP Cloud Platform Cockpit

### ISSUE THREAD

**Issue by Sygyzmundovych** [SAPDocuments/Tutorials#2877]
Hi Jonathan. IoT Service is not available on Neo anymore. May I suggest using another service as an example in Step 7? Thanks!

**Comment by thecodester** [comment]
@jonathanbaker7 Can you update tutorial?

**Comment by rbrainey** [comment]
Assigning this to Max to update the screenshots and copy referencing IOT in what is currently Step 7.

**Comment by maxstreifeneder** [comment]
Will rework the tutorial early next week

**Comment by thecodester** [comment]
@maxstreifeneder Any updates?

**Comment by IObert** [comment]
replaced it with the workflow service
