### ISSUE TITLE
Enable SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by Sygyzmundovych** [SAPDocuments/Tutorials#2878]
Validation in step 4 expects / at the end of the URL, while URL copied from the web browser by default does not have /

Manually adding / at the end of copied URL allowed to pass validation.

Thanks!

https://developers.sap.com/tutorials/webide-multi-cloud.html

**Comment by thecodester** [comment]
@jonathanbaker7 Can you update tutorial?

**Comment by jonathanbaker7** [comment]
Updated the rules.vr file.
