### ISSUE TITLE
Create a low-fidelity SAP Build prototype

### ISSUE THREAD

**Issue by Sygyzmundovych** [SAPDocuments/Tutorials#2881]
In https://developers.sap.com/tutorials/build-low-fi-prototype.html screens and workflow are different now.

Plus lists are not rendered properly in built tutorial.

**Comment by thecodester** [comment]
@rbrainey Who can handle the Build tutorials?

@Sygyzmundovych What lists?

**Comment by Sygyzmundovych** [comment]
Lists are rendered properly now.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
