### ISSUE TITLE
Import your SAP Build project into SAP Web IDE

### ISSUE THREAD

**Issue by Sygyzmundovych** [SAPDocuments/Tutorials#2882]
In https://developers.sap.com/tutorials/build-import-webide.html the old Web IDE is being used. 

As well workflow and screenshots are outdated, i.e. BUILD plugin is now activated from Features and there is no "repository" drop down to select from.

Seems like destinations should not be created manually anymore, as now they are created automatically (https://help.sap.com/viewer/2c656257ea5740328a299638fb65975b/CF/en-US/4be99e779fcb4ff9a8e5179b74bd72cc.html)

**Comment by rbrainey** [comment]
Fixed these issues, although I had to contact the BUILD team, as there's a permissions problem with the link to the SAP Employee instructions for resetting a BUILD password.

**Comment by thecodester** [comment]
@rbrainey Is this resolved? If so can you close?

**Comment by rbrainey** [comment]
I'm good with it if you are.
