### ISSUE TITLE
Wrong Screenshot in  HXE Server - Time Series Forecasting Page... (Forecast SQL)

### ISSUE THREAD

**Issue by msj2** [SAPDocuments/Tutorials#2886]
https://developers.sap.com/tutorials/hxe-aa-forecast-sql-01/_jcr_content.github-proxy.1544109201.file/03-1.png

The same image is re-used for connecting to HXE DB as SYSTEM user & ML_USER 

This Image has wrong radio button chosen.
It MUST HAVE Tenant Database selected
IT IS HAVING System Database selected

Kindly fix this asap.

**Comment by adadouche** [comment]
Thanks for your feedback. Fixed in the following [commit](https://github.com/SAPDocuments/Tutorials/commit/6ee4993dda8b3057e0e7f6f40daee8be862c8892)

However, the explanation is still the one you should consider as screenshots are here for illustration purpose only.
