### ISSUE TITLE
What port number is used by the nameserver link not working (Forecast SQL)

### ISSUE THREAD

**Issue by msj2** [SAPDocuments/Tutorials#2887]
https://developers.sap.com/tutorials/hxe-aa-forecast-sql-01.html

What port number is used by the nameserver?

I enter the value 39001 & Click on Submit Button
Submit Button has a hash link.

Doesn't work.

A bit embarrassing to mention, each Submit button on this page is a # link.

**Comment by adadouche** [comment]
Hi @msj2 

The value entered is correct. But I don't understand your ***hash*** link issue.

I know the validation has hiccups time to times when a new release is pushed to prod.

Have you been able to submit your answer?

**Comment by adadouche** [comment]
Hi @msj2 

We haven't heard from you, so will close this issue. But feel free to reopen or open a new one if needed.
