### ISSUE TITLE
Install the Optional SAP HANA Automated Predictive Library Package for SAP HANA, express edition (Native Linux Machine)

### ISSUE THREAD

**Issue by krisho007** [SAPDocuments/Tutorials#2888]
Several issues with this tutorial.
1. Commands to be entered are not easily copyable. Does not indicate that they are the commands to be entered like other commands
2. This step also requires sudo rights. But that is not documented.

**Comment by JCurrie27** [comment]
Assigning to aptk001 and TerryNing for investigation.

**Comment by TerryNing** [comment]
hi, @krisho007 , what's web link for the original page that you saw there have issue?

**Comment by adadouche** [comment]
Hi @TerryNing 

I think this the following tutorial: 

https://developers.sap.com/tutorials/hxe-ua-apl-binary.html

But I think the content should also be aligned with the following:

https://developers.sap.com/tutorials/hxe-ua-apl-vm.html

as there is no real reason they should differ (unless there is one, but then it should be documented)

Regards

**Comment by thecodester** [comment]
@TerryNing Any updates on this?

**Comment by TerryNing** [comment]
I saw there's a 'Copy' button on the page, which indicated it's command to execute. 

Yes, it also requires sudo rights. The error message would be straightforward that user become aware.  Anyway, @JCurrie27, would you make that change ?

**Comment by JCurrie27** [comment]
@aptk001 - Could you please update the binary APL tutorial per Terry's request above?

**Comment by thecodester** [comment]
@aptk001 Has this been completed? Can we close?
