### ISSUE TITLE
Install the Optional SAP HANA Automated Predictive Library Package for SAP HANA, express edition (Native Linux Machine)

### ISSUE THREAD

**Issue by vishnucta** [SAPDocuments/Tutorials#2889]
1) Commands are not formatted properly . It should be
./HXEDownloadManager_linux.bin linuxx86_64 installer apl.tgz

2) Its getting downloaded in /Downloads

3)No sudo access to GCP hxeadm user

**Comment by JCurrie27** [comment]
Assigning to aptk001 and TerryNing for investigation.

**Comment by Terry1504** [comment]
@vishnucta 

about "Commands are not formatted properly", what's link for the original desc link that's not correct?

**Comment by TerryNing** [comment]
hi, @vishnucta, what's web link for the original description that's not correct?

**Comment by adadouche** [comment]
Hi @TerryNing

I think this the following tutorial:

https://developers.sap.com/tutorials/hxe-ua-apl-binary.html

But I think the content should also be aligned with the following:

https://developers.sap.com/tutorials/hxe-ua-apl-vm.html

as there is no real reason they should differ (unless there is one, but then it should be documented)

In the GCP context, the hxeadm user is not part of the sudoer group and nowhere we explain that sudo/root is required to run the install_apl.sh script.

Regards

**Comment by thecodester** [comment]
@TerryNing any update?

**Comment by aptk001** [comment]
We've updated the tutorial to include sudo in the install command
