### ISSUE TITLE
Import the Time series datasets (Forecast SQL) -Low Prio

### ISSUE THREAD

**Issue by msj2** [SAPDocuments/Tutorials#2891]
Step 4: Import the Dataset

8 files to download
7 file to map

`KxDesc_CashFlows` is not needed OR
SQL Query in Step 3 to create DB Table for it is missing.

**Comment by adadouche** [comment]
Hi @msj2 

Thanks for your feedback, I have removed the KxDesc_CashFlows download as it is not used in my examples.
[Commit](https://github.com/SAPDocuments/Tutorials/commit/55774fa839488936eaaedf8f149ee4455c532bf4)

Regards
