### ISSUE TITLE
HANA xsc not working

### ISSUE THREAD

**Issue by vinita-k** [SAPDocuments/Tutorials#2894]
Please note below screenshot I have the HANA express installed in the VM (I believe)

However unable to start XS engine and webide from browser please advise

And this is what I see when I login and I am able to login using hxeadm

![vm screenshots1](https://user-images.githubusercontent.com/23621930/50045970-d06ddf00-0100-11e9-937c-1b2a0c6ba335.PNG)

However when I try to run hana XSC command as seen in the link below Step 1 it shows nothing

https://developers.sap.com/australia/tutorials/hxe-ua-test-vm-xsa.html

![xsc not working](https://user-images.githubusercontent.com/23621930/50045972-d794ed00-0100-11e9-952a-72be503191eb.PNG)

Same issue with webide it shows app started but I am unable to login from browser:
![webide started](https://user-images.githubusercontent.com/23621930/50045975-dc59a100-0100-11e9-81e3-3272a97bfffc.PNG)
![webide browser not working](https://user-images.githubusercontent.com/23621930/50045974-dc59a100-0100-11e9-903c-a6b7a655116b.PNG)

**Comment by adadouche** [comment]
Hi @vinita-k 

In HXE 2.0, the XS Classic feature is disabled (and may be gone completely). 
Therefore, port 8090 is not used anymore.

You should use port 39030 (3<instance number>30) to check that your server is up and running.
However, it doesn't mean that all the other service like the Web IDE are up and running too.

But anyway, in order to use **hxehost** in your URLs from a remote host, you need to update your remote host file as documented in: 

https://developers.sap.com/tutorials/hxe-ua-hosts.html

For sure ***Step 1: Test XSC*** should be removed from:

https://developers.sap.com/tutorials/hxe-ua-test-vm-xsa.html

along with the same details from the help:

https://help.sap.com/viewer/8c3bbc4a904d42efac77c09da0bccf64/2.0.03/en-US/0377017816dc46b09db7b2e13bfabc0a.html

Regards

**Comment by lin1161** [comment]
Hi @vinita-k,

For your first screenshot, all apps that the requested state is "STARTED", should have 1/1 instances, then you can connect to that app. ( 1/1 means 1 instance is started, 0/1 means no instance is started).
For webide can not be connected issue, please make sure you modified the host file to add the hxehost info like:
[vm_ip] hxehost.localdomain hxehost

**Comment by lin1161** [comment]
Modify the etc hosts file on the client machine that you use browser to logon webide. if you use windows, the etc hosts should be C:\Windows\System32\drivers\etc\hosts.
And make sure the network access between the hxe VM and the client machine is OK.

**Comment by vinita-k** [comment]
> Hi @vinita-k
> 
> In HXE 2.0, the XS Classic feature is disabled (and may be gone completely).
> Therefore, port 8090 is not used anymore.
> 
> You should use port 39030 (330) to check that your server is up and running.
> However, it doesn't mean that all the other service like the Web IDE are up and running too.
> 
> But anyway, in order to use **hxehost** in your URLs from a remote host, you need to update your remote host file as documented in:
> 
> https://developers.sap.com/tutorials/hxe-ua-hosts.html
> 
> For sure _**Step 1: Test XSC**_ should be removed from:
> 
> https://developers.sap.com/tutorials/hxe-ua-test-vm-xsa.html
> 
> along with the same details from the help:
> 
> https://help.sap.com/viewer/8c3bbc4a904d42efac77c09da0bccf64/2.0.03/en-US/0377017816dc46b09db7b2e13bfabc0a.html
> 
> Regards

Hey @adadouche 
I checked the link you shared and I understand now I dont have to check for XSC  but only XSA?
So when I login I get below when I do xs-admin-login
![image](https://user-images.githubusercontent.com/23621930/50199888-3b950b00-03b8-11e9-87b0-89b0373fbb9d.png)

My host file is updated as below 
![image](https://user-images.githubusercontent.com/23621930/50199911-5798ac80-03b8-11e9-96f3-2aa805cc0992.png)

now I try to check XSA on browser and it still shows an error 
![image](https://user-images.githubusercontent.com/23621930/50199953-8c0c6880-03b8-11e9-85bf-541e95379115.png)

Then I start for step 4 which is check Webide and it shows running instance 1/1 and started
![image](https://user-images.githubusercontent.com/23621930/50199973-a6dedd00-03b8-11e9-9c7d-e5f286b2f401.png)

Now I again check in browser and webide does not start as well 
![image](https://user-images.githubusercontent.com/23621930/50199999-d1309a80-03b8-11e9-9085-871c8bb5e67d.png)


What could be the reason that it still does not work?
Note that during the inital setup I actually used the default time zone and did not change would that be an issue? Do I need to change it now and how?

Thanks a lot for your help ! 

Regards
Vinita

**Comment by vinita-k** [comment]
> Modify the etc hosts file on the client machine that you use browser to logon webide. if you use windows, the etc hosts should be C:\Windows\System32\drivers\etc\hosts.
> And make sure the network access between the hxe VM and the client machine is OK.

Thanks that is updated! 

Regards
Vinita

**Comment by lin1161** [comment]
Hello Vinita,

From the screenshot, your HXE VM IP should be *.*.*.*71 (you removed the front part, but I can see it ends with 71). And the etc hosts you showed, the IP address is 172.25.86.13. 
Maybe this is the issue?

**Comment by vinita-k** [comment]
> Hello Vinita,
> 
> From the screenshot, your HXE VM IP should be _._.*.*71 (you removed the front part, but I can see it ends with 71). And the etc hosts you showed, the IP address is 172.25.86.13.
> Maybe this is the issue?

Hey @lin1161  
I see what you mean I have corrected the host IP in the file now 
![image](https://user-images.githubusercontent.com/23621930/50203309-ef50c780-03c5-11e9-8329-4ed812b94182.png)

Still the same 
![image](https://user-images.githubusercontent.com/23621930/50203326-ff68a700-03c5-11e9-98e9-7bb88c3bbfb8.png)





regards
Vinita

**Comment by lin1161** [comment]
Hello Vinita,
Please double check the following items:
1. the network access is OK between the client machine ( which you used to browner webide )  and the HXE VM.
2. modify the hosts file on client machine add the one line "[vm_ip] hxehost.localdomain hxehost", don't forget to save the file.
3. restart the browner and try again. (or try on Chrome?)

**Comment by adadouche** [comment]
Hi @vinita-k 


To check if the host file is properly configured, open a command prompt and run:

```
ping hxehost
```

The output should display the IP address resolved. You may receive also messages saying that the host cannot be resolved but this may not be relevant because ping is not always enabled on host.
 
To check that you can access your hxehost, open a command prompt and run:

```
telnet hxehost 39030
```

This should return a black screen, and if not then you have a firewall/proxy configuration issue.

You can easily enable telnet from the Windows Features.

Another quick one to test, have you tried using the IP address instead of the hxehost in the URL for https://<IP>:39030 in your browser?

If this is not working then you are definitely having a firewall/proxy issue.

Then you will need to try disabling your firewall or proxy (using an internet connection that doesn't require one).

Regards

**Comment by vinita-k** [comment]
> Hi @vinita-k
> 
> To check if the host file is properly configured, open a command prompt and run:
> 
> ```
> ping hxehost
> ```
> The output should display the IP address resolved. You may receive also messages saying that the request timed out but this may not be relevant because ping is not always enabled on host.
> 
> ```
> C:\>ping hxehost
> 
> Pinging hxehost [192.168.1.71] with 32 bytes of data:
> Request timed out.
> Request timed out.
> Request timed out.
> Request timed out.
> 
> Ping statistics for 192.168.1.71:
>     Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
> ```
> To check that you can access your hxehost, open a command prompt and run:
> 
> ```
> telnet hxehost 39030
> ```
> This should return a black screen, and if not and you receive the following then you have a firewall/proxy configuration issue.
> 
> ```
> C:\>telnet hxehost 39030
> Connecting To hxehost...Could not open connection to the host, on port 39030: Connect failed
> ```
> You can easily enable telnet from the Windows Features.
> 
> Another quick one to test, have you tried using the IP address instead of the hxehost in the URL for in your browser?
> 
> ```
> https://<IP>:39030
> ```
> If this is not working then you are definitely having a firewall/proxy issue.
> 
> Then you will need to try disabling your firewall or proxy (using an internet connection that doesn't require one).
> 
> Regards

Hey @adadouche 
Firstly thanks a lot for helping me with this it is also so new and I am getting very confused 
So, now I did a ping and it shows exactly what you mentioned time out but request packet is sent and received 
![image](https://user-images.githubusercontent.com/23621930/50273373-6017e280-049f-11e9-841f-b2ca1213c18a.png)

if I understand correctly I need to run this in host system right?
I tried to first run as below in my host system but it doesnt connect even after 10 mins 
![image](https://user-images.githubusercontent.com/23621930/50273819-91dd7900-04a0-11e9-80be-70dc9cc18bce.png)

Then I tried in VM and it says connected 

![image](https://user-images.githubusercontent.com/23621930/50273854-aae62a00-04a0-11e9-8a2c-0f544ad60ecd.png)

Would you please advise if I cant open in the host system?
I wanted to check the webide tool which is the https://192.168.1.71:53075/
This also does not work 
![image](https://user-images.githubusercontent.com/23621930/50274114-4081b980-04a1-11e9-881d-3af6d50e6a69.png)


I have disabled firwall in my system and I am trying from a home network so should not be that issue?

PLease let me know if you  find time!
Thanks so much! 

Regards
Vinita

**Comment by adadouche** [comment]
Hi @vinita-k 

This is really strange.

Let's go back to the beginning for second and correct me if I'm wrong:
 - you are using the HXE VM (server + apps)
 - you are using VMWare to run it
 - you are using the initial network configuration provided with the VM (bridged)

Can you confirm that?

**Comment by vinita-k** [comment]
> Hi @vinita-k
> 
> This is really strange.
> 
> Let's go back to the beginning for second and correct me if I'm wrong:
> 
> * you are using the HXE VM (server + apps)
> * you are using VMWare to run it
> * you are using the initial network configuration provided with the VM (bridged)
> 
> Can you confirm that?

HI @adadouche 
I am using the below link to download hana express engine 
https://www.sap.com/cmp/ft/crm-xu16-dat-hddedft/index.html

With this there was a getting started guide which I followed
I am using VMWare Workstation 15 player to open hxexsa OVA file in my virtual machine
THe only configuration part I have missed is time zone as I selected the default value and dont know how to change it should that matter?

Does that answer your question?

Thanks a lot for your help 

Regards
Vinita

**Comment by Lsubatin** [comment]
Hi Vinita, 
Can switch the network to NAT, wait a minute get the IP from the VM and pinging it from your laptop?

Can you also try traceroute using NAT and share the results?

Cheers,

Lucia.

**Comment by vinita-k** [comment]
> Hi Vinita,
> Can switch the network to NAT, wait a minute get the IP from the VM and pinging it from your laptop?
> 
> Can you also try traceroute using NAT and share the results?
> 
> Cheers,
> 
> Lucia.

Hey 
Sorry I am probably quite new to this what is NAT I tried to google but not sure if i need to download something to send you the traceroute using NAT could you explain a bit more

Regards
Vinita

**Comment by adadouche** [comment]
Hi @vinita-k 

First let me share a few information about network configuration and virtual machines.

When using the "bridge" mode, your VM will appear like a standalone machine on your network.
This implies a few things:
 - the ip address will be provided by the network your host machine is connected on
 - if your host machine network use a proxy or filter on mac address etc then your vm machine will also be impacted by that
 - if you have no network, you won't be able to reach it as the vm will have no network to connect
 - if you switch network, the VM ip address will change

When using the "host only" mode:
 - only your host machine will be able to connect to the VM
 - the VM will not have access to the internet (if available)
 - the VM will be provided an ip address even if your host machine is not connected to a network (it will use a virtual network setup by VMWare)
 - the ip address of the VM should not change, even when your host machine switch network

When using the "NAT" (Network Address Translation) mode:
 - the VM will have access to the internet (if available)
 - the VM will be provided an ip address even if your host machine is not connected to a network (it will use a virtual network setup by VMWare)
 - the ip address of the VM should not change, even when your host machine switch network
 - anyone could access your VM, as long as you configure the address translation

So, from my pov, NAT is probably the best mode to be used in this context.

When you open VMWare, select your VM then click on **Edit virtual machine settings**:

![image](https://user-images.githubusercontent.com/1446764/50395631-971f1a00-0765-11e9-8e4c-f4575ecc0705.png)

Then choose **Network adapter** on the left side list, then select NAT:

![image](https://user-images.githubusercontent.com/1446764/50395657-c170d780-0765-11e9-92ac-b7d2c6e47361.png)

Click on **OK**.

If you VM is already running, you will need to wait for the change to take effect. If not, just click on **Play virtual machine**.

Then from the VM console, execute the following command (after login in as **hxeadm**):

```
sudo ifconfig
```

![image](https://user-images.githubusercontent.com/1446764/50395796-77d4bc80-0766-11e9-9d94-76db84726584.png)

You can now use  the address marked with the big red 1 which  is starting with 192.168. (FYI: The VM address will remain the same until the MAC address, but I hope you won't have to do that)

The IP address displayed before the login prompt (marked with the big red 2), is not always accurate, so don't use this one.

Now, from your host machine machine, you can update your hosts file (located in C:\Windows\system32\drivers\etc).

And you should be all set

Let us know if this helped.

**Comment by JCurrie27** [comment]
Hi @vinita-k: Was the NAT/bridged information above helpful to you? Are you still experiencing problems?

**Comment by vinita-k** [comment]
> Hi @vinita-k
> 
> First let me share a few information about network configuration and virtual machines.
> 
> When using the "bridge" mode, your VM will appear like a standalone machine on your network.
> This implies a few things:
> 
> * the ip address will be provided by the network your host machine is connected on
> * if your host machine network use a proxy or filter on mac address etc then your vm machine will also be impacted by that
> * if you have no network, you won't be able to reach it as the vm will have no network to connect
> * if you switch network, the VM ip address will change
> 
> When using the "host only" mode:
> 
> * only your host machine will be able to connect to the VM
> * the VM will not have access to the internet (if available)
> * the VM will be provided an ip address even if your host machine is not connected to a network (it will use a virtual network setup by VMWare)
> * the ip address of the VM should not change, even when your host machine switch network
> 
> When using the "NAT" (Network Address Translation) mode:
> 
> * the VM will have access to the internet (if available)
> * the VM will be provided an ip address even if your host machine is not connected to a network (it will use a virtual network setup by VMWare)
> * the ip address of the VM should not change, even when your host machine switch network
> * anyone could access your VM, as long as you configure the address translation
> 
> So, from my pov, NAT is probably the best mode to be used in this context.
> 
> When you open VMWare, select your VM then click on **Edit virtual machine settings**:
> 
> ![image](https://user-images.githubusercontent.com/1446764/50395631-971f1a00-0765-11e9-8e4c-f4575ecc0705.png)
> 
> Then choose **Network adapter** on the left side list, then select NAT:
> 
> ![image](https://user-images.githubusercontent.com/1446764/50395657-c170d780-0765-11e9-92ac-b7d2c6e47361.png)
> 
> Click on **OK**.
> 
> If you VM is already running, you will need to wait for the change to take effect. If not, just click on **Play virtual machine**.
> 
> Then from the VM console, execute the following command (after login in as **hxeadm**):
> 
> ```
> sudo ifconfig
> ```
> ![image](https://user-images.githubusercontent.com/1446764/50395796-77d4bc80-0766-11e9-9d94-76db84726584.png)
> 
> You can now use the address marked with the **big red 1** which is starting with 192.168. (FYI: The VM address will remain the same until the MAC address, but I hope you won't have to do that)
> 
> The IP address displayed before the login prompt (marked with the big red 2), is not always accurate, so don't use this one.
> 
> Now, from your host machine machine, you can update your hosts file (located in C:\Windows\system32\drivers\etc).
> 
> And you should be all set
> 
> Let us know if this helped.

HI There
Thanks a lot for your response
It has not been resolved and is quote frustrating
I have tried to use the NAT settings as well as bridge but still unable to run Webide or any of the tests mentioned in the link as successful 
Issue 1: hxehost:53075 does not run still 

![image](https://user-images.githubusercontent.com/23621930/52173237-547d4280-27e5-11e9-9994-51db76c66261.png)


Issue 2 VM keeps asking to reinstall again as below. I have got the install confirmation message already but every time I login it asks me to setup the configuration again 
![image](https://user-images.githubusercontent.com/23621930/52173227-1a13a580-27e5-11e9-899e-4ff8317cfc09.png)


This is even though I have got the confirmation last time I worked on the VM 
![image](https://user-images.githubusercontent.com/23621930/52173232-37e10a80-27e5-11e9-8dac-00de4bd0bad6.png)


Pl advise issue 2 is more important to resolve than issue 1 it seems to me now 

Thanks for your support and sorry to bother 


Regards
Vinita

**Comment by Lsubatin** [comment]
Took this to where it belongs: https://answers.sap.com/questions/745374/hana-express-edition-installation-issues-and-askin.html
