### ISSUE TITLE
Add a UI to Your Business Application

### ISSUE THREAD

**Issue by mikeedoyle** [SAPDocuments/Tutorials#2896]
When I turn on the mock data options in the run configuration my app no longer loads.  I see the tile but when I click it I just get a blank screen

**Comment by Apfohlmann** [comment]
I run in the same error. After reinstalling the builder I was able to complete the tutorial.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
