### ISSUE TITLE
Change from a mock server to live OData service for TechEd

### ISSUE THREAD

**Issue by kavishdahekar** [SAPDocuments/Tutorials#2898]
Step 6 : "Change the word ToysSet to Sets in line 18."
Line number is wrong. Should be line 11.

**Comment by qmacro** [comment]
https://developers.sap.com/tutorials/pre-teched-2018-webide-odata.html

**Comment by qmacro** [comment]
Thanks for reporting this @kavishdahekar

**Comment by kavishdahekar** [comment]
You're welcome @qmacro :)
