### ISSUE TITLE
Build an SAP Fiori app with SAP Gateway data in SAP Web IDE

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#2899]
The tutorial was great until I got to the last steps and basically the app did not work. I lodged in Twitter and found I had to amend the neo-app.json file. 

**From this:**

}, {
		"path": "/ES5",
		"target": {
			"type": "destination",
			"name": "ES5",
		},
		"description": "ES5"

**To this:**
}, {
		"path": "/sap/opu/odata",
		"target": {
			"type": "destination",
			"name": "ES5",
			"entryPath": "/sap/opu/odata"
		},
		"description": "ES5"

Additionally, once the app ran successfully the string I had to enter for AVANTEL did not work. I had to enter the string below Hermosillo and I did this however it kept reporting it was invalid. 

Great tutorial however this is not currently working as is so would be great if this could be corrected, especially since I cannot complete this now.

**Comment by cdzmcameron** [comment]
Thanks pjcools, I was trying to follow the same tutorial but couldn't get it to work at the end.  Your solution worked for me.

**Comment by qmacro** [comment]
PR merged, issue fixed. Thanks for raising this, @pjcools .
