### ISSUE TITLE
SAP HANA, express edition, in Google Cloud Platform Launcher (Database + XS Advanced)

### ISSUE THREAD

**Issue by ireps** [SAPDocuments/Tutorials#2905]
https://developers.sap.com/tutorials/hxe-gcp-getting-started-launcher-xsa.html

Tutorial does not have completion marker for Steps 3 and 4

**Comment by thecodester** [comment]
WHat do you mean "completion marker"?

**Comment by thecodester** [comment]
I see a Done button at the end of each of the 5 steps ... do they not work?

**Comment by Lsubatin** [comment]
There was a rendering problem. They work now. Thanks!
