### ISSUE TITLE
Authenticate once and share data between multiple application

### ISSUE THREAD

**Issue by mahabaleshwarhnr** [SAPDocuments/Tutorials#2908]
I tried this tutorial. But shared logon is not working in v3.1 SDK.  I am getting passcode mismatch error.
[https://imgur.com/a/4u2NhOi](url)

**Comment by KevinMuessig** [comment]
Hi @mahabaleshwarhnr ,

do you have the tutorial link of the tutorial you're trying to go through? I will look into this.

Thanks,

Kevin

**Comment by mahabaleshwarhnr** [comment]
@KevinMuessig   https://developers.sap.com/india/tutorials/fiori-ios-scpms-shared-keystore.html

**Comment by KevinMuessig** [comment]
@mahabaleshwarhnr I will look into this.

**Comment by KevinMuessig** [comment]
@mahabaleshwarhnr This tutorial is outdated, there have been changes in the Onboarding Flows with version 3.1 of the SDK. There will be a new release anytime soon with more major changes to the Onboarding. We're currently working on updating all the tutorials to the newest version.
Excuse the inconvenience, but I would like you to wait until we've completed the update process of the tutorials before continuing with the tutorial.

**Comment by mahabaleshwarhnr** [comment]
Thanks for the reply. Please let me know when can i expect this tutorial.

**Comment by KevinMuessig** [comment]
Hi @mahabaleshwarhnr,

I am in the middle of updating them but it will take a little bit. I will prioritize the tutorial you were trying to do.

Thank you

**Comment by mahabaleshwarhnr** [comment]
@KevinMuessig  any update on issue?

**Comment by KevinMuessig** [comment]
Hi @mahabaleshwarhnr ,

we decided to remove this tutorial because this is not SAP specific. I just have sent out an email to our SDK team so they can take a look.

Thank you
