### ISSUE TITLE
SAP HANA XS Advanced - Consume the OData service in a basic HTML5 module

### ISSUE THREAD

**Issue by simonefix** [SAPDocuments/Tutorials#2909]
This doesn't work... when I follow the tutorial as soon as I get here i receive the error:

message: "HTTP request failed"
request: {headers: {…}, requestUri: "/xsodata/purchaseOrder.xsodata/$metadata", method: "GET", user: undefined, password: undefined, …}
response: {requestUri: "/xsodata/purchaseOrder.xsodata/$metadata", statusCode: 404, statusText: "", headers: Array(0), body: "<html><head><title>Error report</title></head><bod…h1>HTTP Status 404 - Not Found</h1></body></html>"}
responseText: "<html><head><title>Error report</title></head><body><h1>HTTP Status 404 - Not Found</h1></body></html>"
statusCode: 404
statusText: ""

I am using WebIde in Canary because I can't make this work on HANA Express because can't build .

thanks

**Comment by Lsubatin** [comment]
Different error (after this one) received by email.
