### ISSUE TITLE
Change from a mock server to live OData service for TechEd

### ISSUE THREAD

**Issue by jasonmuzzy** [SAPDocuments/Tutorials#2910]
The answer for step 5 seems to have changed format.  The actual element in WebIDE is "<NavigationProperty Name="Parts" ToRole="PartsDependent" FromRole="SetsPrincipal" Relationship="codejam.toyspace.services.api.PartOfType"/>" but I had to reorder the attributes to get the answer accepted to "<NavigationProperty Name="Parts" Relationship="codejam.toyspace.services.api.PartOfType" FromRole="SetsPrincipal" ToRole="PartsDependent"/>".

**Comment by thecodester** [comment]
This tutorial has been removed.
