### ISSUE TITLE
C++ compilation of rule ‘//tensorflow_serving/model_servers:http_rest_api_handler_test’ failed (Exit 1) tensorflow_serving/model_servers/http_rest_api_handler_test.cc:380:36: error: unterminated raw string

### ISSUE THREAD

**Issue by nachorubio** [SAPDocuments/Tutorials#2918]
Hi,

I’m having a problem during Tensorflow Model Server compilation, seems i have a problem with my gcc version (4.5.8) and the TF version, i’m getting this error:

C++ compilation of rule ‘//tensorflow_serving/model_servers:http_rest_api_handler_test’ failed (Exit 1) tensorflow_serving/model_servers/http_rest_api_handler_test.cc:380:36: error: unterminated raw string

I have a conflict between my gcc version  but i’ve tried to update it but seems for my SUSE 12 SP2 is the highest version possible, also my bazel version is 0.21.0 because the 0.11.0 was giving me errors during TFMS compilation, these are tickets that i’ve checked related with the issue:

https://github.com/tensorflow/serving/issues/905

https://github.com/tensorflow/serving/issues/1001

Let me know if you need more details.

Thanks a lot.

Best Regards.

**Comment by adadouche** [comment]
Hi,

I'm checking now the all installation tutorial steps to make sure I'm not missing something.

Can you confirm that you are using gcc version 4.5.8? This is a rather very old version which is pulled when you install SLES 12SP3. On my side with SP3, I got:

```
hxeadm@hxehost:/usr/sap/HXE/HDB90>gcc --version
gcc (SUSE Linux) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I also realized that the documentation mentions that only TF 1.5 is supported, but the git clone command I reference will pull the latest release (1.12) which is probably why it requires bazel 0.21.0.

I'll check that as well.

**Comment by nachorubio** [comment]
Hi,
Sorry you're right i mistype the gcc version, the version i'm using is the same as you, maybe i should skip the unit testing files during compilation to avoid that error but seems is a bad idea( and i don't know how to do it from the bazel build command ) or also i should try to compile an older TF version, in any case i'll wait until your recommendation to solve/avoid the issue.
Thanks a lot for your time.

Best Regards.
![gcc_version](https://user-images.githubusercontent.com/46114917/50444004-cff1f700-08fd-11e9-90f3-08946e894a30.PNG)

**Comment by nachorubio** [comment]
Hi @adadouche 

I've completed the TMS installation without problems using the Docker Container, the connection is working and i'm on the next step deploying the Irish classifier :), from my side we can close the issue.

Best Regards.

Thanks a lot for your time and effort.

**Comment by adadouche** [comment]
Hi @nachorubio 

Cool!! Hope you found this approach easier than the compilation one.

Have fun!
