### ISSUE TITLE
Upload your Dataset for Image Classification Retraining

### ISSUE THREAD

**Issue by amitavamitra** [SAPDocuments/Tutorials#2922]
Hello Abdel , 

cd flowers
cf sapml fs put test flowers/test/
cf sapml fs put training flowers/training/
cf sapml fs put validation flowers/validation/

Here we need to provide a more clarity else we might be quite confused.

PUT here is asking for a local path to a remote path.

flowers/test/  or flowers/training/ etc are certainly not a local path. 

Would you please expand a little bit on this step ?

**Comment by amitavamitra** [comment]
@adadouche

**Comment by adadouche** [comment]
Hi @amitavamitra,

Can you clarify your request? Are you having an issue running the commands? Or is it more a request for more details about the command themselves and what they are used for?

Thanks
@bdel

**Comment by adadouche** [comment]
Hi @amitavamitra 

I have added some clarifications on the commands. And based on the last email exchange we had, I consider the issue as resolved.

**Comment by amitavamitra** [comment]
Thanks Abdel. Yes it was resolved.
