### ISSUE TITLE
Create a cloud-native application in SAP HANA

### ISSUE THREAD

**Issue by amolguptasap** [SAPDocuments/Tutorials#2923]
The following files have not been provided in the given Tutorial !!! 

"User browse to navigate to the folder Desktop/1- HANA Data Import and choose the file src (native).zip."

**Comment by Lsubatin** [comment]
That tutorial was meant to be executed at the Developer Garage at SAPPHIRE.  There are alternatives at developers.sap.com.

**Comment by amolguptasap** [comment]
Then it should not be published at developers.sap.com without the accompanying files !!!
