### ISSUE TITLE
Create a Business Service Using CDS

### ISSUE THREAD

**Issue by vgup** [SAPDocuments/Tutorials#2925]
I am using the cloud foundry trial in completing this tutorial and all the pre-reqs are in place. When testing the srv module using the run command. I get an error

Service provisioning for module: '/srv'
Could not create the 'bookshop-bookshop-hdi-container-S0inzqBe/Vtu8QIYWm' instance of the 'hana' service type for the 'bookshop-hdi-container' resource. Could not create the 'bookshop-bookshop-hdi-container-S0inzqBe/Vtu8QIYWm' service instance. Failed to select a database for instance 55e4dece-8260-4d97-9731-88949ca975a2, no database mapped to organization '7a0a5f8d-f4a1-4106-b514-1821b041b390' space '39f61ff9-788d-4a38-bac2-ad24ecafa857'

**Comment by Apfohlmann** [comment]
@vgup I just completed the tutorial. It worked for me. I didn't get the error you described.

First I got another error at Step 1 one. To fix this I had to enter the Cloud Foundry Trial via my SAP Cloud Platform Cockpit. Also, make sure you have enough memory left. 

Does this help you?

Best regards,
André

**Comment by vgup** [comment]
It worked with cloud foundry in Europe region. Earlier I was working with US Central region.

**Comment by socenmarc** [comment]
I'm also getting this error in Central US. Maybe some datacenter restriction with hana database?

**Comment by Apfohlmann** [comment]
@chgeo can you help? Is there any datacenter restriction with the hana database?

**Comment by chgeo** [comment]
Not sure what the HANA availability in the various datacenters is.  To follow up: @socenmarc which API endpoints do you refer to which 'Central US'?  Also, I assume you use your personal trial account?
