### ISSUE TITLE
Add a Database to Your Business Application

### ISSUE THREAD

**Issue by vgup** [SAPDocuments/Tutorials#2927]
The Build step shows Build is empty. There is no option to Build. I have changed the version in .hdiconfig file.

**Comment by Apfohlmann** [comment]
@vgup thank you for mentioning this error.

Can you provide a screenshot or any other additional information?

Best regards,
André

**Comment by vgup** [comment]
It was too long ago and I don’t have that setup anymore. Thanks for following up.

Vineet
