### ISSUE TITLE
Maintain platform subaccounts and SAP Web IDE permissions

### ISSUE THREAD

**Issue by Liebherr** [SAPDocuments/Tutorials#2932]
"Step 7: Give SAP Web IDE access to everyone" has changed

"Step 7: Give SAP Web IDE access" 

To enable users to work with Web IDE you have to explicitly assign the DiDeveloper Role to each of them.

1) Go to Roles
2) Select DiDeveloper Role
3) Press Assign in the role's section for individual users. A pop up opens.
4) Enter the required User's ID
5) Press Assign in the pop up

![image](https://user-images.githubusercontent.com/26269696/50819673-0af72000-132b-11e9-8e48-969ddd9e5094.png)

**Comment by mervey45** [comment]
@Liebherr I'll change it asap  :)

**Comment by Liebherr** [comment]
Done in QA

**Comment by thecodester** [comment]
@mervey45 @Liebherr Is this issue resolved?

**Comment by Liebherr** [comment]
resolved by the big last changes
