### ISSUE TITLE
Set up trust between identity authentication and SAP Cloud Platform subaccount

### ISSUE THREAD

**Issue by Liebherr** [SAPDocuments/Tutorials#2933]
Step 7 (Get metadata of subaccount) should be made step 4 (directly after local service provider creation) to reduce tool switches by 2

**Comment by thecodester** [comment]
Also shorten title and make title case -- suggestion: Set Up Trust Between Identity Authentication and Subaccount

**Comment by Liebherr** [comment]
Done in QA to be reviewed with Kai still as major additional changes and improvements done

**Comment by thecodester** [comment]
@Liebherr Not clear to me -- what is status of this and who is taking care of it?

**Comment by Liebherr** [comment]
Hi Daniel (@thecodester ),
I am taking care of this now, and issues reported here are done, but as it pointed out that even more rework is needed, I still need some time to create the version for production.
Regards
Ulrike

**Comment by thecodester** [comment]
Any update?

**Comment by Liebherr** [comment]
Yes, is resolved now.
