### ISSUE TITLE
Set up trust between identity authentication and SAP Cloud Platform subaccount

### ISSUE THREAD

**Issue by Liebherr** [SAPDocuments/Tutorials#2936]
Step 11: Set application' s identity provider

Navigation changed/renamed from "Authenticating Identity Provider > Identity Provider" to "Conditional Authentication > Conditional Authentication"

![image](https://user-images.githubusercontent.com/26269696/50832961-11e45980-1350-11e9-9906-3cabf5ae231c.png)

![image](https://user-images.githubusercontent.com/26269696/50833707-70aad280-1352-11e9-97f2-e325fe4e49fb.png)

**Comment by Liebherr** [comment]
better screenshot for 2nd one
![image](https://user-images.githubusercontent.com/26269696/50834030-486fa380-1353-11e9-8262-6171397f5f17.png)

**Comment by danmanasoiu** [comment]
Hi

Once I setup Local Service Provide to Custom (instead of Default), as per the blog of SAP Help, we cannot loger access the Web   UI URL of the SAP CPI   https://xxxxx-tmn.hci.eu1.hana.ondemand.com/itspaces

We dont want to use a separate corporate IdP, but use the standar SAP IA

So, what's wrong?

Regards
  Dan

**Comment by Liebherr** [comment]
Hi Dan,

first of all, please open a ticket to SAP, if your problems persists. We cannot offer support here.

Anyway, before opening the ticket rethink your use case.
Integration with S/4Hana as described in this tutorial does work with OAuth and a corporate IdP only.
Furthermore, is your SAP CPI really a Neo account? Do you really mean the Web UI of the Account or its Web IDE?
In the ticket you might open more information on these questions would be helpful.

Thanks and Best Regards
Ulrike

**Comment by Liebherr** [comment]
Done in QA, but to be reviewed with Kai still as major additional changes and improvements done
