### ISSUE TITLE
Using JPA in Custom Logic

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#2937]
My pom.xml was created with this information in ${project.parent.version}:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.sap.cloud.servicesdk.prov</groupId>
    <artifactId>projects-parent-odatav2</artifactId>
    <version>1.17.1</version>
  </parent>
```

but at http://central.maven.org/maven2/com/sap/cloud/servicesdk/prov/cf-xsa-util/ the Version 1.17.1 does not exist, the build failed. So I've replaced 1.17.1 with 1.25.0 and the build was successful.

**Comment by JijoRoyJacob** [comment]
Hi Gregor,
Can you confirm if you still see the same version issue in the pom.xml when you create a new project (business application) from template? I'm not able to recreate it and hence the question.

Best regards,
Jijo

**Comment by gregorwolf** [comment]
Hi Jijo,
I've created a fresh project yesterday and had the issue with the pom.xml. But the one I've created today is correct.

```
    <version>1.25.0</version>
```

Is there a file where I can see the template version used?

CU
Gregor

**Comment by JijoRoyJacob** [comment]
We noticed the issue earlier yesterday too but it seems to have resolved itself before we could investigate further. As far as the template version is concerned, I will check with the development team and get back to you.

**Comment by JijoRoyJacob** [comment]
Following is the response from the dev team to your question:

> If you create a CAP project with Java-based srv module, there is a file srv/pom.xml which contains the version of the odatav2 parent:
> ```
>   <parent>
>     <groupId>com.sap.cloud.servicesdk.prov</groupId>
>     <artifactId>projects-parent-odatav2</artifactId>
>     <version>1.25.0</version>
>   </parent>
> ```
> I guess this is what Gregor already found out himself. So, to put it simple: The template (i.e., Maven Archetype) version used is apparent from the parent version in the actual pom.xml

**Comment by JijoRoyJacob** [comment]
This issue can be closed as it is not reproducible anymore.
