### ISSUE TITLE
Using JPA in Custom Logic - Step 4

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#2938]
In Step 4 I'm asked to adjust the file srv/src/main/webapp/META-INF/sap_java_buildpack/config/resource_configuration.yml. But I only have a folder named srv/src/main/webapp/META-INF/java_xs_buildpack/config/resource_configuration.yml. Should I rename that folder?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
