### ISSUE TITLE
Offline Enable Your Android Application - Retest of questions

### ISSUE THREAD

**Issue by JuBerndt** [SAPDocuments/Tutorials#2943]
Is it possible to repeat the questions ? I have answered one question but two marked as 'green'. 
Why is that ?
Could not find any solution to repeat the questions.
Can you help ?

**
![grafik](https://user-images.githubusercontent.com/38529250/50896145-72cf6880-1408-11e9-97fb-e38ea45db862.png)
**

**Comment by thecodester** [comment]
@danielva Any thoughts?

@JuBerndt Is this still an issue? I don't get this problem.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
