### ISSUE TITLE
Create OAuth communication system and user

### ISSUE THREAD

**Issue by Liebherr** [SAPDocuments/Tutorials#2945]
1. rename "Step 4: Copy link address" to "Step 4: Get Web IDE URL"
2. Adapt descriptive text of that step to for example: "Switch to your SAP Cloud Platform cockpit, go to **Services** and select **SAP Web IDE**. Copy the link address of **Go to Service** paste it to some text editor and remove "https://" from that Web IDE's URL. This will be needed in the creation process of the communication system."
3. rename "Step 5: Add host name" to "Step 5: Set Web IDE URL as host name"
4. adapt descriptive text of that step to for example "Switch back to the communication system maintenance in S/4Hana Cloud system. Set Web IDE's URL without "http://" that you got before as **Host Name** of the communication system."

**Comment by mervey45** [comment]
@Liebherr done
