### ISSUE TITLE
Create OAuth communication system and user

### ISSUE THREAD

**Issue by Liebherr** [SAPDocuments/Tutorials#2948]
Whole certificate process in communication system can be simplified

1. rename "Step 10: Get SAP Cloud Platform subaccount's metadata" to "Step 10: Get SAP Cloud Platform subaccount's signing certificate"
2. adapt descriptive text to for example "Switch to your SAP Cloud Platform subaccount. Open trust settings, copy all data from the **Signing Certificate** field ( in windows: click inside and press CTRL+a ) and paste it to some text editor.
![image](https://user-images.githubusercontent.com/26269696/50902894-85539d00-141c-11e9-91c0-0edbcde7040d.png)
4. rename "Step 11: Create certificate from metadata" to "Step 11: Create certificate file"
5. delete step 1 from Step 11
6. adapt descriptive text of step 1 (former 2) of step 11 to for example "In the text editor file that you pasted SAP Cloud Platform subaccount's signing certificate into before, add a line with value "-----BEGIN CERTIFICATE-----" in front of the **Signing Certificate** and a line with value "-----END CERTIFICATE-----" after.
```swift
          -----BEGIN CERTIFICATE-----
               <SIGNING_CERTIFICATE>
          -----END CERTIFICATE-----

```
7. Adapt descriptive text of Step 12 to for example "Go back to your SAP S/4HANA Cloud system and open your created communication system draft. Edit your draft and enable it for OAuth 2.0 by checking the enabled box. Then upload the certificate by clicking upload signing certificate. Take the provider name from the CN attribute of the **Signing Certificate Subject**, that appears after upload and enter it as the provider name. Click Save.
![image](https://user-images.githubusercontent.com/26269696/50904116-c26d5e80-141f-11e9-9105-b06ad0b3fcbc.png)
8. With this step, you’ve uploaded your certificate to your communication system. Now your S/4HANA system trusts your SAP Cloud Platform subaccount."
The picture should also show the execution sequence

**Comment by mervey45** [comment]
@Liebherr  I'll change it asap.

**Comment by mervey45** [comment]
@Liebherr done

**Comment by thecodester** [comment]
@Liebherr Can you look at it and if OK close the issue? Thanks.

**Comment by Liebherr** [comment]
Hi Merve,
following updates I still cannot see
2. new image for trust.png
4. unnecessary step to copy data from metadata file still partly in
7. new image for certificate does not need to be that generic, please take the one given by me, it has dummy data already but shows more realistic what it would look like and what the new description of this step tells
Thanks and Regards
Ulrike

**Comment by Liebherr** [comment]
Done
