### ISSUE TITLE
Minor typo in "Import a Census Sample Dataset" tutorial

### ISSUE THREAD

**Issue by DFranch** [SAPDocuments/Tutorials#2951]
Hi,

One of the Accordian titles contain a typo in the tutorial "Import a Census Sample Dataset".

Current title is "Step 4: Download the *dample* data" - I assume it should be changed to **sample** instead of **dample**.

Markdown file: https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/mlb-hxe-import-data-pa-census/mlb-hxe-import-data-pa-census.md

**Comment by thecodester** [comment]
Just making sure you're paying attention :-)

Fixed https://github.com/SAPDocuments/Tutorials/commit/2434caee563bf81e921f862e0a3a8550ee454318
