### ISSUE TITLE
SAP HANA, express edition, in Google Cloud Platform Launcher (Database Services)

### ISSUE THREAD

**Issue by joymike** [SAPDocuments/Tutorials#2953]
Hi,

When I follow the instructions to launch the Google Cloud platform launcher (it launches Google Marketplace now), I cannot see HANA express listed as one of the options. Even searching for SAP doesn't return anything HANA related.
Can you please advise?

Cheers

**Comment by Lsubatin** [comment]
Hi,

There's been a problem with the marketplace and the images are temporarily unavailable. The teams are working to restore them ASAP. 

I will update this thread in the community once it's back up: https://answers.sap.com/questions/721640/hana-express-on-google-cloud-platform-implementati.html

Best,

Lucia.
