### ISSUE TITLE
Create an HTTP Service

### ISSUE THREAD

**Issue by peterlangner** [SAPDocuments/Tutorials#2955]
I this tutorial I find it difficult to gues, whta you want me to input in Step 7. I have calss, which does, what you wanted me to do, but it is not accepted as a result.

CLASS zcl__http_test DEFINITION
  PUBLIC
  CREATE PUBLIC .

PUBLIC SECTION.

  INTERFACES if_http_service_extension .
PROTECTED SECTION.
PRIVATE SECTION.
ENDCLASS.

CLASS zcl__http_test IMPLEMENTATION.

  METHOD if_http_service_extension~handle_request.
      DATA(lv_user_name) = cl_abap_context_info=>get_user_formatted_name( ).
      DATA: lv_text TYPE string.

      lv_text = lv_user_name.
      response->set_text( lv_text ).
  ENDMETHOD.
ENDCLASS.

**Comment by julieplummer20** [comment]
Hi Peter,
Yes, you are right. I have repaired the "rules" file that provides the code for validation. I will submit this for Pull Request right away. It should be available by EOB today.
I apologise, Julie.

**Comment by julieplummer20** [comment]
@thecodester - Hi Daniel, Just a heads-up:  I am going to push these 2 objects to QA, then Pull Request to Prod., asap, to solve Peter's problem. I have not made any other changes. If possible, can you please push them to Production as soon as possible? Thanks a lot.

**Comment by julieplummer20** [comment]
This issue can be closed. I have updated the tutorial and rules file and will push them to QA, then Pull Request.
