### ISSUE TITLE
Continue Your OData Exploration with EPM

### ISSUE THREAD

**Issue by bask-alur-gh** [SAPDocuments/Tutorials#2958]
1) The Tutorial suggests to use Chrome, but Chrome doesn't accept the credentials entered when prompted. So unable to access with Chrome the URLs used in this tutorial, like https://sapes5.sapdevcenter.com/sap/opu/odata/sap/EPM_REF_APPS_SHOP_SRV/Products/?$filter=MainCategoryId%20eq%20%27Software%27%20and%20StockQuantity%20le%2010&$select=StockQuantity,Name&$format=json 
2) Same issue with Internet Explorer 11 (on Windows 10).  (Works fine on Edge on Windows10).

Thanks in advance for looking into this.

**Comment by qmacro** [comment]
Hi @bask-alur-gh thanks for the message. This is not an issue with the tutorial itself, as it works for many folks with Chrome. This may be an issue with your userid and the SAP ES5 system. I have seen a couple of folks in the past struggle with this. I have a suggestion:

Try to log in to ES5 via the HTML5 GUI first, so you can check your authentication (ie username and password is correct). Without shutting Chrome down in between, now try to access the URL (in your message above). That should show that the access is fine, specifically after authenticating with the GUI. (This is just theory for now, btw). If that still has you stuck, please come back here; in the meantime I will reassign this to my esteemed colleague @jonathanbaker7 for any hints that he can add.

Thanks!

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
