### ISSUE TITLE
Get started with SAP Build

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#2959]
Trying to complete the Get Started with Build tutorial and found that it will not accept the Organisation I enter right at the end of the tutorial.
https://developers.sap.com/tutorials/build-getting-started.html

When I look at my Build profile it states SAP CSR in the organisation even though I entered something different in the front screen. When I enter SAP CSR in the tutorial it states the following:
Sorry, that’s incorrect. Please try again.

Can this be fixed please?
Thanks & Kind Regards
Phil Cooley

**Comment by pjcools** [comment]
Can I please get an update on this, I would like to complete this tutorial?

**Comment by thecodester** [comment]
@rbrainey ?

**Comment by rbrainey** [comment]
There's something about the BUILD account structure that we're working to integrate into our tutorial.  For now, you can safely enter "standard" as the answer to that question. A different organization membership won't have any impact on your downstream usage of BUILD.

Thanks,

Riley

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
