### ISSUE TITLE
Consume a Basic OData Service

### ISSUE THREAD

**Issue by mariomuellergermany** [SAPDocuments/Tutorials#2960]
Hi,

I wonder the tutorial starting with an project that already exits. Cound you please tell me the Prerequisites?
When I click on Prerequisites > this has also a Prerequisites > an so on and so on with prerequisites.
Could you please state the preceeding tutorial? What kind of projekt do I have to set up?

Many thanks
Regards
Mario

**Comment by qmacro** [comment]
The tutorial is a part of a group, which is signified at the very top (in the breadcrumbs) and the group is shown at the very bottom ("Create an SAPUI5 application with SAP HANA XS Advanced"). So the prerequisite shown is the first tutorial ("SAPUI5 User Interface") in this group.

Regarding the prerequisites for the "SAPUI5 User Interface" tutorial - I will defer to my esteemed colleagues @thecodester and @Lsubatin .

Daniel / Lucia - can you please comment and help Mario? Thank you!

**Comment by thecodester** [comment]
From what I can figure out:

There is a group called [Create an SAPUI5 application with SAP HANA XS Advanced](https://developers.sap.com/group.hana-xsa-sapui5.html), starting with SAPUI5 User Interface tutorial. 

That tutorial has a prerequisite of the group called [Expose Entities Using OData and XSJS with SAP HANA XS Advanced](https://developers.sap.com/group.hana-xsjs-xsodata.html), starting with the import tutorial.

That tutorial has a prerequisite of a mission called [Get Started with XS Advanced Development](https://developers.sap.com/mission.xsa-get-started.html), so the path is a little complex (and perhaps time-consuming).

- Navigation: We can discuss offline if we plan to have complex pathways and if there is a way to better show these learning paths.
- There is a bug in that if I start at the first tutorial "SAPUI5 User Interface" and click "Group" I am taken to the correct group for that tutorial. But if I now navigate to the prerequisite (which is in a different group) and then click group, I get the original group and not the group for the current tutorial. I will report.

**Comment by Lsubatin** [comment]
Yes, those prerequisites are correct

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue.

If you still have questions, feel free to reopen the issue.
