### ISSUE TITLE
Consume a Basic OData Service

### ISSUE THREAD

**Issue by mariomuellergermany** [SAPDocuments/Tutorials#2961]
Hi,

your are writing "Within the controller folder, add the following code:"

But it is not possible to add code to a folder. Would you please provide the name of the file in the controller-folder?

Thanks, reagrds
Mario

**Comment by qmacro** [comment]
Thanks for highlighting, the file name is missing. I've added it to the tutorial now ([will be live soon](https://github.com/SAPDocuments/Tutorials/pull/2964)). In the meantime, the file is `App.controller.js`. Cheers!
