### ISSUE TITLE
Create OAuth communication system and user

### ISSUE THREAD

**Issue by danmanasoiu** [SAPDocuments/Tutorials#2968]
Hello 

Does the comm user need some role? If yes, how do you assign to it (I know for normal business users)

It is said: business catalog SAP_CORE_BC_COM to your user - is this the one who sets the config  (already done, as included in BR SAP_BC_ADMINISTRATOR) or for the comm user?

The issue is that I have configure everything according to the blog adn also to the SAP Help file, but when creating a project from template in Web IDE, I get ".. catalog service is unavailable"

So, what is solution?  I have also checked note
https://launchpad.support.sap.com/#/notes/2561567

regards
  Dan Manasoiu

**Comment by mervey45** [comment]
Hi @danmanasoiu, 

you are creating a inbound communication user here. So therefore you don't assign to your communication user a role. But you need to assign business catalog SAP_CORE_BC_COM to your user before even starting with this tutorial. I think you have another issue. Please open a ticket for your issue. 

Best regards, 
Merve

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
