### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by umbertopanico** [SAPDocuments/Tutorials#2973]
When add hdbgrants:

Processing "cfg/plain.hdbgrants"...  Using service "ServiceName_1" of type "sql"Error: Error executing: GRANT "SELECT","SELECT METADATA" ON SCHEMA "PLAIN" TO "DB_1#OO" WITH GRANT OPTION; (nested message: invalid user name: DB_1#OO: line 1 col 55 (at pos 54))grantor service: "ServiceName_1", type: "sql", user: "SYSTEM"file name: /hana/shared/HXE/xs/app_working/hxehost/executionroot/e2ac2363-b9ae-48c8-904e-1753a1358131/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-5725879102677620496/db/cfg/plain.hdbgrants(0s 172ms)

**Comment by Lsubatin** [comment]
Please refer to the community (answers.sap.com) for support. 

That error is probably due to having the user-provided service pointing at a different tenant (e.g., systemdb) from where the container is (first tenant, HXE, mapped to the space).

**Comment by Bano5022-star** [comment]
Hi,

what is the solution?
