### ISSUE TITLE
Create a Business Service Using CDS - update screenshot in Step 1

### ISSUE THREAD

**Issue by boghyon** [SAPDocuments/Tutorials#2976]
Currently, the second screenshot in the [step 1](https://developers.sap.com/tutorials/cp-apm-01-create-business-service.html#4572ff25-693b-4de1-8da1-9eff99cd34fa) looks as follows:

![web-ide-create-template-for-scp-business-application-old](https://user-images.githubusercontent.com/12143247/51465653-9e3b4700-1d68-11e9-9f6e-f0f86eb02b7b.gif)

## Issue
It encourages `my.company` as the _Java Package_ name instead of `my.bookshop`.
I'm aware of the note mentioned below the screenshot:

> You should update the **Java Package** to match the namespace used in this sample application, which is `my.bookshop`.

But that note is easily overlooked.

## New screenshot
![web-ide-create-template-for-scp-business-application](https://user-images.githubusercontent.com/12143247/51465641-9aa7c000-1d68-11e9-9ae7-199be851b290.gif)

**Comment by Apfohlmann** [comment]
@boghyon thank you for raising this issue. We just fixed it. We also replaced the first picture as it showed an old label for SAP Cloud Platform Business Application. 

From my side, this ticket can be closed.
