### ISSUE TITLE
Installing SAP HANA, express edition Server + Apps, with Docker

### ISSUE THREAD

**Issue by michelde** [SAPDocuments/Tutorials#2990]
Wrong URL at chapter 14:
**https://help.sap.com/viewer/product/SAP_HANA,_EXPRESS_EDITION**

correct: 
**https://help.sap.com/viewer/p/SAP_HANA,_EXPRESS_EDITION**

**Comment by JCurrie27** [comment]
@aplata-sap - Please update the URL in step 14 of https://developers.sap.com/tutorials/hxe-ua-install-using-docker-xsa.html. Thanks.

**Comment by aplata-sap** [comment]
This has been updated. @JCurrie27
