### ISSUE TITLE
SAP HANA Docker Upgrade HXE - missing root password

### ISSUE THREAD

**Issue by michelde** [SAPDocuments/Tutorials#2991]
When trying to upgrade HXE I need to run the `sudo ./hxe_upgrade.sh `script as root. But nowhere I can find a hint to the root password.
I follow the documentation from [SAP HANA EXPRESS HELP](https://help.sap.com/viewer/8c3bbc4a904d42efac77c09da0bccf64/2.0.03/en-US/f14b7cf96be74e1fa9f73be9a8926067.html)

**Comment by songrui01** [comment]
You could the following command to login/set root password.
1. docker exec -it -u root containerName bash
2. passwd

**Comment by aplata-sap** [comment]
This has been added to the latest tutorial. @JCurrie27
