### ISSUE TITLE
Create and Expose Core Data Services Based on a Database Table

### ISSUE THREAD

**Issue by DusanSacha** [SAPDocuments/Tutorials#2993]
Hi,

there is a wrong screenshot in following tutorial:
[Create and Expose Core Data Services Based on a Database Table](https://developers.sap.com/tutorials/abap-environment-create-cds-view.html)

Step 12: Open SAP Fiori elements view
In Step 12.1. we are opening ElementSet Bookings - item - to_Country
In Step 12.4 and Step 12.6 the used screenshots are from some Currency ElementSet

Solution:
Change screenshots in Step 12.4 and Step 12.6

Correct screenshots should look like following
![step12_4](https://user-images.githubusercontent.com/16412025/51750113-60645880-20b1-11e9-8716-bd667c14b314.PNG)
![step12_6](https://user-images.githubusercontent.com/16412025/51750114-60645880-20b1-11e9-8a91-f3e303c2798e.PNG)

**Comment by mervey45** [comment]
Hi @DusanSacha, 

thank you for your feedback. I'll change it. My colleague did those changes. I'll change it asap.

Best regards, 
Merve

**Comment by thecodester** [comment]
https://github.com/SAPDocuments/Tutorials/pull/2977
