### ISSUE TITLE
Tutorial Page tutorials/hana-data-access-and-authorizations/hana-data-access-and-authorizations.md Issue

### ISSUE THREAD

**Issue by SAPDocs** [SAPDocuments/Tutorials#3]
Page issue found: [tutorials/hana-data-access-and-authorizations/hana-data-access-and-authorizations.md](https://github.com/SAPDocuments/Test-Tutorials/blob/master/tutorials/hana-data-access-and-authorizations/hana-data-access-and-authorizations.md) contains invalid tags.
[tutorial:technology/SQL]

**Comment by agraebe** [comment]
@lpareek why is this tag invalid?

**Comment by agraebe** [comment]
... I figured it out: Because it's uppercase.
