### ISSUE TITLE
Get Started with SAP UI Development / Create App from Prototype with SAP Web IDE / Change from mock server to live OData service

### ISSUE THREAD

**Issue by sybitdst** [SAPDocuments/Tutorials#3006]
Getting to step 8/9:
When opening the Detail Controller there are 2 errors at line 14+15. Also the validation of the initialization function is not working. 

Running the Web Service is also looking different than the screenshots in the tutorial. The attached File is the screen that appears after running the Project as Web Service. And clicking on Inventory Dashboard leads to an error saying that "the app cannot ne opened, because the SAP-UI5 component of the Application can't be loaded. UI5-Component for navigation intention "#BUILD-prototype" hasn't load"

Greetings 
David Schmitt

![image](https://user-images.githubusercontent.com/47175637/51975065-aa6a8700-2481-11e9-99fb-54ce24d68f2c.png)

**Comment by rbrainey** [comment]
Hi David,
I'm sorry for the horribly log response time here.  That particular Mission was obsoleted and removed earlier this year -- are you still exploring Web IDE development?  If so, there's a few paths I can suggest based on your area(s) of focus.  Out of these areas, are there any that are of particular interest?

* Deploying applications  in Cloud Portal
* Developing OData services using Web IDE and Java
* Developing OData services using Web IDE and Node.js 

Let me know ...

**Comment by rbrainey** [comment]
Closing this issue as we'd direct folks to the new Cloud Portal Missions:  https://developers.sap.com/mission.portal-cf.html
