### ISSUE TITLE
How to write a simple go application that queries HANA, express edition. pyhdb?

### ISSUE THREAD

**Issue by mpw96** [SAPDocuments/Tutorials#3009]
Tutorial URL: https://developers.sap.com/tutorials/hxe-golang-http.html

Hi application.go, line 69 talks about pyhdb driver? This cannot be right, can it?

T&R
Marc-Philip

**Comment by thecodester** [comment]
@Lsubatin You are listed as a reviewer of the tutorial. Do you know who owns this and can help here?

**Comment by thecodester** [comment]
@Lsubatin Any update here?

**Comment by Lsubatin** [comment]
My guess is that the comment Marc-Philip refers to is just wrong (cannot tell without asking the author unfortunately), it does not affect the actual code. These tutorials are getting replaced.

**Comment by thecodester** [comment]
I am going to close this since we will remove and replace this tutorial.

If you still have questions, feel free to reopen the issue.
