### ISSUE TITLE
Import your TechEd BUILD project into SAP Web IDE

### ISSUE THREAD

**Issue by CESolomon** [SAPDocuments/Tutorials#3011]
Tutorial URL: https://developers.sap.com/tutorials/pre-teched-2018-build-import.html

There are actually THREE tutorials that are all the same topic:

1.Import your SAP Build project into SAP Web IDE (https://developers.sap.com/tutorials/build-import-webide.html) 9/20/18
2. Import your TechEd BUILD project into SAP Web IDE ( https://developers.sap.com/tutorials/pre-teched-2018-build-import.html ) 8/27/18
3. Import your TechEd BUILD project into SAP Web IDE (https://developers.sap.com/tutorials/teched-2017-build-import.html) 9/20/18

I completed the first just fine, however, I need to complete 2 and 3 to complete groups/missions. On step 1 of both, the validation on "Copy and paste the URL of the BUILD service in SAP Cloud Platform into the below text box." fails. The same URL, however, worked fine for #1 above. 

Any help on what the URL should be or look like to complete the other ones ?!?!?!

**Comment by CESolomon** [comment]
FYI, I had used....

https://account.hanatrial.ondemand.com/cockpit/#/acc/(my account name)/service/build/overview

.....which now doesn't even work in #1 anymore (unless it doesn't validate again when you were correct....wish it would show "old" correct answer to compare).

**Comment by CESolomon** [comment]
I figured it out....and it is quite "crazy".....so using Firefox (if it matters), my URL to the service appears as ....

https://account.hanatrial.ondemand.com/cockpit/#/acc/(my account name)/service/build/overview

This ALWAYS failed the validation. However, I checked some "old" BUILD videos on YouTube and noticed something different......if I removed the "/" after "cockpit" and before the hash/pound symbol "#", such that the URL is now...

https://account.hanatrial.ondemand.com/cockpit#/acc/(my account name)/service/build/overview

....it now passes in ALL tests! WEIRD WILD STUFF!!!

**Comment by nilpeksen** [comment]
thank you for your helpful answer, I was going crazy before your answer @CESolomon

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
