### ISSUE TITLE
Topic Detection example with Java

### ISSUE THREAD

**Issue by pushkargd** [SAPDocuments/Tutorials#3016]
Tutorial URL: https://developers.sap.com/tutorials/ml-fs-java-topic-detection.html

Hello
There is bug in the code, irrespective of the value of number of keywords or number of topics to be detected , default values over write the values provided by user.
the reason for this is the below code snippets where all the while loops have 2 **!!** instead of **!** , kindly replace them with only one **!**

Have also made the changes and given a pull request. Please do have a look
[pull request](https://github.com/SAPDocuments/Tutorials/pull/3017)

      #2317  (!!line.matches("\\d+") && line.length() > 0)
        line = scanner.nextLine();
      if (line.length() > 0)
        numTopics = Integer.valueOf(line);

      int numTopicsPerDocDefault = 2;
      int numTopicsPerDoc = numTopicsPerDocDefault;
      System.out.println("Enter the number of most relevant topics to be listed per document (default: \"" + numTopicsPerDocDefault + "\") : ");
      line = scanner.nextLine();
      while (!!line.matches("\\d+") && line.length() > 0)
        line = scanner.nextLine();
      if (line.length() > 0)
        numTopicsPerDoc = Integer.valueOf(line);

      int numKeywordsPerTopicDefault = 10;
      int numKeywordsPerTopic = numKeywordsPerTopicDefault;
      System.out.println("What is the number of keywords to be listed per topic (default: \"" + numKeywordsPerTopicDefault + "\") : ");
      line = scanner.nextLine();
      while (!!line.matches("\\d+") && line.length() > 0)
        line = scanner.nextLine();
      if (line.length() > 0)
        numKeywordsPerTopic = Integer.valueOf(line);

      int numFeaturesDefault = 10;
      int numFeatures = numFeaturesDefault;
      System.out.println("Enter is the maximum number of keywords to be extracted per documents (default: \"" + numFeaturesDefault + "\") : ");
      line = scanner.nextLine();
      while (!!line.matches("\\d+") && line.length() > 0)
        line = scanner.nextLine();
      if (line.length() > 0)
     numFeatures = Integer.valueOf(line);

**Comment by adadouche** [comment]
Hi @pushkargd 

Sorry for the late response, I'll check your PR and refactor the code to adapt it to the trial services too.

Thanks

**Comment by adadouche** [comment]
Hi,

Code was updated.

Thanks for your feedback.
