### ISSUE TITLE
Maintain a Communication Arrangement for an Exposed Service

### ISSUE THREAD

**Issue by hdix01** [SAPDocuments/Tutorials#3022]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

Please specify the step you are referring to

Step 9: Select scenario
Select your scenario and click on Create

It's not clear where the scenario is createt, I can only pick up an existing scenario

**Comment by mervey45** [comment]
Hi @niloofar-naseri, 

can you have a look at it?
Thank you.

Best regards, 
Merve

**Comment by niloofar-naseri** [comment]
Hi @hdix01 
This Scenario is the same communication Scenario which you created in the step 9 of this tutorial,
https://developers.sap.com/tutorials/abap-environment-business-service-provisioning.html 
If you do all tutorials in the right sequence, it will be clear what scenario is meant.
But I can make it specific and adress the other tutorial in this step.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
