### ISSUE TITLE
abap-environment-transactional-enablement: edit fails

### ISSUE THREAD

**Issue by andkopp** [SAPDocuments/Tutorials#3025]
Hello!

I completed the tutorial **abap-environment-transactional-enablement**. In the Fiori Elements preview, I can add and delete bookings (changes are written to the database table) but I am not able to edit an entity. I get the following error message: Precondition failed for entity CDS~ZI_BOOKING_xxx with key 1

Any ideas?

Best regards
Andreas

**Comment by mervey45** [comment]
Hi @andkopp,

please try it again. It should work. I've tested this tutorial again. Please be careful with every step.
I could change 1 object and save it.

Best regards, 
Merve

**Comment by andkopp** [comment]
I am sorry but I cannot try again because I have lost access to the trial instance. Thank you for checking.
Best regards
Andreas
