### ISSUE TITLE
Getting Started with the SAP Web IDE Full-Stack Version (Trial)

### ISSUE THREAD

**Issue by MarkusRichterWerth** [SAPDocuments/Tutorials#3034]
Tutorial URL: https://developers.sap.com/tutorials/webide-innovation-beta.html

This tutorial does not really describes the steps for cloud foundry ;-( The link to the help pages of SAP is not really helping if the WebIDE is not picking up destionations that are already configured on the cloud foundry side. Hence, something is missing in the description ...

**Comment by jhornik** [comment]
Hi Markus,

I am looking into this issue this week. Thanks for bringing it to our attention.

Regards,
Julia

**Comment by jhornik** [comment]
Hi Markus, sorry for the delay. I have updated step 4 with a better link: https://developers.sap.com/tutorials/cp-cf-create-account.html. 

Hope this resolves the issue.
