### ISSUE TITLE
Images are not displaying in tutorials

### ISSUE THREAD

**Issue by lmtisme** [SAPDocuments/Tutorials#3039]
Tutorial URL: https://developers.sap.com/tutorials/xsa-e2e-sapphire-analytics.html

Also when people respond with pictures you can not see those either.

**Comment by Lsubatin** [comment]
Hi, Lana, 

I can see the pictures so there may be a refresh problem.  What do you mean by "when people respond with pictures"?

I would also recommend you check the full version of this tutorial:
https://developers.sap.com/tutorials/xsa-calculation-views-anonymization-k.html

The one you are looking at depends on importing a file that you will not find in that format.

Best, 

Lucia.

**Comment by lmtisme** [comment]
Could have been a refresh issue.    I checked about 10 tutorials and could not see any images.
I went to blogs and could not see images in their responses (sorry that was NOT clear).
Thanks for the link. 
Lana
    On Wednesday, February 6, 2019, 4:41:05 PM EST, Lucia Subatin <notifications@github.com> wrote:  
 
 
Hi, Lana,

I can see the pictures so there may be a refresh problem. What do you mean by "when people respond with pictures"?

I would also recommend you check the full version of this tutorial:
https://developers.sap.com/tutorials/xsa-calculation-views-anonymization-k.html

The one you are looking at depends on importing a file that you will not find in that format.

Best,

Lucia.

**Comment by thecodester** [comment]
I will check the image issue. 

@lmtisme If the other issues are resolved, please close the issue.

**Comment by cdeil** [comment]
I also noticed that the images don't load.
For https://developers.sap.com/tutorials/hcp-create-trial-account.html I see this in Chrome:

![screenshot 2019-02-07 at 10 02 11](https://user-images.githubusercontent.com/852409/52400478-87faee00-2abf-11e9-959d-7fd8b996db66.png)

**Comment by thecodester** [comment]
I see the images now. Do you?

**Comment by cdeil** [comment]
Now I also see the images. Thank you for fixing the issue!

**Comment by lmtisme** [comment]
I can not see the images. I deleted my cache.  Same page.. same error as before.  Is it perhaps because the tutorial was meant for Sapphire?
![image](https://user-images.githubusercontent.com/40838326/52406721-63414f00-2a9c-11e9-8342-1650babfb95c.png)

**Comment by cdeil** [comment]
Another page that still has this issue: https://developers.sap.com/tutorials/cp-cf-fundamentals.html

**Comment by thecodester** [comment]
Working on it ...

**Comment by lmtisme** [comment]
Spoke to a developer here that said this is likely a server issue where it is overcapacity.  He said it happened at TechEd.

**Comment by BaerbelW** [comment]
It seems to be an "on-off" type of issue with images sometimes getting displayed and sometimes not. Sometimes, some of the images in a tutorial load but which ones changes when the page gets refreshed or is accessed again.

Just moments ago and using Firefox, this URL didn't show any images for me:
https://developers.sap.com/tutorials/abap-dev-adt-create-new-structure.html

When I hit <ENTER> with the cursor positioned in the address field, the page reloads and now displays the images.

**Comment by thecodester** [comment]
We are working on a solution to fix this intermittent problem. I see the images have reloaded -- yes, there is some reloading of images into cache that takes time. For now, I am closing this issue. If you still have the issue, let us know.
