### ISSUE TITLE
An Open Data Protocol (OData) primer for developers

### ISSUE THREAD

**Issue by lmtisme** [SAPDocuments/Tutorials#3040]
Tutorial URL: https://developers.sap.com/tutorials/hcp-webide-odata-primer.html

I went through this tutorial but the percentage taken never changed from 0%.

**Comment by IObert** [comment]
This issue solved be resolved by #3175, please confirm that you can see blue "Done" buttons after each step.

**Comment by IObert** [comment]
Closed due to inactivity
