### ISSUE TITLE
Installing SAP HANA, express edition Server + Apps, with Docker

### ISSUE THREAD

**Issue by chinhnguyen8855** [SAPDocuments/Tutorials#3041]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker-xsa.html

Per instruction, I tried to pull the docker image using below command, but the image is not available.
![image](https://user-images.githubusercontent.com/3290297/52375129-c509a680-2a13-11e9-8f72-64b4aa0469d5.png)

When I go to docker store, the docker image is still referenced to an older version (33)

![image](https://user-images.githubusercontent.com/3290297/52375180-e66a9280-2a13-11e9-82ff-2b6bf14ca994.png)

Please correct it.

**Comment by aplata-sap** [comment]
This has been corrected. @JCurrie27

**Comment by cocopapagal** [comment]
:) i thought that the Image version would be changed in the docker hub not the documentation. :)
