### ISSUE TITLE
Get a Free Trial Account on SAP Cloud Platform

### ISSUE THREAD

**Issue by cdeil** [SAPDocuments/Tutorials#3044]
Tutorial URL: https://developers.sap.com/tutorials/hcp-create-trial-account.html

Step 6 "Validate URL" doesn't work for me:
https://account.hanatrial.ondemand.com/cockpit/#/acc/p2001104178trial/accountdashboard

![screenshot 2019-02-07 at 10 14 45](https://user-images.githubusercontent.com/852409/52401284-98ac6380-2ac1-11e9-944f-9e24164317cf.png)

**Comment by cdeil** [comment]
Also at step 1 it said "If you have an account on www.sap.com (e.g. an S, C, D or I number)"

I got a P number, which apparently can be used as well.

Looks like steps 1 & 6 in this tutorial need to be updated to accomodate P ID numbers also?

**Comment by thecodester** [comment]
Sorry for the issue. Can you try again?

**Comment by cdeil** [comment]
Works now. Thanks!
