### ISSUE TITLE
Take a Tour of the SAP Cloud Platform Cockpit

### ISSUE THREAD

**Issue by cdeil** [SAPDocuments/Tutorials#3045]
Tutorial URL: https://developers.sap.com/tutorials/cp-tour-cockpit.html

Step 5 currently says "Go ahead a click on Security, and then Roles to get to the Roles page for the application." and shows a screenshot with a "roles" page.

I only see "Trust", the "Roles" doesn't exist.
Maybe it has been renamed / changed a bit?

<img width="248" alt="screenshot 2019-02-07 at 10 36 21" src="https://user-images.githubusercontent.com/852409/52402308-3dc83b80-2ac4-11e9-8517-1a76991bb5aa.png">

**Comment by qmacro** [comment]
Hi @cdeil - what you report seeing is when you select "Security" in the main Neo cockpit menu ("Security" being the same level as, for example, "Applications" and "Connectivity").

The "Security" -> "Roles" referred to here is for the Java application that is being examined in the previous steps. 

HTH!
