### ISSUE TITLE
Connect to SAP HANA, express edition using Python

### ISSUE THREAD

**Issue by Sygyzmundovych** [SAPDocuments/Tutorials#3046]
Tutorial URL: https://developers.sap.com/tutorials/hxe-python-connection.html

Please specify the step you are referring to: In "How-to details" the link in "For more details about the Python driver SAP HANA, please refer to the online documentation." is to HANA 2.0.02 help which still contains an error in one connection string example.

I suggest to relink to 2.0.03 (or "latest") doc: https://help.sap.com/viewer/0eec0d68141541d1b07893a39944924e/2.0.03/en-US/d12c86af7cb442d1b9f8520e2aba7758.html

Regards.

**Comment by thecodester** [comment]
@adadouche I saw you did some work on this one. If someone else is the owner, let me know.

**Comment by adadouche** [comment]
Hi @thecodester,

This was an How-to from HXE UA that I refreshed in the past. But not the owner.

Thanks

**Comment by JCurrie27** [comment]
Hi: Chris owns this one, but I updated the link. It will now always point to the latest published SAP HANA Client Interface Programming Reference. Closing.
