### ISSUE TITLE
Explore and Customize Your SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by cdeil** [SAPDocuments/Tutorials#3048]
Tutorial URL: https://developers.sap.com/tutorials/webide-customize.html

Step 8 says "To add features to your SAP Web IDE, click Features under Workspace Preferences."

Looks like "features" was renamed to "extensions" -> tutorial should be updated:

<img width="296" alt="screenshot 2019-02-07 at 14 26 36" src="https://user-images.githubusercontent.com/852409/52414372-6829f100-2ae4-11e9-9ebc-be8f338788ac.png">

**Comment by jhornik** [comment]
Hi Christoph @cdeil 

Thanks so much for bringing this to our attention. We have indeed recently changed "features" to "extensions" and sorry for any inconvenience that we somehow missed updating this tutorial. 

The updates have now been made.
 
Thanks and regards,
Julia

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
