### ISSUE TITLE
Create an ABAP Project in Eclipse

### ISSUE THREAD

**Issue by 7ashiorkor7** [SAPDocuments/Tutorials#3053]
Tutorial URL: https://developers.sap.com/tutorials/abap-create-project.html

Please specify the step you are referring to

ABAP communication layer is not configured properly. This might be caused by missing Microsoft Runtime DLLs VS2010. Consult the installation guide or download page for further details on how to install this component.
Native library sapjco3 is too old. Found library C:\Program Files (x86)\SAP\SAP Business One Integration\IntegrationServer\Tomcat\webapps\B1iXcellerator\WEB-INF\lib\sapjco3.dll has version "721.510", but required is at least version "721.619".

**Comment by f4abap** [comment]
How do this refer to the tutorial? Looks like it's a problem on your computer...

**Comment by 7ashiorkor7** [comment]
> How do this refer to the tutorial? Looks like it's a problem on your computer...

yes i realized. please how do i fix it. i need help

**Comment by julieplummer20** [comment]
Hi, f4abap is quite correct; this is not an issue with the tutorial. 
Are you a customer or partner? If so, you need to open an OSS message.
If not, I cannot guarantee support, but I can give a few pointers.
I googled your problem and got this: https://archive.sap.com/discussions/thread/3584657 
Please follow the recommendations there. 
If that fails, please post a question to the ABAP development forum, referencing that thread.
Best wishes 
Julie.

**Comment by thecodester** [comment]
This may be a more general question and not about the tutorial itself. Feel free to continue the discussion in the SAP Community or in the SAP Questions & Answers.

https://www.sap.com/community.html
https://answers.sap.com/index.html
