### ISSUE TITLE
Use the Face Detection API from a REST Client

### ISSUE THREAD

**Issue by gepparta** [SAPDocuments/Tutorials#3054]
Tutorial URL: https://developers.sap.com/tutorials/cp-mlf-rest-img-face-detection.html

Please specify the step you are referring to:
 "Here is a simple HTML code you can use to visualize other results"

My improvement suggestion:
Would be nice if you highlight the places in example html code for using with an own picture.
Was a little bit tricky as a abap developer to find out that for example the value of <canvas id="canvas_
has to start with "canvas_".

Kind regards
Keep up the good work

**Comment by adadouche** [comment]
Hi,

Thanks for your feedback.

I justed refactored the sample code provided and added some explanation about how to use it with your own image.

Let me know if that meet your expectation.

I'll close this issue for now, but feel free to reopen if needed.
