### ISSUE TITLE
Create a Business Service with Node.js using Visual Studio Code

### ISSUE THREAD

**Issue by martin-moser** [SAPDocuments/Tutorials#3055]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Please specify the step you are referring to: Prerequisites
Please add that cds version ^3.5.x must be installed.  If an npm install does not do the trick, the issue might be in the package.json file.  (Reference to wrong CDS version.)  If that still does not fix it (npm install does not install the latest version), try removing the folder node_modules and npm install again.

**Comment by chgeo** [comment]
@martin-moser, which error are you referring to?  Npm install error?  Or an 'old' unexpected cds version that you get?

**Comment by Apfohlmann** [comment]
@thecodester you can close this issue.
