### ISSUE TITLE
Use the Similarity Scoring with the Text Feature Extraction API from a REST Client

### ISSUE THREAD

**Issue by tricktresor** [SAPDocuments/Tutorials#3056]
Tutorial URL: https://developers.sap.com/tutorials/cp-mlf-rest-similarity-text.html

Please specify the step you are referring to

Field Name | Value
-- | --
HTTP Method | POST
URL | https://mlftrial--doc-feats.cfapps.eu10.hana.ondemand.com/api/v2alpha1/text/feature-extraction

URL has one "-" to much...

Cheers
Enno

**Comment by adadouche** [comment]
Thanks for your feedback.

It's now fixed in https://github.com/SAPDocuments/Tutorials/commit/0181a14ab20e42618e3dbf7116057b02422506a5
