### ISSUE TITLE
Consume the API Proxy in SAP Web IDE

### ISSUE THREAD

**Issue by jasmikou** [SAPDocuments/Tutorials#3061]
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-webide-int.html
i got this error when i a choose the service.

Thank you very much 
![sap_web_ide](https://user-images.githubusercontent.com/34094577/52532521-f68db500-2d26-11e9-86ba-2730af89d085.PNG)

**Comment by MichaelCzcz** [comment]
@mhassett92 any updates?

**Comment by mhassett92** [comment]
Hi @jasmikou, apologies for the delay. I switched roles in 2018 and fell behind in managing my issues.

Can you share your API Proxy URL? There may be an extraneous character disrupting the metadata url creation.

**Comment by MichaelCzcz** [comment]
@jasmikou Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
