### ISSUE TITLE
Add Map Support to the App - Part 2

### ISSUE THREAD

**Issue by jdubey** [SAPDocuments/Tutorials#3069]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-scpms-teched18-08.html

Please specify the step you are referring to

Step 4: Add a FUIMapDetailPanel to show more details about the tracked package

The setupDetailPanel() method should have detailPanel.isSearchEnabled = false.  Otherwise the search panel is displayed

**Comment by KevinMuessig** [comment]
That is true. Thank you for noticing. Will be in the next patch.
