### ISSUE TITLE
Internet of Things (IoT) made easy

### ISSUE THREAD

**Issue by eliasmsiqueira** [SAPDocuments/Tutorials#3070]
Tutorial URL: https://developers.sap.com/tutorials/teched-2016-9.html

Step 2 - Trial SCP does not offer IOT services anymore

**Comment by thecodester** [comment]
@maxstreifeneder Can you check if this tutorial is still valid. It could be we recently removed the 2016 teched mission but not the individual tutorials. I can check.

**Comment by maxstreifeneder** [comment]
@thecodester deprecated tutorial/mission, since IoT Service 2.0 is not available for new subscriptions anymore, but still for already subscribed users.

**Comment by thecodester** [comment]
I am closing the issue since tutorial has been removed.
