### ISSUE TITLE
Get a Free Trial Account on SAP Cloud Platform

### ISSUE THREAD

**Issue by haanto** [SAPDocuments/Tutorials#3073]
Tutorial URL: https://developers.sap.com/tutorials/hcp-create-trial-account.html

Please specify the step you are referring to : 
Step 6: Validate the SAP Cloud Platform cockpit URL

When I past the URL in the box I get the error "sorry that s incorrect. try again". please refer to the attached image
![desk_1](https://user-images.githubusercontent.com/47561735/52634371-5622c680-2ec7-11e9-9167-b8b37a467fcd.jpg)

**Comment by thecodester** [comment]
Sorry for the problem. Can you try again?

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
