### ISSUE TITLE
Get a Free Trial Account on SAP Cloud Platform

### ISSUE THREAD

**Issue by russmartin304** [SAPDocuments/Tutorials#3074]
Step 6:
 Unable to validate URL. Just gives me an error stating sorry, that is incorrect.

**Comment by thecodester** [comment]
@russmartin304 Can you try again? The URL should end with something like

`.../<yourID>/accountdashboard`

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
