### ISSUE TITLE
How to tune Hana according to the machine hardware configuration

### ISSUE THREAD

**Issue by lin1161** [SAPDocuments/Tutorials#3078]
When installing Hana on a machine, how to config hana according to the machine hardware configuration? 

Such as how many memory/cpu can Hana use, or how many memory/cpu can XSA/optional components use?

Example: if there are two machines, one has 128GB memory and another has 256GB memory. How can we tune the Hana parameter to get better performance according to the machine physical memory size?

**Comment by thecodester** [comment]
What tutorial does this relate to?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
