### ISSUE TITLE
HANA One Console cannot get instance status

### ISSUE THREAD

**Issue by lin1161** [SAPDocuments/Tutorials#3079]
According to the https://s3.amazonaws.com/hanaone-documentation/Rev+122.60.0/Getting+started+guide.pdf, after created Hana One instance from AWS, we need to Log on to the SAP HANA One Portal Console to configure Hana One, wait till Initial HANA settings are updated then I can see the instance status from the HANA One Console. These steps worked a few months ago! But for the Hana One instances I created in the recent 2 days, Instance Status can not be showed in the Hana One Console even after I waited a whole night. And I tried to reboot the instance, still not work. [it is always said : getting cpy/memory/disk usage...]
And I cannot use the system user password I set in the Hana One Console to connect to hana:
* 10: authentication failed SQLSTATE: 28000
So I guess the init steps are not done successfully.

**Comment by thecodester** [comment]
What tutorial does this relate to?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
