### ISSUE TITLE
Create a Global ABAP Class

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#3080]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-create-new-class.html

Please specify the step you are referring to
 Step 4: Instantiate the class
"Still in your program, create an instance of class zcl_invoice_retrieval using the new operator"

Step 2 included this instruction:
"In the run method, create a local variable of the type zcl_invoice_retrieval:data: invoices type ref to zcl_invoice_retrieval."

That statement is still in the run method which then leads to a syntax error once the line "data(invoices) = new ZCL_INVOICE_RETRIEVAL( )." is copied into the run method.

Should this therefore be more explicitely worded so that the DATA-line either gets commented out or replaced by the new code?

**Comment by BaerbelW** [comment]
In Step 7 of the same tutorial ("Step 7: Format your code") the hint "If you want to specify your formatting settings, you can do this in the project’s properties. Right-click on the Project in the Project Explorer and choose Properties." appears twice.

P.S.: not having used Github before is it okay to just add more suggested tweaks to the same issue as I did just now or should each go into a separate one?

**Comment by BaerbelW** [comment]
One more comment: it may just be me not fully understanding what the code is supposed to look like from one step to the next, but it seems that the code snippets shown for the statements in method RUN in the screenshots are not consistent as one works through the steps.

**Comment by julieplummer20** [comment]
Hi Baerbel, No it's not you, it's me. I wanted to make the code compliant with the new 7.40 syntax, eg for Inline Declarations. I then failed to make all the screenshots consistent.
I have updated the tutorial with all your corrections and pushed to QA. If everything works out, I will submit Pull Request to Prod. tonight, so it should look better by tomorrow morning.
Thanks a lot for your feedback; this is really helpful. "is it okay to just add more suggested tweaks...?" - sure, no problem, whatever works for you at the time.
Best wishes
Julie.

**Comment by julieplummer20** [comment]
Sorry, am getting a error when I push to Prod. Am out of office tomorrow, but will resolve on Monday.

**Comment by BaerbelW** [comment]
Thanks, Julie!

**Comment by julieplummer20** [comment]
Hi all, I have simplified the validation and pushed this to QA. If it looks OK, I'll submit the Pull Request pronto. Thanks for the feedback, [Baerbel](https://github.com/BaerbelW) - makes the tutorials more robust. (PS I'll look at the other issue, re SEPM_DG asap).
Julie.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
