### ISSUE TITLE
abap-dev-create-new-class : Users have problems with Validation

### ISSUE THREAD

**Issue by julieplummer20** [SAPDocuments/Tutorials#3086]
Hi colleagues,
Looping in [f4abap](https://github.com/f4abap),  [BaerbelW](https://github.com/BaerbelW)
The validation seems very intolerant. Here is the code Florian entered:
TYPES: ty_table_of_customers TYPE STANDARD 
TABLE OF snwd_bpa WITH DEFAULT KEY.
METHODS get_customers_from_db 
RETURNING VALUE(result) TYPE ty_table_of_customers.

TYPES: ty_table_of_customers TYPE STANDARD 
TABLE OF SNWD_BPA WITH DEFAULT KEY.
METHODS get_customers_from_db
RETURNING
VALUE(result) type ty_table_of_customers.

The only difference seems to be a carriage return after "RETURNING". 
What can be done? 
2 users have now complained about this (see above) - it is very frustrating for them.
Thanks Julie.

**Comment by thecodester** [comment]
Thanks. I have added an issue about this and will update when I hear.

**Comment by BaerbelW** [comment]
This is what I had - very similar to Florian and with one line-break less in the types-statement:
TYPES: ty_table_of_customers TYPE STANDARD TABLE OF SNWD_BPA WITH DEFAULT KEY.
METHODS get_customers_from_db
RETURNING VALUE(result) type ty_table_of_customers.

I had also tried with the methods-definition all in one line which it didn't "like" either.

**Comment by BaerbelW** [comment]
Hi All!
Here is another example for a rather intolerant validation.

Tutorial - Create a Data Element:
https://developers.sap.com/tutorials/abap-dev-adt-create-data-element.html

I had the solution as this which gave an error:
LOOP AT Booking_list ASSIGNING FIELD-SYMBOL(<booking>).

The culprit? Simply the lower case "l" in "_list". Once I switched that to upper case it was happy.

Could the validations be done case-insensitive as a general rule? Case doesn't matter for the ABAP-syntax so it shouldn't for these exercises.

Thanks!

**Comment by thecodester** [comment]
I will request this feature. Thanks for the feedback.

**Comment by thecodester** [comment]
Soon you will be able to create matches that ignore whitespace, or create your own regex. But in the meantime, exact match means exact match.
