### ISSUE TITLE
Connect to OData service on Neo using SAP S/4HANA Cloud SDK

### ISSUE THREAD

**Issue by danielbrumusescu** [SAPDocuments/Tutorials#3087]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-odata-service-neo.html

Step 1: Write the CostCenterServlet

Hi,

The `ErpEndpoint `class no longer exists in the latests sap s4hana sdk framework:
```
            <dependency>
                <groupId>com.sap.cloud.s4hana</groupId>
                <artifactId>sdk-bom</artifactId>
                <version>2.9.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

I used the `com.sap.cloud.sdk.s4hana.connectivity.ErpConfigContext` class instead, which worked.
```
 final ErpConfigContext erpConfigContext=new ErpConfigContext();
 ODataQueryBuilder.withEntity.................execute(erpConfigContext)....
```

**Comment by karstenmelato** [comment]
This content is outdated.

**Comment by thecodester** [comment]
@karstenmelato Will you be updating?

**Comment by karstenmelato** [comment]
@thecodester It's updated with my last request

**Comment by thecodester** [comment]
https://github.com/SAPDocuments/Tutorials/pull/3099
