### ISSUE TITLE
Add a Database to Your Business Application

### ISSUE THREAD

**Issue by timojoh** [SAPDocuments/Tutorials#3088]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-03-add-database.html

Hi,

I followed the steps of this tutorial and everything works till the last step. When I try to receive data in the SAP Fiori Launchpad I get an error "No Connection to database" and under odata/v2/CatalogService/Books it is followed by "CDSRuntimeException.NO_CONNECTION". 

Edit: It seems like the same error occurs during this tutorial: https://developers.sap.com/tutorials/odata-06-add-data-odata-service.html. 

Any ideas how to fix this?

Thanks!

**Comment by Apfohlmann** [comment]
Hi @timojoh,

thank you for your question. 👍 

The tutorial works for me. I completed this two tutorials before:
[https://developers.sap.com/tutorials/cp-apm-01-create-business-service.html](https://developers.sap.com/tutorials/cp-apm-01-create-business-service.html
)
[https://developers.sap.com/tutorials/cp-apm-02-add-ui.html](https://developers.sap.com/tutorials/cp-apm-02-add-ui.html)

Did you also complete this before?

It is important not to skip or change the order of completing the steps mentioned inside the tutorial - In case you did it that way. 

Best regards,
André

**Comment by timojoh** [comment]
Hi @Apfohlmann 

Thank your for your time and response. 

Yes, I completed the previous tutorials. Any other ideas? 

Best regards,
Timo

**Comment by Apfohlmann** [comment]
Hi @timojoh,

Thank you for your further investigations.

@qmacro can you help us out?

Best regards,
André

**Comment by Apfohlmann** [comment]
@thecodester please close the issue.
