### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by joysonds** [SAPDocuments/Tutorials#3090]
Tutorial URL: https://developers.sap.com/tutorials/xsa-create-user-provided-anonymous-service.html

Please specify the step you are referring to : Step 4: SPS02 or lower - Create a User-Provided service using the XS CLI

We are creating a service called CROSS_SCHEMA_PRODUCTS as per the examples given. However in the first line it mentions "**CROSS_SCHEMA_LOCATIONS**" instead. 

Similarly in the second command instead of accessing schema "PLAIN" it shows the schema as "**LOCATION_TEST**" which is incorrect. 

Kindly address the above inconsistencies in the tutorial

**Comment by Lsubatin** [comment]
Done
