### ISSUE TITLE
Create a Business Service Using CDS

### ISSUE THREAD

**Issue by zlosch** [SAPDocuments/Tutorials#3091]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-01-create-business-service.html

Please specify the step you are referring to

In Step 4, running the service failed without an error message. There was just a short notification in the Web IDE, which immediately disappeared when clicked. Neither console.log not run.log contained any information.

I then played around with the project in the Web IDE and tried also to build the srv module. This failed with `Could not create the 'bookshop-bookshop-hdi-container-D0oRdR+pMxiYd6NYDr' instance of the 'hana' service type for the 'bookshop-hdi-container' resource. No hdi-shared plan available found in this space.`

Assigning the entitlement for hdi-shared to the subaccount in the cockpit fixed the issue. Afterwards, also the service run was ok.

The reason for the missing entitlement was that I deleted the subaccount that was created in the initial trial onboarding. Afterwards, I created a new CF subaccount. But it seems that some steps are done during the trial onboarding, which have to be manually replicated afterwards. So far, I've noticed this for entitlements (application runtime, and now hdi-shared), but there might be others as well.

Proposal:
- Improve Web IDE run step to provide details why the run failed
- Make prerequisites (required entitlements) clear in the tutorial.
- Support re-creating the trial subaccount with the same settings / entitlements as in the initial onboarding

If you have any questions, contact me here or SAP-internally.

**Comment by Apfohlmann** [comment]
@zlosch thank you for your big feedback. We will improve the tutorial and mention the hdi-shared entitlement inside the tutorial.

We will also look at your suggestion about re-creating the trial subaccount.

Best regards,
André

**Comment by Apfohlmann** [comment]
@thecodester this ticket can be closed.
