### ISSUE TITLE
Add a Database to Your Business Application

### ISSUE THREAD

**Issue by zlosch** [SAPDocuments/Tutorials#3092]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-03-add-database.html

Please specify the step you are referring to

Step 2: Workspace Preferences -> Features is now called Extensions

<img width="299" alt="screenshot 2019-02-15 at 15 28 07" src="https://user-images.githubusercontent.com/189945/52862776-58d72300-3136-11e9-9718-18ef204519a1.png">

**Comment by Apfohlmann** [comment]
@zlosch  thank you. We just updated the tutorial.

@thecodester this issue is solved.
