### ISSUE TITLE
SAP Web IDE Full-Stack: tutorial needs product name update

### ISSUE THREAD

**Issue by jhornik** [SAPDocuments/Tutorials#3096]
@jonathanbaker7 

The tutorial: [Open SAP Web IDE in SAP Cloud Platform](https://developers.sap.com/tutorials/sapui5-webide-open-webide.html) needs to be updated with the new product name of Web IDE, including screen shots. 

**SAP Web IDE Full-Stack**

![screenshot_new_webide](https://user-images.githubusercontent.com/26198200/52937647-65db5880-3368-11e9-9238-5409b621d4e4.png)

**Comment by jhornik** [comment]
I will make the update today. I'll notify here when the changes are implemented.

**Comment by thecodester** [comment]
You can just close the issue :-)
