### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by Vadoid** [SAPDocuments/Tutorials#3100]
Hello,

Following the tutorial, while building DB module keep getting errors (on SPS03):

> Error: Failed to parse JSON object in SERVICE_REPLACEMENTS: SERVICE_REPLACEMENTS contains duplicate entries for the key ServiceName_1

What could be the cause of this?

Here is the mta.yaml:

>  ID: HA300
> _schema-version: '2.0'
> description: HA300 Training
> version: 0.0.1
> modules:
>   - name: db
>     type: hdb
>     path: db
>     requires:
>       - name: hdi_db
>         properties:
>           TARGET_CONTAINER: '~{hdi-container-name}'
>       - name: cross-container-service-1
>         group: SERVICE_REPLACEMENTS
>         properties:
>           key: ServiceName_1
>           service: '~{the-service-name}'
>       - name: CROSS_SCHEMA_EPM_MODEL
>         group: SERVICE_REPLACEMENTS
>         properties:
>           key: ServiceName_1
>           service: '~{ha300-service-name}'
> resources:
>   - name: hdi_db
>     parameters:
>       config:
>         schema: DB
>     properties:
>       hdi-container-name: '${service-name}'
>     type: com.sap.xs.hdi-container
>   - name: cross-container-service-1
>     parameters:
>       service-name: CROSS_SCHEMA_EPM_MODEL
>     properties:
>       the-service-name: '${service-name}'
>     type: org.cloudfoundry.existing-service
>   - name: CROSS_SCHEMA_EPM_MODEL
>     type: org.cloudfoundry.existing-service
>     properties:
>       ha300-service-name: '${service-name}'
> 
> 

Thanks.

**Comment by Lsubatin** [comment]
Hi, 

As the error message says, you are duplicating the definition for  ServiceName_1, so you have the same logical definition pointing at two different services. These resources also seem to be duplicate by the way. 

Please post requests for help in answers.sap.com. This channel is for feedback on tutorials.

Lucia.

**Comment by Vadoid** [comment]
Well, the tutorial explicitly says use ServiceName_1, so I am not sure what is duplicated. Posting full mta.yaml in tutorial would certainly help, as step by step doesn’t seem to work.

**Comment by Vadoid** [comment]
Just to be clear - on 9.png there is cross-container-service-1 which by default has key ServiceName_1, so your explanation re tutorial isn't clear.

**Comment by Lsubatin** [comment]
That's an interesting way of asking for help... 

There is a full yaml example in the tutorial. You are defining replacements for ServiceName_1 **twice**. You are referencing the same service **twice** too in the resources. 

Nothing in the tutorial would end up in a yaml like yours with duplicates, so don't blame it on a step by step you clearly did not follow.

**Comment by Vadoid** [comment]
As you can see on **9.png** there is a definition of cross-container-service-1 which is automatically generated and has a key of ServiceName_1 and CROSS_SCHEMA_PRODUCTS with SERVICE_REPLACEMENTS and key ServiceName_1.
So the screenshots for SP03 will be rather different.

**Comment by Lsubatin** [comment]
ServiceName_1 is only once in 9.png and also in the sample yaml. 

You can have multiple user provided services, not just the same logical name twice in the service replacements.

Take luck, 
Lucia.

**Comment by nunopereira23** [comment]
Hi Lucia (@Lsubatin), 
I'm getting a similar issue.
However mine says does not define a key for element 0.

Error: Failed to parse JSON object in SERVICE_REPLACEMENTS: SERVICE_REPLACEMENTS does not define a key for element 0

![mta](https://user-images.githubusercontent.com/25822028/175984126-675cb9d1-af2d-49f2-90be-b55d307fae28.png)
Here is my mta, do you have any clue?

Thanks in advance Lucia
