### ISSUE TITLE
HANA Webide not working 

### ISSUE THREAD

**Issue by vinita-k** [SAPDocuments/Tutorials#3112]
HI 
There I am opening a new issue as my previous one is still not resolved 
Here is the link to the old one:
https://github.com/SAPDocuments/Tutorials/issues/2894
Ihave installed express edition and below is the screenshot of the command run 

ls -la /usr/sap/HXE/home/
![image](https://user-images.githubusercontent.com/23621930/53047586-9bfb1280-34f7-11e9-953b-ee8dd9fbff68.png)

ls -la /var/tmp
![image](https://user-images.githubusercontent.com/23621930/53047601-a3bab700-34f7-11e9-8ddb-f30fddd6bafe.png)

ls -apps and xs - apps | grep webide
![image](https://user-images.githubusercontent.com/23621930/53047776-10ce4c80-34f8-11e9-993b-ead290918709.png)
![image](https://user-images.githubusercontent.com/23621930/53047801-1deb3b80-34f8-11e9-9d32-02ce0eb74c63.png)

xs-admin-login

I suspend using the option as below in VMware workstation 15 and I am using Windows 10

but when I restarted this time thankfully this time it was at the last saved version

Now I am still unable to login to carry out doing the development

Issues :

When I try to practice the below tutorials as mentioned in the link

https://developers.sap.com/tutorials/xsa-connecting-webide.html

it asks to check web ide using the link below

https://hxehost:53075/

This link comes up when I use command Xs-admin-login

https://hxehost:39030

Both the link Gives an error that;' site cannot be reached' as seen below:
![image](https://user-images.githubusercontent.com/23621930/53047872-44a97200-34f8-11e9-85f0-dbeab1ca019c.png)

What I have been trying to do is to be able to do the below exercises

https://s3.xopic.de/opensap-public/courses/5gfdg56didOQhzZBUh1DJl/rtfiles/3Hd1651Hy5RrCahDe9h7CA/openSAP_hana7_Master_HANA2_SPS03_2_HandsOn_Hosted_Training.pdf

I can't seem to get the system to work

If you could pl take some time to help would be greatly appreciated

Also some questions for my understanding

-  Is Hana express edition only front end or it has backend HANA DB as well how can we practice calculation views etc?
-  What is the reason to use WebIde in HANA express edition VS using cloud based Webide?

Regards
Vinita

**Comment by Lsubatin** [comment]
Vinita,
This kind of issue belongs in answers.sap.com - this is not the proper channel for support.

I have replied here: https://answers.sap.com/questions/745374/hana-express-edition-installation-issues-and-askin.html 

The system you have has both the database and Web IDE, which is the new editor that allows you to do calculation views. I suggest taking a look at: https://blogs.sap.com/2017/09/04/xs-advanced-for-not-so-dummies/ and https://www.youtube.com/watch?v=eGOxt_acA7o&list=PLoc6uc3ML1JR38-V46qhmGIKG07nXwO6X . There are also plenty of similar questions on answers.sap.com

Best, 
Lucia.

**Comment by choikyow** [comment]
From installation troubleshooting guide,

Normally it only takes a few minutes for XSA services to start. However. depending on your machine, it can take over 30 minutes for XSA services to begin. If the service doesn't show STARTED and doesn't show 1/1 instances, keep waiting until the service is enabled.

Also check,

1. Host name file has correct IP address.

2. Restart the PC to start fresh. Check if your instance in VMWare has enough CPU and memory configured.

3. Using the Tool 1. Start analyzing the SAP Web IDE environment by running the following command: xs check-webide
