### ISSUE TITLE
Build a Business App by Reusing a CDS Model

### ISSUE THREAD

**Issue by agl-phenr** [SAPDocuments/Tutorials#3118]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-06-reuse-extend.html

Please specify the step you are referring to Step 8 - Add an HTML5 template

By creating a new HTML5 module I see the OData Service created on previous steps.

![image](https://user-images.githubusercontent.com/42214365/53086247-a79d0800-34fc-11e9-8faa-7bd45e45c258.png)

I have attached the project .

[SampleApp.zip](https://github.com/SAPDocuments/Tutorials/files/2884280/SampleApp.zip)

Best Regards,
Pietro

**Comment by Apfohlmann** [comment]
Hi @agl-phenr,

thank you for your message. We will add images to this Step for our next update.

Do you think about other additional information?

Best regards,
André

**Comment by agl-phenr** [comment]
hi @Apfohlmann,

By reviewing my issue posted, I saw I mistyped it. 
What I meant was I see no OData service created at the previous steps.
I was wondering if you might guide me through the fixing.

In regards to additional info, I got nothing so far as I stuck at this point.

Best Regards,
Pietro

**Comment by Apfohlmann** [comment]
@agl-phenr,

in this tutorial you are just creating the template for your Data. If you want to add data to your OData service. There is a link at the very bottom of the tutorial referring to this tutorial:

[https://developers.sap.com/tutorials/odata-06-add-data-odata-service.html](https://developers.sap.com/tutorials/odata-06-add-data-odata-service.html)

Does this help you?

Best regards,
André

**Comment by Apfohlmann** [comment]
@thecodester it looks like this issue is not relevant anymore. Please close the issue.
