### ISSUE TITLE
Onboarding a computer as the IoT thing

### ISSUE THREAD

**Issue by mhmmdmz** [SAPDocuments/Tutorials#3121]
Tutorial URL: https://developers.sap.com/tutorials/iotae-comp-thingmodeler0.html

(Please specify the step you are referring to) 
Step 5: Add your computer as a new thing

Seems like the Neo environment has been turned off. We don't have access to create new instance or proceed with other steps in tutorial.

**Comment by maxstreifeneder** [comment]
@marcuscbehrens can you please support here?

**Comment by mhmmdmz** [comment]
Hi ... any luck with this? I'm trying to run a session with a large group of people and we're stuck with the Neo environment not being available. Looking at SAP to bail us out ... as we're learning and promoting SAP technologies.

**Comment by marcuscbehrens** [comment]
i had no problem creating a new thing: This thing has been created using the following provider:SAP Cloud Platform IoT Service for Neo Environment
Thing ID:
Device ID:
Token:
FAC5C9EC9970469EB53EE5388C36EEDB
FAC5C9EC9970469EB53EE5388C36EEDB
b4b75c375f4b9ae5ac24438e

**Comment by mhmmdmz** [comment]
Thank you for your reply. However not just me, it’s a group of ppl from various locations who get an error while creating a new thing. If you see the status of the service it is disconnected. When I use python to send data out, it gives me 202 which means the data is being queued and that’s forever.

**Comment by marcuscbehrens** [comment]
Can you please provide more specific description of what goes wrong or open a ticket on iot-bsv-ops-onb or call my skype for business at marcus.behrens@sap.com?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. I hope you were able to contact Marcus off line and resolve the issue.

If you still have questions, feel free to reopen the issue.
