### ISSUE TITLE
Add a Portal Widget

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Tutorials#3122]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-advanced-embed-widget.html

Please specify the step you are referring to - Step 1 - between 6 / 7 I am asked for PW. And no matter what PW I try I can't "get through" 
I try s-user PW (both S-user with and without ...trial) No matter what error.

KR s0020098827trial / Michael ;-)

**Comment by LindsayBert** [comment]
Hi Michael - I didn't write this particular tutorial but I have written something similar so I'll try and help you. I checked out Step 1 (between 6 and 7).  This is referring to adding a widget to the page section.  Are you being asked to add your password when you try and do this?
Thanks Lindsay

**Comment by mts2605** [comment]
Hi Lindsay
Yes, when adding the supplierlookup, i am asked for PW.
BR Michael

**Comment by LindsayBert** [comment]
Hi Michael I suspect that it has something to do with access to where the widget was deployed to.  I've written to Ido Shemesh who wrote this tutorial and I've asked him to help.

Thanks Lindsay

**Comment by mts2605** [comment]
Hi Lindsay (& Ido) 
I do not think more time should be used on this. I suspect cookies/logon from an earlier S-user access to ES5 to be the reason for the problem. I got it to work when this logon was deleted from my browser. (A bit scary what Chrome stores from years ago when I was working another place...)
Thanks for your assistance!
Best Rgds
Michael
