### ISSUE TITLE
Start SAP HANA, express edition Server

### ISSUE THREAD

**Issue by ZEdwin** [SAPDocuments/Tutorials#3123]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-getting-started-vm-xsa.html

Please specify the step you are referring to

Installation always fails at "Start SAP HANA, express edition Server" --> "Step 10: Complete the installation".
I have entered the passwords according to the requirements (Numbers and letters only). But after proceeding with the configuration, I never get the message "Congratulations! SAP HANA, express edition 2.0 is configured". And also not the "Fail to retrieve certificate".

It just stops after trying to change the HXE password. The message I get is that the Password was already changed and the new password is invalid?

![image](https://user-images.githubusercontent.com/5278654/53153042-7c2b2380-35b7-11e9-838c-00144a121052.png)

If I then login again to the VM with the hxeadm user, the script takes me through the script again to change the passwords for the master, but then it fails with the message 
"Failed to change hardware key".

![image](https://user-images.githubusercontent.com/5278654/53153303-40dd2480-35b8-11e9-83f6-e628bfdb8d8b.png)

**Comment by JCurrie27** [comment]
Hello @ZEdwin: There are some Q@A posts in the community mentioning similar errors. Did you see https://answers.sap.com/questions/319954/hana-express-vm-configuration-error.html ? In that Q&A post, insufficient RAM was causing login issues. Can you verify the available RAM on your host machine?

**Comment by ZEdwin** [comment]
Should be plenty.

![image](https://user-images.githubusercontent.com/5278654/53175187-bf9f8500-35eb-11e9-839c-5f352535fba7.png)

But maybe I shouldn't have assigned all 32G to the VM... I'll try again with the default 16 or perhaps 24.
I hope that fixes the issue. I'll let you know!

**Comment by ZEdwin** [comment]
Tried 16G and 6 cores: Failed.
Tried 24G and 2 cores: Failed.

**Comment by JCurrie27** [comment]
@TerryNing - can you assist @ZEdwin with these VM scenario (server + applications) installation error messages?

**Comment by Lsubatin** [comment]
This belongs in the community (answers.sap.com) for support.
What is the hidden host? Is that an IP address?

**Comment by ZEdwin** [comment]
Question: Is deleting the hxexsa instance from the disk enough, or are more steps necessary to clean my PC for a new instalment? Maybe some old junk in the registry or somewhere else is messing up the re-install?

**Comment by ZEdwin** [comment]
> This belongs in the community (answers.sap.com) for support.
> What is the hidden host? Is that an IP address?

Yes, it's the IP adress...

**Comment by Lsubatin** [comment]
If you right click on the VM from VMware it will give you the option to delete anything it form disk. Since it's a VM, it does not do anything with your laptop's registry so you can just import it again.

Before you start it, try changing the network to NAT. If you still have problems there, run sudo ifconfig and please open a question in the community with the details.

**Comment by JCurrie27** [comment]
Hi @ZEdwin - as Lsubatin suggests, if these installation issues are still unresolved, please add questions to the HXE support community forum at ([answers.sap.com](https://answers.sap.com/index.html)). 
The community has more visibility than this GitHub thread, and is monitored by technical experts.
I'm closing this issue - we can continue troubleshooting these issues on (answers.sap.com).
