### ISSUE TITLE
SAP HANA, express edition, in Google Cloud Platform Launcher (Database + XS Advanced)

### ISSUE THREAD

**Issue by ssurampally** [SAPDocuments/Tutorials#3126]
Tutorial URL: https://developers.sap.com/tutorials/hxe-gcp-getting-started-launcher-xsa.html

Hi Lucia, I am trying to find out the step for Optional installations like SDI,  EA designer etc., I remember that, it was part of this tutorial or may be in another one. can you navigate me to that?

**Comment by ssurampally** [comment]
also is there a tutorial to upgrade my HANA Express web ide to newer version in GCP VM?

**Comment by Lsubatin** [comment]
Hi Sreekanth, instructions for additional plug ins are here (I'll add them to the tutorial now that you mention it):  [https://developers.sap.com/tutorials/hxe-ua-packages-binary.html](https://developers.sap.com/tutorials/hxe-ua-packages-binary.html )

I have two blog posts on upgrading web ide:

- Just Web IDE: https://blogs.sap.com/2018/03/09/upgrading-web-ide-in-hana-express/ 
- Updating HXE entirely: https://blogs.sap.com/2019/01/18/updating-sap-hana-express-edition-in-the-cloud-to-play-with-the-cap-model/

**Comment by ssurampally** [comment]
Thanks Lucia, I book marked them now.
