### ISSUE TITLE
Use the Similarity Scoring with the Text Feature Extraction API from a REST Client

### ISSUE THREAD

**Issue by jastill** [SAPDocuments/Tutorials#3127]
Tutorial URL: https://developers.sap.com/tutorials/cp-mlf-rest-similarity-text.html

Please specify the step you are referring to
Step 3, reference Image Feature Extraction in the step title and first line, should it be Text Feature Extraction?

**Comment by adadouche** [comment]
Hi @jastill 

thanks for the feedback, I just pushed a corrected version (copy/paste issue) : https://github.com/SAPDocuments/Tutorials/commit/1f37c7c7e6a399566ed5024e4b3f8359ac3e4c56

Thanks again!
