### ISSUE TITLE
Commit your project to Git and deploy to the cloud

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Tutorials#3129]
Tutorial URL: https://developers.sap.com/tutorials/teched-2016-5.html

Please specify the step you are referring to - 18 (Step 18: Open the active version of your app)

I do not understand why I can not validate a link to a working app:
https://businesspartners-s0020098827trial.dispatcher.hanatrial.ondemand.com/index.html?hc_reset#/BusinessPartnerSet/0100000031

BR Michael

**Comment by thecodester** [comment]
In the meantime we have removed this tutorial -- since it is from 2016. Sorry for the confusion.
