### ISSUE TITLE
 Tutorials/tutorials/hana-setup-cloud/hana-setup-cloud.md

### ISSUE THREAD

**Issue by Larcen** [SAPDocuments/Tutorials#313]
Hello all,

I'm deploying a new instance of SAP HANA Developer Edition 1.0 SPS 10 on Azure cloud (D13 VM: 8CPU and 56GB). The deploying process finishes successfully, but I can't connect to the instance on HTTP ports 80 and 8000. When I connect to the VM via SSH I get the following error messages:

```
The Appliance Agent detected an error and terminated.
When asked, please provide the file /tmp/applianceagent_20160512-082312.tar.bz2.
```

 
I have extracted the bz2 file and found these errors in "appliancedeploy.log":
```

    Renaming SAP HANA instance failed!
      Renaming master failed!
Renaming of SAP HANA instance failed.
  SAP HANA System rename failed
    Error occurred while executing SAP HANA System rename.
    Failed to rename the system.
 
You can send feedback to SAP with this form: https://sid-hdb:1129/lmsl/HDBLCM/HDB/feedback/feedback.html
Log file written to '/var/tmp/hdb_HDB_hdblcm_register_rename_system_2016-05-12_08.19.11/hdblcm.log' on host 'sid-hdb'.
error in /tmp/applianceagent/scripts/Database.sh: hdblcm with stdin /tmp/appagenttmp/hdblcm.xml : failed with exit code 1


``` 
The "hdblcm.log" and "hdbrename.log" log files show errors related with "process hdbesserver HDB Extended Storage Server".

 Could somebody help me identifying and solving this issue?

Thanks in advance.

**Comment by ccmehil** [comment]
Can you send the log-files to cal.admin@sap.com
