### ISSUE TITLE
Trigger the Endpoints from an SAPUI5 App

### ISSUE THREAD

**Issue by jastill** [SAPDocuments/Tutorials#3130]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-rabbitmq-extend-producer-ui.html

Please specify the step you are referring to 2.

Coding seems to have a formatting issue. I get an error due to line 52, This is the code I ended up using:

      sap.ui.getCore().attachInit(function () {
        new sap.m.App({
          pages: new sap.m.Page({
              title: 'Producer',
              content: new sap.m.IconTabBar({
                items: [
                  new sap.m.IconTabFilter({
                    text: "Send Messages",
                    key: "send",
                    content:
                        new sap.m.VBox({
                          items: [
                              new sap.m.Label({
                                  text: 'Queue',
                                  width: '100%',
                              }),
                              new sap.m.Select({
                                  width: '100%',
                                  items: [
                                    new sap.ui.core.Item({
                                      key: 'Queue_1',
                                      text: 'Queue_1'
                                    }),
                                    new sap.ui.core.Item({
                                        key: 'Queue_2',
                                        text: 'Queue_2'
                                    }),
                                    new sap.ui.core.Item({
                                        key: 'Queue_3',
                                        text: 'Queue_3'
                                    })
                                  ]
                              }),
                              new sap.m.Label({
                                  text: 'Require response',
                                  width: '100%',
                              }),
                              new sap.m.Switch({
                                  width: '100%',
                              }),
                              new sap.m.Label({
                                  width: '100%',
                                  text: 'Message'
                              }),
                              new sap.m.Button({
                                  width: '100%',
                                  text: 'Send',
                                  type: 'Accept'
                              })
                          ]
                        })
                  }),
                  new sap.m.IconTabFilter({
                    text: "Outbox",
                      key: "outbox",
                    content: new sap.m.Table({
                      columns: [
                        new sap.m.Column({
                          header: new sap.m.Text({
                            text: 'Queue'
                          })
                        }),
                        new sap.m.Column({
                          header: new sap.m.Text({
                            text: 'Message'
                          })
                        }),
                        new sap.m.Column({
                          header: new sap.m.Text({
                            text: 'Correlation ID'
                          })
                        }),
                        new sap.m.Column({
                          header: new sap.m.Text({
                            text: 'Response'
                          })
                        })
                      ],
                    })
                  })
                ]
              })
            }).addStyleClass('sapUiSmallMargin')
        }).placeAt('content')
      });

**Comment by IObert** [comment]
Hi @jastill,

nice catch! The code snipped should look like this:
```
sap.ui.getCore().attachInit(function () {
  new sap.m.App({
    pages: new sap.m.Page({
        title: 'Producer',
        content: new sap.m.IconTabBar({
          items: [
            new sap.m.IconTabFilter({
              text: "Send Messages",
              key: "send",
              content:
                  new sap.m.VBox({
                    items: [
                        new sap.m.Label({
                            text: 'Queue',
                            width: '100%',
                        }),
                        new sap.m.Select({
                            width: '100%',
                            items: [
                              new sap.ui.core.Item({
                                key: 'Queue_1',
                                text: 'Queue_1'
                              }),
                              new sap.ui.core.Item({
                                  key: 'Queue_2',
                                  text: 'Queue_2'
                              }),
                              new sap.ui.core.Item({
                                  key: 'Queue_3',
                                  text: 'Queue_3'
                              })
                            ]
                        }),
                        new sap.m.Label({
                            text: 'Require response',
                            width: '100%',
                        }),
                        new sap.m.Switch({
                            width: '100%',
                        }),
                        new sap.m.Label({
                            width: '100%',
                            text: 'Message'
                        }),
                        new sap.m.Button({
                            width: '100%',
                            text: 'Send',
                            type: 'Accept'
                        })
                    ]
                  }).addStyleClass('sapUiSmallMargin')
            }),
            new sap.m.IconTabFilter({
              text: "Outbox",
                key: "outbox",
              content: new sap.m.Table({
                columns: [
                  new sap.m.Column({
                    header: new sap.m.Text({
                      text: 'Queue'
                    })
                  }),
                  new sap.m.Column({
                    header: new sap.m.Text({
                      text: 'Message'
                    })
                  }),
                  new sap.m.Column({
                    header: new sap.m.Text({
                      text: 'Correlation ID'
                    })
                  }),
                  new sap.m.Column({
                    header: new sap.m.Text({
                      text: 'Response'
                    })
                  })
                ],
              })
            })
          ]
        })
          })
  }).placeAt('content');
});
```

Thanks for reporting! I'll fix it asap.

Regards,
Marius

**Comment by IObert** [comment]
Thanks for reporting this. I just fixed the issue and you should be able to see the updated version shortly
