### ISSUE TITLE
Import your SAP Build project into SAP Web IDE

### ISSUE THREAD

**Issue by Funkmyster** [SAPDocuments/Tutorials#3134]
Tutorial URL: https://developers.sap.com/tutorials/build-import-webide.html

In Step 8: Run your application:

Mock data is not deployed with demo application when following tutorial.

The documentation refers to testFLPService.html instead of testFLPServiceMockServer.html

**Comment by rbrainey** [comment]
The automated BUILD import to Web IDE is no longer supported.
