### ISSUE TITLE
Display Database Content and Run SQL Queries

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#3141]
Tutorial URL: https://developers.sap.com/tutorials/abap-display-data-queries.html

Please specify the step you are referring to: Step 2 - Select a database table

The table specified in the tutorial - snwd_so_inv_item - doesn't seem to be filled via transaction SEPM_DG documented here: [The NetWeaver Enterprise Procurement Model - An introduction](https://www.sap.com/documents/2012/09/2a404253-5b7c-0010-82c7-eda71af511fa.html). How about using one of the tables actually filled with generated data instead? 

As an aside: the link to the documentation as shown in the tutorial - https://archive.sap.com/documents/docs/DOC-31458 - ends with a "document not found" message.

**Comment by julieplummer20** [comment]
Hi Baerbel,
Again, SEPM_DG_OIA_NEW or report RS_EPM_DGC_HANA_NEW should work.
I'll fix the link.
Is it ok if I close this?
Thanks Julie.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
