### ISSUE TITLE
Import your SAP Build project into SAP Web IDE

### ISSUE THREAD

**Issue by Ksandala** [SAPDocuments/Tutorials#3144]
Tutorial URL: https://developers.sap.com/tutorials/build-import-webide.html

Please specify the step you are referring to 1- Question

Answer to this question is the URL of BUILD service from SCP is 'https://account.hanatrial.ondemand.com/cockpit/#/home/service/build/overview' or 'https://account.hanatrial.ondemand.com/cockpit/#/acc/  <USER> /service/build/overview'. I hve tried both but none f them are accepted as answers.

Regards,
Krishna S

**Comment by mts2605** [comment]
Look very much forward to response to this, and my, questions regarding this issue...

**Comment by thecodester** [comment]
@rbrainey @mhassett92 Any ideas here?

**Comment by mts2605** [comment]
I tried the above mentioned also. First links tried was;

https://www.build.me/
https://www.build.me
https://www.build.me/splashapp
https://standard.build.me/

All failed...

**Comment by thecodester** [comment]
@Ksandala @mts2605 I have updated the tutorial. Can you try again? (One of those URLs is correct).

@rbrainey The rules used the regex-with-id-exact-match code and not the exact-match code (it would have been better for me to have used the contains code, but didn't think of it)

**Comment by mts2605** [comment]
@thecodester Thanks, now it works for me;-)

**Comment by Ksandala** [comment]
@thecodester  thanks, It is  working fine now..!
