### ISSUE TITLE
Test Hyperledger Fabric Chaincode API

### ISSUE THREAD

**Issue by nimble-123** [SAPDocuments/Tutorials#3146]
Tutorial URL: https://developers.sap.com/tutorials/blockchain-test-chaincode.html

Please specify the step you are referring to
- all steps

Problem
- Images are not shown/loaded. (404 error in chrome dev tools)

**Comment by heytombeck** [comment]
@thecodester - the images are appearing for me currently, can you see any issues?

**Comment by thecodester** [comment]
@nimble-123 Can you clear cache and try again?

**Comment by nimble-123** [comment]
my bad, clearing cache did the trick :) thx for this fast support!
