### ISSUE TITLE
Query options passed as URL param

### ISSUE THREAD

**Issue by grahamrobbo** [SAPDocuments/Tutorials#315]
I think this is not a good example - for several reasons.

For me, instead of ..
`items="{/Products?$orderby=ProductName&amp;$filter=UnitsInStock gt 0}"`

.. a better example would be ...
```
items="{
	path:'/Products',
	sorter:{
		path:'ProductName, descending: false
	},
	filters: [
		{
			path: 'UnitsInStock',
			operator: 'GT',
			value1: 0
		}
	]
}"
```
That way the formulation of the URL can be left entirely to the model control.

**Comment by akula86** [comment]
The sorter addition is a good one but after doing some digging, I found that the List item doesn't support the filter value as a binding path. 

I've modified the tutorial to use an `attachAfterRendering()` function in the view controller to create the filters. Definitely more readable. See the commit: https://github.com/SAPDocuments/Tutorials/commit/b22226472c7f0ea40f3be5ec73fdaf531c588fb4 and [updated tutorial](http://go.sap.com/developer/tutorials/hcp-webide-inserting-query-options.html)
