### ISSUE TITLE
Set up SAP Data Hub, trial edition 2.4

### ISSUE THREAD

**Issue by RandomThis** [SAPDocuments/Tutorials#3150]
Tutorial URL: https://developers.sap.com/tutorials/datahub-trial-v2-setup.html

Please specify the step you are referring to

All of them ... if I click Done it just scrolls back to the top of the screen but progress still shows 0%. I put the url in the answer block at the end and clicked "Submit Answer" and nothing happened.

Note the problem is with the tutorial behavior ... I was able to complete the actual Data Hub trial edition setup just fine.

**Comment by anishgupta85** [comment]
Hi ,
Did you really log in to the developers.sap.com and are shown above on the extreme right as the user?
Regards,
Anish

**Comment by RandomThis** [comment]
Hi Anish,
Yes I did. Tried again this morning to be sure. Same result. FYI my user name is different on SAP Community than here, but linked to the same email address.  When logged into developers.sap.com, I only see my name if I hover over the little user icon in the upper right of the screen. 

More info: I have tried in 2 different browsers: Chrome and Vivaldi. In Chrome I initially had a script blocker active but have now whitelisted the site. I refreshed a couple times and still no difference.  I have not set up any script blocker in Vivaldi.

I moved on to the next tutorial in the sequence and had the same problem.

Thanks for any help you can give!
Margaret

**Comment by anishgupta85** [comment]
Hi Margaret,
I am also using chrome and I don't have any problems.
Please restart your system or update the version of chrome.
Regards,
Anish

**Comment by RandomThis** [comment]
Hi Anish, I have tried restart, cleared cache, different computer. I now tried other tutorials. None of them work. I am definitely logged in on developers.sap.com and have an active SAP community profile.
This is apparently not an issue with your tutorial, but the tutorials in general not working for me. Is it possibly because I am logged in with P# rather than S#?

**Comment by RandomThis** [comment]
Hi Anish, I found the problem. I was connecting via a VPN. I haven't noticed any other issues with sap.com when I connect via VPN (my normal connection). But I could not get these tutorials to work. So I disconnected the VPN and connected directly through my ISP and now it is working.  I will close this issue. But it would be good for the tutorials to work even when connected by VPN.
