### ISSUE TITLE
Use abapGit to Transform ABAP Source Code to the Cloud

### ISSUE THREAD

**Issue by xtough** [SAPDocuments/Tutorials#3151]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-abapgit.html

The questionnaire in the last step has the wrong answer: I need a Github user, not a Google account, to create a new Git repository.

**Comment by niloofar-naseri** [comment]
@mervey45 could you please check this issue?

**Comment by mervey45** [comment]
@thecodester This issue is fixed, we can close it.
