### ISSUE TITLE
Create a Business Service with Node.js using Visual Studio Code

### ISSUE THREAD

**Issue by dtrefzer** [SAPDocuments/Tutorials#3153]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Hello and thanks a lot for the great tutorial! 
This node-functionality for the application programming model was exactly what we are looking for to migrate our products to the SAP cloud platform. 
I have one question though:
We rely heavily on Function Imports for our OData services. Is there a way to implement a custom handler for function imports in node.js yet? Like the srv.on("READ", "Books"... in the tutorial?
If you could point me in the right direction or confirm that the functionality will be implemented, it would help us a lot!

Kind regards,
Dominik Trefzer

**Comment by Apfohlmann** [comment]
Hi @dtrefzer,

thank you for asking the question.

I just looked it up at help.sap.com: [https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/a3c9699ea82a42d4bae0b1babf231015.html](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/a3c9699ea82a42d4bae0b1babf231015.html)

Does this help you?

**Comment by dtrefzer** [comment]
Hi @Apfohlmann,

thanks for your fast reply. 
You pointed me in the right direction there: we will handle function imports with a call of srv.use((req, res, nect) =>...) for the time being. Maybe they will be added to srv.on() directly in the future. 
But we can work with that and thanks again for your help.

Kind regards,
Dominik Trefzer

**Comment by Apfohlmann** [comment]
Hi @dtrefzer,

I am happy to help.

@thecodester you can close this issue.

Best regards,
André

**Comment by thecodester** [comment]
@dtrefzer If you are happy with Andre's help, feel free to close the issue. Thanks for the feedback.
