### ISSUE TITLE
Deploy SAP HANA as a Service

### ISSUE THREAD

**Issue by ssurampally** [SAPDocuments/Tutorials#3154]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-deploying-haas.html

I understand from this tutorial header note that, deploying HANA service on trial account is not available at this point of time, but I can use a service called  "HANA Schemas and HDI containers" right?  What difference it is going to make with these 2 services?

**Comment by Lsubatin** [comment]
Hi, the difference is that one is a database and the other is a schema. All of the database configurations are not possible in the trial as you have no access to the database basically. I would recommend this for further context:  https://blogs.sap.com/2018/10/16/yet-another-intro-to-hana-as-a-service/
