### ISSUE TITLE
Generate sensor data in SAP Data Hub, trial edition 2.4

### ISSUE THREAD

**Issue by BerndKaestner** [SAPDocuments/Tutorials#3155]
Tutorial URL: https://developers.sap.com/tutorials/datahub-trial-v2-pipelines-part01.html

Dear Anish,
In this tutorial I miss the buttons to complete each step like in the other tutorials, labeled as "Done". You can find an example in the attachment. Without these buttons the progress cannot be captured and the tutorial cannot be marked as complete.

Thanks and best regards,
Bernd
![complete_button_tutorial](https://user-images.githubusercontent.com/45342751/53594547-64493600-3b9b-11e9-8186-e95a56b61e57.JPG)

**Comment by anishgupta85** [comment]
Hi Bernd,
In this tutorial we did not put the done buttons explicitly as there was not a possibility for a question that could be asked.
That's why we left it.
Regards,
Anish

**Comment by thecodester** [comment]
@anishgupta85 For install-type tutorials, it is worth putting in DONE buttons only. Can you add?

**Comment by RandomThis** [comment]
@anishgupta85 : this tutorial is part of a "mission" but the mission cannot be completed unless this tutorial is marked as completed. As is, there is no way for the tutorial to be marked as completed.  Can you please add a similar question as you have at the end of the next part, like:

** Open the output Terminal. Copy any row from the output and paste it in the frame below and click on Submit Answer.** 

In this way the mission will allow to be completed. Thanks!!

**Comment by thecodester** [comment]
I see the DONE buttons were added, and I assume all is well, and you can complete the tutorial.

If you still have questions, feel free to reopen the issue.
