### ISSUE TITLE
Create Hyperledger Fabric Service Keys

### ISSUE THREAD

**Issue by prabhatpathania** [SAPDocuments/Tutorials#3157]
Tutorial URL: https://developers.sap.com/tutorials/blockchain-hlf-servicekeys.html

Please specify the step you are referring to:

Step 2: Create service key
Images are not available.

**Comment by thecodester** [comment]
I see the images. Perhaps clear cache and reload?

**Comment by thecodester** [comment]
Were you able to see images?

**Comment by heytombeck** [comment]
> Were you able to see images?

Yes, and without clearing my own cache too.

**Comment by thecodester** [comment]
@prabhatpathania What say you?

**Comment by prabhatpathania** [comment]
Yes, cache clear did not help on the same day.
I tried from different machines as well.
But it is visible now. :)
