### ISSUE TITLE
SAP HANA XS Advanced - Package your MTA application for transport

### ISSUE THREAD

**Issue by ksadayan** [SAPDocuments/Tutorials#3158]
Tutorial URL: https://developers.sap.com/tutorials/xsa-mta-package-transport.html

Transporting in Phases:
If I want to transport only the changes instead of the entire development artifacts, what options do I have ?

**Comment by Lsubatin** [comment]
This kind of question belongs in the community (and I have addressed this there too).  I would recommend explaining what you mean by "only the changes". A note: you transport an updated application, not the code.
