### ISSUE TITLE
Create your own Fiori Launchpad

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Tutorials#3160]
Tutorial URL: https://developers.sap.com/tutorials/teched-2017-fiori-create.html

Please specify the step you are referring to - Step 8 - Update the SAPUI5 version

After selection "Custom" - and waiting for minutes - the field for selecting 1.40.18 is blank / there are no values to select.

What to do?

![empty](https://user-images.githubusercontent.com/43760831/53681354-bcda1980-3ce8-11e9-8993-c80d835d1133.png)

**Comment by rbrainey** [comment]
This specific issue appears to be a Portal bug which will require opening a SAP ticket to be addresses.  I'm assigning this to Marius for further investigation.

**Comment by IObert** [comment]
Hi @mts2605,

thanks for your patience. As you might have noticed, this tutorial is outdated. 
We're currently evaluating if we should update it or simply remove it for good.

For now, I would suggest that you just skip this step. It seems that this step was added as a workaround for an issue in SAPUI5. This issue might have been resolved by now as the most recent SAPUI5 version is 1.65.

Thanks,
Marius

**Comment by thecodester** [comment]
@IObert I am closing the issue, since @mts2605 can proceed, but has the tutorial been updated?

**Comment by IObert** [comment]
We haven't prioritized this issue yet. Not sure when we're going to aim for the update as it is a larger task
