### ISSUE TITLE
Store sensor data in SAP Vora in SAP Data Hub, trial edition 2.4

### ISSUE THREAD

**Issue by BerndKaestner** [SAPDocuments/Tutorials#3164]
Tutorial URL: https://developers.sap.com/tutorials/datahub-trial-v2-pipelines-part04.html

Dear all,
In Step 2: Configure the SAP VORA Loader Operator you have to specify the different parameters for the SAP VORA Loader Operator. As I use the Google Could Storage I need to set the parameter "Storage service" to GCS but there is no such option in the value help. S3 seems to be support but not GCS. Please note that I am using SAP Data Hub, trial edition 2.3 (not 2.4). Is there a way to finish the exercise also with version 2.3 instead of 2.4?
Thanks and best regards,
Bernd

**Comment by fx5151git** [comment]
I think the best way now is to switch to 2.4, while our guide now is based on the newest version. And there are also a lot of things that will not work for 2.3.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
