### ISSUE TITLE
Install Optional Packages

### ISSUE THREAD

**Issue by rahul4sap** [SAPDocuments/Tutorials#3170]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-packages-vm.html

SAP HANA smart data integration | Install the Optional SAP HANA Smart Data Integration Package for SAP HANA, express edition

Link is broken

**Comment by thecodester** [comment]
@JCurrie27 Can we modify the title to "Install Option Packages for SAP HANA, express edition"?

**Comment by JCurrie27** [comment]
Broken links have been fixed.
