### ISSUE TITLE
Store sensor data in Cloud Storage in SAP Data Hub, trial edition 2.4

### ISSUE THREAD

**Issue by datajohngraham** [SAPDocuments/Tutorials#3171]
Tutorial URL: https://developers.sap.com/tutorials/datahub-trial-v2-pipelines-part02.html

Please specify the step you are referring to

One step is missed in the write up.    When connecting read file to 'to_string', image shows connect to terminal operator,  but steps to connect to terminal are not written.

**Comment by fx5151git** [comment]
already changed the image, Thank you for your suggestion.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
