### ISSUE TITLE
Try Out SAP Cloud Platform SDK for Android Wizard

### ISSUE THREAD

**Issue by mjturnr** [SAPDocuments/Tutorials#3177]
Tutorial URL: https://developers.sap.com/tutorials/cp-sdk-android-wizard-app.html

None of the images included in the tutorial are visible - they all return a 404 when accessed.

**Comment by thecodester** [comment]
I see all the images. Clear your cache perhaps?

**Comment by mjturnr** [comment]
> I see all the images. Clear your cache perhaps?

They're working for me now - thanks (I didn't even need to clear my cache :)
