### ISSUE TITLE
Create a UI that Consumes an Exposed ABAP Service

### ISSUE THREAD

**Issue by xtough** [SAPDocuments/Tutorials#3178]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-webide-ui-generation.html

all images broken (404)

**Comment by thecodester** [comment]
Checking ...

**Comment by mervey45** [comment]
@thecodester I can see the pictures. Maybe cache problems?

**Comment by thecodester** [comment]
I can also see them now 

@xtough Can you see them now?

**Comment by xtough** [comment]
yes, it is working again, even though I was sure that I had refreshed my local cache before. maybe a server-side issue.
