### ISSUE TITLE
Tour the SAP Community

### ISSUE THREAD

**Issue by nbnayak88** [SAPDocuments/Tutorials#3181]
Tutorial URL: https://developers.sap.com/tutorials/community-start.html

Please specify the step you are referring to  Step 5 shows technical error while submitting

**Comment by thecodester** [comment]
@WorkJerryJanda Can you handle this?

**Comment by WorkJerryJanda** [comment]
@nbnayak88 I don't understand the issue. Several people have taken the tutorial and no one else reported any problems with Step 5. Could you please provide more details? (cc:ing @thecodester )

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
