### ISSUE TITLE
SAP Data Hub, developer edition 2.4 - SCOPE

### ISSUE THREAD

**Issue by dash042** [SAPDocuments/Tutorials#3184]
What is the scope of the Developer Edition? I 
I can't seem to find most of the components shown in the openSAP presentation about the Datahub Launchpad:
- "Connection Management"
- "Metadata Explorer"
- "Systems Management"
- "Monitoring"

The only components I see are:
- "Vora Tools" (port 9225)
- "Modeler" (port 8090)

Where can I find (first and foremost) the "Connection Management"?
Does is belong to the "data governance and workflow features" that are not part of the DEV Edition?
Are they part of the TRIAL Version?

Thank you sincerely!

**Comment by anishgupta85** [comment]
Hi,
Developer edition is just  to provide the glimpse of operators in the modeler  and vora component. Hiw to work with pipelines and stuff.
If you want to learn about the full fledged SAP data hub with the other components you mentioned then you need to spin up the trial mentioned in the opensap course.
Regards,
Anish

**Comment by Sygyzmundovych** [comment]
You can find the description of the Developer edition in https://blogs.sap.com/2017/12/06/sap-data-hub-developer-edition/

The scope of Trial edition is described in https://blogs.sap.com/2018/04/26/sap-data-hub-trial-edition/

Regards.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
