### ISSUE TITLE
Tutorial "Implement A Card With Content-Based Actions" cannot be completed

### ISSUE THREAD

**Issue by pfefferf** [SAPDocuments/Tutorials#3188]
The tutorial "Implement a Card With Content-Based Actions" (https://developers.sap.com/tutorials/cp-mobile-cards-content-actions.html) cannot be completed, because for step 3 no "complete" button is available.

BR,
Florian

**Comment by thecodester** [comment]
@jitendrakansal The rules file had multi-choice instead of multiple-choice. Please be carefule.

@pfefferf Tutorial republished and you can finish it now. If there still is an issue with this tutorial, feel free to reopen.
