### ISSUE TITLE
Tutorial "Perform Text Analysis with SAP HANA Express Edition" - Graph Creation Issue

### ISSUE THREAD

**Issue by pfefferf** [SAPDocuments/Tutorials#3189]
In tutorial "Perform Text Analysis with SAP HANA Express Edition" (https://developers.sap.com/tutorials/hxe-docstore-05-graph-analysis.html) the last point of step 7 (Create Graph Workspace) is not working, because of following points:
- The source column name must be upper case: SOURCE COLUMN "src_id" -> SOURCE COLUMN "SRC_ID"
- The target column must be upper case: TARGET COLUMN "dest_id" -> TARGET COLUMN "DEST_ID"
- The key column name for the Edge and Vertex table must be "ID" instead of "NAME"

BR,
Florian

**Comment by qualiture** [comment]
Hi @pfefferf,

Many thanks for pointing this out. I will try to update the tutorial later today

**Comment by qualiture** [comment]
Will be fixed with PR https://github.com/SAPDocuments/Tutorials/pull/3520
