### ISSUE TITLE
Upload and query documents in SAP HANA Express Edition

### ISSUE THREAD

**Issue by ZEdwin** [SAPDocuments/Tutorials#3191]
Tutorial URL: https://developers.sap.com/tutorials/hxe-docstore-02-query-jsondocs.html

Step 2: Insert JSON documents into Document Store

Maybe a known issue, but I use the WebIDE SQL editor to enter the data. When copying the code to insert the records, I had some issues.
I had to replace the single quotes around the values with double quotes and add single quotes at the start and end of the statements:
Start: VALUES( { --> VALUES('{
End:  }); -->  }');

I've attached the modified text file.
[STEP2_SQL.txt](https://github.com/SAPDocuments/Tutorials/files/2948364/STEP2_SQL.txt)

**Comment by qualiture** [comment]
Hi @ZEdwin,

Thanks for pointing this out! I will try to update the tutorial later today
