### ISSUE TITLE
SAP HANA XS Advanced, Creating an HDI Module

### ISSUE THREAD

**Issue by DuoBelt** [SAPDocuments/Tutorials#3192]
Tutorial URL: https://developers.sap.com/tutorials/xsa-hdi-module.html

Please specify the step you are referring to
Step 2: Create CDS Table
Save the artifact after entering this code. Go back to the graphical editor to gain better clarity of the data model.

Save the artifact after entering this code `**close-> open tab or refresh  in (SPS03)**`
Go back to the graphical editor to gain better clarity of the data model

**Comment by Lsubatin** [comment]
I'm not having this problem in SPS03 (and haven't seen it in other people's instances), if you're having interface problems on HXE please post in answers.sap.com . Otherwise, I would create an incident. Thanks!
