### ISSUE TITLE
Change from mock server to live OData service

### ISSUE THREAD

**Issue by Ksandala** [SAPDocuments/Tutorials#3193]
Tutorial URL: https://developers.sap.com/tutorials/webide-live-odata.html

Please specify the step you are referring to :  Step 9: Validate your initialization function.

Tutorial is not accepting the answer for this step, i have made changes as suggested in step 8 and copying the code from onInit() as answers to step 9. it comes as "Sorry, that’s incorrect. Please try again."

-Krishna Sandala

**Comment by thecodester** [comment]
Duplicated in https://github.com/SAPDocuments/Tutorials/issues/3187
