### ISSUE TITLE
Send the CPU usage data to SAP IoT Application Enablement

### ISSUE THREAD

**Issue by amarpreet** [SAPDocuments/Tutorials#3195]
Tutorial URL: https://developers.sap.com/tutorials/iotae-comp-sendpy0.html

Please specify the step you are referring to
pushing data only returns a 202 message. I've tried modifying the payload. Hence i'm not able to see the data in the app

**Comment by amarpreet** [comment]
Found the solution , i was suing the older version of the resource_sensor , Read  the text and followed instead of only looking at the screen shots :p

**Comment by thomasalexneuhaus** [comment]
I have the same Issue, also with  resource_sensor_2 and a image warning
