### ISSUE TITLE
Add a User Task and Generic UI to Your Workflow

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Tutorials#3197]
Tutorial URL: https://developers.sap.com/tutorials/cp-wf-02-add-user-task.html

Please specify the step you are referring to step 9 - "Re-deploy the workflow definition and try it out"

I do not get any data shown. Deployment is fine with no errors. 

![nodata](https://user-images.githubusercontent.com/43760831/54154248-c0d10e80-4441-11e9-9c87-0e4d7c82cd59.png)

What have i done wrong?

**Comment by qmacro** [comment]
Hello @mts2605 - I checked the tutorial and this does not happen for me - I suspect it may be something you're encountering that is perhaps related to the steps you've taken so far. This feedback system is mainly for issues with the tutorial content itself (e.g. typos, etc) - if you are still encountering this issue, may I please suggest you ask for help in the relevant section of the SAP Community Q&A - there is a dedicated [SAP Cloud Platform Workflow tag](https://answers.sap.com/tags/73554900100800000555) for this area. Thanks!
