### ISSUE TITLE
Grunt Build in SAP Web IDE: ES6 supported with new version of Grunt build

### ISSUE THREAD

**Issue by MaximilienFourmyBeyond** [SAPDocuments/Tutorials#3198]
Tutorial URL: https://developers.sap.com/tutorials/webide-grunt-basic.html

Hi,

There is a new version of "@sap/grunt-sapui5-bestpractice-build" (1.3.65) which now supports ES6:
https://stackoverflow.com/questions/49237874/const-and-let-declarations-in-ui5/55054360#55054360

**Comment by jhornik** [comment]
@MaximilienFourmyBeyond : 

Thanks for bringing this to our attention. We are planning on updating the Grunt documentation in the SAP Web IDE Developer Guide and the tutorial you mentioned on Thursday, with the new release of SAP Web IDE. 

Regards,
Julia

**Comment by jhornik** [comment]
The tutorial has now been updated (with Thursday's release). 
https://developers.sap.com/tutorials/webide-grunt-basic.html

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
