### ISSUE TITLE
SAP HANA XS Advanced, Creating an HDI Module

### ISSUE THREAD

**Issue by onceup** [SAPDocuments/Tutorials#3199]
Tutorial URL: https://developers.sap.com/tutorials/xsa-hdi-module.html

Please specify the step you are referring to
screenshot's URL are broken, not visible

**Comment by thecodester** [comment]
I see the images. Can you refresh, maybe clear cache?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
