### ISSUE TITLE
Installing SAP HANA, express edition Server + Apps, with Docker

### ISSUE THREAD

**Issue by dellagustin** [SAPDocuments/Tutorials#3201]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker-xsa.html

Please specify the step you are referring to

On step `docker pull store/saplabs/hanaexpressxsa:2.00.035.00.20190223.1` I am getting the error `Error response from daemon: manifest for store/saplabs/hanaexpressxsa:2.00.035.00.20190223.1 not found`

I'm running it on docker for desktop on windows, which is stated as not supported somewhere, but I this this step should go through anyway.

**Comment by aplata-sap** [comment]
Hi there,

Looks like the pull number is incorrect. It should be 2.00.036.20... A fix will be issued soon. Thank you for highlighting this mistake.
