### ISSUE TITLE
Add API Business Hub API to a UI5 Application

### ISSUE THREAD

**Issue by mpredolim** [SAPDocuments/Tutorials#3204]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-api-ui5-app.html

Please specify the step you are referring to

Step 4 - Run your application.

When i run the app, i have CORS error and i can't see JSON results.

**Comment by mhassett92** [comment]
Hello, I apologize for the delay. I have transferred into a new roll at the company last year and am behind on managing my older tutorials.

Are you still experiencing issues this?

**Comment by MichaelCzcz** [comment]
@mpredolim Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
