### ISSUE TITLE
Build a PHP app connecting to SAP HANA Express Edition

### ISSUE THREAD

**Issue by ZEdwin** [SAPDocuments/Tutorials#3205]
Tutorial URL: https://developers.sap.com/tutorials/hxe-docstore-04-php-app.html

Step 6: Run the PHP file

I get an error when executing the code. The message is:
"Base table not found;259 invalid table name: Could not find table/view FOOD_COLLECTION in schema SYSTEM".
Here's a screenshot:
![PHP_Error_001](https://user-images.githubusercontent.com/5278654/54279994-b3796880-4596-11e9-8e7b-a6c3d7351ad4.jpg)
PLEASE NOTE: The name of the table in the screenshot is not the one I use, btw. This was just another test of mine to check if the name in the eror would change after adapting the code (to see if I was changing the right file). The name I used for the table is correct: FOOD_COLLECTION.

When executing the previous node.js app, it works. Just not the PHP.

Here's more info (WebIDE):
![PHP_Error_002](https://user-images.githubusercontent.com/5278654/54280052-d441be00-4596-11e9-823a-a979c3a2621e.jpg)

And the code itself (with the correct password, but commented out):
![PHP_Error_003](https://user-images.githubusercontent.com/5278654/54280094-f0455f80-4596-11e9-8541-85c0f197c4b6.jpg)

Anybody knows why this is happening? I have tried:
$sql = 'SELECT "name" FROM food_collection';
$sql = 'SELECT "name" FROM FOOD_COLLECTION';
$sql = "SELECT 'name' FROM FOOD_COLLECTION";

**Comment by ZEdwin** [comment]
Uhm. The name of the table in the screenshot is not the one I use, btw. That was just another test of mine to check if the name in the eror would change after adapting the code (to see if I was changing the right file).

**Comment by qualiture** [comment]
Hi @ZEdwin,

I am currently not near my HXE environment, so I cannot check right now; I will try to reproduce the issue later tonight.

In the meantime, could you maybe check if your issue might be related to this? https://answers.sap.com/questions/10585164/index.html

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
