### ISSUE TITLE
Installing SAP HANA, express edition with Docker - Ports

### ISSUE THREAD

**Issue by dellagustin** [SAPDocuments/Tutorials#3207]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker-xsa.html

Please specify the step you are referring to

This refers to _Additional Information_ and step _Start SAP HANA, express edition Container_ from both versions of the tutorial (with and without XSA).

The command for running the container specify a list of ports that should be open, but it does not specify why.

I would like to add the link https://help.sap.com/viewer/ports to the section Additional information_ and a reference to it on the section _Start SAP HANA, express edition Container_

At https://help.sap.com/viewer/ports one can filter for product _SAP HANA Platform_

**Comment by JCurrie27** [comment]
Links were added to the tutorials. Thanks for this suggestion - closing.

**Comment by diraschk** [comment]
_51000-51060_ I think this was not enough for XSA. 

It should be 51000 – 51500

_In an XSA runtime environment, port range used for the connection from the xscontroller-managed Web Dispatcher to the xscontroller for access to application instances if port routing is used_

**Comment by JCurrie27** [comment]
Thanks for this feedback. Engineering is reviewing the documented port ranges, and we will update the documentation based on their conclusion.
