### ISSUE TITLE
Installing SAP HANA, express edition with Docker - Networking considerations

### ISSUE THREAD

**Issue by dellagustin** [SAPDocuments/Tutorials#3209]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker-xsa.html

Please specify the step you are referring to

This issue is somewhat related to #2038

It refers to step "Log Into System or Tenant Database"

When running HANA express on docker, one will most likely want to connect to it from the host OS.

If you try to connect to it using either android studio or hdbsql (installed on the host) you will probably face problems.

Let's say you try to connect using the command line (on the host) `hdbsql -n localhost -i 90 -u SYSTEM -d SYSTEMDB -p HXEHana1`, the command line will connect with the HANA instance on the container (I assume it is through port 39013) and the instance will answer with a "redirect" (for lack of better term) to the resolved net public name, which by default (I am assuming it is the default behavior of SAP HANA) it is set to IP. This will be the IP of the container on the internal container network, which is not reachable from the host.

This can be quite complex and hard to troubleshoot and solve.

The way I solved it, using the information from this [blog](https://blogs.sap.com/2018/09/20/how-to-configure-hana-network-communication-channels-part1.-public-network/) was to to set `use_default_route` to `no`, run the container specifing the hostname `hxehost` and setting the host `hxehost` to `127.0.0.1` on `/etc/hosts`

I believe this information should be made clear on the tutorials, as it took me a lot of time to troubleshoot.

**Comment by entmike** [comment]
This is how I handle it in Docker without messing with hosts files...

**Docker Machine example in Windows where `192.168.99.100` is the external docker-machine vm and `hxehost` is the container host name:**

```sql
ALTER SYSTEM ALTER CONFIGURATION ('global.ini', 'system') SET ('public_hostname_resolution', 'use_default_route') = 'name' WITH RECONFIGURE;
ALTER SYSTEM ALTER CONFIGURATION ('global.ini', 'system') SET ('public_hostname_resolution', 'map_hxehost') = '192.168.99.100' WITH RECONFIGURE;
```

**Docker Machine example in Macbook where `localhost` is the docker daemon running on the Mac and `hxehost` is the container host name:**

```sql
ALTER SYSTEM ALTER CONFIGURATION ('global.ini', 'system') SET ('public_hostname_resolution', 'use_default_route') = 'name' WITH RECONFIGURE;
ALTER SYSTEM ALTER CONFIGURATION ('global.ini', 'system') SET ('public_hostname_resolution', 'map_hxehost') = 'localhost' WITH RECONFIGURE;
```

**Comment by JCurrie27** [comment]
Thanks for this feedback. Examples are being added to the tutorials "Installing SAP HANA, express edition with Docker" and "Installing SAP HANA, express edition Server + Apps with Docker".
