### ISSUE TITLE
Display database content and run SQL queries

### ISSUE THREAD

**Issue by eliasjsj** [SAPDocuments/Tutorials#3210]
I am having an issue while entering a database table in eclipse. I followed the needed steps outlined in this link tutorial.

https://www.sap.com/developer/tutorials/abap-display-data-queries.html

STEP 2: Select a database table

I entered snwd_so_inv_item in the search field.
No result.

I read 's document.
https://www.sap.com/documents/2012/09/2a404253-5b7c-0010-82c7-eda71af511fa.html
I generated EPM by ABAP transaction SEPM_DG.

But still, there is no result for snwd_so_inv_item.

In SE11, I can see the table "snwd_so_inv_item".
Why can't I use the database table "snwd_so_inv_item" in eclipse?

I´m sure that I´m executing the search right (Alt + F8).
My SAP_BASIS is 731 SP level 0018.
My Eclipse version is 2018-12 with the ABAP ADT tools for this version.

Appreciate your help.

Thanks.

**Comment by julieplummer20** [comment]
Hi eliasjsj,
Yes, these tutorials were adapted from a CodeJam. We used a different tx to generate the data: SEPM_DG_OIA_NEW . Can you please try this, or failing that tasklist : STC01 -> SAP_BASIS_EPM_OIA_CONFIG ?
I'll update the prerequisites accordingly.
Best wishes 
Julie.

**Comment by julieplummer20** [comment]
Just fyi : Report underlying the Tx SEPM_DG_OIA_NEW = RS_EPM_DGC_HANA_NEW .
BR Julie

**Comment by julieplummer20** [comment]
Hi Eliasjsj,
How did you get on after running the transaction?
I hope it worked. If so, do you mind if I close this issue?
Thanks Julie.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
