### ISSUE TITLE
SAPUI5 - Setup the DataSource in the local application

### ISSUE THREAD

**Issue by kavishdahekar** [SAPDocuments/Tutorials#3215]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-webide-setup-datasource.html

There's no "Done" button on the page for recording my progress. The progress always stays at 0%.

**Comment by IObert** [comment]
Hi @kavishdahekar,

this issue should be resolved by now. Can you please confirm this?
Please re-open the issue if necessary

**Comment by kavishdahekar** [comment]
@IObert Confirmed as resolved. Thanks.
