### ISSUE TITLE
Get a Free Trial Account on SAP Cloud Platform

### ISSUE THREAD

**Issue by JOPereyra** [SAPDocuments/Tutorials#3217]
Tutorial URL: https://developers.sap.com/tutorials/hcp-create-trial-account.html

Please specify the step you are referring to

buen dia. porque no se actualizan los porcentajes de los tutoriales si ya jan sido realizados?

gracias

**Comment by thecodester** [comment]
What do you mean percentages? Where do you see them not updating?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
