### ISSUE TITLE
Create and Run an ABAP Application

### ISSUE THREAD

**Issue by VenkateshhKonduri** [SAPDocuments/Tutorials#3218]
Tutorial URL: https://developers.sap.com/tutorials/abap-create-basic-app.html

Please specify the step you are referring to --> Step 11

I tried the following code but it shows incorrect.

Class Demo definition.
Public Section.
class-methods: Main(r_result) type ref to Demo.
protected section.
private section.
EndClass.

Class Demo implementation.
method Main.
r_result = new Demo( ).
endmethod.
endclass.

start-of-selection.
Demo=>Main( ).

I also tried including ONLY the following two statements for this question but I get a message that it is not correct.

Start-of-selection.
Demo=>Main( ).

What am I doing wrong here?

**Comment by julieplummer20** [comment]
Hi Venkata,
Sorry, you're not doing anything wrong. The validation engine is currently case-sensitive. We are working on changing this.
Therefore, please enter the code in the same case as in the sample code. START-OF-SELECTION. is uppercase. The class=>method statement is all lowercase. I will look at changing the question, until the validation is improved.
Sorry for the inconvenience.
Best wishes,
Julie.

**Comment by julieplummer20** [comment]
Also, just the 2 lines : event, class + method. You don't need to  the class definition / implementation blocks.
BR Julie.

**Comment by CrayonZeng** [comment]
I tried the following code but it wrong.

event.
demo=>main( ).

what should i do?

**Comment by julieplummer20** [comment]
Hi,
You need to use the correct event name:
start-of-selection.
Demo=>Main( ).

However, I will reformulate this as multiple-choice.
Best wishes,
Julie.

**Comment by Hex-3-En** [comment]
> You need to use the correct event name:
> start-of-selection.
> Demo=>Main( ).
> 

its:
START-OF-SELECTION.
demo=>main( ).

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
