### ISSUE TITLE
Could not access the SAP Corporate Nexus system. Make sure the system destination is properly defined.

### ISSUE THREAD

**Issue by shenjiansj** [SAPDocuments/Tutorials#3220]
Hi,

When I create a business service using CDS and try to deploy to my SCP cloud foundry space, the WEBIDE reports error like:
Could not access the SAP Corporate Nexus system. Make sure the system destination is properly defined.
And the console ouput:
Could not resolve dependencies for project sap:Selfbilling_monitor-srv:war:1.0-SNAPSHOT: Failed to collect dependencies at com.sap.cloud.servicesdk.prov:odatav2:pom:1.25.0 -> com.sap.cloud.servicesdk.prov:odata2.web:jar:1.25.0 -> com.sap.cloud.servicesdk.prov:odata2.cds:jar:1.25.0 -> com.sap.cloud.servicesdk.prov:odata2.cdx:jar:1.25.0 -> com.sap.cloud.servicesdk.prov:odata2.core:jar:1.25.0 -> com.sap.gw.rt:core.runtime:jar:1.35.19: Failed to read artifact descriptor for com.sap.gw.rt:core.runtime:jar:1.35.19: Could not transfer artifact com.sap.gw.rt:core.runtime:pom:1.35.19 from/to build.snapshots (http://nexus/nexus/content/repositories/build.snapshots): Failed to transfer file http://nexus/nexus/content/repositories/build.snapshots/com/sap/gw/rt/core.runtime/1.35.19/core.runtime-1.35.19.pom with status code 500 -> [Help 1]

Best Regards,
Jay.

**Comment by thecodester** [comment]
What tutorial are you referencing?

**Comment by shenjiansj** [comment]
https://developers.sap.com/tutorials/cp-apm-01-create-business-service.html

**Comment by Apfohlmann** [comment]
Hi Jay,

do you still have the issue? I worked with a trail SCP account. 

Best regards,
André

**Comment by thecodester** [comment]
@shenjiansj Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
