### ISSUE TITLE
Connect to SAP HANA, express edition using JDBC

### ISSUE THREAD

**Issue by mpern** [SAPDocuments/Tutorials#3221]
Tutorial URL: https://developers.sap.com/tutorials/hxe-connect-hxe-using-jdbc.html

Please specify the step you are referring to

Step 1: Install the SAP HANA client

The link to the SAP Store is broken. Isn't there an easier way to get my client libraries?

**Comment by JCurrie27** [comment]
mpern - can you try the SAP Store link again? It should open a page asking if you want to stay on the United States site, or choose another country or region.

**Comment by mpern** [comment]
Still doesn't work.

BTW, newer driver versions of ngdbc are available in Maven (like they should be 😄 ), I think you should add a link to those + a compatibility matrix which driver to use with which HANA version.

https://mvnrepository.com/artifact/com.sap.cloud.db.jdbc/ngdbc

**Comment by JCurrie27** [comment]
@Lsubatin - is there a location-agnostic link we use for the SAP Store so users can download HANA client software packages? It appears the link in the tutorial doesn't work for users in all countries.
Can you respond to the Maven repository / compatibility matrix request?

**Comment by Lsubatin** [comment]
This is an option: https://tools.hana.ondemand.com/#hanatools 

And HXE's download manager offers to download the clients too: https://www.sap.com/cmp/ft/crm-xu16-dat-hddedft/index.html

**Comment by thecodester** [comment]
@mpern Is the issue resolved?

**Comment by mpern** [comment]
No.

While my issues are solved (I used the drivers from maven), the documentation is still wrong:

- The links still point to the SAP Store
- No link to maven or a compatibility matrix as discussed above

**Comment by JCurrie27** [comment]
@Chris-Huston: would you be able to update this JDBC tutorial (formerly a how-to) per the feedback above?

**Comment by thecodester** [comment]
@JCurrie27 Not sure Chris is going to answer this :-) Can you handle or reassign?

**Comment by JCurrie27** [comment]
Link to compatibility matrix SAP Note was added to https://developers.sap.com/tutorials/hxe-connect-hxe-using-jdbc.html. 
Closing this issue.
