### ISSUE TITLE
Installing SAP HANA, express edition with Docker - Barely useful

### ISSUE THREAD

**Issue by mpern** [SAPDocuments/Tutorials#3222]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html

Please specify the step you are referring to:

There is no specific step

The whole setup guide is quite anemic and unfortunately only covers the most basic steps, that are already covered by basically any other Docker tutorial.

What I would like to know is:

- How does the Dockerfile look like?
- What scripts etc run when the container starts?
- How can I automate the database setup?
  - can I inject custom SQL/Shell/... scripts to automate e.g. user creation, database/schema creation etc
  - how can I automate the import of dumps?

If you look at other DBMS like Oracle, MySQL, Postgres etc, their Docker setup is completely open source and transparent for the developer community. It also includes more advanced setup guides and how-tos that cover the above points

**Comment by mpern** [comment]
To answer my own question:

- The database bootstrap happens in the script `/run_hana.sh`
- The script has two "hook points", the folders `/hana/hooks/pre_start` and `/hana/hooks/post_start`. Any executable shell script in this folders gets executed before and after the startup is finished
- the `run_hana.sh` scripts also provides environment variables to the hook scripts to distinguish between initial bootstrap/startup (`_HOOK_START_TYPE=initial`) and subsequent starts of the container (`_HOOK_START_TYPE=update`)

Based on that information, here is my take on a simplified local bootstrap that auto-imports dumps:

https://github.com/mpern/hana-docker

It would really help if `run_hana.sh` executes user-defined scripts in *additional* folders (that are empty by default), so that I can just mount my custom scripts into the container without the need to dump the out-of-the-box scripts first.

And an off-topic remark:

The HANA container doesn't log *anything* to stdout (maybe I missed some flag or sth)

This makes it really hard to work with this container, because every tool for Docker (or Kubernetes) expects the containers to log to stdout.

As of now, without a deep administrative knowledge of HANA you have no chance to understand what's going on, it's just a big, mysterious black box 🔮

**Comment by thecodester** [comment]
@JCurrie27 @TerryNing Can you guys comment on the issue?

**Comment by JCurrie27** [comment]
@mpern - Thanks for your comments. I've taken your request for open source Docker setup information (for customizable installation and setup) to the program team.
