### ISSUE TITLE
Continue Your OData Exploration with EPM

### ISSUE THREAD

**Issue by tmundt** [SAPDocuments/Tutorials#3227]
Tutorial URL: https://developers.sap.com/tutorials/odata-02-exploration-epm.html

Please specify the step you are referring to: Step 1 Find the EPM OData service
How are the credentials (username/password) to log on to the demo system? 
It is not explained (not visible to me) in the tutorial.

Thank you!

**Comment by thecodester** [comment]
IT's the credentials you created for the Gateway service, no?

**Comment by qmacro** [comment]
Hi there @tmundt - I'm guessing that you may have found what you're looking for (as @thecodester mentioned, it's the credentials that you will have created in a previous tutorial in the group that this tutorial lives in - [Get an Introduction to OData](https://developers.sap.com/group.scp-6-odata-intro.html)). Thanks.
