### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by mpern** [SAPDocuments/Tutorials#3231]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html

Please specify the step you are referring to

Step 11: (Optional) Log Into System or Tenant Database

---

The JDBC URLs have the wrong format, they should look like this:

```
jdbc:sap://<ip_address>:39017/?databaseName=<database_name>
```
(notice the `?` in front of `databaseName`)

And a link to the JDBC Connection Properties would also be nice

https://help.sap.com/viewer/0eec0d68141541d1b07893a39944924e/2.0.03/en-US/109397c2206a4ab2a5386d494f4cf75e.html

**Comment by JCurrie27** [comment]
Thanks for these corrections. The JDBC URLs were corrected in hxe-ua-install-using-docker and hxe-ua-install-using-docker-xsa. A link was added to the JDBC connection properties topic.
