### ISSUE TITLE
Change from mock server to live OData service

### ISSUE THREAD

**Issue by zouzounos** [SAPDocuments/Tutorials#3232]
Tutorial URL: https://developers.sap.com/tutorials/webide-live-odata.html

Have completed step 8 and i try to run the app. oData batch request fails with message: 

\{
	"message": "HTTP request failed",
	"headers": \{
		"Content-Type": "application/xml;charset=utf-8",
		"content-language": "en-GB",
		"Content-Length": "242"
	},
	"statusCode": "500",
	"statusText": "Internal Server Error",
	"responseText": "Service exception: [414] user is forced to change password"
}

**Comment by maxstreifeneder** [comment]
whole [Tutorial Group](https://developers.sap.com/group.introducing-front-end-development.html) is under investigation and needs rework. still to be clarified how we approach this group

**Comment by IObert** [comment]
Closing the issue as we decided to remove the tutorial. Sorry for the inconvenience!
