### ISSUE TITLE
Use JPA in Custom Logic

### ISSUE THREAD

**Issue by rkonnerth** [SAPDocuments/Tutorials#3235]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html

Please specify the step you are referring to:
Step 4: Change the runtime from Tomcat to TomEE

Hi @JijoRoyJacob 

I have some trouble completing this tutorial.
I could complete steps 1 and 2. Meaning that I could see the generated JPA classes in srv/src/gen...

I did all the changes described in steps 3 and 4, built the complete project, and ran the srv module java app.
The app started fine on cloud foundry, but the odata service is no longer working.

I tried building and runing the srv module sevaral time, but no luck.
I am either getting an http 502 (Bad Gateway) or http 404.
My service URL is : https://htcm25v6a0wwd2if-capfullstack-srv.cfapps.sap.hana.ondemand.com/odata/v2/CatalogService/

My latest code is in https://github.com/rkonnerth/CAPFullstack/tree/beforeJPACodeGeneration  branch.

Any Idea whats wrong?

Thanks, Reinhold

**Comment by JijoRoyJacob** [comment]
Hi Reinhold,
Apologies for the delay. Just got back from my sick leave. To solve your problem, try increasing the memory quota of the service module in mta.yaml as show in the following screenshot:
![JPA-mta](https://user-images.githubusercontent.com/41678923/54970638-f5e47180-4fa8-11e9-99c9-7c21c8e58419.png)

Please let me know if it works.

Best regards,
Jijo

**Comment by rkonnerth** [comment]
Hi Jijo,

No problem, welcome back.

I tried increasing the memory up to 4096M, but no luck I'm still getting a 404 when calling the service URL. 

Anything else I could try?

Cheers, Reinhold

**Comment by JijoRoyJacob** [comment]
I've forwarded this issue to the dev team. As soon as they find it's cause, I'll get back to you.

Best regards,
Jijo

**Comment by baxterdale** [comment]
Hello Reinhold,
I had a look at your code.  Please check.
CAPFullstack/srv/src/main/webapp/WEB-INF/web.xml

When doing the example code I did it this same way.
I tried replacing the <resource-ref> tag with what is instructed to do in the exercise step 4.  In other words only have one resource-ref tag - In your git repository I can see that you have two references.

@JijoRoyJacob maybe consider improving the instruction.  Also I notice now the web.xml generated has Tomee tag already in the file, just commented out.

Regards,
Brian

**Comment by baxterdale** [comment]
Also while doing step 5 (I have windows) I needed to improve the curl command to this to get it to work.

`curl -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d "{ \"buyer\" : \"JPA Buyer 1\", \"book_ID\" : 310 }" https://lntjcudpur6avthx-bookshop-srv.cfapps.eu10.hana.ondemand.com/odata/v2/CatalogService/Orders`

**Comment by rkonnerth** [comment]
@baxterdale 
Thanks you!
your hint with CAPFullstack/srv/src/main/webapp/WEB-INF/web.xml solved the issue.
