### ISSUE TITLE
Start SAP HANA, express edition Server

### ISSUE THREAD

**Issue by oluseguni** [SAPDocuments/Tutorials#3237]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-getting-started-vm-xsa.html

Step 3: Log in

At the hxehost login prompt, enter hxeadm.
NO PROBLEM WITH ENTERING hxeadm

For Password, enter the temporary password HXEHana1.
PROBLEM: The system does not respond to my keyboard(except the Enter key). Unable to enter password HXEHana1

**Comment by JCurrie27** [comment]
Hi @oluseguni: Two things to check:

1. Did you set your keyboard? HXE assumes your host machine is using a US-English QWERTY keyboard. If your keyboard is a different type, you need to specify it as described in the previous tutorial in the group: [https://developers.sap.com/tutorials/hxe-ua-keyboard-vm.html](https://developers.sap.com/tutorials/hxe-ua-keyboard-vm.html)

2.  Are you using VMWare? VMWare sometimes loses focus on your keyboard. Hit **CTRL+G** to redirect keyboard and mouse input to your VM. See the VMWare keyboard shortcut Help at [https://www.vmware.com/support/ws5/doc/ws_learning_keyboard_shortcuts.html](https://www.vmware.com/support/ws5/doc/ws_learning_keyboard_shortcuts.html)

Hope this helps.

**Comment by oluseguni** [comment]
Hello . I tried with the US keyboard option and UK keyboard option. 
In both cases I was able to enter the login id hxeadm and then press enter.
After pressing 'enter' the next line with Password:  appears. Then the system does not respond to any keys except 'enter'.

**Comment by oluseguni** [comment]
I initially tried using the VMware Workstation PRO. I have also tried using the  VMware Workstation 15 player and still had the same issue

**Comment by JCurrie27** [comment]
@TerryNing - could your team please investigate this reported password entry problem on the VM image?

**Comment by Lsubatin** [comment]
Please note that there will be no characters and the cursor will not move when entering the password in the console. It looks like it is not writing anything but it is.

**Comment by oluseguni** [comment]
Hello. Thank you for the information on how the cursor does not move when entering the password. I was expecting the cursor to move and perhaps show the characters *** when keying in the password. I have been able to proceed based on your information. Thanks.
