### ISSUE TITLE
Change from mock server to live OData service

### ISSUE THREAD

**Issue by roscoe44** [SAPDocuments/Tutorials#3239]
Tutorial URL: https://developers.sap.com/tutorials/webide-live-odata.html

I believe this page needs updating to reflect the latest versions of files. My manifest.json is at v1.8 vs v1.1 mentioned in the tutorial. I have tried to follow it but I am getting an error when trying to run a live version of the demo . . . 

Failed to load UI5 component for navigation intent "#BUILD-prototype".

My _S1.controller.js imported and edited as mentioned is reporting this error:-
Property mParameters is a private member of sap.UI.Base.Event

**Comment by rbrainey** [comment]
Switching this to Max to be addressed.  Max, would you take a look at this and see what
s going wrong?  thanks.

**Comment by maxstreifeneder** [comment]
whole [Tutorial Group](https://developers.sap.com/group.introducing-front-end-development.html) is under investigation and needs rework. still to be clarified how we approach this group

**Comment by IObert** [comment]
Closing the issue as we decided to remove the tutorial. Sorry for the inconvenience!
