### ISSUE TITLE
Build a mobile app from an SAP Web IDE template

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Tutorials#3241]
Tutorial URL: https://developers.sap.com/tutorials/hcp-template-mobile-web-app.html

Please specify the step you are referring to - All of them

There are no way to complete any steps. How come? (I am logged in)

**Comment by thecodester** [comment]
These are older tutorials that we are in the midst of refreshing, so they don't let you track your progress. We hope to update it soon.

**Comment by mts2605** [comment]
Look forward to news on this;-)

**Comment by rbrainey** [comment]
Marius, I think this one is related to the issue I just assigned to you.

**Comment by IObert** [comment]
We decided to remove this tutorial. If you'd like to learn more about SAPUI5 on SAP Cloud Platform, please check out [this](https://developers.sap.com/mission.sapui5-cf-first.html) tutorial instead.
