### ISSUE TITLE
Use SAP HANA Tools for Eclipse as SQL Query Tool with SAP HANA, express edition

### ISSUE THREAD

**Issue by eralper** [SAPDocuments/Tutorials#3242]
Tutorial URL: https://developers.sap.com/tutorials/mlb-hxe-tools-sql-eclipse.html

Please specify the step you are referring to

During connection setting in additional steps, I realized that 39015 port is added to the end of the host information on the other hand for SAP HANA Express multitenant databases the connection has 39013 as the port number

I cannot modify this port in the Eclipse IDE SAP HANA Administration perspective when I am adding HXE as a new System

Is there a way of overcoming this problem?

**Comment by adadouche** [comment]
Hi @eralper

When using the Eclipse plugin to connect to a tenant like HXE, an initial connection to the SYSTEMDB will be made to request the tenant port. Once done, it will be recorded in the Eclipse metadata.

39013 is the SYSTEMDB port.

So in fact you don’t need to set the ports (unless you are using some port forwarding mechanisms like NAT)

Hope this helps

**Comment by eralper** [comment]
Thank you @adadouche for response,
A friend on stackoverflow asked this question at  https://stackoverflow.com/questions/55261120/cannot-connect-to-sap-hana-express-db-using-eclipse-studio/55275332#55275332

I tried to simulate the case and I actually cannot connect to a SAP HANA Express edition which I obtained on AWS from Amazon AWS Marketplace

I installed the Eclipse on Mac and on Systems I tried to add hxehost (I mapped hxehost to IP address in hosts file)

I defined the connection as described in step 6
But on configuration screen when I go to additional info screen, I see port 39015 is used. And I cannot change it on that screen. 
So actually the problem is Eclipse is assigning that port automatically and preventing me to modify it



![image](https://user-images.githubusercontent.com/26281964/54824535-4fecea80-4cbc-11e9-9d25-c486b173d853.png)

**Comment by adadouche** [comment]
Hi,
I checked you StackOverFlow post, and I think you are missing the HXE security group which allows remote connections.

Please refer to the following tutorial with **Step 3 - configure your Network** for more details: https://developers.sap.com/tutorials/hxe-aws-setup.html

**Comment by eralper** [comment]
Hello adadouche,
I can connect to HXE applications remote via browser on my computer

I copy down the security group settings allowing ports for remote access below

<img width="971" alt="Screenshot 2019-03-23 at 10 15 18" src="https://user-images.githubusercontent.com/26281964/54863148-fcc77600-4d55-11e9-973d-a7e601667010.png">

And I can launch Web IDE and connect to SYSTEMDB via Database Explorer

<img width="1011" alt="Screenshot 2019-03-23 at 10 15 54" src="https://user-images.githubusercontent.com/26281964/54863153-1ec0f880-4d56-11e9-97d7-1de991e93505.png">

I thought all above settings or situation showing the VPC configuration is correct, am I wrong?

**Comment by eralper** [comment]
I installed  Eclipse 2018-09 (4.9) first and then use https://tools.hana.ondemand.com/2018-09 for SAP HANA Tools and ADT, etc. I decided to go with these releases by looking at the table given at https://tools.hana.ondemand.com/  
I doubt if I would have the same issues if I chose Oxygen release

**Comment by adadouche** [comment]
Then are you sure you have a tenant running?

Can you run the following piece connected to your SYSTEMDB:

```
SELECT
	  DATABASE_NAME
	, SERVICE_NAME
	, PORT
	, SQL_PORT
	, (PORT + 2) HTTP_PORT
FROM
	SYS_DATABASES.M_SERVICES
WHERE
  (
        SERVICE_NAME      = 'indexserver'
    and COORDINATOR_TYPE  = 'MASTER'
  )
  or SERVICE_NAME = 'xsengine'
;
```

**Comment by adadouche** [comment]
Hi,

Any news? I'll close the issue for now, but feel free to reopen. 

@bdel
