### ISSUE TITLE
Create a sample application on SCP Neo using SAP S/4HANA Cloud SDK

### ISSUE THREAD

**Issue by ml5hj** [SAPDocuments/Tutorials#3243]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-scp-neo-sample-application.html

Please specify the step you are referring to: Step 5
I am trying to go through this but at this step I am unable to get the browser to display the login page. When I look back up the command prompt I see Errors
[ERROR] java version "1.8.0_201"
[ERROR] Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
[ERROR] Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
[INFO] JAVA version is not correct. The supported versions are 1.6 and 1.7.

I know these are present in sample screenshot.

Can anyone provide any insight please or if there are any logs that could help?

Regards

Mark

**Comment by ml5hj** [comment]
Information in tutorial is wrong.
Url to go to is http://localhost:8080/firstapp-application/

**Comment by thecodester** [comment]
@karstenmelato Can you address this and fix tutorial, as needed?

**Comment by karstenmelato** [comment]
I don't understand the problem. What exactly is the mistake. In the tutorial, the URL 'http://localhost:8080/firstapp-application/' is given.

**Comment by ml5hj** [comment]
Hi Karsten
The tutorial looks correct now, I believe that when I was doing it it had hello-world in the url
Mark

**Comment by karstenmelato** [comment]
That may be, until recently we had a discrepancy between the new and the old URL in the tutorials. Please excuse the confusion.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
