### ISSUE TITLE
Create a CDS view (ABAP)

### ISSUE THREAD

**Issue by TonyDag** [SAPDocuments/Tutorials#3245]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-adt-create-cds-view.html

Please specify the step you are referring to

Step 9: Test yourself - I was able to get my code to generate in eclipse, copied it into the work area, it submit,  get: Submit Answer
×
Sorry, that’s incorrect. Please try again.
Tried several different variations.
At some point we should be able to see the exact code snippet you are looking for.

**Comment by julieplummer20** [comment]
Hi Tony,
I can give you the solution. But we also want to improve the validation process. Please give me at least a couple of the variants you tried. I can either reword the question, or request that the validation engine be less strict - it depends what you wrote.
Thanks and best wishes,
Julie.

**Comment by TonyDag** [comment]
Hi Julie,
Thanks for the response and the tutorials are very helpful.
So the test question was - Add a new field to your CDS view for the product name. Find the correct association and field name. Use the definition of sepm_sddl_so_invoice_item (**F3**).Enter your code in the box below and choose Submit Answer.

We have a Sandbox system and I was able to get the following code to work in it:

@AbapCatalog.sqlViewName: 'ZITEMS_007'
@AbapCatalog.compiler.compareFilter: true
@AbapCatalog.preserveKey: true
@Metadata.allowExtensions: true
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'TD Test CDS'
define view Z_Invoice_Items_2 as select from sepm_sddl_so_invoice_item
{
header.buyer.company_name,
sepm_sddl_so_invoice_item.sales_order_invoice_key,
sepm_sddl_so_invoice_item.currency_code,
sepm_sddl_so_invoice_item.gross_amount,
sepm_sddl_so_invoice_item.product_key,
product.product_name_key,
product.product_name,

@EndUserText.quickInfo: 'Paid'
cast(
case header.payment_status
    when 'P' then 'X'
    else ' '
end as zso_invoice_payment_status )

as payment_status,

//* Associations *//
   header,
   product
}

where currency_code = 'USD'

I also tried to skinny it down to what I thought would be the bare minimum code:

@AbapCatalog.sqlViewName: 'ZITEMS_007'
@Metadata.allowExtensions: true
@EndUserText.label: 'TD Test CDS'
define view Z_Invoice_Items_2 as select from sepm_sddl_so_invoice_item
{
sepm_sddl_so_invoice_item.sales_order_invoice_key,
sepm_sddl_so_invoice_item.currency_code,
sepm_sddl_so_invoice_item.gross_amount,
sepm_sddl_so_invoice_item.product_key,
product.product_name_key,
product.product_name,


//* Associations *//
   product
}

Thanks in advance,
Tony

**Comment by julieplummer20** [comment]
Hi Tony, I'm really sorry; the solution is much simpler: I just wanted the one statement: sepm_sddl_so_invoice_item.product.product_name

I can see that I've phrased it badly; I will have to think about re-formulating it, or using a completely different questions :-(. Thanks a lot for your feedback - if you paste that in, it should work (I copied it straight from the file that we send to the validation engine.)
Best wishes
Julie.

**Comment by TonyDag** [comment]
Ahh – OK. Thanks for the quick response. I guess I assumed that the self tests want you to build on the previous steps of the tutorial.

Thanks,
Tony

**Comment by thecodester** [comment]
@TonyDag Has the issue been resolved?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
