### ISSUE TITLE
Enable Services for Sales Tracker App

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Tutorials#3247]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-services-enable.html

Please specify the step you are referring to - Step 5 - Maybe it's me, but to my knowledge the step approval is not working. No matter which services I choose I get error. Is the validation working?
KR Michael

**Comment by thecodester** [comment]
Yes, the validation is working, I just tried it. 

As far as I can calculate, there are 32 possible answer cobinations. Did you try all of them?

**Comment by thecodester** [comment]
@mts2605 Have you resolved the issue?

**Comment by shilpavij** [comment]
Validation is working fine for me as well. Is the issue resolved for you?

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
