### ISSUE TITLE
Create your own Fiori Launchpad

### ISSUE THREAD

**Issue by avonkorf** [SAPDocuments/Tutorials#3250]
Tutorial URL: https://developers.sap.com/tutorials/pre-teched-2018-fiori-create.html

Hello, I study Step 1: Go to Services. Unfortunately, there are no active pictures in the whole course. Please, check it. 
Thank you.

**Comment by firfarmer** [comment]
Confirmed...  the image links are broken.  I'm seeing this in other tutorials as well.  Looks like maybe images were refactored but tutorials have not been updated.  Often the images are important to the tutorial.

**Comment by thecodester** [comment]
This tutorial was created for the teched contest, and is no longer valid, and has been deleted. If you have issues with other tutorials, feel free to open an issue.
