### ISSUE TITLE
Add an XML fragment for a tab in your app

### ISSUE THREAD

**Issue by russellw999** [SAPDocuments/Tutorials#3256]
Tutorial URL: https://developers.sap.com/tutorials/teched-2016-6.html

Please specify the step you are referring to

Unfortunately this Tutorial from 2017 is tutorial 6 in a series of 10 SAP FIORI Tutorials and refers to a Detail View layout from an earlier version of the SAP Fiori Master Detail Template than used in tutorial number 4 ( Build and SAP Fiori App with SAP Gateway Data in SAP Web IDE ).   Therefore anyone following the tutorial series would not be able to make the changes to the layout specified to add the Map view.   Also a few data element difference for the current SAP Gateway ES5 GWSAMPLE_BASIC  OData service

**Comment by thecodester** [comment]
I will remove the series until we can update it. Thanks for the feedback.

**Comment by thecodester** [comment]
I have removed the tutorial.
