### ISSUE TITLE
Script blocked by uBlock origin prevents submitting answers

### ISSUE THREAD

**Issue by FreHu** [SAPDocuments/Tutorials#3257]
Without disabling adblock, I cannot submit answers due to the following script being blocked:
![image](https://user-images.githubusercontent.com/5097067/54981100-c7b26200-4fa7-11e9-835c-3b857e750bd6.png)

![image](https://user-images.githubusercontent.com/5097067/54981177-f6303d00-4fa7-11e9-8118-3c8bf70ebd91.png)

I generally don't encounter problems like this and would like to be better informed about the script's purpose.

**Comment by thecodester** [comment]
Can explain exactly what you do and what happens? Do you enter answer, press Validate, and then get ad block? Or something else?

**Comment by FreHu** [comment]
The javascript is prevented from loading completly, which causes javascript errors, which causes the button to not respond to actions.

According to the extension log, it is part of https://easylist.to/ 

(using uBlock Origin v1.18.10)

**Comment by thecodester** [comment]
@lpareek Can you help here? Do you know what we could do?

**Comment by lpareek** [comment]
Hi @FreHu,

You will have to add exception to uBlock.

![uBlock-exception](https://user-images.githubusercontent.com/13825376/55020279-e840e300-4fcc-11e9-89c9-104a03dcc899.png)

Regards,
Lalit
