### ISSUE TITLE
Create a Thing Model and Bind to Device

### ISSUE THREAD

**Issue by badichiniran** [SAPDocuments/Tutorials#3258]
Tutorial URL: https://developers.sap.com/tutorials/iot-express-4-create-thing-model.html

Please specify the step you are referring to
in step 5 you have to click save before moving to connectivity.
if you don't click save you won't see the property sets (see pic)
![image](https://user-images.githubusercontent.com/4293806/54981264-8ecabb00-4fb0-11e9-966e-1cc50b8c2edc.png)

**Comment by marcuscbehrens** [comment]
In step 5 we mention that you have to "Add the 2 property sets you worked on earlier and **save** your work. "

Do you think somethign should stil be improved? Thanks for the feedback in any case.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
