### ISSUE TITLE
Detailed Query Plan and Indexes

### ISSUE THREAD

**Issue by ganyang88** [SAPDocuments/Tutorials#3260]

**Comment by ganyang88** [comment]
> Tutorial URL: https://developers.sap.com/tutorials/dt-query-processing-part4.html
> 
> Please specify the step you are referring to:
> 
> Hello, dear colleagues,
> 
> THe picture in this page are all lost.
> Please double check it.
> 
> Thank you
> &
> Best Regards
> 
> Yang

Sorry, My mistake.
It's my chrome's problem.

**Comment by thecodester** [comment]
Hope it straightens out.

**Comment by thecodester** [comment]
@ganyang88 How did you know it was a Chrome issue?

**Comment by ganyang88** [comment]
> Hope it straightens out.

Thank you :)

**Comment by ganyang88** [comment]
> @ganyang88 How did you know it was a Chrome issue?

Good Question.
Acutally, I'm not 100% sure.
