### ISSUE TITLE
Run example pipelines in SAP Data Hub, developer edition 2.4

### ISSUE THREAD

**Issue by onixxl** [SAPDocuments/Tutorials#3261]
Tutorial URL: https://developers.sap.com/tutorials/datahub-docker-v2-examples.html

"Copy any row of the terminal output and paste it in the frame below..."
Hi, the answer is not accepted... i think something is wrong with code
My answer is:
[2019-03-26 11:49:32.801] 13,5,25.780016554360188,47.59644649783984,520.9761763567036,1.0732082853829794,24.481293410571684,50.0214261886894,0,689.0008725578615,496.5980218576377

**Comment by fx5151git** [comment]
Because the rule does not support complex regular expression, I think I need to change the question...

**Comment by fx5151git** [comment]
This should work now. Could you have a check? Thank you so much.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
