### ISSUE TITLE
Deploy HANA Express database on Google Kubernetes cluster

### ISSUE THREAD

**Issue by PavelSosin** [SAPDocuments/Tutorials#3265]
Tutorial URL: https://developers.sap.com/tutorials/hxe-kubernetes-google-cluster.html
Question: 
Please specify the step you are referring to Step 5 and further step
 Is / will docker composer and or OpenShift template supported?

**Comment by Lsubatin** [comment]
HANA Express is a community supported version. In other words, you can try Docker compose and OpenShift and turn to the community (answers.sap.com) if you run into issues. I personally haven't tried but but would like to know how it goes if you do.

**Comment by thecodester** [comment]
@PavelSosin Is your question answered?

**Comment by Lsubatin** [comment]
I'm assuming it is and closing. This belongs in answers.sap.com anyways.
