### ISSUE TITLE
Install SAP HANA 2.0, express edition

### ISSUE THREAD

**Issue by dellagustin** [SAPDocuments/Tutorials#3266]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-installing-binary.html

Please specify the step you are referring to: "You will learn"

This section says "You will learn how to *download* the binary image of SAP HANA 2.0, express edition"

but there is no instructions on how to download the files, only how to extract them and follows form there.

**Comment by JCurrie27** [comment]
https://developers.sap.com/tutorials/hxe-ua-installing-binary.html has been updated (as has the previous tutorial in the group). Thanks for your feedback,
