### ISSUE TITLE
SAP HANA XS Advanced, Creating a Simple OData Service

### ISSUE THREAD

**Issue by WoutB** [SAPDocuments/Tutorials#3267]
Tutorial URL: https://developers.sap.com/tutorials/xsa-xsodata.html

Step 1:
Where do I get this project structure from? I do not have the js/lib/... folders. Where can I get these?

**Comment by Lsubatin** [comment]
The js module gets first created here: https://developers.sap.com/mission.xsa-get-started.html

**Comment by thecodester** [comment]
@WoutB Did you figure out the issue?

**Comment by WoutB** [comment]
Yes I'm helped, thanks a lot!
