### ISSUE TITLE
Set Up SAP Data Hub, Developer Edition 2.4

### ISSUE THREAD

**Issue by juderegys** [SAPDocuments/Tutorials#3268]
Tutorial URL: https://developers.sap.com/tutorials/datahub-docker-v2-setup.html

Hello There,

After unpacking the datahub zip file, I executed the command: "docker build --tag datahub".

I received the following error:
"docker build" requires exactly 1 argument.
See 'docker build --help'.
Usage:  docker build [OPTIONS] PATH | URL | -
Build an image from a Dockerfile

Can you please help me to proceed?

Thanks,
Jude

**Comment by fx5151git** [comment]
already changed. Thanks

**Comment by fx5151git** [comment]
Hi, have you navigated to the directory where you have unpacked the archive (that is the directory which includes the Dockerfile) and open a terminal there?

**Comment by Sygyzmundovych** [comment]
Hi Jude. You need to include the dot at the end of the command, like
`docker build --tag datahub .`

That dot does not mean the end of the sentence, but the current folder where `Dockerfile` is located :)

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
