### ISSUE TITLE
Create and Run an ABAP Application

### ISSUE THREAD

**Issue by dygsylmz** [SAPDocuments/Tutorials#3269]
Tutorial URL: https://developers.sap.com/tutorials/abap-create-basic-app.html

When I finished one step I tried to click done button but it doesn't work. This situation applies to all. I can't click anything, Im curios why?

**Comment by thecodester** [comment]
Were you signed in?

**Comment by dygsylmz** [comment]
Yes I am , also I can't see some pictures.

**Comment by thecodester** [comment]
Strange, I can see pictures and I can complete the done buttons. Is it only on that tutorial? On pictures, try clearing cache.

**Comment by dygsylmz** [comment]
Something wrong with my account ? Different tutorial also same too. I click the button but doesn't work.

**Comment by thecodester** [comment]
Can you send a picture of what you get after clicking Done buttons?

**Comment by thecodester** [comment]
I haven't heard back from you. If this is still an issue, feel free to provide additional information.
