### ISSUE TITLE
Building freestyle IoT application

### ISSUE THREAD

**Issue by amarpreet** [SAPDocuments/Tutorials#3271]
Tutorial URL: https://developers.sap.com/tutorials/iotae-comp-buildappmc0.html

In the tutorial mentioned above. 
On step number 4, While going through the wizard to create a Freestyle IOT application template, it is mentioned that the data **Freestyle-IOTAS-ADVANCEDLIST-THING-ODATA**  should be selected. I do not have this in my drop down. 

From the research that I've done this can be brought in by using the Update IOT destination option in webide but this requires me to enter some details, I understand that some of these details I already have e.g. the Username and password  and URL for the thing modeller etc.. but I'm not able to get the remaining details. Searching for this only leads me posts of where others are asking the same question or to more content where this is already set up and no information on how this is set up.

Any help here would be greatly appreciated. 

Amarpreet.

**Comment by amarpreet** [comment]
nothing?

**Comment by marcuscbehrens** [comment]
Hi, sorry, for the late reply. Please refer to the getting started section of the leonardo iot page at help.sap.com. It will walk you through all the steps including the retrieval of the service key needed for (re-)creatign the destinations. Regards, Marcus

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
