### ISSUE TITLE
Import Tables and Large Datasets (XS Advanced)

### ISSUE THREAD

**Issue by Calibras** [SAPDocuments/Tutorials#3272]
Tutorial URL: https://developers.sap.com/tutorials/xsa-import-shine-data.html

Step 3: Purge duplicates and Build
Hello, nice tutorial but i got a problem when i try to build. I had import the data.zip from git like in the tutorial and delete the three files. But When i try to build i get an error. I would look in the build logs when i now how i can do this.
Thangs for Help.

**Comment by Lsubatin** [comment]
The error log for the build is in the console. You probably need to scroll up until your find the word ERROR. 
![image](https://user-images.githubusercontent.com/24896969/55071367-d3149480-505e-11e9-8651-4d37c42ba51c.png)

**Comment by Lsubatin** [comment]
Closing on inactivity. Please post the relevant error logs in a question in answers.sap.com.
