### ISSUE TITLE
Create a Simple ABAP CDS View in ADT

### ISSUE THREAD

**Issue by dygsylmz** [SAPDocuments/Tutorials#3274]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-adt-create-cds-view.html

Test yourself doesn't work, I wrote my code but nothing..Also view has no data, first I thought I do something wrong but I just copy paste code and try again but nothing.

**Comment by thecodester** [comment]
When you say "nothing", what do you mean? What exactly did you do and what exactly happens?

**Comment by dygsylmz** [comment]
![image](https://user-images.githubusercontent.com/18638615/55077749-915d0b80-50a9-11e9-92d7-07aac41ec252.png)
![image](https://user-images.githubusercontent.com/18638615/55077776-a33eae80-50a9-11e9-8a86-d4a7fe2b3027.png)

**Comment by dygsylmz** [comment]
my code and what happened when I run my code

**Comment by julieplummer20** [comment]
What code did you enter in the Test Yourself space?

**Comment by dygsylmz** [comment]
@julieplummer20 I think something wrong with my account because when I click any button doesn't work.
I enter " product.product_description"

**Comment by julieplummer20** [comment]
Hi, 
1. Actually, I was looking for the whole path: sepm_sddl_so_invoice_item.product.product_name
However, I will reformulate the question as multiple-choice. Too many people are tripping up over the precise wording.

2. Did you run transaction SEPM_DG_OIA, SEPM_DG_OIA_NEW or tasklist STC01 -> SAP_BASIS_EPM_OIA_CONFIG  ? I will update the prerequisites accordingly.

Best wishes, Julie.

**Comment by thecodester** [comment]
@dygsylmz Has this issue been resolved?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
