### ISSUE TITLE
Use the Sample OData Service for Mobile Apps

### ISSUE THREAD

**Issue by firfarmer** [SAPDocuments/Tutorials#3278]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-hcpms-sample-odata-service.html

The image links for this tutorial appear to be broken.

**Comment by thecodester** [comment]
I see them. Clear cache? Try again? If some are still missing, can you list which ones?

**Comment by firfarmer** [comment]
It was not a cache issue because when I went directly to the image link I got a 401.  However, a spot check does show that they are being fixed.  I'm wondering if this was all due to the Revert "Delete old SAPUI5 tutorials" checkin and perhaps that invalidated the image links.  Note that the tutorials are linking to Github via a proxy, e.g. "/_jcr_content.github-proxy.1552396565.file/Markdown_files/img_000.png"

**Comment by thecodester** [comment]
Yes, they are being fixed, thankfully. Let me know if the problem persists.
