### ISSUE TITLE
Implement Logic for a Custom Business Object

### ISSUE THREAD

**Issue by PeterHaynes** [SAPDocuments/Tutorials#3279]
Tutorial URL: https://developers.sap.com/tutorials/abap-extensibility-cbo-logic.html

There's no complete button for step 2 so you can't mark the group as completed.

**Comment by Liebherr** [comment]
Hi Peter,
thank you for finding this issue.
As I was already reworking the whole tutorial group a little this simple fix needed a some time longer.
Please excuse the delay.
Thank you for closing the issue, if it is solved for you now.
Regards
Ulrike

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
