### ISSUE TITLE
Create Cards with Actions (Like Approve Or Reject)

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Tutorials#3280]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-action.html

Step 6 - When doing as described I get:

"You are not authorized to access SAP Cloud Platform, SAP Cloud Platform Mobile Services. Log in with the correct role, or contact system administrator."

**Comment by jitendrakansal** [comment]
@mts2605 quite a strange error. 
If there were issue in authorization to access Mobile Services, you would have stopped in step1 itself. 
Can you try to open Mobile Services in Cockpit in a private or incognito window after clearing browser cache?

**Comment by amitcruz** [comment]
Hello @jitendrakansal  , Images in the above tutorial seems broken . I am facing this issue in other tutorials . When it is going to be fixed ?

**Comment by thecodester** [comment]
We are working on the images. Will update soon.

**Comment by jitendrakansal** [comment]
@amitcruz I can see Images now, please check it again

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you (@mts2605) in a while, so we are closing the issue. The images issue should be resolved.

If you still have questions, feel free to reopen the issue.

@jitendrakansal I have republished the tutorial to try to fix the issue with the first image.
