### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by Calibras** [SAPDocuments/Tutorials#3283]
Tutorial URL: https://developers.sap.com/tutorials/xsa-create-user-provided-anonymous-service.html

Hello, i got a Problem in step 7 add a synonym. When i try to link to the PRODUCT_SEGMENT then i become a build error. Which that 
"PLAIN.PRODUCT_SEGMENT" synonym target does not exist.
I had created the schema and the table row with exact the SQL statement from step 2. So the PRODUCT_SEGMENT row is in the PLAIN schema. Im a little confused.

**Comment by Lsubatin** [comment]
Hi, this belongs in answers.sap.com.  I believe I addressed the same question there and requested the logs for the activation of the grants file only. If that wasn't your question, please include a screenshot of your project structure and the output of the build of the hdbgrants file.
