### ISSUE TITLE
Deploy Your Node.js App with the Cloud Foundry CLI

### ISSUE THREAD

**Issue by nicobost-sap** [SAPDocuments/Tutorials#3285]
Tutorial URL: https://developers.sap.com/tutorials/cp-node-deploy-cf-cli.html

Please specify the step you are referring to

Great tutorial, thanks a lot! 
But I think it could be clearer specified what files needs to be in which directory or which statement needs to be executed out of which directory. I have been able to figure it out (good learning for me :) ), but more defined senteneces would help here.

**Comment by maxstreifeneder** [comment]
@nicobost-sap hope it's clear now.
