### ISSUE TITLE
View the SAP Cloud Platform from 10,000 Meters - missing screenshots

### ISSUE THREAD

**Issue by FreHu** [SAPDocuments/Tutorials#3292]
Tutorial URL: https://developers.sap.com/tutorials/cp-explore-cloud-platform.html
![image](https://user-images.githubusercontent.com/5097067/55382044-f3dc5e80-5524-11e9-977a-372a0a96c7c3.png)

![image](https://user-images.githubusercontent.com/5097067/55382028-e45d1580-5524-11e9-89a5-bf007e1de298.png)

**Comment by thecodester** [comment]
I see the images. Can you check again?

**Comment by FreHu** [comment]
They're there now. Issue must have fixed itself somehow.
