### ISSUE TITLE
Create a Simple Database Table for ABAP Environment

### ISSUE THREAD

**Issue by reinhardjaeschke** [SAPDocuments/Tutorials#3293]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-create-table.html

this is a very interesting tutorial, but unfortunately is essential information missing because the screenshots are not visible.

**Comment by thecodester** [comment]
Sorry for the issue. Can you check again? I see the images now.

**Comment by reinhardjaeschke** [comment]
Wow, that was fast!

Yes I can see them now, too!

Kind Regards / Viele Grüße

Reinhard Jaeschke


Von: Daniel Wroblewski <notifications@github.com>
Gesendet: Dienstag, 2. April 2019 10:02
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Reinhard Jaeschke <Jaeschke@wmd.de>; Author <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Create a Simple Database Table for ABAP Environment (#3293)


Sorry for the issue. Can you check again? I see the images now.

**Comment by thecodester** [comment]
Glad it worked. Sorry for the inconvenience.

**Comment by reinhardjaeschke** [comment]
Hey Daniel,

I just checked the other tutorials for SAP Cloud Platform, ABAP environment.
In all of them are the Screenshots missing …

Kind Regards / Viele Grüße

Reinhard Jaeschke

WMD Group GmbH I Workflow Management & Document Consulting
Hamburger Straße 12 I D-22926 Ahrensburg
Tel. + 49 (0) 4102 88 38-889
eMail: jaeschke@wmd.de<mailto:jaeschke@wmd.de> I www.wmd.de<http://www.wmd.de/>

Von: Daniel Wroblewski <notifications@github.com>
Gesendet: Dienstag, 2. April 2019 10:08
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Reinhard Jaeschke <Jaeschke@wmd.de>; Author <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Create a Simple Database Table for ABAP Environment (#3293)


Glad it worked. Sorry for the inconvenience.

**Comment by thecodester** [comment]
I went through the 7 tutorials in the missions and they all had images. Can you tell me which ones might be missing?

**Comment by reinhardjaeschke** [comment]
At the moment, the pictures are visible.
Thank you.

Kind Regards / Viele Grüße

Reinhard Jaeschke

WMD Group GmbH I Workflow Management & Document Consulting
Hamburger Straße 12 I D-22926 Ahrensburg
Tel. + 49 (0) 4102 88 38-889
eMail: jaeschke@wmd.de<mailto:jaeschke@wmd.de> I www.wmd.de<http://www.wmd.de/>

Von: Daniel Wroblewski <notifications@github.com>
Gesendet: Dienstag, 2. April 2019 15:03
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Reinhard Jaeschke <Jaeschke@wmd.de>; Author <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Create a Simple Database Table for ABAP Environment (#3293)


I went through the 7 tutorials in the missions and they all had images. Can you tell me which ones might be missing?
