### ISSUE TITLE
Maintain Platform Subaccounts and SAP Web IDE Permissions

### ISSUE THREAD

**Issue by charbelkisso** [SAPDocuments/Tutorials#3294]
Tutorial URL: https://developers.sap.com/tutorials/abap-custom-ui-subaccount-permission.html

images are not showing

**Comment by thecodester** [comment]
Can you check again? I see the images...perhaps took a few minutes to be loaded into cache.

**Comment by charbelkisso** [comment]
Hello again,

![image](https://user-images.githubusercontent.com/25483315/55400792-1e431180-554f-11e9-8ab5-829b8fe8171a.png)

you can check the repo the webide.png has 0 size

https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/abap-custom-ui-subaccount-permission/webide.png

thank you in advanced!
//Charbel

**Comment by mervey45** [comment]
@charbelkisso I see the issue now, I'll update this tutorial. Thank you

**Comment by thecodester** [comment]
https://github.com/SAPDocuments/Tutorials/pull/3289

@charbelkisso Fixed for you?

**Comment by charbelkisso** [comment]
works fine :)
