### ISSUE TITLE
Add Transactional Behavior to Your Core Data Services

### ISSUE THREAD

**Issue by reinhardjaeschke** [SAPDocuments/Tutorials#3295]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-transactional-enablement.html

Sorry, but the screenshots for this tutorial are not visible.

**Comment by thecodester** [comment]
Please check again. Do you see them now?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
