### ISSUE TITLE
Extend a Workflow Definition with an Exclusive Gateway

### ISSUE THREAD

**Issue by amitcruz** [SAPDocuments/Tutorials#3296]
Tutorial URL: https://developers.sap.com/tutorials/cp-wf-03-add-excl-gw.html

Hello @qmacro 
Some of the images in the tutorials seems broken . Let us know when it is going to be fixed .  This issue is not pertaining to this tutorial . There are other tutorials  which has broken images,.
For eg:  Below image is not opening

https://developers.sap.com/tutorials/cp-wf-03-add-excl-gw/_jcr_content.github-proxy.1543817409.file/single-flow.png

**Comment by qmacro** [comment]
Thanks for the report, @amitcruz . Passing to @thecodester to follow up with the team. Cheers!

**Comment by thecodester** [comment]
@amitcruz I see the images have redeployed. Do you see them in all 7 tutorials of the mission now?

**Comment by amitcruz** [comment]
@thecodester Thanks it is fixed now . Please close the thread.
