### ISSUE TITLE
Open SAP Web IDE Full-Stack in SAP Cloud Platform

### ISSUE THREAD

**Issue by amitcruz** [SAPDocuments/Tutorials#3297]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-webide-open-webide.html

@thecodester  Whats going on . Now images has been broken for this tutorial . Is any maintenance work going on ?

**Comment by thecodester** [comment]
There is some work that seems to have flushed the images but they are returning. Do you see images in this tutorial now?

**Comment by amitcruz** [comment]
Please close the thread.
