### ISSUE TITLE
Create a Simple Database Table for ABAP Environment

### ISSUE THREAD

**Issue by amitcruz** [SAPDocuments/Tutorials#3298]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-create-table.html

@thecodester  : Images for this tutorial is also not working . Please check.

**Comment by CESolomon** [comment]
You have to turn off content blocking in your browser.

**Comment by thecodester** [comment]
@mervey45 Can you republish the tutorial?

**Comment by mervey45** [comment]
@thecodester I'll republish it.

**Comment by thecodester** [comment]
@amitcruz Can you see images now?

**Comment by amitcruz** [comment]
Yes , please close it . Hope to see more consistency in image viewing from now onwards.
