### ISSUE TITLE
Create a Producer App

### ISSUE THREAD

**Issue by amitcruz** [SAPDocuments/Tutorials#3299]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-rabbitmq-create-producer.html

Sorry to say @thecodester the missing image issue is not yet fixed . Please fix it on priority

**Comment by thecodester** [comment]
I've opened up all the cp-cf tutorials and see all the images. Do you see them now? 

If yes, good. If not, there would be an issue in the load balancer, which I can look into.

**Comment by thecodester** [comment]
Can you do the tutorial now?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
