### ISSUE TITLE
Create an HTTP Service

### ISSUE THREAD

**Issue by reinhardjaeschke** [SAPDocuments/Tutorials#3300]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-create-http-service.html

Why is it so difficult to make sure that the images are visible?
Most tutorials are not usable, because the images containing crucial information do not load. 
:-(

**Comment by thecodester** [comment]
I ask myself the same question :-)

I see them now. It took a while to restore the image cache. Do you see them?

**Comment by reinhardjaeschke** [comment]
Sorry, but no.
Most of the tutorials are currently broken.

Kind Regards / Viele Grüße

Reinhard Jaeschke

WMD Group GmbH I Workflow Management & Document Consulting
Hamburger Straße 12 I D-22926 Ahrensburg
Tel. + 49 (0) 4102 88 38-889
eMail: jaeschke@wmd.de<mailto:jaeschke@wmd.de> I www.wmd.de<http://www.wmd.de/>

Von: Daniel Wroblewski <notifications@github.com>
Gesendet: Mittwoch, 3. April 2019 12:29
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Reinhard Jaeschke <Jaeschke@wmd.de>; Author <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Create an HTTP Service (#3300)


I ask myself the same question :-)

I see them now. It took a while to restore the image cache. Do you see them?

**Comment by thecodester** [comment]
![image](https://user-images.githubusercontent.com/11659786/55472664-5b71d700-5615-11e9-8011-4ba4b9a2a316.png)

Perhaps clear the cache when you load the page.

**Comment by reinhardjaeschke** [comment]
The cache is not the problem. That has been cleared.
Chrome debugger gives this:

[cid:image001.png@01D4EA1A.86C05D30]

Kind Regards / Viele Grüße

Reinhard Jaeschke

WMD Group GmbH I Workflow Management & Document Consulting
Hamburger Straße 12 I D-22926 Ahrensburg
Tel. + 49 (0) 4102 88 38-889
eMail: jaeschke@wmd.de<mailto:jaeschke@wmd.de> I www.wmd.de<http://www.wmd.de/>

Von: Daniel Wroblewski <notifications@github.com>
Gesendet: Mittwoch, 3. April 2019 12:36
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Reinhard Jaeschke <Jaeschke@wmd.de>; Author <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Create an HTTP Service (#3300)


[image]<https://user-images.githubusercontent.com/11659786/55472664-5b71d700-5615-11e9-8011-4ba4b9a2a316.png>

Perhaps clear the cache when you load the page.

**Comment by thecodester** [comment]
Can't see the screen capture

**Comment by reinhardjaeschke** [comment]
The network console shows HTTP GET 404 file not found errors.

Kind Regards / Viele Grüße

Reinhard Jaeschke

WMD Group GmbH I Workflow Management & Document Consulting
Hamburger Straße 12 I D-22926 Ahrensburg
Tel. + 49 (0) 4102 88 38-889
eMail: jaeschke@wmd.de<mailto:jaeschke@wmd.de> I www.wmd.de<http://www.wmd.de/>

Von: Daniel Wroblewski <notifications@github.com>
Gesendet: Mittwoch, 3. April 2019 13:01
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Reinhard Jaeschke <Jaeschke@wmd.de>; Author <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Create an HTTP Service (#3300)


Can't see the screen capture

**Comment by thecodester** [comment]
We place the images in server cache and the images apparently didn;t make, but I see them now. Can you check?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
