### ISSUE TITLE
Deploy UI to Cloud Foundry

### ISSUE THREAD

**Issue by reinhardjaeschke** [SAPDocuments/Tutorials#3301]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-cf-deploy.html

Sorry, but images are - again - not visible here...

**Comment by thecodester** [comment]
I see them now. It took a while to restore the image cache. Do you see them?

**Comment by reinhardjaeschke** [comment]
Sorry, but no.
Most of the tutorials are currently broken.

Kind Regards / Viele Grüße

Reinhard Jaeschke

WMD Group GmbH I Workflow Management & Document Consulting
Hamburger Straße 12 I D-22926 Ahrensburg
Tel. + 49 (0) 4102 88 38-889
eMail: jaeschke@wmd.de<mailto:jaeschke@wmd.de> I www.wmd.de<http://www.wmd.de/>

Von: Daniel Wroblewski <notifications@github.com>
Gesendet: Mittwoch, 3. April 2019 12:28
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Reinhard Jaeschke <Jaeschke@wmd.de>; Author <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Deploy UI to Cloud Foundry (#3301)


I see them now. It took a while to restore the image cache. Do you see them?

**Comment by thecodester** [comment]
Now? I'm confused because I can see them here.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
