### ISSUE TITLE
API portal service error

### ISSUE THREAD

**Issue by VivekRajKM** [SAPDocuments/Tutorials#3303]
With reference to the tutorial: Enable Services for Sales Tracker App.
Trying to access the API portal, facing the below issue attached image.

**Comment by VivekRajKM** [comment]
![API Portal](https://user-images.githubusercontent.com/17874349/55471584-b44a6b00-5627-11e9-8d7d-446ba9e7cbac.JPG)

**Comment by shilpavij** [comment]
Hello,
Did you enable the service?
Can you please sign in with a different gmail account->enable your service->and try it again.
If still, it doesn't work then create an issue on OPU-API-OD-DT and also drop me a note via email.

Regards
Shilpa

**Comment by VivekRajKM** [comment]
Hello,
I did enable the service for API portal, will raise a ticket on the mentioned path. Thanks Shilpa.

Regards,
Vivek.

**Comment by shilpavij** [comment]
Hello Vivek,

Can you please try enabling with a different user.
If still it doesn’t work raise an issue.

Regards
Shilpa

**Comment by VivekRajKM** [comment]
@shilpavij For some reasons, when tried reloading API portal is active and accessible now. Maybe a temporary glitch, thanks for the support Shilpa.

Cheers,
Vivek.
