### ISSUE TITLE
Image links not loading!

### ISSUE THREAD

**Issue by VivekRajKM** [SAPDocuments/Tutorials#3304]

**Comment by VivekRajKM** [comment]
Duplicate of #2186
Images aren't loading for the tutorial : 'Discover Sales Order API from S/4HANA Cloud System'

![Image loading error](https://user-images.githubusercontent.com/17874349/55472271-51f26a00-5629-11e9-8128-09a59c2b4d13.JPG)

**Comment by thecodester** [comment]
https://developers.sap.com/tutorials/cp-apim-sales-tracker-api-discover.html

I see them!!??

![image](https://user-images.githubusercontent.com/11659786/55472576-1d74b300-5615-11e9-900a-f82cb3f3de48.png)

**Comment by VivekRajKM** [comment]
@thecodester I am able to see now, might be a temporary glitch. Thank you! :)
