### ISSUE TITLE
SAP HANA XS Advanced, Creating an OData Service with Create Operation and XSJS Exit

### ISSUE THREAD

**Issue by Calibras** [SAPDocuments/Tutorials#3305]
Tutorial URL: https://developers.sap.com/tutorials/xsa-xsodata-create.html

Hello, 
I got problems to call the create request and i thing i also find an error in some code snippet of the tutorial. Because i can not even get the metadata of the service.

my Sapui5 code to create  an entry looks like this 
`var entity = {"FirstName": "Martin", "LastName": "Lauch", "Email": "foo.bar@foobar.de"}
var oModel = new sap.ui.model.odata.v2.ODataModel("/xsodata/user.xsodata", false)
OModel.setUseBatch(false);
oModel.create("/Users", entity)
`
I am not so familiar with UI5 and do not now if this is right or not. 

I also got the felling thath the code of the  user.xsodata in step 3.
the code in the tutorial says this 
`"User.Details" as "Users"`
the thing is that this "path" not exist, so i . switched it out to 
`"UserData.User" as "Users"`
When i changed this i can get an metadata, but im not sure. If this corect is or not.

**Comment by Lsubatin** [comment]
This will depend on what your project looks like and what  names you've been using. You can find a similar code structure here for further reference: https://github.com/SAP/com.sap.openSAP.hana5.example/tree/master/user-js/lib/user/xsodata

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
