### ISSUE TITLE
Destination wizard is not in sync

### ISSUE THREAD

**Issue by VivekRajKM** [SAPDocuments/Tutorials#3306]
Hello Team,
Observed few difference in the statement mentioned in the tutorial and descriptive picture highlighted. Could you please revert it to actual one, SAP mobile cards have been upgraded and the version highlighted in the tutorial looks like a older version. Correct me if I am wrong, TIA.

Note: Step #3 in 'Download SAP Mobile Cards to Your Device'

![Destination wizard](https://user-images.githubusercontent.com/17874349/55483578-7b6cbf00-5644-11e9-85db-a018cd55cb8f.JPG)

**Comment by shilpavij** [comment]
Platform destination name correctedhttps://github.com/SAPDocuments/Tutorials/issues/3306

**Comment by thecodester** [comment]
Has this issue been resolved?

**Comment by VivekRajKM** [comment]
@thecodester  It wasn't an issue, but was little missed info., Corrected now, thanks @shilpavij  and @thecodester  for all brilliant efforts. :)

**Comment by shilpavij** [comment]
Hello Daniel,

I have already written to Meredith.

Regards
Shilpa
