### ISSUE TITLE
Creation of sample data in mobile cards

### ISSUE THREAD

**Issue by VivekRajKM** [SAPDocuments/Tutorials#3307]
Hello Team,
Observed differences in Step 1 of 'Use Mobile Services to Create UI', while creating a sample data, we didn't find any options to browse through the .json file to be consumed. 
Whilst trying those query URL in data endpoints, it still doesn't fetch the data as mentioned. Your expertise is highly appreciated.

Attaching image for your reference, TIA.

![Sample data](https://user-images.githubusercontent.com/17874349/55484079-78260300-5645-11e9-80bc-833978c48b76.JPG)
![Data endpoint definition](https://user-images.githubusercontent.com/17874349/55484422-174afa80-5646-11e9-9c3a-f07cb1e5f5e9.JPG)

**Comment by shilpavij** [comment]
Dear team,

There is a UI and functionality change and I am talking to concerned people for the same . I will work on the tutorial as soon as I get input. Mostly by this week it should be done.

Regards
Shilpa

**Comment by shilpavij** [comment]
Dear Colleagues,

I have pushed the changes with #3440

Regards
Shilpa

**Comment by thecodester** [comment]
merged
