### ISSUE TITLE
Install the Optional SAP HANA Automated Predictive Library Package for SAP HANA, express edition (Native Linux Machine)

### ISSUE THREAD

**Issue by sebherv** [SAPDocuments/Tutorials#3308]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-apl-binary.html

Please specify the step you are referring to

Step 1 "Download apl.gz" is not very clear: it suggest that we are to use some external download manager.

This section should be beginning by something like "In order to download the APL library, use the Download manager with the following commands, ...".

**Comment by JCurrie27** [comment]
Thanks for this feedback. Clarifications to this tutorial are in process.

**Comment by JCurrie27** [comment]
[https://developers.sap.com/tutorials/hxe-ua-apl-binary.html](https://developers.sap.com/tutorials/hxe-ua-apl-binary.html)
This tutorial was updated. Closing issue.
