### ISSUE TITLE
Install the Optional SAP HANA Automated Predictive Library Package for SAP HANA, express edition (Native Linux Machine)

### ISSUE THREAD

**Issue by sebherv** [SAPDocuments/Tutorials#3309]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-apl-binary.html

Please specify the step you are referring to

Step 2:

The directory where the apl.tgz file has been downloaded to is not indicated !
It took me 1 hour to notice that the file has been downloaded into de ~/Downloads directory, instead of the current directory.

So somewhere there should be 
cd ../Downloads

Before calling tar

**Comment by JCurrie27** [comment]
Thanks for this feedback. Clarifications to this tutorial are in process.

**Comment by JCurrie27** [comment]
[https://developers.sap.com/tutorials/hxe-ua-apl-binary.html](https://developers.sap.com/tutorials/hxe-ua-apl-binary.html)
This tutorial was updated. Closing issue.
