### ISSUE TITLE
Time Series with SAP HANA PAL (Forecast App)

### ISSUE THREAD

**Issue by sebherv** [SAPDocuments/Tutorials#3311]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aa-forecast-06.html

Please specify the step you are referring to

Step 5: the common.hdbcds filename is spelt "commmon.hdbcds", with 3 "m"'s instead on 2.

**Comment by adadouche** [comment]
Thanks you. It now fixed.

@bdel
