### ISSUE TITLE
Image Classification with SAPUI5

### ISSUE THREAD

**Issue by K-MUS** [SAPDocuments/Tutorials#3312]
Tutorial URL: https://developers.sap.com/tutorials/ml-fs-sapui5-img-classification.html

Please specify the step you are referring to 

Step 16 Validation

![image](https://user-images.githubusercontent.com/15014750/55569807-96890e80-56d8-11e9-936b-3ddafaa074ae.png)

I paste the text and it stills tell me is incorrect attached the image as evidence.

![image](https://user-images.githubusercontent.com/15014750/55569928-cf28e800-56d8-11e9-9a43-8a58aab28cb7.png)

**Comment by adadouche** [comment]
Hi @K-MUS 

Thanks for your feedback? The API endpoint changed so I adjusted the validation rule.

It should work now.

@bdel
