### ISSUE TITLE
Topic Detection with SAPUI5

### ISSUE THREAD

**Issue by K-MUS** [SAPDocuments/Tutorials#3313]
Tutorial URL: https://developers.sap.com/tutorials/ml-fs-sapui5-topic-detection.html

Please specify the step you are referring to

Step 13  - Validation

![image](https://user-images.githubusercontent.com/15014750/55571540-1369b780-56dc-11e9-94c8-bfb5136aaf31.png)

The validation doesn't work

![image](https://user-images.githubusercontent.com/15014750/55571524-0c42a980-56dc-11e9-83b7-faf88e322dbf.png)

**Comment by adadouche** [comment]
Hi @K-MUS

Thanks for your feedback? The API changed so I adjusted the validation rule.

It should work now.

@bdel
