### ISSUE TITLE
Create a Business Service Using CDS

### ISSUE THREAD

**Issue by johanngoltz** [SAPDocuments/Tutorials#3314]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-01-create-business-service.html

In step 4, _Test-run the service_, the provision fails with an error message: 

> Could not create the 'Bookshop-Bookshop-hdi-container-D0c+OyVcyZOKxAkjEv' instance of the 'hana' service type for the 'Bookshop-hdi-container' resource. Could not create the 'Bookshop-Bookshop-hdi-container-D0c+OyVcyZOKxAkjEv' service instance. Failed to select a database for instance 5ac6723f-0b39-4819-99be-8a401b37cad5, no database mapped to organization 'a2f76378-b6d5-476c-ae43-da59bbaece64' space '1dff411e-3bb0-4734-8fe5-5f0a95a53f52'

The Hana entitlement is assigned to the correct space. A look at #2925 suggests the error might be related to the data center I'm working from (us30). I couldn't test in other regions because my account is not entitled to Hana there.

**Comment by Apfohlmann** [comment]
@chgeo can you help Johann with this issue?

**Comment by chgeo** [comment]
Mere HANA entitlements are not sufficient.  Please check if there is a service instance of type 'hana-db' available for your space, which represents an actual HANA DB.
See [here](https://help.sap.com/viewer/cc53ad464a57404b8d453bbadbc81ceb/Cloud/en-US/21418824b23a401aa116d9ad42dd5ba6.html) for how to create such an instance, and [here](https://help.sap.com/viewer/cc53ad464a57404b8d453bbadbc81ceb/Cloud/en-US/390b47b7c0314d57a1829a0759a71ace.html) to map it to different spaces within the same organization.

**Comment by johanngoltz** [comment]
I do not have the hana-db service available to me. Is it even a part of the free Cloud Platform trial? If not, the tutorial cannot be completed with a free account, right?

**Comment by chgeo** [comment]
Ok, so you are using a trial landscape?
I know there is a free HANA trial in `eu10`, but for `us` I am not sure.  @AlexRieder can you answer this?

**Comment by johanngoltz** [comment]
The error I posted initially does not occur in `eu10`. I can create a hanatrial there without any problems, but not in `us30`, so something _must_ be different there...

**Comment by chgeo** [comment]
Yes, we would need a statement on HANA availability on `us30` here, which is why I pinged @AlexRieder.

**Comment by arieder83** [comment]
As far as I know there is no HANA on us30 (GCP) would it be an alternative to use us10?

**Comment by johanngoltz** [comment]
Sure. Maybe making sure that Hana is available in the selected region should be added as a tutorial step, then.

**Comment by chgeo** [comment]
@Apfohlmann can you add a statement for HANA in the prerequisites of the tutorial?  We shouldn't mention landscape names, though, since this is subject to change, but tell that HANA needs to be available in the trial account.

**Comment by chgeo** [comment]
Apart from that, let's close this issue.

**Comment by Apfohlmann** [comment]
@chgeo I will add it to the tutorial.

@thecodester you can close this issue.
