### ISSUE TITLE
Create an OData Destination

### ISSUE THREAD

**Issue by jinigirl** [SAPDocuments/Tutorials#3315]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-ms-graph-create-destination.html

Please specify the step you are referring to:
The destination details I inputted is correct (I got the same message when I ran the Check Connection).
However, metadata is still not loading when I ran the index.html.

**Comment by IObert** [comment]
Thanks for opening this issue @jinigirl.
Unfortunately, the "Check Connection" function only checks if the host is reachable, but not if the credentials are correct. Are you able to log in successfully via the[ web interface ](https://sapes5.sapdevcenter.com/sap/bc/gui/sap/its/webgui) ?

**Comment by jinigirl** [comment]
Hello Marius,

Yes, I can access the web interface.
I used the connection details provided but I encounter the error.

Thanks,
Jini

**Comment by IObert** [comment]
Hi Jini,

good to know that loggin in via the web interface works for you.
What error message do you get on the "metadata" request? And can you share your `neo-app.json` file with me?

**Comment by jinigirl** [comment]
Hello Marius,

Below is the snip of my neo-app.json file.
I find that I get errors when following the format in the tutorial.
[image: image.png]

Thanks,
Jini

**Comment by jinigirl** [comment]
I tried copying the file from tutorial line by line.
I get below error:
[image: image.png]

[image: image.png]

**Comment by IObert** [comment]
Hi Jini,

it seems that the images get lost when you use the email reply function. Can you use the web interface?

**Comment by jinigirl** [comment]
Hello Marius,

I'm sorry; I don't think I understood the instruction.

**Comment by IObert** [comment]
Can you upload the screenshots [here](https://github.com/SAPDocuments/Tutorials/issues/3315#issuecomment-480798524)?

**Comment by jinigirl** [comment]
Hello,

Please find attached file for my neo-app.json file.
I followed the steps in the instructions.

![image](https://user-images.githubusercontent.com/36019912/56258808-76f3dc00-6103-11e9-8c61-4a4759e334b1.png)

**Comment by IObert** [comment]
This looks right. Can you also add a screenshot of the error message you get when you request the metadata?

And can you try to remove and re-create your destination in the Cloud Cockpit?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
