### ISSUE TITLE
Set Up SAP Data Hub, Developer Edition 2.4

### ISSUE THREAD

**Issue by thomasalexneuhaus** [SAPDocuments/Tutorials#3316]
Tutorial URL: https://developers.sap.com/tutorials/datahub-docker-v2-setup.html

Please specify the step you are referring to

Its not posibile to mark all steps with done and complite!

Step 5: Perform a smoke test
The port 50070: http://localhost:50070 (Apache Hadoop User Interface) ist not alloud with windwos 10. Take a other port 9870

**Comment by thecodester** [comment]
Please add validation to this tutorial. Without it, people will not be able to get credit for the entire mission.

**Comment by fx5151git** [comment]
I will change the validation as soon as possible. But I am using win10, and the port 50070 works fine in my computer. Could you maybe provide more details about this?

**Comment by thomasalexneuhaus** [comment]
Hello Xiao

Thats the error what I get:

#docker run -ti --publish 127.0.0.1:50070:50070 --name hdfs --hostname hdfs --net dev-net datahub run-hdfs C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint hdfs (7bf60e8a820af7157f693a0da72cd0b6cadb534d0ebb2c3f704e8ef21668a851): Error starting userland proxy: Bind for 127.0.0.1:50070: unexpected error Permission denied.

Windows 10 Pro
Version: 1809
Build: 17763.195

Regards Thomas


Von: Xiao Feng <notifications@github.com>
Gesendet: Montag, 8. April 2019 09:19
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Thomas Neuhaus <thomas.neuhaus@agilita.ch>; Author <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Set Up SAP Data Hub, Developer Edition 2.4 (#3316)


I will change the validation as soon as possible. But I am using win10, and the port 50070 works fine in my computer. Could you maybe provide more details about this?

**Comment by fx5151git** [comment]
I just saw the bug page. I will change it soon. Thanks for pointing out.

**Comment by thomasalexneuhaus** [comment]
Hello Xiao

Thank you for the great tutorial.

Regards Thomas

Von: Xiao Feng <notifications@github.com>
Gesendet: Montag, 8. April 2019 10:10
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Thomas Neuhaus <thomas.neuhaus@agilita.ch>; Author <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Set Up SAP Data Hub, Developer Edition 2.4 (#3316)


I just saw the bug page. I will change it soon. Thanks for pointing out.

**Comment by Sygyzmundovych** [comment]
@thomasalexneuhaus What Docker version do you use on your Win10? Is it Docker for Desktop?

Can you try without the IP address in the command?

docker run -ti --publish 50070:50070 --name hdfs --hostname hdfs --net dev-net datahub run-hdfs

**Comment by thomasalexneuhaus** [comment]
Hello Vitaliy

With out IP is also not running

[cid:image001.png@01D4EE01.E0FCD130]

Von: Vitaliy Rudnytskiy <notifications@github.com>
Gesendet: Montag, 8. April 2019 11:42
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Thomas Neuhaus <thomas.neuhaus@agilita.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Set Up SAP Data Hub, Developer Edition 2.4 (#3316)


@thomasalexneuhaus<https://github.com/thomasalexneuhaus> What Docker version do you use on your Win10? Is it Docker for Desktop?

Can you try without the IP address in the command?

docker run -ti --publish 50070:50070 --name hdfs --hostname hdfs --net dev-net datahub run-hdfs

**Comment by Sygyzmundovych** [comment]
Unfortunately I do not have Docker Desktop for Windows (only Docker Toolbox), so cannot judge if the port is not allowed, or if already taken. So, to check if there is no other process listening on this port already, can you run
```
netstat -ano | findStr "50070"
```
on your Windows command line?

**Comment by Sygyzmundovych** [comment]
> I just saw the bug page. I will change it soon. Thanks for pointing out.

@fx5151git , If you are talking about Apache Hadoop "bug page" then it is applicable to Hadoop ver. 3.0, while the current Data Hub solution is using 2.9.

**Comment by fx5151git** [comment]
> Unfortunately I do not have Docker Desktop for Windows (only Docker Toolbox), so cannot judge if the port is not allowed, or if already taken. So, to check if there is no other process listening on this port already, can you run
> 
> ```
> netstat -ano | findStr "50070"
> ```
> on your Windows command line?

I am using Docker Desktop for  Windows here. The port is allowed. I think more possible that it has already been taken.

**Comment by fx5151git** [comment]
> > I just saw the bug page. I will change it soon. Thanks for pointing out.
> 
> @fx5151git , If you are talking about Apache Hadoop "bug page" then it is applicable to Hadoop ver. 3.0, while the current Data Hub solution is using 2.9.

Ah, get it. So the container port is changed in hadoop 3.0. Or it is better for me to add a warning before to let users check if their host port 50070 has already been taken.

**Comment by Sygyzmundovych** [comment]
@thomasalexneuhaus Have you fixed your issue?

**Comment by thomasalexneuhaus** [comment]
is it fix

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by goldi28** [comment]
Can you please let me know , how did you fix the issue? I am also facing the same issue
