### ISSUE TITLE
Navigate around SAP Data Hub, developer edition 2.4

### ISSUE THREAD

**Issue by thomasalexneuhaus** [SAPDocuments/Tutorials#3317]
Tutorial URL: https://developers.sap.com/tutorials/datahub-docker-v2-navigation.html

Please specify the step you are referring to
Step 1: Access UIs via a web browser

Same thing take a other port 

https://issues.apache.org/jira/browse/HDFS-9427

**Comment by Sygyzmundovych** [comment]
This port change seems to happen with Hadoop 3.0.0. What version of Hadoop did you get in your `hdfs` container?

On my Data Hub Dev installation it is still 2.9, so using a port as in the tutorial.

```
$ docker exec -it hdfs bash

hdfs:/tmp # hadoop version
Hadoop 2.9.0
Subversion https://git-wip-us.apache.org/repos/asf/hadoop.git -r 756ebc8394e473ac25feac05fa493f6d612e6c50
Compiled by arsuresh on 2017-11-13T23:15Z
Compiled with protoc 2.5.0
From source with checksum 0a76a9a32a5257331741f8d5932f183
This command was run using /opt/hadoop-2.9.0/share/hadoop/common/hadoop-common-2.9.0.jar
```

**Comment by thomasalexneuhaus** [comment]
PS C:\Users\TNEU> docker exec -it hdfs bash
hdfs:/tmp # hadoop version
Hadoop 2.9.0
Subversion https://git-wip-us.apache.org/repos/asf/hadoop.git -r 756ebc8394e473ac25feac05fa493f6d612e6c50
Compiled by arsuresh on 2017-11-13T23:15Z
Compiled with protoc 2.5.0
From source with checksum 0a76a9a32a5257331741f8d5932f183
This command was run using /opt/hadoop-2.9.0/share/hadoop/common/hadoop-common-2.9.0.jar
hdfs:/tmp #

Von: Vitaliy Rudnytskiy <notifications@github.com>
Gesendet: Montag, 8. April 2019 12:25
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Thomas Neuhaus <thomas.neuhaus@agilita.ch>; Author <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Navigate around SAP Data Hub, developer edition 2.4 (#3317)


This port change seems to happen with Hadoop 3.0.0. What version of Hadoop did you get in your hdfs container?

On my Data Hub Dev installation it is still 2.9, so using a port as in the tutorial.

$ docker exec -it hdfs bash



hdfs:/tmp # hadoop version

Hadoop 2.9.0

Subversion https://git-wip-us.apache.org/repos/asf/hadoop.git -r 756ebc8394e473ac25feac05fa493f6d612e6c50

Compiled by arsuresh on 2017-11-13T23:15Z

Compiled with protoc 2.5.0

From source with checksum 0a76a9a32a5257331741f8d5932f183

This command was run using /opt/hadoop-2.9.0/share/hadoop/common/hadoop-common-2.9.0.jar

**Comment by fx5151git** [comment]
this one is related also to the occupied port which can also be closed. @thecodester
