### ISSUE TITLE
Error when issuing the docker run command

### ISSUE THREAD

**Issue by mhuijbregts** [SAPDocuments/Tutorials#3318]
I've been trying to set up the SAP HANA Express container on both CentOS 7.5 & Fedora 28 and in the end constantly keep on bumping into the following docker error:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"write sysctl key kernel.shmmni: write /proc/sys/kernel/shmmni: invalid argument\"": unknown.
ERRO[0011] error waiting for container: context canceled

I have ran it on EC2 instances for both CentOS & Fedora and on the same type of instances on VM on my QNAP NAS. 

Followed the tutorial over here: https://developers.sap.com/tutorials/hxe-ua-install-using-docker-xsa.html

It seems to be a docker related issue but I have no clue on how to get around this. 

Thanks in advance.

**Comment by JCurrie27** [comment]
Hi mhuijbregts: Could you post the above docker error to the developer community Q&A at: [https://answers.sap.com/questions/ask.html ](https://answers.sap.com/questions/ask.html )? The primary tag is "SAP HANA, express edition". The developer community is monitored by HANA express experts and users. Thanks,

**Comment by JCurrie27** [comment]
Closing issue
