### ISSUE TITLE
"MOVIELENS": schema is not owned by _SYS_REPO

### ISSUE THREAD

**Issue by jao6693** [SAPDocuments/Tutorials#3324]
Tutorial URL: https://developers.sap.com/tutorials/cp-hana-aa-movielens-01.html

Step 10: Create the Design-Time Role
I am currently experiencing an issue when activating the user role

The message in the console tells:
```
Error while activating /public/aa/movielens/hdb/user.hdbrole:
```
```
[public.aa.movielens.hdb:user.hdbrole]"MOVIELENS": schema is not owned by _SYS_REPO
```
Not sure where it comes from

**Comment by adadouche** [comment]
Hi, 

Any news on this? 

I'll close this issue for now. Feel free to reopen.

Thanks and hope to hear from you soon.

**Comment by pgupta4sap** [comment]
Hi,

I am also facing the same issue and i have logged in as MOVIELENSE_USER in development workbench editor. While creating package data, hdb, service do i need to enter any value for Responsible ?
Need your urgent help to move forward in the tutorial.
![error](https://user-images.githubusercontent.com/51327339/58806468-db2b1a80-8633-11e9-80f5-cb76ebc8b2e5.PNG)

**Comment by adadouche** [comment]
Hi @pgupta4sap,

Can you please open a new issue? 

Have you check if you are using the MOVIELENS_USER when editing the files? You can check that in the upper right corner of the HANA Workbench.

If you are using SYSTEM as user, this could explain why.

Regards

@bdel

**Comment by pgupta4sap** [comment]
Hi,
As per your request created new issue no #3589.
And yes using the same MOVIELENS_USER. Do i need to enter in package attribute "Responsible".
As in Package Movielens its coming SAP automatically. What about data, hdb, service ?
