### ISSUE TITLE
Build a mobile app from an SAP Web IDE template

### ISSUE THREAD

**Issue by IObert** [SAPDocuments/Tutorials#3325]
Hi @rbrainey,

I just found this old tutorial and noticed it's outdated (screenshots and the mentioned template doesn't exist anymore). It's part of [this group.](https://developers.sap.com/group.mobile-app-1.html)
Do you want me to assign this tutorial to myself and to fix it?

**Comment by rbrainey** [comment]
Yes, please. Consult with Josh as needed if you need any advice on current Mobile roadmap (Kevin is on a break) -- although it sounds like we need to remove this Group.

**Comment by IObert** [comment]
Josh agreed and we'll take this tutorial offline
