### ISSUE TITLE
Prepare an SAP Fiori app for translation

### ISSUE THREAD

**Issue by IObert** [SAPDocuments/Tutorials#3326]
Tutorial URL: https://developers.sap.com/tutorials/sth-prepare-fiori-app-translation.html

Please specify the step you are referring to
The Web IDE service is not available anymore. Therefore this tutorial needs to be adapted to the new Full-stack Web IDE

**Comment by thecodester** [comment]
@beapasch Any updates?

**Comment by beapasch** [comment]
I need some more time to update the tutorial. Any other reference app can be used instead.

**Comment by thecodester** [comment]
@beapasch Are you able to address this issue?

**Comment by beapasch** [comment]
Sorry for my late replay but I was not in the office for some months. The tutorial was updated in the meantime. Hopefully everything is fine now.

**Comment by IObert** [comment]
I'm afraid the UI to access the Web IDE has been changed (again) since the tutorials were updated. Would you mind to update it again?

**Comment by beapasch** [comment]
I will do my best and try to update it next week

**Comment by thecodester** [comment]
@beapasch Has the tutorial been updated?

**Comment by beapasch** [comment]
I'm sorry but we will release in near future some changes for the STH UI and therefor I have to update the tutorial again. I plan to change the tutorial in one step as soon as the new UI is released.

**Comment by MichaelCzcz** [comment]
@beapasch any updates?

**Comment by MichaelCzcz** [comment]
@beapasch Any updates? Can this issue be closed?

**Comment by MichaelCzcz** [comment]
@beapasch Any updates? Can this issue be closed?

**Comment by beapasch** [comment]
we could clarify the issue via email
