### ISSUE TITLE
Create a Simple ABAP CDS View in ADT

### ISSUE THREAD

**Issue by Sdfraga** [SAPDocuments/Tutorials#3329]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-adt-create-cds-view.html

Hi,

Screen Captures are missing.

**Comment by thecodester** [comment]
Are you OK now?

**Comment by Sdfraga** [comment]
Hello,

Screen Captures are now OK thanks. 

Regarding the exercise at the end of the tutorial, I find it difficult to do because it's more a matter of format than the answer itself.

I am quite sure the correct answer should be:
**product.product_name.text**

But I always have the error message:
**Sorry, that’s incorrect. Please try again.**

In other tutorials I had a lot of problems in the exercises, not because I didn't knew the answer bur due to wrong formatting.

Is there any way to see the correct answer?

Thank you
Sérgio

**Comment by thecodester** [comment]
The author changed the test to a question, so you should be able to complete. I can't speak of what the previous answer was supposed to be. I will look into whether after 2-3 unsuccessful tries we can just display the answer.

**Comment by Sdfraga** [comment]
Fantastic Customer Service!!
Everything OK now.
Thank you for the support
