### ISSUE TITLE
Store Sensor Data in HDFS in SAP Data Hub, Developer Edition 2.4

### ISSUE THREAD

**Issue by juderegys** [SAPDocuments/Tutorials#3330]
Tutorial URL: https://developers.sap.com/tutorials/datahub-pipelines-v2-storeinhdfs.html

Hello There,

I followed the steps and configuration for the above tutorial exactly (multiple times). Everytime I execute the pipeline, the process stops. I am getting the error "test.myFirstPipeline 'dead'". Please see my attachment.
![hdfs_error](https://user-images.githubusercontent.com/32884692/55761372-1262be00-5a2d-11e9-9f63-260575106e58.PNG)

Am I missing something? I would appreciate your help.

Thanks,
Jude

**Comment by Sygyzmundovych** [comment]
Hi Jude. What is the message if you click on `test.myFirstPipeline` in the status area?
Like clicking on `HDFS` on this picture:
![image](https://user-images.githubusercontent.com/8822534/55832043-de62c800-5b14-11e9-9814-158dc2fd147c.png)

**Comment by juderegys** [comment]
Thanks you very much. I found the issue in the WriteFile operator connection property. Now, it is working.

Best Regards,
Jude

**Comment by juderegys** [comment]
Thank you. Based on the response I fixed my issue.
