### ISSUE TITLE
Use Mobile Services to Create UI

### ISSUE THREAD

**Issue by karpovas1505** [SAPDocuments/Tutorials#3332]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-create-ui.html

Please specify the step you are referring to

Today in step 4 query parameters in Mobile services defined in other tap(URLs)

![image](https://user-images.githubusercontent.com/26958109/55781891-57dac600-5ad5-11e9-9c7c-df7ddd2939cf.png)

**Comment by shilpavij** [comment]
Tutorial corrected as per new UI and changes are pushed to QA.

**Comment by karpovas1505** [comment]
Thanks, Shilpa.

вт, 16 апр. 2019 г., 19:07 Shilpa Vij <notifications@github.com>:

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
