### ISSUE TITLE
Using Groups in SAP Jam Collaboration Developer Edition

### ISSUE THREAD

**Issue by nbnayak88** [SAPDocuments/Tutorials#3340]
Tutorial URL: https://developers.sap.com/tutorials/jam-cloud-group-users-poll-ideas.html

Please specify the step you are referring to-

There's no progress once you complete each section in terms of percentage completeness

**Comment by thecodester** [comment]
I believe these are older tutorials that have not been updated since we added the progress feature. We are working over the next few months to update the existing tutorials with this feature.

**Comment by thecodester** [comment]
We should be updating these by end of the year -- either discontinuing or fixing. We have an internal issue for this so I am closing this one.
