### ISSUE TITLE
Test SAP HANA, express edition

### ISSUE THREAD

**Issue by buglessdr** [SAPDocuments/Tutorials#3344]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-test-vm-xsa.html

Please specify the step you are referring to

This command is incorrect:
xs apps | grep xsa_cockpit

It should be:
xs apps | grep xsa-cockpit

**Comment by JCurrie27** [comment]
Thanks for this feedback. The command has been corrected and the updated tutorial will be published shortly.
