### ISSUE TITLE
Run example pipelines in SAP Data Hub, developer edition 2.4

### ISSUE THREAD

**Issue by BezalelHank** [SAPDocuments/Tutorials#3345]
Tutorial URL: https://developers.sap.com/tutorials/datahub-docker-v2-examples.html

Please specify the step you are referring to 
Step 2 says that the following is incorrect [2019-04-10 19:12:05.966] 1,4,25.14903419611544,51.84885995129685,567.4806676143861,1.032655150380254,23.381197732579423,58.7325159897191,0,770.5273033411906,416.51969787318416

**Comment by BezalelHank** [comment]
@Sygyzmundovych  Hi. I have tried to upload screen shots of my issue, but I get the error message "Something went really wrong, and we can't process that file. Try again" I have tried JPG and PNG. Do you have any ideas? thanks!

**Comment by fx5151git** [comment]
I think it should work right now.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
