### ISSUE TITLE
Connect to OData service on Neo using SAP S/4HANA Cloud SDK

### ISSUE THREAD

**Issue by girishongit** [SAPDocuments/Tutorials#3346]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-odata-service-neo.html

Please specify the step you are referring to step 11,

for troubleshooting issue with metadata, you have specified an workaround for running locally using CF, but how about running locally using neo?? how do we specify TRUSTALL flag in noe environment?

**Comment by cschubertcs** [comment]
Hi @girishongit,

sorry for coming back with such a delay!
Can you please verify whether you still encounter the same issue? Because right now it seems like there is a workaround mentioned that only works for a local Neo deployment.

Greetings
Chris

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
