### ISSUE TITLE
Onboarding a computer as the IoT thing

### ISSUE THREAD

**Issue by Haruyuki-Kobayashi** [SAPDocuments/Tutorials#3347]
Tutorial URL: https://developers.sap.com/tutorials/iotae-comp-thingmodeler0.html

In the Step 5: Add your computer as a new thing...
According to the tutorial, we are supposed to choose a2667617c for the account.
However when we attempt to specify the account in connectivity section, new pop-up 'Update Account Information' appeared and requires to fill out account, user, password,host..etc.
What the value should we input for that?

----------
Populate the name computer_[userid] and the description [Name]'s computer of the newly created thing.
Choose:
Authorization Group: laptoptutorial
Select Provider: SAP Cloud Platform IoT Service for Neo Environment
**Account: a2667617c**
----------

![image](https://user-images.githubusercontent.com/44152954/55932722-d9615e00-5c65-11e9-97cd-0d890ed6e852.png)

![image](https://user-images.githubusercontent.com/44152954/55932740-e67e4d00-5c65-11e9-90c4-fe7981648f23.png)

**Comment by marcuscbehrens** [comment]
This has been fixed in the interim. This happens, when people try to use their trial acocunts with this which is not possible.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
