### ISSUE TITLE
Create Destination for SAP API Management Service

### ISSUE THREAD

**Issue by amitcruz** [SAPDocuments/Tutorials#3348]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-create-destination.html

@thecodester  : Again the images in all the tutorials are gone . How many times we need to report this .

**Comment by thecodester** [comment]
We are working on this (caching) issue and hope to have a permanent solution soon. In the meantime, I believe the images ar

**Comment by thecodester** [comment]
Do you see the images?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
