### ISSUE TITLE
Explore data in SAP Vora in SAP Data Hub, trial edition 2.4

### ISSUE THREAD

**Issue by monidanai** [SAPDocuments/Tutorials#3349]
Tutorial URL: https://developers.sap.com/tutorials/datahub-trial-v2-discovery-part02.html

Please specify the step you are referring to

Hello anish gupta,

screenshots have been removed. Could you please upload them again?

Thank you in advanced!

**Comment by thecodester** [comment]
Are you seeing them now?

**Comment by monidanai** [comment]
yes, thanks:)
