### ISSUE TITLE
Onboarding a computer as the IoT thing

### ISSUE THREAD

**Issue by fedor-pavlov** [SAPDocuments/Tutorials#3352]
Tutorial URL: https://developers.sap.com/tutorials/iotae-comp-thingmodeler0.html

Hi!
I've tried to follow the instructions and found that there's an issue in "Step 5: Add your computer as a new thing". The instructin says: choose "Account: a2667617c". But when i try to change an account from a default value to a2667617c, the system displays "Update Account Information" dialog and asks me to provide a User, Password and Host. Where should I take this information from?

**Comment by marcuscbehrens** [comment]
This has been fixed in the interim. This happens, when people try to use their trial acocunts with this which is not possible.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
