### ISSUE TITLE
Add an Onboarding Flow | Error: Failed to execute onboard flow

### ISSUE THREAD

**Issue by namclu** [SAPDocuments/Tutorials#3353]
Tutorial URL: https://developers.sap.com/tutorials/cp-sdk-android-flows-onboard.html

Please specify the step you are referring to:

At the end of Step 2: Try it out, when I try to run the app, the app shows the following error.

I've checked the settings on the Wiz App and in the `configurationprovider.json`. It matches w what's in the tutorial.

The only thing I did do differently was to remove the logging stuff as I would get an error when using `sdkVersion=2.0.1`. The latest sdk version I could find was 2.0.0

![Screenshot_1555034224](https://user-images.githubusercontent.com/7246438/56006948-3585ba00-5d1a-11e9-966b-6f3564896de6.png)

**Comment by jarjarbentley** [comment]
another issue I need help with @flyingfish162

**Comment by charleszq** [comment]
The tutorial was updated on May this year, there is code like
```
implementation group: 'com.sap.cloud.android', name: 'onboardingflows-logging', version :sdkVersion // Supported in version 2.1.0 and higher
```
With 2.0.1 SDK, there will be many compilation errors, better to go through the tutorial with higher SDK versions.

**Comment by charleszq** [comment]
Tried with higher SDK version, the code in the tutorial works fine. For the reported 403 error, we need make sure the service url and the application id 'configurationprovider.json' were correctly configured. And also the applicationId in MainActivity should be correct. And check on Admin cockpit to make sure the security settings are good.

**Comment by charleszq** [comment]
2 more things to be noted when trying to follow the tutorial,
1. make sure 'allowBackup' set to 'false' in manifest file;
2, Try with a high 'min android SDK' version than 23 if using newer SAP Cloud Platform SDK for Android
