### ISSUE TITLE
Build an SAPUI5 mobile app based on your data model and run it with mock data

### ISSUE THREAD

**Issue by russellw999** [SAPDocuments/Tutorials#3354]
Tutorial URL: https://developers.sap.com/tutorials/hcp-webide-build-app-mock-data.html

Please specify the step you are referring to

A good tutorial however to avoid confusion it could be updated to point out that the choice of Kapsel templates is Deprecated.  However you can do the tutorial with another template like Master-Detail

Step 2 :  Selection of Kapsel Templates

Include reference to deprecation of Kapsel Templates as it makes thisgs clearer

https://blogs.sap.com/2017/06/20/deprecation-of-dedicated-kapsel-templates-for-sap-web-ide-hybrid-app-toolkit/

https://blogs.sap.com/2018/08/16/announcing-end-of-maintenance-for-hybrid-app-toolkit-local-add-on-local-builds-only/

**Comment by KevinMuessig** [comment]
Hi @russellw999 ,

thank you for raising this issue. I am not the expert on that but I will hand it over to my collegue.

Thanks

**Comment by IObert** [comment]
Thanks for pointing this out. We will remove this tutorial

**Comment by thecodester** [comment]
@IObert Should we remove the entire group https://developers.sap.com/group.webide-odata-modeling.html?

**Comment by IObert** [comment]
Please remove the entire group (as an entity), but please keep the first tutorial of the group as a standalone tutorial
