### ISSUE TITLE
Set Up SAP Mobile Cards

### ISSUE THREAD

**Issue by MarcusBrunneckerSAP** [SAPDocuments/Tutorials#3355]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-setup.html

Please specify the step you are referring to: 

Hi, I have trouble to get through step 4.
When scanning the QR code on my android device I find no way to "send" the url to the  SAP Mobile Cards app. There is no toast message : I can either open the url in my browser or share it via whatsapp etc. But I found no way to open it with SAP Mobile Cards.
Maybe my QR app is not the best and you can suggest a better one?
Thanks,
Marcus

**Comment by jitendrakansal** [comment]
@MarcusBrunneckerSAP For Android device, you can install "Lightning QR" app on your device. 
Now, open this app and scan the QR code (make sure you scan the QR code displaying for Android device), once scan is done, click on "open link" option showing up on the screen, it will launch Mobile Cards app installed on the device.
hope this helps.
PS. Have updated tutorial with this note as well, thanks for reporting it.

**Comment by MarcusBrunneckerSAP** [comment]
Hi,
Unfortunately Lightning QR doesn’t help.
It tries to open the link in the browser and says “web page not reachable. Server’s IP address of mobilecards not found.” (translated from German)
The mobile cards app is installed in WS One. But the QR scanner does not open it as described in your tutorial.

Thanks,
Marcus


Von: Jitendra Kansal <notifications@github.com>
Gesendet: Sonntag, 14. April 2019 19:24
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Brunnecker, Marcus <marcus.brunnecker@sap.com>; Mention <mention@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Set Up SAP Mobile Cards (#3355)


@MarcusBrunneckerSAP<https://github.com/MarcusBrunneckerSAP> For Android device, you can install "Lightning QR" app on your device.
Now, open this app and scan the QR code (make sure you scan the QR code displaying for Android device), once scan is done, click on "open link" option showing up on the screen, it will launch Mobile Cards app installed on the device.
hope this helps.
PS. Have updated tutorial with this note as well, thanks for reporting it.

**Comment by jitendrakansal** [comment]
@MarcusBrunneckerSAP 
i tried on my Android device with Lightning QR code app, it works for me. 
Could you share screenshots of the same?

**Comment by MarcusBrunneckerSAP** [comment]
[Bild]


[Bild]



________________________________

**Comment by jitendrakansal** [comment]
@MarcusBrunneckerSAP i somehow cant see images/attached files in your previous comment.

cc : @thecodester

**Comment by jitendrakansal** [comment]
@thecodester issue has been resolved, i received email from @MarcusBrunneckerSAP saying he had to install and use  the “QR Code Reader” within WS One.
