### ISSUE TITLE
Configure your ABAP System to Activate OData Services of Fiori Reference Apps

### ISSUE THREAD

**Issue by jinigirl** [SAPDocuments/Tutorials#3356]
Tutorial URL: https://developers.sap.com/tutorials/cp-connectivity-configure-fiori-reference-apps.html

Please specify the step you are referring to:

Screenshots are not visible especially for configuration part of the tutorial.
![configuration steps](https://user-images.githubusercontent.com/36019912/56026698-4dbffe00-5d47-11e9-8f47-34a355f99c36.PNG)

**Comment by thecodester** [comment]
We have fixed the images on this tutorial. I see them. Do you?

**Comment by jinigirl** [comment]
Hello *Daniel*,

I can see the images now.
Thanks for the help!


Regards,
Jini
