### ISSUE TITLE
Open SAP Web IDE Full-Stack and make it ready for Cloud Foundry Development

### ISSUE THREAD

**Issue by IObert** [SAPDocuments/Tutorials#3360]
Hi Daniel,

this tutorial is outdated (the builder step doesn't exist anymore) and therefore we can remove it.
I didn't find any dependencies, but maybe you want to double check.

**Comment by thecodester** [comment]
Which tutorial was this? (I searched google for that name but did not find)

**Comment by IObert** [comment]
Sorry for the confusion. Not sure why the title of the issue ended up wrong.
I was talking about [this one](https://developers.sap.com/tutorials/teched-cf-prereq1.html)

**Comment by thecodester** [comment]
Removed
