### ISSUE TITLE
Build a mobile app from an SAP Web IDE template

### ISSUE THREAD

**Issue by togocrates** [SAPDocuments/Tutorials#3362]
Tutorial URL: https://developers.sap.com/tutorials/hcp-template-mobile-web-app.html

Please specify the step you are referring to

On Step 17 after clicking on any product, I get this error:

\{
	"message": "HTTP request failed",
	"headers": \{
		"DataServiceVersion": "1.0;",
		"Content-Type": "application/json"
	},
	"statusCode": "400",
	"statusText": "Bad Request",
	"responseText": "\{\r\n\"error\": \{\r\n\"code\": \"\", \"message\": \{\r\n\"lang\": \"en-US\", \"value\": \"Query options $orderby, $inlinecount, $skip and $top cannot be applied to the requested resource.\"\r\n}\r\n}\r\n}"
}

**Comment by KevinMuessig** [comment]
Hi @togocrates ,

I will assign a colleague who is the expert for WebIDE.

Thanks

**Comment by IObert** [comment]
I'll close this issue as this tutorial already has been removed. Sorry for the inconvenience.
