### ISSUE TITLE
Create an HTTP Service

### ISSUE THREAD

**Issue by schwarzc11** [SAPDocuments/Tutorials#3363]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-create-http-service.html

Please specify the step you are referring to
Step 7: Test yourself
putting in code that returns the user name, like:
`  METHOD if_http_service_extension~handle_request.
     DATA(user_name) = cl_abap_context_info=>get_user_formatted_name( ).
     DATA: text TYPE string.
    text = user_name.
    response->set_text( text ).
  ENDMETHOD.`
which works correctly, shows the expected result when testing from Eclipse using URL,
results in 
"Sorry, that’s incorrect. Please try again."
No difference when complete file including declaration is entered.

Step 8: Copy code (optional)
code shows expected result of previous steps before step 7 "test yourself", with system date, and not the expected result when answering the test question.
Not sure if this was intended

**Comment by julieplummer20** [comment]
Hi, Yes, the validation engine is extremely strict, re whitespace, case-sensitivity etc (obviously ABAP isn't case-sensitive, but others are.)
The correct answer is:

DATA(user_name) = CL_ABAP_CONTEXT_INFO=>get_user_formatted_name( ).
DATA: text type string.
text = user_name.
response->set_text( text ).

ie what you put but without the actual METHOD... ENDMETHOD statement.
I apologize; I find it hard to describe what to put in, without actually spelling it out.
So from now on, I will probably just do multiple choice. We will also look at revealing the answer after, eg, 3 wrong attempts.
Best wishes,
Julie.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by schwarzc11** [comment]
Hi Julie, 
thanks for your feedback reassuring me that I was not on teh wrong track here.
Semantic code check is beyond reach of course. I think the idea to challenge with little code snippets is actually a good one.
But that kind of validation engine, if it compares character by character, isn't worth a lot, indeed and sabotages that approach.
Actually, I copy-pasted your solution above into the question field, and even then it said the answer is wrong.
Thanks and best regards,
Christian

**Comment by julieplummer20** [comment]
Hi Christian,
"I copy-pasted your solution above into the question field, and even then it said the answer is wrong."
I'm sorry to hear that. That must be very frustrating (for you and me!)
I'm on vacation next week, but I'll change it to multiple choice pronto when I get back.
Thanks, in turn, for your feedback.
Julie.

**Comment by julieplummer20** [comment]
Hi Christian,
I've changed the test question to "single-choice" in QA and pushed to Prod.
It should be available in the next 24 hours latest.
Best wishes,
Julie.
