### ISSUE TITLE
Explore and Customize Your SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by topherhoffman** [SAPDocuments/Tutorials#3364]
Tutorial URL: https://developers.sap.com/tutorials/webide-customize.html

Please specify the step you are referring to  

**STEP 4: Learn about SAP WEB IDE** - _ Learning Button Missing_
-  There is no longer a button for the learning portal, you have to navigate to the home page then go to the youtube page.

**Step 7: Enable a Cloud Foundry workspace** - _No Builder Installation_
- There is no longer a button to install builder on the Workspace Preference>Cloud Foundry - Cloud Foundry Space Configuration

**Comment by thecodester** [comment]
@jhornik You may also want to put your name on this with author metadata

**Comment by jhornik** [comment]
@topherhoffman 
Thanks for the feedback. I've updated the tutorial accordingly.
