### ISSUE TITLE
Add API Business Hub API to a UI5 Application

### ISSUE THREAD

**Issue by laksyelugoti** [SAPDocuments/Tutorials#3367]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-api-ui5-app.html

Please specify the step you are referring to Step 8.

Issue1:
I have output, but there is record found with Name: Lorelie Lawrie

**Comment by mhassett92** [comment]
It appears as the data has been updated from the SFSF API and therefore Lorelie Lawrie has fallen further down in the list. I will update the tutorial with more recent data from SFSF when the APIs are online.  Currently, there is an authentication issue with Successfactor's API Sandbox. In the meantime, you can use "Scheduler" to complete this tutorial.

Thank you!
Meredith

**Comment by mhassett92** [comment]
This issue has been resolved and the validation question has been updated. Thank you!
