### ISSUE TITLE
Create a Simple IoT Device Model

### ISSUE THREAD

**Issue by alexeysizov** [SAPDocuments/Tutorials#3369]
Tutorial URL: https://developers.sap.com/tutorials/iot-express-2-create-device-model.html

Please specify the step you are referring to

Step 1: Log into your IoT service instance
->Login with your user name and password (in the cloud cockpit you can find the root user credentials in the cloud foundry space in the service key area of the service instance)

This is not correct. In order to proceed, one should log in with the user credentials, which was created in Internet of Things Service Cockpit and assigned under Tentant. When using the root (as the guide suggests) Device Management is not available.

**Comment by marcuscbehrens** [comment]
Yes, this is correct - this has changed in the product. I will update the tutorial accordingly.

**Comment by thecodester** [comment]
@marcuscbehrens Has the tutorial been updated?

**Comment by MichaelCzcz** [comment]
@marcuscbehrens any updates?

**Comment by MichaelCzcz** [comment]
@marcuscbehrens any updates?

**Comment by MichaelCzcz** [comment]
@marcuscbehrens any updates?

**Comment by marcuscbehrens** [comment]
Have changed it and will put in a pull request for the change as soon as my toolchain is up and running (again).

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
