### ISSUE TITLE
Onboarding a computer as the IoT thing

### ISSUE THREAD

**Issue by pahlkelerch** [SAPDocuments/Tutorials#3370]
Tutorial URL: https://developers.sap.com/tutorials/iotae-comp-thingmodeler0.html

Step1: Logon with the provided credentials does not work. user P002627 and password Laptop01 for https://sap-iotaehandson2.iot-sap.cfapps.eu10.hana.ondemand.com/launchpage/

**Comment by marcuscbehrens** [comment]
You had changed the initial password first time going in (I assume). If not let me know and I can reset it.

---
Marcus Behrens, Product Management, SAP Leonardo IoT
+49 160 8896 474, expect SMS and IM response in 1 hour, email in 1 day or never

**Comment by pahlkelerch** [comment]
Hallo Marcus,
zwei Fragen habe ich noch:

  *   Kannst Du meinen User P002627 auf der Demoinstallation  https://sap-iotaehandson2.iot-sap.cfapps.eu10.hana.ondemand.com/launchpage/ mit einem neuen Passwort versehen? Das angegebene Passwort ‚Laptop01‘ funktioniert nicht, ich kann mich aber auch nicht daran erinnern, eine neues vergeben zu haben. Wenn ich das IoT Tutorial von Beginn an starte, laufe ich bei der Registirierung auf einen technischen Fehler.
  *   Die IoT Services finde ich auf dem Marktplatz meiner Neo Trial Instanz, aber nicht auf meiner Cloud Foundry Trial Instanz. Allerdings steht in der Beschreibung für die IoT Services auf Neo ‚The SAP Cloud Platform Internet of Things service for the Cloud Foundry environment’ Das macht mich etwas konfus. Gibt es dafür eine Erklärung?

Danke und Gruß, Christoph

**Comment by thecodester** [comment]
@marcuscbehrens @pahlkelerch Is this issue resolved?

**Comment by marcuscbehrens** [comment]
resolved by reseting the password

**Comment by marcuscbehrens** [comment]
Yes, I talked to Christoph directly. I now updated the ticket.

---
Marcus Behrens, Product Management, SAP Leonardo IoT
+49 160 8896 474, expect SMS and IM response in 1 hour, email in 1 day or never
