### ISSUE TITLE
Build a Simple SAP Screen Personas Dashboard

### ISSUE THREAD

**Issue by SteffenGa** [SAPDocuments/Tutorials#3372]
Tutorial URL: https://developers.sap.com/tutorials/personas-mobile-workbook-create.html

Please specify the step you are referring to

All the images in the tutorial aren't loading for me / tested with several browsers / getting a 404 in the debugger for all image requests.

**Comment by thecodester** [comment]
I see the images now. Do you?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
