### ISSUE TITLE
Assemble and Configure Device Hardware

### ISSUE THREAD

**Issue by alexeysizov** [SAPDocuments/Tutorials#3373]
Tutorial URL: https://developers.sap.com/tutorials/iot-express-3-configure-device.html

Please specify the step you are referring to

Assemble and Configure Device Hardware
Step 4: Run the firmware
It is not clear at this stage, should the device data be displayable in IoT Service Cockpit/Data Visualization section, or not. As the node.js code is slightly different from one, used in previous section, it is difficult to understand, whether it is not displayed due to error or as it is intended. Also, the manual says 'The data is not beeing picked up by anyone.', which is also confusing. This should be somehow addressed in the manual.

**Comment by marcuscbehrens** [comment]
Hi, yes, the data should show up in the device model under visualisation. If it does not then please carefully check your payload. A little error will basically result in the data not beeing processes at all. Regards, MArcus

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
