### ISSUE TITLE
Create a Thing Model and Bind to Device

### ISSUE THREAD

**Issue by alexeysizov** [SAPDocuments/Tutorials#3376]
Tutorial URL: https://developers.sap.com/tutorials/iot-express-4-create-thing-model.html

Create a Thing Model and Bind to Device
Step 1: Access Fiori Launchpad with IoT Application Enablement apps

I don't have a SAP IoT Application Enablement in a SAP Cloud Platform cockpit, but I have SAP Leonardo IoT (also has Packages sections). Will it also work?

**Comment by marcuscbehrens** [comment]
please refer to https://blogs.sap.com/2019/04/12/upgrading-all-iot-application-enablement-subscriptions-to-leonardo-iot-this-week-get-ready-for-major-improvements/ to understand the name change

we will update the tutorials accordingly this week
