### ISSUE TITLE
Generate sensor data in SAP Data Hub, developer edition 2.4

### ISSUE THREAD

**Issue by BezalelHank** [SAPDocuments/Tutorials#3379]
Tutorial URL: https://developers.sap.com/tutorials/datahub-pipelines-v2-sensordata.html

Please specify the step you are referring to 
Step 4 Validate does not work

**Comment by thecodester** [comment]
@fx5151git Also, pictures missing. Please republish.

**Comment by thecodester** [comment]
I see images now.

**Comment by fx5151git** [comment]
I think this should work right now

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
