### ISSUE TITLE
Create a Database Table (ABAP Development)

### ISSUE THREAD

**Issue by CESolomon** [SAPDocuments/Tutorials#3380]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-create-table.html

Step 13 (Test Yourself) will not validate. I have tried everything. I know many(MOST!) of these sorts of checks are VERY buggy and not well done (even a space can throw them at times). Here is the request that is being sent to validate and is failing...

++@AbapCatalog.foreignKey.keyType+:+#KEY++@AbapCatalog.foreignKey.screenCheck+:+true ++city++++++:+s_city+not+null++++++with+foreign+key+[0..*,1]+sgeocity++++++++where+city+=+zxx_account.city;

....which in the textarea is actually....
  @AbapCatalog.foreignKey.keyType : #KEY
  @AbapCatalog.foreignKey.screenCheck : true    
  city      : s_city not null
        with foreign key [0..*,1] sgeocity
        where city = zxx_account.city;

I have tried it with/without "not null". This should work but isn't. It is the only thing stopping me from completing this one.

**Comment by julieplummer20** [comment]
Hi CE, I am officially on vacation but will look into this as soon as I get back. 
Best wishes 
Julie.

**Comment by julieplummer20** [comment]
Hi,
The original text omitted the cardinality for the foreign key. Your version is better, but the validation engine is too strict.
I will convert this (and other code questions) to multiple choice asap.
Best wishes,
Julie.

**Comment by julieplummer20** [comment]
Done - pushed to Prod.

**Comment by thecodester** [comment]
https://github.com/SAPDocuments/Tutorials/pull/3431

**Comment by CESolomon** [comment]
But there is no question shown now....just 3 choices. haha

**Comment by thecodester** [comment]
Fixed @julieplummer20 See the format for adding the question to the rules
