### ISSUE TITLE
Set up your local infrastructure to develop with SAP S/4HANA Cloud SDK

### ISSUE THREAD

**Issue by lnryan** [SAPDocuments/Tutorials#3381]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-setup.html

Please specify the step you are referring to

In the first step, set up your infrastructure, linux is missing as on operrating system choice.

**Comment by sacnl** [comment]
Thank you for the feedback.
* For Java, please refer to https://adoptopenjdk.net/installation.html#x64_linux-jdk
* For Maven, please refer to https://maven.apache.org/install.html

We will check if we add this to the tutorial.

**Comment by thecodester** [comment]
@lnryan Is there something else you need here?

**Comment by lnryan** [comment]
@thecodester - need? no. but it's disappointing that SAP technical documentation doesn't even consider or mention linux users, considering how popular it is among professional developers.

**Comment by thecodester** [comment]
@sacnl @karstenmelato Any additional thoughts on this?

**Comment by sacnl** [comment]
We will adapt the tutorial with a reference to the instructions for Linux.
