### ISSUE TITLE
Explore the ABAP Repository

### ISSUE THREAD

**Issue by CESolomon** [SAPDocuments/Tutorials#3382]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-learn-repo.html

Step 9: Test the function module

Enter the code mentioned exactly as shown and it will not validate. I have tried adding spaces in it, line break, etc. and nothing works. Also, just being picky but the instructions say "enter the following text exactly, then click Validate:"....there is no "Validate" to click....just "Submit Answer" (which does the validation).

**Comment by CESolomon** [comment]
UPDATE:
Very strange....I just got it to validate but not sure how/why.

1. I entered the text.... <code>START-OF-SELECTION.demo=>main( ).</code>   
    ....and it would not validate correctly.

2. I placed cursor at start of the line and hit enter (ie putting a new line/blank space above it) so it was then....
<code>

START-OF-SELECTION.demo=>main( ).   
</code>

3. I then tried to validate again and it failed. So I placed cursor before "demo" and pressed enter/newline. It appeared as....
<code>

START-OF-SELECTION.
demo=>main( ).   
</code>

4. Attempted validate and again it failed. I then removed the first "blank" line so it was....
<code>
START-OF-SELECTION.
demo=>main( ).   
</code>

5. Clicked "Submit Answer" again and it passed. 

No idea why or how! haha

**Comment by julieplummer20** [comment]
Hi CE, That’s embarrassing (for us).
The Validation Engine is very strict. 
We are working to change that but in the meantime I’ll change my questions to multiple choice. 
Thanks for letting me know. 
Julie.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
