### ISSUE TITLE
Use a message broker in SAP Data Hub, developer edition 2.4

### ISSUE THREAD

**Issue by BezalelHank** [SAPDocuments/Tutorials#3386]
Tutorial URL: https://developers.sap.com/tutorials/datahub-pipelines-v2-broker.html

Please specify the step you are referring to:
On Step 1 when I try: docker run --name kafka --hostname kafka --network dev-net spotify/kafka
I get: docker: Error response from daemon: Conflict. The container name "/kafka" is already in use by container "5061c0986abd1ca086f37ddb356aafac59102451c632878230eeacbcfbefe3b8". You have to remove (or rename) that container to be able to reuse that name.

Sorry I don't know what I am doing, but I am trying to learn.

**Comment by Sygyzmundovych** [comment]
Hi there. The message indicates you have created one container with the name `kafka` already.
To check the list of created containers run
```
docker container list -a
```
and you should see something like
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                        PORTS                                                                      NAMES
...
d8b2b3de789a        spotify/kafka       "supervisord -n"         5 minutes ago       Up 5 minutes                  2181/tcp, 9092/tcp                                                         kafka
...
```
Obviously, in your case kafka's container id would display `5061c0986abd`.
If you want to remove it, just run
```
docker rm -f 5061c0986abd
```
and then try to rerun the command, which was failing previously for you.

I would really recommend to look at parts 1 and 2 of https://docs.docker.com/get-started/

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
