### ISSUE TITLE
Create a Thing Model and Bind to Device

### ISSUE THREAD

**Issue by alexeysizov** [SAPDocuments/Tutorials#3387]
Tutorial URL: https://developers.sap.com/tutorials/iot-express-4-create-thing-model.html

Step 6: Map thing type to sensor type
->'First choose the sensor type from the list in the upper right and then choose the device properties that match the thing properties. In this example the names are the same but they do not have to be the same'

Unfortunately, in my case, previously created in IoT Service sensor type is NOT available (see screenshots). The attention has been payed to OData migration as well as appropriate Thing Modeler Apps (OData version) configuration. Any suggestions?

![Capture1](https://user-images.githubusercontent.com/49637543/56208180-c75e3180-6050-11e9-8e0e-8fe2a192ac8b.PNG)
![Capture2](https://user-images.githubusercontent.com/49637543/56208181-c75e3180-6050-11e9-90f2-ca8c8ee87f70.PNG)

**Comment by marcuscbehrens** [comment]
has iot service been hooked to leonardo iot via a ticket to sap or have you used the new apis that allow you to set up the link yourself? in the later case this link is now (iot service) tenant specific and does not work anymore for sensor types created in the root tenant - so you have to create a tenant in iot service.

**Comment by alexeysizov** [comment]
Thank you for the useful note. After appropriate IoT service configuration via API and recreation of all entities it worked out.
