### ISSUE TITLE
Run example pipelines in SAP Data Hub, developer edition 2.4

### ISSUE THREAD

**Issue by thomasalexneuhaus** [SAPDocuments/Tutorials#3390]
Tutorial URL: https://developers.sap.com/tutorials/datahub-docker-v2-examples.html

Please specify the step you are referring to
Copy any row of the terminal output and paste it in the frame below and click on Validate.

[2019-04-16 20:22:47.813] 0,4,25.555219261860465,47.41223556836962,532.4126972690706,1.017645583549283,23.99690674702611,59.746879572444016,0,719.2882102905135,409.22321564322885
Sorry, that’s incorrect. Please try again.
Why is this wrong?

**Comment by BezalelHank** [comment]
I'm having the same issue. That checker does not seem to work until you get to Store Sensor Data in HDFS in SAP Data Hub.

**Comment by fx5151git** [comment]
This should work for now.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by thomasalexneuhaus** [comment]
Thanks ist it works
