### ISSUE TITLE
Use a message broker in SAP Data Hub, developer edition 2.4

### ISSUE THREAD

**Issue by thomasalexneuhaus** [SAPDocuments/Tutorials#3392]
Tutorial URL: https://developers.sap.com/tutorials/datahub-pipelines-v2-broker.html

Please specify the step you are referring to Step 4: Execute the data pipeline

[2019-04-17 19:34:13.402] 508,4,25.441059169277086,50.06729270800206,576.3136582678364,0.9829288585720629,24.446170268142556,57.18224493344707,0,622.1122482714203,471.244684423664
Submit Answer
×
Sorry, that’s incorrect. Please try again.

Why whats wrong?

**Comment by fx5151git** [comment]
This should work now. Could you please have a check?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by thomasalexneuhaus** [comment]
Thanks ist it works
