### ISSUE TITLE
Bundle data (via JavaScript) SAP Data Hub, developer edition 2.4

### ISSUE THREAD

**Issue by thomasalexneuhaus** [SAPDocuments/Tutorials#3393]
Tutorial URL: https://developers.sap.com/tutorials/datahub-pipelines-v2-bundledata.html

Please specify the step you are referring to Step 4: Check the created files in HDFS

0,6,25.090658362700825,44.303874076186695,543.691403199344,0.9743208887546716,23.726837765793906,54.12766534458229,1,721.8617675213762,461.46364374663995
Sorry, that’s incorrect. Please try again.

Why ist this wrong?

**Comment by fx5151git** [comment]
This should work for now. Could you please have a check?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by thomasalexneuhaus** [comment]
Thanks ist is works
