### ISSUE TITLE
Get Started with SAP S/4HANA Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by austinkloske22** [SAPDocuments/Tutorials#3394]
Tutorial URL: https://developers.sap.com/tutorials/s4sdkjs-getting-started.html

Step 4: Use the SDK in existing project (optional)

`austinkloske@penguin:~/git/cloud-s4-sdk-examples$ npm run start:local

> cloud-sdk-starter-app@1.0.0 start:local /home/austinkloske/git/cloud-s4-sdk-examples
> npx ts-node src/

Express server listening on port 8080
^C
austinkloske@penguin:~/git/cloud-s4-sdk-examples$ sudo npm install @sap/s4sdk-core
npm ERR! code E404
npm ERR! 404 Not Found: @sap/s4sdk-core@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-17T22_13_47_721Z-debug.log`

**Comment by sacnl** [comment]
Thanks for reporting this issue. Unfortunately, the tutorial references an obsolete name, this should be `@sap/cloud-sdk-core`. We will adapt the tutorial.

Please try with `sudo npm install @sap/cloud-sdk-core`.

**Comment by sacnl** [comment]
This has been fixed in the tutorial and can be closed.
