### ISSUE TITLE
Send the CPU usage data to SAP IoT Application Enablement

### ISSUE THREAD

**Issue by cfvaz1973** [SAPDocuments/Tutorials#3396]
Tutorial URL: https://developers.sap.com/tutorials/iotae-comp-sendpy0.html

Hello sygyzmundovych
 I can't get it to work.
I keep getting 500 error
500 {"msg":"Processing 1 message(s) received from device [F669B73E594941EAAD1324C47E54E807] failed"}

Is it because i am running Python 3.7.1 ?

Thanks in advance.
Carlos Vaz

**Comment by marcuscbehrens** [comment]
Can you try again? there might have been a temporary issue.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
