### ISSUE TITLE
Create a Destination within the Cloud Foundry Environment

### ISSUE THREAD

**Issue by jaehoon92** [SAPDocuments/Tutorials#3398]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-create-destination.html

Please specify the step you are referring to
In step 7, I am not able to see the Cloud Foundry Northwind destination on Service URL of the Web IDE wizard. Do I need further steps, such as creating a destination instance in CF space, to see the destination coming up on Web IDE?

**Comment by IObert** [comment]
Thanks @jaehoon92!

You're right, the additional properties aren't required for the destination in the Cloud Foundry environment (as the Web IDE only checks the Neo destinations atm).

You should be able to see the destination in the Web IDE once you created the [Neo destination](https://developers.sap.com/tutorials/hcp-create-destination.html)
