### ISSUE TITLE
Edit Web Content in your Portal Freestyle Site - From the web content editor tools, web content editors can?

### ISSUE THREAD

**Issue by TuncayKaraca** [SAPDocuments/Tutorials#3400]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-freestyle-site-edit-content.html

Please specify the step you are referring to _Step - 3: Publish the changes to your web content_

I couldn't pass Step 3: Publish the changes to your web content question: From the web content editor tools, web content editors can:?

To me answer should be "Edit text, images, videos and other web content" or "Edit text, images, videos and other web content." and "Re-order the web content of a page."

But it didn't accept any combinations of the answer. Is there something wrong here, bug? or am I a missing something?

Thanks in advance.

![2019-04-19 11_57_58-Window](https://user-images.githubusercontent.com/17751887/56440147-2e2c5680-62ae-11e9-852c-d36f3e953da8.png)

**Comment by thecodester** [comment]
Neither of the answers you cited are correct. There are 15 possible combinations -- did you try all of them?

**Comment by TuncayKaraca** [comment]
Thanks Daniel. I've got 1010 👍
