### ISSUE TITLE
Create Your Own SAP Fiori Launchpad

### ISSUE THREAD

**Issue by carlospinto1** [SAPDocuments/Tutorials#3401]
Tutorial URL: https://developers.sap.com/tutorials/cp-fiori-create.html

In the step 6: "In your Fiori Launchpad Cockpit dashboard, copy the URL up to the ? and paste it in the below box."

Could you please clarify what URL we need to paste in the box?

I have tried with the URL attached but it does not work.

Many thanks in advance.

Carlos

![Fiori cockpit URL](https://user-images.githubusercontent.com/41262823/56474858-ccb7e380-6477-11e9-8594-3f0db0d4a47b.gif)

**Comment by IObert** [comment]
Hi @carlospinto1,

thanks for mentioning this. Our intention was to ask you for 
`https://flpportal-p1940516058trial.dispatcher.hanatrial.ondemand.com/sites`. Maybe we need to overthink if the should simplify this validation.

Please let me know if this solution worked for you.

**Comment by carlospinto1** [comment]
It worked @IObert , thanks a lot.
