### ISSUE TITLE
Configuring Eclipse with SAPUI5.

### ISSUE THREAD

**Issue by nilpeksen** [SAPDocuments/Tutorials#3402]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-install-eclipse.html

https://tools.hana.ondemand.com/luna link is not working.
Please update tutorial with https://tools.hana.ondemand.com/2018-12 for Eclipse 2018-12,
https://tools.hana.ondemand.com/2018-09 for Eclipse 2018-09 or 
https://tools.hana.ondemand.com/photon for Eclipse Photon links.

**Comment by thecodester** [comment]
@IObert Is this something you can help with?

**Comment by IObert** [comment]
Thanks @nilpeksen!
I updated the screenshots and replaced the link to the specific version with a link to the tools page
