### ISSUE TITLE
Use the Similarity Scoring with the Text Feature Extraction API from a REST Client

### ISSUE THREAD

**Issue by oisee** [SAPDocuments/Tutorials#3409]
Tutorial URL: https://developers.sap.com/tutorials/cp-mlf-rest-similarity-text.html

Hi Abdel,

Thanks for the guide.

Is it possible to re-upload the screenshots? 
![screenshot_report](https://user-images.githubusercontent.com/53392/56570007-04c34180-65b2-11e9-9eb9-fbe99a571fe5.png)

It seems like all screenshots are gone.

Best regards, Ilia.

**Comment by thecodester** [comment]
@oisee I see the images now ... can you? Can we close the issue?

**Comment by oisee** [comment]
@thecodester Yes, indeed, thank you =)
