### ISSUE TITLE
Deploy Application to Cloud Foundry with SAP S/4HANA Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by qmacro** [SAPDocuments/Tutorials#3415]
Tutorial URL: https://developers.sap.com/tutorials/s4sdkjs-deploy-application-cloud-foundry.html

Please specify the step you are referring to: Step 1: Deploy application to Cloud Foundry

When deploying with `cf push`, an error occurs as follows:

```
Staging app and tracing logs...
   Downloading nodejs_buildpack...
   Downloaded nodejs_buildpack
   Cell 35f8dc07-edbb-496b-8286-58d05d7d2e2e creating container for instance 73b0c62a-8a11-4c40-a240-6d313ef91b3b
   Cell 35f8dc07-edbb-496b-8286-58d05d7d2e2e successfully created container for instance 73b0c62a-8a11-4c40-a240-6d313ef91b3b
   Downloading app package...
   Downloading build artifacts cache...
   Downloaded app package (2.4M)
   Downloaded build artifacts cache (20.8M)
   -----> Nodejs Buildpack version 1.6.43
   -----> Installing binaries
          engines.node (package.json): ^11.10.0
          engines.npm (package.json): unspecified (use default)
          **ERROR** Unable to install node: no match found for ^11.10.0 in [6.15.1 6.16.0 8.14.1 8.15.0 9.11.2 10.15.0 10.15.1 11.8.0 11.9.0]
   Failed to compile droplet: Failed to run all supply scripts: exit status 14
   Exit status 223
   Cell 35f8dc07-edbb-496b-8286-58d05d7d2e2e stopping instance 73b0c62a-8a11-4c40-a240-6d313ef91b3b
   Cell 35f8dc07-edbb-496b-8286-58d05d7d2e2e destroying container for instance 73b0c62a-8a11-4c40-a240-6d313ef91b3b
   Cell 35f8dc07-edbb-496b-8286-58d05d7d2e2e successfully destroyed container for instance 73b0c62a-8a11-4c40-a240-6d313ef91b3b
Error staging application: App staging failed in the buildpack compile phase
FAILED
```

The Node.js version `^11.10.0` is specified in `package.json` and it appears that this was from [PR #66](https://github.com/SAP/cloud-s4-sdk-examples/pull/66/files) earlier this month.

Regressing the required Node.js version to what it was previously i.e. `11.9.0` causes the deployment to be successful.

**Comment by mr-flannery** [comment]
Thanks for pointing that out!
@rkamath3 I think we can revert the PR as a quickfix.
Apparently, the Cloud Foundry node.js buildpack is regularly changing which node versions are supported in a breaking manner.
So we should probably do something like this:

```json
"engines": {
  "node": ">=11.0.0"
}
```

**Comment by fgeckeler** [comment]
@mr-flannery I will do that and add you as a reviewer.

I observed the same behaviour with changing the supported node versions, that's why we changed it in the referenced PR.

**Comment by fgeckeler** [comment]
We changed the version as proposed by @mr-flannery 
Thank you for raising this issue @qmacro !

**Comment by thecodester** [comment]
@qmacro Can we close the issue now?

**Comment by qmacro** [comment]
This is for the team to fix, and I have just checked - it has been: https://github.com/SAP/cloud-s4-sdk-examples/commit/fd2fd45fa95e1bfdb41e13882c248bf7c78593c1
