### ISSUE TITLE
Import your TechEd BUILD project into SAP Web IDE

### ISSUE THREAD

**Issue by russellw999** [SAPDocuments/Tutorials#3420]
Tutorial URL: https://developers.sap.com/tutorials/teched-2017-build-import.html

Please specify the step you are referring to

Step 1 : Validation of Build Service URL fails every time

**Comment by thecodester** [comment]
@russellw999 What value are you providing?

**Comment by russellw999** [comment]
Hi,

IT works if i enter the following URL which is the service in Web IDE
https://account.hanatrial.ondemand.com/cockpit/#/acc/pxxxxxxxxxxtrial/service/build/overview

It was a question of semantics.
I understood the  URL of the BUILD service in SAP Cloud Platform to be the actual URL after one clicks on < open Build > in Web IDE Fullstack

which would be 

https://www.build.me/

or after login into Build with the < pUser>

https://standard.build.me/

**Comment by thecodester** [comment]
I have updated the question to refer to the service page within SAP Cloud Platform.
