### ISSUE TITLE
Deploy UI to cloud foundry using HTML5 Repository plan app-host

### ISSUE THREAD

**Issue by MANUGUPTASAP** [SAPDocuments/Tutorials#3421]
Hi Team ,

I am facing issue while deploying mta.yaml to CF using HTML5 repository app-host plan. The error is -

Error creating services: Error creating service "JVSolution_html5_repo_host" from offering "html5-apps-repo" and plan "app-host": Service broker operation failed: 502 Bad Gateway: Service broker error: Store quota lower then 0 or bigger then already assigned quota.Unexpected error:

Similar issue is being raised couple of months back but the solution link given doesn't work now -  https://github.com/SAPDocuments/Tutorials/issues/3082

Please help.
Thanks,
Manu

**Comment by thecodester** [comment]
@mervey45 There is a link to the Help Portal in the other issue but it no longer works. Can you address?

**Comment by thecodester** [comment]
@MANUGUPTASAP Are you doing the tutorial https://developers.sap.com/tutorials/abap-environment-cf-deploy.html?

**Comment by MANUGUPTASAP** [comment]
@thecodester : No , I am simply trying to deploy my custom app to HTML5 repository and consume it on FLP. My main concern is how to check quota for specific service in SAP Cloud foundry and change quota for specific service like HTML5 repo(I know issue is with HTML5 repo service with plan app-host quota). As per document HTML5 repo service quota is being derived on the basis of Application runtime service. -
https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/b8343d9d8b984d73adbae5fe657f13db.html

Thanks,
Manu

**Comment by thecodester** [comment]
I'll let @mervey45 see if she can find a working link. Generally, such general questions (not directly linked to the specific tutorial) should be addressed in the SAP Community / SAP Questions & Answers (https://www.sap.com/community.html / https://answers.sap.com/index.html). 

help.sap.com has their own support pages, and you can provide feedback or report an issue (e.g., missing documentation) @ https://help.sap.com/viewer/get-support.

**Comment by mervey45** [comment]
@MANUGUPTASAP I think you can change the quota, but I don't know, if you can change the quota for HTML5 services. Maybe you have to try it. But I'm not the right person to ask for. I hope I could help you with your issue.

**Comment by thecodester** [comment]
This is a more general question and not about the tutorial itself. Feel free to continue the discussion in the SAP Community or in the SAP Questions & Answers.

https://www.sap.com/community.html
https://answers.sap.com/index.html
