### ISSUE TITLE
Create a Business Service Using CDS

### ISSUE THREAD

**Issue by I850604** [SAPDocuments/Tutorials#3422]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-01-create-business-service.html

Please specify the step you are referring to

I am creating an odata service that supports PUT and Delete operations. Is there any annotation that we can use as well?

**Comment by thecodester** [comment]
@I850604 Are you Jonas? Best to show your real name in your account, and using I number is frowned upon?

@I850604 We'll see if Andre has an answer, but general questions of this type are best opened in the SAP Community or in the SAP Questions & Answers.

https://www.sap.com/community.html
https://answers.sap.com/index.html

**Comment by renejeglinsky** [comment]
I'll have a look at this and will come back to you.

@thecodester You can set me as an assignee here and remove André. Thanks :)

**Comment by renejeglinsky** [comment]
I think your question goes beyond the scope of the tutorial. Do you know the CAP documentation [1]? You find all external information there.

[1] https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/00823f91779d4d42aa29a498e0535cdf.html

**Comment by I850604** [comment]
@renejeglinsky thank for your help. I am able to do PUT and DELET without any annotations.
