### ISSUE TITLE
Getting started with the SAP API Business Hub

### ISSUE THREAD

**Issue by jameskauczka** [SAPDocuments/Tutorials#3423]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-getting-started.html

Please specify the step you are referring to
Step 1. OK except the new account does not have all the items in menu at left.

What to select??? Cloud Foundry Trial or Neo Trial???
Ultimately trying to use GCP, can't figure out how to send a code to my phone..

**Comment by thecodester** [comment]
@rbrainey Do these tutorials need refreshing/deletion? In TDash, this tutorial is shown as Adrian being the first author, but GitHub shows Meredith as first author, and Adrian not having to do anything with it.

**Comment by jameskauczka** [comment]
I expect they need a refresh as the UI has changed.

**Comment by rbrainey** [comment]
Meredith, would you take a look at this and revise it as needed?  Thanks,

**Comment by mhassett92** [comment]
Hello all,
Apologies for the very long delay.
I have refreshed this tutorial to reflect the new location and styling of the API Business Hub.
Thank you,
Meredith
