### ISSUE TITLE
Create a Workflow Project from a Template

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3424]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-create-project.html

Please specify the step you are referring to

Hello,

i can´t create a new Project, because the Point "3.Set the Environment to Neo, ABAP." is not Possible. By the way, the changed the Version.

Regards

Marco

**Comment by AstridHerbst** [comment]
Hi Marco,

Thanks for pointing this out. I have updated the step text and version number.

Regards, Astrid
