### ISSUE TITLE
Set Up SAP Data Hub, Developer Edition 2.4

### ISSUE THREAD

**Issue by amitavamitra** [SAPDocuments/Tutorials#3426]
Tutorial URL: https://developers.sap.com/tutorials/datahub-docker-v2-setup.html

Please specify the step you are referring to

 Step 2: Download SAP Data Hub, developer edition

On trying the link as specified I get the following error

Unfortunately, a technical error occurred when processing your request. Please try again.

@anishgupta85

**Comment by fx5151git** [comment]
Could you try it again, it works fine right now @amitavamitra

**Comment by amitavamitra** [comment]
Thanks @fx5151git it works and I managed to install SAP Datahub.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
