### ISSUE TITLE
Create a Node.js module to expose OData services

### ISSUE THREAD

**Issue by jinigirl** [SAPDocuments/Tutorials#3435]
Tutorial URL: https://developers.sap.com/tutorials/xsa-ml-e2e-create-node-module.html

Please specify the step you are referring to:

Hello, I wanted to try creating my own Node.js app in the SCP, but I don't know how to start.
Is this the web IDE? I can't seem to find the option to create new Node.js module.

Thanks.

**Comment by Lsubatin** [comment]
Hi, 
That tutorial is based on Web IDE for HANA, but the steps are the same as in Web IDE Full stack (which is the version in SCP). You need to start from the first tutorial in the prerequisites (https://developers.sap.com/tutorials/xsa-ml-e2e-github-mta.html). However, I would recommend this group instead: https://developers.sap.com/group.hana-xsa-get-started.html 

Here is another example using the Cloud Application Programming model on SCP: https://developers.sap.com/tutorials/xsa-e2e-capm-fullstack.html  

Closing this as it's not an issue with the tutorial.

Best, 
Lucia.
