### ISSUE TITLE
Create a Hyperledger Fabric Development Node

### ISSUE THREAD

**Issue by equilibrium999** [SAPDocuments/Tutorials#3438]
Tutorial URL: https://developers.sap.com/tutorials/blockchain-create-hlf-node.html

Please specify the step you are referring to
Step 5
When I select dev plan, it said that this is a paid service plan.
Of course I'm using trial account and just want to do tutorials.

**Comment by heytombeck** [comment]
Thanks for raising this. I've just tried the same tutorial on my trial account and you're right, this does say that a dev plan is a paid service plan. That's a bug / an error on our part, but if you select 'Dev' and then click 'Next', the process still works and allows you to create the service instance. If you select 'backbone', for example, you'll notice that you're blocked from creating the service instance and can't continue.

I'll ask for this to be changed. Thanks again.

**Comment by thecodester** [comment]
@heytombeck Can this be closed? Has the tutorial/system been updated?

**Comment by heytombeck** [comment]
@thecodester Sorry for the delay, I was out of the office. This can be closed, thanks.
