### ISSUE TITLE
Explore the Generated App and OData Service

### ISSUE THREAD

**Issue by TThorsager** [SAPDocuments/Tutorials#3441]
In step 2 of this tutorial "Examine the generated application", I get this error message on the simulated device when I tap on either of the collections:

loading data failed!
dataserviceerror error 500 (internal server error) 
{"code":"",message":"service excetion: [414] user is forced to change password"}

![image](https://user-images.githubusercontent.com/33313082/57074111-41461a00-6ce3-11e9-86ad-962883c66246.png)

Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-scpms-teched18-03.html

**Comment by TThorsager** [comment]
By getting this tutorial to work (https://developers.sap.com/tutorials/fiori-ios-scpms-create-sample-app.html) I think that the misstake is happening in the Destination setup.

**Comment by KevinMuessig** [comment]
Hi @TThorsager ,

I am sorry you experienced issues with the tutorial. Could you please off board the app and try on boarding again. Also you can delete the app and re-install. If that doesn't help could you please provide me some logs? While doing that I will verify the tutorial.

Thanks

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
