### ISSUE TITLE
Create a Workflow Project from a Template

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3442]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-create-project.html

Please specify the step you are referring to

Sorry Astrid,

I can´t find the point 4. "Workflow Project"  in my list to set up a Workflow Project.

**Comment by marcobuescher** [comment]
Sorry, I see the plugin was not started.

**Comment by thecodester** [comment]
So you are OK?

**Comment by marcobuescher** [comment]
Yes thank you... 

Regards
