### ISSUE TITLE
Enable Services for Sales Tracker App

### ISSUE THREAD

**Issue by RubenRollano** [SAPDocuments/Tutorials#3447]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-services-enable.html

Please specify the step you are referring to

Hello, it seems imposible to complete the Step 5: Enable Mobile Services. Perhaps is a bug in the answer to the question

**Comment by shilpavij** [comment]
Yes, got your point. I will correct it.

Regards
Shilpa

**Comment by RubenRollano** [comment]
Perfect. Please notify me when it be ready.

Thanks and best regards.

**Comment by thecodester** [comment]
@shilpavij Have you corrected?

**Comment by shilpavij** [comment]
Yes, it is corrected and pushed too
