### ISSUE TITLE
Create a Destination for the Northwind OData Services in the Neo Environment

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3448]
Tutorial URL: https://developers.sap.com/tutorials/hcp-create-destination.html

Please specify the step you are referring to Step 5.

There is no "Done" Button. :)

Regards

**Comment by thecodester** [comment]
Added DONE button. Let me know if you have any more issues.

**Comment by marcobuescher** [comment]
Need it some Time to take effekt? I can`t see the Button.

By the way, good job!

**Comment by thecodester** [comment]
oops ... yes it will take a little more :-)

**Comment by marcobuescher** [comment]
Sorry to be impatient, bit there is no button... :)

**Comment by Waltersen1971** [comment]
Had the same,
checked it out now:

![image](https://user-images.githubusercontent.com/50441418/57524075-0b2e1900-7327-11e9-99ac-df2e299f2853.png)
 It is fixed.

**Comment by marcobuescher** [comment]
Worked!
