### ISSUE TITLE
hcp-template-mobile-web-app, step 2+3

### ISSUE THREAD

**Issue by larshp** [SAPDocuments/Tutorials#345]
http://go.sap.com/developer/tutorials/hcp-template-mobile-web-app.html

in step 2+3, copy pasted from account.hanatrial.ondemand.com:
"SAP WEB IDE is available in the Services panel and therefore will soon be removed from the list of HTML5 subscriptions. We encourage you to already access SAP Web IDE from the Services panel."

![image](https://cloud.githubusercontent.com/assets/5888506/15395711/2f3b5796-1dd9-11e6-842e-9977bb141e65.png)

so I guess the tutorial should be updated to reflect this, and point the users to services instead of subscriptions?

**Comment by akula86** [comment]
Thanks. I had it on my punch list - will change it today. Thanks for the nudge.

**Comment by akula86** [comment]
Tutorial updated:  https://github.com/SAPDocuments/Tutorials/commit/37c910aeef95bb97edc162cf0610e593055d0ac5
