### ISSUE TITLE
Set Up SAP Cloud Appliance Library Account and Install Preconfigured SAP Solution in Cloud

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3455]
Tutorial URL: https://developers.sap.com/tutorials/hcp-prepare-cal-account.html

Please specify the step you are referring to 1-3 also no "done" button

**Comment by thecodester** [comment]
@JensHaley The mission you created, https://developers.sap.com/mission.cp-connectivity-abap.html, cannot be completed since there are no validations in the second group. Can you add?

**Comment by JensHaley** [comment]
@marcobuescher 
We decided to remove tutorial group [Use JCo through the Cloud Connector](https://developers.sap.com/group.cp-connectivity-2.html) instead. 

You will not have to complete the corresponding tutorials to complete the mission.

I would not recommend to do these tutorials -  they are quite old and may no longer work - we're looking into this.

Sorry for any inconvenience caused. Could you close this issue?

**Comment by marcobuescher** [comment]
Hello,

that are no good news, because I liked the Badge so mutch. :)

They are old, I think so too and I think they are form other older Tutorials because I saw I made the User and User Groups in AWS long Time ago.

Regards

Marco
