### ISSUE TITLE
Mission Overview Links not work

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3456]
Hello,

from the Mission Overview (http://tiny.cc/i8l75y) the Links from:
Get   Started with SAP Data Hub, developer edition
Get Started with SAP Data   Hub, trial edition

will targeting to a 404 Page.

and the Mission "Build a Mobile App with SAP API Management" is not listet in Overview.

Regards

**Comment by thecodester** [comment]
Thanks for pointing out. I am checking ...

**Comment by thecodester** [comment]
I have requested an update. Will let you know when it is complete.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
