### ISSUE TITLE
Use JPA in Custom Logic

### ISSUE THREAD

**Issue by balajii7** [SAPDocuments/Tutorials#3457]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html

**From Step 4: Change the runtime from Tomcat to TomEE**: As I understand, from **Step 4**, we are delegating the management of the resources to the container by changing the default container from Tomcat to the TomEE. But the application starts giving the error right after these changes. So, _I had to revert to the version where the run-time container is still the Tomcat_. Please access the project here: https://github.com/balajii7/bookshop.git

However, I moved on to the **Step 5** to push the data using **CURL** and it fails with the below error. What is the _<Java-Backend-URL>_ that we are supposed to use? I presumed it's the application url deployed to the SCP, please correct me if I'm wrong.
![image](https://user-images.githubusercontent.com/7418651/57193338-30dbac80-6f3a-11e9-9608-c19dbf883a6d.png)

Please let me know if I am doing anything wrong. Thank you.

Regards,
Sai

**Comment by JijoRoyJacob** [comment]
Hi Sai,
I dont see the `srv/src/gen/resources/META-INF/persistence.xml` file in the project you shared. This is generated along with the JPA classes. You need to enable JTA support in this file. This is described in Step 3.

Best regards,
Jijo

**Comment by JijoRoyJacob** [comment]
Also try changing the curl command to the following Windows format: `curl -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d "{ \"buyer\" : \"JPA Buyer 1\", \"book_ID\" : 310 }" https://<Java-Backend-URL>/odata/v2/CatalogService/Orders`

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
