### ISSUE TITLE
Configure the Development Environment

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3459]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-configure-dev-env.html

Please specify the step you are referring to Step 4
Sorry, I can´t find the Extension "SAP EIM Smart Data Integration Editors "

Regards

Marco

**Comment by Lsubatin** [comment]
Hi Marco, I see it in my Full stack Web IDE.  I suggest you enter a support ticket as the plug-in should be available. 

Closing this as this is not the channel for support.
