### ISSUE TITLE
titles seem broken

### ISSUE THREAD

**Issue by larshp** [SAPDocuments/Tutorials#346]
Hi,
When accessing eg. http://go.sap.com/developer/tutorials/hcp-template-mobile-web-app.html

the title of the html page is showed as the url, since the html contains `<title></title>`

![image](https://cloud.githubusercontent.com/assets/5888506/15395926/0f999a64-1dda-11e6-98a1-dd43a1763731.png)

I guess the title should somehow be take from the markdown page? 
`title: Build an app from an SAP Web IDE template`

It seems that the final generation of the html page is handled outside of the logic contained in the github repository.

**Comment by akula86** [comment]
Yes - the HTML pages are generated outside of Github, and the HTML title field will be populated with the tutorial title soon (that enhancement is ready for UAT).

**Comment by akula86** [comment]
HTML titles and description fields are now populated automatically when HTML files are generated.
