### ISSUE TITLE
IOT Tutorial: Send Data with MQTT

### ISSUE THREAD

**Issue by kubratkc** [SAPDocuments/Tutorials#3461]
Hello @iwonahahn,

I started your Tutorial group for getting started with SAP IOT Services. 

First problems appeared when i tried to install the **paho client** (MAC) for MQTT messaging. I tried to launch the app via package content as suggested in the tutorial. The app opens, but i can't click anywhere in the app. Everything is disabled. 

**STEP 6:**
https://developers.sap.com/tutorials/iot-cf-send-data-mqtt.html

So I tried to build the MQTT Connection via **MQTT.fx**. I still can't get a connection.
The interface for the connection settings must be different to the paho client. 

**1) Enable SSL: I have several options for the keystore settings. We tried each option with different settings but nothin really worked. I'd like to know which option is the one i need and what i have to fill in the fields.**

1.1) CA Certificate Keystore

![Bildschirmfoto 2019-05-06 um 14 33 54](https://user-images.githubusercontent.com/48827166/57225255-24278900-700c-11e9-97ad-465092271b36.png)

1.2) Self signed certificates in keystores
![Bildschirmfoto 2019-05-06 um 14 40 13](https://user-images.githubusercontent.com/48827166/57225507-e0814f00-700c-11e9-8913-0ec15196761b.png)

Do i have to fill in the changeit password in the trusted keystore field?

1.3) Self signed certificates

![Bildschirmfoto 2019-05-06 um 14 33 54](https://user-images.githubusercontent.com/48827166/57225375-7cf72180-700c-11e9-8fff-3b91d31372c7.png)

**2) What Broker Adress do I have to choose when not using PAHO ? The format ssl://<HOST_NAME>:8883 → ssl://demo.eu10.cp.iot.sap:8883 ist not accepted.** 

![Bildschirmfoto 2019-05-06 um 14 43 53](https://user-images.githubusercontent.com/48827166/57225690-6604ff00-700d-11e9-996a-dea1598f260e.png)

**3) What about the user credentials? I tried solving the problem with entering my credentials for my root user.** 

![Bildschirmfoto 2019-05-06 um 14 45 12](https://user-images.githubusercontent.com/48827166/57225791-a8c6d700-700d-11e9-9aea-7ce187cd8e87.png)

4) I'd be really grateful if you could help me with either solving the PAHO problem or customizing the requirements for my MQTT.fx client. 

Thank you very much.

**Comment by iwonahahn** [comment]
Hi,
1. You need the certificate from 1.2.
2. The tutorial is working as it is published now, we test it for each bi-weekly release.
3. You do not need to add the User Name and Password.

Best regards,
Iwona

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
