### ISSUE TITLE
Create an API Provider System

### ISSUE THREAD

**Issue by amitavamitra** [SAPDocuments/Tutorials#3463]
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-create-provider.html

Please specify the step you are referring to

Step 5.

the tutorial says to provide 

Host | sapes5.sapdevcenter.com

where as my  API Portal comes up as 
Host Alias:
i304524trial-trial.apim1.hanatrial.ondemand.com.

this causes the entires path to be quite different and hence the overall setup could not be completed.

Kind Regards

Amitava

@mhassett92

**Comment by rbrainey** [comment]
Hi, that particular system is a pre-configured API endpoint. It is separate from your normal Trial environment.  It should be accessible to you despite that -- could you be more specific about the issue you were running into?

**Comment by MichaelCzcz** [comment]
@amitavamitra Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
