### ISSUE TITLE
Add a Database to Your Business Application

### ISSUE THREAD

**Issue by vuffiraa72** [SAPDocuments/Tutorials#3467]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-03-add-database.html

When you do the first step, it's not possible to build the db.
I got an error:
`13:01:54 (Executor) Build command failed : Build failed: Failed at pre build operation: Failed to validate service availability: Failed to execute install command: Failed to execute install command: failed to set delete service : Row not found`
`13:01:54 (Executor) The "task for hdb build" process finished with code 1`
`13:01:54 (Executor) Build of /BookShop/db failed.`

**Comment by renejeglinsky** [comment]
Hi @vuffiraa72 ,
are you using a trial account? If yes, in which region?
Please check if the SAP HANA service is available in your Cloud Foundry space.
Thanks,
René

**Comment by vuffiraa72** [comment]
While checking the configuration in the WebIDE, I had to re-enter my credentials for the Cloud Foundary space. Afterwards it worked as expected.
Thanks,
Ulf
