### ISSUE TITLE
Explore data in Cloud Storage in SAP Data Hub, trial edition 2.4

### ISSUE THREAD

**Issue by Rob3487** [SAPDocuments/Tutorials#3469]
Tutorial URL: https://developers.sap.com/tutorials/datahub-trial-v2-discovery-part01.html

Please specify the step you are referring to: **Step 3**

I cannot provide the answer to step 3 as my instance of DataHub Fails to Profile any of the .csv files with the following error:

"Could not start the graph (Code: 70201 Module: dh-app-metadata)"

Error Detail:
"Code
70201
Message
Profiling failed for Devices.csv
Detail
Could not start the graph
Module
dh-app-metadata
GUID
1cae88eb-0e05-410d-aa11-215ac7d42abe
Hostname
metadata-explorer-llftj-57c697986d-qgn5n
Causes
Code
99999
Message
error building docker image. Docker daemon error: The command '/bin/sh -c mkdir -p /project/sbin && mkdir /spark && mkdir /opt/spark && mkdir /opt/hadoop && mkdir -p $HADOOP_CONF_DIR && apt-get update && apt-get -yq --no-install-recommends install wget=1.18-5+deb9u2 unzip=6.0-21 curl && apt-get clean && rm -fR /var/lib/apt/lists/*' returned a non-zero code: 100
Module
vflow"
 
![sap-exercise-issue-with-starting-graph-01](https://user-images.githubusercontent.com/19631990/57325350-2e9d6c00-714d-11e9-8541-19df73a7615b.png)

**Comment by Rob3487** [comment]
Hi,

I'm using Google Cloud.

Rob

**Comment by Rob3487** [comment]
Yes trial version 2.4

**Comment by Rob3487** [comment]
FYI.  When attempting to Profile Vora tables I receve the following error:

Code
70201
Message
Profiling failed for CUSTOMERS
Detail
Could not start the graph
Module
dh-app-metadata
GUID
9c5527fd-2c52-4e20-918e-4aecc7a6bfa0
Hostname
metadata-explorer-llftj-57c697986d-wn47s
Causes
Code
99999
Message
error building docker image. Docker daemon error: The command '/bin/sh -c mkdir -p /project/sbin && mkdir /spark && mkdir /opt/spark && mkdir /opt/hadoop && mkdir -p $HADOOP_CONF_DIR && apt-get update && apt-get -yq --no-install-recommends install wget=1.18-5+deb9u2 unzip=6.0-21 curl && apt-get clean && rm -fR /var/lib/apt/lists/*' returned a non-zero code: 100
Module
vflow

**Comment by schneidertho** [comment]
Hi @Rob3487,

@fx5151git is out till Monday. So I answer. 
As a "quick fix" can you make the edits as shown in the screenshot, please? 
i.E. comment the line "apt-get -yq --no-install-recommends install wget=1.18-5+deb9u2 unzip=6.0-21 curl && \" with a "#"
and add a new line "apt-get -yq --no-install-recommends install wget unzip curl && \"
![image](https://user-images.githubusercontent.com/20142835/57522272-86d99700-7322-11e9-9e2a-75a53696f365.png)

I tested it and it worked. We will check how we can bring the change into all new instances for the trial solution.

Cheers
Thorsten

**Comment by schneidertho** [comment]
Hi @Rob3487, 

seems Github does not display the screenshot. So you need to 
- Open Modeler
- Click on Repository on the left
- Dockerfiles => com => sap => 
- spark_on_k8s

There you make the change I mentioned before. Then press the Build button on the top right

Cheers
Thorsten

**Comment by Rob3487** [comment]
You're suggestion as an immediate fix has been successful!

Thank you for your assistance.

Rob

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by Rob3487** [comment]
Hi, 
have there been any other changes or updates to the system since 3 days ago when I tested your suggestion, that may have affected logging into the Launch Pad?  
Prior to reporting this issue have been successfully logging in to Launch Pad using the RDP (directly using a browser never worked, appared to be a credential or network restriction issue), I did successfully login to test your suggestion using the RDP, however now, when I have time to continue the tutorial, when I try to login using the RDP, using the same credentials for Tenant: default UN: datahub that I previously used, there appears to be an authentication issue - I can no longer login. Any thoughts on this?

Thanks in advance for your assistance.

Rob

**Comment by schneidertho** [comment]
Hi Rob,

no (from our side we would not even have the possibility to make any change to a running instance).

There are three possibilities only, I believe:
a) wrong user / pw => let's assume that this is not the case
b) license expired => I assume you use the normal trial license and your cluster is not older than 30 days.  Then the license "should not" be expired. We install a license for that timeframe.
c) something else in the cluster "is wrong", e.g. not all services are running

Most likely it is c). Few things you can do
d) suspend and activate the instance (once more) via CAL UI
e) check in CAL that all services are up and running (there is a small "tree view" which shows you the services and their status for your instance)
f) get the logs for uaa and vsystem pods (by SSHing into the jump box)

Can you give d-f) a try, please? To advise further I would need a screenshot for e) and if everything is ok according to CAL, the log files 

Cheers
Thorsten

**Comment by Rob3487** [comment]
Thank you for the suggestions;
I started/Activated the Trial 2.4 instance.

Within the CAL console, I bellieve the following image depicts the "tree view" you mention. Was showing no errors, then in a flash showed Vora errors, then flash again no errors;
![CAL-no-aparent-errors](https://user-images.githubusercontent.com/19631990/57741440-2cfd1680-7700-11e9-9238-ea1fe32021ef.jpg)

Now Errors;
![CAL-now--errors](https://user-images.githubusercontent.com/19631990/57741447-371f1500-7700-11e9-858f-d6dd8e67a238.jpg)

I'm now certain it is NOT an incorrect credentials issue because a red message is shown on the Launch Pad login screen when I DO knowninly enter incorrect credentials - see image below;
![Launch-pad-invalid-user-credential-example](https://user-images.githubusercontent.com/19631990/57741508-79e0ed00-7700-11e9-9483-13cf71aeb664.jpg)

Instead when I enter the correct credentials as demonstrated in the below animated .gif, upon submitting the credentials, the screen flashes, then the login screen is re-presented without a credentials fail message;
![SAPDataHub-correct-credentials](https://user-images.githubusercontent.com/19631990/57741552-aac12200-7700-11e9-9413-270d2749f531.gif)

At this immediate moment I don't have time resources available to further track this issue via reviewing logs etc. on the jump box,   ...perhaps I'll first try deleting this instance of SAP Datahub Trial 2.4, and re-initialte a new instance. 

I do also remain open to your suggestions - thanks!

Rob :)

**Comment by Rob3487** [comment]
1)  I spun up a new instance of SAP Data Hub Trial 2.4.
2) During the setup I set a different/new <Master Password>
3) Once the new instance was successfully Active, connected using RDP;

2 important points;

Point A) 
If trying to connect using https://sapdatahubtrial (as per the documentation) I was confronted with the dreded "NET:ERR_CERT_AUTHORITY_INVALID" page (failed ssl certs). There was no mention of this or the need to continue/press forward in spite of this error in the documents (that I have found).

If you instead connect using http:// instead of https:// (to avoid crashing through the 'Your connection is not private" warnings) you will experience as I did previously (read above), where one enters the correct credentials, however cannot log in.

It was necessary to 'Advance' forward disregarding the "Your connnection is not private" warnings using the https://sapdatahubtrial ssl url.

Upon arriving at the Launch Pad using ssl my credentials DID work (however with one caveat - pls keep reading Point B below).
![Launch-pad-no-https](https://user-images.githubusercontent.com/19631990/57748562-d69ed080-771d-11e9-9c34-b551706e768c.jpg)


Point B)
This new instance of SAP Data Hub Trial 2.4 that I set up with  a different/new <Master Password> rejected that different/new <Master Password> and instead accepted the old <Master Password> that I had configured for the previous and already terminated instance of SAP Data Hub Trial 2.4 (Go figure??).

I am now successully logged in to Launch Pad again.

This was my experience - and thank you again schneidertho for your most helpful and timely support  :)

**Comment by schneidertho** [comment]
Hi Rob,
thanks. So I take that you are good for now and can continue testing. 
For A) we will see how we can better describe that when we update the documentation for 2.5
For B) I currently have no idea how this could happen, since the two instances are completely disconnected. 

Have fun with the trial.

Cheers
Thorsten

**Comment by Rob3487** [comment]
SAP Data Hub appears to be an outstanding product; largely it is very nice to use, functionality is intuitive, the problems it solves and the results it delivers I can see to be relevant, and the process/s involved in achieving the results are logical and manageable.

BIG Kudos to you and your team for delivering a learning experience that is largely excellent, and particularly given the complex nature of the product and the sophistication of the overall SAP learning environment!

Well Done!
