### ISSUE TITLE
hcpms-create-hybrid-app - "Mobile Services" renamed?

### ISSUE THREAD

**Issue by larshp** [SAPDocuments/Tutorials#347]
hi, in
http://go.sap.com/developer/tutorials/hcp-template-mobile-web-app.html step 2

I cannot find a "Mobile Services" service, however there is a "Development & Operations" service with the same icon and content, so it looks like the "Mobile Services" service has been renamed?

![image](https://cloud.githubusercontent.com/assets/5888506/15396065/b8de06c8-1dda-11e6-9b84-069601f1115e.png)

**Comment by akula86** [comment]
SAP HANA Cloud Platform mobile services was renamed to SAP HANA Cloud Platform mobile services for development and operations. Other services are being added under the "mobile services" group. Tutorial updated with new screenshots/instructions. See commit: https://github.com/SAPDocuments/Tutorials/commit/2f4cab4c7318ac521dde890b1db7ff415d27601c
