### ISSUE TITLE
Add a Model and Test the SAPUI5 App

### ISSUE THREAD

**Issue by RubenRollano** [SAPDocuments/Tutorials#3470]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-webide-setup-datasource.html

Please specify the step you are referring to

Add a Model and Test the SAPUI5 App
Step 5: Inspect the application network trace

It seems imposible to answer correctly the question.

**Comment by IObert** [comment]
Hi @RubenRollano,

I'm sorry you had problems answering this question. Can you please explain why it's impossible to answer it? Did you see different or confusing data in the request?

**Comment by IObert** [comment]
I'll close this one due to inactivity. Please reopen it if necessary.
