### ISSUE TITLE
Use JPA in Custom Logic

### ISSUE THREAD

**Issue by DanielRentschler** [SAPDocuments/Tutorials#3474]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html

Please specify the step you are referring to: Step 5

We have completed all steps in the tutorial including the conversion to jta and tomee. Initially the service starts and responds to our get/post requests but after exactly 100 requests the app stops responding to requests involving database access. 

For example: https://07yqgrpayeanrzu4-jtabookstore-srv.cfapps.sap.hana.ondemand.com/odata/v2/CatalogService/Books works exactly 100 times after starting the app.
The metadata-request still works. The only way to make the books-request work again is to restart the app in cloud foundry. 

[Link to our sap-github repository](https://github.wdf.sap.corp/ccdm/jtaBookstore)

**Comment by JijoRoyJacob** [comment]
Hi Daniel. Sorry for the late response. I'd forwarded the issue to the dev team to look into but they haven't been able to replicate it so far. Are you still facing this issue?

**Comment by DanielRentschler** [comment]
Hi Jijo, sorry I forgot to update this issue. I was contacted by colleagues who work on the JPA/JTA library. It seems like a bug in a library that they use and they are working on a fix.
