### ISSUE TITLE
Prepare your environment for the SAP Leonardo Machine Learning foundation Image Classification Retraining scenario

### ISSUE THREAD

**Issue by joao1100** [SAPDocuments/Tutorials#3477]
Tutorial URL: https://developers.sap.com/tutorials/cp-mlf-retrain-image-classification-01.html

Please specify the step you are referring to:
STEP 3:
I can't initialize the service. It stays like this forever. Any solution?
![imagem](https://user-images.githubusercontent.com/38331502/57384776-0f342c80-71a9-11e9-8733-775b73d331ce.png)

**Comment by adadouche** [comment]
Hi @joao1100 ,

Really sorry for the lag, but I was away on holiday for the last 2 weeks. I was told that you send this question to answers.sap.com as well which was a really good idea.

But I see that it's not answered yet (https://answers.sap.com/questions/12682616/cant-initialize-cloud-foundry-service.html).

There are 2 options to try solving this.

option 1: **clear the sapml local folder**

To do so, open your windows explorer, and navigate to your user folder (in your case ***c:\users\jjoa***).
Then delete the .cf/sapml folder.
Open a new command prompt (really important)
Then run 
```shell
cf login
```
Then run 
```shell
cf sapml fs init
```

option 2: **recreate a dev space**

In this option, you will need to drop any service instance for MLF, then remove the entitlement on your current space (and optionally drop the space if you don't need it for something else).
Then, create a new space (if you dropped the existing one, you can reuse the same name).
Add the entitlement for MLF and try again.

Hope this will help.

**Comment by joao1100** [comment]
Hi, thank you for the answers. Seems like the developer team changed something and it's now working perfectly. Is there any tutorial I can follow to consume this API in the SAPUI5?
Thank you!

**Comment by VkDinesh** [comment]
hi @adadouche,
Regarding your article about, Discover how to implement SAP Leonardo Machine Learning Foundation service in a SAPUI5 application [https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/ml-fs-sapui5-img-classification/ml-fs-sapui5-img-classification.md] 
I am facing an issue in the final step, as I run the code it runs perfectly but after when I upload the picture it keeps on loading and loading.
URL for image source.{
https://ibb.co/QrJPNsh
}
thanks.

**Comment by adadouche** [comment]
Hi @VkDinesh 

Can you open a new issue? Additionally, you should open the browser "Developer tools" (press F12) and inspect the Console tab which should give us some directions.

Regards

@bdel
