### ISSUE TITLE
Image Classification with SAPUI5

### ISSUE THREAD

**Issue by joao1100** [SAPDocuments/Tutorials#3478]
Tutorial URL: https://developers.sap.com/tutorials/ml-fs-sapui5-img-classification.html

Please specify the step you are referring to: STEP 4
I get the following message when I test the connection : Connection to "sapui5ml-api" established. Response returned: "401: Unauthorized".
I'm using the trial version of SAP Cloud Platform.

**Comment by adadouche** [comment]
Hi @joao1100 

Thanks for catching that. Apparently the message has changed since I last updated the tutorial.

I have updated the relevant tutorials accordingly. The update should appear shortly.

Thanks again for you feedback.
