### ISSUE TITLE
View the SAP Cloud Platform from 10,000 Meters

### ISSUE THREAD

**Issue by gsnel** [SAPDocuments/Tutorials#3482]
Tutorial URL: https://developers.sap.com/tutorials/cp-explore-cloud-platform.html

When I click on Done in step 1 or 3,  I return to the beginning of step 1.
And I cannot submit answers.
It does nog show my progress.

**Comment by thecodester** [comment]
This happens to me but only when I am not logged in -- do you see your avatar at the top right of the tutorial page?

**Comment by gsnel** [comment]
Yes, i'm logged in. My avatar is in the upper right corner.

**Comment by thecodester** [comment]
Have you been able to answer Step 2?

**Comment by gsnel** [comment]
No, I am not able to answer step 2. 
No mather what answer (or combination) I give, nothing happend when I click on Submit Answer.

**Comment by thecodester** [comment]
There are 15 combinations -- you have tried them all? If there were 3 correct answers, there would only be 4 possible combinations. Can you post a screenshot of the tutorial as you see it (full screen)?

**Comment by gsnel** [comment]
I found the solutions. I tried the tutorial on my tablet and was able to fill in the answers. After thinking about the differences, I turned of the uBlockOrigin extension (for blocking adds) in my browser for the tutorial webpage. And now it is working.
Thank you for your help.
