### ISSUE TITLE
Debug Your SAPUI5 App with SAP Web IDE

### ISSUE THREAD

**Issue by raz-korn** [SAPDocuments/Tutorials#3486]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-webide-debug.html

Please specify the step you are referring to

Step 5:
I'm not a SAPUI5 expert...
Adding "debugger" in the code is not best practice. I'd recommend providing this through a best practice.
The build operation removed the "debugger". 
You can workaround using CTRL + ALT + SHIFT + P and check the debug mode.

**Comment by IObert** [comment]
Hi @raz-korn,

thanks for your feedback. You are right, production applications should neither contain the `debugger` statement nor throwing errors without a reason. The purpose of this tutorial is to teach developers how to use debugging tools. 
In general, you should use the `run` feature for debugging. I'll change the tutorial content accordingly.

PS: The build step only seems to remove the debugger when you used the alternative wizard and the html5 app repo service.

**Comment by IObert** [comment]
This should be fixed with the latest PR.
