### ISSUE TITLE
Tour the SAP Community

### ISSUE THREAD

**Issue by RubenRollano** [SAPDocuments/Tutorials#3487]
Tutorial URL: https://developers.sap.com/tutorials/community-start.html

Please specify the step you are referring to

it seems not possible to answer correctly the question 10.

**Comment by thecodester** [comment]
1) There are multiple answers. Did you select more than one?
2) There are 63 possible answers (I think). Did you actually try all of them?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
