### ISSUE TITLE
Create an SAPUI5 App from the Command Line step5

### ISSUE THREAD

**Issue by zysiek77** [SAPDocuments/Tutorials#3488]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-sapui5-local.html
Step 5: Deploy the MTA archive

Bash command specified here is:
cf mta_archives/myUI5App_0.0.1.mtar

but it should be:
cf deploy mta_archives/myUI5App_0.0.1.mtar

**Comment by IObert** [comment]
Good catch, thanks!
