### ISSUE TITLE
Import Tables and Large Datasets (XS Advanced)

### ISSUE THREAD

**Issue by henrystuifzand** [SAPDocuments/Tutorials#3493]
Tutorial URL: https://developers.sap.com/tutorials/xsa-import-shine-data.html

Please specify the step you are referring to
Import Tables and Large Datasets (XS Advanced)

There is not to mark the 4 steps as completed, so the mission can't be completed.

**Comment by Lsubatin** [comment]
Hi Henry, thanks for bringing this up. You should the validations now. 
Best, 
Lucia.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
