### ISSUE TITLE
Get Started with SAP Web IDE for Full-Stack Development (Production)

### ISSUE THREAD

**Issue by entmike** [SAPDocuments/Tutorials#3494]
Tutorial URL: https://developers.sap.com/tutorials/webide-onboarding-mc.html

Please specify the step you are referring to

Prerequisites Documentation link is broken (https://help.sap.com/viewer/page-not-found?url=https:%2F%2Fhelp.sap.com%2Fviewer%2F65de2977205c403bbc107264b8eccf4b%2FCloud%2Fen-US%2Fdba4ae7ef36c4a93a6615c5f24ae9903.html)

**Comment by thecodester** [comment]
@jhornik Please also handle links in step 6

**Comment by ShiraManas** [comment]
Hi,
The links have been updated and are now working properly. Thanks for letting us know.
