### ISSUE TITLE
Create an SAPUI5 Purchase Order App

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3495]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-ms-graph-create-app.html

Please specify the step you are referring to Step 3.

Hello Codetester, Hello Marius, :)
I had the problem that there is no traffic, after I start the Index.html and check it with F12.
I get error messages. The Steps before where fine. (OData Destination).
Can you help me? Is the error at my side?

Regards

Marco

2019-05-14 19:21:38 Device API logging initialized - DEVICE
Log-dbg.js:411 2019-05-14 19:21:38.086840 URL prefixes set to: -  sap.ui.ModuleSystem
Log-dbg.js:411 2019-05-14 19:21:38.087125   (default) : ../../resources/ -  sap.ui.ModuleSystem
Log-dbg.js:411 2019-05-14 19:21:38.087239   'com/sap/teched18/msgraph/PurchaseOrderApp' : ./ -  sap.ui.ModuleSystem
ui5loader-dbg.js:1171 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
loadSyncXHR @ ui5loader-dbg.js:1171
/resources/sap/ui/core/messagebundle_de_DE.properties:1 Failed to load resource: the server responded with a status of 404 ()
index.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
/webapp/i18n/i18n_de_DE.properties:1 Failed to load resource: the server responded with a status of 404 ()
/webapp/i18n/i18n_de.properties:1 Failed to load resource: the server responded with a status of 404 ()
/webapp/i18n/i18n_en.properties:1 Failed to load resource: the server responded with a status of 404 ()
/webapp/i18n/i18n_de_DE.properties:1 Failed to load resource: the server responded with a status of 404 ()
/webapp/i18n/i18n_de.properties:1 Failed to load resource: the server responded with a status of 404 ()
/webapp/i18n/i18n_en.properties:1 Failed to load resource: the server responded with a status of 404 ()
/resources/sap/ui/layout/messagebundle_de_DE.properties:1 Failed to load resource: the server responded with a status of 404 ()
/resources/sap/m/messagebundle_de_DE.properties:1 Failed to load resource: the server responded with a status of 404 ()
3jquery-dbg.js:9203 Failed to load resource: the server responded with a status of 404 ()

**Comment by IObert** [comment]
Hi Marco,

It'd kind of that hard to read in GitHub. From what I see, this seems all ok. It's "normal" that you get those errors regarding the i18n files. Your browser will first try to fetch the i18n file for your primary language `i18n_de_DE.properties` (German, Germany). In case this fails, it'll try to fetch a more generic version `i18n_de.properties` (just German, could be "Austrian German too") and eventually, come to the fallback `i18n_en.properties`. 
The wizard only created one i18n file by default. You can add more files to your project in the `i18n` folder if you'd like to avoid this error.

Can you see the call for the "metadata" file? In case this request is successful, you're all fine.

Regards,
Marius

**Comment by marcobuescher** [comment]
OK, thanks I will test it. By the way, why does the "Done" Button only works on IE?
Or had I to respect some functions in chrome?

Regards

**Comment by IObert** [comment]
You should be able to see the done buttons in all browser. There are some old tutorials that don't have them yet, but you shouldn't see a difference between browsers

**Comment by marcobuescher** [comment]
I see the buttons, yes but they don´t work... It will not registered if I click on them...

**Comment by IObert** [comment]
Are you logged in and does it work for other tutorials / in the incognito mode? Could be an issue with the cookies?

**Comment by thecodester** [comment]
Also, do you have add blocker type plugin?

**Comment by marcobuescher** [comment]
Thanks for your feedback. Suprise suprise, now it works.... :)

**Comment by thecodester** [comment]
Is this issue full resolved or are you still waiting to check something? If resolved, feel free to close.
