### ISSUE TITLE
Edit Web Content in your Portal Freestyle Site

### ISSUE THREAD

**Issue by entmike** [SAPDocuments/Tutorials#3496]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-freestyle-site-edit-content.html

Please specify the step you are referring to

On the final question "From the web content editor tools, web content editors can:", no answer seems to work.  I suspect the answer is "Edit text, images, videos and other web content." however I always get "Sorry, that’s incorrect. Please try again"

**Comment by entmike** [comment]
Never mind.  It finally took.

**Comment by thecodester** [comment]
Good that it worked. If there is something you needed to do to get it to work, or there was some error, feel free to let us know.
