### ISSUE TITLE
Add a Web Dynpro ABAP App to Your Launchpad Page

### ISSUE THREAD

**Issue by entmike** [SAPDocuments/Tutorials#3497]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-freestyle-site-wd-add.html

Please specify the step you are referring to

The last question for the adding Web Dynpro ABAP tutorial is a question about UI Theme Designer.

**Comment by LindsayBert** [comment]
Hi

What is the issue?

Thanks 
Lindsay Bert

**Comment by entmike** [comment]
The issue is that the question has nothing to do with the tutorial contents and appears to be a copy and paste issue from the UI Theme Designer tutorial that contains the same question.

**Comment by thecodester** [comment]
Question is fixed. Let me know if it works for you.

**Comment by LindsayBert** [comment]
Yes I just checked and the tutorial is updated.


Thanks
Lindsay
