### ISSUE TITLE
Perform Text Analysis with SAP HANA Express Edition

### ISSUE THREAD

**Issue by entmike** [SAPDocuments/Tutorials#3498]
Tutorial URL: https://developers.sap.com/tutorials/hxe-docstore-05-graph-analysis.html

Please specify the step you are referring to

Step 7 fails.  I followed all prior steps, however when running this command:

```sql
  CREATE GRAPH WORKSPACE  "EXAMPLE_WORKSPACE"
  EDGE TABLE  "EDGES_DATA"
  SOURCE COLUMN "src_id"
  TARGET COLUMN "dest_id"
  KEY COLUMN "NAME"
  VERTEX TABLE  "NODES_DATA"
  KEY COLUMN "NAME";
```

I get this error:

```
Could not execute 'CREATE GRAPH WORKSPACE "EXAMPLE_WORKSPACE" EDGE TABLE "EDGES_DATA" SOURCE COLUMN "SRC_ID" TARGET ...'
SAP DBTech JDBC: [260]: invalid column name: Cannot find the key column in the edge table.
```

**Comment by qualiture** [comment]
Hi @entmike,

Apologies for the confusion... the error is because the `KEY COLUMN` should be `ID` instead of `NAME`, see related issue https://github.com/SAPDocuments/Tutorials/issues/3189

The correct statement should be:

```
  CREATE GRAPH WORKSPACE  "EXAMPLE_WORKSPACE"
  EDGE TABLE  "EDGES_DATA"
  SOURCE COLUMN "SRC_ID"
  TARGET COLUMN "DEST_ID"
  KEY COLUMN "ID"
  VERTEX TABLE  "NODES_DATA"
  KEY COLUMN "NAME";
```

I will try to update the tutorial later today

**Comment by qualiture** [comment]
Will be fixed with PR https://github.com/SAPDocuments/Tutorials/pull/3520
