### ISSUE TITLE
Set Up Connection Between Google BigQuery and SAP HANA

### ISSUE THREAD

**Issue by entmike** [SAPDocuments/Tutorials#3499]
Tutorial URL: https://developers.sap.com/tutorials/gcp-hxe-evt-bq-1.html

Please specify the step you are referring to

Step 2, would be nice if the `setup.sh` file could be made available for after the event, as I am able to follow along so far otherwise after conference.

**Comment by Lsubatin** [comment]
Sorry, Mike. If I could, I would have made it available and removed that warning from this tutorial series. I documented the steps covered by the script here: https://codelabs.developers.google.com/codelabs/sap-hana-connect-to-bigquery/#0 

I will warn you that the OS user executing the commands is very important and that the process is painful and error prone. And yes, restart the machine when it tells you to.

**Comment by entmike** [comment]
Lucia, understood, and thanks for the link, I'll go through the steps and adapt as need.

**Comment by entmike** [comment]
Also, just FYI, on this step:

https://codelabs.developers.google.com/codelabs/sap-hana-connect-to-bigquery/#6 (Step 7)

I think you have the path wrong:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/sap/XHE/home/simba/googlebigqueryodbc/lib/64
```

Shouldn't it be this?

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/sap/HXE/home/simba/googlebigqueryodbc/lib/64
```
