### ISSUE TITLE
Add a Database to Your Business Application

### ISSUE THREAD

**Issue by entmike** [SAPDocuments/Tutorials#3500]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-03-add-database.html

Please specify the step you are referring to

Step 2 - When attempting to connect to CF Region, I get an error:

**A network request failed with an error (Request failed: error URI: /di/hrtt/prefs/cfapi_us10/service/v2.10.22/sap/hana/cst/api/info?authdlg=true)**

My CF Region and HDI Module are running on US East (VA) - My Database Explorer preference are also pointing to the same region.

The JSON of the error in Chrome Debugger says:

```json
{
   "error":{
      "errorCode":"INVALID_SERVICE_VERSION",
      "message":{
         "value":"The version prefix /v2.10.22 does not match the supported version /v2.10.13 in URL /v2.10.22/sap/hana/cst/api/info?authdlg=true",
         "lang":"en-US",
         "requestId":"95470916-0e87-416d-4445-9cdb89a4af0a"
      },
      "args":[
         "/v2.10.22",
         "/v2.10.13",
         "/v2.10.22/sap/hana/cst/api/info?authdlg=true"
      ]
   }
}
```

Cannot proceed in tutorial further as a result.

**Comment by renejeglinsky** [comment]
@entmike I am in touch with my colleagues and shared this issue with them. We'll get in touch with you soon.

**Comment by adhurst** [comment]
@entmike Can you tell us what neo region is your webIDE being accessed from?

**Comment by entmike** [comment]
Rot (trial)

**Comment by renejeglinsky** [comment]
Thanks @entmike ! Is this the information you need @adhurst ?

**Comment by adhurst** [comment]
Hi @entmike,
At the moment we are rolling out database explorer updates to the various cloud regions.
We are aware of an issue related to connecting to un-upgraded cloud foundry regions from some neo regions.  I believe this is what you are encountering.  We are currently working on a fix for the issue, but in the meantime I believe the US10 region is scheduled to be upgraded early next week.  Once this is upgraded the issue should go away.
An additional workaround would be to access webide from the same geographic area as the cloud foundry region where your module resides.

Thanks for your patience,
Adam

**Comment by entmike** [comment]
Understanding I can give, but I do not have the luxury as a Trial user of switching regions, so I will go the path of patience and try later if I remember.  Just some feedback if you care to pass it along to someone who coordinates updates to SCP, is that this type of problem really doesn't help new developer adoption when roll outs like these can impact people working on actual real projects and even makes me hesitate choosing SCP to develop in.

**Comment by renejeglinsky** [comment]
@entmike I fully understand. Let me point you to a nice blog from a colleague that explains how to switch regions: https://blogs.sap.com/2019/04/16/how-to-change-the-region-in-your-cloud-foundry-trial/
This avoids the waiting period. Hope this helps.

**Comment by thecodester** [comment]
Thank you for your feedback. I am closing the issue, but if you still have questions, feel free to reopen.
