### ISSUE TITLE
Use JPA in Custom Logic

### ISSUE THREAD

**Issue by sroehrig** [SAPDocuments/Tutorials#3505]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html

Please specify the step you are referring to:

Step 1: Generate JPA classes

There seems to be a problem with the changes in the pom.xml, because the jpa files are not generated afterwards.

**Comment by JijoRoyJacob** [comment]
Hi,
When you run a build, make sure you right-click the srv module and choose Build as indicated in sub-step 10. Running a build at the project level does not generate the JPA classes.

Best regards,
Jijo

**Comment by sroehrig** [comment]
Hi,
thanks for your reply! :)
The tutorial is not completely up to date, there are some deviations:
- Step 1.3: There is no need to rename the service
- Step 1.4: If this is not the first tutorial in a trial account the existing service instance need to be deleted
##### break #####
Currently I try to redo the tutorial, because I deleted it accidentally.
After I deleted the old service instance, the creation of the new service instance fails, so I'm blocked at the moment.
Do you have any idea how to overcome this problem?
Best regards,
Stefan

**Comment by JijoRoyJacob** [comment]
Hi Stefan,
Are we still talking about the [JPA tutorial](https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html)? The steps 1.3 and 1.4 in this tutorial are different.

In order to work through the JPA tutorial, you need to make sure you cover the following tutorials first: 
1. [Create a Business Service Using CDS](https://developers.sap.com/tutorials/cp-apm-01-create-business-service.html)
2. [Add a Database to Your Business Application](https://developers.sap.com/tutorials/cp-apm-03-add-database.html)
3. [Add Custom Logic to Your Service](https://developers.sap.com/tutorials/cp-apm-04-custom-logic.html)

I'm not sure I understood the problem correctly. So the following are the two scenarios that I'm guessing:
**Scenario 1:** You deleted the old bookshop project. Before creating a new one, make sure you delete the old instance from the mta-archives folder as well. Or, you could also try renaming the new project to bookshop1.

**Scenario 2:** You deleted the service instance in Cloud Foundry from the SAP CP cockpit. Simply run the Java application again. This should redeploy the service in the Cockpit. If you're still facing problems, please let me know what the error is.

Best regards,
Jijo

**Comment by sroehrig** [comment]
Hi Jijo,

from my perpective it is a series of 6 tutorials starting with tutorial 1: [Create a Business Service Using CDS](https://developers.sap.com/tutorials/cp-apm-01-create-business-service.html)
JPA tutorial is tutorial 5.
"Step 1.3" means: step 3 in tutorial 1.

**My problem is a mixture of both scenarios:**
I accidentally deleted the whole bookshop project in the Web IDE.
Then I tried to delete the service instance in Cloud Foundry from the SAP CP cockpit in order to clean up.
-> this succeeded after some problems
Then I recreated the tutorial till step 1.4.
Then I ran the java application again, but it failed.
**Message:**
_Service provisioning started
Build started
Service provisioning failed. See the console for more information._
**Console log:**
_11:01:05 ...
11:01:05 (Java Build) [INFO] ------------------------------------------------------------------------
11:01:05 (Java Build) [INFO] BUILD SUCCESS
11:01:05 (Java Build) [INFO] ------------------------------------------------------------------------
11:01:05 (Java Build) [INFO] Total time:  19.010 s
11:01:05 (Java Build) [INFO] Finished at: 2019-05-21T09:01:05Z
11:01:05 (Java Build) [INFO] ------------------------------------------------------------------------
11:01:05 (Java Build) deleting: anyfile
11:01:05 (Java Build) 	zip warning: zip file empty
11:01:05 (Java Build) ./target/bookshop-srv-1.0-SNAPSHOT.war
11:01:05 (Java Build) 
11:01:08 (Java Build) Build of "/bookshop/srv" completed.
11:05:44 (Provision) Service provisioning for module: "/srv"
11:05:44 (Provision) Could not create the 'bookshop-bookshop-hdi-container-S0gptXlzekxBCnkIMN' instance of the 'hanatrial' service type for the 'bookshop-hdi-container' resource. null
11:05:44 (Provision) Provision fail since one of the provision tasks finished with error._
**In Cloud Foundry SAP CP cockpit I can see that the creation is still running (now is 15:33).**

Thanks for your help!

Best regards,
Stefan

**Comment by JijoRoyJacob** [comment]
Hi Stefan,
Did you remove the old instance of bookshop from mta-archives folder? If you have and it still causes a problem, this application might be somehow messed up in your CF environment. I would recommend creating a separate project called `bookshop1` or by any other name you choose to avoid conflicts.

Best regards,
Jijo

**Comment by sroehrig** [comment]
Hi Jijo,

I use WebIDE and as I said, I accidentally deleted the whole old project.
What is the mta-archives folder and where can I find it?

Anyway, I started now with bookshop1 and I'll inform you about my results.

Best regards, Stefan

**Comment by sroehrig** [comment]
Hi Jijo,

I found the problem in step 5.1
The description in the tutorial is a bit misleading in two places:

In step 5.1.5 it is written `Add the CSN2JPA plugin in pom.xml as indicated in the following code:`
But in the following snippet, three plugins have to be added!

In step 5.1.6 it is written `In order to actually execute the JPA operations, add EclipseLink to the dependencies section of pom.xml.`
But the existing dependencies section (inside profile 'only-eclipse') is the wrong one.
Instead a new dependencies section after the profiles section has to be created!

I hope this feedback is helpful.

Best regards,
Stefan

**Comment by JijoRoyJacob** [comment]
Hi Stefan,
That's good feedback. I'll incorporate it so that the steps are more clear. Thank you for pointing that out.

Best regards,
Jijo

**Comment by thecodester** [comment]
@JijoRoyJacob Can I close the issue?

**Comment by JijoRoyJacob** [comment]
Yes. The issue can be closed. Updates to the tutorial will be released shortly.
