### ISSUE TITLE
Use JPA in Custom Logic: Could not resolve host

### ISSUE THREAD

**Issue by cookieMonster21** [SAPDocuments/Tutorials#3509]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html

I start the application as described in step 5.

I am using a trial account. 

After increasing my memory as mentioned here: https://github.com/SAPDocuments/Tutorials/issues/3235 I am getting the CatalogService via the link (solved http status 404).

Using the commands as mentioned in step 5 for testing I am getting back:  `Could not resolve host`. I am working on windows so I tried:
`curl -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d "{ \"buyer\" : \"JPA Buyer 1\", \"book_ID\" : 310 }" https://m11dmbrr29jui17d-bookshop-srv.cfapps.eu10.hana.ondemand.com/odata/v2/CatalogService/Orders`

Any ideas?

**Comment by JijoRoyJacob** [comment]
Are you able to see the metadata for the service? Try this URL: https://m11dmbrr29jui17d-bookshop-srv.cfapps.eu10.hana.ondemand.com/odata/v2/CatalogService/$metadata.

**Comment by cookieMonster21** [comment]
Thanks for your replay. I just jumped over and can't try it anymore. When I have this issue again, I will try it.
