### ISSUE TITLE
Create an SAPUI5 App from the Command Line

### ISSUE THREAD

**Issue by ND3V** [SAPDocuments/Tutorials#3512]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-sapui5-local.html

As a windows user, step 4 was giving me a hard time, as 
"cp cf_deployment_resources/package.json  dist/package.json" will not work. 
I added a cp.js file to root containing the line
<code>
require("fs").copyFile(process.argv[2], process.argv[3], err => {if (err) throw err});
</code>
replace "cp" in the script with "node cp.js" and that part is good to go.

please also hint us winnies to use "choco install make" (i found chocolateley easiest to install)
to "make" the last part of the script work.

edit: you might find this entirely normal, but build will also fail when you don't update your .npmrc file (see: https://blogs.sap.com/2017/05/16/sap-npm-registry-launched-making-the-lives-of-node.js-developers-easier/ )
no, i don't think devs usually do this a lot. i pearsonally would wish my live was a littlee harder and i did i had not to find out.

**Comment by IObert** [comment]
Hi @ND3V,

thank you for your very good feedback! I change the script to avoid the platform specific `cp` command and added a note to install `make`. 

Can you explain the issue you're facing with the `.npmrc` file? The file should already come with all information to connect to the npm repository.

Thanks,
Marius

**Comment by ND3V** [comment]
Hi IObert, 
thanks for the update. Back then i was experiencing issues with the @sap modules, which went away once i updated my user-specific .npmrc - I was not able to reproduce this, as now the project-specific setting seems to suffice. I suspect a connectivity-issue or somesuch which coincidently resolved as i was creating a user-npmrc.
In my eyes, this can be closed.
