### ISSUE TITLE
Add an Onboarding Flow

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3513]
Tutorial URL: https://developers.sap.com/tutorials/cp-sdk-android-flows-onboard.html

Please specify the step you are referring to Step 1:

Hello,

I get six errors. I think, there is a problem  by the import of the "OnbordingContext" bibliothek.
![Unbenannt](https://user-images.githubusercontent.com/10000063/57969248-71451c80-7975-11e9-9d05-463ff26b3071.JPG)

So i can´t run the Project in the emulator.

null |  
-- | --
C:/SAP SDK/Androidsdk/Flows |  
app/src/main/java |  
com/sap/flows/MainActivity.java |  
error: cannot find symbol class OnboardingContext |  
error: package com.sap.cloud.mobile.flow.onboarding.presenter does not exist |  
error: cannot find symbol class OnboardingContext |  
error: cannot find symbol class OnboardingContext |  
error: cannot access Settings class file for com.sap.cloud.mobile.onboarding.utility.Settings not found |  
error: cannot find symbol class FlowPresentationActionHandlerImpl |

**Comment by danielva** [comment]
Please try downloading the 2.1.1 version of the SAP Cloud Platform SDK for Android which is available at https://www.sap.com/developer/trials-downloads/additional-downloads/sap-cloud-platform-sdk-for-android-15508.html.  Modify the sdkVersion in the gradle.properties to use 2.1.1.
I believe that will correct the error seen above.  
I will work on updating the tutorial to ensure it reflects that version 2.1.1 is the required version.
Thanks for finding this issue.
Dan van Leeuwen

**Comment by marcobuescher** [comment]
Yes, you are right, now it works!
