### ISSUE TITLE
Access the SAP Screen Personas Training System

### ISSUE THREAD

**Issue by ChrisWake** [SAPDocuments/Tutorials#3514]
Tutorial URL: https://developers.sap.com/tutorials/personas-access-learning-sys.html

Please specify the step you are referring to
Unable to access the above URL link not working on Chrome.

**Comment by Waltersen1971** [comment]
Hello,

I have done that tutorial and I was able to do it via Chrome (from my work PC).

**Comment by marcobuescher** [comment]
I made it too, maybe the System was down. Now, the link works...

**Comment by ChrisWake** [comment]
Hi,

Just checked link is now working thanks for checking.
