### ISSUE TITLE
Create Workflow (part 1), Enrich data with Data Transform in SAP Data Hub, trial edition 2.4

### ISSUE THREAD

**Issue by Rob3487** [SAPDocuments/Tutorials#3515]
Tutorial URL: https://developers.sap.com/tutorials/datahub-trial-v2-workflow-part01.html

Please specify the step you are referring to: 5 

I think it would have been an improvement to the Tutorial if 'set' 'Naming of the Graphs' was given.
The tutorial user has no idea what is coming next in the tutorials. It is not until tutorial 7 that we become aware that we must find the Graphs that we created in tutorial 5 and 6. 

There was no explanation in tuturial 5 of 12 regarding the Graph Naming conventions. During tutorial 7 of 12 it was challenging to find the graphs previously created, as at the time of creation, we were naming our Graphs 'in the dark'.

Just a suggestion :)

**Comment by fx5151git** [comment]
Thank you for your suggestion.  It will be definitely better to add the naming instruction here. I will add it soon.

**Comment by thecodester** [comment]
@schneidertho Has this been handled?

**Comment by schneidertho** [comment]
I checked it today. This still needs to be done (seems we forgot it). I will put it on my todo list for when we make the next update to the tutorials.

**Comment by MichaelCzcz** [comment]
@schneidertho any updates?

**Comment by MichaelCzcz** [comment]
@schneidertho any updates?

**Comment by MichaelCzcz** [comment]
@schneidertho any updates?

**Comment by roy-zhong** [comment]
@Rob3487 
The name is added in step 5.3

**Comment by thecodester** [comment]
@roy-zhong Do you have a PR/commit you can point to to show it is complete (you can put this in the issue)? Can this be closed now?

**Comment by roy-zhong** [comment]
@thecodester
This can be closed.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
