### ISSUE TITLE
Store Sensor Data in Cloud Storage in SAP Data Hub, Trial Edition 2.4

### ISSUE THREAD

**Issue by Rob3487** [SAPDocuments/Tutorials#3516]
Tutorial URL: https://developers.sap.com/tutorials/datahub-trial-v2-pipelines-part02.html

Please specify the step you are referring to 1

Am unable to connect with the https://sapdatahubtrial  
I am receiving a 502 error (bad gateway), I am using SAP Datahub Trial Edition 2.4.

I have tried rebooting the Trial 2.4 Instance, however with no improvement.

I have waited and retried for 60 minutes.

I have tried both the RDP path to connection and also the directly from my local browser (which I have successfully used for a number of days now, including yesterday), same 502 error both paths.

I am looking forward to some feedback - thank you in advance.

Rob

![image](https://user-images.githubusercontent.com/19631990/57986071-6690a180-7ab3-11e9-9261-748b77bb6e8a.png)

**Comment by Rob3487** [comment]
Today all is working again!

**Comment by thecodester** [comment]
👍
