### ISSUE TITLE
Access a Classic Schema from SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by bcschaich** [SAPDocuments/Tutorials#3519]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-access-cross-container-schema.html

Please specify the step you are referring to
Step1.

When going throug this I get an error message for
CREATE ROLE CCROLE;

WebIDE says: "ROLE is not supported" 
![ROLE Error message](https://user-images.githubusercontent.com/20598911/58017991-e8a7b700-7b01-11e9-87a8-eb6f096fd4a9.png)

**Comment by Lsubatin** [comment]
Have you tried executing the statement? Do you get an error after execution?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
