### ISSUE TITLE
Grunt Build in SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by PavanAthreyas** [SAPDocuments/Tutorials#3521]
Tutorial URL: https://developers.sap.com/tutorials/webide-grunt-basic.html

Please specify the step you are referring to

How to create build for SAP Fiori Extension project. ? to create component-preload.js and component-preload-h2.js ?

BR,
Pavan

**Comment by ShiraManas** [comment]
Hi Pavan, 
Can you please explain your question a little bit more? 
I am not sure I understand what the question is that you are asking.

Thanks!
Shira

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
