### ISSUE TITLE
Store Sensor Data in Cloud Storage in SAP Data Hub, Trial Edition 2.4

### ISSUE THREAD

**Issue by Rob3487** [SAPDocuments/Tutorials#3522]
Tutorial URL: https://developers.sap.com/tutorials/datahub-trial-v2-pipelines-part02.html

Please specify the step you are referring to 2.

"Open the pipeline which you have created in the previous tutorial (test.myFirstPipeline)" 
I cannot find any referrence to "test.myFirstPipeline" in previous tutorials. 

Is this the tutorial no. 7 of 12; "Create Workflow (part 3), Build a task Workflow in SAP Data Hub, trial edition 2.4"?

**Comment by Rob3487** [comment]
Found it!
Tutorial "Tutorial 10 of 12"; "Generate sensor data in SAP Data Hub, trial edition"

**Comment by thecodester** [comment]
👍 

@fx5151git You might want to make sure the tutorial is clear.

**Comment by fx5151git** [comment]
Thank you so much for your info, already add the tutorial name and link to help you find the created pipeline.
