### ISSUE TITLE
Download SAP Mobile Cards to Your Device

### ISSUE THREAD

**Issue by ND3V** [SAPDocuments/Tutorials#3525]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-download-card.html

Please specify the step you are referring to: 1

Both qr-codes lead to the iTunes landingpage

**Comment by shilpavij** [comment]
You can go to app store and download mobile card apps too.

Regards
Shilpa

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
