### ISSUE TITLE
Deploy Application to Cloud Foundry with SAP Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by austinkloske22** [SAPDocuments/Tutorials#3530]
Tutorial URL: https://developers.sap.com/tutorials/s4sdkjs-deploy-application-cloud-foundry.html

I am attempting to run this node.js module as part of a larger Multi-Target-Application (MTA) that I originally created using the SAP Full Stack Web IDE, Business Application Template. 

When Attempting to run the s4sdk for javascript module on the Web IDE, I run into error "You have not provided a name to set. Usage: npm run init -- <YOUR_APPNAME>". I don't believe running this type of command is possible via Web IDE. 

My MTA has four main modules: db (the HDI Container), srv (the node.js OData service), sdk (this s4sdk javascript module) and shipping (html5 module).

Is it possible to integrate your typescript approach to an existing MTA being developed and running on Web IDE? If so, I would greatly appreciate any assistance. My project repository is currently public here: https://github.com/austinkloske22/s4sdk

**Comment by mr-flannery** [comment]
Hi @austinkloske22,

thanks for reaching out to us and sorry for the delay.
We don't have much experience with the SDK for JavaScript in MTA/WebIDE projects.
However, the error you mention is thrown in `initialize.js`, which is only called when running `npm run init`, which is the exact script the error tells you to run. So I'm wondering how this can happen if the command can't be run like this in WebIDE.
Either way, you can delete `initialize.js` and also the `init` script in the `package.json` and instead do what the script does yourself, which is mainly overwriting the app name in the `manifest.yml`.
Hope this helps!
