### ISSUE TITLE
Create Handlebars Helper Card - Step 6: Subscribe to the card

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#3531]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-handlebar.html

Step 6: Subscribe to the card

I've followed the steps in the tutorial and I was able to subscribe to the card. But I don't see 3 available cards. Was that done in another tutorial? In https://developers.sap.com/tutorials/cp-mobile-cards-web-push.html the was created using the Web IDE App.

**Comment by jitendrakansal** [comment]
@gregorwolf handlebar tutorial has been updated with some UI level changes, please try again, you should see top 3 (as per default query).

**Comment by jitendrakansal** [comment]
@thecodester i haven't heard back from OP. Assuming it has worked for him.
 In case, you want to close this issue.
