### ISSUE TITLE
Deploy SAP HANA as a Service

### ISSUE THREAD

**Issue by fernandolw19** [SAPDocuments/Tutorials#3532]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-deploying-haas.html

Please specify the step you are referring to:

HI. 

When you perform the step-by-step "Deploy SAP HANA as a Service", I will check that the service option, which is in the tutorial: "SAP HANA Service" is not found, as shown in the attached image.
Which option should I follow?

![image](https://user-images.githubusercontent.com/50889636/58132214-191d4d00-7bf7-11e9-829a-bb715e7d36fd.png)

**Comment by Lsubatin** [comment]
Hi Fernando, 
Thanks for bringing this up. I'm not sure why it was still showing the trial in the titles but I have refreshed it to make it consistent with the initial warning.

Unfortunately, for now, you can only complete this with a productive account and a subscription to the HANA service.  

Thanks, 
Lucia.
