### ISSUE TITLE
Add an Onboarding Flow

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3534]
Tutorial URL: https://developers.sap.com/tutorials/cp-sdk-android-flows-onboard.html

Please specify the step you are referring to 3:

Isn´t It right, that we all work on your App as shown in configorationprovider.json: 

{
  "auth":[{"type":"basic.default","config":{},"requireOtp":false}],
  "host":"hcpms-p1743065160trial.hanatrial.ondemand.com",
  "port":443,
  "protocol":"https",
  "appID":"com.sap.wizapp"
}

so, we can´t disable passcode for this app in this tutorial?

Regards

Marco

**Comment by danielva** [comment]
The line above the configurationprovider.json mentions
Update the host value to match your Mobile Services host.
So the intent is for someone following the tutorial to change p1743065160 to their user id.
I will try to make that more clear in the tutorial.

Regards,
Dan van Leeuwen

**Comment by marcobuescher** [comment]
OK, I made the Toutorial ready one hour ago. It was grat to see what we can do with the mobile devices. Thanks for that!
