### ISSUE TITLE
Onboarding a computer as the IoT thing

### ISSUE THREAD

**Issue by davidgrindleysap** [SAPDocuments/Tutorials#3536]
Tutorial URL: https://developers.sap.com/tutorials/iotae-comp-thingmodeler0.html

Please specify the step you are referring to

I'm at step 1 and have followed the initial link top get a username and password but they are not recognised when trying to logon to 'sap-iotaehandson2'. 

The username is 'P002750'

I am an SAP employee and so have SSO set up for access to other SAP systems (email etc.)

Can you help?

Thanks
Dave Grindley

**Comment by marcuscbehrens** [comment]
Hi, SSO within SAP does not apply here. Please use the initial password and your user id P002750 to login. If you need to reset your password ping me. Regards, Marcus

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
