### ISSUE TITLE
Use JPA in Custom Logic

### ISSUE THREAD

**Issue by svenkohlhaas** [SAPDocuments/Tutorials#3538]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html

The build command in the package.json file needs to be:
`"build": "cds build/all --clean && cds compile db/data-model.cds -o ./",`
otherwise it will fail, the /all part is missing in the tutorial.

**Comment by JijoRoyJacob** [comment]
Hi Sven,
I've checked with the dev team on this and they say that `build/all` is a new build implementation that will eventually replace the current `build`. And so for now, we're leaving it as is.

Best regards,
Jijo

**Comment by svenkohlhaas** [comment]
Ok, will close the issue then. Just wanted to provide the feedback that without the /all the build failed and with the /all the build worked.
