### ISSUE TITLE
Add Basic Logging to Your Node.js App

### ISSUE THREAD

**Issue by Haruyuki-Kobayashi** [SAPDocuments/Tutorials#3539]
Tutorial URL: https://developers.sap.com/tutorials/cp-node-app-logging.html

Please specify the step you are referring to
At step Step 5: Stream application logs
The command :cf logs myapp | grep -v RTR does't work.
Seems simply cf logs myapp works!

**Comment by maxstreifeneder** [comment]
Hey @Haruyuki-Kobayashi, 

thanks for your observation and for the according issue! Of course grep doesn't work on Windows and hadn't considered that. Should be fixed now. Could you please retest?

Cheers,
Max
