### ISSUE TITLE
Set Up SAP Data Hub, Developer Edition 2.4

### ISSUE THREAD

**Issue by thulium3** [SAPDocuments/Tutorials#3541]
Tutorial URL: https://developers.sap.com/tutorials/datahub-docker-v2-setup.html

Please specify the step you are referring to
The command docker run -ti --env VORA_USERNAME=vora --env VORA_PASSWORD=SomeNicePassword19920706 --publish 127.0.0.1:8090:8090 --publish 127.0.0.1:9225:9225 --publish 30115:30115 --name datahub --hostname datahub --network dev-net datahub run --agree-to-sap-license
 is not working because the name of the docker image is "sapdatahub/dev-edition:2.4" instead of "datahub"

**Comment by fx5151git** [comment]
Hi, Could you share me your screenshot or give me some more details? From my side I checked the images it is still datahub.

**Comment by fx5151git** [comment]
@thulium3

**Comment by thulium3** [comment]
I would have to redo all steps to create a screenshot. Maybe I made a mistake in one of the steps and after that my image was named "sapdatahub/dev-edition:2.4" instead of "datahub". If noone else has the error than it should be ok.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
