### ISSUE TITLE
Use Mobile Services to Create UI

### ISSUE THREAD

**Issue by ND3V** [SAPDocuments/Tutorials#3550]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-create-ui.html

Please specify the step you are referring to: 1:4

In the screenshot it says "Destination: API_Portal_Trial" (which works - I think), The "other destination which is available as a dropdown", and as such propably what you meant in the table 
 of values, leads to a 403.

The "HTML Template: User defined template" is not available as initial dropdown but appeared somehow after saving the card and reopening it. (was not able to reproduce, still stuck on the following issue)

the values in step 1:5 unfortunately lead me to a "HTTP error: 500; please check the back-end logs." when checking the query URL on the right side. 
Are the serverlogs available somewhere in the API Manager?

**Comment by shilpavij** [comment]
Hello,

Its just that whatever destination you have created to point it to API Portal you need to select that.
Just check for spaces and your proxy path for query URL. I cross checked and it works me.

Unfortunately, I can not check this log as this is in your trial, I would request you to check the error in your query.

Regards
Shilpa

**Comment by shilpavij** [comment]
Also, Please check the recent document we have couple of changes.

**Comment by ND3V** [comment]
Thank you for your prompt reply. Sorry for not being more specific, the issue that kept me from completing was that i could not find the backend logs. I investigated further and found the Tryout in API portal to be the next best thing. With this tool i am able to specify the issue much better:

GET /A_SalesOrder without parameters leads to the response: 
Code:  "", Details: "Error: Created"

by adding the "to_Item" parameter the response is: 
Code: 500, Response Body: `<?xml version="1.0" encoding="utf-8"?>
  <error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
    <code>RAISE_SHORTDUMP</code>
    <message>Runtime Error: 'RAISE_SHORTDUMP'. The OData request processing has been abnormal terminated. If "Runtime Error" is not initial, launch transaction ST22 for details and analysis. Otherwise, launch transaction SM21 for system log analysis.</message>
    <timestamp>20190525073156</timestamp>
  </error>`

**Comment by ND3V** [comment]
Oh and as a sidenote: your i# and p# accountnuumbers are shown in the screenshots here:
https://developers.sap.com/tutorials/cp-apim-sales-tracker-api-discover.html

**Comment by shilpavij** [comment]
Thanks a lot for the feedback.I will blur my personal details.
If I get your problem right, you are unable to try out the API from SAP API Business Hub itself right?
I tried again and found out there is no issue for me there. Are you fetching 3- 5 records. Just try that.
I am attaching the screen shot too .
![image](https://user-images.githubusercontent.com/44152823/58394677-1a6cd080-8062-11e9-9a92-53f82d74af2c.png)

If this is not your problem, I would request you to please mention the exact steps from beginning.

Regards
Shilpa

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
