### ISSUE TITLE
Polygons

### ISSUE THREAD

**Issue by Bingzi-Li** [SAPDocuments/Tutorials#3551]
Tutorial URL: https://developers.sap.com/tutorials/hana-spatial-intro3-polygon.html

Please specify the step you are referring to
Polygons step1 code snippet does not correspond to the graph shown.

code in tutorial:
SELECT NEW ST_Polygon('Polygon ((0 0, 4 0, 0 3, 0 0), (0.5 0.5, 0.5 1.5, 1.5 1.5, 1 0.5, 0.5 0.5))').ST_asSVG() FROM dummy;

code corresponding to graph:
SELECT NEW ST_Polygon('Polygon ((0 0, 4 0, 0 3, 0 0), (0.5 0.5, 0.5 1.5, 1.5 1.5, 1.5 0.5, 0.5 0.5))').ST_asSVG() FROM dummy;

**Comment by MichaelCzcz** [comment]
@Sygyzmundovych any updates?

**Comment by Sygyzmundovych** [comment]
Code is fixed and the tutorial updated.
