### ISSUE TITLE
Import the MovieLens dataset (MovieLens App)

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3555]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aa-movielens-03.html

Please specify the step you are referring to Step 7.

Hello Abdel,
I think the Folder is "movielens" not "forcast", isn´t it?

Regards 
Marco

**Comment by adadouche** [comment]
Thank you for catching that. It should be fixed and in production soon.

Thanks again

@bdel
