### ISSUE TITLE
SAP HANA XS Advanced, Creating an HDI Module

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3556]
Tutorial URL: https://developers.sap.com/tutorials/xsa-hdi-module.html

Please specify the step you are referring to Step 4.

There is no Question to answer. I made it with try and error.

Regards

Marco

PS: Nice tutorial so far...

**Comment by thecodester** [comment]
I see in the text "Right-click on the Header table and use the generated SQL statement in the validation below". This is the question, no?

**Comment by marcobuescher** [comment]
yes, but that is a bit ambiguous, isn´t it?
