### ISSUE TITLE
Perform Text Analysis with SAP HANA Express Edition

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3558]
Tutorial URL: https://developers.sap.com/tutorials/hxe-docstore-05-graph-analysis.html

Please specify the step you are referring to Step 4,

Hello,

I get the followin error Message when I try to Import the JSON documents:

Could not execute 'insert into food_sentiment
 with doc_store as (select "name", "description" from food_collection)
 ...'
Error: (dberror) [301]: unique constraint violated: TrexUpdate failed on table 'SYSTEM:FOOD_SENTIMENT' with error: unique constraint violation in self check for table HXE::SYSTEM:FOOD_SENTIMENTen, constraint='NAME', udiv='436f6d6d6f6e2062656574', pos=19; indexname=_SYS_TREE_CS_#163243_#0_#P0, rc=55

Thanks in Advance

Marco

**Comment by qualiture** [comment]
Hi @marcobuescher,

The unique constraint violation is thrown because the `name` column in table `food_sentiment` is defined as primary key. Could you check whether your `food_collection` Document Store contains multiple similar values in its `name` column via 

    SELECT "name", "group" FROM food_collection;

Each entry should only be listed once

**Comment by marcobuescher** [comment]
Yes, there are 20 entries in the Table. Thanks...

**Comment by qualiture** [comment]
Glad it was sorted out! :)

**Comment by marcobuescher** [comment]
Now I want to delet the double entrys whithout dropping the table.
I try this:

DELETE FROM food_collection WHERE "name" IN (
SELECT "name"
FROM food_collection
GROUP BY "name"
HAVING (COUNT(*) > 1 ))

**Comment by qualiture** [comment]
Not entirely sure if this would work with Document Stores, but you could also use the `$rowid$` pseudo column:

(NB: **SQL below is not tested**, but loosely handcrafted using Witalij's answer here: https://answers.sap.com/answers/11590676/view.html)

```
DELETE FROM food_collection
WHERE "$rowid$" in (
	SELECT LEAD("$rowid$") over (partition by "name", "group", "subgroup", "nutrients", "description" order by "name")
	FROM food_collection
);
```

**Comment by marcobuescher** [comment]
Thanks for that, I dropped the Table and made it new.
