### ISSUE TITLE
Use JPA in Custom Logic

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#3562]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html

Step 1: Generate JPA classes

I've followed the steps and updated package.json & srv/package.json. But when I try to compile I get the error:

17:40:55 (Java Build) [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project bookshop-srv: Compilation failure: Compilation failure: 
17:40:55 (Java Build) [ERROR] /projects/bookshop/srv/src/gen/java/com/sap/demo/bookshop/jpa/my/bookshop/Authors.java:[8,25] package javax.persistence does not exist

I've created a Git repository with my code at https://github.com/gregorwolf/bookshop-java so you should be able to replicate my issue easy.

**Comment by JijoRoyJacob** [comment]
Hi Gregor,
I found an issue in the pom.xml file. You'll need to redo Step 1 - substep 6. Do not add the dependencies to the `dependencies` section under the `only-eclipse` profile. Instead, create a separate `dependencies` section under `project` and add them there as indicated in the sample code. I added some clarification around that today.

Best regards,
Jijo

**Comment by gregorwolf** [comment]
Thank you for the hit. I've made progress with that now.
