### ISSUE TITLE
Explore and Customize Your SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by raz-korn** [SAPDocuments/Tutorials#3565]
Tutorial URL: https://developers.sap.com/tutorials/webide-customize.html

Please specify the step you are referring to: Step 7.
Update screenshots and text that include "builder" information. 
Builder is no longer handled by the users.

**Comment by ShiraManas** [comment]
Hi,
I updated the tutorial and it no longer includes the "Install Builder" information and button in the screenshots. Thanks for pointing it out.
