### ISSUE TITLE
Connect to OData Service on Cloud Foundry Using SAP Cloud SDK

### ISSUE THREAD

**Issue by jpetersendk** [SAPDocuments/Tutorials#3566]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-odata-service-cloud-foundry.html

Step 5: Deploying the Project

Never got past this step as the instructions are unclear on the ODATA service. How to setup and access.

**Comment by cschubertcs** [comment]
Hi @jpetersendk,

sorry for the long response delay!
Can you check whether the tutorial is still unclear, and if so, which statement? With this information we can then help you as well as anyone that is reading the tutorial in the future.

Greetings
Chris

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
