### ISSUE TITLE
Deploy SAP HANA as a Service

### ISSUE THREAD

**Issue by russellw999** [SAPDocuments/Tutorials#3567]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-deploying-haas.html

Please specify the step you are referring to

Step 2 :  it would be worth mentioning in the Tutorial that you cannot create the HANA Instance from a Trial Account of Cloud Foundry

**Comment by Lsubatin** [comment]
Hi, This is mentioned at the beginning (right before the first step).  Is that what you mean?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
