### ISSUE TITLE
Create a Sample Application on SCP Neo Using SAP Cloud SDK

### ISSUE THREAD

**Issue by jpetersendk** [SAPDocuments/Tutorials#3568]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-scp-neo-sample-application.html

Step 5: Local deployment

When asked for "Enter URL for destination ErpQueryEndpoint:" the tutorial does not explain what to enter here. The same is shown in the screenshot in the tutorial.

**Comment by a-d** [comment]
> You can enter arbitrary values for now, because the destination is not used at this point of the tutorial.

Please enter any URL, e.g. `http://128.0.0.1/`

**Comment by sacnl** [comment]
Thanks for raising this issue.
I believe this is sufficiently explained in the tutorial. If you have any improvement suggestion on how to clarify the wording, please let us know.
Thanks.
