### ISSUE TITLE
Add a UI to Your Business Application

### ISSUE THREAD

**Issue by shenjiansj** [SAPDocuments/Tutorials#3569]
Hi colleagues,

I follow the steps and I want to use the smart template for the UI, and I am wondering if I can use the annotations like the old ways we used in CDS views in S4. Or how can I modify my smart template project because there is no explicit code in project.

Best Regards,
Jay.

**Comment by renejeglinsky** [comment]
Hi @shenjiansj ,

if you are looking for Fiori Elements annotations have a look here: https://sapui5.hana.ondemand.com/#/topic/03265b0408e2432c9571d6b3feb6b1fd

For the CDS syntax here, check this out: https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/855e00bd559742a3b8276fbed4af1008.html 

Regards,
René

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
