### ISSUE TITLE
Send the CPU usage data to SAP IoT Application Enablement

### ISSUE THREAD

**Issue by thomasalexneuhaus** [SAPDocuments/Tutorials#3570]
Tutorial URL: https://developers.sap.com/tutorials/iotae-comp-sendpy0.html

Please specify the step you are referring to

('\nValues to post: ', 99.6, 1559039458)
('Payload to post: ', '{"mode":"sync","messageType":"b6a553afa88aa513df68677e5abddde","messages":[{"cpu_usage":99.6,"cpu_type":"generic","timestamp":1559039458}]}')
(202, u'{"msg":"https://iotmmsa2667617c.hana.ondemand.com/com.sap.iotservices.mms/v1/api/http/ack/5A6E14AA33604F79A36818B0DA485F43/e20484ca-8826-4e69-96ab-e1e9f015f6cc","retryAfterHeaderValue":"60"}')

**Comment by Sygyzmundovych** [comment]
Hi @thomasalexneuhaus Sorry for delay.
What is exactly the issue with the tutorial?
Thank you.

**Comment by marcuscbehrens** [comment]
202 is not a "good" response code in my experience. It makes you believe that processing is still going on but usually it is not with iot service 2.0.

We have fixed an issue that might have led to this issue. If you still have this problem please bring it up again.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
