### ISSUE TITLE
Import Tables and Large Datasets (XS Advanced)

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3571]
Tutorial URL: https://developers.sap.com/tutorials/xsa-import-shine-data.html

Please specify the step you are referring to Step 3.

Hello,

I get the following error if I BUILD the DB:

--> to here, everything is fine!
Deploying "src/data/load.hdbtabledata$0.expand"...     
Expanded from "src/data/load.hdbtabledata"     

--> first error
Error: com.sap.hana.di.tabledata: The "include_filter" definitions in the table import files "src/data/load.hdbtabledata" and "src/data/loads/PurchaseDemo.hdbtabledata" use key values that are not disjunct; "src/data/load.hdbtabledata" has an empty filter set [8251511]       at "src/data/load.hdbtabledata" (54:22)    

-->second error
Error: Worker 4 has encountered an error; all remaining jobs will be canceled [8214600]     
Error: com.sap.hana.di.tabledata: The "include_filter" definitions in the table import files "src/data/load.hdbtabledata" and "src/data/loads/PurchaseDemo.hdbtabledata" use key values that are not disjunct; "src/data/load.hdbtabledata" has an empty filter set [8251511]       at "src/data/load.hdbtabledata" (14:22)    

-->Build failed...
Inserted 2 records of the data source file "header.csv" into the target table "PurchaseOrder.Header"    Deploying "src/data/loads/PurchaseDemo.hdbtabledata$0.expand"... ok    
 Inserted 20 records of the data source file "item.csv" into the target table "PurchaseOrder.Item"    Deploying "src/data/loads/PurchaseDemo.hdbtabledata$1.expand"... ok  
 Error: Processing work list... failed [8212102]   
Make failed (4 errors, 67 warnings): tried to deploy 61 files, undeploy 2 files, redeploy 2 dependent files  Error: Making... failed [8211605] 
Error: Starting make in the container "DB_1" with 61 files to deploy, 2 files to undeploy... failed [8214168] Command failedDeployment to container DB_1 failed - error: HDI make failed [Deployment ID: none].
Error: HDI make failed(50s 658ms)npm ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! deploy@ start: `node node_modules/@sap/hdi-deploy/deploy.js`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the deploy@ start script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.npm ERR! A complete log of this run can be found in:npm ERR!     /hana/shared/HXE/xs/controller_data/executionagent/executionroot/768bc893-0bc8-4969-a833-9a396ee5f1d1/app/META-INF/cache/node8.14/.npm/_logs/2019-05-28T11_55_12_177Z-debug.log
13:55:10 (Builder) Build of /HANA_APP/db failed.

**Comment by Lsubatin** [comment]
Hi, What is the content of the files causing the error? What version of HXE is this?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by Git-DT** [comment]
I just had the same issue as the one posted here.

**Comment by thecodester** [comment]
Can you open a new ticket -- and provide the information on the files?

**Comment by Git-DT** [comment]
Done #3772 raised.
