### ISSUE TITLE
Create additional database artifacts (MovieLens App)

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3572]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aa-movielens-09.html

Please specify the step you are referring to Step 5:

Hello Abdel,

The Build of the three files recommendation_execute.hdbprocedure
•recommendation_result_collaborative.hdbprocedure
•recommendation_result_contentbased.hdbprocedure
 faild whith following:

 Precompiling "src/hdb/apl/procedures/recommendation_execute.hdbprocedure"...     Precompiling "src/hdb/apl/procedures/recommendation_execute.hdbprocedure"... ok    Precompiling... ok    Merging...    Merging... ok    Error: The file requires "db://aa.movielens.db.hdb.apl.afllang::recommendation" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (34:10-59)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.function_header" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (15:20-77)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.indicators" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (55:20-72)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.model" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (49:20-67)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.model_links" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (52:20-73)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.model_node_movie" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (51:20-78)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.model_node_user" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (50:20-77)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.model_sql_code" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (56:20-76)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.operation_config" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (18:20-78)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.operation_log" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (53:20-75)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.summary" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (54:20-69)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.tt_indicators" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (9:23-78)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.tt_model_sql_code" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (10:23-82)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.tt_operation_log" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (7:23-81)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.tt_summary" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (8:23-75)    Error: The file requires "db://aa.movielens.db.hdb.apl::recommendation.variable_descs" which is not provided by any file [8212001]      at "src/hdb/apl/procedures/recommendation_execute.hdbprocedure" (30:20-76)   Error: Calculating dependencies... failed [8212108]   Error: Could not compose a consistent make graph [8212012]   Make failed (18 errors, 0 warnings): tried to deploy 1 files, undeploy 0 files, redeploy 0 dependent files  Error: Making... failed [8211605] Error: Starting make in the container "ML_1" with 1 files to deploy, 0 files to undeploy... failed [8214168] Error: Could not run make [8211554] Error: Could not compose a consistent make graph [8212012]Deployment to container ML_1 failed - error: HDI make failed [Deployment ID: none].Error: HDI make failed(9s 70ms)npm ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! deploy@ start: `node node_modules/@sap/hdi-deploy/deploy.js`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the deploy@ start script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.npm ERR! A complete log of this run can be found in:npm ERR!     /hana/shared/HXE/xs/controller_data/executionagent/executionroot/768bc893-0bc8-4969-a833-9a396ee5f1d1/app/META-INF/cache/node8.14/.npm/_logs/2019-05-28T16_03_26_241Z-debug.log
18:03:16 (Builder) Build of /movielens/db failed.

Can You help?

Regards

**Comment by adadouche** [comment]
Hi @marcobuescher 

Sorry for the late response but I was on holiday and just returned to work (we have too many paid vacation here in France).

Apparently, there are some missing artefacts that the procedure depend on.

These artefacts are created in https://developers.sap.com/tutorials/hxe-aa-movielens-05.html in step 7 & 8.

You should have them in the Database Explorer under your HDI Container below the Table Type & AFL Procedure nodes.

If that's not the case, please redo the steps from https://developers.sap.com/tutorials/hxe-aa-movielens-05.html.

Regards

@bdel

**Comment by adadouche** [comment]
Hi @marcobuescher,

I haven't heard from you so far, so I'll close this issue for now but feel free to reopen it if needed.

Thanks

@bdel

**Comment by marcobuescher** [comment]
Hello, thats ok.. In the Moment it is too hot in my office and I can´t start my Hana on Premise VM. I have only 16GB RAM and its not enough for that because the processor is just too hot and I became a time out. Jealous I look at your Laptop with 64GB .... I would be glad if I can come back to the Ticket soon ...
