### ISSUE TITLE
Create Your First Application with SAP Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#3580]
Tutorial URL: https://developers.sap.com/tutorials/s4sdkjs-odata-service-cloud-foundry.html
Step 4: Execute an OData request

I try to replicate this tutorial but in the Step 4 I get the error message:

> get request failed!

when opening `http://localhost:8080/business-partners`. I've added a console.log  line in:

```typescript
    .catch(error => {
      console.log(error)
      res.status(500).send(error.message);
    })
```

the reason seems to be:

```
TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
```

So it might be the better option to use the Sandbox from SAP API Business Hub by using this:

```typescript
function getAllBusinessPartners(): Promise<BusinessPartner[]> {
  console.log('start getAllBusinessPartners')
  return BusinessPartner.requestBuilder()
    .getAll()
    .withCustomHeaders({'APIKey': '<Your API Key>'})
    .execute({
      url: 'https://sandbox.api.sap.com/s4hanacloud/'
    });
}
```

**Comment by gregorwolf** [comment]
Or when using dotenv:

```
function getAllBusinessPartners(): Promise<BusinessPartner[]> {
  console.log('start getAllBusinessPartners')
  return BusinessPartner.requestBuilder()
    .getAll()
    //.withCustomHeaders({'APIKey': 'FSYqegb0UsHA3fpylttczzOaRsUWAU5d'})
    .withCustomHeaders({ 'APIKey' : process.env.APIKey || ""})
    .top(10)
    .execute({
      destinationName: 'MockServer'
    });
}
```

**Comment by mr-flannery** [comment]
Hi @gregorwolf,

thanks for bringing the issue up and sorry for the delay.
Do you remember which version of the SDK you have used to produce this issue? The "technical part" of this issue is solved already, I think.
We will probably add the API Hub Sandbox as option in the blog post, thanks for the suggestion!

**Comment by gregorwolf** [comment]
Here is the dependencies section from my package.json:

```
  "dependencies": {
    "@sap/cloud-sdk-core": "^1.2.1",
    "@sap/cloud-sdk-vdm-business-partner-service": "^1.3.0",
    "express": "^4.16.4"
  }
```

**Comment by mr-flannery** [comment]
Can you try upgrading to `1.4.2`? This should get rid of the error.

**Comment by gregorwolf** [comment]
Thanks, the upgrade fixed it.

**Comment by socenmarc** [comment]
Hi everyone,

I get the same error reported by @gregorwolf some months ago:
`TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:`

The sdk versions in my package.json are:
`    "dependencies": {
        "@sap/cds": "^3.18.3",
        "@sap/cloud-sdk-core": "^1.11.3",
        "@sap/cloud-sdk-vdm-business-partner-service": "^1.11.3",`
My node_modules folder is up to date. 

I downgraded the sdk to 1.4.2 and the error still remains.

The complete stack trace:
`Error: get request failed!
    at Object.errorWithCause (/home/user/projects/s4n/node_modules/@sap/cloud-sdk-util/dist/error.js:14:20)
    at specializeError (/home/user/projects/s4n/node_modules/@sap/cloud-sdk-core/dist/request-builder/request/odata-request.js:175:32)
    at /home/user/projects/s4n/node_modules/@sap/cloud-sdk-core/dist/request-builder/request/odata-request.js:162:58
Caused by:
**TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"**
    at new ClientRequest (_http_client.js:119:11)
    at Object.request (http.js:42:10)
    at RedirectableRequest._performRequest (/home/user/projects/s4n/node_modules/follow-redirects/index.js:169:24)
    at new RedirectableRequest (/home/user/projects/s4n/node_modules/follow-redirects/index.js:66:8)
    at Object.wrappedProtocol.request (/home/user/projects/s4n/node_modules/follow-redirects/index.js:307:14)
    at dispatchHttpRequest (/home/user/projects/s4n/node_modules/axios/lib/adapters/http.js:180:25)
    at new Promise (<anonymous>)
    at httpAdapter (/home/user/projects/s4n/node_modules/axios/lib/adapters/http.js:20:10)
    at dispatchRequest (/home/user/projects/s4n/node_modules/axios/lib/core/dispatchRequest.js:59:10)`

Here is my source code, pointing to the sandbox:

`			const addresses = await BusinessPartnerAddress
				.requestBuilder()
				.getAll()
				.filter()
				.withCustomHeaders({
				         APIKey: 'Sj0ZX57deZZ0J1GPjchtQrAxgig7rBZz'
				})
				.top(10)
				.execute({
				          url: 'https://sandbox.api.sap.com/s4hanacloud'
				})
`
Thanks in advance.

BR,
Marc

**Comment by mr-flannery** [comment]
Hi Marc,

I tested this with the versions you've mentioned and cannot reproduce the issue. Could you quickly check which node version you're running (`node -v`)?

Thanks 
Dennis

**Comment by socenmarc** [comment]
Hi Dennis,

of course, it is v10.16.0

As additional information, I am using SAP Business Application Studio.

Thanks,
Marc

**Comment by mr-flannery** [comment]
Hmm, even with v10.16.0 I couldn't reproduce this... Can you try the following, just to make sure?
* set the versions of `core ` and `business-partner-service` back to `^1.11.3`
* delete your `package-lock.json`
* delete your `node_modules`
* run `npm install`
* execute your code again

**Comment by socenmarc** [comment]
Thank you very much for your support Dennis. 

I did it and the same error appears, unfortunately.

I've gone a little further with my tests:
- From SAP Business Application Studio, I uploaded my capm app to git.
- I cloned the app locally in my computer and ran: npm install + cds deploy + cds serve all. **The app worked without errors**. I'm running node v10.16.3 and VSCode as editor.
- I created a new dev space in SAP Business Application Studio. Then I cloned the app and ran: npm install + cds deploy + cds serve all -> **I get the error again**.  Here node v10.16.0 is running.

So there seems to be something wrong with SAP Business Application Studio and how it runs applications locally.

Regards,
Marc

**Comment by socenmarc** [comment]
Thank you Dennis!

**Comment by socenmarc** [comment]
Just to confirm my suspicions about incorrect behavior of SAP Business Application Studio running locally: I deployed the project in Cloud Foundry, and it works correctly.

**Comment by liatbor** [comment]
Hi Marc,
Are you using a real S/4 cloud system or a mock server?
There's a known issue connecting to a real S/4 cloud system using the cloud sdk and xsuaa that we will address soon in the application studio.

Thanks,
Liat

**Comment by socenmarc** [comment]
Hi Liat,
thank you so much for your answer. 
I am using a real S/4 cloud system, so it seems feasible that my problem is related to this issue that you are pointing out. At the moment I will use a mock server.
I will be attentive to the release notes of new releases, but I would really appreciate it if you could notify me when available.

Thanks,
Marc

**Comment by liatbor** [comment]
Hi Marc,
Sounds good.  :) Also, if you encounter issues with the mock server, let me know.
Thanks,
Liat
