### ISSUE TITLE
Use JPA in Custom Logic

### ISSUE THREAD

**Issue by MaximilienFourmyBeyond** [SAPDocuments/Tutorials#3582]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html

Is it possible to have a github repo with the final code ?
It would be very helpful to check and compare the code with ours.

**Comment by JijoRoyJacob** [comment]
Thank you Maximilien. We've noted your request and will take it into consideration when deciding the positioning of the whole JPA topic in the programming model.

**Comment by thecodester** [comment]
Thanks for the comment. For general questions like this -- not bugs in the tutorials -- feel free to use:

https://www.sap.com/community.html
https://answers.sap.com/index.html
