### ISSUE TITLE
Build and Deploy a Java Application

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3587]
Tutorial URL: https://developers.sap.com/tutorials/cp-java-reference-app-deploy.html

Please specify the step you are referring to Step 4: Bind the Application to a Database

Hello,

If I want to bind the Application to the Database i became the Error that 

"Problems registering HANA database for account 's0007042004trial' and id 'espm'. Application with name 'espm' already exists."

I think the System will create a database not a shema?

Regards

**Comment by simonarangelova** [comment]
Hello, 
Can you try creating a database with a name other than the application name (espm) e.g. espmDatabase.

Regards,
Simona

**Comment by marcobuescher** [comment]
Hi,

yes I made a new database but it has the same error...

Hm....

**Comment by simonarangelova** [comment]
Hello,
Do you have any other applications deployed in your trial account with the same name as the name of your database?
If not could you please send a screenshot of the error that you are getting.
Thanks and Regards,
Simona

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
