### ISSUE TITLE
Error: "MOVIELENS": schema is not owned by _SYS_REPO in movielense_user

### ISSUE THREAD

**Issue by pgupta4sap** [SAPDocuments/Tutorials#3589]
Hi,

I am  facing one issue in Tutorial below link:
https://developers.sap.com/tutorials/cp-hana-aa-movielens-01.html
Getting error message  "MOVIELENS": schema is not owned by _SYS_REPO. 
I have logged in as MOVIELENSE_USER in development workbench editor. While creating package data, hdb, service do i need to enter any value for Responsible ?
I have logged in with MOVIELENS_USER, but not able to identify the root cause.
@adadouche @saphanaacademy

![error](https://user-images.githubusercontent.com/51327339/58814710-dc644380-8643-11e9-982a-c4d4477b4312.PNG)

**Comment by adadouche** [comment]
Hi @pgupta4sap ,

Can you switch to the Catalog view, and verify if the MOVIELENS schema exists?

Can you also share what content you have in the  MOVIELENS.hdbschema file?

Thanks

**Comment by adadouche** [comment]
Hi @pgupta4sap,

I haven't heard from you so I'll assume that the provided details helped you solve the issue. If not, please reopen the issue.

Regards

@bdel
