### ISSUE TITLE
Configure your ABAP System to Activate OData Services of Fiori Reference Apps

### ISSUE THREAD

**Issue by ND3V** [SAPDocuments/Tutorials#3590]
Tutorial URL: https://developers.sap.com/tutorials/cp-connectivity-configure-fiori-reference-apps.html

Please specify the step you are referring to 

Step 3: SAP_EPM_REF_APPS_BASIC_AUTH is not available as role in my system. Any Idea on why that might be? prerequesites have been done.

Step 4: SEPMRA_SO_MAN not available in IWFND/MAINT_SERVICE (also not for manual adding) has it been renamed to SEPMRA_PO_MAN?

**Comment by JensHaley** [comment]
Could please share your ABAP release of your system? The objects might not be available in older systems.

Thank you

**Comment by ND3V** [comment]
Forgive - holiday. Its Release 750 SP 4 (We are talking SAP_BASIS & SAP_ABA. If theres more i can provide let me know)

**Comment by JensHaley** [comment]
Sorry, I missed your reply - I was told that role SAP_EPM_REF_APPS_BASIC_AUTH should be available for all ABAP systems as of Release 750.

I'll check with the colleagues for the Fiori Reference apps if that role can be imported into the system from somewhere.

**Comment by thecodester** [comment]
@JensHaley Any update here?

**Comment by JensHaley** [comment]
@ND3V : 
Apologies for the late reply. I tried to check several times with the colleagues about the role. 

Apparently there is no capacity to provide the role by other means than though a regular support package. The only way I see to solve this is to update your 750 system to a higher support package.

Unfortunately, I do not know as of which SP the role was included.
Sorry for the inconvenience.

**Comment by thecodester** [comment]
I am closing the issue. If you need additional information, please consider continuing the discussion in the SAP Community or in the SAP Questions & Answers.

https://www.sap.com/community.html
https://answers.sap.com/index.html
