### ISSUE TITLE
Create a Workflow Definition Using an External Service

### ISSUE THREAD

**Issue by thecodester** [SAPDocuments/Tutorials#3591]
Tutorial URL: https://developers.sap.com/tutorials/cp-wf-01-create-definition.html

Please specify the step you are referring to: Step 7

You show when clicking on the service the JSON so nicely formatted. But when I click I just get a run-on text that is not formatted nicely. Should I open the link in a different way, different browser?

**Comment by qmacro** [comment]
You can add a browser extension if you want it nicely formatted. I've added a note to the tutorial text accordingly.
