### ISSUE TITLE
SAP HANA XS Advanced - Modules within Node.js SAP HANA applications

### ISSUE THREAD

**Issue by Fermartyni** [SAPDocuments/Tutorials#3596]
Tutorial URL: https://developers.sap.com/tutorials/xsa-node-modules.html

At the last step: when I run the application, it fails:

Application is running
> core@1.0.0 start /home/vcap/app
> node server.js
module.js:550
throw err;
^
Error: Cannot find module '@sap/xssec'
at Function.Module._resolveFilename (module.js:548:15)
at Function.Module._load (module.js:475:25)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object.initExpress (/home/vcap/app/utils/initialize.js:7:15)
at Object.<anonymous> (/home/vcap/app/server.js:16:16)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
npm
ERR! code ELIFECYCLE
npm ERR!
errno 1
npm
ERR! core@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the core@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /home/vcap/app/.npm/_logs/2019-06-04T11_59_46_437Z-debug.log

Seems like there is a lack of dependencies between all the libraries added in initialize.js and the ones added in package.json

**Comment by Lsubatin** [comment]
Thanks for the note. The dependencies for this track will be reorganized to include this.

**Comment by jmalla** [comment]
HI Lucia,
I ran into the same problem.  Also the tutorial from Craig refers to your tutorial but then it's not the same - I think it's referencing a different version than the latest one you have.

**Comment by jung-thomas** [comment]
This tutorial has been completely updated and tested on HANA Express 2.0 SPS 04. This issue has been resolved with the update. Sorry for the inconvenience.

**Comment by Fermartyni** [comment]
Many thanks Thomas!
