### ISSUE TITLE
Getting Started with the SAP Web IDE Full-Stack Version (Trial)

### ISSUE THREAD

**Issue by timrehrmann** [SAPDocuments/Tutorials#3597]
Tutorial URL: https://developers.sap.com/tutorials/webide-innovation-beta.html

Link to "Try It Out: 3 Easy Steps to Get You Started With the Cloud Foundry Environment" in step 4 doesn't work.

**Comment by greg2git** [comment]
Agreed, the link in Step 4 (https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/e3d82674bd68448eb85198619aa99b6d.html?q=Get%20a%20Trial%20Space%20on%20the%20Cloud%20Foundry%20Instance) returns this: https://saphelp.hana.ondemand.com/page-not-found.html

**Comment by ShiraManas** [comment]
Hi all,
The link in Step 4 has been updated and is working. 

Thanks,
Shira
