### ISSUE TITLE
Get Ready to Develop on Your Local Machine

### ISSUE THREAD

**Issue by mjhcorporate** [SAPDocuments/Tutorials#3598]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-sapui5-local-setup.html

Please specify the step you are referring to: Step 4

I think the provided ansers are wrong. According to my console, the supported commands of mbt are (this is the output of mbt --help):

Available Commands:
  assemble    Assembles MTA Archive
  build       Execute MTA project build
  gen         Generation commands
  help        Help about any command
  init        generates Makefile
  validate    MBT validation

Through trial and error, I found out the accepted ansers are "assemble, init". When I also place a checkmark at "build", then my answer is rejected.

**Comment by IObert** [comment]
Good catch @mjhcorporate 
Thanks for your feedback!
