### ISSUE TITLE
Use Mobile Services to Create UI

### ISSUE THREAD

**Issue by erichnunez** [SAPDocuments/Tutorials#3600]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-create-ui.html

Please specify the step you are referring to

I am stuck while getting data in the Use Mobile Services to Create UI section. Following URL is not working... Query is not getting any results.

/<yourP#>trial/s4hanacloud/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder?$expand=to_Item nor /<yourP#>trial/s4hanacloud/sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder?$expand=to_Item&$format=json. 

Does anyone has any idea to make sure it is working....

**Comment by shilpavij** [comment]
Dear,
Please check the space after A_SalesOrder?.
![image](https://user-images.githubusercontent.com/44152823/59010329-80213f80-884e-11e9-8091-85c7184e84de.png)

Regards
Shilpa

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
