### ISSUE TITLE
 Rapid

### ISSUE THREAD

**Issue by zzdjb** [SAPDocuments/Tutorials#3601]
Tutorial URL: https://developers.sap.com/tutorials/mendix-salesorders.html

Please specify the step you are referring to

**Comment by thecodester** [comment]
Do you have a question?

**Comment by zzdjb** [comment]
![image](https://user-images.githubusercontent.com/50519079/59015968-cdafa380-8872-11e9-9556-51da6c428a3f.png)
Step 12: Run locally

**Comment by Paolaufer** [comment]
Hi,
I am sorry but I do not understand the question. Could you please rephrase?

**Comment by zzdjb** [comment]
Thanks,I've solved it,importing Atlas_UI_Resources.
