### ISSUE TITLE
Add a User Task to Your Workflow

### ISSUE THREAD

**Issue by dazowens** [SAPDocuments/Tutorials#3605]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-add-usertask.html

Please specify the step you are referring to

when selecting Monitor Workflows in Step 2 the following message is displayed:

Error
App could not be opened because the SAP UI5 component of the application could not be loaded.
Failed to load UI5 component for navigation intent "#bpmworkflowmonitor-DisplayDefinitions"

Here is the console entry:

2019-06-06 20:12:28.834580 The issue is most likely caused by application com.sap.bpm.monitorworkflow. Please create a support incident and assign it to the support component of the respective application. - Failed to load UI5 component with properties: '{
    "name": "com.sap.bpm.monitorworkflow",
    "url": "/sap/fiori/bpmworkflowmonitor/",
    "manifest": "/sap/bc/lrep/content/~1541669202009~/apps/com.sap.bpm.monitorworkflow/app/wfs/bpmworkflowmonitor/sv/1.26.0/manifest.appdescr",
    "self": {
        "name": "com.sap.bpm.monitorworkflow",
        "url": "/bpmworkflowmonitor/"
    },
    "asyncHints": {
        "libs": [
            {
                "name": "sap.uxap",
                "lazy": false
            },
            {
                "name": "sap.ui.layout",
                "lazy": false
            },
            {
                "name": "sap.ui.codeeditor",
                "lazy": false
            },
            {
                "name": "sap.m",
                "lazy": false
            },
            {
                "name": "sap.suite.ui.commons",
                "lazy": false
            }
        ],
        "components": [],
        "requests": [
            {
                "name": "$sap.ui.fl.changes",
                "reference": "com.sap.bpm.monitorworkflow.Component",
                "version": {
                    "major": 1,
                    "minor": 26,
                    "patch": 0
                }
            }
        ],
        "preloadBundles": [
            "sap/fiori/core-ext-light-0.js",
            "sap/fiori/core-ext-light-1.js",
            "sap/fiori/core-ext-light-2.js",
            "sap/fiori/core-ext-light-3.js"
        ],
        "waitFor": []
    },
    "version": {
        "major": 1,
        "minor": 26,
        "patch": 0
    },
    "messages": [
        {
            "severity": "error",
            "text": "App 'com.sap.bpm.monitorworkflow' has errors and will possibly not run properly"
        },
        {
            "severity": "error",
            "text": "Error in application dependency 'sap.uxap': 'The descriptor was not found in the specified version'"
        },
        {
            "severity": "error",
            "text": "Error in application dependency 'sap.ui.layout': 'The descriptor was not found in the specified version'"
        },
        {
            "severity": "error",
            "text": "Error in application dependency 'sap.ui.codeeditor': 'The descriptor was not found in the specified version'"
        },
        {
            "severity": "error",
            "text": "Error in application dependency 'sap.m': 'The descriptor was not found in the specified version'"
        },
        {
            "severity": "error",
            "text": "Error in application dependency 'sap.suite.ui.commons': 'The descriptor was not found in the specified version'"
        }
    ],
    "technology": "UI5",
    "html5AppName": "bpmworkflowmonitor",
    "siteId": "985c2c93-68a3-469b-9c8b-2b5b2b32480b",
    "appId": "c5b446b7-0a70-4f05-8275-b4d4a7d9af3a-1489316330750",
    "id": "application-bpmworkflowmonitor-DisplayDefinitions-component",
    "componentData": {
        "startupParameters": {
            "hcpApplicationId": [
                "985c2c93-68a3-469b-9c8b-2b5b2b32480b:c5b446b7-0a70-4f05-8275-b4d4a7d9af3a-1489316330750"
            ]
        },
        "technicalParameters": {}
    },
    "async": true
}'. Error likely caused by:
Error: resource undefined could not be loaded from /sap/bc/lrep/content/~1541669202009~/apps/com.sap.bpm.monitorworkflow/app/wfs/bpmworkflowmonitor/sv/1.26.0/manifest.appdescr?sap-language=EN. Check for 'file not found' or parse errors. Reason: 
    at Object.error (https://sapui5.hana.ondemand.com/1.66.0/resources/sap/fiori/core-min-1.js:104:2155)
    at p (https://sapui5.hana.ondemand.com/1.66.0/resources/sap/fiori/core-min-3.js:441:25152)
    at Object.fireWith [as rejectWith] (https://sapui5.hana.ondemand.com/1.66.0/resources/sap/fiori/core-min-3.js:441:26003)
    at h3 (https://sapui5.hana.ondemand.com/1.66.0/resources/sap/fiori/core-min-3.js:441:77625)
    at XMLHttpRequest.<anonymous> (https://sapui5.hana.ondemand.com/1.66.0/resources/sap/fiori/core-min-3.js:441:81379)
    at s.E.dispatch (https://flpportal-s0004124381trial.dispatcher.hanatrial.ondemand.com/cloud/flp/3.87.1/runtime/sap/hana/uis/flp/library-preload.js?eval:499:2673)
    at XMLHttpRequest.X.handleEvent (https://flpportal-s0004124381trial.dispatcher.hanatrial.ondemand.com/cloud/flp/3.87.1/runtime/sap/hana/uis/flp/library-preload.js?eval:499:3994)
    at XMLHttpRequest.h [as _fnHandler] (https://flpportal-s0004124381trial.dispatcher.hanatrial.ondemand.com/cloud/flp/3.87.1/runtime/sap/hana/uis/flp/library-preload.js?eval:499:4253) com.sap.bpm.monitorworkflow

I hope you can help me with this issue.  Thanks Daz

**Comment by oleg-duvanayev** [comment]
i have the same issue. Do anybody know how to solve it ?
br

**Comment by thecodester** [comment]
@AstridHerbst Can you answer?

**Comment by AstridHerbst** [comment]
Hi, 

Please see the new tutorials at: https://developers.sap.com/group.cp-workflow-cf.html 

Best regards,
Astrid
