### ISSUE TITLE
Installing XS CLI Client

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#3606]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-xs-xli-client.html

There is no step that describes to add the bin folder to the PATH environment variable.

**Comment by JCurrie27** [comment]
Thanks for this feedback. This issue is being investigated and we'll respond as soon as we can.

**Comment by JCurrie27** [comment]
Apologies for the delay, Our team has recommended the following steps:

Add the client bin path to the system execute PATH after step “Step 3: Install the XS CLI client.”

For example, untar the xs client package in /untar_dir on linux and c:\untar_dir on windows,
•	for linux ppcle and mac : run “export PATH=$PATH:/untar_dir/bin”
•	for windows add c:\untar_dir\bin to Path in System variables.  (after you add the system variables you should restart your command to make it take effect)

This information will be added to the [https://developers.sap.com/tutorials/hxe-ua-install-xs-xli-client.html]( https://developers.sap.com/tutorials/hxe-ua-install-xs-xli-client.html) tutorial shortly.
