### ISSUE TITLE
SAP HANA XS Advanced, Creating an HTML5 Module

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#3607]
Tutorial URL: https://developers.sap.com/tutorials/xsa-html5-module.html

Step 2: Create the UAA service instance for your application

For the alternative option to add the UAA using the command line it might be good to have a concrete example that works with HXE:

```
xs login -a https://hxehost:39030 -o HANAExpress -s development -u XSA_ADMIN --skip-ssl-validation
```

**Comment by Lsubatin** [comment]
pushed to prod. Thanks Gregor!
