### ISSUE TITLE
Use the Object Detection API from a REST Client

### ISSUE THREAD

**Issue by zerghector** [SAPDocuments/Tutorials#3608]
Tutorial URL: https://developers.sap.com/tutorials/cp-mlf-rest-img-object-detection.html

HI, In the step 2, when calling the API, it appeared a error code message #308, I thought it was the serever, however it appeared again with the HUMAN RECOGNITION,

How could I fix it?

Thank you!!!!

**Comment by adadouche** [comment]
Hi @zerghector ,

The HTTP code 308 is related to a Permanent Redirect message.

Can you check is you properly configured Postman as described in step from here: https://developers.sap.com/tutorials/api-tools-postman-install.html

![image](https://user-images.githubusercontent.com/1446764/59431528-69965d80-8de5-11e9-9bd5-e59d57b44194.png)
 

Thanks

@bdel

**Comment by adadouche** [comment]
Hi @zerghector ,

I haven't heard from you so I'll assume that the provided details helped you solve the issue. If not, please reopen the issue.

Regards

@bdel
