### ISSUE TITLE
Explore and Customize Your SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by reenumaryjose** [SAPDocuments/Tutorials#3611]
Tutorial URL: https://developers.sap.com/tutorials/webide-customize.html

Please specify the step you are referring to: Step 4: Learn about SAP Web IDE

Correction: 
There is no 4th tab (hat icon) to the Learning Center in the side panel. It is only available in Home page. Screenshot below

![WebIDE](https://user-images.githubusercontent.com/47062869/59182594-c5fc4180-8b87-11e9-8066-5e45036168ce.PNG)
Thanks,
Mary

**Comment by Paolaufer** [comment]
Hi,
You are right, we have removed the Learning Center. You can still access the videos that were there previously in our YouTube page.
https://www.youtube.com/channel/UCgScBj_AEGo_mI5accM4XhA

Thank you for pointing this out to us. We will make sure to update the tutorial.

**Comment by thecodester** [comment]
Tutorial has been updated.
