### ISSUE TITLE
Create an API Provider System

### ISSUE THREAD

**Issue by VishnAndr** [SAPDocuments/Tutorials#3613]
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-create-provider.html

Please specify the step you are referring to
in Step 1 question "Where do you discover and consume Products that contain API Proxies?" expects free text answer. However, whatever I tried to enter - didn't work. Apparently, the answer should contain "Dev portal". But it's not really clear what exactly it expects us to enter.

**Comment by VishnAndr** [comment]
Agh, not Dev portal, but "Developer Portal".....

**Comment by VivianMS** [comment]
Thank you.
