### ISSUE TITLE
Use JPA in Custom Logic

### ISSUE THREAD

**Issue by mojitodaiquiri** [SAPDocuments/Tutorials#3616]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html

Please specify the step you are referring to 
Step 4: Change the runtime from Tomcat to TomEE

Hi, I cannot make it work after changing the application server to TomEE
I've got this error, any idea?

{
   "written_at":"2019-06-11T12:53:37.255Z",
   "written_ts":1612050934513860,
   "component_type":"application",
   "component_id":"61b04f12-fe6d-41a4-b524-c8f1a76ef26c",
   "space_name":"dev",
   "component_name":"5q7lPJIFxgXfMpfc-bookshop-srv",
   "component_instance":"0",
   "organization_id":"-",
   "correlation_id":"-",
   "organization_name":"-",
   "space_id":"7db971e0-be06-4dcd-81da-06904695f9b8",
   "container_id":"10.0.138.251",
   "type":"log",
   "logger":"com.sap.cloud.sdk.service.prov.v2.rt.core.web.ServletListener",
   "thread":"localhost-startStop-1",
   "level":"ERROR",
   "categories":[

   ],
   "msg":"No UserContext Class Found, Fallback to properties file"
}

**Comment by JijoRoyJacob** [comment]
Can you share your code? I can take a look to see where the problem is.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
