### ISSUE TITLE
Use abapGit to Transform ABAP Source Code to the Cloud

### ISSUE THREAD

**Issue by DerGuteWolf** [SAPDocuments/Tutorials#3617]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-abapgit.html

Tutorial is missing information how to add/commit code from the cloud abap system to the local git repo and push to the remote repo.

**Comment by mervey45** [comment]
Hi @DerGuteWolf, 

thank you for your comment. We will update this tutorial. 

Best regards, 
Merve

**Comment by thecodester** [comment]
@mervey45  Has tutorial been updated? Can we close issue?

**Comment by mervey45** [comment]
I'll update this asap.

**Comment by mervey45** [comment]
@DerGuteWolf The push feature is available in 1911. That's why it hasn't been in this tutorial. With 1911 this tutorial will be updated, so we can close this issue.
