### ISSUE TITLE
Add a Database to Your Business Application

### ISSUE THREAD

**Issue by gutknechts** [SAPDocuments/Tutorials#3618]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-03-add-database.html

Please specify the step you are referring to: "Step 5: Re-build the db module and run the app"

When building the DB, I get the following error:

5:06:06 PM (Executor) Build command failed : Build failed: Failed during post build event: Failed to create JSON from build log: json: cannot unmarshal string into Go struct field BuilderLog.level of type int
5:06:06 PM (Executor) The "task for hdb build" process finished with code 1
5:06:06 PM (Executor) Build of /bookshop/db failed.

**Comment by renejeglinsky** [comment]
@gutknechts The issue is fixed. Please try again.
I had to go into my space and delete the app _hdispacedeploy<GUID_NUMBER>_ and then it worked.
