### ISSUE TITLE
Export Data to OneDrive or GDrive ?

### ISSUE THREAD

**Issue by AmauryVanEspen** [SAPDocuments/Tutorials#3621]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-ms-graph-export-drive.html

Regarding interface with OneDrive,
Does it work with GDrive or how could you set up a GDrive (spreadsheet) connector ?

Thank you

Amaury

**Comment by IObert** [comment]
Hi @AmauryVanEspen,

good question. The tutorial only focusses on the Microsoft SDK, so you cannot simply replace the OneDrive part with GDrive. Having said that, the flow for GDrive probably follows the same principles. First, you need to acquire a token and then you can use this token to[ upload a file to GDrive](https://developers.google.com/drive/api/v3/manage-uploads).
