### ISSUE TITLE
Create a Business Service Using CDS

### ISSUE THREAD

**Issue by iwonahahn** [SAPDocuments/Tutorials#3623]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-01-create-business-service.html

In step 3, please remove step 1 & 2, since a rename is no longer necessary because the file in the template is already called cat-service.cds.

Thanks and best regards,
Iwona

**Comment by renejeglinsky** [comment]
Thanks @iwonahahn I'll take care of that.

**Comment by renejeglinsky** [comment]
@iwonahahn The issue is fixed. Thanks :)
