### ISSUE TITLE
Create a Workflow Project from a Template

### ISSUE THREAD

**Issue by RobertVit** [SAPDocuments/Tutorials#3624]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-create-project.html

Step 2.4: there is no Category "Business Process Management"
![image](https://user-images.githubusercontent.com/3217350/59433329-9482b080-8de9-11e9-8629-6bf6b54e8270.png)

**Comment by AstridHerbst** [comment]
Hi Robert,

Have you enabled the services and extensions as described in the first tutorial "Prepare to Create Workflows in SAP Cloud Platform"?

Best regards,
Astrid

**Comment by RobertVit** [comment]
Hi Astrid,
yes i did.
For me also the Workflow Service comes within Orchestration, not Integration
![image](https://user-images.githubusercontent.com/3217350/60003010-184e5f80-966a-11e9-97bd-cc163f36890c.png)

Best regards
Robert

**Comment by AstridHerbst** [comment]
Hi Robert,

I see that the Workflow service itself is enabled. There is an option to enable the workflow extension inside the Web IDE. Have you set that one, too?

![step5-enablewf](https://user-images.githubusercontent.com/18418519/60012500-6a987c00-967c-11e9-98c8-a1c68b844902.PNG)

Regards,
Astrid

**Comment by RobertVit** [comment]
Hi Astrid,
thanks, that's it - complicated but works....

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
