### ISSUE TITLE
Set Up Your Local Infrastructure to Develop with SAP Cloud SDK

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#3629]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-setup.html

Step 1: Prepare the Infrastructure

Perhaps SAP could promote it's own OpenJDK distribution [SapMachine](http://sapmachine.org)

**Comment by Emdee89** [comment]
Hi Gregor, thanks for the suggestion. We are currently investigating your proposal.

**Comment by Emdee89** [comment]
Hi Gregor,

the SAP Cloud SDK relies on Java 8. SapMachine does not support Java 8.

Thanks
Marco
