### ISSUE TITLE
Build a Shopping Fresh Fiori App in SAPUI5

### ISSUE THREAD

**Issue by bstk0** [SAPDocuments/Tutorials#3630]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-create-fioriapp.html

Please specify the step you are referring to
Item 7 - I got the message "The application cannot be subscribed to product eCommerceProduct using service 'salesTrackerAPI'. Please contact your System Administrator."

What should I do? Thanks

**Comment by shilpavij** [comment]
Dear,
Looks like a problem with your dev portal destination. For me, it works.

I have updated the destination part. Can you adopt it in your flow and check again.
If still, it does not work please select the destination type as basic and give your credentials and check.

Regards
Shilpa

**Comment by bstk0** [comment]
Hi 

> Dear,
> Looks like a problem with your dev portal destination. For me, it works.
> 
> I have updated the destination part. Can you adopt it in your flow and check again.
> If still, it does not work please select the destination type as basic and give your credentials and check.
> 
> Regards
> Shilpa

Hi Shilpa. thank you for your support!

I've changed the authentication of "apimgmtdevportal" destination to "BasicAuthentication" and now when I try to define a Destination for Fiori App I got the message: 
"_API is subscribed to product eCommerceProduct. Unable to get medatada of selected server or API. Please contact your System Administrator._"

Any idea?

Best Regards

**Comment by bstk0** [comment]
Hi Shilpa,
The error may be some Internet connection problem because the ES5 connection was too slow.
I left the connection authentication as basic. 

Thank you very much!

**Comment by rajyeswar** [comment]
I am struggling with this issue. How is this resolved?

**Comment by Prof-Greipl** [comment]
Same here...

**Comment by shilpavij** [comment]
Dear All,

In this case please check your backend. I cross-checked again from ES5 it works fine for me.
Can you please elaborate on which issue you mean here?

Regards
Shilpa

**Comment by Prof-Greipl** [comment]
Pls. give me moment…

Von: Shilpa Vij <notifications@github.com>
Gesendet: Dienstag, 4. August 2020 11:32
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Greipl Dieter <dieter.greipl@haw-landshut.de>; Comment <comment@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Build a Shopping Fresh Fiori App in SAPUI5 (#3630)


Dear All,

In this case please check your backend. I cross-checked again from ES5 it works fine for me.
Can you please elaborate on which issue you mean here?

Regards
Shilpa

**Comment by Prof-Greipl** [comment]
Shilpa, thx.  My bad, as the credentials to the ES5  backend where invalid due to too many false logins. I can continue and will hopefully finalize the Fiori-app in the next hour...

**Comment by Prof-Greipl** [comment]
Shilpa, thx -  i finished the tutorial. No more issues...

**Comment by shilpavij** [comment]
Thank you for the confirmation. Glad to know that you were able to finish the tutorial

Regards
Shilpa
