### ISSUE TITLE
Build a Shopping Fresh Fiori App in SAPUI5

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3631]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-create-fioriapp.html

Please specify the step you are referring to Step 3,

hello, if I try to set up the data Connection, i get the errror "The application cannot be subscribed to product eCommerceProduct using Service 'salestrackerapi'. Please contakt your System adminstrator.

Have you any Idea?

**Comment by shilpavij** [comment]
Dear,
Looks like a problem with your dev portal destination. For me, it works.

I have updated the destination part. Can you adopt it in your flow and check again.
If still, it does not work please select the destination type as basic and give your credentials and check.

Regards
Shilpa

**Comment by marcobuescher** [comment]
Hello, 

if I check the connection I became the Information:

apimgmt_proxy
 Connection to "apimgmt_proxy" established. Response returned: "404: Not Found"
The same with basic aut.

And with apimgmtdevportal:
Connection to "apimgmtdevportal" established. Response returned: "200: OK"

**Comment by shilpavij** [comment]
This is completely fine, for me also the same, please go ahead and complete the next steps.

Regards
Shilpa

**Comment by marcobuescher** [comment]
Yes, and now, if I want to make the Data Connection now, there is the error.. The application cannot be subscribed to product eCommerceProduct using Service 'salestrackerapi'. Please contakt your System adminstrator.

**Comment by marcobuescher** [comment]
By the Way, the "Done"button did not Work at tutorial 3... But the tutorial at all is really cool! thanks for that!

**Comment by thecodester** [comment]
Thanks for compliments.

What do you mean it did not work. I just now pressed all 4 steps and they all completed.

**Comment by marcobuescher** [comment]
ok, my mistake, i wrote tutorial 3. I meant part three of the mission: Discover and Manage Third-Party HERE Maps API from SAP API Business Hub https://developers.sap.com/tutorials/cp-apim-shoppingfresh-discover-location-apis.html  Maybe I should have mentioned it in a new ticket.

**Comment by thecodester** [comment]
In that tutorial there is no DONE button, only a question with a Submit Answer button, and it works for me.

![image](https://user-images.githubusercontent.com/11659786/59750307-4822ef00-9287-11e9-9f8c-56a6c051dd0a.png)

**Comment by marcobuescher** [comment]
Hello,

yes I see that today the input of the buttons is saved. That was different yesterday or the day before yesterday. Please do not misunderstand, I do not want to nag. I really like the tutorials ... The confirmation that the tutorial is done is currently not passed through to me with the overview?
![Unbenannt](https://user-images.githubusercontent.com/10000063/59750949-edd26000-927f-11e9-9605-cf563395ab96.JPG)

**Comment by marcobuescher** [comment]
Hello,
the tutorial can still not be finished. The technique does not realize that the part "Discover and Manage Third-Party HERE MAps API from API Business Hub" is finished. So the counter stops at 88

**Comment by thecodester** [comment]
@apilets I completed the tutorial and it shows in the tutorial that it was completed, but in the mission it does not show completion (even though other tutorials in the mission show completion). Can you check?

**Comment by thecodester** [comment]
Sorry we dropped this. @marcobuescher Are you still missing the validation?

**Comment by marcobuescher** [comment]
I´m sorry, it is too long ago now, I think about more than six Month. I had to made it new from the ground up.  Please close the Ticket.

**Comment by dattu34** [comment]
I am facing the similar issue. Does anyone solved this

**Comment by rajyeswar** [comment]
I am struggling with this issue. How is this resolved?
