### ISSUE TITLE
Use the ESPM to Manage Orders and Stock Information

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3632]
Tutorial URL: https://developers.sap.com/tutorials/cp-java-reference-app-manage-orders.html

Please specify the step you are referring to Step 1,

hello I cant check out the Notebook, I became the Information "Check your Input and try again".

Regards

**Comment by simonarangelova** [comment]
Hello, 

Can you perform a fresh deployment, as it is working from our side.

Thanks.
Regards,
Simona

**Comment by marcobuescher** [comment]
I stet up a new Database and a new Binding etc... I cant check out... Wich Credit Card had I to Use?

**Comment by simonarangelova** [comment]
Hello,

There is no need for any card at all. This is a reference application that shows the capabilities of SAP Cloud Platform. 
The tutorial you are referring to only aims to demonstrate how you can create a sales order, how to approve it, and how to update stock information.

Regards,
Simona

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
