### ISSUE TITLE
Create a Cloud Foundry Account

### ISSUE THREAD

**Issue by jitendrakansal** [SAPDocuments/Tutorials#3634]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-create-account.html

hyperlink in step#3 navigates to an empty page
(check to be certain it has the services you want before selecting it.) https://help.sap.com/doc/aa1ccd10da6c4337aa737df2ead1855b/Cloud/en-US/3b642f68227b4b1398d2ce1a5351389a.html?3b642f68227b4b1398d2ce1a5351389a.html

**Comment by IObert** [comment]
Hi @jitendrakansal,

the link seems to work for me. It might have been a temporary issue.
Please reopen if the link is still dead for you.
