### ISSUE TITLE
Discover and Manage Third-Party HERE Maps API from SAP API Business Hub

### ISSUE THREAD

**Issue by valentini50** [SAPDocuments/Tutorials#3636]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-discover-location-apis.html

Please specify the step you are referring to

**Comment by valentini50** [comment]
Good Morning.
Tutorial:
Build an SAP Fiori App with SAP API Management
Issue 1:
Step: Discover and Manage Third-Party HERE Maps API from SAP API Business Hub
Same time completed all steps counts only as 25% complete

Issue 2:
Step: Discover and Manage Third-Party HERE Maps API from SAP API Business Hub
Even though it was completed it does not appear in the final score

With these problems I completed the tutorial, but only conts like 75% complete

**Comment by thecodester** [comment]
There is one step int hat tutorial. Do you see it as completed -- checkmark in the step or tutorial icon? Maybe post an image. Where do you see 25% or 75%?

**Comment by thecodester** [comment]
If you are speaking of this tutorial -- https://developers.sap.com/tutorials/cp-apim-shoppingfresh-create-fioriapp.html -- then the DONE button for one of the steps was missing so you could only complete 3 of 4 steps (75%). But now we added the extra DONE button and you can complete. I assume this is the issue you mean.

**Comment by valentini50** [comment]
Good Morning.
I will try to explain more in detail.
1) Step: Discover and Manage Third-Party HERE Maps API from SAP API Business Hub.
Mest having completed, does not count in the overall score.
![step 1](https://user-images.githubusercontent.com/38915450/59605662-a6b06780-90e5-11e9-8fb4-9745e56ccd0f.png)

1) Step: Build a Shopping Fresh Fiori App in SAPUI5
It only has 25% complete, but I completed the whole tutorial.
![step 2](https://user-images.githubusercontent.com/38915450/59605828-09a1fe80-90e6-11e9-851f-be798ac70a8b.png)

Even completing everything, it's not like 100%

**Comment by valentini50** [comment]
Good Morning.
The problem still persists even though
does not complete the 100%.
Any position on the solution?

**Comment by thecodester** [comment]
@lpareek Can you help here?

**Comment by valentini50** [comment]
Good Morning.
What I need to know is when will the tutorial problem be solved ?:
Already complete all steps is still not change to 100% complete.
Below print of the evidence, Any doubts about the problem? It was clear?
I'm waiting, thanks.
![erro percentual](https://user-images.githubusercontent.com/38915450/60256642-5042e600-98a8-11e9-9aeb-f9201e5123ab.png)

**Comment by thecodester** [comment]
Can you clear cache and go to the page again? I think that in our backend you are credited with finishing the tutorial, but there is a bug on client side (which we are fixing)?

**Comment by valentini50** [comment]
Good afternoon.
I have performed the requested procedures and the problem continues.

De: Daniel Wroblewski [mailto:notifications@github.com]
Enviada em: sábado, 29 de junho de 2019 15:16
Para: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Carlos Alberto Valentini <Carlos.Valentini@t-systems.com.br>; Author <author@noreply.github.com>
Assunto: Re: [SAPDocuments/Tutorials] Discover and Manage Third-Party HERE Maps API from SAP API Business Hub (#3636)


Can you clear cache and go to the page again? I think that in our backend you are credited with finishing the tutorial, but there is a bug on client side (which we are fixing)?

**Comment by valentini50** [comment]
Good afternoon.
I have performed the requested procedures and the problem continues.

**Comment by apilets** [comment]
Hello, @valentini50 
Could you please try to clear local storage in Chrome and then refresh the page?

**Comment by valentini50** [comment]
Good Morning.
The problem still persists.
I did the requested procedures, cleaned the cache of Chrome, I used other browsers (Mozila, IE), I tested in another machine and still continues as attached.
Does not complete and completes the 100%

![Erro](https://user-images.githubusercontent.com/38915450/60800322-658efe80-a14b-11e9-84c2-19414121d9d0.png)

**Comment by thecodester** [comment]
I think Andrei means to open the page in Chrome, open the Dev Tools, go to Application tab, and click Clear storage.

**Comment by valentini50** [comment]
Good morning, I already did that, I even tested it on another machine.

**Comment by thecodester** [comment]
@apilets Ball's in your court ... any help is appreciated :-)

**Comment by MichaelCzcz** [comment]
Hello @valentini50, does the problem still exist or did you get your badge in the meantime?

**Comment by valentini50** [comment]
Good Morning.
Problem solved, thanks.

De: Michael Czadankiewicz [mailto:notifications@github.com]
Enviada em: quarta-feira, 19 de fevereiro de 2020 09:01
Para: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Carlos Alberto Valentini <Carlos.Valentini@t-systems.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [SAPDocuments/Tutorials] Discover and Manage Third-Party HERE Maps API from SAP API Business Hub (#3636)


Hello @valentini50<https://github.com/valentini50>, does the problem still exist or did you get your badge in the meantime?
