### ISSUE TITLE
Publish and Receive MQTT Messages

### ISSUE THREAD

**Issue by soschlegel** [SAPDocuments/Tutorials#3637]
Tutorial URL: https://developers.sap.com/tutorials/abap-connectivity-mqtt.html

I miss the input field at Step 7 "Test your Program" of the Tutorial... :-(

**Comment by thecodester** [comment]
@MoellJ I don't see this tutorial in QA and therefore the validation step could not be created. Can you check this out?

**Comment by MoellJ** [comment]
@thecodester It seems like you deleted it in commit 1578c5fba03f746293b2735af390019aed639ce1 I'll see if I can fix it

**Comment by thecodester** [comment]
@soschlegel This is now fixed so you can complete the tutorial. Let me know if all is OK.
