### ISSUE TITLE
Testing API Business Hub APIs with Curl

### ISSUE THREAD

**Issue by thiengom** [SAPDocuments/Tutorials#3638]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-test-locally.html

Please specify the step you are referring to.

We are at step 3 run sample with CURL however the address https://sandbox.api.sap.com seems unreachable.

**Comment by mhassett92** [comment]
Apologies for the long delay. It looks like the authentication scheme was changed. I have alerted the product team and hope to have an update soon.

Thank you for your patience!

**Comment by mhassett92** [comment]
The authentication issue has been resolved by the API management team. Thank you!
