### ISSUE TITLE
Build an SAP Fiori App with SAP API Management

### ISSUE THREAD

**Issue by valentini50** [SAPDocuments/Tutorials#3640]
Mission URL: https://developers.sap.com/mission.apim-fiori-app.html
Good Morning.
Any news about my problem as to the completion percentage of the tutorial?

**Comment by thecodester** [comment]
Duplicate issue (I am checking)

https://github.com/SAPDocuments/Tutorials/issues/3636

**Comment by valentini50** [comment]
Good Morning.
About Isseu open any position?
The problem still continues and even finished the tutorial, it does not upgrade to 100%

De: Daniel Wroblewski [mailto:notifications@github.com]
Enviada em: quarta-feira, 19 de junho de 2019 06:59
Para: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Carlos Alberto Valentini <Carlos.Valentini@t-systems.com.br>; Author <author@noreply.github.com>
Assunto: Re: [SAPDocuments/Tutorials] Build an SAP Fiori App with SAP API Management (#3640)


Duplicate issue (I am checking)

#3636<https://github.com/SAPDocuments/Tutorials/issues/3636>
