### ISSUE TITLE
Build an SAP Fiori App with SAP API Management

### ISSUE THREAD

**Issue by bstk0** [SAPDocuments/Tutorials#3641]
Mission URL: https://developers.sap.com/mission.apim-fiori-app.html

I've concluded all the mission but complete percent still in 88%. 
I've clean the browser cache, restarted the S.O. and still 88%.
Could you verify, please?

**Comment by thecodester** [comment]
Can you let me know which tutorial is not complete? Screenshot would help of the mission page, and then the tutorial that does not complete.

**Comment by bstk0** [comment]
Hi thecodester,
Sorry for being late. I tried a few days ago and got it done.
Thank you.
