### ISSUE TITLE
SAP HANA XS Advanced, explore the basic tools

### ISSUE THREAD

**Issue by QVA327** [SAPDocuments/Tutorials#3644]
Tutorial URL: https://developers.sap.com/tutorials/xsa-explore-basics.html

Please specify the step you are referring to:
Step 3, Explore the WebIde. I can call the webide and log in, but get a lot of error messages:
![image](https://user-images.githubusercontent.com/52071232/59917627-b819ac80-9422-11e9-9769-08c4efc0267a.png)
as a consequence (I think) the database explorer is not visible in my webide:
![image](https://user-images.githubusercontent.com/52071232/59917718-f3b47680-9422-11e9-83b8-1e659842ac01.png)
I have found no hint, what went wrong in my installation of HANA XS as virtual machine.

please advise.
Best regards

Heider

**Comment by Lsubatin** [comment]
Hi, 

Please create a question in the community to ask for technical help (answers.sap.com), there are more people monitoring there. This channel is meant for tutorial feedback.

I would recommend a quick Google search first, as you should find possible fixes for this: using Chrome as a browser or adding the certificate for HXE to the trusted root or using the [troubleshooting guide](https://help.sap.com/viewer/4505d0bdaf4948449b7f7379d24d0f0d/2.0.04/en-US/ff923ba2166846928d5190a4c235e1ee.html)

If you create a question, include the output of the console in Chrome (F12) and the logs from the webide application.

Best, 

Lucia.
