### ISSUE TITLE
Create a Simple IoT Device Model

### ISSUE THREAD

**Issue by andreschgz95** [SAPDocuments/Tutorials#3646]
Tutorial URL: https://developers.sap.com/tutorials/iot-express-2-create-device-model.html

Step 1.4. We are trying to access to: Open the **Service Instances** list and click on the **Open Dashboard** icon in the **Actions** column

We are not able to identity "Open Dashboard" in "Service Instances" menu option. 

We would like to know if we are missing some license registration because we have understood that the Trial CF account was succesful.

**Comment by marcuscbehrens** [comment]
Hi, IoT Service is not part of the CF trial. The price of the package including both Leonardo IoT and IoT Service has been reduced significantly in sapstore.com recently or you can talk to your SAP account team about test license. Regards, Marcus

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
