### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Tutorials#3650]
Tutorial URL: https://developers.sap.com/tutorials/xsa-create-user-provided-anonymous-service.html

Please specify the step you are referring to:

In section Step 5: Check or modify the MTA.yaml file - The text and the images are inconsistent.  In the text, the instructions are to use ~{products-service-name} but in the image, it shows ~{the-service-name} 

So the "These are the relevant pieces of the MTA.yaml file. You can see the database module and its dependency to the user provided service." section that shows the YAML snippet, it shows it based on the text and not the image.  This is confusing.

Regards,
Jay

**Comment by jmalla** [comment]
Looks like the documentation is still incorrect.  It's a simple fix that would help users.

**Comment by Lsubatin** [comment]
Yes, the update will continue to be pending.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
