### ISSUE TITLE
Add a User Task to Your Workflow

### ISSUE THREAD

**Issue by spremalatha** [SAPDocuments/Tutorials#3652]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-add-usertask.html

I have added the user task for the workflow(Step 4) and  Started a new workflow instance(Step 5)  as well. Then, when i tried to open the workflow task in My inbox, I am not listed with the new task as per the next step (step 6). But I could see the workflow instances for my workflow definition. 
Screenshot 1 - Task Missing in the My Inbox
Screenshot 2 - Monitor Workflows - Workflow Instances

My user information - Premalatha Saravanan (P2000931418)

![Screenshot 1](https://user-images.githubusercontent.com/46582138/60062617-5c5e6480-973d-11e9-8d40-079c6ca3d1c9.png)
![Screenshot 2](https://user-images.githubusercontent.com/46582138/60062619-5cf6fb00-973d-11e9-945c-736334f59584.png)

**Comment by thecodester** [comment]
You set your user name as the Recipient of the user task?

**Comment by spremalatha** [comment]
Thanks for the reply. Have added the recipients name as my name. Attached the screenshot for reference. 
![image](https://user-images.githubusercontent.com/46582138/60076311-972ac180-976a-11e9-94e2-74817809c65d.png)

**Comment by thecodester** [comment]
I'm not an expert, but I would imagine that the user must be your technical user -- if you go to the upper right of the cloud platform and click user information, it will show you your ID.

**Comment by AstridHerbst** [comment]
Hi,

You need to log on to the SAP Cloud Platform cockpit. 

Step 6: Under Recipients, define who will receive the task. Enter your user ID exactly as displayed in the User Information popup of your subaccount in the SAP Cloud Platform cockpit.

Best regards,
Astrid

**Comment by thecodester** [comment]
@spremalatha Is would be nice to know if you solved your issue. I am closing the issue since it seemed the issue was resolved.
