### ISSUE TITLE
SAP HANA XS Advanced - Modules within Node.js SAP HANA applications

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Tutorials#3653]
Tutorial URL: https://developers.sap.com/tutorials/xsa-node-modules.html

Please specify the step you are referring to

Step 6: Extend dependencies in package.json

Need to add the packages for:
	"@sap/xssec": "2.1.15",
	"@sap/hdbext": "~5.0",
	"@sap/logging": "~4.0",

Also - this code did not work for us and we had to comment it:
//app.use(logging.expressMiddleware(appContext));

Regards,
Jay

**Comment by Lsubatin** [comment]
These tutorials will be removed once the new ones are ready and the dependencies fixed. Leaving this open until then.

**Comment by MichaelCzcz** [comment]
@Lsubatin any updates on the new tutorial versions?

**Comment by Lsubatin** [comment]
I ran this at a couple of events before leaving SAP and other than versions, the steps were correct. I think a previous tutorial was missed here. The entire mission needs an update but I'm not at SAP anymore.,

**Comment by jung-thomas** [comment]
This tutorial group has been revised and tested on HANA Express 2.0 SPS 04. This issue is now resolved.  Sorry for the inconvenience.
