### ISSUE TITLE
Create a Workflow Definition Using an External Service

### ISSUE THREAD

**Issue by RobertVit** [SAPDocuments/Tutorials#3655]
Tutorial URL: https://developers.sap.com/tutorials/cp-wf-01-create-definition.html

Step 7: Do i have to create the Destination "Northwind" in the Cloud Platform Cockpit?

**Comment by thecodester** [comment]
I believe so ... towards the end of Step 7 of your tutorial, there is an explanation of the fields you need to enter, with a link to the tutorial https://developers.sap.com/tutorials/hcp-create-destination.html for creating a Northwind destination.

**Comment by qmacro** [comment]
Yes, please see the "Prerequisites" in the tutorial, which links to the tutorial ("Create a Destination for the Northwind OData Services") that @thecodester referred to above. Thanks.
