### ISSUE TITLE
Create a Business Service with Node.js using Visual Studio Code

### ISSUE THREAD

**Issue by octavonu** [SAPDocuments/Tutorials#3658]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Can you please write the same tutorial with HANA Server Only instead of SQLite?

I was not able to understand the SAP documentation.

Thank you

**Comment by renejeglinsky** [comment]
Hi @octavonu ,
I'll look into this. Please be patient a couple of days, I'll get back to you. 

Thanks :)

**Comment by renejeglinsky** [comment]
Hi @octavonu ,
there is no easy shortterm solution I can offer you. If you are willing to create an instance of your SAP HANA service yourself and take care of the binding etc to deploy to your SAP HANA service instance you can give it a try. But cds deploy does not support that until now.
I'll leave this issue open to keep you posted on the progress wrt cds deploy.

Regards,
René

**Comment by octavonu** [comment]
Thank you very much @renejeglinsky 
I had the same feeling. 

Best regards,
Octav
