### ISSUE TITLE
Manage APIs with Policies

### ISSUE THREAD

**Issue by Theo-van-Dijk** [SAPDocuments/Tutorials#3659]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-apis-manage.html

Step 3: Set limit
Point 5. Click Save on the next screen.
The changes are not saved and an error is displayed: "Unable to update API"

**Comment by shilpavij** [comment]
Dear Colleague,

There are a couple of reasons for API not getting updated.
1. wrong basepath.
2. spaces.
3. session expired

Can you please attach a screenshot.

Regards
Shilpa

**Comment by shilpavij** [comment]
Dear Daniel,

I have already replied to #3659.

Regards
Shilpa

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
