### ISSUE TITLE
Create a Basic Node.js App

### ISSUE THREAD

**Issue by I812441** [SAPDocuments/Tutorials#3662]
Tutorial URL: https://developers.sap.com/tutorials/cp-node-create-basic-app.html

Please specify the step you are referring to
Step 3 the console.log at line 10 is incorrect.  It causes SyntaxError: Unexpected end of input.  
I believe you want:
console.log('myapp listening on port',  port);

-Greg

**Comment by maxstreifeneder** [comment]
should be fixed.
