### ISSUE TITLE
Build Your First Full-Stack App on SAP Cloud Platform

### ISSUE THREAD

**Issue by mojitodaiquiri** [SAPDocuments/Tutorials#3664]
Mission URL: https://developers.sap.com/mission.scp-5-full-stack.html

It's possible to have an example working with odata v4?

Is the some complete reference about cds annotation ( i cannot find any documentation about come @insertonly, @cds.autoexpose, @cds.persistance.skip  ) ?

**Comment by renejeglinsky** [comment]
Hi @mojitodaiquiri ,

I am sorry for being that late.
Answering your first question: No, we don't have an example with odata V4. You could go for a deviation of our tutorial (create a V4 project, use the V4 UI template) but we cannot offer support for that here.

If you are looking for reference documentation, have a look at [cap.cloud.sap](https://cap.cloud.sap/docs/).

Regards,
René

**Comment by MichaelCzcz** [comment]
@mojitodaiquiri Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
