### ISSUE TITLE
Create Your First ABAP Console Application - other cloud environment?

### ISSUE THREAD

**Issue by dennis-grothe** [SAPDocuments/Tutorials#3666]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-console-application.html

Hello,

is it possibly to use the SAP Cloud Platform Neo environment for creating a cloud project with the ADT since there is only a 30 days trial for CF. Are there any other options for interns?

Best regards,
Dennis

**Comment by mervey45** [comment]
Hi, 

you can only use Cloud Foundry Trial. We do have a tutorial for that now: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html 

Best regards, 
Merve

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
