### ISSUE TITLE
Continuous Integration (CI) Best Practices with SAP – Introduction and Navigator

### ISSUE THREAD

**Issue by KarelVerbanck** [SAPDocuments/Tutorials#3667]
Tutorial URL: https://developers.sap.com/tutorials/ci-best-practices-intro.html

Part 4.5 – Implementing the CI pipeline to build an SAPUI5/SAP Fiori application on SAP Cloud Platform.

It is not really an issue but just something that I want to understand.
We would love to start using CI/CD @our project but there is something that I'm missing and I'm not sure what the best practice are when you are:
 - Building SAPUI5 applications on the cloud and running them on the cloud (currently manually deployed to the different systems (QA/PROD)
 - Building your gateway services on an on premise system (Via CHARM (monthly releases))

What am i missing basically:
 - How do you use CI/CD on the frontend when there is a lot of dependency with the backend/gateway  developments that are released monthly?
    -> so what we want is that we can have more or less a package with both frontend developments and backend developments. In this way we make sure that all the code of both frontend/backend are in sync on all the different systems.

Does anyone have any experience on this topic?
Thanks in advance of sharing your best/practices to tackle this "issue"

**Comment by radsoulbeard** [comment]
Hi,
this scenario is at the moment addressed here: https://sap.github.io/jenkins-library/scenarios/changeManagement/ and will come at a later point in time for general best practices.
Here https://help.sap.com/viewer/disclaimer-for-links?q=https%3A%2F%2Fwww.slideshare.net%2Fsapcp%2Fchange-control-management-supports-continuous-integration-and-delivery you can also find some slides from TechEd 2018.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
