### ISSUE TITLE
CI Best Practices Guide – SAPUI5/SAP Fiori on SAP Cloud Platform

### ISSUE THREAD

**Issue by mhealey2018** [SAPDocuments/Tutorials#3668]
Tutorial URL: https://developers.sap.com/tutorials/ci-best-practices-fiori-sapcp.html

Please specify the step you are referring to.

The CI Best Practise guides are a great introduction to using Jenkins to support 

With SAP's recent release of "UI5 Build"  as the primary build tool for UI5 applications over grunt, it'd be great to update this tutorial to reflect this.

What impact does UI5 Build have on:

1) Creation of Multi-Target Archives especially for deployment to Neo via Multi-Target Archive Builder ?
2) Build steps required in Jenkins pipeline job to trigger "UI5 Build" ?

**Comment by radsoulbeard** [comment]
Hi,
did you had a look at our Project "Piper"? Here we describe the UI5 scenario 
https://sap.github.io/jenkins-library/scenarios/ui5-sap-cp/Readme/
Here you have "ready to use" build steps for Jenkins Pipelines.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
