### ISSUE TITLE
Create Your First Application with SAP Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by pichel3000** [SAPDocuments/Tutorials#3669]
Tutorial URL: https://developers.sap.com/tutorials/s4sdkjs-odata-service-cloud-foundry.html

Please specify the step you are referring to

The sentence "Then, add this route to the routes of your application in application.ts:" should say something like "Please replace the previous route to the HelloWorld example with this:". Alternatively, it should say that you create a second route under a different name.

I had issues getting the example to work because I simply pasted the new routes() code under the existing one, which obviously doesn't work since you can't have duplicate declarations. It's only a simple mistake, I realise, but many people using this are transferring skills into node.js.

**Comment by mr-flannery** [comment]
Hi Michael,

thanks for your feedback! I have improved the phrasing to hopefully make it more clear what the correct action is.
