### ISSUE TITLE
Create Your First Application with SAP Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by qmacro** [SAPDocuments/Tutorials#3674]
Tutorial URL: https://developers.sap.com/tutorials/s4sdkjs-odata-service-cloud-foundry.html

Please specify the step you are referring to: 4

The sample code in "here's what it should look like" is quite different from what has just been specified a moment earlier (use of `await` vs a `then/catch` structure).

**Comment by mr-flannery** [comment]
Hey DJ,

thanks for the heads-up, I have rewritten the respective part to make consistent use of `Promises`!
