### ISSUE TITLE
Get Started with ABAP Development

### ISSUE THREAD

**Issue by NToulouse** [SAPDocuments/Tutorials#3675]
Mission URL: https://developers.sap.com/mission.abap-dev-get-started.html

Good tutorials.  One suggestion though - check all screenshots!  some of them do not match what is being said in the text.  Whilst certainly not a show stopper, it causes some confusion to a complete SAP & Eclipse noob like myself :)  had to scroll to the end of the tutorial to make sure of the correct code.

For example, in the "create basic app" tutorial, the program starts off as "demo" but has become "create basic report tutorial" by the end (which I have since learnt was to do with the "description" when creating the program).  A bit confusing!  Similar issues in some of the other tutorials.

**Comment by julieplummer20** [comment]
Hi NToulouse,
OK, thanks for the positive feedback.
I may not be able to correct all the previous screenshots, for capacity reasons, but will try to do that in future.
Best wishes,
Julie

**Comment by thecodester** [comment]
Thank you for your feedback, and for the compliment. We will work on keeping the tutorials and screenshots up to date. I am closing the issue. 

If you still have questions, feel free to reopen the issue.

@julieplummer20 If you need the issue open as a reminder, feel free to reopen.
