### ISSUE TITLE
Configuring Eclipse with SAP Cloud Platform Tools for Java

### ISSUE THREAD

**Issue by tiagobalmeida** [SAPDocuments/Tutorials#3677]
Tutorial URL: https://developers.sap.com/tutorials/hcp-java-eclipse-setup.html

In step 15 it is mentioned to download Java web (neo-java-web-sdk.X.X.X) although this package is deprecated. The tutorial should be updated to use Java web tomcat 7 or 8.

Thanks

**Comment by rbrainey** [comment]
Max, I'm assigning this to you for action.  Would you update the instructions?  Thanks

**Comment by MichaelCzcz** [comment]
@maxstreifeneder any updates?

**Comment by MichaelCzcz** [comment]
@maxstreifeneder Can you please look into this issue and provide an update? Thank you.

**Comment by MichaelCzcz** [comment]
@maxstreifeneder Can you please look into this issue and provide an update? Thank you.

**Comment by MichaelCzcz** [comment]
@tiagobalmeida Please note that this tutorial is deprecated and will not be updated anymore.
