### ISSUE TITLE
Deploy SAP HANA as a Service

### ISSUE THREAD

**Issue by mikeyfreake** [SAPDocuments/Tutorials#3679]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-deploying-haas.html

Please specify the step you are referring to: Navigate to Services -> Service Marketplace. Click on SAP HANA Service.

This shows a screenshot with a service called "SAP HANA Service" which does not exist for me. Is this service still available in Cloud Foundry? Maybe the tutorial must be updated? Below is what I see.

![image](https://user-images.githubusercontent.com/3608028/60548128-97810a80-9cde-11e9-8ea0-ab86f43055a2.png)

**Comment by mikeyfreake** [comment]
Sorry, I just realized that this tutorial (https://developers.sap.com/tutorials/haas-dm-deploying-haas.html) is meant for Customer/Partner license.

I am simple playing with SCP on my own and was not looking to make any purchases to explore the functionality.

**Comment by Lsubatin** [comment]
Hi Michael, 

Unfortunately, there is no full trial yet. You can still use the trial HDI containers in your screenshot with something like this: https://developers.sap.com/tutorials/xsa-e2e-capm-fullstack.html 

Or HANA express with XS Advanced (the "on premise" version of Cloud Foundry), which is for free even for productive use up to 32GB of RAM: https://developers.sap.com/topics/sap-hana-express.html

Closing this as the tutorial already has the header that it cannot be completed on a trial account.
