### ISSUE TITLE
Define SAP Web IDE as Communication Partner in S/4HANA Cloud

### ISSUE THREAD

**Issue by Farooq1414** [SAPDocuments/Tutorials#3680]
Tutorial URL: https://developers.sap.com/tutorials/abap-custom-ui-communication-systems.html

Step 12 : 
I have created all communication system by following all the steps provided.
But having an issue while saving communication system.

For reference.
![image](https://user-images.githubusercontent.com/52484179/60569547-45e38900-9d8d-11e9-99bd-c232150a0a92.png)

Can anyone please help me out in resolving the issue.

Thanks in advance.

Regards,
Farooq.

**Comment by Liebherr** [comment]
Hi Farooq,
please open an Incident on BC-SRV-APS-COM.
Thanks and Regards
Ulrike

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be a support issue, not an issue with the tutorial. 

If you still have questions, feel free to reopen the issue.
