### ISSUE TITLE
Create an ABAP Project in ABAP Development Tools (ADT)

### ISSUE THREAD

**Issue by albanislucena2019** [SAPDocuments/Tutorials#3682]
Tutorial URL: https://developers.sap.com/tutorials/abap-create-project.html

Please specify the step you are referring to Get a logon data trial,

**Comment by julieplummer20** [comment]
Hi 	albanislucena2019, I don't understand the question. What step are you referring to? 
Do you already have an ABAP application server, e.g. in your company?
If not, you can get a free download or Cloud Appliance from here : https://developers.sap.com/trials-downloads.html  - search "AS ABAP". You need to register as a SAP Community member but you don't need to be an SAP customer / partner.
HTH Julie.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
