### ISSUE TITLE
SAP HANA XS Advanced, debug XSJS and node.js scripts

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Tutorials#3685]
Tutorial URL: https://developers.sap.com/tutorials/xsa-debug-nodejs-xsjs.html

Please specify the step you are referring to

For HANA Express, there are problems with debugging on Safari or Chrome due to the browsers not allowing web socket communication to the server which has a self signed certificate.  I do not recall having this issue before - but with my Mac OS High Sierra, and Safari Version 12.1.1 (13607.2.6.1.2) now I am getting this problem.  I was able to get debugging on Chrome to work only after running this from the terminal via:
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --ignore-certificate-errors &> /dev/null &`

 -   It may be helpful to add this information as a side note in case users have issues not being able to connect to the active session at least on HANA Express.

Regards,
Jay

**Comment by Lsubatin** [comment]
This was tested in two other Mac machines and this issue did not happen. Thanks anyway.
