### ISSUE TITLE
Create your own Fiori Launchpad

### ISSUE THREAD

**Issue by ChrisWake** [SAPDocuments/Tutorials#3687]
Tutorial URL: https://developers.sap.com/tutorials/teched-2017-fiori-create.html

Please specify the step you are referring to I don't have the Enable option for the portal within the services menu.

What would the reason be for this?

Regards

**Comment by rbrainey** [comment]
Hi.  There's two ways we could attack this issue: first, if you send me a screenshot of the services cockpit panel, I might be able to track the issue down -- second (maybe better), there's a completely revamped version of Cloud Portal now available; You can try it out through one of our new TechEd 2019 Missions: see https://developers.sap.com/app-space.html -- the Cloud Portal mission is the one at the top of this page.

**Comment by thecodester** [comment]
I suggest using this mission for learning portal: https://developers.sap.com/mission.portal-cf.html

Good luck

**Comment by rbrainey** [comment]
I'm closing this issue, Chris.  Feel free to reach out to me directly if you'd like to discuss the updated functionality in the new Tutorial.
