### ISSUE TITLE
Build and Deploy a Java Application

### ISSUE THREAD

**Issue by DI9-dev** [SAPDocuments/Tutorials#3689]
Tutorial URL: https://developers.sap.com/tutorials/cp-java-reference-app-deploy.html

Please specify the step you are referring to 
while binding the database to the application I am getting the error even though I have provided the valid credentials. Can you please look into this. Looking forward for your reply. I have also attached the screenshot for reference.
![Databinding error](https://user-images.githubusercontent.com/52600567/60836445-b0ccff80-a193-11e9-9002-03086b999da8.PNG)

Thank you,
Venkhatesh.

**Comment by simonarangelova** [comment]
Hi,

Can you navigate to:
Database/schemas -> (the tenant db. In this case its espm1) and check what value does JDBC URL holds?

 
![IMG_4056](https://user-images.githubusercontent.com/32678370/61049062-35b25600-a3ec-11e9-8795-c9f83b09e900.jpg)


If its null, then there might be a problem with tenant creation. In that case you should delete the existing DB and recreate it.

Thanks and Regards,
Simona

**Comment by DI9-dev** [comment]
Hi,

Thank you. It's showing up.

Regards,
Venkhatesh.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
