### ISSUE TITLE
Create an application using SAP HANA and the Cloud Application Programming model

### ISSUE THREAD

**Issue by mikeyfreake** [SAPDocuments/Tutorials#3690]
Tutorial URL: https://developers.sap.com/tutorials/xsa-e2e-capm-fullstack.html

Please specify the step you are referring to:

Prerequisite is "You have configured and installed a builder in your space". Builders are no longer required in SCP, so this should not apply.

Having said this, I'm unsure that this tutorial works unless you are an SAP Partner or Customer (i.e. not using a trial account) as I'm unable to right click on the "db" folder and successfully Open HDI Container. Does it work for trial accounts?

Thanks,
Mike

**Comment by Lsubatin** [comment]
Hi, it works for trials but only in Europe AFAIK. 
You are right on the builder, it's not necessary anymore.

**Comment by Lsubatin** [comment]
Changed verbiage on prerequisites. Added EU10 while US10 is unavailable.
