### ISSUE TITLE
Access a Classic Schema from SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by S0016713463** [SAPDocuments/Tutorials#3691]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-access-cross-container-schema.html

Please specify the step you are referring to

An error occurred when I was proceeding Step5 and 6.
The error occurred when executed Build sequence.
The error message is below. Would you give me some advice, since I am stuck for a day?

15:45:12 (HDB)  Processing "cfg/plain.hdbgrants"...
15:45:12 (HDB)   Using service "CC_ACCESS" of type "sql"
15:45:12 (HDB) Error: authentication failed grantor service: "CC_ACCESS", type: "sql", user: "PLUSR"file name: /tmp/hdi-space-deploy-36idl5rgvm75ks-content/cfg/plain.hdbgrants
15:45:12 (HDB) (0s 197ms)
15:45:12 (HDB) Deployment failed with exit code: 1

plain.hdbgrants  : 

{
  "CC_ACCESS": {
    "object_owner" : {
      "roles" : ["CCROLE"]
    },
    "application_user" : {
      "roles" : ["CCROLE"]
    }
  }
}

**Comment by Lsubatin** [comment]
Hi, 
This forum is for feedback on the tutorial, not support. However, that error tells me you are using the wrong username/password in your user provided service. 

Make sure you can access the database with that username and password and that the HDI container is also bound to the database in which you created PLUSR.

I would recommend you google for this kind of error in answers.sap.com where this kind of questions is quite frequent.

Best, 

Lucia.
