### ISSUE TITLE
Create a Calculation View with K-anonymity (XS Advanced)

### ISSUE THREAD

**Issue by gauravaggarwal21** [SAPDocuments/Tutorials#3695]
Tutorial URL: https://developers.sap.com/tutorials/xsa-calculation-views-anonymization-k.html

Please specify the step you are referring to

Step 7 - after completing my build, i get the following error

![image](https://user-images.githubusercontent.com/16799989/60915432-ae74af00-a240-11e9-89fa-e66c4c518af3.png)

**Comment by Lsubatin** [comment]
There seems to be something missing in the model from that error ("entry in table not found in level 0 of the hierarchy..."). It's impossible to diagnose without looking at the model or even the full error message.
As this forum is for feedback on the tutorials and not support, please open a question in the community including all relevant information (the model, the error, version of your platform). You can also take a look at the existing GitHub repository for a known-good model and compare.
