### ISSUE TITLE
Prepare to create a Java app with an MTA template

### ISSUE THREAD

**Issue by DI9-dev** [SAPDocuments/Tutorials#3696]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-java-create.html

Please specify the step you are referring to template MTA. I dont see the MTA template in my trail version. Could you please help me on this. I have also attached the screenshot for reference. Looking forwoard for your reply.

Thank you,
Venkhatesh.
![MTA](https://user-images.githubusercontent.com/52600567/60923402-d7129e00-a26c-11e9-9de5-9cdc5712cc9c.PNG)

**Comment by maxstreifeneder** [comment]
Hey @DI9-dev ,

thanks for your issue. You are right, the screenshots in the tutorial are confusing. I'll fix this. 

In the meantime: If you choose "Cloud Foundry" instead of "Neo" in the selectbox for the "Environment" you should be able to continue with the tutorial. 

Cheers,
Max

**Comment by maxstreifeneder** [comment]
Fixed.
