### ISSUE TITLE
Add a User Task to Your Workflow

### ISSUE THREAD

**Issue by mchcn2018** [SAPDocuments/Tutorials#3703]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-add-usertask.html

After completing Step 5: Start a new workflow instance, I do see any task in my Inbox. Please advise

**Comment by thecodester** [comment]
Did you add your user ID to the task?

**Comment by mchcn2018** [comment]
Yes, I did exactly according to the tutorial

**Comment by AstridHerbst** [comment]
Please access the "Monitor Workflows" app (MWA) and check the workflow execution log.
In that log, you see whether the task has been created and to whom it  is assigned or if the workflow possibly failed before that step.

**Comment by mchcn2018** [comment]
I jsut got this error message in "Workflow - SAP Web IDE Full-Stack"
HTTP Status 500 - An internal application error occurred. Request: 3580661365 s0011149706trial:webidecp

**Comment by AstridHerbst** [comment]
Can you please give more details on the issue ? When is the below error occurring in Web IDE?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
