### ISSUE TITLE
Build and Deploy a Java Application

### ISSUE THREAD

**Issue by DI9-dev** [SAPDocuments/Tutorials#3706]
Tutorial URL: https://developers.sap.com/tutorials/cp-java-reference-app-deploy.html

Please specify the step you are referring to I am unable to view retailer part UI showing HTTP status 403 error.

Thank you,
Venkhatesh.

**Comment by simonarangelova** [comment]
Hello, 

Are you sure that you have added the retailer role and assigned your user ID as a retailer. Please note you should exclude the “trial” part when entering your ID.

Let me know, if you still have this issue.
Thanks.
Simona

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
