### ISSUE TITLE
Store Sensor Data in HDFS in SAP Data Hub, Developer Edition 2.4

### ISSUE THREAD

**Issue by karthikbw** [SAPDocuments/Tutorials#3707]
Tutorial URL: https://developers.sap.com/tutorials/datahub-pipelines-v2-storeinhdfs.html

Please specify the step you are referring to
Step 1: Start and Check Hadoop
 While running the command - 

docker run -ti --publish 127.0.0.1:50070:50070 --name hdfs --hostname hdfs --net dev-net datahub run-hdfs

It fails with error below

docker: Error response from daemon: Conflict. The container name "/hdfs" is already in use by container "1cad1444404fd3d138457b69b1484129a5b0574cbeaca8efdc82b3071b857901". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

As a result, the hadoop can't be accessed - http://localhost:50070/ - says site can't be reached.

Please help!

Thanks
Karthik

**Comment by schneidertho** [comment]
Hi, you already have a container with name "hdf" running. Hence you need to delete this first (as the response from the docker daemon says): docker rm hdfs
Cheers
Thorsten

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
