### ISSUE TITLE
Inspect and Test the API Proxy

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Tutorials#3709]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-inspect-apiproxy.html

Please specify the step you are referring to - Step 1, ad 1
"In case you have used your own userid and password, use a Base64 encoder tool to encode the text username:password – without the single quote and place it in the field instead."
What ever I try, i can't log on to the llink. ES5 access is fine, and have tried with an encoded version of user and PW.
What do I do wrong?
Kr Michael

**Comment by thecodester** [comment]
@shilpavij Also, only your last name is shown. You can fix this by setting your name in Git.

**Comment by shilpavij** [comment]
Dear Michael,

You need to be very careful about the space. Kindly check that while encoding there are no extra spaces or after encoding there should not be extra spaces.

Regards
Shilpa

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
