### ISSUE TITLE
Manage Hubspot Instance using SAP API Management

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Tutorials#3711]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-openconnectors-hubsopt-manage.html

Please specify the step you are referring to
Step 1 - ad 6 - Test connection
I Get "System is up and reachable. However, the ping check responded with code : 404; Message :"
How come, think I followed manual to "the letter" ;-)

Best rgds Michael

**Comment by shilpavij** [comment]
Dear Michael,

Regarding the 404 issue- Please go ahead and check your scenario it should work. Regarding the letter, so sorry for spamming but we want to communicate our finding hence documented in detail:)

Regards
Shilpa

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
