### ISSUE TITLE
SAP HANA XS Advanced, debug XSJS and node.js scripts

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Tutorials#3712]
Tutorial URL: https://developers.sap.com/tutorials/xsa-debug-nodejs-xsjs.html

Please specify the step you are referring to

Hi Lucia - do we have a document or video on debugging a HANA stored procedure being called from a NodeJS module?  We are trying to do that by setting up a debugging session with the HDB container RT user but we are getting a permissions issue.

Thanks,
Jay

**Comment by Lsubatin** [comment]
I at least have no knowledge of such video.

Closing this as it;s not an issue and the community is still the place to go.

**Comment by jmalla** [comment]
I looked through lots of articles but could not see anything on debugging the stored procedure from the call from outside via the NodeJS layer.  It would be good if there is a published blog about this since this is fundamental part of developing.  We found an issue with the SAP HDB client yesterday and it was a tough one to debug.  Once I figure out the debugging, I will create a blog - but I was hoping that you may already have those details or know of one.

Thanks,
Jay
