### ISSUE TITLE
SAP HANA XS Advanced - Database access from Node.js

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Tutorials#3713]
Tutorial URL: https://developers.sap.com/tutorials/xsa-node-dbaccess.html

Please specify the step you are referring to

Hi Craig - we are also doing NodeJS and stored procedures.  We are trying to debug our stored procedure from the NodeJS call and are running into issues trying to get the debugging to work.  Any details on how to debug the stored procedure from the NodeJS call?

Thanks,
Jay

**Comment by Lsubatin** [comment]
Jay, 

Once again, the channel to ask for help is the community, an incident or consulting. 

Closing this.

**Comment by jmalla** [comment]
Hi Lucia - There are two to three questions in the community that have been open for a while but no answers.  I can't find any answers.  Can you respond in the community?  That would help.

This is the closest one - but I could not get this to work....
HANA Express: How to debug a SQLScript procedure when called through UI5 module/nodejs module
[https://answers.sap.com/questions/687849/hana-express-how-to-debug-a-sqlscript-procedure-wh.html
](url)

Here is another one with the same question:
How to debug database procedure through NodeJS application with Postman? (XSA - WebIDE)
[https://answers.sap.com/questions/728027/how-to-debug-database-procedure-through-nodejs-app.html?childToView=12731862&answerPublished=true#answer-12731862](url)


[How to debug database procedure through NodeJS application with Postman? (XSA - WebIDE)](url)

Here is mine (we found an issue with the SAP HDB client not passing undefined correctly to the stored procedure):
How to debug SAP HANA XSA stored procedure from a web nodeJS call - problem passing parameters
[https://answers.sap.com/questions/12731861/how-to-debug-sap-hana-xsa-stored-procedure-from-a.html](url)

Are you able to debug stored procedures from the NodeJS code?
