### ISSUE TITLE
Debug Your SAPUI5 App with SAP Web IDE

### ISSUE THREAD

**Issue by paxperscientiam** [SAPDocuments/Tutorials#3716]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-webide-debug.html

Step 3: Write a log message to the console

The first snippet of code (and corresponding thumbnail) overlaps pre-existing code.

**Comment by IObert** [comment]
Hi @paxperscientiam,

thanks for opening this issue. I'm afraid I'm not sure if I understand the issue you're describing. Can you please add more details?

**Comment by paxperscientiam** [comment]
Oops, I see that my comment was pretty vague.
To clarify, where the snippet to copy from the tutorial page is this ...
```js
,
	"sap/base/Log"
], function (Controller, Log) {
```
... the pertinent region from the project code base looks like this:
```js
sap.ui.define([
	"sap/ui/core/mvc/Controller" // <-- snippet should be pasted here according to tutorial
], function (Controller) {
	"use strict";
```
Given this, pasting the snippet at the prescribed location would lead to this:
```js
sap.ui.define([
	"sap/ui/core/mvc/Controller",
	"sap/base/Log"
], function (Controller, Log) {
], function (Controller) {
	"use strict";
```
This is obviously wrong. My recommendation would be to add a little more detail. 
* Delete line three.
* Paste snippet in the same way as currently prescribed.

I think I see what thought process was for the author. The callback now has two arguments, but it's not explicitly mentioned (i'm guessing because it's beyond the scope of the tutorial in question).

Does that help?

**Comment by IObert** [comment]
Sorry for the late response. I see the confusion and I added more text around it. 
Please let me know if it's still ambiguous.

And yes, there are devs that just want to copy and paste the code. Others want to learn as much as possible about each step. It's always hard to meet both expectations :)
