### ISSUE TITLE
Build a Shopping Fresh Fiori App in SAPUI5

### ISSUE THREAD

**Issue by mparoti** [SAPDocuments/Tutorials#3717]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-create-fioriapp.html

Please specify the step you are referring to

Step 3, Item 7
I have the message "The application cannot be subscribed to product eCommerceProduct using service 'salesTrackerAPI'. Please contact your System Administrator."

What can I do?

These are my URLs:
API Management Runtime
https://mytrialusernametrial-trial.apim1.hanatrial.ondemand.com:443/mytrialusernametrial/salesTrackerAPI

API Management Dev Portal
https://devportalu34f5b50f-mytrialusername.hanatrial.ondemand.com/

And see the attached files.
![API Management Runtime](https://user-images.githubusercontent.com/52739318/61511129-fbe9dc80-a9f5-11e9-82ed-33acbfd47d29.jpg)
![API Management Runtime_Connection Check](https://user-images.githubusercontent.com/52739318/61511130-fbe9dc80-a9f5-11e9-872a-a9fc4e49d440.jpg)
![API Management Dev Portal](https://user-images.githubusercontent.com/52739318/61511131-fbe9dc80-a9f5-11e9-9cdc-4d134c0bf1e3.jpg)
![API Management Dev Portal_Connection Check](https://user-images.githubusercontent.com/52739318/61511132-fc827300-a9f5-11e9-9448-be1f775424e0.jpg)

Thank you

**Comment by shilpavij** [comment]
Dear Colleague,
If you have cross-checked your destination and all the urls are correct, the product is also published successfully and still, you are getting this issue, please log a ticket on OPU-API-OD-DT.

Regards
Shilpa

**Comment by mparoti** [comment]
Hi Shilpa

I have cross-checked. I only had to register correctly with the "Developer Portal Trial".
Now it seems to be working.

Thank you
Marco
