### ISSUE TITLE
Create a Workflow Project from a Template

### ISSUE THREAD

**Issue by Syafi95** [SAPDocuments/Tutorials#3718]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-create-project.html

Please specify the step you are referring to Step 2: Create a new project

The selection at "New From Template" does not have the selection "Business Process Management"

![image](https://user-images.githubusercontent.com/39061717/61520238-59a31680-aa40-11e9-812f-0cdc984e49b2.png)

**Comment by AstridHerbst** [comment]
Please check whether you have enabled all the services and extensions as described in the first tutorial Prepare to Create Workflows in SAP Cloud Platform?

Make sure to save all settings.
  
![wf_editor](https://user-images.githubusercontent.com/18418519/61610155-8f224c80-ac58-11e9-8c85-202ba79c2978.jpg)
[](url)
Best regards,
Astrid

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
