### ISSUE TITLE
Get Started with SAP API Management

### ISSUE THREAD

**Issue by Chet77** [SAPDocuments/Tutorials#3719]
Group URL: https://developers.sap.com/group.cp-apim-code-1.html

Brilliant 
But ... the screenshots are dated and needs updating

**Comment by thecodester** [comment]
@shilpavij Can you take ownership of this group of tutorials and let me know what you'd like to do with them?

**Comment by shilpavij** [comment]
Sure Daniel, I will take the ownership. Kindly give me some time to cross-check all the tutorials with recent updates. I will keep the community posted.

**Comment by thecodester** [comment]
@Have tutorials been updated?

**Comment by MichaelCzcz** [comment]
@shilpavij have the tutorials been updated?

**Comment by shilpavij** [comment]
Yes, tutorials are updated. Couple of small update will be done when we start our movement on CF.
Do you see specific updates required?

**Comment by thecodester** [comment]
As long as the updates mentioned in this issue have been done, I will close the issue. Thanks.
