### ISSUE TITLE
Connect to SAP HANA, express edition using Python

### ISSUE THREAD

**Issue by abhi7878** [SAPDocuments/Tutorials#3723]
Tutorial URL: https://developers.sap.com/tutorials/hxe-python-connection.html

Please specify the step you are referring to-
Step 5 - 
"To access a specific database, you will use the databasename in the option parameter."

Where is the options parameter here -

from hdbcli import dbapi
connection = dbapi.connect('<server-host>', <port>, '<username>', '<password>')

**Comment by thecodester** [comment]
@Lsubatin @adadouche Can you help with this?

**Comment by Sygyzmundovych** [comment]
@abhi7878 There is a link to documentation at the beginning of the tutorial. You can find parameters page: https://help.sap.com/viewer/0eec0d68141541d1b07893a39944924e/2.0.04/en-US/ee592e89dcce4480a99571a4ae7a702f.html

**Comment by entmike** [comment]
I think it should be something like below if you did the usual tutorials to run HXE in a VM:

`connection = dbapi.connect('hxehost', 39015, 'SYSTEM', 'YourSystemPassword')`

**Comment by thecodester** [comment]
Can you just be more specific as to the issue, if any. Is the documentation not clear and the parameters you guessed/specified did not work for you? 

@Lsubatin Can you also weigh in?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
