### ISSUE TITLE
Create a Workflow Definition Using an External Service

### ISSUE THREAD

**Issue by amitcruz** [SAPDocuments/Tutorials#3726]
Tutorial URL: https://developers.sap.com/tutorials/cp-wf-01-create-definition.html

Please specify the step you are referring to

Images in the tutorials are not displaying. Please fix it as earliest as possible.

**Comment by thecodester** [comment]
Do you see them now?

**Comment by thecodester** [comment]
I believe they are working now. Reopen if you still have issues.
