### ISSUE TITLE
Extend a Workflow Definition with an Exclusive Gateway

### ISSUE THREAD

**Issue by amitcruz** [SAPDocuments/Tutorials#3727]
Tutorial URL: https://developers.sap.com/tutorials/cp-wf-03-add-excl-gw.html

Please specify the step you are referring to

Can't belive the images are gone from Sap developer tutorials. This issue has been happening intermittently. Why this problem is not fixed permanently??

**Comment by thecodester** [comment]
I see the images now. Do you?

I will check why this happens.

**Comment by amitcruz** [comment]
Yes i can see it now.. But this happened last year also. Please find out the root cause.

**Comment by thecodester** [comment]
Will do ...
