### ISSUE TITLE
Display a CDS View Using ALV with IDA

### ISSUE THREAD

**Issue by TonyDag** [SAPDocuments/Tutorials#3728]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-adt-use-cds-view.html

Please specify the step you are referring to

**Comment by TonyDag** [comment]
Hello,
Do you have an example similar to this one where I can pass in a parameter from the ABAP program to a CDS view that has the  with parameters clause and a where clause and then render it with the command
cl_salv_gui_table_ida=>create_for_cds_view( 'your view here ' )->fullscreen( )->display( )? This would be a nice, more real world example to work with.

Thanks in advance,
Tony

**Comment by julieplummer20** [comment]
Hi Tony,
It's a nice idea, but at present I have quite a backlog of tutorials, so I may not be able to do this. I have taken note, however. If I can update it, I will.
Thanks for your feedback. Julie.

**Comment by thecodester** [comment]
Thank you for your feedback. Julie will see if this can be done. In the meantime, I am closing the issue. 

If you still have questions, feel free to reopen the issue.
