### ISSUE TITLE
Define a Simple Data Model and OData Service with CDS

### ISSUE THREAD

**Issue by IObert** [SAPDocuments/Tutorials#3730]
Tutorial URL: https://developers.sap.com/tutorials/odata-05-data-model-service.html

Please specify the step you are referring to: 3

Half of step 3 can be omitted as the builder isn't needed anymore

**Comment by qmacro** [comment]
Fixed, thanks. https://github.com/SAPDocuments/Tutorials/commit/f289ecd8f43a259d079aabb8bf55263ed75deb98
