### ISSUE TITLE
Create a Cube Calculation View (XS Advanced)

### ISSUE THREAD

**Issue by teejaytarun** [SAPDocuments/Tutorials#3732]
Tutorial URL: https://developers.sap.com/tutorials/xsa-graphical-cube-view.html

Step 3: Join Purchase Orders with products dimension

This step doesn't work. No fields are visible in webide full stack in graphical mapping for **Products View** ( it is activated successfully in step 2 and Data preview is working  for Products View) . 
Only an issue in SCP webide full stack. Step 3 Works fine in on-premise HANA.

**Comment by Lsubatin** [comment]
Hi, 
I think I replied on Twitter. This looks like a bug and an incident should be filed.
Thanks, 
Lucia.
