### ISSUE TITLE
Destination only choose SAPCPMobileServices in "Use Mobile Services to Create UI"

### ISSUE THREAD

**Issue by HiArcher** [SAPDocuments/Tutorials#3734]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-create-ui.html

Please specify the step you are referring to: I created API_Portal_Trial, but I can only choose destination SAPCPMobileServices.

**Comment by shilpavij** [comment]
Dear Colleague,

If you have created a destination and saved it with the same name we will get it in mobile service. Are you in trial?

Regards
Shilpa
