### ISSUE TITLE
No mapping fields from 'Front' in Use Mobile Services to Create UI

### ISSUE THREAD

**Issue by HiArcher** [SAPDocuments/Tutorials#3737]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-create-ui.html

In Data Mapping section, it`s blank under Front. It should have some fields to do the mapping, right?
![image](https://user-images.githubusercontent.com/44632698/61776517-c72eb880-ae2d-11e9-88a3-f050762d45d0.png)

**Comment by shilpavij** [comment]
Is your destination correct?

**Comment by HiArcher** [comment]
Now, I have it. I create the destination in the wrong place by directly in 'Destinations'.
