### ISSUE TITLE
No response during register MC in my mobile app: Use Mobile Services to Create UI

### ISSUE THREAD

**Issue by HiArcher** [SAPDocuments/Tutorials#3738]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-create-ui.html

Please specify the step you are referring to Step 3: Scan QR code
In this step, I have the Registration(Android) address: https://mobilecards/configure?serverURL=https://hcpms-i312717trial.hanatrial.ondemand.com&oauthClientId=b9d68bee-2741-4029-a6a5-3fc29a03e1f2
Then I open the Mobile Cards in my mobile, But after I pasted the above address and agree with the agreement, sometimes later, back to the initial screen, can not register.

**Comment by shilpavij** [comment]
You have to subscribe with your ID. Are you doing that

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
