### ISSUE TITLE
Create an Empty SAPUI5 Project in SAP Web IDE

### ISSUE THREAD

**Issue by dtvgit1** [SAPDocuments/Tutorials#3743]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-webide-create-project.html

Step 5: Check the service bindings

Unable to see "- name: dest_mta_app" in the requires section of the mta.yaml file

I have deleted and re-created the project a couple of times. The issue is still the same.

**Comment by dtvgit1** [comment]
I have deleted and re-created the project a couple of times. The issue is still the same.

**Comment by IObert** [comment]
Hi @dtvgit1,

thanks for your comment. You're right, the current phrase is misleading. I intended to say "Create this service binding if it doesn't exist".

I'll update the sentence to make this clear. Thanks!

**Comment by dtvgit1** [comment]
Hi Marius,
Noted. Thanks.
