### ISSUE TITLE
Prepare SAP Web IDE for Cloud Foundry Development

### ISSUE THREAD

**Issue by nunorcsousa** [SAPDocuments/Tutorials#3747]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-webide-open-webide.html

Please specify the step you are referring to

Hello.

I received an error trying to enter the Cloud Foundry endpoint. The error is attached in this message.

Could you guys help me on that. 

Thanks in advance

Nuno Sousa

Attachement:
![ecrancloudfoundry](https://user-images.githubusercontent.com/21372062/61966957-06930b80-afcc-11e9-918b-eeb274ea5e09.PNG)

**Comment by nunorcsousa** [comment]
I subscribed a 90 days trial of Cloud Foundry in the Cockpit and it solved my issue.

**Comment by IObert** [comment]
Hi @nunorcsousa,

I just wanted to answer. Great! Btw, on the right-hand-side, you can see the entire mission which includes all prerequisite tutorials. https://developers.sap.com/mission.sapui5-cf-first.html
