### ISSUE TITLE
Create a Workflow Project from a Template

### ISSUE THREAD

**Issue by louiereyes** [SAPDocuments/Tutorials#3750]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-create-project.html

Please specify the step you are referring to:

Step 3 - Deploy your workflow. This step is not accepting the submitted answers and just responding as "Technical Error". The page has been refreshed several times.

**Comment by thecodester** [comment]
I was able to complete that step. Can you try again?

If still problem, can you clear cache, use new browser, make sure you are logged in?

**Comment by louiereyes** [comment]
Got that to work by closing my browser all together. Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by thecodester** [comment]
:-)
