### ISSUE TITLE
Import Business Rules with Custom Business Object

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#3754]
Tutorial URL: https://developers.sap.com/tutorials/abap-extensibility-cbo-rules-import-rulesproject.html

The box in step 5.6 says: 
Each CDS view is imported into 2 data objects. One is of type structure (name ends with TT) and other is of type table. Table data object refers to the structure data object.

I am pretty sure that the name of the table type should end with _TT, not the structure?

In additional I think in the following steps it is a little confusing. 
In the screenshot of 5.6 Bonus_Plan_TT has type Table, Bonus_Plan has type Structure. In step 5.9 it is vice versa.

**Comment by ArchanaShukla** [comment]
Thank you for the feedback. We will improve the documentation accordingly.

**Comment by MichaelCzcz** [comment]
@ArchanaShukla can we close this issue?

**Comment by ArchanaShukla** [comment]
Tutorial updated. please close the issue
