### ISSUE TITLE
Expose Custom Business Object as External Web Service

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#3755]
Tutorial URL: https://developers.sap.com/tutorials/abap-custom-ui-business-object.html

Step 5: 
This step says "Add your CDS view YY1_BONUSPLAN_CDS by clicking + and Publish it."

I am not sure, but I am wondering if this is correct. Isn't this the Service, which we add? At least coming from the On-Premise World Auto-Exposure scenario (@OData.publish:true) I would assume that YY1_BONUSPLAN is the CDS View and YY1_BONUSPLAN_CDS is the generated service?

I would assume that we are publishing a service in the communication scenario - not a CDS View?

**Comment by Liebherr** [comment]
Hi freilinger,
yes you are right, it's the Service that you are adding to the scenario and exposing via Communication Arrangement later.
The original tutorial https://blogs.sap.com/2017/05/17/part-viii-custom-business-object-exposure-as-external-web-service-bonus-plan/ for this part describes it a little more detailed and correct. 
YY1_BONUSPLAN is the CBO Identifier as well as a generated CDS view, yes (see 2nd hint of Step4 here https://developers.sap.com/tutorials/abap-extensibility-cbo-logic.html).
It will take me some time to improve this tutorial, but your understanding was correct.
Thanks for pointing out the issues.
Best Regards
Ulrike

**Comment by freilinger** [comment]
No Problem, thanks for taking care and generally creating the tutorials.
They help a lot.
Best regards,
Sebastian

Ulrike Liebherr <notifications@github.com> schrieb am Do., 1. Aug. 2019,
09:34:

**Comment by thecodester** [comment]
@Liebherr Just add a comment when we can close this issue. Thanks for your quick response. :-)

**Comment by thecodester** [comment]
@Liebherr Any update on this?

**Comment by Liebherr** [comment]
Hi Sebastian/ @freilinger ,
the wrong wording is corrected now.
Thanks and Regards
Ulrike
