### ISSUE TITLE
Create and expose a custom CDS view

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#3756]
Tutorial URL: https://developers.sap.com/tutorials/abap-extensibility-custom-cds.html

Hi, 
I am missing the done buttons to finish the steps and the tutorials.
Best regards, 
Sebastian Freilinger

**Comment by thecodester** [comment]
@ArchanaShukla I believe this is your tutorial. Can you add validation to this tutorial? Thanks.

**Comment by ArchanaShukla** [comment]
Hello Daniel,
I am responsible for **abap-extensibility-cbo-rules** tutorials. Liebherr, Ulrike is responsible for this tutorial. Please do the reassignment.

**Comment by Liebherr** [comment]
Hi Daniel,
as written by mail, this is @mervey45 's tutorial, please assign her.
Thanks and Regards
Ulrike

**Comment by mervey45** [comment]
Hi @thecodester ,

I created following pull request: #4637. Can you merge it and close this ticket?

Thank you.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
