### ISSUE TITLE
Custom Analytical Queries

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#3757]
Tutorial URL: https://developers.sap.com/tutorials/abap-custom-analytical-queries.html

Hi, 
I am missing the Done Buttons to finish the tutorial. 
Best regards, 
Sebastian Freilinger

**Comment by thecodester** [comment]
@mervey45 Can you add DONE buttons plus at least one validation step? Thanks.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
