### ISSUE TITLE
Custom Analytical Queries Calculated Measures

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#3758]
Tutorial URL: https://developers.sap.com/tutorials/abap-custom-analytical-queries-measures.html

Hi, 
I am missing the Done buttons to finish the tutorial,
Best regards, 
Sebastian Freilinger

**Comment by thecodester** [comment]
@mervey45 Can you add DONE buttons plus at least one validation step? Thanks.

**Comment by mervey45** [comment]
Hi @thecodester,

it‘s done.

Best regards,
Merve

**Comment by thecodester** [comment]
@mervey45  Thanks.
