### ISSUE TITLE
Build a Simple SAP Screen Personas Dashboard

### ISSUE THREAD

**Issue by pataselano** [SAPDocuments/Tutorials#3759]
Dear SAP Screen Personas Team,

Tutorial URL: https://developers.sap.com/tutorials/personas-mobile-workbook-create.html

After create "Create Notification" button with 'S3' as default value of notifaction type, I want create new button for "Create Notification" with 'S1' as default value. Is it possible in same screen?

Is it possible to move that button in main screen (not in IW51 screen)?

Thank you for your help.

Best regards,
Andy Pataselano

**Comment by cjbernal** [comment]
Hi Andy,

You could definitely place some sort of button that navigates to another transaction, called a Transaction button, onto another screen like SMEN.

When it comes to navigating to an "S1" notification vs an "S3" notification, you have a few different options:

1. You could create two different script buttons. Record yourself navigating to the S1 screen and attach that to one of the script buttons. Then do the same for S3 and attach it to the other script button.

2. You could also use our [Viewport feature ](https://www.youtube.com/watch?v=zK2mACslF7Q). Navigate to IW51 and create one viewport with an onLoad script that navigates to an S1 notification and another that navigates to an S3 notification.

The best option is the one that makes the most sense to your users. Do you want them to jump straight into the right screen from SMEN? Do you want them to navigate to IW51 and then click a button to navigate to the right screen? Depending on your use case, one option may also render faster than the other. So, again, this requires a little bit of user input.

Please let me know if you have any further questions.

Kind regards,
Conrad

**Comment by pataselano** [comment]
Hi Conrad,

Thank you for your answer.

Your tutorial in [Tutorial Navigator](https://developers.sap.com/tutorial-navigator.html) is very helpful.  Hope you can create the next tutorial for more complex screens to show the power of SAP screen personas.

Best regards,
Andy Pataselano

**Comment by cjbernal** [comment]
Hi Andy,

Happy to help! We're glad to hear that you are enjoying our tutorials. Happy learning!

Cheers,
Conrad
