### ISSUE TITLE
Set up Secure Tunnel between ABAP System and SAP Cloud Platform (CF)

### ISSUE THREAD

**Issue by jjaimes** [SAPDocuments/Tutorials#3763]
Tutorial URL: https://developers.sap.com/tutorials/cp-connectivity-create-secure-tunnel.html

Please specify the step you are referring to 
**STEP 5:**
When I try to save all data, the system display next rror: 
**Tunnel Information**
StatusFailed to connectTunnel ID
account:///2c408c87-f2e1-xxxx-bb71-f18fccc0e541
Remote Name
connectivitynotification.cf.eu10.hana.ondemand.com

I've tried with **cf.eu10.hana.ondemand.com** and **cf.us10.hana.ondemand.com servers**. Even I've tried to use Europe (Rot) - Trial Region and because of this the field "**Login e-mail**" changes to "**_Subaccount user_**" which and I wrote it the valor S_use_trial (and S_user without the trial word) but the result  is the same. 

My aim is to connect SAP CAI with SAP ECC and these steps I am follow them form the website: https://developers.sap.com/tutorials/cp-connectivity-create-secure-tunnel.html.

Coul you any valuable information ? 
Thanks.

![SAP_CF_Setup2](https://user-images.githubusercontent.com/15263362/62291384-d3200900-b431-11e9-94db-b048b607f6c7.jpg)

![SAP_CF_Setup](https://user-images.githubusercontent.com/15263362/62291283-8b997d00-b431-11e9-97f1-15fe7decbe5c.jpg)

**Comment by jjaimes** [comment]
The issue was because I was trying to connect from home.... I mean I was out of subred area where I am working.

The attachement shows the **OK Connection**.

![SAP_CF_OK](https://user-images.githubusercontent.com/15263362/62297017-58a9b600-b43e-11e9-8af2-d54ff6b926d4.jpg)

**Comment by thecodester** [comment]
@JensHaley FYI

**Comment by JensHaley** [comment]
@jjaimes : Thank you for this feedback.

So the cloud connector was installed on your local PC, right?

I believe that you may have to check your proxy settings at home. In the tutorial, I tried to give this hint in the following note:

> If your internal landscape is protected by a firewall that blocks any outgoing TCP traffic, the connection will only work using an HTTPS proxy. For more information see section [Set up Connection Parameters and HTTPS Proxy](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/db9170a7d97610148537d5a84bf79ba2.html#loiodb9170a7d97610148537d5a84bf79ba2__configure_proxy) in the official documentation.

Did you try that?
