### ISSUE TITLE
Manage Hubspot Instance using SAP API Management

### ISSUE THREAD

**Issue by bstk0** [SAPDocuments/Tutorials#3767]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-openconnectors-hubsopt-manage.html

Please specify the step you are referring to
The API Test Connection is returning "System is up and reachable. However, the ping check responded with code : 404; Message :"

**Comment by shilpavij** [comment]
Dear Colleague,
Its perfectly fine, please go ahead and try your scenario.
We are in the process of checking this error message and I am already talking to implementing teams.
This should not stop you for further execution.

Regards
Shilpa

**Comment by bstk0** [comment]
Hi Shilpa,
Thank you. My scenario that worked well.

Best Regards.
Bisterço
