### ISSUE TITLE
Build a Shopping Fresh Fiori App in SAPUI5

### ISSUE THREAD

**Issue by prabhatpathania** [SAPDocuments/Tutorials#3769]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-create-fioriapp.html

Please specify the step you are referring to
Loading Detail page in the Fiori application.

Execution of ServiceCallout CallGeocodingAPI failed. Reason: ResponseCode 404 is treated as error

It seems that the parameter structure passed in GeoCoding service used in the tutorial has been updated.
Could you please look into this?

**Comment by shilpavij** [comment]
Dear Prabhat,

I cross-checked again and found that it works for me.

So please check again. did you change anything?

Regards
Shilpa
Regards
Shilpa

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
