### ISSUE TITLE
Execute the Image Classification Model Retraining Job

### ISSUE THREAD

**Issue by patrickfontdean** [SAPDocuments/Tutorials#3770]
Tutorial URL: https://developers.sap.com/tutorials/cp-mlf-retrain-image-classification-03.html

Please specify the step you are referring to:

Exercise 8 - Step 14...
Entering CLI Command : cf sapml retraining jobs -m image

I've been getting "PENDING" for over an hour... is there any way to get a more detailed report on what's going on, if it's going to work at all!?

**Comment by thecodester** [comment]
@rbrainey Who will take over these tutorials?

**Comment by rbrainey** [comment]
Hi, I'm not aware of a way to obtain more detailed logging unfortunately.

**Comment by rbrainey** [comment]
I'm closing this, as we don't have a method for obtaining more detailed logs at this time.
