### ISSUE TITLE
Import Tables and Large Datasets (XS Advanced) similar to #3571

### ISSUE THREAD

**Issue by Git-DT** [SAPDocuments/Tutorials#3772]
Tutorial: Import Tables and Large Datasets (XS Advanced)
Tutorial URL: https://developers.sap.com/tutorials/xsa-import-shine-data.html

Error countered when executing build as part of "Step 3: Purge duplicates and Build".
Error message(s):

...
Error: com.sap.hana.di.tabledata: The "include_filter" definitions in the table import files "src/data/load.hdbtabledata" and "src/data/loads/PurchaseDemo.hdbtabledata" use key values that are not disjunct; "src/data/load.hdbtabledata" has an empty filter set [8251511]       at "src/data/load.hdbtabledata" (54:22)    Error: Worker 5 has encountered an error; all remaining jobs will be canceled [8214600]     Error: com.sap.hana.di.tabledata: The "include_filter" definitions in the table import files "src/data/load.hdbtabledata" and "src/data/loads/PurchaseDemo.hdbtabledata" use key values that are not disjunct; "src/data/load.hdbtabledata" has an empty filter set [8251511]       at "src/data/load.hdbtabledata" (14:22)
...

Full log in text file: (Errors are in the last 30 lines or so).
[webide_build_error_log.txt](https://github.com/SAPDocuments/Tutorials/files/3465175/webide_build_error_log.txt)

**Background information:**
Using HANA Express Edition as per tutorial (which I completed a couple of weeks ago. I have the server-plus-apps version):
Install SAP HANA 2.0, express edition on a Preconfigured Virtual Machine
https://developers.sap.com/group.hxe-install-vm.html

Working on this mission (have complete the first few parts before encountering to this problem):
Get Started with XS Advanced Development
https://developers.sap.com/mission.xsa-get-started.html

The tutorial "Import Tables and Large Datasets (XS Advanced)" is part of "Create Calculation Views with XS Advanced". Note that I have (accidentally) missed out the tutorial "AP HANA XS Advanced, Access a classic schema from an HDI container" (hope this isn't the root cause).

**Information about the HANA system**:
(From the HANA Cockpit)
System Usage: DEVELOPMENT
Start Time of First Started Service: Aug 4, 2019, 3:59:54 PM
Start Time of Most Recently Started Service: Aug 4, 2019, 4:25:01 PM
Multiple Hosts: No
SAP HANA Version: 2.00.036.00.1547699771 (fa/hana2sp03)
Last Build Time: Jan 17, 2019, 6:16:43 AM
Platform: SUSE Linux Enterprise Server for SAP Applications 12 SP2
Linux Kernel Version: 4.4.121-92.101-default
Hardware Manufacturer: VMware, Inc.
Installed Plugins: AFL, EPMMDS

In issue #3571 someone asked about the content of the files causing the error. I have included the file and the link to where it is held.

Zipped Data File URL given in the tutorial: 
https://github.com/SAP/com.sap.openSAP.hana5.templates/raw/hana2_sps01/ex2/core-db/data.zip 
The actual file for reference: 
[data.zip](https://github.com/SAPDocuments/Tutorials/files/3465167/data.zip)

Hope this helps in finding a fix for this issue.
`Error: com.sap.hana.di.tabledata: The "include_filter" definitions in the table import files "src/data/load.hdbtabledata" and "src/data/loads/PurchaseDemo.hdbtabledata" use key values that are not disjunct; "src/data/load.hdbtabledata" has an empty filter set [8251511]  `

**Other notes and observations:**
Virtual Machine (VM) running OpenSUSE has been allocated 6 cores and 14 GB RAM.
On starting up I usually leave the VM running for about an hour to allow it to settle down (and for the laptop fans to stop running at maximum).
WebIDE is used on a second laptop which is on the same network.
Often get Gateway Timeout errors. After this nothing works. I find I have to issue the command HDB stop via an SSH client, wait and then reboot the VM. Just saying this in case people out there have a solution for this.

**Comment by Lsubatin** [comment]
Thanks for adding the details. Can you try this file instead? https://github.com/SAP/com.sap.openSAP.hana5.templates/blob/hana2_sps03_2/ex2/core-db/data.zip

14 GB of RAM is way below the recommended sizing. 16GB is the minimum but 24 will give you less trouble. Even with 16GB I would recommend stopping apps you are not using (e.g., the cockpit). Also, HDB stop is not necessary. Chances are the XSA apps are crashing and there should not be a need to restart the database.

**Comment by Git-DT** [comment]
Hello Lucia. Thanks for the update.

Once the XSA apps crash do they restart themselves or is some intervention required from me?

On sizing I found this...

Recommended VM Size | Server-only plus Application Function Library, PAL | Tenant DB* | XSA | Cockpit | Web IDE | SAP HANA Streaming Analytics | SAP HANA Interactive Education | SAP Enterprise Architecture Designer | Total Memory Consumption
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
8.0 GB | 2.7 GB |   |   |   |   |   |   |   | 2.7 GB
8.0 GB | 2.7 GB | 1.8 GB |   |   |   |   |   |   | 4.5 GB
12.0 GB | 2.7 GB | 1.8 GB | 2.5 GB |   |   |   |   |   | 7.0 GB
12.0 GB | 2.7 GB | 1.8 GB | 2.5 GB | 2.3 GB |   |   |   |   | 9.3 GB
**12.0 GB** | 2.7 GB | 1.8 GB | 2.5 GB | 2.3GB | 1.3 GB |   |   |   | 10.6 GB
16.0 GB | 2.7 GB | 1.8 GB | 2.5 GB | 2.3 GB | 1.3 GB | 1.0 GB |   |   | 11.6 GB
16.0 GB | 2.7 GB | 1.8 GB | 2.5 GB | 2.3 GB | 1.3 GB | 1.0 GB | 1.0 GB |   | 12.6 GB
16.0 GB | 2.7 GB | 1.8 GB | 2.5 GB | 2.3 GB | 1.3 GB | 1.0 GB | 1.0 GB | 1.3 GB | 13.9 GB

https://help.sap.com/viewer/9e4243e92f244537b2164a57a405a9fd/2.0.040/en-US
I should be okay with a 12GB VM as I'm not running anything past the WebIDE. However I would love to have enough RAM to assign 24GB but this 5 year old laptop is fixed as 16GB max.

I'll try the new data zip file shortly and post another update.

**Comment by Git-DT** [comment]
Update on the new data.zip file. [data (2).zip](https://github.com/SAPDocuments/Tutorials/files/3486777/data.2.zip)

In short, it was successful.

In more detail, as per the steps in the tutorial "Import Tables and Large Datasets (XS Advanced)" due to the state of the data folder from previous tutorials it is still necessary to delete some files and folders. Here is the old instruction from the tutorial showing what to delete.
![DeleteFiles](https://user-images.githubusercontent.com/53184311/62786784-373e6f00-babb-11e9-8b21-c78607d1e81f.png)

With the new file it was still necessary to delete the FLIGHT.hdbcds but is this is now in a folder with related files so I deleted the whole folder. Also, the header and item csv files still need to be deleted, additionally all files related to the old purchase order database created in a previous tutorial need to be deleted too. This leaves the new folder PurchaseOrder that contains the new database and data from the new data.zip file.

My data folder now looks like this.
![62787339-67d2d880-babc-11e9-91fa-b9752e062b43](https://user-images.githubusercontent.com/53184311/62787627-04957600-babd-11e9-9717-106c3cf238ab.png)

Before I close this issue can I ask if the tutorial will be updated to make it more clear on how to download the correct data.zip file from github? 

In any case thanks Lucia for the quick solution.

**Comment by Git-DT** [comment]
Problem is solved so closing.
