### ISSUE TITLE
Navigate to Blockchain Services on SAP Cloud Platform

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#3774]
Tutorial URL: https://developers.sap.com/tutorials/blockchain-navigate-cloudplatform.html

Please specify the step you are referring to: Step 4
Issue:
Can I rename my previously created global account name? I don't want to my S to be displayed in any web pages.

thx, greg

**Comment by heytombeck** [comment]
Hi Greg,

With a trial account on SAP Cloud Platform, the global account name is fixed. The good news though, this is only exposed to our service admins (SAP staff) and not made publicly available. 

With a paid account, this can be changed by raising a support ticket to the SAP Cloud Platform team:
https://support.sap.com/en/contact-us.html

Let me know if you need anything else.

Thanks

Tom

**Comment by greg2git** [comment]
Hi Tom,

appreciate the response.

thx, greg
