### ISSUE TITLE
Navigate to Blockchain Services on SAP Cloud Platform

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#3775]
Tutorial URL: https://developers.sap.com/tutorials/blockchain-navigate-cloudplatform.html

Please specify the step you are referring to: Step 6

The step contains this statement: "integration with HANA database." 
My question: Which blockchain service provides this integration?

Thx, greg

**Comment by heytombeck** [comment]
Hi Greg - the HANA integration is blockchain technology agnostic, meaning that you can choose from Hyperledger Fabric, MultiChain, or Quorum here. Many of our users are running with MultiChain for now, if that helps.

The blockchain adapter information can be found here: https://help.sap.com/viewer/c5bee9180afc4a4e93a0742bb352db11/1.0/en-US

And then the wider integration documentation can be found here:
https://help.sap.com/viewer/7a74204803ef48dc85332199dc251e8a/BLOCKCHAIN/en-US

I hope that helps.

Tom

**Comment by greg2git** [comment]
Hi Tom, have tried MultiChain multiple times but got stuck with peers not running. Let me close this issue, so it doesn't clutter the repository.
Thx, greg
