### ISSUE TITLE
Configure Smart Data Integration with the SAP HANA Service

### ISSUE THREAD

**Issue by ssurampally** [SAPDocuments/Tutorials#3781]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-connect-sdi.html
Hi Lucia, Just a clarification in Step 2: Download and install the DP agent On Premise  ---- Is that step required when I am connecting to SQL server DB  on AWS?  using SDI on SCP, is there any other way to replicate data into HANA Service on SCP?

**Comment by Lsubatin** [comment]
Hi Sreekanth, you will need something to expose the data from the source DB. You could also use SLT to replicate data into HaaS and use cross-container access to get the data from the classic schema.

I would recommend adding this as a question in the community so the HANA PM folks could chime in.

**Comment by ssurampally** [comment]
sorry I have not made my question clear Lucia. Actually I wanted to go ahead with SDI on SCP, but my source is my SQL DB which is in AWS.(it is not On-premise as described in your tutorial). So now, your tutorial is still applicable in this case?  I mean I have to install DP agent and continue with ??

**Comment by Lsubatin** [comment]
That's correct, it doesn't matter where the OS is sitting :)

**Comment by ssurampally** [comment]
Ok, got it Thanks Lucia. I will continue with your tutorial.

**Comment by PROD-BR3-MRI** [comment]
I Lucia, I have successfully check all the steps off your tutorial, but when I try to open the remote source I've got the following error message :  The requested backend service did not succeed
{"error":{"code":"500","message":{"lang":"en-US","value":"Error while executing a DB query"}}}

What does it mean ? 

Thank you per advance 

Maxime
