### ISSUE TITLE
Deploy Your First SAPUI5 App to Cloud Foundry

### ISSUE THREAD

**Issue by xujian-jh** [SAPDocuments/Tutorials#3782]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-webide-new-app.html

Please specify the step you are referring to

Step 4: Deploy the archive to Cloud Foundry

You will see a success message in the log once the deployment finished.

 No `Open`  in the popup (top-right corner) to start your application.

**Comment by IObert** [comment]
Good catch! The popup has been removed, I'll update the tutorial
