### ISSUE TITLE
Add a User Task to Your Workflow - Add Image to a step

### ISSUE THREAD

**Issue by sandeep-tds** [SAPDocuments/Tutorials#3785]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-add-usertask.html

Please specify the step you are referring to
Under Step 4: Add a User Task to Workflow go to S No: 6.

Can you please add a screenshot of the pop-up? 

I was using a trial account to do this tutorial and it took me a lot of time to figure out the correct value to be entered. 

A screenshot of the pop-up in question would be extremely helpful.

**Comment by AstridHerbst** [comment]
Hi, 

Please see the new tutorials at: https://developers.sap.com/group.cp-workflow-cf.html 

Best regards,
Astrid

**Comment by sandeep-tds** [comment]
Thank you so much for updating the documentation @AstridHerbst
