### ISSUE TITLE
Deploy Application to Cloud Foundry with SAP Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by ravipativenu** [SAPDocuments/Tutorials#3789]
Tutorial URL: https://developers.sap.com/tutorials/s4sdkjs-deploy-application-cloud-foundry.html

Please specify the step you are referring to

npm run ci-build && npm run ci-package

Giving Error:

===========================================
> mkdir -p deployment/ && cp -r node_modules dist package.json index.html deployment/ && rm -rf deployment/node_modules && npm i --production --prefix deployment

The syntax of the command is incorrect.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! businesspartners@1.0.0 ci-package: `mkdir -p deployment/ && cp -r node_modules dist package.json index.html deployment/ && rm -rf deployment/node_modules && npm i --production --prefix deployment`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the businesspartners@1.0.0 ci-package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\VENU\AppData\Roaming\npm-cache\_logs\2019-08-09T02_37_04_874Z-debug.log
===========================================

**Comment by marikaner** [comment]
Hello, thank you for raising this issue. Are you running this in a Git Bash as pointed out by this note?

> Note: We are aware, that the ci-package script currently does not work when executed in Windows’ CMD. Currently, the easiest workaround is to install a bash on your system (by default, git for Windows comes with Git Bash) and configure npm to execute scripts in that bash. This can be done by executing npm config script-shell <P:\ath\to\your\bash.exe>.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
