### ISSUE TITLE
Join a MultiChain Network

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#3790]
Tutorial URL: https://developers.sap.com/tutorials/blockchain-mc-node-joins-network.html

Please specify the step you are referring to: Step 4

Getting this error message in the browser when opening the dashboard: 
404 Not Found: Requested route ('maas-dashboard.cfapps.us10.hana.ondemand.com') does not exist.

**Comment by thecodester** [comment]
@heytombeck @joseprados can you answer?

**Comment by thecodester** [comment]
@joseprado Can you update your profiel to have your name/SAP and if possible an image? Thanks

**Comment by heytombeck** [comment]
@greg2git - Hi Greg, sorry about this. Is this still happening to you? I've replicated the steps in my own test account (as a regular user) and I'm able to access the dashboard.

**Comment by greg2git** [comment]
Hi Tom,

i had to check the flag for "Access your data with scope 'openid" and that seems to have cleared the issue. thx for the quick response.

br, greg
