### ISSUE TITLE
step6 can't finished.

### ISSUE THREAD

**Issue by superwangnan** [SAPDocuments/Tutorials#3791]
Tutorial URL: https://developers.sap.com/tutorials/cp-wf-02-add-user-task.html

Please specify the step you are referring to
in step 6, I can't deploy my UI app. in webide, the deploy to cloud platform menu item is grey.
<img width="823" alt="error" src="https://user-images.githubusercontent.com/20192234/62796036-b1e2ab00-bb0a-11e9-91ac-0ac7f09ca67c.png">

**Comment by qmacro** [comment]
Hello - issues here are for technical / content based problems with the tutorials. I would recommend that you reach out with this question on the SAP Community Q&A - there is a specific tag for SAP Cloud Platform Workflow. You're more likely to get an answer there and also other folks will benefit from the question and the answers. Good luck! 

By the way, I notice from the screenshot that you have put the genericusertask folder within the workflow project folder structure. It needs to be at the top level of your workspace - see the instructions in Step 2. Cheers!
