### ISSUE TITLE
Create a Workflow Project from a Template

### ISSUE THREAD

**Issue by poonamassudani** [SAPDocuments/Tutorials#3792]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-create-project.html

Please specify the step you are referring to

when I create a Project from template , enter project name and workflow name and click finish, the process keeps running , never creating the workflow .

I tried from IE as well as chrom , but does not work , there is no error message as well.

Please suggest .

**Comment by AstridHerbst** [comment]
Hi, 

Please see the new tutorials at: https://developers.sap.com/group.cp-workflow-cf.html 

Best regards,
Astrid
