### ISSUE TITLE
Use JPA in Custom Logic

### ISSUE THREAD

**Issue by mchytracek** [SAPDocuments/Tutorials#3793]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html

I followed the tutorial in Step 3 and modified the generated persistence.xml adding  transaction-type="JTA". But the file is re-generated when the project is built and the modifications are gone.

So the following steps in the tutorial are not working

**Comment by renejeglinsky** [comment]
Hi @mchytracek ,
I am checking with my colleagues. I'll get back to you then.
In the meantime, I saw there were an issue with the same tutorial, step 3, in the past. Maybe you want to check it out:
https://github.com/SAPDocuments/Tutorials/issues/3111

Regards,
René

**Comment by mchytracek** [comment]
I have already seen #3111 but this is an other issue where the JPA sources were not generated. This have nothing to do with this issue.

**Comment by gregorwolf** [comment]
Maybe https://stackoverflow.com/questions/17331024/persistence-xml-different-transaction-type-attributes is a solution as in a JavaEE environment like TomEE the default seems to be JTA.

**Comment by gregorwolf** [comment]
When I deploy the mtar built from the version https://github.com/gregorwolf/bookshop-java/tree/cae12576f515ac0684be9ba4389947c8b65172ef of my tutorial project it's running fine. But it's not working when I start from Web IDE as Java App.

**Comment by thecodester** [comment]
@renejeglinsky Any update here? Can we close?

**Comment by renejeglinsky** [comment]
Hi @mchytracek ,

I am sorry but I can't reproduce what you describe. When I edit the generated persistence.xml and build the `srv` module again, my edit stays.
Could you try again? I went through the whole tutorial today and it works fine.

Regards,
René

**Comment by mchytracek** [comment]
Hi René,

You are right! I have done the tutorial once again and everything is fine.
Maybe i missed something in the tutorials prev steps because now the generated sources are art of the /src directory and not part of the /target.

So everything is fine, you can close this issue. Sorry for the unnecessary effort on your side.

Regards,
Michael
