### ISSUE TITLE
Grant Requesting MultiChain Node Permission to join a MultiChain Network

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#3796]
Tutorial URL: https://developers.sap.com/tutorials/blockchain-mc-node-grant-permissions.html

Please specify the step you are referring to Step 2
After getting this: 
"PERMISSIONS
Grant Permissions
Permissions for address '1Nm...' successfully set."

Still getting this: 
"Peers
No connections to peers"

Tried closing the browser, clearing cookies and re-logging into the SAP Could multiple times. Cannot continue with the tutorial until this works.
thx, gm

**Comment by thecodester** [comment]
@joseprados can you answer?

**Comment by greg2git** [comment]
resolved, thx for trying to help.
