### ISSUE TITLE
SAP HANA XS Advanced, Creating an HTML5 Module

### ISSUE THREAD

**Issue by badichiniran** [SAPDocuments/Tutorials#3797]
Tutorial URL: https://developers.sap.com/tutorials/xsa-html5-module.html

Please specify the step you are referring to
step 2 is different from what I see in my environment
in the Authorization and Trust management
where is choose New Instance is dont have option to select Plan= Space.
this is what i have.
what should i choose?
![image](https://user-images.githubusercontent.com/4293806/62924568-0b700180-bdb9-11e9-9dc2-baf5b3c573a7.png)

**Comment by Lsubatin** [comment]
What environment is this?
You can choose application. This is the scope of the UAA service.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
