### ISSUE TITLE
Cannot view CLA documents

### ISSUE THREAD

**Issue by pacaceres** [SAPDocuments/Tutorials#3799]
I am asked to sign a CLA page stating I read the following documents which do not exist!

https://github.com/SAPDocuments/Tutorial-Contribution/blob/master/contributing.md
https://github.com/SAPDocuments/How-To-Contribution/blob/master/contributing.md

Please fix the broken links or do not ask users to sign a CLA.

**Comment by thecodester** [comment]
Why are you writing this in this repo, when the issue is in those 2 repos. And why are creating PRs in those repos?
