### ISSUE TITLE
SAP HANA XS Advanced, Creating a Node.js Module

### ISSUE THREAD

**Issue by badichiniran** [SAPDocuments/Tutorials#3802]
Tutorial URL: https://developers.sap.com/tutorials/xsa-xsjs-xsodata.html

Please specify the step you are referring to
step 6
I'm running the web module but I'm getting "Unauthorized" response
any idea why?

**Comment by miteshjpatel** [comment]
I am having same issue.

**Comment by Lsubatin** [comment]
Hi folks - Unauthorized could very well be that you are accessing the node.js endpoint instead of the web one after configuring the routes and uaa. I cannot guess just from the word "Unauthorized" though

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
