### ISSUE TITLE
Deploy an App to SAP Cloud Platform Cloud Foundry Environment

### ISSUE THREAD

**Issue by marinalan** [SAPDocuments/Tutorials#3803]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-dev-02-deploy-app.html

Please specify the step you are referring to

Can not do step 4
I deployed app, but each time I attempt to start , it then shows "Stopped", shows in red that there was some error, but I can not find on what error it complains

**Comment by qmacro** [comment]
Hello - issues here are for technical / content based problems with the tutorials. 

I would recommend that you reach out with this question on the [SAP Community Q&A](https://answers.sap.com/index.html). You're more likely to get an answer there and also other folks will benefit from the question and the answers. Good luck!
