### ISSUE TITLE
Expose a Standard Core Data Service for ABAP Environment

### ISSUE THREAD

**Issue by prasenjitsbist0103** [SAPDocuments/Tutorials#3807]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-business-service-provisioning.html

Please specify the step you are referring to- Test yourself.

`service Z_Testyourself  is not valid as there is space ,

**Comment by mervey45** [comment]
Hi @prasenjitsbist0103, 

thank you for your feedback. We' ll update this. 

Best regards, 
Merve

**Comment by thecodester** [comment]
@mervey45 Has this been updated?

**Comment by mervey45** [comment]
@thecodester This has been updated

**Comment by mervey45** [comment]
We can close this issue.
