### ISSUE TITLE
MovieLens with SAP HANA APL Recommendation (MovieLens SQL)

### ISSUE THREAD

**Issue by Devanther12** [SAPDocuments/Tutorials#3812]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aa-movielens-sql-04.html

Under MovieLens with SAP HANA APL Recommendation (MovieLens SQL) - Step 7 "Run the Algorithm" following Error occurs: 
Could not execute 'call sap_pa_apl."sap.pa.apl.base::CREATE_RECO_MODEL_AND_TRAIN" ( apl_movielens_function_header , ...' in 1.998 seconds . 
SAP DBTech JDBC: [423]: AFL error: "SAP_PA_APL"."sap.pa.apl.base::CREATE_RECO_MODEL_AND_TRAIN": line 29 col 4 (at pos 1243): "SAP_PA_APL"."sap.pa.apl.base.internal::GET_PROCNAME_4": line 74 col 6 (at pos 3615): "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE": line 156 col 5 (at pos 5073): Registration of AFLLANG wrapper procedure "SAP_PA_APL"."APL_P_4ED8A3AC9E0B2BFA87A63345F3FFF929B52C7258D0D43AEA226F94BD6FAB44F3_221984327305" failed with error 'inconsistent parameter description'.

**Comment by Devanther12** [comment]
Solution: https://answers.sap.com/questions/12850453/sap-hana-express-apl-recommendation.html

**Comment by thecodester** [comment]
Answers is generally the best place to go for general questions on the technology not related to bugs in the tutorials. Since you asked this on Answers I am closing this issue.

@jarjarbentley Please pass this on to whoever is maintaining this tutorial.
