### ISSUE TITLE
Bad Gateway 502 - Use the Application Router in Cloud Foundry to Connect to ABAP System

### ISSUE THREAD

**Issue by eguo** [SAPDocuments/Tutorials#3813]
Hi, I followed tutorial URL: https://developers.sap.com/tutorials/cp-connectivity-consume-odata-service-approuter.html I have configured and deployed this tutorial to both trial and canary CF.

I am seeing Bad Gateway 502 error on Step 7.4 in both trial and canary CF. 

Log entry:
`2019-08-19T09:05:28.92-0400 [APP/PROC/WEB/0] OUT {"written_at":"2019-08-19T13:05:28.927Z","written_ts":1566219928927000000,"csn_component":"-","correlation_id":"7adb95c2-5f32-4d78-5e8b-434ce80285f9","type":"log","logger":"nodejs-logger","layer":"/Handler","level":"error","container_id":"10.0.138.234","component_type":"application","component_id":"04fcb282-3a4a-496b-8add-306150e9fdb0","component_name":"approuter-demo","component_instance":-1,"source_instance":-1,"organization_id":"-","organization_name":"-","space_id":"a6e13550-6076-4644-88e3-a348ece88835","space_name":"dev","request_id":"7adb95c2-5f32-4d78-5e8b-434ce80285f9","msg":"GET request to / completed with status 502 - error while forwarding request to http://abap-as-eu01:443/sap/opu/odata/sap/API_BUSINESS_PARTNER: getaddrinfo ENOTFOUND abap-as-eu01 abap-as-eu01:443"}`

Trouble shooting I have done so far:

1. The cloud connector monitor doesn't show any traffics.
2. When I use the cloud connector UI to disconnect the secure tunnel, I still get same log entry.

What can I do to further trouble shooting this issue?

Thanks,
Eddy

**Comment by JensHaley** [comment]
Hi Eddy,

I assume you successfully completed [tutorial https://developers.sap.com/tutorials/cp-connectivity-configure-fiori-reference-apps.html](https://developers.sap.com/tutorials/cp-connectivity-configure-fiori-reference-apps.html).

The error message in your log suggests that the virtual endpoint `abap-as-eu01 abap-as-eu01:443` which you defined in [this step](https://developers.sap.com/tutorials/cp-connectivity-create-secure-tunnel.html#caeace56-86d0-4a79-9ff6-eb4887504173) is not found. Hm.

If your secure tunnel works (ABAP System in status `reachable` in CC UI, subaccount in status `connected`in CC UI) I would next look for a typo. The URL you used when creating the destination in the cockpit must match the virtual host and port you used when you set up your secure tunnel in the CC. 

Sometimes you can have connection problems if you have your CC installed on your PC and if you do home office using a VPN connection to your intranet where the ABAP system is. You will need to use an HTTPS proxy in such cases, see [here](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/db9170a7d97610148537d5a84bf79ba2.html#loiodb9170a7d97610148537d5a84bf79ba2__configure_proxy).

Hope this helps.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by eguo** [comment]
@JensHaley thanks for your reply. Sorry for reply late.  Specifying the approuter version to ^6.1.0 was what overcame my 502 error:
`git diff package.json
diff --git a/address-manager/approuter/approuter/package.json b/address-manager/approuter/approuter/package.json
index dd2caeb..649cf84 100644
--- a/address-manager/approuter/approuter/package.json
+++ b/address-manager/approuter/approuter/package.json
@@ -1,7 +1,7 @@
 {
   "name": "approuter",
   "dependencies": {
-    "@sap/approuter": "*"
+    "@sap/approuter": "^6.1.0"
   },
   "scripts": {
     "start": "node node_modules/@sap/approuter/approuter.js"`

**Comment by JensHaley** [comment]
@eguo thanks for letting me know.

When I tested this scenario, I used approuter version 5.3.0, see step 5:
[step 5](https://developers.sap.com/tutorials/cp-connectivity-consume-odata-service-approuter.html#2e60351d-a38c-48c8-a15b-2aefa3035e21)

So before you just didn't specify any version?
It would be great if you could try version 5.3.0 of the approuter as described in my tutorial, then I would know if there is any open issue I need to follow up to (you use 6.1.0).
