### ISSUE TITLE
Access a Classic Schema from SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by ssurampally** [SAPDocuments/Tutorials#3814]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-access-cross-container-schema.html

Please specify the step you are referring to : Step 3
While creating the cups, you just provided user id and password. I am wondering without providing HANA host and port, how do we get access to the database? 
I remember that, In XSA on premise world, we provide the host and port while setting external connection, isn't that required in HANA cloud in cf environment?

**Comment by ssurampally** [comment]
I am unable to proceed with completion of this tutorial.

**Comment by Lsubatin** [comment]
Hi Sreekanth, just like it shows in the tutorial, you do not need the port and host. They are taken from the primary target HDI container.
This question belongs in the community (I have answered it there before, at least twice). This is for issues related to the tutorial, so closing it.

**Comment by ssurampally** [comment]
Ok got it, Sorry I did not know that Lucia. I thought I can ask clarifications on the tutorials also. From now on, I will post my questions in the community.
