### ISSUE TITLE
Add a User Task and Generic UI to Your Workflow

### ISSUE THREAD

**Issue by agraricha** [SAPDocuments/Tutorials#3815]
Tutorial URL: https://developers.sap.com/tutorials/cp-wf-02-add-user-task.html

Please specify the step you are referring to 
Step 5. 
manifest.json is giving errors
![image](https://user-images.githubusercontent.com/44371178/63341605-e1cf5100-c349-11e9-985f-d1e2e4d76150.png)
Missing property _version

**Comment by qmacro** [comment]
Hi @agraricha sorry for the delay in responding! You can safely ignore these flagged issues - they only occur sometimes and don't affect what we're learning in this tutorial. I will add a note to the tutorial text to this effect. Thank you!

**Comment by qmacro** [comment]
Note added https://github.com/SAPDocuments/Tutorials/commit/f7cf74a09153e6fb84565bfbc629098113508d20
