### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by entmike** [SAPDocuments/Tutorials#3816]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html

Tutorial still references old SP3 docker image tag rather than `2.00.040.00.20190729.1`.

**Comment by JCurrie27** [comment]
Closing 3816. Image tags updated from "036..." to "040..." in hxe-ua-install-using-docker, hxe-ua-install-using-docker-xsa.
