### ISSUE TITLE
Create Sales Order App with SAP Cloud Platform Rapid Application Development by Mendix

### ISSUE THREAD

**Issue by yeeteeho** [SAPDocuments/Tutorials#3820]
Tutorial URL: https://developers.sap.com/tutorials/mendix-salesorders.html

Step 3 can't be done.
In Mendix studio Pro I get the following error message when importing the generated module package:
"Loading the module failed. The package could not be imported, because it was created with version 7.5.1 of mendix modeler. please open it in any version in the range from 7.23.0 to 7.23.99 first".

**Comment by ShiraManas** [comment]
Hi,
We ran through the steps in the tutorial with the latest version of Mendix Studio Pro and we could not reproduce the issue. Please update to the latest version of Mendix Studio Pro that is available in the portal. Then complete the steps in the tutorial from the beginning.

Thanks,
Shira

**Comment by MichaelCzcz** [comment]
@yeeteeho Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
