### ISSUE TITLE
Extend a Workflow Definition with an Exclusive Gateway

### ISSUE THREAD

**Issue by DuoBelt** [SAPDocuments/Tutorials#3821]
Tutorial URL: https://developers.sap.com/tutorials/cp-wf-03-add-excl-gw.html

Please specify the step you are referring to
Step 5: Connect the exclusive gateway to the new user task

Address the SequenceFlow5 flow:
Select the line marked SequenceFlow5 and you’ll see that it too can have properties – indeed, now there are two flows from this exclusive gateway, the Condition property is mandatory.

**Condition property** is missing in Workflow Editor ?
Do i need to use the code editor?

**Comment by qmacro** [comment]
Hello. This is for technical issues relating to tutorial content (e.g. spelling mistakes, incorrect information). May we please suggest you ask your question in the SAP Community Q&A, where you're more likely to receive an appropriate answer and also others will benefit from both your question and the answers. Thank you. -> https://answers.sap.com/index.html
