### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by JNeil-tech** [SAPDocuments/Tutorials#3823]
Tutorial URL: https://developers.sap.com/tutorials/xsa-create-user-provided-anonymous-service.html
Regarding
Step 2: Create a Schema and table and Import data,
after creating the schema and creating the table, the schema isn't listed in the catalog at bubble 4. I can connect to the schema (I called my schema "TECH_ACADEMY") and select * from product_segment; successfully. 
Also having trouble in
Step 5: Check or modify the MTA.yaml file
I am unable to Build the db module. 
From the console:
Error: Error executing: GRANT "SELECT","SELECT METADATA" ON SCHEMA "TECH_ACADEMY" TO "undefined#OO" WITH GRANT OPTION; (nested message: invalid user name: undefined#OO: line 1 col 62 (at pos 61))grantor service: "ServiceName_1", type: "sql", user: "SYSTEM"

PS - I admire your work; I'm a big fan. 👍 💯

**Comment by Lsubatin** [comment]
The undefined there is weird... Can you see the HDI container and explore it? Can you please add some screenshots of the structure of the project and confirm you can see the container in a question in the community and at mention me? I'm on vacations so not monitoring it these days. These forum is for fixes to the tutorials themselves and I cannot involve other folks to help.

PS thanks a ton :D

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
