### ISSUE TITLE
Add Data to Your OData Service

### ISSUE THREAD

**Issue by S0003904187** [SAPDocuments/Tutorials#3826]
Tutorial URL: https://developers.sap.com/tutorials/odata-06-add-data-odata-service.html

Please specify the step you are referring to: 4

When I select the table to create the entries an internal error occurs, as from attachment
[readme01.docx](https://github.com/SAPDocuments/Tutorials/files/3537587/readme01.docx)

**Comment by qmacro** [comment]
Hello. This is for technical issues relating to tutorial content (e.g. spelling mistakes, incorrect information). May we please suggest you ask your question in the SAP Community Q&A, where you're more likely to receive an appropriate answer and also others will benefit from both your question and the answers. Thank you. -> https://answers.sap.com/index.html
