### ISSUE TITLE
Build and Deploy a Java Application

### ISSUE THREAD

**Issue by WheresTheMoneyLebowski** [SAPDocuments/Tutorials#3829]
Tutorial URL: https://developers.sap.com/tutorials/cp-java-reference-app-deploy.html

Hello, 

Step 4: Bind the Application to a Database.

When trying to bind the deployed web application to the database schema a dialog window shows up asking for the login credentials (Username, Password). I tried to enter my login credentials for the cloud as well as my username in conjunction with the password which I have specified when setting up the database schema. However, it seems that the connection to the database could not be established as the login credentials are not valid. 

Thus my question: Which username are we supposed to use for the database connection? 

The attached screenshot shows the corresponding dialog window. 

Thank you!

Jakub

![new_binding](https://user-images.githubusercontent.com/36352210/63698383-02eae280-c81f-11e9-9f85-ead68ff67636.png)

**Comment by shankarigr** [comment]
Hi,

Can you please delete your HANA instance and try recreating it again?

Thanks and Regards,
Shankari G R

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
