### ISSUE TITLE
Get Started with SAP Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by bvarwig** [SAPDocuments/Tutorials#3833]
Tutorial URL: https://developers.sap.com/tutorials/s4sdkjs-getting-started.html

Please specify the step you are referring to step4:

isn't it better to use option ```--save``` in the ```npm install``` command: ```npm install @sap/cloud-sdk-core --save```

Regards Britta

**Comment by mr-flannery** [comment]
Hi Britta,

Thank you for your feedback! Since [version 5.0.0](https://blog.npmjs.org/post/161081169345/v500), `--save` is the default option when calling `npm install`, i.e. the respective dependency will be added to your project's `package.json` automatically. 

Best regards
Dennis

**Comment by bvarwig** [comment]
oh, I did not know this, as i am a newbee to nodejs and somone told me to not forget the save option. 

So i will close the issue.
