### ISSUE TITLE
Setup AWS - Create your IAM policy, role and user

### ISSUE THREAD

**Issue by anushka-singh** [SAPDocuments/Tutorials#3835]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aws-eml-01.html

Please specify the step you are referring to:
Tutorial 2 Step 4: Create a Role in IAM

Steps to reproduce:
Followed the steps as mentioned in Tutorial from Tutorial 2 through 9. 
Error at Tutorial 9 step 5 line 5. get_role function in get_execution_role not found. Can be ignored and can move to future steps. But got stuck later on. 

Expected result: follow tutorial step by step and everything works
Actual result: got error because of permission roles of user

Workaround: Need to do the following - 
Create an extra role in IAM apart from sap-hxe-eml-sagemaker-role.
Follow same steps.
Name : ecsTaskExecutionRole
Attach Policies: AmazonECS_FullAccess | AmazonEC2ContainerRegistryPowerUser
Edit Trust Relationship to add: ec2.amazonaws.com |  ecs-tasks.amazonaws.com

**Comment by jarjarbentley** [comment]
you may also need to add  firewall rules opening ports 53075 and 39030 in AWS as a custom TCP rule.  please let me know.
