### ISSUE TITLE
Tour the SAP Community

### ISSUE THREAD

**Issue by srivas-s** [SAPDocuments/Tutorials#3836]
Tutorial URL: https://developers.sap.com/tutorials/community-start.html

Once all steps are completed, blogger permission and badge not generated

**Comment by thecodester** [comment]
Badges are distributed once a week (soon this will be immediate and automatic).

@WorkJerryJanda Can you comment on when blog permissions are granted?

**Comment by WorkJerryJanda** [comment]
If the steps were followed, permissions should be granted right away...although you may need to log in and out again. Please see the answer here and confirm that you did everything: https://answers.sap.com/questions/12848865/i-ask-the-sap-community-for-help.html. If you have, please tell me your profile name on SAP Community. Thanks!

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
