### ISSUE TITLE
Create a Workflow Definition Using an External Service

### ISSUE THREAD

**Issue by AbhijitNilegaonkar** [SAPDocuments/Tutorials#3839]
Tutorial URL: https://developers.sap.com/tutorials/cp-wf-01-create-definition.html

Please specify the step you are referring to
I get an error on Step 8 
Error message:
The destination 'Northwind' could not be found. Create it or check the spelling.
GET unknown /V3/Northwind/Northwind.svc/Products(1)?$format=json

Step 7 
is where this URL is provided. I made sure the spellings are correct no spaces
URL 
/V3/Northwind/Northwind.svc/Products(${context.ProductID})?$format=json

**Comment by AbhijitNilegaonkar** [comment]
Destination was missing. Followed this tutorial and it fixed the problem. 
https://developers.sap.com/tutorials/hcp-create-destination.html

**Comment by thecodester** [comment]
@qmacro FYI

**Comment by qmacro** [comment]
That's the right course of action @AbhijitNilegaonkar.

@thecodester the hcp-create-destination tutorial is already listed as a pre-requisite for this one.
