### ISSUE TITLE
Change from mock server to live OData service

### ISSUE THREAD

**Issue by EkaterinaArena** [SAPDocuments/Tutorials#3840]
Tutorial URL: https://developers.sap.com/tutorials/webide-live-odata.html

Please specify the step you are referring to 'Step 4: Validate the data source'
In the tutorial it states:
"Double click on the metadata.xml file to open it. Copy the NavigationProperty element in the XML under the entity SetsType."
At the current version of metadata.xml there is no entity "SetsType".
The actual existing entity :    <EntityType Name="Toys"> contains
   <NavigationProperty Name="PartOf" Relationship="6d651f640cf8df81121e844f.ToysPartOfParts" FromRole="FromRole_ToysPartOfParts" ToRole="ToRole_ToysPartOfParts"/>

Could you please verify and update the tutorial?

thank you and regards
Ekaterina
![2019-08-30_14-31-34](https://user-images.githubusercontent.com/26485662/64020850-ed353000-cb32-11e9-877a-e8b473377664.jpg)

**Comment by thecodester** [comment]
@IObert Is this something you handle? If not, do you know who?

**Comment by IObert** [comment]
I'll check with @mhassett92

**Comment by IObert** [comment]
Closing the issue as we decided to remove the tutorial. Sorry for the inconvenience!
