### ISSUE TITLE
homebrew's java8 cask no longer available

### ISSUE THREAD

**Issue by tcmb** [SAPDocuments/Tutorials#3841]
Hi, in the file `tutorials/s4sdk-setup/s4sdk-setup.md` the line `brew cask install caskroom/versions/java8` should be changed to `brew cask install adoptopenjdk8`.

The cask `java8` referred to the Oracle JDK and is no longer available in homebrew.

(I can open a PR if you want, but the README says you prefer issues to be opened.)

**Comment by MatKuhr** [comment]
Thank you for raising this. I'll update it but it will take some time until it shows on the tutorial.

**Comment by tcmb** [comment]
This is fixed now with the PR, thanks!
