### ISSUE TITLE
Get Your Hands on SAP Leonardo IoT Foundation Software and Hardware

### ISSUE THREAD

**Issue by thomasalexneuhaus** [SAPDocuments/Tutorials#3842]
Tutorial URL: https://developers.sap.com/tutorials/iot-express-1-buy-sapstore.html

Please specify the step you are referring to

The full configuration are not in part of this steps. The turtorial is not running, when you not make the configuration of cloud service:

Getting Started with SAP Leonardo IoT:
https://help.sap.com/viewer/195126f4601945cba0886cbbcbf3d364/1904a/en-US

Enable SAP Cloud Platform Internet of Things Service for Cloud Foundry:
https://help.sap.com/viewer/c48328a1bee749da9902d52f080dba0d/Cloud/en-US

yo have no changes do this !!! Please Add this to the turtorial!

Then also that you get >> Security >> Adminstration Rigth for the Subaccount!!!!

**Comment by marcuscbehrens** [comment]
Hi Thomas, thanks for your comments. We had included the instructions you mention as pre-requisites in the sub-sequent tutorials that follow this one. If someone only wants to try out device management from SAP he for example will find what is needed to configure on the next tutorial and he would not have to go through enabling leonardo iot. This first tutorial is really just a placeholder for a trial offering, that we do not offer today. I hope you still got through all of them successfully - if not please feel free to search for answers or post new questions in the community at: https://developers.sap.com/topics/leonardo-iot.html#community.

On the last point - Unfortunatly to see the subscriptions one has to be security administrator for the cloud foundry subaccount. For people who follow this tutorial they will be the security administrator. But I think it would be good to add it to the subsequent tutorial, that the user has to be in that role to be able to see the subscrptions - thanks for the tip - i will add it. Rgeards, AMrcus

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
