### ISSUE TITLE
Create a Simple IoT Device Model

### ISSUE THREAD

**Issue by thomasalexneuhaus** [SAPDocuments/Tutorials#3843]
Tutorial URL: https://developers.sap.com/tutorials/iot-express-2-create-device-model.html

Please specify the step you are referring to

Also here the importent step for SAP Leonardo IoT ist not write!
The connection between an SAP Leonardo IoT and SAP Cloud Platform Internet of Things for the Cloud Foundry Environment ist not exist!

https://help.sap.com/viewer/a7172eb02bf54229add4664fff702676/Cloud/en-US/de42d2f505144e439b924fc9a3b58584.html

**Comment by marcuscbehrens** [comment]
Hi, thanks for your comment. Have you checked all the prerequisites? Number 3 is referring to what you are suggesting, is it not? Regards, Marcus

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
