### ISSUE TITLE
Build an IoT Condition Monitoring App

### ISSUE THREAD

**Issue by thomasalexneuhaus** [SAPDocuments/Tutorials#3844]
Tutorial URL: https://developers.sap.com/tutorials/iot-express-5-use-webide-template.html

Please specify the step you are referring to

The step one and two are not enough
Step 1: Start the Web IDE Full-Stack and Step 2: Enable the Leonardo IoT feature

Take the also the Configure SAP Web IDE for SAP Leonardo IoT in the Turtorial:
https://help.sap.com/viewer/195126f4601945cba0886cbbcbf3d364/1908b/en-US/3802b7cf023a4331a36248b5d021dc23.html

**Comment by marcuscbehrens** [comment]
Yes, you are right. I will mention that al sections of the getting started guide have to be completed in the next update.

**Comment by thecodester** [comment]
@marcuscbehrens  Do tutorials still need to be updated? Can I close this issue?

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

@marcuscbehrens Please make any updates you think are needed
