### ISSUE TITLE
Create and expose a custom CDS view

### ISSUE THREAD

**Issue by ZacharyLeahan** [SAPDocuments/Tutorials#3847]
Tutorial URL: https://developers.sap.com/tutorials/abap-extensibility-custom-cds.html

Please specify the step you are referring to

This document is not clear if it is for S/4 on prem or S/4 cloud.

**Comment by anfisc** [comment]
The document as such is for S/4 cloud.
However the first 5 steps that describe how to create a custom CDS view using the Key User Tools can also be used in an on-premise System.
From this point on however you would have to use transaction /iwfnd/maint_service to publish the generated OData Service.

**Comment by MichaelCzcz** [comment]
@ZacharyLeahan Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
