### ISSUE TITLE
Create an ABAP Project in ABAP Development Tools (ADT)

### ISSUE THREAD

**Issue by rafaelfigueiredo-l** [SAPDocuments/Tutorials#3850]
Hi,

I'm following this tutorial https://developers.sap.com/tutorials/abap-create-project.html and needs logon data. I tried my logon data that I'm using to access developers.sap.com but the access still fail. Is this correct?

 **Logon to system NPL failed (partner '127.0.0.1:3300' not reached)**

Other issue and I don't know if is related to the first is eclipse showing an error with this message:
Location 'C:\Users\User\AppData\Roaming\SAP\Common' does not point to a SAP GUI configuration file

**Comment by rafaelfigueiredo-l** [comment]
Hi @julieplummer20. Following the Tutorial was not very explicit how to get the logon data. After some research I understand that I need to install miniSap and then use the default logon data generated for developer user. Now I'm ok with and this thread can be closed.

I can achieve this following the tutorial bellow created by you. Thanks twice.
https://blogs.sap.com/2017/09/04/newbies-guide-installing-abap-as-751-sp02-on-linux/

**Comment by julieplummer20** [comment]
Glad to hear, @rafaelfigueiredo-l. Thanks for closing. Hope you enjoy!
