### ISSUE TITLE
Create a Business Service Using CDS

### ISSUE THREAD

**Issue by SumaiyaPK** [SAPDocuments/Tutorials#3852]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-01-create-business-service.html

Step 4: Test run the service.
after running the service, I get the below error.
"bash: Best: command not found".

Also when I click on the "Run console URL", I am not able to see the Odata.
The below error is displayed.
"404 Not Found: Requested route ('8ifliqfwezrijhmj-bookshop-srv.cfapps.sap.hana.ondemand.com') does not exist." 
![Capture](https://user-images.githubusercontent.com/40350644/64235015-1f6cd600-cf15-11e9-961a-6661566a7901.PNG)
![Odata](https://user-images.githubusercontent.com/40350644/64235061-36132d00-cf15-11e9-960a-6073a5ca37f4.PNG)

**Comment by renejeglinsky** [comment]
Hi @sumaiyaPK, 
I just tested it and it worked for me.
Which OData did you choose during project generation?
Has the CDS build been successful?

Regards,
René

**Comment by SumaiyaPK** [comment]
Hi Rene

Thank you for responding.
I have selected OData Version : OData V2.
Yes, The build was successful, but couldn’t open the link that shows OData.


Thanks & Regards!
Sumaiya PK
SAP Labs Pvt Ltd,
138 EPIP, Whitefield, Bangalore - 560066, India
☎ +91-8095433599

[sap-logo]

**Comment by renejeglinsky** [comment]
Can you give it a try again? 
Maybe this issue was on the infrastructure side and not with the tutorial itself.

**Comment by SumaiyaPK** [comment]
Hi Rene

I tried this in Fiori-dispatcher "https://webidecp-fiori.dispatcher.int.sap.hana.ondemand.com/" (instead hanatrial), now it works.
Really not sure, why it wasn't working in the trial instance.

Thank you for the support.

Thanks and regards
Sumaiya
