### ISSUE TITLE
Create a Calculation View with Differential Privacy

### ISSUE THREAD

**Issue by JCurrie27** [SAPDocuments/Tutorials#3853]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-calculation-view-differential-privacy.html

Please specify the step you are referring to:
Step 5: Configure the HANA Analytics Adapter

Hi Lucia: FYI a link in step 5 is not rendering correctly in output.

**Comment by Lsubatin** [comment]
pushed change, thanks!
