### ISSUE TITLE
SAP HANA XS Advanced, Creating an HDI Module

### ISSUE THREAD

**Issue by jjmiquel** [SAPDocuments/Tutorials#3855]
Tutorial URL: https://developers.sap.com/tutorials/xsa-hdi-module.html

Hi,
I have a general question about the HDI-Container and the database schemas.
The HDI Containers at run time have their own isolated schema, so if I am looking forward to creating and manipulate enterprise data where should I store it? 
Should I create another independent db schema?

Best regards,
Juan José Miquel

**Comment by Lsubatin** [comment]
Hi Juan José, 
 An HDI container consists of both the design time artifacts and the physical artifacts. That includes a schema and tables, for example. Not sure what you mean by manipulation of data, but you would do that in the HDI container like with any other database schema, just like it's shown on steps 4, 5 and 6 on the tutorial you for which you are creating an issue.

This kind of question belongs in the SAP Community (answers.sap.com), as this is for problems with the content in the tutorials. I'd also suggest taking a look at the Developer guide for XS Advanced in the SAP Help. 

Regards, 
Lucia Subatin
