### ISSUE TITLE
Import your SAP Build project into SAP Web IDE

### ISSUE THREAD

**Issue by erxivi** [SAPDocuments/Tutorials#3857]
Tutorial URL: https://developers.sap.com/tutorials/build-import-webide.html

Please specify the step you are referring to : 

Hi gurús, at step : 

Step 7: Select a project to import

I try to select prototypes availables to my user and there are not. An error message tolds me : 

![2019-09-04 18_25_59-SAP Web IDE Full-Stack](https://user-images.githubusercontent.com/54840790/64273586-e5fe8f80-cf41-11e9-87fe-da5c646de285.png)

So for that I can't continue.

Thanks for your time.

**Comment by rbrainey** [comment]
This tutorial has been removed as the capability is no longer present in Web IDE.
