### ISSUE TITLE
Add a Model and Test the SAPUI5 App

### ISSUE THREAD

**Issue by EkaterinaArena** [SAPDocuments/Tutorials#3858]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-webide-setup-datasource.html

Please specify the step you are referring to 'Step 4: Test the application in the Cloud Foundry environment'

Hi Colleagues,
following the tutorial group on the trial account (cf/neo).
Actual result at attempt to run the application in WEB IDE:
8:15:10 AM (HTML5 application runner) Starting module "/mta_app/app".
8:15:30 AM (HTML5 application runner) html5_runner_log_cf_push_failure
8:15:30 AM (HTML5 application runner) Could not create the 'mtaapp-destmtaapp-I0XXXXX-workspaccbfy+3un2tokz56a' instance of the 'destination' service type for the 'dest_mta_app' resource. Service destination does not exist
Please, see also the attachments.

![subaccount_destinations_NEO](https://user-images.githubusercontent.com/26485662/64316876-6068f700-cfb6-11e9-9502-262eb0a7d8ba.jpg)

![subaccount_destinations_CF](https://user-images.githubusercontent.com/26485662/64316908-770f4e00-cfb6-11e9-8226-7624ee271139.jpg)

![space_service_instances_created](https://user-images.githubusercontent.com/26485662/64316912-7a0a3e80-cfb6-11e9-89d3-2f1491a0831f.jpg)

thank you
Ekaterina

**Comment by IObert** [comment]
Hi @EkaterinaArena,

sorry for the late reply! It seems that the destination service is not activated in your trial account. Can you [check your entitlements](https://blogs.sap.com/2019/06/05/the-new-way-to-manage-entitlements-and-quotas-on-sap-cloud-platform-cockpit/) to make sure the "destination" service plan is available in your subaccount?

**Comment by IObert** [comment]
Will close due to inactivity. Please re-open the issue if it still persists.

**Comment by jakes2255** [comment]
Thank you Marius, adding destination service plan helped me!
