### ISSUE TITLE
Enable the Push Notification service for your iOS app

### ISSUE THREAD

**Issue by agiguere** [SAPDocuments/Tutorials#3862]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-hcpms-push-notifications.html

Please specify the step you are referring to

If your SCP trust is set to custom to proxy the authentication to an external IdP, this is probably the case of most enterprise App, that means we cannot used SAP ID service to assign the notification user role, how we do ? Does that means we will need to have 2 IdP ? thanks

**Comment by KevinMuessig** [comment]
Hi @agiguere,

I am currently traveling but will take a look as soon as I get back home.

Just to be clear: You want to send notifications over Mobile Services to your app? You have configured the APNs with the certificate in Mobile Services as well? Now you want to assign the Notification User Role in SCP but using your own IDP instead of the SAP IDP?

Thanks

**Comment by agiguere** [comment]
Hi Kevin, yeah, I have worked in the past with APNS (without SAP), I know
how it works,

I can see that my app successfully push it's token to SCPms, I am also able
to take that token and with a custom JavaScript program I made, push it to
my App (just by sending it to APNS)

now I want to send it from SCPms cockpit, and also I want to test your REST
API, cause in real life we will probably dispatch notifications from an
ABAP system.

What is strange is that I don't have any option to send the push
notification in the cockpit, in your blog I can see "Send Notifications",
mine is blank

[image: Screen Shot 2019-09-18 at 6.25.21 PM.png]

I registered an iPhone device and I can see the token being uploaded
successfully

[image: Screen Shot 2019-09-18 at 6.25.49 PM.png]


my push config looks like this, we are not using certificate but
token-based (latest&greatest)

[image: Screen Shot 2019-09-18 at 6.33.46 PM.png]


everytime I log through SCPms is with my Windows users, cause I set up the
trust in SCP with IAS which delegate the authentication to a corporate IdP
(Azure)

[image: Screen Shot 2019-09-18 at 6.35.32 PM.png]


you can see here my SCP trust is configure with IAS (our trusted IdP)

and then I have some role mapping,

very strange, let me know what you think ?


For the REST API
https://api.sap.com/api/mob_PushRuntimeAndAdminV1/resource

if I want to call these API to send notification (with SAP ID, I guess you
only need a username & password for basic auth)

but real life scenario, most chance enterprise are not using SAP ID, they
use they own IDP,

I can't use basic auth to send a notification if my trust is configured
with SAML

hope it's clear, very appreciated the help

thanks

alex

**Comment by agiguere** [comment]
quick update, I can now see the push notification in SCPms, I think it was
because I only add 1 device register, now we have multiple and I can see it

if I tried to sent a notification, it says notification failed, can't find
why or where to check for root cause analysis ?

thanks

**Comment by thecodester** [comment]
@KevinMuessig Thanks for addressing this issue. Any updates?

**Comment by KevinMuessig** [comment]
Hi @agiguere,

sorry for my late reply, I was traveling a lot. So you have the button in Mobile Services now to send notifications?

Also when you send a notification you get an error? - Could you please attach the error?

**Comment by MichaelCzcz** [comment]
@agiguere Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
