### ISSUE TITLE
Set Up the SAP HANA Plugin for Microsoft Visual Studio -> on MacOS

### ISSUE THREAD

**Issue by CBasis** [SAPDocuments/Tutorials#3864]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-visual-studio.html

The tutorial doesn't mention MacOS so it might not be possible to follow the tutorial with MacOS and VisualStudio(Mac).

I fail because there is no "ServerExplorer" like described for the WindowsVersion.

Does anyone know if there is just another way to reach the same goal .. or if not:   It should be mentioned that VisualCode is not an option on MacOS for this tutorial.
(The DBeaver steps of the other tutorial went fine on MacOS)

**Comment by JCurrie27** [comment]
Hi CBasis - We've been asking around but this tutorial hasn't been tested on a Mac in-house. Perhaps others in the community have tried this and have answers for you. I recommend posting this question to the Community Q&A page: [Questions & Answers](https://developers.sap.com/topics/sap-hana.html#community).
Closing.
