### ISSUE TITLE
How to download and install the HANA Eclipse plugin

### ISSUE THREAD

**Issue by CBasis** [SAPDocuments/Tutorials#3865]
Tutorial URL: https://developers.sap.com/tutorials/hxe-howto-eclipse.html

Just a little typo:
In Step 7 it's written:
"For Docker environments follow instructions in 7B."

The Docker descriptions comes in the next step, but this step is named "8" in the meantime.

**Comment by thecodester** [comment]
@Lsubatin Can you help here?

**Comment by Lsubatin** [comment]
Pushed changes 20 mins ago but they are not reflecting

**Comment by thecodester** [comment]
I see the updates 

@Lsubatin Thanks for updating
