### ISSUE TITLE
Create ABAPDoc Comments in Your Class

### ISSUE THREAD

**Issue by vgup** [SAPDocuments/Tutorials#3867]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-create-abapdoc.html

Please specify the step you are referring to - Step 9

What is the correct answer. Why is the following incorrect
"! @parameter PLANETYPE | <p class="shorttext synchronized"> Type of plane.</p>

**Comment by thecodester** [comment]
@julieplummer20 Please let me know if I can help. According to the rule, the period after plane is not supposed to be included. The same is true for the space before Type -- and though we ignore extra whitespace, I don't think we ignore word breaks.

@vgup Do you want to try again without space and period?

**Comment by vgup** [comment]
The recommended solution worked

**Comment by WKRazik** [comment]
Sorry but i have the same issue , the below is not validated as a valid answer  
"! @parameter PLANETYPE | Type of plane
i don't know why ?

Tutorial URL: https://developers.sap.com/tutorials/abap-dev-create-abapdoc.html
 Step 9

**Comment by julieplummer20** [comment]
Hi WKRazik, You need to follow Step 4: "Synchonize short texts":
Equivalent code in my class= 

 "! @parameter lt_result | <p class="**shorttext synchronized**">Table of invoice items</p>

HTH Julie.
