### ISSUE TITLE
Installing SAP HANA HDB Client (Windows)

### ISSUE THREAD

**Issue by danielva** [SAPDocuments/Tutorials#3869]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-hdb-client-windows.html

Step 5
sudo <unzipped_filepath>/HDB_CLIENT_<version>/hdbuninst

I don't believe sudo is a windows command.

**Comment by JCurrie27** [comment]
Hi Dan - Yes the above command should not include "sudo". Step 5 should read:
<unzipped_filepath>/HDB_CLIENT_/hdbuninst
We're updating the tutorial. Thanks.
