### ISSUE TITLE
Learn about OData Fundamentals

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#3879]
Tutorial URL: https://developers.sap.com/tutorials/odata-01-intro-origins.html

Please specify the step you are referring to
Steps 3 & 4

The links indicated in these two steps don't currently (Sept. 11, 2019) show what the tutorial has. 

The file at https://services.odata.org/V3/Northwind/Northwind.svc/ only shows one long string in Firefox:
"DefaultCategoriesCustomerDemographicsCustomersEmployeesOrder_DetailsOrdersProductsRegionsShippersSuppliersTerritoriesAlphabetical_list_of_productsCategory_Sales_for_1997Current_Product_ListsCustomer_and_Suppliers_by_CitiesInvoicesOrder_Details_ExtendedsOrder_SubtotalsOrders_QriesProduct_Sales_for_1997Products_Above_Average_PricesProducts_by_CategoriesSales_by_CategoriesSales_Totals_by_AmountsSummary_of_Sales_by_QuartersSummary_of_Sales_by_Years"

And the file at https://services.odata.org/V3/Northwind/Northwind.svc/$metadata is completely empty.

If this isn't just a temporary glitch at services.odata.org, the tutorial might need to be updated.

Cheers
Bärbel

**Comment by thecodester** [comment]
@BaerbelW Both links return for me properly formatted content. Can you check again? If the problem persists, please reopen the issue.

@qmacro FYI

**Comment by BaerbelW** [comment]
Thanks! It seems to be a browser issue where Firefox (68.0.2esr) doesn't show/format the content while Chrome (Version 76.0.3809.100) opens the file and displays the expected content, albeit with this note at the top "This XML file does not appear to have any style information associated with it. The document tree is shown below."

Could it make sense to add a note in the tutorial about potential browser issues and to try with another one if the files don't open properly?

Cheers
Bärbel

**Comment by thecodester** [comment]
Well ... I opened them in Firefox (version 69.0 64-bit, Windows) and it displayed fine, formatted and all.

**Comment by qmacro** [comment]
Hi @BaerbelW ! Love that you're trying out these tutorials. 

I think that if we started to add notes to account for glitches in software that we don't control, the tutorials would become unwieldy. BTW, the note about not having any style associated" is standard behaviour from Chrome, and isn't seen as an issue (altho I do agree it's not particularly attractive! :-))
