### ISSUE TITLE
Set Up Connection Between Google BigQuery and SAP HANA

### ISSUE THREAD

**Issue by miturbe** [SAPDocuments/Tutorials#3882]
Tutorial URL: https://developers.sap.com/tutorials/gcp-hxe-evt-bq-1.html

Within step 2, the instructions state "Copy the contents into the editor".
However, the "contents" is an IMAGE! So there is no way to copy/paste and the contents of setup.sh are nowhere to be found...

**Comment by Lsubatin** [comment]
The tutorial starts with "this tutorial can only be completed at TechEd", and the availability of such script is one of the reasons why. Unfortunately, we cannot share that script.

However, the script does the same that is described here: https://codelabs.developers.google.com/codelabs/sap-hana-connect-to-bigquery/#0
