### ISSUE TITLE
Setup AWS - Create a SageMaker Notebook

### ISSUE THREAD

**Issue by neilobremski** [SAPDocuments/Tutorials#3883]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aws-eml-02.html

Step 4 confirmation is broken. I'm successfully getting the tensorflow and Python versions but pasting the Python version into the confirmation box results in a "wrong answer".

I'm pasting in:

```Python 3.6.5 :: Anaconda, Inc.```

The terminal looks like this:

```
sh-4.2$ source activate tensorflow_p36
(tensorflow_p36) sh-4.2$ python -c 'import tensorflow as tf; print(tf.__version__)'
1.14.0
(tensorflow_p36) sh-4.2$ python --version
Python 3.6.5 :: Anaconda, Inc.
(tensorflow_p36) sh-4.2$
```

I see the tutorial shows tensorflow version 1.12.0 so possibly the Python version check is for an earlier version. The error that results is _Sorry, that’s incorrect. Please try again._

**Comment by jarjarbentley** [comment]
im looking into the verification now.  Thank you.

**Comment by MichaelCzcz** [comment]
@jarjarbentley any updates?

**Comment by jarjarbentley** [comment]
This issue has not been something I can re-create.  Please go back a few steps and try the copy paste again.
