### ISSUE TITLE
Setup AWS - Create a SageMaker Notebook

### ISSUE THREAD

**Issue by xupiter** [SAPDocuments/Tutorials#3884]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aws-eml-02.html

Validation for "Step 4" is always failing.

**Comment by thecodester** [comment]
@jarjarbentley: I tested and the tutorial is working according to the current rules. Please check.

**Comment by jarjarbentley** [comment]
tutorial is working as expected for me.
