### ISSUE TITLE
Prepare and upload your Dataset for Image Classification Retraining

### ISSUE THREAD

**Issue by sebastianduque7** [SAPDocuments/Tutorials#3885]
Tutorial URL: https://developers.sap.com/tutorials/cp-mlf-retrain-image-classification-02.html

Hi all:

It seems that the storage service is down. I've done all the steps, but when i try to upload data to the fs, it does not work.

I've initialized the storage as in this guide:
https://help.sap.com/viewer/a86b12f81f424c45a0e7c83c1d5025c4/1908B/en-US/65df4d78cb6b485aab2c9fb11ae89ac1.html

I got the following message:
 "message": "The endpoint is ready to use."

But I havent been able to execute the final step to PUT images in the FS (I've tried with CF and MC).

Finally, when I try to enter to the endpoint, via web browser I get:

No se puede encontrar esta página (...storage.trial.eu-central-1.aws.ml.hana.ondemand.com) (Page cannot be found).

Regards,

Sebastián

**Comment by jarjarbentley** [comment]
if you restart tutorial and this occurs again please reopen issue.
