### ISSUE TITLE
Check your environment (MovieLens SQL)

### ISSUE THREAD

**Issue by ssineriz** [SAPDocuments/Tutorials#3890]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aa-movielens-sql-01.html

At step #2: the repository https://tools.hana.ondemand.com/oxygen/ doesn't contain the SAP HANA Tools Package (anymore?)
It can be found currently only in the https://tools.hana.ondemand.com/2019-03 repository, which doesn't install on Eclipse 2019-06.
Eclipse Error:
An error occurred while collecting items to be installed
session context was:(profile=D__Programs_Eclipse_jee-latest-released_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.andmore.base,0.5.0.201605181018

**Comment by jarjarbentley** [comment]
very sorry for the issue.  we will re-write this tutorial link to reference the repository correctly.
