### ISSUE TITLE
Create an Account on the Gateway Demo System - not accepting URL entered

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#3891]
Tutorial URL: https://developers.sap.com/tutorials/gateway-demo-signup.html

Please specify the step you are referring to
Step 5 and the validation at the end

It doesn't accept the URL but it's not clear why as it should be the correct one:
https://developers.sap.com/tutorials/gateway-demo-signup.html

There were similar issues with other tutorials where the validation only worked if the solution was typed in exactly as expected (upper/lower case, line breaks....). But I'm not sure what the issue might be with the URL as I already tried with different options like all in upper case (however unlikely!) and without the "https://" at the beginning.

What else can I try?

**Comment by BaerbelW** [comment]
I tried again today and while doing that realised that I had pasted the wrong link in the message above and - even though I think that it's unlikely - I may have accidentally tried with that link in the tutorial as well. 

When I tried now with the following link, it worked:
https://sapes5.sapdevcenter.com/sap/bc/gui/sap/its/webgui?sap-client=002&sap-language=DE 

It however gives an error if I try with "language=EN" which I think is what I may have used yesterday as I remember switching the login language from the default "DE" to "EN".

**Comment by thecodester** [comment]
I'm not sure what might have happened, but it should work as long as you have the right domain and path -- what you type in the querystring should make no difference. I did exactly that -- with `?sap-client=002&sap-language=ENasdfadsdassadasdsdadsdasdasdasdadssffasfafffassdfsdf` as the query string -- and I get completed.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
