### ISSUE TITLE
cannot find created communication scenario when creating new communication arrangement

### ISSUE THREAD

**Issue by i042416** [SAPDocuments/Tutorials#3892]
dear colleagues,

thanks a lot for creating such helpful tutorials, I learned a lot through them.

One issue I found:

url: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

step9: it says we should use the communication scenario created in previous tutorial:https://developers.sap.com/tutorials/abap-environment-business-service-provisioning.html

![clipboard1,1](https://user-images.githubusercontent.com/5669954/64794717-82163f80-d5af-11e9-8b61-9acd231e3472.png)

# My issue:

I did create the service scenario according to the tutorial:

![clipboard2,2](https://user-images.githubusercontent.com/5669954/64794606-55fabe80-d5af-11e9-9258-cf9ebf9f1e4a.png)
![clipboard3,3](https://user-images.githubusercontent.com/5669954/64794612-572beb80-d5af-11e9-9e3b-4cb7a0ba31b6.png)
![clipboard4,4](https://user-images.githubusercontent.com/5669954/64794614-57c48200-d5af-11e9-8901-3be16ba92f69.png)

and had pressed the button "publish locally":

![clipboard5,5](https://user-images.githubusercontent.com/5669954/64794616-58f5af00-d5af-11e9-83b1-d9bc466b0e7f.png)

and saw the successful publish message:

![clipboard6,6](https://user-images.githubusercontent.com/5669954/64794618-598e4580-d5af-11e9-840a-b0f96da6ce5f.png)

url:
https://325df18f-0b6b-4d85-a127-ee6ad7437a7c.abap.eu10.hana.ondemand.com

unfortunately, when I tried to create a communication arrangement, I cannot find any scenario I created in my local package ZJERRY although they are activated and published locally, why?

![clipboard7,7](https://user-images.githubusercontent.com/5669954/64794791-9fe3a480-d5af-11e9-97dd-baa8b8eca45d.png)

all my communication scenario are created and stored here:

![clipboard8,8](https://user-images.githubusercontent.com/5669954/64794718-82aed600-d5af-11e9-9b5a-53ebaaac09c7.png)

your help will be really appreciated!

Best Regards,
Jerry

**Comment by mervey45** [comment]
Hi @i042416 , 

it seems like you didn't activate your communication scenario.
Can you try this out?

Best regards, 
Merve

**Comment by i042416** [comment]
Hi Merve,

Thanks a lot for your help. I close the issue.

Best Regards,
Jerry
