### ISSUE TITLE
Install SAP HANA, express edition on Ubuntu on Google Cloud Platform (XS Advanced applications)

### ISSUE THREAD

**Issue by jiayiwangjw** [SAPDocuments/Tutorials#3893]
Tutorial URL: https://developers.sap.com/tutorials/hxe-gcp-ubuntu-xsa.html

Please specify the step you are referring to

in step 2, I input 
wget --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie"
https://download.oracle.com/otn/java/jdk/8u221-b11/230deb18db3e4014bb8e3e8324f81b43/jre-8u221-linux-x64.tar.gz

it shows the below error:

Resolving download.oracle.com (download.oracle.com)... 23.218.108.34
Connecting to download.oracle.com (download.oracle.com)|23.218.108.34|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/akam/otn/java/jdk/8u221-b11/230deb18db3e4014bb8e3e8324f81b43/jre-8u221-linux-x
64.tar.gz [following]
--2019-09-13 00:14:22--  https://edelivery.oracle.com/akam/otn/java/jdk/8u221-b11/230deb18db3e4014bb8e3e8324f81b43/jr
e-8u221-linux-x64.tar.gz
Resolving edelivery.oracle.com (edelivery.oracle.com)... 23.56.112.136, 2600:1409:a:791::366, 2600:1409:a:78f::366, .
..
Connecting to edelivery.oracle.com (edelivery.oracle.com)|23.56.112.136|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://login.oracle.com:443/oam/server/obrareq.cgi?encquery%3Dh9qUwGGlB6WYI2GQiQCaawFE28MgkmAqoR%2B63n3kxl
S1rx9dQig8YSnxt8jowAv497COeKTzCoCLy0s8g04o33Gp7kaBeEfBWyDldwd0kjfAfxmqOD2V4GmNNhcq4quYVWaM6%2BMqTaeFnp2xSBT2QIVu6rNIW
%2BK87bvFDgEa%2FQ2oeU1gB8jFcfRRBKoFn9DyD110slbffNH9jbc5BrC%2BjRmtFwPVPiGv0w4fLZNvbny2lnscivYcpA5pD%2FnQjiHmP4pNdqkHHY
Mj0XVE2vbpzIfRHVpHQVRuwoWE3pYu4%2FfXE2wauzodKPn8o2Xcx%2B6pC9K6tyYA5jAHoVkJbAtaYj61NBHvhbaDHCwTEYQZN63yk4Epao2Q4jKAKI8
tEjnmA7A48GI9esDsCywJvCOEP0vSXTVdDUFMjuQkOIZhD3ThgDfH2XkfnrtQQ4Z8caqHe81A5cZ6l4dFUbHo535dD0FW5fGh3C39wsNPVYjwzNBk%2Bx
1CqEWZPThXuWm7pZewEFEdxqLc7DyZh7tE8SIPvQ%3D%3D%20agentid%3Dedelivery-extprod%20ver%3D1%20crmethod%3D2%26cksum%3Dcad2e
f25a58d14032a2a22556cded966aae80ab4&ECID-Context=1.005%5EaGYogNb7a6KaETu1US0002C5001lBi%3BkXjE.......
Resolving login.oracle.com (login.oracle.com)... 209.17.4.8
Connecting to login.oracle.com (login.oracle.com)|209.17.4.8|:443... connected.
HTTP request sent, awaiting response... 401 Authorization Required
Username/Password Authentication Failed.

**Comment by Lsubatin** [comment]
Updated instructions to manual download/upload
