### ISSUE TITLE
Continue Your OData Exploration with EPM

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#3894]
Tutorial URL: https://developers.sap.com/tutorials/odata-02-exploration-epm.html

Please specify the step you are referring to
Step 6: Reduce the number of properties returned

When using the URL as shown in the tutorial to return data for the first entry, the "AverageRating" is "0.00" and no reviews are found: 
https://sapes5.sapdevcenter.com/sap/opu/odata/sap/EPM_REF_APPS_SHOP_SRV/Products?$top=1&$format=json&$expand=Supplier,Reviews&$select=AverageRating,Name,StockQuantity,Supplier/Name,Supplier/FormattedAddress,Reviews/UserDisplayName

Playing with the parameters in the URL and changing it to "$top=15" or "top=15&$skip=8" finds some entries with ratings, including the one shown in the tutorial:
https://sapes5.sapdevcenter.com/sap/opu/odata/sap/EPM_REF_APPS_SHOP_SRV/Products?$top=15&$format=json&$expand=Supplier,Reviews&$select=AverageRating,Name,StockQuantity,Supplier/Name,Supplier/FormattedAddress,Reviews/UserDisplayName

How about adding a note that if no ratings are returned to try with different values for top (and/or skip)?

**Comment by qmacro** [comment]
Thanks @BaerbelW that's a good suggestion. Interestingly I just tried the URL above (the first one in your comment) and I get a product with 3 reviews. Are you still getting one with no reviews and average rating 0.00? I'm wondering why that might be. 

In any case, I will add a note to this effect. Thank you!

**Comment by qmacro** [comment]
Done https://github.com/SAPDocuments/Tutorials/commit/c6d23a443ca1adcc29383ce162ad5a0cf3745e56
