### ISSUE TITLE
Deploy Application to Cloud Foundry with SAP Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by mskergeth** [SAPDocuments/Tutorials#3901]
Tutorial URL: https://developers.sap.com/tutorials/s4sdkjs-deploy-application-cloud-foundry.html

At Step 1, the command to configure bash a shell is missing the set keyword.
Current command: npm config script-shell <P:\ath\to\your\bash.exe>
Correct command: npm config **set** script-shell <P:\ath\to\your\bash.exe>

**Comment by mr-flannery** [comment]
Thanks for the heads-up, I will fix it!

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
