### ISSUE TITLE
Create Communication System to Connect to SAP Cloud Platform ABAP environment.

### ISSUE THREAD

**Issue by prithamr** [SAPDocuments/Tutorials#3905]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-s4hanacloud.html

Please specify the step you are referring to
Step 1: Download trust
Open SAP Cloud Platform Cockpit 

Can you specify the URL of the SAP Cloud Platform Cockpit or specify how to find this URL

**Comment by mervey45** [comment]
Hi @prithamr 

the URL is following: https://account.hana.ondemand.com

Best regards, 
Merve

**Comment by mervey45** [comment]
@thecodester Can we close this issue?

**Comment by prithamr** [comment]
Yes. Thanks.
