### ISSUE TITLE
Create a Communication Arrangement for Outbound Communication

### ISSUE THREAD

**Issue by prithamr** [SAPDocuments/Tutorials#3906]
Tutorial URL: https://developers.sap.com/tutorials/abap-env-create-comm-arrangement-api.html

Please specify the step you are referring to
Step 1: Create a Cloud Foundry destination service instance
What is the URL for the SAP Cloud Cockpit or how do I navigate to it?

**Comment by julieplummer20** [comment]
Hi Prithamr,
Can you please send me an email asap? I'm first dot last at sap com 
Also, could you please close this?

Thanks Julie.

**Comment by thecodester** [comment]
@prithamr If you are from SAP, its best to identify yourself in your profile. The link you provided is for SAP employees, and this is a public forum :-)
