### ISSUE TITLE
Test Hyperledger Fabric Chaincode API

### ISSUE THREAD

**Issue by DinavahiR** [SAPDocuments/Tutorials#3912]
Tutorial URL: https://developers.sap.com/tutorials/blockchain-test-chaincode.html

Please specify the step you are referring to:
Copy and paste the block Writes entry here and click Submit Answer

Whatever we paste from the Writes entry, system rejects it. What is expected as answer?

**Comment by heytombeck** [comment]
Hi there - based on the key and value fields provided in step 4, the write entry should be:

```
{
  "key": "id001",
  "value": "Hello World!"
}
```

Does this work for you?

**Comment by DinavahiR** [comment]
Tried that, didn't work.

Also tried including the transaction and chaincode id... Nothing works

**Comment by heytombeck** [comment]
That's unfortunate, sorry about that. Can you try taking a screen grab for me and attaching that here? I've tried to replicate this and it's working for me in my standard account. 

![Step 6 answer](https://user-images.githubusercontent.com/43130875/65126021-d2016600-d9f6-11e9-8aee-0066ddbeca6c.png)

**Comment by DinavahiR** [comment]
Here is the screenshot

[image: image.png]

Regards
Rajasekhar Dinavahi

Mobile: +91 9581515333

Your value doesn't decrease based on someone's inability to see your worth

**Comment by heytombeck** [comment]
I'm just seeing '[image: image.png]' here currently.

**Comment by DinavahiR** [comment]
Regards
Rajasekhar Dinavahi

Mobile: +91 9581515333

Your value doesn't decrease based on someone's inability to see your worth

**Comment by thecodester** [comment]
@DinavahiR I don;t see the image either -- perhaps use the GitHub web interface for messaging

**Comment by DinavahiR** [comment]
![Error](https://user-images.githubusercontent.com/37798957/65270268-6de6bb00-db38-11e9-8ff4-7db2e3a3603b.png)

Hope you can see the error I encounter in Step 6. Help me please!

**Comment by heytombeck** [comment]
Oh I see, it looks like your key field is "id-001" and the answer is set to only allow "id001" without the dash. It's a very minor difference, but hopefully removing that (even just for your answer here) should allow you to successfully submit the answer.

Thanks for your patience with this and for raising an interesting point about the way the answers are scored.

**Comment by DinavahiR** [comment]
Heytombeck,
Thanks a ton! Am able to successfully complete step 6.
Have a nice evening! 
Regards,
Raj

**Comment by thecodester** [comment]
Do you plan to update the question? You can specify a validation where it is a substring and does not need to match completely.

**Comment by thecodester** [comment]
@heytombeck Did you want to update the validation (see previous comment)?

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

@heytombeck Is there still anything needed to be updated in the tutorial?

**Comment by heytombeck** [comment]
@thecodester sorry for the late reply, the comment came in whilst I was away from work for a few weeks. I'm happy with the existing validation, but will update it if it causes any further issues.
