### ISSUE TITLE
View the SAP Cloud Platform from 10,000 Meters

### ISSUE THREAD

**Issue by jakes2255** [SAPDocuments/Tutorials#3913]
Tutorial URL: https://developers.sap.com/tutorials/cp-explore-cloud-platform.html

Please specify the step you are referring to
Step7: 'Done' button is not working
Step8: 'Done' button is not working.

Thanks,
Jakes

**Comment by thecodester** [comment]
But the other DONE buttons work? I just tried and it was set to completed for me. Can you try again? Does this happen to any other tutorial?

**Comment by jakes2255** [comment]
Thank you Daniel very quick response and fix on the same. I can see the buttons turned Green(Done).

Thank you,
Jakes
