### ISSUE TITLE
Configure Mobile Services in the iOS Assistant

### ISSUE THREAD

**Issue by jakes2255** [SAPDocuments/Tutorials#3919]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-scpms-teched18-01.html

Please specify the step you are referring to: Prior to Step 1, there is a requirement to have the "Have downloaded SAP Cloud Platform SDK for iOS version 3.0 SP01" installed on the local machine.

While following the link provided to download, it redirects to another page(as it was moved), from the result page, if we try to download, it again goes back to the earlier page.

Kindly provide the correct link.

Thank you,
Jakes

**Comment by KevinMuessig** [comment]
This should be fixed now.
