### ISSUE TITLE
Create an MDK Offline App

### ISSUE THREAD

**Issue by jakes2255** [SAPDocuments/Tutorials#3922]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-dev-kit-offline-app.html

Please specify the step you are referring to:Step 5

- After clicking the Open Link , it does not show a toast message to launch SAP Mobile Services Client.

- Sometimes it shows the SAP Mobile Services for a second, but the app does not get launched in SAP Mobile Services Client.
Kindly check.

Thanks,
Jakes

**Comment by jitendrakansal** [comment]
Hello Jakes,
Please provide more details:

- You are trying to on-board on iOS client or Android client? 
If iOS, what is iOS version? can you also find "SAP Mobile Services client" version, go to settings and look for "Mobile Svcs" app and then application version

If it is Android, you switch to Android tab and follow the instructions (please dont use Lighting QR code scanner app, you can use [Barcode scanner app](https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en) from Google play). 
_We are in process of updating the tutorials._

**Comment by jakes2255** [comment]
Thank you Jithendra,

I am trying Android Client.
Will try with Barcode scanner app  and update here.

Thanks,
Jakes

**Comment by jakes2255** [comment]
Thanks again Jithendra, with the Barcode scanner, the application opened in SAP Mobile Service Client.

Many thanks for such wonderful end to end tutorials, Chill.

Kind Regards,
Jakes
