### ISSUE TITLE
Create a Customer List Page in an MDK App

### ISSUE THREAD

**Issue by jakes2255** [SAPDocuments/Tutorials#3927]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-dev-kit-list-page.html

Please specify the step you are referring to: Step 1.

It was found that to set something(city, first name and last name of customers entity set) as the binding expression,  "Insert to Expression"  has to be clicked. 

Bypassing this and clicking on the 'Ok' button directly was not setting the values bound.

Kindly see.

Thank you,
Jakes

**Comment by jakes2255** [comment]
Double Clicking would be sufficient for the same instead, my mistake. 

Thank you,
Jakes

**Comment by thecodester** [comment]
@jitendrakansal FYI

**Comment by jitendrakansal** [comment]
@jakes2255   glad you got it working. Yes, double clicking is sufficient to insert the binding to expression section.
