### ISSUE TITLE
Create an SAPUI5 App from the Command Line

### ISSUE THREAD

**Issue by GoncharSY** [SAPDocuments/Tutorials#3929]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-sapui5-local.html

Step 5: Deploy the MTA archive.

I always get this error:
Service operation failed: Controller operation failed: 502 Updating service "dest_SecondApp" failed: Bad Gateway: Error creating service "dest_SecondApp" from offering "destination" and plan "lite": Service broker error: Quota limit exceeded. Instance creation not allowed.

I tried to set 256M, 512M, 1024M.
But from a remote Web IDE, deployment is working fine with 256M.

**Comment by IObert** [comment]
Hi,

I understand your confusion. The term "quota" refers to the service instance in this case (and not to the memory of your app runtime. The trial account only allows you to have two "destination service instances" in use at a time. You can fix the issue by [removing the services instances ](https://answers.sap.com/questions/12684501/error-while-running-sapui5-app-in-webide--service-.html)via the SCP cockpit.

Please let me know if it worked

**Comment by GoncharSY** [comment]
Thank you very much!
This solved my problem.

Maybe this link is also useful to someone: [Delete Service Instances Using the Cockpit](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/f56d4ae8bc5e4199a6d949ab8c49a447.html)
