### ISSUE TITLE
Get a Free Trial Account on SAP Cloud Platform

### ISSUE THREAD

**Issue by ravipativenu** [SAPDocuments/Tutorials#3938]
Tutorial URL: https://developers.sap.com/tutorials/hcp-create-trial-account.html

Please specify the step you are referring to

Step 6: Validate the SAP Cloud Platform cockpit URL

Not accepting though correct answer is given

**Comment by thecodester** [comment]
What answer do you give? Are you in Neo?

@IObert This will have to be fixed in any event by TechEd Barcelona -- screenshots of cockpit will change.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
