### ISSUE TITLE
Continue Your OData Exploration with EPM

### ISSUE THREAD

**Issue by jakes2255** [SAPDocuments/Tutorials#3940]
Tutorial URL: https://developers.sap.com/tutorials/odata-02-exploration-epm.html

Please specify the step you are referring to: Stp 6.

While submitting the answer for Step 6,  SubCategory/Name. 'Technical Error' is shown and button is not allowing to be submitted.

Kindly enable the button to proceed with the step.

Thank you,
Jakes

**Comment by thecodester** [comment]
Can you try again ... I believe there was indeed a technical error with the tutorial system at that time. I am able to complete the step.

**Comment by jakes2255** [comment]
Thank you for the prompt response Daniel. I am able to mark the status as completed.

Regards,
Jakes
