### ISSUE TITLE
Use the Human Detection API from a REST Client error 308

### ISSUE THREAD

**Issue by tiosteel** [SAPDocuments/Tutorials#3942]
Tutorial URL: https://developers.sap.com/tutorials/cp-mlf-rest-img-human-detection.html

Please specify the step you are referring to:

Step 2.

My response for the query of the example is
{
  "error": {
    "code": 308,
    "message": null,
    "requestId": "0211843e-952e-4ef8-5e8e-a4963378b26c"
  }
}

At the same time the FACE_DETECTION service works correctly with the same authorization / headers / body settings (include files)

add: OBJECT_DETECTION service also fails with the same error

**Comment by rbrainey** [comment]
The Product management team has requested that we remove this tutorial. A large swathe of ML Foundation functionality is being rolled into our SAP Data Intelligence Product.  Please stand by -- we'll create tutorials for Data Intelligence as soon as we have Trial for that product sorted out.
