### ISSUE TITLE
Datahub dev version - invalid download link

### ISSUE THREAD

**Issue by michalgromiec** [SAPDocuments/Tutorials#3950]
Tutorial URL: https://developers.sap.com/tutorials/datahub-docker-v2-setup.html

Please specify the step you are referring to

Step 2: Download SAP Data Hub, developer edition

The link indicated in instructions redirect to site with message that file has been moved. Could you please update link and refer to valid address?

**Comment by schneidertho** [comment]
Hi,
thanks for reporting this issue. We have fixed it. The tutorial has been changed to link to https://www.sap.com/registration/trial.f47300f6-63b8-4f22-b189-dbadd3c903d6.html?id=0050000001302052018&external-site=aHR0cHM6Ly9kZXZlbG9wZXJzLnNhcC5jb20vdHJpYWxzLWRvd25sb2Fkcy5odG1s
(it might take a few hours before the sap.com page reflects the change)
Best regards
Thorsten

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
