### ISSUE TITLE
Create a Frontend with SAP Fiori Elements and Annotations

### ISSUE THREAD

**Issue by adadouche** [SAPDocuments/Tutorials#3959]
Tutorial URL: https://developers.sap.com/tutorials/cap-cloudsdk-6-fiori-frontend.html

step 1: the "At the root URL" point to this: 
```
https://developers.sap.com/tutorials/http_localhost_4004.html
```
instead of : http://localhost:4004/

**Comment by thecodester** [comment]
I assume DJ fixed already -- can you check if this is still an issue?

**Comment by qmacro** [comment]
Fixed already. Still pending the fix in the tutorial rendering (to sort the cause rather than this symptom, but that's not to track here.
