### ISSUE TITLE
Create a Database Table

### ISSUE THREAD

**Issue by brunoursine** [SAPDocuments/Tutorials#3960]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-create-table.html

On "Step 5: Add the field bank, based on a new data element"

The system is not letting use the domain CHAR0032. I have tried several others but got the message: "Use of Domain CHAR0032 is not permitted.".

The same happens when I try to use any "Standard" Data Element.

I have searched whether there was any warning or instruction how to handle this situation in this tutorial, but didn't find.

Thanks for the tutorial, because it's very useful anyway.

All the best,
Bruno.

**Comment by julieplummer20** [comment]
Hi Bruno,
I apologize for the long delay. I have just tested this in 7.52, SP04, ADT 3.7.1, and cannot reproduce.
So 2 questions: What AS ABAP version? What ADT version?
Also, when you say "standard" data elements, do you mean e.g. BUKRS? If so, and if you are using the Developer Edition, then these are not available: AS ABAP Dev Edition includes only NW and EPM Dictionary transactions and objects, not Business Suite.
Again, I apologize for the delay, but if this is still an issue, please provide these 2 answers as a first step.
Best wishes,
Julie.

**Comment by brunoursine** [comment]
Hi Julie,

Thanks for your time analysing my question. Actually it's not something very urgent.
The AS ABAP version is 7.52 SP04. I'm using the SAP GUI for Windows 7400.3.11.1128.
For "standard" I mean objects in SAP namespace, not exactly BUKRS, but something like that.
But in the end, my doubt is: In this Developer Edition version is not possible to have access do OBJECTS keys making possible to edit STANDARD objects, right? I've searched all forum, blog and wiki possible and no concrete answer was found.

Just a final remark: I have installed this SAP version on Linux OpenSUSE 15.1 using Parallels 13 on a MacOS Catalina. If you think interesting I can send you the steps, but maybe I'm the only crazy here who installs SAP on a MAC.

All the best and thank you very much for such a detailed support.
Bruno.

**Comment by brunoursine** [comment]
Hi Julie,

If you have received an e-mail with my previous answer, please ignore it. I made such a big confusion because I had another issue and I was thinking this thread was about that.
I'm now trying to remember the right/original issue and I will get back to you soon.

Thanks for your support.

All the best,
Bruno.

**Comment by julieplummer20** [comment]
Hi Bruno,
OK, thanks for letting me know. Don’t worry – I’ll await your response, either here or on Github as you prefer.

But BTW, re your previous mail: Yes, please, if you have successfully installed AS ABAP 7.5x on Parallels 13 on a MacOS Catalina, I would love to see a blog, or notes. I try to feature all these in the FAQs: https://blogs.sap.com/2018/10/16/sap-as-abap-7.5x-developer-editions-faqs/

Best wishes,
Julie.

**Comment by brunoursine** [comment]
Hi Julie,

Here we go again.

I found out that I using your tutorial to get started in SAP Cloud Platform Trial using ADT, but later noticed that this tutorial is intended to NPL users as you have stated in your first answer on this topic.

I'm using SAP Cloud Platform Trial version (authentication.eu10.hana.ondemand.com).
Eclipse IDE for Java Developers Version: 2019-09 R (4.13.0) Build id: 20190917-1200.
ABAP Development Tools Version: 3.4.1.

Nevetheless, I'm sending the images attached, because I think that SAP Cloud Platform Trial does not let us use standard objects inside custom objects, such using a standard domain CHAR0032 in a ZJP_BANK_2 data element, for example.

I'll take care about the instalation of NPL on OpenSUSE 15.1 using Parallels on MacOS.

Thanks once again for your time. Really appreciate such a kind support and discussion.

All the best,
Bruno.



![image](https://user-images.githubusercontent.com/22693953/69050405-e9aa9a00-09f9-11ea-9c0a-e75df3345d88.png)
![image](https://user-images.githubusercontent.com/22693953/69050469-06df6880-09fa-11ea-8a78-f9422a174a50.png)

**Comment by julieplummer20** [comment]
Hi Bruno, 
You are correct: The tutorial is not currently suitable for SAP CP, ABAP Environment. I will investigate whether we can create a new tutorial for Steampunk.

Is it ok for me to close this Issue?
Best wishes,
Julie.

**Comment by brunoursine** [comment]
Hi Julie,
That's all good.
All clarified, let's close it.
Thanks for your attention.
All the best,
Bruno.

**Comment by julieplummer20** [comment]
Hi Bruno, I know this is officially closed. However, I checked in the system and talked to my manager about this. I would have to rewrite the tutorial for Steampunk, but creating a custom ("Z") domain.I would like to do this, but I can't commit do this at the moment. If I can , I will, but probably not before Christmas. If you want to create your own Z-domain, that might be best.
Best wishes, Julie.

**Comment by brunoursine** [comment]
Ok Julie, I was just exploring the Cloud Platform, but I understand the purpose.
I think this topic may be good for others.
Thanks for your efforts making the tutorials better for everyone.
I wish you a Merry Christmas and a Fantastic New Year's eve.
All the best,
Bruno.
