### ISSUE TITLE
Create a Workflow Project from a Template

### ISSUE THREAD

**Issue by markgreen-deloitte** [SAPDocuments/Tutorials#3966]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-create-project.html

Please specify the step you are referring to 4. The Business Process Management category is not available to select.

**Comment by markgreen-deloitte** [comment]
Update Step 2 part 4.

**Comment by AstridHerbst** [comment]
Thank you for your feedback. I have updated the screenshot.

**Comment by thecodester** [comment]
@AstridHerbst  I am closing issue but I believe you have rights to close yours yourself :-)
