### ISSUE TITLE
Create a Cloud Foundry Account

### ISSUE THREAD

**Issue by awagreich77** [SAPDocuments/Tutorials#3967]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-create-account.html
Step 3: Verify your account
I has tried to get a Foundry Trial while doing the tutorial "Deploy Your First SAPUI5 App to Cloud Foundry".  It started with trying to get a NEO trial, not a Foundry Trial.  When I tried to set the Foundry it failed.  So I tried to get a Foundry Trial, and when it said to verify the phone number, Nothing happened trying to use my company desk phone.  Never did get a code. So I tried my cell and nothing happened.  When I switched browsers from EDGE to CHROME it displays: We did not send you a code because you have reached the limit of 5 codes. Please contact your system administrator.  
Now what?

**Comment by IObert** [comment]
Hi @awagreich77,

I'm sorry to hear that. I agree that this process is not optimal today. Please contact sso@sap.com. The SSO colleagues should be able to reset the attempts.

Please let me know if they were able to help you.

Regards,
Marius

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by awagreich77** [comment]
I don't know that the issue is resolved.  The tutorials say any browser can be used, but I got no phone verification code using chrome or edge.  Now I'm being told to use firefox.  Does that mean the apps created won't work well in Chrome or Edge?
Also, the tutorial says to get a Neo trial, but then it says you need a Foundry, which requires a foundry trial, which is not mentioned.
So the phone verification is still broken.

Thanks,
Amy

**Comment by IObert** [comment]
Sorry to hear about your experiences.
We recently updated the cockpit and had to change the tutorial accordingly. From now on, there is no "neo-only" trial anymore. You need to sign up with your phone number to have access to the overall trial (which includes the Neo, Cloud Foundry, and ABAP environment).

Please stay in contact with my support colleagues to fix the issue. Alternatively, you can try to create a new SAP account with another email address.

PS:  Apps created with SAP Cloud Platform work on all major browsers.
