### ISSUE TITLE
Deploy Your First SAPUI5 App to Cloud Foundry

### ISSUE THREAD

**Issue by I323780** [SAPDocuments/Tutorials#3968]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-webide-new-app.html

Please specify the step you are referring to Step 4: Deploy the archive to Cloud Foundry
Right-click on the project and select Deploy and Deploy to SAP Cloud Platform.

It should be "Right-click on the .mtar file and select ..."

**Comment by IObert** [comment]
Good catch! Thanks a lot
