### ISSUE TITLE
Import your SAP Build project into SAP Web IDE

### ISSUE THREAD

**Issue by GoncharSY** [SAPDocuments/Tutorials#3978]
Tutorial URL: https://developers.sap.com/tutorials/build-import-webide.html

Step 8: Run your application

The tutorial tells you to run the file **'testFLPService.html'**.
But this results in a 404 error from the OData service.
And the address in the browser is also not correct.
![404_NotFound](https://user-images.githubusercontent.com/47101945/65776764-6aac8a00-e14b-11e9-86cd-538e47aabfd0.PNG)

To launch the application successfully, you need to select **'testFLPServiceMockServer.html'**.
This is the only way to get the correct link and complete the last step of the tutorial.

**Comment by rbrainey** [comment]
This tutorial has been removed as Web IDE no longer supports this capability,
