### ISSUE TITLE
Create a Cloud Foundry Account

### ISSUE THREAD

**Issue by jitendrakansal** [SAPDocuments/Tutorials#3981]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-create-account.html

screenshots need to be updated as per current UI changes in CP cockpit landing page
default is **Home [Europe (Rot) - Cloud Foundry - Trial]**

**Comment by IObert** [comment]
Thanks for opening the issue. Fixed in #4004

**Comment by IObert** [comment]
The old tutorial will be removed by @thecodester

**Comment by thecodester** [comment]
I have removed tutorial. Please use this one: https://developers.sap.com/tutorials/hcp-create-trial-account.html
