### ISSUE TITLE
Add Transactional Behavior to Your Core Data Services

### ISSUE THREAD

**Issue by vgup** [SAPDocuments/Tutorials#3988]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-transactional-enablement.html

Please specify the step you are referring to: Step 5

Following error is returned by eclipse
Description	Resource	Path	Location	Type
BEHAVIOR "ZI_BOOKING_VG" cannot be implemented in class "Z_I_BOOKING_VG".	z_i_booking_vg.aclass	/TRL_EN_VG/.adt/classlib/classes/z_i_booking_vg/z_i_booking_vg.aclass	line 1	ABAP Syntax Check Problem

**Comment by vgup** [comment]
Looks like it works as a managed implementation

**Comment by thecodester** [comment]
@vgup Is this still an issue?

**Comment by vgup** [comment]
The tutorial step instructions should be changed to use Managed implementation. It doesn’t work as specified in the tutorial

**Comment by thecodester** [comment]
@mervey45 Can you update as needed?

**Comment by rhubarbkid** [comment]
I am having the same issue.

**Comment by mervey45** [comment]
Hi @rhubarbkid, 

I tested this tutorial. It works, are you sure, that you have the latest ADT? Please check this.

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi,

did you add the coding from step 5 in your local types tab? Please be sure, that it is in the right place.  Be also sure, that you replaced the XXX. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
@vgup Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
