### ISSUE TITLE
Use SAP HANA Tools for Eclipse as SQL Query Tool with SAP HANA, express edition

### ISSUE THREAD

**Issue by jiayiwangjw** [SAPDocuments/Tutorials#3991]
Tutorial URL: https://developers.sap.com/tutorials/mlb-hxe-tools-sql-eclipse.html

hi,

I stuck in Step 6: Add a connection to the System database. I have provided host name, SYSTEM user credential, when click finish, it shows the below error:

java.lang.NoClassDefFoundError: javax/xml/soap/SOAPException

I checked stackoverflow, it seems the solution is 
#############
JavaSE 8 includes package java.xml.soap.
JavaSE 9 moved package javax.xml.soap to the module java.xml.ws.
Modules shared with JEE (like java.xml.ws) are included in JavaSE 9, but are
- deprecated for removal from a future version of JavaSE, and
- not on the default module path.

A quick workaround is to either
- run the jar with JRE 8: $MY_JRE8_HOME/bin/java -jar my.jar, or
- add a module for JRE 9: java --add-modules java.xml.ws -jar my.jar
#############

here is the JDK I installed
jdk-13_osx-x64_bin.dmg

I am not a java guy, could you check if the solution is the right one and how I can add a module?

**Comment by jarjarbentley** [comment]
@jiayiwangjw that is a workable solution.  Some users who have older Java have had to install newer after removing older version.  Should be fine.

**Comment by Pravin-kumar7** [comment]
Hi Josh Bentley,

I am not able to add Hana DB in Eclipse (2019-09 R (4.13.0)) .  "java version "13.0.1" 2019-10-15" is install in my system.
I am getting below error after providing userid and password at Eclipse.

Please help me to resolve this error.
Thanks,
Pravin Kumar
