### ISSUE TITLE
Bundle Data (via JavaScript) SAP Data Hub, Developer Edition

### ISSUE THREAD

**Issue by andersonmorita** [SAPDocuments/Tutorials#3993]
Tutorial URL: https://developers.sap.com/tutorials/datahub-pipelines-v2-bundledata.html

Please specify the step you are referring to 4

The message "Technical Error" is shown no matter my answer. Could you please check it out? 

Thank you in advance.

**Comment by thecodester** [comment]
Fixed. Please try again.
