### ISSUE TITLE
Deploy your app to SAP Fiori launchpad

### ISSUE THREAD

**Issue by 38ajay** [SAPDocuments/Tutorials#3996]
Tutorial URL: https://developers.sap.com/tutorials/webide-fiori-deploy.html

In Step 9.

_In your running Fiori Launchpad, copy the Launchpad URL and paste it into the field below and click Validate._

The screenshot of the tutorial step is missing.

**Comment by rbrainey** [comment]
Hi and thanks for your feedback. It's always appreciated. Coincidentally, we recently decommissioned this particular Mission/Group owing to the rollout of the new Cloud Portal service.  You can find a new mission covering the new Portal here (https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html)  and here (https://developers.sap.com/tutorials/cp-portal-cloud-foundry-create-app.html)
