### ISSUE TITLE
MovieLens with SAP HANA APL Recommendation (MovieLens App)

### ISSUE THREAD

**Issue by jiayiwangjw** [SAPDocuments/Tutorials#3998]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aa-movielens-05.html

in step 10, I tried to build HANA DB table, here is the error I see:

$$$$$$$$$$$$$$$$$
Deploying "src/hdb/apl/views/recommendation_contentbased.hdbview"... ok  (0s 325ms)    Deploying "src/hdb/apl/views/recommendation_collaborative.hdbview"... ok  (0s 332ms)     

Error: com.sap.hana.di.afllangprocedure: Database error 129: : transaction rolled back by an internal error: "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE": line 156 col 5 (at pos 5073): 

**### AFL error: Registration of AFLLANG wrapper procedure "ML"."movielens.db.hdb.apl.afllang::recommendation" failed with error 'unknown function APL_AREA::CREATE_RECO_MODEL_AND_TRAIN'.** [8201003]       at "src/hdb/apl/afllang/recommendation.hdbafllangprocedure" (0:0)    

Warning: Worker 3 running the "com.sap.hana.di.afllangprocedure" plugin has encountered an error while deploying 1 objects [8212030]    

Error: Worker 3 has encountered an error; all remaining jobs will be canceled [8214600]   

Error: Processing work list... failed [8212102]   Make failed (4 errors, 1 warnings): tried to deploy 4 files, undeploy 0 files, redeploy 0 dependent files   

Error: Making... failed [8211605] Error: Starting make in the container "ML" with 4 files to deploy, 0 files to undeploy... failed [8214168]Deployment to container ML failed - error: HDI make failed [Deployment ID: none].

Error: HDI make failed(9s 975ms)npm ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! deploy@ start: `node node_modules/@sap/hdi-deploy/deploy.js`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the deploy@ start script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.npm ERR! A complete log of this run can be found in:npm ERR!     

**/hana/shared/HXE/xs/controller_data/executionagent/executionroot/49f689ad-100c-4ef3-a4d8-c7afc47fa6a6/app/META-INF/cache/node8.15/.npm/_logs/2019-10-01T22_13_34_937Z-debug.log

3:13:25 PM (Builder) Build of /movielens/db failed.
$$$$$$$$$$$$$$$$$$$$

why it shows unknown function APL_AREA::CREATE_RECO_MODEL_AND_TRAIN'

`{
  "area" : "APL_AREA",
  "function" : "CREATE_RECO_MODEL_AND_TRAIN",
  "parameters" : [
    {"direction" : "IN",  "type" : "movielens.db.hdb.apl::recommendation.tt_function_header"},
    {"direction" : "IN",  "type" : "movielens.db.hdb.apl::recommendation.tt_operation_config"},
    {"direction" : "IN",  "type" : "movielens.db.hdb.apl::recommendation.tt_variable_descs"},
    {"direction" : "IN",  "type" : "movielens.db.hdb.apl::recommendation.tt_movielens_dataset"},
    {"direction" : "OUT", "type" : "movielens.db.hdb.apl::recommendation.tt_model"},
    {"direction" : "OUT", "type" : "movielens.db.hdb.apl::recommendation.tt_model_node_user"},
    {"direction" : "OUT", "type" : "movielens.db.hdb.apl::recommendation.tt_model_node_movie"},
    {"direction" : "OUT", "type" : "movielens.db.hdb.apl::recommendation.tt_model_links"},
    {"direction" : "OUT", "type" : "movielens.db.hdb.apl::recommendation.tt_operation_log"},
    {"direction" : "OUT", "type" : "movielens.db.hdb.apl::recommendation.tt_summary"},
    {"direction" : "OUT", "type" : "movielens.db.hdb.apl::recommendation.tt_indicators"},
    {"direction" : "OUT", "type" : "movielens.db.hdb.apl::recommendation.tt_model_sql_code"}
  ]
}`

**Comment by jung-thomas** [comment]
@jiayiwangjw  - The error you are receiving (unknown function APL_AREA::CREATE_RECO_MODEL_AND_TRAIN) would indicate that you haven't successfully completed Step 5 Install SAP HANA APL package.  It is this step that would create the schema APL_AREA and the Function referenced here.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
