### ISSUE TITLE
Install the Optional SAP HANA Automated Predictive Library Package for SAP HANA, express edition (Preconfigured VM)

### ISSUE THREAD

**Issue by jiayiwangjw** [SAPDocuments/Tutorials#3999]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-apl-vm.html

when I execute step 2, HXEDownloadManager_linux.bin linuxx86_64 vm apl.tgz

I see the below error:

no java in (/hanna/shared/HXE/xs/bin:urs/sap/HXE/HDB90/exe/krb5/bin:usr/sap/HXE/HDB90...........)
this program is generated by unregistered JarExe and it has expired to run for DEMO use

Help please. thanks.

**Comment by JCurrie27** [comment]
Hi jiayiwangjw  - engineering is looking at this issue. In the meantime, have you considered posting this error issue to the community support Questions and Answers page? [https://developers.sap.com/topics/sap-hana.html#community](https://developers.sap.com/topics/sap-hana.html#community)

**Comment by JCurrie27** [comment]
Actually, on the Q&A page I see others have raised this issue here: [https://answers.sap.com/questions/12857573/hxecheckupdatejar-jar2exe-has-expired.html](https://answers.sap.com/questions/12857573/hxecheckupdatejar-jar2exe-has-expired.html) 

Here's the workaround:

> Developers are working on to fix it asap.
> 
> The issue only exists in Download Manager inside the VM/Binary.
> 
> The workaround for this issue :
> 
> 1.)download the SAP Hana Express Download Manager from
> 
> https://www.sap.com/cmp/ft/crm-xu16-dat-hddedft/index.html
> 
> 2.)use the Download Manager to download the new version SAP Hana Express/Optional components.

Closing this issue.

**Comment by jiayiwangjw** [comment]
I downloaded SAP HANA EXPRESS via the link you provided. This does not address the issue.

**Comment by JCurrie27** [comment]
I'm sorry to hear the workaround did not address your issue. Engineering is working on a fix for the JAR problem. In the meantime, I recommend adding this latest issue to the community support Questions and Answers page (link above) describing how the workaround did not fix the problem. That site receives more views than this GitHub repository.

**Comment by lin1161** [comment]
What's the exact error msg with the download Manager that downloaded from https://www.sap.com/cmp/ft/crm-xu16-dat-hddedft/index.html?
