### ISSUE TITLE
Call an External API

### ISSUE THREAD

**Issue by henwr123** [SAPDocuments/Tutorials#4005]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-external-api.html

Please specify the step you are referring to

Step 10: Test yourself - question and submit button missig

There is no question to submit

**Comment by thecodester** [comment]
@henwr123 Fixed. Please check.

@julieplummer20 Please test and check published tutorials. There is also formatting issue you may want to address in Step 7. Use blank lines between ALL list items and before/after all coding inside a list item.
