### ISSUE TITLE
SAP HANA XS Advanced, Creating an HDI Module

### ISSUE THREAD

**Issue by mechevarria** [SAPDocuments/Tutorials#4006]
Tutorial URL: https://developers.sap.com/tutorials/xsa-hdi-module.html

Please specify the step you are referring to
**Step 5**
For new database modules the **data** folder is not automatically generated. It would be good to mention adding the folder under **db/src**

**Comment by rbrainey** [comment]
Hi. This is a great suggestion. I am updating the tutorial with some refined instructions.

Thanks for your feedback.  This change has been committed in git and push to production.
