### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by darrenm898** [SAPDocuments/Tutorials#4014]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html

On Step 12
Adding additional containers. Is there a way to specify the "SAP HANA System ID" to change it from the default of HXE?

**Comment by JCurrie27** [comment]
Hi darrenm898: To take advantage of the Community Support model, could you post this question to the HANA express  [Questions & Answers](https://developers.sap.com/topics/sap-hana.html#community) forum? I've sent the question to Engineering in case they respond before the community does.
Closing this issue for now.
