### ISSUE TITLE
Integrate an SAP Fiori App into Your Portal Site (Cloud Foundry)

### ISSUE THREAD

**Issue by pdominique** [SAPDocuments/Tutorials#4015]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-sapui5-app.html

Step 4: system is missing when creating a new app.

The console shows that a POST request is sent to a GraphQL endpoint to get the destinations (**https://<s-user>trial.dt.cpp.cfapps.eu10.hana.ondemand.com/bff/graphql**) but the response is **404 Not Found: Requested route ('portal-service.cfapps.eu10.hana.ondemand.com') does not exist.**

**Comment by IrisSasson** [comment]
Hi
There was a defect that our devops solved

Please close this issue

Thanks
Iris.
