### ISSUE TITLE
Install SAP HANA 2.0, express edition on a Preconfigured Virtual Machine (with SAP HANA XS Advanced) - Last tutorial not completable

### ISSUE THREAD

**Issue by apoeschl** [SAPDocuments/Tutorials#4018]
Group URL: https://developers.sap.com/group.hxe-install-vm-xsa.html

The last tutorial of the for the group "Install SAP HANA 2.0, express edition on a Preconfigured Virtual Machine (with SAP HANA XS Advanced)" cannot be finished. Therefore the whole group stays open at 90%. I think it would make sense to include a button in the troubleshooting page (or a question) to be able to complete the last tutorial:
https://developers.sap.com/tutorials/hxe-ua-troubleshooting.html

**Comment by rbrainey** [comment]
Yes, that makes sense.  I'll add it.

**Comment by rbrainey** [comment]
This has been addressed, but it required adding "Done" buttons to all steps in this tutorial.

**Comment by apoeschl** [comment]
> This has been addressed, but it required adding "Done" buttons to all steps in this tutorial.

Works perfect, thanks!
