### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by HenrikDA** [SAPDocuments/Tutorials#4021]
Tutorial URL: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html

Please specify the step you are referring to: Step 6

When I played with the tutorial on a SAP HANA Express 2.0 SP04 it was necessary to create the JSON Collection (community) before 'build' in step 6.

Additional steps:
- Login to SAP HANA Express Edition with the hxeadm user
- hdbsql -u SYSTEM -d SYSTEMDB -i 90
- ALTER DATABASE HXE ADD 'docstore';
- \c -u SYSTEM -d HXE -i 90
- CREATE COLLECTION community;

I really enjoyed it! Nice and well done!

Regards,
Henrik

**Comment by Sygyzmundovych** [comment]
Hi Henrik. There’s step 5 https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html where you clone the project that has the definition of that collection. Did cloning and building work for you?

**Comment by HenrikDA** [comment]
Hi Vitaliy,

The cloning work, but the build failed.

A plain SAP HANA Express don’t have docstore by default (ALTER DATABASE HXE ADD 'docstore').

I didn’t try to build after just adding docstore. It would properly have worked.

**Comment by HenrikDA** [comment]
It does. The tutorial Create a food database in SAP HANA Express Edition (https://developers.sap.com/tutorials/hxe-docstore-01-create-database.html) include the same steps as I did. It has to be executed before building the DB to create the docstore.

**Comment by Sygyzmundovych** [comment]
That specific tutorial https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html is meant to be used with HANA in CF environment of SCP Trial. It is still in works so we will try to make sure it is more clear. Thank you once again for bringing it.
