### ISSUE TITLE
Create Your First ABAP Console Application

### ISSUE THREAD

**Issue by jakes2255** [SAPDocuments/Tutorials#4023]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-console-application.html

Please specify the step you are referring to:Step 2, Create ABAP Cloud Project.

It appears this option "Create ABAP Cloud Project" is no longer available in Eclipse Neon or Oxygen.
I have tried with both and installed the plugin accordingly. Still this option is not available.
Is this now deprecated?
Kindly check also the related discussion in SCN below:-
[Add New Cloud System" doesn't appear in Eclipse IDE](https://answers.sap.com/questions/428211/option-to-add-new-cloud-system-doesn't-appear-in-e.html)
However even with Neon now, this is not available.

Please help us to resolve this and proceed with the steps.

Thank you,
Jakes

**Comment by mervey45** [comment]
Hi @jakes2255,

just select ABAP project and then click ABAP Cloud Project. Can you try this out?

Best regards,
Merve

**Comment by jakes2255** [comment]
Hi Merve,

Thank you for the response,

Please see the available options being displayed under ABAP node in the wizard below:-
![ABAP Cloud Project Not Available in Eclipse Neon](https://user-images.githubusercontent.com/40160913/66414877-e7771800-ea17-11e9-92ad-b29433a2f17b.png)

When I select ABAP project, SAP System that are declared in SAP Logon are being shown, there is no Cloud Project option being available as below:-
![ABAP Project Step1](https://user-images.githubusercontent.com/40160913/66415063-4dfc3600-ea18-11e9-9f82-2a8317ce64cd.png)
and then:-
![ABAP Project Step2](https://user-images.githubusercontent.com/40160913/66415189-aa5f5580-ea18-11e9-804e-911db9943f11.png)

Kindly advise how to proceed on this.

Thank you,
Jakes

**Comment by mervey45** [comment]
Hi Jakes,

please Check if you have the latest ADT in your Eclipse. If not, please install this.

Best regards,
Merve

**Comment by jakes2255** [comment]
Hi Merve,
I have tried with the latest ADT as well as with the earlier version.

It appears the steps are no longer possible with the changes at Eclipse/ADT side.

Kindly also see the SCN thread mentioned in the initial comment.

Thanks,
Jakes

**Comment by mervey45** [comment]
Hi @jakes2255, 

please make sure that:

You have downloaded the ABAP Development Tools (ADT), version 3.4 or later. See ABAP [Development Tools](https://tools.hana.ondemand.com/#abap).

You have established a connection to your system from within[ ADT](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/7379dbd2e1684119bc1dd28874bbbb7b.html).

Best regards, 
Merve

**Comment by jakes2255** [comment]
Thank you Merve,

I had tried that also😕

Thanks,
Jakes

**Comment by mervey45** [comment]
Hi @jakes2255 ,

you also have to add the ADT link to your latest Eclipse, by selecting help -> install new software on your eclipse menu:
![image](https://user-images.githubusercontent.com/27953324/66657342-f213f600-ec3f-11e9-89b4-209bfc344c56.png)

Add the ADT link -> select everything and install it:

![image](https://user-images.githubusercontent.com/27953324/66657238-c85acf00-ec3f-11e9-9869-cb1c490a35f1.png)

Then you can see ABAP Cloud Project
![image](https://user-images.githubusercontent.com/27953324/66657462-2b4c6600-ec40-11e9-8610-ed79407fedce.png)

Please try it out again, otherwise, you have to open a ticket. 

Best regards, 
Merve

**Comment by jakes2255** [comment]
Thank you Merve,

Finally got it working with the below combinations(jdk1.8, Eclipse 2019-06, SCP Tools:2019-06, including ADT).
![ABAP Cloud Project](https://user-images.githubusercontent.com/40160913/66661248-4d57df80-ec64-11e9-9641-3f5aef3355b6.jpg)

Thank you,
Jakes

**Comment by jakes2255** [comment]
Closing the issue as it is working now, thank you once again.😂
