### ISSUE TITLE
Develop a Fiori App Using the ABAP RESTful Programming Model (Managed Scenario)

### ISSUE THREAD

**Issue by I304296** [SAPDocuments/Tutorials#4027]
Group URL: https://developers.sap.com/group.abap-env-restful-managed.html

Very nice tutorial to on-board on ABAP on cloud. 

One point. With this tutorial I was able to complete the Firoi app and preview the app. However I am not sure how I should be deploying the app to CF. 

Cloud you please add those steps as well?

BR
Shibaji

**Comment by mervey45** [comment]
Hi @I304296 ,

thank you for your feedback. It depends on what you are doing. If you are using the ABAP trial, then I have to say, that it's not possible now. But with a normal SAP Cloud Platform ABAP system, you could do this. The following tutorial explains the deployment: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html 

Best regards, 
Merve

**Comment by mervey45** [comment]
@thecodester Can we close this issue, the license tag has been added.

**Comment by mervey45** [comment]
@thecodester  We can close this issue.
