### ISSUE TITLE
backend url

### ISSUE THREAD

**Issue by Rajeevkallalu97** [SAPDocuments/Tutorials#4030]
Hi, how to create our own backend url in SAP cloud platform after defining a database schema. So that my database created on SAP can be integrated into xcode

**Comment by thecodester** [comment]
Is this about a specific tutorial or a general question about SAP Cloud Platform?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
