### ISSUE TITLE
Deploy the Azure Service Broker to Cloud Foundry

### ISSUE THREAD

**Issue by cdonau** [SAPDocuments/Tutorials#4033]
Tutorial URL: https://developers.sap.com/tutorials/cp-osba-azure-deploy-service-broker.html

Please specify the step you are referring to

Deploy the Azure Service Broker to Cloud Foundry
Step 1: There is CF only in the hana trial accounts (rip neo)

**Comment by thecodester** [comment]
FYI - Not dead completely yet. There is a link in the cockpit to the old Neo.

**Comment by maxstreifeneder** [comment]
@cdonau thanks a lot! fixed.
