### ISSUE TITLE
Build and Deploy a Java Application

### ISSUE THREAD

**Issue by yuri-adeodato** [SAPDocuments/Tutorials#4034]
Tutorial URL: https://developers.sap.com/tutorials/cp-java-reference-app-deploy.html

Please specify the step you are referring to

In the step 4, you have to put the username and password of a database, but in not shown in the tutorial that the name of the user in SYSTEM and that the password is the password that you choose when create a database in SAP HANA / SAP ASE > Databases & Schemas

**Comment by simonarangelova** [comment]
Hello,

Thank you for the feedback. The tutorial will be updated.

**Comment by thecodester** [comment]
I am assuming that this PR https://github.com/SAPDocuments/Tutorials/pull/4354 resolves this issue.
