### ISSUE TITLE
Set Up a Workflow With Extended Employee Onboarding

### ISSUE THREAD

**Issue by shaktibarath** [SAPDocuments/Tutorials#4036]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html

For Step 2: Configure Sample Application , point 4 which says "Add a new entry and name it workflow." should change to

Add a new entry and name it "workflow_sample_onboarding". with name "workflow", sample.onboarding.mta build fails with following error:

ERROR: Invalid mta.yaml. Make sure that the required module or resource workflow_sample_onboarding is defined.

**Comment by ArchanaShukla** [comment]
Due to recent change in the Web IDE, the changes in the resources like renaming the workflow instance does not update the reference. One need to explicitly go and update the references in the uiDeployer. I will update the tutorial soon.

**Comment by ArchanaShukla** [comment]
Tutorial updated.
@thecodester - please close the issue
