### ISSUE TITLE
Use the Document Service in Your Java Application

### ISSUE THREAD

**Issue by yuri-adeodato** [SAPDocuments/Tutorials#4037]
Tutorial URL: https://developers.sap.com/tutorials/cp-java-reference-app-document-service.html

Please specify the step you are referring to

All this tutorial is already made in the github code, and does not need done the pox.xml changes to include the chemistry libs

**Comment by MichaelCzcz** [comment]
Hello @simonarangelova any updates?

**Comment by MichaelCzcz** [comment]
Hello @simonarangelova any updates?

**Comment by simonarangelova** [comment]
We are using the code snippets which are already in  https://github.com/SAP/cloud-espm-v2 to explain the document service scenario.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
