### ISSUE TITLE
Set Up a Workflow With Extended Employee Onboarding

### ISSUE THREAD

**Issue by shaktibarath** [SAPDocuments/Tutorials#4038]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html

When I try to deploy the application, I am getting following errors and deployment failed.

12:26:56 PM (DeploymentToCF) Deployment of the "sample.onboarding.mta" project started.
12:26:57 PM (DeployService) Deployment in progress.
12:26:57 PM (DeployService) Deploying /sample.onboarding.mta/mta_archives/sample.onboarding.mta_0.0.1.mtar to endpoint: https://api.cf.us10.hana.ondemand.com, organization: S0009650633, space: dev.
12:28:34 PM (DeployService) Target: https://deploy-service.cfapps.us10.hana.ondemand.com/slprot/S0009650633/dev/slpPreparing to deploy /sample.onboarding.mta/mta_archives/sample.onboarding.mta_0.0.1.mtarPrepare deployment filesChecking if there are conflicting processesFound 1 conflicting processesAborting process 123199967Uploading mtar archiveStarting deploymentDeploying in org "S0009650633" and space "dev"Detected MTA schema version: "3"Detected deployed MTA with ID "sample.onboarding.mta" and version "0.0.1"Detected new MTA version: "0.0.1"Deployed MTA version: "0.0.1"Processing service "sample_onboarding_html5_repo_host"...Updating application "uiDeployer"...Application "uiDeployer" attributes are not modified and will not be updatedService "sample_onboarding_html5_repo_host" will not be rebound to application "uiDeployer" because the binding parameters are not modifiedUploading application "uiDeployer"...Staging application "uiDeployer"...Application "uiDeployer" stagedStarting application "uiDeployer"...Application "uiDeployer" startedApplication "uiDeployer" executedStopping application "uiDeployer"...Deleting discontinued configuration entries for application "uiDeployer"...Error building content deployment configuration for module: "onboarding": Controller operation failed: 404 Not Found: Service workflow_sample_onboarding not found. To download logs of the process, use the multi-target application plug-in for the Cloud Foundry CLI command "cf dmol -i 123210557" directly in your Cloud Foundry space.For more information see https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/e93b231895b64cbc9221a62953563a6f.html.Job failed.
12:28:34 PM (DeploymentToCF) Deployment of the "sample.onboarding.mta" project failed.(Response state is FAILED)

**Comment by ArchanaShukla** [comment]
Did it solve? The error messages says that you have already deployed a version of this MTA. The default version in the MTA is 0.0.1 and If you are not trying out this for first time and have deployed this MTA before then you need to change the version in the MTA file to say 0.0.2 etc. depending upon the last version you deployed.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by bcschaich** [comment]
The error message says:
"Controller operation failed: 404 Not Found: Service workflow_sample_onboarding not found. "

This is exactly the resource you are asked to delete during the tutorial. I filed an extra issue on this.
