### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by OksanaShumova** [SAPDocuments/Tutorials#4039]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-data-model.html
Step 4: Create service binding, 5. Double-click on TravelProcessor to see the application on the UI.

Everything in Eclipse looks like in tutorial, but nothing happens when I double-click on TravelProcessor.

**Comment by kunjbiharishukla** [comment]
I have the exact same issue [https://github.com/SAPDocuments/Tutorials/issues/4048]

**Comment by mervey45** [comment]
Hi @OksanaShumova and @kunjbiharishukla , 

do you have the latest ADT? If yes, then please right-click on TravelProcessor and click on **Open Fiori Elements App Preview**. If this doesn't work, please try it out with another browser or check your browser settings. Your browser should open and the preview should be visible. 

Best regards, 
Merve

**Comment by ruthvikg193** [comment]
Hi @mervey45 can you please share here the version of Eclipse that you used for the tutorials ?
It would help a lot of people in understanding than creating confusion.

Thanks,
RG

**Comment by kunjbiharishukla** [comment]
Hi @mervey45, I have the latest ADT and still i am facing the same issue. The eclipse i am using is 2019-06.
@OKsanaShumova, Is it working for you.

Warm Regards,
KB

**Comment by cna-shiozaki** [comment]
Hello,

Are you sure that your OS (e.g. Windows10) has been assigned a default Internet Browser ?? Check this out in the Control Panel (for Windows10).

If not, then ADT/Eclipse does not know how to open the "App Preview".

Hope it helps
CNA

**Comment by ruthvikg193** [comment]
Thanks @cna-shiozaki.

I have reset the default browser in Windows 10 to Internet Explorer. Now, I am to preview.
For all having issue, just use IE and check the App Preview, it should work.

Thanks all again for inputs.

**Comment by kunjbiharishukla** [comment]
Thanks @cna-shiozaki

It is working for me now.

**Comment by thecodester** [comment]
@OksanaShumova Seems that the issue is resolved. If you have additional questions about this issue, let us know.

**Comment by OksanaShumova** [comment]
Hello!
Thanks for your advices. I changed my default browser from Chrome to IE, and preview button works now
