### ISSUE TITLE
Create a Destination for the SAP Gateway Demo System

### ISSUE THREAD

**Issue by mikemainguy** [SAPDocuments/Tutorials#4041]
Tutorial URL: https://developers.sap.com/tutorials/teched-2016-3.html

Please specify the step you are referring to

Putting in additional properties in the tutorial, the WebIDEUsage property values are truncated in the image and it's not apparent what the additional values should be in the list.

Actually, relooking, I see they are at the top, but it's isn't obvious to someone unfamiliar if they're just trying to follow along.

**Comment by thecodester** [comment]
@qmacro Can you take a look at this and see what you think?

**Comment by qmacro** [comment]
I would say unless this is a component tutorial in other groups or missions, it should be removed anyway as it's 3 years old and teched specific. Unless you (or @akula86 the author) say otherwise.

**Comment by thecodester** [comment]
As far as I see, the only mission/group that uses this is the mission **Take a Deep Dive into OData**, specifically in this group: https://developers.sap.com/group.scp-7-odata-tools.html

**Comment by qmacro** [comment]
Hi @mikemainguy thanks for the note. I'm guessing you're referring to Step 4, which looks like this:

![Screenshot 2019-11-07 at 13 50 01](https://user-images.githubusercontent.com/73068/68394341-8f8e1700-0165-11ea-8523-b07f47e22283.png)

As you point out, the values are there for the person to copy and paste into the input fields, in this case I think you're referring to the value for WebIDEUsage, which is given as:

```
odata_gen, odata_abap, bsp_execute_abap
```

I would hope that it's quite obvious if they're following along and reading the instructions - the screenshot is there for context :-)
