### ISSUE TITLE
Create Your First Fiori for iOS App

### ISSUE THREAD

**Issue by Leoooob** [SAPDocuments/Tutorials#4043]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-scpms-teched18-02.html

Step 5: Set up Xcode Project, clicking "finish" in the final stage of the wizard.

I get the following error:
![screenshot of wizard error](https://i.imgur.com/hqIeTgt.png)

I couldn't edit the Admin UI URL when setting up my account with the iOS assistant nor could i see the full url for the generated url. I did use the "Importing URLs directly" link from the important links section of the mobile services trial page, as per the tutorial

**Comment by KevinMuessig** [comment]
Correct, you have to click on the 'Importing URLs directly'. It will open up a screen in the locally installed iOS Assistant. Please provide a name and change the authentication to SAML and Save.

Then you can create the application. Please make sure of the following:

- The iOS Assistant has to be locally on your hard drive not mounted.
- While in the Features step during the app creation please scroll down and make sure the Discovery Service is done resolving the email.
- You can use the Console application on your Mac and look for logs of the Assistant. If the error still occurs please provide the logs as well. Make sure no sensitive data is encluded!
- **Make sure to use the latest SDK version from the SAP website.**

**Comment by KevinMuessig** [comment]
Update: I will soon replace the Neo setup guide with the CF guide.
