### ISSUE TITLE
SAP Mobile Card CF "Destination not created."

### ISSUE THREAD

**Issue by junaidhf** [SAPDocuments/Tutorials#4044]
Hi,
  While following the tutorial https://developers.sap.com/tutorials/cp-starter-digitalexp-mobilecards-1-setup.html#e0acd616-fe0b-4bec-8189-e2533d08f1ea . I am geting an error after entering the api key telling **Destination not created.**

**Comment by jitendrakansal** [comment]
@junaidhf could you share the screenshot of that error?

**Comment by junaidhf** [comment]
Hi @jitendrakansal please find the screenshot as requested. 
![Screen2](https://user-images.githubusercontent.com/55427649/66729217-99bf3d00-ee67-11e9-8f52-a6d3ed0b2baa.PNG)
![Scren1](https://user-images.githubusercontent.com/55427649/66729223-a2b00e80-ee67-11e9-882b-2cd02b7c31d9.PNG)

**Comment by jitendrakansal** [comment]
I think you are missing some steps in between.
Please follow as per below:
1. Under Template Manager, select "SuccessFactors" from category dropdown
2. Click "create card template" icon for any given SuccessFactors templates
3. Card template should be of type "Automatic instance generation" (i have 
attached screenshot for the same) unlike in [your screenshot](https://user-images.githubusercontent.com/55427649/66729223-a2b00e80-ee67-11e9-882b-2cd02b7c31d9.PNG) which is of type "server managed card" 
![Screenshot 2019-10-14 at 10 08 05 AM](https://user-images.githubusercontent.com/31536700/66736845-a6916000-ee6a-11e9-850c-04ca110302e0.png)
4. Once you entered the API key, on saving, Destination should point to SFDEMO_APIHUB and template should be of type "Automatic instance generation".  (i have attached screenshot for the same) ![Screenshot 2019-10-14 at 10 11 47 AM](https://user-images.githubusercontent.com/31536700/66737002-0d167e00-ee6b-11e9-96cb-0b7c20ed5b8e.png)

**Comment by junaidhf** [comment]
Hi @jitendrakansal  this issue is resloved it was to do with the Card template should be of type "Automatic instance generation" as suggested by you. Thanks for the help.
