### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by NPSAP** [SAPDocuments/Tutorials#4047]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Please specify the step you are referring to
Tenant provisioning step:
"Tenant provisioning failed. Please try again after some time."
I have tried yesterday and today but also today it did not work.

**Comment by gauthamkrishna-sap** [comment]
Hello,
Apologies for the inconvenience. Our dev team has identified the issue and working on fixing it. Will update you as soon as it is fixed. Thank you for your patience.

**Comment by MichaelCzcz** [comment]
@gauthamkrishna-sap any news on the update?

**Comment by gauthamkrishna-sap** [comment]
Hi,
The issue is fixed and provisioning should work as expected. Can you please retry now?
Best Regards,
Gautham

**Comment by lsypula** [comment]
@gauthamkrishna-sap 
I'm facing the same issue. Already tried multiple times and at 52% I'm getting the error message: 
Tenant provisioning has failed. Create service broker instances only after successful provisioning. Please try after some time.

**Comment by MichaelCzcz** [comment]
@NPSAP Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
