### ISSUE TITLE
Prepare the Portal Environment for Creating Sites

### ISSUE THREAD

**Issue by iwonahahn** [SAPDocuments/Tutorials#4049]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Please specify the step you are referring to: In step 1 please add the URL to SAP Cloud Platform cause a lot of attendees have asked the us in the App Space at TechEd for this URL to continue with the mission ;-). Thanks!

**Comment by IrisSasson** [comment]
Hi Daniel

I don't know how to edit tutorials and Lindsay is on vacation, do you want to add a link to the trial of SAP Cloud Platform as they ask?

Thanks
Iris.

**Comment by thecodester** [comment]
Link added

https://github.com/SAPDocuments/Tutorials/commit/910802c3008314f1fe169d718df100210ec9d572
