### ISSUE TITLE
Develop SAP Fiori Applications for SAP Cloud Platform on Cloud Foundry

### ISSUE THREAD

**Issue by iwonahahn** [SAPDocuments/Tutorials#4050]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-fioriapps-create.html

Please specify the step you are referring to: 

general: first we need to update the author, it seems that Julia is no longer in the company and responsible for the content. 

Explain what MTA is. The description is in the mission here https://developers.sap.com/tutorials/cp-portal-cloud-foundry-create-app.html.

step 1.1: Please add in the tutorial how to access the SAP Web IDE cause this tutorial is part of this mission at TechEd https://developers.sap.com/tutorials/cp-portal-cloud-foundry-create-app.html. 

step 1.2: Category should be "Featured" otherwise the SAPUI5 Application tile will not appear.
THANKS :).

**Comment by thecodester** [comment]
@Paolaufer This was written by your team.

@LindsayBert You make reference to this. If Julia's tutorial is OK for you, no need to do anything. If not, feel free to update.

@iwonahahn I think next time you should go through internal channels.

**Comment by IObert** [comment]
I noticed other issues with this tutorial too. I'd suggest we remove it entirely as we already have other tutorials that cover the same content in more detail [(see here).](https://developers.sap.com/mission.sapui5-cf-first.

Please reach out to me via email if you disagree

**Comment by thecodester** [comment]
@Paolaufer @LindsayBert Can you comment?

**Comment by IObert** [comment]
We continued the discussion via email. We'll let you know when we come to a conclusion.
Thanks for checking!

**Comment by MichaelCzcz** [comment]
@IObert any updates? Can the issue be closed?

**Comment by IObert** [comment]
Thanks for the reminder @MichaelCzcz.
Some of the  issues has been addressed in #4288 and #4289, I'll ping the colleague in charge
