### ISSUE TITLE
SAP HANA XS Advanced - Consume the OData service in a basic HTML5 module

### ISSUE THREAD

**Issue by mechevarria** [SAPDocuments/Tutorials#4051]
Tutorial URL: https://developers.sap.com/tutorials/xsa-html5-expand-module.html

Please specify the step you are referring to
Step 2: Bind the OData model to a Table

The classname has a typo ```sap.ui.tabke.Table``` should be ```sap.ui.table.Table```

**Comment by Sygyzmundovych** [comment]
Fixed https://github.com/SAPDocuments/Tutorials-Contribution/commit/fb0e93997f470002b1098c8440b61ad4ba2c861b
Thank you!
