### ISSUE TITLE
Configure Initial Setup for SAP Mobile Cards

### ISSUE THREAD

**Issue by jayeshsaini** [SAPDocuments/Tutorials#4052]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-digitalexp-mobilecards-1-setup.html

Please specify the step you are referring to

Step 6
Getting no pop-up on clicking the Create Card Template icon in SuccessFactors My TimeSheet.

**Comment by jitendrakansal** [comment]
Hi @jayeshsaini 
Could you check if you  are seeing a warning message in "Mobile Services cockpit" like mentioned in this issue ? 
https://github.com/SAPDocuments/Tutorials/issues/4022
If so, could you follow the steps as i mentioned there and try again.

**Comment by jayeshsaini** [comment]
Hi @jitendrakansal 
I'm facing the following issue when scanning the QR code and setting up Mobile Cards App on my phone. Not even showing the Welcome Card and any other cards defined by me in subscriptions.
Not sure if the issue is with trail account and Connectivity.

![image](https://user-images.githubusercontent.com/19631970/66827803-20aa0d80-ef6d-11e9-913a-9297fd4122bf.png)

Also when clicking on the Create Card Template icon in SuccessFactors My TimeSheet, I'm getting no popup as showed in tutorial for putting the API Key value. Please check the following step:

![image](https://user-images.githubusercontent.com/19631970/66828104-dc6b3d00-ef6d-11e9-83ec-041eeae54c1a.png)

**Comment by jitendrakansal** [comment]
@jayeshsaini Could we have a short call if you are available? Can you send me a short note to my email address 
jitendra.kansal@sapdotcom , i will send meeting request.

**Comment by jayeshsaini** [comment]
Sure

**Comment by jitendrakansal** [comment]
@thecodester i had a short call with @jayeshsaini ..issue has been resolved, you can close it.

**Comment by thecodester** [comment]
@jitendrakansal If there is something with the solution that you and @jayeshsaini discussed that would be helpful for others, please add it to this issue. And thanks for handling.
