### ISSUE TITLE
SAP Cloud Platform Service is misisng in Data Connection

### ISSUE THREAD

**Issue by i042416** [SAPDocuments/Tutorials#4053]
I am talking about this tutorial:
https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html#8a0bc6ea-d709-445a-8843-ac1011210136

I have a ABAP system service in CloudFoundry environment with API end point:

https://api.cf.eu10.hana.ondemand.com

![clipboard1,1](https://user-images.githubusercontent.com/5669954/66630933-c1c85980-ec37-11e9-915c-6c0e5c3b784b.png)
![clipboard2,2](https://user-images.githubusercontent.com/5669954/66630938-c260f000-ec37-11e9-9e95-afc40995574a.png)

 
I have already created a MTA project following step4:

![clipboard3,3](https://user-images.githubusercontent.com/5669954/66630941-c2f98680-ec37-11e9-9252-5912cc56da7d.png)
![clipboard4,4](https://user-images.githubusercontent.com/5669954/66630943-c2f98680-ec37-11e9-858e-4224317bf037.png)

And add ABAP system service：

![clipboard5,5](https://user-images.githubusercontent.com/5669954/66630945-c2f98680-ec37-11e9-93a3-82af0e798ce8.png)
![clipboard6,6](https://user-images.githubusercontent.com/5669954/66630947-c3921d00-ec37-11e9-8bc9-4d677e927fe6.png)

done：

![clipboard7,7](https://user-images.githubusercontent.com/5669954/66630950-c42ab380-ec37-11e9-95dc-a593bf8eab54.png)

# My problem

![clipboard8,8](https://user-images.githubusercontent.com/5669954/66630952-c42ab380-ec37-11e9-9ed0-b894abc073d9.png)
![clipboard9,9](https://user-images.githubusercontent.com/5669954/66630954-c4c34a00-ec37-11e9-8e83-da9a094a233d.png)

In your tutorial, the menu "SAP Cloud Platform Service" is in Data Connection wizard step:

![clipboard10,10](https://user-images.githubusercontent.com/5669954/66630965-c68d0d80-ec37-11e9-8b06-a4c7b6a509af.png)

unfortunately, I cannot find it in my case:

![clipboard11,11](https://user-images.githubusercontent.com/5669954/66630931-c1c85980-ec37-11e9-8082-43ecfcfa901b.png)

**Comment by mervey45** [comment]
Hi @i042416 

you only can use this with the "normal offering". With ABAP Trial this won't work. 

Best regards, 
Merve

**Comment by thecodester** [comment]
@mervey45 If tutorial only works on purchased software, we need to tag the tutorial as such and make it very obvious.

**Comment by mervey45** [comment]
@thecodester I'll add the license tag.

**Comment by mervey45** [comment]
@I updated this tutorial and all other tutorials, that needed the license tag

**Comment by mervey45** [comment]
@thecodester I updated this tutorial and all other tutorials, that needed the license tag

**Comment by thecodester** [comment]
@mervey45 Thanks. I didn;t see a PR for this. Did you send to production?

**Comment by mervey45** [comment]
@thecodester I just created the pull request: #4066

**Comment by mervey45** [comment]
@thecodester We can close this issue.
