### ISSUE TITLE
Create an ABAP Project in ABAP Development Tools (ADT)

### ISSUE THREAD

**Issue by henwr123** [SAPDocuments/Tutorials#4054]
Tutorial URL: https://developers.sap.com/tutorials/abap-create-project.html

Please specify the step you are referring to - STEP 1

Would you update the step to point to one of the supported Eclipse and Plug-ins?  It mentions Photon and it would be nice to point to on of the more recent versions.

Since 2019-09 just became available, please update to https://tools.hana.ondemand.com/2019-09/

**Comment by julieplummer20** [comment]
Done.
