### ISSUE TITLE
Send Commands with MQTT

### ISSUE THREAD

**Issue by niladri30** [SAPDocuments/Tutorials#4057]
Tutorial URL: https://developers.sap.com/tutorials/iot-cf-send-commands-mqtt.html

Please specify the step you are referring to: Receiving Commands Using the Paho Client

I was able to push the command and received 202 response, whereas; I cannot see the JSON message received. 

I am passing:
{
    "sensorId": "{my-sensorId}",
    "capabilityId": "{my-capabilityId}",
    "command": {
        "RELAY": "true"
    }
}

Could you please suggest?

**Comment by iwonahahn** [comment]
Hi, we have updated the mentioned tutorial based on this issue here https://answers.sap.com/questions/12889011/not-receive-commands-via-mqtt.html?childToView=12889032. Please try again. It should work now as described.

Best regards,
Iwona
