### ISSUE TITLE
Configure Smart Data Integration with the SAP HANA Service

### ISSUE THREAD

**Issue by alexanderparr** [SAPDocuments/Tutorials#4058]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-connect-sdi.html

Please specify the step you are referring to:
Step 1: Connect to the database using the Database Cockpit

Hi,
thank you for providing the tutorial how to setup SDI @ CF. I would love to do that but on SAP CF @ Azure (EU20) the HANA Dashboard is not supported (according to SAP Support), due to the fact how SAP HANA is provisioned.

It would be great to know a solution for this problem and / or reflect these informations in the tutorial and in the offical documentation :-)

Kind regards,
Alexander Parr

**Comment by rbrainey** [comment]
Hi Alexander, 

I'm investigating a couple of things now on this.  It is true that HANA as a Service instances in AWS (either us10 or eu10) will expose the most complete functionality today, although plans have Azure regions catching up fast.

Let me investigate a couple of things and I'll report back ...

**Comment by alexanderparr** [comment]
Hi @rbrainey,
thank you for taking care. Please have a look at SAP Ticket 627419 / 2019. It was confirmed, that SDI @ Azure is not supported right now.

Thanks,
Alexander

**Comment by rbrainey** [comment]
Thanks for the info, Alexander. Is running this in an Azure region a hard requirement for you?  If not, it is possible to switch regions for a SAP Cloud Platform Trial.  I'll close this issue after you've had a chance to reply.  Regards,

**Comment by alexanderparr** [comment]
For the project I'm working on it is relevant and we switched to another Hyperscaler until it is provided on Azure. However, it had saved me hours, if it would have been documented somewhere.

**Comment by thecodester** [comment]
@rbrainey Should the tutorial be updated in any way or can we close the issue?

**Comment by MichaelCzcz** [comment]
@rbrainey Should the tutorial be updated in any way or can we close the issue?

**Comment by se-wo** [comment]
Hi @alexanderparr ,
not working SDI on Azure is plain wrong. Maybe SAP is not officially supporting this but it works fine, don´t know. I have it working in production.
Never use HANA as Service tutorials for Azure instances as all of them are targeted towards AWS. Frankly, most SAP staff does not know the difference between both services or that there at least is a difference. This is also why I can´t recommend using HAAS on Azure to anyone if you did not already heavily invest into SCP on Azure.
SCP is on Azure is sofar a terrible product, Application Runtimes are much more costly, featureswise it is behind AWS in all aspects (No access to HDI containers from NEO WebIDE) and the documentation is lackluster.
Just treat any HAAS on Azure instace as on-premise system or HAAS 1.0 system. See [https://help.sap.com/viewer/7952ef28a6914997abc01745fef1b607/2.0_SPS04/en-US/cef2129eea944e7ab11b2fb723ab3196.html](https://help.sap.com/viewer/7952ef28a6914997abc01745fef1b607/2.0_SPS04/en-US/cef2129eea944e7ab11b2fb723ab3196.html)
This tutorial works fine. All that did not work is registering adapters using the DP agent. Instead I created them directly using SQL commands using the SQL Console.
My recommendation towards SAP: Create seperate tutorials as long as Azure and AWS need to be treated different and make people aware of this fact.
Anyone having problems feel free to contact me.
