### ISSUE TITLE
SAP Data Intelligence - Modeler: No tenant found

### ISSUE THREAD

**Issue by schefa** [SAPDocuments/Tutorials#4059]
Tutorial URL: https://help.sap.com/viewer/5ac15e8fccb447199fda4509e813bf9f/Cloud/en-US/7def2149758741d59c28436d8ab21c3d.html

When I run any of your training sample code, the Modeler throughs this error

`Graph failure: operator.com.sap.ml.training:training-0: Job was not submitted { "error": { "code": "412", "message": "No tenant found" } } |`

I am using SAP Data Intelligence logged in as an admin on tenant "default"

**Comment by thecodester** [comment]
Which tutorial does this refer to?

**Comment by schefa** [comment]
The tutorial url is in the description...

Home/ML Scenario Manager/Set Up Your Machine Learning Scenario/Add a Jupyter Notebook/JupyterLab Environment/SAP Data Intelligence Python SDK/ **Working with Training Pipelines**

https://help.sap.com/viewer/5ac15e8fccb447199fda4509e813bf9f/Cloud/en-US/7def2149758741d59c28436d8ab21c3d.html

**Comment by thecodester** [comment]
This repository (and issues) is for issues related to tutorials in the [SAP Tutorial Navigator](https://developers.sap.com/tutorial-navigator.html).

For documentation, there is a "Send feedback" link.
