### ISSUE TITLE
Add Transactional Behavior to Your Core Data Services

### ISSUE THREAD

**Issue by brehberg** [SAPDocuments/Tutorials#4060]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-transactional-enablement.html

Please specify the step you are referring to **Step 6: Test yourself**

It appears that the correct answer still refers to an older syntax for RAP unmanaged.  I was able to pass this step with first line as: `implementation unmanaged;`

**Comment by mervey45** [comment]
Hi @brehberg,

I'll update this. Thank you for your feedback. 

Best regards, 
Merve

**Comment by mervey45** [comment]
@thecodester This has been added, we can close this issue

**Comment by mervey45** [comment]
@thecodester It has been updated
