### ISSUE TITLE
Add Web Content to Your Portal Site and Set the Layout

### ISSUE THREAD

**Issue by nievesnavarro1** [SAPDocuments/Tutorials#4061]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-add-webcontent.html

All the options seems posible but I can't complete the last question. I have tested all the combinations with the 4 answers.

**Comment by thecodester** [comment]
I am able to complete the tutorial -- can you try again and provide screenshot?

**Comment by nievesnavarro1** [comment]
i'm actually able to complete the tutorial too, and the result it's really
cool, but in the last step (Step 6: Review your site) i'm not able to
answer the question correctly, all the options look correct to me.

**Comment by thecodester** [comment]
I'm saying I can answer the question. Not all the items can you set in a page section settings area.

There are 16 combinations of possible answers. Did you try all of them?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
