### ISSUE TITLE
Call an External API: Screenshots for Step 3 are from the wrong example

### ISSUE THREAD

**Issue by DerGuteWolf** [SAPDocuments/Tutorials#4062]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-external-api.html

Screenshots for Step 3 are from the wrong example, This tutorial is for nominatim access, not chuck norris jokes...

**Comment by julieplummer20** [comment]
Done

**Comment by DerGuteWolf** [comment]
@julieplummer20 : are you sure this is fixes? I still der Chuck Norris Jokes in the Screenshots from step 3.

**Comment by julieplummer20** [comment]
Hi, Sorry, on closer examination, I have made the changes, but they are not yet publicly visible. Not a tool problem- the error was mine. I will resolve this on Monday, when I am back in the office. Best wishes Julie
