### ISSUE TITLE
Create Table Persistence and Generate Data

### ISSUE THREAD

**Issue by jakes2255** [SAPDocuments/Tutorials#4071]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-persistence.html

Please specify the step you are referring to: Step1 or any particular step in the tutorial.

Second time after exiting Eclipse and then log in, authentication succeeds. But the Packages are not getting loaded.

Step1: Exit the Eclipse IDE
Step2: Try to view the ABAP project
Step3: Logon screen opens  up 
Step 4: Provide credentials and then the above situation occurs.

![EclipseADTError](https://user-images.githubusercontent.com/40160913/66902735-c5385800-f01e-11e9-907e-75b03d1d29c3.png)

SAP note on the same(notes/0002755002) refers to [Messaging Service Instance](https://help.sap.com/viewer/bf82e6b26456494cbdd197057c09979f/Cloud/en-US/d0483a9e38434f23a4579d6fcc72654b.html) which looks like the repetition of steps. In addition to email id, it has details like 'version', 'namespace' etc.

Please advice how to proceed.

Thank you,
Jakes

**Comment by MichaelCzcz** [comment]
@jakes2255 Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
