### ISSUE TITLE
Create a Communication Arrangement for Outbound Communication

### ISSUE THREAD

**Issue by smile-ot** [SAPDocuments/Tutorials#4074]
Tutorial URL: https://developers.sap.com/tutorials/abap-env-create-comm-arrangement-api.html

Hi,

I am doing this tutorial with a trial abap instance and I am stuck at step 6. I am able to log in to the ABAP system, but it seems my user has a very limited permission and there is no app to create a communication scenario. How could I request more permission?

**Comment by Dagravio** [comment]
Hello Julie,

Got stuck on the same issue and I know that it is because of the business catalog. I've check other tutorials and you can do this from the launchpad via "Maintain Employee" app but it's also not available.

Thanks,
Dimmak

**Comment by ruthvikg193** [comment]
Hello Julie,
As you have directed in the response earlier, I tried to open the following link:
"https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/f65e51a7203443efb58fe535c3d13e5f.html"

This is used to maintain the business roles. But when I launch the Fiori Lauchpad (link taken from the Eclipse ADT), I end up NOT getting the title to maintain business roles.

Can you please look into this and let the community know how to go about the these configs?

Thanks,
Ruthvik.

**Comment by ruthvikg193** [comment]
Hi Julie,
I checked that and found that I am indeed administrator.

![SCP_Admin](https://user-images.githubusercontent.com/56668708/69220753-b738a280-0b9b-11ea-8d91-f5efa25d0020.jpg)

Thanks,
Ruthvik.

**Comment by julieplummer20** [comment]
Hi @ruthvikg193, 
I am currently investigating this. I will get back to you.
Best wishes,
Julie.

**Comment by julieplummer20** [comment]
Hi @ruthvikg193 , 
Sorry, I should have realized earlier: You are using a trial. It is not possible to create Communication Arrangements etc in the ABAP Environment Trial version. If you look at the title, there is a Key icon beside it - this means that you must have a license version.
Sorry about the delay.
Best wishes,
Julie.
PS - can you please close this ticket?
