### ISSUE TITLE
Small Observation during mimicking ABAP on Cloud Tutorials

### ISSUE THREAD

**Issue by ruthvikg193** [SAPDocuments/Tutorials#4076]
Hi Merve Temel,

It is a fabulous guide to explore new offerings in ABAP on Cloud. 

But, I have observed a small issue in the CDS Root View "ZI_TRAVEL_M_XXX" where you have defined @AccessControl.authorizationCheck as "#CHECK".

But, while creating the consumption or rather projection view "ZC_TRAVEL_M_XXX", it is given as @AccessControl.authorizationCheck: #NOT_REQUIRED. 

It is conflicting in nature. It would be great if you can address my concern by either letting me know if my understanding is correct OR there is a need to change in your sample code.

Thank You.

**Comment by mervey45** [comment]
Hi @ruthvikg193, 

thank you for your feedback, I'll involve my colleagues. 

Thank you. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
@mervey45 any updates? Can I close the issue?

**Comment by mervey45** [comment]
@MichaelCzcz I created following pull request #4319. You can close this issue.

**Comment by mervey45** [comment]
@thecodester  We can close this issue
