### ISSUE TITLE
Open SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by jitendrakansal** [SAPDocuments/Tutorials#4079]
Hi, 

screenshots are not visible. 
<img width="1167" alt="Screenshot 2019-10-18 at 12 32 39 PM" src="https://user-images.githubusercontent.com/31536700/67087578-7c5ddc00-f1a3-11e9-8eb1-edaaed10e8ad.png">

**Comment by thecodester** [comment]
@IObert I think you assumed that you can you reuse images from other tutorials -- via specifying path to another tutorial -- but you cannot currently. You'll have to copy images to that folder.

**Comment by IObert** [comment]
Thanks for reporting @jitendrakansal
