### ISSUE TITLE
Enable Essential Neo Services

### ISSUE THREAD

**Issue by juancarlosrodriguezf** [SAPDocuments/Tutorials#4081]
Tutorial URL: https://developers.sap.com/tutorials/cp-enable-essential-neo-services.html

Please specify the step you are referring to "Click on the “Go To Service” action for the portal service, and past the URL that you will be directed to?", I tried this one, but the 'answer' is not correct:  
https://flpportal-p2000727752trial.dispatcher.hanatrial.ondemand.com/sites/adminspace

**Comment by thecodester** [comment]
@juancarlosrodriguezf When I go to the URL you specified (for my trial account, of course), it redirects me to a longer URL. Do you get the portal "Admin Space" with a "Welcome to SAP Cloud Platform Portal" title?

@jarjarbentley Can you help here?
