### ISSUE TITLE
Create Your Own SAP Fiori Launchpad

### ISSUE THREAD

**Issue by juancarlosrodriguezf** [SAPDocuments/Tutorials#4082]
Tutorial URL: https://developers.sap.com/tutorials/cp-fiori-create.html

Please specify the step you are referring to "Step 6: Validate your Fiori Launchpad" my answer is not valid and I don't understand why:
https://flpportal-p2000727752trial.dispatcher.hanatrial.ondemand.com/sites

**Comment by thecodester** [comment]
@IObert Can you take a look at this one?

**Comment by IObert** [comment]
This should be the correct answer. It checks if your input matches `https://flpportal-[id]trial.dispatcher.hanatrial.ondemand.com/sites`. Are you logged in with the same user that matches the p-user from your answer? 
Otherwise, I could be related to the trailing whitespaces

**Comment by juancarlosrodriguezf** [comment]
Thanks!
