### ISSUE TITLE
Create a New Welcome Card

### ISSUE THREAD

**Issue by jatinj** [SAPDocuments/Tutorials#4083]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html

Please specify the step you are referring to, 

I noticed that when I pressed the Save button to finally save the Welcome Card, it's state was still development. So, you should add one more screenshot, which shows that on click of Mobile card, scroll down to Versions table and then tap on actions to change the state from development to productive. Once that is done, the mobile card is pushed. Just in case, if not pushed, user can pull the mobile card by getting out of the app and then getting in again. 

<img width="482" alt="Screen Shot 2019-10-18 at 10 51 46 PM" src="https://user-images.githubusercontent.com/7816298/67137386-e30de480-f1f9-11e9-8e57-b4d8724fcbfd.png">

**Comment by jitendrakansal** [comment]
@jatinj you are right, we are aware of it. we ll update the tutorial in next few weeks.
Thanks for pointing out.

**Comment by jitendrakansal** [comment]
@thecodester this issue can be closed. 
Author @jatinj pointed out a missing step, this tutorial will be updated after TechEd Bangalore.

**Comment by thecodester** [comment]
@jitendrakansal  If OK with you, let's keep open until tutorial is updated. Please add a comment when that is complete and I will close issue. Thanks for all your help.

**Comment by MichaelCzcz** [comment]
@jitendrakansal any updates?

**Comment by jitendrakansal** [comment]
@MichaelCzcz still working..hoping to create PR in next couple of days.

**Comment by jitendrakansal** [comment]
@MichaelCzcz we have already updated the tutorial. Please check it.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
