### ISSUE TITLE
Maintain a Communication Arrangement for Inbound Communication

### ISSUE THREAD

**Issue by marcfrenay** [SAPDocuments/Tutorials#4086]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

Please specify the step you are referring to STEP 8 :
I have only those options :
![image](https://user-images.githubusercontent.com/56831459/67208343-a74f6680-f415-11e9-9f41-fc6466af6855.png)

What can I do change this?

**Comment by mervey45** [comment]
Hi @marcfrenay, 

are you trying to do this tutorial with the trial offering?

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @marcfrenay ,

you can't do this tutorial with the trial. You need a license to do so. 
We added the license tag to this tutorial.

Best regards, 
Merve
