### ISSUE TITLE
Create Your First Fiori for iOS App

### ISSUE THREAD

**Issue by parry146** [SAPDocuments/Tutorials#4088]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-scpms-teched18-02.html

Please specify the step you are referring to  

Create Your First Fiori for iOS App - Step #5 gives an error

![Screen Shot 2019-10-22 at 7 52 52 PM](https://user-images.githubusercontent.com/47413309/67273721-bc59f180-f50a-11e9-93cd-50c3bd969006.png)

**Comment by parry146** [comment]
....been trying to debug using information in step #6 ... getting the followinge error message..
![Screen Shot 2019-10-22 at 10 36 54 PM](https://user-images.githubusercontent.com/47413309/67282111-b2d98500-f51c-11e9-99bf-c951cddb6f01.png)

**Comment by parry146** [comment]
re do the steps again.., still the same state.... any updates.. pls
![Screen Shot 2019-10-25 at 11 23 18 AM](https://user-images.githubusercontent.com/47413309/67534498-1a105880-f71a-11e9-8d4f-8f9e8ceca04a.png)

**Comment by KevinMuessig** [comment]
There is a new version out in the store. Could you please try downloading and using that?!

**Comment by MichaelCzcz** [comment]
@parry146 Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
