### ISSUE TITLE
Enhance CAP-Based Service to Refer to Remote Addresses

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#4091]
Tutorial URL: https://developers.sap.com/tutorials/cap-cloudsdk-4-enhance-consume.html

In Step 8 you mention "You’ll address this in the next tutorial in this mission.". Unfortunately this tutorial isn't assigned to a mission yet. Only when I use [SAP TechEd 2019 App Space − Tutorial Missions](https://developers.sap.com/app-space.html) I can work through the S/4HANA Extensions with Cloud Application Programming Model (CAP) mission.

**Comment by iwonahahn** [comment]
This issue can be closed. The tutorial mentioned by Gregor is now linked to the mission Use CAP and SAP Cloud SDK to Extend S/4HANA (see the mission at the bottom of the tutorial).
