### ISSUE TITLE
Open SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#4094]
Tutorial URL: https://developers.sap.com/tutorials/webide-multi-cloud.html

Please specify the step you are referring to
Step 2

The Tutorial is not accepting the link I copied into the box:
https://webidecp-p1005717trial.dispatcher.hanatrial.ondemand.com/ 

Message:
" Sorry, that’s incorrect. Please try again."

Does it - like in some other tutorials - expect it to be written in a specific way or has the format of the link changed since the tutorial was created?

**Comment by IObert** [comment]
Hi @BaerbelW,

the solution should match `https://webidecp-[id]trial.dispatcher.hanatrial.ondemand.com` where [id] is the placeholder of your p-user (i.e. the trailing slash need to be removed). Please let me know if this works

**Comment by BaerbelW** [comment]
Hi @IObert,

I just tried again but it doesn't like it either without the slash at the end. Somehow these "copy & paste" type answers are not working very well in the tutorials as the verification logic seems to be way too "nitpicky"!

**Comment by IObert** [comment]
I agree these strict validations are not helpful :( I'll change the logic of the validation.

Please try the same input again in a few minutes

**Comment by BaerbelW** [comment]
Thanks, Marius! Now it works and accepts the copied URL.

Cheers
Bärbel
