### ISSUE TITLE
Analyze AMDP Performance

### ISSUE THREAD

**Issue by XanctusDelta** [SAPDocuments/Tutorials#4097]
In step 1 of the tutorial, it says that you need to create a package under /DMO/SAP. Upon checking, there is no package /DMO/SAP in the eclipse. I don't know where to find it.

**Comment by julieplummer20** [comment]
Hi Xanctus, 
NOTE: I am updating the tutorial, so it's probably better if you wait until you see the new one. I will release it asap.
Just out of interest, what system are you using?
Is it on-premise; if so, it doesn't matter.
If it is Steampunk, ie SAP Cloud Platform, ABAP Environment, then this no longer applies - just create a normal package in your normal SW component. As I say, I am updating the tutorial to reflect this.
Best wishes,
Julie.

**Comment by thecodester** [comment]
@julieplummer20 Can we close this ticket? Have you updated the tutorial?

**Comment by julieplummer20** [comment]
Hi @thecodester , hi @XanctusDelta , 
Yes, I have updated the tutorial. You can close this issue.
Best wishes,
Julie.
