### ISSUE TITLE
Create an SAPUI5 Purchase Order App

### ISSUE THREAD

**Issue by juancarlosrodriguezf** [SAPDocuments/Tutorials#4098]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-ms-graph-create-app.html

Please specify the step you are referring to "Step 7: Deploy to the Neo environment", which is the correct URL?

I try 'https://purchaseorderapp-[id]trial.dispatcher.hanatrial.ondemand.com/index.html?hc_reset' and it doesn't work

**Comment by IObert** [comment]
Did you try the URL with the `[id]` placeholder? Please insert the URL that you see in your browser (without the placeholder)

**Comment by IObert** [comment]
Are you sure the application is running? The validation will check the HTTP status code that is being returned from there. To me, this URL is not accessible (e.g. it doesn't return code 200).

**Comment by juancarlosrodriguezf** [comment]
Solved, it was a spelling error. Thanks.

**Comment by yogananda-muthaiah** [comment]
we are getting similAR error while submitting the url in the text comment box

**Comment by IObert** [comment]
@yogananda-muthaiah 
Are you working on the same tutorial? If so, please create a new issue and add details about the related step so we can follow up on this.
