### ISSUE TITLE
Need more input for tutorial - Create Business Partner in S/4HANA Cloud using ABAP Environment Data

### ISSUE THREAD

**Issue by i042416** [SAPDocuments/Tutorials#4099]
dear colleague,

When I am trying to study tutorial [Create Business Partner in S/4HANA Cloud using ABAP Environment Data](https://developers.sap.com/tutorials/abap-environment-business-partner.html), I am even stuck the very first step: 

# Step 1: Download service metadata

There is only one pure sentence without any example / screenshot provided:
![image](https://user-images.githubusercontent.com/5669954/67459047-394fad00-f66a-11e9-8117-83aa01a56b09.png)

> Copy the service URL from communication arrangement on S/4 HANA Cloud system in a browser.

My question:

1. Is the mentioned communication arrangement created in **S/4HANA cloud system**, or in **SAP Cloud Platform ABAP environment** ?

2. Can you please kindly elaborate a little more about where could we locate such communication arrangement? Where can we find its service url? Can you please provide an example of service url?

I am sure this will definitely be beneficial to a lot of beginners. Thanks a lot for your great work!

Best Regards,
Jerry

**Comment by mervey45** [comment]
Hi @i042416, 

you need to copy the communication arrangement URL from the S/4HANA Cloud system. 
You need to open the communication arrangement you've created earlier, the URL will be listed and then you need to paste it in your browser. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
@i042416 Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
