### ISSUE TITLE
Time Series with SAP HANA APL Forecast (Forecast SQL)

### ISSUE THREAD

**Issue by jberthe** [SAPDocuments/Tutorials#4100]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aa-forecast-sql-04.html

Step :Run the algorithm with “No Extra Predictors”
I have this error in my console : 

Statement 'truncate table apl_cashflow_indicators' 
successfully executed in 66 ms 834 µs  (server processing time: 7 ms 434 µs) - Rows Affected: 0 
**java.sql.SQLWarning: wrong number or types of parameters in call: Column mismatch happened at "SAP_PA_APL"."sap.pa.apl.base::FORECAST": Declared type "NCLOB"  of attribute "VALUE" not same as assigned type "NVARCHAR(5000)"** 

Could not execute 'call sap_pa_apl."sap.pa.apl.base::FORECAST" ( apl_cashflow_function_header , ...' in 1.812 seconds . 
**SAP DBTech JDBC: [362]: invalid schema name: "SAP_PA_APL"."sap.pa.apl.base::FORECAST": line 20 col 3 (at pos 878): "SAP_PA_APL"."sap.pa.apl.base.internal::GET_PROCNAME_2": line 50 col 6 (at pos 2233): [362] (range 3) invalid schema name exception: invalid schema name: "SAP_PA_APL"."sap.pa.apl.base.internal::GENERATE_TYPE": line 37 col 5 (at pos 1493): APL_CACHE: line 1 col 13 (at pos 12)** 
Duration of 5 statements: 2.082 seconds

**Comment by jarjarbentley** [comment]
Sorry for the delay, is this still an issue.  If so I will try and recreate on my side.
