### ISSUE TITLE
Learn Annotation Basics for OData and Fiori

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#4101]
Tutorial URL: https://developers.sap.com/tutorials/odata-04-basic-annotations.html

Please specify the step you are referring to
Step 5 - Specify the OData Service

I'm trying to work through the tutorial but am hitting an auth pop-up when selecting the system as shown. I'm fairly certain that I'm putting in the correct data (what the browser has stored and what has worked thus far throughout the mission) but I'm not able to get over the pop-up: it always gets displayed again with the entries reset to empty. What can I try to proceed?

![Tutorial-Odata-ServiceCatalog-Logon](https://user-images.githubusercontent.com/18588108/67482867-cf80d480-f664-11e9-988b-eb69ef648b25.jpg)

Thanks & Cheers
Baerbel

**Comment by BaerbelW** [comment]
When I tried again, I get the pre-populated pop-up but it still doesn't accept my credentials and just displays the pop-up again after clicking on "login".
![grafik](https://user-images.githubusercontent.com/18588108/67546556-fd195c80-f6fc-11e9-89c8-f20d0a3677dd.png)

Should I try to set up a new SAP_Gateway connection as explained in the previous tutorial or is there a "password reset" functionality I can use?

Cheers
Baerbel

**Comment by qmacro** [comment]
Hi Baerbel - you can request a password reset here: https://register.sapdevcenter.com/SUPSignForms/ 

When you (re)create the destination, ensure you use the `sap-client` parameter as shown in Step 4 of the previous tutorial https://developers.sap.com/tutorials/teched-2016-3.html

**Comment by BaerbelW** [comment]
Thanks, DJ!

Turned out that I didn't need to request a new password: when I opened the sapdevcenter-page, I realised that the trial account for the gateway demo system was for my S-User (the "P123456789" mentioned in the tutorial had me confused). Once I updated the user and password in my connection definition, I was able to login and continue with the tutorial.

Cheers
Bärbel
