### ISSUE TITLE
Develop an SAP Fiori App Using ABAP

### ISSUE THREAD

**Issue by VenkateshhKonduri** [SAPDocuments/Tutorials#4106]
Mission URL: https://developers.sap.com/mission.cp-starter-extensions-abap.html

Extremely great mission. When adding a travel, I used the end date before the start date but it still accepted. I guess we need to build a validation logic on Dates. Good mission overall.

**Comment by mervey45** [comment]
Hi @VenkateshhKonduri , 

thank you for your feedback. There is a validation, which tests the start and end date. If your end date is before the start date, then there should be an error message. Please test it again.

Best regards, 
Merve

**Comment by mervey45** [comment]
@thecodester we can close this issue.
