### ISSUE TITLE
Execute the APL Forecast algorithm (Forecast App)

### ISSUE THREAD

**Issue by hml8** [SAPDocuments/Tutorials#4107]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aa-forecast-13.html

Please specify the step you are referring to
step 9, execute APL forecast on Ozone LA data

The timestamp in the data set is stored in format 1971-12-28 12:00:00  
This format is required by the oData service too. The UI convert the selected date to 
Sun Nov 28 1971 00:00:00 GMT+0000 (Coordinated Universal Time)
and passes this on to:  
POST https://<servername>:51029/xsjs/apl/forecast.xsjs 
=>     400 (Bad Request)

I'm using HANAexpress 2.0 SP 04

**Comment by adadouche** [comment]
HI @hml8, @MichaelCzcz & @jarjarbentley ,

I no longer work for SAP so I won't be able to fix the content if needs be.

When calling the xsjs, it should send a date in the yyyy-mm-dd format.

On the following screen, you should have date with the same format : 
![image](https://user-images.githubusercontent.com/1446764/70071766-1a8fef00-15f6-11ea-99cc-3806da14a313.png)

There is a formater behind it in the SAPUI5 app to handle the conversion properly.

Hope this will help to debug.

**Comment by thecodester** [comment]
@jarjarbentley @Sygyzmundovych Can you take a look at this?

**Comment by MichaelCzcz** [comment]
@jarjarbentley @Sygyzmundovych Can you please take a look at this?

**Comment by jarjarbentley** [comment]
@hml8  did the note from Abdel help?  If not, please re-open issue.


"I no longer work for SAP so I won't be able to fix the content if needs be.
When calling the xsjs, it should send a date in the yyyy-mm-dd format.
On the following screen, you should have date with the same format" (see pic in above comment)
