### ISSUE TITLE
Execute the PAL Auto Smoothing algorithm (Forecast App)

### ISSUE THREAD

**Issue by hml8** [SAPDocuments/Tutorials#4108]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aa-forecast-15.html

Please specify the step you are referring to
inconsistent naming of files and references  ... "auto_smoot**h**ing"  and "auto_smooting" 
=> route not found

**Comment by jarjarbentley** [comment]
while the syntax does change from one section to another the smoothing action can be performed, correct?
