### ISSUE TITLE
Create an SAP Cloud Platform ABAP Environment Trial User

### ISSUE THREAD

**Issue by wassupgon** [SAPDocuments/Tutorials#4109]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html

Cannot find ABAP Trial here..

![image](https://user-images.githubusercontent.com/51322014/67563610-572c1900-f721-11e9-8b63-6aeacc6e57d8.png)

**Comment by mervey45** [comment]
Hi @wassupgon, 

please make sure you have configured the entitlements (step 2) and you have Europe frankfurt as a region for your subaccount. And make sure, you have a dev space.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
@wassupgon Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
