### ISSUE TITLE
Learn Annotation Basics for OData and Fiori

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#4110]
Tutorial URL: https://developers.sap.com/tutorials/odata-04-basic-annotations.html

Please specify the step you are referring to
Step 13: Add Header information

Me again!

When I add UI.HeaderInfo, I'm only asked to specify 2 instead of 3 items. The one for "Title" seems to be missing:
![grafik](https://user-images.githubusercontent.com/18588108/67564394-1d5c1200-f723-11e9-8fe4-93955de17d0b.png)

Most likely due to this, no "Name" is shown for a selected line item:
![grafik](https://user-images.githubusercontent.com/18588108/67564774-0669ef80-f724-11e9-958f-4b21e1087559.png)

I tried adding the "Title" field manually by clicking "+" for the UI.HeaderInfo-node. The field shows without the "*" for a mandatory field and can be selected:
![grafik](https://user-images.githubusercontent.com/18588108/67565081-d53def00-f724-11e9-9da4-fd23b107be11.png)

But, I cannot select the "Name" field as nothing meaningful shows up in the drop-down list:
![grafik](https://user-images.githubusercontent.com/18588108/67565233-35cd2c00-f725-11e9-89a7-d29cf46f7819.png)

Up to this point, everything had fit the descriptions in the tutorial so I don't know where I may have gone wrong or what I could check.

Cheers
Bärbel

**Comment by qmacro** [comment]
Hi Baerbel, I've checked this out (see also https://twitter.com/qmacro/status/1192464545853427712 ;-) and made a modification to the tutorial, to take into account that, as you've noticed, the addition of a UI.HeaderInfo Title property is not supported now in the Annotation Modeler ... but you can add it directly, manually, as it were. So Step 13 is now different, showing you how you can add annotations directly to the XML. Thanks for bringing this to my attention! 

Changes made in https://github.com/SAPDocuments/Tutorials/commit/2460f5a1327dabcce1ebb396dd53b404beb08bf2
