### ISSUE TITLE
Configure Initial Setup for SAP Mobile Cards

### ISSUE THREAD

**Issue by pavan141080** [SAPDocuments/Tutorials#4114]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-digitalexp-mobilecards-1-setup.html

Please specify the step you are referring to

9. Switch back to Mobile Services cockpit, paste the copied API key in the open pop-up, and then choose OK.

I missing this step, can you please explain how to maintained copied API key?

**Comment by jitendrakansal** [comment]
@pavan141080 could you share some more info? 
Were you not able to copy the API key? 
This key is from API hub sandbox system specific to your account. you can get this key from https://api.sap.com/preferences , login with cloud platform credentials, click "Show key"

**Comment by jitendrakansal** [comment]
@pavan141080  has your issue been resolved? 
Let me know if you need any help.

**Comment by pavan141080** [comment]
Hi Jitendra,

Yes, I need help on step9
Switch back to Mobile Services cockpit, paste the copied API key in the open pop-up, and then choose OK.

I have API key from Step8. I don't see a Pop-Up to paste the API key as mentioned in Step9

**Comment by jitendrakansal** [comment]
@pavan141080  We found that there is a bug with some SF template, e.g. if you choose TimeSheet, you wont see pop-up window (we have fixed it in one of upcoming release)
Could you try with MyToDo template and see if you get the pop-up to enter API key?

**Comment by jitendrakansal** [comment]
@pavan141080 tutorial has been updated with this change. Please try again, issue should be resolved now.

**Comment by MichaelCzcz** [comment]
@pavan141080 Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
