### ISSUE TITLE
Create a Project to Author Rules

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#4115]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules04-create-project.html

Please specify the step you are referring to

Step: 1

There is a massive assumption here that users know which page to launch. There needs to be a blurb at the start (before the Step 1 instructions) to tell the user they must run their Business Rules application URL they saved from one of the previous tutorials. I worked it out in the end but this was not clear. 

Just my suggestion. Otherwise, all good! 

thanks
Phil Cooley

**Comment by VandanaVasudevan** [comment]
Hi Phil,

Thanks for your feedback. I'm working on it. I'll be pushing the updated tutorials soon.

Best Regards,
Vandana

**Comment by MichaelCzcz** [comment]
@VandanaVasudevan any updates?

**Comment by VandanaVasudevan** [comment]
Hi Michael,

The tutorials are updated. We can close this issue if there are no further comments.

Best Regards,
Vandana

**Comment by MichaelCzcz** [comment]
@pjcools Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
