### ISSUE TITLE
Test the Business Rules API from SAP API Business Hub

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#4117]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules09-test-apis.html

Please specify the step you are referring to:
Step 4. When I tested the Business Rules API I received an Unauthorised 401 message and nothing returned due to this error. 

{
  "error": "unauthorized",
  "error_description": "Full authentication is required to access this resource"
}

Content-Length: 102 
 Expires: 0 
 Server: tomcat 
 Cache-Control: no-cache,  no-store,  max-age=0,  must-revalidate, no-store 
 Pragma: no-cache, no-cache 
 X-Content-Type-Options: nosniff 
 X-Vcap-Request-Id: 9cca6e85-dfbc-46eb-48c1-5904c4c9651a 
 X-Frame-Options: DENY 
 X-Xss-Protection: 1; mode=block 
 Strict-Transport-Security: max-age=31536000; includeSubDomains; preload; 
 Date: Sun,  27 Oct 2019 06:10:28 GMT 
 Vary: Accept-Encoding 
 Www-Authenticate: Bearer realm="oauth2-resource",  error="unauthorized",  error_description="Full authentication is required to access this resource" 
 Content-Type: application/json;charset=UTF-8 

I checked my Business rules Service Key and triple checked I was using the right values for the configuration. Also checked the ID of the DetermineEquipmentRuleservice (rule service) I was using and this was correct. 

Am I doing something wrong here? I finished the tutorial however would have liked to see a positive end result. 

Thanks & Kind Regards
Phil Cooley

**Comment by VandanaVasudevan** [comment]
Hi Phil,

Can you please check if you have deployed the rule service (DetermineEquipmentRuleservice) in the Manage Rules Project application?

Best & Regards,
Vandana

**Comment by ArchanaShukla** [comment]
Hello Phil,
Hope the issue is resolved. This error usually comes if either of the token/runtime/repository URL is not correct, or username and password don't match. Let me know if it gets resolved.

**Comment by MichaelCzcz** [comment]
@pjcools Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by RamkumarKrishnasamy** [comment]
I am also facing the same problem. When I try to deploy to HANA system. The RuleSuperUser is assigned to my user id.

**Comment by ArchanaShukla** [comment]
Hello Ramkumar,
This tutorial is not related to SAP HANA deployment. I have already responded to you in the blog. please check all your configuration. This issue comes when you had wrong credentials

**Comment by shruti0487** [comment]
Hi Archana, I am facing the same issue while testing the API from API Business Hub. Following role collections have been assigned to by user in BTP trial account
![Capture](https://user-images.githubusercontent.com/71022501/119147196-feda0c00-ba68-11eb-97a4-2db1c065c001.JPG)
and both the rules services are deployed as instructed in the blog
![Capture](https://user-images.githubusercontent.com/71022501/119147336-1d400780-ba69-11eb-9d8c-8087ab16f65f.JPG)
