### ISSUE TITLE
Add API Business Hub API to a UI5 Application

### ISSUE THREAD

**Issue by minok104** [SAPDocuments/Tutorials#4118]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-api-ui5-app.html

Please specify the step you are referring to

Step 2: Get JavaScript pre-generated code

I copied the sample code from Code Snippet and submit answer.
It became "Sorry, that’s incorrect. Please try again."
I think there is an version issue.
Please fix to latest version.
![image](https://user-images.githubusercontent.com/46273748/67632463-ed5d6c00-f8e6-11e9-99d2-240d439fc7ca.png)

**Comment by thecodester** [comment]
@IObert Can you look at this? Feel free to reassign if necessary.

**Comment by IObert** [comment]
Thanks for opening this issue. You are right, the snippet has been updated which is why the old solution doesn't work anymore.

I updated the solution to accept the correct answer. Please try again in a couple of minutes

**Comment by minok104** [comment]
Thank you for the update.
I passed the check.
