### ISSUE TITLE
Maintain a Communication Arrangement for Inbound Communication

### ISSUE THREAD

**Issue by Dagravio** [SAPDocuments/Tutorials#4119]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

Hello Team,

I'm following the tutorial to connect SAP Cloud Platform to my 7.52 SP04 ABAP Server but got stuck at the step ( Step 6: Create a communication arrangement using the service key ). There are only two options on the dashboard ( SQL Trace and SQL Explain ) when it opens up. I think this is because I don't have  "SAP_CORE_BC_COM" business catalog assign to my user. 

Thanks,
Dimmak

**Comment by mervey45** [comment]
Hi @Dagravio ,

this tutorial is for SAP Cloud Platform ABAP Environment. You can do this with our cloud offering. 

Best regards, 
Merve
