### ISSUE TITLE
Deploy Your First SAPUI5 App to Cloud Foundry

### ISSUE THREAD

**Issue by jackleetw** [SAPDocuments/Tutorials#4120]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-webide-new-app.html

Please specify the step you are referring to
Step 4: Deploy the archive to Cloud Foundry

I try to deploy to Cloud Foundry but failure
the error log as attached
and I been check the help , no idea where I perform wrong steps or missed something

[MAIN_LOG.TXT](https://github.com/SAPDocuments/Tutorials/files/3776978/MAIN_LOG.TXT)

**Comment by IObert** [comment]
It seems that the "destination" service is not activated in your trial account. Please [configure the entitlements ](https://blogs.sap.com/2019/06/05/the-new-way-to-manage-entitlements-and-quotas-on-sap-cloud-platform-cockpit/)of your account and add the service plan "destination"

**Comment by IObert** [comment]
I'll close this issue due to inactivity, please reopen if needed.
