### ISSUE TITLE
Remote sources error 

### ISSUE THREAD

**Issue by PROD-BR3-MRI** [SAPDocuments/Tutorials#4123]
I Lucia, I have successfully check all the steps off your tutorial, but when I try to open the remote source I've got the following error message : The requested backend service did not succeed
{"error":{"code":"500","message":{"lang":"en-US","value":"Error while executing a DB query"}}}

What does it mean ?

Thank you per advance

Maxime

**Comment by thecodester** [comment]
Which tutorial is this for?

**Comment by PROD-BR3-MRI** [comment]
Sorry I forgot the URL :  https://developers.sap.com/tutorials/haas-dm-connect-sdi.html

This is a tutorial to create a remote sources in SAP HANA Database in 2.0 based on Websocket connectivity.

**Comment by PROD-BR3-MRI** [comment]
I'm in HANA 2.0 SP04 in AWS 
I've installed the SDI SP04 patch 10

**Comment by PROD-BR3-MRI** [comment]
Hello, 

Do you find a solution to my issue ? 

Thk's

**Comment by rbrainey** [comment]
Hi, when you say "HANA 2.0 SP04 in AWS", are you saying you are using HANA as a Service in SAP Cloud Platform in an AWS region (e.g., us10 or eu10) or that you are using a HANA installation in an AWS VM? This tutorial is designed for the former use case (SAP Cloud Platform) -- we might still be able to help but it's important to resolving the issue to know.  Thanks.

**Comment by PROD-BR3-MRI** [comment]
Yes I use HANA as a Service in SAP Cloud Platform in an AWS region in EU10

**Comment by rbrainey** [comment]
Hi Maxime,

Would you be able to retry this step and see if you still have the issue? I know it's possible that your SCP Trial has timed out and may need to be restarted -- I hope that's not the case. 

Riley

**Comment by MichaelCzcz** [comment]
@PROD-BR3-MRI Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
