### ISSUE TITLE
Using Autonomous Transactions

### ISSUE THREAD

**Issue by tiagobalmeida** [SAPDocuments/Tutorials#4124]
Tutorial URL: https://developers.sap.com/tutorials/xsa-sqlscript-trans-autonomous.html

Hey, it's not clear if autonomous transactions run synchronously or asyncronously to the code that started them. From my empirical tests they run sequentially but can you provide some clarity please?

Thanks

**Comment by thecodester** [comment]
@Sygyzmundovych Can you help here?

**Comment by rich-heilman** [comment]
Because these blocks are usually used in conjunction with CRUD operations, they  can not be processed in parallel mode, so they would be sequential.
Cheers,
Rich
