### ISSUE TITLE
Add a Database to Your Business Application

### ISSUE THREAD

**Issue by ahusemann** [SAPDocuments/Tutorials#4126]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-03-add-database.html

Please specify the step you are referring to
Step 1: Add a database

The Build that is triggered in step 1 fails, according to the log some connections have been refused.
The .hdiconfig was already adjusted to match the required plugin version: 
 "plugin_version": "2.0.2.0"

Please advise how to proceed.

[Console.log](https://github.com/SAPDocuments/Tutorials/files/3783095/Console.log)

**Comment by renejeglinsky** [comment]
Hi @ahusemann ,

could you try again? Your might have been connected with an infrastructure issue.

Please let me know if the problem persists. Thanks.

René

**Comment by ahusemann** [comment]
The build succeeds now, thanks for the update.
