### ISSUE TITLE
Call IoT Application Enablement service APIs with Postman

### ISSUE THREAD

**Issue by jenska** [SAPDocuments/Tutorials#4129]
Tutorial URL: https://developers.sap.com/tutorials/iotae-api-postman.html

Please describe the parts of tenant-specific application router more briefly or reference to an example app from another tutorial. 
Thx Jens

**Comment by banurekhabalaji** [comment]
Hi Jens,

A table with the description of the different parts is already documented in the same section **Tenant-specific Application Router**. Kindly go through and hope that helps.

Regards,
Banurekha Balaji

**Comment by banurekhabalaji** [comment]
Hi Jens,

Hope the information was useful. Please let us know if you were able to proceed further.

Regards,
Banurekha Balaji

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
