### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by lesbink** [SAPDocuments/Tutorials#4130]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Please specify the step you are referring to:

- Concern:
- In step # 2.4, what is the Application Identifier to use?

**Comment by gauthamkrishna-sap** [comment]
Hello,
Thank you for the feedback. You can use the application identifier with prefix 'it'. We created the tutorial with the assumption that Cloud Integration will be the only active service, but we will add it as a additional note. 
Thanks & Best Regards, Gautham

**Comment by gauthamkrishna-sap** [comment]
Also, enhanced the tutorial with this information about application identifier.

**Comment by lesbink** [comment]
Thanks a lot! That solution worked from my end!
