### ISSUE TITLE
Prepare the Portal Environment for Creating Sites

### ISSUE THREAD

**Issue by Karacraft** [SAPDocuments/Tutorials#4133]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Please specify the step you are referring to

Step 2 : 5
The Add role popup dropdowns are disabled.
![add_role](https://user-images.githubusercontent.com/42495441/67851131-8da3d280-fb2b-11e9-9547-e7328502d17f.jpg)

**Comment by LindsayBert** [comment]
Hi

Can you please open up a BCP ticket for this issue so that the developers can look at the problem.

Thanks
Lindsay Bert
