### ISSUE TITLE
Install an OData V2 Adapter

### ISSUE THREAD

**Issue by pwasem** [SAPDocuments/Tutorials#4136]
Tutorial URL: https://developers.sap.com/tutorials/cap-cloudsdk-2-v2-adapter.html

There is an issue with the provided example code that the database will not be connected.
The solution is to wait for the database to be connected as shown below:

```javascript
const express = require('express');
const cds = require('@sap/cds');
const proxy = require('@sap/cds-odata-v2-adapter-proxy');

// config
const host = '0.0.0.0';
const port = 4004;

(async () => {
  // create new app
  const app = express();

  // serve odata v4
  await cds
    .connect('db') // IMPORTANT!
    .serve('all')
    .in(app);

  // serve odata v2
  app.use(proxy({
    // app
    path: 'v2',
    // target
    port: port
  }));

  // start server
  const server = app.listen(port, host, () => console.info(`app is listing at ${host}:${port}`));
  server.on('error', error => console.error(error.stack));
})();
```

Bests,

Pascal

**Comment by qmacro** [comment]
Hi there @pwasem - thanks so much for getting in touch. I've just tried the code in the tutorial as-is, on a new machine and it all works fine, as expected. In case you want to explore alternative approaches to `server.js` (a perfectly valid thing to do) I'd recommend doing that within the CAP community - find out links to those places, and the SAP Community Q&A, here: bit.ly/cap-com. Cheers! DJ

**Comment by pwasem** [comment]
@qmacro 
At least for local development using **sqlite**  and some csv data being deployed to local db file,`await cds.connect('db')` seems to be mandatory.
Without this call any request e.g. **GET**  http://localhost:4004/service/Entity will not return any results:
```json
{
    "d": {
        "results": []
    }
}
```
But with `await cds.connect('db')` the same request from above will return the csv being deployed to local db file.
So though it looks like your code is working I doubt that you will get any results from your local sqlite db file. Same issue may also apply for running in production with an actual database.

Best regards,

Pascal

**Comment by qmacro** [comment]
I do get results from the DB, no problem. So I'm a bit puzzled, I'm afraid. All the folks who have gone through this tutorial (and the mission) so far have not encountered any issue either. I'm wondering whether it's something specific to your Node.js setup? Perhaps you could share it in Q&A. Cheers!

**Comment by badarinath-katti** [comment]
It would be better if you have a tutorial that converts from odata v4 to v2 in java based CAP project.
Thanks in advance!
Badari

**Comment by badarinath-katti** [comment]
It would be helpful if you have a tutorial that converts from odata v4 to v2 in java based CAP project.
Thanks in advance!
Badari
