### ISSUE TITLE
Set Up the Manage Rules Project Application

### ISSUE THREAD

**Issue by echagas-accenture** [SAPDocuments/Tutorials#4138]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules03-setup-mrp.html

Please specify the step you are referring to

2. After the build completes, navigate to the mta_archives > businessruleseditor_0.0.1.mtar file. Right-click businessruleseditor_0.0.1.mtar and choose Deploy > Deploy to SAP Cloud Platform.

It only works if you have created the service as businessrules instead business-rules

**Comment by VandanaVasudevan** [comment]
Hi,
You need to modify the name of the service instance only if it's different from "businessrules". I'll add the (optional) tag to the step so that it's clear. Thanks for your feedback!

Best Regards,
Vandana

**Comment by MichaelCzcz** [comment]
@echagas-accenture Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
