### ISSUE TITLE
Get Started with SAP Cloud Platform Rapid Application Development by Mendix

### ISSUE THREAD

**Issue by lesbink** [SAPDocuments/Tutorials#4140]
Can you kindly re-visit Step 5 if it is working? Tried many times but it is not working. Tried using hana-schema or postgresql but it did not work. Errors are:
- Service postgresql does not exist
- Service hana does not exist

**Comment by thecodester** [comment]
@IObert I think this involves more the services on the cloud then the Mendix functionality.

@otiliamarinescu Can you help here?

**Comment by otiliamarinescu** [comment]
@thecodester @IObert postgresql and all other backing services have been retired for new SAP CP customers as well as for trial from July 15: 
https://blogs.sap.com/2019/07/15/evolution-of-sap-cloud-platform-retirement-of-sap-managed-backing-services/ 
So this tutorial definitely has to be updated it it requires the use of that.

Hana schema should still be available on trial, not very familiar with the details or what specific service plan is required for the tutorial. It could also be an issue with the lack of entitlements, but these are just guesses, I am not very deep into this topic.

**Comment by MichaelCzcz** [comment]
@Paolaufer @ShiraManas Can you please look into this and provide an update?

**Comment by ShiraManas** [comment]
Hi,
I have updated the tutorial. I added the domain and database that should be used when choosing the Cloud Foundry environment- see Step 4. ([https://developers-qa.sap.com/tutorials/mendix-onboarding.html#642c97ee-3223-4689-9196-df0974c344f1])

Select **hanatrial-schema** for the database.

Can you please run through the steps in the tutorial again. It should work now.

Thanks,
Shira

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by williyamhunter** [comment]
very useful information for,[Rapid Application **Development](https://www.enterprisetouch.com/technology/).Thanks** for Sharing.
