### ISSUE TITLE
Monitor Temperature Data by Calling APIs via Node.js

### ISSUE THREAD

**Issue by NeffetsKasier** [SAPDocuments/Tutorials#4142]
Tutorial URL: https://developers.sap.com/tutorials/iotae-api-nodejs-events.html

Please specify the step you are referring to:
Monitor Temperature Data by Calling APIs via Node.js: Step2

Issue: 

when calling the url:
```
nodeAE.setBaseUrl('analytics-thing-sap');
var url = '/iotae.agilita-aws.greenhouse2:envData/aggregates?' +
    '$select=id,temperature_AVG,time&' +
    '$filter=time ge datetime\'' +
    fourminutesago.slice(0, -1) +
    '\' and time lt datetime\'' +
    twominutesago.slice(0, -1) +
    '\'&' +
    '$format=json';
```

it raises following error: 
`404 - {"error":{"code":"NotFound","message":{"lang":"en","value":"Invalid pstId iotae.agilita-aws.greenhouse2:envData"}}}"`

what are I'm doing wrong? 

Thank you, 
Steffen

**Comment by banurekhabalaji** [comment]
Hi Steffen,

Kindly check your package name - iotae.agilita-aws.greenhouse2. Package name cannot contain special characters. Please find the naming conventions for a package in the following help portal topics: 

- https://help.sap.com/viewer/080fabc6cae6423fb45fca7752adb61e/1910b/en-US/72815137035e48e0ac38e50934e718df.html
- https://help.sap.com/viewer/080fabc6cae6423fb45fca7752adb61e/1910b/en-US/462b49382316427aa59fe671a75fa39e.html 

Hope this helps.

Thanks and regards,
Banurekha Balaji

**Comment by banurekhabalaji** [comment]
Hi Steffen,

Hope you were able to proceed further. Please let us know if you were still facing issues.

Regards,
Banurekha Balaji

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
