### ISSUE TITLE
CP Provisioning reached to 94% and stopped

### ISSUE THREAD

**Issue by takismart** [SAPDocuments/Tutorials#4145]
Tuturial: 
https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Step 4: Provision SAP Cloud Platform Integration tenant

After I chose 'Provision to provision a SAP Cloud Platform Integration tenant', provisioning progress processed to 94% and then stopped there for 2 hours.

Please help.

Thank you very much.

**Comment by gauthamkrishna-sap** [comment]
Hello,
Thank you for your feedback. 
Can you kindly try to provision the tenant again? Sometimes, due to huge load of provisioning requests, this issue might happen. 
Thanks & Best Regards, Gautham

**Comment by takismart** [comment]
Hi Gautham,

Thank you for your quick response. 

I tried again - it works now. 

Best Regards,
Judy
