### ISSUE TITLE
QR Code for SAP Mobile Cards (iOS)

### ISSUE THREAD

**Issue by takismart** [SAPDocuments/Tutorials#4146]
Tutorial: Create SAP SuccessFactors Timesheet and To Dos Card
https://developers.sap.com/tutorials/cp-starter-digitalexp-mobilecards-2-create.html

Step 4: Configure SAP Mobile Cards client

After scan QR code on my iphone, the error message 'Safari cannot open the page because the address is invalid'

QR Code Address:
com.sap.content2go://configure?serverURL=https://pXXXXXXXXXXtrial-dev-com-sap-mobile-platform-cards.cfapps.eu10.hana.ondemand.com&oauthClientId=125a64a9-f5d5-4f2a-a89e-7ef6122583e2&oauthEndpoint=https://pXXXXXXXXXXtrial-dev-com-sap-mobile-platform-cards.cfapps.eu10.hana.ondemand.com

**Comment by jitendrakansal** [comment]
@takismart do you already have "sap mobile cards" app (https://apps.apple.com/us/app/sap-content-to-go/id1168110623) installed on your iphone?

**Comment by takismart** [comment]
Hi @jitendrakansal, thank you for your respose. I installed "sap mobile cards" app to my iPhone and scan the QR code, now I get the error message 'Cannot connect. Please check server URL or email and OAuth client ID. I am pretty sure that my e-mail is correct.

**Comment by jitendrakansal** [comment]
@takismart i tried with my P-user trial account, scanned the QR code and i got the same error. 
And then i noticed that required mobile services instance was in "stopped" mode, when i restarted it, qr scan worked.

Just in case you want to check it once:

1. go to https://cockpit.hanatrial.ondemand.com/cockpit/ > click Enter trial account
2. click subaccount (my case- its "trial")
3. click on "spaces" >> click "dev"
4. check the state for "BindMobileApplicationRoutesToME" application, if it is in "stop" mode, start it. 

and then scan it again. You should see a page where it asks you to enter your SCP account email address and password.
Let me know your findings.

**Comment by takismart** [comment]
Hi @jitendrakansal,
Thank you for your quick response. 
I started "BindMobileApplicationRoutesToME" application
![Image 4](https://user-images.githubusercontent.com/57156004/68253842-de687d80-008d-11ea-8c64-a0df38c6a414.jpg)
However, I still got the same error message. Is there any security configuration I missed?
Please advise.
![Screenshot 2019-11-06 at 12 07 07 PM](https://user-images.githubusercontent.com/57156004/68253928-17085700-008e-11ea-9e5e-8ddb314edd28.png)

**Comment by jitendrakansal** [comment]
@takismart strange, if you are ok, we have a screen sharing session to troubleshoot this issue.
Can you drop me an email (jiendra.kansal@sapdotcom) with possible timeslots as per your availability. 
I am in CET timezone.

**Comment by takismart** [comment]
Hi @jitendrakansal , 
Thank you for your help. After yesterday's sharing session, I tried SAP Mobile Card on my old iPhone, and it works. I can see the timesheet card on my SAP Mobile Cards APP. I tried the same process on other iPhone - the access is failed as well - same issue as my new iPhone. 
I guess the issue might be caused by iOS version:
- The iPhone that can access my Mobile Cards is on iOS version 11.4.1;
- Both iPhones cannot access Mobile Cards is on iOS version 13.1.3.
Anyway, it works for me by now. I will stick with my old phone for my further testing. 
Please drop me a note if you find a way to fix this issue. 
Thanks again.

**Comment by jitendrakansal** [comment]
@takismart i can access mobile cards on my iPhone (iOS 13.2). I will check with development colleagues if there is any issue with iOS version 13.1.3

**Comment by takismart** [comment]
Hi Jitendra,

Thank you for your email.

I upgraded my iOS to 13.2.2 and SAP Mobile Cards worked! I guess there are
some issues with iOS version 13.1.3.

Best regards,
Judy

**Comment by Aemilia-VonWunderland** [comment]
Hi all,
I met the same issue! My iOS version is 13.4.1.
But it worked on it before, and I now use the same device, it is not working...
Can anyone tell me how to fix it?

**Comment by Aemilia-VonWunderland** [comment]
> Hi all,
> I met the same issue! My iOS version is 13.4.1.
> But it worked on it before, and I now use the same device, it is not working...
> Can anyone tell me how to fix it?

I upgraded to 13.5.1, still not working

**Comment by sandeep-tds** [comment]
Hi @Aemilia-VonWunderland,

Thank you so much for raising the issue. Can you please try to uninstall the app, reinstall it and try it again? 

Warm Regards
Sandeep T D S
