### ISSUE TITLE
Invalid JWT token: 'Not allowed JWT header

### ISSUE THREAD

**Issue by adozgec** [SAPDocuments/Tutorials#4147]
Hi,

When I try to cf sapml fs init, I receive the following error. Is there a step I'm missing?

Initialization had issues. (status=ERROR) Unexpected Error: "Invalid JWT token: 'Not allowed JWT header: 'jku'=https://sxxxxxxxxxxtrial.authentication.eu10.hana.ondemand.com/token_keys.'".

Best regards,
Ali Özgeç

**Comment by thecodester** [comment]
WHat tutorial are you referring to?

**Comment by adozgec** [comment]
Hi,

Customize Image Classifier Machine Learning Foundation Services on SAP Cloud Platform Trial

- Prepare your environment for the SAP Leonardo Machine Learning foundation Image Classification Retraining scenario
Step 3: Set the Machine Learning foundation plugin Configuration

https://developers.sap.com/tutorials/cp-mlf-retrain-image-classification-01.html

**Comment by jarjarbentley** [comment]
are you using a production system for the ml_foundation_service like the note refers to:
"When using a productive account the ml_foundation_service_name might be different than the one using in trial. Make sure to adjust the value accordingly."
