### ISSUE TITLE
Connect to SAP S/4HANA Cloud with SAP Cloud Platform ABAP Environment

### ISSUE THREAD

**Issue by valentini50** [SAPDocuments/Tutorials#4149]
Mission URL: https://developers.sap.com/mission.abap-env-connect-s4hana.html

Unable to complete the mission.
Step '3': Create Service Binding for Bonus Plan Scenario with SAP Cloud Platform ABAP environment

Step one does not have the option to mark as done

**Comment by thecodester** [comment]
@mervey45 Can you fix?

**Comment by mervey45** [comment]
@thecodester I fixed it (merge: #4151). 
We can close this issue.
