### ISSUE TITLE
Add a Model and Test the SAPUI5 App

### ISSUE THREAD

**Issue by lesbink** [SAPDocuments/Tutorials#4152]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-webide-setup-datasource.html

Please specify the step you are referring to:

- In Tutorial 5 of 12, Step 4.1, Step 4.2 and Step 4.3, can you kindly replicate from your end if the tutorial still working. 
- From my end, it is always "Uh oh. Something went amiss.". 
![Uhoh](https://user-images.githubusercontent.com/55445200/68174076-bd355d80-ffb7-11e9-9ffc-63eac9ec847d.png)

**Comment by IObert** [comment]
Very strange error, thanks for reporting this one!

It seems that something went wrong with the redirect. Can you please try to click on the "run" icon one more time? Please double-check whether the run configuration is set to "Cloud Foundry". This could be an issue to

**Comment by lesbink** [comment]
So I tried again but no success.

![image](https://user-images.githubusercontent.com/55445200/68269162-ae23dd80-0093-11ea-8553-5e930fdbceb8.png)

![image](https://user-images.githubusercontent.com/55445200/68269189-d57aaa80-0093-11ea-9a67-a75b0e6e9e94.png)

**Comment by IObert** [comment]
It seems that this isn't the correct URL of your application

Can you have a look at all apps in your CF space? Follow steps 6-8 in [this tutorial](https://developers.sap.com/tutorials/hcp-create-trial-account.html) to do so and click on your UI application to see it's URL.

**Comment by IObert** [comment]
I'll close this issue due to inactivity, please reopen if needed.
