### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by tpembe** [SAPDocuments/Tutorials#4168]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-behavior.html

Step 4: Replace your code with following.
I receive a compile error when using the line of code "etag master last_changed_at"

If instead I use "etag last_changed_at" compile error appears no longer. 

Thanks

**Comment by mervey45** [comment]
@tpembe It will be updated, thank you. @thecodester I created a pull request: #4175. We can close this issue.
