### ISSUE TITLE
Marking Tutorial Steps as "Done" or submitting a response is not working

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#4171]
Tutorial URL: https://developers.sap.com/tutorials/odata-05-data-model-service.html

Please specify the step you are referring to
Step 11 (but others as well)
Clicking on the blue "Done" bar to tick off the step, doesn't turn it green right away. It sometimes takes several tries (to mark step as "done"), sometimes I see "technical error" (where a selection needs to be made). It's been happening with other tutorials and steps as well today.
Link shown: https://developers.sap.com/tutorials/odata-05-data-model-service.html#
Browser: Firefox

Update: It's also happenening in the next tutorial - https://developers.sap.com/tutorials/odata-06-add-data-odata-service.html

Another Update: It's working fine for tutorial #7 - https://developers.sap.com/tutorials/odata-07-explore-generated-odata-service.html

**Comment by BaerbelW** [comment]
This is really weird - after yet again refreshing the still open browser windows for tutorials 05 and 06 (which I had already done multiple times), all the steps showed up as green.

**Comment by thecodester** [comment]
I am going to close this issue, but report the general issue to IT. We hope to considerably update the usability of the completion buttons.
