### ISSUE TITLE
See What Cloud Platform Tools Can Do with OData

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#4174]
Group URL: https://developers.sap.com/group.scp-7-odata-tools.html

Hi Folks!

As a complete newbie to anything SCP-related, this OData Mission on beginner-level turned out to be quite a challenge. Not only but especially as most of the terminology was new to me. I had for example never heard about "Cloud Foundry" and couldn't really relate it to anything. Not sure if I'm the exception to the rule for those who take on this mission and the tutorials it contains, but for me it would have been helpful to first get some background and basic information about the cloud environment in general and Cloud Foundry in particular. So, I poked around a bit more after completing the mission and found "[View the SAP Cloud Platform from 10,000 Meters](https://developers.sap.com/tutorials/cp-explore-cloud-platform.html)" and "[Fundamentals of the Cloud Foundry Environment](https://developers.sap.com/tutorials/cp-cf-fundamentals.html)". They helped me to better grasp what it is and would have been helpful to work through before tackling the mission, basically to first get the "big picture" before starting in on the details. Could this - and perhaps some related tutorials - either be added at the beginning of the mission or be shown as a prerequisite?

Thanks much and Cheers
Bärbel

**Comment by qmacro** [comment]
Nice comments and very useful, thanks Baerbel! Passing over to @thecodester who may have an option to organise these missions differently in the future.

**Comment by thecodester** [comment]
I have added a prerequisite in the description of the mission: https://developers.sap.com/mission.scp-3-odata.html
