### ISSUE TITLE
Use JPA in Custom Logic

### ISSUE THREAD

**Issue by MichaelWegelin** [SAPDocuments/Tutorials#4176]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-05-using-jpa.html

Step 1:

The pom.xml file after finisching tutorial 4 does not even look remotely like the one shown in the tutorial and is much simpler. So it is extremely hard to find the places where to put the code in.

**Comment by renejeglinsky** [comment]
Hi @MichaelWegelin ,

sorry for getting back to you that late. 
Have you opened the pom.xml in your `srv` folder or in the root of your project? Please use the one in your `srv` folder and then you should be ready to go.

**Comment by MichaelCzcz** [comment]
@MichaelWegelin Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
