### ISSUE TITLE
SAP HANA, express edition, install dependencies for openSUSE

### ISSUE THREAD

**Issue by sieburga** [SAPDocuments/Tutorials#4181]
Tutorial URL: https://developers.sap.com/tutorials/hxe-azure-opensuse-dependencies.html

I tried HANA Express 2.0 SP4 with openSUSE Leap 15.1 :
- Step 2: **libtool** is already installed, no action necessary 
- Add Step 3: Install **insserv-compat** and **libatomic1** with YaST, otherwise the installation fails to ceate the database instance.
- Add Step 4: Check the linux firewalld and add the necessary ports for SAP HANA
1129 for hdblcm web UI
3xx13, 3xx15 for SQL connections (xx=instance ID)
43xx for XS classic
all required ports for XS advanced

**Comment by jung-thomas** [comment]
Yes this tutorial is out of date and we have scheduled it for removal. Instead we would recommend installing HANA Express on Azure via the Marketplace: https://developers.sap.com/tutorials/hxe-ms-azure-marketplace-xsa.html
