### ISSUE TITLE
Take a Tour of the SAP Cloud Platform Cockpit

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#4186]
Tutorial URL: https://developers.sap.com/tutorials/cp-tour-cockpit.html

Please specify the step you are referring to
Step 8 - Storing your code

The entries in the left-hand menu I see in my SCP cockpit after working through the mission "[Take a deep dive into OData](https://developers.sap.com/mission.scp-3-odata.html)" look considerably different than what is shown in the tutorial. For example, I don't see an entry for "Repositories":

![grafik](https://user-images.githubusercontent.com/18588108/68577470-755b7e00-0470-11ea-9ded-aab0b435f14b.png)

Is this to be expected and/or can it be somehow added/made visible? 

It's also possible that I'm looking for it from the wrong context which is in my "dev space".
![grafik](https://user-images.githubusercontent.com/18588108/68577772-0599c300-0471-11ea-8605-bcbb1a6e6b74.png)

Thanks and Cheers
Bärbel

**Comment by thecodester** [comment]
@rbrainey Meredith wrote this -- and Josh reviewed -- this tutorial as part of SCP refresh before the 2018 TechEd season.

**Comment by IObert** [comment]
Hi @BaerbelW,

your assumption is correct. The view that is visible in your screenshot shows a different. Here you are in the "Space" in the Cloud Foundry environment.

The tutorial explains how to use the Neo environment. I'll update the tutorial shortly to make this more explicit.
