### ISSUE TITLE
Install the Cloud Foundry Command Line Interface (CLI)

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#4189]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-download-cli.html

Please specify the step you are referring to
Step 1 - Download the Command Line interface

When I try to run the exe after unpacking the zip-file I get an error message which I think is due to lacking admin-rights on the company laptop. Is there a way around this and/or can the rest of the tutorial group/mission be done without having CLI installed locally?

Thanks and Cheers
Bärbel

**Comment by IObert** [comment]
Hi @BaerbelW,

you should also be able to download the binary for windows and add it manually to the path in your env variables.

Good luck,
Marius

**Comment by BaerbelW** [comment]
Thanks Marius! Turned out that I only had to extract the content from the zip-file into another and new directory on my C-drive than the one it defaultet to. I could then run the exe from there.

Cheers
Bärbel

**Comment by IObert** [comment]
Great! I hope you enjoyed the tutorial
