### ISSUE TITLE
Create a food database in SAP HANA Express Edition

### ISSUE THREAD

**Issue by wertygol** [SAPDocuments/Tutorials#4191]
Tutorial URL: https://developers.sap.com/tutorials/hxe-docstore-01-create-database.html

Step 3: Create a Document Store Collection

What is the correct answer? the command execution returns :
0 rowns affected (overall time xxxxx msec; server time xxxx msec) 

but in the tutorial expects another answer.
![image](https://user-images.githubusercontent.com/5190729/68625012-e887e300-04b6-11ea-9901-213130b1dd53.png)

**Comment by thecodester** [comment]
If I put it EXACTLY what is returned in your screenshot it works for me. Can you explain exactly what you put in, exactly what you did?

**Comment by wertygol** [comment]
I put exactly thats appears in my screen, I try different combinations, nothing work, today I will try again.

**Comment by wertygol** [comment]
Well, today works...
