### ISSUE TITLE
Create Your First ABAP Console Application

### ISSUE THREAD

**Issue by kgorin8** [SAPDocuments/Tutorials#4193]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-console-application.html

Hello. Trying to connect to abap instance via ADT and getting no errors but can't complete login either. I was able to login to abap instance via cloud dashboard just fine.

screenshots https://imgur.com/a/NhAlszw

**Comment by kgorin8** [comment]
Seems like eclipse auth is not working...

http://localhost:60342/oauth/client/redirect/external_browser?code=<somecode>

HTTP ERROR 500

**Comment by mervey45** [comment]
@kgorin8 Did you already finish following tutorial: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html. If not please do so and try it out again.

**Comment by mervey45** [comment]
Hi @kgorin8, 

do you need further help? Or can we close this issue?

Best regards, 
Merve
