### ISSUE TITLE
Deploy a TensorFlow Iris Classifier in SAP HANA, express edition

### ISSUE THREAD

**Issue by mbenetti** [SAPDocuments/Tutorials#4198]
Tutorial URL: https://developers.sap.com/tutorials/mlb-hxe-tensorflow-iris.html

Please specify the step you are referring to

Hello, I am having problems with the scrip  ~/export/iris_test_client.py

the error I get is:

(tms) tmsadm@hxehost:~> sudo python ~/export/iris_export_savedmodel.py
  File "/home/tmsadm/export/iris_export_savedmodel.py", line 48
    query_iris  = 'SELECT ID, SEPALLENGTH, SEPALWIDTH, PETALLENGTH, PETALWIDTH, SPECIES FROM
                                                                                            ^
SyntaxError: EOL while scanning string literal

I would appreciate if someone can help me. I tried also the other script: 
https://raw.githubusercontent.com/SAPDocuments/Tutorials/master/tutorials/mlb-hxe-tensorflow-iris/source/iris_test_client.py

**Comment by adadouche** [comment]
HI @mbenetti, @MichaelCzcz, @rbrainey  & @jarjarbentley ,

I no longer work for SAP so I won't be able to fix the content if needs be.

My guess is that you saved the wrong content in the iris_export_savedmodel.py.

There is no SQL in that python script.

You are probably referring to iris_import_data.

BTW, I discourage the use of root/sudo to run such script that would mean something is wrong in your env if you need to sudo your python command.

**Comment by MichaelCzcz** [comment]
@jarjarbentley Can you please look into this issue?

**Comment by jarjarbentley** [comment]
@mbenetti  did the note from Abdel help, if not, please re-open issue:
"My guess is that you saved the wrong content in the iris_export_savedmodel.py.
There is no SQL in that python script.
You are probably referring to iris_import_data."

**Comment by mbenetti** [comment]
Thank you jarjarbentley, I was on holidays but I will try the solution proposed soon. Thank you!
