### ISSUE TITLE
Define a Simple Data Model and OData Service with CDS

### ISSUE THREAD

**Issue by tpembe** [SAPDocuments/Tutorials#4200]
Tutorial URL: https://developers.sap.com/tutorials/odata-05-data-model-service.html

Please specify the step you are referring to: Step 9 

"my-service.cd" should be "cat-service.cds"

**Comment by qmacro** [comment]
Thanks for the heads-up, @tpembe  - it looks like the wizard generator changed as it did use to be `my-service.cds` (as shown in some of the screenshots). I'll endeavour to update this in the next few days. Appreciated!

**Comment by qmacro** [comment]
Thanks again @tpembe the tutorial has been updated (see https://github.com/SAPDocuments/Tutorials/commit/753c5cb9ccdbd1876435e67b689dbdc4678c3904)
