### ISSUE TITLE
Add Data to Your OData Service

### ISSUE THREAD

**Issue by tpembe** [SAPDocuments/Tutorials#4201]
Tutorial URL: https://developers.sap.com/tutorials/odata-06-add-data-odata-service.html

Please specify the step you are referring to: Step 5

After populating MY_APP_PRODUCTS table and rebuilding I receive the following error in the console log.  Application is started in cloud foundry. When clicking the app hyperlink in the console no database data is displayed for the products service.

Console Error log:

{ "written_at":"2019-11-12T17:41:50.624Z","written_ts":324472033403521,"component_type":"application","component_id":"7002c721-f007-4da3-bd47-b37340b4c506","space_name":"dev","component_name":"5yHsnK2OK0JmG5er-Products-srv","component_instance":"0","organization_id":"-","correlation_id":"-","organization_name":"-","space_id":"6be813da-716e-40e3-acb8-2afdc4e67009","container_id":"10.32.1.10","type":"log","logger":"org.apache.catalina.startup.Catalina","thread":"main","level":"INFO","categories":[],"msg":"Initialization processed in 1586 ms" } { "written_at":"2019-11-12T17:41:50.764Z","written_ts":324472171639298,"component_type":"application","component_id":"7002c721-f007-4da3-bd47-b37340b4c506","space_name":"dev","component_name":"5yHsnK2OK0JmG5er-Products-srv","component_instance":"0","organization_id":"-","correlation_id":"-","organization_name":"-","space_id":"6be813da-716e-40e3-acb8-2afdc4e67009","container_id":"10.32.1.10","type":"log","logger":"org.apache.catalina.core.StandardService","thread":"main","level":"INFO","categories":[],"msg":"Starting service [Catalina]" } { "written_at":"2019-11-12T17:41:50.793Z","written_ts":324472200310659,"component_type":"application","component_id":"7002c721-f007-4da3-bd47-b37340b4c506","space_name":"dev","component_name":"5yHsnK2OK0JmG5er-Products-srv","component_instance":"0","organization_id":"-","correlation_id":"-","organization_name":"-","space_id":"6be813da-716e-40e3-acb8-2afdc4e67009","container_id":"10.32.1.10","type":"log","logger":"org.apache.catalina.core.StandardEngine","thread":"main","level":"INFO","categories":[],"msg":"Starting Servlet Engine: Apache Tomcat/8.5.32" }
{ "written_at":"2019-11-12T17:42:05.493Z","written_ts":324486901189815,"component_type":"application","component_id":"7002c721-f007-4da3-bd47-b37340b4c506","space_name":"dev","component_name":"5yHsnK2OK0JmG5er-Products-srv","component_instance":"0","organization_id":"-","correlation_id":"-","organization_name":"-","space_id":"6be813da-716e-40e3-acb8-2afdc4e67009","container_id":"10.32.1.10","type":"log","logger":"org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/]","thread":"localhost-startStop-1","level":"ERROR","categories":[],"msg":"For security constraints with URL pattern [/*] only the HTTP methods [HEAD OPTIONS] are covered. All other methods are uncovered." }
{ "written_at":"2019-11-12T17:42:05.494Z","written_ts":324486902009433,"component_type":"application","component_id":"7002c721-f007-4da3-bd47-b37340b4c506","space_name":"dev","component_name":"5yHsnK2OK0JmG5er-Products-srv","component_instance":"0","organization_id":"-","correlation_id":"-","organization_name":"-","space_id":"6be813da-716e-40e3-acb8-2afdc4e67009","container_id":"10.32.1.10","type":"log","logger":"org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/]","thread":"localhost-startStop-1","level":"ERROR","categories":[],"msg":"For security constraints with URL pattern [/odata/v2/*] the HTTP methods [HEAD DELETE POST GET PUT PATCH] are uncovered." }
{ "written_at":"2019-11-12T17:42:05.912Z","written_ts":324487319245256,"component_type":"application","component_id":"7002c721-f007-4da3-bd47-b37340b4c506","space_name":"dev","component_name":"5yHsnK2OK0JmG5er-Products-srv","component_instance":"0","organization_id":"-","correlation_id":"-","organization_name":"-","space_id":"6be813da-716e-40e3-acb8-2afdc4e67009","container_id":"10.32.1.10","type":"log","logger":"org.apache.catalina.startup.Catalina","thread":"main","level":"INFO","categories":[],"msg":"Server startup in 15177 ms" }

**Comment by qmacro** [comment]
Hello there, sorry for the delay @tpembe  . I will assume for now that this was a temporary issue and you are OK now. If not, may we please suggest you turn to the [Community Q&A](https://answers.sap.com) for help with this, as it's not specifically related to the mechanics of the tutorial content or format (which is what these issues are for). Thank you and good luck!
