### ISSUE TITLE
Take a Tour of the SAP Cloud Platform Cockpit

### ISSUE THREAD

**Issue by I053029** [SAPDocuments/Tutorials#4202]
Tutorial URL: https://developers.sap.com/tutorials/cp-tour-cockpit.html

Please specify the step you are referring to

![image](https://user-images.githubusercontent.com/57703040/68743849-52200280-0619-11ea-9073-17a2e309befd.png)

I do not see tabs in left navigation pane as given in screenshot. Till last tutorial everything was as per screenshot

**Comment by IObert** [comment]
Thanks for opening this issue. You are right, there was a navigation step missing in the beginning. I added it with the linked PR
