### ISSUE TITLE
Try Out SAP Cloud Platform SDK for Android Wizard

### ISSUE THREAD

**Issue by tpembe** [SAPDocuments/Tutorials#4210]
Tutorial URL: https://developers.sap.com/tutorials/cp-sdk-android-wizard-app.html

Please specify the step you are referring to: Step 1:

When asked to add and existing destination in the android wizard the UI has different parameters to that provided in the tutorial.
![ad new destination](https://user-images.githubusercontent.com/17800562/68854614-50674500-06d4-11ea-9b9f-a1fec8bdb05b.PNG)

**Comment by flyingfish162** [comment]
The tutorial is for mobile server NEO landscape, but unfortunately you are using Cloud Foundry landscape. Please see the screenshot on how to set destination for Cloud Foundry landscape. And BTW, we are working on new tutorials for Cloud Foundry.
<img width="994" alt="Screen Shot 2019-11-22 at 17 49 15" src="https://user-images.githubusercontent.com/56924323/69416648-09bbbf80-0d52-11ea-8a49-f80880a12123.png">
