### ISSUE TITLE
Enable the SAP Cloud Platform, API Management Service

### ISSUE THREAD

**Issue by Tiberriver256** [SAPDocuments/Tutorials#4212]
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-enable-service.html

Please specify the step you are referring to

This entire tutorial seems to be out of date. The images don't match what I'm seeing in the Cockpit any more.

**Comment by thecodester** [comment]
@shilpavij Can you look at this issue and see if this series is still relevant and is covered by things you've written?

@rbrainey FYI - Since this was written by your group

**Comment by shilpavij** [comment]
Hello Daniel,

i know the tutorial is outdated but since we are moving to CF in a month , I would say lets wait for couple of more days and then have a look at this else again it will be a rework. Only few images are changed which people can follow easily. Let me know your thoughts?

Regards
Shilpa

**Comment by thecodester** [comment]
If it is only outdated by screenshots and people can follow anyone, then that is fine. If people cannot do the tutorial, we should take it down. And if we want to steer people to CF, even if the tutorial is OK we should also take it down. If we truly have an updated tutorial coming in a mattter of weeks, then we can probably wait.

**Comment by shilpavij** [comment]
Hello Daniel,

I have corrected it.

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
@Tiberriver256 Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
