### ISSUE TITLE
Create Instance of SAP Cloud Platform Enterprise Messaging Service

### ISSUE THREAD

**Issue by dassoumya87** [SAPDocuments/Tutorials#4213]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html

Please specify the step you are referring to

Step 1 Create an Instance fails with the below error:

Service broker error: Service broker enterprise-messaging-service-broker failed with: Service broker parameters are invalid: [\{"message":"Unrecognized field","propertyPath":"namespace"}]

**Comment by pradeeppanda-sap** [comment]
Hi,
  Can you please share the json file which you are using?
regards
Pradeep

**Comment by dassoumya87** [comment]
Hi Pradeep,

I am using the below JSON:

{
	"emname": "em-trial",
	"namespace": "sap/trial/1",
	"options": {
		"management": true,
		"messagingrest": true,
		"messaging": true
	},
	"rules": {
		"queueRules": {
			"inboundFilter": [
				"${namespace}/#"
			],
			"outboundFilter": [
				"${namespace}/#"
			]
		},
		"topicRules": {
			"inboundFilter": [
				"${namespace}/#"
			],
			"outboundFilter": [
				"${namespace}/#"
			]
		}
	}
}

Thanks & Regards,
Soumya Ranjan

**Comment by pradeeppanda-sap** [comment]
Hi Soumya,
  Please try it in Factory landscape. For some reason it is not available in TRIAL and hence I have updated the documents accordingly. Sorry for the inconvenience caused.
Should you face any issue even in Factory environment, please let me know.
regards
Pradeep

**Comment by MohanRamu** [comment]
I got  the same error as above in factory landscape, when i hard code the name space i get below error. 
Service broker parameters are invalid: [{"message":"Invalid namespace","propertyPath":"rules.topicRules.namespace"}]

**Comment by pradeeppanda-sap** [comment]
Hi MohanRamu,
  Can you please share the descriptor file (JSON) which you have used ?

regards
Pradeep

**Comment by sivaram498** [comment]
Hi Pradeep,

Even I am getting the same berror and couldn't create an instance .can you please help. I am using the JSON.

Error details 
Service broker error: Service broker enterprise-messaging-service-broker failed with: Service broker parameters are invalid: [\{"message":"Unrecognized field","propertyPath":"namespace"}]

JSON file used.
{
	"emname": "messaging",
	"namespace": "SAP/BO/SalesOrder",
	"options": {
		"management": true,
		"messagingrest": true,
		"messaging": true
	},
	"rules": {
		"queueRules": {
			"outboundFilter": [
				"SAP/BO/SalesOrder/#"
			]
		},
		"topicRules": {
			"outboundFilter": [
				"SAP/BO/SalesOrder/#",
				"SAP/BO/SalesOrder/#"
			]
		}
	}
}

**Comment by manjunathgudisi** [comment]
Hi @pradeeppanda-sap @sivaram498 @dassoumya87 

I'm having the same issue with the factory account.

<img width="821" alt="Screen Shot 2020-03-06 at 7 35 29 PM" src="https://user-images.githubusercontent.com/6059076/76099855-c4b25500-5ff1-11ea-9cc9-dabcde53fa1d.png">

Did you find any solution to this?

Thanks, Manju

**Comment by sivaram498** [comment]
Did not find any till now..

**Comment by MohanRamu** [comment]
> Hi MohanRamu,
> Can you please share the descriptor file (JSON) which you have used ?
> 
> regards
> Pradeep

HI Pradeep

My all issues are resolved and I am able to create messages as well as i am to post message and access those also.

{
	"emname": "sky-messaging",
	"namespace": "home/vcap/skymessage",
	"version": "1.1.0",
	"options": {
		"management": true,
		"messagingrest": true,
		"messaging": true
	},
	"rules": {
		"queueRules": {
			"publishFilter": [
				"${namespace}/*"
			],
			"subscribeFilter": [
				"${namespace}/*"
			]
		},
		"topicRules": {
			"publishFilter": [
				"${namespace}/*"
			],
			"subscribeFilter": [
				"${namespace}/*"
			]
		}
	}
}


Thanks & Regards,
Mohan Ramu

**Comment by MohanRamu** [comment]
Hi All,

I have solution for this. This is not a problem with your json files.

You can not create EM (Enterprise Messaging) using this json in Dev Plan. It can be done in Default plan.

**Comment by pradeeppanda-sap** [comment]
yes.....nice to know that you could do it successfully.

**Comment by manjunathgudisi** [comment]
Hi,
Sorry for late, I figured it out on the same day. 

@MohanRamu As you said, we need to use `'default'` plan to create an instance of Enterprise Messaging.

And one more prerequisite is, `the length of 'namespace' in JSON should be 24 characters`. For ex, the value of 'namespace' above is 'home/vcap/skymessage' and it is 20 characters in length.

Thanks, Manju

**Comment by pradeeppanda-sap** [comment]
And from my side, I was on leave ...hence could not reply ...

**Comment by jvasquezm79** [comment]
Hi.

I created on DEV space only with json property:

{
"emname": "emname",
"options": {
    "management": true,
    "messagingrest": true,
    "messaging": true
}

And did work fine.

Delete namespace, version and rules from json.

**Comment by edwinballesteros** [comment]
this solution work fine for me
Thks

**Comment by pradeeppanda-sap** [comment]
nice to know that things are working fine.

**Comment by Alexd-sap** [comment]
Apologies for reviving this old thread, but i wanted to bring to your attention, that in SCP Trial, while creating an EM service, you dont get the option to select Default Service Plan (only *dev* option is available. Aka. the tutorials available like this https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html are out of date.

**Comment by JoaoGuedes01** [comment]
po crlh gajo do sap

**Comment by JoaoGuedes01** [comment]
fdp

**Comment by pradeeppanda-sap** [comment]
not able to understand what is the issue.

**Comment by JoaoGuedes01** [comment]
i issue é que ainda nao foste po crlh

**Comment by rmaripeddi** [comment]
When I am trying this JSON for dev plan,

{
"emname": "emdev",
"options": {
"management": true,
"messagingrest": true,
"messaging": true
}

I am getting error as "Service broker error: Service broker enterprise-messaging-service-broker failed with: Pool for plan dev is exhausted.". 

Please help

**Comment by pradeeppanda-sap** [comment]
can you try now and let me know please ?

**Comment by rmaripeddi** [comment]
> can you try now and let me know please ?

Thanks Pradeep, Now I am able to create instance using the above code.

But I am getting below error if I use the below code which you have mentioned in the SAP developer site.

**Service broker error: Service broker enterprise-messaging-service-broker failed with: Service broker parameters are invalid: [{"message":"Unrecognized field","propertyPath":"namespace"}]**

I am using this JSON code

{
"emname": "emd",
"namespace": "759b6e5atrial/emd/1",
"version": "1.1.0",
"options": {
    "management": true,
    "messagingrest": true,
    "messaging": true
},
"rules": {
    "queueRules": {
        "publishFilter": [
            "${namespace}/*"
        ],
        "subscribeFilter": [
            "${namespace}/*"
        ]
    },
    "topicRules": {
        "publishFilter": [
            "${namespace}/*"
        ],
        "subscribeFilter": [
            "${namespace}/*"
        ]
    }
}
}

**Comment by JoaoGuedes01** [comment]
mas vais ou precisas de ajuda?

**Comment by rmaripeddi** [comment]
> mas vais ou precisas de ajuda?

I moved ahead but not facing authorization issue while opening application from Subscription.

Created now issue " Create Queues and Queue Subscriptions for SAP Event Mesh #382" .

Could you please assist me on that.

**Comment by wivwiv** [comment]
When I am trying this JSON for dev plan:

### JSON

```
{
    "emname": "emqx",
    "namespace": "emqx/emqx/mqtt-in",
    "version": "1.1.0",
    "options": {
        "management": true,
        "messagingrest": true,
        "messaging": true
    },
	"rules": {
        "queueRules": {
            "publishFilter": [
                "${namespace}/*"
            ],
            "subscribeFilter": [
                "${namespace}/*"
            ]
        },
        "topicRules": {
            "publishFilter": [
                "${namespace}/*"
            ],
            "subscribeFilter": [
                "${namespace}/*"
            ]
        }
    },
    "resources" : {
    "units" : "10"
  }
}
```

### Errors
```
Service broker error: Service broker enterprise-messaging-service-broker failed with: Service broker parameters are invalid: [{"message":"Unrecognized field","propertyPath":"namespace"}]
```

### Which JSON can created?

**Comment by pradeeppanda-sap** [comment]
this descriptor file is for a default plan type.
Should you have default plan (possible, only if you are working on production version of BTP).
Should you intend to try this in trial version, you need to work with dev plan.
The descriptor definition for dev plan goes as below

{
	"emname": "<your-emname>",
	"options": {
		"management": true,
		"messagingrest": true
	}
}

**Comment by jmalla** [comment]
> Hi All,
> 
> I have solution for this. This is not a problem with your json files.
> 
> You can not create EM (Enterprise Messaging) using this json in Dev Plan. It can be done in Default plan.

In the trial account, there is no Default plan.

**Comment by jmalla** [comment]
@pradeeppanda-sap 

It does

**Comment by jmalla** [comment]
It works with this in the trial account.  The documentation really needs to be updated.  A lot of of users are using the trial account.

{
"emname": "emname",
"options": {
"management": true,
"messagingrest": true,
"messaging": true
}
}

**Comment by pradeeppanda-sap** [comment]
Hi @jmalla 
  What you have done is for dev plan and dev plan will work in the trial environment. And as i have mentioned, trial environment does not have default plan, and hence if you are trying to create an instance with default plan in trial environment, it will not work. You need to be working in productive environment, to be able to work with the default plan. And hence, if you notice, this tutorial has that information .  


![image](https://user-images.githubusercontent.com/51952722/121133146-9e601280-c84f-11eb-960e-82347f939aba.png)

Hope it is clear.
thanks Pradeep

**Comment by JoaoGuedes01** [comment]
é isso mm filho, no teu lugar é que estas bem

**Comment by JoaoGuedes01** [comment]
fdp

**Comment by saumya96das** [comment]
Hi Pradeep,

Facing below error while creating instance of Event Mesh in Trial Account (US Region) for dev space.

Service broker error: Service broker enterprise-messaging-service-broker failed with: Pool for plan dev is exhausted.
<img width="443" alt="Error_EventMesh" src="https://user-images.githubusercontent.com/67323200/153189396-3aaf3ba5-26b1-4b2b-84ac-7b9c5d6cb017.png">

**Comment by harshagarwal1** [comment]
Hi Praddep

facing pool for dev is exhausted error

**Comment by pradeeppanda-sap** [comment]
Hi,
 As it is a trial landscape at times you might get an exhausted error. Please try after sometime. You might not get the error.

**Comment by JoaoGuedes01** [comment]
fdp

**Comment by pradeeppanda-sap** [comment]
can you elaborate what do you want to convey ?

**Comment by DD877** [comment]
event mesh with trail account US EAST(VA) not working .could you please help to fixed this .
Cannot create the instance for Event Mesh
