### ISSUE TITLE
Set Up a Workflow With Extended Employee Onboarding

### ISSUE THREAD

**Issue by bcschaich** [SAPDocuments/Tutorials#4215]
When deploying for the first time there is an error resulting from changes made during the tutorial:
In step 2.1 you are asked to:
"In the Resources tab, delete the existing workflow_sample_onboarding."

Unfortunately this is declared as required in the yaml file and will result in error during deployment.
The generator seems not to check this change. So it needs a manual step in the file.

**Comment by ArchanaShukla** [comment]
This is because the changes you did to in Step 2.1 is not saved and MTA.yaml file still refers to the old sample onboarding resource. Please ensure that you have saved the changes, if not then you can close the mta editor and try again.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
