### ISSUE TITLE
Add Managed Associations with Core Data Services

### ISSUE THREAD

**Issue by janhuachu** [SAPDocuments/Tutorials#4216]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-foundation-01.html

Please specify the step you are referring to
Step 7: Build your db module and explore build
With the current downloaded tutorial-enhance-the-product-catalog.zip, got the following error:
    Build command failed : hdi-build operation failed: No suitable major-minor version found for requested version \\'3.3.0\\'. Latest available version: 3.11.0

After I updated "@sap/hdi-deploy" to "3.11.0" in /tutorial-enhance-the-product-catalog/db/package.json, the Build failed with the following warnings and errors:

(Same warning repeated several times)
Warning: com.sap.hana.di.tabledata: No "include_filter" is specified; it's strongly recommended to define an "include_filter" to also allow other table imports into the table; if no other table imports are intended, please specify at least an empty "include_filter":[] in the  "import_settings" section [8251576]
        at "src/gen/cloud-samples-foundation/_csv/Data.hdbtabledata" (3:196) 

———
9:51:55 AM (HDB)      Precompiling "$cds.merge/CLOUDS_PRODUCTS_PRODUCTS" (merged)... ok  (0s 26ms)
     Precompiling "$cds.merge/CLOUDS_PRODUCTS_STOCKAVAILABILITIES" (merged)... ok  (0s 25ms)
    Merging... ok  (0s 207ms)
    Error: "tabledata.source://AreaUnits.csv": the object cannot be provided more than once [8212002]
     "src/_csv/AreaUnits.csv": the file would provide it 
     "src/gen/cloud-samples-foundation/_csv/AreaUnits.csv": the file would provide it 
    Error: "tabledata.source://BaseUnits.csv": the object cannot be provided more than once [8212002]
     "src/_csv/BaseUnits.csv": the file would provide it 
     "src/gen/cloud-samples-foundation/_csv/BaseUnits.csv": the file would provide it 
———
9:51:55 AM (HDB)     Error: "tabledata.source://Countries.csv": the object cannot be provided more than once [8212002]
     "src/_csv/Countries.csv": the file would provide it 
     "src/gen/cloud-samples-foundation/_csv/Countries.csv": the file would provide it 
    Error: "tabledata.source://Currencies.csv": the object cannot be provided more than once [8212002]
     "src/_csv/Currencies.csv": the file would provide it 
     "src/gen/cloud-samples-foundation/_csv/Currencies.csv": the file would provide it 
    Error: "tabledata.source://Languages.csv": the object cannot be provided more than once [8212002]
     "src/_csv/Languages.csv": the file would provide it 
     "src/gen/cloud-samples-foundation/_csv/Languages.csv": the file would provide it 
    Error: "tabledata.source://LengthUnits.csv": the object cannot be provided more than once [8212002]
     "src/_csv/LengthUnits.csv": the file would provide it 

———
9:51:55 AM (HDB)      "src/gen/cloud-samples-foundation/_csv/LengthUnits.csv": the file would provide it 
    Error: "tabledata.source://VolumeUnits.csv": the object cannot be provided more than once [8212002]
     "src/_csv/VolumeUnits.csv": the file would provide it 
     "src/gen/cloud-samples-foundation/_csv/VolumeUnits.csv": the file would provide it 
    Error: "tabledata.source://WeightUnits.csv": the object cannot be provided more than once [8212002]
     "src/_csv/WeightUnits.csv": the file would provide it 
     "src/gen/cloud-samples-foundation/_csv/WeightUnits.csv": the file would provide it 
    Error: Could not compose a consistent make graph [8212012]
   Error: Calculating dependencies... failed [8212108]
   Make failed (11 errors, 22 warnings): tried to deploy 51 files, undeploy 0 files, redeploy 0 dependent files

**Comment by renejeglinsky** [comment]
Hi @janhuachu ,

please perform a cds build before the db build.

1. Open the context menu on the model.cds file and select "Build > Build CDS"
2. After the build has been successfull, please do the build on the db module as described in the tutorial.

Hint: You might want to enable build upon save, as described in Step 4.

Regards,
René

**Comment by janhuachu** [comment]
Thanks for your info.
I did have the build upon save preference set.
After I did the "Build > Build CDS" on model.cds succeeded, I tried to do the step 7 again.
This time, I got the following error message:

4:32:39 PM (Executor) The "task for hdb build" process started.
4:32:39 PM (Executor) Started the "task for hdb build" provision.
4:32:49 PM (Provision) Service provisioning for module: "/db"
4:32:49 PM (Provision) Service instance 'tutorial-enhance-the-product-catalaRnrQGQJLOx7mpX/' for resource 'tutorial-enhance-the-product-catalaRnrQGQJLOx7mpX/' already exists, no operation will be performed.
4:32:49 PM (Provision) Service instance 'tutorial-enhance-the-product-catalGT1wBpH99g6hrTpj' for resource 'tutorial-enhance-the-product-catalGT1wBpH99g6hrTpj' already exists, no operation will be performed.
4:32:51 PM (Executor) Starting process: "cd /projects/tutorial-enhance-the-product-catalog/db; export DEVX_MTA_RESOLVED_PLACEHOLDERS="{\"services\":[{\"platformName\":\"tutorial-enhance-the-product-catalaRnrQGQJLOx7mpX/\",\"resourceName\":\"product-catalog-logging\",\"resourceProperties\":{},\"resourceType\":\"org.cloudfoundry.managed-service\",\"serviceKeyName\":\"SharedDevKey\",\"serviceTarget\":{\"endpoint\":\"https://api.cf.us10.hana.ondemand.com\",\"org\":\"I825141trial_trial\",\"space\":\"dev\"}},{\"platformName\":\"tutorial-enhance-the-product-catalGT1wBpH99g6hrTpj\",\"resourceName\":\"product-catalog-hdi-container\",\"resourceProperties\":{},\"resourceType\":\"com.sap.xs.hdi-container\",\"serviceKeyName\":\"SharedDevKey\",\"serviceTarget\":{\"endpoint\":\"https://api.cf.us10.hana.ondemand.com\",\"org\":\"I825141trial_trial\",\"space\":\"dev\"}}]}"; export CF_HOME=/projects/.webide/cf/2743ff1a6cd6bcc8310f3960948b4603; export DEVX_MTA_HDI_BUILD_OPTIONS="{\"IsSelectiveBuild\":false,\"SelectedFiles\":[],\"IsSimulateBuild\":false,\"AdditionalOptions\":{\"migrationtable-development-mode\":true}}"; export PROJECT_PATH=/projects/tutorial-enhance-the-product-catalog/db; mkdir -p $CF_HOME/.cf/plugins/ && cp -u $CF_PLUGIN_PATH/config.json $CF_HOME/.cf/plugins/config.json 2>/dev/null || :;hdi-space-builder build"
4:32:52 PM (HDB) Executing Build command:
4:32:52 PM (HDB)  HDI BUILDER VERSION:1.1.8-20191023151637
4:32:52 PM (HDB) temp folder created at: /tmp/hdispacebuilder427706782
4:32:52 PM (HDB) Starting pre-hdiBuild operations...
4:32:54 PM (HDB) Build command failed : failed to prepare payload on pre build stage: service hdispacedeploy4dd0350d-21eb-4c29-be90-c3ceafbeb787 is not valid: failed install hdispacedeploy4dd0350d-21eb-4c29-be90-c3ceafbeb787 application: Failed to execute install command: Failed to execute install command: failed to set delete service : Row not found
4:32:55 PM (HDB) Build of /tutorial-enhance-the-product-catalog/db failed due to The "task for hdb build" process finished with code 1.

**Comment by renejeglinsky** [comment]
Hi @janhuachu ,

I've tested it now also in your region (us10). And it works for me. Could you please check if your account has enough resources? Or would you be willing to create a new subaccount in a new region (Frankfurt preferably) and try it there with the same sources? Here is a nice blog, explaining [How to change the region in your Cloud Foundry trial](https://blogs.sap.com/2019/04/16/how-to-change-the-region-in-your-cloud-foundry-trial).
You could share your sources. I know it should only differ by two lines but maybe it gives a hint.

-René

**Comment by janhuachu** [comment]
Thanks for your response. I was working using Chrome on a MacBook. There were some problems using the Chrome this morning. So, I switched to use Safari and everything is fine now.

Thanks for your support.
