### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#4217]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Please specify the step you are referring to.

Step:4 - Choose Add Role. In the Role Template dropdown list, select AuthGroup_Administrator and click on Save. Before doing this I need to select the Application Identifier from the drop down list and I have no idea which one includes the role template. 

The application identifier that needs to be selected is nonsensical and I have no idea before I have to select it that this identifier actually contains the AuthGroup_Administrator role template.

I ended up finding the right identifier but seriously not user friendly.

**Comment by gauthamkrishna-sap** [comment]
Hello,
Thank you for the feedback. I will improve the tutorial with info on how to find the right application identifier. 
Best Regards, Gautham

**Comment by thecodester** [comment]
@gauthamkrishna-sap Let me know when you have done this and then I will close the issue.

**Comment by gauthamkrishna-sap** [comment]
@thecodester I have made the updates and created a PR.

**Comment by thecodester** [comment]
https://github.com/SAPDocuments/Tutorials/pull/4237
