### ISSUE TITLE
Create SAP SuccessFactors To Dos and Timesheet Card

### ISSUE THREAD

**Issue by i820390** [SAPDocuments/Tutorials#4218]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-digitalexp-mobilecards-2-create.html

Please specify the step you are referring to 4Step 4: Configure SAP Mobile Cards client

Hi guys - I'm following this interesting exercise but I'm stuck on logon. Looks like my SCP credential is being rejected.
How can I check the credentials should I use?

Regards,
Dagoberto

**Comment by thecodester** [comment]
Not sure this is an issue with the tutorial. Perhaps it would be better to ask in the SAP Community or in the SAP Questions & Answers.

https://www.sap.com/community.html
https://answers.sap.com/index.html

@jitendrakansal Just assigning you in case you have any thoughts.

**Comment by jitendrakansal** [comment]
@i820390 Could you share the screenshot of the error? 
you need to enter email address/password to login to SAP Cloud Platform. Go to https://cockpit.hanatrial.ondemand.com/cockpit/#/home/trial, login to this page, on right hand side, click on "your name" and user information.

**Comment by jitendrakansal** [comment]
@thecodester author hasn't come back with further details. Maybe we can close this issue?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
