### ISSUE TITLE
Try Out SAP Cloud Platform SDK for Android Wizard

### ISSUE THREAD

**Issue by tpembe** [SAPDocuments/Tutorials#4223]
Tutorial URL: https://developers.sap.com/tutorials/cp-sdk-android-wizard-app.html

Please specify the step you are referring to: Step 3

When enabling the password passcode policy this feature is now under "mobile settings exchange"

**Comment by jarjarbentley** [comment]
Bruce, can you assist?

**Comment by flyingfish162** [comment]
Well, I presume that you were following the tutorials based on **CF** platform. In this case, you are absolutely right. However, all the tutorials for now are based on **NEO** platform and in that case, the instructions and screenshots in the tutorials still make sense.
