### ISSUE TITLE
Set Up Process Visibility to Track Employee Onboarding Workflow

### ISSUE THREAD

**Issue by bcschaich** [SAPDocuments/Tutorials#4225]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-4-visibility.html

Please specify the step you are referring to
This happens in Step 2 Add a workflow.
I can get to point number 2. After clicking on the "onboard" workflow it starts to load but never finishes. Message says already at loading the page that an eroor occured and I should try later or ask the service provider.
The module BPMFLP is not runing and crashing constantly. The only visible thing is a web error that occurs in the logs. (nothing more specific)

**Comment by ArchanaShukla** [comment]
This could have been due to cloud platform outages last week. Can you please confirm, if you still facing the same issue.

**Comment by bcschaich** [comment]
Seems like this was it. Thank you.
