### ISSUE TITLE
Expose Your App to the Portal Service (Cloud Foundry)

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#4226]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-create-launchpad.html

Step 3: Build and deploy your project

Hello @LindsayBert,

I try to follow the above tutorial in my CF Trial Account. As the starting point I use my MTA applicaiton [HTML5UserAPIforCF](https://github.com/gregorwolf/HTML5UserAPIforCF). But as soon as I add the "SAP Fiori Launchpad Site Module" in Step 1 the build of the app fails in Step 3 with the following error:

ERROR: Invalid mta.yaml. Make sure that the required module or resource dt_HTML5UserAPIforCF_appRouter is defined.

Hope you can reproduce the issue and provide me some help.

Best regards
Gregor

**Comment by gregorwolf** [comment]
OK, my app was created as a MTA. It seems that the wizard for adding the "SAP Fiori Launchpad Site Module" can only be applied for MTA's where the HTML5 module was created using the tickbox "User HTML5 repository"

**Comment by LindsayBert** [comment]
Lindsay and Iris

**Comment by LindsayBert** [comment]
Hi Gregor - sorry my last reply was deleted somehow.  
You should create the app using the CF dev model. You cannot use an existing app.
Thanks
Lindsay and Iris

**Comment by MichaelCzcz** [comment]
@gregorwolf Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
