### ISSUE TITLE
Maintain a Communication Arrangement for Inbound Communication

### ISSUE THREAD

**Issue by samantak123** [SAPDocuments/Tutorials#4227]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

Please specify the step you are referring to Step 5: Create communication system

In the SAP Fiori Page, I am unable to see the links for 'Communication Management' settings and hence can't proceed with Step 5 of this tutorial. Am I missing something here or I need to do some configuration settings ?

**Comment by mervey45** [comment]
@samantak123 Which system are you using? You only can do this with a license You need to assign as an admin your user the catalog role: ID_SAP_BCR_CORE_IAM. I'll add this to this tutorial.

**Comment by mervey45** [comment]
Hi @samantak123, 

do you need further help? Or can we close this issue?

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
@samantak123 Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
