### ISSUE TITLE
Debug srv/cat-service.js

### ISSUE THREAD

**Issue by octavonu** [SAPDocuments/Tutorials#4228]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Hello,

how would you debug the srv/cat-service.js in VSCode?

Thank you

**Comment by thecodester** [comment]
This is really a more general question and not about the tutorial itself. Feel free to continue the discussion in the SAP Community or in the SAP Questions & Answers.

https://www.sap.com/community.html
https://answers.sap.com/index.html

I will close the issue but have assigned to the author if he has any comments.
