### ISSUE TITLE
Set Up Connection Between Google BigQuery and SAP HANA

### ISSUE THREAD

**Issue by tpembe** [SAPDocuments/Tutorials#4232]
Tutorial URL: https://developers.sap.com/tutorials/gcp-hxe-evt-bq-1.html

Please specify the step you are referring to: Step 2.

I would be great if you could provide the setup.sh file.

**Comment by rbrainey** [comment]
Hi @tpembe, this specific tutorial was designed to be executed at one of our TechEd booths. The setup.sh file would have been on the machine in the booth. The page is marked "THIS TUTORIAL SERIES CAN ONLY BE EXECUTED AT TECHED" -- I'm going to close this issue, but I'm working to get a copy of the file in question and attach it to the Tutorial and message you once I have done that.  

Thanks,

Riley
