### ISSUE TITLE
Try Out SAP Cloud Platform SDK for Android Wizard

### ISSUE THREAD

**Issue by BenScandit** [SAPDocuments/Tutorials#4233]
Tutorial URL: https://developers.sap.com/tutorials/cp-sdk-android-wizard-app.html

Please specify the step you are referring to: When trying to add the backend URL, the dialogue I get seems to be different and it does not accept the SAP EDM URL.

Any suggestions, ideas, workarounds? Tried different spelling and all.

Thx - Ben

**Comment by flyingfish162** [comment]
The tutorial is for mobile server NEO landscape, but unfortunately you are using Cloud Foundry landscape. Please see the screenshot on how to set destination for Cloud Foundry landscape. And BTW, we are working on new tutorials for Cloud Foundry.
<img width="994" alt="Screen Shot 2019-11-22 at 17 49 15" src="https://user-images.githubusercontent.com/56924323/69417004-d3cb0b00-0d52-11ea-820b-b40aa0e0acbd.png">

**Comment by BenScandit** [comment]
Thanks for the quick reply Bruce!

Ben
