### ISSUE TITLE
Create a Database Table

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#4236]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-create-table.html

Please specify the step you are referring to
Step #1 - Create a table

Hi!

For some prototyping I'm using Eclipse to create a Z-table and thought I'd use the tutorial to follow the proper process instead of doing it via SE11 in SAP GUI. Unfortunately, it's not working as explained in the tutorial, as I cannot enter a table description - the field and the "Next" button are greyed out:
![grafik](https://user-images.githubusercontent.com/18588108/69157128-d1637980-0ae4-11ea-9e90-c2ee3b3d9452.png)
When I click on "Finish", a GUI windows opens and I'm in the usual DDIC-screen to provide the table information. 

Is this due to using a NW 7.50 SP13 system in the background? It's happening with both the latest Eclipse version (1909) and the old Neon. For the latter, the description field isn't even displayed and a GUI tab is opened as well.

Update: checking the Help information within Eclipse the underlying NW version seems to be the reason for this behaviour. If that is indeed the case, how about adding the information that NW 7.52 SP00 is a prerequisite to actually follow the tutorial?

Thanks much and Cheers
Bärbel

**Comment by julieplummer20** [comment]
Hi Bärbel, Yes, you're quite correct. I will update accordingly asap.
Thanks for your feedback -it's genuinely very helpful.
Best wishes,
Julie.

**Comment by BaerbelW** [comment]
Thanks, Julie!

**Comment by julieplummer20** [comment]
Hi @BaerbelW ,
Now fixed. Apologies. 
Can you please close this?
Thanks and best wishes,
Julie.
