### ISSUE TITLE
View the SAP Cloud Platform from 10,000 Meters

### ISSUE THREAD

**Issue by duyvietdo** [SAPDocuments/Tutorials#4238]
Tutorial URL: https://developers.sap.com/tutorials/cp-explore-cloud-platform.html

At step 3: The link 

https://cloudplatform.sap.com/support/service-description.html 

does not work anymore. I guess it moved to 

https://www.sap.com/products/cloud-platform/capabilities/services.list.html

**Comment by IObert** [comment]
Hi @duyvietdo,

both links work for me. Are you sure the first one is not working?

**Comment by duyvietdo** [comment]
Thanks for the reply. The first link, which is provided in the tutorial at step 3 in the sentence "take a look at a more complete list for details." does not work anymore, because when I click on it I get automatically redirected to 

https://www.sap.com/about/agreements/policies/cloud-platform.html

Instead of the service descriptions, I only see SAP Product policies...I guess this is not intended. The second link was only a suggestion from my side because, there, I can find a list of available services on SAP cloud platform.

**Comment by IObert** [comment]
I see.
I think the link still points to the intended document which can be downloaded from the policy page.

Nevertheless, thanks a lot for opening this issue!

**Comment by duyvietdo** [comment]
Ah, now I get it. My mistake then. Sorry.
