### ISSUE TITLE
Update SAP HANA, express edition (Binary Installer)

### ISSUE THREAD

**Issue by mechevarria** [SAPDocuments/Tutorials#4239]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-updating-binary.html

Please specify the step you are referring to

Step 1: Download Update files
Attempting to run ```./HXECheckUpdate_linux.bin``` results in the following **error**
```This program is generated by unregistered Jar2Exe and it has expired to run for DEMO use.```

This seems to be a a pretty wide issue affecting all SAP HANA Express users
[https://answers.sap.com/questions/12857573/hxecheckupdatejar-jar2exe-has-expired.html](https://answers.sap.com/questions/12857573/hxecheckupdatejar-jar2exe-has-expired.html)

**Comment by thecodester** [comment]
@JCurrie27 Are you still working on these tutorials?

**Comment by JCurrie27** [comment]
@mechevarria - I checked with the development teams and they are actively working on this issue, but a release date is not available at this time.
