### ISSUE TITLE
Install SAP HANA 2.0, express edition

### ISSUE THREAD

**Issue by dtondo** [SAPDocuments/Tutorials#4240]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-installing-binary.html

Please specify the step you are referring to: sudo ./setup_hxe.sh

____________________________________________________________________________________________

Installation is not working in Ubuntu: 19.10
Summary before execution:
=========================

SAP HANA Express Edition System Installation
   Installation Parameters
      SAP HANA System ID: HXE
      Instance Number: 90
      Local Host Worker Group: default
      System Usage: development
      Location of Data Volumes: /hana/shared/data/HXE
      Location of Log Volumes: /hana/shared/log/HXE
      Directory containing custom configurations: /home/dtondo/hana/HANA_EXPRESS_20/DATA_UNITS/HDB_SERVER_LINUX_X86_64/configurations/custom
      Certificate Host Names: hanaexpress -> hanaexpress
      System Administrator Home Directory: /usr/sap/HXE/home
      System Administrator Login Shell: /bin/bash
      System Administrator User ID: 1001
      ID of User Group (sapsys): 79
      Restart system after machine reboot?: Yes
      Inter Service Communication Mode: ssl
      Remote Execution: ssh
      Use single master password for all users, created during installation: Yes
      Database Isolation: low
      Install Execution Mode: optimized
      Installation Path: /hana/shared
      Local Host Name: hanaexpress
   Software Components
      SAP HANA Database
         Install version 2.00.040.00.1553674765
         Location: /home/dtondo/hana/HANA_EXPRESS_20/DATA_UNITS/HDB_SERVER_LINUX_X86_64/server
      SAP HANA AFL (incl.PAL,BFL,OFL)
         Install version 2.00.040.0000.1553698248
         Location: /home/dtondo/hana/HANA_EXPRESS_20/DATA_UNITS/HDB_AFL_LINUX_X86_64/packages
      SAP HANA EPM-MDS
         Install version 2.00.040.0000.1553698248
         Location: /home/dtondo/hana/HANA_EXPRESS_20/DATA_UNITS/SAP_HANA_EPM-MDS_10/packages
   Log File Locations
      Log directory: /var/tmp/hdb_HXE_hdblcm_install_2019-11-19_22.16.24
      Trace location: /var/tmp/hdblcm_2019-11-19_22.16.24_22097.trc
Installing components...
Installing SAP HANA Database...
  Creating System...
          Starting external program update-rc.d
Resume of SAP HANA Express Edition Installation failed
  Installation of SAP HANA Database failed
    Installation failed
      error installing
        Cannot create system
          Error checking sapinit
            Starting external program update-rc.d
              Command line is: update-rc.d -n sapinit defaults
              Output line 1: update-rc.d: error: unknown option
              Output line 2: usage: update-rc.d [-f] <basename> remove
              Output line 3:        update-rc.d [-f] <basename> defaults
              Output line 4:        update-rc.d [-f] <basename> defaults-disabled
              Output line 5:        update-rc.d <basename> disable|enable [S|2|3|4|5]
              Output line 6:            -f: force
              Output line 7:
              Output line 8: The disable|enable API is not stable and might change in the future.
              Program terminated with exit code 1

Log file written to '/var/tmp/hdb_HXE_hdblcm_install_2019-11-19_22.16.24/hdblcm.log' on host 'hanaexpress'.

Failed to install HDB server.
#########################################################################
# Summary after execution                                               #
#########################################################################
Server Installation...(FAIL)
XSC Installation...(NOT STARTED)
HXE Optimization...(NOT STARTED)

**Comment by greg2git** [comment]
i thought it was 'certified' only on 17.04 (Zesty Zapus) and i got used to 18.04 (bionic), so would be interested how they go about 19.10 (EoanErmine?). 

sorry for not having a solution for you, though.

**Comment by JCurrie27** [comment]
Hi dtondo: Ubunto is not officially supported for SAP HANA Express:
[https://help.sap.com/viewer/32c9e0c8afba4c87814e61d6a1141280/2.0.040/en-US/a347f9eb3fc444faa56b5caee9e9c010.html](https://help.sap.com/viewer/32c9e0c8afba4c87814e61d6a1141280/2.0.040/en-US/a347f9eb3fc444faa56b5caee9e9c010.html)

_Disclaimer
SAP HANA, express edition is officially supported on SLES. SAP Community members have been successful in running SAP HANA, express edition on other Linux operating systems that are not formally supported by SAP, such as Ubuntu, openSUSE and Fedora. SAP is not committing to resolving any issues that may arise from running SAP HANA, express edition on these platforms._

I recommend posting this issue on the Community page (Q&A) site in case fellow community members can assist.

**Comment by Lsubatin** [comment]
@dtondo Somebody sent this issue to me even though I'm not part of SAP any more. By the way, I would have caught your question in the community (answers.sap.com, where you'll find similar questions). 

Anyways, Ubuntu 16.04 LTS and 18.09 were working last time I checked. There are some dependencies to fulfill before the installation script can do its trick and you'll find them here: https://developers.sap.com/tutorials/hxe-gcp-ubuntu-xsa.html

HXE is supported by the community, not SAP, so if you make it work on a further version and are comfortable enough, go for it.

**Comment by fmavrodiev** [comment]
Hello, @dtondo,
I recently ran into the same problem using this guide - https://developers.sap.com/tutorials/hxe-gcp-ubuntu-xsa.html
Fortunately, I found solution here: https://blogs.sap.com/2018/07/21/how-to-install-sap-hana-express-edition-2.0-on-ubuntu-18.04-bionic-beaver/

Hope this helps!
