### ISSUE TITLE
Create an SAP Cloud Platform ABAP Environment Trial User

### ISSUE THREAD

**Issue by jjaimes** [SAPDocuments/Tutorials#4250]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html

Please specify the step you are referring to Create an SAP Cloud Platform ABAP Environment Trial User.

I've tried unsuccessfully to validate the Service KEY in Eclipse and I don't know what I have to do to get a solution.

Please, see the next video with my issue:     https://jmp.sh/v/TOcXFvQgPPTpO1yi0bpZ 

Eclipse version:  Eclipse 2019-09.

Thanks,
José Darío Jaimes Alviárez

**Comment by mervey45** [comment]
@jjaimes You need to have the latest ADT installed in your eclipse. Please do this first. This is the prerequisite. After that, try it out again. You can find the latest ADT link here: https://tools.hana.ondemand.com/#abap 
Just add it in eclipse -> help -> install new software and then install it and restart your eclipse.

**Comment by mervey45** [comment]
Hi @jjaimes , 

do you need further help? Or can we close this issue?

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
@jjaimes Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by jjaimes** [comment]
Sorry for delaying. 

The issue was because I didn't have permission to install software in the laptop I was using. I tried 
 to install it using another laptop and it was ok!

Thanks!.
