### ISSUE TITLE
Assign Roles to Users for Managing Business Rules

### ISSUE THREAD

**Issue by qmacro** [SAPDocuments/Tutorials#4252]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules02-assign-roles.html

Please specify the step you are referring to: **Step 2 Assign role collection**

In some cases it seems that there's an extra step required. In my case, I had to click through this:

![image](https://user-images.githubusercontent.com/73068/69313333-2f00de80-0c29-11ea-8b39-41fe033d091d.png)

Might be worth adding that to avoid confusion?

**Comment by VandanaVasudevan** [comment]
Hi,

Thanks a lot for this. I'll add this particular step to avoid confusion. :)

Best Regards,
Vandana

**Comment by thecodester** [comment]
https://github.com/SAPDocuments/Tutorials/pull/4258
