### ISSUE TITLE
Set Up the Manage Rules Project Application

### ISSUE THREAD

**Issue by qmacro** [SAPDocuments/Tutorials#4253]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules03-setup-mrp.html

Please specify the step you are referring to: **Step 3: Modify mta.yaml file (optional)**

"_If you have created a service instance with the name other than businessrules, you need to perform the following procedure._"

The name of the instance created in previous tutorials is 'business-rules' (with a dash). I can't tell whether this mismatch is deliberate or not. If it is deliberate (so the learner sees where a modification can / must be made) that's great but it's probably worth explaining that explicitly. So raising this issue just in case. Thanks!

**Comment by VandanaVasudevan** [comment]
The idea was to make users understand that they need to change or ensure that the right service instance name is provided. To avoid confusion, I've updated the tutorial :)

**Comment by thecodester** [comment]
https://github.com/SAPDocuments/Tutorials/pull/4258
