### ISSUE TITLE
Set Up the Manage Rules Project Application

### ISSUE THREAD

**Issue by qmacro** [SAPDocuments/Tutorials#4254]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules03-setup-mrp.html

Please specify the step you are referring to: **Step 4: Build and deploy project**

"_Right-click on the businessruleseditor project_" -> the project is `cf-businessruleseditor`

Also (and I sympathise with this - cloud based tools are hard to write tutorials for as they keep changing! :-)), the Build options have changed:

![Screenshot 2019-11-21 at 06 51 23](https://user-images.githubusercontent.com/73068/69314287-ad5e8000-0c2b-11ea-84a5-0ab14caa3144.png)

**Comment by VandanaVasudevan** [comment]
Hi,

Thanks a lot for letting me know about this change. I've updated the tutorial :)

Best Regards,
Vandana

**Comment by thecodester** [comment]
https://github.com/SAPDocuments/Tutorials/pull/4258
