### ISSUE TITLE
Add a Web Dynpro ABAP App to Your Portal Site

### ISSUE THREAD

**Issue by srissel** [SAPDocuments/Tutorials#4255]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-webdynpro-app.html

Please specify the step you are referring to
Step 5: Launch the app:

Upon opening the WebDyn Pro application via Launchpad, the following error is yielded:

> 
> 
> Service cannot be reachedWhat has happened?URL call was terminated because the corresponding service is not available.
> --
>  
> NoteThe termination occurred in system with error code 404 and for the reason Not found.
>  
> What can I do?Select a valid URL.HTTP 404 - Not foundYour SAP Internet Communication Framework Team
> 
>

**Comment by LindsayBert** [comment]
Hi - can you please open up a ticket for this issue.  It seems to be something technical that only the dev team can help with.

Thanks Lindsay

**Comment by srissel** [comment]
Sure, Lindsay.
Where can I open up such a ticket?

**Comment by LindsayBert** [comment]
Trying to find out for you - will get back to you soon.

**Comment by MichaelCzcz** [comment]
@LindsayBert Any updates?

**Comment by IrisSasson** [comment]
Hi, 

Can you try to add /sap/bc to the ES5 destination URL, can you try to see if this solved the issue?
Here is the complete URL: https://sapes5.sapdevcenter.com/sap/bc

Thanks, 
Iris.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
