### ISSUE TITLE
Test the Business Rules API from SAP API Business Hub

### ISSUE THREAD

**Issue by qmacro** [SAPDocuments/Tutorials#4259]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules09-test-apis.html

Please specify the step you are referring to: **Step 2: Configure the environment**

This step, in conjunction with the preamble, has the learner copy / paste the URL from the service key into the "Token URL" field in the environment configuration. However, doing this will lead to authentication errors.

Not all of the URL should be copy/pasted - the scheme should be omitted. In other words, this part of the URL should be copied: 

`i347491trial.authentication.eu10.hana.ondemand.com`

and not the entire URL;

`https://i347491trial.authentication.eu10.hana.ondemand.com`

(this is because the real TokenURL is made up from different bits and already has the "https://" scheme specified. Not a great UI there in the API Business Hub, but we have to make sure the learner doesn't trip up over it). 

Thanks!

**Comment by VandanaVasudevan** [comment]
I've explicitly mentioned it now as it is confusing and not so clear in the screenshot. Thanks for your feedback! It helped a lot in improving and updating the tutorials.

**Comment by thecodester** [comment]
https://github.com/SAPDocuments/Tutorials/pull/4260/files
