### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by jitendrakansal** [SAPDocuments/Tutorials#4264]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Please specify the step you are referring to
**Step 3: Start project
3.Go to View | Command Palette | Terminal: Create New Integrated Terminal to open a command-line window within Visual Studio Code and run the following command.**
when i run cds watch, i get this error in terminal section
**_ bash: cds: command not found_**
<img width="1583" alt="1" src="https://user-images.githubusercontent.com/31536700/69467456-5b7f3c80-0d88-11ea-91ce-fa23b2928b42.png">

I have already installed "CDS Language Support" Visual Studio Code extension.

But if i run cds watch in a terminal (outside vscode), i get the message as mentioned in the step.

<img width="476" alt="2" src="https://user-images.githubusercontent.com/31536700/69467461-5fab5a00-0d88-11ea-9488-27340267feda.png">

Is something missing in VSCode for this part?

**Comment by iwonahahn** [comment]
Hi,

After step 1.2 (installing cds using "npm i -g @sap/cds.dk") you have tried "cds" or "cds" version to check if cds was installed and if yes, which version? Could you share the screenshot with the version(s)?

Thanks a lot and best regards,
Iwona

**Comment by MichaelCzcz** [comment]
@jitendrakansal Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
