### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by jakes2255** [SAPDocuments/Tutorials#4265]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Please specify the step you are referring to:3

After installing the vsix extension, cds is not being recognized in the terminal.

Is there any additional steps required or a path be created the system registry? Please advise.

The full error message is as below:-
"cds : The term 'cds' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ cds
+ ~~~
    + CategoryInfo          : ObjectNotFound: (cds:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException"

**Comment by iwonahahn** [comment]
Hi,

After step 1.2 (installing cds using "npm i -g @sap/cds.dk") you have tried "cds" or "cds" version to check if cds was installed and if yes, which version? Could you share the screenshot with the version(s)? Are you using a Mac or a windows machine?

Thanks a lot and best regards,
Iwona

**Comment by MichaelCzcz** [comment]
@jakes2255 Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by silasd23** [comment]
> Hi,
> 
> After step 1.2 (installing cds using "npm i -g @sap/cds.dk") you have tried "cds" or "cds v" to check if cds was installed and if yes, which version? Could you share the screenshot with the version(s)? Are you using a Mac or a windows machine?
> 
> Thanks a lot and best regards,
> Iwona

I'm having the same issue this are my versions the problem here in my case is that if i use cmd i can run cds but if i use visual studio code i can not.
![image](https://user-images.githubusercontent.com/49450546/79999774-3bc57f00-84b4-11ea-80b0-54b5b5e797d4.png)

![image](https://user-images.githubusercontent.com/49450546/79999810-4718aa80-84b4-11ea-8578-b6c9b7553990.png)

i have also tryed to run as administrator but the error continues

**Comment by iwonahahn** [comment]
Did you installed the CDS Language Support extension for VS Code as described [here](https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html#7d1d1225-d7d0-40a2-8b43-413a488e5b82). Please check in VS code and get back to me. 

Best regards,
Iwona
