### ISSUE TITLE
Set Up a Workflow With Extended Employee Onboarding

### ISSUE THREAD

**Issue by JeremyChabert** [SAPDocuments/Tutorials#4266]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html

Please specify the step you are referring to

Hello, on following tutorial at this specific step => Step 5: Build and deploy the sample application, if you use the new Build MTA, there's an error occuring stating this
10:59:20 (Executor) line 33: the "acceptworkplace" module does not contain the mandatory "supported-platforms" and "build-result" build configurations; see "https://sap.github.io/cloud-mta-build-tool/migration/#features-that-are-handled-differently-in-the-cloud-mta-build-tool"
10:59:20 (Executor) Error: could not build the MTA project: could not execute the "make -f Makefile_20191124095921.mta p=cf mtar= strict=true mode=" command: exit status 2
10:59:20 (Executor) line 38: the "appro
10:59:20 (MTA BUILD) The "Task for mta build" process finished with code 1
10:59:20 (MTA BUILD) Build of "sample.onboarding.mta" failed.

But if you use the old deprecated one, it's working fine.
Please be aware of it.

**Comment by ArchanaShukla** [comment]
Thanks for bringing this up. We will improve the tutorial

**Comment by ArchanaShukla** [comment]
Tutorial updated.
@thecodester - please close the issue
