### ISSUE TITLE
Add a Model and Test the SAPUI5 App

### ISSUE THREAD

**Issue by manuelseeger** [SAPDocuments/Tutorials#4269]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-webide-setup-datasource.html

Step 2, design the data source, fails on a freshly created trial account used for this tutorial. The system dropdown listbox is empty. Reloaded Web IDE, restarting the browser, etc does not work. The destination maintained in the trial CF subaccount for the Northwind service does not show up in Web IDE.

**Comment by IObert** [comment]
Hi Manuel,

correct observation :)
This tutorial is part of a larger group ([this one](https://developers.sap.com/group.cp-frontend-ui5-1.html)) where you need to start from the beginning, e.g. when the developer reaches this tutorial (s)he already set up a destination in the Neo env and in the CF env. (Setting up two destinations is the available workaround for the issue that the Web IDE can only read destinations from the Neo env)

Please let me know if you have further questions!

**Comment by manuelseeger** [comment]
Hi Marius, 

Thanks, got it now.

It seems like the trial environment has changed a bit. I can't find a way anymore to access the trial cockpit on a global account level. It looks like we can only access Neo through this link on the new trial home page:

![image](https://user-images.githubusercontent.com/45933060/69614941-56deb080-1034-11ea-9970-499774bf603c.png)

The screenshots on https://developers.sap.com/tutorials/hcp-create-destination.html still show the old trial cockpit.

**Comment by IObert** [comment]
Good catch! I fixed it in PR #4276

The screenshot should be updated in the next few minutes
