### ISSUE TITLE
Run, Test and Deploy Your Java App

### ISSUE THREAD

**Issue by whiteezeng** [SAPDocuments/Tutorials#4272]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-java-run.html

Please specify the step you are referring to
Step 1: Attempt to run your Java app
I can't run my Java app due to Cloud Foundry setting , pls help

![image](https://user-images.githubusercontent.com/29919366/69616429-924ba000-1071-11ea-9163-74ed240641e8.png)

my cloud foundry
![image](https://user-images.githubusercontent.com/29919366/69616505-b0b19b80-1071-11ea-8c76-aa0cc1d52bad.png)

**Comment by jarjarbentley** [comment]
Have you opened WEB IDE, navigated to your project and right clicked for project settings?  After that you should see cloud foundry settings.  They should be default and should match your user name and password for the SAP Cloud Platform login.

**Comment by whiteezeng** [comment]
Hi jarjarbentley, check my screenshot again, if I use default setting, the error is given like 'The Cloud Foundry settings are not configured for your project...', that's why I radio button 'use the following settings for this project'

**Comment by jarjarbentley** [comment]
if this is still an issue upon re-truing the tutorial from start please re-open issue.
