### ISSUE TITLE
Create a Decision Support App and Enable Notification in SAP Fiori Launchpad

### ISSUE THREAD

**Issue by valentini50** [SAPDocuments/Tutorials#4273]
Group URL: https://developers.sap.com/group.iot-app-decision-support.html

It is not possible to complete the mission even though all stages are as 100%.
Tutorial is 67%

**Comment by thecodester** [comment]
Can you be more specific?

- On the group page, are all tutorials showing as completed?
- Is the group showing as completed?

**Comment by valentini50** [comment]
I was able to complete, I entered again and redid all the steps (I had already done that, but did not save what I did) now completed.
You can close the topic
