### ISSUE TITLE
Prepare the SAP Cloud Platform Cloud Foundry Environment for Development (non-trial account)

### ISSUE THREAD

**Issue by whiteezeng** [SAPDocuments/Tutorials#4274]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-prepare-dev.html

Please specify the step you are referring to
Step 1: Set up your own subaccount for development
WHY my space memory plan is 0 MB?
![image](https://user-images.githubusercontent.com/29919366/69618875-97125300-1075-11ea-8065-4fd885ffd537.png)

**Comment by thecodester** [comment]
@whiteezeng You are using trial account?

@qmacro Do you know how the quota is allocated?

**Comment by LindsayBert** [comment]
If you are  using a trial account the quota is allocated automatically.  In this tutorial it mentions that if you are not using a trial account, you should contact your SAP Cloud Platform administrator and ask them to provide the relevant entitlements and quotas.
Thanks Lindsay

**Comment by whiteezeng** [comment]
@LindsayBert @thecodester  YES, I am using trial account.  it should‘ve been allocated automatically , but it's not. How can I fix this?

**Comment by thecodester** [comment]
I think this is beyond the scope of the people who write the tutorials. I suggest asking in the community https://www.sap.com/community.html or https://answers.sap.com/index.html 

@otiliamarinescu Before closing the issue, how can we handle these types of SAP Cloud Platform issues, unrelated to the specific tutorial?

**Comment by otiliamarinescu** [comment]
@thecodester this should be clarified with Katrin or Annika.

One suggestion I have for this particular case, since the issue of entitlements not being automatically assigned is quite common, would be that authors add a note to the step informing users how to assign entitlements manually in case the automatic provisioning failed.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
