### ISSUE TITLE
Create a Service Instance of SAP Cloud Platform Process Visibility

### ISSUE THREAD

**Issue by Kopylov-aa** [SAPDocuments/Tutorials#4278]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-processvisibility-setup-serviceinstance.html

Please specify the step you are referring to
Step 2. I have no service "Process Visibility" at my https://account.hanatrial.ondemand.com/cockpit
Additionally i found that I have no quotas 
![image](https://user-images.githubusercontent.com/36968487/69647881-54ec1000-107b-11ea-8982-68989878224a.png)

**Comment by Kavya-Gowda** [comment]
Hi,

Could you please check your assigned entitlements?
You can find them when you click on the I318791trial link in the breadcrumb and then choose 'Entitlements'.
There should be a table with a lot of entitlement assignments.
If there is no Process Visibility assignment please try to assign it to your subaccount.
Maybe something went wrong during the creation of your trial account?

If the issue still persists, please create a ticket. Navigate to your cockpit, refer to the below screenshot and choose "Contact us" to create a ticket.

![Cockpit](https://user-images.githubusercontent.com/51773410/69696503-e2744200-1105-11ea-98ad-343499f64251.PNG)

**Comment by Kopylov-aa** [comment]
Today it works.
