### ISSUE TITLE
Feedback on Tutorial: How to create an SAP HANA Developer Edition in the Cloud

### ISSUE THREAD

**Issue by prasadbcd** [SAPDocuments/Tutorials#428]
Any can provide the differences between the HANA Developer Edition and SAP HANA ONE.
As we are looking for 64GB memory. can we proceed with the developer edition,  is there any limitation of features.

**Comment by ccmehil** [comment]
There are several differences between them, the main difference is that the SAP HANA Developer Edition falls under the Unified Developer License and is for development purposes only (no license costs only hosting fees to your provider AWS or Azure) and SAP HANA ONE has a full productive use license (you pay SAP a license fee and your hosting fees with AWS) - both are available in 64GB.
