### ISSUE TITLE
Add a UI to Your Business Application

### ISSUE THREAD

**Issue by fsebbane** [SAPDocuments/Tutorials#4280]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-02-add-ui.html

Step 6: Add an annotation file: Ok
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
	<edmx:Reference Uri="/srv_api/catalog/$metadata"/>
	<edmx:DataServices>
		<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm"/>
	</edmx:DataServices>
</edmx:Edmx>

Step 7: Add UI annotations: Error
Go to app/webapp/localService, right-click on the file you just created and choose Open Annotation Modeler.
Error:
Cannot read property 'split' of undefined

I am using the Worklist template V4 / with Nodejs

**Comment by renejeglinsky** [comment]
Hi @fsebbane, 

have you also created an V4 project? If not, please use the List Report template as used in the tutorial.
If you've created a V4 project, then you have two options.

*Option 1:*
Change your project to a V2 project (in the package.json on root level)  and follow the tutorial using the List Report template.

*Option 2:*
Keep your V4 project and use the Worklist V4 template. But this deviation is then not part of this tutorial. In that case you could try to find your own V4 way, which is, as already stated, then not part of this tutorial anymore and can't be supported here.


Regards,
René

**Comment by MichaelCzcz** [comment]
@fsebbane Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
