### ISSUE TITLE
Create a Business Scenario for a Deployed Workflow

### ISSUE THREAD

**Issue by Kopylov-aa** [SAPDocuments/Tutorials#4287]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-processvisibility-model-configscenario.html

Please specify the step you are referring to Step 2: Add workflows

I don't see onboard in SAP Cloud Platform Workflow list
![image](https://user-images.githubusercontent.com/36968487/69729406-4ebb6980-1137-11ea-990d-865f19c6b723.png)

Additionally  i Found error in log:
"error": {
"code": "bpm.pvs.request.processing.error",
"message": "Internal server error. An error occurred while processing your request. Please contact the service provider."
}

**Comment by Deeksha-R** [comment]
Hi Kopylov-aa,
Have you followed the prerequisite provided in the tutorial?
"You have a deployed workflow from SAP Cloud Platform Workflow on Cloud Foundry. If you do not have a workflow deployed, then refer to the following blog."
the prerequisite is that you already have your workflow deployed. 

Regards
Deeksha

**Comment by MichaelCzcz** [comment]
@Kopylov-aa Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
