### ISSUE TITLE
Deploy SAP HANA as a Service

### ISSUE THREAD

**Issue by lrcherubini** [SAPDocuments/Tutorials#4291]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-deploying-haas.html

Please specify the step you are referring to 

Hi,

In the Step "Navigate to Services -> Service Marketplace. Click on SAP HANA Service.".
In the Cloud Platform thers's no SAP HANA Service, intead of there is the service SAP HANA Schemas & HDI Containers (Trial) but is a little different.

**Comment by Sygyzmundovych** [comment]
Hi Leandro. Are you using a productive account with entitlement to the SAP HANA Service in Cloud Foundry? That's the prerequisite for that tutorial listed on the right. It will not work with SCP Trial.
Regards,
-Vitaliy

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
