### ISSUE TITLE
Configure the Development Environment

### ISSUE THREAD

**Issue by lrcherubini** [SAPDocuments/Tutorials#4292]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-configure-dev-env.html

Please specify the step you are referring to
Step 1: Navigate to the Neo subaccount
Step 2: Access the SAP Web IDE

Hi 

The way to access the SAP Web IDE Full-Stack has been changed. The screens showed into the tutorial are wrong.

**Comment by MichaelCzcz** [comment]
Hello,

thanks for your feedback. We are aware of the issue and will soon update the tutorial.

cheers,
Michael
