### ISSUE TITLE
Connect to the SAP HANA Cockpit

### ISSUE THREAD

**Issue by lrcherubini** [SAPDocuments/Tutorials#4293]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-connect-hana-cockpit.html

Please specify the step you are referring to
Connect to the SAP HANA Cockpit

Hi

I can't be able to do this tutorial using Service: SAP HANA Schemas & HDI Containers (Trial) - Overview.

**Comment by jung-thomas** [comment]
@lrcherubini 
Yes this tutorial is not intended to apply to the Trial.  There is a note at the beginning of the tutorial to inform the user of this:
**This tutorial cannot currently be completed with a trial account.**
