### ISSUE TITLE
Step 3: Navigation in the cockpit - Need a correct answer

### ISSUE THREAD

**Issue by ShahidLatif-CAN** [SAPDocuments/Tutorials#4294]
https://developers.sap.com/tutorials/cp-trial-quick-onboarding.html#7ff34f51-4c0f-44a8-ab76-870a057d9065

Please see the above link for Tutorial: Get Started with SAP Cloud Platform Trial

For some reason, I cannot get the write answer for the third Step: Step 3: Navigation in the cockpit 

Can someone please help me out, and give me the correct answer.  
I would appreciate it very much.

Thanks.

Shahid.

**Comment by thecodester** [comment]
I am closing because this is duplicated.
