### ISSUE TITLE
Get Started with SAP Cloud Platform Trial

### ISSUE THREAD

**Issue by ShahidLatif-CAN** [SAPDocuments/Tutorials#4295]
Tutorial URL: https://developers.sap.com/tutorials/cp-trial-quick-onboarding.html

Please specify the step you are referring to:
Step 3.
No matter what answer I put up there, it never accepts it.
Could you please provide me with the correct answer.

Thanks.

Shahid.

**Comment by otiliamarinescu** [comment]
Same issue as #4294 and #4301. This has been solved (validation was removed), the issue can be closed.

**Comment by MichaelCzcz** [comment]
@ShahidLatif-CAN Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
