### ISSUE TITLE
Add a New Entitlement to Your Subaccount

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#4298]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-entitlements-add.html

Please specify the step you are referring to

In Step 4 it seems like Functions (beta) is not available anymore.

**Comment by IObert** [comment]
Thanks for opening this issue. I still see it but this might depend on the user and the time when he/she created the account.

To keep things simple, I'll remove it from the table.

Thanks!
