### ISSUE TITLE
Explore and Customize Your SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#4299]
Tutorial URL: https://developers.sap.com/tutorials/webide-customize.html

Please specify the step you are referring to

In Step 7 only "Technical error" shows up after submitting the answer. Step 8 cannot be switched to Done afterwards.

**Comment by thecodester** [comment]
There was probably a temporary problem, but I can do it now. Can you check again?

**Comment by freilinger** [comment]
It works now again, thanks a lot!

**Comment by MichaelCzcz** [comment]
@freilinger Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
