### ISSUE TITLE
Install the Cloud Foundry Command Line Interface (CLI)

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#4300]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-download-cli.html

Please specify the step you are referring to

Clicking on Done is not possible in step 1 & 3

**Comment by freilinger** [comment]
Issue resolved - probably temporary problem.

**Comment by MichaelCzcz** [comment]
Thanks for your feedback. I will close the issue.
