### ISSUE TITLE
Get Started with SAP Cloud Platform Trial

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#4301]
Tutorial URL: https://developers.sap.com/tutorials/cp-trial-quick-onboarding.html

Please specify the step you are referring to

In Step 3 the second value of the left menu for applications is requested. 
At the point in time of step 3, the trainee does not have an application yet, where he could navigate into to check the menu.

**Comment by otiliamarinescu** [comment]
This has been solved, I removed the validation question for Step 3 which was causing issues

**Comment by MichaelCzcz** [comment]
@freilinger Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
