### ISSUE TITLE
Deploy Your First SAPUI5 App to Cloud Foundry

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#4302]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-webide-new-app.html

Please specify the step you are referring to

No must have, but it would be nice if the new tool to build MTS archives would be used in the tutorial. 
https://blogs.sap.com/2019/11/19/enjoy-our-new-tool-for-building-mta-archives/

**Comment by IObert** [comment]
Thanks for the suggestion @freilinger !
I just made the change and it should be live soon
