### ISSUE TITLE
Add a User Task to Your Workflow (Neo)

### ISSUE THREAD

**Issue by HubertWeber** [SAPDocuments/Tutorials#4306]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-add-usertask.html

Step 1:
Fiori Launchpad (Default Site) does not find a My Inbox app, using the App finder.

**Comment by AstridHerbst** [comment]
Hi Hubert,

We are investigating the issue.

Regards,
Astrid

**Comment by AstridHerbst** [comment]
Hi Hubert,

Thanks for your feedback and please excuse the inconvenience.
Step 5 (Assign roles) from the first part of the tutorial went missing (https://developers.sap.com/tutorials/cp-workflow-getting-started.html). If you assign the roles, the apps should be visible in the launchpad.

Best regards,
Astrid
