### ISSUE TITLE
Set up SAP HANA, express edition on Amazon Web Services (XS Advanced)

### ISSUE THREAD

**Issue by walsap** [SAPDocuments/Tutorials#4309]
Tutorial URL: https://developers.sap.com/tutorials/hxe-xsa-aws-setup.html

Please specify the step you are referring to

@Lsubatin you wrote this blog? 

in a hackaton you said there is a cheap method for AWS and I don't want to delete Hana express. I want to install Shine in web ide but I can't find the blog.

**Comment by Lsubatin** [comment]
Hi - yes, I wrote this tutorial and then @adadouche added a ton of contributions. 

Thanks for calling this out, as taking credit for someone else's contributions goes against the spirit of open source communities and the one I know the SAP Developers team abides by. @jarjarbentley @rbrainey @akula86  I hope this mistake can be fixed.

A disclaimer: I no longer work at SAP, so this is an "unofficial" answer. 

First, the cheaper way on AWS would be a manual installation on an alternative OS (Ubuntu or opensuse) and the important part here: a cheaper choice of disk. As long as it's SSD, it should be enough. Scroll down this page for all of the alternatives, including the instructions for other operating systems on GCP and Azure (you'll need to "convert" the instructions to work on AWS): https://developers.sap.com/topics/sap-hana.html 

As a reminder, Google Cloud normally offers 300 USD worth of credits for first time users. So if you go with Ubuntu there, the first runs should be free. 

Remember to switch off the database  (command HDB stop) before switching off the virtual machine on any platform.

Third, I disagree with deleting HANA Express after installing it. It does not make sense to "complete this in one sitting" just to delete the instance. The HXE installation tutorials were not meant to be part of any missions either, but again, I'm not in that team anymore.

For the SHINE instructions, I would follow the instructions in the repository itself: https://github.com/SAP/hana-shine-xsa . The tutorial with detailed instructions is here but is outdated: https://developers.sap.com/tutorials/xsa-ml-e2e-access-shine.html

**Comment by adadouche** [comment]
To added up to @Lsubatin, you can use the "Launcher" to create an HXE instance and during the steps you will have an option to tweak the disk setting and select something cheap (cold storage). So you won't have to download the binary and install it from the ground and potentially face so system configuration issues.

However, this will still incur a charge for the disk (but not 400$ a month).

As @Lsubatin mentioned, GCP offers 300$ of credit to use for anything you like, and one of the good thing there is that if you shutdown your HXE instance it should not cost you anything (not even the disks). 

Another freebee of GCP is that once your credit are all gone, they won't charge you and just stop everything unless you accept being charged.

But I'm not part of the team either so this is an "unofficial" answer too.

**Comment by jarjarbentley** [comment]
please re-open if the comments above do not answer your issue (free AWS trial for new accounts under a certain amount of usage) . Turn off resources as soon as tutorial complete.  There are only vouchers for AWS when doing an onsite event with AWS employees available.  SAP does not offer AWS credit.
