### ISSUE TITLE
General suggestion for Tutorials: Generate a list of "my" tutorials

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#4310]
Hi Folks,
whenever I'm accessing the growing list of tutorials I have a hard time finding the ones I already did and want to revisit or the ones I started and would like to continue. I've been looking around on the page but don't seem to find a link with which tutorials I at least started but not necessarily finished could be displayed. Something like an additional filter for "accessed by me", "in process by me" or "completed by me" would come in very handy.

And, it may well be that it's already there and that I'm just too blind to spot it!

And if there's a better place to make this suggestion, please let me know and I'll repost it there.

Thanks much and Cheers
Bärbel

**Comment by MichaelCzcz** [comment]
Hello Bärbel,

thanks for your input. As a workaround you could set bookmarks for tutorials you have worked on:

![image](https://user-images.githubusercontent.com/57144076/70061362-6e91d800-15e4-11ea-8267-53deffc485f2.png)

Cheers,
Michael

**Comment by BaerbelW** [comment]
Hi Michael,
yes I saw the bookmarks but as these contain all of them and are not automatically restricted to "bookmarks set for tutorials" it's not really helpful given how the list looks for me:
![grafik](https://user-images.githubusercontent.com/18588108/70062380-2ffd1d00-15e6-11ea-81ac-d00b39f8e96a.png)
Not even sure how the shown entries are picked from complete and ever growing list of bookmarks!

Cheers
Bärbel

**Comment by thecodester** [comment]
If you go to https://developers.sap.com/ and log in, there is a "Continue Yoru Learning" section and a "History" tab for completions. Will that work for you?

![image](https://user-images.githubusercontent.com/11659786/70859207-4b3a2780-1f18-11ea-83c9-9472d21be9c4.png)

**Comment by BaerbelW** [comment]
Hi Daniel,

 

thanks!

 

Yes, that page works. It just wasn't easy to find if you start on the tutorial navigator page which is what I usually do. Has a link been added to the menu there which opens on the left-hand side? It is where I looked for such a page now but none of the then shown options led me there (or perhaps I missed it, I don't remember). How about renaming "Developer" to "Your Developer Center" to make it more apparent?

 

Cheers

Bärbel
 

Gesendet: Sonntag, 15. Dezember 2019 um 07:53 Uhr
Von: "Daniel Wroblewski" <notifications@github.com>
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: "Bärbel Winkler" <baerbelw-sks@online.ms>, Author <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] General suggestion for Tutorials: Generate a list of "my" tutorials (#4310)


If you go to https://developers.sap.com/ and log in, there is a "Continue Yoru Learning" section and a "History" tab for completions. Will that work for you?

**Comment by thecodester** [comment]
I will put it in my backlog to find a way to link from navigator to the Developer center. I have also notified the person responsible for the hamburger menu (upper left) to consider the naming of that option. Thanks.
