### ISSUE TITLE
Define a Simple Data Model and OData Service with CDS

### ISSUE THREAD

**Issue by andrecontax** [SAPDocuments/Tutorials#4311]
Tutorial URL: https://developers.sap.com/tutorials/odata-05-data-model-service.html

Please specify the step you are referring to

Hello, I got the error below when trying to build the db module:
"15:26:16 (HDB) Build command failed : failed to prepare payload on pre build stage: service hdispacedeploy3c6d1298-c699-440a-8a90-316535ba9b7b is not valid: failed install hdispacedeploy3c6d1298-c699-440a-8a90-316535ba9b7b application: Failed to execute install command: Failed to execute install command: failed to set delete service : Row not found
15:26:16 (HDB) Build of /Products/db failed due to The "task for hdb build" process finished with code 1."

Some other people seem to be having the same issue, as mentioned on this post:
https://answers.sap.com/questions/12862407/hana-cloud-foundry-trial-hdispacedeploy-creation-f.html#

**Comment by qmacro** [comment]
Hello there, sorry for the delay @andrecontax . I will assume for now that this was a temporary issue and you are OK now. If not, may we please suggest you turn to the [Community Q&A](https://answers.sap.com) for help with this, as it's not specifically related to the mechanics of the tutorial content or format (which is what these issues are for). Thank you and good luck!

**Comment by fjcarrasco** [comment]
Hi  @andrecontax. Did you solve it ? I'm getting the same error. 

Please, if you did, tell me how solved. 

Thanks
