### ISSUE TITLE
Add a User Task and Generic UI to Your Workflow

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#4312]
Tutorial URL: https://developers.sap.com/tutorials/cp-wf-02-add-user-task.html

Please specify the step you are referring to

No big deal, but the link in step 1 to "Create a workflow definition using an external service" is broken.

**Comment by qmacro** [comment]
Thanks @freilinger - nice spot. Fixed with https://github.com/SAPDocuments/Tutorials/commit/e5e6fbdf244ba029a88315b75c202cacf0c0f331 (update will appear in a short while on the live site).
