### ISSUE TITLE
Create Data Objects and Configure Value Help for Scenario

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#4315]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules05-dataobjects.html

Please specify the step you are referring to

The description of the jobTitle should probably not be Company name in Step 1.

**Comment by VandanaVasudevan** [comment]
Hi,

Thanks a lot for your feedback. This issue is fixed now.

Best Regards,
Vandana
