### ISSUE TITLE
Create a Sample Application on Cloud Foundry Using SAP Cloud SDK

### ISSUE THREAD

**Issue by lambavikas** [SAPDocuments/Tutorials#4322]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-cloud-foundry-sample-application.html

1. After you have created your project it fails to build (mvn clean package) as the last goal related to usage analytics doesn't work. The error suggest that it was unable to download the plugin dependencies for the usage analytics plugin. I was able to move ahead by disabling the goal in pom.xml but kindly see what's missing.

2. The part where we can run this locally using mvn tomee:run also fails due to "No plugin found for prefix 'tomee' in the current project and in the plugin groups...".

Vikas

**Comment by MatKuhr** [comment]
Hi Vikas, thank you for reporting this and sorry for the delayed response. As to your points:
1. We had some trouble with this in the past. This might be related to maven not updating stuff in time. Try running the goal while forcing maven to update by also passing `-U` to the command. That should do the trick.
2. Are you sure you navigated to the correct directory (`application`)? You can also run the command from the root dir by passing `-pl Application` to the command.

If not and these things are still an issue please run maven with the `-X` option for debugging and provide the relevant log output.

Best regards, Matthias

**Comment by MichaelCzcz** [comment]
@lambavikas Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
