### ISSUE TITLE
Test the Business Rules API from SAP API Business Hub

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#4325]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules09-test-apis.html

Hi, 
the following description is a little missleading: 
Enter the token URL without https://. For example, if the token URL in the service key is https://<trial ID>.authentication.eu10.hana.ondemand.com, then enter //<trial ID>.authentication.eu10.hana.ondemand.com.

I think it should be like this, without // for the url to be entered: 
... then enter <trial ID>.authentication.eu10.hana.ondemand.com.

**Comment by VandanaVasudevan** [comment]
Hi,

Thanks for your feedback. I've updated the tutorial.

Best Regards,
Vandana

**Comment by MichaelCzcz** [comment]
@freilinger Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
