### ISSUE TITLE
Status 502 - Use the Application Router in Cloud Foundry to Connect to ABAP System

### ISSUE THREAD

**Issue by vivek-krishnadas** [SAPDocuments/Tutorials#4326]
I followed this tutorial to build myself an approuter on CF.
https://developers.sap.com/tutorials/cp-connectivity-consume-odata-service-approuter.html

The router works perfectly fine for routes with destination of type Internet, but ends with a 502 status while accessing OnPremise destinations.

Log entry:
_{"written_at":"2019-12-06T12:27:27.943Z","written_ts":1575635247943000000,"csn_component":"-","correlation_id":"b5db957c-715b-48dc-79c3-e34c7d581ae7","type":"log","logger":"nodejs-logger","layer":"/Handler","level":"error","container_id":"10.32.2.9","component_type":"application","component_id":"2d39ce3c-d0a7-48c0-954b-236a18fb1217","component_name":"approuter","component_instance":-1,"source_instance":-1,"organization_id":"-","organization_name":"-","space_id":"3ae5a25a-dce9-4370-bede-4d26a032d31d","space_name":"dev","request_id":"b5db957c-715b-48dc-79c3-e34c7d581ae7","msg":"GET request to /sap/opu/odata/sap/ZBC_USER_SRV/UserSet completed with status 502 - error while forwarding request to http://myrouter-ah1:123/sap/opu/odata/sap/ZBC_USER_SRV/UserSet: getaddrinfo ENOTFOUND myrouter-ah1 myrouter-ah1:123"}_

I tried different approuter versions: 5.3.0(like in this tutorial), 6.1.0(like in resolution of issue https://github.com/SAPDocuments/Tutorials/issues/3813) and 6.7.0(latest).

I tried defining the destinations on subaccount level, destination service instance level and in the manifest file as environment variable destinations. None of them are accessible to the approuter, same message in every case.

Cloud connector doesnt show any incoming requests. I have confirmed the accessibility of backend via cloud connector by using it in an app deployed in Neo, it works fine. 

What else can i check ?

**Comment by MichaelCzcz** [comment]
@JensHaley Can you please look into this issue and provide an update?

**Comment by JensHaley** [comment]
@vivek-krishnadas : 
Sorry, but I was not in the office for 7 weeks.

What puzzles me is that you say you confirmed the accessibility of the backend by a Neo app. 

So you completed the first of my tutorials successfully to configure the Fiori Reference Apps in your ABAP system? Other colleagues missed that the [demo user that is configured there](https://developers.sap.com/tutorials/cp-connectivity-configure-fiori-reference-apps.html#d88225e0-6a7b-4e09-a561-b9b4c120b048) must be used when you later [create the destination](https://developers.sap.com/tutorials/cp-connectivity-consume-odata-service-approuter.html#b11c9363-5ade-4a5a-998c-030801b13f44) on CF.

`ENOTFOUND` sounds to me as if the endpoint is not found.
Is `myrouter-ah1:123` the virtual host for the ABAP system that you configured in the Cloud Connector? It sounds a bit as if the address refers to the approuter, not to the ABAP backend system.

**Comment by MichaelCzcz** [comment]
@vivek-krishnadas Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
