### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by patrickfontdean** [SAPDocuments/Tutorials#4327]
First up, thanks a lot for creating such rich content, it makes learning so much easier!

Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

I'm looking at the step involving Postman, and I'm getting the error {"error":"invalid_request","error_description":"Missing grant type"}

I'm pretty sure I've followed all the instructions correctly!? Where does the Grant Type get set?

**Comment by gauthamkrishna-sap** [comment]
Hi Patrick,
Thanks for the kind words, glad you found it helpful :) 
From the error, it looks like your user does not have all the roles assigned to it. 
Can you please check if you have performed all the tasks mentioned in steps 2 & 3 in this tutorial: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html 
Best Regards,
Gautham

**Comment by MichaelCzcz** [comment]
@patrickfontdean Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
