### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by russellw999** [SAPDocuments/Tutorials#4330]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

A great Tutorial as it clearly shows where you set up the Integration Services in SAP Cloud Platform.
The SAP Press Book   SAP Cloud Platform Comprehensive Guide starts describing the actual screens for Integration services but omits to show how it is set up , configured or accessed.   This tutorial fills in that gap

**Comment by MichaelCzcz** [comment]
@russellw999 Thank you for your positive feedback on our tutorial.
