### ISSUE TITLE
Get Started with SAP Cloud Platform Trial

### ISSUE THREAD

**Issue by Bajuz123** [SAPDocuments/Tutorials#4331]
Tutorial URL: https://developers.sap.com/tutorials/cp-trial-quick-onboarding.html

Step 3: Navigation in the cockpit
There is no valid answer to this question. Did you change the ui after creating this tutorial?

Btw. the navigation between finished and unfinished courses is a little confusing. When I end a series of tutorials, I can't get back to where I started (unless I open that in a new window).

**Comment by meisle** [comment]
Same issue in step 3 for me.
