### ISSUE TITLE
Tour the SAP Community

### ISSUE THREAD

**Issue by thhapke** [SAPDocuments/Tutorials#4335]
Tutorial URL: https://developers.sap.com/tutorials/community-start.html

Please specify the step you are referring to

3)
I might be too stupid for answering question 3. But I have only to choices to select for email notification: 1. comments and answers... and 2. Content I was mentioned in. But this is the wrong answer?
Thanks

Thorsten

**Comment by thecodester** [comment]
@thhapke There are 3 correct answers -- the 2 you mentioned and one more

**Comment by MichaelCzcz** [comment]
@thhapke Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
