### ISSUE TITLE
Installing SAP HANA, express edition Server + Apps, with Docker

### ISSUE THREAD

**Issue by draschke** [SAPDocuments/Tutorials#4336]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker-xsa.html

Step 8: Set Up Password for SAP HANA, express edition
"If the file is to be stored locally, store it in the /data/ directory you created earlier." this part is not mentioned in the ealier steps.

but is here mentioned:
https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html
Step 6: (Optional) Create a Directory to Persist SAP HANA, express edition Data Outside of the Container

**Comment by MichaelCzcz** [comment]
@aplata-sap @JCurrie27 any updates?

**Comment by JCurrie27** [comment]
@MichaelCzcz - Apologies for the delay. https://developers.sap.com/tutorials/hxe-ua-install-using-docker-xsa.html is missing the password persistence directory creation task in what should be step #8. This missing step will be visible online within the hour.
