### ISSUE TITLE
Introduction to Offline OData

### ISSUE THREAD

**Issue by miffels** [SAPDocuments/Tutorials#4338]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-hcpms-offline-odata-introduction.html

Pls. correct mentions of "Fiori iOS SDK". The approved One Voice product name is "SAP Cloud Platform SDK for iOS". There is no "Fiori iOS SDK".

Pls. also check other iOS tutorials for brand compliance.

Thanks,
Michael

**Comment by qualiture** [comment]
@KevinMuessig as I'm no longer in charge of the iOS tutorials, could you please have a look?

**Comment by KevinMuessig** [comment]
Hi @miffels 

thank you for your feedback, those are legacy tutorials which will be replaced with updated versions soon.

I will change the naming in the current version until the newest version is only.

Thank you
