### ISSUE TITLE
Create a Basic Node.js App

### ISSUE THREAD

**Issue by mblst** [SAPDocuments/Tutorials#4341]
Tutorial URL: https://developers.sap.com/tutorials/cp-node-create-basic-app.html

Please specify the step you are referring to

Step 1:The choco command didn't work on my Monsoon image. I could get around this issue because node.js was already installed on my Monsoon.

**Comment by maxstreifeneder** [comment]
Hi @mblst, 

I have no idea what Monsoon is? Choco would only work on Windows machines. 

Regards,
Max

**Comment by MichaelCzcz** [comment]
@maxstreifeneder Monsoon is landscape that provides virtual servers.

**Comment by maxstreifeneder** [comment]
thanks @MichaelCzcz! We can't provide any other recommendation than for Linux/Windows based machines and I'm sure that Monsoon also has some kind of Linux based OS underneath.
