### ISSUE TITLE
Deploy Your Node.js App with the Cloud Foundry CLI

### ISSUE THREAD

**Issue by mblst** [SAPDocuments/Tutorials#4342]
Tutorial URL: https://developers.sap.com/tutorials/cp-node-deploy-cf-cli.html

Please specify the step you are referring to

Step 1: On my Monsoon, I could not get the folder structure you depict in the tutorial. My 'node_modules' folder is always on the same level as the app folder.

Step 2: When I pushed the app, the push process download all the buildpacks. In the process, I get an error saying: "None of the buildpacks detected a compatible application
   Exit status 222"
Error staging application: An app was not successfully detected by any available buildpack

TIP: Use 'cf buildpacks' to see a list of supported buildpacks.
FAILED
I did 'cf buildpacks' but it is not clear which buildpack (if at all) caused the issue.
Result: The app could be deployed, but it never starts and keeps on running. On SCP, it has the status Started, but I cannot call it to see the UI.

**Comment by maxstreifeneder** [comment]
node_modules directory will be created on the level you have executed the npm install command. 
```npm install express``` in the **myapp** directory will also solve the buildpack problem. If not, please make sure that you execute ```cf push``` in the **node_tutorial** folder (where your manifest.yml is located).

**Comment by MichaelCzcz** [comment]
@mblst Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
