### ISSUE TITLE
Create Destination for SAP API Management Service

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#4347]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-create-destination.html

Unfortunately the Connection Check tells me "404 Not found". 

My URL is
https://c5246034trial-trial.apim1.hanatrial.ondemand.com

Not sure, if this is the problem, but additionally the Property "TrustAll" is not available anymore (you can set a checkmark "Use default JDK truststore" instead). 

Could you provide some help here, otherwise it doesn't make sense to continue with the tutorial. 

Best regards, 
Sebastian

**Comment by shilpavij** [comment]
Hello,

If you are not able to see from the dropdown, you can still add it. by just manually putting TrustAll.

Regards
Shilpa
![image](https://user-images.githubusercontent.com/44152823/70883031-ba3a7d80-1ff7-11ea-895c-ad1d4f6bc34a.png)

**Comment by shilpavij** [comment]
Please ignore the previous screenshot
![image](https://user-images.githubusercontent.com/44152823/70883169-1d2c1480-1ff8-11ea-8f5c-db159abe724c.png)

**Comment by MichaelCzcz** [comment]
@freilinger Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
