### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by amsapgit** [SAPDocuments/Tutorials#4356]
**Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html**

Hello... 
I'm new to iFlow and CPI and trying to learn from your blog but facing a challenge resolving an issue...

**Step 3: Add JSON to XML converter**
I followed all the steps and deployed the scenario but the "JSON to XML Converter" step is having an warning sign with the following message "Http Sender component may not pass Json message to JSON to XML Converter. JSON to XML converter supports JSON input only."

And when I execute the scenario, I received the following error message at the JSON to XML conversion step:
"com.sap.it.rt.adapter.http.api.exception.HttpResponseException: An internal server error occured: No type converter available to convert from type: null to the required type: java.io.InputStream with value null."

Please suggest.
Thanks so much,
Anirban

**Comment by gauthamkrishna-sap** [comment]
Hi Anirban,
Looks like there is some issue with the payload that you are sending from the postman client. Can you please ensure that it is a valid JSON? I suggest that you copy the code from the tutorial and try with it. 
Thanks & Best Regards,
Gautham

**Comment by MichaelCzcz** [comment]
@amsapgit Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
