### ISSUE TITLE
Set Up SAP Data Hub, Developer Edition

### ISSUE THREAD

**Issue by lolek24** [SAPDocuments/Tutorials#4357]
Tutorial URL: https://developers.sap.com/tutorials/datahub-docker-v2-setup.html

Please specify the step you are referring to Step 4: Run a Docker container (based on the image)
Some of the ports are disabled on my computer. It would be good to add information about this and how to deal with it. It helped me:
netsh int ipv4 show excludedportrange protocol=tcp
docker run -ti --publish 50701:50070 --name hdfs --hostname hdfs --net dev-net datahub run-hdfs

**Comment by MichaelCzcz** [comment]
@schneidertho any updates?

**Comment by MichaelCzcz** [comment]
@schneidertho  Can you please look into this issue and provide an update?

**Comment by MichaelCzcz** [comment]
@dimvor @roy-zhong Any updates?

**Comment by dimvor** [comment]
SAP Data Hub, Developer Edition will be removed completely from the platform therefore it should "solve" this ticket.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
