### ISSUE TITLE
HANA EXPRESS errors during installation 

### ISSUE THREAD

**Issue by voxron** [SAPDocuments/Tutorials#4358]
Hi all,
I' m new in HANA, and of course have not clear erros.
The most of that, how to prepare correct RHEL, to install HANA EXPRESS without any errors.
At my last time, I have error with XS components. I've attached screenshots from gui.
![hana1](https://user-images.githubusercontent.com/58906219/70862067-5147fc80-1f48-11ea-9dd7-f17463185233.png)
![hana2](https://user-images.githubusercontent.com/58906219/70862070-57d67400-1f48-11ea-87ab-4754bc4b01a9.png)

**Comment by thecodester** [comment]
Is this related to a specific tutorial?

**Comment by voxron** [comment]
> Is this related to a specific tutorial?

This is not specific relation. I've tried to install HANA EXPRESS on SLES, but has lot's of not understandable errors. 
I assume to try RHEL, it's almost ok. But XS is ... my brain :)

**Comment by thecodester** [comment]
I'm sorry you are having issues with installation. However, I think this is a more general question and you would have better answers by engaging the SAP Community or SAP Questions & Answers.

https://www.sap.com/community.html
https://answers.sap.com/index.html

I will close this issue for now.

**Comment by voxron** [comment]
Unfortunately in the SAP community, I don't have any response :(
