### ISSUE TITLE
Create a Simple Database Table for ABAP Environment

### ISSUE THREAD

**Issue by thecodester** [SAPDocuments/Tutorials#4359]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-create-table.html

Please specify the step you are referring to -- step 9 

a table with key as client will be requested. When I want to add multiple values, an Duplicate Key Error appears. It would probably be better to adapt the wording, so that it’s clear that one need to define an additional element as key.”

P.S.: I am opening issue for an external user.

**Comment by mervey45** [comment]
@thecodester I created following pull request for this issue: #4405
