### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by sreejithppsap** [SAPDocuments/Tutorials#4360]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html

Please specify the step you are referring to

I get the following error @ step 5 ->
Go back to the SAP Fiori launchpad homepage. The My Inbox tile shows one open task.

The OAuth token request to URL 'https://i034941trial.authentication.eu10.hana.ondemand.com?grant_type=client_credentials' failed with HTTP status code 403 (Forbidden) and response body '{"error":"Could not verify the provided CSRF token because your session was not found."}'
Log ID: ea7955a2-8455-455e-98c2-888af27bca9d
Determine EquipmentDec 13, 2019, 9:35:24 AM

**Comment by ArchanaShukla** [comment]
your session would have expired. Please login into incognito mode and try again.

**Comment by sreejithppsap** [comment]
I had already tried this. I get the same error in incognito mode too.

**Comment by ArchanaShukla** [comment]
(a) Can you open the Monitor Instances and send the error from execution log. (b) Hope you have given all the needed roles to your users from the setup section and also deployed the business rules successfully in your tenant.

**Comment by sreejithppsap** [comment]
I am not able to upload an image here....Will copy paste the execution log here :
"Determine Equipment" failed
Dec 18, 2019, 11:01:53 AM
Service endpoint:
BUSINESS_RULES
Error message:
The OAuth token request to URL 'https://i034941trial.authentication.eu10.hana.ondemand.com?grant_type=client_credentials' failed with HTTP status code 403 (Forbidden) and response body '{"error":"Could not verify the provided CSRF token because your session was not found."}'
"Determine Equipment" started
Dec 18, 2019, 11:01:14 AM
"Prepare Rules Input" completed successfully
Dec 18, 2019, 11:01:14 AM
"Prepare Rules Input" started
Dec 18, 2019, 11:01:14 AM
"Process Buddy List" completed successfully
Dec 18, 2019, 11:01:12 AM
"Process Buddy List" started
Dec 18, 2019, 11:01:12 AM
sreejith.p.p@sap.com started the workflow
Dec 18, 2019, 11:01:11 AM

**Comment by ArchanaShukla** [comment]
Were you able to go through this step?

**Comment by sreejithppsap** [comment]
I still get the same error
"Determine Equipment" failed
Jan 3, 2020, 2:27:26 PM
Service endpoint:BUSINESS_RULES
Error message:The OAuth token request to URL 'https://i034941trial.authentication.eu10.hana.ondemand.com?grant_type=client_credentials' failed with HTTP status code 403 (Forbidden) and response body '{"error":"Could not verify the provided CSRF token because your session was not found."}'

**Comment by ArchanaShukla** [comment]
Hope the issue is resolved as we do not see this issue any more in any other landscape. 
@thecodester - please close the issue

**Comment by thecodester** [comment]
@sreejithppsap Can you comment or close the issue?

**Comment by sreejithppsap** [comment]
[ImportError.zip](https://github.com/SAPDocuments/Tutorials/files/4085727/ImportError.zip)

Hi Archana,
       I tried the same again from step 1, but I get the following error @
Tutorial 2 of 5  Set Up Business Rules for Determining Equipment
Step 2: Import business rules
Error: “An error has occurred. Contact technical support.” 
Please see the attachment.
Thanks and Regards
Sreejith

**Comment by ArchanaShukla** [comment]
There was a similar issue earlier and it occurred only when the destination configuration for APIHub is not correct. Can you put a screenshot of destination for API Business Hub and also attach the browser developer traces.

**Comment by ArchanaShukla** [comment]
Please close the issue, as this seem to have resolved. 
Reason: The token URL was not entered correctly by while modelling the destination
