### ISSUE TITLE
Add a UI to Your Business Application

### ISSUE THREAD

**Issue by IObert** [SAPDocuments/Tutorials#4363]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-02-add-ui.html

Please specify the step you are referring to: Step 1

Hi René,

it seems like on small (but crucial) step is missing here. Users need to trigger a "[Build CDS](https://answers.sap.com/questions/12928738/cap-html5-destionation.html?childToView=12931864&answerPublished=true#answer-12931864)" before step 1. Otherwise, they won't be able to see endpoint in the "Current Project" list.

Can you please add this information?

**Comment by renejeglinsky** [comment]
Hi @IObert ,

I am trying to reproduce it. I think, by running the service in the first tutorial, it should have been built and be available.
But right now, I am having other difficulties running the service in the first place, so it's hard to validate right now :)
Nevertheless it doesn't harm mentioning it. So, I'll get back to you soon.

Regards,
René

**Comment by MichaelCzcz** [comment]
@renejeglinsky Any updates?

**Comment by renejeglinsky** [comment]
This tutorial is out of maintenance and already removed from the platform. This issue can be closed.
