### ISSUE TITLE
Configure Mobile Services in the iOS Assistant

### ISSUE THREAD

**Issue by sjsaha** [SAPDocuments/Tutorials#4365]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-scpms-teched18-01.html

Please specify the step you are referring to

The tutorial is no longer updated with cloud foundry version of Mobile Services

**Comment by KevinMuessig** [comment]
Hi @sjsaha 

thanks for the feedback but could you specify what you mean?

The tutorials will be switched from Neo to CF soon.

Thanks,

Kevin

**Comment by MichaelCzcz** [comment]
@sjsaha Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
