### ISSUE TITLE
Get to Know the ABAP RESTful Programming Model

### ISSUE THREAD

**Issue by baskart2112** [SAPDocuments/Tutorials#4366]
Explained about how the ABAP RESTful Programming Model is structured and how the development flow is organized.

**Comment by thecodester** [comment]
Who are you? Can you update your GitHub profile?

**Comment by thecodester** [comment]
And why do you erase the tutorial link in the issue!!??

**Comment by mervey45** [comment]
Hi @baskart2112 , 

didn't get your issue. Please create just one issue, for your whole feedback and paste the tutorial links as well. 

Thank you. 

Best regards, 
Merve

**Comment by baskart2112** [comment]
Hi, I just have given a comment on this tutorial that it has been explained well about how the ABAP RESTful Programming Model is structured and how the development flow is organized.
From this tutorial, we will understand the concept of the ABAP RESTful Programming Model.
