### ISSUE TITLE
Enhance Behavior With Action and Validation

### ISSUE THREAD

**Issue by baskart2112** [SAPDocuments/Tutorials#4368]
In Step 5, Check your result, it is written as Create a new travel booking with the booking status O. But the detailed steps to create a travel booking is missing. 
If the details are provided in the tutorial, it will be good for the end user to understand.

**Comment by mervey45** [comment]
Hi @baskart2112 ,

do you mean the creation of the entry of the persistence? If yes, this is already done here: https://developers.sap.com/tutorials/abap-environment-persistence.html 

If you mean the detail screen, then this is also there. You just need to select one entry and click on it.

Best regards, 
Merve

**Comment by baskart2112** [comment]
Hi Merve,

Thanks for your swift response.
I meant for step "5. Check your result.
The accept travel button appears, but this can take a few minutes. Create a new travel booking with the booking status O. O stands for open. Save your travel booking and you are able to accept your created travel booking." 
which is mentioned in the page https://developers.sap.com/tutorials/abap-environment-behavior-action.html. 
But the detailed steps of creating a travel booking is missing.  it will be good for end user if it would have been provided.
Thanks,
Baskar

**Comment by MichaelCzcz** [comment]
@baskart2112 Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
