### ISSUE TITLE
Develop a Fiori App Using the ABAP RESTful Programming Model (Managed Scenario)

### ISSUE THREAD

**Issue by baskart2112** [SAPDocuments/Tutorials#4369]
Actually  in the beginning of the tutorial, it is written as "In this tutorial, wherever XXX appears, use a number (e.g.   000)."  In many steps, we have to copy and paste the code snippet given in the   tutorial. So before these steps, it is written as "Replace your code   with following:" But inside the code snippet, some where XXX is there.  So if we forget to change replace this XXX with the changed value, then the   Save and Activation will fail.

So It will be good if a reminder to change XXX with the actual value in each place.
--

**Comment by mervey45** [comment]
Hi @baskart2112,

thank you for your feedback. We wrote this in the first step of the tutorial and explained it as well in the beginning. So this should be enough.  
@thecodester  Can we close this issue?


Thank you.

Best regards, 
Merve
