### ISSUE TITLE
Build a Business Application Using Node.js

### ISSUE THREAD

**Issue by C5269483** [SAPDocuments/Tutorials#4370]
**Mission URL:** https://developers.sap.com/mission.cp-starter-extensions-cap.html

**Landscape :** EU-AWS   Trial and US-East(VA) trial

**Generic Feedbacks:** 
1.	It would be good if all Prerequisite steps are mentioned in the main page itself. Currently these steps are on the right side of the page and users will miss to read these prerequisite steps.
2.	Good to have brief introduction on CAP model.

**Tutorial1. Step 1:**
Feedback: Not specified where the command should be run, Either in VS Code terminal or in cmd.

**Tutorial1. Step 3:**
Feedback: Bit explanation on the directory of the project would be good for the better understanding of the Project

**Tutorial1. Step 3, 4 and 10:** 
Feedback: One line explanation on the code would be nice.

**Tutorial1. Step4:**
Feedback:
•	Mention explicitly to select the created folder in the tree structure & then click on New File icon 
•	It would be good to have a screenshot attached for every step during creating the file structure for easy understanding & avoiding file conflicts

**Tutorial1. Step 7:**
Feedback: It should specify that the newly added element Jane Eyre should be visible **along with the previous data**

**Tutorial1. Step 8:**
Feedback: Screenshot of package.json should be added to verify how it should look like.
![cds](https://user-images.githubusercontent.com/39294341/70968978-bb83ad00-20c0-11ea-83d9-0e3d552d2956.jpg)

•	In pt 4 : Open SQLite and view the newly created database – **US Region**
The “my-bookshop.db” is getting created under db folder but user is unable to view in editor and unable to open the database file in sqlite.
![bookshopdb](https://user-images.githubusercontent.com/39294341/70968778-339da300-20c0-11ea-90a7-dea29d943052.png)
 

**Tutorial2. Step 1:**
Feedback: Before deployment, we have to stop CDS watch which is not mentioned in the document. Also need to specify change only to the CDS content.

**Tutorial2. Step 2:**
Feedback: If the log is cleared, specify an alternate method to fetch the URL- Like in the Cloud platform, under applications.
![route](https://user-images.githubusercontent.com/39294341/70969000-c6d6d880-20c0-11ea-83f0-dc4b837daac6.png)

**Comment by iwonahahn** [comment]
Hi,

Thank you for your feedback. We will review it and get back to you asap.

Best regards,
Iwona

**Comment by thecodester** [comment]
Since this was written, the prerequisites (in tutorial) are more prominently listed.
@iwonahahn  If the mission requires a set of prerequisites, we should list them in the first tutorial -- if necessary, have a separate introductory tutorial

**Comment by iwonahahn** [comment]
This issue can be closed. No further improvements are planned on the existing tutorials. Prereqs are now on top and other improvements were implemented yesterday with an additional update on both tutorials.
