### ISSUE TITLE
Create SAP SuccessFactors To Dos and Timesheet Card

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#4371]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-digitalexp-mobilecards-2-create.html

Save step is missing in the document.
After we change card status from ‘Development’ to ‘Productive’, (Step 3) we need to save and that step is missing in the document.

**Comment by jitendrakansal** [comment]
@NidhiMurkute Once you change the card status from "development" to "productive" , card status gets updated and you dont need to explicitly click "Save". 
We have taken this as a feedback and will improve the user experience in the Admin UI. 
Thanks for raising this to us.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved -- and involves a feature change, not issue with the tutorial -- so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
