### ISSUE TITLE
Configure Initial Setup for SAP Mobile Cards

### ISSUE THREAD

**Issue by abdeep** [SAPDocuments/Tutorials#4372]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-digitalexp-mobilecards-1-setup.html

Please specify the step you are referring to
1) Step 3: Create destination for SAP SuccessFactors sandbox
Scroll down and choose SuccessFactors My ToDos and select the Create Card Template icon. To proceed, You will be asked to enter the API Key.

Here at this step a screen shot is attached to inform user for how to get the API key. It would be good if you  provide the URL (https://api.sap.com/preferences) which  can be copied & paste in browser

**Comment by jitendrakansal** [comment]
@abdeep when you see the pop-up (https://developers.sap.com/tutorials/cp-starter-digitalexp-mobilecards-1-setup/_jcr_content.github-proxy.1573740358.file/img_14.png) to enter the APIKey, this is where you see the URL. You can copy the URL from there and paste in the browser.
