### ISSUE TITLE
Create SAP SuccessFactors To Dos and Timesheet Card

### ISSUE THREAD

**Issue by abdeep** [SAPDocuments/Tutorials#4373]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-digitalexp-mobilecards-2-create.html

Please specify the step you are referring to
Step 2: Create Timesheet card
Choose **Create a New Card** to display a user’s Time Sheet log for a given date

In Application tool tip is displayed as **Create Card Template**.  It will confue use whether we are creating a new card or template
[Create_Card_Template_Tool_tip.docx](https://github.com/SAPDocuments/Tutorials/files/3971419/Create_Card_Template_Tool_tip.docx)

**Comment by jitendrakansal** [comment]
I have shared this as a feedback to our development team.

**Comment by thecodester** [comment]
I am closing since this is not related to our tutorials.
