### ISSUE TITLE
Create Table Persistence and Generate Data

### ISSUE THREAD

**Issue by abdeep** [SAPDocuments/Tutorials#4374]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-persistence.html

Please specify the step you are referring to
Step 1: Create ABAP package
4. Click Finish to create your transport request

Request Description is mandatory
[Request Description is mandatory.docx](https://github.com/SAPDocuments/Tutorials/files/3971484/Request.Description.is.mandatory.docx)
 field in **New ABAP Package** wizard.
You need to update the Document with correct screen shot(Where it shows Request Description as mandatory) & Step to enter the value for 'Request Description' field

**Comment by mervey45** [comment]
Hi @abdeep ,

this will be updated. 

@thecodester I created following pull request: #4492. Can you merge it and close this ticket?

Thank you. 

Best regards, 
Merve
