### ISSUE TITLE
Create Table Persistence and Generate Data

### ISSUE THREAD

**Issue by abdeep** [SAPDocuments/Tutorials#4375]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-persistence.html

Please specify the step you are referring to
Step 3: Create ABAP class
4. Replace your code with following
In the give code there is a variable GET TIME STAMP FIELD DATA for "*   read current timestamp defined but i didn't see the usage of this variable in further coding

**Comment by mervey45** [comment]
Hi @abdeep ,

I'll update this. 

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @abdeep ,

@thecodester I created following pull request: #4492. Can you merge it and close this ticket?

Thank you. 

Best regards, 
Merve
