### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by abdeep** [SAPDocuments/Tutorials#4376]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-data-model.html

Please specify the step you are referring to
Step 2: Create projection view for travel
5. Define root view entity for ZC_TRAVEL_M_XXX.
6. You result should look like this. Replace your code with following:

Step 3: Create service definition
2. Create a new service definition:
Name: ZUI_C_TRAVEL_M_XXX
4. Replace your code with following:

Step 4: Create service binding
2.Create a new service binding:
Name: ZUI_C_TRAVEL_M_XXX

Even though in the beginning of this tutorial its mentioned  as **In this tutorial, wherever XXX appears, use a number (e.g. 000).** . It is better to remind user in steps mentioned above (wherever its mentioned to do the code changes & create objects ) to replace 'XXX' with his own group number.

**Comment by mervey45** [comment]
Hi @abdeep ,

I already have this in the second tutorial of the grouping: https://developers.sap.com/tutorials/abap-environment-persistence.html 

Best regards, 
Merve

**Comment by mervey45** [comment]
@thecodester  We can close this issue.
