### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by abdeep** [SAPDocuments/Tutorials#4377]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-data-model.html

Please specify the step you are referring to
Step 1: Define CDS-based travel data model
6. You result should look like this. Replace your code with following:

Step 2: Create projection view for travel
6. You result should look like this. Replace your code with following:

Typo Error:  **Your** in place of you

**Comment by mervey45** [comment]
Hi abdeep.

I'll update this. 

Best regards, 
Merve
