### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by abdeep** [SAPDocuments/Tutorials#4378]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-behavior.html

Please specify the step you are referring to
4. Replace your code with following.

Even though in the beginning of this tutorial its mentioned as In this tutorial, wherever XXX appears, use a number (e.g. 000). . It is better to remind user in steps  (wherever its mentioned to do the code changes & create objects ) to replace 'XXX' with his own group number.

**Comment by mervey45** [comment]
Hi @abdeep ,

we already have this in the second tutorial of this grouping: https://developers.sap.com/tutorials/abap-environment-persistence.html

Best regards, 
Merve

**Comment by mervey45** [comment]
@thecodester  We can close this issue.
