### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by abdeep** [SAPDocuments/Tutorials#4379]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-behavior.html

Please specify the step you are referring to
5. Save and activate.

When we activate we get a warning message "warning message "Class "ZCL_BP_I_TRAVEL_M_ABP" does not exist."
It would be good to mention the reason for warning in the user tutorial

**Comment by mervey45** [comment]
Hi @abdeep ,

I'll update this tutorial. 

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi

@thecodester I created following pull request: #4492. Can you merge it and close this ticket?

Thank you. 

Best regards, 
Merve
