### ISSUE TITLE
Set Up Process Visibility to Track Employee Onboarding Workflow

### ISSUE THREAD

**Issue by sreejithppsap** [SAPDocuments/Tutorials#4396]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-4-visibility.html

Please specify the step you are referring to
4 Set Up Process Visibility to Track Employee Onboarding Workflow - 
Step 1: Create a business scenario - 3. Enter Name as Employee Onboarding, any Description of your choice, and click Save. 
it is mentioned as "The business scenario will be created with DRAFT status.", but the screenshot shows the status as 'ACTIVE'. This is confusing for the end user. Please provide valid screenshot.

**Comment by ArchanaShukla** [comment]
Yes that was a recent change. Will update the tutorial.

**Comment by ArchanaShukla** [comment]
This was a bug and it is fixed now. New scenario will be created with DRAFT status only

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
