### ISSUE TITLE
Set Up a Workflow With Extended Employee Onboarding

### ISSUE THREAD

**Issue by sreejithppsap** [SAPDocuments/Tutorials#4397]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html

Please specify the step you are referring to
Tutorial 3, Step 1
3. Set Up a Workflow With Extended Employee Onboarding, Step 1. 
1.	In your web browser, open SAP Cloud Platform Trial cockpit.
2.	Choose Launch SAP Web IDE.

For new users, Web IDE Full-Stack will not be enabled.  User will see a message saying "SAP  Web IDE Full-Stack will not be enabled". Should this be included for the sake of users executing for the first time? Please see the attachment,

![After_Step_3_point2](https://user-images.githubusercontent.com/58926896/71061725-b5f49880-218e-11ea-8fab-4401bdfbe168.jpg)

**Comment by ArchanaShukla** [comment]
Need to check this. Looks like a changed behavior from trial WebIDE.

**Comment by ArchanaShukla** [comment]
I have incorporated this in the tutorial.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
