### ISSUE TITLE
Set up SAP HANA, express edition on Amazon Web Services (XS Advanced)

### ISSUE THREAD

**Issue by davidsmith288** [SAPDocuments/Tutorials#4398]
Tutorial URL: https://developers.sap.com/tutorials/hxe-xsa-aws-setup.html

In step 9, the guide  mentions giving IP access to ports 51000 - 51500, but it does not describe how to do this

Later it says 
You will also need to add 3 ranges (highlighted to the security group) to be able to be able to access the XSA services (like SAP Web IDE). Open your AWS console and add the highlighted ports to the roles created earlier

But, it does not clarify which 3 ranges to add.
It also refers to roles created earlier, however roles are not created earlier in this tutorial

**Comment by jarjarbentley** [comment]
In AWS Console open security group my-security-group and go to Inbound and click on Edit to Add Rule and add the following ports:
51000-51500
39030-39033
53075
--See attachments
[security group aws 2.pdf](https://github.com/SAPDocuments/Tutorials/files/4118722/security.group.aws.2.pdf)
[security group AWS 1.pdf](https://github.com/SAPDocuments/Tutorials/files/4118723/security.group.AWS.1.pdf)
