### ISSUE TITLE
Make Available the Process Visibility Applications Using SAP Fiori Launchpad

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#4399]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-processvisibility-setup-flp.html

Please specify the step you are referring to Step 4: Build and deploy project

The deplying faild at my exercise, i made it two times, have you an Idea why?

Log:
13:46:50 (Executor)   adding: mta_archives/FLPConfigForPVS_0.0.1.mtar (deflated 0%)
13:46:54 (mtaBuildTask) Build of "FLPConfigForPVS" completed.
13:48:00 (DeploymentToCF) Deployment of the "FLPConfigForPVS" project started.
13:48:00 (DeployService) Deployment in progress.
13:48:00 (DeployService) Deploying /FLPConfigForPVS/mta_archives/FLPConfigForPVS_0.0.1.mtar to endpoint: https://api.cf.eu10.hana.ondemand.com, organization: S0007042004trial_trial, space: dev.
13:48:40 (DeployService) Target: https://deploy-service.cfapps.eu10.hana.ondemand.com/slprot/S0007042004trial_trial/dev/slpPreparing to deploy /FLPConfigForPVS/mta_archives/FLPConfigForPVS_0.0.1.mtarPrepare deployment filesChecking if there are conflicting processesFound 1 conflicting processesAborting process 18a81aa3-204a-11ea-a57e-eeee0a80fec5Uploading mtar archiveStarting deploymentDeploying in org "S0007042004trial_trial" and space "dev"Detected MTA schema version: "3"No deployed MTA detected - this is initial deploymentDetected new MTA version: "0.0.1"Processing service "FLPConfigForPVS_html5_repo_runtime"...Creating service "FLPConfigForPVS_html5_repo_runtime" from MTA resource "FLPConfigForPVS_html5_repo_runtime"...Processing service "portal_resources_FLPConfigForPVS"...Processing service "uaa_FLPConfigForPVS"...Creating service "portal_resources_FLPConfigForPVS" from MTA resource "portal_resources_FLPConfigForPVS"...Setting service "uaa_FLPConfigForPVS" parameters from "xs-security.json"Creating service "uaa_FLPConfigForPVS" from MTA resource "uaa_FLPConfigForPVS"...Service operation failed: Controller operation failed: 403 Updating service "FLPConfigForPVS_html5_repo_runtime" failed: Forbidden: Error creating service "FLPConfigForPVS_html5_repo_runtime" from offering "html5-apps-repo" and plan "app-runtime": You are not authorized to perform the requested action Service operation failed: Controller operation failed: 404 Updating service "portal_resources_FLPConfigForPVS" failed: Not Found: Error creating service "portal_resources_FLPConfigForPVS" from offering "portal" and plan "standard": Could not create service instance "portal_resources_FLPConfigForPVS". Service plan "standard" from service offering "portal" was not found. Service operation failed: Controller operation failed: 403 Updating service "uaa_FLPConfigForPVS" failed: Forbidden: Error creating service "uaa_FLPConfigForPVS" from offering "xsuaa" and plan "application": You are not authorized to perform the requested action To download logs of the process, use the multi-target application plug-in for the Cloud Foundry CLI command "cf dmol -i ad31310e-2194-11ea-9991-eeee0a88e0f1" directly in your Cloud Foundry space.For more information see https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/e93b231895b64cbc9221a62953563a6f.html.Job failed.
13:48:40 (DeploymentToCF) Deployment of the "FLPConfigForPVS" project failed.(Response state is FAILED)

**Comment by MichaelCzcz** [comment]
@Deeksha-R any updates?

**Comment by Deeksha-R** [comment]
"portal_resources_FLPConfigForPVS" from offering "portal" and plan "standard"

have you followed the instructions provided in the prerequisite tutorial where the plan to be selected is "Lite"? here is the link: https://developers.sap.com/tutorials/cp-cf-processvisibility-setup-serviceinstance.html

@MichaelCzcz it might be due to the selection of a wrong plan during service instance creation.

**Comment by marcobuescher** [comment]
Yes... :)

**Comment by Deeksha-R** [comment]
@marcobuescher Did the correction of your service plan help you in resolving the issue?

**Comment by marcobuescher** [comment]
No, that means I had the right service Plan.... sry.

**Comment by Deeksha-R** [comment]
@marcobuescher can you please tell me if you have the entitlement to the Portal service?

If you do, then can you use the following command "cf dmol -i ad31310e-2194-11ea-9991-eeee0a88e0f1" and download the log details that you receive, then send the log to us?

**Comment by MichaelCzcz** [comment]
@marcobuescher Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
