### ISSUE TITLE
Service cannot be reached

### ISSUE THREAD

**Issue by AlexandreCordaJunior** [SAPDocuments/Tutorials#4403]
I'm trying to complete the tutorial, but I can't make the app work, it falls in this page with this message
![Captura de Tela (1)](https://user-images.githubusercontent.com/48927666/71112876-3d500500-21ab-11ea-87aa-99a642906236.png)

**Comment by thecodester** [comment]
What tutorial is this part of?

P.S.: When you click Provide Feedback, we automatically generate all the informarmation we need to help you. No need to delete. :-)

**Comment by thecodester** [comment]
I will close if this is a duplicate.
