### ISSUE TITLE
Learn about OData Fundamentals

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#4411]
Tutorial URL: https://developers.sap.com/tutorials/odata-01-intro-origins.html

Please specify the step you are referring to: 1 "Submit" button: all three options result in a 'Technical Error'. 

Shouldn't at least one option be correct?

**Comment by thecodester** [comment]
PLease try again ... it works for me now

**Comment by greg2git** [comment]
thx for checking and making sure it works. will reopen if it starts generating technical errors again.
