### ISSUE TITLE
Create an Account on the Gateway Demo System

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#4412]
Tutorial URL: https://developers.sap.com/tutorials/gateway-demo-signup.html

Please specify the step you are referring to password reset

the password reset email doesn't get sent immediately, but other sap.com access gets invalidated, e.g. with this message:
"500
We’re sorry, but something went wrong.
If you are the application owner check the logs for more information."

**Comment by thecodester** [comment]
@akula86 Previous DJ said that you (your team) is responsible for this. Is that so?

**Comment by MichaelCzcz** [comment]
@qmacro Could you please take over? Thank you.

**Comment by qmacro** [comment]
I can but resolution will only come when I find out how the system works, currently I have no idea, need some handover documents first :-)

**Comment by qmacro** [comment]
Update: I have no access myself, but have alerted the system owner and asked them to take a look.

**Comment by greg2git** [comment]
thx for the followup.

**Comment by qmacro** [comment]
Hi @greg2git - I understand that this has now been addressed and the internal server error has been rectified.
