### ISSUE TITLE
Create a Global ABAP Class

### ISSUE THREAD

**Issue by zazawang-789** [SAPDocuments/Tutorials#4416]
SNWD_BPA and other table ara empty, someone could provide the way to genetating data in these tables?  I tried tcode:SEPM_DG, but not work for these tables.

**Comment by thecodester** [comment]
Does this relate to a specific tutorial?

**Comment by zazawang-789** [comment]
> Does this relate to a specific tutorial?

Yes, it`s :Get Started with ABAP Development Tutorial 6 of 8

**Comment by zazawang-789** [comment]
I think Problem solved, I should add numbers in Set to Invoiced&Set to Delivered in 'Purchase Order' and 'Sales Orders' tabs. not only 'basic settings'.  than the corrspanding tables will be filled.
Thanks anyway.
