### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by Demonium** [SAPDocuments/Tutorials#4419]
Tutorial URL: https://developers.sap.com/tutorials/xsa-create-user-provided-anonymous-service.html

Please specify the step you are referring to Step 5

After following all steps I'm getting the error below when building 

> 22:16:04 (Builder) Build of "/HANA_APP/db" started.
22:16:08 (DIBuild) Build of "/HANA_APP/db" in progress.
22:16:09 (DIBuild) Service provisioning for module: '/db'Service instance 'XSA_DEV-cwkj3feeoqey6i9a-HANA_APP-hdi_db' for resource 'XSA_DEV-cwkj3feeoqey6i9a-HANA_APP-hdi_db' already exists, no operation will be performed.[INFO] Injecting source code into builder...[INFO] Source code injection finished[INFO] ------------------------------------------------------------------------Your module contains a package.json file, it will be used for the build.up to date in 0.469s
22:16:11 (DIBuild) > deploy@ start /hana/shared/HXE/xs/controller_data/executionagent/executionroot/23541851-60af-48f7-a0e4-67ed0ddeba4e/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-1019994024488284778/db> node node_modules/@sap/hdi-deploy/deploy.js@sap/hdi-deploy, version 3.10.0 (mode default), server version 2.00.040.00.1553674765 (2.0.40.0), node version 8.15.1, HDI version 2, container API version 44No ignore file at /hana/shared/HXE/xs/controller_data/executionagent/executionroot/23541851-60af-48f7-a0e4-67ed0ddeba4e/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-1019994024488284778/db/.hdiignore.Collecting files...Collecting files... ok (0s 4ms)2 directories collected6 files collected0 reusable modules collectedTarget service: XSA_DEV-cwkj3feeoqey6i9a-HANA_APP-hdi_dbSession variable APPLICATION is set to "SAP_HDI/development/HANAExpress".Previous build with request ID 273 finished at 2019-12-26 21:15:31.725768000 with status Finished and message: Make failed (7 errors, 2 warnings): tried to deploy 3 files, undeploy 4 files, redeploy 0 dependent files.Processing revoke files...Processing revoke files... ok (0s 0ms)Processing grants files...Processing grants files... ok (0s 0ms)Preprocessing files...Preprocessing files... ok (0s 0ms)Connecting to the container "DB"...Connecting to the container "DB"... ok (0s 17ms)Locking the container "DB"...Locking the container "DB"... ok (0s 84ms)Synchronizing files with the container "DB"...Synchronizing files with the container "DB"... ok (0s 398ms)3 modified or added files are scheduled for deploy based on delta detection4 deleted files are scheduled for undeploy based on delta detection (filtered by undeploy whitelist)0 files are scheduled for deploy based on explicit specification0 files are scheduled for undeploy based on explicit specificationDeploying to the container "DB"... Starting make in the container "DB" with 3 files to deploy, 4 files to undeploy...   Disabling table replication for the container schema "DB"...   Disabling table replication for the container schema "DB"... ok  (0s 66ms)  Migrating libraries...   Migrating libraries... ok  (0s 7ms)  Making...    Preparing...    Preparing the make transaction...    Deploying the namespace file "src/.hdinamespace"...    Deploying the namespace file "src/.hdinamespace"... ok  (0s 12ms)   Adding "src/data/PurchaseOrder.hdbcds" for deploy...    Adding "src/data/PurchaseOrder.hdbcds" for deploy... ok  (0s 9ms)   Adding "src/data/load.hdbtabledata" for deploy...    Adding "src/data/load.hdbtabledata" for deploy... ok  (0s 0ms)   Adding "src/time_tables/M_TIME_DIMENSION.hdbcds" for undeploy...    Adding "src/time_tables/M_TIME_DIMENSION.hdbcds" for undeploy... ok  (0s 0ms)   Adding "src/time_tables/M_TIME_DIMENSION_MONTH.hdbcds" for undeploy...    Adding "src/time_tables/M_TIME_DIMENSION_MONTH.hdbcds" for undeploy... ok  (0s 0ms)   Adding "src/time_tables/M_TIME_DIMENSION_WEEK.hdbcds" for undeploy...    Adding "src/time_tables/M_TIME_DIMENSION_WEEK.hdbcds" for undeploy... ok  (0s 0ms)   Adding "src/time_tables/M_TIME_DIMENSION_YEAR.hdbcds" for undeploy...    Adding "src/time_tables/M_TIME_DIMENSION_YEAR.hdbcds" for undeploy... ok  (0s 0ms)   Readding "src/data/header.csv" for deploy...    Readding "src/data/header.csv" for deploy... ok  (0s 1ms)   Readding "src/data/item.csv" for deploy...    Readding "src/data/item.csv" for deploy... ok  (0s 1ms)   Preparing... ok  (0s 139ms)   Preparing the make transaction... ok  (0s 153ms)   Calculating dependencies...     Expanding...      Expanding "src/data/load.hdbtabledata"...      Expanding "src/data/load.hdbtabledata"... ok  (0s 2ms)    Expanding... ok  (0s 19ms)    Precompiling...      Precompiling "src/data/PurchaseOrder.hdbcds"...      Precompiling "src/data/header.csv"...      Precompiling "src/data/header.csv"... ok  (0s 11ms)     Precompiling "src/data/item.csv"...      Precompiling "src/data/PurchaseOrder.hdbcds"... ok  (0s 12ms)     Precompiling "src/data/load.hdbtabledata"...      Precompiling "src/data/load.hdbtabledata"... ok  (0s 0ms)     Precompiling "src/data/load.hdbtabledata$0.expand"...       Expanded from "src/data/load.hdbtabledata"       Warning: com.sap.hana.di.tabledata: No "include_filter" is specified; it's strongly recommended to define an "include_filter" to also allow other table imports into the table; if no other table imports are intended, please specify at least an empty "include_filter":[] in the  "import_settings" section [8251576]        at "src/data/load.hdbtabledata" (3:13)     Precompiling "src/data/load.hdbtabledata$0.expand"... ok  (0s 1ms)     Precompiling "src/data/load.hdbtabledata$1.expand"...       Expanded from "src/data/load.hdbtabledata"      Precompiling "src/data/item.csv"... ok  (0s 1ms)      Warning: com.sap.hana.di.tabledata: No "include_filter" is specified; it's strongly recommended to define an "include_filter" to also allow other table imports into the table; if no other table imports are intended, please specify at least an empty "include_filter":[] in the  "import_settings" section [8251576]        at "src/data/load.hdbtabledata" (43:1)     Precompiling "src/data/load.hdbtabledata$1.expand"... ok  (0s 0ms)    Precompiling... ok  (0s 33ms)    Merging...      Merging "src/data/PurchaseOrder.hdbcds"...      Merging "src/data/PurchaseOrder.hdbcds"... ok  (0s 0ms)     Precompiling "$cds.merge/HANA_APP.db.src.data::PurchaseOrder" (merged)...       Merged from "src/data/PurchaseOrder.hdbcds"      Precompiling "$cds.merge/HANA_APP.db.src.data::PurchaseOrder" (merged)... ok  (0s 11ms)    Merging... ok  (0s 81ms)    Error: The file requires "db://PurchaseOrder.Header" which is not provided by any file [8212001]      at "src/data/load.hdbtabledata$0.expand" (0:0)     Expanded from "src/data/load.hdbtabledata"     Error: The file requires "db://PurchaseOrder.Item" which is not provided by any file [8212001]      at "src/data/load.hdbtabledata$1.expand" (0:0)     Expanded from "src/data/load.hdbtabledata"     Error: The file requires "tabledata.source://header.csv" which is not provided by any file [8212001]      at "src/data/load.hdbtabledata$0.expand" (0:0)     Expanded from "src/data/load.hdbtabledata"     Error: The file requires "tabledata.source://item.csv" which is not provided by any file [8212001]      at "src/data/load.hdbtabledata$1.expand" (0:0)     Expanded from "src/data/load.hdbtabledata"     Error: Could not compose a consistent make graph [8212012]   Error: Calculating dependencies... failed [8212108]   Make failed (7 errors, 2 warnings): tried to deploy 3 files, undeploy 4 files, redeploy 0 dependent files   Error: Making... failed [8211605] Error: Starting make in the container "DB" with 3 files to deploy, 4 files to undeploy... failed [8214168]Deployment to container DB failed - error: HDI make failed [Deployment ID: none].Error: HDI make failed(1s 689ms)npm ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! deploy@ start: `node node_modules/@sap/hdi-deploy/deploy.js`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the deploy@ start script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.npm ERR! A complete log of this run can be found in:npm ERR!     /hana/shared/HXE/xs/controller_data/executionagent/executionroot/23541851-60af-48f7-a0e4-67ed0ddeba4e/app/META-INF/cache/node8.15/.npm/_logs/2019-12-26T21_16_11_164Z-debug.log
22:16:11 (Builder) Build of /HANA_APP/db failed.

**Comment by jungsap** [comment]
These seem to be the main errors from thsi log:

Error: The file requires "db://PurchaseOrder.Header" which is not provided by any file [8212001] at "src/data/load.hdbtabledata$0.expand" (0:0) Expanded from "src/data/load.hdbtabledata" Error: The file requires "db://PurchaseOrder.Item" which is not provided by any file [8212001] at "src/data/load.hdbtabledata$1.expand" (0:0) Expanded from "src/data/load.hdbtabledata" Error: The file requires "tabledata.source://header.csv" which is not provided by any file [8212001] at "src/data/load.hdbtabledata$0.expand" (0:0) Expanded from "src/data/load.hdbtabledata" Error: The file requires "tabledata.source://item.csv" which is not provided by any file [8212001] at "src/data/load.hdbtabledata$1.expand" (0:0) Expanded from "src/data/load.hdbtabledata"

These errors would seem to be coming from an earlier part of the tutorial than what you referred to in your issue:
https://developers.sap.com/tutorials/xsa-hdi-module.html

Did you complete this earlier part of the tutorial successfully?  Could it be that you are missing parts from this earlier part of the tutorial?  Perhaps you could post an image of what your project structure under the db module looks like?

**Comment by MichaelCzcz** [comment]
@Demonium Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
