### ISSUE TITLE
Tutorial Mission "Build a Single Page Application using UI5 Web Components for React" -> set steps to "Done" and submitting answers does not work

### ISSUE THREAD

**Issue by pfefferf** [SAPDocuments/Tutorials#4420]
For Tutorial "Build a Single Page Application using UI5 Web Components for React" the "Done" setting for steps does not work. It is not possible to submit answers too.

Valid for all tutorials part of that mission:
https://developers.sap.com/mission.react-spa.html

**Comment by thecodester** [comment]
I have opened up the first tutorial and am able to click Done and to answer the question at the end. Can you try again?

**Comment by pfefferf** [comment]
Still having the issue. Tried with Chrome, Firefox, Edge (based on Chromium). Always with cleared cache. Browser Versions, e.g. Chrome 79.0.3945.88

Console log with some errors:
![image](https://user-images.githubusercontent.com/9888617/71555348-8285f980-2a2b-11ea-97cd-d48fdcb6dc35.png)

**Comment by thecodester** [comment]
And you are logged in?

I don't think the errors are related to the answering of questions. I will check with colleagues.

**Comment by pfefferf** [comment]
Yes, I am logged in.

**Comment by pfefferf** [comment]
One additional information: 
Seems like a general issue, cause I have the problem for other tutorials too.

Maybe due to the errors occuring during page loading something does not get applied well. For instance when I am on the mission page I can see the header of the page with some links and my profile pic, etc.. Navigating to a specific tutorial page (there the errors occur), I just get a black header.
![image](https://user-images.githubusercontent.com/9888617/71555778-cda20b80-2a2f-11ea-9b6f-c7fa434b134b.png)

Clicking on Done just navigates to the top of the page (due to the hash navigation). https://developers.sap.com/tutorials/ui5-webcomponents-react-introduction.html# is the link called by pressing Done.

**Comment by thecodester** [comment]
That is standard behavior if you are not logged in (i.e., link with hash taking you to the top). So I would imagine there is some login problem -- though don't know why the header would be black.

On the tutorial page there is supposed to be 2 navigation bars -- the one for the entire developers.sap.com site, and then the one for the tutorials (that says Mission / Tutorial). Do you get both?

Can you log into sap.com and see everything OK -- and that you are logged in?

**Comment by pfefferf** [comment]
As said, I am logged in. I logged off, logged in again now -> same behavior

**Comment by thecodester** [comment]
I understand ... I'm trying to diagnose.

On the tutorial page there is supposed to be 2 navigation bars -- the one for the entire developers.sap.com site, and then the one for the tutorials (that says Mission / Tutorial). Do you get both?

Can you log into sap.com and see everything OK -- and that you are logged in?

**Comment by pfefferf** [comment]
That is what I get when I am on the "mission" page:
![image](https://user-images.githubusercontent.com/9888617/71556576-e5cb5800-2a3a-11ea-82f6-bd2975ad9497.png)

On the tutorial page I just get what I have posted already above.

And yes, I logged into sap.com (and log off and log in as said above already).

**Comment by thecodester** [comment]
Can you try to clear your cache and try again?

**Comment by pfefferf** [comment]
As written already above I tried it with a cleared cache (in all three browers). So no, it is not such a "beginner-error" from my side ;-)
