### ISSUE TITLE
Add Custom Logic to Your Service

### ISSUE THREAD

**Issue by agl-phenr** [SAPDocuments/Tutorials#4425]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-04-custom-logic.html

Please specify the step you are referring to step 02 - Add custom code.

Web IDE editor highlights a couple of errors with class CloudLoggerFactory:

- JAVA: the type org.slf4j.Logger cannot be resolved. It´s indirectly referenced from required .class files
- JAVA: the method getLogger(String) from the type CloudLoggerFactory refers to the missing type Logger

Could someone help me out? 

Thanks a lot
Pietro
![errors](https://user-images.githubusercontent.com/42214365/71671568-445e4200-2d6b-11ea-8ea1-614afc633c70.png)
[OrdersService.zip](https://github.com/SAPDocuments/Tutorials/files/4016132/OrdersService.zip)

**Comment by renejeglinsky** [comment]
Hi Pietro,

I am sorry, I can't reproduce these errors. And from what I see in your file, I think you are using exactly what is in the tutorial, right?
Could you try again today? Maybe it was a temporary issue. Let's give it a try, please.

Regards,
René

**Comment by agl-phenr** [comment]
Hi @renejeglinsky ,

I tried it out again and sounds like no issue anymore. Thus, I close it.
Thanks a lot for the prompt help :)

Pietro
