### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by topherhoffman** [SAPDocuments/Tutorials#4426]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Please specify the step you are referring to Step 5.3 - Namespace is a required field.  There are no instructions on what to put in for the namespace.

**Step 3**
```
Provide following information:

    Module Name: TRAVEL_APP_XXX
    Title: TRAVEL_APP_XXX

Click Next.
```
Tutorial Guide Picture:
https://developers.sap.com/tutorials/abap-environment-deploy-cf-production/_jcr_content.github-proxy.1576681816.file/module2.png

Current Environment: 
https://gyazo.com/72a59e96d2bea39f879bc6bce857049d

**Comment by mervey45** [comment]
Hi @topherhoffman ,

with which ABAP system have you been trying this tutorial? With your trial user? If you use your trial user, then you don't need any namespace. Otherwise, you can type in anything you want as a namespace.
@thecodester We can close this issue.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
