### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by topherhoffman** [SAPDocuments/Tutorials#4427]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Please specify the step you are referring to
### Incorrect Instructions

**Step 9: Create SAP Fiori launchpad site module**

> 9.1 Open SAP Web IDE and right-click on your project MTA_Project_XXX and select Build > SAP Fiori Launchpad Site Module.

The Instructions and the screenshot do not match. The Instructions should be 
>Open SAP Web IDE and right-click on your project MTA_Project_XXX and select **New** > SAP Fiori Launchpad Site Module.

**Picture in the Instructions:** 
https://developers.sap.com/tutorials/abap-environment-deploy-cf-production/_jcr_content.github-proxy.1576681816.file/site.png

**Reason for change:** 
There is no option for SAP Fiori Launchpad Site Module under Build. (See Link for Picture) 
https://gyazo.com/d489c086785c046d8b59f319e403efa1

However it is there under New
https://gyazo.com/e58e817c10f125d54e31aeb02bf37382

**Comment by mervey45** [comment]
Hi @topherhoffman,

if you are doing this tutorial with your trial user, then you don't need to fill in anything for the namespace. Otherwise, you can fill in anything you want. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
@topherhoffman Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
