### ISSUE TITLE
Get Started with SAP Cloud Platform Rapid Application Development by Mendix

### ISSUE THREAD

**Issue by Chuergo** [SAPDocuments/Tutorials#4429]
Tutorial URL: https://developers.sap.com/tutorials/mendix-onboarding.html

A customer raised a few issues when trying to complete this tutorial on trial. I checked with Ohad Navon and it seems Mendix has not yet integrated our hana trial completely, so the tutorial does not work. Mendix is working on this and Ohad will advise when it is complete. Should we in the meantime add a note stating that this tutorial cannot be completed on trial?

I have added the error screenshots sent by the user, unfortunately the quality is not very good. If you want more information on the issues, please let me know and I can forward the email.

Also, a few other changes are required:
1. The screenshots seem to be updated. We received a screenshot from the user of the “Create Development” window and it does not match the screenshot in the tutorial (step 5). 
2. Steps 1-3 are outdated since the launch of the new trial welcome page in October.

Thanks,
Ceci

![error1](https://user-images.githubusercontent.com/39368137/71715318-4ed31700-2e11-11ea-9b0f-f7e321f6592d.png)
![error2](https://user-images.githubusercontent.com/39368137/71715319-4f6bad80-2e11-11ea-838a-231ffd8e5108.png)
![error3](https://user-images.githubusercontent.com/39368137/71715320-4f6bad80-2e11-11ea-9adc-b02ab1149dcd.png)
![error4](https://user-images.githubusercontent.com/39368137/71715321-4f6bad80-2e11-11ea-9564-df07c12ae04d.png)

**Comment by MichaelCzcz** [comment]
@Paolaufer @ShiraManas Could you please look into this and provide an update? Thank you.

**Comment by ShiraManas** [comment]
Hi Ceci,
I have updated the tutorial with Ohad Navon. 

- The screenshots are now up-to-date and the instructions have been updated. 

- We added the domain and database that should be used when choosing the Cloud Foundry environment. 

- We updated Steps 1-3 to match the new trial welcome page. Please ask the customer to try again with the updated tutorial.

Thanks,
Shira
