### ISSUE TITLE
Installing SAP HANA HDB Client (Linux)

### ISSUE THREAD

**Issue by eralper** [SAPDocuments/Tutorials#4430]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-hdb-client-linux.html

Please specify the step you are referring to

At Step 2.2 the code is using a file named hdb_client_linux_x84_64.tgz with a wrong typo
It should be hdb_client_linux_x86_64.tgz

**Comment by JCurrie27** [comment]
Thanks for communicating the typo -- the tutorial has been corrected and republished.
