### ISSUE TITLE
Service cannot be reached 404

### ISSUE THREAD

**Issue by Waltersen1971** [SAPDocuments/Tutorials#4432]
Hello,

the tutorial is:

https://developers.sap.com/tutorials/cp-portal-cloud-foundry-webdynpro-app.html step  # 10.

I have created the connection, which gives result 307 redirected when tested.
I can also connect with my user (which is used in the connection) to the backend without any problems.

The app tile  is there, but when I click on it there comes the error above. In issue #4403  seems the same to be happen, there is also a screenshot. And #4255 seems also to be the same topic.  

Thanks in advance, it is the last step to finish the mission.
Also have a nice weekend

**Comment by LindsayBert** [comment]
Hi

This seems to be a bug - I think it's best to open a ticket and see if the problem can be solved

Thanks 
Lindsay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by Waltersen1971** [comment]
Today it worked.
