### ISSUE TITLE
Add SAP Web Analytics Tracking Snippet

### ISSUE THREAD

**Issue by superwangnan** [SAPDocuments/Tutorials#4434]
Tutorial URL: https://developers.sap.com/tutorials/cp-webanalytics-add-tracking-snippet.html

Please specify the step you are referring to

I got following error, how to overcome it?
![image](https://user-images.githubusercontent.com/20192234/71759784-46e8a500-2eed-11ea-896a-6a470d4f8cef.png)

**Comment by Karunaharan** [comment]
Hi @superwangnan 
We are looking into the issue and will get back to you as soon as we have the right solution for you. Thanks.

- Karunaharan

**Comment by Karunaharan** [comment]
Hi @superwangnan 
In your application, you need to allow https://events.wa.canaryac.vlab-sapcloudplatformdev.cn to access it.
You can do it by adding this snippet to your application header.
Access-Control-Allow-Origin: https://events.wa.canaryac.vlab-sapcloudplatformdev.cn

You can also add the below to let any application access yours
Access-Control-Allow-Origin: *

It will handy if we can see your application code so that we can help you best. Please let me know if this helps you.

**Comment by superwangnan** [comment]
This is a SAP UI5 application and I deployed it in SAP Cloud Platform, please refer to my index.html code as following, where should I put this header? Thanks.

<!DOCTYPE HTML>
<html>

	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta charset="UTF-8">
		Access-Control-Allow-Origin: *
		<title>ESPM-UI</title>

		<script id="sap-ui-bootstrap"
			src="https://sapui5.hana.ondemand.com/resources/sap-ui-core.js"
			data-sap-ui-libs="sap.m"
			data-sap-ui-theme="sap_bluecrystal"
			data-sap-ui-compatVersion="edge"

			data-sap-ui-resourceroots='{"com.sap.ESPM-UI": "./"}'>
		</script>

		<link rel="stylesheet" type="text/css" href="css/style.css">

		<script>
			sap.ui.getCore().attachInit(function() {
				new sap.m.Shell({
					app: new sap.ui.core.ComponentContainer({
						height : "100%",
						name : "com.sap.ESPM-UI"
					})
				}).placeAt("content");
			});
		</script>
	</head>

	<body class="sapUiBody" id="content">
		<script>
			var swa = {
				pubToken: '2f01c1f4-94a7-41c7-9ade-3d845b9e67f1',
				baseUrl: 'https://events.wa.canaryac.apps.vlab-sapcloudplatformdev.cn/tracker/',
				owner: null, 
				//set this to a function that returns the identifier of the tracked user
				loggingEnabled: true,
				//set this to true inorder to enable tracking on load
				//If set to false, call swa.enable() to start tracking
				Access-Control-Allow-Origin: *
			};
			(function(){
				var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
				g.type='text/javascript'; g.defer=true; g.async=true; g.src=swa.baseUrl+'js/track.js';
				s.parentNode.insertBefore(g,s);
			 })();
		</script>
	</body>

</html>

**Comment by Karunaharan** [comment]
It looks fine now. Please redeploy your application to SAP Cloud Platform and then you should be able to send tracking events to SAP Web Analytics.
Feel free to reach out for further questions.

**Comment by MichaelCzcz** [comment]
@superwangnan Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
