### ISSUE TITLE
Access a Classic Schema from SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by AmauryVanEspen** [SAPDocuments/Tutorials#4435]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-access-cross-container-schema.html

Please specify the step you are referring to

Could not execute 'call SYS.GET_INSUFFICIENT_PRIVILEGE_ERROR_DETAILS ('D93A4E1E45E49846B11995F89FDEE970', ?)'
Error: (dberror) [258]: insufficient privilege: Detailed info for this error can be found with guid '66E047010064384AB3598C20DA933E88'

**Comment by jung-thomas** [comment]
So this error is telling you that the user you are trying to call GET_INSUFFICIENT_PRIVILEGE_ERROR_DETAILS doesn't have the privilege to run this procedure.  What user are you trying to use here?  What user are you using here to run this privilege?  It has to be a system admin kind of user (and yes the tutorial should probably be clearer that this has to be a power kind of user to run this troubleshooting).

**Comment by MichaelCzcz** [comment]
@AmauryVanEspen Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
