### ISSUE TITLE
SAP HANA XS Advanced - Cross-container access

### ISSUE THREAD

**Issue by AmauryVanEspen** [SAPDocuments/Tutorials#4436]
Tutorial URL: https://developers.sap.com/tutorials/xsa-cross-container-access.html

Please specify the step you are referring to

not able to click the "Done" bouton

**Comment by thecodester** [comment]
I assume you are saying that there are no DONE buttons in this tutorial, yes? Not that the DONE buttons don't work. We are working to update our tutorials without these buttons, and will do so shortly.

By the way, are you able to complete the steps in the tutorial, that is, access objects from another container?

@jung-thomas Here's an example of a tutorial without validation, and also not organized into a mission. Let's discuss.

**Comment by AmauryVanEspen** [comment]
Hello,
unfortunately not, not able to access objects from another container,
I believe some steps have changed or maybe i miss some role/authorization to perform the actions

**Comment by jung-thomas** [comment]
I assume that isssue https://github.com/SAPDocuments/Tutorials/issues/4435 has the details of your cross container problem?  If so can I close this issue.

**Comment by AmauryVanEspen** [comment]
Yes, it has,
however, this is not the same topic,
one is related to missing "Done" button in order to complete the task, the other is related to issue about the task

**Comment by jung-thomas** [comment]
@AmauryVanEspen  - yes this issue is about the lack of Done button.  But the lack of Done button isn't a bug per say. Its simply that not all tutorials on the developer center were built to use the tracking/done button.  Although this is something we'd like to improve overall for these tutorials, it isn't strictly an issue/bug.

**Comment by thecodester** [comment]
I will close this issue, as we have a more general issue related to the DONE buttons
