### ISSUE TITLE
Create a Data Element

### ISSUE THREAD

**Issue by topherhoffman** [SAPDocuments/Tutorials#4438]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-adt-create-data-element.html

Please specify the step you are referring to

#### The field-symbol booking has been defined as follows. Rewrite the LOOP AT statement using an inline declaration. Enter your code in the box below and choose **Submit Answer**:

>ABAP
```
FIELD-SYMBOLS <booking> TYPE sbook.
LOOP AT Booking_List ASSIGNING <booking>.
```

#### ISSUE: Validation not working properly.  _I believe_.
I submitted the following below as at the input.  Based on the work from the tutorial and then further research on http://abapmentor.expertise-team.com/post/7-4-release-news-inline-declaration-ii.aspx

```
LOOP AT Booking_List ASSIGNING FIELD-SYMBOL (<booking>).
```
Please let me know if this is correct as I would like to complete the tutorial with a 100% completion.  Additionally if this is incorrect there might need to be some helpful hints for what it should be.

**Comment by julieplummer20** [comment]
Hi topherhoffman, 
The only difference is that you have inserted a space after FIELD-SYMBOL (before the opening bracket):
LOOP AT Booking_List ASSIGNING FIELD-SYMBOL(<booking>).

I cannot currently check whether this space makes a difference. However, you should now be able to complete the tutorial.
BR Julie.

**Comment by MichaelCzcz** [comment]
@topherhoffman Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
