### ISSUE TITLE
Create a Simple ABAP CDS View in ADT

### ISSUE THREAD

**Issue by topherhoffman** [SAPDocuments/Tutorials#4439]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-adt-create-cds-view.html

Please specify the step you are referring to

#### Issue: Incorrect instructions that conflict with step 6.  No need to add header.payment_status

>If the invoice has been paid, you want to set the payment_status to X (true). Do this by implementing a CASE expression, assigning the alias payment_status to the CASE expression. Do not forget to separate payment_status and header with a comma.

#### Current Wrong Code
```
    header.buyer.company_name,
    sepm_sddl_so_invoice_item.sales_order_invoice_key,
    sepm_sddl_so_invoice_item.currency_code, 
    sepm_sddl_so_invoice_item.gross_amount,
    header.payment_status,
```

#### Step 6 has the user add a case for payment status.  This makes payment_status not unique and will throw an error.
```
    case header.payment_status
        when 'P' then 'X'
        else ' '
    end as payment_status,
```

### Either step 5 or 6 should be edited, to reflect that header.payment_status is not needed.

**Comment by topherhoffman** [comment]
> 
> 
> Tutorial URL: https://developers.sap.com/tutorials/abap-dev-adt-create-cds-view.html
> 
> Please specify the step you are referring to
> ### Step 6, 7, 8: Case for payment Status
> #### Related to #4439
> #### Issue: Incorrect code, no mention of the fix in later steps.
> 
> > If the invoice has been paid, you want to set the payment_status to X (true). Do this by implementing a CASE expression, assigning the alias payment_status to the CASE expression. Do not forget to separate payment_status and header with a comma.
> 
> #### Current Wrong Code
> 
> ```
> case header.payment_status
>     when 'P' then 'X'
>     else ' '
> end as payment_status
> ```
> 
> #### Assume to be correct code that is in step 7 screenshot and makes payment status unique.
> 
> Note the change on the last line "end as payment_**status**" -> "end as payment_**statement**"
> 
> ```
>     case header.payment_status
>         when 'P' then 'X'
>         else ' '
>     end as payment_statement,
> ```
> 
> The 'Final' Code in Step 8 has the code from Step 6, but not from step 7's screen shot.

### Incorrect Issue Originally stated.  The issue is with Step 5. Updated the issue with the correct information.  The original post is quoted above

**Comment by topherhoffman** [comment]
On another note this issue persists into the next tutorial in the group, with a picture,

https://developers.sap.com/tutorials/abap-dev-adt-use-cds-view/_jcr_content.github-proxy.1555220742.file/step3b-alv-ida.png

**Comment by julieplummer20** [comment]
Have added "Remove the existing declaration, **`header.payment_status,`** and replace it with the following code." 
I cannot see "payment_statement" in my tutorial. Please clarify where that is.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
