### ISSUE TITLE
Display a CDS View Using ALV with IDA

### ISSUE THREAD

**Issue by topherhoffman** [SAPDocuments/Tutorials#4440]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-adt-use-cds-view.html

Please specify the step you are referring to

Please specify the step you are referring to

#### Issue: Incorrect code, no mention of the fix in later steps.

>If the invoice has been paid, you want to set the payment_status to X (true). Do this by implementing a CASE expression, assigning the alias payment_status to the CASE expression. Do not forget to separate payment_status and header with a comma.

#### Current Wrong Code
```
case header.payment_status
    when 'P' then 'X'
    else ' '
end as payment_status
```

#### Assume to be correct code that is in step 7 screenshot and makes payment status unique.
Note the change on the last line "end as payment_**status**" -> "end as payment_**statement**"
```
    case header.payment_status
        when 'P' then 'X'
        else ' '
    end as payment_statement,
```

The 'Final' Code in Step 8 has the code from Step 6, but not from step 7's screen shot.

**Comment by topherhoffman** [comment]
### After Reviewing this issue can be closed.  Updating the related #4439 ticket. 

The real issue is in step 5 of the tutorial in #4439

**Comment by topherhoffman** [comment]
Small issue with the picture in 

Step 3: Add ALV grid to method implementation

This is related to the payment_status #4439 

https://developers.sap.com/tutorials/abap-dev-adt-use-cds-view/_jcr_content.github-proxy.1555220742.file/step3b-alv-ida.png

**Comment by topherhoffman** [comment]
Small issue with the picture in

Step 3: Add ALV grid to method implementation

This is related to the payment_status #4439

https://developers.sap.com/tutorials/abap-dev-adt-use-cds-view/_jcr_content.github-proxy.1555220742.file/step3b-alv-ida.png

Note that if the previous tutorial was done correctly, it would not have 'P' but would have 'X'

Reopening to have it resolved

**Comment by thecodester** [comment]
@julieplummer20 Can you review.

@topherhoffman Next time I suggest opening a new ticket, especially after this has been closed.

**Comment by MichaelCzcz** [comment]
@julieplummer20 Any updates?

**Comment by julieplummer20** [comment]
Hi Michael,
One of our tutorials is out of date, so I need to fix that first, then I will get onto this.
BR Julie.

**Comment by MichaelCzcz** [comment]
@julieplummer20 Any updates?

**Comment by julieplummer20** [comment]
Hi Michael,
No, I'll let you know.
BR Julie.

**Comment by julieplummer20** [comment]
Hi [@topherhoffman](https://github.com/topherhoffman),
I apologize for the delay.
However, when I look at the image, it shows 'X' : 
[image](https://developers.sap.com/tutorials/abap-dev-adt-use-cds-view/_jcr_content.github-proxy.1555220742.file/step3b-alv-ida.png)
Therefore, I do not understand the issue.
Please explain.
Best wishes,
Julie.

**Comment by thecodester** [comment]
@julieplummer20 I will close this issue. Please just double-check the images in Step 3.

@topherhoffman All the entries in that image show X's to me as well.
