### ISSUE TITLE
Issue nvarchar Athena

### ISSUE THREAD

**Issue by PaulVelthuis93** [SAPDocuments/Tutorials#4441]
Hello,
I am looking for nvarchar support in Athena. I could not yet find this in the Athena tutorial. Let me know if there exsists such a possiblity.

https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/hxe-aws-athena-05/hxe-aws-athena-05.md

**Comment by thecodester** [comment]
@jarjarbentley Are you taking over Abdel's tutorials?

@PaulVelthuis93 This is really a more general question, not on the specific tutorial. This forum is for errors in the tutorial. Best to continue the discussion in the SAP Community or in the SAP Questions & Answers.

https://www.sap.com/community.html
https://answers.sap.com/index.html

**Comment by PaulVelthuis93** [comment]
The issue is regarding that in this tutorial not all SAP Data Types are mentioned like **nvarchar**.
So the SDA is incomplete. I don't know to ask this on the SAP platform.

**Comment by thecodester** [comment]
So I will close this issue here, since this is more a feature request of the product.
