### ISSUE TITLE
Send Data with MQTT (host demo.eu10.cp.iot.sap not valid anymore)

### ISSUE THREAD

**Issue by aholler** [SAPDocuments/Tutorials#4442]
Tutorial URL: https://developers.sap.com/tutorials/iot-cf-send-data-mqtt.html

Please specify the step you are referring to

Step 6 The host demo.eu10.cp.iot.sap (point 7.) does not exist anymore.

Best regards,

Alexander

**Comment by iwonahahn** [comment]
Hi Alexander,

Your issues were addressed to the development team. I´ll get back asap here to you.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi Alexander,

We have fixed that in the tutorial. 
@thecodester please close the issue.

Thank you and best regards,
Iwona
