### ISSUE TITLE
Create an Analytical Dashboard via UI5 Web Component

### ISSUE THREAD

**Issue by lechnerc77** [SAPDocuments/Tutorials#4443]
Tutorial URL: https://developers.sap.com/tutorials/ui5-webcomponents-react-dashboard.html

Reason: Minor issue; duplicate declaration of style

Where: 
Step 5: Dashboard Layout
The style Property is declared twice:
```
style={{ width: "300px" }}
style={{ width: "300px", ...spacing.sapUiContentPadding }} 
```
=> Only the second one should be relevant
The same is valid for the complete code block following afterwards and the tutorial 
https://developers.sap.com/tutorials/ui5-webcomponents-react-routing.html Step 3

**Comment by thecodester** [comment]
@Marius FYI

**Comment by thecodester** [comment]
@IObert FYI

**Comment by IObert** [comment]
Thanks for opening this one Christian 🥇
