### ISSUE TITLE
Send and Receive Test Enterprise Messages

### ISSUE THREAD

**Issue by Pavithra0705** [SAPDocuments/Tutorials#4445]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-test-queue-sendreceive.html

Please specify the step you are referring to:

Step 2: Send message to the queue

It says the url has to be formed like "https://<uri_of_the_rest_protocol_based_section_from_Service Keys>/**messaging**/v1/queues/<Queue name>/messages"

However the postman image url has "**messagingrest**" and only messagingrest works. The url from the service key has to be followed by messagingrest for the post to work. Please correct the step 2 instructions. Thank you!

**Comment by pradeeppanda-sap** [comment]
Hi Pavithra,
 Thanks for the correction. Yes, it should be "messagingrest". I will update it.

**Comment by MichaelCzcz** [comment]
@pradeeppanda-sap Have youupdated the tutoriald and can I close this issue?

**Comment by pradeeppanda-sap** [comment]
yes.... I have updated the url as pointed out.
So please close the issue.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
