### ISSUE TITLE
Send and Receive Test Enterprise Messages

### ISSUE THREAD

**Issue by Pavithra0705** [SAPDocuments/Tutorials#4446]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-test-queue-sendreceive.html

Please specify the step you are referring to

Step 3: Receive message from queue : URL mentioned in the step has **consumption** whereas in the postman image it doesnot have **consumption** in the url. Please correct the image. Also the url should have **messagingrest** instead of **messaging** for the receive to work. 

Thank you,
Pavithra

**Comment by pradeeppanda-sap** [comment]
Yes it should be messagingrest.
Thanks for pointing it out.

regards
Pradeep

**Comment by MichaelCzcz** [comment]
Hello @pradeeppanda-sap, will there be an update on the tutorial? Can I close this issue?

**Comment by pradeeppanda-sap** [comment]
yes pls go ahead...
