### ISSUE TITLE
Create a Sample Application on Cloud Foundry Using SAP Cloud SDK

### ISSUE THREAD

**Issue by ffffffffffk** [SAPDocuments/Tutorials#4447]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-cloud-foundry-sample-application.html

Please specify the step you are referring to

To generate your first project from the Maven archetype, run the following command: (for Windows PowerShell see Appendix)

I think that url of Appendix might be different from Windows PowerShell.

**Comment by MatKuhr** [comment]
Thank you for pointing this out. I will update the link, it should actually [link here](https://developers.sap.com/tutorials/s4sdk-cloud-foundry-sample-application.html#ee4b1f20-6e96-409a-b009-92251db51289).

**Comment by MichaelCzcz** [comment]
@MatKuhr Have you updated the tutorial and can I close this issue?

**Comment by MatKuhr** [comment]
Yes, this can be closed.
