### ISSUE TITLE
Maintain a Communication Arrangement for Inbound Communication

### ISSUE THREAD

**Issue by cdmatos** [SAPDocuments/Tutorials#4449]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

Please specify the step you are referring to: In step 3 after opening Fiori launchpad I don't get option **Maintain Communication User available**: 

![2020-01-07_15-06-54](https://user-images.githubusercontent.com/31477286/71905129-6e46a880-315f-11ea-86a0-32a4dc4de316.jpg)

Is there any previous step I might have missed?

**Comment by mervey45** [comment]
Hi @cdmatos ,

you need to assign your user the business catalog communication management (SAP_CORE_BC_COM). I'll update this tutorial. Thank you for your feedback.
@thecodester I created following pull request: #4492. Can you merge it and close this ticket?

Thank you. 

Best regards, 
Merve
