### ISSUE TITLE
Get Started with SAP Cloud Platform Portal (Neo) : 500 SAP Internal Server Error

### ISSUE THREAD

**Issue by Waltersen1971** [SAPDocuments/Tutorials#4454]
Hello,

Tutorial is https://developers.sap.com/tutorials/cp-portal-freestyle-site-wd-add.html
Step 3, to start the app.

There is no problem to build the tile and it is shown. But when you want to start it you get this:

500 SAP Internal Server Error
ERROR: URL-Parameter sap-theme ist nicht in der HTTP White-List vorhanden (termination: RABAX_STATE)

If you google for this you will find sap notes for this problem:

https://apps.support.sap.com/sap/support/knowledge/preview/en/2578665

So could anybody so nice to fix the backend system?

THX

**Comment by IrisSasson** [comment]
Hi

This issue doesn't reproduce here. Please verify you are following all tutorial setps.

Thanks

**Comment by Waltersen1971** [comment]
Hello,

I have it tried:

a.) via my work PC

b.) via iphone

got in both cases:




I am going to check this with with my private PC also.

Regards


_____________________________________________________
Jan Schlichting
Deutsche Bundesbank
Zentrale
IT-Plattformanagement Drittprodukte

Willy-Brandt-Straße 73
20459 Hamburg

Tel.: 040 3707-6571
E-Mail: jan.schlichting@bundesbank.de
www.bundesbank.de

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte
Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail
irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte
Weitergabe dieser Mail oder von Teilen dieser Mail ist nicht gestattet.

Wir haben alle verkehrsüblichen Maßnahmen unternommen, um das Risiko der
Verbreitung virenbefallener Software oder E-Mails zu minimieren, dennoch
raten wir Ihnen, Ihre eigenen Virenkontrollen auf alle Anhänge an dieser
Nachricht durchzuführen. Wir schließen außer für den Fall von Vorsatz oder
grober Fahrlässigkeit die Haftung für jeglichen Verlust oder Schäden durch
virenbefallene Software oder E-Mails aus.

Jede von der Bank versendete E-Mail ist sorgfältig erstellt worden, dennoch
schließen wir die rechtliche Verbindlichkeit aus; sie kann nicht zu einer
irgendwie gearteten Verpflichtung zu Lasten der Bank ausgelegt werden.
______________________________________________________________________

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this e-mail in error)
please notify the sender immediately and destroy this e-mail. Any
unauthorised copying, disclosure or distribution of  the material in this
e-mail or of parts hereof is strictly forbidden.

We have taken precautions to minimize the risk of transmitting software
viruses but nevertheless advise you to carry out your own virus checks on
any attachment of this message. We accept no liability for loss or damage
caused by software viruses except in case of gross negligence or willful
behaviour.

Any e-mail messages from the Bank are sent in good faith, but shall not be
binding or construed as constituting any kind of obligation on the part of
the Bank.

**Comment by MichaelCzcz** [comment]
@Waltersen1971 Have you been able to test with your private PC? How did it go?

**Comment by Waltersen1971** [comment]
Hello,

sorry for responding a little bit late. I used now my private PC (with
Firefox), but I still get the same error.


Regards
_____________________________________________________
Jan Schlichting
Deutsche Bundesbank
Zentrale
IT-Plattformanagement Drittprodukte

Willy-Brandt-Straße 73
20459 Hamburg

Tel.: 040 3707-6571
E-Mail: jan.schlichting@bundesbank.de
www.bundesbank.de

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte
Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail
irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte
Weitergabe dieser Mail oder von Teilen dieser Mail ist nicht gestattet.

Wir haben alle verkehrsüblichen Maßnahmen unternommen, um das Risiko der
Verbreitung virenbefallener Software oder E-Mails zu minimieren, dennoch
raten wir Ihnen, Ihre eigenen Virenkontrollen auf alle Anhänge an dieser
Nachricht durchzuführen. Wir schließen außer für den Fall von Vorsatz oder
grober Fahrlässigkeit die Haftung für jeglichen Verlust oder Schäden durch
virenbefallene Software oder E-Mails aus.

Jede von der Bank versendete E-Mail ist sorgfältig erstellt worden, dennoch
schließen wir die rechtliche Verbindlichkeit aus; sie kann nicht zu einer
irgendwie gearteten Verpflichtung zu Lasten der Bank ausgelegt werden.
______________________________________________________________________

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this e-mail in error)
please notify the sender immediately and destroy this e-mail. Any
unauthorised copying, disclosure or distribution of  the material in this
e-mail or of parts hereof is strictly forbidden.

We have taken precautions to minimize the risk of transmitting software
viruses but nevertheless advise you to carry out your own virus checks on
any attachment of this message. We accept no liability for loss or damage
caused by software viruses except in case of gross negligence or willful
behaviour.

Any e-mail messages from the Bank are sent in good faith, but shall not be
binding or construed as constituting any kind of obligation on the part of
the Bank.

**Comment by LindsayBert** [comment]
Hi

I think it's best to open a ticket for this problem

Thanks
Lindsay

**Comment by Waltersen1971** [comment]
Hello,

Shall I open a ticket and if yes where?
_____________________________________________________
Jan Schlichting
Deutsche Bundesbank
Zentrale
IT-Plattformanagement Drittprodukte

Willy-Brandt-Straße 73
20459 Hamburg

Tel.: 040 3707-6571
E-Mail: jan.schlichting@bundesbank.de
www.bundesbank.de

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte
Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail
irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte
Weitergabe dieser Mail oder von Teilen dieser Mail ist nicht gestattet.

Wir haben alle verkehrsüblichen Maßnahmen unternommen, um das Risiko der
Verbreitung virenbefallener Software oder E-Mails zu minimieren, dennoch
raten wir Ihnen, Ihre eigenen Virenkontrollen auf alle Anhänge an dieser
Nachricht durchzuführen. Wir schließen außer für den Fall von Vorsatz oder
grober Fahrlässigkeit die Haftung für jeglichen Verlust oder Schäden durch
virenbefallene Software oder E-Mails aus.

Jede von der Bank versendete E-Mail ist sorgfältig erstellt worden, dennoch
schließen wir die rechtliche Verbindlichkeit aus; sie kann nicht zu einer
irgendwie gearteten Verpflichtung zu Lasten der Bank ausgelegt werden.
______________________________________________________________________

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this e-mail in error)
please notify the sender immediately and destroy this e-mail. Any
unauthorised copying, disclosure or distribution of  the material in this
e-mail or of parts hereof is strictly forbidden.

We have taken precautions to minimize the risk of transmitting software
viruses but nevertheless advise you to carry out your own virus checks on
any attachment of this message. We accept no liability for loss or damage
caused by software viruses except in case of gross negligence or willful
behaviour.

Any e-mail messages from the Bank are sent in good faith, but shall not be
binding or construed as constituting any kind of obligation on the part of
the Bank.

**Comment by IrisSasson** [comment]
Hi

We just thought of one idea. Are you working on a trial environment or on a production one. If you are working with trial you should use this tutorial group instead: https://developers.sap.com/mission.portal-cf.html

If you are indeed working on a production environment with a Neo env, please share 3 screenshots:
1.  app configuration , 
2. app navigation configuration
3. destination

Thanks

**Comment by MichaelCzcz** [comment]
@Waltersen1971 Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by SGA54** [comment]
Had the same issue, with MS Edge and Firefox when trying to open my SAP cloud trial space.
The I tried with Chrome and it works fine, no more 'Internal Server Error (500)' ...
