### ISSUE TITLE
Generate Custom OData Client Library with SAP Cloud SDK's Generator

### ISSUE THREAD

**Issue by kepair** [SAPDocuments/Tutorials#4456]
Tutorial URL: https://developers.sap.com/tutorials/cloudsdk-js-generator.html

Hi!
I'm following the guide without problems until step 4 (completed).
Before starting with the step 5, and having the scaffolded default aplpication `sap-cloud-sdk init my-sdk-project`, I try to run the application using `npm run start:dev`.
I get the following errors (I've tried with different entities (Candidate and requisitions) and there are similar errors in the auto-generated files in odata-client:

```
odata-client/sfo-data-service/function-imports.ts:59:128 - error TS2345: Argument of type '(val: any) => any' is not assignable to parameter of type '"Edm.String" | "Edm.Boolean" | "Edm.Guid" | "Edm.Decimal" | "Edm.Double" | "Edm.Single" | "Edm.Float" | "Edm.Int16" | "Edm.Int32" | "Edm.Int64" | "Edm.SByte" | "Edm.DateTime" | "Edm.DateTimeOffset" | "Edm.Time" | "Edm.Binary" | "Edm.Byte"'.
  Type '(val: any) => any' is not assignable to type '"Edm.Byte"'.

59   return new FunctionImportRequestBuilder('get', '/odata/v2', 'reassignJobReq', (data) => transformReturnValueForEdmType(data, (val) => edmToTs(val, Edm.String)), params);

odata-client/sfo-data-service/function-imports.ts:59:150 - error TS2304: Cannot find name 'Edm'.

59   return new FunctionImportRequestBuilder('get', '/odata/v2', 'reassignJobReq', (data) => transformReturnValueForEdmType(data, (val) => edmToTs(val, Edm.String)), params);
```
These files are automatically generated, so I'm not sure if there's something missing from my side.
Can you reproduce this issue?

Kind regards,
Pedro

**Comment by mr-flannery** [comment]
Hi Pedro,

thanks for reaching out to us! Can you please check which version of the `@sap/cloud-sdk-generator` you are using and upgrade if necessary? The current version should be `1.15.0`.
If it still fails with this version, please let us know.

Thanks!
Dennis

**Comment by kepair** [comment]
Hi Dennis,

Thanks for your prompt response. It seems to be updated to 1.15.0:

```
>npm list @sap/cloud-sdk-generator
sdk-sfsf@0.0.1 C:\workspace\sdk-sfsf
+-- @sap-cloud-sdk/cli@0.1.2
| `-- @sap/cloud-sdk-generator@1.15.0  deduped
`-- @sap/cloud-sdk-generator@1.15.0
```

I don't know if it's relevant, but in the package.json there's also the 1.15.0.

Kind regards,
Pedro

**Comment by mr-flannery** [comment]
Okay in that case we'll need to investigate. I'll get back to you soon!

**Comment by mr-flannery** [comment]
After investigating the issue, I can confirm that this is a bug that we'll need to fix. In the meantime, you can simply delete the `function-imports.ts` file from the output directory. This should at least make the application run. Unless, of course, you wanted to test these specific function imports. In that case, I'll need to look at a fix first.

**Comment by kepair** [comment]
Hi Dennis,

I don't need those functions for now, so I'll delete them.
Thanks for your quick answer!

Kind regards,
Pedro
