### ISSUE TITLE
Enable SAP Cloud Platform Mobile Services

### ISSUE THREAD

**Issue by ASRHARDING** [SAPDocuments/Tutorials#4462]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-hcpms-setup.html

When you search for “Mobile” in Service Marketplace you now only get one option to choose, “Mobile Services”, and not a list of mobile services as illustrated/referenced in the instructions.

**Comment by MichaelCzcz** [comment]
Hello @jitendrakansal. Did your commit solve the issue? Can the ticket be closed?

**Comment by ASRHARDING** [comment]
Looks good.
