### ISSUE TITLE
Set Up SAP Mobile Cards

### ISSUE THREAD

**Issue by ASRHARDING** [SAPDocuments/Tutorials#4463]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-setup.html

When you search for “Mobile” in Service Marketplace you now only get one option to choose, “Mobile Services”, “Mobile Services Kit” is not available as a service to select.

**Comment by sandeep-tds** [comment]
Hi @ASRHARDING 

Thank you for bringing this to our notice. 

The cloud service has been updated. We now have only one service called Mobile Services in the Cloud Foundry Service Marketplace.

Please proceed with the tutorials using the Mobile Services Tile. 

We will be updating the tutorial to reflect the latest changes shortly. 

Warm Regards
Sandeep T D S

**Comment by ASRHARDING** [comment]
Thanks for updating the tutorial.
