### ISSUE TITLE
CI Best Practices Guide – SAPUI5/SAP Fiori on ABAP Front-End Server

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#4470]
Tutorial URL: https://developers.sap.com/tutorials/ci-best-practices-fiori-abap.html

The tutorial still references the old Grunt based build process. As in the meantime the [ui5-tooling](https://github.com/SAP/ui5-tooling) is also used as the default build tooling in Web IDE I think this should be updated.

**Comment by SarahNoack** [comment]
See #4471. The new tutorial on the Help Portal can be found [here](https://help.sap.com/viewer/3324745951b44b578bd65221d2ff8f9a/Cloud/en-US/3713b07025274c2fbc95467627921a7a.html).

**Comment by thecodester** [comment]
I will close this issue. Any further discussion can continue in the other issue.
