### ISSUE TITLE
CI Best Practices Guide – SAPUI5/SAP Fiori on SAP Cloud Platform

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#4471]
Tutorial URL: https://developers.sap.com/tutorials/ci-best-practices-fiori-sapcp.html

Like in #4470 also this tutorial still references the old Grunt based build process. As in the meantime the [ui5-tooling](https://github.com/SAP/ui5-tooling) is also used as the default build tooling in Web IDE I think this should be updated.

**Comment by SarahNoack** [comment]
Hi Gregor, we have already reworked this tutorial. It can now be found on the [Help Portal](https://help.sap.com/viewer/3324745951b44b578bd65221d2ff8f9a/Cloud/en-US/1fd3a82e80b34a8a807c880850d64e11.html).
However, we would like to move the CI/CD Best Practices as a whole to the Help Portal and only then remove the old tutorials from the Tutorial Navigator. The deadline is the end of January.

**Comment by gregorwolf** [comment]
Unfortunately the Feedback functionality in the Help Portal isn't enabled. I hope that this can be done to allow feedback without raising incidents in the SAP Service Marketplace.

**Comment by SarahNoack** [comment]
Unfortunately, that's true - You can only directly comment on text passages as an SAP internal. However, you can also use the "Send feedback" button on top of the page or (which will be even more effective) write me an e-mail, as I'm responsible for the content of these tutorials: sarah.noack@sap.com

**Comment by MichaelCzcz** [comment]
@gregorwolf Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
