### ISSUE TITLE
Set Up SAP Mobile Cards

### ISSUE THREAD

**Issue by ASRHARDING** [SAPDocuments/Tutorials#4477]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-setup.html

Please specify the step you are referring to = Step 4 iOS tab.

If you get the logon screen, but don’t get the “Set Passcode” screen there could be a problem with your camera reading the barcode. To fix this problem close SAP Mobile Cards on your iPhone, then start it again manually without using the barcode - you will be presented with the SAP connect screen.

Using the values listed in the “APIs” tab first enter the Server URL and click on connect:
https://p<your user id>-dev-com-sap-mobile-platform-cards.cfapps.eu10.hana.ondemand.com

You will then need to enter, from the Registration iOS URL:
oauthClientId: 1825770f-b2a6-4a15-b46a-0fd98bf7e9ee
oauthEndpoint: https://p<your user id>-dev-com-sap-mobile-platform-cards.cfapps.eu10.hana.ondemand.com

Click on Connect, and after the logon screen you should see the Set Passcode screen to enter your passcode.

**Comment by ASRHARDING** [comment]
Correction to above text, after https:// for server and oauthEndpoint, the p should be p<your user id>.

Server to connect to: 
https://p<your user id>-dev-com-sap-mobile-platform-cards.cfapps.eu10.hana.ondemand.com 

oauthEndPoint: https://p<your user id>-dev-com-sap-mobile-platform-cards.cfapps.eu10.hana.ondemand.com

**Comment by jitendrakansal** [comment]
@sandeep-tds could you look at this thread?

**Comment by ASRHARDING** [comment]
Sorry, this is html and it strips out the less than / greater than symbols and content in my previous 2 posts. After the p in "p-dev" should go your user id.
I suspect the problem I was having with the QR code was just because I was using an old iPhone 6 where the camera was not picking up all of the QR code correctly. The phone had worked previously recognising the QR code for SAP Mobile Cards on an openSAP course last year. Finally fixed the painfully slow way of typing server and oauth URLs/code into the iPhone directly.

**Comment by MichaelCzcz** [comment]
@ASRHARDING Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by ASRHARDING** [comment]
I have seen the update. It would be worth adding a note to say if you have a problem with the QR code not being recognised, e.g. you get a blank screen instead of the passcode screen as I was encountering, you can enter server & oauth values directly from the APIs page to connect to Mobile Services.

**Comment by sandeep-tds** [comment]
> I have seen the update. It would be worth adding a note to say if you have a problem with the QR code not being recognised, e.g. you get a blank screen instead of the passcode screen as I was encountering, you can enter server & oauth values directly from the APIs page to connect to Mobile Services.

@ASRHARDING Thank you so much for the your wonderful suggestion. I will be sure to include the a note in the upcoming version. 

I hope that you are able to work with SAP Mobile Cards seamlessly now.
