### ISSUE TITLE
Using API Hub with Web IDE

### ISSUE THREAD

**Issue by bcschaich** [SAPDocuments/Tutorials#4481]
Tutorial URL: https://developers.sap.com/tutorials/webide-api-hub.html

Please specify the step you are referring to
In STEP 4 I am asked to select the "Employee Entity Type" package. This seems to not exist any longer. There also is no alternative there.

**Comment by thecodester** [comment]
@IObert Is this something you can help with?

**Comment by IObert** [comment]
It seems not only the entity is not part of the API Hub anymore and most screenshots from the tutorial are outdated too.


I would recommend to switch to the "Marketing Contact" artifact from the Marketing Cloud and use the following settings in the next step:
<img width="1176" alt="Screen Shot 2020-01-15 at 16 07 12" src="https://user-images.githubusercontent.com/1873245/72445366-e5102100-37b1-11ea-9218-0f698f07aeec.png">


Also, please select the environment "Neo" at the first step of the wizard

**Comment by bcschaich** [comment]
sounds like a solution
