### ISSUE TITLE
No Option to Subscribe to Process Integration

### ISSUE THREAD

**Issue by jake-barry** [SAPDocuments/Tutorials#4483]
In my trail account there is no option to subscribe to Process Integration.  Do I need to make a request to be able to use it somewhere else first?  I see other service such as Portal and Enterprise Messaging but not Process Integration...

**Comment by gauthamkrishna-sap** [comment]
Hello,
Can you please confirm that your subaccount is in Europe(Frankfurt) DC? Process Integration trial is only available in that region at this moment.
Thanks & Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
@jake-barry Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
