### ISSUE TITLE
Write HTTP Rest API for Hyperledger Fabric Chaincode

### ISSUE THREAD

**Issue by blockchain-infos** [SAPDocuments/Tutorials#4485]
Tutorial URL: https://developers.sap.com/tutorials/blockchain-hlf-rest-api.html

Please specify the step you are referring to
I copied and pasted the sample coding in swagger.io editor. There some errors appear.

**Comment by heytombeck** [comment]
Hello - can you please provide a screen shot of your Swagger.io with the errors displayed? I'll then be able to discuss this further with our blockchain developers.

**Comment by blockchain-infos** [comment]
Hey, I had to reduce the SAP disclaimer, then it worked.
Thanks,
Dennis

Tom Beck <notifications@github.com> schrieb am Mi., 15. Jan. 2020, 14:31:

**Comment by MichaelCzcz** [comment]
@blockchain-infos Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
