### ISSUE TITLE
Add UI Annotations for Detail and List Screens and Connect to Text Tables

### ISSUE THREAD

**Issue by henwr123** [SAPDocuments/Tutorials#4487]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-text-table.html

Step 3.2
The NAME in the text is **ZCAL_HOLITXT_XXX**, but the screenshot is **ZCAL_I_HOLITXT_XXX**.  Additional steps refer to **ZCAL_I_HOLITXT_XXX**.

![Capture](https://user-images.githubusercontent.com/1766017/72448525-c6dbfe00-377c-11ea-9e24-87f746dd09b3.PNG)

Please update name to **ZCAL_I_HOLITXT_XXX** to avoid confusion

**Comment by mervey45** [comment]
Hi @henwr123 ,

thank you for your feedback. I'll update this. 

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @thecodester,

I created following pull request: #4492. Can you merge it and close this ticket?

Thank you. 

Best regards, 
Merve
