### ISSUE TITLE
Implement the Text Handling for Your Factory Calendar

### ISSUE THREAD

**Issue by henwr123** [SAPDocuments/Tutorials#4488]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-validation.html

Please specify the step you are referring to

Step 2.4

Highlight the fact that "with additional save" annotation is needed.  

![Capture](https://user-images.githubusercontent.com/1766017/72450307-bf6a2400-377f-11ea-98aa-f72740066ebc.PNG)

**Comment by mervey45** [comment]
Hi @henwr123 ,

thank you for your feedback. I'll update this. 

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @thecodester,

I created following pull request: #4492. Can you merge it and close this ticket?

Thank you. 

Best regards, 
Merve
