### ISSUE TITLE
Try Out SAP Cloud Platform SDK for Android Wizard

### ISSUE THREAD

**Issue by omargarcia3000** [SAPDocuments/Tutorials#4489]
Tutorial URL: https://developers.sap.com/tutorials/cp-sdk-android-wizard-app.html

Step 1, section where  we create a destination for OData.
the screenshots dont correspond with the new version of the wizard. I dont know what url of the end point to use

**Comment by jarjarbentley** [comment]
@flyingfish162 can you take a look at this?

**Comment by flyingfish162** [comment]
> Tutorial URL: https://developers.sap.com/tutorials/cp-sdk-android-wizard-app.html
> 
> Step 1, section where we create a destination for OData.
> the screenshots dont correspond with the new version of the wizard. I dont know what url of the end point to use

According to your information, I presume that you are using Cloud Foundry landscape. Please see the screenshot on how to set destination for Cloud Foundry landscape. And BTW, we are working on new tutorials for Cloud Foundry.
<img width="994" alt="Screen Shot 2019-11-22 at 17 49 15" src="https://user-images.githubusercontent.com/56924323/73624214-e62ec280-467a-11ea-8804-a20bbbcf2dfe.png">

**Comment by flyingfish162** [comment]
PS: The tutorial for now is for mobile server NEO landscape.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by omargarcia3000** [comment]
Thank you for your help guys!
