### ISSUE TITLE
Set Up Business Rules for Determining Equipment

### ISSUE THREAD

**Issue by weisensen** [SAPDocuments/Tutorials#4491]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-businessrules.html

Please specify the step you are referring to
Step 2 when import Equipment Determination Rules,

**An error has occurred. Contact technical support.**

![image](https://user-images.githubusercontent.com/8147601/72489662-aaf55c80-384f-11ea-90aa-04add35e605d.png)

**Comment by weisensen** [comment]
This issue did not occur on second try.

**Comment by Shiva2906** [comment]
My issue is not getting resolved after multiple tries and login/logout. PLease help. It's the same issue at this exact step.
