### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by weisensen** [SAPDocuments/Tutorials#4496]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Please specify the step you are referring to

Step 5 Create HTML5 module  -  Logon to SAP Cloud Platform ABAP environment trial
A new window is opened with :
{"message":"Failed to create authorization request: null"}

![image](https://user-images.githubusercontent.com/8147601/72578365-db50ff80-3910-11ea-8768-54103ff3213e.png)

Chrome is using proxy.

**Comment by mervey45** [comment]
Hi @weisensen ,

did you try this out with your own ABAP trial? I see my name listed as the resource name. 


Thank you. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
@weisensen Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
