### ISSUE TITLE
Prepare the Portal Environment for Creating Sites

### ISSUE THREAD

**Issue by weisensen** [SAPDocuments/Tutorials#4497]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Please specify the step you are referring to
Step 1: Subscribe to the Portal service 
nothing happens when click on Subscribe 

![image](https://user-images.githubusercontent.com/8147601/72579929-7cda5000-3915-11ea-8ac4-ec78282014fa.png)

**Comment by LindsayBert** [comment]
Please open a ticket for this issue - I don't know how come you can't subscribe to the Portal

Thanks Lindsay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
