### ISSUE TITLE
Secure Your Application on SAP Cloud Platform Cloud Foundry

### ISSUE THREAD

**Issue by artemkovalyov** [SAPDocuments/Tutorials#4499]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-secure-cloudfoundry.html

Please specify the step you are referring to
These copy links don't provide visual UX which is a wrong behavior. These should be buttons or feedback has to be provided. This is relevant for all the tutorials.

![image](https://user-images.githubusercontent.com/10460752/72613944-40b4e880-3931-11ea-8a3e-108da6b752e5.png)

**Comment by MatKuhr** [comment]
@thecodester This is general UI/UX feedback for the tutorial page and not related to the specific tutorial.

**Comment by thecodester** [comment]
@artemkovalyov Thanks for feedback. When you say it should be button or "feedback should be provided", what do mean?

**Comment by thecodester** [comment]
I understand now, it is 2 requests: Make it look like a button, and have dialog that says ~"Code Copied". I have reviewed with our UX and added it to our backlog. Thanks for the idea.

**Comment by artemkovalyov** [comment]
@thecodester, your correct, I want it to look like a button and give visual feedback to user confirming that copying was successful. Thanks for taking care of this.
