### ISSUE TITLE
Add Transactional Behavior to Your Core Data Services

### ISSUE THREAD

**Issue by pgireendran** [SAPDocuments/Tutorials#4502]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-transactional-enablement.html

Please specify the step you are referring to

Implement Behaviour class - Step 6
A detail explanation of the code would help a new developer. There are new concepts like%cid .At least comments on what is happening in the each line of code would be helpful.

**Comment by mervey45** [comment]
Hi @pgireendran,

thank you for your feedback. We'll update this asap. 

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi@thecodester,

Can you merge following pull request: #4610?
Thank you.

Best regards, 
Merve

**Comment by thecodester** [comment]
Done
