### ISSUE TITLE
Create an Analytical Dashboard via UI5 Web Component

### ISSUE THREAD

**Issue by pacheco7** [SAPDocuments/Tutorials#4503]
Tutorial URL: https://developers.sap.com/tutorials/ui5-webcomponents-react-dashboard.html

In the following code snippet:

<Card
    heading="Progress"
    subtitle="List"
    style={{ width: "300px" }} >
    avatar={<Icon name="list" />}
</Card>

The atribute "avatar" was placed wrongly, the correctly place is inside on Card.

BR,

**Comment by Lukas742** [comment]
Hi @pacheco7,

thanks for creating this issue.
The [fix](https://developers.sap.com/tutorials/ui5-webcomponents-react-dashboard.html#221322ed-69b2-4017-9203-91cc2cfad9c4) has been applied.

BR
Lukas
