### ISSUE TITLE
Getting started with the SAP API Business Hub

### ISSUE THREAD

**Issue by ArunDomnic** [SAPDocuments/Tutorials#4508]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-getting-started.html

Please provide the correct  answer for this following question which has been posted.
What is the name of the 3rd user from the results array?
The name field is not available in that list . kindly provide the correct field name

**Comment by IObert** [comment]
Hi @anantmaks,

thanks for reporting this issue, you are right, the question is not deterministic. I'll change the question to a unique result in the next hour. For now, you can enter Linda which is the correct answer to this question.

**Comment by IObert** [comment]
Hi @ArunDomnic ,

thanks for reporting this issue, you are right, the question is not deterministic. I'll change the question to a unique result in the next hour. For now, you can enter Linda which is the correct answer to this question.

**Comment by ArunDomnic** [comment]
Thanks @IObert

**Comment by ArunDomnic** [comment]
But still the issue persist and the answer is not valid

**Comment by IObert** [comment]
Linda was the answer to the old question. I did change the entire question to get to a deterministic response. Please repeat step 4 of the tutorial to find the correct solution.
