### ISSUE TITLE
How to use Django with HANA, express edition

### ISSUE THREAD

**Issue by zeeshan-k** [SAPDocuments/Tutorials#4509]
Tutorial URL: https://developers.sap.com/tutorials/hxe-python-django-polls.html

**Please specify the step you are referring to**

Under the section: Following the Django Tutorial
The database engine name is simply mentioned as django_hana without mentioning how Django will get to know about django_hana.
`'ENGINE': 'django_hana',`
Does this need to be added as a custom database backend in Django, extending the native classes? Ultimately as soon as you run the project it throws error:

>   Message='django_hana' isn't an available database backend.
> Try using 'django.db.backends.XXX', where XXX is one of:
>     'mysql', 'oracle', 'postgresql', 'sqlite3'
>   Source=C:\Users\\<MY_USERNAME>\source\repos\project_name\manage.py
>   StackTrace:
>   File "C:\Users\\<MY_USERNAME>\source\repos\project_name\manage.py", line 25, in <module>
>     execute_from_command_line(sys.argv)

**Comment by jung-thomas** [comment]
An answer was suggested by a colleague in the development team of HANA Client (although Django is an open source project and not an official supported delivery from SAP). 

The key is here in Step 3c:
https://developers.sap.com/tutorials/hxe-python-django-polls.html
Installing Django and Django HANA Modules
Step 3c
…
Run python setup.py install. This should write out messages to the console indicating that it is running install and should conclude with the line Installed <path>/lib/site-packages/django_hana-1.1-py2.7.egg. There should not be any errors reported by the pip installer.

I would recommend re-running that step and ensuring that the Django_hana egg file was successfully created and copied into the python site-packages folder. It is this Django_hana egg file that is referenced in the ENGINE specification.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
