### ISSUE TITLE
Getting started with the SAP API Business Hub

### ISSUE THREAD

**Issue by anantmaks** [SAPDocuments/Tutorials#4510]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-getting-started.html

The expected answer of the 3rd user doesn't show up in the 3rd section exactly. As there are many other users being fetched, we have to fetch a large number of users and then try which a particular number of users fits the desired answer result. 
Also, it would be better if we ask the exact answer like what we want in the text area to be entered **firstName** or **lastName**. There is no _name_ parameter in the output

**Comment by IObert** [comment]
Hi @anantmaks,

thanks for reporting this issue, you are right, the question is not deterministic. I'll change the question to a unique result in the next hour. For now, you can enter `Linda` which is the correct answer to this question.
