### ISSUE TITLE
Add API Business Hub API to a UI5 Application

### ISSUE THREAD

**Issue by anantmaks** [SAPDocuments/Tutorials#4511]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-api-ui5-app.html

**Step 1: Create a basic SAPUI5 application**
**1.** Screenshots needs to be changed as there is no 'Finish' button until we reach to the 'Confirmation' tab
**2.** Under the 'Basic Information' tab, the _Namespace_ parameter is mandatory now while the tutorial doesn't give any clue about it.
**3.** `onInit` function comes already added in the controller in the _Main.controller.js_ , so we do not need to add it manually which is written in the tutorial

**Step 4: Run your application**
**1.** xhr.open("GET", url) is showing error as _sap-no-harcoded-url_

**Comment by thecodester** [comment]
@IObert Feel free to reassign if someone else is responsible

**Comment by IObert** [comment]
Hi @anantmaks,

thanks for opening this issue. You are right, the tutorial is quite outdated. I made a couple of changes to bring it up to date that should be available later today.

The warning about hardcoded URLs (rule sap-no-hardcoded-url) your seeing makes sense in general. As this is a tutorial, we can ignore it and disable the warning by adding the following comment in the respective line:

`// eslint-disable-line sap-no-hardcoded-url`
This will also be mentioned in the updated tutorial.
