### ISSUE TITLE
Call an External Endpoint to Retrieve Additional Information

### ISSUE THREAD

**Issue by hashimoto-ksc** [SAPDocuments/Tutorials#4512]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-consume-external-api.html

Thank you for creating the Cloud Platform Integration educational content. CPI does not have on-site training, so this material is very helpful.

The following problem has occurred.
Step4-3: What value should be set for Content Enricher?
The setting value of Step4-3 is incorrectly set to Step4-5.

**Comment by sbenoit99** [comment]
Here are the parameters you are looking for the Content Enricher:
Aggregation Algorithm: "Enrich"
ORIGINAL MESSAGE
Path to Node: /orders/order
Key Element: orderID
LOOKUP MESSAGE
Path to Node: /order
Key Element: orderID

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
