### ISSUE TITLE
Map Message Structure

### ISSUE THREAD

**Issue by hashimoto-ksc** [SAPDocuments/Tutorials#4513]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-convert-message-structure.html

Step1-1: When I try to download a file from a link to add a Source Message and a Target Message, I get an error if it has expired.
Please correct the link.

**Comment by gauthamkrishna-sap** [comment]
Hi,
The link is corrected now. Please try again and let us know. 
Best Regards,
Gautham

**Comment by thecodester** [comment]
@hashimoto-ksc I am closing the issue. If you still have an issue, feel free to reopen.
