### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by thearngrim** [SAPDocuments/Tutorials#4515]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Hello,

I am following the cpi design flow tutorial, I have a problem at the deployment, the status of the deployment is starting and not started

![webshop deploy](https://user-images.githubusercontent.com/10627616/72886931-feaded00-3d0a-11ea-9557-b6babfd5c4fe.png)

i have also the message saying i don't have any endpoint, although i have maintained one as described in the tutorial.

![webshop endpoint](https://user-images.githubusercontent.com/10627616/72886929-feaded00-3d0a-11ea-8856-a4881faa6dcf.png)

I have read and implemented the toturial multiple times, but always with the same issue, the deployment in in status starting for more than 12 hours now.

Could you guide me to what could be the problem? Let me know if you need anything more from my side.

Regards

Denis

**Comment by thearngrim** [comment]
I just checked this morning the status of the deployment and i have now an error message

![CPI error deploy](https://user-images.githubusercontent.com/10627616/72974262-020aac80-3dcf-11ea-8e8d-0f23d535f0ac.png)

**Comment by gauthamkrishna-sap** [comment]
Dear Denis,
Can you kindly check this again and let me know if you still face this issue? We have released a fix and this issue should ideally be resolved. Please check and let me know. 
Thanks & Best Regards, Gautham

**Comment by thearngrim** [comment]
Hello Gautham,

I tried again today, it goes in the right direction since i can see now the endpoint to my deployed flow, however it is still in status starting for more than 10 hours.
How long does it take for an iflow to go from status starting to started?
![Untitled](https://user-images.githubusercontent.com/10627616/73598397-1a4d9a80-4538-11ea-835f-4bf7fdec5270.png)

**Comment by gauthamkrishna-sap** [comment]
Hello,
Sorry for the delay in response. It usually takes less than 30 seconds if it is a simple integration flow. For complex flows, it might take longer. 
Are you still facing these issues?
Best Regards, Gautham

**Comment by thearngrim** [comment]
Hello,
I am still blocked yes, but I have abandoned to try on a trial puse. 
My company maanged to  give me access to one tenant in neo environment, so I will go forward from there.

Thanks for the assistance anyway.

Denis Galand

**Comment by gauthamkrishna-sap** [comment]
Hi Denis,
Sorry to hear that you could not proceed on the trial but good to hear that you have access to a productive tenant. We will continuously work on improving the trial in the meantime. 
Thanks & Best Regards, Gautham
