### ISSUE TITLE
How to install and setup git on HANA, express edition.

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#4516]
Tutorial URL: https://developers.sap.com/tutorials/hxe-install-git.html

Step: Setting Up Software Repositories and Installing Git

I'm running HXE SP03 and need to install git. Unfortunately the repositories that are used there are not available anymore. But the repositories:

http://download.opensuse.org/repositories/devel:/languages:/perl/SLE_12_SP4/
http://download.opensuse.org/repositories/devel:/tools:/scm/SLE_12_SP5/

do not contain git.

**Comment by jung-thomas** [comment]
I'm not exactly sure why but git and git-core seem to be missing from SLE_12_SP5 scm. They were there in earlier versions (even in SLE 11) and they are there in newer version (15, tumbleweed, and other openSUSE variants).

Even the search page only shows it for SLE 15
https://software.opensuse.org/download.html?project=devel%3Atools%3Ascm&package=git

Whereas git-crypt is available for SLE 15 and 12. SP5:
https://software.opensuse.org/download.html?project=devel%3Atools%3Ascm&package=git-crypt

Here is the link for SLE 15 (which has git):
http://download.opensuse.org/repositories/devel:/tools:/scm/SLE_15/x86_64/
Or Leap 15.2:
http://download.opensuse.org/repositories/devel:/tools:/scm/openSUSE_Leap_15.2/x86_64/

I did a little more searching and it seems that git is contained in sle-sdk for 12.5.  Maybe the results from this search tool will help:
https://scc.suse.com/packages?name=SUSE%20Linux%20Enterprise%20Server&version=12.5&arch=x86_64&query=git&module=

**Comment by MichaelCzcz** [comment]
@gregorwolf Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
