### ISSUE TITLE
Create a Card from a Web Application

### ISSUE THREAD

**Issue by ASRHARDING** [SAPDocuments/Tutorials#4517]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-web-push.html

Please specify the step you are referring to: Step 2: Create a new Card

Is this tutorial intended for Neo or Cloud Foundry environment?

The screenshots and destination indicate Neo environment, but when you select the “Sample Product Template” you get an Alert saying:
“The connection (com.sap.edm.sampleservice.v2) defined in the template is not known on this system. It needs to be manually created before the card can work on the device.”

I have seen com.sap.edm.sampleservice.v2 destination referred to in the tutorial "Set Up SAP Mobile Cards" using Cloud Foundry.

**Comment by ASRHARDING** [comment]
![Alert connection sampleservice v2](https://user-images.githubusercontent.com/57531943/72892310-1b97ef80-3d0e-11ea-80f0-da73e2a5c062.png)

**Comment by ASRHARDING** [comment]
Revisiting this problem a day later a number of observations:

- The com.sap.edm.sampleservice.v2 is listed in the "Destinations" tab, but you can't select it when choosing a destination for the card.
![image](https://user-images.githubusercontent.com/57531943/73009642-dc9a9480-3e08-11ea-85c0-42c9b02d4350.png)
![image](https://user-images.githubusercontent.com/57531943/73009700-f4721880-3e08-11ea-8c73-28c7199b9019.png)

- Attempting to create the card again in Neo version of Mobile Services Cockpit I was successfully able to select SAPCPMobileServices when creating PushCard. I successfully continued the exercise all the way to the end, but only received the mobile card template text, not any of the data in the card on my iPhone.

- To connect to the Neo version of Mobile Services I first had to reset (remove) the connection held by Mobile Cards on my phone to Cloud Foundry. The connection to Neo Mobile Services was achieved, but the process was not without its problems.

- Attempting the exercise on Cloud Foundry version of Mobile Services I was able to get all the way to near the end of Step 7, but then it failed when trying to create the card - possibly to be expected when the solution includes a file called neo-app.json.
![image](https://user-images.githubusercontent.com/57531943/73010438-567f4d80-3e0a-11ea-96fa-6dac2b35d8ed.png)

**Comment by jitendrakansal** [comment]
@sandeep-tds please will look into this.

**Comment by sandeep-tds** [comment]
@ASRHARDING Thank you so much for bringing the issue to our notice. 

As you rightly observed, [the tutorial in question](https://developers.sap.com/tutorials/cp-mobile-cards-web-push.html) is currently designed for the Neo environment. The destination for the same should be SAPCPMobileServices. 

We are in the process of updating the tutorial to point to Cloud Foundry. Once done, you will be able to successfully complete the tutorial. 

Thank you so much for your patience. We truly appreciate it.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
