### ISSUE TITLE
Feedback on Tutorial: SAP HANA XS Advanced, Connecting to the WebIDE to begin development

### ISSUE THREAD

**Issue by Datronix** [SAPDocuments/Tutorials#452]
This is not a good tutorial.
It is unclear how the very first step follows on from the previous tutorial.

**Comment by ccmehil** [comment]
Exactly which part is unclear? The previous tutorial is how to get your system which also indicates that steps are necessary which can be found on the landing page of the system once it has been created. We'd like to update this to remove confusion so if you can help me better understand what was/is unclear then I'll get those changes into place.

**Comment by rojasc77** [comment]
Hello @ccmehil,

My name is Carlos Rojas, I am studying SAP HANA and I want to help improve this tutorial, 

I will try to explain my experience with the tutorial:

- SAP HANA XS Classic Group 1: Basic development, it has very little problems  but you can figure out and resolve.

- But, SAP HANA XS Advanced Group 1: Basic development,  it was difficult execute the first step, the first instruction says: 

> Launch the SAP Web IDE for SAP HANA at the following URL in your web browser.

but to me, it not explains what i have to do , then I I had read all the first step, and based on:

> ...that you created in the previous tutorial.

I tried to use the url: [codejamp**999999**trial.hanatrial.ondemand.com:53075](https://codejamp999999trial.hanatrial.ondemand.com:53075)  (**999999** is not the real number) but not work, then I search in google: SAP Web IDE for SAP HANA and found the video: [SAP HANA Academy - SAP Web IDE: Getting Started [1.15]](https://www.youtube.com/watch?v=RC1TGO3Yyqk&list=PLkzo92owKnVwnV5o1psI7XSA-AquO9_9g&index=1) at 4'20" it shows the link to access to SAP Web IDE for SAP HANA.

- The second step was easy, but third step was impossible,  it says: 

> Choose Multi-Target Application Project...

but this option not exist, the screen only showed templates related with SAPUI5, SAP Fiori and an empty plugin. Then I found http://go.sap.com/developer/tutorials/sapui5-webide-open-webide.html and in this page explains step by step how launch the Web IDE. At this point I said: enough with XS, and start SAPUI5 tutorial, it has little troubles but similar to the first tutorial you can figure out and resolve.

In some moment I clicked in some blue box "feedback", and I wrote something about the "template options" in the third step, but at the end says: "Thanks for the survey" and I know sometimes surveys are slow, then I click in the link "feedback" and discover this GitHub forum. I hope it will be faster than survey.

If you need more details I can help you.

Best Regards,
Carlos Rojas.

**Comment by ccmehil** [comment]
SAP HANA XSA is not available on the SAP HANA Cloud Platform nor is the SAP WebIDE for SAP HANA - for XSA development you can only use the SAP HANA Developer Edition (via http://cal.sap.com where it is hosted on Amazon AWS or Microsoft Azure)
