### ISSUE TITLE
Add API Business Hub API to a UI5 Application

### ISSUE THREAD

**Issue by sodogan** [SAPDocuments/Tutorials#4526]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-api-ui5-app.html

Nice tutorial. 
Thank you for the effort.

Only one question, i get eslint error on console.log saying that its not recommended
Is it better not to use the javascript code
is there a best practice approach?

**Comment by IObert** [comment]
Hi @sodogan,

thanks for opening this issue. Writing output to the console is not a problem in tutorials/demo applications. Productive apps should refrain from doing so as it could contain sensitive information.

As this is a tutorial, you can ignore it and disable the warning by adding the following comment in the respective line:

`// eslint-disable-line no-console`

PS: I'm currently updating the tutorial and a more recent version should be online soon.

**Comment by sodogan** [comment]
Thank you for your reply Marius

That's great
I didn't know you can suppress the warning.
Thanks alot
I look forward to more tutorials.

Have a nice day
Solen
