### ISSUE TITLE
Unable to Create destination for SAP SuccessFactors sandbox -EU Region

### ISSUE THREAD

**Issue by C5269483** [SAPDocuments/Tutorials#4527]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-digitalexp-mobilecards-1-setup.html

**In Tutorial-1 Step-3**: While creating a destination to be connected to the SAP Success Factor sandbox system, we are supposed to select a **Success factor My To Dos template**.

After clicking on the Create button for this template, according to the documentation, we are supposed to get a popup where we have to enter the API Key. 

But I see that this popup does not appear and instead we get the below alert message.

![Mobile_Card_Issue](https://user-images.githubusercontent.com/39294341/73055627-3d7ea700-3eb3-11ea-96eb-2cb65acc2bf5.JPG)

After this it is not mentioned in the tutorial as to how to proceed further.

Thanks,
Priyanka

**Comment by jitendrakansal** [comment]
@C5269483 thanks for reporting it. We are already aware of this issue and currently working with development team to fix it.

**Comment by jitendrakansal** [comment]
@sandeep-tds please will look into this.

**Comment by sandeep-tds** [comment]
HI @C5269483, 

Thank you for bringing the issue to our notice. We are experiencing an issue with the Sandbox API for SuccessFactors at the moment.  We are working to resolve this issue at the earliest. 

I will create notify you via a comment here. 

Thank you for your patience.

**Comment by MichaelCzcz** [comment]
Hello @sandeep-tds. Have the issues with Sandbox API been solved? Can I close this issue?

**Comment by sandeep-tds** [comment]
Hi @MichaelCzcz, 

We are in the process of providing a fix. We plan to ship this in our upcoming release.
Once it releases, I will post an update on this ticket.

In the meantime, I believe you're the best judge to decide the status of the ticket.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by MamathaKH** [comment]
Still this issue persist. Could you please check this once

**Comment by sandeep-tds** [comment]
@MichaelCzcz  Thank you so much for bringing this to my notice. The tutorial was outdated and thus has been retired. 

@C5269483 @MamathaKH  In place of this tutorial, we recommend [a new tutorial](https://developers.sap.com/mission.mobile-cards-get-started.html) that is a great place to start development for SAP Mobile Cards. 

New Tutorial Details - [Get Started with SAP Mobile Cards](https://developers.sap.com/mission.mobile-cards-get-started.html)
