### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by CAARNICL** [SAPDocuments/Tutorials#4528]
Tutorial URL: https://developers.sap.com/tutorials/xsa-create-user-provided-anonymous-service.html

Please specify the step you are referring to

Step 3: SPS03 - Create a User-Provided service using a wizard

please provide the way for SPS04 and above:  db -> right click -> new -> SAP HANA Service Connection

thank you

**Comment by jung-thomas** [comment]
This tutorial was recently updated to add the SPS 04 version of the menu option as well.
