### ISSUE TITLE
Unable to install @sap/cds-dk

### ISSUE THREAD

**Issue by btmitchellau** [SAPDocuments/Tutorials#4529]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Failing for me at step 1 sadly, tried 10+ times from the command line

![image](https://user-images.githubusercontent.com/33737855/73151792-b59bd580-411c-11ea-8eb1-8f298e4e8d5a.png)

**Comment by btmitchellau** [comment]
used different internet connection, worked fine.

**Comment by thecodester** [comment]
@iwonahahn FYI
