### ISSUE TITLE
Mismatch in expected result screenshot for "Set Up a Workflow With Extended Employee Onboarding"

### ISSUE THREAD

**Issue by BaskarThambiayah** [SAPDocuments/Tutorials#4531]
Hi ,

While executing the starter Scenario for "Automate and Extend Employee Onboarding", we found a mismatch in the expected result Screenshot for the tutorial "Set Up a Workflow With Extended Employee Onboarding" in Step "3 : Build and deploy sample application".

Actually, A successful deployment message is shown at the top-right corner once the deployment successfully completes. 
But the actual result message is mismatching with the screenshot attached in the tutorial. Because of this the end user might get confuse with the obtained result.

Expected Screenshot: 
![image](https://user-images.githubusercontent.com/60343237/73165824-8edc9f80-411a-11ea-8a56-f4aa388d0b0f.png)

Actual Screenshot: 
![image](https://user-images.githubusercontent.com/60343237/73165867-aae04100-411a-11ea-8b60-4deaf448a4c8.png)

Note: I have executed this test for AWS in trial account for US region.

Thanks & regards,
Baskar

**Comment by ArchanaShukla** [comment]
Hello Baskar,
The screenshot changes depending upon the updates from WebIDE. As the existing screenshot matches the overall screenshot, I would still like to keep it because the message is communicated that the deployment is successful. 

No need to update the tutorial. Please close the issue
