### ISSUE TITLE
Missing of data in tutorial : Create Table Persistence and Generate Data.

### ISSUE THREAD

**Issue by C5231723** [SAPDocuments/Tutorials#4532]
Hi Colleagues,

As part of scenario : Develop an SAP Fiori App Using ABAP.

Tutorial : Create Table Persistence and Generate Data.
In step 1 , Create ABAP package: Under point 4 , I have observed that an additional step should be mentioned as :
User should select the "Create a new request" radio button and enter the "Request Description"  text field and click on Finish button.

**Actual result :** Inappropriate screenshot is attached and below mentioned step is missing in the tutorial.
![image](https://user-images.githubusercontent.com/58938250/73168167-4c699180-411f-11ea-82bc-370681c86625.png)

**Expected result :** The below point should be included as : 
User should select the "Create a new request" radio button and enter the "Request Description"  text field. 
And appropriate screenshot should be attached.
![image](https://user-images.githubusercontent.com/58938250/73168200-630fe880-411f-11ea-868e-d55cb7483b69.png)

Thanks & Regards,
Sony Narayan

**Comment by mervey45** [comment]
Hi @C5231723 , 

thank you for your feedback. We'll update this.
@thecodester I created following pull request: #4562, can you merge? We can close this ticket. 

Best regards, 
Merve
