### ISSUE TITLE
Missing of data in tutorial : Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules.

### ISSUE THREAD

**Issue by C5231723** [SAPDocuments/Tutorials#4533]
Hello Colleagues,

As part of scenario : Develop an SAP Fiori App Using ABAP.
Tutorial : Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules.
In step 5, Create HTML5 module: Under point 3, an additional point should be mentioned since "Namespace" has become mandatory field as : User should fill the "Namespace" text field.

**Actual result :** The below mentioned step is missing and the inappropriate screenshot is attached.
![image](https://user-images.githubusercontent.com/58938250/73168896-df56fb80-4120-11ea-9410-e50c508813cd.png)

**Expected result :** An additional point should be mentioned as : User should fill the "Namespace" text field and appropriate screenshot should be attached.
![image](https://user-images.githubusercontent.com/58938250/73168907-e2ea8280-4120-11ea-86b1-0a2d31953dff.png)

Thanks & Regards,
Sony Narayan

**Comment by mervey45** [comment]
Hi @C5231723 ,

this only appears, if you don't use your ABAP trial. You can fill in anything you want as a namespace. But in our example, we use the ABAP trial. So, therefore, we don't need the namespace. 

Best regards, 
Merve

**Comment by C5231723** [comment]
Hi Mervey,

Thanks for the update.
Even i am using the ABAP trial. But without filling the "Namespace" text field, the "Next" button is not getting enabled because its an mandatory field. So the user must fill the data and we can enter any value in namespace.
But my only concern is that inappropriate screenshot is attached in the tutorial and data such as "User should fill the "Namespace" text field" is missing, which should be updated in the tutorial.

**Comment by mervey45** [comment]
Hi @C5231723 , 

thank you for your feedback. We'll update this asap.
@thecodester Can you merge following pull request: #4610?
Thank you.

Best regards, 
Merve

**Comment by thecodester** [comment]
Done
