### ISSUE TITLE
Description of "step 2: Add a workflow" in "Tutorial 4: Set Up Process Visibility to Track Employee Onboarding Workflow" is not clear

### ISSUE THREAD

**Issue by BaskarThambiayah** [SAPDocuments/Tutorials#4534]
Hi ,

While executing the starter Scenario for "Automate and Extend Employee Onboarding", we found a mistake in the description of the step "step 2: Add a workflow", in tutorial "Tutorial 4: Set Up Process Visibility to Track Employee Onboarding Workflow".

It is written in the tutorial as:
Go back to the homepage and click **Processes** tab, choose **+** and select **Add SAP Cloud Platform Workflow** to add workflow to business scenario.

Issue: If we go back to the homepage, we will not find Processes tab.

But actually it should have been written as : 
“Click the **newly created business scenario** and click on **Processes** tab, choose + and select Add SAP Cloud Platform Workflow to add workflow to business scenario."

Note: I have executed this test for AWS in trial account for US region.

Many thanks & regards,
Baskar

**Comment by ArchanaShukla** [comment]
Thanks Bhaskar for the feedback. Tutorial is updated.
Please close the issue.
