### ISSUE TITLE
One additional step require for the step 6 of the Tutorial 5: Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by BaskarThambiayah** [SAPDocuments/Tutorials#4535]
Hi,

While executing "Automate and Extend Employee Onboarding" starter scenario, we observed the below findings.

Tutorial 5: Run the Employee Onboarding Sample Scenario 
Step 6: Continue with the workflow execution.

In the tutorial, it is written as:
3. In the SAP Fiori launchpad, open the Monitor Workflow - Workflow Instances tile, choose the filter button, add the Completed status.

Actual Result: When we choose the filter button, there are two options. 
![image](https://user-images.githubusercontent.com/60343237/73169894-22b26980-4123-11ea-80ba-a43092f0c34d.png)

Now select the option “Status”. Then we will get the list to choose the “Completed” status. 
![image](https://user-images.githubusercontent.com/60343237/73169902-26de8700-4123-11ea-9b01-095f727b6bc1.png)

Now add the “Completed” status.

Note: I have executed this test for AWS in trial account for US region.

Many thanks & regards,
Baskar

**Comment by ArchanaShukla** [comment]
Tutorial updated. Please close the ticket
