### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#4536]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Node_Tut1_Step3

After   initializing the given app in the tutorial, srv and dev folders have already been created in Visual studio code editor but in tutorial screenshot the folders are not present.

Expected   result: The sentence as displayed in screenshot could be slightly changed to "After initializing the app, check whether the srv and dev folders are already created, if Yes then create the respective file. If No, type srv/cat-service.cds to create folder and file at once.
Please find the screenshot for the same.

<img width="498" alt="Node_Tut1_Step4" src="https://user-images.githubusercontent.com/50734023/73177763-cc9af180-4135-11ea-8066-29535faf1ffb.png">

**Comment by qmacro** [comment]
Hi @iwonahahn can you please take a look at this - I think this is a recent tutorial from you / your team, is that right? Thanks!

**Comment by iwonahahn** [comment]
Thank you for the suggestions. We have updated our tutorials based on your feedback. 
Best regards, 
Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
