### ISSUE TITLE
Install the Optional SAP HANA Smart Data Integration Package for SAP HANA, express edition (Native Linux Machine)

### ISSUE THREAD

**Issue by chholzer1190** [SAPDocuments/Tutorials#4540]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-sdi-binary.html

Hi, I am using the GCP HANA Express + XSA package from the GCP marketplace. Everything seems to work. But when I try to create a virtual table on the Remote Source or try to open the Remote Source in Hana Cockpit, I get the following error:
Error: (dberror) [476]: invalid remote object name: exception 70000000: No error; $message$=not well-formed (invalid token) ErrorCode=4 lineNumber=1 columnNumber: 181 : line 0 col -1 (at pos 0)

The strange thing is, that I did exactly the same steps in December. And at time they worked.
Can you help me in analyzing the issue?
Best Regards
Christian

**Comment by JCurrie27** [comment]
Hi Christian: Could you please log this error in [Questions and Answers](https://developers.sap.com/topics/sap-hana.html#community) section of the HANA Express community? That forum has much more visibility, and community members will help troubleshoot.

**Comment by thecodester** [comment]
To ask a question, see https://answers.sap.com/index.html
