### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by Venkatpicons** [SAPDocuments/Tutorials#4542]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Please specify the step you are referring to
Tutorial 1 :  Create a Business Service with Node.js Using Visual Studio Code
Step 8:   Add persistent database
6th Step : cds watch - When executing this command the below output should be displayed.

[cds] - connect to datasource - sqlite:db/my-bookshop.db
[cds] - serving CatalogService at /catalog - with impl: srv/cat-service.js
[cds] - launched in: 4356.854ms
[cds] - server listening on (http://localhost:4004) ...
--

But in the document, they mentioned use copy the above output in Terminal or command prompt. Actually its not required to use the above command and its output of CDS WATCH command.

Please find the attached screenshot for your reference.
![Copy_tile](https://user-images.githubusercontent.com/60374957/73233284-073f7100-41ac-11ea-8777-197c0f228e61.JPG)

Kind Regards
Venkat

**Comment by iwonahahn** [comment]
We have updated our tutorial based on your feedback. 
Thank you and best regards, 
Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by Venkatpicons** [comment]
Hi Team,

This issue is still exists. Can u please check.
So, reopening the ticket.
