### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by Venkatpicons** [SAPDocuments/Tutorials#4543]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

Please specify the step you are referring to
Step 2   : Deploy using cf push -  the below command is mentioned to execute in the tutorial 2
cf create-service hanatrial hdi-shared   my-bookshop-db-hdi-container and we got an error and unable to proceed further.

However, we have executed one more tutorial before executing the above command which is not mentioned in the tutorial. Please check.

The below is the URL that we used and its missed in prerequisite step.
https://developers.sap.com/tutorials/cp-cf-download-cli.html

Note : The above link should be added in prerequisite step.

Kind Regards
Venkat

**Comment by iwonahahn** [comment]
We have updated our tutorial based on your feedback.
Thank you and best regards,
Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by Venkatpicons** [comment]
Hi Team,

Issue is still persist and we couldn't find any updated tutorial for this issue. Please check and let me know if you need any input on this.

Kind Regards
Venkat

**Comment by iwonahahn** [comment]
The link is in the prerequisites now.  Issue can be closed.
