### ISSUE TITLE
Mismatch in the "Application Identifier" name for the tutorial "Set Up Business Process Management Services in Cloud Cockpit"

### ISSUE THREAD

**Issue by BaskarThambiayah** [SAPDocuments/Tutorials#4544]
Hi ,

While executing the starter Scenario for "Automate and Extend Employee Onboarding", we found a mismatch in the "Application Identifier" name for the tutorial "Set Up Business Process Management Services in Cloud Cockpit" in Step "6 : Assign roles".
5. Click **Add Role** and select these roles to add them to the role collection one by one. In **Add Role** popup, click **Save** after each selection.

Expected Result as per the the screenshot in the document:
![image](https://user-images.githubusercontent.com/60343237/73234661-28569080-41b1-11ea-9be4-d4e53e53063e.png)

Actual Result:
![image](https://user-images.githubusercontent.com/60343237/73234737-753a6700-41b1-11ea-842f-43093514713c.png)

Here, the Application Identifier name is appended with some extra character and numbers when we select it from the Application Identifier drop down field.
As per the screenshot this appended numbers are mismatching with the actual value.

The end user might get a confusion in this situation. 
So it would be good if you add an extra line for this step with the detail of this appended extra character and numbers.

Note: I have executed this test for AWS in trial account for US region.

Many thanks & regards,
Baskar

**Comment by ArchanaShukla** [comment]
Hello Baskar,
The application identifier differs depending upon from which data center you have entitled the business rules service. As yours was US region, and screenshot are from EU region therefore the change in the number. I have kept the note though in the tutorial.

Tutorial updated, please close the issue
