### ISSUE TITLE
Develop an SAP Fiori App Using ABAP

### ISSUE THREAD

**Issue by C5231723** [SAPDocuments/Tutorials#4545]
Mission URL: https://developers.sap.com/mission.cp-starter-extensions-abap.html

Hello Colleagues,

**Tutorial : Develop a Fiori App Using the ABAP RESTful Programming Model (Managed Scenario).**
I have observed that, the total time displayed for the execution of the below tutorial is incorrect.
i-e., the tutorial “Develop a Fiori App Using the ABAP RESTful Programming Model (Managed Scenario)” includes 6 tutorials and time mentioned for each of the tutorials are as below :
Get to Know the ABAP RESTful Programming Model --> 5min 
Create Table Persistence and Generate Data  -->10 mins 
Define and Expose a CDS-Based Travel Data Model --> 20 mins 
Create Behavior Definition for Managed Scenario  --> 15 mins 
Enhance Behavior With Action and Validation --> 10mins 
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules --> 15mins 

**Actual result :** Total time displayed in the tutorial is 1 hr.   
![image](https://user-images.githubusercontent.com/58938250/73236381-322fc200-41b8-11ea-944a-665addd3ee9d.png)

**Expected result :** The total time displayed should be 1hr 15mins.

Thanks & Regards,
Sony Narayan

**Comment by thecodester** [comment]
Fixed ... thanks

https://developers.sap.com/mission.cp-starter-extensions-abap.html -- 80 minutes
https://developers.sap.com/group.abap-env-restful-managed.html --75 minutes

**Comment by C5231723** [comment]
Hello Colleagues,

I have observed that , In the Home page, the total time displayed for executing the scenario is incorrect
Actual result : 1hr 5min is displayed.
![image](https://user-images.githubusercontent.com/58938250/77038077-da078600-69d8-11ea-9aec-31974c3bb9e1.png)

Expected result : 1hr 20mins should be displayed.

Thanks & Regards,
Sony Narayan
