### ISSUE TITLE
Integrate a URL App into Your Portal Site

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#4546]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-url-app.html

Portal_Tut4_Step5

Explore button is not displayed in the tutorial screenshot. But at present, the Explore button is present. Please look into the attached screenshot.

<img width="959" alt="explorebutton" src="https://user-images.githubusercontent.com/50734023/73239202-71aedc00-41c1-11ea-9ee3-e4b11a2fab5a.png">

**Comment by IrisSasson** [comment]
Sent mail to Lindsay to replace the screenshot

**Comment by MichaelCzcz** [comment]
@IrisSasson @LindsayBert Have you updated the screenshot and can I close this issue?

**Comment by LindsayBert** [comment]
Hi - sorry for the delay - just returned from vacation.  The Explore button is to search for apps from content providers.  This feature was not implemented when the tutorials were written.  If we are going to change the screen capture, we need to add the functionality to the tutorial.  It also means changing many more screen captures.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
