### ISSUE TITLE
Configure Initial Setup for SAP Mobile Cards

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#4552]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-digitalexp-mobilecards-1-setup.html

Please specify the step you are referring to Step 3.

Hello I have a Problem to initialize the Service. 
![Unbenannt](https://user-images.githubusercontent.com/10000063/73438851-fed36b80-434e-11ea-8664-b494d6913f62.JPG)

Is there a technical Problem?

**Comment by sandeep-tds** [comment]
@marcobuescher Thank you for bringing your issue to our attention. 

Do you continue to face the issue? If so, can you please attach a screenshot of your SAP Cloud Platform Mobile Services application list. 

Thank you for your support.

**Comment by MichaelCzcz** [comment]
@marcobuescher Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
