### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by KimSAP** [SAPDocuments/Tutorials#4553]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Please specify the step you are referring to: Step 5: Create service instance and key

Hi,
When I want to create an instance, I receive an error message, stating that I am not authorized to do that. It seems that it is linked to trial version, with insufficient entitlement.
Is there a  way to finish the exercice?

Regards,
Kim

**Comment by gauthamkrishna-sap** [comment]
Hi Kim,
Ideally, you should be able to do this with the defaults in your trial account. Did you by any chance create a new subaccount for this tutorial? If yes, please ensure that **Process Integration Runtime** entitlement is assigned to your subaccount. Then, you should not have any issues with the service instance creation. 
Thanks & Best Regards,
Gautham

**Comment by MichaelCzcz** [comment]
@KimSAP Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
