### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by xRicardinhox** [SAPDocuments/Tutorials#4556]
Step 1.2 In your subaccount, select Subscriptions > Process Integration.
when I try to find the services "Process Integration" is not an option.  But i see that in the next steps it appear in the space>service MarketPlace the option of the process integration runtime. 
So is really necessary the step 1.2? 
Step 2.4
And when i Try to add Role. I not find the Application Identifier that begin with "it", so what can i do?

**Comment by xRicardinhox** [comment]
Hello. 
<img width="960" alt="trialSubscriptions" src="https://user-images.githubusercontent.com/9669132/73861674-f7a2d680-4802-11ea-9d29-65ee7276312b.png">
This are the only subscription that I see, what can i do, to have the "Process Integration"

**Comment by gauthamkrishna-sap** [comment]
Hello,

Thanks for the feedback. Can you kindly confirm if your sub account is in Europe Frankfurt region?

Thanks & Regards
Gautham
Sent from my iPhone

On 05-Feb-2020, at 5:34 PM, xRicardinhox <notifications@github.com> wrote:

﻿

Hello.
[trialSubscriptions]<https://user-images.githubusercontent.com/9669132/73861674-f7a2d680-4802-11ea-9d29-65ee7276312b.png>
This are the only subscription that I see, what can i do, to have the "Process Integration"

**Comment by xRicardinhox** [comment]
Hello Gautham 

I look, and my trial subaccount was not in the Europe Frankfurt region, i delete the previes subaccount and create a new in that region, and the process integration option appear... 

Thanks.
