### ISSUE TITLE
Add Localization to a Managed Association with Core Data Services

### ISSUE THREAD

**Issue by MartinStenzigRiz** [SAPDocuments/Tutorials#4560]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-itelo-product-catalog-02.html

Please specify the step you are referring to
The link in step 5 to "More information about localization in CDS on the SAP Help Portal" does not seem to work.

**Comment by renejeglinsky** [comment]
Hi @MartinStenzigRiz,

thanks for pointing that out. I'll fix it. The proper link is: https://cap.cloud.sap/docs/guides/i18n

-René

**Comment by renejeglinsky** [comment]
https://github.com/SAPDocuments/Tutorials/pull/4561

**Comment by thecodester** [comment]
merged
