### ISSUE TITLE
Build Your First Full-Stack App on SAP Cloud Platform

### ISSUE THREAD

**Issue by shefbel** [SAPDocuments/Tutorials#4563]
Mission URL: https://developers.sap.com/mission.scp-5-full-stack.html
Problem: db hdi is not deployed if you follows steps from doc
Additional steps are required:
1. build mta
2. deploy mta

**Comment by MichaelCzcz** [comment]
@shefbel Thank you for your feedback. Unfortunately the link you have provided is for a whole tutorial mission containing several tutorial groups. Could you please provide the link to the tutorial where you encountered this issue? Thank you.

**Comment by qmacro** [comment]
Hello @shefbel - can you please be more specific? Thanks.

**Comment by qmacro** [comment]
Hi @shefbel - perhaps you're otherwise occupied right now, which is no problem. I'll close this right now but if you have something more specific to share, by all means please let us know. Thanks!
