### ISSUE TITLE
Consume the API Proxy in SAP Web IDE

### ISSUE THREAD

**Issue by jubo0001** [SAPDocuments/Tutorials#4571]
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-webide-int.html

Step 7: Create destination for the API Proxy

The additional proper "TrustAll" doesn't exist

Rgds,

Jürgen

**Comment by shilpavij** [comment]
Hello Jurgen,

Try to put your destination in text file and import it. For example.
#
#Mon Oct 22 09:39:39 UTC 2018
Description=API Management Dev Portal
Type=HTTP
TrustAll=true
Authentication=AppToAppSSO
WebIDEUsage=api_mgmt_catalog
Name=apimgmtdevportal
WebIDEEnabled=true
URL=https\://<URL>
ProxyType=Internet

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
@jubo0001 
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
