### ISSUE TITLE
Getting started with the SAP API Business Hub #4508

### ISSUE THREAD

**Issue by ArunDomnic** [SAPDocuments/Tutorials#4574]
the given answer Linda is not correct .so it is still on the continuing and the answer is not valid

_Originally posted by @ArunDomnic in https://github.com/SAPDocuments/Tutorials/issues/4508#issuecomment-581900648_

**Comment by ArunDomnic** [comment]
![API issue ](https://user-images.githubusercontent.com/48125497/73748096-c680c280-477e-11ea-9d17-5adbd2b104e4.jpg)

**Comment by IObert** [comment]
Hi, I'll close this one and answer at #4508
