### ISSUE TITLE
Set Up the SAP HANA Plugin for Microsoft Visual Studio

### ISSUE THREAD

**Issue by wurst0815** [SAPDocuments/Tutorials#4575]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-visual-studio.html

Please specify the step you are referring to
Step 4. 
This works fine for Visual Studio 2017
![image](https://user-images.githubusercontent.com/13557494/73765467-deebdf80-4774-11ea-849c-494ca07fcdaf.png)

But not for Visual Studio 2019
![image](https://user-images.githubusercontent.com/13557494/73765397-c4b20180-4774-11ea-9360-f71367226934.png)

**Comment by JCurrie27** [comment]
Hi wurst0815: I've forward this issue to our engineering teams to investigate. In the meantime, could you log this issue in the Q&A forum to take advantage of the HANA express community support model?

1. Go to https://answers.sap.com/index.html
2. Add your question. In the Select Primary Tag field, search for "express" and select "SAP HANA, express edition"

**Comment by wurst0815** [comment]
Done
https://answers.sap.com/questions/12970978/visual-studio-hana-driver-missing.html

**Comment by wurst0815** [comment]
Okay.. on a newly set up device, the driver doesn't show up anymore on any Visual Studio Version...

Running hdbuninst.exe and afterwards hdbinst.exe again did not help.

**Comment by i067268** [comment]
I have find the same issue when I test it, and I have send it to DEV to check it

**Comment by JCurrie27** [comment]
@i067268; @wurst0815: Since this issue is now with development, and has been logged in the Q&A site at https://answers.sap.com/questions/12970978/visual-studio-hana-driver-missing.html, I'm closing this issue. Let's use the Q&A question to track progress. Thanks.
