### ISSUE TITLE
Set Up the SAP HANA Plugin for Microsoft Visual Studio

### ISSUE THREAD

**Issue by wurst0815** [SAPDocuments/Tutorials#4576]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-visual-studio.html

Please specify the step you are referring to
Step 4
I was not able to connect to a hosted instance of SAP Hana. I guess it is because I am not able to add `Encrypt=true` to the connectionstring using the GUI, but this is mandatory to make the connection work.

**Comment by JCurrie27** [comment]
Hi wurst0815: As with issue 4575, I've forward this issue to our engineering teams to investigate. In the meantime, could you log this issue in the Q&A forum to take advantage of the HANA express community support model?

1. Go to https://answers.sap.com/index.html
2. Add your question. In the Select Primary Tag field, search for "express" and select "SAP HANA, express edition"

**Comment by wurst0815** [comment]
Done 
https://answers.sap.com/questions/12970977/visual-studio-connection-string-parameter-option-m.html

**Comment by i067268** [comment]
It is a server issue for SSL support. I don't find this issue because I ignore SSL conection in my test, I only test NO-SSL connection, I have sent it to dev and wait for response

**Comment by JCurrie27** [comment]
@i067268; @wurst0815: Since this issue is now with development, and has been logged in the Q&A site at https://answers.sap.com/questions/12970977/visual-studio-connection-string-parameter-option-m.html, I'm closing this issue. Let's use the Q&A question to track progress. Thanks.
