### ISSUE TITLE
Get Started with SAP Cloud Platform Rapid Application Development by Mendix

### ISSUE THREAD

**Issue by ralfvath** [SAPDocuments/Tutorials#4583]
Tutorial URL: https://developers.sap.com/tutorials/mendix-onboarding.html

Please specify the step you are referring to
Step 1:
... the hyperlink behind:
Trial Home or go to cockpit.hanatrial.ondemand.com.

is not working!

please check and correct.

**Comment by ShiraManas** [comment]
Hi,
The link has been updated and works now.

Thanks,
Shira

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
