### ISSUE TITLE
Call API Business Hub API from a SAPUI5 Application

### ISSUE THREAD

**Issue by myka1o** [SAPDocuments/Tutorials#4587]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-api-ui5-app.html

Please specify the step you are referring to: Step 7: Add a list

1. Open the view file ### **mta_app/app/webapp/controller/View1.controller.js.**
be mind **View1.view.xml**

**Comment by IObert** [comment]
Good catch!

Thanks for reporting this one.
