### ISSUE TITLE
Map Message Structure

### ISSUE THREAD

**Issue by BerndHerbold** [SAPDocuments/Tutorials#4591]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-convert-message-structure.html

Step 1. The Links to the XSDs are not accessable

**Comment by gauthamkrishna-sap** [comment]
@BerndHerbold The links are fixed now.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
