### ISSUE TITLE
Create an Account on the Gateway Demo System

### ISSUE THREAD

**Issue by calarcon1995** [SAPDocuments/Tutorials#4592]
Tutorial URL: https://developers.sap.com/tutorials/gateway-demo-signup.html

Please specify the step you are referring to

QUESTION  5
Enter the URL of the SAP Easy Access page below and click Validate.

MY ANSWER:
https://sapes5.sapdevcenter.com/
Sorry, that’s incorrect. Please try again.

Fix this bug please

**Comment by IObert** [comment]
Hi,

thanks for opening this issue. 
The system seems alright as the answer you submitted is incorrect. You're already very close, but we're looking for the full URL, e.g. with the path that is being autocompleted.

Thanks,
Marius

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
