### ISSUE TITLE
Get Started with Cloud Integration

### ISSUE THREAD

**Issue by weissdonovan** [SAPDocuments/Tutorials#4593]
Mission URL: https://developers.sap.com/mission.cp-starter-integration-cpi.html

Hi,
I tried following the steps on this guide, but in my trial account I don't have the option to enrol to Cloud Integration; it's simply not there!
How can we test the CPI without buying a license?

Thanks

**Comment by gauthamkrishna-sap** [comment]
Hello,
Can you please check & confirm if your subaccount is in Europe (Frankfurt)) region?
Best, Gautham

**Comment by weissdonovan** [comment]
> Hello,
> Can you please check & confirm if your subaccount is in Europe (Frankfurt)) region?
> Best, Gautham

Hello Gautham, my account is in Mexico, I tried to change it, but could not do it.
do you know where could I check this?

Thanks

**Comment by gauthamkrishna-sap** [comment]
Hello,

I don’t think you can change the region once you’ve created a sub account. Can you kindly create a new sub account in Europe Frankfurt region? You should be able to see Process Integration there.

Best,
Gautham
Sent from my iPhone

On 10-Feb-2020, at 4:11 PM, weissdonovan <notifications@github.com> wrote:

﻿

Hello,
Can you please check & confirm if your subaccount is in Europe (Frankfurt)) region?
Best, Gautham

Hello Gautham, my account is in Mexico, I tried to change it, but could not do it.
do you know where could I check this?

Thanks

**Comment by weissdonovan** [comment]
Will do!

Thanks for the tip!!

**Comment by weissdonovan** [comment]
Problem solved!! thanks a lot!!
