### ISSUE TITLE
Inspect and Test the API Proxy

### ISSUE THREAD

**Issue by myka1o** [SAPDocuments/Tutorials#4594]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-inspect-apiproxy.html

Please specify the step you are referring to
Inspect and Test the API Proxy
Step 1: Inspect the API proxy
After several times retrying previous steps, my Policy Editor looks this way:
![Screenshot_33](https://user-images.githubusercontent.com/60221099/74012590-aaa63800-499b-11ea-9bc2-0a51b6f5ac1f.png)

**Comment by shilpavij** [comment]
Hello,

Please delete the proxy and recreate it and apply the policy template again. There seems to be a problem while applying template.

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
