### ISSUE TITLE
Enable SAP Cloud Platform Open Connectors

### ISSUE THREAD

**Issue by joe-binkley-sap** [SAPDocuments/Tutorials#4596]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-openconnectors-enable.html

Step 2

Question should probably follow the step where you actually go to the application and it appears that
LinkedIn is the "correct" answer, but LinkedIn is not currently offered as a connector.

**Comment by shilpavij** [comment]
Hello,

I understand your point-even I am not able to see linkedin now. Have corrected it.

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
