### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by DuoBelt** [SAPDocuments/Tutorials#4603]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Please specify the step you are referring to

Provide following information:

Module Name: TRAVEL_APP_XXX
Title: TRAVEL_APP_XXX
Click Next.

Namespace   - value is required

**Comment by mervey45** [comment]
Hi @DuoBelt , 

thank you for your feedback. We'll update this asap.
@thecodester Can you merge following pull request: #4610?
Thank you.

Best regards, 
Merve

**Comment by thecodester** [comment]
Done
