### ISSUE TITLE
Discover Sales Order API from S/4HANA Cloud System

### ISSUE THREAD

**Issue by ArunDomnic** [SAPDocuments/Tutorials#4605]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-api-discover.html

The Sales Order – Create, Read, Update, Delete (A2X)  API Not found from the list.
Please provide that API.

**Comment by shilpavij** [comment]
Hello,
You can use any API, these APIs are renamed and for now, you can use https://api.sap.com/api/API_SALES_ORDER_SRV/resource

Regards
Shilpa

**Comment by ArunDomnic** [comment]
When i try to get top 5 sales order lists from that API .it could not fetch it and showing error like server response 500.
![Error Response 500](https://user-images.githubusercontent.com/48125497/74233513-d2293780-4cf0-11ea-83bc-f0b21e952564.JPG)

**Comment by shilpavij** [comment]
Works for me.
![image](https://user-images.githubusercontent.com/44152823/76284746-1e51a280-62c4-11ea-8673-a5bd6b6f94e2.png)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
