### ISSUE TITLE
Tour the SAP Community

### ISSUE THREAD

**Issue by CCFenner** [SAPDocuments/Tutorials#4612]
Tutorial URL: https://developers.sap.com/tutorials/community-start.html

Tutorial is completed but *Mission* not marked as completed.

Profile: https://people.sap.com/fennercc

**Comment by thecodester** [comment]
Do you mean you don;t have the badge in your profile? It takes a week for the badge to appear in profile.

**Comment by CCFenner** [comment]
<img width="987" alt="Bildschirmfoto 2020-02-11 um 09 16 43" src="https://user-images.githubusercontent.com/26137398/74220214-3e834700-4caf-11ea-9eb9-09baa6ed1de8.png">

The "mission" is still listed as 0% completed. I think I need this as a prerequisite for posting a blog (?), does the reviewer see that it's actually completed or do I need to wait a week?

**Comment by thecodester** [comment]
To be honest, not sure what the blogging people see -- I will check. 

Generally, it takes to the end of the week for you to get credit for completing a mission (i.e., getting the badge in your profile, indicating on the missions page)

**Comment by CCFenner** [comment]
Ok, thanks.
To me the "progress bar" is here a bit misleading.
