### ISSUE TITLE
Continuous Integration (CI) Best Practices with SAP – CI/CD Practices

### ISSUE THREAD

**Issue by bvarwig** [SAPDocuments/Tutorials#4618]
Tutorial URL: https://developers.sap.com/tutorials/ci-best-practices-ci-cd.html

Chapter **Feature Branches**:
![image](https://user-images.githubusercontent.com/8438658/74238217-9e8ce400-4cd5-11ea-96d1-50dde91af824.png)

I remember that i read various articles arguing too put source changes as fast as possible back to the main line to avoid merge conflicts. That means to held feature branch small. E.g. you can prepare a new feature in the code, but have the feature still somhow "inactive".

So my suggestion would be to add  a hint to cut feature branches as small as possible. 

Regards Britta

**Comment by wolframK** [comment]
We are currently migrating the CI/CD pages fro the tutorial section to the SAP Helpportal. The new guides are available from [Continuous Integration and Delivery by SAP](https://help.sap.com/viewer/product/CICD_OVERVIEW/Cloud/en-US?task=discover_task).
The CI/CD pages on the tutorial section will be discontinued.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
