### ISSUE TITLE
Set Up a Basic Mock S/4HANA Service

### ISSUE THREAD

**Issue by d023604** [SAPDocuments/Tutorials#4624]
Tutorial URL: https://developers.sap.com/tutorials/cap-cloudsdk-1-mock-service.html

Step 3: Download the API Business Partner JSON. 
A novice might simply expect to click on the URL and save as. 

The additional information _Be sure to use the Raw link to get to the raw file contents before downloading, and keep the .json extension. If you opt for copy/pasting the content into a new file, make sure you only copy the JSON content, and not any comments that might otherwise be rendered by a Chrome extension._ implies that the user has gone to GitHub. 

Perhaps it would be useful to say explicitly that the JSON is to be downloaded from GitHub. Click on the URL to navigate to GitHub . Then follow with the additional information as it currently is.

**Comment by qmacro** [comment]
Thanks @d023604 I've modified the text to clarify. https://github.com/SAPDocuments/Tutorials/commit/526eab9a9aa0790eabcabd52fdc66e846c83c658
