### ISSUE TITLE
Explore Your Generated OData Service

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#4625]
Tutorial URL: https://developers.sap.com/tutorials/odata-07-explore-generated-odata-service.html

Please specify the step you are referring to 4

it still takes multiple tries to build, run, and restart the service before it can be properly delivered through the web into the browser. a little hint to the student wouldn't hurt.

**Comment by greg2git** [comment]
just a comment.

**Comment by thecodester** [comment]
@qmacro FYI
