### ISSUE TITLE
Set Up Business Rules for Determining Equipment

### ISSUE THREAD

**Issue by MartijnHulshofMB** [SAPDocuments/Tutorials#4627]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-businessrules.html

Please specify the step you are referring to: step 2

I cannot import the project from the api business hub;"An error has occurred. Contact technical support." 
![image](https://user-images.githubusercontent.com/60887221/74318736-11519a00-4d7e-11ea-951c-dd0d0a1f5fa5.png)

I have followed the setup guide. When i check the "BUSINESSRULES_APIHUB" connection, it is successful "200: OK".

Can you please look into this? 

Regards, Martijn

**Comment by ArchanaShukla** [comment]
This error comes when the credentials are not correctly used in destination. 200 OK in the destination does not check the real connectivity with the given URL and credentials. Here is also the standard [troubleshooting](https://help.sap.com/viewer/0e4dd38c4e204f47b1ffd09e5684537b/Cloud/en-US/2e715cccd1ce4fd980c9ca23870bc5cb.html)

**Comment by MartijnHulshofMB** [comment]
Thanks. Indeed an issue with the API hub credentials.
