### ISSUE TITLE
Configure Initial Setup for SAP Mobile Cards

### ISSUE THREAD

**Issue by Leoooob** [SAPDocuments/Tutorials#4630]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-digitalexp-mobilecards-1-setup.html

Step: Search the Mobile Services and click on it.

Issue: Mobile Services does not exist in the catalog. It appears that the catalog has been vastly reduced as the screenshot in the tutorial shows 38 different services when searching, however only 9 are available to me.

**Comment by Leoooob** [comment]
i've just checked back after attempting the same in a Neo environment (which didn't work for other reasons) and now there are 16 services available. 

![https://i.imgur.com/SxkzKxE.png](https://i.imgur.com/SxkzKxE.png)

**Comment by jitendrakansal** [comment]
@Leoooob can you check below? 
Go to https://cockpit.hanatrial.ondemand.com/cockpit/#/home/trial >Enter your trial account > click **Entitlements** on left hand side>Subaccount Assignments > select subaccount and click Go.
Do you see **Mobile Services** in the list? (check screenshot)
<img width="1304" alt="Screenshot 2020-02-12 at 9 39 10 PM" src="https://user-images.githubusercontent.com/31536700/74375183-2c54f600-4de0-11ea-9e74-1e822dcc6a69.png">

**Comment by Leoooob** [comment]
@jitendrakansal thanks for the quick reply, I followed your steps and it looks like it's already enabled. However I've only got 17 services available on the cockpit, mobile services is not on there still.

Anything else I could try?

![https://i.imgur.com/bbqsCp0.png](https://i.imgur.com/bbqsCp0.png)

**Comment by jitendrakansal** [comment]
@Leoooob in this case, i need to check with our server colleagues on what is missing. 
Could you send me an email to jitendra.kansal@sapdotcom with your tenant/account details?
