### ISSUE TITLE
Inspect and Test the API Proxy

### ISSUE THREAD

**Issue by k1mset** [SAPDocuments/Tutorials#4631]
Hello all! 

I am working on this series and have come across an issue with implementing the app_id and app_code into the API policy. 

I have signed up on HERE, and generated the codes for each REST and JS (tried both sets, neither work), however they do not seem to work.

When accessing the API through the browser, the file is returned for …/salesTrackerAPI, …/salesTrackersAPI/BusinessPartnerSet, ...salesTrackerAPI/BusinessPartnerSet?$top=10. However when attempting to get the geocode information from …/salesTrackerAPI/BusinessPartnerSet('0100000003') an error is returned.

" {"fault":{"faultstring":"Execution of ServiceCallout CallGeocodingAPI failed. Reason: ResponseCode 401 is treated as error","detail":{"errorcode":"steps.servicecallout.ExecutionFailed"}}} " is the returned error.

I believe it is an issue when attempting to use the app_id and app_code, but feedback is appreciated. Thank you.

**Comment by k1mset** [comment]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-inspect-apiproxy.html

**Comment by shilpavij** [comment]
Hello,

401 one error is issue with your user. in this case it is app id and code. 
It is not correct or may be it has spaces. Kindly copy it in notepad and use it deleting the spaces.

Regards
Shilpa

**Comment by k1mset** [comment]
Hello,

Thank you for your response. I have it copied correctly, however still getting this issue. Where is the HERE api called from in the salesTrackerAPI? Also, on the HERE page you get a JS app_id and app_key, is that they same as app_code?

**Comment by shilpavij** [comment]
Hello,
JS app_id and app_key, is  same as app_code -the names keep on changing.
The here api is called in Step1 -point 5.

Regards
shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
