### ISSUE TITLE
Add a User Task to Your Workflow

### ISSUE THREAD

**Issue by joe-binkley-sap** [SAPDocuments/Tutorials#4632]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-3-add-usertask-cf.html

Step 7:  
A nit, but "Workflow Monitor - Workflow Definitions tile" should really say: "Monitor Workflows - Workflow Definitions tile".

**Comment by AstridHerbst** [comment]
Hi Joe,
Thanks for the find. I have fixed the name.
Best regards,
Astrid
