### ISSUE TITLE
Create a Start Form and its Custom Tile for Your Workflow

### ISSUE THREAD

**Issue by joe-binkley-sap** [SAPDocuments/Tutorials#4633]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-4-approval-ui-cf.html

Step 5 --
"Where do you safe the configuration of your custom tile?
mta.yaml
CommonDataModel.json
app.json"

Should be "save" not "safe".
And, why is this question here? No mention of app.json or any of the other files in this tutorial.

**Comment by joe-binkley-sap** [comment]
looks like this should be several steps down from where it shows up.

**Comment by AstridHerbst** [comment]
Hi Joe,
Thanks for your feedback! I have now fixed the issue and will republish shortly.
Best regards,
Astrid
