### ISSUE TITLE
Inspect and Test the API Proxy

### ISSUE THREAD

**Issue by jakes2255** [SAPDocuments/Tutorials#4634]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-inspect-apiproxy.html

Please specify the step you are referring to: 2 then 4. Pick up the instance id of any entry in the collection and make a get specific call.

URL used is as below:-
.......l/salesTrackerAPI/BusinessPartnerSet('0100000003')

Error I have received is as below:-
`{"fault":{"faultstring":"Execution of ServiceCallout CallGeocodingAPI failed. Reason: ResponseCode 401 is treated as error","detail":{"errorcode":"steps.servicecallout.ExecutionFailed"}}}`

Any guidance on how to get past this is highly appreciated.

All credentials(ES5, encoded) and Here app id and app code are provided, and I was able to retrieve the BusinessPartnerSet, but unable to make specific entry call to fetch lat and long.

Please help.

Thanks,
Jakes

**Comment by jakes2255** [comment]
any updates? Is it possible that this tutorials is now outdated and these steps are no longer working? Please check.

Thanks,
Jakes

**Comment by shilpavij** [comment]
Hello,

I would propose the following.
ES5 is a public system and hence you can create your own user and the same for HERE.

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
