### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#4638]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Please specify the step you are referring to 1

Are those screenshots now obsolete? My page is now showing these:

![image](https://user-images.githubusercontent.com/24355032/74489930-e9088f00-4e94-11ea-9c4b-daae166f1fb4.png)

i'm trying 'Open Connectors' tile instead of 'Process  integration'.

**Comment by gauthamkrishna-sap** [comment]
Hello,
Can you please confirm if your subaccount is in Europe (Frankfurt) region? 
Best Regards, Gautham

**Comment by greg2git** [comment]
account is in Rot and subaccount is in US East.

**Comment by gauthamkrishna-sap** [comment]
Hello,
Kindly create a new subaccount in the Europe (Frankfurt) region, entitle the subaccount with Process Integration services, and try again. You will see the Process Integration tile in the list. 
Thanks & Regards, Gautham

**Comment by greg2git** [comment]
i see, subscriptions are geo specific. thx for the tip.
