### ISSUE TITLE
Feedback on Tutorial: SAPUI5 - Setup the DataSource in the local application

### ISSUE THREAD

**Issue by yongjiu2006** [SAPDocuments/Tutorials#464]
HI

Please check the following screenshot. 
The link for Create a new project doesn't work.

![2016-06-28_16-26-22](https://cloud.githubusercontent.com/assets/9588233/16408822/18ea0896-3d4d-11e6-9359-1b3f917b34cd.png)

BR
Benny

**Comment by jonathanbaker7** [comment]
Good catch.  The URL was missing, I added it.  Fixed!
