### ISSUE TITLE
Develop SAP SAPUI5 Application for SAP Cloud Platform on Cloud Foundry

### ISSUE THREAD

**Issue by I079506** [SAPDocuments/Tutorials#4640]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-fioriapps-create.html

Please specify the step you are referring to
Step 9 shall say:
In your text editor you need to add the following suffix to the URL that you saved in step 8: /mynamespaceFioriDemo-1.0.0/index.html
For future reference, bear in mind that this is the construct of the final URL: <URL_from_application_overview_page>/<mynamespace><project_name>-<application_version>/index.html

**Comment by Paolaufer** [comment]
Hi, 
I have changed the wording of the note and left the final URL construct.

**Comment by thecodester** [comment]
@Paolaufer Did you publish yet and open a pull request? If so, you can paste it into a comment here and I can close the issue.

**Comment by thecodester** [comment]
@Paolaufer Can this be closed?

**Comment by Paolaufer** [comment]
We are testing the tutorial again to check this out.

**Comment by MichaelCzcz** [comment]
@Paolaufer Any updates?

**Comment by Paolaufer** [comment]
I asked the devs to answer (previously to answer me, but failing that to answer on the issue itself).

**Comment by thecodester** [comment]
@idogoren can you help here?

**Comment by Paolaufer** [comment]
OK... made the change and created a PR
https://github.com/SAPDocuments/Tutorials/pull/5598

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
