### ISSUE TITLE
Create and expose a custom CDS view

### ISSUE THREAD

**Issue by bvrajan12** [SAPDocuments/Tutorials#4641]
Tutorial URL: https://developers.sap.com/tutorials/abap-extensibility-custom-cds.html

Please specify the step you are referring to:
We are  trying to follow this tutorial in system https://xt1-715.wdf.sap.corp/ui?sap-client=715&sap-language=EN (XT1 is the Extensibility Test System). We see two tiles "Custom CDS Views - to be deprecated" and another tile "Custom CDS Views". Using "Custom CDS Views" tile we created a custom CDS view for API. We want to expose this as a OData Service. But in this tile we do not see the "General" Tab which is suggested by this blog. In the deprecated tile we were able to see this General tab, but we were not able to go to the "Edit" mode. Any suggestions?
Rajan & Pritham

**Comment by mervey45** [comment]
Hi @bvrajan12,

thank you for your message. Can you please send me a screenshot of your problem? 

Thank you. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
@bvrajan12 Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
