### ISSUE TITLE
Create Table Persistence and Generate Data

### ISSUE THREAD

**Issue by JanRohde80** [SAPDocuments/Tutorials#4642]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-persistence.html

Please specify the step you are referring to
3. ZLOCAL will be added as software component. Click Next >.
--> doesn't work (Message: Software component ZLOCAL does not exist), see screen shot
![image](https://user-images.githubusercontent.com/60812217/74563469-293b4080-4f6d-11ea-8835-08d8369dd432.png)

**Comment by WKRazik** [comment]
Try  Software component  : HOME

**Comment by JanRohde80** [comment]
Hi

I already tried HOME. :-(
It doesn't work.

Regrads
Jan


Razik <notifications@github.com> schrieb am Fr., 14. Feb. 2020, 22:06:

**Comment by JanRohde80** [comment]
Hi

Second try. Today it work with "ZLOCAL"
Ticket can be closed.

Thank you!

Regards
Jan

Am Fr., 14. Feb. 2020 um 22:48 Uhr schrieb Jan Rohde <
jan.rohde.80@googlemail.com>:
