### ISSUE TITLE
Create ABAPDoc Comments in Your Class

### ISSUE THREAD

**Issue by WKRazik** [SAPDocuments/Tutorials#4643]
Sorry but i have an issue , the below is not validated as a valid answer
"! @parameter PLANETYPE | Type of plane
i don't know why ? 

Tutorial URL: https://developers.sap.com/tutorials/abap-dev-create-abapdoc.html
Step 9

**Comment by julieplummer20** [comment]
Hi WKRazik - I commented in your other (identical) post. 
Please close this duplicate.
Best wishes, Julie.
