### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by JanRohde80** [SAPDocuments/Tutorials#4644]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-data-model.html

Everything works fine as described in the tutorial. 

I have one additional question:
How can I translate the labels of the CDS - UI annotations with the ADT (without SAP GUI & SE63)?

Maybe you can add it to the tutorial.

I don't find any information on it. I not sure if there is an option.
But at the ABAP Cloud Environment is no SAP GUI access. I have only the ADT to do it. 

Thanks a lot!

Regards
Jan

**Comment by mervey45** [comment]
Hi @JanRohde80 ,

labels, for e.g. column labels, field Labels, etc. can be specified while creating CDS Views. The column and fields can pick up labels from their corresponding data elements. This ensures that the translations for the data element labels are available to the fields and thus no separate translation needs to be done.

However, it is also possible to add fields in field lisst as literals that do not refer to any data element in particular. In such cases, the field labels can still be specified using the Annotation “@EndUserText.label:”

I hope, I could help you. 

Best regards, 
Merve

**Comment by JanRohde80** [comment]
Hi Merve,
sorry, that doesn't help. I know how to define labels and how to create
data elements. But I find no way to translate the texts in ATD (ABAP in
Eclipse). As I described, in the ABAP Cloud Environment i have no SAP GUI
access. So my question stay: How can I add different languages to my own
appliaction in the ABAP Cloud Environment incl. CDS View Labels, UI Labels,
Data Elements, Messages etc.? (without SAP GUI, only with ADT)
Otherwise I can't write a custom application on the SCP - ABAP Cloud
Environment in my company context, because german and english are mandatory
languages for each application.
Thank you!

Regards
Jan



Am Fr., 21. Feb. 2020 um 10:37 Uhr schrieb Merve Temel <
notifications@github.com>:

**Comment by mervey45** [comment]
Hi @JanRohde80 , 

sorry for the misunderstanding. For translations, we also have this mission: https://developers.sap.com/mission.abap-dev-factory-calendar.html. This mission describes how to add translations for public holidays in a factory calendar. In tutorial: https://developers.sap.com/tutorials/abap-environment-text-table.html in step 4.9 you learn how to add a translation for a public holiday. 

Is this what you are looking for? 
I hope, I can help you.

Thank you.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
@JanRohde80 Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by hansnf** [comment]
@mervey45 Can you provide a link to a tutorial solving the problem described here? In the first I can not the creation of texts for labels and the link to the second is dead.
