### ISSUE TITLE
Image Classification with SAPUI5

### ISSUE THREAD

**Issue by raz-korn** [SAPDocuments/Tutorials#4655]
Tutorial URL: https://developers.sap.com/tutorials/ml-fs-sapui5-img-classification.html

Please specify the step you are referring to - Step 1

This tutorial cannot be completed as ti references deprecated APIs that do not provide URLs.
I was not able to find replacement APIs (looks like all SAP Leonardo ML APIs on API Business Hub are deprecated).

![image](https://user-images.githubusercontent.com/6040433/74763283-35ceda00-5288-11ea-96e3-8c543651bfc6.png)

**Comment by Sygyzmundovych** [comment]
This API is indeed deprecated, but click **Continue** and you could complete the tutorial.

But with the deprecation of these APIs and their movement to Data Intelligence we are going to remove these tutorials soon.
