### ISSUE TITLE
Prepare the Portal Environment for Creating Sites

### ISSUE THREAD

**Issue by I075818** [SAPDocuments/Tutorials#4657]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Please specify the step you are referring to
Hi colleagues,
    I can subscribe the portal in my trail account. but in our dev environment, I cannot find it in the subscriptions. Do I need any authorization or any settings?

**Comment by IrisSasson** [comment]
Hi, 
You can follow this document for required permissions to have Portal in your productive env: https://www.sap.com/documents/2019/08/6c6b960b-5e7d-0010-87a3-c30de2ffd8ff.html search for **Entitlements** part

If you have any problem, you can email me. Please note this issues should be used for problems in the started scenario and less for generic questions like this one..
Thanks
Iris

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
