### ISSUE TITLE
Create Extension Controls with NativeScript in an MDK App

### ISSUE THREAD

**Issue by pjalbrz16** [SAPDocuments/Tutorials#4661]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-dev-kit-slider-extension.html

Please specify the step you are referring to : Step 6

Hello,
I tried to use the code explained in this section but I feel like I am missing some JS imports.
I do not find BaseControl and BaseObservable.
Also I installed all the dependecies with MDKDependeciesInstaller but I cannot import tns-core-modules. Should I install tns with npm in my .mdkproject folder ?

Is is possible that I missed some steps somewhere ?

Kind regards,
pjalbrz16

**Comment by jitendrakansal** [comment]
@pjalbrz16 
could you tell what is MDK SDK you are trying with? Latest MDK SDK is 4.1.1 (you can download the latest from here https://developers.sap.com/trials-downloads.html?search=mobile%20development%20kit). 

could you share a screenshot from dependencies installer window? 
could you also check  tns --version ? 
We'll need to see what's the exact error they get when calling the create-client command.

**Comment by pjalbrz16** [comment]
Hello again,

I solved my problem ! It was my stupid mistake, I used a wrong path.
Everything is working as it is supposed to.

Thanks for this tutorial !
