### ISSUE TITLE
Fundamentals of the Cloud Foundry Environment

### ISSUE THREAD

**Issue by 3llino** [SAPDocuments/Tutorials#4671]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-fundamentals.html

In Step 2 IaaS definition differs from that present  in step 2 of "https://developers.sap.com/tutorials/cp-explore-cloud-platform.html": "The cloud provides the hardware, the customer provides the Operating System and everything else."
Thank You for the material.

**Comment by IObert** [comment]
You are absolutely right, the definition was incorrect (misleading at best). I fixed it.

Thanks for reporting!
