### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by jfilak** [SAPDocuments/Tutorials#4672]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html

Please specify the step you are referring to;

The link https://www.sap.com/hana-express-support does not exist.
The non-working link is at https://hub.docker.com/_/sap-hana-express-edition?tab=resources

**Comment by JCurrie27** [comment]
Thanks for bringing this to our attention. I've asked our Docker team to remove that non-functioning "Support" link from [https://hub.docker.com/_/sap-hana-express-edition?tab=resources](https://hub.docker.com/_/sap-hana-express-edition?tab=resources).
