### ISSUE TITLE
Generate Custom OData Client Library with SAP Cloud SDK's Generator

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#4673]
Tutorial URL: https://developers.sap.com/tutorials/cloudsdk-js-generator.html

The headline or the abstract that is visible on the [SAP Cloud SDK tutorial overview page](https://developers.sap.com/topics/cloud-sdk.html#tutorials) should mention that this tutorial is for the JavaScript version of the SDK.

**Comment by mr-flannery** [comment]
Hi Gregor, thanks for the suggestion! We will take a look at it.

**Comment by FrankEssenberger** [comment]
Added a `for JavaScript` in the title in one open PR we have currently:
https://github.com/SAPDocuments/Tutorials/pull/4666

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
