### ISSUE TITLE
Enable Essential Neo Services

### ISSUE THREAD

**Issue by arguapacha** [SAPDocuments/Tutorials#4677]
Tutorial URL: https://developers.sap.com/tutorials/cp-enable-essential-neo-services.html

Step 2 is requiring a connection to a NEO environment, but the creation of the trial account does not allow to create NEO environments, only Cloud Foundry ones. As a result, the created URL does not work.

![image](https://user-images.githubusercontent.com/1663486/74956937-d500e800-53d4-11ea-8995-d3164e405221.png)

**Comment by jarjarbentley** [comment]
My apologies, these tutorials should have been removed as we are turning off Neo services as we activate Cloud Foundry based services.  please give this tutorial a try:  https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html
