### ISSUE TITLE
Create an SAP Fiori App Consuming HubSpot Data

### ISSUE THREAD

**Issue by joe-binkley-sap** [SAPDocuments/Tutorials#4680]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-openconnectors-create-fioriapp.html

Several comments on this.
Step 1: It would be useful to indicate that Check Connection will returns "404: Not Found" and creating a connection clone that includes the end of the URL ("/<account_id>trial/HubSpotCRM/basic-companies") is a good way to test and will return a "200: OK"

Step 2.5 Shows view name changed to App, but later the file is View1.view.xml.

Step 2.8 Shows the resource name as Basic_Companies but in map fields tutorial the name basic-companies was used. That's easy to miss and without the connection test i mentioned in step 1, it's a little hard to discover the erro later on.

Step 2.10 Extra "<" in the copy source. "<<Table"

Step 3 -- Suggest adding a third step to successfully deploy to a CF subaccount.

**Comment by shilpavij** [comment]
Thanks for all your suggestions. We will incorporate these once APIM will go on CF so that the tutorial is updated once.

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
