### ISSUE TITLE
Deploy SAP HANA as a Service

### ISSUE THREAD

**Issue by vsiatr** [SAPDocuments/Tutorials#4682]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-deploying-haas.html

Step 2: Create a new instance of SAP HANA Service

issue: No SAP HANA Service available in Marketplace.
Also, one cannot be created through CLI

![hana issue](https://user-images.githubusercontent.com/19407989/75029491-ce44a480-54aa-11ea-8604-65c4f6ed8928.png)

**Comment by jung-thomas** [comment]
Please see the prerequisites in the tutorial:
**You have a productive account with entitlement to the SAP HANA Service in Cloud Foundry
This tutorial cannot currently be completed with a trial account.**

If SAP HANA Service doesn't show up in the marketplace this means your productive account does not have the entitlement.
