### ISSUE TITLE
Install the SAP Cloud Platform SDK for iOS

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#4685]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-hcpms-install-sdk.html

I'm running MacOS Catalina in Version 10.15.3 (19D76). When I open the "SAP Cloud Platform SDK for iOS Assistant" for the first time I get the following error message:

![Screenshot 2020-02-24 at 09 32 57](https://user-images.githubusercontent.com/2639535/75143485-69c95580-56f5-11ea-8292-e3299cdb6f70.png)

I had to use the "Open Anyway" button in the System Preferences --> Security --> General to allow opening the app. I would think that together with the support of Apple SAP can do better here or?

**Comment by KevinMuessig** [comment]
Which version of the SDK are you using? The version 4.0.10 as described in the tutorial is not notarized yet, version 5.X is notarized (Technology got released 2019 Apple). With the notarized version of the new SDK 5.X you shouldn't see that issue anymore.

**Comment by gregorwolf** [comment]
I can confirm that also with version 4.0.9 the error didn't occur anymore.
