### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by sbenoit99** [SAPDocuments/Tutorials#4687]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html

Please specify the step you are referring to "Step 4: Create a user credential"

Not sure if it was only me but I faced some difficulties with the tutorial to be able to connect to the Gmail SMTP. I'd recommend to add some comments if not sub-step to add the Google Root Certificate. Also for me even with the certificate added to the Keystore I was only able to use "Plain User/Password", since "Encrypted User/Password" is sending the java error "javax.mail.AuthenticationFailedException: No authentication mechanisms supported by both server and client". I am interested to know if you have a solution for that.

But thank you for the tutorial it's really helpful!

Sebastien Benoit

**Comment by lalit74u** [comment]
Hey Sebastien,

Did you get any fix by now ?

In step 4, i just used the credentials of CPI Trial account(P id and password, which is linked to my gmail id)

But i am getting error at step 8 - Could not convert socket to TLS;

are you able to run this tutorial completely?

Thanks,
Lalit

**Comment by fegutieri** [comment]
> Hey Sebastien,
> 
> Did you get any fix by now ?
> 
> In step 4, i just used the credentials of CPI Trial account(P id and password, which is linked to my gmail id)
> 
> But i am getting error at step 8 - Could not convert socket to TLS;
> 
> are you able to run this tutorial completely?
> 
> Thanks,
> Lalit

Same problem here Lalit! Let's wait an answer

**Comment by gauthamkrishna-sap** [comment]
Dear Lalit and Sebastian,
Please use the **Connectivity Tests** feature in the **Monitor** tab of your tenant to verify the connection. 

In **Connectivity Tests** Select **SMTP** tab and fill the details below. 
Host: smtp.gmail.com
Port: 587
Protection: STARTTLS Mandatory
Authentication: Plain Username/password
Credential Name: select the credential where you added your Gmail user name and password. 

Uncheck the other two options below and run a test. You should see a successful response from the Gmail server, which means connectivity is possible. 

I will add this as a troubleshooting step in the tutorial. Thanks for the feedback. 

if you have issues, please let me know. 

Best,
Gautham

**Comment by lalit74u** [comment]
Thanks Gautham for detailed response.

Issue is fixed now.

I was able to do connection test successfully.

however, i would like to highlight few points for the benefit of other users who are beginner in CPI like me.

1. While connection test was successful finally, it took me few iterations to reach there, for example, in tutorial step 4, while creating user credential, for field user, author provides I user ie I046103. I did same thinking that it will automatically map to gmail id of my P user - but i had to fix it by providing gmail id in user field  - so this is the first catch

2. even minor adapter setting plays a big role in success / failure, and i have noticed it with all adapters types including mail adapter - and this is frustrating. For example, in tutorial step 5, authentication method is Encrypted User/Password, but Gautham has suggested to test with Plain Username/password - this also caused me error - i fixed it with changing Authentication in iFlow as Plain Username/password.

Afterall, this all helped me to learn.

Thanks Gautham once again

**Comment by lalit74u** [comment]
also, if you are using your personal gmail id, you have to allow less secure apps to login to your account. After completing tutorial, protect to gmail again, otherwise it may be a security lapse for your gmail.  :D

**Comment by fridtjof1** [comment]
I tried this today and sat my gmail to allow less secure apps.  I was not able to connect.
I received different error messages and it seems like gmail server is refusing me to connect.
Was not able to test this scenario then.

**Comment by gauthamkrishna-sap** [comment]
Did you try the connection test feature available in the **Monitor** section? If yes, can you please share a screenshot of the details that you used to run the connection test?

**Comment by gauthamkrishna-sap** [comment]
@lalit74u thank you for the feedback. Yes, it can be quite tricky sometimes. Have you tried using the Gmail connector in Open Connectors service? This is more of an API based approach for connecting and you might prefer this. It is available on trial as well, please try it out and let me know what you think :)

**Comment by lalit74u** [comment]
Thanks Gautham  , I will explore it

**Comment by fridtjof1** [comment]
@gauthamkrishna-sap    The best would be if you could try to execute the whole test again and update all steps.   I gave up trying to hack my gmail account in order to make the SAP integration work.
I mostly got authentication issues even I knew that password and ID was correct.   
It seems like gmail refused the SAP trial account to logon to my gmail even though I turned off the secure mode.    Test it and see if you are able to do it.   As the task-scenario is defined now, it won't work.

**Comment by gauthamkrishna-sap** [comment]
@fridtjof1 can you please give me a brief overview of the steps you tried? We regularly demo with gmail accounts and there have been no issues, so I am curious to know where you got stuck.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by zhmq0124v** [comment]
In case you hit this error, please refer to the following blog and use Google App Password to connect to Gmail.
https://blogs.sap.com/2020/01/15/cpi-gmail-smtp-integration/comment-page-1
