### ISSUE TITLE
Set Up SAP Mobile Cards

### ISSUE THREAD

**Issue by sorenviggo** [SAPDocuments/Tutorials#4690]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-setup.html

Please specify the step you are referring to:
Step 1:
I have provisioned a trial Cloud Foundry account, but cannot assign the service 'Mobile Services' via Service Marketplace. 
In the guide there are 38 available services. 
I only have 13 - which does not include 'Mobile Services'.
What am I missing ?

Thx and Best regards, 
Søren Hansen

**Comment by sorenviggo** [comment]
After a while I got all the services. Maybe there is some waiting time after you setup the account, before all services are available.
Best regards,
Søren Hansen

**Comment by thecodester** [comment]
@sandeep-tds Maybe we should give people a heads up in the tutorial that it might take a while or whatever they need to know?

**Comment by sandeep-tds** [comment]
@sorenviggo Thank you for bringing the issue to our notice.

**Comment by sandeep-tds** [comment]
> @sandeep-tds Maybe we should give people a heads up in the tutorial that it might take a while or whatever they need to know?

That's a wonderful suggestion @thecodester. I will verify the time with the development team and make the necessary changes. 

Thank you
