### ISSUE TITLE
Inspect and Test the API Proxy

### ISSUE THREAD

**Issue by 2020guyl** [SAPDocuments/Tutorials#4693]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-inspect-apiproxy.html

Please specify the step you are referring to

**Comment by MichaelCzcz** [comment]
@2020guyl Hello, could you please state the nature of the issue with this tutorial? Thank you.

**Comment by 2020guyl** [comment]
I'm sorry, but this is a mistake. I encountered a difficulty in tutorial 6, step2: testing the api proxy.My configuration is not the same as your step 1 because I don't have any "Products associated". Can you explain me how to activate "eCommerceProduct".

**Comment by shilpavij** [comment]
Kindly elaborate, if you are not following the tutorial kindly tell me what steps you executed and what you are not able to test.

I think you, you have an API proxy and you are not able to test it? what is this API proxy pointing to?

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
@2020guyl Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
