### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by joe-binkley-sap** [SAPDocuments/Tutorials#4694]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Step 1 -- "Process Integration" is not available in the US East trial landscape.

**Comment by gauthamkrishna-sap** [comment]
Hello,
Can you please create a new subaccount in Europe (Frankfurt) region and try the process? We offer Process Integration trial in Europe region only.
Thanks & Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
