### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by joe-binkley-sap** [SAPDocuments/Tutorials#4695]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Step 4 -- XML error message when I try to run this -- Insufficient scope for this resource

Notes:
1.) The Tenant_Administrator Role Collection is assigned to my user
2.) the three roles (AuthGroup_Administrator, AuthGroup_BusinessExpert, AuthGroup_IntegrationDeveloper) are assigned to the Tenant_Administrator Role Collection.
3.) Attempting this in the Europe trial landscape

**Comment by joe-binkley-sap** [comment]
Resolved after closing browser and re-opening. Perhaps this is related to stale credentials?When it did not work, i had not been challenged to login again.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
