### ISSUE TITLE
Maintain a Communication Arrangement for Inbound Communication

### ISSUE THREAD

**Issue by D029515** [SAPDocuments/Tutorials#4696]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

I have done the tutorial an wonder how I can make use of the communication arragement. Are there any tutorials available showing how to use a communication arragement?

**Comment by mervey45** [comment]
Hi @D029515 ,

a communication arrangement helps you to configure the electronic data exchange between the system and a communication partner .
Here is the link to the documentation![image](https://user-images.githubusercontent.com/27953324/75545848-a794e980-5a27-11ea-9e34-c20556c44671.png)

We also have this example for outbound communication: 
https://developers.sap.com/tutorials/abap-env-create-comm-arrangement-api.html

Do you have any further questions?

Best regards, 
Merve

**Comment by D029515** [comment]
Hi Merve,

thanks a lot for your quick answer. Unfortunately I did not get the docu link. Could you please re-send it?

Yes, I have another question: As part of the tutorial I created a communication user. What authorities does this user have? I was not able to find any docu on this nor the place where communication users get their authorizations assigned.

Thanks a lot in advance,
Claudi

**Comment by mervey45** [comment]
Hi @D029515 ,

here is the general link to the documentation: https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/e34a329acc804c0e874496548183682f.html 

Communication arrangement: https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/fab3fd449cf74c6384622b98831e989e.html 

Maintaining communication user: https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/eef80dda3867461c92ac1273689ed36f.html

Best regards,
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
