### ISSUE TITLE
Bookmark button broken on some tutorials / missions

### ISSUE THREAD

**Issue by boghyon** [SAPDocuments/Tutorials#4698]
Visit e.g. https://developers.sap.com/mission.sapui5-cf-first.html

Click on the bookmark button:  
![developers sap com_mission sapui5-cf-first](https://user-images.githubusercontent.com/12143247/75436414-cd9d8980-5954-11ea-968e-d9ea42209f40.gif)

Console reports a 400 POST error:
![developers sap com_mission sapui5-cf-first clicking bookmark fails](https://user-images.githubusercontent.com/12143247/75436909-a0051000-5955-11ea-8f16-e6f7347a454b.gif)

Reproducible in all browsers.

**Comment by thecodester** [comment]
I will pass this along, though I am able to set bookmarks fine and do not get this error

**Comment by boghyon** [comment]
Interestingly, it's only https://developers.sap.com/mission.sapui5-cf-first.html that I can't bookmark. All other tutorial pages seem to work.

**Comment by thecodester** [comment]
When I log in I can create bookmarks fine, even on those pages. Are you still having an issue? Can you describe exactly the problem? Do you see the icon? Can you click it?

**Comment by boghyon** [comment]
Yes, the issue is still reproducible with my account.
* I tested with plain stable Chrome without any extensions or flags enabled.
* P-User

When I click on the bookmark icon, the console reports above error.

**Comment by boghyon** [comment]
Here is another tutorial (mission) I can't bookmark: https://developers.sap.com/mission.cap-s4hana-cloud-extension.html

@thecodester I wonder if I'm the only one having this issue. I even created a dummy account with which I could bookmark all tutorials I mentioned here.

**Comment by thecodester** [comment]
I just can't reproduce. I will let IT know about it and be on the lookout for other cases and do some testing. Sorry for the inconvenience.
