### ISSUE TITLE
SAP HANA XS Advanced, Creating a Node.js Module

### ISSUE THREAD

**Issue by alteraugem** [SAPDocuments/Tutorials#4701]
Tutorial URL: https://developers.sap.com/tutorials/xsa-xsjs-xsodata.html

Please specify the step you are referring to: Step 3
server.js and testrun.js are not available in the generated core_xsjs folder. The structure is also different, no lib nor test folder.

**Comment by jung-thomas** [comment]
Are you sure that in step 1, third screenshot that you checked the Enable XSJS Support?  Not checking this option in the wizard would result in the missing files/folders as you describe.

**Comment by alteraugem** [comment]
I am quite sure I did. However, I’ll try to rebuild from scratch later.

 

Von: Thomas Jung <notifications@github.com> 
Gesendet: Freitag, 28. Februar 2020 20:01
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: alteraugem <markus.alterauge@hamburg.de>; Author <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] SAP HANA XS Advanced, Creating a Node.js Module (#4701)

 

Are you sure that in step 1, third screenshot that you checked the Enable XSJS Support? Not checking this option in the wizard would result in the missing files/folders as you describe.

**Comment by alteraugem** [comment]
Hi Thomas,

 

looks like a problem with my HXE. After restarting HDB everything looks fine. Thx.

 

Von: Thomas Jung <notifications@github.com> 
Gesendet: Freitag, 28. Februar 2020 20:01
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: alteraugem <markus.alterauge@hamburg.de>; Author <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] SAP HANA XS Advanced, Creating a Node.js Module (#4701)

 

Are you sure that in step 1, third screenshot that you checked the Enable XSJS Support? Not checking this option in the wizard would result in the missing files/folders as you describe.

**Comment by alteraugem** [comment]
all objets available after reboot of HXE
