### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by austinkloske22** [SAPDocuments/Tutorials#4702]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

operating system ubuntu 19.04:

Please specify the step you are referring to
1. command `cds build/all `
2. no manifest.yaml generated

![image](https://user-images.githubusercontent.com/45456027/75577687-21c56e00-5a28-11ea-9a5e-b8fe8df3a558.png)

**Comment by iwonahahn** [comment]
Thank you for the reported issue. Could you please try again with the latest release of our tools and get back to us if the issues still exist. Thank you and best regards, Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
