### ISSUE TITLE
SAP HANA XS Advanced - Clone and run SHINE applications

### ISSUE THREAD

**Issue by alteraugem** [SAPDocuments/Tutorials#4703]
Tutorial URL: https://developers.sap.com/tutorials/xsa-ml-e2e-access-shine.html

Please specify the step you are referring to Step 6:

This tutorial seems a bit outdated as the structure of the SHINE app is different nowadays. (js. vs. xsjs)

**Comment by luizcarlospedrosogomes** [comment]
###OFF_TOPIC
SAP HANA XS Advanced is good alterantive, using CDS (https://cap.cloud.sap/docs/) the result not is better?

**Comment by jung-thomas** [comment]
Tutorial has been updated to reflect the current state of SHINE and HANA 2.0 SPS 04.
