### ISSUE TITLE
Unable to install @sap/cds-dk

### ISSUE THREAD

**Issue by manjunathgudisi** [SAPDocuments/Tutorials#4705]
Hi
Im getting warnings & errors while installing the npm module @sap/cds-dk.

`npm set @sap:registry=https://npm.sap.com`
`npm install -g @sap/cds-dk`

Here is the warnings & errors log
------
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code EINTEGRITY
npm ERR! sha512-fcCedZ/W92oxMzNI2e8c0jhr9Kh/Q8o5ELj81NPyo+Xm9Q4lIEzikgZ6a/Ci9XrH/f+CGOqDL4DXS+AoYww88Q== integrity checksum failed when using sha512: wanted sha512-fcCedZ/W92oxMzNI2e8c0jhr9Kh/Q8o5ELj81NPyo+Xm9Q4lIEzikgZ6a/Ci9XrH/f+CGOqDL4DXS+AoYww88Q== but got sha512-NtKDRX08NLXVqnvCkxK8WaJajDYoR8FH/C0c2AUw5DPfA9peNK5bYqRpdJRC7D398fIpfSCwh4a6G1Y0oH9nnQ==. (17633 bytes)
npm ERR! code EINTEGRITY
npm ERR! sha512-uHdbvD/2MqXH8suqHwlk2BgUxvZaxYiNLkYVRVPZYwQ2mNgnVDyvwKGqdQQ8k56Le+dnlJHzeorhciP3TuqXXw== integrity checksum failed when using sha512: wanted sha512-uHdbvD/2MqXH8suqHwlk2BgUxvZaxYiNLkYVRVPZYwQ2mNgnVDyvwKGqdQQ8k56Le+dnlJHzeorhciP3TuqXXw== but got sha512-s6giiC7whCO6gnVc9cYSHKCSPv704q2N132r8MQA/Yt3HD1+aAYqqqyabpd5BAasVturVfhNv2gcfVaL0DtrpQ==. (14858 bytes)
npm WARN tarball tarball data for @sap/odata-commons@2.1.1 (sha512-hvdF9Lj466R3lnvmBdYk+SbAhWDSJDKsGxF8oE1jET/VJHeZClhx+ZxEVAVDOo+xMgWQXjUdvWMTRnUARXt/WA==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/odata-commons@2.1.1 (sha512-hvdF9Lj466R3lnvmBdYk+SbAhWDSJDKsGxF8oE1jET/VJHeZClhx+ZxEVAVDOo+xMgWQXjUdvWMTRnUARXt/WA==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/cds@3.16.2 (sha512-hVjuhC0J5tE180wj+yzRImooB9yoJ81qa0kqcQUdx2qWgBci0HP4s9QoQa5CaSgfJP0fwLgvdVR9SpvqkHtU1w==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/cds-compiler@1.17.1 (sha512-sNLSL7Hoy5Z/Y5jlMRO12t8FZhbLEKsj9ySi7/40+xR2LqPbQPR8z5kzD5NSJImeADpiPbKulwU3ksOpJCH3Sg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/cds-compiler@1.17.1 (sha512-sNLSL7Hoy5Z/Y5jlMRO12t8FZhbLEKsj9ySi7/40+xR2LqPbQPR8z5kzD5NSJImeADpiPbKulwU3ksOpJCH3Sg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/cds@3.16.2 (sha512-hVjuhC0J5tE180wj+yzRImooB9yoJ81qa0kqcQUdx2qWgBci0HP4s9QoQa5CaSgfJP0fwLgvdVR9SpvqkHtU1w==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/cds-sqlite@1.16.0 (sha512-gwDCATyTao2+K050KHbkmJjSeL7684SfF33/7C7cYWJLeOi68WY7L9PXA9QSAzPtqjfDaiGSer8Lm7Ug6WeCYA==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/cds-ql@1.17.0 (sha512-2aNbWfKo+DAb0ub8VXBFVkWDH55jc2ncdjTTz7x/xuajtSbfoTLGS5686vUN2Q8M4x9gXkSVSahDFsYLC+7lmg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/cds-hana@1.16.0 (sha512-okh9SxWtsNCWmkTEC8UTNdywDGw8ppS7wOzOcl2pN4SkrAglegeOEQhgQMFB3NJLgXEdGpRvR1MuRQZ7BSi+XQ==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/cds-sql@1.16.0 (sha512-G3PkF/KiCiYEOcTMpWplAYXAX61Iwf9EDjfHCsn5HoPKlL6Eh0+pZiMot7Yy/x4VqUWAhMUwOLF8CwMYaIpKVQ==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/generator-cds@2.7.0 (sha512-qjYQZWj/b7agKL/lUV1llx16ux37BNUz5bzC375Hr4H/DYLluYzWIKteMqcGpTuB+spI8eM4myYgt7YFFe0PLQ==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/cds-compiler@1.17.1 (sha512-sNLSL7Hoy5Z/Y5jlMRO12t8FZhbLEKsj9ySi7/40+xR2LqPbQPR8z5kzD5NSJImeADpiPbKulwU3ksOpJCH3Sg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/cds-sqlite@1.16.0 (sha512-gwDCATyTao2+K050KHbkmJjSeL7684SfF33/7C7cYWJLeOi68WY7L9PXA9QSAzPtqjfDaiGSer8Lm7Ug6WeCYA==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/cds-ql@1.17.0 (sha512-2aNbWfKo+DAb0ub8VXBFVkWDH55jc2ncdjTTz7x/xuajtSbfoTLGS5686vUN2Q8M4x9gXkSVSahDFsYLC+7lmg==) seems to be corrupted. Trying one more time.
npm ERR! code EINTEGRITY
npm ERR! sha512-okh9SxWtsNCWmkTEC8UTNdywDGw8ppS7wOzOcl2pN4SkrAglegeOEQhgQMFB3NJLgXEdGpRvR1MuRQZ7BSi+XQ== integrity checksum failed when using sha512: wanted sha512-okh9SxWtsNCWmkTEC8UTNdywDGw8ppS7wOzOcl2pN4SkrAglegeOEQhgQMFB3NJLgXEdGpRvR1MuRQZ7BSi+XQ== but got sha512-k4uOam/gDDZKJfxgAKhHg7oFukWUZBG2iGitmWmOgZ+IMZBmiZLuFyNE2zFDCrMysMLC3XDvbX8J8x1F5dykgQ==. (23758 bytes)
npm WARN tarball tarball data for @sap/cds-compiler@1.17.1 (sha512-sNLSL7Hoy5Z/Y5jlMRO12t8FZhbLEKsj9ySi7/40+xR2LqPbQPR8z5kzD5NSJImeADpiPbKulwU3ksOpJCH3Sg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/cds-sql@1.16.0 (sha512-G3PkF/KiCiYEOcTMpWplAYXAX61Iwf9EDjfHCsn5HoPKlL6Eh0+pZiMot7Yy/x4VqUWAhMUwOLF8CwMYaIpKVQ==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sap/generator-cds@2.7.0 (sha512-qjYQZWj/b7agKL/lUV1llx16ux37BNUz5bzC375Hr4H/DYLluYzWIKteMqcGpTuB+spI8eM4myYgt7YFFe0PLQ==) seems to be corrupted. Trying one more time.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/i302342/.npm/_logs/2020-03-02T09_19_48_054Z-debug.log
-----

**Comment by MichaelCzcz** [comment]
@manjunathgudisi Could you please provide the tutorial name where this is required.

**Comment by manjunathgudisi** [comment]
Hi @MichaelCzcz  This is the tutorial Im following https://developers.sap.com/tutorials/cap-cloudsdk-3-basic-service.html

**Comment by jung-thomas** [comment]
This is not an issue with the tutorial itself but a problem in the latest update of the @sap/cds-dk module itself.  The latest version can not currently be used. The problem has been reported to the development team responsible.

**Comment by hadasdavid** [comment]
@jung-thomas is there is workaround for this issue?

**Comment by nijunyan** [comment]
Same issue here.

**Comment by jung-thomas** [comment]
This isn't really the correct place to ask product problems kind of questions. This issues area is only for problems with the content of the tutorials.  Really the SAP Community Q&A would be the correct place to ask this kind of question (and therefore the issue remains closed). Development is working to resolve the issue with this version of the @sap/cds-dk module. In the mean time you can try to install the older 1.4.4.  I've seen reports that using yarn instead of npm to install the latest version might work, but I've not personally tested that approach.

**Comment by manjunathgudisi** [comment]
`npm install -g @sap/cds-dk@1.4.4` works for me.

**Comment by jyothiradityak** [comment]
Thanks! even i am facing same issue !. Will try with 1.4.4
