### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by joe-binkley-sap** [SAPDocuments/Tutorials#4707]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Step 7 -- After 30 minutes, status never changed from "Starting" to "Started".  However, the Step 8 test using Postman work fine.  So, something must be wrong with the status reporting.

**Comment by islandhopper72** [comment]
I wonder where I can find the request URL which I need for the test in Postman...?

**Comment by gauthamkrishna-sap** [comment]
Hello,
Thank you for the feedback and apologies for the delay in response. 
Have you tried to undeploy and redeploy the iflow again? Please let me know if you see the same issue for all iflows. If not, this might be an intermittent issue, which I will ask our team to check. 
Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
@joe-binkley-sap Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
