### ISSUE TITLE
Inspect and Test the API Proxy

### ISSUE THREAD

**Issue by islandhopper72** [SAPDocuments/Tutorials#4710]
Hi!
I have problems testing the API proxy because I don't understand which user ID / password should be encoded into Base64: is it either my SCP trial account or my HERE account data?
Furthermore, I don't know if -when encoding- I have to separate user ID and password with a special character; e.g. ":"?!
I don't understand in this context what is exactly meant by:  

> "In case you have used your own userid and password, use a Base64 encoder tool to encode the text username:password – without the single quote and place it in the field instead."

Thanks in advance! :-)

Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-inspect-apiproxy.html

**Comment by shilpavij** [comment]
Kindly create an account on HERE and you will get user id and password. Then use Base64 encoder to encode it.

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
