### ISSUE TITLE
Enable SAP Cloud Platform Mobile Services

### ISSUE THREAD

**Issue by FHubert** [SAPDocuments/Tutorials#4713]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-hcpms-setup.html

My Cloud Platform Service List does not have Mobile Services. I have only 10 services available, since in the tutorial are 37.

**Comment by FHubert** [comment]
@KevinMuessig Any update? Still number of services available in Cloud Foundry is 10.

**Comment by KevinMuessig** [comment]
Hi @FHubert,

are you using the Cloud Foundry trial on Europe or US? In both trial landscapes the service should be available. 

<img width="1440" alt="Screen Shot 2020-04-07 at 9 01 33 AM" src="https://user-images.githubusercontent.com/9074514/78692254-745b3b00-78ae-11ea-8e27-ef5bf6069990.png">

@jitendrakansal could you please take over?

**Comment by jitendrakansal** [comment]
@FHubert are you looking into Cloud platform Neo or Cloud Foundry environment ? 
could you share a screenshot of available services what you see there?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
