### ISSUE TITLE
Connect to SAP HANA, express edition using Python -- Py2 i/o Py3

### ISSUE THREAD

**Issue by Sygyzmundovych** [SAPDocuments/Tutorials#4715]
Tutorial URL: https://developers.sap.com/tutorials/hxe-python-connection.html

This tutorial is based on Python2 which is not supported since the beginning of 2020. I recommend to rework it to Python3 (both driver and sample code in the tutorial).

Thanks!

**Comment by JCurrie27** [comment]
Opened an action to update these outdated Python tutorials. Closing this comment to keep the metrics down.
