### ISSUE TITLE
Create Extension Controls in an MDK App (Using Metadata Approach)

### ISSUE THREAD

**Issue by jalonsov** [SAPDocuments/Tutorials#4717]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-dev-kit-slider-extension.html

Please specify the step you are referring to "Run the MDK client"

Hi! 
After implemented the tutorial and tried to run the app on an iOS and Android device, the slider extension was working fine on iOS, but not on Android. I've build the app on a Macbook with options 'all' and 'device'. Attached images of exception on android class SeekBar.
![IMG1](https://user-images.githubusercontent.com/4375468/75994215-e977d100-5efa-11ea-859d-af51f195b112.JPG)
![IMG2](https://user-images.githubusercontent.com/4375468/75994219-eaa8fe00-5efa-11ea-875f-feb0d1da454c.jpg)

**Comment by jitendrakansal** [comment]
@jalonsov I have made changes in android>myslider.ts file and also updated in tutorial page(would take couple of days to get PR merged).

In meanwhile, you can grab this file from here and test it.
https://github.com/SAP-samples/cloud-mdk-tutorial-samples/blob/master/4-Brand-Your-Customized-App-with-Mobile-Development-Kit-SDK/2-Create-Extension-Controls-with-NativeScript-in-an-MDK-App/mdk-extensions/Extensions/MySliderModule/controls/MySliderPlugin/android/MySlider.ts

**Comment by jalonsov** [comment]
Thanks @jitendrakansal for the quick reply. 
Now is working fine.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
