### ISSUE TITLE
Discover Sales Order API from S/4HANA Cloud System

### ISSUE THREAD

**Issue by ChrisTrum** [SAPDocuments/Tutorials#4718]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-api-discover.html

Please specify the step you are referring to Step 2 point 3. 
The OK button stays greyed out if I select the link as shown in picture https://developers.sap.com/tutorials/cp-apim-sales-tracker-api-discover/_jcr_content.github-proxy.1576479901.file/06-copy.png

I don't think I'm doing anything wrong. 

Thanks

**Comment by shilpavij** [comment]
Hello,

Once check the base path -it should be unique and there should not be any validation errors.If you still feel you have not missed anything and its a valid OData. Please raise an issue on OPU-API-OD-DT.

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
