### ISSUE TITLE
Create Your SAP Fiori Launchpad Project and its Module

### ISSUE THREAD

**Issue by deepaksinghvi** [SAPDocuments/Tutorials#4720]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-2-create-module-cf.html

Please specify the step you are referring to

Build was failing in Step 3 with the following errors:
08:33:24 (Executor) line 17: the "workflow_workflowtiles" property set required by the "workflowtilesApprouter" module is not defined
08:33:24 (Executor) make: *** [Makefile_20200306030324.mta:26: pre_validate] Error 1
08:33:24 (Executor) Error: could not build the MTA project: could not execute the "make -f Makefile_20200306030324.mta p=cf mtar= strict=true mode=" command: exit status 2
08:33:24 (MTA BUILD) The "Task for mta build" process finished with code 1
08:33:24 (MTA BUILD) Build of "sample.workflowtiles.mta.trial" failed.

Even after multiple trials.

Finally i directly edited in the Code Editor
From:
`
modules:
  - name: workflowtilesApprouter
    type: approuter.nodejs
    path: workflowtilesApprouter
    parameters:
      disk-quota: 256M
      memory: 256M
    requires:
      - name: workflowtiles_html5_repo_runtime
      - name: portal_resources_workflowtiles
      - name: workflow_workflowtiles
      - name: my-workflow-instance
`

To:
`
modules:
  - name: workflowtilesApprouter
    type: approuter.nodejs
    path: workflowtilesApprouter
    parameters:
      disk-quota: 256M
      memory: 256M
    requires:
      - name: workflowtiles_html5_repo_runtime
      - name: portal_resources_workflowtiles
      - name: uaa_workflowtiles
      - name: my-workflow-instance
`

And build succeeded.
Can this be corrected for the sample app properly.

**Comment by AstridHerbst** [comment]
Hi deepaksinghvi,

Thank you very much for your detailed input. I am sorry that the step description did not work for you. Have you tried pushing the update of the required resource using the 4 steps at the end of Step 2.4?
****************
To really ensure that the updated instance name is used in all respective places, execute the following steps:
1. Select the workflowtilesFLP module and under Requires switch the my-workflow-instance (resource) entry to some other entry.
2. Save your changes.
3. Switch the changed resource entry back to my-workflow-instance (resource).
4. Save your changes.
****************
For me this workaround updates the resource in all places. However, if they do not work for you I will add the code editor texts.

Please let me know.

Best regards,
Astrid

**Comment by MichaelCzcz** [comment]
@deepaksinghvi Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
