### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules - No data in Fiori App

### ISSUE THREAD

**Issue by kuntalbasu1** [SAPDocuments/Tutorials#4721]
I am following all the steps provided in the module, but no data is appearing in the Fiori Application. The only difference that I can find is in Step 5 Create HTML5 Module, where in point 7 screen shot only 'Selected Service Metadata' is appearing in my case, not the custom one. The resource I have selected in previous step is ZUI_C_TRAVEL_M_KB19. I have tried with others resources also, but facing same issue on those cases also.

**Comment by mervey45** [comment]
Hi @kuntalbasu1 ,

can you please retry it. In Step 5.7 you should have your own annotation file of your travel app listed. Sometimes it takes a few seconds. Please wait a few seconds/minutes and wait until it appears. Then you can move on and it should work then. 

Best regards,
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
