### ISSUE TITLE
Create a Sample Application on Cloud Foundry Using SAP Cloud SDK

### ISSUE THREAD

**Issue by GuoquanXing** [SAPDocuments/Tutorials#4722]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-cloud-foundry-sample-application.html

Please specify the step you are referring to:
    If user is using maven 3.6.3, he/she would run into the issue when running `mvn clean package`:

> ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called? 

this is due to in package unit-test and integration tests, the jacoco version is 0.8.2, when update to version 0.8.4 the issue would be resolved, can you please kindly check this?

**Comment by MatKuhr** [comment]
Thank you for reporting this, we will check it 👍

**Comment by MatKuhr** [comment]
Out of curiosity how do you derive that this might be due to the jacoco version?

**Comment by MichaelCzcz** [comment]
@MatKuhr Any Updates?

**Comment by Emdee89** [comment]
You can update the version of the jacoco-maven-plugin yourself in your pom files yourself.

Morever, we will update here in case the version gets updated in the archetypes with a new SAP Cloud SDK version.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
