### ISSUE TITLE
Create an SAPUI5 App from the Command Line

### ISSUE THREAD

**Issue by alteraugem** [SAPDocuments/Tutorials#4724]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-sapui5-local.html

Please specify the step you are referring to: Step 5

It should be mentioned that a login to CF is required.

**Comment by IObert** [comment]
Hi @alteraugem,

thanks for your feedback. This particular tutorial is part of a [larger tutorial group](https://developers.sap.com/group.cp-ui5-first-app-your-tools.html) in which the login is described in the [first tutorial](https://developers.sap.com/tutorials/cp-cf-download-cli.html).
Hence, I'm closing the issue. Feel free to reopen it if something is not clear.
