### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by DuoBelt** [SAPDocuments/Tutorials#4727]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Please specify the step you are referring to

11.5. Now your project app Travel_App_XXX is added to your group.

Save operation is mising in the tutorial  before step 11.5 :)
Without this  in the next step  12.1 user doesn't see  Build > Build with Cloud MTA Build Tool (recommended).

Best regards

Nice tutorial, great  job :)

**Comment by mervey45** [comment]
Hi @DuoBelt , 

thank you, for your feedback. You can save you file by pressing **CTRL + S**. Or you can use **File > Save**.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
