### ISSUE TITLE
Add a Web Dynpro ABAP App to Your Portal Site

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#4728]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-webdynpro-app.html

Please specify the step you are referring to:

Step:5 Launch the app (WebDynpro Search PO's app)

This did not work for me - I get the "Service cannot be reached" error. I get a 404 basically. I logged into the ES5 system successfully so not sure where to go from here as I have security issues when trying to run transaction /n/IWFND/MAINT_SERVICE to check it. 

Needing some assistance here please. 

Thanks
Phil Cooley

**Comment by IrisSasson** [comment]
Hi
Please share a screenshot to show your application and destination configurations
Thanks

**Comment by MichaelCzcz** [comment]
@pjcools Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
