### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by alteraugem** [SAPDocuments/Tutorials#4729]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-data-model.html

Please specify the step you are referring to set 4 §7: 
You state: "The annotation ensures that all columns are already selected" I ask: "Which annotation?" The app doen't show any data if you do not at least make an empty selection!

In general, the background information provided in the tutorial is much to sparse to understand, what one is doing.

**Comment by mervey45** [comment]
Hi @alteraugem ,

thank you for your feedback. You are adding annotations in step 2.6 to your coding, which gets visible on your UI in step 4.7.
The data is created in step 3.4 of following tutorial: https://developers.sap.com/tutorials/abap-environment-persistence.html.
This tutorial is the prerequisite of the tutorial: https://developers.sap.com/tutorials/abap-environment-data-model.html. So you have to do all tutorials in the right order.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
