### ISSUE TITLE
Develop an SAP Fiori App using SAP Business Application Studio

### ISSUE THREAD

**Issue by vishnucta** [SAPDocuments/Tutorials#4730]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

When the SAP Business Application Studio available for test instance in SCP.

**Comment by raz-korn** [comment]
Hi @vishnucta - SAP Business Application Studio is available on SAP Cloud Platform trial landscape. Note that you need to have a subaccount on AWS Frankfurt. More details on steps needed to enable it are available in the Administrator Guide. I'm also working on a tutorial for on-boarding. Should be available soon.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
