### ISSUE TITLE
Start Developing on SAP Cloud Platform

### ISSUE THREAD

**Issue by ceerix** [SAPDocuments/Tutorials#4731]
Mission URL: https://developers.sap.com/mission.scp-1-start-developing.html

Why I have to log in at Github after clicking on a feeback button on a SAP page?

And why already 5 browser windows open? I just tried to login at SAP Trial account?!?!

Why I am after 1 hour clicking on SAP Urls I am most time back to the beginning?

**Comment by IObert** [comment]
Hi @ceerix,

we leverage GitHub to store and publish the markdown files that contain our tutorials. Because of this, we also use GitHub to track issues related to the tutorials. Therefore, logging in to GitHub is required to submit feedback (GitHub doesn't allow anonymous issues).

I'm afraid I don't understand the other questions, can you please clarify why you opened so many browser windows? If you want to access the SAP Cloud Platform trial, please use this link <https://hanatrial.ondemand.com/>

**Comment by ceerix** [comment]
Hello IObert, 

I don't get it, too. 

Now I had first to check if you from SAP or not or if I am on a totally wrong "Github" page. 

I clicked on a "Feedback" button on a SAP page. Since when we need access for a FEEDBACK to Github? It's extremely confusing for me to jump from on Url (SAP) to a complete other Url (Github) only for a feedback. 

For NON SAP people it's quite easy to understand. SAP getting more and more TOO complicated. 
Very often I don't know WHERE I am. At SAP or anywhere else like now. 

I am still not sure if I am on a FEEDBACK page for SAP on Github or not. 

Or I am on a SAP Tutorial page and my "Feedback" it totally wrong on this page?

**Comment by thecodester** [comment]
@ceerix There seems to be 2 issues you are raising:

- You are not satisfied with the functionality or usability of SAP Cloud Platform trial. I can appreciate your frustration -- I also sometimes wish it would work differently. However, we (the people who create and run the tutorials) are not responsible for the product itself. I recommend first using the feedback option within the trial, as well as starting a discussion in the SAP Community, where I think you can easily find product managers and developers connected to the platform.

- You did not like the feedback mechanism for the tutorials. The feedback mechanism only requires you to log into GitHub (after which it will automatically redirect you to the right page). We assume that everyone in our audience will have an account on GitHub and be familiar with GitHub, and GitHub already has the functionality for tracking customer issues and lets us -- transparently -- assign and answer your questions, and for us to interact with you.

I hope that helps. Let me know if you have any other questions.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
