### ISSUE TITLE
Set Up the SAP HANA Plugin for Microsoft Visual Studio

### ISSUE THREAD

**Issue by Whsitler** [SAPDocuments/Tutorials#4736]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-visual-studio.html

Please specify the step you are referring to

After going through the install procedure, The data provider is not available in Visual studio 2019.
It does get added to 2015. 

I need this to work in both versions, so telling me to uninstall one is not acceptable.

**Comment by JCurrie27** [comment]
Hi @Whsitler: Thanks for this feedback. Could you please log this problem on the Community page to take advantage of the community support model? The HANA express community has much more visibility than this GitHub repo, and is regularly monitored by experts, and other Visual Studio/SAP HANA, express edition users:

- Go to [https://answers.sap.com/questions/ask.html](https://answers.sap.com/questions/ask.html)
- In the **Select Primary Tag** field, search for "express", and select **SAP HANA, express edition**.
- Describe the problem in the Details section

Many thanks. Based on recommendations from the Community, we'll update the tutorial if necessary. (Closing this GitHub issue).
