### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by niladrisdeb** [SAPDocuments/Tutorials#4738]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Please specify the step you are referring to
It is Step 7, the issue is same as - Design and Test Your First Integration Flow #4707

I cannot see the artifact in monitor under the Manage Integration Content section, Can anyone please check?

**Comment by gauthamkrishna-sap** [comment]
Hello,
Can you please send your global account ID and subdomain ID? We will check this and get back to you. 
Best Regards, Gautham

**Comment by niladrisdeb** [comment]
Global account ID- S0021196441
Subdomain - s0021196441trial

**Comment by niladrisdeb** [comment]
any idea when this can be resolved?

**Comment by gauthamkrishna-sap** [comment]
Unfortunately, we do not provide any SLAs for trial. But I can assure you that our team is looking into this with priority and provide a resolution as soon as possible.

**Comment by niladrisdeb** [comment]
thanks for the update

**Comment by MichaelCzcz** [comment]
@gauthamkrishna-sap Are there any updates on this issue?

**Comment by gauthamkrishna-sap** [comment]
@MichaelCzcz Unfortunately, not yet. I will update you if I hear anything.

**Comment by MichaelCzcz** [comment]
@gauthamkrishna-sap any update?

**Comment by gauthamkrishna-sap** [comment]
Hi @niladrisdeb 
We have made some updates to the landscape and the issues must have been resolved. Can you please check and revert if you are still facing the issue?
Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
