### ISSUE TITLE
Call a Remote Function Module From SAP Cloud Platform, ABAP Environment

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#4743]
Tutorial URL: https://developers.sap.com/tutorials/abap-env-rfc.html

Step 3: Specify the remote function modules and BAPIs

The last screenshot does not contain BAPI_EPM but RFC_SYSTEM_INFO from the step before.

**Comment by julieplummer20** [comment]
Thanks. Fixed.
Could this now be closed, please?

**Comment by gregorwolf** [comment]
Will check again tomorrow. Currently I do not see the changes.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
