### ISSUE TITLE
Create Instance of SAP Cloud Platform Enterprise Messaging Service

### ISSUE THREAD

**Issue by joe-binkley-sap** [SAPDocuments/Tutorials#4744]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html

Prerequisites says: 
"You must fulfill at least one of the following two points to be able to proceed with this tutorial." but there's no two points.  I suspect this is where I might have been alerted that the tutorial does not work in the trial.

Also, the Key icon and the subtle line "Requires Customer/Partner License" should be more pronounced. The error, if you miss that requirement, is pretty meaningless:

_Service broker error: Service broker enterprise-messaging-service-broker failed with: Service broker parameters are invalid: [\{"message":"Unrecognized field","propertyPath":"namespace"}]_

**Comment by pradeeppanda-sap** [comment]
thanks for pointing out the issue.
I have fixed and submitted it.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
