### ISSUE TITLE
Create Queues and Queue Subscriptions for Enterprise Messaging

### ISSUE THREAD

**Issue by joe-binkley-sap** [SAPDocuments/Tutorials#4745]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-queue-queuesubscription.html

When I went to the subscribed application, I got an error indicating that I need to add appropriate roles. After doing that, I still got the same error message. That didn't go away until I closed my browser and re-opened. So, something is probably being cached in the browser.

**Comment by MichaelCzcz** [comment]
@pradeeppanda-sap Can you please look into this?

**Comment by pradeeppanda-sap** [comment]
The Role Assigning what we do against a Service is a feature of SCP. It is not in control of SAP Enterprise Messaging.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
