### ISSUE TITLE
Send and Receive Test Enterprise Messages

### ISSUE THREAD

**Issue by joe-binkley-sap** [SAPDocuments/Tutorials#4746]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-test-queue-sendreceive.html

Step 1.1 -- (Minor) should be either "Open the Postman application" or "Open Postman"

Step 1.3 -- Please explain that you can the Service Keys in the service instance in the Enterprise Messaging service. Note that the most recent instructions in the mission have one in the Enterprise Messaging dashboard.

Step 1.3 -- Needs to have an instruction to create a service key first.

**Comment by pradeeppanda-sap** [comment]
have committed the changes as per your valuable comment.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
