### ISSUE TITLE
Add a New Entitlement to Your Subaccount

### ISSUE THREAD

**Issue by krishbiswas** [SAPDocuments/Tutorials#4749]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-entitlements-add.html

It says "Entitlements are the hearth of all subaccounts in the Cloud Foundry environment." What does "hearth" mean here?

**Comment by IObert** [comment]
It means that I'm not able to spell "heart" 😅

Thanks for reporting this one, I'll fix it momentarily
