### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#4751]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Prerequisites

I had to witch from NoAuthentication to BasicAuthentication and provide my ES5 user and password. With NoAuthentication I've got an error during the Step 4: Add an OData service to the project.

**Comment by raz-korn** [comment]
We are familiar with this issue. A fix is expected next week. An additional workaround is to use a different service, CATALOGSERVICE (there are 2 - choose the 2nd from the top).

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by abhijeetsap** [comment]
Whats the solution?

**Comment by raz-korn** [comment]
Hi @abhijeetsap ,
What error do you encounter? Which step / sub-step? Can you share a screenshot?
Regards - Raz

**Comment by abhijeetsap** [comment]
![Annotation 2020-07-05 190637](https://user-images.githubusercontent.com/20759981/86533972-963a7d00-bef2-11ea-84b5-98411540c7fb.png)

**Comment by raz-korn** [comment]
The tutorial is based on ES5 destination configured with Basic Authentication.
Is it the same in your case?
If it is defined with Basic Authentication, what you received is usually due to incorrect credentials. Either username or password.
Regards - Raz
