### ISSUE TITLE
Integrate an SAPUI5 App into Your Portal Site (Cloud Foundry)

### ISSUE THREAD

**Issue by manjunathgudisi** [SAPDocuments/Tutorials#4755]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-sapui5-app.html

Please specify the step you are referring to, Step#7.

When I click on "Candidates" tile, I get this error.

in a frame because it set 'X-Frame-Options' to 'sameorigin'.

<img width="1635" alt="Screen Shot 2020-03-12 at 10 06 05 AM" src="https://user-images.githubusercontent.com/6059076/76487674-1ec77600-6449-11ea-9d2f-1b97696e2335.png">

Thanks, Manju

**Comment by weitlos** [comment]
Hi manjunathgudisi,

I got the same problem but solved it by adding some options to the user variables on the approuter instance in CF like described here in this issue: https://github.com/SAPDocuments/Tutorials/issues/4162

Dear team can you please add this to the tutorial as it seems to be a general issue. Is it intended to add this entry manually for each app which will be developed or is it something which can be configured within the app source files directly?

kind regards,
Simon

**Comment by IrisSasson** [comment]
Hi, to verify the security of this solution, and as this issue does not happen to all tutorial users, it is best to open a ticket. 
Please open a BCP with the component EP-CPP-CF-FLP to get this reviewed with Portal development as the security aspects of this issue should be reviewed. 

Thanks

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
