### ISSUE TITLE
[Error while accessing the app] Add a Web Dynpro ABAP App to Your Portal Site

### ISSUE THREAD

**Issue by manjunathgudisi** [SAPDocuments/Tutorials#4756]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-webdynpro-app.html

Please specify the step you are referring to, Step#5

When I click on "Search POs" tile, Im getting this error.

<img width="1637" alt="Screen Shot 2020-03-12 at 11 34 04 AM" src="https://user-images.githubusercontent.com/6059076/76492150-8388cd80-6455-11ea-9aa6-8e31ed3c3055.png">

**Comment by IrisSasson** [comment]
Hi
Please add a screenshot of your destination configuration, your app configuration and you app navigation configuration 

Thanks

**Comment by manjunathgudisi** [comment]
<img width="1184" alt="Screen Shot 2020-03-17 at 7 50 05 PM" src="https://user-images.githubusercontent.com/6059076/76865302-838b3200-6888-11ea-9e3f-f15f44ba1aab.png">

Here is the destination configuration.

**Comment by IrisSasson** [comment]
Hi @manjunathgudisi 
Can you also include app configuration (one screenshot) and app navigation configuration (another screenshot?)?
Thanks

**Comment by MichaelCzcz** [comment]
@manjunathgudisi Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
