### ISSUE TITLE
Continue Your OData Exploration with EPM

### ISSUE THREAD

**Issue by anantmaks** [SAPDocuments/Tutorials#4757]
Tutorial URL: https://developers.sap.com/tutorials/odata-02-exploration-epm.html

Please specify the step you are referring to

I am unable to see the option to access 'GUI Actions and Settings' as shown in step 1. Refer: https://prnt.sc/rf4ze5  
Something is needed to be updated in the tutorial I suppose

**Comment by qmacro** [comment]
Thanks for highlighting this, @anantmaks . Fixed with https://github.com/SAPDocuments/Tutorials/commit/ff12904e45f9fa9afa8191f4c205c2bb937ccc8a
