### ISSUE TITLE
SAP Cloud Platform Integration - Technical Error during Tenant Provisioning

### ISSUE THREAD

**Issue by tvikramkumar** [SAPDocuments/Tutorials#4760]
Hallo Team,

currently, I am working on the tutorial, 
https://developers.sap.com/mission.cp-starter-integration-cpi.html 
to learn SAP CPI. I have the following error when I click on the Provision button in the Cloud Platform Integration Tenant platform. I have tried several times but I still have the same issue. I followed the steps as mentioned here:
https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

![SAP_CPI_TenantProvisioning_Error](https://user-images.githubusercontent.com/24615531/76558109-041eec80-649d-11ea-9f16-93b457028479.PNG)

I have also sent a mail to cpitrialfeedback@sap.com as mentioned in the error prompt. I still have not received an answer.

I have seen similar problems in the hub but they are only solved through the team assistance.

Can you please guide me how to fix this problem? Thank you in advance.

**Comment by gauthamkrishna-sap** [comment]
Hello,
Can you please confirm if you are still facing the same issue?
Best Regards,
Gautham

**Comment by tvikramkumar** [comment]
> Hello,
> Can you please confirm if you are still facing the same issue?
> Best Regards,
> Gautham

Hallo Gautham,
I just tried again and i still have the same issue. Thank you.

Best Regards,
Vikram Kumar

**Comment by gauthamkrishna-sap** [comment]
Hello Vikram,
Apologies for the inconvenience. 
Can you please share your global account and subaccount name, ID and details, please? I will ask our team to check this.
Best Regards,
Gautham

**Comment by tvikramkumar** [comment]
Hallo Gautam,
here are my details:
ID : P1941861066
Global Account : P1941861066trial
Sub Account: trial
Email: tallapanenivikram@gmail.com

Please let me know if you need any other details. Thank you.

Best Regards,
Vikram Kumar

**Comment by gauthamkrishna-sap** [comment]
Hello Vikram,
Can you please check if you can provision your tenant? 
Best Regards, Gautham

**Comment by tvikramkumar** [comment]
Hi Gautam, unfortunately, i still get the same error !

**Comment by gauthamkrishna-sap** [comment]
Hi Vikram,

We have the new integration suite starter scenario. Kindly try provisioning a tenant in integration suite as we do not offer cloud integration trial anymore. 

Best Regards,
Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
