### ISSUE TITLE
Create Your First Integration Package and Integration Flow

### ISSUE THREAD

**Issue by IvoVermeer** [SAPDocuments/Tutorials#4761]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-create-iflow.html

Please specify the step you are referring to: Step 2

When I access the design tab, i get the error 'Error in fetching packages'
![image](https://user-images.githubusercontent.com/5347891/76560126-c9b74e80-64a0-11ea-8151-dd5e7ca99d0c.png)

I can still click 'Create' and fill in the details for a new package, but when I try to save it, I get the following error:
![image](https://user-images.githubusercontent.com/5347891/76560211-f66b6600-64a0-11ea-9caa-0ceeae7ff06a.png)

My global account is S0021363306trial

**Comment by ischlueter** [comment]
I just raised issue #4763 on the same error

**Comment by gauthamkrishna-sap** [comment]
Hello,
Can you please confirm if you are still facing this issue?
Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
@IvoVermeer Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
