### ISSUE TITLE
Create Your First Integration Package and Integration Flow --> Internal Server Error (500)

### ISSUE THREAD

**Issue by ischlueter** [SAPDocuments/Tutorials#4763]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-create-iflow.html

Please specify the step you are referring to: Step 2

Cannot save new package because of "Internal server error" Status Code = 500

Copy of request in chrome development tools:

curl 'https://s0015186016trial.it-cpitrial01.cfapps.eu10.hana.ondemand.com/itspaces/odata/1.0/workspace.svc/ContentEntities.ContentPackages' -H 'Connection: keep-alive' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Sec-Fetch-Dest: empty' -H 'X-CSRF-Token: f080a1063c32849a-WfLJhwyvxYSLXttcPJt4Jqio520' -H 'X-Requested-With: XMLHttpRequest' -H 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Mobile Safari/537.36' -H 'Content-Type: application/json' -H 'Origin: https://s0015186016trial.it-cpitrial01.cfapps.eu10.hana.ondemand.com' -H 'Sec-Fetch-Site: same-origin' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://s0015186016trial.it-cpitrial01.cfapps.eu10.hana.ondemand.com/itspaces/shell/design/package?create=true&section=HEADER' -H 'Accept-Language: en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7,pl;q=0.6' -H 'Cookie: __VCAP_ID__=f6c31888-fc75-4b45-6eb4-6738; JSESSIONID=s%3ANORaWKezSbVsVc_aeFEShmisI5nameSE.bA7u7C30a8oxkS4xdBXehphoZwmo7miEsnMxuTB%2BnQg' --data-binary '{"Category":"Integration","SupportedPlatforms":"SAP HANA Cloud Integration","TechnicalName":"CloudIntegrationTrialExperience","DisplayName":"Cloud Integration Trial Experience","ShortText":"Package for SAP Cloud Platform Integration Trial Experience","Description":""}' --compressed

**Comment by gauthamkrishna-sap** [comment]
Hello,
Can you please confirm if you are still facing this issue?
Best Regards,
Gautham

**Comment by MichaelCzcz** [comment]
@ischlueter Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
