### ISSUE TITLE
Add Transactional Behavior to Your Core Data Services

### ISSUE THREAD

**Issue by jrodriguez-rc** [SAPDocuments/Tutorials#4764]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-transactional-enablement.html

Could be interesting adding some explications about some things, like what's the meaning to add "root" and the difference between `Managed` and `Unmanaged`

Also, can update tutorial to replace obsolete sentences
![image](https://user-images.githubusercontent.com/56556686/76615477-6e2da500-6522-11ea-9bd0-b349f96fa1f1.png)

**Comment by mervey45** [comment]
Hi @jrodriguez-rc ,

thank you for your feedback. We'll update this issue.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by jrodriguez-rc** [comment]
No change was done in the tutorial

**Comment by mervey45** [comment]
Hi @jrodriguez-rc ,

currently, we are not able to update the content because of some server issues. Hopefully, I'll can make updates later today or tomorrow. 

Thank you.

Best regards, 
Merve
