### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by amitcruz** [SAPDocuments/Tutorials#4765]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

I am keep on getting below error while adding OData service in the project ( step 4 ) :

'Consume SAP Services failed. Reason: Error: Failed to get metadata. Reason: Not Authorized'

![error studio](https://user-images.githubusercontent.com/42535599/76634912-99d57d00-656c-11ea-84c9-b50be564e521.JPG)

**Comment by amitcruz** [comment]
Please help and look into the issue

**Comment by raz-korn** [comment]
A fix is on the way. As a workaround in the destination configuration use Basic Authentication with your credentials.

**Comment by amitcruz** [comment]
Yes It worked using basic authentication.
