### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by amitcruz** [SAPDocuments/Tutorials#4766]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

I got stuck again at below error when I ran module to run the application (Step 8 ) :
UAA tenant mode is shared, but environment variable TENANT_HOST_PATTERN is not set

I am using ‘application’ plan for UAA service instance as per tutorial.
Please advice where am I going wrong ?

![uaa error2](https://user-images.githubusercontent.com/42535599/76696230-18d2ce80-66af-11ea-94cb-4f97ef653d2e.jpg)

**Comment by raz-korn** [comment]
Using UAA makes things a bit more complicated. I'll remove this part from the tutorial. As a workaround you can create the app without UAA and ignore all UAA steps later on - I think there's only one for biding and one for authenticating when running the app.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
