### ISSUE TITLE
Create Your First Application with SAP Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by rahulnlb1** [SAPDocuments/Tutorials#4768]
Tutorial URL: https://developers.sap.com/tutorials/s4sdkjs-odata-service-cloud-foundry.html

Please specify the step you are referring to
`Step 5: Manage destinations centrally (optional)` in the group `Create an App Using SAP Cloud SDK for JavaScript`. 

To import .env variable in process.env, we should use following code:
```JS
import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';

@Module({
  imports: [ConfigModule.forRoot()],
})
export class AppModule {}
```

and not just
```JS
imports: [ConfigModule]
```

For confirmation, please see the NestJS documentation: https://docs.nestjs.com/techniques/configuration

Regards,
Rahul

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
