### ISSUE TITLE
Configure Initial Setup for SAP Mobile Cards

### ISSUE THREAD

**Issue by aleaker** [SAPDocuments/Tutorials#4772]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-digitalexp-mobilecards-1-setup.html

Please specify the step you are referring to: "Switch back to Mobile Services cockpit, paste the copied API key in the open pop-up, and then choose OK."

There is no pop-up to add the API

**Comment by jitendrakansal** [comment]
@sandeep-tds please have a look

**Comment by sandeep-tds** [comment]
Thank you, Jitendra. @aleaker Our Development team is looking into the issue. I will be sure to notify you of the latest developments this week.

Thank you so much for your patience.

**Comment by MichaelCzcz** [comment]
@sandeep-tds Any updates?

**Comment by sandeep-tds** [comment]
@MichaelCzcz   Thank you so much for bringing this to my notice. The tutorial was outdated and thus has been retired. 

@aleaker In place of this tutorial, we recommend [a new tutorial](https://developers.sap.com/mission.mobile-cards-get-started.html) that is a great place to start development for SAP Mobile Cards. 

New Tutorial Details - [Get Started with SAP Mobile Cards](https://developers.sap.com/mission.mobile-cards-get-started.html)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
