### ISSUE TITLE
Create Your First Application with SAP Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by shankarigr** [SAPDocuments/Tutorials#4773]
Tutorial URL: https://developers.sap.com/tutorials/s4sdkjs-odata-service-cloud-foundry.html

Please specify the step you are referring to
when i do a cf push, the deployment process is not progressing. It gets stuck in Uploading stage.
I am using a windows machine. When my colleague executed the same in mac it worked.

Not sure what I am doing wrong here.
Any leads on the same would be really appreciated.

Thanks and Regards,
Shankari G R

**Comment by mr-flannery** [comment]
Hi Shankari,

Given that you've posted your question already on [answers.sap.com](https://answers.sap.com/questions/13002822/sap-cloud-sdk-for-javascript-couldnt-deploy-cloud.html) and that this is not an issue on the tutorials per se, are you fine with closing the issue here?

Best regards,
Dennis

**Comment by shankarigr** [comment]
Hello Dennis,

So, When I execute this step of the tutorial from a windows pc
https://developers.sap.com/tutorials/s4sdkjs-deploy-application-cloud-foundry.html#af291f91-d17a-413c-9590-07dafe5d47a2
the package command creates a deployment folder which is more than 3 GB. 
I think that makes it difficult to push.

Can you please let me know how can i make this work?

Thanks and Regards,
Shankari G R

**Comment by MichaelCzcz** [comment]
@mr-flannery Any updates?

**Comment by mr-flannery** [comment]
It's on our radar, but I cannot yet say when it'll be done.

**Comment by thecodester** [comment]
@mr-flannery  Is this a problem on how the tutorial is constructed (we create a 3GB package when we did not have to and this is really annoying, or the way we tell them to push is difficult and there is another way) or is it an issue with the software. You seem to say in your 1st response that this is not a tutorial issue. If it isn't, let's close the issue.

@shankarigr Feel free to weigh in

**Comment by mr-flannery** [comment]
> You seem to say in your 1st response that this is not a tutorial issue. If it isn't, let's close the issue.

That is correct, and I still assume so. We're tracking the issue in our project, so from my perspective this issue here can be closed.
