### ISSUE TITLE
Map Message Structure

### ISSUE THREAD

**Issue by lsypula** [SAPDocuments/Tutorials#4778]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-convert-message-structure.html

Step 1: Add message mapping
I'm unable to download source and target xsd files. Both links have expired.

**Comment by gauthamkrishna-sap** [comment]
@lsypula The links are corrected now.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
