### ISSUE TITLE
Add an Onboarding Flow

### ISSUE THREAD

**Issue by JuxTalias** [SAPDocuments/Tutorials#4779]
Tutorial URL: https://developers.sap.com/tutorials/cp-sdk-android-flows-onboard.html

Please specify the step you are referring to : Step 2 : Try it Out

"After tapping Get Started, an authentication screen is shown. Enter your Mobile Services credentials."
Is it possible to know what are the Mobile Services credentials ? I tried to log in with my SAP userID and i get a timeout.
--> 7794-7794/com.sap.flows D/com.sap.flows.MyApplication: [main] Failed to onboard.  timeout

I use the sdkVersion 3.0.0.

Best regards,

**Comment by jarjarbentley** [comment]
the mobile service credentials are mapped to your SAP Cloud Platform account as you tried.  I am not sure what caused the time out.  Please let us know if this is still happening.
