### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#4783]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to: Prerequisites

There is no 'HTML5.DynamicDestination' Additional Property available in my destination configuration in the us space as per this instruction:

Additional Properties:
HTML5.DynamicDestination: true - not in the dropdown
sap-client: 002
WebIDEEnabled: true
WebIDESystem: ES5
WebIDEUsage: odata_abap

**Comment by raz-korn** [comment]
It is not available if you expand the list or try code completion. You can manually type it in and it will work.

**Comment by greg2git** [comment]
ok, i think i have done that. but now not sure about my destination settings and the link that is supposed to help https://developers.sap.com/tutorials/cp-cf-create-destination.html is for a different type of destination as i keep getting this error: 

Consume SAP Services failed. 
Reason: Error: Failed to get list of destinations. 
Reason: Error: No OData service destinations received.

after trying basic, none, or odata authentication settings.

**Comment by raz-korn** [comment]
I think a better tutorial is: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-gateway-connection.html. 
Did yo perform "Check Connection"?
It might help if you can share screenshot with the error, and the steps leading to this.

**Comment by greg2git** [comment]
Check connection gives me this status:
_Connection to "ES5" established. 
Response returned: "307: 
Temporary Redirect"_
and i'm not sure how to interpret that. 

if i try to open the destination service instance i keep getting the error 404 with this verbage: 
_Welcome, first_last_name my_login_id.
We are sorry, but we cannot find what you are looking for._

**Comment by raz-korn** [comment]
The 307 response is OK.

The 404 is NOT OK.
Can you share how you created the destination service and its configuration?

**Comment by greg2git** [comment]
this config results in status 307:
#Password=<< Existing password/certificate removed on export >>
#
#datestamp
Description=ES5 
Type=HTTP
HTML5.DynamicDestination=true
Authentication=BasicAuthentication
WebIDEUsage=odata_gen, odata_abap
Name=ES5
WebIDEEnabled=true
ProxyType=Internet
URL=https\://sapes5.sapdevcenter.com
sap-client=002
User=
WebIDESystem=ES5

This config results in status 404:
https://cockpit.hanatrial.ondemand.com/instance/<gibberish>/destinations
i think the account is entitled and space has the quota to serve all the services, but between US and EU i'm never sure.

**Comment by raz-korn** [comment]
two requests:
1. remove odata_gen from WebIDEUsage.
2. There is a difference between "destination" and "destination service". The above configuration for ES5 is a "destination" configuration. My ask from you is how you created the "destination service" and its configuration. The destination service is an instance created in the space. The easy way (for me) is to do it through the SCP Cockpit. See in the tutorials pre-requisites section (at the top) a link to the relevant documentation.

**Comment by greg2git** [comment]
prerequisites seem to ask for 2 different services to be created: 
1. destination service and 
2. HTML Application repository runtime and/or host. 
i have also tried connectivity and creating destination service from the cf command line. 
not sure how to connect all the pieces together, though.

**Comment by raz-korn** [comment]
pre-req asks for (1) destination - ES5; (2) destination service.
You can create a destination service in the relevant space using SCP cockpit.
In SCP cockpit enter the space > Service Marketplace > Destination > Instances > New Instance > (use all defaults + Provide a unique Instance Name. Done.

The destination is needed for the design time as well as when test running the app (Run configuration).
The destination service is needed when test running the app.

hope this helps.

**Comment by greg2git** [comment]
destination within destination service returns 200 for this url: https://sapes5.sapdevcenter.com/sap/bc/gui/sap/its/webgui

i'm sure it's all obvious to others but the best i could get out ES5 odata is this:
https://sapes5.sapdevcenter.com/sap/opu/odata/iwfnd/rmtsampleflight/FlightCollection/$count

since i cannot verify any data using standard SE16, as my id is not authorized, and since that box is pretty slow for the us user, i'm closing this defect, other parts of studio have been great for me so far. 

thank you very much for all your support.
