### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by Venkatpicons** [SAPDocuments/Tutorials#4784]
Tutorial 2: Deploy a CAP Business Application to SAP Cloud Platform

Please specify the step you are referring to

Step 2   : Deploy using cf push:-
Point No: 4 - > Open this URL in the browser and try out the provided   links, for example, .../catalog/Books. Application data is fetched from SAP   HANA.         

The below is the url:
 https://my-bookshop-srv-responsible-toucan-dv.cfapps.us10.hana.ondemand.com/catalog/Books

After excuting above url, we are getting some additional values which is not there in the books catalog.

Present in the books catalog:
ID;title;author_ID;stock
201;Wuthering Heights;101;12
207;Jane Eyre;107;11
251;The Raven;150;333
252;Eleonora;150;555
271;Catweazle;170;22

Please find the attached screenshot for your reference.

![image](https://user-images.githubusercontent.com/60374957/76964099-2a82d300-6948-11ea-9c1c-624e2bac9c2b.png)

Note: these issues has been applicable for both regions(US and EU)

**Comment by iwonahahn** [comment]
Hi,

the values are coming from step 10 (see code line 20) https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html#d94586c4-547d-4f3d-ae5e-c207603cb2a9 in the first tutorial "Create a Business Service with Node.js Using Visual Studio Code". This is not an issue, we can close it.

Best regards,
Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
