### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by abpradeep** [SAPDocuments/Tutorials#4785]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Please specify the step you are referring to

**Step 8: Test UI on Cloud Foundry**
_6. Select the TRAVEL_APP_XXX tile to test your application._
Here we are getting error as "App could not be opened because the SAP UI5 component of the application could not be loaded.
Failed to load UI5 component for navigation intent "#TravelProcessor-display"

Observed this behavior in both US & EU trial landscape.
ABAP artifcats I created in EU region are available in package **ZTRAVEL_APP_ABP_0320**
Logs attached.
[Build a Fiori App using ABAP_Not able to launch application.txt](https://github.com/SAPDocuments/Tutorials/files/4352619/Build.a.Fiori.App.using.ABAP_Not.able.to.launch.application.txt)

Thanks & Best Regards,
Pradeep

**Comment by mervey45** [comment]
Hi @abpradeep ,

thank you for your feedback. There seems to be an issue. We are working on this. As soon as we have an answer, we'll update this tutorial.

Thank you for your understanding.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
