### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by C5231723** [SAPDocuments/Tutorials#4786]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

I have observed that , In Step 4: Define your first service, user should create cat-service.cds file and add the code.
The code is has mentioned below 
using { Country, managed } from '@sap/cds/common';

service CatalogService {

  entity Books {
    key ID : Integer;
    title  : localized String;
    author : Association to Authors;
    stock  : Integer;
  }

  entity Authors {
    key ID : Integer;
    name   : String;
    books  : Association to many Books on books.author = $self;
  }

  entity Orders : managed {
    key ID  : UUID;
    book    : Association to Books;
    country : Country;
    amount  : Integer;
  }

}
Observation : After adding the code, below error message is displayed.
![image](https://user-images.githubusercontent.com/58938250/77034231-7593f900-69cf-11ea-8898-dbfb33ea5eb4.png)

Thanks & Regards,
Sony Narayan

**Comment by iwonahahn** [comment]
Hi Sony,

Can you please download the updated VS Code extension here https://tools.hana.ondemand.com/#cloud-vscodecds. The error message should disappear. Please confirm so that we can close the issue.

Thank you and best regards,
Iwona

**Comment by C5231723** [comment]
Hi Iwona,

Thanks for the update.
As suggested, i have downloaded the updated VS code extension (vscode-cds-2.1.4.vsix) and retested but observed that the issue still persists.

I have attached the screenshot for your reference.
![image](https://user-images.githubusercontent.com/58938250/78634741-3a942f80-78c2-11ea-8b49-d643a54b30a9.png)


Thanks & Regards,
Sony Narayan

**Comment by iwonahahn** [comment]
Hi,

Could you please share which version of cds you are using by entering _cds version_ in the terminal?

Thanks a lot and best regards,
Iwona

**Comment by C5231723** [comment]
Hi Iwona,

Please find the below details : 
I have downloaded the updated VS code extension as suggested (vscode-cds-2.1.4.vsix) and executed the below steps:
1. Open Visual Studio Code and clicked on View tab --> clicked on install from VSIX and browser and select the "vscode-cds-2.1.4.vsix".
2. Open a command line window and run the following command in a folder of your choice
cds init my-bookshop
3. Open Visual Studio Code, go to File > Open Folder and choose the my-bookshop folder.
4. Go to Terminal > New Terminal and run the following command
cds watch
5. After initializing the app, check whether the srv and dev folders are already created, if yes then create the respective file as mentioned in the following step. If not, choose the New File icon and type srv/cat-service.cds to create folder and file at once in Visual Studio Code.
6. In cat-service.cds file add the below code and save .
using { Country, managed } from '@sap/cds/common';

service CatalogService {

  entity Books {
    key ID : Integer;
    title  : localized String;
    author : Association to Authors;
    stock  : Integer;
  }

  entity Authors {
    key ID : Integer;
    name   : String;
    books  : Association to many Books on books.author = $self;
  }

  entity Orders : managed {
    key ID  : UUID;
    book    : Association to Books;
    country : Country;
    amount  : Integer;
  }

}

I have attached the screenshot of the cds version for your reference.
![image](https://user-images.githubusercontent.com/58938250/79309470-f9ca9500-7f17-11ea-8744-f45e8762bd78.png)

Thanks & Regards,
Sony Narayan

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by C5231723** [comment]
Hi Iwona,

Thanks for the update.
As suggested , i have retested and observed that , after executing the "npm install" command in terminal, the error message is not displayed.

Reagrds,
Sony Narayan
