### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by C5231723** [SAPDocuments/Tutorials#4787]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-data-model.html

I have observed that, In Define and Expose a CDS-Based Travel Data Model tutorial,
Step 4: Create service binding: Click on GO button & observe the buttons availability.

Actual Result: Create button is enabled & available.
![image](https://user-images.githubusercontent.com/58938250/77034454-17b3e100-69d0-11ea-8e8f-b480aeb9e543.png)

Expected Result: Create button should not be available.
![image](https://user-images.githubusercontent.com/58938250/77034479-213d4900-69d0-11ea-951d-eb8c80fc817f.png)

Thanks & Regards,
Sony Narayan

**Comment by mervey45** [comment]
Hi @C5231723 ,

please try it out again. If you already moved on with this tutorial and got back to this step, then you need to save and activate everything and deactivate and activate your service binding again. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
