### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by Venkatpicons** [SAPDocuments/Tutorials#4788]
Issue 1: 
Tutorial 1: Create a Business Service with Node.js Using Visual Studio Code
Step 4: Define your first service
-- > "Copy" option is not required as the beow output is result of the  command.

[cds] - connect to datasource - sqlite:db/my-bookshop.db
[cds] - serving CatalogService at /catalog - with impl: srv/cat-service.js
[cds] - launched in: 4356.854ms
[cds] - server listening on (http://localhost:4004) …

Please find the attached screenshot for your reference.
![image](https://user-images.githubusercontent.com/60374957/77037501-834d7c80-69d7-11ea-8f84-b7ac24024c7e.png)

Issue2:
Tutorial 2: Deploy a CAP Business Application to SAP Cloud Platform

Step 2 : Deploy using cf push
--> Point no : 3  - "Copy" option is not required as the beow output is information of the previous output.

Please find the attached screenshot for your reference.
![image](https://user-images.githubusercontent.com/60374957/77037583-b0019400-69d7-11ea-856b-7dd9575dc418.png)

Please look in this issue and let me know if you need any input on this.

Kind Regards
Venkat

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
