### ISSUE TITLE
Configure Initial Setup for SAP Mobile Cards

### ISSUE THREAD

**Issue by Venkatpicons** [SAPDocuments/Tutorials#4789]
Tutorial 2 : Create SAP SuccessFactors To Dos and Timesheet Card
Step 4: Configure SAP Mobile Cards client
Records are not displayed in Mobile Cards.
Showing only under subscription List and it’s not displayed in home page in Mobile cards and ToDo's

Please kindly check this issue and let me know if you need any inputs on this.

Tutorial URL : https://developers.sap.com/tutorials/cp-starter-digitalexp-mobilecards-2-create.html

Kind Regards
Venkat

**Comment by jitendrakansal** [comment]
@sandeep-tds please look into this.

**Comment by sandeep-tds** [comment]
Thank you, Jitendra. @Venkatpicons  Our Development team is looking into the issue. I will be sure to notify you of the latest developments this week.

Thank you so much for your patience.

**Comment by MichaelCzcz** [comment]
@sandeep-tds Any uppdates?

**Comment by sandeep-tds** [comment]
@MichaelCzcz  Thank you so much for bringing this to my notice. The tutorial was outdated and thus has been retired. 

@Venkatpicons In place of this tutorial, we recommend [a new tutorial](https://developers.sap.com/mission.mobile-cards-get-started.html) that is a great place to start development for SAP Mobile Cards. 

New Tutorial Details - [Get Started with SAP Mobile Cards](https://developers.sap.com/mission.mobile-cards-get-started.html)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
