### ISSUE TITLE
Add a Model and Test the SAPUI5 App

### ISSUE THREAD

**Issue by sdanter** [SAPDocuments/Tutorials#4791]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-webide-setup-datasource.html

Please specify the step you are referring to

Step 1, Step 2 

Both steps contain a typographical error, listing "manifest.json" as "mainfest.json". 

The screenshot provided in Step 2 also shows a different name for the Northwind service URL than the one that appears in the Web IDE. The IDE displays "Northwind - Northwind OData services," while the screenshot shows "Northwind - Sample Data." 

Upon first trying the tutorial I was confused by this, thinking I had made a mistake and backtracking through several other tutorial sections to find out what went wrong.

**Comment by IObert** [comment]
Thanks for opening the issue. You are abruptly right about both points. I just fixed them and the changes should be live soon (next 30 min-ish).

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by sdanter** [comment]
Thank you Michael and Marius!
