### ISSUE TITLE
Develop a Fiori App Using the ABAP RESTful Programming Model (Managed Scenario)

### ISSUE THREAD

**Issue by mfdotta** [SAPDocuments/Tutorials#4794]
Hi, 

When I click on TravelProcessor in my Service Binding I get a dump (see below). I'm trying to find out why I get it... I tried to search in google and I found something about Currency, but I'm not sure the problem is the Currency. Please, could anyone help me?

untime Error: 'RAISE_SHORTDUMP'. The OData request processing has been abnormally terminated. If you use SAP S/4HANA Cloud, please create an incident. Otherwise, if "Runtime Error" is not initial, launch ADT feed "Runtime Errors" or transaction ST22 / SM21 (system log analysis) for details and analysis.

Thanks!

Best regards, 
Marcos F. Dotta

Group URL: https://developers.sap.com/group.abap-env-restful-managed.html

**Comment by mervey45** [comment]
Hi @mfdotta ,

please deactivate your service binding and activate it again. If this problem is still there, please contact me again. 

Best regards, 
Merve

**Comment by mfdotta** [comment]
Hi @mervey45, 

I did it many times and it didn't work. :(
Do you have any idea?

Thanks!

Best regards, 
Marcos F. Dotta

**Comment by mervey45** [comment]
Hi @mfdotta ,

you did this in the trial environment?

Best regards, 
Merve

**Comment by mfdotta** [comment]
Hi @mervey45,

Yes, in the trial environment.

Best regards,
Marcos F. Dotta

**Comment by mervey45** [comment]
Hi @mfdotta ,

can you please give me the name of your package, so that I can have a look at it?

Thank you.

Best regards,
Merve

**Comment by mfdotta** [comment]
Hi @mervey45,

ZPACKAGE_DOTTA

Thanks!!

Best regards,
Marcos F. Dotta

**Comment by mervey45** [comment]
Hi @mfdotta ,

please ensure, that you have replaced all XXX s with your ID or naming. 
![image](https://user-images.githubusercontent.com/27953324/77177348-a48c9680-6ac5-11ea-8332-c503bc013c96.png)

Furthermore, you have to make sure, that you use the same naming. You have here 2 different names. Please make it consistent.
![image](https://user-images.githubusercontent.com/27953324/77177488-e1f12400-6ac5-11ea-9770-71deddc78740.png)

After you corrected everything, please deactivate and activate your service binding again and test it. 

If you still have issues, please feel free to contact me. 

Best regards, 
Merve

**Comment by mfdotta** [comment]
Hi @mervey45,

I got no errors when I activated the objects and I could not see these points. 
I'm beginner with these new technologies!! :)

Thanks!

Best regards,
Marcos F. Dotta

**Comment by mervey45** [comment]
Hi @mfdotta ,

you have to wait a few seconds, it will again, it takes just a while.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
