### ISSUE TITLE
Create an SAPUI5 App from the Command Line

### ISSUE THREAD

**Issue by d023604** [SAPDocuments/Tutorials#4795]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-sapui5-local.html

After Step 2 but before Step 3 I had to run npm run build:ui . Only then was I able to complete step 3

**Comment by IObert** [comment]
Hi Andrew,

this is strange. "build:mta" includes "build:ui" implicitly which means it should work the way it's described in the tutorial (I just tested it on my machine).
Are you using the latest easy-ui5 generator 1.3.1 (you can check with `npm ls -g  --depth=0`) and is the issue reproducible?

If so, please share the log message that is printed then running  "build:mta"

**Comment by IObert** [comment]
I'll close this for now. Please reopen if you still see the issue
