### ISSUE TITLE
Create Service Instance for Document Information Extraction

### ISSUE THREAD

**Issue by enric11** [SAPDocuments/Tutorials#4796]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dox-service-instance.html

Where can I find the PDF document in "Step 5: Upload" a document?

Thanks

Regards

**Comment by Juliana-Morais** [comment]
Hi, I believe you mean:
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dox-swagger-ui.html (and not https://developers.sap.com/tutorials/cp-aibus-dox-service-instance.html)
You can upload any document in PDF format that has content in headers and tables. The model accuracy with invoices is usually higher.
I hope this helps.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
