### ISSUE TITLE
Add Managed Associations with Core Data Services

### ISSUE THREAD

**Issue by d023604** [SAPDocuments/Tutorials#4799]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-foundation-01.html

Step 5 - Link to "More information about associations in CDS on the SAP Help Portal" leads to a page that cannot be found. 

https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/b3a0321c94194a21a17a991b0f879fbb.html

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
