### ISSUE TITLE
Learn Annotation Basics for OData and Fiori

### ISSUE THREAD

**Issue by dhorions** [SAPDocuments/Tutorials#4802]
Tutorial URL: https://developers.sap.com/tutorials/odata-04-basic-annotations.html

Step 5: Specify the OData service

The Odata service, even though defined and tested correctly, doesn't show up in webide.
![2020-03-23 15_51_06-Window](https://user-images.githubusercontent.com/1682004/77329388-3abaf980-6d1e-11ea-91a5-967a973aa2e9.png)

**Comment by qmacro** [comment]
Hi @dhorions - you'd be better asking this on the SAP Community Q&A (answers.sap.com) where you're more likely to get focused help, and your question and the eventual answer will help others too. This issue system is for issues with the tutorial content itself. 

That said, did you check you followed all the steps in the destination setup tutorial referred to? I just went through this now and it works as described:

![image](https://user-images.githubusercontent.com/73068/77427122-bde75880-6dcd-11ea-9d66-b5a30f319627.png)

Check the other tutorial, esp. the values for WebIDEUsage, and if required please ask on answers.sap.com. 

Good luck!

**Comment by dhorions** [comment]
My bad, I didn't realize the destinations in neo and cloudfoundry environments were separate.  Sorry for wasting your time.
