### ISSUE TITLE
Get Started with SAP Cloud Platform Trial

### ISSUE THREAD

**Issue by knkumar** [SAPDocuments/Tutorials#4806]
Tutorial URL: https://developers.sap.com/tutorials/cp-trial-quick-onboarding.html

Please specify the step you are referring to

Step 4:

The writing is verbose at best and pedantic. A getting started tutorial should have tight focus on what it is accomplishing. This article has too much jargon to help anyone get started in my opinion.

The questions which immediately come to my mind are 
1. What is a service?
2. Why are we discussing services? 

The article should answer these before going into details if a reader has to get started and not give up.

**Comment by IObert** [comment]
Hi Kiran,

I'm sorry you feel this way about the tutorial, I agree that this tutorial is not coding focussed. I also know from my discussions with developers that many have initial difficulties understanding the fundamentals concepts of SCP like the relation between SCP business services and CF services. The same goes for the accounting terminology and navigation in the cockpit.
Overall, I think this tutorial is ok. But you are obviously free to skip any tutorial that is too verbose.

**Comment by knkumar** [comment]
> Hi Kiran,
> 
> I'm sorry you feel this way about the tutorial, I agree that this tutorial is not coding focussed. I also know from my discussions with developers that many have initial difficulties understanding the fundamentals concepts of SCP like the relation between SCP business services and CF services. The same goes for the accounting terminology and navigation in the cockpit.
> Overall, I think this tutorial is ok. But you are obviously free to skip any tutorial that is too verbose.

I agree with your statements. The target audience is perhaps not a novice or a developer for this tutorial.
In that case, there should be a pre-requisites for the tutorial.

However, the following issue still remains -
1. What is a service?
2. Why are we discussing services?

Can you point me to a resource or tutorial which answers these questions? 
I can open another issue with a tighter focus on the above questions. I am hoping someone looking for answers to these questions doesn't have to spend many hours or days getting to the right information.
