### ISSUE TITLE
Use abapGit to Transform ABAP Source Code to the Cloud

### ISSUE THREAD

**Issue by weisensen** [SAPDocuments/Tutorials#4807]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-abapgit.html

Please specify the step you are referring to
Step 6: Install abapGit Eclipse plugin

I have already added the URL http://eclipse.abapgit.org/updatesite/ to update site to ADT Version: 3.9.300
but still could not install abapGit because no update found.

![image](https://user-images.githubusercontent.com/8147601/77389789-094e3680-6dcf-11ea-8427-356c6ff667f4.png)

and it is not possible to Install New Software because the button is grayed out.

**Comment by mervey45** [comment]
Hi @weisensen ,

sometimes it can happen, that you need to deinstall and install your ADT again. Please try this out first.

Best regards,
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
