### ISSUE TITLE
Set up SAP HANA, express edition on Amazon Web Services (XS Advanced)

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#4814]
Tutorial URL: https://developers.sap.com/tutorials/hxe-xsa-aws-setup.html

Please specify the step you are referring to 9

When connecting via WebIDE to 'di-core-hdi' i get this error: 
Error: Error returned from XSA: User "XSA_DEV" is not permitted to create a resource in space "SAP" of org "HANAExpress".

**Comment by jung-thomas** [comment]
There is nothing in that step that I see that tells you to connect to di-core-hdi. Nor would there be any reason to connect to this HDI container instance.  As the error says this user isn't authorized to resources in the SAP space. You should instead be doing your work with the development user in the development space.
