### ISSUE TITLE
Set Up Initial Configuration for an MDK App

### ISSUE THREAD

**Issue by FHubert** [SAPDocuments/Tutorials#4815]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-dev-kit-ms-setup.html

Please specify the step you are referring to

In step 2 Mobile Settings Exchange is not available as well as others. It looks like naming has changed.

Regards,
Hubert

**Comment by jitendrakansal** [comment]
@FHubert could you share a screenshot on what you see on your side? 
Tutorial points to **Mobile Services on Cloud Foundry Environment ,** please make sure that you are on right environment as per tutorial.

**Comment by MichaelCzcz** [comment]
@FHubert Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
