### ISSUE TITLE
Service offering "destination" was not found

### ISSUE THREAD

**Issue by mendezjcarlos** [SAPDocuments/Tutorials#4817]
I'm following this material: https://developers.sap.com/tutorials/cp-ui5-webide-new-app.html

On step 5.3, where I need to deploy a MTA file to Cloud Foundry, I'm not able to do it. I'm having this error message: "Service operation failed: Controller operation failed: 404 Updating service "dest_tutorial" failed: Not Found: Error creating service "dest_tutorial" from offering "destination" and plan "lite": Could not create service instance "dest_tutorial". Service plan "lite" from service offering "destination" was not found. "

I was reading how to add an instance but I cannot find the destination service to create manually a new instance, even when I have it assigned correctly on Entitlements.

**Comment by IObert** [comment]
Hi,

it sounds like your missing the proper entitlement for this service. Can you follow along [this tutorial](https://developers.sap.com/tutorials/cp-cf-entitlements-add.html) to check if you have it?

**Comment by IObert** [comment]
I'll close it as the issue has been resolved/worked around
