### ISSUE TITLE
Get a Free Trial Account on SAP Cloud Platform

### ISSUE THREAD

**Issue by nhebling** [SAPDocuments/Tutorials#4819]
Tutorial URL: https://developers.sap.com/tutorials/hcp-create-trial-account.html

Please specify the step you are referring to:
Step 9: Understand the trial counter - Question.
The answer is not correct. The trial does end permanently as the data and configuration will be deleted and cannot be accessed anymore. Setting up a new account to start a new(!) trial is not the same as a never ending trial.

**Comment by IObert** [comment]
You're right, I'll replace the question with a more precise one.

Thanks!

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by IObert** [comment]
Reopen for me as a reminder
