### ISSUE TITLE
Display Data from the Northwind Service

### ISSUE THREAD

**Issue by miyasuta** [SAPDocuments/Tutorials#4823]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-fiori-cf-display-data.html

Step 5: Redirect traffic to the data source

First of all, thank you for providing this tutorial.
I followed below mission, and found that ui5-middleware-cfdestination had not been installed.
https://developers.sap.com/mission.sapui5-cf-launchpad.html

So I manually installed it and was able to connect to Northwind.
I might have missed some steps or prerequisites?

**Comment by IObert** [comment]
Hi @miyasuta,

I'm glad you were able to solve the issue. 
That is strange. I just tested it on my machine and the middleware has been installed by default. Is it possible that you are using an old version of the easy-ui5 generator?
You can check the version via `npm ls -g --depth=0`, it should be Version 1.3.1.

Another reason could be, that you interrupted the install process that has been triggered by yeoman.

**Comment by miyasuta** [comment]
Thanks for your advice.
I updated easy-ui5 generator and run tutorial again.
Now the middleware is added automatically.
