### ISSUE TITLE
Create Data Model and Lock Object in SAP Cloud Platform ABAP Environment

### ISSUE THREAD

**Issue by lekshmimili** [SAPDocuments/Tutorials#4825]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-lock-object.html

Please specify the step you are referring to

**Comment by lekshmimili** [comment]
Use of Entity I_BusinessUser is not permitted.

**Comment by thecodester** [comment]
@mervey45  Can you update this issue?

**Comment by mervey45** [comment]
Hi @lekshmimili ,


please make sure your system is up to date and you are using the correct version:

https://tools.hana.ondemand.com/#abap

Procedure
To install the front-end component of ADT, proceed as follows:

Get an installation of Eclipse 2020-03 (e.g. Eclipse IDE for Java Developers)
In Eclipse, choose in the menu bar Help > Install New Software...
Enter the URL https://tools.hana.ondemand.com/latest
Press Enter to display the available features.
Select ABAP Development Tools and choose Next.
On the next wizard page, you get an overview of the features to be installed. Choose Next.
Confirm the license agreements and choose Finish to start the installation.


Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
