### ISSUE TITLE
Create an API Provider System

### ISSUE THREAD

**Issue by NikolayStarikov** [SAPDocuments/Tutorials#4826]
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-create-provider.html

Please specify the step you are referring to

At step
UserName | <your_GATEWAY_username>
Password | <your_GATEWAY_password>

SAP SSO authentication data do not work and not cleaar which data to type for non-SAP users

**Comment by shilpavij** [comment]
Hello,

You need to create a different user for you backend.
https://developers.sap.com/tutorials/gateway-demo-signup.html

Regards
shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
