### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by ruiaakshay** [SAPDocuments/Tutorials#4829]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Please specify the step you are referring to

Deployment is stuck, Not able to test the integration flow.
![CPI_ERROR](https://user-images.githubusercontent.com/62788159/77817817-f354b480-70f3-11ea-9cf3-0a1c9664030c.PNG)

**Comment by Vikramkulkarni01** [comment]
Hi @ruiaakshay , 

Thanks for reaching out to us. 

I understand your concern, could you please share me the below details to investigate the issue further?

1. Global Account name & ID
2. Subaccount name and ID 
3. Error message or the screenshots. 

We truly appreciate your support and looking forward to hear from you. 

Regards, 
Vikram Kulkarni

**Comment by ruiaakshay** [comment]
Hello Vikram,

Please find the details below :

Global Account ID : S0007724782
Subaccount name and ID  : ruiaakshay@gmail.com /  S0007724782trial
Error :
[image: image.png]

Thanks & Regards,
Akshay Ruia

**Comment by Vikramkulkarni01** [comment]
Hi Akshay, 

Thank you for sharing the requested information with us. 

I have reported this issue to our development team and they are looking at on high priority.

I will keep you posted with an update as and when I hear from them. 

Thanks for understanding, 

Regards,
Vikram Kulkarni

**Comment by Vikramkulkarni01** [comment]
Hi Akshay, 

With reference to your concern, we worked with our internal teams and they have resolved the issue. 

Could you please check and let me know. 

Regards, 
Vikram Kulkarni

**Comment by ruiaakshay** [comment]
Thanks Vikram.

I will deploy the scenario and confirm you back.

Appreciate your help.

Thanks & Regards,
Akshay Ruia

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
