### ISSUE TITLE
2 Errors - Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by dbbanks** [SAPDocuments/Tutorials#4831]
Tutorial URL: https://developers.sap.com/group.abap-env-restful-managed.html

I have been able to successfully complete the 7 part tutorial except I receive 2 errors during the 7th tutorial at step 8 and step 13. At step 8.6, I can see the tile but when I click on it, I get the below error

_App could not be opened because the SAP UI5 component of the application could not be loaded.
Failed to load UI5 component for navigation intent "#TravelProcessor-display"_

I continue through the tutorial successfully until I get to step 13. At step 13.3, when I click on the Application Route, a separate browser window opens with an error that the _Site is Unavailable_.

Please see the details in the attached document. Please advise on how to complete the tutorial.

Thanks,
Derrick

[2 Errors - Develop a Fiori App Using the ABAP RESTful Programming Model.docx](https://github.com/SAPDocuments/Tutorials/files/4397861/2.Errors.-.Develop.a.Fiori.App.Using.the.ABAP.RESTful.Programming.Model.docx)

**Comment by chaouki-akir** [comment]
Hello,

I have the same error Step 8.6 "Select the TRAVEL_APP_XXX tile to test your application".
Here some informations from the console of the web browser :
![image](https://user-images.githubusercontent.com/23510132/77861234-b5ce5500-71e1-11ea-950d-e4625a1f3b89.png)

**Comment by mervey45** [comment]
Hi @dbbanks and @chaouki-akir ,

thank you for your feedback. There seems to be an issue. We are working on this. As soon as we have an answer, we'll update this tutorial.

Thank you for your understanding.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by PrinceJoshi** [comment]
Hi @MichaelCzcz  I am also facing the same issue. How did it resolve? Could you please provide the resolution.
![ui5_error_RAP](https://user-images.githubusercontent.com/40033219/80225510-ccdd5700-8668-11ea-871f-6dd08f0d10d2.PNG)


below is console:
![ui5_error_RAP_2](https://user-images.githubusercontent.com/40033219/80225535-d36bce80-8668-11ea-8ba5-1b56489d4e05.PNG)

SCP screenshot:
![ui5_error_RAP_3](https://user-images.githubusercontent.com/40033219/80225705-0a41e480-8669-11ea-90a2-14b33f5237b9.PNG)


Could you please help.

Regards,
Prince
