### ISSUE TITLE
Create a Card Component

### ISSUE THREAD

**Issue by jjaimes** [SAPDocuments/Tutorials#4832]
Tutorial URL: https://developers.sap.com/tutorials/ui5-webcomponents-react-card.html

Please specify the step you are referring to

**Comment by jjaimes** [comment]
Hi team,

**Step 1: Add components to MyApp.jsx. Number 1.**

I am sure you have to update the Storybook link. It is link to 

[current](https://sap.github.io/ui5-webcomponents-react/?path=/story/welcome-getting-started--page)
instead of 
[real](https://sap.github.io/ui5-webcomponents-react/?path=/docs/4-ui5-web-components-card--default-story)

Could you verify it?

Thanks,
José Jaimes

**Comment by Lukas742** [comment]
Hi @jjaimes 

Thanks for creating this issue. 
I created a PR: https://github.com/SAPDocuments/Tutorials/pull/4838

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
