### ISSUE TITLE
SAP HANA XS Advanced, Creating a Node.js Module

### ISSUE THREAD

**Issue by davyveilleux** [SAPDocuments/Tutorials#4833]
Tutorial URL: https://developers.sap.com/tutorials/xsa-xsjs-xsodata.html

Step 1: complete step 1 and try to build the new Node.js module with XSJS support. You got a strange compilation error : 
   "make: g++: Command not found"

I found the solution by increasing the version in package.json to "10.x" instead of "8.X". Quite tricky for a beginner. 

Thanks
Davy

**Comment by jung-thomas** [comment]
This is unfortunately a recent update required by the end of life of Node.js ver 8 but the templates in the Web IDE wizard aren't updated yet.  I've added a few sentences to the tutorial to address the necessary manual workaround steps.
