### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by iludi** [SAPDocuments/Tutorials#4834]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Please specify the step you are referring to:

 I am having problems since the application does not finish Starting status in Manage Integration Content. It takes more than 8 hours loading. What I can do?

![2020-03-29_10-37-01](https://user-images.githubusercontent.com/19378913/77865770-6f3f2180-7206-11ea-9807-27a538544614.png)

**Comment by Vikramkulkarni01** [comment]
Hi @iludi , 

Thanks for reaching out to us. 

I understand your concern, could you please share me the below details to investigate the issue further?

1. Global Account name & ID
2. Subaccount name and ID 
3. Error message or the screenshots. 

We truly appreciate your support and looking forward to hear from you. 

Regards, 
Vikram Kulkarni

**Comment by iludi** [comment]
Hi Vikram, 

Good morning, I attach requested information. Thanks for the help.

Global Account:  dan ega (P2002198312)
Subaccount p2002198312trial ID 91f06295-68e4-46e2-9236-43d1a129cf2e


Perform Tenant update, desploy and undeploy on item.



Best regards,
Daniel

**Comment by Vikramkulkarni01** [comment]
Hi Daniel,

Thank you for sharing the requested information with us.

I have reported this issue to our development team and they are looking at on high priority.

I will keep you posted with an update as and when I hear from them.

Thanks for understanding,

Regards,
Vikram Kulkarni

**Comment by iludi** [comment]
Thanks for the help, I remain attentive to the support to know how to advance.

Best regards,
Daniel

**Comment by Vikramkulkarni01** [comment]
Hi Daniel,

With reference to your concern, we worked with our internal teams and they have resolved the issue.

Could you please check and let me know.

Regards,
Vikram Kulkarni

**Comment by iludi** [comment]
Hi Vikram,
I checking and is correct!, thank's all team.
Regards,
Daniel Egaña

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
