### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by ASAPADVISORY** [SAPDocuments/Tutorials#4839]
Hello,

I am running tuto Develop a Fiori App Using the ABAP RESTful Programming Model (Managed Scenario).

Everything works well instead of in last steps:

Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules
Step 8: Test UI on Cloud Foundry

When run configuration I have some error message:
<img width="1394" alt="Capture d’écran 2020-03-30 à 14 18 16" src="https://user-images.githubusercontent.com/62886108/77911638-68a9bc00-7291-11ea-8385-33f7ee79c571.png">

Workspace Name: MTA_PROJECT_AGI2 >TRAVEL_APP_AGI2

I am beginner, thanks for helping :)

Alex

**Comment by mervey45** [comment]
Hi @ASAPADVISORY ,

thank you for your feedback. There seems to be an issue. We are working on this. As soon as we have an answer, we'll update this tutorial.

Thank you for your understanding.

Best regards, 
Merve

**Comment by ASAPADVISORY** [comment]
Hello,
Thank you for your quick feedback. I will try again as soon as I have your GO.

BR,

Alex

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
