### ISSUE TITLE
Debug Your SAPUI5 App with SAP Web IDE

### ISSUE THREAD

**Issue by ASAPADVISORY** [SAPDocuments/Tutorials#4850]
Hello,

I am running SAP tutotorial:
Debug Your SAPUI5 App with SAP Web IDE

On step:
Step 4: Add a breakpoint

There is an error message because debugger command is not allowed. We can see the error in the screenshot of the tutorial.

<img width="984" alt="Capture d’écran 2020-03-31 à 11 40 37" src="https://user-images.githubusercontent.com/62886108/78012499-538e6500-7345-11ea-8f74-9528115fcb32.png">

I am beginner and I don't know how to allow debugger command.

Thanks for helping :)

Alex

**Comment by IObert** [comment]
Hi Alex,

in this case, it is only a warning from the WebIDE to remind you that you should deploy code with breakpoints. For the sake of the tutorial, this is completely fine :)

PS: You can tell the Web IDE that it shouldn't consider this an error in the eslint settings of your project (rule: no-debugger)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by ASAPADVISORY** [comment]
Thank you for your answer :)
