### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by davyveilleux** [SAPDocuments/Tutorials#4858]
Hi,
 I got the exact same issue as Endersk, wrong default HDI container.
Tutorial URL: https://developers.sap.com/tutorials/xsa-create-user-provided-anonymous-service.html
Step 6: Grant privileges to the schema
Build failed using "cfg/plain.hdbgrants":

I understand the recomendatation that he gives, but don't know how to apply it. From what I understand the build complains about granting access to schema to user "DB_1#OO" that does not exist in HXE DB. But how do I remap the schema PLAIN to HXE DB instead of default SYSTEM DB?

Thanks for the hint
Davy

_Originally posted by @Endersk in https://github.com/SAPDocuments/Tutorials/issues/3888#issuecomment-530767823_

**Comment by jung-thomas** [comment]
You need to change the port number in the User Provided Service. This controls which tenant you connect to in order to apply the grant.

**Comment by davyveilleux** [comment]
Ok, so in my Cockpit under Services and User-Provided Services, I already use "port": "39013", which should point to my HXE.  How do I confirm on which port my HXE is mapped compared to SYSTEMDB.
![image](https://user-images.githubusercontent.com/62529446/78129920-568d6200-73e6-11ea-8bdf-8b26315fa114.png)

Thanks Thomas
Davy

**Comment by jung-thomas** [comment]
You can run this query in the SYSTEMDB and it will report the ports for all services in your system.
SELECT DATABASE_NAME, 
	SERVICE_NAME, 
	PORT, 
	SQL_PORT
FROM SYS_DATABASES.M_SERVICES;

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
