### ISSUE TITLE
Issue in accessing the destination

### ISSUE THREAD

**Issue by JOSEPHSASIKANTHREDDY** [SAPDocuments/Tutorials#4860]
Hi, 
I followed Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules tutorial and it worked fine for me.
After that i wanted to create my own app and deploy.In the process i've configured a destination in cockpit and added in my xs-app.json but while accessing i face Internal Server Error.
Could you please help me here.
Below are the necessary details.
My destination:
![image](https://user-images.githubusercontent.com/8137364/78108555-42ad2480-7415-11ea-9f05-692a608166cd.png)

xs-app.json:
![image](https://user-images.githubusercontent.com/8137364/78108605-5c4e6c00-7415-11ea-8792-46aa9ea25987.png)

mta.yml:
![image](https://user-images.githubusercontent.com/8137364/78108670-7ab46780-7415-11ea-8a83-4bbb005816f0.png)

This is the error i am facing:
![image](https://user-images.githubusercontent.com/8137364/78110694-1398b200-7419-11ea-9457-a99cb69da80e.png)

Thanks.

**Comment by mervey45** [comment]
Hi @JOSEPHSASIKANTHREDDY,

thank you for your feedback. There seems to be an issue with SAP Web IDE. We are working on this. As soon as we have an answer, we'll update this tutorial.

But regards to your Internal Server Error with your own app and deployment, it is better to open a ticket on the following component:  BC-CP-ABA.

Thank you for your understanding.

Best regards,
Merve
