### ISSUE TITLE
Add SAP Cloud Platform Service from the dev Space

### ISSUE THREAD

**Issue by derkorn** [SAPDocuments/Tutorials#4863]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Please specify the step you are referring to

Step 4:
3. Reuse Instance:
I followed every step and until now I had no problems. But now, the system does not find my Service Name (it shows "No data") - as I added the ABAP-trial service from the marketplace in a previous step, I used my first name as service name. Even when I type my name into the Service Name textfield and Resource Name, nothing happens. The "Next" Button stays grey... :-(

<img width="959" alt="image" src="https://user-images.githubusercontent.com/37311123/78192958-95202c80-7479-11ea-92de-505cd7dd536e.png">

Then I've chosen "Add Instance" instead, thus I got a message, that I'm not allowed to create one - this I only tried, because the "Reuse" Option did not work.

Thank you. 
Best regards, Thorsten

**Comment by mervey45** [comment]
Hi @derkorn ,

have you also finished the following tutorial: 
https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html ?

You need a service instance to get an instance name shown.

Best regards, 
Merve

**Comment by derkorn** [comment]
> Hi @derkorn ,
> 
> have you also finished the following tutorial:
> https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html ?
> 
> You need a service instance to get an instance name shown.
> 
> Best regards,
> Merve

Hi Merve,
thank you for your reply!

Yes, I think I did this the right way! This is how it looks on my account:

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/37311123/78234226-25d92580-74d7-11ea-8d4a-e7db0d64246f.png">

Instead of "merve-temel" I use my first name "thorsten". The rest of the tutorial (service key creation, the later integration into eclipse worked successfully for me! 

Strange behaviour... is there an option to do a refresh on the cloud environment? Just to make sure, that the WebIDE refers to the latest system configuration? 

Thank you,
best regards,
Thorsten

**Comment by thecodester** [comment]
@mervey45 Can you update this issue?

**Comment by mervey45** [comment]
Hi @derkorn ,

do you use the region US(VA) as your gobal account? This is a new feature. We only do support US(VA) currently. 

Please make sure, you are using this region.

Otherwise, feel free to contact me again.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
