### ISSUE TITLE
Register SAP Cloud Platform Cloud Foundry Subaccount in Identity Authentication Service

### ISSUE THREAD

**Issue by qinghe721** [SAPDocuments/Tutorials#4870]
Tutorial URL: https://developers.sap.com/tutorials/cp-ias-azure-ad-cf.html

Please specify the step you are referring to:
Step 10: Test your configuration - no option to select Microsoft Azure Directory, after completing all the configuration step, even after de-selecting the "SAP ID Service"
<img width="1403" alt="图片" src="https://user-images.githubusercontent.com/32155650/78352366-cc5a1f00-75da-11ea-9ff1-68a0309921a8.png">
![图片](https://user-images.githubusercontent.com/32155650/78352488-f9a6cd00-75da-11ea-87bb-2ed3eaca3e60.png)

**Comment by maxstreifeneder** [comment]
Hi, 

hard to tell what the issues here is but what's the url you are accessing (where you have taken the screenshot)? 

They need to match the subdomain + region of the subaccount you are configuring the trust configuration. 
![image](https://user-images.githubusercontent.com/36535298/78360803-a2dbcc00-75b7-11ea-9af4-814680bf6b2a.png)

**Comment by maxstreifeneder** [comment]
same issue in #4880

**Comment by MichaelCzcz** [comment]
@qinghe721 Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
