### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by kevinnoll** [SAPDocuments/Tutorials#4871]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Please specify the step you are referring to: Step 13.

Hello guys, I did the whole tutorial, and everything worked fine until the last step. 
When I click on the link given from my approuter, the FLP opens and I am able to log in, which is still fine. 
After Clicking on the app tile, the app opens but is not able to retrieve the metadata file from the abap backend. Instead, it is showing me a 404:
![image](https://user-images.githubusercontent.com/5312110/78359289-16c8a500-75b5-11ea-8aec-a06b474745f4.png)

Directly navigating to the /test/flpSandbox.html file of the app to have the app displayed standalone does not work for the same reason.

Best,
Kevin

**Comment by mervey45** [comment]
Hi @kevinnoll ,

thank you for your feedback. There seems to be an issue. We are working on this. As soon as we have an answer, we'll update this tutorial.

Thank you for your understanding.

Best regards,
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
