### ISSUE TITLE
Deploy Your Node.js App with the Cloud Foundry CLI

### ISSUE THREAD

**Issue by sdanter** [SAPDocuments/Tutorials#4872]
Tutorial URL: https://developers.sap.com/tutorials/cp-node-deploy-cf-cli.html

Please specify the step you are referring to

Step 1: 
In the code example for the yaml file, "random route" is used, but this term does not show up in the table explaining the properties at the end of step 1. Instead, you find "host" explained there. 

<img width="651" alt="step1" src="https://user-images.githubusercontent.com/62387758/78367216-010dac80-75c2-11ea-8844-aad0496dcb3f.PNG">

<img width="645" alt="step1_2" src="https://user-images.githubusercontent.com/62387758/78367227-0539ca00-75c2-11ea-9e59-2a3566c9519b.PNG">

**Comment by maxstreifeneder** [comment]
thanks for the note! Will change it :-)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
