### ISSUE TITLE
Manage Message Processing in Case of Errors

### ISSUE THREAD

**Issue by ravipativenu** [SAPDocuments/Tutorials#4874]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-handle-exceptions.html

Please specify the step you are referring to

What are the different message processing status in SAP Cloud Platform Integration?

I am answering 
Completed, Failed, Accepted.

My answer is not getting accepted. Could you please help me what i am doing wring.

Thank you,
Venu

**Comment by thecodester** [comment]
@ravipativenu There is no "Accepted" answer ??? There is clearly one that you are missing.

@gauthamkrishna-sap Can you make sure the question has the correct answers?

**Comment by gauthamkrishna-sap** [comment]
Hello,
The right answers are completed, failed and error. 
Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
@gauthamkrishna-sap Can I close this issue?

**Comment by gauthamkrishna-sap** [comment]
@MichaelCzcz Please wait for the updates to be published. i will notify you.

**Comment by MichaelCzcz** [comment]
@gauthamkrishna-sap Any updates?

**Comment by gauthamkrishna-sap** [comment]
Hello,
We are working on overhauling the entire tutorial series and will publish the updates shortly. Apologies for the delay in response.
Thanks & Best Regards, Gautham

**Comment by gauthamkrishna-sap** [comment]
@MichaelCzcz This issue can be closed now.
