### ISSUE TITLE
Add UI Annotations for Detail and List Screens and Connect to Text Tables

### ISSUE THREAD

**Issue by jkopcinski** [SAPDocuments/Tutorials#4876]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-text-table.html

Step 1. pt.1 The code below the red box contains superfluous annotations: @Semantics.user.createdBy,  @Semantics.user.lastChangeBy, and 2 x @Semantics.systemDateTime.lastChangedAt
The screenshot is inconsistent with ABAP source in Step 1. pt 2 and could be misleading

**Comment by mervey45** [comment]
Hi @jkopcinski ,

we will update this mistake as soon as possible. Thank you for your feedback. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
