### ISSUE TITLE
Call an External Endpoint to Retrieve Additional Information

### ISSUE THREAD

**Issue by iludi** [SAPDocuments/Tutorials#4877]
Hi Team!
Has anyone had the following error? I have an error in line 26 of groovy code.

![2020-04-04_17-33-10](https://user-images.githubusercontent.com/19378913/78460855-dd6a6500-769a-11ea-824e-ef8652c331cc.png)

Tutorial URL: https://developers.sap.com/tutorials/cp-integration-consume-external-api.html

Please specify the step you are referring to

best regards,
DE

**Comment by gauthamkrishna-sap** [comment]
Hello,
We are working on overhauling the entire tutorial series and will publish the updates shortly. Apologies for the delay in response.
Thanks & Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
