### ISSUE TITLE
Implement the Transport for Your Factory Calendar

### ISSUE THREAD

**Issue by jkopcinski** [SAPDocuments/Tutorials#4878]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-transport.html

Step 1. pt 4. Source Line 27:
    me->transport_api = cl_a4c_bc_factory=>get_handler( ).

Error: Use of class CL_A4C_BC_FACTORY is not permitted
It seems that the class is not release for Cloud.

Step 2. pt 12. Source line 10
  DATA(holiday_transport) = NEW zcl_cal_holiday_transport_xxx( )( ).

Syntax error - Double ()() at the end

**Comment by mervey45** [comment]
Hi @jkopcinski ,

which system are you using? You can do this tutorial with SAP Cloud Platform ABAP environment.
You can either use your trial user or do it with a licensed user.

Best regards, 
Merve

**Comment by jkopcinski** [comment]
I'm using SAP Cloud Platform ABAP Trial system. The code doesn't compile due to 
"Error: Use of class CL_A4C_BC_FACTORY is not permitted"

**Comment by thecodester** [comment]
@Merve ?

**Comment by mervey45** [comment]
Hi @jkopcinski ,

this tutorial does not work with the ABAP Trial system. We have a license key embedded in this tutorial. You need to have an ABAP license system.

Best regards,
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
