### ISSUE TITLE
Use Machine Learning to Extract Information from Documents

### ISSUE THREAD

**Issue by jitendrakansal** [SAPDocuments/Tutorials#4879]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dox-swagger-ui.html

Step 3: Create a client 

Value for **ClientId** would be from **doc-info-extraction-key**, right? 
What about **clientName**? Where do i get it from?

**Comment by Juliana-Morais** [comment]
Hello,

No, in step 3, clientId  and clientName values are anything you want as long as you follow the format below.

Single client: {"value":[{"clientId":"c_00","clientName":"client 00"}]}
Multiple clients: {"value":[{"clientId":"c_00","clientName":"client 00"}, {"clientId":"c_01","clientName":"client 01"}]}

Best regards,
Juliana
