### ISSUE TITLE
Register SAP Cloud Platform Cloud Foundry Subaccount in Identity Authentication Service

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#4880]
Tutorial URL: https://developers.sap.com/tutorials/cp-ias-azure-ad-cf.html

Please specify the step you are referring to:

Have a few questions on this whole series of Tutorials. 

- On the Login window I did not have the "or sign in with" Azure AD Tutorial link showing up at all. I  even deactivated the SAP ID service in the Trust configuration of my CF trial account. 
- The application name in earlier steps was My SAP Tutorial however then it changed to 'MyAzureTutorial' in Step 9 (as I saw in the screenshots) so not sure if they have the same settings?
- There are no steps here that point the CF application (added into SCIAS) to use the Azure AD identity provider. Even though we set this up in the Corporate Identity Provider section we have not pointed it to the application. I'm assuming this would show the additional link in the pop-up. 
- When I entered my URL according to Step 9 I just got the normal login screen - Welcome to trial! so this is not even going to the SCIAS tenant. I did notice though that the URL from the SAML metadata link has   aws-live-eu10 in it so I'm not sure whether this is causing issues. 

I did get the correct response at the end 'Where to?' however I am not convinced that this is linked up to SCIAS nor Azure AD and seriously confused given I deactivated the SAP ID service altogether in the Trust settings. 

Thanks & Kind Regards
Phil Cooley

**Comment by maxstreifeneder** [comment]
Hey Phil,

thanks for the detailed feedback! Already sent you DM to go over the particular issues.

Thanks in advance!
Max

**Comment by maxstreifeneder** [comment]
Hi Phil, 

quick question: 
could you please send me a few more details for further investigation (guess I could reproduce the issue): 

- The about information (essentially the Feature Set A or Feature Set B information behind "about"):
![image](https://user-images.githubusercontent.com/36535298/78587432-37a32b80-783d-11ea-8d33-5db33b71beb9.png)

- Are you using it in a trial environment/production environment? 
- Which Region? (AWS EU10, Azure EU20, etc?) 

Thanks a lot in advance! 
Max

**Comment by pjcools** [comment]
Hey Max

Sorry for late reply. Responses are:
- About info -> Feature Set A
- Using Trial account
- Region AWS EU10. Host = neo-eu1-trial-cf

Did you send me a meeting for 4.00pm today? Just could not see it although I could have missed the invite. If you can send through. Also, we are not in Daylight savings time anymore :-) so not sure if this changes the time you were thinking of. I can do anytime really so all good. 

Thanks
Phil

**Comment by maxstreifeneder** [comment]
Hey Phil,

sorry for coming back that late but I couldn't reproduce the issue with some other folks.

a) do you have the same issue in your enterprise account?
b) would you mind checking again when your trial is expired & newly created? Hopefully it's gone then. 

Sorry that we couldn't find an explanation. 

Cheers,
Max

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
