### ISSUE TITLE
Get Started with Document Information Extraction

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#4881]
Mission URL: https://developers.sap.com/mission.cp-aibus-extract-document-service.html

Hi, is there a Badge availeble for this Tut?

Regards

**Comment by Juliana-Morais** [comment]
Hi Marco, 

There's a badge for this tutorial mission (the same icon as on the mission). Badges are given out once a week (so if you finish it Sunday you'll see it by end of the week.

Best regards,
Juliana

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by marcobuescher** [comment]
Hello,

not shure, if you listet it here:
https://community.sap.com/resources/missions-badges

**Comment by Juliana-Morais** [comment]
Hi Marco,

Our tutorial is not listed there. I'll follow up with the Tutorial Navigator team.

Best regards,
Juliana

**Comment by Juliana-Morais** [comment]
Hi Marco,

The Get Started with Document Information Extraction (https://developers.sap.com/mission.cp-aibus-extract-document-service.html) mission has been added to https://community.sap.com/resources/missions-badges.
Thank you for letting us know it was not there.

Best regards,
Juliana

**Comment by marcobuescher** [comment]
Hello, the Badge is on the list, but there is still no badge in my profile... :)

**Comment by Juliana-Morais** [comment]
Hi Marco,

I'll follow up with the responsible team and get back to you.

Best regards,
Juliana

**Comment by marcobuescher** [comment]
No stress, I just wanted to say...

**Comment by Juliana-Morais** [comment]
Hi Marco,

Can you please check if you have the badge now? 

Best regards,
Juliana

**Comment by marcobuescher** [comment]
Hello Juliana,

yes, I got yesterday a E-Mail and I found it today  on my Profil... 

Regards

Marco
