### ISSUE TITLE
Create Your First Integration Package and Integration Flow

### ISSUE THREAD

**Issue by jkopcinski** [SAPDocuments/Tutorials#4883]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-create-iflow.html

Step 1.
Incorrect description:
Click the **Discover** tab (pencil icon) to access your workspace. 
Should be:
Click the **Design** tab (pencil icon) to access your workspace.

**Comment by Vikramkulkarni01** [comment]
Hi @jkopcinski , 

Thanks for reaching out to us 

We made corrections from our end and it will be updated at the earliest.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
