### ISSUE TITLE
Create Your First Application with SAP Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by miyasuta** [SAPDocuments/Tutorials#4885]
Tutorial URL: https://developers.sap.com/tutorials/s4sdkjs-odata-service-cloud-foundry.html

Step 4: Execute an OData request
Problem: I'm getting an error 'Error: get request to https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER failed! '

I'm using SAP API Business Hub sandbox and my code is blow:
`function getAllBusinessPartners(): Promise<BusinessPartner[]> {
    return BusinessPartner.requestBuilder()
    .getAll()
    .withCustomHeaders({ APIKey: '<API Key>'})
    .execute({
        url: 'https://sandbox.api.sap.com/s4hanacloud'
    });
}`

I'm running this app behind proxy. 
Calling the same API from Postman works fine.
I see below error messages in console.
`Error: get request to https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER failed!
    at Object.errorWithCause (C:\Users\11436858\sapui5Local\cloudSDK\my-sdk-project\node_modules\@sap-cloud-sdk\util\dist\error.js:5:20)
    at constructError (C:\Users\11436858\sapui5Local\cloudSDK\my-sdk-project\node_modules\@sap-cloud-sdk\core\dist\request-builder\request\odata-request.js:206:19)
    at C:\Users\11436858\sapui5Local\cloudSDK\my-sdk-project\node_modules\@sap-cloud-sdk\core\dist\request-builder\request\odata-request.js:195:73
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\11436858\sapui5Local\cloudSDK\my-sdk-project\node_modules\@nestjs\core\router\router-execution-context.js:45:28
    at async C:\Users\11436858\sapui5Local\cloudSDK\my-sdk-project\node_modules\@nestjs\core\router\router-proxy.js:8:17
Caused by:
Error: getaddrinfo ENOTFOUND sandbox.api.sap.com`

**Comment by FrankEssenberger** [comment]
Hello miyasuta ,

I just tried the code snipped and it works fine so the reason is definitely the proxy you have as indicated already b the last part of the stack trace.

If you are accessing the destination via the destination methods of the SDK it sould add the proxy configuration automatically from the env varialbes `http_proxy` and `https_proxy`. For a test you could extend the destination you put in the `execute()` with the proxyConfiguration:

```json
{
 url: 'https://sandbox.api.sap.com/s4hanacloud' 
proxyConfiguration:{
  host: 'yourHost',
port: 1234
protocol: 'http' or 'https'
   }
}
``` 

If this is working you should add the destination in the env variable and use `getDestination()` from the `destination-accessor.ts` to do this automatically.

I hope this help.

**Comment by miyasuta** [comment]
Hello Frank,

Thank you for your quick response. Above code worked fine.
How can I use `getDestination()` to work with `execute()` ?

I took below steps.
1. Added below destination to my .env file.
```
    {
        "name": "APIHub", 
        "url": "https://sandbox.api.sap.com/s4hanacloud",
        "proxyConfiguration" : {
                "host": 'proxy host',
                "port": port,
                "protocol": "http"
        }
    }
```
2. execute
```
        .execute({
            destinationName: "APIHub"
        })
```
This led to error `Could not find a destination with name "APIHub"! Unable to execute request`.

**Comment by FrankEssenberger** [comment]
Good that it worked when you put the proxy by hand, so we also verified our code with some real life proxy example. You did also everything right but you need a key `destinations` in the env variables which contains a list of possible destination in other words:

```
process.env['destinations'] = [
{
        "name": "APIHub", 
        "url": "https://sandbox.api.sap.com/s4hanacloud",
        "proxyConfiguration" : {
                "host": 'proxy host',
                "port": port,
                "protocol": "http"
        }
    }
]
```
When you execute the request it should find the destination in the env and parse it.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by miyasuta** [comment]
Thank you Frank!
Now the app is working with .env configuration.
