### ISSUE TITLE
Create Your First Fiori for iOS App

### ISSUE THREAD

**Issue by flow23** [SAPDocuments/Tutorials#4887]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-scpms-teched18-02.html

Step 4: I'm not able to enable the box for "Use Discovery Service for Application bootstrapping". I got a popup error message regarding issue with domain name.

**Comment by KevinMuessig** [comment]
Hi @flow23 ,

this tutorial is not going to be updated to version 5 of the SDK. I am sorry that you ran into issues there. Soon there will be a replacement which is fully up-to-date.

**Comment by KevinMuessig** [comment]
@flow23 ,

If you still want to complete it, make sure you use the version 4.0.10 SDK for this tutorial. The Discovery Service is a bit hidden and you have to scroll down in the assistant to see it. By default it should be activated.

**Comment by CONCETO-flow** [comment]
Thank you very much @KevinMuessig. Forwarding to my business account @CONCETO-flow.
