### ISSUE TITLE
Connect to the SAP HANA Cockpit

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#4888]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-connect-hana-cockpit.html

Please specify the step you are referring to before 1.

Any plans to open up the hana service dashboard to trial accounts, so step 1 of the tutorial can be executed? 

thx, greg

**Comment by jung-thomas** [comment]
No. There are no plans to change the way that HaaS works in trial. HaaS will be replaced in the long term by the new HANA Cloud and it will have a different trial experience which is planned to launch later this year.
