### ISSUE TITLE
Set up Secure Tunnel between ABAP System and SAP Cloud Platform (CF)

### ISSUE THREAD

**Issue by xkeaton** [SAPDocuments/Tutorials#4889]
Tutorial URL: https://developers.sap.com/tutorials/cp-connectivity-create-secure-tunnel.html

Please specify the step you are referring to

Enter the internal host and port of your ABAP system 

how?

**Comment by JensHaley** [comment]
This tutorial is part of the following tutorial group:
https://developers.sap.com/group.cp-connectivity-odata.html

Did you complete the first tutorial of this group? This one:
https://developers.sap.com/tutorials/cp-connectivity-configure-fiori-reference-apps.html

* In [Step 5](https://developers.sap.com/tutorials/cp-connectivity-configure-fiori-reference-apps.html#6896c7cb-613e-4e1e-a551-dce8aafaef26) is described how to find out the HTTP port of your ABAP system.
* In [Substep 8 of step 6](https://developers.sap.com/tutorials/cp-connectivity-configure-fiori-reference-apps.html#cb57b867-a01b-4e81-bb7c-50c684a17d29)  you should see the host address in the URL field of the browser while testing the OData service. 

Hope this helps, kind regards
Jens

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
