### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by ericavieira3** [SAPDocuments/Tutorials#4890]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Please specify the step you are referring to

I am not able to test:

I am getting the error:

Error Details
com.sap.it.rt.adapter.http.api.exception.HttpResponseException: An internal server error occured: Failure converting a node of class javax.xml.transform.sax.SAXSource: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog..
The MPL ID for the failed message is : AF6LhdTdfVpIqitOnexqXGWVyzm4
For more details please check tail log.

**Comment by Vikramkulkarni01** [comment]
Hi @ericavieira3 , 

Thanks for reaching out to us. 

I understand your concern, could you please share me the below details to investigate the issue further?

1. Global Account name & ID
2. Subaccount name and ID 
3. Error message along with the screenshots. 

We truly appreciate your support and looking forward to hear from you. 

Regards, 
Vikram Kulkarni

**Comment by ericavieira3** [comment]
Hello Vikram,Follow the information;Name: Erica Rodrigues Viera (S0020983599)ID:S0020983599E-Mail:erica.vieira@ibm.com\Global Account: S0020983599trialSubaccount DetailsSubdomainEUROPE1ID7a64581b-f236-420d-a38e-742806ef84faAttached are the screens with the logs and other information.Thank youErica VieiraIBM Global Business ServicesSAP ConsultantMobile +55 11 967089794e-mail: erica.vieira@ibm.com                                                  -----Vikram Kulkarni <notifications@github.com> wrote: -----To: SAPDocuments/Tutorials <Tutorials@noreply.github.com>From: Vikram Kulkarni <notifications@github.com>Date: 04/07/2020 04:13AMCc: ericavieira3 <erica.vieira@ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [SAPDocuments/Tutorials] Design and Test Your First Integration Flow (#4890)Hi @ericavieira3 ,Thanks for reaching out to us.I understand your concern, could you please share me the below details to investigate the issue further?Global Account name & IDSubaccount name and IDError message along with the screenshots.We truly appreciate your support and looking forward to hear from you.Regards,Vikram Kulkarni

**Comment by Vikramkulkarni01** [comment]
Hello @ericavieira3, 

I don't see any error screenshots. I executed the tutorial https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html again and don't see any issues. 

Could you please retest and let us know at which step you are facing this error message?

**Comment by ericavieira3** [comment]
HiDid you not received my attached file?No problem, now I am seending the screensots hereErica VieiraIBM Global Business ServicesSAP ConsultantMobile +55 11 967089794e-mail: erica.vieira@ibm.com                                                  -----Vikram Kulkarni <notifications@github.com> wrote: -----To: SAPDocuments/Tutorials <Tutorials@noreply.github.com>From: Vikram Kulkarni <notifications@github.com>Date: 04/08/2020 06:03AMCc: ericavieira3 <erica.vieira@ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [SAPDocuments/Tutorials] Design and Test Your First Integration Flow (#4890)Hello @ericavieira3,I don't see any error screenshots. I executed the tutorial https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html again and don't see any issues.Could you please retest and let us know at which step you are facing this error message?

**Comment by ericavieira3** [comment]
Hi,The exercise worked now, but only when I unchecked the option "Add XML Root Element" as below:Erica VieiraIBM Global Business ServicesSAP ConsultantMobile +55 11 967089794e-mail: erica.vieira@ibm.com                                                  -----Erica Vieira/Brazil/IBM wrote: -----To: SAPDocuments/Tutorials <reply@reply.github.com>From: Erica Vieira/Brazil/IBMDate: 04/08/2020 08:20AMCc: SAPDocuments/Tutorials <Tutorials@noreply.github.com>, Mention <mention@noreply.github.com>Subject: Re: [EXTERNAL] Re: [SAPDocuments/Tutorials] Design and Test Your First Integration Flow (#4890)HiDid you not received my attached file?No problem, now I am seending the screensots hereErica VieiraIBM Global Business ServicesSAP ConsultantMobile +55 11 967089794e-mail: erica.vieira@ibm.com                                                  -----Vikram Kulkarni <notifications@github.com> wrote: -----To: SAPDocuments/Tutorials <Tutorials@noreply.github.com>From: Vikram Kulkarni <notifications@github.com>Date: 04/08/2020 06:03AMCc: ericavieira3 <erica.vieira@ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [SAPDocuments/Tutorials] Design and Test Your First Integration Flow (#4890)Hello @ericavieira3,I don't see any error screenshots. I executed the tutorial https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html again and don't see any issues.Could you please retest and let us know at which step you are facing this error message?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
