### ISSUE TITLE
Secure a Basic Node.js App with the Authorization and Trust Management Service (XSUAA)

### ISSUE THREAD

**Issue by felikowski** [SAPDocuments/Tutorials#4892]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-security-xsuaa-create.html

Hey, i just stepped over this very interesting tutorial and wondered: Would this also work with a HANA XSA system in the ConvergedCloud which provides some application servers built with node.js? I believe, in SCP CF and also in this tutorial, there is also a HANA XSA behind, so it should be possible to do the same things there, right?My goal is to connect an IAS tenant to the backend of our applications and to do role management via the saml token that gets provided by the IAS tenant after authentification.
I would be very happy about an answer. 

Kind regards,
Felix

**Comment by felikowski** [comment]
just noticed that i was logged in into github via my private github account. As i am also an SAP employee, you can also contact me via MS Teams or email, my name is Felix Glockner

**Comment by nedo-SAP** [comment]
Hi @felikowski , I sent you an email :)

**Comment by MichaelCzcz** [comment]
@nedo-SAP @felikowski Can this issue be closed then?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
