### ISSUE TITLE
Add Data Visualization to the App - Part 2

### ISSUE THREAD

**Issue by CONCETO-flow** [SAPDocuments/Tutorials#4894]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-scpms-teched18-06.html

Step 1: The bar chart implemtation doesn't work. e.g. line and waterfall are working fine though.

**Comment by KevinMuessig** [comment]
Hi @CONCETO-flow ,

Please when working with this tutorial series use the mentioned SDK version. The mission is not fully compatible with SAP Cloud Platform SDK for iOS V 5.0. There will be a replacement soon.
