### ISSUE TITLE
Execute the PAL Auto Smoothing algorithm (Forecast App)

### ISSUE THREAD

**Issue by jameslim87** [SAPDocuments/Tutorials#4899]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aa-forecast-15.html

file name is mixed with smoothing and smooting.
Therefore, we need to change file name and some XML files.
Please check it and update it properly.

**Comment by jameslim87** [comment]
I fixed it and updated in my git hub.

https://github.com/jameslim87/forecast.git

I did same thing for movielens that I opened the ticket #4912

https://github.com/jameslim87/movielens.git

**Comment by thecodester** [comment]
@jarjarbentley Updates?

**Comment by jarjarbentley** [comment]
thanks for the correction.
