### ISSUE TITLE
Enable SAP Cloud Platform Mobile Services

### ISSUE THREAD

**Issue by prateekjais** [SAPDocuments/Tutorials#4900]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-hcpms-setup.html

Please specify the step you are referring to Step 1:Open the SAP Cloud Platform Cockpit

![Submit Answer Button Error](https://user-images.githubusercontent.com/37372220/78772279-2417d200-79af-11ea-9a2b-0768a10ea78f.JPG)

**Comment by KevinMuessig** [comment]
Hi @prateekjais , do you mean for the question? Do you want me to reference the step in the question?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
