### ISSUE TITLE
Quick Start with the Mobile Development Kit (MDK)

### ISSUE THREAD

**Issue by rpanneel** [SAPDocuments/Tutorials#4903]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-dev-kit-quick-start.html

Please specify the step you are referring to

In step 1, sub step 5 I receive a bad request on clicking get service:
![image](https://user-images.githubusercontent.com/1115693/78825798-d87e1c00-79e0-11ea-9bd0-2250137117b7.png)

I completed https://developers.sap.com/tutorials/cp-mobile-dev-kit-ms-setup.html without any issues. The destination in Neo is also created to point to the cf mobile services and when I do check connection it gives success.

Kind regards,

Robin

**Comment by rpanneel** [comment]
More information: 
It looks like the Mobile connectivity ping also fails:
![image](https://user-images.githubusercontent.com/1115693/78880558-e1f59b80-7a55-11ea-891d-2c9e72784c65.png)

**Comment by Juliana-Morais** [comment]
@MichaelCzcz: please assign to the responsible person. Thank you!

**Comment by rpanneel** [comment]
Without a change from my side it now works, so maybe it was a minor issue on server side.

Closing the issue.
