### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by kumser0** [SAPDocuments/Tutorials#4907]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to: 11 (last step)

In the last step we deploy the app to CF. Tutorial also says how to start the deployed app, using the link: <URL_from_application_overview_page>/<mynamespace><project_name>/index.html

The tutorial does not say what should happen when starting the app, but I suppose it should list the business partners same way as it did when starting from SAP Business Application Studio. But it does not - instead the list shows "Drop list items here" (no data text).
![image](https://user-images.githubusercontent.com/51796490/78882413-503b5d80-7a58-11ea-9fc8-0de1d8aa6ee0.png)

Is it expected that the deployed app also access and lists data? (I guess so) If yes, what could be the issue or missing step?

Note: the same app started from  SAP Business Application Studio works fine and lists the data.

**Comment by raz-korn** [comment]
Hi @kumser0 ,

Please check the dataSources uri setting in manifest.json (in the webapp folder of the BusinessPartners HTML5 module). if it looks like this "uri": "/sap/opu/odata/iwbep/GWSAMPLE_BASIC/", you should remove the '/' preceding 'sap'. it should look like the following: "uri": "sap/opu/odata/iwbep/GWSAMPLE_BASIC/",

Regards,
Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by kumser0** [comment]
Hi @raz-korn ,
yes that helped and I see the desired result!
Nice to know though how to avoid it future, or do I always has to change the uri manually?

**Comment by raz-korn** [comment]
1. This is a bug that should be fixed.
2. If the data source is added as part of the project creation wizard, you will not encounter this issue. Only if the data source is added using the command palette consume service.
BTW - I'm updating the tutorial to use the template wizard instead of yo and it will include the data source binding as part of the wizard.
