### ISSUE TITLE
Create Cards with Actions to Enable Workflows (Like Approve Or Reject)

### ISSUE THREAD

**Issue by schmidinger** [SAPDocuments/Tutorials#4908]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-action.html

Please specify the step you are referring to
Step 5: Add Reject Action
If Is Nullable == Uncheck then the reject action does not work on my iPhone XR (Version 13.3.1). I run the latest version of mobile cards (20.3.1). If I check is nullable then I can reject the card.

**Comment by sandeep-tds** [comment]
Hi @schmidinger, 

Thank you for bringing this to our notice.  I'm sorry the response took some time because I was trying to identify the iPhone XR device. 

I have identified a device for the test and will be getting back to you on it by tomorrow. 

Thank you so much for your patience.

**Comment by sandeep-tds** [comment]
Hi @schmidinger, 

I got to test the behaviour on an iPhone 8 plus and an iPhone XR. In both cases, the action is performed successfully. 

Can you please provide the following details: 
1. What's the issue you face when you tap on Reject?
2. What's the input you enter in the reason for rejection?

Thank you so much for your patience. 

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
@schmidinger Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
