### ISSUE TITLE
Secure your application with XSUAA (MovieLens App)

### ISSUE THREAD

**Issue by jameslim87** [SAPDocuments/Tutorials#4912]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aa-movielens-14.html

I found this tutorial has many issues,

Here is the working steps and working github
https://github.com/jameslim87/movielens.git

step 1. ok
step 2. create a new user

step3 and step4 should be skipped

step 5. ok
step 6. json contents should be same as step 3. role template name should be "MovieLensUser"
step 7. path should be xs-security.json instead of ./xs-security.json
step 8. ok
step 9. ok 
step 10. ok 
step 11. ok
step 12. ok

need to add additional steps.

step 12-1. Create Util.js file in the html/resources/webapp folder
step 12-2. update index.html file in the html/resources/webapp folder
           add a line for including Util.js script file.

		<link rel="stylesheet" type="text/css" href="css/style.css">
		<script src="Util.js" > </script>

step 12-3. Create csrf.xsjs file  in the js/lib/xsjs folder
           it is an empty file for feting the csrf token.   

step 13-0. run step 11 again because we updated js modelue.
step 13. ok 

step 13-1. create role collectionin using xsa cockpit
           MOVIERENS_USER            

step 13-2. Assign role using xsa cockpit
           In the application identifier, you can find a name similar as below
           movielensXXXXXX-XXXX-XXXX-XXXX-XXXXX!in              
            
           select it and you will see the role template as 'MovieRensUser'  

step 13-3. Assign the role collection to user that we created in step 2 using xsa cockpit

step 14. ok
step 15. ok

* Util.js file
---------------
/*eslint no-console: 0, no-unused-vars: 0, no-use-before-define: 0, no-redeclare: 0*/
$.ajaxSetup({
	    beforeSend: function(xhr,settings) {
	      if (settings && settings.hasOwnProperty("type")
	          && settings.type !== "GET"){
	    	  var token = getCSRFToken();
	        xhr.setRequestHeader("X-CSRF-Token", token);
	      }
	    },
	    complete: function(xhr,textStatus) {
	        var loginPage = xhr.getResponseHeader("x-sap-login-page");
	        if (loginPage) {
	            location.href = loginPage + "?x-sap-origin-location=" + encodeURIComponent(window.location.pathname);
	        }
	    }
	});

	function getCSRFToken() {
	    var token = null;
	    $.ajax({
	        url: "/xsjs/csrf.xsjs",
	        type: "GET",
	        async: false,
	        beforeSend: function(xhr) {
	            xhr.setRequestHeader("X-CSRF-Token", "Fetch");
	        },
	        complete: function(xhr) {
	            token = xhr.getResponseHeader("X-CSRF-Token");
	        }
	    });
	    return token;
	}

**Comment by jarjarbentley** [comment]
i will review these issues and make needed changes.  thank you.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by jameslim87** [comment]
The steps are not changed... I am a SAP employee and the steps should be updated then should be closed after it is fixed.
