### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by jameslim87** [SAPDocuments/Tutorials#4915]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

The step4 has an issue.

I can access ES5 and it works in my browser to get the odata service.
https://sapes5.sapdevcenter.com/sap/opu/odata/iwbep/GWSAMPLE_BASIC/

The first issue is  when i typed 'gws', it doesn't show the list.
The second issue is it didn't work even though i typed  /sap/opu/odata/iwbep/GWSAMPLE_BASIC

is this a known issue?

here is the error message

"Consume SAP Services failed. Reason: Error: Failed to get metadata. Reason: Could not retrieve the service metadata. Make sure the destination and service path are correct and that the service is available."

**Comment by jameslim87** [comment]
Hi Michael 

I found the reason. 

There is no 'Destination' Service in the service marketplace of the Frankfurt Region AWS.
so that's why it can't get the metadata because 'Destination' service is not active.

Please check it and add the missing services.
It has many missing services compare to US EAST(VA).

The reason why I had to select Frankfurt because it is the only region that has Business Studio.

Thanks!
James Lim

**Comment by MichaelCzcz** [comment]
@raz-korn Can you please continue with this issue?

**Comment by raz-korn** [comment]
Hi @jameslim87 ,
with the new version of AppStudio you need to have the ES5 destination correctly configured. 
Please note that the new version of the tutorial merged the steps of creating the project and consuming the data service into a single step leveraging the wizard.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
