### ISSUE TITLE
Upload Data to Data Attribute Recommendation

### ISSUE THREAD

**Issue by jameslim87** [SAPDocuments/Tutorials#4918]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dar-upload-data.html

Please specify the step you are referring to

In the step1, it returned error because the hostname has something wrong.

"url": "https://aiservices-trial-dar.cfapps.eu10.hana.ondemand.com",
	"uaa": {

I got below error because the hostname doesn't exist.

404 Not Found: Requested route ('aiservices-trial-dar.cfapps.eu10.hana.ondemand.com') does not exist.

I tried aiservices-trial-dar-demo.cfapps.eu10.hana.ondemand.com but it didn't work.

**Comment by Juliana-Morais** [comment]
Hi, have you followed the steps in https://developers.sap.com/tutorials/cp-aibus-dar-setup-postman.html? Please double-check the steps in this prerequisite tutorial and then you should not get errors in https://developers.sap.com/tutorials/cp-aibus-dar-upload-data.html Step 1: Get an access token.

Be aware that the following values should come from your service key ONLY (as explained in https://developers.sap.com/tutorials/cp-aibus-dar-setup-postman.html Step 1: Add service key credentials to Postman environment):
-authentication_endpoint
-clientid
-clientsecret
-hostname
Do not create values such as hostnames, this will not work Use the values from your service key!

**Comment by jameslim87** [comment]
Hi Juliana
Now I found the reason after read it line by line.
The order of field in the environment template JSON file is
         Authentication_endpoint
         Client ID
         Client Secret
         Hostname

but our key order is.
         Hostname
         Client ID
         Client Secret
         Authentication_endpoint

It might be easy if we change the order of the JSON template file so that the other person can avoid this simple issue.

Thank you.
Regards,
James Lim
