### ISSUE TITLE
Create an SAP Cloud Platform ABAP Environment Trial User

### ISSUE THREAD

**Issue by ahmedkhan29789** [SAPDocuments/Tutorials#4919]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html

Can you please let me what annotation i would use to create my cds table as ROW table in ABAP ON CLOUD.

**Comment by mervey45** [comment]
Hi @ahmedkhan29789 ,

please do also following tutorials https://developers.sap.com/tutorials/abap-environment-data-model.html to understand how UI annotations are created and how it looks like on the UI. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
