### ISSUE TITLE
Create Table Persistence and Generate Data

### ISSUE THREAD

**Issue by ahmedkhan29789** [SAPDocuments/Tutorials#4920]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-persistence.html

Can you please let me what annotation i would use to create my cds table as ROW table in ABAP ON CLOUD.

**Comment by mervey45** [comment]
Hi @ahmedkhan29789 ,

please move on with the next tutorial: https://developers.sap.com/tutorials/abap-environment-data-model.html.

Annotations are part of step2.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by ahmedkhan29789** [comment]
I checked all SAP CDS DML annotations but was unable to found, What
annotation i would to create my CDS table aa ROW table in ABAP ON CLOUD.
