### ISSUE TITLE
Upload and query documents in SAP HANA Express Edition

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#4921]
Tutorial URL: https://developers.sap.com/tutorials/hxe-docstore-02-query-jsondocs.html

Please specify the step you are referring to prerequisites

There are details missing for the step of altering the database which i understand to be SYSTEMDB and not HXE to execute the following command via hdbsql: "ALTER DATABASE SYSTEMDB ADD 'docstore';" 
otherwise the following error is triggered and the docstore remains unavailable for executing any queries: 
"* 7: feature not supported: ALTER database command on SYSTEMDB only SQLSTATE: HY000"
what's more important, the first step in the tutorial cannot be executed.

**Comment by jung-thomas** [comment]
I'm not sure I'm following your feedback.  The tutorial does tell you specifically to log into the SYSTEMDB:
hdbsql -u SYSTEM -d **SYSTEMDB** -i 90

And then it tells you to add the docstore to the HXE tenant:
ALTER DATABASE **HXE** ADD 'docstore';

These are the correct steps.  
https://developers.sap.com/tutorials/hxe-docstore-01-create-database.html

**Comment by greg2git** [comment]
Missed the first tutorial in the series and now it worked like a charm except for this command: 
   \c -u SYSTEM -d HXE -i 90
i ended up running this instead:
   hdbsql -u SYSTEM -d HXE -i 90

thx for the tip.
