### ISSUE TITLE
Setup your SAP HANA MDC instance

### ISSUE THREAD

**Issue by yadnesh98** [SAPDocuments/Tutorials#4922]
Tutorial URL: https://developers.sap.com/tutorials/cp-hana-create-mdc-instance.html

This tutorial doesn't seem to be up to date. The options in the left pane are completely different in latest version I think and I cannot find the way to create a database/schema at all.

**Comment by jung-thomas** [comment]
This is a Neo based tutorial.  Are you trying it in a trial account?  Are you in the Neo cockpit or the Cloud Foundry one?  Most likely unless you explicitly need the older Neo productive approach (which this tutorial covers); you would instead be better off using HANA As A Service on Cloud Foundry: https://developers.sap.com/group.hana-service-setup.html

**Comment by jung-thomas** [comment]
@yadnesh98  - any feedback on the response to your question?  Did it address your question about what you are seeing?  If so I'd like to close this issue.

**Comment by jung-thomas** [comment]
I've not heard back so I'm closing this issue. Feel free to reopen if you are still having issues and have additional questions.
