### ISSUE TITLE
Get Started with SAP Cloud Platform, SAP HANA Service

### ISSUE THREAD

**Issue by wyunze** [SAPDocuments/Tutorials#4924]
Mission URL: https://developers.sap.com/mission.haas-get-started.html,this service is not available in CF trial account for now,is it decorated?

**Comment by jung-thomas** [comment]
Is it decorated? I'm not sure what you mean by that.

**Comment by wyunze** [comment]
Thanks for your quick reply .Sorry for my mistake,I mean ‘Deprecated‘ or ‘obsolete’.

Sent from my iPhone XS

On Apr 12, 2020, at 21:22, Thomas Jung <notifications@github.com> wrote:

﻿

Is it decorated? I'm not sure what you mean by that.

**Comment by jung-thomas** [comment]
Essentially it is obsolete.  It has recently been replaced by the new HANA Cloud: https://saphanacloudservices.com/hana-cloud/  The current CF HANA As A Service isn't technically deprecated nor will it be removed right away; but clearly the long term solution is the new managed service.  There is a trial planned for it in the near future. You can sign up on the above website to be notified when the trial is available.
