### ISSUE TITLE
Build a Node.js app querying SAP HANA Express Edition

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#4925]
Tutorial URL: https://developers.sap.com/tutorials/hxe-docstore-03-nodejs-app.html

Please specify the step you are referring to 1
since HANA Express is running on SLES the nodejs installation steps should be specific to SLES and not general to all linux distros, imho.

**Comment by jung-thomas** [comment]
I'm sorry but I'm not following your feedback here.  There is nothing to do with Linux in this tutorial.  It is performed on the developer's client machine (generally Windows or Mac). I don't understand what part of this tutorial should be specific to SLES or why.

**Comment by greg2git** [comment]
sorry about that, but is JSON docstore in HANA Express only supposed to work on Windows or Mac? my last 2 attempts to install npm on SLES that has HANA Express installed have failed, so if the docstore is not robust enough to handle SQL with complex nested JSON structures then i will probably give it a pass and try to make it work with traditional table joins. my apologies again if this is beyond the scope of this particular tutorial and thank you again for picking up my issue.

**Comment by jung-thomas** [comment]
>sorry about that, but is JSON docstore in HANA Express only supposed to work on Windows or Mac?
No, but this tutorial has nothing really do with where HANA Express is installed. The steps in this tutorial are all designed to be done on the developer's desktop regardless of where HANA Express is installed. As the first line of the tutorial says: "**On your client laptop**, create a directory which will serve as the root folder for the Node.js food app".  You are developing on your local machine in this example and that's where Node.js and NPM should be installed.

**Comment by greg2git** [comment]
it makes more sense now, so if i don't want to depend on local hardware (and installed software) for HANA Express JSON docstore development then there is little point for me to continue this particular tutorial series. 

thx for clarifying that.
