### ISSUE TITLE
Set Up a Workflow With Extended Employee Onboarding

### ISSUE THREAD

**Issue by fc158** [SAPDocuments/Tutorials#4933]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html

Please specify the step you are referring to: Step 3

When deploying to SAP Cloud Platform, operation fails with this error:

`Service operation failed: Controller operation failed: 502 Updating service "sample_onboarding_html5_repo_host" failed: Bad Gateway: Error creating service "sample_onboarding_html5_repo_host" from offering "html5-apps-repo" and plan "app-host": CF-ServiceBrokerBadResponse(10001): Service broker error: Service broker html5-apps-repo-sb failed with: Failed to report quota consumption`

Any help is very much appreciated

**Comment by ArchanaShukla** [comment]
Is this still coming? You need to increase the quota of your HTML app or shut down some existing application to free up the space.

**Comment by ArchanaShukla** [comment]
I assume the issue is solved. If not please reopen it.
@MichaelCzcz  - please close the issue!

**Comment by fc158** [comment]
yes, solved; thank you
