### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by atanasyordanov21** [SAPDocuments/Tutorials#4936]
Hello!

Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

In step 3, point 2, after executing the third command:
cf push -f gen/srv --random-route

I get the following output:
...
Waiting for app to start...
Unexpected Response
Response code: 503
CC code:       0
CC error code:
Request ID:    a5a4458d-5ac7-4f9a-4aad-6ad1156fb457::055c8970-7c53-445c-87f8-7b4942e90f49
Description:   {
  "description": "Instances information unavailable: Connection refused - Connection refused - connect(2) for \"bbs.service.cf.internal\" port 8889 (bbs.service.cf.internal:8889)",
  "error_code": "CF-InstancesUnavailable",
  "code": 220002
}

FAILED
---

What might be the reason?
Thank you!

**Comment by iwonahahn** [comment]
Hi,

Can you please try it again? We have updated step 1 in the tutorial. Could you also please share which version (Feature Set) you have in SAP Cloud Platform Cockpit (you can find this when you are in the subaccounts overview under _About_? 

Thank you and best regards,
Iwona
Thank you and best regards,
Iwona

**Comment by atanasyordanov21** [comment]
Hi Iwona,

meanwhile I took a better look at the output after the command:
cds build

There was the following line:
[WARNING] odata.version = 'v2' not supported by node runtime, define odata.version = 'v4' in package.json instead

Then I added the following in the "cds" section of package.json:
		"odata": {
			"version": "v4"
		}

Once again "cds build" and the above warning was not present anymore.
There are no problems when deploying the db (cf push -f gen/db).
Once again deploying the srv was not successful (cf push -f gen/srv --random-route). This time the output was different:

Waiting for app to start...
Start unsuccessful

TIP: use 'cf logs my-bookshop-srv --recent' for more information
FAILED

Then I followed the tip and executed the following:
cf logs my-bookshop-srv --recent

This is part of the output:

[CELL/0] OUT Downloading droplet...
[CELL/0] OUT Downloaded droplet (57.2M)
[CELL/0] OUT Starting health monitoring of container
[APP/PROC/WEB/0] OUT > my-bookshop@1.0.0 start /home/vcap/app
[APP/PROC/WEB/0] OUT > npx cds run
[APP/PROC/WEB/0] ERR npx: installed 4 in 20.705s
[APP/PROC/WEB/0] ERR command not found: cds
[APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
[APP/PROC/WEB/0] ERR npm ERR! errno 1
[APP/PROC/WEB/0] ERR npm ERR! my-bookshop@1.0.0 start: `npx cds run`
[APP/PROC/WEB/0] ERR npm ERR! Exit status 1
[APP/PROC/WEB/0] ERR npm ERR! 
[APP/PROC/WEB/0] ERR npm ERR! Failed at the my-bookshop@1.0.0 start script.
[APP/PROC/WEB/0] ERR npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[APP/PROC/WEB/0] ERR npm ERR! A complete log of this run can be found in:
[APP/PROC/WEB/0] ERR npm ERR!     /home/vcap/app/.npm/_logs/2020-04-16T09_43_17_000Z-debug.log
[APP/PROC/WEB/0] OUT Exit status 1

To your question - I have "Feature Set B".

Thank you and best regards,
Atanas

**Comment by atanasyordanov21** [comment]
I think I found the problem. In Step 1, Point 2, the command "npm add hana" added the following at the end of the file package.json:
	"dependencies": {
		"@sap/hana-client": "^2.4.191"
	}

I took the line with hana-client and added it to the section "dependencies" at the beginning of the file before "scripts". With other words - after "npm add hana" there were two times "dependencies" in package.json. After fixing this the deployment was successful.

**Comment by iwonahahn** [comment]
Great that it works now. Can we close the issue?

Best regards,
Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by chgeo** [comment]
> I think I found the problem. In Step 1, Point 2, the command "npm add hana" added the following at the end of the file package.json

The command is `cds add hana`, not `npm add hana`.  This caused confusion in https://github.com/SAPDocuments/Tutorials/issues/4962#issuecomment-619362970
