### ISSUE TITLE
Store Sensor Data in Cloud Storage in SAP Data Hub, Trial Edition

### ISSUE THREAD

**Issue by nilpeksen** [SAPDocuments/Tutorials#4940]
Tutorial URL: https://developers.sap.com/tutorials/datahub-trial-v2-pipelines-part02.html

Copy any row from the output and paste it in the frame below and click on Submit Answer - 
Step 4 Execute the data pipeline step is not working. 
After executing the pipeline, my terminal's row values are correct over GCS. 
However, the submitted answer is incorrect.

Here is any requested row from the output->
[2020-04-15 20:17:23.251] sensordata/file_177.txt

GCS output ->
0,6,25.518828381483885,59.19748467946496,569.1695216316563,0.9524518306088944,23.83941607361044,59.481948627085714,1,607.0686982802245,492.2521727728777

**Comment by nilpeksen** [comment]
I am still looking for an answer, thank you.

**Comment by thecodester** [comment]
@dimvor Can you help here?

@nilpeksen note the tutorial URL is changed to https://developers.sap.com/tutorials/dataintelligence-trial-v2-pipelines-part02.html but there is a redirect

**Comment by roy-zhong** [comment]
@nilpeksen
Please put the content from the beginning of the line. Means you need to include the date time and the rest

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
