### ISSUE TITLE
Map Message Structure

### ISSUE THREAD

**Issue by lchanb** [SAPDocuments/Tutorials#4943]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-convert-message-structure.html

Please specify the step you are referring to

the path was not found https://sap-my.sharepoint.com/:u:/p/meghna_shishodiya/EaqbQ9t0jGFMvSzYPnowpVABk4l6mnN50prkKIAez1UMYA?e=lsrj63

**Comment by gauthamkrishna-sap** [comment]
The links are updated now.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
