### ISSUE TITLE
Consume an OData Service with Create Option

### ISSUE THREAD

**Issue by voxron** [SAPDocuments/Tutorials#4944]
Tutorial URL: https://developers.sap.com/tutorials/xsa-sapui5-consume.html

Please specify the step you are referring to

Hello Thomas,

Could you please to write correct syntax here. Thanks!
![problem](https://user-images.githubusercontent.com/58906219/79483858-80b46600-801b-11ea-9197-ea6830bd739a.png)

**Comment by jung-thomas** [comment]
Actually this syntax is correct; just "new-ish".  I'm assuming your default eslint settings aren't set to consider es6 syntax.  If you don't want to change your global eslint settings, you can add a line to the top of your code in particular files to add the newer es6 syntax rules:

```JavaScript
/*eslint-env es6 */
```

https://www.sitepoint.com/es6-arrow-functions-new-fat-concise-syntax-javascript/

**Comment by jung-thomas** [comment]
But I will also change this one code snippet to not use the newer (and in my opinion cleaner syntax ;) ). That way those with older eslint settings in their Web IDE, won't be confused by the false error message.
