### ISSUE TITLE
Consume an OData Service with Create Option

### ISSUE THREAD

**Issue by voxron** [SAPDocuments/Tutorials#4945]
Tutorial URL: https://developers.sap.com/tutorials/xsa-sapui5-consume.html

Hello Thomas,

Excuse me, but still have another error. Please see screenshot and my js file.

![2020-04-16 22_26_35-Window](https://user-images.githubusercontent.com/58906219/79498101-7309db00-8031-11ea-864f-86b96f3455a9.png)
[hex.localdomain.com-1587065185254.log](https://github.com/SAPDocuments/Tutorials/files/4489357/hex.localdomain.com-1587065185254.log)
[App.controller.js.txt](https://github.com/SAPDocuments/Tutorials/files/4489359/App.controller.js.txt)

**Comment by jung-thomas** [comment]
Add 	<script type="text/javascript" src="/common/error.js" ></script> to you index.html right after the script call to startup.js.  That should solve the issue.  Its another one of the prerequisites from higher up in the chain of tutorials.  I will add a specific step to this tutorial for it as well.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by voxron** [comment]
Hello,

Yes, everything ok. Thanks Thomas!

**Comment by voxron** [comment]
Thomas, one question: what kind of books or resources you can recommend for dummies of that topic? I mean how to manipulate with JS and UI5.
Do you have exercies about how to create odata v4 with using Java Module, I think this is more complicated rather than odata v2 as NodeJS module.

**Comment by jung-thomas** [comment]
I'd recommend look at openSAP as they have some very good and deep UI5 courses.  I've take a few of their UI5 ones myself.  

As far OData v4 specifically with Java, then I'd suggest you have a look at the newest information on Cloud Application Programming Model.

**Comment by voxron** [comment]
Thanks!
