### ISSUE TITLE
Integrate an SAPUI5 App into Your Portal Site (Cloud Foundry)

### ISSUE THREAD

**Issue by AshithaDechamma** [SAPDocuments/Tutorials#4950]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-sapui5-app.html
Step 4: Add your app to the site
Could you please also include steps to configure dynamic tile with count?.

Thanks,
Ashitha

**Comment by AshithaDechamma** [comment]
Any update on this as I have a requirement to display tile count in Portal?

Regards,
Ashitha

**Comment by IrisSasson** [comment]
Hi Ashitha

Dynamic tiles are not yet supporting on CF. Our roadmap is to support dynamic tiles form S/4HANA soon, and for developed apps in Q3. 

You can follow the documentation to see when these are available

Thanks

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
