### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by vishalkundal01** [SAPDocuments/Tutorials#4951]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html

Please specify the step you are referring to

Hi Archana,

Thank you for the detailed tutorial, I have encountered an issue tutorial 5 of 5 at step 4. The execution log says - 

"Determine Equipment" failed
17 Apr 2020, 18:02:16
Service endpoint:
BUSINESS_RULES
Error message:
The OAuth token request to URL 'https://p2000499014trial.authentication.eu10.hana.ondemand.com?grant_type=client_credentials' failed with HTTP status code 403 (Forbidden) and response body '{"error":"Could not verify the provided CSRF token because your session was not found."}'

I have tried in incognito, I have even checked the destination once again and it returns the code 302, not sure if this is causing the problem.

Could you please help me with this?

Vishal

**Comment by ArchanaShukla** [comment]
This issue comes because the token url for business rules destination is not correct. check if you have **/oauth/token** in the end of the token url.

**Comment by vishalkundal01** [comment]
![image](https://user-images.githubusercontent.com/41996346/80483431-b4748180-8973-11ea-9daf-814d0445a13d.png)
No I have not included yet, do you want me to include?

**Comment by vishalkundal01** [comment]
I tried including as well and it didn't work.. it's still giving me 302.

**Comment by dirugadr** [comment]
Hello, I'm also stuck in the same step (Well, I continued with the next steps, and I got an error when I start a workflow instance related to OAuth). Did you find a way to solve it?

**Comment by ArchanaShukla** [comment]
Please check your token service URL. It's still not correct. In the end its should have **/oauth/token** for example: Token Service URL should be: **https://p787658trial.authentication.eu10.ondemand.com/oauth/token** (also check the setup chapter, its clearly mentioned there)

**Comment by vishalkundal01** [comment]
Thank you, Archana! The issue has been resolved.
