### ISSUE TITLE
Set up SAP HANA, express edition on Amazon Web Services (XS Advanced)

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#4953]
Tutorial URL: https://developers.sap.com/tutorials/hxe-xsa-aws-setup.html

Please specify the step you are referring to 1.

Amazon just notified me that a newer edition - 45 - rather than - 36 - is available on their Marketplace website. 

Please update the screenshots to that effect.

Thank you, greg

**Comment by jarjarbentley** [comment]
thank you, we will update this screenshot

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
