### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by specialword** [SAPDocuments/Tutorials#4955]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-behavior.html

Please specify the step you are referring to step 1 substep 4.

step 3 substep 5 the implementation class will have syntax error because step1 substep 4 the behavior definition is missing one line:
action ( features:instance ) acceptTravel result [1] $self;

Please review to see if this line should be added to step 1 substep4. then going to step3 substep5 it will be working in local class syntax check.

George

**Comment by specialword** [comment]
I see this line is in "Enhance Behavior With Action and Validation" step1, substep1.
chronically this line should be in behavior model, step1, substep4 otherwise it will get syntax error below in step3 substep5.

**Comment by mervey45** [comment]
Hi @specialword ,

please do no activate the whole step 3 and move on with the next tutorial:https://developers.sap.com/tutorials/abap-environment-behavior-action.html 

In tutorial: activate your implementation class first in step 3 of the following tutorial: https://developers.sap.com/tutorials/abap-environment-behavior-action.html.

We will fix this issue as soon as possible.

Thank you for your understanding.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
