### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by MKatsu** [SAPDocuments/Tutorials#4957]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-behavior.html

Step 3-5.

I cannot activate the objects due to this error that says "The property "features:instance" is not defined for "ZI_TRAVEL_M_xxx".

Not sure what I am missing. Please help.

**Comment by mervey45** [comment]
Hi @MKatsu ,

please do no activate the whole step 3 and move on with the next tutorial:https://developers.sap.com/tutorials/abap-environment-behavior-action.html 

In tutorial: activate your implementation class first in step 3 of the following tutorial: https://developers.sap.com/tutorials/abap-environment-behavior-action.html.

We will fix this issue as soon as possible.

Thank you for your understanding.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
