### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by atanasyordanov21** [SAPDocuments/Tutorials#4958]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Thank you for the great tutorial!
One question - how to re-design the integration flow, so that the result which comes to the client (for example Postman) is in JSON format?

Thanks,
Atanas

**Comment by Vikramkulkarni01** [comment]
Hi @atanasyordanov21 , 

Thanks for reaching out to us. 

I  have read the details you shared and understand that you have how to question on re-designing an integration flow in JSON format. 

You can raise any issues while using our tutorial on this channel and I will be happy to address those. 

With reference to your concern, could you please check the below-shared link and check in the guides and I hope you will get some answer to it. https://help.sap.com/viewer/product/CLOUD_INTEGRATION/Cloud/en-US?task=discover_task 

I hope it serves the purpose of your concern. 

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
