### ISSUE TITLE
Add a User Task to Your Workflow

### ISSUE THREAD

**Issue by bask-alur-gh** [SAPDocuments/Tutorials#4959]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-3-add-usertask-cf.html

Step7, bullet 1:  accessing the URL gives an error "Internal Server Error" with no further details.  How do troubleshoot & resolve this?  Thanks!

**Comment by AstridHerbst** [comment]
Hi,
When does the message appear? Before the launchpad loads or when the My Inbox tile is loading?
Best regards,
Astrid

**Comment by MichaelCzcz** [comment]
@bask-alur-gh Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
