### ISSUE TITLE
Prepare to Create Workflows in SAP Cloud Platform

### ISSUE THREAD

**Issue by bask-alur-gh** [SAPDocuments/Tutorials#4960]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-1-getting-started-cf.html

Step3, bullet 2: My actual screen looks different from the screenshot.  'Name' shows 'Default Identity Provider' also, and 'Origin Key' is 'sap.default', not 'ldap'.  But if the change icon is clicked, it shows the 'Name' as 'SAP ID Service'.  Wondering if this is leading to issues in the subsequent tutorials when deploying the apps!

**Comment by AstridHerbst** [comment]
Hi,
We are currently working on replacing this tutorial. There will be a new tutorial for the Cloud Foundry Environment that will be adapted to use the SAP Business Application Studio.
Best regards,
Astrid

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
