### ISSUE TITLE
Issue while executing the step Enhance project configuration for SAP HANA from Tutorial 2

### ISSUE THREAD

**Issue by BaskarThambiayah** [SAPDocuments/Tutorials#4962]
Hi Colleagues,

Turorial 2: Deploy a CAP Business Application to SAP Cloud Platform
Step 1: Enhance project configuration for SAP HANA
1. Add the following configuration in the package.json file of your my-bookshop project (overwrite any existing cds configuration):
"cds": {
    "requires": {
      "db": {
        "kind": "hana"
      }
    }
  }

**Findings:**
After added the above code in **package.json** file and while saving this file, we are getting the below error message in cds watch.

**[ERROR] Cannot find module '@sap/hana-client'**
![image](https://user-images.githubusercontent.com/60343237/79689698-23672180-8274-11ea-8006-2e1a53344358.png)

**Note:** 
This issue got resolved after the execution of the command **"npm install @sap/hana-client"**

I have reported this as an issue since we were not able to execute scenario successfully by following the tutorial.
Please check and do the needful.

Many thanks & regards,
Baskar

**Comment by iwonahahn** [comment]
Hi Baskar,

Could you please check [issue](https://github.com/SAPDocuments/Tutorials/issues/4936) if that helps?

Thank you and best regards,
Iwona

**Comment by BaskarThambiayah** [comment]
Hi Iwona,

As you suggested i tried the steps provided in the issue https://github.com/SAPDocuments/Tutorials/issues/4936 .
But no luck.
Please find my observations below.

Before i run Step 2 (**npm add hana**) , the **package.json** file is as below.
{
  "name": "my-bookshop",
  "version": "1.0.0",
  "description": "A simple CAP project.",
  "repository": "<Add your repository here>",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "@sap/cds": "^3",
    "express": "^4"
  },
  "scripts": {
    "start": "npx cds run"
  },
  "devDependencies": {
    "sqlite3": "^4.1.1"
  },
  "cds": {
    "requires": {
      "db": {
        "kind": "hana"
      }
    }
  }
}

After i ran the "**npm add hana**" command, the **package.json** file is changed as below.
{
  "name": "my-bookshop",
  "version": "1.0.0",
  "description": "A simple CAP project.",
  "repository": "<Add your repository here>",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "@sap/cds": "^3",
    "express": "^4",
    "hana": "0.0.2"
  },
  "scripts": {
    "start": "npx cds run"
  },
  "devDependencies": {
    "sqlite3": "^4.1.1"
  },
  "cds": {
    "requires": {
      "db": {
        "kind": "hana"
      }
    }
  }
}


Here, i found, **"hana": "0.0.2"** has got added in "dependencies" section.
But i didn't find following dependencies added at the end of package.json file as mentioned in the reference hithub issue.
"dependencies": {
"@sap/hana-client": "^2.4.191"
}

But i was getting the error **[ERROR] Cannot find module '@sap/hana-client'** after i saved this file.
I also tried replacing **"hana": "0.0.2"** with **"@sap/hana-client": "^2.4.191"** under dependencies section in my package.json file and saved.
{
  "name": "my-bookshop",
  "version": "1.0.0",
  "description": "A simple CAP project.",
  "repository": "<Add your repository here>",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "@sap/cds": "^3",
    "express": "^4",
    "@sap/hana-client": "^2.4.191"
  },
  "scripts": {
    "start": "npx cds run"
  },
  "devDependencies": {
    "sqlite3": "^4.1.1"
  },
  "cds": {
    "requires": {
      "db": {
        "kind": "hana"
      }
    }
  }
}

But i was getting the same error.

Many thanks & regards,
Baskar

**Comment by chgeo** [comment]
Most of the confusion and issues here comes from the wrong `npm add hana` command, which does something completely different.  The command is `cds add hana`.  I have reported this in the other issue https://github.com/SAPDocuments/Tutorials/issues/4936#issuecomment-620558260

**Comment by BaskarThambiayah** [comment]
Hi,

I tried running the command "npm add @sap/hana-client --save" In Step 1, Point 2 instead of "npm add hana". 

After that the package.json looks as below.
{
  "name": "my-bookshop",
  "version": "1.0.0",
  "description": "A simple CAP project.",
  "repository": "<Add your repository here>",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "@sap/cds": "^3",
    "@sap/hana-client": "^2.4.196",
    "express": "^4"
  },
  "scripts": {
    "start": "npx cds run"
  },
  "devDependencies": {
    "sqlite3": "^4.2.0"
  },
  "cds": {
    "requires": {
      "db": {
        "kind": "hana"
      }
    }
  }
}

But still the error message "**[ERROR] Cannot find module '@sap/hana-client'**" is shown in terminal. 

Thanks & regards,
Baskar

**Comment by chgeo** [comment]
Then please make sure to build the application before pushing it.  Also check if you have a redundant `package.json` file in `srv` folder (which some apps have, though not recommended).

**Comment by chgeo** [comment]
P.S. When adding Json content to Github comments, enclose them with 3 backticks, so that Json gets nicely formatted. 
````
```json
{...}
```
````
Learn more about Github markdown [here](https://guides.github.com/features/mastering-markdown/):

**Comment by BaskarThambiayah** [comment]
Hi,

I continued with "**Step 3: Deploy using cf push**". All the steps were successfully completed without any error.

Now only think is, i was getting the error message "[ERROR] Cannot find module '@sap/hana-client'" in cds watch when i executed the step 1 as i mentioned in my earlier reply.

Also observed that the package.json file is available in three places.
1. Directly under my-bookshop folder
2. my-bookshop\gen\db
3. my-bookshop\gen\srv

Thanks & regards,
Baskar

**Comment by chgeo** [comment]
> Now only think is, i was getting the error message "[ERROR] Cannot find module '@sap/hana-client'" in cds watch when i executed the step 1 as i mentioned in my earlier reply.

Yes, that's explainable.   Because of the `kind:hana` configuration, local runs with `cds watch` will try to connect to HANA through the `@sap/hana-client` driver. 
Starting with `@sap/cds` 3.34.1 , which has been published today, you can have a [smarter configuration](https://cap.cloud.sap/docs/advanced/deploy-to-cloud#enhance-project-configuration-for-sap-hana) that switches between `hana` and `sqlite`: Just replace `kind:hana` with `kind:sql`.  This will lead local runs to use sqlite again.  On Cloud Foundry, HANA is activated autmatically.  

> Also observed that the package.json file is available in three places.

Occurences in `gen/` are fine since these are generated during build.  It's only duplicates in _source_ folders that one should avoid.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
