### ISSUE TITLE
sapui5-fiori-cf: runtime ui adaptation of created app does not work out of the box

### ISSUE THREAD

**Issue by gabriel-k** [SAPDocuments/Tutorials#4963]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-fiori-cf-display-data.html

Great tutorial 👍

I originally thought that the app would allow for runtime adaptation (that's how I understood the "enabled SAPUI5flexibility features" in "Leverage local development tools to build an SAP Fiori app with enabled SAPUI5 flexibility features" but unfortunately it doesn't, at least not as it is.

The "Adapt UI" item does show up in the user menu but there is no way whatsoever to interact with the elements. It took me a while to figure out why, as there is no feedback from the adaptation tools themselves as to why one is not able to manipulate anything on the page. 

It turns out the problem is that the views generated by `easy-ui5` in the targets section of the app manifest do not have a viewId assigned to them. I guess you might want to indicate that to potential readers. And I suppose the yeoman generator should be patched to generate view ids alongside view names so that things just work, out of the box.

**Comment by IObert** [comment]
Hi @gabriel-k,

very good catch! I'll add a default view ID to the code that is being generated by easy-ui5 and also instructions on how to add IDs to the newly generated views to the tutorial.

There are actually a couple of other things I wanted to add to this tutorial as well. All these changes will come in early next week.

Thanks,
Marius

**Comment by gabriel-k** [comment]
Great! Thank you Marius!
Gabriel
(gabriel.kevorkian@sap.com)
