### ISSUE TITLE
Maintain Platform Subaccounts and SAP Web IDE Permissions

### ISSUE THREAD

**Issue by bask-alur-gh** [SAPDocuments/Tutorials#4964]
Tutorial URL: https://developers.sap.com/tutorials/abap-custom-ui-subaccount-permission.html

Step2 doesn't have Neo has an option at all :-(   Only option is AWS.  Unable to proceed with this tutorial due to this.  Kindly help!

**Comment by Liebherr** [comment]
Hi Michael,
it seems the UI has slightly changed. There is a "Neo Environment" check box now which you have to tick to be able to create a Neo Subaccount.
I will update the tutorial as soon as possible.
Thanks and Regards
Ulrike

**Comment by Liebherr** [comment]
Oh sorry, I adressed bask-alur-gh

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
