### ISSUE TITLE
Create a Remote Client Proxy

### ISSUE THREAD

**Issue by aliaksei-dunets-public** [SAPDocuments/Tutorials#4968]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-a4c-create-proxy.html

Please specify the step you are referring to **Step 11: Test yourself**
I can't determine issue for my answer of the step 11 - _Create a CONSTANT structure named **agency_unkown** for an exception class, specifying the message class **/DMO/CM_FLIGHTS**, message number **010**, and four attributes. The first attribute should have the value **MV_AGENCY_ID**. Enter your code in the space below and choose Submit Answer._

CONSTANTS:
      BEGIN OF agency_unkown,
        msgid TYPE symsgid VALUE '/DMO/CM_FLIGHTS',
        msgno TYPE symsgno VALUE '010',
        attr1 TYPE scx_attrname VALUE 'MV_AGENCY_ID',
        attr2 TYPE scx_attrname VALUE 'attr2',
        attr3 TYPE scx_attrname VALUE 'attr3',
        attr4 TYPE scx_attrname VALUE 'attr4',
      END OF agency_unkown.

I have no idea what is wrong.

**Comment by julieplummer20** [comment]
Hi Aliaksei,
You are right. There is an error in the sample code. I will fix it at once.
Sorry for the inconvenience. 
Best wishes,
Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by gregorwolf** [comment]
Hi @julieplummer20 ,

I've created the following but also get the error "Sorry, that’s incorrect. Please try again.":

```ABAP
    CONSTANTS:
      BEGIN OF agency_unkown,
        msgid TYPE symsgid VALUE '/DMO/CM_FLIGHTS',
        msgno TYPE symsgno VALUE '010',
        attr1 TYPE scx_attrname VALUE 'MV_AGENCY_ID',
        attr2 TYPE scx_attrname VALUE 'attr2',
        attr3 TYPE scx_attrname VALUE 'attr3',
        attr4 TYPE scx_attrname VALUE 'attr4',
      END OF agency_unkown.
```

Seems it's broken again.

Best regards
Gregor

**Comment by julieplummer20** [comment]
Hi Gregor,
Yes, I've spotted a second typo in the sample code. I apologize.
I will repair this at once.

BR Julie.
