### ISSUE TITLE
Implement a CDS Custom Entity and Query Implementation Class

### ISSUE THREAD

**Issue by aliaksei-dunets-public** [SAPDocuments/Tutorials#4969]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-a4c-create-custom-entity.html

Please specify the step you are referring to **Step 6: Check the code for your query implementation class**

Why does this code need - line 21 - 28:

TRY.
          """Create Read Request
          CATCH /iwbep/cx_gateway INTO DATA(lx_gateway).
            RAISE EXCEPTION TYPE ZCX_TRAVELS_CONS_XXX
              EXPORTING
                textid   = ZCX_TRAVELS_CONS_XXX=>query_fail
                previous = lx_gateway.
    ENDTRY.

**Comment by julieplummer20** [comment]
Hi Aliaksei,
Basically, you're reading the data from a remote OData service. So you need to surround the read request with a TRY...CATCH block. SAP Gateway is just the framework for handling OData services. This tutorial is based on this documentation: [Implementing Data and Count Retrieval](https://help.sap.com/viewer/923180ddb98240829d935862025004d6/Cloud/en-US/33497472ad294918b8a0184d9d8369bd.html). Is that what you meant? There is really not much more info I can give within the scope of this tutorial.
I will add the link to the docu to the tutorial.
Best wishes,
Julie.

**Comment by aliaksei-dunets-public** [comment]
I guess the line 19 - **DATA(lo_read_request) = lo_client_proxy->create_resource_for_entity_set( 'TRAVEL' )->create_request_for_read( ).** has to be into block try-catch.
![2020-04-21_15h58_54](https://user-images.githubusercontent.com/22812746/79874374-ee340e00-83f0-11ea-8743-e93d1a2bee75.png)

**Comment by julieplummer20** [comment]
Ah, now I see what you mean. Yes, I will correct this.
Thanks a lot for pointing this out.
Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
