### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by sachinbhutani** [SAPDocuments/Tutorials#4971]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Please specify the step you are referring to
>Step 7 
>In the db folder, choose New File and enter csv/my.bookshop-Authors.csv

on windows system file name my.bookshop-Authors.csv is not allowed

**Comment by iwonahahn** [comment]
Hi, 

You should perform the steps in Visual Studio Code and not on your system. Please try it again as described in the tutorial.

Thank you and best regards,
Iwona
