### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by C5231723** [SAPDocuments/Tutorials#4972]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-behavior.html

Hello Colleagues,

In Create Behavior Definition for Managed Scenario tutorial, Step 3 : Create implementation class, point 5 : In your local types replace your code with following. User should save and Activate the below code.

CLASS lhc_travel DEFINITION INHERITING FROM cl_abap_behavior_handler.

  PRIVATE SECTION.

    TYPES tt_travel_update TYPE TABLE FOR UPDATE zi_travel_m_xxx.

    METHODS get_features               FOR FEATURES IMPORTING keys REQUEST    requested_features FOR travel    RESULT result.

ENDCLASS.

CLASS lhc_travel IMPLEMENTATION.

  METHOD get_features.
  ENDMETHOD.

ENDCLASS.

**Actual result :** Activation of Implementation Class ZCL_BP_I_TRAVEL_M_XXX is failing. 
**Expected result :**  Activation of Implementation Class ZCL_BP_I_TRAVEL_M_XXX should be able successful.

We were not getting this activation error during last execution. After analyzing found that, in the code given for behavior implementation class zcl_bp_i_travel_m_xxx, they are defining ‘METHODS get_features’ but this is not defined in Behavior Definition ZI_TRAVEL_M_XXX. And in tutorial "Enhance Behavior With Action and Validation",  the behavior definition ZI_TRAVEL_M_XXX is enhanced in Step1: Where you can find the respective code :
// instance action and dynamic action control
action ( features : instance ) acceptTravel result [1] $self;

Solution : In Create Behavior Definition for Managed Scenario tutorial, Step 1: Create behavior definition. point 4 : Additional line of code should be included.

 // instance action and dynamic action control
  action ( features : instance ) acceptTravel result [1] $self;

Thanks & Regards,
Sony Narayan

**Comment by mervey45** [comment]
Hi @C5231723 ,

please do no activate the whole step 3 and move on with the next tutorial:https://developers.sap.com/tutorials/abap-environment-behavior-action.html 

In tutorial: activate your implementation class first in step 3 of the following tutorial: https://developers.sap.com/tutorials/abap-environment-behavior-action.html.

We will fix this issue as soon as possible.

Thank you for your understanding.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
