### ISSUE TITLE
Build a micro App for SAP Mobile Cards

### ISSUE THREAD

**Issue by Venkatpicons** [SAPDocuments/Tutorials#4974]
Tutorial 4: Create Cards with Actions to Enable Workflows (Like Approve Or Reject)
Action
-- >Click Automatic Instance Card in the Card Templates tab.
Observation :- Wrong screenshot assigned, there should be **Productive status** screenshot

Please find the below url for reference.

Tutorial Details:- [ - Get Started with SAP Mobile Cards](https://developers.sap.com/mission.mobile-cards-get-started.html)

Kind Regards
Venkat

**Comment by sandeep-tds** [comment]
Dear @Venkatpicons,

Thank you for raising your concern. 

The image under Click Automatic Instance Card in the Card Templates tab in [the tutorial you've mentioned ](https://developers.sap.com/tutorials/cp-mobile-cards-action.html) shows the status of the card as Productive. 

[Image Link](https://developers.sap.com/tutorials/cp-mobile-cards-action/_jcr_content.github-proxy.1585635046.file/img_4.png)

Can you please review the issue? 

Thank you for your support.

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
@Venkatpicons Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
