### ISSUE TITLE
SAP HANA XS Advanced - Cross-container access

### ISSUE THREAD

**Issue by ahmedkhan29789** [SAPDocuments/Tutorials#4979]
Tutorial URL: https://developers.sap.com/tutorials/xsa-cross-container-access.html

In total: Not much clarification, What should be on Source container and what should be on Target container.
Step 1.
No clarity what  needs to be done on source container and what needs to be done target container, 

Step 2.
Don't contain any sample code

**Comment by jung-thomas** [comment]
I'm sorry but I'm not really following your feedback.  Step 1 - the source container is in separate instructions linked from this one: https://github.com/SAP-samples/hana-shine-xsa/blob/master/SHINE-XSA.md
Step 2.  There is no sample code needed for this step. Its demonstrating what already exists in the source container (the standard SHINE content).

**Comment by jung-thomas** [comment]
@ahmedkhan29789  - Can you clarify if the response addressed your question or not.  I hope the link to the related installation instructions did the trick.  Please let me know as I'd like to close this issue if you are OK now.

**Comment by ahmedkhan29789** [comment]
Thanks Thomas, Kindly close it
