### ISSUE TITLE
Consume the API Proxy in SAP Web IDE

### ISSUE THREAD

**Issue by ChrisTrum** [SAPDocuments/Tutorials#4982]
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-webide-int.html

Please specify the step you are referring to: Step 8

In Step 8 it's mentioned with an exclamation mark that we should use the Web IDE and not the full stack version. However in the Demo instance we only have the Full Stack version available. 

_The application cannot be subscribed to product .... using service 'GWSAMPLE_BASIC'. Please contact your System Administrator._ 
![image](https://user-images.githubusercontent.com/61841485/79849411-b8783080-83c2-11ea-91a0-92099ae5f666.png)

I proceeded with the Full Stack version and face an issue on stage 13. 
![image](https://user-images.githubusercontent.com/61841485/79850842-c464f200-83c4-11ea-9927-904a5bc475f0.png)

I tried also to create an application directly from the API dev portal. Although I get something created, I can't see it in the Web IDE after. 

So what should I do to make it work ? 

Thanks

**Comment by shilpavij** [comment]
Hello,
There is something wrong with the destination. The communication between WEB IDE and Dev Portal is via destination. If you are sure its correct would suggest you open up a ticket on OPU-API-OD-DT

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
