### ISSUE TITLE
Deploy the Fiori App to Cloud Foundry

### ISSUE THREAD

**Issue by Immanuelbh** [SAPDocuments/Tutorials#4984]
Hi, 
Great guide and tutorial, it helped me tremendously.
Just wanted to mention a small typo:
In the tutorial: https://developers.sap.com/tutorials/sapui5-fiori-cf-deploy.html
Under the 4th step: The answer to the question "How many products are still left after applying these filter criteria?" is **17** and not 70 as mentioned in the answer.
Overall great job with the whole series!
Immanuel

**Comment by IObert** [comment]
Very good catch! I fixed it
