### ISSUE TITLE
Get a Free Trial Account on SAP Cloud Platform

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#4987]
Tutorial URL: https://developers.sap.com/tutorials/hcp-create-trial-account.html

Please specify the step you are referring to
Step # 4

When I go to the trial site (https://account.hanatrial.ondemand.com/) I currently see this badly formatted content
![grafik](https://user-images.githubusercontent.com/18588108/79955152-a9ef4f00-847e-11ea-9516-51580620d8c1.png)

Is this a general issue at the moment or could it have to do with me trying to go to the trial site again after not visiting it for a couple of months? I already tried emptying Chrome's cache but it didn't make a difference.

Cheers
Bärbel

**Comment by IObert** [comment]
Hi,
thanks for opening the issue. I just checked it on my machine and the CSS works there (I also cleared my cache). Do you see this issue as well when you use an alternative browser?

**Comment by BaerbelW** [comment]
Thanks for checking!

I tried with Internet Explorer and it looks fine there - can't check it easily in Firefox as I'm logged in via SSO and another user there. 

Chrome is on version 80.0.3987.116 (Offizieller Build) (64-Bit) which I cannot update as it's the company laptop. If I can follow the steps outlined in the tutorial via IE, I'll use that for now - but the CSS-issue is weird.

Cheers
Bärbel

**Comment by IObert** [comment]
Do you see the same issue when you use an incognito tab in Chrome?

**Comment by BaerbelW** [comment]
Yes, the CSS looks the same if I login in an icognito tab in Chrome.

Is this "good news" or "bad news"?

Cheers
Bärbel

**Comment by IObert** [comment]
Thanks for checking. I'm not sure if it is good news :D 
Using an incognito tab allows opening at a page from a clean state because it ignores the cache and other things like active user sessions etc. But the fact that you see the CSS issue there as well really makes me think it could be the Chrome version.

**Comment by BaerbelW** [comment]
As I needed to use my own laptop to finish another tutorial, I tried accessing the SCP-Trial site via Chrome from there and the CSS looks fine with Version 81.0.4044.113 (Offizieller Build) (64-Bit).

Another indication that it might be Chrome-version related?

Cheers
Bärbel

**Comment by IObert** [comment]
I forwarded the issue internally :)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
