### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by mconvertino** [SAPDocuments/Tutorials#4988]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

I am stucked at Step 8: Test run the application, while I have successfully performed the previous steps. When I click the '+' button in Run Configurations I am prompted with the message

"There are no runnable resources"

What am I missing? Thanks in advance for the help.

**Comment by raz-korn** [comment]
Is a workspace open (visual indication - the status bar at the bottom should be blue)?
Can you share a screenshot of the entire screen, with the HTML5 module folders expanded (in the project explorer pane)?

**Comment by mconvertino** [comment]
This is the project structure 
![image](https://user-images.githubusercontent.com/55501964/80131886-33943f00-859b-11ea-8fff-055e49713cf6.png)

**Comment by raz-korn** [comment]
This looks like a full-stack project that was created in SAP Web IDE full-stack.
is this correct? Are you trying to migrate a project from SAP Web IDE to SAP AppStudio?

**Comment by mconvertino** [comment]
Correct. I had to create the project template in Web IDE and then import the structure, since when I try to create the template directly in Application Studio the project creation remains stucked and never ends

**Comment by raz-korn** [comment]
Did you try to create a full-stack app in an SAP Fiori dev-space? I do not think this will work.
For full-stack, I recommend the following tutorial: https://developers.sap.com/mission.cap-java-app.html

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
