### ISSUE TITLE
Transport a Software Component Between Test and Development Systems

### ISSUE THREAD

**Issue by peterpersiel** [SAPDocuments/Tutorials#4991]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-gcts.html

Please specify the step you are referring to: Headline
Usually Transport of a Software Component is done **Between Development and Test Systems**

**Comment by mervey45** [comment]
Hi @peterpersiel ,

thank you for your feedback. We will update this as soon as possible.

Best regards,
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
