### ISSUE TITLE
Call an External Endpoint to Retrieve Additional Information

### ISSUE THREAD

**Issue by shumagundam** [SAPDocuments/Tutorials#4992]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-consume-external-api.html

Please specify the step you are referring to

The screenshots don't match with text instructions. And also the iFlow doesn't make sense either. For example, use content enrich to call another iFlow that doesn't return any useful information.

**Comment by gauthamkrishna-sap** [comment]
Hello,
We are working on overhauling the entire tutorial series and will publish the updates shortly. Apologies for the delay in response.
Thanks & Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
