### ISSUE TITLE
Deploy SAP HANA as a Service

### ISSUE THREAD

**Issue by bask-alur-gh** [SAPDocuments/Tutorials#4993]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-deploying-haas.html

Step2 "Services -> Service Marketplace. Click on SAP HANA Service" - SAP HANA Service is not available as shown in the screenshot, just "SAP HANA Schemas & HDI Containers (Trial) ", and this one doesn't have "Enterprise" service plan as shown in the subsequent step when creating an instance.  Thanks for checking this.

**Comment by jung-thomas** [comment]
You probably don't have the license for SAP HANA Service then. As the tutorial states:
**This tutorial cannot currently be completed with a trial account.**
**Requires Customer/Partner License**
**You have a productive account with entitlement to the SAP HANA Service in Cloud Foundry**

**Comment by bask-alur-gh** [comment]
That explains it, thanks for the feedback.

**Comment by jung-thomas** [comment]
We do have a trial offering coming soon. You can sign up to be notified once its available here: https://info.sapdigital.com/sap-hana-cloud.html
