### ISSUE TITLE
Image Similarity Scoring with SAPUI5

### ISSUE THREAD

**Issue by mykhaylo-dinul** [SAPDocuments/Tutorials#4994]
Tutorial URL: https://developers.sap.com/tutorials/ml-fs-sapui5-img-similarityscoring.html

In this tutorial validate step (step 17) correct answer is not correct anymore due to path to image feature extraction was changed.

**Comment by jarjarbentley** [comment]
Thank you for pointing this out.  We will correct the validation.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
