### ISSUE TITLE
Create Table Persistence and Generate Data

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#4997]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-persistence.html

Please specify the step you are referring to
Step # 2: Create database table
Step # 3: Create ABAP Class

The instructions mention this:
"Click Finish to create your transport request"

But - and I know this is nitpicking! - it should actually be something like this as the transport request was already created in Step # 1:
"Click Finish to add the object to the transport you created earlier."

Cheers
Bärbel

**Comment by mervey45** [comment]
Hi @BaerbelW ,

thank you for your feedback. We will update this as soon as possible.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
