### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#4998]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-data-model.html

Please specify the step you are referring to
Step # 2: Create projection view for travel

Under 5. it says "Define root view entity for ZC_TRAVEL_M_XXX."
![grafik](https://user-images.githubusercontent.com/18588108/80097622-de8d0480-856b-11ea-98d1-a3139640bda7.png)

But this doesn't really fit with what I see when I click "Finish" under 4. Instead I see this (s.th. comparable happened in Step # 1)
![grafik](https://user-images.githubusercontent.com/18588108/80097457-9d94f000-856b-11ea-8df9-54bb32c208f0.png)

"6. Your result should look like this. Replace your code with following:" therefore doesn't really fit.

I can still replace the code with what is shown below that and it can be activated, but I always find it confusing if what I see in the system doesn't fit the instructions - esp. as I don't really know the details of what I'm doing. The rest of the steps in the tutorial worked as described.

Not sure if it's related, but when I worked on Step 1 of this tutorial and reached the "Finish" step to pick the transport request, I got this error message (which I grabbed the screenshot of but otherwise ignored):
![grafik](https://user-images.githubusercontent.com/18588108/80098219-cb2e6900-856c-11ea-8cd9-a4f831ce099b.png)

I'm using this version of Eclipse/ADT 2019-09 R (4.13.0)

Is the update of the client installation actually required? If yes, than it might cause some issues as it's usually not possible for me to update Eclipse directly on my company laptop.

Thanks much and Cheers
Bärbel

**Comment by mervey45** [comment]
Hi @BaerbelW ,

you need to specify your data source (database table) and try it out again.

Best regards, 
Merve

**Comment by BaerbelW** [comment]
Hi Merve,
thanks for your quick reply. Just not really sure what you mean as everything did work and I did get the app preview displayed. So, there's nothing technically wrong from what I can tell. It was just confusing to me, that I didn't really know what you wanted me to do with these instructions:
![grafik](https://user-images.githubusercontent.com/18588108/80101193-61fd2480-8571-11ea-865c-5c8786ea55a9.png)

What I saw on my end after clicking "Finish" looked quite different as shown in my OP.

Cheers
Bärbel

**Comment by mervey45** [comment]
Hi @BaerbelW ,

the first instruction (5.) is the definition of the root view. The second picture describes how the complete result looks like (if you want to compare your projection view, with the one from the tutorial).

I hope it is clear now.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
