### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by BaerbelW** [SAPDocuments/Tutorials#4999]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-behavior.html

Please specify the step you are referring to
Step # 5 / 5: In your local types replace your code with following:

After copying the provided code and replacing XXX with 815 I get a syntax error I don't know where & how to fix:
![grafik](https://user-images.githubusercontent.com/18588108/80104602-ae4b6300-8577-11ea-9f6b-52a7bf2b16a4.png)

How can I find out what's wrong in ZI_TRAVEL_M_815 which I copied from the earlier tutorial/step (and as somebody who doesn't really know what all the code in there means I might add)? In case you need it, the code is in the attached file:
[IssueWithTutorial-related-to-ZI_TRAVEL_M_815.txt](https://github.com/SAPDocuments/Tutorials/files/4522799/IssueWithTutorial-related-to-ZI_TRAVEL_M_815.txt)

Thanks for your help & Cheers
Bärbel

**Comment by BaerbelW** [comment]
Just wondering if this issue could be due to the earlier warning I mentioned [here](https://github.com/SAPDocuments/Tutorials/issues/4998), regarding the need to update the client installation:
![grafik](https://user-images.githubusercontent.com/18588108/80351018-ebfb0500-8871-11ea-92c2-c3609c74c043.png)

I just got it again and this time clicked on "Update now" only to see this a short while later:
![grafik](https://user-images.githubusercontent.com/18588108/80351116-0fbe4b00-8872-11ea-817e-2368c46cb00c.png)

Cheers
Baerbel

**Comment by mervey45** [comment]
Hi @BaerbelW ,

please make sure you have the latest ADT installation:  https://tools.hana.ondemand.com/#abap 

Please follow the instruction:

**Procedure**
To install the front-end component of ADT, proceed as follows:

Get an installation of Eclipse 2020-03 (e.g. Eclipse IDE for Java Developers)
In Eclipse, choose in the menu bar Help > Install New Software...
Enter the URL https://tools.hana.ondemand.com/latest
Press Enter to display the available features.
Select ABAP Development Tools and choose Next.
On the next wizard page, you get an overview of the features to be installed. Choose Next.
Confirm the license agreements and choose Finish to start the installation.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
