### ISSUE TITLE
Map Message Structure

### ISSUE THREAD

**Issue by RS-CONCETO** [SAPDocuments/Tutorials#5000]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-convert-message-structure.html

Please specify the step you are referring to

STEP1 

Dear Team,

FYI: The links for the source and target message in Step 1 are expired.

Best regards
Robert

**Comment by RS-CONCETO** [comment]
Hi Team

Is somebody working on this issue?

Thanks for a quick response and best regards
Robert

**Comment by thecodester** [comment]
@gauthamkrishna-sap Updates?

**Comment by gauthamkrishna-sap** [comment]
Hello,
We are working on overhauling the entire tutorial series and will publish the updates shortly. Apologies for the delay in response.
Thanks & Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
