### ISSUE TITLE
Map Message Structure

### ISSUE THREAD

**Issue by NzengaFr** [SAPDocuments/Tutorials#5004]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-convert-message-structure.html

Step3 paragraph 2 : "Go to visual editor at the bottom and click on Create function".

when i select mapping Address in the visual Editor  mapping expression is empty (no function dispaly)
only a warning message for multiple outputs.
I have added function SplitAddr after selecting the target mapping fields one by one.
regards

**Comment by gauthamkrishna-sap** [comment]
Hello,

Could you please share a screenshot of your error? I am unable to reproduce it. 

Thanks, Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
