### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by RaquelSpain** [SAPDocuments/Tutorials#5007]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Please specify the step you are referring to Step 9: Test generic handlers with Postman

Click on the following link and save the file to a folder of your choice: postman.json.
The file is attached. I get the error: Error while importing: format not recognized

To update the file, I had to rename to TxT as JSON is not supported
[postman.txt](https://github.com/SAPDocuments/Tutorials/files/4528775/postman.txt)

**Comment by chgeo** [comment]
I can perfectly save the file as json.  Which browser do you use?
Also, the attached postman.txt from above seems to be binary, so I am not sure what went wrong there.

Please verify this link really doesn't work fpr you: https://raw.githubusercontent.com/SAPDocuments/Tutorials/master/tutorials/cp-apm-nodejs-create-service/postman.json

**Comment by RaquelSpain** [comment]
> I can perfectly save the file as json. Which browser do you use? I can save it, but the files .json can not be uploaded here. 
>Also, the attached postman.txt from above seems to be binary, so I am not sure what went wrong there. Here I checked when saving the file->Used encoding UTF-8 and it works so

Thanks

**Comment by iwonahahn** [comment]
Is your issue resolved and to close it?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
