### ISSUE TITLE
Configure the SAP HANA R Integration with SAP HANA, express edition

### ISSUE THREAD

**Issue by dritter2** [SAPDocuments/Tutorials#5008]
Tutorial URL: https://developers.sap.com/tutorials/mlb-hxe-setup-r.html

Please specify the step you are referring to

**Comment by dritter2** [comment]
Dear Team,

The guide is missing a crucial step of setting up the Rserve.conf file.

Without that, the scenario will not work.

You can reach out to me at
d.ritter@sap.com
I347241

Kind regards,
Daniel

**Comment by thecodester** [comment]
@Sygyzmundovych If someone else is responsible for Abdel's tutorials, let me know. Sorry if this should be assigned someone else.

**Comment by thecodester** [comment]
@jung-thomas Who can handle this issue?

**Comment by MichaelCzcz** [comment]
@jung-thomas please respond.

**Comment by jung-thomas** [comment]
@Sygyzmundovych is already assigned to this issue. Witalij please supply an update on the status of this issue.

**Comment by Sygyzmundovych** [comment]
Sorry for the delay. I will contact @dritter2

**Comment by Sygyzmundovych** [comment]
I tested the tutorial and it works as published: without setting `Rserve.conf` (https://help.sap.com/viewer/a78d7f701c3341339fafe4031b64f015/2.0.04/en-US/d2c2eeac2beb4e709161e77a238f3b3b.html). 

The communication between HANA and Rserve is via the localhost.
