### ISSUE TITLE
Prepare the Portal Environment for Creating Sites

### ISSUE THREAD

**Issue by ceerix** [SAPDocuments/Tutorials#5010]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Please specify the step you are referring to

The result of this lesson a kind of blue sceen with some little clouds and just this two sentence:
**Sorry, we couldn’t find the site.
Please contact your site administrator for assistance.**

![2020-04-24 17_01_48-Access Denied Page](https://user-images.githubusercontent.com/59439052/80227000-60a12a00-864d-11ea-8943-783c26c93c17.png)

???

**Comment by IrisSasson** [comment]
Hi

This seems to be that at the minute you tried, the trial environment was down. Please try again and let us know

Thanks

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
