### ISSUE TITLE
Test SAP HANA, express edition

### ISSUE THREAD

**Issue by lpareek** [SAPDocuments/Tutorials#5015]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-test-vm-xsa.html

Please specify the step you are referring to
**Step #3.3**
From SAP laptop I cannot reach https://hxehost:53075.

How can I resolve this issue?

**Comment by jung-thomas** [comment]
Did you complete this step earlier in the tutorial? https://developers.sap.com/tutorials/hxe-ua-hosts.html

This is what makes hxehost reachable from you main OS.

**Comment by jung-thomas** [comment]
VPN connection was blocking network access

**Comment by lpareek** [comment]
Hi Thomas,
Thanks for pointing out that VPN must be disconnected on SAP laptop. Problem solved.

**Comment by Aijaz-Qureshi** [comment]
I am experiencing the same issue of being unable to connect to [(https://hxehost:53075)] via the browser on my PC. Please note that I have defined the hxehost in my hosts file on my PC and I can ping the name from a CMD prompt. As someone mentioned above, I also tried with Windows Defender Firewall turned-off but still unable to get into the HXE IDE from a browser.
