### ISSUE TITLE
Create Cloud Foundry App with Blockchain Features of SAP Cloud SDK

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#5017]
Tutorial URL: https://developers.sap.com/tutorials/blockchain-sdk-sample.html

Please specify the step you are referring to: 1

any plans to make it also fabric and not only multichain centric?

thank you

**Comment by thecodester** [comment]
@chrisfries Can you look at this?

**Comment by chrisfries** [comment]
Hi @greg2git 
There's currently no plan to add the same tutorial for hyperledger fabric.
