### ISSUE TITLE
Setup Node.js to connect to HXE

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#5018]
Tutorial URL: https://developers.sap.com/tutorials/hxe-nodejs-setup.html

Please specify the step you are referring to 2

yes, it will definitely fail on SLES distro (CPE_NAME="cpe:/o:suse:sles:12:sp3") for both nodejs10 and 12 with the same error message:
      npm ERR! zlib: invalid distance too far back
and it seems like the same HANA instance cannot be both server and client in SLES.

**Comment by jung-thomas** [comment]
I'm sorry but I don't understand.  This step is just to determine the version of Node.js you are running.  This is on your developer desktop NOT the server.  You are supposed to install Node.js and then just to check the installation determine the version.

**Comment by greg2git** [comment]
this command line is in step 2: "npm install @sap/hdbext" and it has failed multiple times for me on SLES with this error message: "npm ERR! zlib: invalid distance too far back". 

i understand the tutorial is for HXE and not SLES, so maybe it belongs to prerequisites.  

thx for the quick response, nevertheless.

**Comment by jung-thomas** [comment]
The command in this tutorial should be done on your development machine - not on the HANA instance.  So your Windows or Mac laptop.  

I'm closing this issue as there is nothing wrong with the tutorial in question.  If you need assistance installing @sap/hdbext I'd recommend that the correct action is to post a question in the SAP Community Q&A.
