### ISSUE TITLE
Install the Cloud Foundry Command Line Interface (CLI)

### ISSUE THREAD

**Issue by AmauryVanEspen** [SAPDocuments/Tutorials#5020]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

Installing Cloud Foundry CLI on windows, report to this issue
cloudfoundry/docs-cf-cli#57

For Windows 10 user, type :
SET HOMEDRIVE=C:

to solve the issue :
mkdir P:: The system cannot find the path specified.

**Comment by iwonahahn** [comment]
Thank you for contacting us. Please close this issue cause it is a duplicate and already reported in #5019.
