### ISSUE TITLE
Unable to update Enterprise Messaging default plan service instance

### ISSUE THREAD

**Issue by rahulkapoor** [SAPDocuments/Tutorials#5021]
Hello Colleague,

I am unable to update enterprise messaging default plan service instance in CF EU10 canary via CF command-line. Getting the error as:

Server error, status code: 502, error code: 10001, message: Service broker error: Service broker enterprise-messaging-service-broker failed with: Service broker parameters are invalid: [{"message":"Invalid combination of queue and topic pattern versions. Do not mix standard and unified syntax.","propertyPath":""},{"message":"Invalid combination of queue and topic pattern versions. Do not mix standard and unified syntax.","propertyPath":""}]

Can you please help fix this or correct me if I am missing something ?

Below is the json I am using:

{
	"options": {
		"management": true,
		"messagingrest": true,
		"messaging": true
	},
	"emname": "emdefault",
	"namespace": "EAM/emdefault/01",
	"rules": {
		"queueRules": {
			"publishFilter": [
				"${namespace}/*"
			],
			"subscribeFilter": [
				"${namespace}/*"
			]
		},
		"topicRules": {
			"publishFilter": [
				"${namespace}/*"
			],
			"subscribeFilter": [
				"${namespace}/*"
			]
		}
	}
}

**Comment by rahulkapoor** [comment]
Just to add, same issue is reproducible on CF EU10 (AWS) Live instance too.
Feel free to let me know if you need additional details from my end. 

Thanks a lot,
Rahul Kapoor

**Comment by pradeeppanda-sap** [comment]
two issues :

  1. add the version after namespace
              "version": "1.1.0",
   2. in all the filter patterns, you have not given *.  Add * after /

**Comment by rahulkapoor** [comment]
I guess I was just missing version in the payload. I did put /* in the filter, somehow it didn't show in my comment earlier. 

Added version now and it worked. Didn't understand, why version is mandatory in the payload ?

Thanks a lot Pradeep, this issue is resolved. 

Probably if you don't mind asking & in case you help me with a quick question, in CF EU10 canary, for enterprise messaging (default plan) there is no access to service instance dashboard.

Its expected to manage queue/events from Enterprise Messaging hub UI, but in **Canary** there doesn't give to be an option to maintain enterprise channel group as explained in the tutorial [here](https://developers.sap.com/tutorials/s4sdk-consuming-messages.html#aabaa707-8d44-4e01-b002-0028ca2f207c) (Step 18). 

On the other hand, in EU10 **Live**, Step 19 doesn't seem feasible with EM **Default** plan. Unfortunately this bit confusing.

[This](https://developers.sap.com/tutorials/s4sdk-consuming-messages.html#aabaa707-8d44-4e01-b002-0028ca2f207c) tutorial doesn't seem up to date with latest changes.

Can you suggest if someone can help me clarify this ?

Thanks
Rahul Kapoor
