### ISSUE TITLE
Integrate Microsoft Azure AD with SAP Cloud Platform Cloud Foundry

### ISSUE THREAD

**Issue by BenediktHoelker** [SAPDocuments/Tutorials#5023]
Tutorial URL: https://developers.sap.com/tutorials/cp-azure-ad-saml.html

I am trying to configure Azure AD as Identity Provider for my CF trial subaccount. In order to create a new Trust Configuration in SAP CP I am supposed to upload the Azure AD metadata. Yet when I click on upload, nothing happens. When I inspect it with Chrome debugger I find a 405 error on POSTing to https://cockpit.eu10.hana.ondemand.com/.

**Comment by maxstreifeneder** [comment]
thanks @BenediktHoelker! just had a look, works for me. Could you try it once again? 

Right now I think you have to open a Support Ticket - trying to find out the right Component for assigning the ticket.

**Comment by maxstreifeneder** [comment]
as we just had a conversation in Slack: You want to add another TrustConfiguration for CF Trial. (but apparently the call you debugged goes to a non-trial environment - thanks for the analysis, makes things way easier for me!) 

can you please do me a favor and tell me a little about your trial account? A screenshot would be highly appreciated. 

![image](https://user-images.githubusercontent.com/36535298/80364242-d8599980-8885-11ea-94c5-c97ca23b0431.png)

thank in advance!

**Comment by BenediktHoelker** [comment]
Hi @maxstreifeneder! Thanks for your help on the issue. This is my account information
![image](https://user-images.githubusercontent.com/16203886/80373930-26769900-8896-11ea-98aa-e925c40d1bd1.png)

**Comment by maxstreifeneder** [comment]
Hi @BenediktHoelker - unfortunately I don't have a solution right now. Does the error still occur? Might have a feedback from the responsible team by next week.

**Comment by BenediktHoelker** [comment]
Still no luck :( 
![image](https://user-images.githubusercontent.com/16203886/80790765-fda11d00-8b8f-11ea-8477-8323d6d5560c.png)

Thanks for your efforts anyway!

**Comment by maxstreifeneder** [comment]
Hey @BenediktHoelker,

thanks for your effort! We identified the reason already together, I know - but wanted to document it anyway. The upload doesn't work - please copy the metadata of the actualy metadata xml manually and parse it. 

Opened a Ticket for the responsible product team - they'll take care of it. 

Cheers,
Max
