### ISSUE TITLE
Reuse a CAP Java Service

### ISSUE THREAD

**Issue by raz-korn** [SAPDocuments/Tutorials#5028]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-service-reuse.html

Please specify the step you are referring to
Step 2.2: the created tgz is sap-capire-products-1.0.0.tgz

**Comment by maxstreifeneder** [comment]
thanks raz! will go over all created issues by end of the week

**Comment by maxstreifeneder** [comment]
fix provided
