### ISSUE TITLE
Use JupyterLab with SAP HANA, express edition

### ISSUE THREAD

**Issue by biscuit-70** [SAPDocuments/Tutorials#5031]
Tutorial URL: https://developers.sap.com/tutorials/mlb-hxe-tools-jupyter.html

Please specify the step you are referring to:
- Step 5: Install JupyterLab

Building wheels for collected packages: subprocess32
  Building wheel for subprocess32 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
compilation terminated.
    error: command 'gcc' failed with exit status 1

[linux log.txt](https://github.com/SAPDocuments/Tutorials/files/4540546/linux.log.txt)

**Comment by Sygyzmundovych** [comment]
Hi @biscuit-70 . Sorry for delay replying.

There was an error message `fatal error: Python.h: No such file or directory` in your log. It means that Python2 developer libraries are not properly installed.

Fix it with `sudo zypper in python-devel`

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
