### ISSUE TITLE
Create a Developer User in SAP Cloud Platform ABAP Environment

### ISSUE THREAD

**Issue by I322851** [SAPDocuments/Tutorials#5032]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-developer-user.html

Step 2:Log in to SAP Fiori Launchpad as administrator
Sub step 4: Login with admin user and password in SAP Fiori Launchpad.

Hi I am following the tutorials with The trial instance. In the Step 4 can you please let me know what is the admin username and password. 

Best Regards,
Chaitra

**Comment by mervey45** [comment]
Hi @I322851 ,

you can't do this tutorial with the trial user. You need a license for it. We marked this tutorial as a licensed tutorial.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by I322851** [comment]
Hello,

I wanted to check if we can try this using Europe(Frankfurt)-canary account.
I could not find ABAP trial in the entitlements.

Best Regards,
Chaitra
