### ISSUE TITLE
Add Service Logic to Consume Remote Address Data

### ISSUE THREAD

**Issue by gabriel-k** [SAPDocuments/Tutorials#5033]
Tutorial URL: https://developers.sap.com/tutorials/cap-cloudsdk-5-srv-logic.html

Referring to step 4

In the custom handlers, we see that the expand query options get to be processed manually. Knowledge about the domain model is thus mixed with logic around processing query options.

For one thing, it does not feel right to gain access to OData specifics inside a CAP handler (I suspect it is a hack because the CQN query has been mutated in the before handler to avoid pushing unknown stuff to SQL. As a result it no longer holds the expanded column info). But, more importantly, the custom handler approach seems ill-conceived when implementing a query handler considering how rich and expressive the query language can be. 

For instance what happens if the query includes a filter or an order by clause that leverages the information in the expanded field. This is entirely possible even in OData v2 e.g. https://services.odata.org/Northwind/Northwind.svc/Orders?$format=json&$expand=Customer&$filter=Customer/City%20eq%20%27Aachen%27. 
Then it appears this thing would break, unless the filter gets split in the before handler so as to remove parts that deal with address properties from the CQN (avoiding a push down to SQL), and then gets to be applied in the after handler in memory. This is tricky to implement as one need to deal with an expression tree.  Also it means putting the burden of handling all query options (not just filter) on the developer's shoulder which I guess is not really in the spirt of the framework.

**Comment by qmacro** [comment]
Thanks @gabriel-k these are great comments. I must stress though that this is just an example and not designed to be 100% robust in all circumstances - it's more to give a taste of the layers involved, and what's possible. That said, what you say is extremely interesting, and I'd encourage you to continue this conversation over in the SAP Community - there are CAP team folks there who will be able to add far more than I can in the context of this tutorial feedback system, and the discussion would benefit others too. Cheers. DJ
