### ISSUE TITLE
Set Up SAP Business Application Studio for Development

### ISSUE THREAD

**Issue by bask-alur-gh** [SAPDocuments/Tutorials#5034]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-onboarding.html

Step 5, bullet 5: Go the application gives an error "Access Denied.  You do not have the required permissions to access SAP Business Application Studio. Please contact your administrator to request access. Read more about managing authorizations for SAP Business Application Studio.", even though I have granted the BAS_Administrator and BAS_Developer roles to myself.  Thanks in advance for help!

**Comment by raz-korn** [comment]
A full logout-login cycle is required. It might take a few minutes for the changes to kick in.

**Comment by bask-alur-gh** [comment]
Hi, Thanks for looking into this.  I had previously added these roles directly to my ID and that seems to be the issue.  Subsequently following an OpenSAP course I added a 'Role Collection' with this Application ID, added the BAS_Developer role to it, and added this role collection to my ID under Trust Config and it started working.  So closing this issue.  Sincerely appreciate your feedback.
