### ISSUE TITLE
Test the Business Rules API from SAP API Business Hub

### ISSUE THREAD

**Issue by veeraa83** [SAPDocuments/Tutorials#5035]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules09-test-apis.html

in this step - Step 4: Observe the API response

I receive the below response, when I sent the payload as given in step# 3
Response
**{
  "Result": []
}**

Request Payload:
**{
 "RuleServiceId": "<id>",
  "Vocabulary": [
    {
      "Employee": {
        "isFullTimeEmployee": true,
        "countryofCompany": "USA",
        "jobTitle": "Engineer II",
         "company": "2000"
       }
    }
  ]
}**

**Comment by VandanaVasudevan** [comment]
Hi,

The payload is correct. Can you send me a snapshot of your DetermineEquipmentRules decision table? or cross-check if the values entered in the decision table are correct?

Best Regards,
Vandana

**Comment by veeraa83** [comment]
Hi Thanks for the very quick response.I verified once again but could not find out an issue in the decision table. Attaching a snapshot here. Could you please help me identify the issue?

Thanks in advance.
![DetermineEquipmentRule1](https://user-images.githubusercontent.com/8470543/80479454-abcc7d00-896c-11ea-99d5-7392d3b7cf36.JPG)
![DetermineEquipmentRule2](https://user-images.githubusercontent.com/8470543/80479470-b129c780-896c-11ea-825c-55fecd0a6511.JPG)

2) Also, I would like to know if the UI used for maintaing the business rules which we deployed SCP
(https://<trial num>-dev-businessruleseditor-approuter.cfapps.eu10.hana.ondemand.com/comsapbpmrule.ruleeditor/index.html#//Projects) shall this remain the same in actual scenario, I would like to know whether cloud developers need to develop a UI for maintaining  these rules for business users or it is the standard UI that can be used  in a production scenario as well. If not is there any low level API to develop the UI for business rules maintainence.
3)  when we deploy a business rule after activating it in the Manage Project Application, where is it getting deployed?. I do not find any new application in SAP cloud platform cockpit after the deployment. If this is not the correct forum to raise these doubts,can you please point me to the place where can ask these questions. Since these are not clearly explained in the tutorials, raising them here. Thanks

**Comment by VandanaVasudevan** [comment]
Hi,

Do you mind sharing your project zip file with me? You can export the project to your local system using the steps in this link: [Export a Project](https://help.sap.com/viewer/0e4dd38c4e204f47b1ffd09e5684537b/Cloud/en-US/3e39d772410c4759983786a7bf60c4e1.html)

2. This is the standard UI that is available in the production scenario too. 

3. When we deploy a rule service, it gets deployed to the SAP Cloud Platform (in this case). You can also deploy it to other systems if you configure it. In short, a rule service should be deployed first before invoking it. In this tutorial, we are invoking the rule service using API Business Hub to automate the decision scenario. In a bigger picture, when Business Rules is embedded as a part of a custom application, the rule service should be deployed to the system (For example, SAP Cloud Platform) and invoked to implement the decision logic in your custom application. You can also refer to the Business Rules documentation for more information on the service: [SAP Cloud Platform Business Rules](https://help.sap.com/viewer/product/BUSINESS_RULES/Cloud/en-US)

**Comment by veeraa83** [comment]
Hi Thanks for your quick reply. I have uploaded the project  here. I have tried another scenario with decision table(ProductDiscountRuleService) and it is working fine.

[DetermineEquipment01.zip](https://github.com/SAPDocuments/Tutorials/files/4549974/DetermineEquipment01.zip)
Thanks for your clarification. I deployed the file businessruleseditor_0.0.1.mtar from web IDE as mentioned in the tutorial. so in my trial version, inside the dev space, I could only see one application deployed with the name businessruleseditor_appRouter.(PFA the screenshot app.JPG)
![app](https://user-images.githubusercontent.com/8470543/80565625-90b24980-8a0e-11ea-8d34-7a1167650e1d.JPG)After this even if I create any number of rule services inside the Mange Projects UI, I do not see them in this location. I raise this point, since if the deployment of a rule service is as deploying any application from web IDE to cloud platform, then the business user should also be provided with the same authorizations.

**Comment by ArchanaShukla** [comment]
Hello Veera, 
Here are the answers to your questions: 

1. You payload in not according to your data object. In your payload you have used **is**FullTimeEmployee but in your data object you have used **Is**FullTimeEmployee and the rule engine does not find any matching condition, and it return an empty value. Also, I see that your rule-service Id is not defined in your payload, in that case rule engine does not know which rule service to invoke. 

2. Manage Rule Projects application is a standard pre-delivered app-router based application that one needs to set it up in their respective cloud accounts - trial or factory. Entire life cycle of the business rules projects is maintained and managed from this Manage Rule Project app. Business rules project is the container for all design time artefacts of rules like data objects, rule services, rules and rulesets. Everything you create in manage rules application is persisted in the data base maintained by the business rules provider accounts and consumers do not have access to it. This is pretty much standard for all cloud services. 

3. When you deploy the rule service, it becomes available to consumption only via public REST APIs. There is currently no way available to see these deployed rule services. When you deploy the rule service it will not be available in under applications coz it is not an CF application instead its a runtime object that can be consumed only via public APIs. All the APIs design time and runtime are available in API Business Hub (https://api.sap.com)

Please read more in the [documentation](https://help.sap.com/viewer/p/BUSINESS_RULES) or several [blogs](https://blogs.sap.com/tags/73554900100800000842/) published by us.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
