### ISSUE TITLE
Configure Eclipse with SAPUI5

### ISSUE THREAD

**Issue by kueblertgb** [SAPDocuments/Tutorials#5037]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-install-eclipse.html

Please specify the step you are referring to

This Tutorial was a nice start with Eclipse.
But wen i search your Tutorials, there is not one to find with a single example of using the
Javascript framework with Eclipse. This is verry sad.

Kind Regards
Tobias

**Comment by IObert** [comment]
Hi @kueblertgb,

I can understand your frustration. Let me explain why you found this "orphaned" tutorial. We decided to keep it because it gets a lot of traffic, however, we don't recommend using Eclipse for UI5 development any longer. Newer solutions from SAP are the Web IDE or the Business Application Studio.
In case you prefer a local IDE, you can use such as well (thanks to the [ui5 tooling](https://sap.github.io/ui5-tooling/)). I personally use VS Code but you can use literally any editor.

Here is a tutorial mission I'd recommend for these IDEs: <https://developers.sap.com/mission.sapui5-cf-first.html>

**Comment by kueblertgb** [comment]
Hi,
thank you for your Response,

the Problem is, that we are not allowed to use Cloud development.
Because of Datasecurity and  dependency.

What is VS Code???
Any Tips for a good  IDE with some Syntax help. Eclipse has almost no help
for syntax. At last if you compere it with the SE80 in SAP-Abap.

Mit freundlichen Grüßen

Tobias Kübler


www.fewo-erlensee.de
T: 015142451688
E: info@fewo-erlensee.de



Am Di., 28. Apr. 2020 um 11:18 Uhr schrieb Marius Obert <
notifications@github.com>:

**Comment by IObert** [comment]
VS Code is short for "Visual Studio Code", an [open source editor](https://code.visualstudio.com/_) by Microsoft.

**Comment by kueblertgb** [comment]
Hi,
The Link you sendet me gives me 3 Option.
Because i can not use cloud i have to choose nr. 3.


Get Ready to Develop on SAP Cloud Platform
<https://developers.sap.com/group.scp-1-get-ready.html>

Learn the basics of SAP Cloud Platform, then get ready for development by
registering for a trial account and taking a tour of the SAP Cloud Platform
cockpit.
Develop Your First SAPUI5 Web App with SAP Web IDE
<https://developers.sap.com/group.cp-ui5-first-app.html>

Get to know SAP Web IDE while you build a simple web app and deploy it to
the SAP Cloud Platform Cloud Foundry environment.
Develop Your First SAPUI5 Web App with Your Own Dev Tools
<https://developers.sap.com/group.cp-ui5-first-app-your-tools.html>
If i do this i get linked again to this view

all thiese Tutorials tell how to develop on CLI...
But Colde Line Interfaces are compleatly new for me...what is this ??? And
again it is the Cloud word in it...
so i said i dont want Cloud.

Tutorials
Install the Cloud Foundry Command Line Interface (CLI)
<https://developers.sap.com/tutorials/cp-cf-download-cli.html>

Download and install the CLI, which allows access via the command line.
Install the MultiApps Cloud Foundry CLI Plugin
<https://developers.sap.com/tutorials/cp-cf-install-cliplugin-mta.html>

Download and install the Command Line Interface (CLI) plugin. This plugin
allows you to deploy MTA achives from the command line.
Get Ready to Develop on Your Local Machine
<https://developers.sap.com/tutorials/cp-cf-sapui5-local-setup.html>

Prepare you local development environment to implement successful SAPUI5
projects.
Create an SAPUI5 App from the Command Line
<https://developers.sap.com/tutorials/cp-cf-sapui5-local.html>

Create and test a newly created SAPUI5 app on you local machine with the
editor of your choice.
Debug Your SAPUI5 App
<https://developers.sap.com/tutorials/cp-cf-sapui5-local-debug.html>

Debugging and logging are the nut and bolts to inspect your application.
Learn how to debug and test your web apps with the Google Chrome Dev Tools.



Mit freundlichen Grüßen

Tobias Kübler


www.fewo-erlensee.de
T: 015142451688
E: info@fewo-erlensee.de



Am Di., 28. Apr. 2020 um 12:07 Uhr schrieb Marius Obert <
notifications@github.com>:

**Comment by IObert** [comment]
Yes, you can also skip the first two tutorials of the last group if you don't want to deploy the web app to the cloud. 
If you're interested, you could also do all three tutorial groups in the trial landscape (which is free). There's no license required for that :)

**Comment by IObert** [comment]
Please reopen this issue if you have additional questions :)
