### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by EricW145** [SAPDocuments/Tutorials#5038]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
Thank you for the good learning material, but In xs-app.json the source is wrong:

      "source": "^/sap/opu/odata/sap/Z_I_BOOKING_XXX/(.*)$",
      "target": "/sap/opu/odata/sap/Z_I_BOOKING_XXX/$1",

should be:
      "source": "^/sap/opu/odata/sap/ZUI_C_TRAVEL_M_XXX/(.*)$",
      "target": "/sap/opu/odata/sap/ZUI_C_TRAVEL_M_XXX/$1",

Thank you

**Comment by mervey45** [comment]
Hi @EricW145 ,

thank you for your feedback. We will update this as soon as possible.

Best regards, 
Merve

**Comment by mervey45** [comment]
@thecodester we can close this issue.

**Comment by EricW145** [comment]
thank you.
