### ISSUE TITLE
Maintain a Communication Arrangement for Inbound Communication

### ISSUE THREAD

**Issue by Juanvictormanuel1188** [SAPDocuments/Tutorials#5041]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

Please specify the step you are referring to

Cannot continue this tutorial because of trial user account:

![image](https://user-images.githubusercontent.com/64492634/80519882-49648400-894e-11ea-8bb9-e0f5cd5c81a6.png)

Can you please numb next steps to display other elements?

Thanks and Regards!
Victor

**Comment by mervey45** [comment]
Hi @Juanvictormanuel1188 ,

you need a licensed tutorial for this tutorial. It is also marked as a licensed one. You are not allowed to do this tutorial with your trial user.

Best regards, 
Merve
