### ISSUE TITLE
Create Your First Console Application with ABAP Environment

### ISSUE THREAD

**Issue by Juanvictormanuel1188** [SAPDocuments/Tutorials#5042]
Group URL: https://developers.sap.com/group.abap-env-first-app.html

Hello, GA,

This tutorial group cannot be completed due to next issue: 

Maintain a Communication Arrangement for Inbound Communication #5041 

Let me know anything please.

Thanks and regards!
Victor

**Comment by mervey45** [comment]
Hi @Juanvictormanuel1188 ,

you need a licensed user to do the following tutorial: Maintain a Communication Arrangement for Inbound Communication.

@thecodester we can close this issue.

Best regards, 
Merve

**Comment by yutangc** [comment]
Hello, GA.

How can I get a license for Inbound Communication?

**Comment by Juanvictormanuel1188** [comment]
Hello, 

Im also interested as @yutangc.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
