### ISSUE TITLE
Deploy MTA App Using Open Service Broker API

### ISSUE THREAD

**Issue by jukedbymom** [SAPDocuments/Tutorials#5043]
Tutorial URL: https://developers.sap.com/tutorials/cp-osba-azure-deploy-mta.html

 Step 3: Deploy application to SAP Cloud Platform Cloud Foundry

in this step i have to execute this command: cd ~ && cf deploy teched_cap_application.mtar

when I do it I get this error 
![image](https://user-images.githubusercontent.com/64496231/80525737-9a459e00-8989-11ea-85d1-b3835258d8e9.png)

If anyone can help me I would be very grateful, I've followed each step like in the tutorial.

**Comment by maxstreifeneder** [comment]
Hi @jukedbymom,

thanks for your feedback! The error message basically says that something is wrong with the Service Broker (obviously) - this can have several reasons. 

Could you please do several things for trouble shooting: 

1) make sure you have replaced all the placeholders in the manifest.yml - the file shouldn't contain any <> anymore. (see screenshot with absolute fictive and random values by me just to show that there shouldn't be any more <>)

![image](https://user-images.githubusercontent.com/36535298/80705242-60d67500-8ae6-11ea-864a-37f6a2fcbe45.png)

2) make sure that the service broker application is successfully deployed and in state started. 

```bash
cf apps
````
(please provide a screenshot so I can double-check)

3) make sure that the service broker application is registered with the right URL. Therefore take the URL from cf apps for Step 9: Register service broker in Cloud Foundry space

please provide a screenshot from the output of: 

```bash
cf service-brokers 
```

4) if all of those steps are correctly done we need to check the deployment log of the MTA. Could be that the service broker application was deployed so quickly (kudos ;-) ) that the redis cache wasn't yet fully provisioned. The service broker application needs a fully provisioned redis cache to work. 

At the end of the deployment process of `c` there should appear a **Use "cf dmol -i XXXXXXXXXX" to download the logs of the process.**

Please do the deployment of the MTA app once again, download the logs as said and provide the logfiles (will be downloaded to /mta-op-YOUR-OP-ID). 

Thanks and cheers,
Max

**Comment by jukedbymom** [comment]
![image](https://user-images.githubusercontent.com/64496231/80708265-4f3f9e00-8ae3-11ea-8a96-d14b79788eac.png)
Here is the screenshot of the cf apps,
city-cap-db appear to be stopped can this be the issue?
![image](https://user-images.githubusercontent.com/64496231/80708391-7dbd7900-8ae3-11ea-8ff3-09225221b06e.png)
and here is the screenshot for the cf service-brokers,  there's 2 urls since iv'e tried with twos accounts while getting the same issue.
Thanks for the help Max!

**Comment by maxstreifeneder** [comment]
that looks good unfortunately ;-)

cap-db in state stopped is intentional - it's just a one time task which stops after deploying things to the database. 

At the end of the deployment process of *cf deploy teched_cap_application.mtar*  there should appear a **"Use cf dmol -i XXXXXXXXXX to download the logs of the process."**

Please do the deployment of the MTA app once again, download the logs as said and provide the logfiles (will be downloaded to /mta-op-YOUR-OP-ID).

**Comment by jukedbymom** [comment]
Hey max, I've used the code to download the logs of the process but I don't know how to download them. Sorry, it's my first time using this, can you help me?

**Comment by jukedbymom** [comment]
[OPERATION.log](https://github.com/SAPDocuments/Tutorials/files/4558507/OPERATION.log)
I think this is it

**Comment by jukedbymom** [comment]
@maxstreifeneder   I have provided the logs you asked, can you help?
Thank you!

**Comment by maxstreifeneder** [comment]
hey @jukedbymom,

haven't forgotten to come back to you, sorry! Will give you a reply as soon as I have a fix! 
You can definitely expect a solution next week. 

Sorry for the delay,
Max

**Comment by jukedbymom** [comment]
No problem Max! Thanks for the help!

**Comment by maxstreifeneder** [comment]
Hey @jukedbymom,

could you please try the following steps: 

1) deploy the service broker application once again: 

```Bash
cd ~/open-service-broker-azure && cf push -f contrib/cf/manifest.yml
```
(make sure the values in your manifest.yml file are still the right ones - https://developers.sap.com/tutorials/cp-osba-azure-deploy-service-broker.html)

2) download the newest sample application release from GitHub

```Bash
curl https://github.com/SAP-samples/cloud-foundry-cap-azure-cities/releases/download/1.7.6/city-explorer-demo-app.mtar -L --output ~/cap-azure-sample-app.mtar
```

3) Deploy the newest sample application to SAP Cloud Platform:
cd ~ && cf deploy cap-azure-sample-app.mtar

if something crashes again, please provide once again the logs. If it still doesn't work, we might do a quick screenshare to check what's going on. 

Cheers,
Max

**Comment by jukedbymom** [comment]
[OPERATION (2).log](https://github.com/SAPDocuments/Tutorials/files/4634153/OPERATION.2.log)
Hi Max, here is the operation log, it still failed. No need to do the quick screenshare since this was for a school presentation and i'm picking up something else now! Thank you a lot for your time and patience!

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved (or no longer relevant), so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
