### ISSUE TITLE
Choose an SAP HANA Database

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#5046]
Tutorial URL: https://developers.sap.com/tutorials/hana-clients-choose-hana-instance.html

Please specify the step you are referring to 5

My login happens after these steps are executed:
1. sudo su - hxeadm
2. hdbsql -n localhost:39013 -u SYSTEM
3. <password>
4. ip addr fails with: "* 257: sql syntax error: incorrect syntax near "ip": line 1 col 1 (at pos 1) SQLSTATE: HY000"

**Comment by danielva** [comment]
Thanks for the good feedback.  I had meant for the ip addr command to be executed at the Linux shell and not in the hdbsql tool.  I have changed the order of the commands in the tutorial to make this clearer.  The change will appear in the next update to the tutorial.

Regards,
Dan van Leeuwen

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
