### ISSUE TITLE
Test Hyperledger Fabric Chaincode API

### ISSUE THREAD

**Issue by knair7** [SAPDocuments/Tutorials#5050]
Tutorial URL: https://developers.sap.com/tutorials/blockchain-test-chaincode.html

Please specify the step you are referring to Step 6

I am getting following error
{
  "key": "id001",
  "value": "Hello World!!"
}

**Comment by greg2git** [comment]
it's been a while since i've run this script, but why do you call this output an error? 

what were you expecting instead?

**Comment by thecodester** [comment]
@chrisfries Can you review this issue?

**Comment by chrisfries** [comment]
Hi @knair7 
take a look at the value attribute. There're two exclamation marks at `Hello World!!` in your case.
It should be only `Hello World!`. Then the validation of Step 6 will be successful.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
