### ISSUE TITLE
Create a Card from a Web Application

### ISSUE THREAD

**Issue by karicat7358** [SAPDocuments/Tutorials#5051]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-web-push.html

Please specify the step you are referring to: Create a New Card

Hi there,
The destination 'SAPCPMobileServices' doesn't appear in the Destination dropdown menu. 

<img width="641" alt="MobileCardsIssue" src="https://user-images.githubusercontent.com/64539970/80608828-5d1ef180-8a05-11ea-8d9b-9584b3b2ed29.PNG">

Are you able to add SAPCPMobileServices? I'm not able to continue with the tutorials without that destination. Thank you!

**Comment by sandeep-tds** [comment]
Hi @karicat7358, 

Thank you for raising the issue. 

The tutorial you are following can only be done in the Neo Environment of SAP Cloud Platform. 

To enable mobile services on Neo, please follow the steps mentioned under the [Neo Tab in this tutorial](https://developers.sap.com/tutorials/fiori-ios-hcpms-setup.html).

I hope this information proves to be helpful. 

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
