### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by mgmorey** [SAPDocuments/Tutorials#5053]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html

Step 1: Install Docker. Why are so few Linux distros tested? Ubuntu 17.04 is no longer supported by Canonical. It was supported for 9 months until January 2018. Which versions of openSUSE Leap have been tested?

Step 5: Edit the host sysctl.conf file. There is no rationale provided for this step. Why is this needed? And how is this at all practical, for example, when running in a cloud environment, such as Kubernetes? More documentation would be most helpful.

**Comment by xhit** [comment]
I installed in Ubuntu 18.04.4 LTS. When creating the container with command example:

```
docker run -p 39013:39013 -p 39017:39017 -p 39041-39045:39041-39045 -p 1128-1129:1128-1129 -p 59013-59014:59013-59014 -v /data/<directory_name>:/hana/mounts \
--ulimit nofile=1048576:1048576 \
--sysctl kernel.shmmax=1073741824 \
--sysctl net.ipv4.ip_local_port_range='40000 60999' \
--sysctl kernel.shmmni=524288 \
--sysctl kernel.shmall=8388608 \
--name <container_name> \
store/saplabs/hanaexpress:2.00.045.00.20200121.1 \
--passwords-url <file://<path_to_json_file> OR http/https://<url_to_json_file>> \
--agree-to-sap-license
```

It will fail creating tenant database, ignore the fail and do a `docker start <container_name>` and  tenant works in 39017 port. You can connect to databases for development.

I am not testing other stuff, but for databases you can test all, included connect remotely with eclipse.

**Comment by JCurrie27** [comment]
@mgmorey: Thanks for your questions -- I've forwarded them to our Docker team and will post their answers here. In the interim,  please log these questions on the HANA Express community Q&A page to take advantage of the community support model. The Q&A page receives much more traffic, and other Docker users may be able to provide answers immediately.

To log your questions on the Q&A page:

1. Go to [https://answers.sap.com/questions/ask.html](https://answers.sap.com/questions/ask.html)
2. Add a **Title**. Enter your GitHub question in the **Fill in the details...** field.
3. In **Select Primary Tag**, search for "express". Select **SAP HANA, express edition**.
4. Click **Submit your Question**.

Kind regards,

**Comment by toreluntang** [comment]
@JCurrie27 
> I've forwarded them to our Docker team and will post their answers here. 

Any updates? :)
