### ISSUE TITLE
Connect Using the SAP HANA Node.js Interface

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#5056]
Tutorial URL: https://developers.sap.com/tutorials/hana-clients-node.html

Please specify the step you are referring to 2

Feel free to close this ticket without updating the tutorial but i have found these instructions helpful in installing nodejs/npm on SUSE HANA Expresss XSA: https://github.com/nodejs/help/wiki/Installation#how-to-install-nodejs-via-binary-archive-on-linux

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
