### ISSUE TITLE
Map Message Structure

### ISSUE THREAD

**Issue by kharhou** [SAPDocuments/Tutorials#5057]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-convert-message-structure.html

Please specify the step you are referring to - Step 1: Add message mapping

Issue: Link broken to download the source and target message XSD.

**Comment by gauthamkrishna-sap** [comment]
Hello,
Thank you for your feedback. Can you please share a screenshot of what you see when you click on the link?
Best Regards, Gautham

**Comment by kharhou** [comment]
Hi,

It will show the link has expired. Attached screenshot.
![link_expired](https://user-images.githubusercontent.com/64568682/80695266-37c6dc00-8b08-11ea-843c-94909c84eaea.PNG)

Thanks.

**Comment by gauthamkrishna-sap** [comment]
Hi, I am a little confused here! 

From the screenshot, it looks like you are accessing some sharepoint link. Can you also please include the place where you click?

**Comment by kharhou** [comment]
Hi,

Sorry to confuse you, the link expired is from the Tutorial 5
- Step 1: Add message mapping - 'Source' and 'Target' link
- Step 4: Simulate mapping - 'Input Message' link

**Link highlighted in yellow in screenshot.

![image](https://user-images.githubusercontent.com/64568682/80697646-da348e80-8b0b-11ea-95fd-3f2f0c9e5a53.png)

![image](https://user-images.githubusercontent.com/64568682/80697774-0bad5a00-8b0c-11ea-93f9-f8fac5faeadb.png)

Thanks.

**Comment by gauthamkrishna-sap** [comment]
Hello,

Thank you for the feedback & apologies about the same. We will fix these links soon.

Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
