### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by KatsuoAshimine** [SAPDocuments/Tutorials#5058]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-behavior.html

Please specify the step you are referring to

--flow source be errord
METHODS get_features               FOR FEATURES IMPORTING keys REQUEST    requested_features FOR travel    RESULT result.

--error detail--
error is a part of "FOR travel"

error message is     
The property "features:instance" is not defined for "ZI_TRAVEL_M_AK1".	zcl_bp_i_travel_m_ak1 implementations.acinc	/TRL_EN/.adt/classlib/classes/zcl_bp_i_travel_m_ak1/zcl_bp_i_travel_m_ak1implementations.acinc	line 21	ABAP Syntax Check Problem

**Comment by mervey45** [comment]
Hi @KatsuoAshimine ,

this tutorial has been updated.
Pull request: #5062. 

Best regards, 
Merve

**Comment by KatsuoAshimine** [comment]
thenk you!
i can confirmed
