### ISSUE TITLE
SAP HANA XS Advanced, Creating a Node.js Module

### ISSUE THREAD

**Issue by vhsouza** [SAPDocuments/Tutorials#5065]
Tutorial URL: https://developers.sap.com/tutorials/xsa-xsjs-xsodata.html

Please specify the step you are referring to

Step 6 - Execute the xsjs module
I've been following all steps from Developers Tutorial to create a small XSA application, but when I try to start XSJS_CORE, I am getting the error below:
Running module /HANA_APP/core_xsjs failed. See console logs for more details. Cannot read property '_addUrlAsLink' of undefined

There are two posts about this very same error in SAP Forum, but without answer
https://answers.sap.com/questions/13013034/sap-hana-express-20-sps04-nodejs-xsjs-run-error-ad.html
https://answers.sap.com/questions/12945938/full-authentication-is-required-to-access-this-res.html

**Comment by vhsouza** [comment]
After lots of troubleshooting, I changed Node.js package.json file sections like below and it solved the problem

"devDependencies": { "@sap/xsjs-test": "^2.0.16" }

"engines": { "node": "8.x" }

**Comment by jung-thomas** [comment]
There are similar instructions in the tutorial:
please update the node version from 8.x to 10.x in the package.json. Also update the @sap/xsjs-test package to at least “^3.1.2”. For more details on this compatibility situation, see service note: https://launchpad.support.sap.com/#/notes/2905261

Are you saying that those versions did not work for you and you had to go back to these older versions?  If so what release of HANA/XSA/Web IDE are you running.  The tutorial was tested with the versions shown and described on HANA Express 2.0 SPS 04 and did work.

**Comment by vhsouza** [comment]
Hello Thomas,
Yes, I followed these instructions (at Step 3: Enable authentication in your service) but when I tried to start my node module I was getting the error mentioned above, so after comparing files with your video (SAP HANA Basics For Developers: Part 8.1 XSJS and XSODATA) I tried to use these old versions and it worked for me

Information about my system:

SAP WEB IDE Version:
SAP Web IDE for SAP HANA
Version: SAP Web IDE for HANA 2 SPS 04 Patch 0 ( Build 4.4.10 )

HANA Version: 2.00.040.00.1553674765 (fa/hana2sp04)
Platform: SUSE Linux Enterprise Server for SAP Applications 12 SP2
