### ISSUE TITLE
Enable SSO Between Azure AD and SAP Cloud Platform Using Identity Authentication Service

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#5066]
Mission URL: https://developers.sap.com/mission.cp-azure-ias-single-signon.html

I think, I can´t find this Tutorial on the Tutorial Navigator Page, right?

Regards

**Comment by thecodester** [comment]
@marcobuescher  Which tutorial? The mission link above works for me.

**Comment by marcobuescher** [comment]
ok, now it is there... thanks...
