### ISSUE TITLE
Display Data from the Northwind Service

### ISSUE THREAD

**Issue by jakes2255** [SAPDocuments/Tutorials#5067]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-fiori-cf-display-data.html

Please specify the step you are referring to: Step5
Destination empty array was not available in ui5.yaml file.
Had to manually add as below and then it worked:-
`- name: ui5-middleware-cfdestination
      afterMiddleware: compression
      configuration: 
        debug: true
        port: 1091
        xsappJson: approuter/xs-app.json
        destinations: `

Thanks,
Jakes

**Comment by IObert** [comment]
Hi,

I understand your confusion. The term "quota" refers to the service instance in this case (and not to the memory of your app runtime. The trial account only allows you to have two "destination service instances" in use at a time. You can fix the issue by [removing the services instances ](https://answers.sap.com/questions/12684501/error-while-running-sapui5-app-in-webide--service-.html)via the SCP cockpit.

See #3929

**Comment by IObert** [comment]
You are absolutely right, I had to take that part out because of issue SAP/generator-easy-ui5#32 until a dependency got fixed.

I'll bring this part of the template back in now.
