### ISSUE TITLE
Integrate Microsoft Azure AD with SAP Cloud Platform Cloud Foundry

### ISSUE THREAD

**Issue by colinjoy** [SAPDocuments/Tutorials#5068]
Tutorial URL: https://developers.sap.com/tutorials/cp-azure-ad-saml.html

> Step 1: Download metadata file from Cloud Foundry subaccount

Instead of manually piecing together the url for the saml metadata download, you can also navigate to "Security > Trust Configuration" and press the "SAML Metadata" action in the page header.

**Comment by maxstreifeneder** [comment]
Thanks Collin! Button wasn't there when I created the tutorial - will adjust it :-)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
