### ISSUE TITLE
Internationalize UI Strings

### ISSUE THREAD

**Issue by khaledpage** [SAPDocuments/Tutorials#5069]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-webide-update-internationalization.html

Please specify the step you are referring to

its not Wrking alle !, no effect on App page or deteile Page has been detected, only on home page  where title=Product Overview

**Comment by khaledpage** [comment]
i figure it out
i added
 title="{i18n>DetailTitle}"
to Deail view

**Comment by thecodester** [comment]
@khaledpage Good going :-)

@IObert FYI
