### ISSUE TITLE
Build and Deploy a Java Application

### ISSUE THREAD

**Issue by jukedbymom** [SAPDocuments/Tutorials#5070]
Tutorial URL: https://developers.sap.com/tutorials/cp-java-reference-app-deploy.html

Hi, on Step 5: Add the Retailer role,
I start the Java Application, and it stays in "starting" for a long time.
![image](https://user-images.githubusercontent.com/64496231/80864243-57314680-8c79-11ea-959b-556ace026482.png)
After that, the application fails due to APP_TIMEOUT
![image](https://user-images.githubusercontent.com/64496231/80864298-af684880-8c79-11ea-9d04-d7c4fdc6e23f.png)
And the URLs of said app show that it's temporarily down for maintence.
![image](https://user-images.githubusercontent.com/64496231/80864310-c018be80-8c79-11ea-9428-951849f97dfd.png)
I would like to know if this issue is because of some error I made, or if it's on Sap's end,
Thank you for the attention

**Comment by shankarigr** [comment]
Hi, 

Could you please try deploying it again and let me know what happens?
Because timeout could happen due to network issues also.

Also can you please let me know if you are using a trial or productive instance?

Thanks and Regards,
Shankari G R

**Comment by jukedbymom** [comment]
I'm using a trial version

**Comment by shankarigr** [comment]
Hi,

Thanks for the information.
Could you please try deploying it again and let me know what happens?

Because timeout could happen due to network issues also.

Thanks and Regards,
Shankari G R

**Comment by jukedbymom** [comment]
Hi, 
![image](https://user-images.githubusercontent.com/64496231/81167701-90292e00-8f8d-11ea-8f7f-0fc53db44b30.png)
I'm getting this problem now after trying to bind it again

**Comment by jukedbymom** [comment]
I've deployed the app, but it stays in "Starting", I'm waiting for the result but I'm afraid it will have teh same result

**Comment by jukedbymom** [comment]
![image](https://user-images.githubusercontent.com/64496231/81171482-5c053b80-8f94-11ea-837b-b8b01e345401.png)
Same error I had still persists

**Comment by shankarigr** [comment]
Hi,

I tested it from my side. I am able to deploy the application.
Can you please download the logs and send it to me?

Thanks and Regards,
Shankari G R

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
