### ISSUE TITLE
Unable to connect to ABAP Environment via ADT (Hana Studio)

### ISSUE THREAD

**Issue by rahulkapoor** [SAPDocuments/Tutorials#5071]
Hello,

With reference to the tutorial:
https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html

I am unable to perform Step 5, 'Create ABAP cloud Project' getting error as "_You were successfully authenticated, but an error occurred during the Service Instance logon. Please ensure that your user has the appropriate roles._", after importing/pasting service key in the HANA Studio.

Screenshot attached for reference too.
**Note**: ABAP service Instance in CF EU10 Canary is created with same admin email address with which I am trying to logon and have Admin/Org manager privileges in the CF EU10 (AWS) Canary sub-account. HANA studio has latest ADT too.

Kindly suggest what could be the issue here ?

Thanks
Rahul Kapoor

<img width="747" alt="Screen Shot 2020-05-03 at 2 17 59 AM" src="https://user-images.githubusercontent.com/1660525/80891858-65687c80-8ce4-11ea-8026-67a530623f21.png">

**Comment by mervey45** [comment]
Hi @rahulkapoor ,

please do not use the SAP Hana Studio. Please use following: https://tools.hana.ondemand.com/#abap. 

Procedure
To install the front-end component of ADT, proceed as follows:

Get an installation of Eclipse 2020-03 (e.g. Eclipse IDE for Java Developers)
In Eclipse, choose in the menu bar Help > Install New Software...
Enter the URL https://tools.hana.ondemand.com/latest
Press Enter to display the available features.
Select ABAP Development Tools and choose Next.
On the next wizard page, you get an overview of the features to be installed. Choose Next.
Confirm the license agreements and choose Finish to start the installation.


Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by CoderRahu1** [comment]
Hi @mervey45,

i tried everything installed latest adt and eclipse version but still its showing the same error.
whille creating instance even same mail as that of btp account was used still no idea why this is happening.

![image](https://github.com/user-attachments/assets/e0faa2b4-505b-4aee-bdef-1eddec2c0458)


and even after logon same error is seen

![image](https://github.com/user-attachments/assets/2f97dbde-b752-4276-9a09-11bab0c1a201)

i have tried everything even tried in another browser stuck with this for more than 30 days please do let me know if anything can be done.

Thanks.

**Comment by prabhatpathania** [comment]
Hi @CoderRahu1
Check this link:
[](https://help.sap.com/docs/btp/sap-business-technology-platform/assigning-abap-developer-user-to-abap-developer-role
)

Follow the steps and then you need to assign 'developer' role to your user.

![image](https://github.com/user-attachments/assets/abc88580-4dbc-40f6-ba60-f1c150ca19db)

**Comment by BishalGitHubs** [comment]
Unable to connect to ABAP Environment via ADT (Hana Studio) 
Error shown:  "Cannot connect to the Service Instance. The service is currently not available. "

**Comment by CoderRahu1** [comment]
> Unable to connect to ABAP Environment via ADT (Hana Studio) Error shown: "Cannot connect to the Service Instance. The service is currently not available. "

Create new trial account in different browser this time make sure only abap service is activated

**Comment by CoderRahu1** [comment]
> Hi [@CoderRahu1](https://github.com/CoderRahu1) Check this link: https://help.sap.com/docs/btp/sap-business-technology-platform/assigning-abap-developer-user-to-abap-developer-role
> 
> Follow the steps and then you need to assign 'developer' role to your user.
> 
> ![image](https://github.com/user-attachments/assets/abc88580-4dbc-40f6-ba60-f1c150ca19db)

thanks prabhat seems to be working , its that there is some issues with trial account at some points
