### ISSUE TITLE
Build a Shopping Fresh Fiori App in SAPUI5

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#5072]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-create-fioriapp.html

Please specify the step you are referring to

Step 3: Create SAP Fiori app

When I select the salesTrackerAPI I receive a popup asking for credentials. Even when adding my credentials it does not work. This was not covered in the tutorial. I did notice when looking at the policies it did say 'Base 64 encoded text required' but on the screenshots there had been one maintained. The tutorial did not actually say what we need to add here....so was confusing. 

If I could get some more information to finish this tutorial that would be appreciated. 

Thanks & Kind Regards
Phil Cooley

**Comment by shilpavij** [comment]
Dear Phil,

Are you getting pop-up at step 7? i am still not getting in my landscape. But this is your SSO the developer portal password.

Regards
Shilpa

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
