### ISSUE TITLE
Create an SAPUI5 App from the Command Line

### ISSUE THREAD

**Issue by mfdotta** [SAPDocuments/Tutorials#5073]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-sapui5-local.html

Please specify the step you are referring to 
Step 4: Package the MTA archive

Hi, 
It was not possible the *.mtar creation. Please, could anyone help me?

Thanks!
Dotta

[2020-05-03T10_20_34_048Z-debug.log](https://github.com/SAPDocuments/Tutorials/files/4570037/2020-05-03T10_20_34_048Z-debug.log)

**Comment by IObert** [comment]
I'm afraid the error log doesn't provide too much information. Can you run `npx mbt build` to check if you see a more detailed output?

As this is a Windows log, `make`  is usually the first suspect here. Did you already install this tool?

**Comment by IObert** [comment]
I'll close this one due to inactivity, please reopen if needed :)
