### ISSUE TITLE
Display Data from the Northwind Service

### ISSUE THREAD

**Issue by mfdotta** [SAPDocuments/Tutorials#5074]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-fiori-cf-display-data.html

Please specify the step you are referring to
Step 6: Display more product information on a detail page

Hi, 

What should I do? I got this message log:

Invalid value press="handleListItemPress"(UI5plugin) [8,45]

Thanks, 
Dotta

**Comment by IObert** [comment]
Can you provide more info please? Where do you see this error message, in the browser dev tools or somewhere else?
Did you complete step 6 (also the part where you'd this function to the controller)?

**Comment by IObert** [comment]
I'll close this one due to inactivity, please reopen if needed :)
