### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by mfdotta** [SAPDocuments/Tutorials#5075]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Please specify the step you are referring to Step 4: Define your first service

Hi, 

What should I do?
I could not see the log below and I got an page error when I click on http://localhost:4004
==============================================
[cds] - connect to db { database: ':memory:' }
/> successfully deployed to sqlite in-memory db

[cds] - serving CatalogService { at: '/catalog' }

[cds] - launched in: 696.753ms
[cds] - server listening on { url: 'http://localhost:4004' }
[ terminate with ^C ]
==============================================

Thanks, 
Dotta

**Comment by iwonahahn** [comment]
Thank you for your question. We have added in step 3.3 a new command _npm install_. Could you please test it again from the beginning and get back here? Thanks a lot.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
