### ISSUE TITLE
Create a Business Scenario for a Deployed Workflow

### ISSUE THREAD

**Issue by mfdotta** [SAPDocuments/Tutorials#5076]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-processvisibility-model-configscenario.html

Please specify the step you are referring to Step 2: Add workflows

Hi, 

How could I add ONBOARD if it doesn't appear?? Please, what should I do??

Thanks, 

Dotta

**Comment by Deeksha-R** [comment]
Kindly refer to the prerequisites. You need to have your workflows deployed on cloud foundry. Refer to the blog link.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
