### ISSUE TITLE
Reuse a CAP Java Service

### ISSUE THREAD

**Issue by jitendrakansal** [SAPDocuments/Tutorials#5077]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-service-reuse.html

Please specify the step you are referring to - step#6 

_To initialize the bookstore database with the defined domain model and sample data, run:_ **npm run deploy**

I get this error in terminal console (also screenshot attached).

user: bookstore $ npm run deploy
npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` opt
ion to include the path for the node binary npm was executed with.

> bookstore@1.0.0 deploy /home/user/projects/bookstore
> cds deploy

[ERROR] db/schema.cds:14:56-62: Artifact "sap.capire.bookstore.Books" has no element "author" (in entity:"sap.capire.bookstore.Authors"/element:"books")
[ERROR] db/schema.cds:4:49-71: Cannot find package module '@sap/capire-products'
[ERROR] srv/services.cds:16:33-55: Cannot find package module '@sap/capire-products'
[ERROR] srv/services.cds:5:65-73: Element or variable "category" has not been found (in entity:"BooksService.Books"/element:"genre")
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bookstore@1.0.0 deploy: `cds deploy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bookstore@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-05-03T17_15_12_983Z-debug.log
user: bookstore $ 

![image](https://user-images.githubusercontent.com/31536700/80920810-8bd4f900-8d72-11ea-9e15-3d59a4d22f8c.png)

I see some error message in "problems" tab, are these related to above issue? 
![image](https://user-images.githubusercontent.com/31536700/80920836-aeffa880-8d72-11ea-9b52-3ae653451c25.png)

**Comment by jitendrakansal** [comment]
Issue has been fixed by retrying the same step.

**Comment by muzeyr** [comment]
Hi,,how did you solve this question :)
