### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code - Step 4.3

### ISSUE THREAD

**Issue by bigld** [SAPDocuments/Tutorials#5078]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Please specify the step you are referring to: Step 4.3

change **db/schema.cds** to **srv/cat-service.cds**

Detail:
_"This means, cds watch detected the changes in db/schema.cds and automatically bootstrapped an in-memory SQLite database when restarting the server process."_

but this step is about  srv/cat-service.cds, there isn't any schema, yet.

**Comment by iwonahahn** [comment]
Thank your for your feedback. You are right and we have updated the [description](https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html#2c0dde4e-d05a-4952-8094-e142217cd1cd). We can close the issue.
