### ISSUE TITLE
Deploy SAP HANA, express edition

### ISSUE THREAD

**Issue by fatihkayan** [SAPDocuments/Tutorials#5082]
Tutorial URL: https://developers.sap.com/tutorials/gcp-hxe-evt-gke-2.html

getting an error @kubectl describe pods : 'unauthorized: incorrect username or password '
Please specify the step you are referring to

**Comment by jung-thomas** [comment]
Please refer to the previous tutorial in this series:
https://developers.sap.com/tutorials/gcp-hxe-evt-gke-1.html

Step 2 of this tutorial loads the credentials for kubectl:
https://developers.sap.com/tutorials/gcp-hxe-evt-gke-1/_jcr_content.github-proxy.1540820160.file/9.png

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
