### ISSUE TITLE
Maintain a Communication Arrangement for Inbound Communication

### ISSUE THREAD

**Issue by yutangc** [SAPDocuments/Tutorials#5084]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

Please specify the step you are referring to
Step 3: Create communication user

not found "Maintain Communication User"

**Comment by mervey45** [comment]
Hi @yutangc ,

which system are you using? If you are using the ABAP trial, then this won't work for you. The ABAP trial is restricted.

Best regards, 
Merve

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

@mervey45 Please make sure the tutorial indicates the need for license in the prerequisites.
