### ISSUE TITLE
Deploy Your Node.js App with the Cloud Foundry CLI

### ISSUE THREAD

**Issue by mfdotta** [SAPDocuments/Tutorials#5085]
Tutorial URL: https://developers.sap.com/tutorials/cp-node-deploy-cf-cli.html

Please specify the step you are referring to Step 2: Push the app to your SAP Cloud Platform Cloud Foundry space

Hi, 

I've tried to execute the command cf push manifest.yaml but I got this message:

Please, how could I know the space?
![cloud foundry message](https://user-images.githubusercontent.com/47184452/80988302-b1611180-8e09-11ea-9edb-a03cf8588911.jpg)

Thanks!

Best regards, 

Dotta

**Comment by maxstreifeneder** [comment]
hey @mfdotta,
please change your app name in the manifest.yaml. Somebody else is already using the app name and thus the route is already taken. But that shouldn't happen if you have set random_route to true. 

can you post a screenshot of your manifest.yaml? 

Thanks,
Max
