### ISSUE TITLE
Create ABAPDoc Comments in Your Class in ABAP Environment

### ISSUE THREAD

**Issue by foessleitnerj** [SAPDocuments/Tutorials#5086]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-create-abapdoc.html

Please specify the step you are referring to 

Step 6: Test yourself - I think "Method" is also right.

**Comment by julieplummer20** [comment]
Hi, I meant specifically using the object type, e.g. INTF. However, that is perhaps too obscure, so I will change the tutorial.
Thanks for your feedback,
Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
