### ISSUE TITLE
Add Managed Associations with Core Data Services

### ISSUE THREAD

**Issue by iMilazzo** [SAPDocuments/Tutorials#5087]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-foundation-01.html

Please specify the step you are referring to: 
Step 7: Build your db module and explore build results

There is a problem with the file db/package.json with have the following content:

{
	"name": "deploy",
	"dependencies": {
		"@sap/hdi-deploy": "3.3.0"
	},
	"scripts": {
		"postinstall": "node conditionalBuild.js",
		"start": "node node_modules/@sap/hdi-deploy/deploy.js"
	}
}

This line @sap/hdi-deploy": "3.3.0 can cause errors in some environments while BUILDing the project

**Comment by renejeglinsky** [comment]
Thank you @iMilazzo .

Please try 3^ as a value for @sap/hdi-deploy and let me know if this solves the build issue.

-René

**Comment by iMilazzo** [comment]
It worked !!! tyvm
