### ISSUE TITLE
Capture Streaming Output in the HANA Database

### ISSUE THREAD

**Issue by dritter2** [SAPDocuments/Tutorials#5088]
Tutorial URL: https://developers.sap.com/tutorials/sds-event-stream-tables.html

Please specify the step you are referring to

**Comment by dritter2** [comment]
Dear Team,

There is no option in Step 2 for Output Adapters, also nothing for Input Adapters.
I was following each steps of the guide.

Could you please assist with finding the misssing step.

Regards,
Daniel
d.ritter@sap.com

**Comment by RobWaywellSAP** [comment]
If no Input or Output adapters are showing in the Palette in HANA Studio, then that indicates that the installation of the Streaming plug in was not down with the appropriate Windows permissions. To resolve the issue you need to:

1) Start HANA Studio with "Run as administrator" permissions
2) Uninstall the Streaming Analytics plug in
3) Re-start HANA Studio, again with "Run as administrator" permissions
4) Re-install the Streaming Analytics plug in.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
