### ISSUE TITLE
Display Data from the Northwind Service

### ISSUE THREAD

**Issue by MartinStenzig** [SAPDocuments/Tutorials#5093]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-fiori-cf-display-data.html

In step 5, your instructions are to: "Replace the empty array of the property destinations in the ui5.yaml..." the problem is after I followed all the steps, my ui5.yaml looks as follows and does not contain a destinations array to begin with: 

specVersion: "2.0"
metadata:
  name: products
type: application
framework:
  name: SAPUI5
  version: 1.76.0
  libraries:
    - name: sap.ui.core
    - name: sap.m
    - name: sap.ui.layout
    - name: themelib_sap_fiori_3
server:
  customMiddleware:
    - name: ui5-middleware-livereload
      afterMiddleware: compression
      configuration:
        port: 35729
        path: webapp

**Comment by MartinStenzig** [comment]
I added this to the ui5.yaml to make it work. 

    - name: ui5-middleware-cfdestination
      afterMiddleware: compression
      configuration:
        debug: true
        port: 1091
        xsappJson: "approuter/xs-app.json"
        destinations:
        # check that the destination name (here: "backend") matches your router in xssppJson
        - name: "Northwind"
          url: "https://services.odata.org/"

**Comment by IObert** [comment]
You are absolutely right, I had to take that part out because of issue SAP/generator-easy-ui5#32 until a dependency got fixed.

I'll bring this part of the template back in now.
