### ISSUE TITLE
Create Authorization Model and App in SAP Cloud Platform ABAP Environment

### ISSUE THREAD

**Issue by P000834** [SAPDocuments/Tutorials#5098]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-authorization.html

Please specify the step you are referring to : Step 7

I am working on cloud development.
When I am trying to create restriction type it is giving me the attached error.
Kindly assist me on this.
![Restriction type](https://user-images.githubusercontent.com/64911516/81194876-c8a32900-8fda-11ea-9204-a8094326f656.PNG)

**Comment by mervey45** [comment]
Hi @P000834 ,

it seems, that your ADT is not up to date. Please ensure, that you are using the latest ADT. If you are trying this tutorial with the ABAP trial, then this will not work, because this tutorial is only for licensed systems. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
