### ISSUE TITLE
Map Message Structure: Attached file links are expired

### ISSUE THREAD

**Issue by asaidesita** [SAPDocuments/Tutorials#5100]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-convert-message-structure.html

Hello Experts,

The source and target file links are expired on the above URL.
Could you attach them again?

Kind Regards,

**Comment by gauthamkrishna-sap** [comment]
Hello,
Thank you for the feedback. We will update the links shortly. 
Best Regards,
Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
