### ISSUE TITLE
Enable the Push Notification service for your iOS app

### ISSUE THREAD

**Issue by flow23** [SAPDocuments/Tutorials#5106]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-hcpms-push-notifications.html

Hi,
I'm having issues with Step 6 Part 3.
I'm not getting the information of the registration of the device token did work or not. No feedback in the XCode debug window. After setting the breakpoint on line starting with "session.registerDeviceToken" I assume that this function doesn't get called. I deleted the app on the phone and I also deleted the "User Registration" in the mobile services. 
FYI, we use the neo environment and not CF.

Please advice.

Edit: I did the tutorial with my CF trial. Didn't work either.
Meanwhile I created an incident 311668 / 2020.

Best regards,
Florian

**Comment by KevinMuessig** [comment]
Hi Florian,

let me verify that the tutorial doesn't have anything missing. If not I probably need more details to help you find the issue. 

I will get back to you as soon as possible.

Thanks,
KM

**Comment by MichaelCzcz** [comment]
@KevinMuessig Any updates?

**Comment by KevinMuessig** [comment]
Hi @MichaelCzcz ,

I've verified and for me on MS and it works for me. Please check the box for **enable detailed event log** in the Mobile Push Notification feature. But when you generate the app with the SAP CP iOS Assistant the registration code should be generated as well and just work. 
Maybe you can try delete the app on your phone, re-deploy and try to onboard into the app new. Then go into Mobile Services and check the event logs for this app. You should find them on the main screen of MS.

<img width="1178" alt="Screen Shot 2020-07-24 at 11 14 47 AM" src="https://user-images.githubusercontent.com/9074514/88422361-fceae200-cd9e-11ea-9122-fca4e29931df.png">

If the error still occurs please continue with the ticket you've opened.

Thanks,

Kevin

**Comment by MichaelCzcz** [comment]
@flow23 Kindly try Kevin's suggestion.

**Comment by flow23** [comment]
Hi,
it only works for me if I'm using a custom IdP setup for the tenant.
It doesn't work for the default setup.
I don't know why to be honest.

Best regards,
Florian

**Comment by KevinMuessig** [comment]
Hi @flow23 ,

I don't know either. This might be something on the cloud side. Let me bring in additional help here.

Thanks,
Kevin

**Comment by flow23** [comment]
Hi @KevinMuessig ,
how was your tenant set up?
Did you configure the custom IdP beforehand?

Best regards,
Florian

**Comment by KevinMuessig** [comment]
Hi @flow23 ,

at this point I would like to refer you to the [SAP Community Q&A](https://answers.sap.com) where you can tag your question to have it appear in the appropriate section, and where others will also benefit from your question, and everyone from the answers you receive. This tutorials issues area is for problems with the tutorial content itself (typos, incorrect screenshots, and so on) rather than challenges you may face relating to specific or general runtime circumstances. 

I am more then happy to continue the problem solving there :)

Thanks!
