### ISSUE TITLE
Set Up the SAP HANA Plugin for Microsoft Visual Studio

### ISSUE THREAD

**Issue by specialword** [SAPDocuments/Tutorials#5109]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-visual-studio.html

Please specify the step you are referring to

In the Add Connection window, for Data source:, select SAP HANA Database (.NET Framework Data Provider for SAP HANA).

this selection of SAP HANA Database is NOT available. I did double click HDBCLIENT.exe to install HDB client and visual studio plug-in. 
however I don't how how to check/validate that the hana plug-in is installed successfully. I checked log file hdbinst_client.txt and could not find any evidence.

**Comment by specialword** [comment]
note 2588464 seems to be too old.

**Comment by JCurrie27** [comment]
Hi @specialword: Many thanks if you could log this VS plugin issue on the HANA Express community Q&A page to take advantage of the community support model. The Q&A page receives much more traffic than this page, and other users may be able to provide answers immediately.

To log your questions on the Q&A page:

1. Go to[ https://answers.sap.com/questions/ask.html]( https://answers.sap.com/questions/ask.html)
2. Add a **Title**. Enter your GitHub question in the **Fill in the details...** form.
3. In **Select Primary Tag**, search for "express". Select **SAP HANA, express edition**.
4. Click **Submit your Question**.

**Comment by specialword** [comment]
Hi John,
I just did. thank you.

https://answers.sap.com/questions/13045627/hana-plugin-is-not-available-in-hana-express-insta.html

George
