### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by ahmedkhan29789** [SAPDocuments/Tutorials#5110]
Tutorial URL: https://developers.sap.com/tutorials/xsa-create-user-provided-anonymous-service.html

This is a great tutorial,
I have some similar requirement but fits in this tutorial Kindly help me.

I have a container in one space and i want to access the objects of another container which is in different space
When I try to create an SAP HANA SERVICE CONNECTION on my db module i dont find that hdi container since it is in different space, can you give me any suggestion how can I add other space container as a service in my hdi container.

**Comment by jung-thomas** [comment]
First. Please only use this forum to directly discuss problems with the tutorial content itself or its execution. For additional questions just related to the same topics, you should use the SAP Community Q&A. 
For more details on your specific questions please refer to this best practice guide (section 5.2.2): https://www.sap.com/documents/2018/04/fe086f0d-fa7c-0010-87a3-c30de2ffd8ff.html

And please ask any follow up questions via the SAP Community Q&A.
