### ISSUE TITLE
Connect Using the SAP HANA Python Interface

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#5112]
Tutorial URL: https://developers.sap.com/tutorials/hana-clients-python.html

Please specify the step you are referring to 3.3

it only worked when sending the password 'in the clear' and running this command in the shell:
'python3 pythonQuery.py' 
for me, but https://blogs.sap.com/2020/05/07/secure-connection-from-python-to-sap-hana/ was more helpful than the official notes 2499500 and 2403606 when troubleshooting. 
the py client seems to be just a wrapper to the regular hdbcli interface.

**Comment by danielva** [comment]
In this tutorial, the password is retrieved from the secure user store as documented in the [security guide](https://help.sap.com/viewer/b3ee5778bc2e4a089d3299b82ec762a7/2.0.04/en-US/dd95ac9dbb571014a7d7f0234d762fdb.html).

I am glad that the blog post was helpful.  I will look into adding a link to it from this tutorial.  

If you are having an issue with a problem not directly related to this tutorial, I would recommend opening a ticket with support or posting a question at (answers.sap.com)[https://answers.sap.com/tags/73554900100700000996].

Regards,
Dan van Leeuwen

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
