### ISSUE TITLE
Install the Optional SAP HANA Smart Data Integration Package for SAP HANA, express edition (Preconfigured VM)

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Tutorials#5114]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-sdi-vm.html

Please specify the step you are referring to:

We just spun up a new AWS HANA Express instance.   
hxeadm@hxehost:/usr/sap/HXE/HDB90> HDB -version
HDB version info:
  version:             2.00.040.00.1553674765
  branch:              fa/hana2sp04
  machine config:      linuxx86_64
  git hash:            c8210ee40a82860643f1874a2bf4ffb67a7b2add
  git merge time:      2019-03-27 09:19:25
  weekstone:           0000.00.0
  cloud edition:       0000.00.00
  compile date:        2019-03-27 09:30:26
  compile host:        ld4551
  compile type:        rel

We had to update the HXEDownloadManager.  We then downloaded the sdi.tgz file via:
ec2-user@hxehost:/usr/sap/HXE/HDB90> sudo ./HXEDownloadManager_linux.bin linuxx86_64 installer sdi.tgz
which: no java in (/usr/sbin:/usr/bin:/sbin:/bin)
which: no java in (/usr/sbin:/usr/bin:/sbin:/bin)
Connecting to download server...

SAP HANA, express edition version: 2.00.045.00.20200121.1

Downloading "SAP HANA smart data integration"...
sdi.tgz : 100%
Concatenate download files to /home/ec2-user/sdi.tgz...
/home/ec2-user/sdi.tgz created.
Verify /home/ec2-user/sdi.tgz file checksum...
/home/ec2-user/sdi.tgz file checksum is OK.

But then when we try to install this, then we got this error:
hxeadm@hxehost:/usr/sap/HXE/HDB90> ./HANA_EXPRESS_20/install_sdi.sh
Cannot install SAP HANA smart data integration.  This SAP HANA smart data integration version is not compatible with your installed HANA, express edition version.

So it seems like the sdi.tgz that the latest HANA Download manager installs is not compatible with the newest HANA Express on AWS.  How can we download the correct sdi.tgz for our AWS HANA Express 2.00.045.00.20200121.1?

Thanks,
Jay

**Comment by JCurrie27** [comment]
Hi @jmalla: There may be an answer to this on sdi.tgz issue on the Q&A page. Many thanks if you could log these questions on the HANA Express community Q&A page to take advantage of the community support model. The Q&A page receives much more traffic than this page, and other users may be able to provide answers immediately.

To log your questions on the Q&A page:

1. Go to [https://answers.sap.com/questions/ask.html](https://answers.sap.com/questions/ask.html)
2. Add a **Title**. Enter your GitHub question in the **Fill in the details...** form.
3. In **Select Primary Tag**, search for "express". Select **SAP HANA, express edition**.
4. Click **Submit your Question**.

Best,

**Comment by jmalla** [comment]
Doesn't SAP support the HANA Express product anymore?  It looks like they released the new version of HANA Express 2 SPS 4 without checking whether the SDI installation works.  Not very thorough regression testing on the part of SAP.

**Comment by jmalla** [comment]
I don't think this issue should be closed - because no one can do the SDI tutorials on the new HANA Express without installation SDI first.

**Comment by JCurrie27** [comment]
Hi @jmalla: HANA Express uses a Community Support model; I'm closing the issue in this repository, but it will remain open in the community support Q&A page until your installation problem is resolved.
Thanks for logging your issue on the Q&A page -- I see you've had a response already with some suggestions.
