### ISSUE TITLE
Deploy the Fiori App to Cloud Foundry

### ISSUE THREAD

**Issue by iMilazzo** [SAPDocuments/Tutorials#5115]
Tutorial URL: [https://developers.sap.com/tutorials/sapui5-fiori-cf-deploy.html](https://developers.sap.com/tutorials/sapui5-fiori-cf-deploy.html)

Please specify the step you are referring to **Step 1: Build the project**

In this step I'm able to create do MTAR file Project.0.0.1.mtar but if i use the command CF DMOL I can see the logs and there are issues in some components :

> #2.0#2020 05 08 17:02:37.569#Z#ERROR#com.sap.cloud.lm.sl.xs2.541605c7-914d-11ea-b701-eeee0a84db76.OPERATION.executeTaskTask#
######com.sap.cloud.lm.sl.cf.persistence.services.ProcessLogger########flowable-async-job-executor-thread-28###
[ExecuteTaskStep] Execution of task "deploy" on application "products_launchpad_deployer" failed.
Download the application logs via the dmol command and check them for more information.#

In this case, I've looked into the products_launchpad_deployer.log file, there no ERROR messages in this file !!!

Can you help me plz?

Thanks
Ivan

**Comment by IObert** [comment]
It sounds like the same problem you described in the other issue (dmol log doesn't show crash log). Can you please confirm that this is a duplicate?
