### ISSUE TITLE
Enable SAP Cloud Platform Open Connectors

### ISSUE THREAD

**Issue by MKatsu** [SAPDocuments/Tutorials#5116]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-openconnectors-enable.html
Step 3: Access Open Connectors home page

After I click on "Go to Application", it goes to the next screen where it says "No authorized user found. Please contact your administrator to obtain access"

I have created a role collection that contains;
OpenConnectors_Administrator,OpenConnectors_DevOps,OpenConnectors_Support

but still get the same error message.

**Comment by shilpavij** [comment]
Dear Colleagues,
It is self onboarding in trial and hence you do not need any roles. Now I guess that your onboarding has some problem so kindly use another email and trial account.

Regards
Shilpa

**Comment by MKatsu** [comment]
Hi Shilpa,

I tried with three different trial accounts and got the same error.
This was never the case the first time using the trial account. It only
happened since the second time creating a trial account after 90 days
period is over.
Can you please check to see if a newly created trial account can access
Open Connector?

Regards,
Motoki

2020年5月11日(月) 12:03 Shilpa Vij <notifications@github.com>:

**Comment by shilpavij** [comment]
Hello Team,

Yes, there is an issue with new users on trial. We are fixing it.

Regards
Shilpa

**Comment by thecodester** [comment]
@shilpavij Any update on if/when the issue will be resolved?

**Comment by shilpavij** [comment]
Hello,
It should be done by 12th June.

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
@shilpavij is this solved? Can I close this issue?

**Comment by shilpavij** [comment]
Yes, please its solved

**Comment by vinibiscolla** [comment]
Hello there i'm facing the same issue, but in my case is not a free instance is a pay-as-you-go-for-partners license, i have the same situation, i've created the instance of Integration Suite, added capabilites Extend Non-SAP Connectivity in the Integration Suite panel and when i click discover connectors or create connectors i got an xml error: 

<SobaMap>
<requestId>667d6e9ae4b0e444f71b7746</requestId>
<message>No authorized user found. Please contact your administrator to obtain access</message>
</SobaMap>

and already added all the user roles possible for the integration suite in my own user which is also the administrator of SAP BTP and not being able to access Open Connector instance.

**Comment by dennisrihm** [comment]
@vinibiscolla I experience the same issue.
