### ISSUE TITLE
Add a Model and Test the SAPUI5 App

### ISSUE THREAD

**Issue by vijayredd19** [SAPDocuments/Tutorials#5117]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-webide-setup-datasource.html

Step 4 & 5:  I am facing $metadaa missing issue even after maintaining the service URL with /destinations/ in both neo-app.json and manifest.json files.

I am attaching screenshots of my code from web IDE and error screen shots.

Please could you please guide me as I really stuck and not able to progress for the last 2 days. Thank you. 
![Console Error_after maintaing destinations](https://user-images.githubusercontent.com/65125161/81504558-f1c8ff80-92e1-11ea-9d5d-d72f7946b88e.jpg)
![Console Error_before maintaining destinations](https://user-images.githubusercontent.com/65125161/81504559-f2619600-92e1-11ea-879b-1ab49d620349.jpg)
![manifest_json](https://user-images.githubusercontent.com/65125161/81504560-f2fa2c80-92e1-11ea-9ddf-5437f59e8a14.png)
![neo_app](https://user-images.githubusercontent.com/65125161/81504563-f392c300-92e1-11ea-8e3f-9e8b185ff362.png)

URL before maintaining /destinations/
https://xxxxxxxxxxxxxx-app-approuter.cfapps.eu10.hana.ondemand.com/sapcpcftutorialapp-1.0.0/northwind/V2/Northwind/Northwind.svc/$metadata?sap-language=EN

URL after maintaining /destinations/
https://abcabcabcabc-app-approuter.cfapps.eu10.hana.ondemand.com/sapcpcftutorialapp-1.0.0/destinations/northwind/V2/Northwind/Northwind.svc/$metadata?sap-language=EN

**Comment by IObert** [comment]
Hi,

the neo-app.json file is only used for deployment to Neo. Can you check if the destination is also referred to in the xs-app.json file (this is the configuration for the CF approuter).

Another reason could be that the destination you use is only defined in the Neo environment but not in the CF environment of the cockpit.

**Comment by radusimen** [comment]
Have you set the destination properties WebIDEEnabled=true and WebIDEUsage=odata_gen ?

**Comment by IObert** [comment]
I'll close this one due to inactivity, please reopen if needed :)
