### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by lalit74u** [SAPDocuments/Tutorials#5119]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html

Please specify the step you are referring to

Dear Team, i got following error in Step 8. Please advise. i have completed all other steps successfully mentioned in above tutorial.

error code 500
javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, cause: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Thanks,
Lalit

**Comment by xRicardinhox** [comment]
Hello. 
I have the same issue.

did they find any solution?

**Comment by gauthamkrishna-sap** [comment]
Hello,
Can you please try importing the certificates into the Cloud Integration keystore? You can access the keystore in the **Monitor** section.
Thanks,
Gautham
