### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by iMilazzo** [SAPDocuments/Tutorials#5120]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

Please specify the step you are referring to **Step 3: Deploy using cf push**

In this substep states:
2. Now, build and deploy both the database part and the actual application and add: 

```
SET CDS_ENV production && cds build
cf push -f gen/db
cf push -f gen/srv --random-route
```

I'm unable to run this command, I think there is a CR+LF instead a  "&&" which meand there is 4 command instead 3.
The 2nd line doesn't work because there is no "gen/db" in my project, am I missing somthing ??

Thanks
Ivan

**Comment by iwonahahn** [comment]
Hi Ivan,

We have check again the code samples and there was a missing "=". The correct code is:

`SET CDS_ENV=production && cds build`
`cf push -f gen/db`
`cf push -f gen/srv --random-route`

We will fix this in our tutorial asap. Sorry for the inconvenience. Please let me know if it works now.

Thank you and best regards,
Iwona

**Comment by iMilazzo** [comment]
1st, I'm sorry for the delay in my feedback !!!

Well, it worked !!!! But now I need to understand what this command really did because I though that was creating a environment variable but it seems that it is doing something else becasue I had a big output like this command as running something else.
I assume that the "&&" it just doing 2 command in one line "set this variable and than run cds...".

Thank you
Ivan

**Comment by iwonahahn** [comment]
Hi Ivan,

Thank you for your quick response. Now the [tutorial](https://developers.sap.com/tutorials/cap-service-deploy.html#e282e8aa-fe28-492f-a22a-02839132943b) is also up to date online. Yes with `&&`you can combine commands. I can also recommend the ongoing [openSAP course](https://open.sap.com/courses/cp7) for CAP for more details and demos. Can we close this issue here?

Best regards,
Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
