### ISSUE TITLE
Testing API Business Hub APIs with Curl

### ISSUE THREAD

**Issue by Marrryy** [SAPDocuments/Tutorials#5121]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-test-locally.html

//Please specify the step you are referring to
Step 5: Add multiple parameters to the API call

I did the command this : 

curl --request GET  --url "https://sandbox.api.sap.com/successfactors/odata/v2/User?%24top=5&%24select=firstName%2ClastName%2CjobTitle"  --header "APIKey: <API KEY>"  --header "Accept: application/json"  --header "Content-Type: application/json"

getting results =
{
"d" : {
"results" : [
{
"__metadata" : {
"uri" : "https://sandbox.api.sap.com/successfactors/odata/v2/User('6584e7f9-9fab-4b31-ade1-357291c74f1d')", "type" : "SFOData.User"
}, "firstName" : "Amy", "lastName" : "Craig", "jobTitle" : null
}, {
"__metadata" : {
"uri" : "https://sandbox.api.sap.com/successfactors/odata/v2/User('extuser1')", "type" : "SFOData.User"
}, "firstName" : "╨ÿ╨▓╨░╨╜ ", "lastName" : "╨É╨║╤ü╨╡╨╜╨╛╨▓ ", "jobTitle" : null
}, {
"__metadata" : {
"uri" : "https://sandbox.api.sap.com/successfactors/odata/v2/User('50004')", "type" : "SFOData.User"
}, "firstName" : "Sami", "lastName" : "Ibrahim", "jobTitle" : null
}, {
"__metadata" : {
"uri" : "https://sandbox.api.sap.com/successfactors/odata/v2/User('15885825643')", "type" : "SFOData.User"
}, "firstName" : "Runscope1", "lastName" : "Alan1", "jobTitle" : null
}, {
"__metadata" : {
"uri" : "https://sandbox.api.sap.com/successfactors/odata/v2/User('15782875893')", "type" : "SFOData.User"
}, "firstName" : null, "lastName" : null, "jobTitle" : null
}
]
}
}

Submit answer (try)=
-"firstName" : "Amy", "lastName" : "Craig", "jobTitle" : null
- "Amy", "Craig", null
- Amy, Craig, null
- Amy Craig null

Still didn't get correct answer

**Comment by IObert** [comment]
You are right, this validation is not very resilient to changing orders of the entities. I updated the entire tutorial and adapted the validation question. In the new one, we're actually not checking for the names but for the format of the response in this validation.

**Comment by IObert** [comment]
Can you please test again once the new validation is live (within the next 10 min)

**Comment by Marrryy** [comment]
Thank you so much for replying and fixing, it's already works! :))
