### ISSUE TITLE
SAP hana express installation

### ISSUE THREAD

**Issue by buongiorno999** [SAPDocuments/Tutorials#5128]
Dear Lucia
I am asking for your help as I have spent a lot of time and many trials to install SAP Hana express 2 SP04.

I cannot login via XSA_DEV.  it looks like this user does not exist.

I have checked the installation:
$./hdblcm -–action=check_installation
No issue

$xs apps
all the required apps are running

When I try to login in webide via XSA_ADMIN
"You are not authorized to access SAP WEB IDE
Ask you admin to assign you to the SAP web ide SAP WEBIDE_DEVELOPER role"

What I have done so far:
I have untared 
$tar -zxvf apl.tgz
$tar -zxvf hxe.tgz
$tar -zxvf hxexsa.tgz 
$tar -zxvf hsa.tgz
$tar -zxvf eml.tgz
$tar -zxvf shine.tgz
$./hdblcmgui
The installation ran until the end
I checked all log files
/var/tmp/hdb_HXE_hdblcm_install_2020-05-11_07.44.54/hdbinst.msg
/var/tmp/hdb_HXE_hdblcm_install_2020-05-11_07.44.54/hdbinst_afl.msg
/var/tmp/hdb_HXE_hdblcm_install_2020-05-11_07.44.54/hdbinst_eml.msg
/var/tmp/hdb_HXE_hdblcm_install_2020-05-11_07.44.54/hdbinst_epmmds.msg
/var/tmp/hdb_HXE_hdblcm_install_2020-05-11_07.44.54/hdbinst_sap_afl_sdk_apl.msg
/var/tmp/hdb_client_2020-05-11_07.54.38_22103/hdbinst_client.msg
/var/tmp/hdb_HXE_hdblcm_install_2020-05-11_07.44.54/hsainst.log
/var/tmp/hdb_HXE_hdblcm_install_2020-05-11_07.44.54/hdbinst_xs.log
No Issues
except in
xs_install_components.log (see attached)

Many errors and I could not find any notes on them.

Thanks for your help.
if you could lead me in the right direction

[xs_install_components.log](https://github.com/SAPDocuments/Tutorials/files/4610015/xs_install_components.log)

**Comment by jung-thomas** [comment]
This issue area is for specific items to do directly with tutorials. For general support of HANA Express, you really must post your questions on the SAP Community Q&A in the SAP HANA, express edition tag: https://answers.sap.com/tags/73555000100800000651
