### ISSUE TITLE
Create additional CDS entities and a view

### ISSUE THREAD

**Issue by iMilazzo** [SAPDocuments/Tutorials#5130]
Tutorial URL: https://developers.sap.com/tutorials/xsa-e2e-cds-new.html

Please specify the step you are referring to **Step 1: Create a new CDS artifact**

The 1st line of this tutorial says "Back in the development perspective..."
I think it assume that I have made other tutorial before I start this one.
Can you link which tutorial is this ???

Thanks
Ivan

**Comment by jung-thomas** [comment]
This tutorial was originally used at SAPPHIRE 2018 in the App Space.  The overall structure was part of the experience at this space. However now only a sub set of the original tutorials remain.
