### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Tutorials#5132]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

Please specify the step you are referring to

Step 3: SET CDS_ENV production && cds build in not working. I am getting this error "Environment variable CDS_ENV production not defined".

**Comment by iwonahahn** [comment]
Hi,
Thank you for the issue. Please look at the answer in this [issue](https://github.com/SAPDocuments/Tutorials/issues/5120). We have fixed the code snippets yesterday. You should use:

'SET CDS_ENV=production && cds build'
'cf push -f gen/db'
'cf push -f gen/srv --random-route'

Please retest and get back to us.
Best regards,
Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
