### ISSUE TITLE
Debug Your SAPUI5 App with SAP Web IDE

### ISSUE THREAD

**Issue by alteraugem** [SAPDocuments/Tutorials#5133]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-webide-debug.html

Please specify the step you are referring to: Step 3 Java Script snippet:
The advice to **replace** lines #2 and 3 with the snippet is not correct because line #2 contains the definition of the "sap/ui/core/mvc/Controller" which is essential. Either the definition of the controller must be part of the replacement script or the description of what has to be done has to be adjusted.

**Comment by IObert** [comment]
You are right, I should have stated that the comma needs to be appended at the end of line 2.
We'll roll out a new code line highlighting feature today which can be used to be more precise in the description.

Thanks for the feedback!

**Comment by IObert** [comment]
Fixed in #5140, please close if you think this resolved the problem

**Comment by alteraugem** [comment]
okay
