### ISSUE TITLE
Use SAP Web IDE OData Features to Create a Simple App

### ISSUE THREAD

**Issue by alteraugem** [SAPDocuments/Tutorials#5139]
Tutorial URL: https://developers.sap.com/tutorials/odata-03-webide-odata-features.html

Please specify the step you are referring to: 
Step 7:
The created folder is called "mta_ProductData", the context menu has changed to "Open Layout Editor" or "Open Code Editor", e.g "open with" is obsolete.

Step 8: same as above
Also it should be mentioned that the preceding statement '"preload": true' has to be finalized with a comma!

Step 9:
The behaviour of the Table Control has changed, new GET requests are automatically generated when a user scrolls the page (no "More" button)

**Comment by qmacro** [comment]
Hey @alteraugem thanks so much for such detailed attention - it's definitely something that appeals to me :-)

I've updated the screenshots for the "open with" issues, but also updated the screenshot in step 2 to reflect the (relatively) new specific choice of environments. With the `mta_ProductData` I'm suspecting that the default environment in the wizard for you was Cloud Foundry, which would have resulted in the other differences you see. 

There is a plan to update content for Cloud Foundry, but as you can imagine that's a large task and for now I thought it prudent to at least update this tutorial to make it consistent again. 

Appreciate the detailed report, thanks again!
