### ISSUE TITLE
Create a Neo Destination for the SAP Gateway Demo System

### ISSUE THREAD

**Issue by alteraugem** [SAPDocuments/Tutorials#5141]
Tutorial URL: https://developers.sap.com/tutorials/teched-2016-3.html

Please specify the step you are referring to; Step 5

The values for WebIDEUsage should be specified especially because the help page says: "Caution
Enter either the odata_abap value or the odata_gen value. Do not use both values at the same time." but both values are provided in the screenshot

**Comment by alteraugem** [comment]
I just saw, that values are provided, however these include odata_gen **and** odata_abap which contradicts the statement on the help page. I think this should be clarified internaly at SAP and at least be mentioned here.

**Comment by IObert** [comment]
You are right, it's not necessary to use both values. I fixed the tutorial, thanks for reporting this one!
