### ISSUE TITLE
View the SAP Cloud Platform from 10,000 Meters

### ISSUE THREAD

**Issue by harley-bernie** [SAPDocuments/Tutorials#5144]
Tutorial URL: https://developers.sap.com/tutorials/cp-explore-cloud-platform.html

Excellent overview!
Perhaps the (philosophical) question remains open: what is a cloud?

Cheers, Bernd

**Comment by IObert** [comment]
Thanks for the feedback :)
I agree that this question would turn philosophical very fast. I think the term cloud is quite overloaded and the term IaaS, PaaS, and SaaS try to differentiate it a little bit more (not that I'm saying these terms are very precise).
So I'd like to turn the table: What is a cloud for you? :)

**Comment by IObert** [comment]
I'll close this one due to inactivity, please reopen if needed :)
