### ISSUE TITLE
unable to find CI/CD Best Pactices Doc for XSC in Tutorials

### ISSUE THREAD

**Issue by kartiksap481** [SAPDocuments/Tutorials#5145]
HI Team,

I have previously accessed below link and found best practices architecture and configuration for CI/CD for xsc hana.

now when i have logged to below url, i am unable to see and throwing error, please let me know repo has been changed. it is very important for us.

https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/ci-best-practices-xsc/ci-best-practices-xsc.md

**Comment by thecodester** [comment]
All of that material is located here now: https://help.sap.com/viewer/8cacec64ed854b2a88e9a0973e0f97a2/Cloud/en-US/e9fa320181124fa9808d4446a1bf69dd.html (this link also redirects https://developers.sap.com/group.ci-best-practices.html).

The one you referenced is at http://developers.sap.com/tutorials/ci-best-practices-xsc.html.

I would bookmark the new URLs, not sure how long the redirects will work.

Is that what you need?

**Comment by thecodester** [comment]
I will close the issue. If you need more help, let me know.

**Comment by kartiksap481** [comment]
Sure Daniel please close

**Comment by kartiksap481** [comment]
@thecodester we are able to perform few steps as per above git link, but we are unable to go ahead with Maven and Nexus configuration with HANA which involves pom.xml file creation. can i please get contact of person who created this. when we have reached SAP support team, they are saying that this is not sap standardized configuration and they can not support this. do we have any other option to get support for above configuration to automate Native HANA Transport configuration.
