### ISSUE TITLE
Maintain a Communication Arrangement for Inbound Communication

### ISSUE THREAD

**Issue by bask-alur-gh** [SAPDocuments/Tutorials#5146]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

Step3 doesn't show these tiles in the screenshot for my ID, shows only 'SQL Explain', 'SQL Trace', and 'Install additional software' tiles.  At the top in the prerequisites it says "You have the business catalog communication management (SAP_CORE_BC_COM) assigned to your business user.", not sure if this is the issue.  Any steps to resolve this would be appreciated.  Thanks.

**Comment by mervey45** [comment]
Hi @bask-alur-gh ,

which system are you using? If you are using the ABAP trial, then this won't work. This is a licensed tutorial.

Best regards, 
Merve

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
