### ISSUE TITLE
Set Up Process Visibility to Track Employee Onboarding Workflow

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Tutorials#5148]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-4-visibility.html

In Step 1 in screenshot the tile is configure business scenario but in app showing configure Visibility scenario

**Comment by ArchanaShukla** [comment]
This is expected. That is coming from the product itself and how the the tiles have been recommended to be configured. Will request the product documentation to be changed appropriately.

**Comment by ArchanaShukla** [comment]
I have been confirmed by the dev team that this is fixed. If you re-deploy the BPMServicesFLP then the issue would not be there any more. @MichaelCzcz  - Please close the ticket

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
