### ISSUE TITLE
Prepare the Portal Environment for Creating Sites

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5151]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Step 3.4

Change the screenshot for the above step mentioned.
Expected Result : 
![image](https://user-images.githubusercontent.com/50734023/81929234-4e8b2980-9604-11ea-976f-f87b96b57960.png)

Actual result : 
![image](https://user-images.githubusercontent.com/50734023/81929460-aa55b280-9604-11ea-90f3-834d9d92ac05.png)

Regards,
Nidhi

**Comment by IrisSasson** [comment]
Hi, 
Thanks for the comment, we updated the tutorial

Iris

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
