### ISSUE TITLE
Integrate a URL App into Your Portal Site

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5154]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-url-app.html

Step 3.1
Change the screenshot
Expected
![image](https://user-images.githubusercontent.com/50734023/81931220-60ba9700-9607-11ea-8319-5b00fba2a7b3.png)

Actual : Also there are three option in the left panel.
![image](https://user-images.githubusercontent.com/50734023/81931607-0110bb80-9608-11ea-8e1e-00130b5cb1a9.png)

Step 7
Change the screenshot

Expected
![image](https://user-images.githubusercontent.com/50734023/81931687-200f4d80-9608-11ea-9536-1af01a3025f9.png)

Actual : There are two tabs, Home and My Apps
![image](https://user-images.githubusercontent.com/50734023/81931770-3ddcb280-9608-11ea-9b32-6a991870cfa5.png)

Regards,
Nidhi

**Comment by IrisSasson** [comment]
Hi, 
Thanks for the comments, we updated the tutorial accordingly
Iris.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
