### ISSUE TITLE
Set Up Business Process Management Services in Cloud Cockpit

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5157]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html

Step 9.3
Change the screenshot
Expected:
![image](https://user-images.githubusercontent.com/50734023/81947038-b601a300-961d-11ea-8f9c-067356a69a33.png)

Actual : There a filter option
![image](https://user-images.githubusercontent.com/50734023/81947136-d598cb80-961d-11ea-8941-2b56f65c1050.png)

Regards,
Nidhi

**Comment by ArchanaShukla** [comment]
In discussion with the product team, this feature was not suppose to be rolled out. I will change the screenshot accordingly

**Comment by ArchanaShukla** [comment]
I have updated the screenshots.
@MichaelCzcz  - please close this issue

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
