### ISSUE TITLE
Welcome Card not downloaded automatically in Mobile cards client

### ISSUE THREAD

**Issue by priyankars2210** [SAPDocuments/Tutorials#5158]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html

Please specify the step you are referring to: Step 4: View the Welcome Card in Mobile Cards client

Issue:
Here it is given that "Welcome cards are auto subscribed by default and downloaded automatically after registration." 
But sometimes the app will not be auto downloaded and we have to reload the mobile card client for the Welcome card to be visible.
So from a end user perspective, please add a line in the tutorial that if the card is not visible automatically then we have to reload the Mobile card client.

Regards,
Priyanka

**Comment by sandeep-tds** [comment]
Hi @priyankars2210,

Thank you so much for raising this concern.
Can you please elaborate on the following statement you made in your comment:

> But sometimes the app will not be auto downloaded and **we have to reload the mobile card client** for the Welcome card to be visible

Did you do a pull-refresh or did you unsubscribe and subscribe?

Thank you for providing additional information. 

Warm Regards
Sandeep T D S

**Comment by priyankars2210** [comment]
Hi Sandeep,

I had to do a pull refresh for the card to be visible.
But in the document it is said that the card would be auto downloaded. So from an end user perspective that means that we should be able to see the card without doing a pull request.
Hope this helps...

Regards,
Priyanka

**Comment by sandeep-tds** [comment]
Hi Priyanka, 

Thank you so much for providing the details; your feedback is very helpful.

We will address the same in our documentation.

Warm Regards
Sandeep T D S

**Comment by thecodester** [comment]
@sandeep-tds Is this something that has to be updated in the tutorial?

- If yes, please update.
- if no, I can close the issue.

**Comment by sandeep-tds** [comment]
Hi @thecodester, 

I have made the changes and will be submitting the Pull Request along with other changes tomorrow.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
