### ISSUE TITLE
Set Up Business Rules for Determining Equipment

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5159]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-businessrules.html

Step 2.3
Change the screenshot
Expected:
![image](https://user-images.githubusercontent.com/50734023/81947555-53f56d80-961e-11ea-90d2-ee9de2f28d18.png)

Actual :
![image](https://user-images.githubusercontent.com/50734023/81947606-61125c80-961e-11ea-9228-0512457c55d1.png)

Regards,
Nidhi

**Comment by ArchanaShukla** [comment]
In discussion with the product team, this feature was not suppose to be rolled out. I will change the screenshot accordingly

**Comment by ArchanaShukla** [comment]
I have updated the screenshots.
@MichaelCzcz  - please close this issue

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
