### ISSUE TITLE
Issue while cross verifying status update in the back end

### ISSUE THREAD

**Issue by priyankars2210** [SAPDocuments/Tutorials#5160]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-action.html

Please specify the step you are referring to: Step 8: Cross verify status update in the back end

Issue:
Here in this tutorial. we are performing the Approve and Reject operation both on the same sales order. 
But at the last when we verify the status in the backend, only one status that is either approved or rejected is shown for that particular sales order. This is correct as at once only one status is available for a sales order.
But the screenshot at the end of the tutorial shows the status for 2 different sales orders, this causes a little confusion.
So from an end user perspective, please add a line in the tutorial that the screenshot shows the status for 2 different sales orders and at once one sales order can only have one status.

Thanks & Regards,
Priyanka

**Comment by sandeep-tds** [comment]
Hi @priyankars2210,

Thank you so much for raising this concern.
We will be sure to update our documentation accordingly.

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
