### ISSUE TITLE
Set Up a Workflow With Extended Employee Onboarding

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5161]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html

Step 3.1 : After clicking on deprecated option to build the resources, it would be good to add the following screenshot to notify the user with deprecated build prompt in WebIDE.
![image](https://user-images.githubusercontent.com/50734023/81948932-e4807d80-961f-11ea-8004-9bfc13418c19.png)

Regards,
Nidhi

**Comment by ArchanaShukla** [comment]
I will soon update the BPMServicesFLP to use the new build and so this dialog wont come. Will update the tutorial accordingly

**Comment by ArchanaShukla** [comment]
Tutorial has been updated to use the new recommended build option and this dialog wont come anymore. @MichaelCzcz  - please close this issue

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
