### ISSUE TITLE
Create Card Template Issue

### ISSUE THREAD

**Issue by priyankars2210** [SAPDocuments/Tutorials#5162]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html

Please specify the step you are referring to:
In the following 3 Tutorials, step 2 step says "Click the Create a New Card icon.", but in the application, button is "Create Card Template" and not "Create a New Card" as mentioned in test case. It will be better to update the screenshot with the button toot-tip which says "Create Card Template"

Tutorial 2: Create A New Welcome Card
Step 2: Create a Welcome card
Tutorial 3: Create Cards Automatically with the Automatic Instance Generation Template
Step 2: Create an Automatic Instance card
Tutorial 5: Implement A Card With Content-Based Actions
Step 2: Create a new action card
![image](https://user-images.githubusercontent.com/65353045/81949433-7ab4a380-9620-11ea-8acf-f999293dc468.png)

Thanks & Regards,
Priyanka

**Comment by sandeep-tds** [comment]
Hi @priyankars2210,

Thank you so much for raising this concern.
We will be sure to update our documentation accordingly.

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
