### ISSUE TITLE
Save is missing after adding Reject Action

### ISSUE THREAD

**Issue by priyankars2210** [SAPDocuments/Tutorials#5163]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-action.html

Please specify the step you are referring to: Step 5: Add Reject Action

Save step missing in step 5. Deploy a new version of the Card' can only be executed after save.

Thanks & Regards,
Priyanka

**Comment by sandeep-tds** [comment]
Hi @priyankars2210,

Thank you so much for raising this concern.
We will be sure to update our documentation accordingly.

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
