### ISSUE TITLE
Stop cds watch prior to deploy

### ISSUE THREAD

**Issue by priyankars2210** [SAPDocuments/Tutorials#5165]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

Please specify the step you are referring to: Step 1: Enhance project configuration for SAP HANA

Issue: 
Prior to performing the steps in the terminal cds watch should be stopped (As it would still be running at this point according to the tutorial).
If we don't stop the cds watch, the terminal will be busy and we cannot perform any other steps in this terminal. So in this case, we have to open a new terminal and perform the steps there.

So from an end user perspective, please include the steps to either stop cds watch or to open a new terminal in the tutorial.

Thanks & Regards,
Priyanka

**Comment by iwonahahn** [comment]
Hi Priyanka,
Thank you for this issue. We added a sentence to stop cds watch if it´s still running. Will be visible asap.
Best regards,
Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
