### ISSUE TITLE
Include screenshot of ABAP Console

### ISSUE THREAD

**Issue by priyankars2210** [SAPDocuments/Tutorials#5166]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-persistence.html

Please specify the step you are referring to: Step 3: Create ABAP class

After we activate and run the ABAP Class, please include a screenshot of the ABAP Console in the tutorial, which shows that data was successfully inserted.
![image](https://user-images.githubusercontent.com/65353045/81951483-d41dd200-9622-11ea-8699-b9a643769ee2.png)

Thanks & Regards,
Priyanka

**Comment by mervey45** [comment]
Hi @priyankars2210 ,

thank you for your feedback. We' ll update this as soon as possible.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
