### ISSUE TITLE
Save is missing in Steps 9 and 10

### ISSUE THREAD

**Issue by priyankars2210** [SAPDocuments/Tutorials#5167]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Please specify the step you are referring to: 
Step 9: Create inbound tile
Step 10: Create SAP Fiori launchpad site module

Step 9: Please include a save operation in the tutorial after adding the Semantic object and action, as without this inbound tile will be disabled and cannot be edited

Step 10: After adding the app to the created group, please include a Save operation in the tutorial.

Thanks & Regards,
Priyanka

**Comment by mervey45** [comment]
Hi @priyankars2210 ,

thank you for your feedback. We' ll update this as soon as possible.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
