### ISSUE TITLE
Inspect and Test the API Proxy

### ISSUE THREAD

**Issue by iMilazzo** [SAPDocuments/Tutorials#5169]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-inspect-apiproxy.html

Please specify the step you are referring to **Step 1: Inspect the API proxy**

Part 5 - Make a service call out as a local target connection into the proxy path for the geocode API that we created. Replace the Path with <actual relative path>/geocode.json that represents your API proxy path of the geocoding API.

The image shows me 3 parameters:

```
<ServiceCallout async="true" continueOnError="false" enabled="true" xmlns="http://www.sap.com/apimgmt">
	<Request>
	    <Set>      
		<QueryParams>        
		    <QueryParam name="street">{country}</QueryParam>
			<QueryParam name="street">{street}</QueryParam>
			<QueryParam name="city">{city}</QueryParam>
			<QueryParam name="app_id"></QueryParam>
			<QueryParam name="app_code"></QueryParam>
		</QueryParams>      
		<Verb>GET</Verb>      
		</Set>  
	</Request>
	<Response>LatLongResponse</Response>
	<Timeout>30000</Timeout>
	<LocalTargetConnection>
		<Path>/p622138trial-trial.apim1.hanatrial.ondemand.com/p622138trial/6.2/geocode.json</Path>
	</LocalTargetConnection>
</ServiceCallout>
```
In the HERE.com I get `App ID`,  `API Key` and `Access Key ID` except for the `app_id` with ir equal for both, which one should I use in `app_code` field ?

When I run my page:
https://p622138trial-trial.apim1.hanatrial.ondemand.com/p622138trial/salesTrackerAPI/BusinessPartnerSet('0100000003') I'm getting the following error: 
`
{"fault":{"faultstring":"Execution of ServiceCallout CallGeocodingAPI failed. Reason: ResponseCode 404 is treated as error","detail":{"errorcode":"steps.servicecallout.ExecutionFailed"}}}`

And there are 2 options in HERE.com, Javascript or REST, which one should I use ?

What am I doing wrong? Can you help me?

Thanks
Ivan

**Comment by iMilazzo** [comment]
I have found 7 issues for this particular step of the tutorial and all of them decribing the same problem.
After spent hours of reasearch and a lot of frustration with this tutorial I was able to find what's happening:

1) The very first point in this whole step states "injects the Base64 encoded equivalent" with your user and password. At the contrary with some answers I've found for this issue, the user and password must be the same as you used when you setting up the API Provider (ES5 in my case).

2) The part 5 of this step shows the information about the CallGeocodingAPI. I removed the parameter `app_id` and the old and obsolete parameter `app_code` and replace them with `appKey` (doesn't matter if it the Javascript or the REST appKey, both will work). And finally , I was using the whole url at `<path>` tag. A minor issue: both `country` and `street` are using the same `<QueryParam name="street">`

```
<ServiceCallout async="true" continueOnError="false" enabled="true" xmlns="http://www.sap.com/apimgmt">
	<Request>
	    <Set>      
		<QueryParams>        
		    <QueryParam name="street">{country}</QueryParam>
			<QueryParam name="street">{street}</QueryParam>
			<QueryParam name="city">{city}</QueryParam>
			<QueryParam name="apiKey">QkrgClUqDpMowr_4cAtPSdTt5iETBQhsewFih48VonY</QueryParam>
		</QueryParams>      
		<Verb>GET</Verb>      
		</Set>  
	</Request>
	<Response>LatLongResponse</Response>
	<Timeout>30000</Timeout>
	<LocalTargetConnection>
		<Path>/p622138trial/6.2/geocode.json</Path>
	</LocalTargetConnection>
</ServiceCallout>
```
Now, there is this thing that makes me really upset, the 1st issue for this problem was dated 06/2019, almost an year and the tutorial stills the same. We came here to study and to learn and this **negligence** with this fixes are disrespectful with the community who shares the desire for learning and growing up. 
It doesn't reflect the view/image have about SAP. So it would be great if you fix it up.

Thanks
Ivan

**Comment by shilpavij** [comment]
Dear Colleague,
Thank for your feedback, apologies if there is a miss.

Let me clarify-
Point 1 -  the Base64 encoded equivalent of the user and password credentials for the **backend.**. This can be your ES5 or whatever you use. It is clearly mentioned and hence there is no correction required. For a few colleagues, they were not pasting the correct value and hence the error.

Point 2 - Here Map trial is evolving in terms of the UI and also scenes. Which SAP does not own. 
You are right we should put a generic text because today it is appKey and tomorrow it may be applicationkey and so on. Added a generic text with the note-https://github.com/SAPDocuments/Tutorials/pull/5171

Regards
Shilpa
