### ISSUE TITLE
Save Step is missing after we change the status to Productive

### ISSUE THREAD

**Issue by priyankars2210** [SAPDocuments/Tutorials#5170]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html

Please specify the step you are referring to: Step 3: Set card status to productive

Issue:
Save step is missing after we change card status from ‘Development’ to ‘Productive’ in the document. 
Even if we are aware that once you change the card status from "development" to "productive" , card status gets updated and you don't need to explicitly click  on "Save". 
But an End user might not be aware of this.
So from an end user perspective, please include the save step in the tutorial.

Thanks & Regards,
Priyanka

**Comment by sandeep-tds** [comment]
Hi @priyankars2210, 

Thank you so much for raising this concern.
We will be sure to update our documentation accordingly.

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
