### ISSUE TITLE
Prerequisites update sqlite.

### ISSUE THREAD

**Issue by mjochum** [SAPDocuments/Tutorials#5172]
The tutorial **Create a Business Service with Node.js Using Visual Studio Code** links to the [CAP documentation](https://cap.cloud.sap/docs/advanced/troubleshooting#sqlite).

In the section [How Do I Install SQLite on Windows?](https://github.wdf.sap.corp/cap/cap.github.wdf.sap.corp/blob/a54b7f413aa096edecc355cbd343a4740454ecdf/07-Advanced/99-Troubleshooting/index.md#how-do-i-install-sqlite-on-windows) , the documentation suggests:
* From the [SQLite download page](https://sqlite.org/download.html) download the precompiled binaries for Windows `sqlite-dll-win64-*.zip`.

However, the executables one wants to obtain are located in `sqlite-tools-win*.zip`.

**Comment by iwonahahn** [comment]
Hi,
thank you for your issue. We recommend to download the binary as marked in the screenshot. So the public docs ;-) [here](https://cap.cloud.sap/docs/advanced/troubleshooting#sqlite) are correct.
![recommended_download](https://user-images.githubusercontent.com/22098308/82067856-8dd37c00-96d1-11ea-887e-6d817d565aa3.png)

Best regards,
Iwona

**Comment by mjochum** [comment]
Thank you for your reply! I guess I was just confused where the file `sqlite3.exe` came from, as the recommended zip file only contains a `.def` and `.dll` file?
