### ISSUE TITLE
Build a Shopping Fresh Fiori App in SAPUI5

### ISSUE THREAD

**Issue by iMilazzo** [SAPDocuments/Tutorials#5174]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-create-fioriapp.html

Please specify the step you are referring to **Step 4: Deploy app**.

For some reason I'm unable to Deploy my app, the option for Deploy to SAP Cloud Platform is missing and I created my project as a SAP Fiori Master/Detail as stated in the tutorial:

![Anotação 2020-05-15 105244](https://user-images.githubusercontent.com/19697155/82058171-c310a780-969a-11ea-9cde-4c58c89897d1.png)

![Anotação 2020-05-15 105414](https://user-images.githubusercontent.com/19697155/82062421-76c86600-96a0-11ea-82d4-fe623638f4af.png)

I did exactly what the tutorial said.
I clear all my quotas deleting my applications and my service instances.

Can you help plz ?

Thanks
Ivan

**Comment by shilpavij** [comment]
Hello Ivan,

Right-click on your project and check. I am getting the options.
<img width="521" alt="Deploy" src="https://user-images.githubusercontent.com/44152823/82197239-5acef980-9918-11ea-8d9b-d9cd01697fd8.png">

Regards
Shilpa

**Comment by iMilazzo** [comment]
Well, there is something wrong and no one is able to help me, I will leave this tutorial behind !!

Thanks
