### ISSUE TITLE
Build OData Queries with the SAP Cloud SDK's Virtual Data Model

### ISSUE THREAD

**Issue by iMilazzo** [SAPDocuments/Tutorials#5178]
Tutorial URL: https://developers.sap.com/tutorials/cloudsdk-js-vdm-getall.html

Please specify the step you are referring to **Step 13: Test yourself (3)**

> “What have I got in my pocket?" he said aloud. He was talking to himself, but Gollum thought it was a riddle, and he was frightfully upset.
>"Not fair! not fair!" he hissed. "It isn't fair, my precious, is it, to ask us what it's got in it's nassty little pocketsess?”
>
>― J.R.R. Tolkien, The Hobbit, or There and Back Again 

This is the code I did and brought me 1249 records:
``` javascript
import { Injectable } from '@nestjs/common';
import { BusinessPartner } from '@sap/cloud-sdk-vdm-business-partner-service';

@Injectable()
export class BusinessPartnerService {

  getAllBusinessPartners(): Promise<BusinessPartner[]> {
    return BusinessPartner.requestBuilder()
    .getAll()
    .withCustomHeaders({
      apikey: 'Wxsw3bRuQQApZLOkJ21G2UNJu49LIJ72',
      demoDB: "string"
    })
    .execute({
      url: 'https://sandbox.api.sap.com/s4hanacloud'
    });
  }
}
```
![image](https://user-images.githubusercontent.com/19697155/82158056-a5d70700-985b-11ea-9033-0a025bdba680.png)

Would you mind in show me the code I have to paste to advance in this tutorial ??

btw: it took me a long time to discover this all by myself:

```
      demoDB: "string"
      url: 'https://sandbox.api.sap.com/s4hanacloud'
```

Thanks
Ivan

**Comment by jjtang1985** [comment]
Hi @iMilazzo , thank you for approaching us.
To answer your question, the code should be:
```
BusinessPartner.requestBuilder()
.getAll()
.execute({
    url: "https://my.cloud.erp.com"
})
```
Your code is definitely working, but the question is 
> Write the minimum necessary code to get all business partners from a system under 'https://my.cloud.erp.com' (assuming no authentication is necessary).

We don't want to discourage/confuse people like that so we changed the tests.
Thank you.

**Comment by karstenmelato** [comment]
Tutorial has been changed to Text exactly matches with ID.

**Comment by iMilazzo** [comment]
I'm still no able to advance: 

![image](https://user-images.githubusercontent.com/19697155/83699972-e5338080-a5db-11ea-8438-abe85a0aa9c1.png)

I will open a new ticket and I hope you don't close it too...

**Comment by iMilazzo** [comment]
![image](https://user-images.githubusercontent.com/19697155/83700185-8a4e5900-a5dc-11ea-96d4-0e4187d75d6b.png)

**Comment by jjtang1985** [comment]
Hi @iMilazzo , since we updated the tests, I guess you have to refresh your pages.
The question you posted does not exist any more, if we are talking about the same [link](https://developers.sap.com/tutorials/cloudsdk-js-vdm-getall.html).
If refreshing doesn't work, maybe you can clean your cache or use e.g., Chrome incognito window.
Please let me know, if you still have questions.
