### ISSUE TITLE
Error during Tenant Provisioning in SAP Cloud Platform Trial Account

### ISSUE THREAD

**Issue by gouravkumarjena** [SAPDocuments/Tutorials#5180]
Hello Team,

I am facing issues with my Tenant provisioning. The same is getting stuck after completion of 18 percent. Earlier I thought maybe I will try with a new account. But I faced the same problem.
Here are my trial account details:

Global Account: ba30d83atrial
Subaccount: trial
Error Message:
Tenant provisioning is in progress and it can take 20 minutes. Please wait for the provisioning to complete before creating service broker instances.

Global Account: 931506cctrial
Subaccount: trial
Error Message:
Tenant provisioning is in progress and it can take 20 minutes. Please wait for the provisioning to complete before creating service broker instances.

Please do the needful so that I can set up the tenant provisioning successfully. both the processes are stuck after 18% progress.

Regards
Gourav Jena

**Comment by MichaelCzcz** [comment]
Hello Jena,

this channel is only for issues with tutorials. If you are facing problems with our products, kindly create a ticket.

Regards,
Michael
