### ISSUE TITLE
Use OData Navigation Properties with the SAP Cloud SDK's Virtual Data Model

### ISSUE THREAD

**Issue by iMilazzo** [SAPDocuments/Tutorials#5182]
Tutorial URL: https://developers.sap.com/tutorials/cloudsdk-js-vdm-getbykey.html

Please specify the step you are referring to **Step 6: Test yourself**

> “What have I got in my pocket?" he said aloud. He was talking to himself, but Gollum thought it was a riddle, and he was frightfully upset.
>"Not fair! not fair!" he hissed. "It isn't fair, my precious, is it, to ask us what it's got in it's nassty little pocketsess?”
>
>― J.R.R. Tolkien, The Hobbit, or There and Back Again 

Again, this is code I wrote:
``` javascript
  getBusinessPartnerById(businessPartnerId: string): Promise<BusinessPartner> {
    return BusinessPartner.requestBuilder()
    .getByKey(businessPartnerId)
    .select(
        BusinessPartner.BUSINESS_PARTNER,
        BusinessPartner.BUSINESS_PARTNER_NAME,
        BusinessPartner.BUSINESS_PARTNER_UUID,
        BusinessPartner.TO_BUSINESS_PARTNER_ADDRESS.select(
            BusinessPartnerAddress.BUSINESS_PARTNER,
            BusinessPartnerAddress.ADDRESS_ID,
            BusinessPartnerAddress.COUNTRY,
            BusinessPartnerAddress.POSTAL_CODE,
            BusinessPartnerAddress.CITY_NAME,
            BusinessPartnerAddress.STREET_NAME,
            BusinessPartnerAddress.HOUSE_NUMBER
          )
      )    
      .withCustomHeaders({
        apikey: 'Wxsw3bRuQQApZLOkJ21G2UNJu49LIJ72',
        demoDB: "string"
      })
      .execute({
        url: 'https://sandbox.api.sap.com/s4hanacloud'
      });
  }  
```
And this is the result:

![image](https://user-images.githubusercontent.com/19697155/82157953-0ca7f080-985b-11ea-885b-b6fb17477624.png)

Would you mind in show me the code I have to paste to advance in this tutorial ??

Thanks
Ivan

**Comment by jjtang1985** [comment]
Hi @iMilazzo ,
just like [this similar issue](https://github.com/SAPDocuments/Tutorials/issues/5178).

The answer should be:
```
BusinessPartner
.requestBuilder()
.getByKey('1')
.select(
    BusinessPartner.TO_BUSINESS_PARTNER_ADDRESS
)
.execute({ 
    url: 'https://my.cloud.erp.com' 
})
```
because the question was:
> Write the minimum necessary code to get a single business partner with ID '1' and its addresses, using system 'https://my.cloud.erp.com' (assuming no authentication is necessary).

Again, we changed the test to make it less confusing.

Thank you.

**Comment by karstenmelato** [comment]
Tutorial has been changed to Text exactly matches with ID.
