### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by conworld** [SAPDocuments/Tutorials#5183]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Please specify the step you are referring to step 7 deploy the iFlow
Very excellent tutorial. Help me a lot. I do all steps. but step 7 deploy failed.
![image](https://user-images.githubusercontent.com/48739942/82169938-9906f180-98f5-11ea-9e04-5fe0b47206c9.png)
![image](https://user-images.githubusercontent.com/48739942/82169950-a1f7c300-98f5-11ea-830a-5b582feac645.png)
I need expand channel timeout duration? Could you tell me how to configure?
Thanks & Best Regards,
Dou

**Comment by Vikramkulkarni01** [comment]
Hi Dou, 

Thanks for reaching out to us. 

I understand your concern. It seems like some connection issues. However, could you please try deploying again and check. 

If the issue persists, could you please share with me the below details to investigate the issue further?

1. Global Account name & ID
2. Subaccount name and ID 
3. Error log or screenshots. 


We truly appreciate your support and looking forward to hearing from you. 

Regards, 
Vikram Kulkarni

**Comment by conworld** [comment]
Hi @Vikramkulkarni01 ,
Thanks for your reply. I redeployed but errors still appeared.
Global Account: 1446964btrial
Subaccount: trial
Deploy Log
StoreArtifactMetadata >> 12:51:02.783 [itcoMEDIUM64] INFO  - (createBundleRecord) Creating bundle record for task: 1782c36b-e837-432a-a688-b95633709d1e, tenant: TenantInfo{id='f2d8136a-a373-48d6-92d5-cb83e1055d88', name='1446964btrial', domain='1446964btrial', status=ON_BOARDED, createdTime=1589806262776}, partitionId: __unassigned and path: /home/vcap/tmp/bb540270-81b4-40a7-8c0b-c39348cac50c/CPI_Trail_iFlow.zip with tags: {artifact.authenticity.status=REPUDIATED, artifact.package.id=CPITrailPackage, artifact.package.name=CPI_Trail_Package}
StoreArtifactMetadata >> 12:51:02.792 [itcoMEDIUM64] INFO  - (createBundleRecord) Enriching SAP-ArtifactId with value: 60221632-5220-40b4-a743-bdfbfe0853bd for: /home/vcap/tmp/bb540270-81b4-40a7-8c0b-c39348cac50c/CPI_Trail_iFlow.zip
StoreArtifactMetadata >> 12:51:02.838 [itcoMEDIUM64] INFO  - (createBundleRecord) Artifact tags being set are:{artifact.authenticity.status=REPUDIATED, artifact.package.id=CPITrailPackage, artifact.package.name=CPI_Trail_Package, artifact.trait=}
StoreArtifactMetadata >> 12:51:02.844 [itcoMEDIUM27] INFO  - (loadExistingArtifactIds)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) existingArtifactIds: []
StoreArtifactMetadata >> 12:51:02.855 [itcoMEDIUM27] INFO  - (loadExistingArtifactIds)(task 1782c36b-e837-432a-a688-b95633709d1e) Completed in time 13 millis
StoreArtifactMetadata >> 12:51:02.866 [itcoMEDIUM27] INFO  - (storeArtifactInfos)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Successfully stored artifact infos [60221632-5220-40b4-a743-bdfbfe0853bd]
StoreArtifactMetadata >> 12:51:02.887 [itcoMEDIUM27] INFO  - (storeArtifactInfos)(task 1782c36b-e837-432a-a688-b95633709d1e) Completed in time 29
Generation&Build >> 12:51:02.890 [itcoMEDIUM27] INFO  - 1782c36b-e837-432a-a688-b95633709d1e|1446964btrial|GENERATION_BUILD| (uploadDesignTimeArtifacts) artifacts [Artifact{tenantId='f2d8136a-a373-48d6-92d5-cb83e1055d88', id='60221632-5220-40b4-a743-bdfbfe0853bd', symbolicName='CPI_Trail_iFlow', name='CPI_Trail_iFlow', version='1.0.0', localPath=/home/vcap/tmp/bb540270-81b4-40a7-8c0b-c39348cac50c/CPI_Trail_iFlow.zip}]
Generation&Build >> 12:51:03.030 [itcoMEDIUM27] INFO  - (uploadDesignTimeArtifacts)(task 1782c36b-e837-432a-a688-b95633709d1e)(tenant 1446964btrial) Completed in 140 millis
Generation&Build >> 12:51:03.034 [itcoMEDIUM27] INFO  - 1782c36b-e837-432a-a688-b95633709d1e|1446964btrial (requestGenerationAndBuild) publish gbReq: GbRequestEvent{taskId='1782c36b-e837-432a-a688-b95633709d1e', tenantName='1446964btrial', sourceFolder='artifacts/1782c36b-e837-432a-a688-b95633709d1e/', artifactIds=[60221632-5220-40b4-a743-bdfbfe0853bd], targetFolder='artifacts/1782c36b-e837-432a-a688-b95633709d1e/rta', robust=false, originInfo=OriginInfo{originUser='dujin@beself.pro', originClient='sap.default'}, tags={artifact.authenticity.status=REPUDIATED, artifact.package.id=CPITrailPackage, artifact.package.name=CPI_Trail_Package, artifact.trait=}}, gbTimeout: PT4M
Generation&Build >> 12:51:03.036 [itcoMEDIUM27] INFO  - (requestGenerationAndBuild)(task 1782c36b-e837-432a-a688-b95633709d1e) Completed in time 1
Generation&Build >> 12:51:08.112 [itcoMEDIUM61] INFO  - (handleGbResponseEvent) (task: 1782c36b-e837-432a-a688-b95633709d1e) RECEIVED event:StandardMessage{number=856, tenantName='1446964btrial', topicName='it-cpitrial01.co.notification', correlationId='1782c36b-e837-432a-a688-b95633709d1e', headers={talk.exchange.pattern=OutOnly, talk.payload.type=com.sap.it.talk.payload.gb.GbResponseEvent, talk.correlation.id=1782c36b-e837-432a-a688-b95633709d1e, talk.message.number=856, talk.tenant.name=1446964btrial}, payload=com.sap.it.talk.payload.gb.GbResponseEvent}
Generation&Build >> 12:51:08.119 [itcoMEDIUM61] INFO  - (handleGbResponseEvent)(task: 1782c36b-e837-432a-a688-b95633709d1e) Stage finished in time 0 millis
Generation&Build >> 12:51:08.169 [itcoMEDIUM61] INFO  - (downloadRuntimeArtifacts)(task 1782c36b-e837-432a-a688-b95633709d1e) Completed in time 47 millis
CreateMessagingResource >> 12:51:08.174 [itcoMEDIUM61] INFO  - (getQueueDescriptorPath) All manifest attributes for this artifact: {SAP-ArtifactTrait=, SAP-PreDeployment=null, Bundle-SymbolicName=CPI_Trail_iFlow, Bundle-Version=1.0.0, SAP-ArtifactId=60221632-5220-40b4-a743-bdfbfe0853bd, SAP-BundleType=IntegrationFlow, Bundle-Name=CPI_Trail_iFlow}, Queue Descriptor Path: null
CreateMessagingResource >> 12:51:08.175 [itcoMEDIUM61] INFO  - (createMessageQueues) (taskId: 1782c36b-e837-432a-a688-b95633709d1e)(tenant: 1446964btrial) No queue descriptor found in artifact: 60221632-5220-40b4-a743-bdfbfe0853bd
CreateMessagingResource >> 12:51:08.180 [itcoMEDIUM61] INFO  - (storeQueueInfo/s)(taskId: 1782c36b-e837-432a-a688-b95633709d1e)(tenant: 1446964btrial) Storing Queue Infos: []
CreateMessagingResource >> 12:51:08.183 [itcoMEDIUM61] INFO  - (storeQueueArtifactMapping)(taskId: 1782c36b-e837-432a-a688-b95633709d1e)(tenant: 1446964btrial) queue info/s to be stored in queue_artifact_mapping: []
CreateMessagingResource >> 12:51:08.184 [itcoMEDIUM61] INFO  - (createMessageQueues)(task 1782c36b-e837-432a-a688-b95633709d1e) Completed in time 10 millis
PartitionContent >> 12:51:14.406 [itcoMEDIUM61] INFO  - (getExpectedWorkerCount) tenant 1446964btrial, workerSetId itw-1446964btrial-0 numWorkers 1
PartitionContent >> 12:51:14.413 [itcoMEDIUM61] INFO  - (partitionContents)(task 1782c36b-e837-432a-a688-b95633709d1e) Completed in time 6227
PartitionContent >> 12:51:14.418 [itcoMEDIUM33] INFO  - (recordEvents)(task 1782c36b-e837-432a-a688-b95633709d1e) Completed in time 3 millis
NotifyWorkerToDeploy >> 12:51:14.424 [itcoMEDIUM33] INFO  - (createDeployRequest)(task 1782c36b-e837-432a-a688-b95633709d1e) Completed in time 0
NotifyWorkerToDeploy >> 12:51:14.446 [itcoMEDIUM33] INFO  - (processDeploy) (taskId: 1782c36b-e837-432a-a688-b95633709d1e) Sent deploy request: StandardMessage{number=12643, tenantName='1446964btrial', topicName='it-cpitrial01.agent.notification.itw-1446964btrial-0', correlationId='1782c36b-e837-432a-a688-b95633709d1e', headers={stage.number=6, talk.payload.type=com.sap.it.spi.types.deploy.DeployRequest, talk.exchange.pattern=OutOnly, talk.correlation.id=1782c36b-e837-432a-a688-b95633709d1e, talk.message.number=12643, talk.tenant.name=1446964btrial}, payload=com.sap.it.spi.types.deploy.DeployRequest} to Topic: it-cpitrial01.agent.notification.itw-1446964btrial-0
ProcessWorkerDeployResponses >> 12:51:14.450 [itcoMEDIUM33] INFO  - (getExpectedWorkerCount) tenant 1446964btrial, workerSetId itw-1446964btrial-0 numWorkers 1
ProcessWorkerDeployResponses >> 12:51:14.452 [itcoMEDIUM33] INFO  - (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Received #0 responses out of #1 for payload com.sap.it.spi.types.deploy.DeployResponse
ProcessWorkerDeployResponses >> 12:51:24.454 [itcoMEDIUM33] INFO  - (getExpectedWorkerCount) tenant 1446964btrial, workerSetId itw-1446964btrial-0 numWorkers 1
ProcessWorkerDeployResponses >> 12:51:24.460 [itcoMEDIUM33] INFO  - (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Received #0 responses out of #1 for payload com.sap.it.spi.types.deploy.DeployResponse
ProcessWorkerDeployResponses >> 12:51:34.462 [itcoMEDIUM33] INFO  - (getExpectedWorkerCount) tenant 1446964btrial, workerSetId itw-1446964btrial-0 numWorkers 1
ProcessWorkerDeployResponses >> 12:51:34.470 [itcoMEDIUM33] INFO  - (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Received #0 responses out of #1 for payload com.sap.it.spi.types.deploy.DeployResponse
ProcessWorkerDeployResponses >> 12:51:44.472 [itcoMEDIUM33] INFO  - (getExpectedWorkerCount) tenant 1446964btrial, workerSetId itw-1446964btrial-0 numWorkers 1
ProcessWorkerDeployResponses >> 12:51:44.478 [itcoMEDIUM33] INFO  - (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Received #0 responses out of #1 for payload com.sap.it.spi.types.deploy.DeployResponse
ProcessWorkerDeployResponses >> 12:51:54.479 [itcoMEDIUM33] INFO  - (getExpectedWorkerCount) tenant 1446964btrial, workerSetId itw-1446964btrial-0 numWorkers 1
ProcessWorkerDeployResponses >> 12:51:54.485 [itcoMEDIUM33] INFO  - (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Received #0 responses out of #1 for payload com.sap.it.spi.types.deploy.DeployResponse
ProcessWorkerDeployResponses >> 12:52:04.487 [itcoMEDIUM33] INFO  - (getExpectedWorkerCount) tenant 1446964btrial, workerSetId itw-1446964btrial-0 numWorkers 1
ProcessWorkerDeployResponses >> 12:52:04.493 [itcoMEDIUM33] INFO  - (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Received #0 responses out of #1 for payload com.sap.it.spi.types.deploy.DeployResponse
ProcessWorkerDeployResponses >> 12:52:14.495 [itcoMEDIUM33] INFO  - (getExpectedWorkerCount) tenant 1446964btrial, workerSetId itw-1446964btrial-0 numWorkers 1
ProcessWorkerDeployResponses >> 12:52:14.502 [itcoMEDIUM33] INFO  - (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Received #0 responses out of #1 for payload com.sap.it.spi.types.deploy.DeployResponse
ProcessWorkerDeployResponses >> 12:52:24.503 [itcoMEDIUM33] INFO  - (getExpectedWorkerCount) tenant 1446964btrial, workerSetId itw-1446964btrial-0 numWorkers 1
ProcessWorkerDeployResponses >> 12:52:24.507 [itcoMEDIUM33] INFO  - (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Received #0 responses out of #1 for payload com.sap.it.spi.types.deploy.DeployResponse
ProcessWorkerDeployResponses >> 12:52:34.510 [itcoMEDIUM33] INFO  - (getExpectedWorkerCount) tenant 1446964btrial, workerSetId itw-1446964btrial-0 numWorkers 1
ProcessWorkerDeployResponses >> 12:52:34.516 [itcoMEDIUM33] INFO  - (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Received #0 responses out of #1 for payload com.sap.it.spi.types.deploy.DeployResponse
ProcessWorkerDeployResponses >> 12:52:44.518 [itcoMEDIUM33] INFO  - (getExpectedWorkerCount) tenant 1446964btrial, workerSetId itw-1446964btrial-0 numWorkers 1
ProcessWorkerDeployResponses >> 12:52:44.526 [itcoMEDIUM33] INFO  - (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Received #0 responses out of #1 for payload com.sap.it.spi.types.deploy.DeployResponse
ProcessWorkerDeployResponses >> 12:52:54.527 [itcoMEDIUM33] INFO  - (getExpectedWorkerCount) tenant 1446964btrial, workerSetId itw-1446964btrial-0 numWorkers 1
ProcessWorkerDeployResponses >> 12:52:54.532 [itcoMEDIUM33] INFO  - (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Received #0 responses out of #1 for payload com.sap.it.spi.types.deploy.DeployResponse
ProcessWorkerDeployResponses >> 12:53:04.534 [itcoMEDIUM33] INFO  - (getExpectedWorkerCount) tenant 1446964btrial, workerSetId itw-1446964btrial-0 numWorkers 1
ProcessWorkerDeployResponses >> 12:53:04.540 [itcoMEDIUM33] INFO  - (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Received #0 responses out of #1 for payload com.sap.it.spi.types.deploy.DeployResponse
ProcessWorkerDeployResponses >> 12:53:14.542 [itcoMEDIUM33] INFO  - (getExpectedWorkerCount) tenant 1446964btrial, workerSetId itw-1446964btrial-0 numWorkers 1
ProcessWorkerDeployResponses >> 12:53:14.550 [itcoMEDIUM33] INFO  - (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Received #0 responses out of #1 for payload com.sap.it.spi.types.deploy.DeployResponse
ProcessWorkerDeployResponses >> 12:53:14.551 [itcoMEDIUM33] ERROR - (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) TIMED-OUT waiting for responses from #1 workers. Only received responses from [] workers for payload: com.sap.it.spi.types.deploy.DeployResponse
ProcessWorkerDeployResponses >> 12:53:14.554 [itcoMEDIUM33] INFO  - (getDeployResponsesFuture)(task 1782c36b-e837-432a-a688-b95633709d1e) Completed in time 120104
ProcessWorkerDeployResponses >> 12:53:14.555 [itcoMEDIUM33] ERROR - (deployPostProcess) Failed DeployTask: 1782c36b-e837-432a-a688-b95633709d1e
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Deploy timed out: 120 seconds
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:967)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:836)
Caused by: java.util.concurrent.TimeoutException: (msgReceiver)(taskId: 1782c36b-e837-432a-a688-b95633709d1e) Deploy timed out: 120 seconds
	at com.sap.it.co.core.task.DeployTaskMaker.getDeployResponsesFuture(DeployTaskMaker.java:577)
	at com.sap.it.co.core.task.DeployTaskMaker.lambda$processDeploy$26(DeployTaskMaker.java:496)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
	... 9 common frames omitted
ProcessWorkerDeployResponses >> 12:53:14.562 [itcoMEDIUM33] INFO  - (deployPostProcess)(task 1782c36b-e837-432a-a688-b95633709d1e) Completed in time 7

Thanks & Best Regards,
Dou

**Comment by Vikramkulkarni01** [comment]
Hi Dou, 

Thank you for sharing the requested information. 

However, for the deeper investigation, we need some more detail. 

Could you please share us the complete application URL?

Click on the Process Integration--> Click Go to Application --> and share that complete URL with us.

We truly appreciate your support and looking forward to hearing from you.

Regards,
Vikram Kulkarni

**Comment by conworld** [comment]
Hi @Vikramkulkarni01 ,
Thank you for your reply.
Web UI URL
https://1446964btrial.it-cpitrial01.cfapps.eu10.hana.ondemand.com/itspaces

Thanks & Best Regards,
Dou

**Comment by Vikramkulkarni01** [comment]
Hi Dou,

Thank you for sharing the information with me. I shared the same with my internal team to provide the necessary fix. 

I am working closely with the team and keep you posted with an update. 

Regards, 
Vikram Kulkarni

**Comment by conworld** [comment]
Hi @Vikramkulkarni01 .
really appreciate your help. I find the iFlow is already ok.
could you tell me how to fix the issue?
Thanks & Best Regards,
Dou

**Comment by Vikramkulkarni01** [comment]
Hi Dou, 
I understand your concern.

I already involved our internal team to check this issue and the work is still in progress. 

I will keep you posted with an update as soon as I hear from them. 

Regards, 
Vikram Kulkarni

**Comment by Vikramkulkarni01** [comment]
Hi Dou, 
With reference to your concern, our internal team worked on it and provided the necessary fix to it. 

You can now deploy your integration flows. 

Since there are no action required from our end, we are closing this issue. Kindly share your feedback. 

Regards, 
Vikram Kulkarni

**Comment by conworld** [comment]
Hi @Vikramkulkarni01 ,
very appreciate your team. I already redeployed successfully.
I want to know how you fixed the issue or what is wrong. Could you tell me?
Will the issue appear again next new deploy?
Thanks & Best Regards,
Dou

**Comment by Vikramkulkarni01** [comment]
Hi Dou, 

There was some technical glitch from our end and it has been fixed to resolve your issue.
There is no action required from your end if the issue persists.

Since there are no action required from our end, we are closing this issue. 

Regards, 
Vikram Kulkarni
