### ISSUE TITLE
Create Service Consumption Model for Business Partner and Sales Order Item Cube

### ISSUE THREAD

**Issue by I322851** [SAPDocuments/Tutorials#5193]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-s4hanacloud-service-consumption.html

Please specify the step you are referring to : Step 3 - Subpart 8(Select External API and click on the butterfly symbol).

I thing there is a missing step as it is just mentioned to click on the butterfly symbol but noting is mentioned about the association condition. This results in an error later while saving.
![image](https://user-images.githubusercontent.com/37858820/82337568-8c73bd80-9a09-11ea-93c0-f09489fbee12.png)
I believe the the association condition should be mapping between BusinessPartner and sold-to-party.

Best Regards,
Chaitra

**Comment by mervey45** [comment]
Hi @I322851,

thank you for your feedback. We'll update this as soon as possible.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
