### ISSUE TITLE
Create Service Binding for Bonus Plan Scenario with SAP Cloud Platform ABAP environment

### ISSUE THREAD

**Issue by I322851** [SAPDocuments/Tutorials#5196]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-s4hanacloud-binding.html

Please specify the step you are referring to - Prerequisites

Hello colleagues,
I am trying to execute this scenario in canary landscape. In the prerequisites it is mentioned that Communication arrangement for scenario SAP_COM_0027 is created in your SAP Cloud Platform, ABAP environment system has to be created. But in my SCP ABAP environment, I couldn't find Communication Scenario for SAP_COM_0027.
![image](https://user-images.githubusercontent.com/37858820/82428468-2ee27e00-9aa8-11ea-9be7-fad38455cbe6.png)

Kindly have a look into this.

Best Regards,

**Comment by mervey45** [comment]
Hi @I322851 ,

which system are you using? This should an SAP Cloud Platform ABAP environment system (not trial). 

There it should look like following: 
![image](https://user-images.githubusercontent.com/27953324/83127848-edbb2100-a0da-11ea-9902-49bf87df9901.png)

You should be able to select the SAP CP CF Destination Service Integration.

Best regards, 
Merve

**Comment by I322851** [comment]
I am using Canary Landscape. As it was mentioned in the tutorial that it works only if there is customer or partner License.

**Comment by mervey45** [comment]
Hi @I322851 ,

yes, you do need a license to do this tutorial. You should have a valid SAP Cloud Platform ABAP environment license. Are you using a system with a valid  SAP Cloud Platform ABAP environment license?

Best regards, 
Merve

**Comment by I322851** [comment]
Yes I have a paid account in canary landscape. Where I have setup ABAP instance newly.
Kindly let me know how to check if it is correct license.

**Comment by mervey45** [comment]
Hi @I322851 ,

you can have a look at following: 
Go to your global account -> select your space -> service marketplace (left side) -> select abap trial-> instances -> and check if you have an instance.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
