### ISSUE TITLE
Create a Basic Node.js App

### ISSUE THREAD

**Issue by bharanidharanspm** [SAPDocuments/Tutorials#5199]
Hi All,
Tutorial URL: https://developers.sap.com/tutorials/cp-node-create-basic-app.html

Please specify the step you are referring to

user@host:~/nodetutorial/myapp
=> node server.js

C:\Users\bharanidharan_spm\nodetutorial\myapp>node server.js
internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module 'C:\Users\bharanidharan_spm\nodetutorial\myapp\server.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:890:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by maxstreifeneder** [comment]
HI @bharanidharanspm, 

sorry for the late response. Are you sure that you have created the server.js file in the myapp directory? 
A screenshot of your folder structure would help. 

Cheers,
Max

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
