### ISSUE TITLE
Create a Simple ABAP CDS View in ADT

### ISSUE THREAD

**Issue by Juanvictormanuel1188** [SAPDocuments/Tutorials#5202]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-adt-create-cds-view.html

Please specify the step you are referring to 

Activating View Definition:

![image](https://user-images.githubusercontent.com/64492634/82693992-1dc07b00-9c28-11ea-8f07-710fdf7e251a.png)

![image](https://user-images.githubusercontent.com/64492634/82694095-45174800-9c28-11ea-97e5-b7a35d3cd523.png)

![image](https://user-images.githubusercontent.com/64492634/82694220-814aa880-9c28-11ea-90af-adf6b1ca3e1e.png)

Im using a trial account.

Let me know anything please.

Thanks and regards!
Victor

**Comment by julieplummer20** [comment]
Hi Victor,
Which trial version? If you mean SAP Cloud Platform, ABAP Environment, then no, this tutorial is only valid for on-Premise. I am in the process of writing a CDS tutorial for Cloud.
If you are on-Premise, what release?
BR Julie.

**Comment by Juanvictormanuel1188** [comment]
Hi Julie,

Yes, SAP Cloud Platform.

Thanks and Regards!
Victor
