### ISSUE TITLE
Build a Simple Approval UI for Your Workflow with Workflow Forms (Neo)

### ISSUE THREAD

**Issue by bprolikeme** [SAPDocuments/Tutorials#5203]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-build-approval-ui.html

Hi, 
in the Approval Process. How can we use the decision made be the user task (Approved or not) be used in the further workflow, like in a gateway. Can i somehow access in the gateway, which button has been clicked in the user task before? 
Br

**Comment by ArchanaShukla** [comment]
Hello DJ,
You can access the decision using the following documentation:
https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/9fd9395339e94143ac9ce9e693b06bd1.html?q=decision

${usertasks.usertask1.last.decision} where _usertask1_ is the user task ID of your user task. You can access this in gateways like ${usertasks.usertask1.last.decision == 'true' }

**Comment by qmacro** [comment]
Thanks @ArchanaShukla. @bprolikeme this issues list is for issues with the tutorial content - for questions like this you'd be better heading over to the SAP Community Q&A where others will see your question and also benefit from the answers and discussion. Thanks!
