### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#5205]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to

Step:3 point 8. 
In the described screenshot you seem to have a drop down list of services you can choose from based on your ES5 selection. I have the destination created as per the pre-requisite but for me I have to enter the service directly? Have I missed something in getting that dropdown - to then select the OData service from a list?? 

![image](https://user-images.githubusercontent.com/38389079/82749257-480e6600-9deb-11ea-8fd5-3fd3ab1f2415.png)

A further difference I see is the ES5 has [Catalog] but in mine it states [System URL]??? 

I managed to find a service /sap/opu/odata/sap/EPM_REF_APPS_PO_APV_SRV but just wondered why the tutorial shows differently than what I am experiencing. 

Thanks & Kind Regards
Phil Cooley

**Comment by raz-korn** [comment]
Hi Phil,
I apologize for the late response.
From what you describe, I believe there's something wrong with the destination configuration. My bet would be that the additional property WebIDEUsage does not contain odata_abap or it contains additional sub-properties. If this solves your issue - great. If not - please share a screenshot of how ES5 is configured in the Cockpit.
Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
