### ISSUE TITLE
Set Up SAP Business Application Studio for CAP Java

### ISSUE THREAD

**Issue by JuanDK** [SAPDocuments/Tutorials#5206]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-app-studio.html

Please specify the step you are referring to: Step 4: Compile model definition
command: "mvn clean install" Fails

 [INFO] products-service parent ............................ SUCCESS [  1.574 s]
[INFO] products-service ................................... FAILURE [  3.868 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.950 s
[INFO] Finished at: 2020-05-24T08:59:22Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:npm (cds schema) on project products-service: Failed to run task: 'npm run schema --https-proxy=http://127.0.0.1:8887 --proxy=http://127.0.0.1:8887' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:npm (cds schema) on project products-service: Failed to run task

**Comment by maxstreifeneder** [comment]
Hi Juan,

is this problem still occuring? There where several updates to the SAP Business Application Studio. 

Sorry for the late response! 
Max

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
