### ISSUE TITLE
Inspect and Test the API Proxy

### ISSUE THREAD

**Issue by nsreerambhatla** [SAPDocuments/Tutorials#5207]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-inspect-apiproxy.html

Please specify the step you are referring to

There are two issues.

1) There is no generate APP code for HERE.com apps
2) BusinessPartnerSet : Address type "GWSAMPLE_BASIC.CT_Address" does not have longitude and latitude fields .

Please help.

![image](https://user-images.githubusercontent.com/65887355/82785987-4d1df480-9e81-11ea-9809-7a1592eceeac.png)

**Comment by shilpavij** [comment]
Hello, 
kindly take the aapkey parameter now-HERE has changed this with new trials.
For step 2- we need to debug what is wrong with your code. Anyways not a mandatory step-kindly proceed.

Regards
Shilpa

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
