### ISSUE TITLE
Integrate an SAPUI5 App into Your Portal Site (Cloud Foundry)

### ISSUE THREAD

**Issue by Clmaureira** [SAPDocuments/Tutorials#5212]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-sapui5-app.html

Please specify the step you are referring to
In the step 5, i can't assing "Candidates" to group "Work in progress". The follow message it appers:

"Something went wrong, and your changes were not saved. Please Retry, or Close and try again later"
2 day it's the same message.

Regards.
Clmaureira

![image](https://user-images.githubusercontent.com/65935429/82858842-019c3280-9ee3-11ea-8f14-faeeb8ada9ea.png)

**Comment by IrisSasson** [comment]
Hi
Does this still reproduce? Assigning any app to any group should work and is independent of the app
Please try again, if reproduced, please try from a different browser

Thanks
Iris.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by Clmaureira** [comment]
Hi, sorry that´s ok, the problem was the space disck.

Thank you.
