### ISSUE TITLE
Set Up SAP Web Analytics

### ISSUE THREAD

**Issue by null-saad** [SAPDocuments/Tutorials#5213]
Tutorial URL: https://developers.sap.com/tutorials/cp-webanalytics-setup.html

Hi, by any chance is the SAP Web analytics service deprecated, as I am unable to find it under Subscriptions
Region : Europe
Environment : Cloud Foundry 

Below are the services that are visible.
![image](https://user-images.githubusercontent.com/12512916/82859097-6b442d00-9f33-11ea-8922-1e74bbc40f81.png)

**Comment by Karunaharan** [comment]
Hello @null-saad 
SAP Web Analytics is currently available on CF in AWS Europe (Frankfurt) and Azure Europe (Netherlands). For more information, see [SAP Cloud Platform Regions and Service Portfolio](https://help.sap.com/doc/aa1ccd10da6c4337aa737df2ead1855b/Cloud/en-US/3b642f68227b4b1398d2ce1a5351389a.html). Feel free to reach out if you have further questions.

**Comment by null-saad** [comment]
Okay thank you
