### ISSUE TITLE
Add Automated System Tests with the SAPUI5 Test Recorder to Your CI/CD Pipeline

### ISSUE THREAD

**Issue by nair-sumesh** [SAPDocuments/Tutorials#5227]
Tutorial URL: https://developers.sap.com/tutorials/cp-cicd-systemtest-recorder.html

Please specify the step you are referring to: Prerequisites

1.  npm ~install@ui5/uiveri5 -g~
_should be_ 
**npm install @ui5/uiveri5 -g**

2.  Additionally I was required to execute the below command too
**npm install sinon@latest**

**Comment by SarahLendle** [comment]
@MichaelCzcz I fixed this issue, so it can be closed. Thanks!
