### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by mikeginob** [SAPDocuments/Tutorials#5228]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-behavior.html

Step 2.  Trying to create a new behavior definition.  when i click NEXT I get the following internal error
![Error](https://user-images.githubusercontent.com/66082511/83170256-e0516700-a0d9-11ea-904c-ee1a424dbdf8.PNG)

**Comment by mervey45** [comment]
Hi @mikeginob,

which system are you using? Please make sure, you have the latest ADT installed:
https://tools.hana.ondemand.com/#abap

Best regards,
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
