### ISSUE TITLE
Enhance Behavior With Action and Validation

### ISSUE THREAD

**Issue by sedacrivity** [SAPDocuments/Tutorials#5229]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-behavior-action.html

Please specify the step you are referring to: step 4

For the action implementation - the generated code defines method 'acceptTravel' but the example code uses method 'set_status_completed'.

**Comment by mervey45** [comment]
Hi @sedacrivity ,

'acceptTravel' is the action that is needed for the method 'set_status_completed'. Therefore you need both.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by sedacrivity** [comment]
@mervey45 @MichaelCzcz 

You are misunderstanding my comment. 

I followed the tutorial using the latest updates of the eclipse addons and the source code generated is different from your tutorial.

The behaviour implementation class no longer has a method 'set_status_completed' but a method with the same name as the action.

    METHODS acceptTravel FOR MODIFY
      IMPORTING keys FOR ACTION Travel~acceptTravel RESULT result.


`CLASS lhc_Travel DEFINITION INHERITING FROM cl_abap_behavior_handler.
  PRIVATE SECTION.

    TYPES tt_travel_update TYPE TABLE FOR UPDATE zi_sds_travel_1_m.

    METHODS CalculateTravelKey FOR DETERMINATION Travel~CalculateTravelKey
      IMPORTING keys FOR Travel.

    METHODS validateCustomer FOR VALIDATION Travel~validateCustomer
      IMPORTING keys FOR Travel.

    METHODS validateDates FOR VALIDATION Travel~validateDates
      IMPORTING keys FOR Travel.

    METHODS acceptTravel FOR MODIFY
      IMPORTING keys FOR ACTION Travel~acceptTravel RESULT result.

    METHODS get_features FOR FEATURES
      IMPORTING keys REQUEST requested_features FOR Travel RESULT result.

ENDCLASS.`
