### ISSUE TITLE
Installing the Optional Data Warehousing Foundation Package for SAP HANA, express edition (Preconfigured VM)

### ISSUE THREAD

**Issue by Jeegnesh14** [SAPDocuments/Tutorials#5232]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-dwf-vm.html

Installing the Optional Data Warehousing Foundation Package for SAP HANA, express edition (Preconfigured VM)

Please advice how to connect to DWF using Eclipse IDE or WebIDE.

**Comment by JCurrie27** [comment]
Hi @Jeegnesh14 - I'm polling the teams for some connection advice for you. We'll respond here shortly.

**Comment by JCurrie27** [comment]
Hi - here's a blog post that will help you connect:
[https://blogs.sap.com/2019/02/17/how-to-install-dwf-on-sap-hana-express/](https://blogs.sap.com/2019/02/17/how-to-install-dwf-on-sap-hana-express/)

Kind regards,
