### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by schoelzm** [SAPDocuments/Tutorials#5233]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

Step 3: Deploy using cf push
Substep 2: Now, build and deploy both the database part and the actual application and add

Till this step i think all CLI commands are OS agnostic.
But the command "SET CDS_ENV=production" will only work on Windows.
Could you emphasize this? Or can you add a version for Linux (export CDS_ENV=production)?

I think that Linux-Beginners will have problems finding the "error" because the build will do a dev-build.

**Comment by iwonahahn** [comment]
Thank you for your message. Did you saw that it is possible to display the code blocks also for macOS / Linux? The commands for the operating systems are shown using different tabs. Does this help you?
![CDS_ENV](https://user-images.githubusercontent.com/22098308/84027659-9eed7100-a98f-11ea-9e4e-9b5612c4053e.png)

**Comment by schoelzm** [comment]
Ahh sorry, i missed that button. Sure, that helps.
