### ISSUE TITLE
Use SAP HANA as the Database for a CAP Java Application

### ISSUE THREAD

**Issue by vcanilkumar** [SAPDocuments/Tutorials#5236]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-hana-db.html

Please specify the step you are referring to
I'm trying to execute cds deploy --to hana:bookstore-hana
getting the below error
onnecting to the container "74E7E3DCEF384CE381EC0BD676900AF8"...

Deployment to container 74E7E3DCEF384CE381EC0BD676900AF8 failed - error: Could not connect to any host: [ zeus.hana.canary.eu-central-1.whitney.dbaas.ondemand.com:24932 - connect ECONNREFUSED 3.120.181.25:24932 ] [Deployment ID: none].

Error: Could not connect to any host: [ zeus.hana.canary.eu-central-1.whitney.dbaas.ondemand.com:24932 - connect ECONNREFUSED 3.120.181.25:24932 ]

Regards,
Anil

**Comment by maxstreifeneder** [comment]
Hi, 

seems like you are using the SAP internal canary landscape as deployment target. My assumption that external IPs are not whitelisted. Please try to contact the responsible team. 

Cheers,
Max
