### ISSUE TITLE
Build a Product List

### ISSUE THREAD

**Issue by fc158** [SAPDocuments/Tutorials#5237]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-scpms-starter-mission-03.html

Please specify the step you are referring to: 4

Missing validation button for Step 4, that is, the button where the user clicks after completing the step and, in this case, then going to the next tutorial (Step 4 is the last one in this tutorial)

Thanks for taking care of this

**Comment by fc158** [comment]
Issue occurring on MacOS Mojave and Catalina, with Safari, Firefox and Chrome; on Windows 10 Pro with Microsoft Edge, Firefox and Chrome

**Comment by thecodester** [comment]
Problem fixed. Thanks for letting us know.

@KevinMuessig Rules file had a question text without question tag. Double-check before publishing.
