### ISSUE TITLE
SAP HANA XS Advanced - Clone and run SHINE applications

### ISSUE THREAD

**Issue by ntrdeeplearning** [SAPDocuments/Tutorials#5238]
Tutorial URL: https://developers.sap.com/tutorials/xsa-ml-e2e-access-shine.html

Please specify the step you are referring to step 6, run index.html, getting following error.

Failed to resolve reference for provided property: 5c462bdc-9f16-44c4-ace6-42f7161ea285-8rh1u47pi0nywp5x-hana-shine-xsa#core_node_api#url

**Comment by jung-thomas** [comment]
You will get this error if you don't start the modules in the correct order or if you try to start the web module before the Node.js module is fully started (most likely the later item). Make sure the Node.js module is fully started without error before moving on to the next step.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
