### ISSUE TITLE
Map Message Structure

### ISSUE THREAD

**Issue by sunilchandra007** [SAPDocuments/Tutorials#5239]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-convert-message-structure.html

Download the source and target on your filesystem.

The link for source and target is not working in Step 1. Please check.

Regards,
Sunil Chandra

**Comment by gauthamkrishna-sap** [comment]
Hello,
Thank you for the feedback. We have fixed this and you will see the update shortly. 
Best Regards, Gautham

**Comment by xRicardinhox** [comment]
Hello Guathamkrishna
I try today to download the files, but when i did, they show the message 
**Sorry, the link has expired.
The link was set to expire after a certain amount of time. Please contact the person who shared this link with you.**

So how can i get the files.

**Comment by gauthamkrishna-sap** [comment]
Hi @xRicardinhox 
The links are updated.
Best,
Gautham

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
