### ISSUE TITLE
Create an SAPUI5 App from the Command Line

### ISSUE THREAD

**Issue by bufiku** [SAPDocuments/Tutorials#5240]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-sapui5-local.html

Please specify the step you are referring to: Step 5, Deploy the MTA archive
Deploying the generated archive can not be done with command 
_cf deploy_
An error message is returned: _'deploy' is not a registered command. See 'cf help -a'_ 
I've deployed with command:  _cf push mta_archives/myUI5App_0.0.1.mta_ as described in 
[https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html](https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html)

however, it still fails: 
_instance: de4a61fc-6023-4c8e-70fa-058d, index: 0, cell_id: 9d4b115f-ea58-43e8-ba55-118dea4fb61d, exit_description: Instance never healthy after 1m0.556s: Failed to make TCP connection to port 8080: connection refused; process did not exit, reason: CRASHED_

So it is deployed to the CF, but not correctly. And I am not familiar enough with deploying to find out where the problem is.

**Comment by IObert** [comment]
Hi,

`cf push` is a different command. This explains why it wasn't working for you. 
From the `cf deploy` error message, I would guess that the [multiapps plugin](https://developers.sap.com/tutorials/cp-cf-install-cliplugin-mta.html) hasn't been installed. Can you please double-check with `cf plugins` if you installed it?

**Comment by bufiku** [comment]
Hi @IObert ; 
Thanks! That indeed was the problem. What I think happened is that I did the tutorial for installation of the multiapp-plugin during another series and on another computer, and skipping it in my current series because it was marked copmleted. It works now, thanks! I'll close the issue.
