### ISSUE TITLE
Maintain a Communication Arrangement for Inbound Communication

### ISSUE THREAD

**Issue by iMilazzo** [SAPDocuments/Tutorials#5243]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

Please specify the step you are referring to **Step 3: Create communication user**

Well, I'm using the trial account to make this tutorial and I don't have the proper Business Catalog associated to my account (SAP_CORE_BC_COM).

Would you mind in provide me this access so I can continue to do this amazing tutorial ??

Thanks
Ivan

**Comment by mervey45** [comment]
Hi @iMilazzo ,

thank you for your message. You can't do this tutorial with the trial. You need a license for this tutorial. This tutorial is marked with the license key on the top left corner.

Best regards, 
Merve

**Comment by thecodester** [comment]
@mervey45 Please also add this to prerequisites.
