### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by jjmiquel** [SAPDocuments/Tutorials#5244]
Tutorial URL: https://developers.sap.com/tutorials/xsa-create-user-provided-anonymous-service.html

Hi there,
After creating the segment.hdbcds I get a build problem. It is not recognicing the  2nd code line 
"using PurchaseOrder.Item as Item;"

Best regards.
Juan José

**Comment by jung-thomas** [comment]
PurchaseOrder is local to your container and would have been created in a previous tutorial in this mission series?  Have you done that pre-requisite step?   If you go to your container in the Database Explorer do you see PurchaseOrder.Item in the tables?  Can you provide more details of the build error you are getting?

**Comment by jjmiquel** [comment]
just to complete the information.

In the last step, Number 8. This is the error message:
Deploying "$cds.merge/segments"...      Merged from "src/data/segments.hdbcds"      Error: com.sap.hana.di.cds: Cannot find artifact "PurchaseOrder" [1310042]       at "src/data/segments.hdbcds" (2:7-20)

Apparently it is not recognicing the building of the file "PurchaseOrderItem.hdbtable"

When I create a Test.hbbcds file. 
Context: Test
View: TestView

Add local objects: is empty
Add Active Objects: Throug the external service, "PRODUCT_SEGMENT"  I can find both:
     PurchaseOrder.Item in BD_1
     PORUDUCT_SEGMENT in PLAIN

Checking the previous Tutorials of this Mission,  Creating an HDI Module
In the last step: Step 6: Check data in the database explorer. I get the SQL EXEC right, but the option "Open Data" gives me an insufficient privilege message.

Best regards

**Comment by jjmiquel** [comment]
Here is a screen shot
![Pic PurchaseOrderItem](https://user-images.githubusercontent.com/29468321/83452675-246ca080-a427-11ea-9abd-331016522d80.PNG)

Thanks for your response Thomas.

**Comment by jung-thomas** [comment]
I think I know what happened. A little while back I update the prerequisite tutorial - https://developers.sap.com/tutorials/xsa-hdi-module.html and converted it from hdbcds to hdbtable.  HDBCDS is actually deprecated now.  But in this tutorial it is still using hdbcds and the using command is trying to reference the PurchaseOrder object as another HDBCDS.  

You might try rewriting this line as:
using "PurchaseOrder.Item" as Item; 

If that doesn't work then we might well have to rewrite this whole tutorial to convert from HDBCDS to HDBVIEW at this step.

**Comment by jjmiquel** [comment]
Thomas,
Yes it worked. The build went trough and I can see the "segments.SegmentsView".

Thanks for your help.
P.S.
The PurchaseOrder.ItemView is ttill giving me the "insufficient privilege" message. Is it Ok?
Sould I open another Issue.
Vielen dank

**Comment by jung-thomas** [comment]
I think PurchaseOrder.ItemView that is expected. It has a structured privilege on it right?  So without the tutorial steps to create a role and extend the default-access-role.hdbrole; you should be getting insufficient privilege on the view.

**Comment by jung-thomas** [comment]
I will update the tutorial to include the quotes around the item table USING statement.
