### ISSUE TITLE
Create Instance of SAP Cloud Platform Enterprise Messaging Service

### ISSUE THREAD

**Issue by bcschaich** [SAPDocuments/Tutorials#5248]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html

Please specify the step you are referring to

Step 1 does not work because of wrong JSON file.
Error message:
Service broker error: Service broker enterprise-messaging-service-broker failed with: Service broker parameters are invalid: [\{"message":"Unrecognized field","propertyPath":"version"}]

It did work with a much more simple JSON.

**Comment by pradeeppanda-sap** [comment]
Can you please share the json file which you are using.

regards
Pradeep

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
