### ISSUE TITLE
Create Queues and Queue Subscriptions for Enterprise Messaging

### ISSUE THREAD

**Issue by bcschaich** [SAPDocuments/Tutorials#5250]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-queue-queuesubscription.html

Please specify the step you are referring to

Sorry guys, but this completely does not work!
After step 1 the screen looks completely different and there is no way to create a queue!

**Comment by pradeeppanda-sap** [comment]
Hi,
When you subscribe the Enterprise Messaging using the subscription menu, and after that click on the "Go to application" link as mentioned in the tutorial, the Management Dashboard should open showing the messaging clients you have. You click on the client on which you want to work on, you will get to see the overview screen as has been mentioned.
Please let us know, if you are experiencing something different. An attachment will help in resolving the issue, if any.

regards
Pradeep

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
