### ISSUE TITLE
Create Service Consumption Model for Business Partner and Sales Order Item Cube

### ISSUE THREAD

**Issue by I322851** [SAPDocuments/Tutorials#5251]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-s4hanacloud-service-consumption.html

Please specify the step you are referring to step 3

It is mentioned:
 P_ExchangeRateType: EUR
P_DisplayCurrency: M

But it is the other way:
P_ExchangeRateType:M
P_DisplayCurrency: EUR

Also the binding condition is not mentioned.
Please have a look into it.

Best Regards,
Chaitra

**Comment by mervey45** [comment]
Hi @I322851 ,

thank you for your feedback. We'll update this as soon as possible.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
