### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by gcsfred2** [SAPDocuments/Tutorials#5255]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Please specify the step you are referring to

Step 2: Assign required roles
"Choose Add Role. In the Role Template dropdown list, select AuthGroup_Administrator and click on Save."

AuthGroup_Administrator is not available.
#

![Screenshot at Jun 03 13-02-40](https://user-images.githubusercontent.com/39340197/83666235-9e716680-a59a-11ea-999e-b9ae3cd7f188.png)

**Comment by Vikramkulkarni01** [comment]
Hi @gcsfred2, 

Thank you for contacting SAP Team. 

Could you please check  if you have multiple application identifiers, choose the application identifier that starts with **‘it’.**

Please try this and let me know how it works for you. 

I am looking forward to hearing from you. 

Regards, 
Vikram Kulkarni

**Comment by gcsfred2** [comment]
Hi, Vikram, thanks for your reply. There is no application identifier
starting with 'it'.
Also in Step 1 there is no "Process Integration" available. I'm attaching
screenshots.
Yesterday I also saw the list of application identifiers with many
identifiers, but none starting with 'it'.

Gustavo

**Comment by Vikramkulkarni01** [comment]
Hi  Gustavo, 

Thanks for reaching out to us. 

I understand your concern, could you please share with me the below details to investigate the issue further?

1. Global Account name & ID
2. Subaccount name and ID 
3. Error message or the screenshots. 

We truly appreciate your support and looking forward to hearing from you. 

Regards, 
Vikram Kulkarni

**Comment by Vikramkulkarni01** [comment]
Hi Gustavo, 

I checked from my end and I can see the application identifier starts with 'it' 

Below screenshot attached for your reference. 

![image](https://user-images.githubusercontent.com/59861880/84644294-9c08f800-af1c-11ea-83b5-e45e6349ff6d.png)
could you please check from your end and try to create a new subaccount and see how it works for you. 

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
