### ISSUE TITLE
Create Your First Integration Package and Integration Flow

### ISSUE THREAD

**Issue by gcsfred2** [SAPDocuments/Tutorials#5257]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-create-iflow.html

Please specify the step you are referring to

The page doesn't say how to access the workspace. That is, it has no URL.

**Comment by Vikramkulkarni01** [comment]
Hi @gcsfred2, 

You can see that there is a 

**Prerequisites**
You have provisioned and logged into your SAP Cloud Platform Integration tenant. For more information see [Set Up Your SAP Cloud Platform Integration Tenant](https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html)

Could you please perform and let me know how it works for you. 

Regards, 
Vikram Kulkarni

**Comment by gcsfred2** [comment]
Thanks for your message, Vikram,

My issue is not with the dependency of completing the setup of the
prerequisite. My problem is that the page of the subsequent tutorial in
this ticket does not give me a URL to start. In other words, I don't know
how to start this other tutorial.

Gustavo

**Comment by Vikramkulkarni01** [comment]
Hi Gustavo,

Could you please share me the screenshot, or short video reproducing the issue. 

This will really help me to assess your issue and provide you the solution. 

I appreciate your response. 

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
