### ISSUE TITLE
Getting started with the SAP API Business Hub

### ISSUE THREAD

**Issue by dirugadr** [SAPDocuments/Tutorials#5263]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-getting-started.html

Please specify the step you are referring to: 4
According to this step, I should get a record, but in my case, no one is returned.
See the attached image for details.
Thank you in advance

![image](https://user-images.githubusercontent.com/16107164/83757660-3462cb00-a647-11ea-9b9c-22cedc3a3713.png)

**Comment by IObert** [comment]
Thanks again for hinting us there. This issue was also caused by the new sandbox system. I updated the tutorial question as well as the validation of the answer. The changes should be live within the next 10-15min.
