### ISSUE TITLE
Testing API Business Hub APIs with Curl

### ISSUE THREAD

**Issue by dirugadr** [SAPDocuments/Tutorials#5265]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-test-locally.html

Please specify the step you are referring to: 5
I don't know what is the right answer to this step. I Copied the entire response from the CURL command, and however, it's marked as wrong.

curl --request GET  --url "https://sandbox.api.sap.com/successfactors/odata/v2/User?%24top=3&%24select=firstName%2ClastName%2CjobTitle"  --header "APIKey: RfqqwN30LQACVeCvw3cyoUhLqzA8mgX5"  --header "Accept: application/json"  --header "Content-Type: application/json"

![image](https://user-images.githubusercontent.com/16107164/83759234-a50ae700-a649-11ea-8db0-24ccea75e063.png)

Thanks in advance

**Comment by IObert** [comment]
You are right, it seems like the API Business Hub changed the way the data is being returned which broke the validation. Thanks for the hint!

I updated the validation and the fix should be live within the next 10-15 min
