### ISSUE TITLE
Create Data Model and Lock Object in SAP Cloud Platform ABAP Environment

### ISSUE THREAD

**Issue by gow-sap** [SAPDocuments/Tutorials#5266]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-lock-object.html

Hello, after lock object creation I got error message 'Use of ENQUEUE_... is not permitted'.
Not sure how to make it work.
Are there any hints for this issue?

Regards, 
Grzegorz Owczarek

**Comment by mervey45** [comment]
Hi @gow-sap ,

which system are you using? You need a license for this tutorial.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
