### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by Zimbo1990** [SAPDocuments/Tutorials#5269]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to

Step 4 : "Choose FioriDemo > webapp > view"
Missing BusinessPartners between FioriDEmo and webapp:
 FioriDemo > BusinessPartners  > webapp > view

**Comment by raz-korn** [comment]
Thanks for bringing this to my attention.
An update will be available soon.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
