### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by fegutieri** [SAPDocuments/Tutorials#5271]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Please specify the step you are referring to

Hello guys,

Just wanted to ask you to update the roles that you ask to be assigned to the role collection. If we only add those three mentioned in the tutorial, CPI does not allow to modify the package. In order to solve my issue (as well as other friends of mine) we used this SAP blog which mentions a few more.

https://blogs.sap.com/2019/10/01/creating-trail-account-for-cloud-platform-integration-on-cloud-foundry-environment-creating-user-credentials-and-connection-test/

I would appreciate if you could fix it since DEVELOPERS is supposed to be the main source of knowledge of SAP in terms of development.

Thanks a lot

**Comment by Vikramkulkarni01** [comment]
Hi @fegutieri , 

Thanks for reaching out to us. 

I understand your concern. The tutorial has been designed to execute the initial step and to complete the flow of steps. Hence those 3 roles are sufficient to execute all the steps mentioned in the tutorial. 

However, I have taken your suggestion and I will try to incorporate in upcoming tutorials if that needs modifying the package. 

Regards, 
Vikram Kulkarni

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
