### ISSUE TITLE
Connect to Microsoft Graph

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#5273]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-ms-graph-connect-graph.html

Step: Step 1: Load Microsoft Authentication Library

The example should be updated with the latest version of the library that is available [via Latest Microsoft CDN Version](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-core#via-latest-microsoft-cdn-version-with-sri-hash).

**Comment by MichaelCzcz** [comment]
@IObert What is the status on this issue?

**Comment by IObert** [comment]
We're still working on it

**Comment by IObert** [comment]
We decided to remove this tutorial as it's quite outdated and I still didn't find a working way to use the MS Graph from Fiori apps. 
Therefore, I'll close the issue

**Comment by gregorwolf** [comment]
But wasn't that a demo shown by @maxstreifeneder ?
