### ISSUE TITLE
Explore Data Preparation in SAP Data Intelligence, Trial Edition

### ISSUE THREAD

**Issue by condamoor-sap** [SAPDocuments/Tutorials#5275]
Tutorial URL: https://developers.sap.com/tutorials/dataintelligence-trial-v2-discovery-part03.html

Please specify the step you are referring to

Towards the end  when we want to overwrite the original file with the corrections (here you are overwriting Contacts_USA.csv), I get the error 
'The source dataset cannot be selected as the target'

How can I overwrite the old file with the prepared/corrected data?

**Comment by condamoor-sap** [comment]
I was doing this on DI 3.0.2 on prem. Same error on GCP and AWS stores.

**Comment by dimvor** [comment]
Do you have a Contacts.csv file in your CLOUD_STORAGE connection? The Contacts_USA.csv should have been created as a copy of this file in [Part 1 -> Step 2](https://developers.sap.com/tutorials/dataintelligence-trial-v2-discovery-part01.html)

**Comment by condamoor-sap** [comment]
Hi Dimitri,
I had my own CSV file (enriched_rev.csv) in S3 with a Country column.
See screenshot below of the error. Am trying to persist the changes I made to the Country column back on the original file like you did.
Am using DI 3.0.2 on-prem. Same error on GCS as well.

[cid:image002.jpg@01D63D8D.178E8EB0]

**Comment by dimvor** [comment]
Hi Ravi, the tutorial is meant to be used with the SAP DI Trial Edition which comes with the required Contacts.csv file. For your convenience I've attached it here. 
[Contacts.csv.zip](https://github.com/SAPDocuments/Tutorials/files/4748099/Contacts.csv.zip)

**Comment by condamoor-sap** [comment]
Hi Dimitri,
I was repeating the Tutorial with my own dataset. In principal, I am assuming you should be able to overwrite the original data with the changes so that we can go thru’ the Rules to validate the data correction.
Anyways, I will debug further..

Thanks
-ravi

**Comment by MichaelCzcz** [comment]
@dimvor Any updates?

**Comment by dimvor** [comment]
@MichaelCzcz You can close the issue
