### ISSUE TITLE
Create Workflow Instances for Process Visibility

### ISSUE THREAD

**Issue by Cattiebri** [SAPDocuments/Tutorials#5281]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-processvisibility-model-workflow.html

Please specify the step you are referring to: Step 1. 

It is very unclear as to where to find the tiles for Monitor Workflow and Inbox. The instruction I had in this tutorial until now was in one workflow, which did not tell me to create the tiles stated above. Now suddenly I need to use those tiles. Do I have to add them to my workflow? Do I need to create a separate workflow and somehow connect it to this? I`ve been sitting on this step for 10 hours now and do not have a solution to this. Please, tell me exactly how to proceed to this step - exactly how can I add the needed tiles to FLPforPVS project, cause from the information here it is not clear at all.

**Comment by Deeksha-R** [comment]
@Cattiebri Could you let me know if the My Inbox and Monitor workflows tiles are created using the procedure mentioned in the prerequisite? Basically, you would need to create these tiles using either SAP Business Application Studio or SAP Web IDE Full-Stack. Here is the link on how you configure these tiles: 
https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/97c079f9317c42bba31cc9ca9d4cc7c3.html

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
