### ISSUE TITLE
Create Data Model and Lock Object in SAP Cloud Platform ABAP Environment

### ISSUE THREAD

**Issue by sedacrivity** [SAPDocuments/Tutorials#5282]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-lock-object.html

Please specify the step you are referring to: 5

The used standard association view 'I_BusinessUser' is not whitelisted in ABAP cloud so it is not permitted to be used:

The following error is shown:

_Use of Entity I_BusinessUser is not permitted.	
ABAP Syntax Check Problem_

```
define root view Z_I_ROOM_XXX as select from zroom_xxx as room
  association [0..1] to I_BusinessUser as _SAPSysAdminDataChangeUser on _SAPSysAdminDataChangeUser.UserID = room.lastchangedbyuser
```

**Comment by mervey45** [comment]
Hi @sedacrivity ,

you need a licensed user to do this tutorial. This won't work with a trial user. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
