### ISSUE TITLE
Installing SAP HANA, express edition + Apps, with Docker - Root Access /etc/hosts

### ISSUE THREAD

**Issue by diraschk** [SAPDocuments/Tutorials#5284]
Hi Experts,

https://developers.sap.com/tutorials/hxe-ua-install-using-docker-xsa.html

we need to change the **hosts**-file inside of the HXE-Docker Instance.
The issue is we do not have **root access** for doing this. 

 **hxeadm@hxehost:/usr/sap/HXE/HDB90> cat /etc/hosts
172.30.0.2      hxehost**

Pls., would you only let me know, if this is a "No-Go" for you?
If so, then we unfortunately are not able to work with Docker. 

Any help would be great!
BR, Dirk

**Comment by aptk001** [comment]
Hi Dirk: Would you be able to post this issue on the HXE community Q&A page? This current GitHub repository is for reporting problems in the tutorial text, and it looks like your issue should take advantage of the community support model. The Q&A page receives much more traffic, and other users may be able to provide answers immediately.

To log your questions on the Q&A page:
•	Go to [https://answers.sap.com/questions/ask.html](https://answers.sap.com/questions/ask.html)
•	Add a **Title**. Enter your GitHub question in the **Fill in the details...** form.
•	In **Select Primary Tag**, search for "express". Select **SAP HANA, express edition**.
•	Click **Submit your Question**.

**Comment by diraschk** [comment]
@aptk001 Thanks for your indirect help! Glad to see that it works. :) (Sorry, I'm new with docker...)
https://stackoverflow.com/questions/28721699/root-password-inside-a-docker-container#:~:text=You%20can%20log%20into%20the,E.g.&text=root%20(id%20%3D%200)%20is,developer%20can%20create%20additional%20users.
