### ISSUE TITLE
Create an app consuming calculation view using Hibernate on SAP HANA

### ISSUE THREAD

**Issue by ralphsteurer** [SAPDocuments/Tutorials#5285]
Tutorial URL: https://developers.sap.com/tutorials/hana-hibernate-calculation-view.html

Please specify the step you are referring to

Is there an overview of the most common syntax for querying calc views? For example how to submit parameters to a calc view? I was able to do it via native query, but not with a typed query. thanks!

**Comment by jung-thomas** [comment]
This question is not related to the content of the tutorial itself. This forum is only for problems/issues with the tutorial content. For general product and technical questions please use the SAP Community Q&A.
