### ISSUE TITLE
Set Up Business Rules for Determining Equipment

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Tutorials#5286]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-businessrules.html

Please specify the step you are referring to:

**_Step 2_**:   Import business rules

(1)Click Design icon and select Import Project from API Business API Hub.
(2)In the popup, do the following:
In the System field, select APIHub or the name you entered while configuring the system.
From the options shown in the Content Package Name dropdown, choose Equipment Determination Business Rules.
Choose Go.
Select the latest version of the project named Equipment Determination Rules.
Choose Import.

Actual Result : 
After import, i am getting " Bad Gateway error" even after trying couple of times .
This issue is specific to "US" region in trial account

**Comment by ArchanaShukla** [comment]
Can you check this again. I tried in US sub-account and it works fine for me. May be some temporary issues with US trial.

**Comment by ArchanaShukla** [comment]
@mounikat987 - can you try this again. I able to import the the business rules. May be some temporary issue with US trial.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
