### ISSUE TITLE
Error on testing from SAP API hub - Business Rules

### ISSUE THREAD

**Issue by NamrataSrinivas** [SAPDocuments/Tutorials#5287]
Hi , 
I get the below error when i try to test business rules service from API hub. The service is deployed on CLoud foundry

Tutorial followed : https://developers.sap.com/tutorials/cp-cf-businessrules09-test-apis.html

{
  "error": "invalid_token",
  "error_description": "JWT signature validation failed"
}

**Comment by VandanaVasudevan** [comment]
Hi Namrata,

Can you please check if you've entered the correct values for clientID, client secret, and token URL when you configured the test environment on SAP API Hub?

You could also try generating a new service key in the cockpit and using the new credentials. Please do let me know if this isn't working.

Best Regards,
Vandana

**Comment by NamrataSrinivas** [comment]
Hi Vandana , 

I did the changes and am able to test . Thanks!!! 
Also can you help me do the test via postman

**Comment by VandanaVasudevan** [comment]
Hi Namrata,

Sure. You can use the following steps:
1) Get an {{access token}} by sending a post request using **{{runtimeurl}}/oauth/token**.
2) To invoke the rule service, send a get request using **{{runtimeurl}}/rules-service/rest/v2/rule-services**  using the following values:
 a. **Authorization**: No Auth
 b. **Header**: Authorization
     Key: Bearer {{access token}}
 c. **Body**: Same as the body mentioned in SAP API Business Hub.

I hope this helps.

Best Regards,
Vandana

**Comment by NamrataSrinivas** [comment]
Thanks Vandana . It helps . 
I was trying to embed Business Rules in ui5 app . But the destinations for runtime and repository are not created automatically . Can you provide the destination config 
Thanks 
Namrata

**Comment by VandanaVasudevan** [comment]
Hi Namrata,

Sorry for the delay in reply. I was on vacation for two weeks. 

Can you try following the procedure in this document:
https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/783fa1c418a244d0abb5f153e69ca4ce.html

Best Regards,
Vandana

**Comment by NamrataSrinivas** [comment]
Hey Vandana ,

Thanks a lot for your response . I was able to embed business rules in CF . Got to know that destinations are not needed for Cloud foundry . Now i am able to embed
