### ISSUE TITLE
Use Machine Learning to Extract Information from Documents

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5288]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dox-swagger-ui.html

**Step 6: See extracted fields**- Here instead of GET /document/jobs/{uuid} endpoint mentioned in the tutorial, I can see the GET /document/jobs/{id} endpoint in the Swagger UI as below
![image](https://user-images.githubusercontent.com/65999547/84504622-e0f11c80-acd9-11ea-9e33-18f298376879.png)

Please change this in the Tutorial.

Thanks & Regards,
Priyanka

**Comment by Juliana-Morais** [comment]
Hi Priyanka,

The tutorial has already been updated with the latest endpoint details.

Best regards,
Juliana

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
