### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Tutorials#5289]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Issue : In trial US region
-In Step 4  Provision SAP Cloud Platform Integration Tenant : on 4th instruction screenshot is showing Provision button, but in application there is no Provision button instead there is "Activate" button.

**Comment by Vikramkulkarni01** [comment]
Hi Mounika,

Thanks for the update. its already in our road map and we are working towards adopting the screenshots of these tutorials to the latest one.

You can see these changes in the coming days.

I hope it will suffice your concern.

Regards,
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
