### ISSUE TITLE
Create Table Persistence and Generate Data

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5291]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-persistence.html

Step 1: Create ABAP package

Here the  ZLOCAL component was added already in step2. Hence did not get the another wizard as below 
![image](https://user-images.githubusercontent.com/50734023/84510806-3bdb4180-ace3-11ea-9f5c-49a51cdfa782.png)

Instead got the wizard where ZLOCAL was already mentioned as shown below,
![image](https://user-images.githubusercontent.com/50734023/84511022-8eb4f900-ace3-11ea-9959-b6027e097530.png)

Regards,
Nidhi

**Comment by mervey45** [comment]
Hi @NidhiMurkute ,

thank you for your feedback. Seems like a new version of the wizard. We'll update this as soon as possible.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by NidhiMurkute** [comment]
The tutorial is not updated yet with mentioned screenshot
