### ISSUE TITLE
Enhance Behavior With Action and Validation

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5292]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-behavior-action.html

Step 3: Create implementation class
After setting the cursor before the implementation class and pressing Ctrl +1  did not get suggestions for creating implementation class as below
![image](https://user-images.githubusercontent.com/50734023/84512060-0fc0c000-ace5-11ea-9ac5-803333ca0f6e.png)

Instead got  the suggestions after click on the bulb icon present on the first line. 

Regards,
Nidhi

**Comment by mervey45** [comment]
Hi @NidhiMurkute ,

set your curser before your class ZCL... Then it should work. It should not be set before the managed... .

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
