### ISSUE TITLE
No Option to select the Subaccount after starting the recipe

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5293]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html

**Step 1: Setup services in your account using Recipe**- Here in the Intelligent BPM Setup recipe, there is no option to select the sub-account in which the recipe should start in. 
Suppose if an end user has multiple subaccounts, this recipe does not provide the option to select the sub account in which this should start.

So from an end user perspective, there should be an option to select the sub account as soon as we click on Start recipe

Thanks & Regards,
Priyanka

**Comment by ArchanaShukla** [comment]
Hello Priyanka,
Only if you have more than 1 sub-accounts or spaces then it will ask, other wise it will continue with the existing sub-account and space. This is for better user experience.

**Comment by I537413** [comment]
Hi Archana,

In my global account, currently i have 2 subaccounts- One on EU region and the other one in US region.
After starting the recipe, i got a link to navigate to subaccount, But on selecting that it navigated directly to my EU region account, I didnt get any option here.

Thanks,
Priyanka

**Comment by ArchanaShukla** [comment]
@thecodester - please close this issue. The guidance has been given to the reporter through call.
