### ISSUE TITLE
Build and Deploy of cf-onboarding-sample fails

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5294]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html

**Step 3: Build and deploy sample application**- Here noticed 2 issues as below:

**During Build:**
Here when we build the cf-onboarding-sample, it fails with the below error- 
![image](https://user-images.githubusercontent.com/65999547/84528486-63d79e80-acfd-11ea-8aa5-383b836eb614.png)
Here the mta.yaml file is missing the build parameters(supported-platforms and build-result) which is a requirement to build with the new MTA build tool. 
After adding these parameters to the mta.yaml as below, the **build is successful**
![image](https://user-images.githubusercontent.com/65999547/84528808-f7a96a80-acfd-11ea-8028-27a82b11a9db.png)

**During Deploy:**
After the build is successful, when we deploy the mtar to the cloud platform, the build fails with the below error log:
**Error building content deployment configuration for module: "onboarding": Controller operation failed: 404 Not Found: Service instance workflow not found.**
This is because the mtar is searching for the service instance by the name **workflow**, but when we start the recipe the name of the instance created is **default_workflow** as below:
![image](https://user-images.githubusercontent.com/65999547/84529272-cb421e00-acfe-11ea-99e0-5e014c2da3de.png)
Due to this name mismatch,the deployment fails. After changing the name of the instance in the mta.yaml, when we build and deploy again, the **deployment is successful**

Please include these changes in the code available in the Github or include the steps in the Tutorial to add these changes.

Thanks & Regards,
Priyanka

**Comment by ArchanaShukla** [comment]
Hello Priyanka,
Thanks, changes done. Can you try once again
