### ISSUE TITLE
A few roles are missing even after using the Intelligent BPM Setup recipe

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5295]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-4-visibility.html

**Step 1: Create a business scenario**- Here when we click on the Configure Visibility Scenarios app, got the below permission error:
![image](https://user-images.githubusercontent.com/65999547/84530049-1dd00a00-ad00-11ea-9d63-1f009ed3f4b1.png)

Later noticed that below process visibility roles were missing for my user-
PVAdmin, PVDeveloper, PVEventSender, PVOperator, PVTenantOperator

These roles should have been added when the recipe was used. But these roles were missing due to which the above shown permission error was displayed.

Please include these roles to be added when we start the recipe or include a step in the tutorial to add these roles.

Thanks & Regards,
Priyanka

**Comment by ArchanaShukla** [comment]
Hello Priyanka, 
Was the process visibility entitlement assigned in your account?

**Comment by I537413** [comment]
Hi Archana,

yes the process visibility entitlement was assigned to my account.

Thanks & Regards,
Priyanka

**Comment by ArchanaShukla** [comment]
The hotfix is provided for the recipe. 

@thecodester - please close the issue
