### ISSUE TITLE
SAP HANA, express edition + Apps, with Docker - XSA - xs create space

### ISSUE THREAD

**Issue by diraschk** [SAPDocuments/Tutorials#5296]
Hi,
we tried to create a Space within the XSA, but it fails.

hxeadm@hxehost:/usr/sap/HXE/HDB90> xs create-space DEV
FAILED: Failed to determine mdcdispatcher XSA mode availability

Saw this behavior in the last two images.
Any idea how to fix this?

**Comment by jung-thomas** [comment]
For technical support issues using HANA Express, please post your question in the SAP Community Q&A, https://answers.sap.com/tags/73555000100800000651

**Comment by diraschk** [comment]
maybe someone has a solution. 
https://answers.sap.com/questions/13174374/sap-hana-express-edition-apps-with-docker-xsa-xs-c.html
