### ISSUE TITLE
SAP HANA XS Advanced, Creating a Node.js Module - Authorization Error

### ISSUE THREAD

**Issue by bruceleong** [SAPDocuments/Tutorials#5297]
Tutorial URL: https://developers.sap.com/tutorials/xsa-xsjs-xsodata.html

Please specify the step you are referring to

Step 6 - Execute the XSJS Module

Having an issue with authorization.

mta.yaml
ID: HANA_APP
_schema-version: '2.1'
version: 0.0.1
modules:
  - name: web
    type: html5
    path: web
    requires:
      - name: UAA-service
      - name: core_xsjs_api
        group: destinations
        properties:
          name: core-xsjs-backend
          url: '~{url}'
          forwardAuthToken: true
  - name: db
    type: hdb
    path: db
    requires:
      - name: hdi_db
  - name: core_xsjs
    type: nodejs
    path: core_xsjs
    provides:
      - name: core_xsjs_api
        properties:
          url: '${default-url}'
    requires:
      - name: UAA-service
      - name: hdi_db
      - name: db
resources:
  - name: UAA-service
    type: com.sap.xs.uaa-space
  - name: hdi_db
    parameters:
      config:
        schema: DB
    properties:
      hdi-container-name: '${service-name}'
    type: com.sap.xs.hdi-container

package.json 

{
  "dependencies": {
    "@sap/xsenv": "^2.0.0",
    "@sap/xsjs": "^5.2.0"
  },
  "description": "my description",
  "files": [],
  "main": "server.js",
  "name": "nodejs",
  "scripts": {
    "start": "node server.js"
  },
  "engines": {
    "node": "10.x"
  },
  "version": "1.0.0"
}

![Screen Shot 2020-06-12 at 4 58 47 PM](https://user-images.githubusercontent.com/32654479/84554739-29a2d880-acce-11ea-9cba-99a4768fea82.png)

**Comment by jung-thomas** [comment]
Please provide some details.  Are you testing the page via the XSJS module URL or the Web (app router) URL.  If via the Web app do you get prompted for your user name and password? If you are referring to the very last action in the tutorial when you test the XSJS module directly, you are supposed to get an unauthorized error. The App router provides the redirect to the UAA service and therefore the logon token. Without it you should not be able to access the XSJS module directly.

**Comment by bruceleong** [comment]
Apologies. Getting the correct response from the xsjs and web application. Missed the step of running web after running node app. Thank you
