### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#5298]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html

Please specify the step you are referring to - Step 9

The multi choice question at the end of the tutorial does not work properly. 

![image](https://user-images.githubusercontent.com/38389079/84562314-eeb8a780-ad96-11ea-82d1-1e4d3aa83dcc.png)

The answer is [Design View] but it comes up stating "Sorry thats incorrect". Instead when I choose [Operations View] it says that is Correct. I finished the tutorial but this is the wrong answer. 

thanks & kind regards
Phil Cooley

**Comment by thecodester** [comment]
I'll let @gauthamkrishna-sap speak on the correct answer, but the tutorial was written such that Design View is not the correct answer -- but it sure looks like Design View is correct.

@gauthamkrishna-sap Please also fix the bad indention of the picture in steps 9 and 7

**Comment by gauthamkrishna-sap** [comment]
Hi Phil & Daniel,
Design view is indeed the right answer. 
I will fix these images and questions soon.
Best Regards,
Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
