### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#5299]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html

Please specify the step you are referring to - Step 8 testing from Postman

When trying to test the call from Postman it always fails 

![image](https://user-images.githubusercontent.com/38389079/84562939-4ce78980-ad9b-11ea-970a-4bb69c14da26.png)

It does not even hit the CPI tenant because I receive a 403 Forbidden. I set Basic Auth and then enter my email address (userid for Cloud Foundry) followed by my password. 

Please assist. 

THanks & Kind Regards
Phil Cooley

**Comment by gauthamkrishna-sap** [comment]
Hi Phil,

You need to create a service instance and a service key. Then, use those credentials for connecting to your endpoint using postman. 
Please refer to step 5 in this tutorial: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Thanks for the feedback as well. I will enhance this tutorial with those steps. 

Best Regards,
Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
