### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#5300]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to - Step 6 Test the APplication 

When I run the application I receive an error message

![image](https://user-images.githubusercontent.com/38389079/84589526-6c051a80-ae72-11ea-8d28-64ed7f056ad9.png)

I also had an additional option during Step 3. It asked me whether or not the app was a Standalone App or Deploy to SAP Cloud Platform?? Which was not included in the tutorial so I think there is a missing step somewhere in this process. 

Please let me know how I can continue. 

thanks & kind regards
Phil Cooley

**Comment by raz-korn** [comment]
Hi @pjcools ,

Thanks for the feedback.

- The additional step you refer to is for selecting the type of Approuter to be used. It's a new step that was recently released and will be added in an update to this tutorial. For now, you should use the Standalone Approuter option.

- We're familiar with the error message that you and investigating the best approach to overcome it.  as a workaround, you can right-click the folder fioridemo-approuter and select "Open in Terminal".  In the terminal, execute the command "npm install".

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
