### ISSUE TITLE
Column name has changed- Set Up SAP Mobile Cards

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5301]
Open https://developers.sap.com/tutorials/cp-mobile-cards-setup.html#b3213ab1-702d-4891-bf8d-e011f21ea8bf

Step 3- Column name changed

In Document- Nullable
In actual- Can be nulled
![1](https://user-images.githubusercontent.com/7221229/84602257-b226a200-aea3-11ea-83c8-fe36db6e915c.PNG)

**Comment by sandeep-tds** [comment]
Hi @Mukesh-50,

Thank you for raising the issue. We will update the screenshot.

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
