### ISSUE TITLE
New Field and button added in 

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5302]
Open tutorial https://developers.sap.com/tutorials/cp-mobile-cards-setup.html#b3213ab1-702d-4891-bf8d-e011f21ea8bf

New tab- Event tab added 
New button- Integrate SAP Cloud Platform workflow 

![image](https://user-images.githubusercontent.com/7221229/84602301-f4e87a00-aea3-11ea-9450-92cf82e1321e.png)

**Comment by sandeep-tds** [comment]
Hi @Mukesh-50,

Thank you for raising the issue.
The new tabs don't have a bearing on this tutorial. Thus, we will update the tutorial once we ask users to click on those options.

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
