### ISSUE TITLE
New Link added- Set Up SAP Mobile Cards

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5303]
Open https://developers.sap.com/tutorials/cp-mobile-cards-setup.html#b3213ab1-702d-4891-bf8d-e011f21ea8bf

New link added- Use a Cloud foundry service  

![image](https://user-images.githubusercontent.com/7221229/84602362-6fb19500-aea4-11ea-9797-996e1e1a998c.png)

**Comment by sandeep-tds** [comment]
Hi @Mukesh-50,

Thank you for raising the issue. We will update the screenshot.

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
