### ISSUE TITLE
Behavior after action field updated- Create Cards with Actions to Enable Workflows

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5304]
Open url https://developers.sap.com/tutorials/cp-mobile-cards-action.html#799cdb07-1186-43d6-a95e-a5eef8f6f25e

Actual Result- Behavior after action field is coming on right side

![image](https://user-images.githubusercontent.com/7221229/84602530-a6d47600-aea5-11ea-902e-f5f91bbb9cd9.png)

**Comment by sandeep-tds** [comment]
Hi @Mukesh-50,

Thank you for raising the issue. We will update the screenshot.

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
