### ISSUE TITLE
New Column added called parameter

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5305]
Open https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html#3a79a274-7d8b-4b30-b65f-a4b63050c5f1

In welcome card page, new tab Parameter added

Remark- Screenshot has to be updated

![image](https://user-images.githubusercontent.com/7221229/84622445-a4503b80-aefa-11ea-8264-bf003cdc402f.png)

**Comment by sandeep-tds** [comment]
Hi @Mukesh-50, 

Thank you for raising the issue. We will update the screenshot.

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
