### ISSUE TITLE
Cloud Destination section added

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5306]
Open https://developers.sap.com/tutorials/cp-mobile-cards-setup.html

Under mobile connectivity section> configuration > New section cloud destination present

Remark- Screenshot has to be updated

![image](https://user-images.githubusercontent.com/7221229/84622834-9353fa00-aefb-11ea-998d-2d8ac5159965.png)

**Comment by sandeep-tds** [comment]
Hi @Mukesh-50, 

Thank you for raising the issue. We will update the screenshot.

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
