### ISSUE TITLE
Reject status is not present

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5307]
Open https://developers.sap.com/tutorials/cp-mobile-cards-action.html#8a84954e-8669-43ff-9905-e74ef6e224ea

Step 8- Cross verify status update in the back end

Only accepted status is coming twice- Rejected, Invalid data record is not present.

![image](https://user-images.githubusercontent.com/7221229/84622886-b41c4f80-aefb-11ea-8e72-3d51305c9191.png)

**Comment by sandeep-tds** [comment]
Hi @Mukesh-50, 

Thank you so much for raising the issue. 

Can you please specify the actions you performed? 
You are required to perform Accept on one Card and Reject another. 

When you click on Reject, you are prompted to enter a Reason for Rejection. 
Did you see this dialogue? 

Also, can you please verify that the body of your Reject Action is as follows.
`{"LifeCycleStatusName": "Rejected: ${reasonForRejection}", "LifeCycleStatus": "R"}`

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
