### ISSUE TITLE
Name mismatch of the application

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5308]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html

Step 1: Download a sample application- Here the name of the app given is Employee Onboarding but after download the name of the app imported into the webide is cf-onboarding-sample.

Please change this in the tutorial.

Thanks & Regards,
Priyanka

**Comment by ArchanaShukla** [comment]
The name of the GitHub project is a technical name, but the content is of employee onboarding. It anyways says Employee Onboarding sample application with relates to the project name. I would like to keep it as is. 

@thecodester - please close this issue
