### ISSUE TITLE
Screenshot for the Workflow scenario issue

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5309]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-4-visibility.html

Step 2: Add a workflow- Here the screen shot is old. Now under Processes creation, we get 3 options in the drop down as below.
![image](https://user-images.githubusercontent.com/65999547/84624886-d748fe00-aeff-11ea-9225-daf884971419.png)
Please change this in the tutorial

Thanks & Regards,
Priyanka

**Comment by ArchanaShukla** [comment]
Updated the screenshot.

@MichaelCzcz - please close the issue
