### ISSUE TITLE
Different step for MacOs to set environment variable

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5310]
tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html
Step 3: Deploy using cf push:
Sub-step 2:
command "SET CDS_ENV=production && cds build" works fine for windows, but for MacOS, "export CDS_ENV=production && cds build" works!
for MacOS, this step is not mentioned in the tutorial.

Also, three commands need to be executed one by one, that can also be mentioned as it is mentioned everywhere else in the document.

<img width="1237" alt="Screenshot 2020-06-15 at 12 25 09 PM" src="https://user-images.githubusercontent.com/66831161/84628144-c00d0f00-af05-11ea-82af-8cc98e57298e.png">

Thanks,
Shubham

**Comment by iwonahahn** [comment]
Did you saw that it is possible to display the code blocks also for macOS / Linux? The commands for the operating systems are shown using different tabs. Please refer to this issue https://github.com/SAPDocuments/Tutorials/issues/5233#issuecomment-640557562. Does this help you?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue
