### ISSUE TITLE
Update the tutorial page with latest UI Changes

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5316]
Tutorial URL:https://developers.sap.com/tutorials/cp-portal-cloud-foundry-url-app.html

Launchpad UI looks changed for groups, earlier is used to come at header level
now coming at page level (refer to the attached screenshots where group "SAP" is coming at the header level in one, while at the page level in the other).

<img width="1680" alt="New-UI_Group-SAP" src="https://user-images.githubusercontent.com/66831161/84656476-62da8300-af30-11ea-931f-6be19df8846a.png">
<img width="1201" alt="OLD-UI_Group-SAP" src="https://user-images.githubusercontent.com/66831161/84656487-679f3700-af30-11ea-854d-a74abe14e6e0.png">

Please update the screenshots in the tutorial.
Thanks,
Shubham

**Comment by LindsayBert** [comment]
Hi
The name of the group appears both in the header and on the page if there are other groups.  See that here I have other groups too:
![groups](https://user-images.githubusercontent.com/33653038/87245737-853cbf00-c450-11ea-8735-bd4763a9b9b2.png)

**Comment by IrisSasson** [comment]
Hi , this issue was fixed. Please confirm and close or comment

**Comment by i353590** [comment]
Hello,
Please refer to the 1st screenshot attached.!
the issue is that groups are not coming under headers.. if you observe the group name "SAP" it comes on the page, which is fine, but it doesn’t come in "headers".
Please check once again.

Thanks & Regards,
Shubham

**Comment by thecodester** [comment]
@LindsayBert Can you handle or answer issue?

**Comment by LindsayBert** [comment]
Hi  We will be updating the Portal tutorials in the next 2 weeks according to the new Launchpad and will look at this.

Thanks Lindsay

**Comment by MichaelCzcz** [comment]
@LindsayBert Can I close this issue?

**Comment by IrisSasson** [comment]
Hi Michael
Yes, we are rewriting all tutorials these days. All comments on our tutorials are less relevant

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
