### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by umitcel** [SAPDocuments/Tutorials#5317]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

I am referring to step 2. 

I want to deploy UI part also but how can I do it. I tried several methods by trial-error but I couldn't manage. Can you please help?

**Comment by iwonahahn** [comment]
What do you mean with "UI part"? What is your concrete issue? In step 2 we only describe how to enter the [SAP Cloud Platform Trial Cockpit](https://cockpit.hanatrial.ondemand.com/cockpit/) and how to logon with the [command line client](https://developers.sap.com/tutorials/cp-cf-download-cli.html). As mentioned in the prerequisites you need a Cloud Foundry Trial Subaccount and also you can find there links to reference docs.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
