### ISSUE TITLE
Subaccount UI Update- Build Your First Portal Site

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5318]
Open https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Step 1- Subaccount details page- 

Remark- Screenshot has to be updated

Expected 
![image](https://user-images.githubusercontent.com/7221229/84732404-40407c80-afb9-11ea-8226-2808a9c547df.png)

Actual
![image](https://user-images.githubusercontent.com/7221229/84732410-46365d80-afb9-11ea-9568-497ec25ea6a7.png)

**Comment by LindsayBert** [comment]
Already updated - this tutorial was updated about a month ago

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
