### ISSUE TITLE
Subaccount Home page update- Build Your First Portal Site #5318

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5319]
Open https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Remark- Screenshot has to be updated

Expected 
![image](https://user-images.githubusercontent.com/7221229/84732620-c9f04a00-afb9-11ea-89d4-6a6bb9cb877f.png)

Actual
![image](https://user-images.githubusercontent.com/7221229/84732551-a200e680-afb9-11ea-8303-3d7b56c93cd6.png)

**Comment by LindsayBert** [comment]
Tutorial already updated a while back

**Comment by thecodester** [comment]
@LindsayBert I still see the "expected" screenshot

**Comment by LindsayBert** [comment]
done

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
