### ISSUE TITLE
Subscription Page updated- Build Your First Portal Site

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5321]
Open https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Navigate to Subscription page UI

Remark- Screenshot has to be updated

Expected
![image](https://user-images.githubusercontent.com/7221229/84732840-57cc3500-afba-11ea-8d40-ed114c2c96a0.png)

Actual
![image](https://user-images.githubusercontent.com/7221229/84732845-5ac72580-afba-11ea-8913-f17c856dff87.png)

**Comment by LindsayBert** [comment]
Hi
I've just checked the tutorial and the screenshot already seems to be updated??
![image](https://user-images.githubusercontent.com/33653038/87244702-bfee2980-c447-11ea-8730-c0077492984d.png)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by LindsayBert** [comment]
Done
