### ISSUE TITLE
2 role collection missing-Build Your First Portal Site

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5322]
Open https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Navigate to assign role collection section

Expected 

![image](https://user-images.githubusercontent.com/7221229/84732992-b396be00-afba-11ea-9fa7-0033c7284d5b.png)

Actual
![image](https://user-images.githubusercontent.com/7221229/84732998-b72a4500-afba-11ea-8f95-8d3107456273.png)

**Comment by IrisSasson** [comment]
I need to verify on a new trial account. Will work on this later. In general, this is not related to the flow, and different services update this issue and we need to discuss if this must be accurate in the screenshot

**Comment by MichaelCzcz** [comment]
@IrisSasson Any updates?

**Comment by IrisSasson** [comment]
Hi 
We plan an update for the tutorials in the coming 2 weeks, 
Thanks
Iris.

**Comment by IrisSasson** [comment]
Hi
Please use the Launchpad tutorials at: https://developers.sap.com/mission.portal-cf.html

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
