### ISSUE TITLE
Create an SAP Cloud Platform ABAP Environment Trial User

### ISSUE THREAD

**Issue by NidhiM9** [SAPDocuments/Tutorials#5327]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html

Please specify the step you are referring to : Step 5: Create ABAP cloud project
Region: US
1.Create ABAP cloud project
2.Select service key and import the same > Next
See that there is an issue with login though its getting authenticated, but repeats in loop displaying the error as below, and unable to complete the scenario.
![LogonIssueAbap](https://user-images.githubusercontent.com/59353373/84762798-e3f55100-afe8-11ea-88d3-129e9cfb7296.png)

Regards,
Nidhi

**Comment by mervey45** [comment]
Hi @NidhiM9 ,


please check your global account in your cockpit. We have a new feature. Our region is US VA only. Please check if you have a global account in this region. I'll update this asap. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
