### ISSUE TITLE
Issue while running mbt build..Cannot find module "@sap/node-jwt/build.js"

### ISSUE THREAD

**Issue by sooraj2589** [SAPDocuments/Tutorials#5328]
After successfully installed mbt, I have tried to run mbt build on my project code. But its getting below error

Error: Cannot find module '/root/MTA/DevOpsSample/node_modules/@sap/node-jwt/build.js'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:188:16)
at bootstrap_node.js:609:3
.npm WARN DevOpsSample@0.0.1 No description
npm WARN DevOpsSample@0.0.1 No repository field.
npm WARN DevOpsSample@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sap/node-jwt@1.6.9 install: node ./build.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sap/node-jwt@1.6.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2020-06-16T08_47_03_757Z-debug.log
[2020-06-16 08:47:03] ERROR could not build the "DevOpsSample" module: could not execute the "npm install" command: exit status 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20200616084642.mta p=cf mtar= strict=true mode=" command: exit status 2

Could anyone please help?

**Comment by MichaelCzcz** [comment]
Please provide the name of the tutorial where you have encountered this issue. Thank you.

**Comment by sooraj2589** [comment]
Referred https://sap.github.io/cloud-mta-build-tool/usage/

**Comment by MichaelCzcz** [comment]
Sorry, but this channel is for issues with tutorials only.
Please use the proper channel:  https://github.com/SAP/cloud-mta-build-tool/issues/new/choose 
Thank you.
