### ISSUE TITLE
Map Fields Between Open Connectors and HubSpot

### ISSUE THREAD

**Issue by kludhani** [SAPDocuments/Tutorials#5329]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-openconnectors-common-resources.html

Please specify the step you are referring to

**Comment by kludhani** [comment]
Tutorial is not the giving the output as expected. JSON payload response is blank

**Comment by kludhani** [comment]
Tutorial is not the giving the output as expected. JSON payload response is blank

**Comment by shilpavij** [comment]
Which are the step you are referring too?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
