### ISSUE TITLE
SAP HANA XS Advanced - Modules within Node.js SAP HANA applications

### ISSUE THREAD

**Issue by bruceleong** [SAPDocuments/Tutorials#5332]
Tutorial URL: https://developers.sap.com/tutorials/xsa-node-modules.html

Step #6 - "Build and Run" - All done within webIDE

Unable to build and run node application - error logs

`npm ERR! code E404
npm ERR! 404 Not Found - GET https://____/accept-language-parser - no such package available
npm ERR! 404 
npm ERR! 404  'accept-language-parser@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'core_node'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`

mta.yaml (set "properties" within webIDE)
`  - name: core_node
    type: nodejs
    path: core_node
    provides:
      - name: core_node_api
        properties:
          url: '${default-url}'
    requires:
      - name: UAA-service
      - name: hdi_db
      - name: db
    properties:
      UPSTREAM_LINK: '"http://registry.npmjs.org/"'
      SAPUPSTREAM_LINK: '"https://npm.sap.com"'`

Is there additional configuration of environment?

**Comment by jung-thomas** [comment]
I would guess that your HANA System can't access the internet (http://registry.npmjs.org).  Perhaps your machine is behind a firewall and needs some proxy configuration.

**Comment by bruceleong** [comment]
To clarify - the app is not trying to access "npmjs.org" from my error message, but "[our server].com:51017/accept-language-parser". 

![screenshotNPM](https://user-images.githubusercontent.com/32654479/84964095-09a15980-b0c0-11ea-8b13-ab7db181c1b5.png)

To fix this, I set the "UPSTREAM_LINK" and "SAPUPSTREAM_LINK" in the mta.yaml as noted above. 

Also, in XSA Cockpit, I set the "npm_config_registry" to "http://registry.npmjs.org" as below: 
![Screen Shot 2020-06-17 at 5 30 53 PM](https://user-images.githubusercontent.com/32654479/84964226-6dc41d80-b0c0-11ea-8afa-df32e94085ed.png)

How is the url built to retrieve the npm packages? Am I missing a step in the configuration and thus it's looking for the npm packages locally? 

Thank you!

**Comment by jung-thomas** [comment]
Yes it goes to your local registry cache (we use Sinopia). That's what its hitting at your 51017 port.  But the UPSTRAM_LINK tells the registry cache where to forward the request when the package isn't found in the local cache. That message is telling you that the package isn't in the cache nor could it call out to the upstream link (npmjs) and fine it.  If you upsteam link is configured correctly then this is most likely firewall/proxy.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
