### ISSUE TITLE
Install the Cloud Connector in your System Landscape

### ISSUE THREAD

**Issue by yfliao90** [SAPDocuments/Tutorials#5335]
Tutorial URL: https://developers.sap.com/tutorials/cp-connectivity-install-cloud-connector.html

Please specify the step you are referring to

When I install sapcc-2.12.4-windows-x64.msi on the server, I double click the installer, then click next, then it prompt "There is a problem with this Windows Installer package. A DLL required for this install to complete could not be run. Contact your support personnel or package vendor."

I have no idea what the missing DLLs are.

**Comment by maxstreifeneder** [comment]
Hi @yfliao90,

sorry for the late reply. Please open a Support Ticket (Component: BC-MID-SCC) since this is not an issue with the tutorial but rather with the Cloud Connector itself. 

Thanks in advance and regards,
Max
