### ISSUE TITLE
Create a List Report Floorplan

### ISSUE THREAD

**Issue by puyihua** [SAPDocuments/Tutorials#5337]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-scpms-floorplan.html

Please specify the step you are referring to: Step 5

Hi there, I was following the tutorial and I tired to create a segue to navigate from supplier list to product list. I believe I created segue correctly (control-drag from supplier list cell to product list viewer / selection segue / segue identifier), also I implemented prepare function same as the tutorial.

But the every time I tap on the cells of supplier list, it will not jump the products list, the prepare function is not called.

macOS version: 10.15.4
Xcode version: 11.5 (11E608c)
SAP iOS SDK version: Version 5.0.2

**Comment by KevinMuessig** [comment]
Hi @puyihua ,

a couple of questions to better understand your current state of the project:

1. You have both needed ViewControllers (SupplierTableViewController & SupplierProductsTableViewController)?
2. Are the segue identifiers set correctly?
3. Are the segues drawn correctly please double check?!
4. Are the custom classes set correctly?
5. Did you set a breakpoint inside the prepareForSegue to check if it enters or not?
6. As the UI element you're tapping on is a tableview cell which means that if the delegate is not set correctly the tap event never gets called. Please make sure that the tableview delegates are set correctly (which automatically should be correct if you've used UITableViewControllers. 

Thanks,

Kevin
