### ISSUE TITLE
Open SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by CPTN021** [SAPDocuments/Tutorials#5339]
Tutorial URL: https://developers.sap.com/tutorials/webide-multi-cloud.html

Please specify the step you are referring to

The tutorial seems to be outdated. When clicking on the suggested link, there is no "Launch SAP Web IDE" button on the landing page.

**Comment by IObert** [comment]
Thanks for letting us know, you are absolutely right. I updated the tutorial and the change should be live within the next few minutes.
