### ISSUE TITLE
ABAP RESTful Programming Model - Behavior definition

### ISSUE THREAD

**Issue by manhofmann** [SAPDocuments/Tutorials#5340]
Hello,

working throught the [tutorial of ABAP RESTful Programming](https://github.com/SAPDocuments/Tutorials/tree/master/tutorials/abap-environment-restful-programming-model) i experienced an issue with a [definition of a behaviour](https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/abap-environment-behavior/abap-environment-behavior.md)
I think it is missing this line to work properly

`field ( numbering : managed ) mykey;`

If you finish this tutorial it is only possible to create exactly one new instance. Adding more than one results in an error. The reason for this is that in the database table 
`ZTRAVEL_XXX`
The key is 0000000... for the created entry. Maybe @mervey45 can update this section?

**Comment by mervey45** [comment]
Hi @manhofmann ,

thank you for this information. We'll update this as soon as possible.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
