### ISSUE TITLE
Try Out the SAP Cloud Platform SDK for Android Wizard

### ISSUE THREAD

**Issue by tobecrazy** [SAPDocuments/Tutorials#5341]
Tutorial URL: https://developers.sap.com/tutorials/cp-sdk-android-wizard-app.html

Please specify the step you are referring to

Is it possible to translate to other language ? Ex:Chinese ?

**Comment by flyingfish162** [comment]
@tobecrazy Sorry, I don't follow. Are you meaning is it possible to translate tutorials to other languages? Or translate the wizard windows to other languages? Or translate the app to other languages?

**Comment by tobecrazy** [comment]
I mean  tutorials

**Comment by jarjarbentley** [comment]
I am not aware of any plans to translate tutorials into other languages.  @thecodester  , any comments?

**Comment by flyingfish162** [comment]
> I mean tutorials

So far, no plans to translate them.

**Comment by thecodester** [comment]
We are considering translation, especially to Chinese, but I do not have any planned/expected date for this. Sorry.
