### ISSUE TITLE
SAP HANA PAL 

### ISSUE THREAD

**Issue by jinigirl** [SAPDocuments/Tutorials#5342]
Tutorial URL: https://developers.sap.com/tutorials/cp-hana-aa-movielens-04.html

Please specify the step you are referring to: Step 2: Calling SAP HANA PAL functions

Hello, Is there already a new tutorial on how to call SAP HANA PAL functions from SAP Cloud Platform? Currently, the HANA version in Cloud Foundry trial is already on version 2.0. Is this correct? I got the database version from SQL script:

Select version from m_database

I am trying to call PAL Functions from CF trial but I get an Unresolved Error saying that the PAL_DECISION_TREE is an unresolved procedure.

**Comment by jarjarbentley** [comment]
Hi, this tutorial was out of date and has been removed.
