### ISSUE TITLE
Install the MultiApps Cloud Foundry CLI Plugin

### ISSUE THREAD

**Issue by ricardojlopez** [SAPDocuments/Tutorials#5347]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-install-cliplugin-mta.html

Please specify the step you are referring to
**STEP 3:**

PS C:\WINDOWS\system32> cf install-plugin multiapps
Searching CF-Community for plugin multiapps...
Plugin multiapps 2.4.1 found in: CF-Community
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
cf : The handle is invalid.
En línea: 1 Carácter: 1
+ cf install-plugin multiapps
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The handle is invalid.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
**FAILED**

PS C:\WINDOWS\system32>

**Comment by IObert** [comment]
I haven't seen this error before. Are you using the most recent version of the CF tool? Are you able to install other plugins like `cf install-plugin -r CF-Community "html5-plugin"`

**Comment by IObert** [comment]
Seems like this issue is not active anymore, please reopen if needed.
