### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#5350]
Tutorial URL: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html

Please specify the step you are referring to 6

expected this: "completed successfully"

got this: "Build command failed : hdi-build failed: hdi-build operation failed: connection failure: failed to connect to hdi deployer with 'wss://hdispacedeploy***.cfapps.us10.hana.ondemand.com/eykrvoSBG' URL, 'bad handshake' please try again"

3 times in a row.

**Comment by jung-thomas** [comment]
That doesn't sound like anything incorrect with the tutorial or the steps.  It sounds like a low level problem with the HDI deployer in your space.  Now that some time has passed, have you tried it again?  What environment are you attempting this in?  Trial or a productive account?

**Comment by greg2git** [comment]
Hi Thomas,

if this tutorial applies to prod only then please close the issue after putting a disclaimer up front, but if it's supposed to work in trial then there's something going on with the 'handshake' preventing the student from completing the tutorial. btw, the same error is showing up in other tutorials but i would like to avoid finding steps that may have triggered it. it's also ok if the issue is unique to my dev space that somehow got corrupted 'along the way'.

Thank you for doing the needful.
greg

**Comment by jung-thomas** [comment]
I don't ask the question about the environment to limit the scope of the tutorial, but only to know which environment I should test in to see if I can recreate the problem.

**Comment by greg2git** [comment]
if it needs to work in trial then i'm all for it.

**Comment by greg2git** [comment]
with a slightly different success message:

_10:18:52 AM (HDB) STRUCTURED LOG CHECKSUM 1801...
10:18:52 AM (HDB) STRUCTURED LOG SIZE....
10:18:52 AM (HDB) SENDING STRUCTURED LOG
10:18:52 AM (HDB) Build of /hana-cf-get-started-trial/db completed successfully._

the magic has happened and the issue has cleared in the trial account.

Thank you for looking into this.

**Comment by jung-thomas** [comment]
Glad to hear the issue is corrected.
