### ISSUE TITLE
CIC/CD for Hana using regi

### ISSUE THREAD

**Issue by kartiksap481** [SAPDocuments/Tutorials#5351]
HI Team,

we are trying configure to automate transports in our landscape, we are using below link from git.

https://github.com/SAPDocuments/Tutorials/blob/test-link-checker/tutorials/ci-best-practices-xsc/ci-best-practices-xsc.md

we have checked few sap notes, but could not find information regarding --regi--- tool usage for export and information that  we need to append for regi other than import.

as we have found sap note on import languages

eg: regi import languages PATH to tgz file

but when we are trying to use below command to export delivery units, it is showing as DU not found.

regi export ${DELIVERY_UNIT} "${WORKSPACE}/target/${DELIVERY_UNIT}.tgz" --key=HDBKEY

can we please get help on this from any of contributors  @thecodester @wolframK @akula86  @nancymic2

**Comment by thecodester** [comment]
I must say that is a strange way to find this information. Please identify yourself in your profile.

CI/CD tutorials are now housed here: https://help.sap.com/viewer/3324745951b44b578bd65221d2ff8f9a/Cloud/en-US/e49a97d4f2b44254866e749058b78e70.html

Please refer to this documentation and its support process.
