### ISSUE TITLE
Update the tutorial of SAP Cloud Platform SDK for Android

### ISSUE THREAD

**Issue by VGordillo-Resulto** [SAPDocuments/Tutorials#5354]
Tutorial URL: https://developers.sap.com/tutorials/cp-sdk-android-wizard-app.html

Update the tutorial to the current version of SAP Cloud Platform SDK for Android (3.0.6) and Android Studio version (4.0)

**Comment by flyingfish162** [comment]
We are updating tutorials to the version of SAP Cloud Platform SDK for Android (3.1.2 and higher) and Android Studio version (3.6.x).

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
