### ISSUE TITLE
Integrate Your App into Your Portal Site (Cloud Foundry)

### ISSUE THREAD

**Issue by korayyersel** [SAPDocuments/Tutorials#5355]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-sapui5-app.html

Please specify the step you are referring to

The tutorial works fine but we are having issues with handling the dynamic content. It would be great to also have this step in this tutorial.

**Comment by IrisSasson** [comment]
Hi, 
Dynamic tiles are in the roadmap. This is not currently possible. 

Thanks
Iris.

**Comment by korayyersel** [comment]
Hi Iris,
Actually I could implement also dynamic tiles (at least dynamic content - numbers) with a bit trial and error.
https://github.com/korayyersel/cloud_foundry_ui5_portal
I needed a destination setting which was not well documented: HTML5.DynamicDestination
Regards,
Koray

**Comment by IrisSasson** [comment]
I am happy to hear. This is not officially supported so I cannot document it. But i am happy to address any questions

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
