### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by sergiojj7** [SAPDocuments/Tutorials#5357]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Thank you!
![image](https://user-images.githubusercontent.com/45602347/85490746-b429e880-b5a8-11ea-9693-5b265a07ba2f.png)

**Comment by raz-korn** [comment]
You're welcome.
I'm working with my colleagues on new tutorials to cover additional use-cases. I hope you'll enjoy them as well.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
