### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by miyasuta** [SAPDocuments/Tutorials#5361]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

Please specify the step you are referring to: Step 4: Configure the main project attributes

After clicking Next I received below error.
![image](https://user-images.githubusercontent.com/39408125/85547354-c7948c80-b658-11ea-9b02-fc823a1ceabd.png)
Project folder was created, but node_modules and package-lock.json were not created.
![image](https://user-images.githubusercontent.com/39408125/85547420-d7ac6c00-b658-11ea-9d21-9a4db092aa2f.png)
After executing `npm install` manually, node_modules and package-lock.json were created and I could proceed.

VS code Version: 1.46.0
Node.js: 12.8.1

**Comment by cjbernal** [comment]
Hi miyasuta,

Sorry that you experienced an issue. We're glad that you were able to proceed.

We have not seen a cluster of similar issues, though we will keep an eye out for it now. Were you able to complete the rest of the tutorial without further problems?

Kind regards,
Conrad (SAP UX Engineering)

**Comment by miyasuta** [comment]
Hi Conrad,

Yes, I was able to complete the rest of the tutorial.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
