### ISSUE TITLE
Set Up the SAP HANA Plugin for Microsoft Visual Studio - Not work with VS2019

### ISSUE THREAD

**Issue by andreslozada** [SAPDocuments/Tutorials#5363]
Tutorial url: https://developers.sap.com/tutorials/hxe-ua-visual-studio.html

Hello
I have VS2017 and VS2019 installed in my PC and I followed the steps mentioned in the manual and the Connector to SAP HANA is only allowed for VS2017 not for VS2019. Is there any other step to allow it in vs2019?

Thanks!

**Comment by JCurrie27** [comment]
Hi andreslozada: The development team has confirmed that the plugin is compatible with VS2017 only, not VS2019. There are no workarounds available for VS2019 users.  I'll make the VS2017 prerequisite clear in the tutorials, and in the tutorial group. 

The team recommends customers start using **SAP HANA Database Explorer** as the recommended tool for using an SAP HANA database. A tutorial group for using Database Explorer is in the works, and should be available in the Fall -- your feedback against those upcoming Database Explorer tutorials would be most welcome.
