### ISSUE TITLE
Installing XS CLI Client

### ISSUE THREAD

**Issue by marinho** [SAPDocuments/Tutorials#5365]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-xs-xli-client.html

This tutorial suggest user to use **tar** to unzip a .zip file in Linux, which is not a valid option. User should use **unzip** instead.

**Comment by JCurrie27** [comment]
Thanks for pointing out this bug. The command should be to use **sudo tar -xzf** to extract the **.tgz** file -- we're correcting this mistake.
