### ISSUE TITLE
Update step in Create a Basic CAP-Based Service Tutorial

### ISSUE THREAD

**Issue by iwonahahn** [SAPDocuments/Tutorials#5370]
Tutorial URL: https://developers.sap.com/tutorials/cap-cloudsdk-3-basic-service.html

Step 1: `npm set @sap:registry=https://npm.sap.com` is no longer necessary.

@sap Node.js packages have moved from https://npm.sap.com to the default registry https://registry.npmjs.org.
Maybe add a note: As future versions are going to be published only there , please make sure to adjust your registry with:

`npm config delete "@sap:registry"`

We will update this also in our CAP documentation asap.

Thanks and best regards,
Iwona

**Comment by qmacro** [comment]
Thanks for the heads-up, @iwonahahn - I've removed references to this now in all of the tutorials in that mission.
