### ISSUE TITLE
Configure Object Pages Using SAP Fiori Tools

### ISSUE THREAD

**Issue by bharanidharanspm** [SAPDocuments/Tutorials#5371]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-configure-object-pages.html

Please specify the step you are referring to

Why there are no expected output screenshots shown in the tutorial to compare and confirm if the output are correct.

**Comment by cjbernal** [comment]
Hi bharanidharanspm,

Thank you for your feedback. I will share with the team that it would be useful to see the end result. As this process takes some time and requires review, it may not be an immediate change. Rest assured, however, that if you have two object pages that feature the mentioned elements, you did it correctly :-) SAP Fiori elements floorplans are intended to provide apps that are consistent in look and feel -- meaning that the positioning of elements is standardized. 

Please let me know if you have any further questions.

Kind regards,
Conrad (SAP UX Engineering)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
