### ISSUE TITLE
Add Conditional Routing to Your Integration Flow

### ISSUE THREAD

**Issue by fridtjof1** [SAPDocuments/Tutorials#5372]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-add-conditional-routing.html

STEP 6 Check the mail received:

You should have received the following mail:
![image](https://user-images.githubusercontent.com/67004881/85847506-cb82f480-b7a7-11ea-8ed0-39b7adecd7ef.png)

I do not receive the mail like that.  I still have the order-element inside the order. How do you remove that?  There is not step in that tutorial that explains that.    When later configure this to convert to CSV-format the code-value is not in the payload!

This is my mail result =
`<orders xmlns:dis="http://camel.apache.org/cxf/jaxws/dispatch" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"> <order> <orderID>BS00010023</orderID><order xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><code>KWADRIT</code><orderID>BS00010023</orderID></order> <OrderDate>11.04.2019</OrderDate> <`

**Comment by gauthamkrishna-sap** [comment]
Hello,
We are working on overhauling the entire tutorial series and will publish the updates shortly. Apologies for the delay in response.
Thanks & Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
