### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by JeremyChabert** [SAPDocuments/Tutorials#5373]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-configure-lrop.html

Step 5: Preview app with real backend data

While trying to execute command `npm start`, I encounter the following issue
Could not locate module @sap/ux-ui5-tooling via resolve logic (error: Cannot find module '@sap/ux-ui5-tooling/package.json'

I tried to install the devDependencies with `npm i`, but I also encounter an issue
npm ERR! 404 Not Found - GET https://npm.sap.com/@sap%2fux-ui5-tooling

**Comment by theStiggySpd** [comment]
Hi @JeremyChabert 

This is due to an npm registry setting for @sap that is no longer supported. Please execute the following to update the generator libraries:
`npm i -g @sap/generator-fiori-elements --@sap:registry=https://registry.npmjs.org`
Once this completes, restart VScode.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by JeremyChabert** [comment]
Hi @theStiggySpd ,
It worked. Thanks for the answer.
