### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by seanpmcn** [SAPDocuments/Tutorials#5375]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html

Step 4: Execute the workflow sample application:

After I start the new instance in the Monitor Workflow section, I go back to the main page, but "My Inbox" is still at 0. Upon clicking it, the list of tasks is empty.

**Comment by ArchanaShukla** [comment]
Can you check in Monitor Workflow Instances view --> Execution Log (logs are available bottoms-up which means latest are on the top) as to where your workflow instance is currently waiting. If it is waiting for user task, then check which user it is. It is a high chance that your workflow could have gone in erroneous state.

**Comment by seanpmcn** [comment]
> 
> 
> Can you check in Monitor Workflow Instances view --> Execution Log (logs are available bottoms-up which means latest are on the top) as to where your workflow instance is currently waiting. If it is waiting for user task, then check which user it is. It is a high chance that your workflow could have gone in erroneous state.

Unfortunately, I do not see the view --> Execution Log on my screen
![monitor workflow](https://user-images.githubusercontent.com/46979553/86539696-b22b2800-becc-11ea-8207-bc0873538703.PNG)

**Comment by ArchanaShukla** [comment]
Can you scroll up to the last Execution Log, and show me that screenshot. Does it has a user task?

**Comment by seanpmcn** [comment]
> 
> 
> Can you scroll up to the last Execution Log, and show me that screenshot. Does it has a user task?

![mw4](https://user-images.githubusercontent.com/46979553/86815771-09f29c00-c051-11ea-9ef6-c88731328c9a.PNG)

Here it is

**Comment by ArchanaShukla** [comment]
Yeah so you see the recipient. It says <your trial email ID> and not to your user and so you dont see anything in your Inbox.  you needed to change than when you start the workflow. There was a recent change in the onboarding workflow and the tutorial need to be adapted. For now if you can click _Show Task_, and then do _Assign Processor_ and enter your trial email ID. The task would appear in your Inbox.

**Comment by seanpmcn** [comment]
Thank you! I was thinking it was likely a change the tutorial didn't account for.
