### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by jitendrakansal** [SAPDocuments/Tutorials#5377]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

After clicking on **SAP Fiori tools - Application Generator: Launch**, it says: 

<img width="874" alt="Screenshot 2020-06-28 at 10 04 33 PM" src="https://user-images.githubusercontent.com/31536700/85957161-638d0380-b98b-11ea-928e-85c31ca5c521.png">

SAP Fiori tools - Extension Pack is already installed. 

also verified SAP Fiori tools - Application Modeler is installed as well. 
Have restarted VSC couple of times but issue still persists.

**Comment by theStiggySpd** [comment]
Hi @jitendrakansal 

We found this issue today that "SAP Fiori tools - Extension Pack" is not listing "Application Wizard". We are working to fix it asap.
Meanwhile, from your VSCode, click on extensions, and search for "Application Wizard" and install it separately. This will fix your issue and you should be able to proceed with the tutorial

![image](https://user-images.githubusercontent.com/59027566/86034332-3d994a80-b9ef-11ea-8ca6-309a98489d3b.png)
