### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by zouyi100** [SAPDocuments/Tutorials#5378]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to

Hi, teams

I think this document is out of date. The Business Application Studio has been updated many times until now. 
So could you please update the tutorial document base on the latest version? Thank you!

**Comment by raz-korn** [comment]
Hi,

An update is available and will be released in a few days.

Regards,
Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
