### ISSUE TITLE
Access the SAP Screen Personas Training System

### ISSUE THREAD

**Issue by garayachile** [SAPDocuments/Tutorials#5382]
Tutorial URL: https://developers.sap.com/tutorials/personas-access-learning-sys.html

The link published is not working: http://link.personas.help/opensap/se

**Comment by cjbernal** [comment]
Hi garayachile,

I just tried it myself. It looks like it is back up again. Please try again and let me know if you have trouble logging on.

Thanks and regards,
Conrad (SAP UX Engineering)

**Comment by greg2git** [comment]
maybe it works behind this firewall?

This site can’t be reachedlvpal593.dmzpal.sap.corp’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by garayachile** [comment]
Hi Conrad,

The issue continues. This is the screen displayed:

[image: image.png]

When I registered my account it was ok, but when I try to access with my
account using the published link (http://link.personas.help/opensap/se) I
have the problem.

[image: image.png]
Please your help.


*Saludos*

*Gerardo A. Araya H.*

**Comment by cjbernal** [comment]
Hi Gerardo,

Regrettably, I cannot see the images in your post. Could you please put the error into your response?

Thanks,
Conrad

**Comment by garayachile** [comment]
Hi,

This is the browser error:

Hmmm… can't reach this page

*lvpal593.dmzpal.sap.corp*’s server IP address could not be found.


   - Try running Windows Network Diagnostics.

DNS_PROBE_FINISHED_NXDOMAIN

I'm using Mcafee Total Protection and disabled it, but the issue continues.

Best regards


*Gerardo A. Araya H.*
*Consultor Senior SAP BI*

**Comment by thoznek** [comment]
Hi Gerardo,

Try it again, it should work now.

**Comment by garayachile** [comment]
Yes, Now it's working. What was the problem?

Bets regards

**Comment by thoznek** [comment]
HTTP access was redirected to an SAP-internal HTTPS server.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
