### ISSUE TITLE
Create Authorization Model and App in SAP Cloud Platform ABAP Environment

### ISSUE THREAD

**Issue by peterpersiel** [SAPDocuments/Tutorials#5385]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-authorization.html

Please specify the step you are referring to

- Tutorial Description: Create IAM Apps, services and catalogs for authorization model in the SAP Cloud Platform ABAP, environment. &rarr; no comma needed
- 2.5 this is not part of the authorization object, screenshot shows authorizations tab in IAM app
- 2.6 this is not part of the authorization object, screenshot shows authorizations tab in IAM app
- 5.3 only needs to maintain default authorization values for Z_LOCAOXXX
- 5.3 Screenshot proposal status in screenshot should be as follows:
  - S_SERVICE, S_START &rarr; Proposal Status "No"
  - Z_LOCAOXXX &rarr; Propoal Status "Yes, Without Values"
- 6.9 No need to add authorization object, as of now authorization object is added by default
- 6.12 UI changed: Inline editing for activity field, same as for Z_LOCAOXXX field
- 6.14 Save and activate &rarr; should save click button "Publish Locally" (button is also missing in screenshot)
- 7.10 Missing step: Add authorization object to restriction type

**Comment by mervey45** [comment]
Hi @peterpersiel ,

thank you for your feedback. 

_Tutorial Description: Create IAM Apps, services and catalogs for authorization model in the SAP Cloud Platform ABAP, environment. → no comma needed_  
-> This is the official name of our product (with a comma).

_2.5 this is not part of the authorization object, screenshot shows authorizations tab in IAM app
2.6 this is not part of the authorization object, screenshot shows authorizations tab in IAM app
6.12 UI changed: Inline editing for activity field, same as for Z_LOCAOXXX field_
--> in those steps the UI changed. The authorization objects and services types are now listed in the IAM App only.

_5.3 only needs to maintain default authorization values for Z_LOCAOXXX_
-> Yes, you only need to add values for Z_LOCAOXXX, S_SERVICE was just another example. 

I'll change those steps and the rest of it.

Thank you.

Best regards, 
Merve

**Comment by peterpersiel** [comment]
Hi Merve,

in steps 5.1/5.2:
Screenshots do not reflect the correct Default Authorization Values object:
I would suggest to not select the default authorization values directly from the object tree, but rather using the link provided in the service binding.
This link always refers to the right object  → the ...HT object without spaces in the object description is the right one.
The right object also can be identified by the General → Type = ODataV2 setting when showing the Authorization Default Values. For the other incorrect object the value for General → Type setting is empty

Best regards,
Peter

**Comment by mervey45** [comment]
Hi @peterpersiel,

I update this tutorial. @MichaelCzcz  I created following pull request: #5426.

We can close this issue.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
