### ISSUE TITLE
SAP Fiori tools - Service Modeler (Extension) / An unexpected error ocurred.

### ISSUE THREAD

**Issue by juanfelipe82193** [SAPDocuments/Tutorials#5391]
SAP Fiori tools - Service modeler cannot be executed when using in VS code Version 1.46.1

![Screen Shot 2020-07-01 at 10 29 29 AM](https://user-images.githubusercontent.com/58919119/86262734-e11c6380-bb85-11ea-9936-b11348375b3f.png)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. Please name the tutorial where you are facing this issue.

**Comment by juanfelipe82193** [comment]
Hi Michael, the tutorial is Configure a List Report Page Using SAP Fiori Tools. This is the link

https://developers.sap.com/tutorials/fiori-tools-configure-lrop.html

**Comment by juanfelipe82193** [comment]
Hi Michael, btw I'm using Northwind V2 OData service due to issue:

 https://github.com/SAPDocuments/Tutorials/issues/5358#issuecomment-653057516

I don't know if probably Service Modeler don't work with Nothwind

**Comment by theStiggySpd** [comment]
@juanfelipe82193 Let me get back to you. I had checked Northwind service few weeks back and it seemed to work.

**Comment by juanfelipe82193** [comment]
Thanks @theStiggySpd, yes Northwind is working fine when gining entry point as Products. But what's not working is the Service Modelerer (Extension). I couldn't try with another OData service because I'm also facing the issue "btoa is not defined".

Thanks.

**Comment by theStiggySpd** [comment]
Hi @juanfelipe82193 
We are looking into this. Thanks for reporting this. I will let you know as soon as the fix it out.
Meanwhile, would you be ok to close this issue as its not directly replated to the SAP tutorials repository and tutorial. 


Regards,
Sushant (SAP)

**Comment by juanfelipe82193** [comment]
Yes, were you'll be tracking it?

Thanks.

**Comment by theStiggySpd** [comment]
HI @juanfelipe82193 

I would also recommend that you create a ticket in BCP using component "CA-UX-IDE". Will that be ok with you?

**Comment by juanfelipe82193** [comment]
Please provide a step by step to raise it.

Thanks.
