### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio High Productivity Tools

### ISSUE THREAD

**Issue by Shield12** [SAPDocuments/Tutorials#5392]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to STEP 8.

Hello everyone,

I followed the steps in the manual above, but after step 8 I went to test my app and I have the following error when trying to access On Premise via destination. My Destination is configured as Basic Authentication.

StatusCode: 400.
StatusText: Bad Request
body: "Invalid Proxy Header"
![image](https://user-images.githubusercontent.com/22206093/86266931-52ffa780-bb9c-11ea-8c3c-72e97830e9be.png)

**Comment by raz-korn** [comment]
Hi @Shield12 ,

It looks like you're following the tutorial, but using your own on-premise system. Is that correct?
If this is correct, then the on-premise system is probably behind a firewall.

- Do you have Cloud Connector setup between the on-premise system and SAP Cloud Platform?

- Did you check that the destination is configured correctly? For Corporate on-premise systems, the destination configuration is somewhat different than ES5.

When you mention "Step 8" do you refer to Step 8 of the tutorial (Get URL to access the application) or sub step 8 within a different step in the tutorial?

Regards - Raz

**Comment by Shield12** [comment]
Hello,

Yes the destination has been configured to point to the OnPremise environment.
![image](https://user-images.githubusercontent.com/22206093/86373969-65401b00-bc5a-11ea-81b9-a4a158c05643.png)

When testing the app through Business Aplication the service consumption worked, however when deploying on the SCP I try the mentioned error.

**Comment by raz-korn** [comment]
Hi @Shield12 ,
In the Cockpit > Destinations, when you click "Check Connection" what do you receive?
Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
