### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio High Productivity Tools

### ISSUE THREAD

**Issue by CPTN021** [SAPDocuments/Tutorials#5394]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to
When trying to execute "Run ES5" as described in step 4. I could the following error "Attribute 'program' does not exist ('{path}').".

**Comment by raz-korn** [comment]
Hi @CPTN021 ,

Please refer to issue [5300](https://github.com/SAPDocuments/Tutorials/issues/5300).

Regards,
Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
