### ISSUE TITLE
Customize the Overview View Controller to Display Customers and Products

### ISSUE THREAD

**Issue by juanfelipe82193** [SAPDocuments/Tutorials#5396]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-scpms-teched19-03.html

Please specify the step you are referring to

Step 1 : Implement loading of customer and product data

In order to use FileConfigurationProvider we need to import SAPFoundation
In order to use OnboardingSessionManager we need to import SAPFioriFlows

These frameworks are missing in the tutorial.

**Comment by KevinMuessig** [comment]
Hi @juanfelipe82193 ,

thank you for letting me know. I will look into it and push a fix.

Cheers,
KM
