### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by amosang** [SAPDocuments/Tutorials#5398]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

Please specify the step you are referring to
In "Step 5: Preview app with real backend data"
- My backend is ES5. I tested that I can connect. 

After "npm start" in terminal.

I got this URL from Chrome Inspector. It is red (error).

[http://localhost:8080/sap/opu/odata/sap/SEPMRA_PROD_MAN/$metadata?sap-value-list=SEPMRA_PROD_MAN.SEPMRA_C_PD_ProductPriceRangeType%2FPriceClassification%2CSEPMRA_PROD_MAN.SEPMRA_I_ProductCategoryType%2FMainProductCategory&sap-language=EN](http://localhost:8080/sap/opu/odata/sap/SEPMRA_PROD_MAN/$metadata?sap-value-list=SEPMRA_PROD_MAN.SEPMRA_C_PD_ProductPriceRangeType%2FPriceClassification%2CSEPMRA_PROD_MAN.SEPMRA_I_ProductCategoryType%2FMainProductCategory&sap-language=EN)
====================================================================
From the error, I think the problem lies with the metadata definition.
You get the below XML when viewing the above URL in browser.

```
<error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<code>/IWFND/CX_SODATA_EDM_PROVIDER/</code>
<message xml:lang="en">Value-List SEPMRA_PROD_MAN.SEPMRA_C_PD_ProductPriceRangeType/ not found in Metadata</message>
<innererror>
<application>
<component_id>BC-SRV-NWD-FRA</component_id>
<service_namespace>/SAP/</service_namespace>
<service_id>SEPMRA_PROD_MAN</service_id>
<service_version>0001</service_version>
</application>
<transactionid>B9E0A2A100BE0040E005EFCF1C2B79D7</transactionid>
<timestamp>20200703033858.4680560</timestamp>
<Error_Resolution>
<SAP_Transaction>For backend administrators: run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details</SAP_Transaction>
<SAP_Note>See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)</SAP_Note>
</Error_Resolution>
<errordetails/>
</innererror>
</error>
```

![image](https://user-images.githubusercontent.com/30390885/86429550-7f453080-bd22-11ea-88dd-3e0b9e4567c4.png)

**Comment by theStiggySpd** [comment]
Hi @amosang 
Yes you are right. I see some issues with the service but this should not prevent you from completing your tutorial.
Internally, I will follow up with my colleagues who are maintaining the ES5 demo system to see if the service can be updated.

Thanks,
Sushant

**Comment by amosang** [comment]
@theStiggySpd Thanks for your reply and followup with your backend colleagues. Perhaps you can close this issue when that's done?
Meanwhile, "this should not prevent you from completing your tutorial" -> what is the workaround?

**Comment by theStiggySpd** [comment]
Hi @amosang ,
Are you stuck due to this error showing up in console?
As long as you can run the app using `npm start`, you should be good to go.
Let me know if you are not.

Thanks,
Sushant

**Comment by amosang** [comment]
Hi Sushant,
Well technically one can start the app with "npm start", but it was not very useful seeing absolutely no data records.
I've tried "Preview in Browser" for the test folder as well, but same outcome.

![image](https://user-images.githubusercontent.com/30390885/86714880-3955d880-c052-11ea-8673-f4e28d255869.png)

I supposed one can move on to other tutorials, if no data records are shown. Thanks anyway.

**Comment by theStiggySpd** [comment]
Hi @amosang 
>Well technically one can start the app with "npm start", but it was not very useful seeing absolutely no data records.

Did you press the "Go" button and you don't see the list of Products?

**Comment by amosang** [comment]
Sorry my bad. Clicking the "Go" button loads data from locally, but only for the MockServer. 
Appreciate your help :)

![image](https://user-images.githubusercontent.com/30390885/86742026-657d5380-c06a-11ea-8700-346a48cfd501.png)

**Comment by amosang** [comment]
This has been fixed on the non-MockServer as well.
I am impressed :)
