### ISSUE TITLE
Add a Web Dynpro ABAP App to Your Portal Site

### ISSUE THREAD

**Issue by mipsita17** [SAPDocuments/Tutorials#5399]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-webdynpro-app.html

Please specify the step you are referring to
Step 5:
4. In the Purchase Orders group, click the Web Dynpro ABAP app called Search POs to launch it.
I have followed all the steps as suggested but after launching I am getting the below error:

"Service cannot be reachedWhat has happened?URL call was terminated because the corresponding service is not available.
--
 
NoteThe termination occurred in system with error code 404 and for the reason Not found.
 
What can I do?Select a valid URL.HTTP 404 - Not foundYour SAP Internet Communication Framework Team"

**Comment by IrisSasson** [comment]
Hi
Please share an image of your destination configuration and also 2 images of your app configuration (both main screen and navigation configuration)
Please also add a screenshot from after your launch the app and include the URL in it

Thanks

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
