### ISSUE TITLE
Add a Model and Test the SAPUI5 App

### ISSUE THREAD

**Issue by kueblertgb** [SAPDocuments/Tutorials#5400]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-webide-setup-datasource.html

Please specify the step you are referring to

I was at Step 2: Define the Data source
and there i had do select the Service URL and choose a system to connect. But there was no connection to select.
The step before i created a destination in the Cloud Platform Cockpit and it worked fine.
So i don't understand wy i was not been able to select a connection.

Please help me.

Kind Regards 
Tobias Kübler

**Comment by IObert** [comment]
Hi Tobias,

did you create the destination in the CF and in the Neo environment (with all additional properties that were mentioned in the tutorial)? Usually that the reason why it doesn't show up.

**Comment by kueblertgb** [comment]
Hi, thank you 
the Neo einviorment settings where missing, i thougt i could chouse between CF or Neo, i didnt know that i have to set up both.

And i realy did not know wy. But now the service was avalible, after i set up neo.

kr
tobi

**Comment by kueblertgb** [comment]
the hole tutorial part is so buggy, i klick on the "Done" button and nothing worked. i reloaded. nothing.
i am on crome browser.

**Comment by IObert** [comment]
I understand your confusion - which is very understandable. The reason why you need the destination in both places, it that the Web IDE itself is a Neo application, which means it cannot access the destination in the CF environment. This is intended as an explanation - not an excuse. It should be simpler than this and thankfully one destination in CF will work fine when you use the new SAP Business Application Studio.

About the done issue. I assume it doesn't work when you see a small lock before the "Done" label, right? This means you are not logged in and need to click on the login button on the top right corner. 

@thecodester Are you aware of this

**Comment by thecodester** [comment]
Are you logged in when trying to push Done button? I was able to do the first step just now.

**Comment by IObert** [comment]
I'll close this one due to inactivity. Please reopen if needed.
