### ISSUE TITLE
Connect Using the SAP HANA Node.js Interface

### ISSUE THREAD

**Issue by DanCummins-SAP** [SAPDocuments/Tutorials#5401]
Tutorial URL: https://developers.sap.com/tutorials/hana-clients-node.html

Please specify the step you are referring to

Step 1 
> The SAP HANA client provides a 32-bt and a 64-bit install, as does Node.js. It is important that both versions are the same (i.e., 64-bit). For additional details see SAP note 2499500 - SAP HANA Client Supported Platforms.

The node driver only supports 64-bit so I think the above could be adjusted to:

> The SAP HANA client provides a 32-bt and a 64-bit install, as does Node.js. The Node.js driver provIded with the SAP HANA Client is available for 64-bit only. For additional details see SAP note 2499500 - SAP HANA Client Supported Platforms.

**Comment by danielva** [comment]
Thanks for the feedback.  I will make that change in the next update.  The SAP note will also change to the 2.5 equivalent SAP note.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
