### ISSUE TITLE
Create a List Report Object Page App with SAP Fiori Tools

### ISSUE THREAD

**Issue by kirrmannpius** [SAPDocuments/Tutorials#5402]
Group URL: https://developers.sap.com/group.fiori-tools-lrop.html
Hi,
after having completed this tutorial, I would like to ask some questions:
1) in the Application Modeler some json files have been generated in the directory myfioriapp/src/pages,
for example ListReport_SEPMRA_C_PD_Product.json. However, I cannot find these files in the explorer.
Where are these files?
2) Can OData services from an on-premise SAP System be used? Do we have to use a proxy?
3) Can apps developed with Fiori tools be deployed to an on-premise SAP System (Business Suite, S/4HANA)?
Thank you very much,
kind regards
Pius

**Comment by theStiggySpd** [comment]
Hi @kirrmannpius ,
Thanks for trying out SAP Fiori tools and tutorial. Please let me know if you need more explanation:

> 1. in the Application Modeler some json files have been generated in the directory myfioriapp/src/pages,
>    for example ListReport_SEPMRA_C_PD_Product.json. However, I cannot find these files in the explorer.
>    Where are these files?

You can read about the config files in Application Modeler here:
https://help.sap.com/viewer/a9f57505bbb34a6da3c5ba3a49d409d8/Latest/en-US/047507c86afa4e96bb3d284adb9f4726.html

You should see the pages/*.json in your Application modeler explorer:
![image](https://user-images.githubusercontent.com/59027566/86636774-8c178d80-bf89-11ea-84f2-82dee0823954.png)

**Comment by theStiggySpd** [comment]
> 3. Can apps developed with Fiori tools be deployed to an on-premise SAP System (Business Suite, S/4HANA)?

https://help.sap.com/viewer/a9f57505bbb34a6da3c5ba3a49d409d8/Latest/en-US/1b7a3be8d99c45aead90528ef472af37.html

**Comment by theStiggySpd** [comment]
> 2. Can OData services from an on-premise SAP System be used? Do we have to use a proxy?

Yes certainly. You can find options to connect to a data source here:
https://help.sap.com/viewer/a9f57505bbb34a6da3c5ba3a49d409d8/Latest/en-US/99061814ead548808d539861fb27bafb.html

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
