### ISSUE TITLE
Implement the Customer Detail - Value of type 'ApplicationOnboardingSession' has no member 'odataController'

### ISSUE THREAD

**Issue by juanfelipe82193** [SAPDocuments/Tutorials#5403]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-scpms-teched19-04.html

Please specify the step you are referring to: Step 1 Fetch right customer from data service sub-step 6 You’re viewDidLoad(:) method should look like this now:

`override func viewDidLoad() {
    super.viewDidLoad()

    guard let dataService = **appDelegate.sessionManager.onboardingSession?.odataController.espmContainer** else {
        AlertHelper.displayAlert(with: "OData service is not reachable, please onboard again.", error: nil, viewController: self)
        logger.error("OData service is nil. Please check onboarding.")
        return
    }
    self.dataService = dataService

    updateTable()
}
`

This code snippet is causing the appllication to fail during build time, it seems to be an issue with the odataController or odataControllers and the espmContainer.

It's weird because in the same class CustomerDetailTableViewController we have the definition of the dataService as follows:

`var dataService: ESPMContainer<OnlineODataProvider>? {
        guard let odataController = OnboardingSessionManager.shared.onboardingSession?.odataControllers[destinations["com.sap.edm.sampleservice.v2"] as! String] as? Comsapedmsampleservicev2OnlineODataController, **let dataService = odataController.espmContainer** else {
            AlertHelper.displayAlert(with: NSLocalizedString("OData service is not reachable, please onboard again.", comment: ""), error: nil, viewController: self)
            return nil
        }
        return dataService
    }
`

and here the error message does not appear.

Thanks for any insights I'd like to keep following this great tutorial.

**Comment by KevinMuessig** [comment]
Hi @juanfelipe82193 ,

looking at the code snippets you have quiet a lot of * in there where they shouldn't be. Which is causing compile time errors if you have the code in Xcode that way. 
Also below the described step it says: "To fix the rest of the compile-time errors, you have to implement the additional properties for storing the fetched customer, the flag isDataLoaded, as well as a computed property for the Sales Order Headers."

- Do you have the console output for the build error? 
- Is the odataController not known?

It would be great if you have more detail on what Xcode tells you went wrong. 
Thanks,
KM

**Comment by juanfelipe82193** [comment]
Hi Kevin, sorry for the bad snippet.

Please find below a screenshot of the error message.

![Screen Shot 2020-07-24 at 12 59 02 PM](https://user-images.githubusercontent.com/58919119/88421314-fa43b900-cdad-11ea-9981-7c514f98e5c0.png)


Thanks in advance.

**Comment by KevinMuessig** [comment]
Hi @juanfelipe82193 ,

you don't need the unwrapping of the data service in the viewDidLoad() because you already retrieve it as computed property. The code in the viewDidLoad is not valid anymore as it changed with version 5 of the SDK. Kindly delete the dataService code in the viewDidLoad and proceed with the computed property.

Thanks,

Kevin

**Comment by juanfelipe82193** [comment]
Thanks Kevin!
