### ISSUE TITLE
Set Up Your Local Infrastructure to Develop with SAP Cloud SDK

### ISSUE THREAD

**Issue by horsemanjacky** [SAPDocuments/Tutorials#5404]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-setup.html

Please specify the step you are referring to

run in CMD with @powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

The error is : Access is denied.

**Comment by newtork** [comment]
Hello @horsemanjacky,

Please run the command with elevated rights, i.e. "as administrator":
![image](https://user-images.githubusercontent.com/22489773/86926272-261a3a00-c132-11ea-8ba1-c5ecac7bf9be.png)

Alternatively just install the required applications manually (as I do):
- adoptopenjdk8
- maven

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by bcschaich** [comment]
I do have exactly the same problem. It does not help to run as admin.

**Comment by MatKuhr** [comment]
@bcschaich I don't have a windows machine but I recommend to just skip this step and installing the required software (Java & Maven) manually if you don't have it installed already.
