### ISSUE TITLE
Test SAP HANA, express edition

### ISSUE THREAD

**Issue by ericmartorana** [SAPDocuments/Tutorials#5406]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-test-binary-xsa.html

Please specify the step you are referring to

Step 3: Test the Webide with the XSA_DEV user
We dont have the password of the XSA_DEV user. The one that was used during the install to create users hxeadm, SYSTEM, XSA_ADMIN, etc... is not working with this user XSA_DEV.

Thanks in advance.

Regards,

Eric Martorana.

**Comment by JCurrie27** [comment]
Hi Eric: You may have discovered a software bug here; the the master password you specified during installation ([here](https://developers.sap.com/tutorials/hxe-ua-installing-binary.html)) is supposed to be the password you enter at the step you mention. 

Many thanks if you could please log this issue on the HANA Express community **Q&A** page to take advantage of the community support model. The Q&A page receives much more traffic, and other users may be able to provide answers immediately.

To log your question on the Q&A page:

1. Go to **[https://answers.sap.com/questions/ask.html](https://answers.sap.com/questions/ask.html)**
2. Add a **Title**. Enter your GitHub question in the **Fill in the details...** form.
3. In **Select Primary Tag**, search for "express". Select **SAP HANA, express edition**.
4. Click **Submit your Question**.

Kind regards,
JCurrie27
