### ISSUE TITLE
Set Up SAP Business Application Studio for Development

### ISSUE THREAD

**Issue by chappel** [SAPDocuments/Tutorials#5409]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-onboarding.html

I can't set step 1 and step 5 to done. Nothing happens when I click on the Done buttons for those steps.

**Comment by raz-korn** [comment]
@thecodester - Can you look into this?

**Comment by thecodester** [comment]
I think this is a general problem. I am checking.
 
@raz-korn Can you put borders around the images? Also the images in Step 5, substeps 6 and beyond are unnecessarily large and can be cut off at the bottom (especially the very last one).

**Comment by thecodester** [comment]
@chappel  Looks like it is working now ... can you check?

**Comment by chappel** [comment]
@thecodester Worked today. Thanks!

**Comment by thecodester** [comment]
@chappel :-)

@raz-korn If you can make those small changes then we can close the issue

**Comment by raz-korn** [comment]
@thecodester : Made the changes, pushed, and created pull request.

**Comment by thecodester** [comment]
Changes in https://github.com/SAPDocuments/Tutorials/pull/5423
