### ISSUE TITLE
Connect Using the SAP HANA Node.js Interface

### ISSUE THREAD

**Issue by DanCummins-SAP** [SAPDocuments/Tutorials#5410]
Tutorial URL: https://developers.sap.com/tutorials/hana-clients-node.html

Please specify the step you are referring to

Step 3 (sample code - lines 12, 13)

    sslValidateCertificate: 'false',  //Must be set to false when connecting
    //to a HANA, express instance that uses a self signed certificate.

I think the comma is out-of-place ... and it means to say "to a HANA Express instance..."

**Comment by danielva** [comment]
I will update it to use the official name.
//Must be set to false when connecting
//to an SAP HANA, express edition instance that uses a self signed certificate.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
