### ISSUE TITLE
Develop a Fiori App Using the ABAP RESTful Programming Model (Managed Scenario)

### ISSUE THREAD

**Issue by aik-sap** [SAPDocuments/Tutorials#5412]
Hello,
I'm using the trial account.

Package: ZTRAVEL_APP_AIK_001
Step "Enhance Behavior With Action and Validation".

 During testing CREATE action, I'm constantly getting the message "An instance with the same key already exists". Somehow, only one record was added but all others keep failing. 

Thank you!

**Comment by MichaelCzcz** [comment]
@aik-sap Please name the tutorial you are referring to. Thank you.

**Comment by aik-sap** [comment]
Hi Michael,
Develop a Fiori App Using the ABAP RESTful Programming Model (Managed Scenario)
Enhance Behavior With Action and Validation
https://developers.sap.com/tutorials/abap-environment-behavior-action.html
Thank you!

**Comment by mervey45** [comment]
Hi @aik-sap,

can you please check if you have changed all XXXs with your number, otherwise this can happen.
CTRL + F -> search for XXX and replace all with your number.

Best regards, 
Merve

**Comment by aik-sap** [comment]
Not sure what was it. Replaced code in behavior definition with code from the tutorial and replaced _XX with my object number - it did the trick.
Thank you for the idea!

**Comment by aik-sap** [comment]
resolved.
