### ISSUE TITLE
CLA: Both links go to 404

### ISSUE THREAD

**Issue by ch264** [SAPDocuments/Tutorials#5419]
Both links in the CLA go to 404 : 

https://github.com/SAPDocuments/Tutorial-Contribution/blob/master/contributing.md
https://github.com/SAPDocuments/Tutorial-Contribution/blob/master/contributing.md

**Comment by MichaelCzcz** [comment]
Thank you for your feddback. You have posted one link twice. The link is working.

**Comment by thecodester** [comment]
@MichaelCzcz The link works for you because you have permission. The links should be changed and I will handle.

**Comment by thecodester** [comment]
We have updated the CLA
