### ISSUE TITLE
Connect to OData Service on Cloud Foundry Using SAP Cloud SDK

### ISSUE THREAD

**Issue by horsemanjacky** [SAPDocuments/Tutorials#5421]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-odata-service-cloud-foundry.html

Please specify the step you are referring to

mvn test -Derp.username=USER -Derp.password=PASSWORD

ends with error

nknown lifecycle phase ".username=". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, 
clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]

**Comment by MatKuhr** [comment]
I think on Windows you have to put the `-D` parameters in double quotes, so in this case:

```bash
mvn test "-Derp.username=USER" "-Derp.password=PASSWORD"
```

Sorry for the late reply, I missed the Github notification.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
