### ISSUE TITLE
Get Started with Spring Boot

### ISSUE THREAD

**Issue by renejeglinsky** [SAPDocuments/Tutorials#5424]
Tutorial URL: https://developers.sap.com/tutorials/spring-boot-getting-started.html

Please specify the step you are referring to: Note in Step 6

Hi,

the link to the official documentation is outdated/broken. Please update it with a current link. Thank you.

-René

**Comment by MichaelCzcz** [comment]
@maxstreifeneder @renejeglinsky Has this been fixed by now?

**Comment by maxstreifeneder** [comment]
hi @renejeglinsky, 

we'll remove the tutorial most likely! I will have a look at it tomorrow. Sorry for the late response. 

Cheers,
Max

**Comment by thecodester** [comment]
Tutorial removed
