### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by shaiSAP** [SAPDocuments/Tutorials#5429]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
Step 4: Test run the application

After pressing on Run Module icon, error message "Attribute 'program' does not exist ('{path}')." is raised.
It seems that the program defined in launch.json: ${workspaceFolder}/fioridemo-approuter/node_modules/@sap/html5-repo-mock/index.js doesn't exist.

**Comment by raz-korn** [comment]
Hi @shaiSAP ,

Please refer to issue [5300](https://github.com/SAPDocuments/Tutorials/issues/5300).

Regards - Raz

**Comment by shaiSAP** [comment]
> Hi @shaiSAP ,
> 
> Please refer to issue [5300](https://github.com/SAPDocuments/Tutorials/issues/5300).
> 
> Regards - Raz

Thanks for the quick response.
Following the hint regarding "npm install", I have found out there is an NPM Scripts view.
Executing "Run Install" seems to solve the issue.
![image](https://user-images.githubusercontent.com/67959112/87043730-30096f00-c1fe-11ea-8cf6-910dbb5eeb82.png)

I guess you should add this part to the tutorial.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
