### ISSUE TITLE
Deploy CAP Java App to SAP Cloud Platform - missing depdendency for cloud deployment

### ISSUE THREAD

**Issue by Uli-Tiger** [SAPDocuments/Tutorials#5432]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-deploy-cf.html

Step 2: Enable auto-configuration of SAP HANA database connection
its is mentioned to update the POM.xml with

```
<dependency>
        <groupId>com.sap.cds</groupId>
        <artifactId>cds-feature-cloudfoundry</artifactId>
</dependency
```
so far so good. **For me there was another dependency missing.** 

```
<dependency>
	<groupId>com.sap.cds</groupId>
	<artifactId>cds-feature-hana</artifactId>
</dependency>
```

without the second dependency starting of the application failed, with error

``` 
 2020-07-09T15:35:51.81+0200 [APP/PROC/WEB/0] OUT Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
   2020-07-09T15:35:51.81+0200 [APP/PROC/WEB/0] OUT Reason: Failed to determine a suitable driver class
```
I hope i did not over read this. Maybe also dependent on the maven archetype version used to generate the project...
**Anyhow, it could be worth just to add hint to check whether this dependency is present in the POM as well.**

**Comment by maxstreifeneder** [comment]
Hi @Uli-Tiger, 

good observation in general :-) not sure if you have done the previous tutorial in the set of tutorials ( = called Mission): https://developers.sap.com/tutorials/cp-cap-java-hana-db.html

There's the instruction to add the dependency in Step 4 :-)

Please reopen the issue if you have any further problems with the tutorial. 

Cheers,
Max
