### ISSUE TITLE
Get a Free Trial Account on SAP Cloud Platform

### ISSUE THREAD

**Issue by patriciachac** [SAPDocuments/Tutorials#5434]
Tutorial URL: https://developers.sap.com/tutorials/hcp-create-trial-account.html

Please specify the step you are referring to

An error occurred during JWT validiation. The JWT is expired. Therefore please check your local system clock.

**Comment by IObert** [comment]
Hi,

I'm sorry to hear you are facing some issues. Can you please provide more details like the step you are referring to and where you see this error message?

**Comment by IObert** [comment]
Please reopen with details if the issue still persists.
