### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code: cds not installing properly

### ISSUE THREAD

**Issue by seanpmcn** [SAPDocuments/Tutorials#5435]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

In step 1, the tutorial says to install cds using the command `npm i -g @sap/cds-dk` in shell or bash. It does not say in what folder or what application. I tried to do the command in VS Code's powershell, and it seemed to work, but when I ran the comand `cds` as instructed, I received the following error: 

![vs error](https://user-images.githubusercontent.com/46979553/87101930-60f99c00-c21e-11ea-8f0d-6f289bc319c0.PNG)

**Comment by iwonahahn** [comment]
Please open a command line window/terminal and run `npm i -g @sap/cds-dk`. As mentioned in the tutorial this process takes some minutes installing the cds command. Are you using MacOS or Windows?

**Comment by seanpmcn** [comment]
I am using Windows. When I run the command in the command prompt, it installs quickly. When i run `cds` I am met with an error.
![cmd](https://user-images.githubusercontent.com/46979553/87169591-39e2af00-c29e-11ea-86ca-a181af1565bb.PNG)

**Comment by iwonahahn** [comment]
Hi,

please check if your environment variables are properly set on Windows for npm and Node, as described in the [troubleshooting guide](https://cap.cloud.sap/docs/advanced/troubleshooting#npm-installation). 

Best regards,
Iwona
