### ISSUE TITLE
Create A New Welcome Card

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Tutorials#5439]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html

Please specify the step you are referring to

Step 4: View the Welcome Card in Mobile Cards Client

Issue :  In tutorial , it is mentioned that "You should see **two** Welcome Card in your Mobile application. One created through the cockpit, and the other created using SAP Cloud Platform Boosters for SAP Mobile Cards."

Actual Result :In android device,  i am getting only **one** Welcome card ie.,  "Booster Welcome card".

Please change this step in the document that user will get only one welcome card in device i.e., "Booster Welcome Card".

**Comment by sandeep-tds** [comment]
Hi @mounikat987 

Thank you for raising the issue. I will update the document in the upcoming release.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
