### ISSUE TITLE
Create Cards with Actions to Enable Workflows (Like Approve Or Reject)

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Tutorials#5442]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-action.html

Please specify the step you are referring to

Step 8: Cross verify status update in the back end

Actual Result :

In "Entity Property" Dialog box, the button displayed in document is 'OK'.But, the actual button displayed is 'Select'.
![Select](https://user-images.githubusercontent.com/33411431/87145516-11bb7600-c2c7-11ea-8b4a-8495b475e56c.PNG)

Please change the screenshot.

**Comment by sandeep-tds** [comment]
Hi @mounikat987 

Thank you for raising the issue. We will update the screenshot in the upcoming release.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
