### ISSUE TITLE
Learn Annotation Basics for OData and Fiori

### ISSUE THREAD

**Issue by Jose-Angel83** [SAPDocuments/Tutorials#5443]
Tutorial URL: https://developers.sap.com/tutorials/odata-04-basic-annotations.html

**In Step 5: Specify the OData service**, I get stuck in the screenshot attached, even though username and password are ok, the system keeps asking me this information and can't move forward. Could you support me to get this resolved?, 

Thanks,
![SAP Gateway ES5](https://user-images.githubusercontent.com/68109066/87147924-c21c8080-c2ad-11ea-81cf-611e861f2bc6.JPG)

@qmacro

**Comment by qmacro** [comment]
Hey @Jose-Angel83 this issue system is for problems with tutorial content itself - I'd definitely recommend you use the SAP Community Q&A to ask about this. But briefly - ensure you haven't locked yourself out of ES5 and also check you've specified the sap-client in the destination. Good luck!
