### ISSUE TITLE
Create Cards with Actions to Enable Workflows (Like Approve Or Reject)

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5446]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-action.html

Please specify the step you are referring to : Step 6: Deploy a new version of the Card : Once card is successfully saved after performing previous step it is navigating to Card template. So add a step to navigate inside the Automatic card instance

Tutorial 
No step mentioned to navigate inside the Automatic card instance
![image](https://user-images.githubusercontent.com/50734023/87152470-5fd67680-c2d3-11ea-9708-23481a9154d4.png)

Actual
![image](https://user-images.githubusercontent.com/50734023/87152491-6cf36580-c2d3-11ea-85d2-0e419233b637.png)

Also there is no edit button for the newly created version of card.

Tutorial
![image](https://user-images.githubusercontent.com/50734023/87152774-f014bb80-c2d3-11ea-91b7-089eee423b97.png)

Actual
![image](https://user-images.githubusercontent.com/50734023/87152790-f9058d00-c2d3-11ea-9684-075f79371ad1.png)

Regards,
Nidhi

**Comment by sandeep-tds** [comment]
Hi @NidhiMurkute, 

Thank you for raising the issues: 

* Issue 1 
    ```
         Tutorial
         No step mentioned to navigate inside the Automatic card instance
    ```
    At the end of the last step, we are already in the automatic instance card. This is why we see the **Info** tab.

* Issue 2 - Updated the screenshot.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
