### ISSUE TITLE
Create Cards with Actions to Enable Workflows (Like Approve Or Reject)

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5447]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-action.html

Please specify the step you are referring to : Step 8: Cross verify status update in the back end 

Change the screenshot as below,
Tutorial
![image](https://user-images.githubusercontent.com/50734023/87154191-69151280-c2d6-11ea-86cc-603af6de9453.png)

Actual
![image](https://user-images.githubusercontent.com/50734023/87154209-729e7a80-c2d6-11ea-9f6d-49eac9acac55.png)

Also in Entity properties dialog, if we select some additional properties to display, the existing properties will be removed and only selected one's will show. It would be great if the select dialog retains the already selected properties.
(For e.g. https://sapui5.hana.ondemand.com/#/entity/sap.m.SelectDialog/sample/sap.m.sample.SelectDialog)

Regards,
Nidhi

**Comment by sandeep-tds** [comment]
Hi @NidhiMurkute  

Thank you for raising the issue. We will update the screenshot in the upcoming release.

The behaviour you've highlighted is expected. 
```
Also in Entity properties dialog, if we select some additional properties to display, the existing properties will be removed and only selected one's will show. It would be great if the select dialog retains the already selected properties.
(For e.g. https://sapui5.hana.ondemand.com/#/entity/sap.m.SelectDialog/sample/sap.m.sample.SelectDialog)
```

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
