### ISSUE TITLE
Create a Calculation View with K-anonymity (XS Advanced)

### ISSUE THREAD

**Issue by davidborbely** [SAPDocuments/Tutorials#5448]
Tutorial URL: https://developers.sap.com/tutorials/xsa-calculation-views-anonymization-k.html

Please specify the step you are referring to

In Step 6, there is a question asked: "What is the value of the first Origin Country?", but there is no opportunity to submit an answer.
It would be an important step, to be able to check whether our solution was correct.

**Comment by thecodester** [comment]
@jung-thomas I see that you defined a question in the rules file (What does it say under the Mapped Spaces column for the tenant database?) -- do you want me to republish and put this question in? Should I remove the question that is there now (Sort the column CURRENT TENURE descending. What is the value of the first Origin Country?)?

**Comment by jung-thomas** [comment]
There are no formal questions defined in this tutorial. Its just asking you to check your work.  There is system validation defined or intended here. Works as intended.
