### ISSUE TITLE
Set Up Workflow Management in Cloud Cockpit

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5449]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html

Please specify the step you are referring to : Step 2.8 : Setup Fiori Launchpad 
Change of screenshot for build option
Tutorial
![image](https://user-images.githubusercontent.com/50734023/87164230-29562700-c2e6-11ea-8bcf-a1e0c8ea5dc2.png)

Actual
![image](https://user-images.githubusercontent.com/50734023/87164248-2e1adb00-c2e6-11ea-8213-401f621793c6.png)

The same screenshot change needs to be done in Tutorial 3 Step 3.8

Also in Step 3 : Configure destination
Observed that the destination was configured already with trial credentials. So not required to perform this step. Please update the same accordingly.

Regards,
Nidhi

**Comment by ArchanaShukla** [comment]
Ok, Will change the screenshot.
If you read carefully the Configure Destination step, it does not ask you to create the destination but just to update the password. Yes destination is created but the password has to be entered by the user. 

@MichaelCzcz - Please  close the ticket

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by NidhiMurkute** [comment]
The tutorial is not yet updated with mentioned screenshot.

**Comment by mounikat987** [comment]
Hi,

This issue still exist in trial US region.

Please update the screenshot w.r.to Build.


Thanks
Mounika
