### ISSUE TITLE
Here New is missing. We have to select New->ABAP Package

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5452]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-persistence.html

**Step: 1: Create ABAP Package.**
Here after we right click on the ZLOCAL pakage, we have to select New and then we have to select ABAP Package.
Here please include New
![image](https://user-images.githubusercontent.com/65999547/87166851-c8305280-c2e9-11ea-8ae7-cc902d309e41.png)

Best Regards,
Priyanka

**Comment by mervey45** [comment]
Hi @I537413,

thank you, we'll update this as soon as possible.

Best regards, 
Merve

**Comment by julieplummer20** [comment]
Hi Priyanka, @I537413,
I have  fixed this. You should see the changes soon.
BR Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
