### ISSUE TITLE
Step was skipped during execution

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5453]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-persistence.html

**Step: 1: Create ABAP Package.**

Here during execution, below Step was skipped and went directly to the next step where Transport request is created
![image](https://user-images.githubusercontent.com/65999547/87167646-eba7cd00-c2ea-11ea-8cf6-17fc9c89585e.png)

Regards,
Priyanka

**Comment by mervey45** [comment]
Hi @I537413 ,

thank you, we'll update this as soon as possible.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
