### ISSUE TITLE
@AbapCatalog.dataMaintenance : #LIMITED Issue

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5454]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-persistence.html

**Step 2: Create database table**

Here When we add @AbapCatalog.dataMaintenance : #LIMITED in the database table ZTRAVEL_XXX, We get the below warning in console,
![image](https://user-images.githubusercontent.com/65999547/87168172-b5b71880-c2eb-11ea-9048-9acbac27c416.png)

When we save the database table, @AbapCatalog.dataMaintenance : #LIMITED is automatically set to @AbapCatalog.dataMaintenance : #RESTRICTED as below:
![image](https://user-images.githubusercontent.com/65999547/87168286-de3f1280-c2eb-11ea-9840-2908137b7e34.png)

Please change this in the document.

Regards,
Priyanka

**Comment by mervey45** [comment]
Hi @I537413 ,

thank you, we'll update this as soon as possible.

Best regards, 
Merve

**Comment by julieplummer20** [comment]
Hi Priyanka, @I537413,
I have fixed this. You should see the changes soon.
BR Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
