### ISSUE TITLE
Update the screenshot for the List report html5 module template

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5455]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

**Step 5: Create HTML5 module**

Screenshot while creating the list report Html5 module is changed, please change this in the document.
**Old Screenshot:**
![image](https://user-images.githubusercontent.com/65999547/87168708-881e9f00-c2ec-11ea-8ba6-713e71e60866.png)

**New Screenshot:**
![image](https://user-images.githubusercontent.com/65999547/87168761-9bca0580-c2ec-11ea-9b3a-8c3a855779fd.png)

Please update the document.

Regards,
Priyanka

**Comment by mervey45** [comment]
Hi @I537413 ,

thank you, we'll update this as soon as possible.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
