### ISSUE TITLE
Build with Cloud MTA Build tool is Changed to Build

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5456]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

**Step 11: Deploy UI to Cloud Foundry**

Here the build with MTA build tool is changed to build

**Old screenshot**
![image](https://user-images.githubusercontent.com/65999547/87169055-08dd9b00-c2ed-11ea-9748-5c1c1dbc82f1.png)

**New screenshot**
![image](https://user-images.githubusercontent.com/65999547/87169124-21e64c00-c2ed-11ea-95b9-aa97bcb9f088.png)

Please update the document

Best Regards,
Priyanka

**Comment by mervey45** [comment]
Hi @I537413 ,

thank you, we'll update this as soon as possible.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
