### ISSUE TITLE
Save step is missing

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5457]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

**Step 10: Create SAP Fiori launchpad site module**

Here after adding the project app to the created group, We have to save the CommonDataModel.json file.
Here Save step is missing.
Please include this in document.

Regards,
Priyanka

**Comment by mervey45** [comment]
Hi @I537413 ,

thank you, we'll update this as soon as possible.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
