### ISSUE TITLE
Create a List Report Object Page App with SAP Fiori Tools

### ISSUE THREAD

**Issue by juanfelipe82193** [SAPDocuments/Tutorials#5458]
Group URL: https://developers.sap.com/group.fiori-tools-lrop.html

Hi, all tutorials in this group are completed but the group % is showing only 75% for me.

Thanks.

**Comment by cjbernal** [comment]
Hi Juan,

Sorry to hear you're having trouble. @thecodester Do you have any idea why this might be the case?

Thanks and regards,
Conrad

**Comment by thecodester** [comment]
@juanfelipe82193 Sorry for the delay. Can you  go through the 4 tutorials and let me know what steps were not completed

**Comment by juanfelipe82193** [comment]
Hi, please see screenshots below.

![Screen Shot 2020-08-06 at 9 03 54 AM](https://user-images.githubusercontent.com/58919119/89541427-f78c8f00-d7c3-11ea-92a1-35500be06bf6.png)
![Screen Shot 2020-08-06 at 9 04 45 AM](https://user-images.githubusercontent.com/58919119/89541432-f9eee900-d7c3-11ea-9eeb-5e69f3511d16.png)

Thank you!

**Comment by thecodester** [comment]
Thanks for the images. I am checking on this. Will come back soon.

**Comment by thecodester** [comment]
Still investigating

**Comment by thecodester** [comment]
@juanfelipe82193 Can you send me your SAP community ID (P number)? You can send to my email -- daniel.wroblewski@sap.com

**Comment by thecodester** [comment]
Can you check or show me that you actually completed the steps in the tutorial "Set up and generate ...." ?

**Comment by thecodester** [comment]
@juanfelipe82193 Can you let me know if this is still a problem? Send image inside tutorial showing all steps completed, and then show the group page again.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
