### ISSUE TITLE
Getting a warning message on deployment

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5459]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

**Step 3: Deploy using cf push**

Here when we perform the cf push -f gen/db operation we get the below warning 
**"odata.version='v2' not supported by node runtime, define odata.version='v4' in package.json instead"**
![image](https://user-images.githubusercontent.com/65999547/87169840-29f2bb80-c2ee-11ea-956f-dc63076f3913.png)

From an end user perspective, please include a step to state that this warning might come while push operation.

Best Regards,
Priyanka

**Comment by iwonahahn** [comment]
Hi Priyanka,

The dev colleagues are still working on a new version and with the next release, this hint will disappear. 

Best regards,
Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
