### ISSUE TITLE
Let Customers Ask Chatbot for Shipping Price

### ISSUE THREAD

**Issue by jjournot** [SAPDocuments/Tutorials#5460]
Tutorial URL: https://developers.sap.com/tutorials/cai-bot-shipping-3-price-parcel.html

2 points to be addressed:

- In step 1, near the end, when we need to add the entities values for each group. This cannot be done unless you add the rate-parcel intent. I assume you need to have the entity tagged at least in one intent to be able to retrieve the values in this selector.

- the final question: In a skill, what actions can you take?

Send message if requirement is missing
Call webhook
Send Quick Replies message
Update the memory

All answers are corrects to me and yet, the first one: "Send message if requirement is missing" is considered invalid.

**Comment by thecodester** [comment]
@jjournot I fixed the question. On the first point, I am able to create the groups without any intent involved.

**Comment by thecodester** [comment]
@jjournot Do you have any more issues?

**Comment by jjournot** [comment]
@thecodester nothing else I believe. I created tickets for the few things I encountered while doing the tutorials. Thanks for addressing the problems. It's really great material overall.
