### ISSUE TITLE
Build a Webhook for a Chatbot using Python

### ISSUE THREAD

**Issue by jjournot** [SAPDocuments/Tutorials#5461]
Tutorial URL: https://developers.sap.com/tutorials/conversational-ai-webhook-script-python.html

Needs an update at the following line:
"You can test this by opening Postman, and calling the endpoint https://localhost:5000/bot (with POST method and no body)."

the URL should be HTTP and not https. otherwise, postman is returning an SSH error.

**Comment by thecodester** [comment]
Fixed https://github.com/SAPDocuments/Tutorials/commit/5a802932e997ba58842e7123cfbbfcd309d46e6d
