### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by ASRHARDING** [SAPDocuments/Tutorials#5462]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Please specify the step you are referring to - Step 8

When I perform the last step in Postman to POST the body "productIdentifier": "HT-2000" request I only get "<Products/>" as the response, not the equipment details for HT-2000 shown in the tutorial. I get no errors in the CPI message log so all appears to work OK and I have rechecked I followed all the tutorial steps correctly. 

Why don't I get the expected response of equipment details for HT-2000?

Postman
![T00817 - Postman Response (1)](https://user-images.githubusercontent.com/57531943/87193420-966eba00-c2f0-11ea-93a9-6bc62115be08.png)

CPI Message Log entry
![T00817 - CPI Message Log](https://user-images.githubusercontent.com/57531943/87193437-9c649b00-c2f0-11ea-81b2-80e6a089414f.png)

Kind regards, Andrew

**Comment by Vikramkulkarni01** [comment]
Hi @ASRHARDING, 

Thank you for reaching out to us. 

Could you please re-deploy the integration flow and check if it works or not?
If the same issue persists, please share the below details with me?

1. Global account ID
2. Sub account ID

This will help me to investigate the issue further. 

Regards, 
Vikram Kulkarni

**Comment by ASRHARDING** [comment]
Hi Vikram

I have redeployed the integration flow, then tried both a POST and GET request. Still get the same response of "<Products/>" only. The message log says the messages were processed successfully. 

I have used a P account which has not been upgraded to a Global ID. Should I try upgrading my P account to a Global account ID?

I documented what I did to setup the flow, hopefully this helps you spot what is not working.

[T00411 - Design and Test Your First Integration Flow.docx](https://github.com/SAPDocuments/Tutorials/files/4912577/T00411.-.Design.and.Test.Your.First.Integration.Flow.docx)

Many thanks
Andrew

**Comment by ASRHARDING** [comment]
Hi Vikram

I have re-provisioned Integration Suite, replacing Process Integration, and re-built the flow from scratch. It now works :)
However, the new "Set Up Integration Suite Trial" tutorial, replaces "Set Up Your SAP Cloud Platform Integration Tenant", did not include the Step to "Create service instance and key". I had to copy the guide given in "Set Up Your SAP Cloud Platform Integration Tenant" Step 5 to create the ClientID & ClientSecret.
Please update "Set Up Integration Suite Trial" to include this missing step.

Thanks, Andrew
