### ISSUE TITLE
Provide proper message for the latest UI version

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5463]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html#d19bae73-798b-461c-a06c-e5f7d42ec7d4
 in step 1, after selecting MTA, automatically the latest SAP UI5 version is picked up (which is expected also), but looking at the screenshot, user might try to select that specific SAP UI5 version
Proposed solution: A message can be provided with the screenshot that it will automatically pick the latest SAP UI5 version.

Please refer to screenshots for clarification.
<img width="1224" alt="UIVersionOLD" src="https://user-images.githubusercontent.com/66831161/87226976-2f670900-c3b5-11ea-8299-8eb6652da2f6.png">
<img width="859" alt="UIversionNEW" src="https://user-images.githubusercontent.com/66831161/87226979-33932680-c3b5-11ea-8476-7e2e8e67da5d.png">

Thanks & Regards,
Shubham

**Comment by mervey45** [comment]
Hi @I537413 ,

thank you, we'll update this as soon as possible.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
