### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by peterli-code** [SAPDocuments/Tutorials#5464]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to

Hi There,

Tried to follow the steps but encountered problem with Step 8. Further details below:

Step | Parameter | Value
-- | -- | --
A | Select a system | My SAP systems                    <-- OK - dropdown value selectable
B | Select a source | ES5_BASIC_AUTH [Catalog]    <-- could not get this entry to be accepted (Forced to choose ES5 [Catalog] in dropdown and once selected asked for Gateway Authentication name and password for which I entered valid credentials? but  got "Not Authorized" when I clicked on Login button
C | Select a service | GWSAMPLE_BASIC  <---- Not available

And could not get project to be created. (next button was disabled).

Could you please clarify what action is required? Thanks in advance,

Regards
Peter

**Comment by raz-korn** [comment]
Hi Peter,

The ES5 destination should be configured in the subaccount from which you launch SAP Business Application Studio. In the Cockpit, below the Subscriptions tab (that you used in order to access AppStudio) there's the Connectivity tab, and within it there's the Destination option. In here the ES5 destination should be configured.

Please also refer to the following ES5 destination creation [tutorial](https://developers.sap.com/tutorials/cp-portal-cloud-foundry-gateway-connection.html).

Regards,
Raz

**Comment by peterli-code** [comment]
Hi Raz
I have already subscribed to ES5 Gateway and it still does not seem to register when I go back into SBAS and use it. It still comes up with the only option ES5 [Catalog]  in the dropdown. So I cannot pick GWSAMPLE_BASICas the next in Select a Service option. I must be missing something here but have no clue what.
I cannot progress with the tutorial steps from there.
Thanks & Regards
Peter
    On Monday, 13 July 2020, 13:52:02 BST, Raz Korn <notifications@github.com> wrote:  
 
 


Hi Peter,

The ES5 destination should be configured in the subaccount from which you launch SAP Business Application Studio. In the Cockpit, below the Subscriptions tab (that you used in order to access AppStudio) there's the Connectivity tab, and within it there's the Destination option. In here the ES5 destination should be configured.

Please also refer to the following ES5 destination creation tutorial.

Regards,
Raz

**Comment by raz-korn** [comment]
Hi Peter,

- Are you able to access the [ES5 service](https://sapes5.sapdevcenter.com/sap/opu/odata/iwbep/GWSAMPLE_BASIC/$metadata) directly?

- Can you share screenshots of your destinations? In addition a screenshot of the ES5 destination configuration?

Regards - Raz

**Comment by peterli-code** [comment]
Hello again, I did get further this time. See attached scrshots but now cannot progress beyond Run configurations. Please let me in know any suggestions. Thanks in advance,
[Document.docx](https://github.com/SAPDocuments/Tutorials/files/4921553/Document.docx)

**Comment by raz-korn** [comment]
Hi Peter,

Great to hear that connecting to ES5 is working properly.

I tried reproducing the Run Configuration issue, but without success. I'll check with my colleagues.
Meanwhile, can you try the following workaround:
- open the Explorer pane (the top button on the left side).
- refresh the browser and wait until the Welcome page appears (if the "Show welcome page on startup" is checked), or wait until the "NPM SCRIPTS" section in the explorer pane gets filled with content.
- Proceed with creating the run configuration, etc.

Also - please share if 
- a launch.json file was created inside a .vscode folder in the project's root directory.
- a .env file was created inside the HTML5 module folder (BusinessPartners folder).
These files contain the content of the created run configuration. Please share their content / screenshot.

Regards - Raz

**Comment by peterli-code** [comment]
Hi Raz, I progressed a little bit more. 
[Document2.docx](https://github.com/SAPDocuments/Tutorials/files/4924815/Document2.docx)
Please find attached the steps where I got to this time round. Please suggest if any workaround. Thanks a lot.

**Comment by raz-korn** [comment]
Hi Peter,

As you probably guessed, all run configurations were created, but were not displayed.
The issue you experience now is a known issue - see issue [5300](https://github.com/SAPDocuments/Tutorials/issues/5300).

Regards, Raz

**Comment by peterli-code** [comment]
Hi Raz

No luck.I did the workaround but still receive same error when I run the conf again.Picked another run conf and get the same. Please see attached and check bottom 2 screenshots. Thanks.
Regards Peter
[Document2.docx](https://github.com/SAPDocuments/Tutorials/files/4924961/Document2.docx)

**Comment by raz-korn** [comment]
Hi Peter,

It looks like npm install was run in the wrong directory. it should be run in the approuter directory. In your case something like "fd2-approuter", which is inside "fd2" directory. If you right-click "fd-2-approuter" directory in the explorer and choose "Open in terminal", the terminal will open in the right directory for executing the npm install.

Regards - Raz

**Comment by peterli-code** [comment]
Hello Raz

I finally managed to complete all 8 steps in the tutorial. Thank you for your assistance. 
I wonder if you can tell me if there are any more tutorials like this one that I can go thru to enhance my experience of this trial cloud environment.

Regards
Peter
P.S Either Yourself or an Admin can close this issue log now. Thanks very much.

**Comment by raz-korn** [comment]
Hi Peter,

Excellent!
Despite the hick ups, I hope that you see the benefits of the new development environment and feel comfortable with it.

I'm not sure what exactly you mean by "experience of this trial cloud environment", but I suggest the following:

- Enhance your knowledge of AppStudio, including hands-on, visit the [homepage](https://community.sap.com/topics/business-application-studio), or filter the [tutorials ](https://developers.sap.com/tutorial-navigator.html?tag=products:technology-platform/sap-business-application-studio) for it.

- If you're interested in a specific business scenario or product: You can visit [SCP Discovery Center](https://discovery-center.cloud.sap/) and start your journey with a specific mission or look for the missions related to a specific service. Additional options are to filter the [tutorials](https://developers.sap.com/tutorial-navigator.html) based on a specific topic or product or visit the relevant product page on [SAP Community](https://community.sap.com/topics). 

I'm sure that by googling you'll find additional resources :-)

Regards - Raz

**Comment by peterli-code** [comment]
Hello Raz
Thanks a lot for the help. Much appreciated. As I am currently on a trial sap cloud account that's what i meant. I will look into those urls and hope I can find more interesting tutorials like your one. Yes Google is the answer to everything if you know what to look for. Cheers.
RegardsPeter Li 
    On Wednesday, 15 July 2020, 15:34:03 BST, Raz Korn <notifications@github.com> wrote:  
 
 


Hi Peter,

Excellent!
Despite the hick ups, I hope that you see the benefits of the new development environment and feel comfortable with it.

I'm not sure what exactly you mean by "experience of this trial cloud environment", but I suggest the following:
   
   -    
Enhance your knowledge of AppStudio, including hands-on, visit the homepage, or filter the tutorials  for it.

   -    
If you're interested in a specific business scenario or product: You can visit SCP Discovery Center and start your journey with a specific mission or look for the missions related to a specific service. Additional options are to filter the tutorials based on a specific topic or product or visit the relevant product page on SAP Community.


I'm sure that by googling you'll find additional resources :-)

Regards - Raz
