### ISSUE TITLE
For new user no site should exist is site directory

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5466]
Open below link
https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Step 3- Access Portal Service

Remark- For new user, no site should be present in site directory. Screenshot needs to be updated

Actual
![image](https://user-images.githubusercontent.com/7221229/87251466-9b1aa600-c489-11ea-92c9-40c3b9a0bbb2.png)

Expected
![image](https://user-images.githubusercontent.com/7221229/87251470-9fdf5a00-c489-11ea-823e-9f744ae1a326.png)

**Comment by LindsayBert** [comment]
Done

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
