### ISSUE TITLE
Screenshot update required for create site step

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5467]
Open https://developers.sap.com/tutorials/cp-portal-cloud-foundry-create-site.html

Step 1- Provide the site name 

Remark- Screenshot should be updated

Actual
![image](https://user-images.githubusercontent.com/7221229/87251555-2e53db80-c48a-11ea-87cf-f2ee2fc91b77.png)

Expected
![image](https://user-images.githubusercontent.com/7221229/87251562-36ac1680-c48a-11ea-83f9-3eb46b51746d.png)

**Comment by IrisSasson** [comment]
Hi - i do not understand the difference between Actual and expected screenshots, can you explain?

**Comment by MichaelCzcz** [comment]
@IrisSasson I think @Mukesh-50 is referring to the "Import Site" button.

**Comment by IrisSasson** [comment]
Hi
We are planning an update of the tutorials at the end of this month

Thanks
Iris.

**Comment by MichaelCzcz** [comment]
@IrisSasson Can I close this issue?

**Comment by MichaelCzcz** [comment]
@IrisSasson Did you update the tutorial and can I close this issue?

**Comment by IrisSasson** [comment]
Yes, you can close it
