### ISSUE TITLE
Portal-Screenshot update required for design site menu

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5468]
Open https://developers.sap.com/tutorials/cp-portal-cloud-foundry-create-site.html

Step 3- Design the site menu

Remark- Screenshot update required.

Actual
![image](https://user-images.githubusercontent.com/7221229/87252023-8d671f80-c48d-11ea-8913-b6b4df0360b3.png)

Expected
![image](https://user-images.githubusercontent.com/7221229/87252024-922bd380-c48d-11ea-8c20-74eadbae8bf8.png)

**Comment by IrisSasson** [comment]
Hi, I do not understand the difference between expected and actual screenshots - can you please explain?

**Comment by MichaelCzcz** [comment]
@IrisSasson I think @Mukesh-50 is referring to the Translation tab that is missing in the "expected" screenshot.

**Comment by IrisSasson** [comment]
Hi
We are planning to update all tutorials at the end of this month

Thanks for your comment

Iris

**Comment by IrisSasson** [comment]
Hi, 
All tutorials were replaced with Launchpad tutorials. Please use the Launchpad service tutorials instead

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
