### ISSUE TITLE
Portal- Screenshot update for configure new app

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5469]
Open https://developers.sap.com/tutorials/cp-portal-cloud-foundry-url-app.html

Remark- For new user only default option is present  

Actual
![image](https://user-images.githubusercontent.com/7221229/87252080-09f9fe00-c48e-11ea-948a-dd6d3db34011.png)

Expected
![image](https://user-images.githubusercontent.com/7221229/87252083-0cf4ee80-c48e-11ea-8d7e-e52c599b13c9.png)

**Comment by IrisSasson** [comment]
Hi, this issue was fixed, please see it fits your ask and close or comment

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
