### ISSUE TITLE
Portal- Screenshot update for review site

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5470]
Open https://developers.sap.com/tutorials/cp-portal-cloud-foundry-url-app.html#ff1f1f91-5352-4e03-bceb-4784ff558f73

Step 6- for the new user no new order app and purchasing group is present- Screenshot has to be updated.

Actual
![image](https://user-images.githubusercontent.com/7221229/87252130-65c48700-c48e-11ea-9427-065e67efde73.png)

Expected
![image](https://user-images.githubusercontent.com/7221229/87252140-6b21d180-c48e-11ea-8577-0226b14801d7.png)

**Comment by LindsayBert** [comment]
Done
