### ISSUE TITLE
Portal- Screenshot and Text update required for edit content

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5471]
Open https://developers.sap.com/tutorials/cp-portal-cloud-foundry-add-webcontent.html

Step 3- add own content to the site

Remark- screenshot has to be updated with text field.

Actual
![image](https://user-images.githubusercontent.com/7221229/87252325-bdafbd80-c48f-11ea-949e-b3494661b9b3.png)

Expected
![image](https://user-images.githubusercontent.com/7221229/87252332-cc967000-c48f-11ea-8fbe-1bb23b8644dc.png)

**Comment by IrisSasson** [comment]
Hi
This issue was fixed, please confirm and close or comment

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
