### ISSUE TITLE
Portal- Main Tutorial page link should be updated

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5472]
Open below link
https://developers.sap.com/mission.cp-starter-digitalexp-portal.html

Expected- Last tutorial name should be **Add URL App to Your Portal Site**

Actual
![image](https://user-images.githubusercontent.com/7221229/87252596-ffd9fe80-c491-11ea-9cad-a6ef69e8772c.png)

**Comment by thecodester** [comment]
Fixed
