### ISSUE TITLE
Portal- Screenshot is missing after review site

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5473]
Open tutorial 4
https://developers.sap.com/tutorials/cp-portal-cloud-foundry-url-app.html#ff1f1f91-5352-4e03-bceb-4784ff558f73

Step 6- Review the site

Actual Result- Screenshot is missing

Expected Result- After clicking on Innovation at SAP tile- Page should open
![image](https://user-images.githubusercontent.com/7221229/87252764-5431ae00-c493-11ea-8944-baacb4f40e24.png)

**Comment by IrisSasson** [comment]
Hi, we didn't put a screenshot on purpose as this page change often and we cannot update the tutorial on every update of this site

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
