### ISSUE TITLE
Create Your SAP Fiori Launchpad Project and its Module

### ISSUE THREAD

**Issue by SK-2014** [SAPDocuments/Tutorials#5474]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-2-create-module-cf.html

Please specify the step you are referring to 4.2
Copy the URL to your browser.

If the URL does not work, append /cp.portal to it.
This gives an internal server error as shown below-
https://4ccf4faftrial-dev-workflowtilesapprouter.cfapps.eu10.hana.ondemand.com/cp.portal/

![image](https://user-images.githubusercontent.com/34122145/87256303-ee531f80-c4ae-11ea-913d-8aa5f6bf7a88.png)

Regards,
Saritha K

**Comment by AstridHerbst** [comment]
Hi,
We are currently working on this tutorial. The content has to be adapted to use the SAP Business Application Studio before you can execute it.
Best regards,
Astrid

**Comment by MichaelCzcz** [comment]
@AstridHerbst Any updates?

**Comment by AstridHerbst** [comment]
Hi,

The new tutorial for Trial is available at: https://developers.sap.com/group.cp-workflow-cf.html 

Best regards, Astrid

**Comment by SK-2014** [comment]
Thank you Astrid.
Will try it out.

Regards,
Saritha
