### ISSUE TITLE
Onboard to SAP Integration Suite Trial

### ISSUE THREAD

**Issue by shilpavij** [SAPDocuments/Tutorials#5475]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

Please specify the step you are referring to

**Comment by shilpavij** [comment]
Step 2 point 3-  Europe frankfurt is not coming.

**Comment by Vikramkulkarni01** [comment]
Hi @shilpavij, 

Thanks for your feedback. 

Our internal teams are working on it. It will be available soon. 

 for the current scenario, you must select US region. 

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
