### ISSUE TITLE
Onboard to SAP Integration Suite Trial

### ISSUE THREAD

**Issue by shilpavij** [SAPDocuments/Tutorials#5476]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

Please specify the step you are referring to

Step 4 -point 2 add user is not coming. Kindly check

Not able to submit answer-Which of the following tiles you subscribed?

**Comment by Vikramkulkarni01** [comment]
Hi @shilpavij, 

Thank you for submitting your feedback. 

1. Add user option will be available for the new email IDs, if you are already using trial account it won't appear. 
2. to submit answer you must be logged into the tutorial just by clicking on the Logon option at the top right corner.

Please let me know if there are any further concerns. 

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
