### ISSUE TITLE
Build a Business Application Using CAP for Node.js

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5477]
Mission URL: https://developers.sap.com/mission.cp-starter-extensions-cap.html

In the Home page, the total time displayed for executing the scenario is incorrect.
Actual result : 1hr is displayed.

![image](https://user-images.githubusercontent.com/50734023/87280549-e5466a80-c50f-11ea-84b8-e1678a14f89b.png)

Expected result : 1hr 20mins should be displayed.

![image](https://user-images.githubusercontent.com/50734023/87280724-1888f980-c510-11ea-8dbb-82582a8a7874.png)

Regards,
Nidhi

**Comment by thecodester** [comment]
Fixed in the Tutorial Navigator. In the Starter Scenarios, don;t know if it takes some time.

@AnnikaGonnermann Can you look at this?

**Comment by AnnikaGonnermann** [comment]
Hi @thecodester:

changes show in the Cockpit: https://cockpit.hanatrial.ondemand.com/cockpit/#/home/trial
