### ISSUE TITLE
Portal- Screenshot Update after subscription of portal service

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5478]
Open https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Actual
![image](https://user-images.githubusercontent.com/7221229/87283676-2b50fd80-c513-11ea-96ee-f5f6a0aa08de.png)

Expected
![image](https://user-images.githubusercontent.com/7221229/87283691-2f7d1b00-c513-11ea-9ac6-3d31883ae518.png)

**Comment by LindsayBert** [comment]
Done

**Comment by IrisSasson** [comment]
Thanks!

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
