### ISSUE TITLE
Onboard to SAP Integration Suite Trial

### ISSUE THREAD

**Issue by durganav** [SAPDocuments/Tutorials#5483]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

Please specify the step you are referring to

Step 5 Point 2 - On clicking "Go to Application", I am being redirected to a page with the following error

```
<oauth>
<error_description>Insufficient scope for this resource</error_description>
<error>insufficient_scope</error>
</oauth>
```

**Comment by durganav** [comment]
When I tried again today morning, I don't have this issue anymore. I am able to proceed with the setup.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
