### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by masarubito** [SAPDocuments/Tutorials#5486]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Step 1 -- "Process Integration" is not available in the US East trial landscape.
And I've already tried Europe region subaccount too, but "Process Integration" appear in neither "Subscription" nor "Entity Assignments."

I followed steps of "Get a Free Trial Account on SAP Cloud Platform"(URL: https://developers.sap.com/tutorials/hcp-create-trial-account.html) when I created my trial account.

**Comment by Vikramkulkarni01** [comment]
Hi @masarubito, 

Thanks for reaching out to SAP. 

The onboarding to CPI tenant will be replaced with this https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html 

Could you please follow the exact steps mentioned In the above tutorial and let us know how it works for you?

You can unsubscribe the subscriptions or create a new subaccount to perform the steps.

Regards, 
Vikram Kulkarni

**Comment by masarubito** [comment]
Hi Vikram,

Thanks for replying and introducing a new version of tutorial.

Now I'm on almost end of "Set Up Integration Suite Trial" whose URL you send to me.

I subscribed "Integration Suite," chose all Capabilities, and activation went successful.

However, there is still a problem. I assigned all Role Collection that is needed for Cloud Integration to my account, but I cannot enter Design page of Cloud Integration.

<img width="433" alt="CloudIntegrationPage" src="https://user-images.githubusercontent.com/68256664/87655591-6eb99f00-c793-11ea-9859-923233c3758d.png">
<img width="704" alt="RoleCollection" src="https://user-images.githubusercontent.com/68256664/87655595-6feacc00-c793-11ea-8c2c-9aeae174d3b3.png">

Is there lack of my procedure?

Regards,
Masaru Ito

**Comment by masarubito** [comment]
Hi Vikram,

11 days after this comment, I find my Cloud Integration's Design and Discover page although I can't understand why they didn't appear 11 days ago...
![image](https://user-images.githubusercontent.com/68256664/88513495-582d0680-d023-11ea-980e-d9d01985084c.png)
Anyway, thanks for replying and introducing a new version of tutorial.

Regards,
Masaru Ito
