### ISSUE TITLE
Build a Java-based E-Commerce Site

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#5487]
Mission URL: https://developers.sap.com/mission.cp-java-ecommerce.html

I think that it should be clearly mentioned that this Mission is using the SAP CP Neo environment. Also I think it shouldn't be promoted anymore on [Twitter](https://twitter.com/wolf_gregor/status/1282780456686100483).

**Comment by thecodester** [comment]
@simonarangelova Can you update?

**Comment by simonarangelova** [comment]
Hello,
I am waiting for an official statement from the team and will provide it as soon as possible.

**Comment by simonarangelova** [comment]
Hello,
The mission and its description will be updated to include the Neo Environment.
Also, it will not be promoted anymore.

Thanks for the patience.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by gregorwolf** [comment]
I think it should not be closed yet as there is no enhanced description of the mission. And due to the coming shutdown of Neo Trial I think the mission should perhaps be removed completely.
