### ISSUE TITLE
Navigate around SAP Data Intelligence, Trial Edition

### ISSUE THREAD

**Issue by carl-lexsys** [SAPDocuments/Tutorials#5491]
Tutorial URL: https://developers.sap.com/tutorials/dataintelligence-trial-v2-navigation.html

Please specify the step you are referring to: 2

This step says to study the screenshot and answer a question based on the screenshot. However, no question is given and so it isn't possible to complete this step.

**Comment by dimvor** [comment]
Hi Carl, thanks pointing this out. I am pushing a change to fix this. 

https://github.com/SAPDocuments/Tutorials/pull/5505

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
