### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by Ms-fernandes** [SAPDocuments/Tutorials#5493]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to

Step 1: Create new SAP Fiori project
(8. )For Consume Services, select the following, and click Next.

In the above mentioned step,  
after i select system and source, it is asking me to enter user name and password for the backend system, and when i enter it says not authorized. Can you please guide me on this.

what is the user name and password for backend system.
where can i find and change it.
i entered as it was in the destination - ES5 Gateway user and password.
<img width="960" alt="Annotation 2020-07-14 160736" src="https://user-images.githubusercontent.com/65336409/87424073-65da9900-c5ec-11ea-8883-273cad102598.png">

**Comment by raz-korn** [comment]
Hi,

The user/pass that should be part of the destination configuration is the one that is used to access the ES5 system. You can try accessing the ES5 service directly using this [link](https://sapes5.sapdevcenter.com/sap/opu/odata/iwbep/GWSAMPLE_BASIC/$metadata). You should get a popup asking for your ES5 credentials. If you are able to access the ES5 service, then use the same credentials in the ES5 destination configuration. If you are not able, your user might be blocked and you need to reset it (follow this [tutorial](https://developers.sap.com/tutorials/gateway-demo-signup.html)).

Regards - Raz

**Comment by Ms-fernandes** [comment]
Hi Raz, 

It worked!! 
Thank you so much for the quick response.
I followed the tutorial you mentioned to reset the password and i was able to create my first SAP Fiori Project.
Many thanks..

Regards
