### ISSUE TITLE
Customize the Wizard Generated Application

### ISSUE THREAD

**Issue by VGordillo-Resulto** [SAPDocuments/Tutorials#5494]
Tutorial URL: https://developers.sap.com/tutorials/cp-sdk-android-wizard-app-customize.html

Language: Kotlin

Step 6: Add a Top Products section with a CollectionView

13 .Add the following methods to the class:

```
...
private class CollectionViewAdapter(current_activity: FragmentActivity, product_list: List<Product>) : CollectionView.CollectionViewAdapter() {
    ...
    override fun onBindViewHolder(collectionViewItemHolder: CollectionViewItemHolder, i: Int) {
        val cvi: CollectionViewItem = collectionViewItemHolder.collectionViewItem
        ...
    }
    ...
}
...
```
Android Studio returns an error:
`Cannot access 'CollectionViewAdapterInternal': it is package-private in 'com.sap.cloud.mobile.fiori.object'`

**Comment by jarjarbentley** [comment]
Bruce, let me know if we can address this issue or if we need to take tutorials offline for a little while.

**Comment by flyingfish162** [comment]
SDK for Android 3.1.0 does have such isuue. We fixed it in SDK for Android 3.1.2 and higher version.

**Comment by flyingfish162** [comment]
> Bruce, let me know if we can address this issue or if we need to take tutorials offline for a little while.

Tutorials don't have to go offline because I specify the version of SDK for Android (2.2.x) and Android Studio (3.5.x)  in the **_Prerequisites_** in the first tutorial which is good to the published tutorials. @VGordillo-Resulto is using SDK 3.1.0 and in this scenario, the tutorials are not fully applicable.

**Comment by flyingfish162** [comment]
Up-to-date tutorials will be published soon.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
