### ISSUE TITLE
Create Multi-Cloud Application Consuming Object Store Service

### ISSUE THREAD

**Issue by korayyersel** [SAPDocuments/Tutorials#5496]
Tutorial URL: https://developers.sap.com/tutorials/cp-objectstore-mc-java-app.html

Is it planned to provide examples with ACL usage for different providers (Azure, GCP, AWS)? As of now the only access management that I can think of is the usage of JWT tokens for scope checking on the Java Proxy App using Spring Boot. Is there a way combine JWT/scope check and ACL usage?

**Comment by indusankar89** [comment]
Hi,

we havent explored on ACL usgae with different provided. No sample is planned on the same for now. 
https://jclouds.apache.org/guides/aws/ shows how ACL can be done with jclouds library.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
