### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by rvodela** [SAPDocuments/Tutorials#5497]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

Some of the issues I faced with Cloud Integration Suite
I found 3 issues with the new Version on Cloud Foundry with the Integration

1 Open Connector issue on start up

The Authorisation I have
OpenConnectors_User which was added to my email id.

Global Account ID
S0009209636
Subaccount ID
09c657fe-1f14-4b85-9480-8587f3026315
 
The error I got when I clicked on link is No Authorised user found.
I'am not able to attach the screenshot
2) Cloud Connector and Foundry API management
I tested the cloud connector in Neo/API it works fine but not in the Integration Suite on the Foundry
 in the CPI on Foundry when I  do a connectivity test with cloud connector it passes but the destination fails
3) Gmail Configuration - Prior to the upgrade I had configured Gmail with SMTP and POP3 but the same steps are not working - When I test without Protection smtp.gmail.com at port 587 it passes with Server Certificate invalid but with TLS optional I get Exception could not convert to socket TLS.
I have PDF document with screen shots as well.   Please let me know if you need more info
Ramesh

**Comment by Vikramkulkarni01** [comment]
Hi Ramesh, 

Thanks for reaching out to us. 

Error screenshot, in this case, will be really helpful. 

Could you please copy-paste the image or just drag and drop the file in the reporting window.

This will help me to resolve this issue at the earliest. 


Regards, 
Vikram Kulkarni

**Comment by rvodela** [comment]
Vikram
Thanks for getting back to me.  Here is a PDF document I created with the screen shots
Please let me know if you need more info.
best regards
Ramesh
[CloudFoundryIssues.pdf](https://github.com/SAPDocuments/Tutorials/files/4925882/CloudFoundryIssues.pdf)

**Comment by rvodela** [comment]
Vikram
I also wanted to point out that in trial cloud foundry under the connections tab there is only option Destination and option to check Cloud Connector, unlike the NEO environment.  Does this mean we can't use the Cloud Connector in the Foundry environment? If this is the case is there a way around.  The Connectivity test with cloud connector passes but when I create the destination it fails.
Best regards
Ramesh

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by rvodela** [comment]
This issue is not resolved. I had informed Vikram as well.
Waiting to hear from him
R
