### ISSUE TITLE
XS Advanced, Create Database Artifacts Using Core Data and Services

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#5498]
Tutorial URL: https://developers.sap.com/tutorials/xsa-cap-create-database-cds.html

Please specify the step you are referring to 2

WebIDE fails to load the menu option (the plugin?) 'Build CDS' or 'CTRL+B' most of the time and only sometimes becomes available when creating a CAP project from a template. the log is showing CDS commands executing as expected.

Thank you!

**Comment by jung-thomas** [comment]
I'm sorry but I don't see any issue with the tutorial content itself here. If you are having technical issues with the Web IDE not working as it should, please report those via the SAP Community Q&A.
