### ISSUE TITLE
Create a Sample Application on Cloud Foundry Using SAP Cloud SDK

### ISSUE THREAD

**Issue by burreo** [SAPDocuments/Tutorials#5500]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-cloud-foundry-sample-application.html

Please specify the step you are referring to

I tried 
mvn archetype:generate -DarchetypeGroupId=com.sap.cloud.sdk.archetypes -DarchetypeArtifactId=scp-cf-tomee -DarchetypeVersion=RELEASE
and do
mvn install
but the java.security.acl.Group was marked as deprecated and seems to be removed.

**Comment by MatKuhr** [comment]
Hi burreo, I tried reproducing the issue on my machine but it went through smoothly, I didn't see any warnings.

Could you please run `install` with the `-X` flag and attach the relevant log output? Sorry for the late response.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
