### ISSUE TITLE
Define a Simple Data Model and OData Service with CDS

### ISSUE THREAD

**Issue by dwipayan99** [SAPDocuments/Tutorials#5506]
Tutorial URL: https://developers.sap.com/tutorials/odata-05-data-model-service.html

I am facing the problem in Step 9
When I am saving both of the files at the same time using the path **File > Save All** i am encountering an error.

8:22:25 PM (CDS build) Start CDS cleanup previous build.
8:22:25 PM (CDS build) Start CDS build execution task.
8:22:25 PM (Executor) The "Building CDS artifacts." process started.
8:22:25 PM (CDS build) Start CDS cleanup previous build.
8:22:25 PM (CDS build) Start CDS build execution task.
8:22:25 PM (Executor) The "Building CDS artifacts." process started.
8:22:26 PM (Content) All changes have been saved in all open files
8:22:29 PM (Executor) Starting process: "cd /projects/Products; export CDS_BUILD_NODEJS_EDMXGENERATION=true; export CDS_BUILD_MODE=inplace; export CDS_BUILD_OUTPUTFILE=.cds_gen.log; export GENERATION_LOG=.cds_gen.log; rm -f copy_back.zip; npm install && npm run build && cat .cds_gen.log | zip -@ copy_back.zip && zip copy_back.zip .cds_gen.log"
8:22:29 PM (CDS build) Build of "/Products" failed.
8:22:29 PM (CDS build) Build of "/Products" failed.

The last two line showing Build of "/Products" failed. Can anyone please guide me where i am doing the mistake, though i have followed the tutorial line by line. @qmacro

**Comment by greg2git** [comment]
this is a great tuturial. but wondering if it's going to be updated for Business Application Studio as parts of it seem to work for me there rather than on WebIDE.

**Comment by qmacro** [comment]
Thanks both. @dwipayan99 - this issue list is for problems relating to the actual tutorial content. For help on the error you're encountering, I'd advise you to please ask on the [SAP Community Q&A](https://answers.sap.com). 

@greg2git conversion of this tutorial (and its siblings) to App Studio is planned and has actually started. Watch this space! :-)
