### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by iMilazzo** [SAPDocuments/Tutorials#5507]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

Please specify the step you are referring to Step 2: Select application template

![image](https://user-images.githubusercontent.com/19697155/87583182-f16a2d80-c6b1-11ea-9dce-c837858bf5b7.png)

I have installed SAP Fiori tools - Extensions Pack

![image](https://user-images.githubusercontent.com/19697155/87583330-28404380-c6b2-11ea-9586-8397849102b2.png)

I'm unable to get this "tool" working !!!

Can you help me ?!

I'm using Visual Studio Code

Thanks
Ivan

**Comment by vandanadeep** [comment]
@MichaelCzcz Did you install the Fiori elements generator from [here](https://www.npmjs.com/package/@sap/generator-fiori-elements)

**Comment by iMilazzo** [comment]
> 
> 
> @MichaelCzcz Did you install the Fiori elements generator from [here](https://www.npmjs.com/package/@sap/generator-fiori-elements)

![image](https://user-images.githubusercontent.com/19697155/87713323-6310ad00-c780-11ea-97c7-c53ea44cd94c.png)

**Comment by iMilazzo** [comment]
> 
> 
> @MichaelCzcz Did you install the Fiori elements generator from [here](https://www.npmjs.com/package/@sap/generator-fiori-elements)

I tried with a different syntax but didn't work: 
![image](https://user-images.githubusercontent.com/19697155/87713475-a2d79480-c780-11ea-9adf-c492d54115f5.png)

**Comment by theStiggySpd** [comment]
Hi @iMilazzo 
Please see FAQ#2 from here: https://help.sap.com/viewer/42532dbd1ebb434a80506113970f96e9/Latest/en-US

Thanks

**Comment by iMilazzo** [comment]
> 
> 
> Hi @iMilazzo
> Please see FAQ#2 from here: https://help.sap.com/viewer/42532dbd1ebb434a80506113970f96e9/Latest/en-US
> 
> Thanks

It worked, thank you theStiggySpd !!!
