### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by rvodela** [SAPDocuments/Tutorials#5508]
When I tried this I and tested with postman I had to do a get with X-CSRF-Token = fetch and then populate this
for POST.
Ramesh

**Comment by Vikramkulkarni01** [comment]
Hi Ramesh, 

Could you please confirm, if you are pointing out an issue or something that you are facing to execute the tutorial?
anything which is blocking for you?

**Comment by rvodela** [comment]
Vikram
The first issue that I mentioned relating to auth issue when we click on open connectors is related to the blog.
In the PDF I have also included related issues that are bound to come up.  
I have written a blog 
https://blogs.sap.com/2020/07/16/integration-suite-process-integration-sap-odata-with-splitter-gather
I plan to write blogs on all aspects and hoped that I will be able to resolve issues that I face with the help
of SAP. I understand that this is not part of the tutorial.  If you can, however, pass to the right people and
see what they say as it will help others as well who want to learn.
Best regards
Ramesh

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by rvodela** [comment]
Michael
Thanks for this. I just tried the open connector issue - Once I open the application I got the same error.
Error Attached.  
Ramesh
![Capture](https://user-images.githubusercontent.com/6215920/89192977-28698b80-d55a-11ea-93ce-dbad8cbac16c.PNG)

**Comment by Vikramkulkarni01** [comment]
Hi @rvodela , 
Thanks for your response. 

The error message clearly tell that the " No Authorized user found"

Kindly check your role collections and assign the right one. 

Please feel free to share if there are any further concerns. 

Regards, 
Vikram Kulkarni

**Comment by rvodela** [comment]
Thanks for the response.  I have assigned all the roles and followed all the instructions mentioned in the tutorial.
I dont think that this is due the roles.  However I have given my id and subaccount id.  If possible can you look at
or let me know if open connectors is working for you - if so send me the all the authorizations you have given and let me check it out.
Best regards
Ramesh
