### ISSUE TITLE
Installing SAP HANA HDB Client (Mac)

### ISSUE THREAD

**Issue by sandeepdixit05** [SAPDocuments/Tutorials#5511]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-hdb-client-mac.html

Please specify the step you are referring to
Step 2: Install the SAP HANA HDB client**
Navigate to the HDB_CLIENT_MACOS directory and run hdbinst to start the installer:
```
cd HDB_CLIENT_MACOS
sudo ./hdbinst
```

While executing the above command I get following error:
```
“hdbinst” cannot be opened because it is from an unidentified developer.
macOS cannot verify that this app is free from malware.
```

**Comment by JCurrie27** [comment]
@sandeepdixit05  - Apologies for the delay here. Many thanks if you could log this macOS issue on the HANA Express community Q&A page to take advantage of the community support model. The Q&A page receives much more traffic, and community members may be able to provide answers immediately. To log your questions on the Q&A page:

1. Go to [https://answers.sap.com/questions/ask.html](https://answers.sap.com/questions/ask.html)
2. Add a **Title**. Enter your GitHub question in the **Fill in the details...** form.
3. In **Select Primary Tag**, search for "express". Select **SAP HANA, express edition**.
4. Click **Submit your Question**.
