### ISSUE TITLE
Connect to the SAP HANA Cockpit

### ISSUE THREAD

**Issue by Suncatcher** [SAPDocuments/Tutorials#5515]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-connect-hana-cockpit.html

The steps and screenshots seems to be outdated.
Now the default user is DBADMIN, not SYSTEM and the screenshot of instance state looks not like on the screenshots

![image](https://user-images.githubusercontent.com/6388034/87667562-3d30db80-c773-11ea-938b-b20bbaee83aa.png)

**Comment by jung-thomas** [comment]
This tutorial covers SAP Cloud Platform, SAP HANA Service in Cloud Foundry.  What you are referring to is actually a completely separate service called SAP HANA Cloud.  Both products are still offered by SAP. Its not so much that this tutorial is out of date as much as it is simply designed for a completely different product (but both based upon HANA). We will be adding some more tutorials soon for the new SAP HANA Cloud and perhaps we will update some of these to switch them over from the SAP Cloud Platform, SAP HANA Service in Cloud Foundry to the SAP HANA Cloud. In fact if you are looking for a tutorial on the new HANA Cloud, might I suggest this tutorial: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html
