### ISSUE TITLE
Configure the Development Environment

### ISSUE THREAD

**Issue by Suncatcher** [SAPDocuments/Tutorials#5516]
Tutorial URL: https://developers.sap.com/tutorials/haas-dm-configure-dev-env.html

The tutorial seems to be outdated. Not the builder installation for CF in WebIDE is not required.

![image](https://user-images.githubusercontent.com/6388034/87667735-8d0fa280-c773-11ea-9a84-ceaab84a16a7.png)

**Comment by jung-thomas** [comment]
Thank you. We will take it under advisement and update the screenshot when next this tutorial is revised.
