### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by mchcn2018** [SAPDocuments/Tutorials#5517]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

Set Up and Generate a New SAP Fiori App Project
Step 2: Select application template
SAP Fiori tools - Application Generator tile does not appear in Yeoman Generators - Select Generator at all, even though SAP Fiori tools - Extension Pack is installed and Visual Code Studio is restarted twice.

Please advice

**Comment by theStiggySpd** [comment]
Hi @mchcn2018  
Please see FAQ#2 from here: https://help.sap.com/viewer/42532dbd1ebb434a80506113970f96e9/Latest/en-US

Thanks

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
