### ISSUE TITLE
Create Instance of SAP Cloud Platform Enterprise Messaging Service

### ISSUE THREAD

**Issue by ursadithya** [SAPDocuments/Tutorials#5518]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html

Please specify the step you are referring to

Having issue in Step 1 for creating an instance. I am using trial account for trying this tutorial and here is the message that I am receiving. 
![image](https://user-images.githubusercontent.com/68391971/87697896-59734f00-c758-11ea-8f43-2811db08473b.png)

Here is the simple json I am using according to the template provide

{
    "emname": "myScenario",
    "namespace": "akorg/myScenario/1",
    "version": "1.1.0",
    "options": {
        "management": true,
        "messagingrest": true,
        "messaging": true
    },
	"rules": {
        "queueRules": {
            "publishFilter": [
                "${namespace}/*"
            ],
            "subscribeFilter": [
                "${namespace}/*"
            ]
        },
        "topicRules": {
            "publishFilter": [
                "${namespace}/*"
            ],
            "subscribeFilter": [
                "${namespace}/*"
            ]
        }
    }
}

**Comment by ursadithya** [comment]
Just an FYI, when I have created the trial account, it created the plan name as "dev" as shown below and also have required entitlements. 

![image](https://user-images.githubusercontent.com/68391971/87698213-ca1a6b80-c758-11ea-8e28-060178ca6b06.png)

**Comment by pradeeppanda-sap** [comment]
As mentioned in the tutorial
Select "default" type service plan from the dropdown and click Next.
it has to be "default" plan. Other plans are obsolete now. 
Please note that, "default" plan is available only in CANARY and Factory landscape. It is not available on Trial landscape.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
