### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by conanlei** [SAPDocuments/Tutorials#5520]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

Please specify the step you are referring to
In Step 2, there is nothing for me to select and there is no response when I click on Next button.

![can't select template](https://user-images.githubusercontent.com/20474300/87745699-3b255600-c821-11ea-9521-7b239076c562.png)

**Comment by vandanadeep** [comment]
Can you please make sure you have the the Application Generator installed from [here](https://www.npmjs.com/package/@sap/generator-fiori-elements).

**Comment by theStiggySpd** [comment]
Hi @conanlei 
Please see FAQ#2 from here: https://help.sap.com/viewer/42532dbd1ebb434a80506113970f96e9/Latest/en-US

Thanks

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
