### ISSUE TITLE
Prepare to Create Workflows in SAP Cloud Platform (Neo), can't login on sap web ide

### ISSUE THREAD

**Issue by zhang-yafei** [SAPDocuments/Tutorials#5521]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-getting-started.html

Please specify the step you are referring to
Step 6: Set up the workflow editor

When i click 
![image](https://user-images.githubusercontent.com/19721688/87762406-ad0f9680-c845-11ea-9820-2b1918e100c4.png)

The page is always in the loading state.Such as
![image](https://user-images.githubusercontent.com/19721688/87762530-de886200-c845-11ea-85b7-f954544b3c03.png)

**Comment by AstridHerbst** [comment]
Hi,
We are currently working on replacing this tutorial. There will be a new tutorial for the Cloud Foundry Environment that will be adapted to use the SAP Business Application Studio.
Best regards,
Astrid

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
