### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by fredVertexDev** [SAPDocuments/Tutorials#5523]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Please specify the step you are referring to:

Step 8:

Select the Authorization tab and choose Basic Auth in the Type dropdown list. In the Username and Password field, enter the clientid and clientsecret that you copied from the service key that you created when you provisioned the SAP Cloud Platform Integration tenant.

Question: I followed through the tutorial using my trial account, and I don't remember seeing a step for saving the clientid and clientsecret. Is there a way for me to retrieve those values?

**Comment by Vikramkulkarni01** [comment]
Hello @fredVertexDev, 

Thanks for reaching out to my tutorial. 

It's your emailID and password when you first login to the cloud platform integration tenant. 

You can try with that and it will solve the purpose of your concern. 

Please feel free to reach out to us, if you need any further help.

Regards, 
Vikram Kulkarni

**Comment by fredVertexDev** [comment]
Hi Vikram. Thank you for your response.

I entered my "S" Id and the appropriate password in Postman (Basic Auth), and I get a 403 error as the response.

Regards,
Fred

**Comment by Vikramkulkarni01** [comment]
Hi Fred, 

I Understand your concern. 

In this case, could you please create a new service instance key and then try. It should work. 

I will update the tutorial with that information. 

Meanwhile, please check on the below document and follow the same procedure to generate clientid and clientsecret. 

https://help.sap.com/viewer/DRAFT/14657160b5554d11a5386e22a935ca88/Cloud/en-US/94c3eadaf97f4a1f80d36c260d11537b.html?q=create%20service%20instance%20and%20key

Regards, 
Vikram Kulkarni

**Comment by fredVertexDev** [comment]
Hi Vikram. 

Thank you for making the update. I tried to follow the draft link in the previous comment but got a 403 error.

Regards,
Fred

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
