### ISSUE TITLE
Add Rich Enterprise Controls to the User Interface

### ISSUE THREAD

**Issue by mlvai** [SAPDocuments/Tutorials#5524]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-fiori-cf-fiorify.html

Please specify the step you are referring to
8.3 
change
sap.ui.define([
  //"sap/ui/core/mvc/Controller"                        >>DEL
  "tutorial/products/controller/BaseController" <<<INS

**Comment by IObert** [comment]
Hi @mlvai,

thanks for your feedback. Can you please specify where you found the string "sap/ui/core/mvc/Controller" in this tutorial? I cannot find it.

**Comment by mlvai** [comment]
Hi ,  
 ..  i try
Tutorial 8 step 8.3 
when  I change  controller.js  ,  add   ... this.addHistoryEntry({ ...

i have an error  in the webconsole  -> unknow  "addHistoryEntry"  ( possible scope  missing)
in my  case default controller.js look like this:

sap.ui.define([
  "sap/ui/core/mvc/Controller"
 ], function(Controller) {

to solve  the  error   apply de change 

sap.ui.define([
  //"sap/ui/core/mvc/Controller"
  "tutorial/products/controller/BaseController"
], function(Controller) {

validate if the error only applies to me.
discard the proposed fix.

thank for your time

**Comment by IObert** [comment]
It is correct that the BaseController should be referenced. What confuses me is that this should be default case anyway (as you can see in [step 6.4 of the previous tutorial](https://developers.sap.com/tutorials/sapui5-fiori-cf-display-data.html#e18ff2f0-2930-4d12-98a1-038c6cd4f7be)).

Is it possible that you used an old version of the easy-ui5 generator? This could explain why the base controller is not used.

**Comment by IObert** [comment]
fixed [SAP/generator-easy-ui5/commit/0d60372a66585c61179149a5fa7e0765c3b13653](https://github.com/SAP/generator-easy-ui5/commit/0d60372a66585c61179149a5fa7e0765c3b13653)
