### ISSUE TITLE
Enhance an ABAP Core Data Services (CDS) View in SAP Cloud Platform, ABAP Environment

### ISSUE THREAD

**Issue by yutangc** [SAPDocuments/Tutorials#5525]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-enhance-cds-view.html

Please specify the step you are referring to Step 1: Add value help
'/DMO/I_Agency_U' is undefined.

**Comment by julieplummer20** [comment]
Hi, Which system are you working in: Trial, Licensed, on-Premise, "Steampunk" (SAP Cloud Platform, ABAP Environment)?

**Comment by yutangc** [comment]
Trial, Licensed 
SAP Cloud Platform

**Comment by julieplummer20** [comment]
Hi,
It can't be trial AND licensed. If it's trial, it's free for 90 days; if you paid for it, it's licensed.
However, if it's SAP Cloud Platform, ABAP Environment (aka "Steampunk"), then it sounds as if you have not pulled the correct repository. See here for details :[ Downloading the ABAP Flight Reference Scenario](https://help.sap.com/viewer/923180ddb98240829d935862025004d6/Cloud/en-US/def316685ad14033b051fc4b88db07c8.html)

NOTE: This tutorial is part of a group. If you haven't done the prerequisite tutorial, as clearly stated, including the **prerequisites** to that fisrt tutorial, then it may not work.

BR Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
