### ISSUE TITLE
Create a Destination within the Cloud Foundry Environment

### ISSUE THREAD

**Issue by mlvai** [SAPDocuments/Tutorials#5526]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-create-destination.html

Please specify the step you are referring to
T5S4 : "HTML5.DynamicDestination " parameter  dont`s display on listbox.  but that important  manual  add.

**Comment by IObert** [comment]
Hi,

you are right, this parameter is not part of the list and you need to enter it manually. I'm not sure if I understand what the issue is. 
Do you think the tutorial should highlight this?

**Comment by mlvai** [comment]
hi ,   yes the last !  , I think  that important   add to tutorial. (should be helpful). I hope so.

**Comment by IObert** [comment]
I agree, I just made the change and it should be live within the next 10-20 minutes.
Thanks for your feedback!
