### ISSUE TITLE
Deploy a Rule Service

### ISSUE THREAD

**Issue by kbprasad79** [SAPDocuments/Tutorials#5527]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules08-deploy-ruleservice.html

Please specify the step you are referring to

Step 3

Cannot deploy with below "Error". Is Value Help required to be maintained for all data objects that are used in decision table?

And how to find out what below object IDs are?

The reference object with ID d0a0d6953ef34144b7717725c94ab9f5 not found in the rule service or ruleset vocabulary.
The reference object with ID d0a0d6953ef34144b7717725c94ab9f5 not found in the rule service or ruleset vocabulary.
The reference object with ID d0a0d6953ef34144b7717725c94ab9f5 not found in the rule service or ruleset vocabulary.
The reference object with ID d0a0d6953ef34144b7717725c94ab9f5 not found in the rule service or ruleset vocabulary.
The reference object with ID d0a0d6953ef34144b7717725c94ab9f5 not found in the rule service or ruleset vocabulary.
The reference object with ID d0a0d6953ef34144b7717725c94ab9f5 not found in the rule service or ruleset vocabulary.
The reference object with ID 4ca4a6500b864e2ebed98e302af15995 not found in the rule service or ruleset vocabulary.
The reference object with ID ed3bfcc1541d42659d52b04ce5f36583 not found in the rule service or ruleset vocabulary.
The reference object with ID 6e03766e4d2a44ffbf3e9131b0089427 not found in the rule service or ruleset vocabulary.
The reference object with ID 08080fec80ad46b58af63cb08f8bd6da not found in the rule service or ruleset vocabulary.
The reference object with ID 9081ab0c53f74323bf22e8382e3bfd31 not found in the rule service or ruleset vocabulary.

**Comment by VandanaVasudevan** [comment]
Hi,

Value help is not required for all the data objects. You can always enter your custom values.
To view the data object ID, do the following:
1. In the Manage Rule Projects application, go to the Data Objects tab, and choose the Settings icon.
2. Select ID from the list of column properties.
You will be able to view the data object IDs. In this case, can you please check if you've configured the data objects, rules, rulesets, and rule services correctly?
Also, please ensure that you have deployed the rule service, before trying out the invoke API.

Hope this helps.

Best Regards,
Vandana

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
