### ISSUE TITLE
Test the Business Rules API from SAP API Business Hub

### ISSUE THREAD

**Issue by kbprasad79** [SAPDocuments/Tutorials#5528]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules09-test-apis.html

Please specify the step you are referring to
Step 3

Rule Services are deployed and Required roles (RuleRuntimeSuperUser and RuleRepositorySuperUser ) are assigned
Rule service test via API executed with below errors.

  "error": "unauthorized",
  "error_description": "Full authentication is required to access this resource"

Object not found. The entity you are trying to invoke does not exist.

**Comment by VandanaVasudevan** [comment]
Hi,

This error occurs when the API environment is incorrectly configured. For more information, see Authentication Error in our [Troubleshooting Guide](https://help.sap.com/viewer/0e4dd38c4e204f47b1ffd09e5684537b/Cloud/en-US/0f1439096f1040b4944a8ee936b9bb1d.html).

Also, can you please check if you've accidentally deleted any of the data objects? or if all the data objects are in the active state?

Best Regards,
Vandana

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
