### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by nvnarendran** [SAPDocuments/Tutorials#5529]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

Please specify the step you are referring to: Step 2: Select application template

Problem: When I exactly follow the steps, the generator is not having any templates, kindly provide additional steps or documentation to further continue.  

![image](https://user-images.githubusercontent.com/4816877/87897295-84b3b200-ca68-11ea-8a17-33ef0963c108.png)

P.S. I also tried npm install -g @sap/generator-fiori-elements but seems like this is also not working for some reason the npm install keeps failing with below error

npm ERR! code E404
npm ERR! 404 Not Found: @sap/generator-fiori-elements@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\i331181\AppData\Roaming\npm-cache\_logs\2020-07-20T03_15_44_844Z-debug.log

**Comment by nvnarendran** [comment]
I updated node to the latest version & now I get a different error when I try to `npm install -g @sap/generator-fiori-elements`

![image](https://user-images.githubusercontent.com/4816877/87898131-f68cfb00-ca6a-11ea-8705-88db796cfa93.png)

**Comment by theStiggySpd** [comment]
Hi @nvnarendran 
Can you please follow the steps mentioned in FAQ#2 from here:
https://help.sap.com/viewer/42532dbd1ebb434a80506113970f96e9/Latest/en-US

-Sushant(SAP)

**Comment by nvnarendran** [comment]
Many thanks @theStiggySpd , the solution mentioned in the URL works, hence closing this issue
