### ISSUE TITLE
Enable SAP Cloud Platform Open Connectors

### ISSUE THREAD

**Issue by PhoebePoonSAP** [SAPDocuments/Tutorials#5530]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-openconnectors-enable.html

Please specify the step you are referring to: Step 3

Step 3 does not seem to work. When clicking on "Go to Application", it tries to log me in using the SAP Identity Service, but there was no setup of Roles for the Open Connectors service, so it comes back with an error that the user is not authorized.

**Comment by shilpavij** [comment]
Lets move to CF and try following the below tutorial and enable OCN as part of the complete new Integration Suite.
We are also in the process of replacing this tutorial with 
https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
Kindly use this one.

Regards
Shilpa

**Comment by PhoebePoonSAP** [comment]
@shilpavij I'm trying to activate Open Connectors in the integration suite but it seems to fail. Should I unsubscribe and try again? 

This is in EU10

![image](https://user-images.githubusercontent.com/68536540/88035808-422bcb80-cb75-11ea-8442-640a9c460eb1.png)

**Comment by shilpavij** [comment]
Dear Colleague,

Please try once again otherwise kindly send a mail to cpitrialfeedback@sap.com

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
