### ISSUE TITLE
ClientID & ClientSecret not created in 1st Tutorial of mission - Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by ASRHARDING** [SAPDocuments/Tutorials#5534]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Step 8, point 2.
In the Username and Password field, enter the clientid and clientsecret that you copied from the service key that you created when you provisioned the SAP Cloud Platform Integration tenant.

The "SAP Cloud Platform Integration tenant" tutorial has been replaced by "Set Up Integration Suite Trial" (https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html) which does not include a step to generate the clientid and clientsecret required in the Postman transaction.

**Comment by ASRHARDING** [comment]
Hi,
Having added the step to create the ClientID & ClientSecret given in the old "SAP Cloud Platform Integration tenant" tutorial the final Step 8 works correctly. Please update "SAP Cloud Platform Integration tenant" tutorial to include this step.
Kind regards, Andrew

**Comment by Vikramkulkarni01** [comment]
Hi Andrew, 

Thanks for your advice. 

We have considered this feedback and incorporated in the tutorial. 

You can see the changes shortly. 

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
