### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by mikhaelrms** [SAPDocuments/Tutorials#5535]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

Please specify the step you are referring to

At the step 4. Click Activate to provision the selected capabilities.

I recieve the error "UPDATE_FAILED"

![image](https://user-images.githubusercontent.com/68564799/87979068-7af97100-ca9f-11ea-8f55-cfb1c70ddc5a.png)

there is something that i can do to solve that issue?

regards.

**Comment by mikhaelrms** [comment]
If i try to "subscribe" again it give this error

![image](https://user-images.githubusercontent.com/68564799/87979305-dc214480-ca9f-11ea-8166-f6e2e83f8b8f.png)

**Comment by Vikramkulkarni01** [comment]
Hi @mikhaelrms , 

Thanks for reaching out to me. 

I am Vikram, an author of this tutorial. 

Could you please unsubscribe and re-subscribe it. 

Tip: If you have already subscribed **Process Integration**  please unsubscribe this as well. 

Try this and let me know how it works for you?

Regards, 
Vikram Kulkarni

**Comment by mikhaelrms** [comment]
Hello,

I was able to fix it deleting the trial account and following the guide again. Thanks.

[cid:image001.jpg@01D65F54.A2AF5720]
Regards.

Michael Rodriguez
Consultant, Procurement Technology Services (PTS), Intelligent Delivery Group (IDG)
Rosario Norte 100 - piso 13 - Las Condes , Santiago - Chile
M +56 9 52492802, E michael.rodriguez02@sap.com

[cid:image002.jpg@01D65F54.A2AF5720]

**Comment by mikhaelrms** [comment]
I was able to fix it deleting the trial account and following the guide again. Thanks.

![image](https://user-images.githubusercontent.com/68564799/88076418-0c242280-cb48-11ea-8650-e73d4e42a099.png)
