### ISSUE TITLE
Create an ABAP Core Data Services (CDS) View in SAP NetWeaver 7.5

### ISSUE THREAD

**Issue by sreechakka** [SAPDocuments/Tutorials#5536]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-create-cds-view.html

Please specify the step you are referring to

I followed your steps and completed . when I used Query browser App this particular CDS view is not visible similar to other views which has annotation with @OData.publish: true . With binding , I think we are mimicking the same right?

Your answer this will be helpful.
thanks  in advance
Sree

**Comment by julieplummer20** [comment]
Hi Sree,
Yes, service definition and service binding combined is the exact same thing: Create an OData service, specifying elements to be exposed (Definition) + protocol (eg OData v2) + use case (A2A API or UI).
The previous mechanism (annotation) created a large number of artifiacts under the hood, so we want to avoid that.
Best wishes,
Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
