### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by Snorn** [SAPDocuments/Tutorials#5537]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

Step 3.  SET CDS_ENV does not work if using Powershell (either native or from within vs-code terminal).

Solution: use cmd

**Comment by iwonahahn** [comment]
Hi,

for power shell please use:
`$env:CDS_ENV = "production" ; cds build`
`cf push -f gen\db`
`cf push -f gen\srv --random-route`

Unfortunately, the tool provides only tabs for Windows and MacOS. But you can also refer to the section in the [troubelshooting guide](https://cap.cloud.sap/docs/advanced/deploy-to-cloud#deploy-using-cf-push).

Hope that helps. Best regards,
Iwona
