### ISSUE TITLE
Set Up Workflow Management in Cloud Cockpit

### ISSUE THREAD

**Issue by fera-coder** [SAPDocuments/Tutorials#5541]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html

Please specify the step you are referring to

Step 3: Configure destination
The sample business rule used in this scenario is published in API Business Hub. BUSINESSRULES_APIHUB destination is used in SAP Cloud Platform Business Rules application to import business rules from API Business Hub.

From your global account page, choose the trial tile to access your subaccount.

If you run the booster in different subaccount then navigate into the respective account.

what does i have to do exactly? i am new to sap..
secondly i have another issue

Click Connectivity | Destinations from the left-hand navigation and search for the destination with name BUSINESSRULES_APIHUB

how can i do it? 
please help
<img width="1409" alt="createdestination-apihub" src="https://user-images.githubusercontent.com/68582608/88033588-fb2fdd00-cb58-11ea-9b6e-86c4784b458b.png">
![entertrialaccount](https://user-images.githubusercontent.com/68582608/88033620-0551db80-cb59-11ea-8fcc-e3144faf6298.png)

**Comment by ArchanaShukla** [comment]
Hello, 
Answer to your Question 1 : When you start the trial for the first time, a sub-account with name trial and space with name dev is already created for you. Many times user create a separate sub-account of their own, and so I have mentioned that as a note - in case users are not working on the default sub-account but have created account of their own name. 

Answer to your Question 2 : You have to search the destination with name BUSINESSRULES_APIHUB in the destinations page.  The screenshot highlighting shows it. There is a filter search bar on top-right of the page. You need to type in APIHUB in there and then you will see the destination. After the search you have to have to select the destination, scroll down and click on Edit button to change the password of the destination.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
