### ISSUE TITLE
Set Up Workflow Management in Cloud Cockpit

### ISSUE THREAD

**Issue by fera-coder** [SAPDocuments/Tutorials#5542]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html

Please specify the step you are referring to

when i click new subaccount it says
 Display name:
description:
Domain name:
enable beta features..

please help what do i do? to proceed further

**Comment by ArchanaShukla** [comment]
You do not have to create a new account, when you launch the trial a sub-account will automatically be created for you.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
