### ISSUE TITLE
Add Multiple Receivers and Convert Message Format

### ISSUE THREAD

**Issue by jonkerpeter** [SAPDocuments/Tutorials#5544]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-add-multiple-receiver-formats.html

Converter step xml to csv are two DIFFERENT processings mentioned.  Whic one of the two is correct:
Path to Source Element in XSD //orders
OR
Path to Source Element in XSD /orders/order

**Comment by gauthamkrishna-sap** [comment]
Hi @jonkerpeter 

//orders should be the right option. We will fix the screenshot; it is confusing.

Thank you for the feedback.

Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
