### ISSUE TITLE
Map Message Structure

### ISSUE THREAD

**Issue by jonkerpeter** [SAPDocuments/Tutorials#5545]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-convert-message-structure.html
Messagemapping add source and target : in the exercise it is said to save the sample messages (source and target) as xml on your computer.
Later when adding the message mapping it is said to use these files for source and target. However xml files CAN NOT BE USED as source or target message.  An xsd or wsdl only can be used. Change the tutorial on this point please, because this is completely wrong.  
Even when you generate the xml to xsd with online tools, the image of the source structure is not correct. How come there are so many mistakes in these tutorials ??????

**Comment by ASRHARDING** [comment]
Hi jonkerpeter 
I am way behind you on this tutorial and appreciate your comments.

I have been able to replicate the source xml structure by making the following changes:

1. Find Closest Warehouse Code
   In Content Modifier 2 (the last action in the flow before End) I have changed the Message Body tab 
From: 
<?xml version="1.0" encoding="utf-8"?> <order><code>${in.body}</code><orderID>${headers.OrderID}</orderID></order>
To:
<ordercode><order><orderID>${headers.OrderID}</orderID><code>${in.body}</code></order></ordercode>

2. Manage Freight Logistics
   In the Content Enricher 1, Processing tab to the following configuration
Aggregation Algorithm: Enrich
ORIGINAL MESSAGE
   Path to Node: /orders/order/
   Key Element:  orderID
LOOKUP MESSAGE
   Path to Node: /ordercode/order/
   Key Element:  orderID

That just leaves the extra <code>KWA2PRBK5I</code> after the <address>...</address>. Don't see any point in trying to work out how that as inserted there so will remove from my source.xml giving me a result that matches with my output from Content Enricher step in the Manage Freight Logistics iFlow.

Did you do something like this to sort out your problems with this tutorial?

I will have a go at finding an XML to XSD converter tomorrow.

Cheers, Andrew

**Comment by jonkerpeter** [comment]
Hi Andrew,

 

Unfortunately I will soon not be able to help you any further.  My Hana trial account has expired and I cannot extend it anymore ( did that already twice.  My data will be deleted. Today is my last day so anytime it will stop working

 

The last content modifier has the following message body:

<?xml version="1.0" encoding="utf-8"?> 

<order>

<code>${in.body}</code>

<orderID>${headers.OrderID}</orderID>

</order>

 

The content enricher settings are the same in my iflow.

 

I noticed that the source message in the tutorial doesn’t always have the same structure as the one that is produced.  I use the source as is produced in the flow to work with.  

 

Good luck with the rest of the tutorial.

 

 

Trial Period 0 days left

Your free trial is about to expire.

You have already extended your free trial to the maximum usage period, after which your free trial will be deleted along with your data and applications.

If you want to continue using the SAP Cloud Platform, you can purchase an enterprise account.

 

Peter Jonker

**Comment by ASRHARDING** [comment]
Hi Peter

Even after extending twice and down to 0 days left I have been able to extend my account again and continue doing so for several years. Give it a try, it should allow you to extend again unless something has radically changed.

Andrew

**Comment by gauthamkrishna-sap** [comment]
Dear All,

Thanks for your feedback. 

1. XSDs have been updated
2. The trial can be extended every 30 days for a maximum of 90 days. 

Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
