### ISSUE TITLE
Handling Bulk Messages

### ISSUE THREAD

**Issue by jonkerpeter** [SAPDocuments/Tutorials#5547]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-handle-bulk-messages.html

After adding the message mapping, the condition in the router needs to be adapted as well. This is missing in the tutorial and therefore you will NOT receive an email anymore if you don't adjust the condition.

**Comment by gauthamkrishna-sap** [comment]
Hello,
Thank you for the specific feedback. We will update the tutorial.
Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
