### ISSUE TITLE
Portal Tutorial - Incorrect Image used.

### ISSUE THREAD

**Issue by sandeep-tds** [SAPDocuments/Tutorials#5551]
In [Step 3 of this tutorial](https://developers.sap.com/tutorials/cp-portal-cloud-foundry-create-sitelaunchpad.html#eec3f165-5132-4540-ab1e-7efc059e62bf), the image is incorrect.

The step asks you to launch the site, but the icon highlighted is the edit button.

![image](https://user-images.githubusercontent.com/43441840/88173125-b03cc500-cc3f-11ea-9b61-c9235034a87d.png)

For ease, I am attaching a plain image in which the correct icon can be highlighted.

![image](https://user-images.githubusercontent.com/43441840/88173326-00b42280-cc40-11ea-9f6d-59d4001bdb0b.png)

**Comment by LindsayBert** [comment]
Thanks - it's updated.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
