### ISSUE TITLE
Add a New Entitlement to Your Subaccount

### ISSUE THREAD

**Issue by dangmru** [SAPDocuments/Tutorials#5553]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-entitlements-add.html

Please specify the step you are referring to: Does the question "Which of the following entitlements are available for selection in the SAP Cloud Platform Trial?" have an answer? I asked because when I selected "Workflow" - it says it's incorrect. 

What am I missing here? Thanks for your help!

**Comment by IObert** [comment]
Thanks for providing the feedback. I assume you are using region US10, in which case you are right. In this region, the service Screening, which would be the correct second answer, is not available. 
I updated the choices and replaced Screening with the Alert Notification service which is available in EU10 and US10

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
