### ISSUE TITLE
Create an API Proxy

### ISSUE THREAD

**Issue by elainetu** [SAPDocuments/Tutorials#5554]
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-create-api.html

Please specify the step you are referring to
step  6
Discover the services
Nothing comes up
Only Error: Incorrect configuration of API Provider
I checked the API Provider setting, when I click the "test connection", it shows: Connection to the system was unsuccessful with HTTP response code: 503; Message : Service Unavailable
I'm thinking of the service is not available on gateway system ES5.

**Comment by shilpavij** [comment]
Dear Colleague,

The service is not available on the gateway. Kindly the complete URL first in the browser. If this works, API Provider will work for sure.

Regards
shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
