### ISSUE TITLE
Setup PuTTY and WinSCP to access your HANA Express Edition on Google Cloud Platform

### ISSUE THREAD

**Issue by gitbenedict** [SAPDocuments/Tutorials#5555]
Tutorial URL: https://developers.sap.com/tutorials/hxe-gcp-setup-putty-winscp-windows.html

Please specify the step you are referring to
1. The 'Complete' button is not available. I am unable to mark my progress
<img width="687" alt="noCompleteButton" src="https://user-images.githubusercontent.com/14294991/88253718-8089cd80-ccd0-11ea-8710-0468e5011909.png">

2. The private key download is not available in the previous tutorial as mentioned
    https://developers.sap.com/tutorials/hxe-gcp-getting-started-launcher.html
3. Please add a step to identify the user name of the instance.

**Comment by jung-thomas** [comment]
Thank you for your feedback. However at this point there are no plans to further enhance this particular tutorial. If you wish to run a free version of HANA in the Cloud; we would strongly recommend the SAP HANA Cloud trial on SAP Cloud Platform.
