### ISSUE TITLE
Set Up SAP Business Application Studio for Development

### ISSUE THREAD

**Issue by dangmru** [SAPDocuments/Tutorials#5558]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-onboarding.html

Please specify the step you are referring to:  On the question - "Which of the following subscriptions are available for selection in the SAP Cloud Platform trial?" - the available choices does are not available in the AWS, US East (VA) .

**Comment by raz-korn** [comment]
Hi @dangmru ,

Yes - This question might be a bit tricky.
When creating trial account, most entitlements should be automatically assigned to the subaccount.
From this you might have guessed that if the subscriptions do not appear in the subscriptions tab, you should check what's available in the Entitlements tab.

I'll investigate this a bit more and check if/how the question should be modified.

Regards - Raz

**Comment by raz-korn** [comment]
Hi @dangmru ,

In the recent tutorial update, a new question replaced the one you mentioned.
I hope that this will remove any confusion.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
