### ISSUE TITLE
Feedback on Tutorial: End-to-End Weather App Scenario Part 4

### ISSUE THREAD

**Issue by ajkpub** [SAPDocuments/Tutorials#556]
using the pom.xml link in the tutorial I copy and paste the contents into my pom.xml and just saving the file and I get errors that prevent anything from building. Subsequent steps also throw errors. 

Links on the Maven site all seem to refer to Java Web Tomcat 8 web applications, but that isn't what the tutorial prerequisites seems to have specified.

Any help would be appreciated.

// errors listed when saving pom.xml with contents from tutorial's link to github pom.xml
---------------------------------------------------------------
Errors occurred during the build.
Errors running builder 'Maven Project Builder' on project 'weatherapp'.
Could not calculate build plan: Plugin org.apache.maven.plugins:maven-resources-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.5
Plugin org.apache.maven.plugins:maven-resources-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.5
Could not calculate build plan: Plugin org.apache.maven.plugins:maven-resources-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.5
Plugin org.apache.maven.plugins:maven-resources-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.5

// ---------------------------------------
// errors listed for <plugin> element after saving pom.xml with contents from github
//--------------------------------------------------- 
CoreException: Could not calculate build plan: Plugin org.apache.maven.plugins:maven-compiler-plugin:2.5.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-compiler-plugin:jar:2.5.1: ArtifactResolutionException: Failure to transfer org.apache.maven.plugins:maven-compiler-plugin:pom:2.5.1 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.apache.maven.plugins:maven-compiler-plugin:pom:2.5.1 from/to central (https://repo.maven.apache.org/maven2): connect timed out

**Comment by anmorf** [comment]
Hi there, I am experiencing the exact same problem with the pom files. Tutorial so far was very good and helpful, however with the Maven Project Generation there seems to be some stumble stones to get around. Can someone provide an answer to the question above?

**Comment by jonathanbaker7** [comment]
So, this problem is actually a communication problem with the Maven server.  

> Failure to transfer org.apache.maven.plugins:maven-compiler-plugin:pom:2.5.1 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. 

This error is trying to say "I couldn't talk to the Maven server, so I'm relying on the cached data".  

This is usually caused by a firewall or proxy server in your organization.  One possible way to fix this is to use the proxy settings for maven.  [You can find more information on that here](https://maven.apache.org/guides/mini/guide-proxies.html).  Note that the settings are **not** in Eclipse, but in the .m2 folder.

Another way to solve this problem is to move your computer to a public network.  (Any coffee shop will do.)

To force Eclipse to try again, and determine if the error is still occurring, follow these steps:

1.  Right click on the project folder
2.  Choose the Maven --> Update Project
3.  In the dialog, click the **Force Update of Snapshots/Releases** setting at the bottom of the screen.
4.  Click OK

If Maven is able to contact the server, the errors should go away.

**Comment by rvrkj** [comment]
Hi Jonathan,
I have done what you've told in your previous response to do.
To force Eclipse to try again, and determine if the error is still occurring, follow these steps:

1.Right click on the project folder
2.Choose the Maven --> Update Project
3.In the dialog, click the Force Update of Snapshots/Releases setting at the bottom of the screen.
4.Click OK
If Maven is able to contact the server, the errors should go away.

but I'm getting this error
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project weatherapp: Fatal error compiling: tools.jar not found: C:\Program Files\Java\jre7\..\lib\tools.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
