### ISSUE TITLE
Create an ABAP Table Type

### ISSUE THREAD

**Issue by yutangc** [SAPDocuments/Tutorials#5560]
Tutorial URL: https://developers.sap.com/tutorials/abap-env-create-table-type.html

Step 3: Define a primary key でPrimary Key type を設定する Key Components でdrop-down listの表示が、私の使っているPCの画面解像度(1366x768)の為に表示されません。

Step 3: Set Primary Key type with Define a primary key The drop-down list is not displayed in Key Components because of the screen resolution (1366x768) of my PC.

![範囲を選択_002](https://user-images.githubusercontent.com/55310943/88283903-51eb1180-cd27-11ea-908e-cff36a9eabf6.png)

**Comment by julieplummer20** [comment]
Hi Yutangc,
This trouble-shooting is somewhat beyond the scope of the tutorial. Have you tried a different resolution? If so, have you tried entering each entry by text: CLIENT, BANK_CUSTOMER_ID ?
If you are a customer, you can certainly open a ticket under BC-DWB-AIE-DIC.
Best wishes,
Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
