### ISSUE TITLE
Maintain a Communication Arrangement for Inbound Communication

### ISSUE THREAD

**Issue by YoungSeo-Yoo** [SAPDocuments/Tutorials#5561]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

Please specify the step you are referring to

Step3 : Create communication user.
I'm sticked in this step.
Because I can't find the the "maintain communication user" on the launchpad.
[Referring your document](https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html), I made my "ABAP trial user" in the SAP Cloud Platform .
How can I step over this issue? 

![001](https://user-images.githubusercontent.com/60785857/88289098-ae522f00-cd2f-11ea-8304-fd28656de40c.png)

**Comment by julieplummer20** [comment]
Hi YoungSeo-Yoo,
This tutorial can only be performed in the **licensed** version, not the trial version, as stated in the prerequisites.
Sorry.
Julie.

**Comment by YoungSeo-Yoo** [comment]
p{margin-top:0;margin-bottom:0}
    


    Hi Julie.Thank you for fast your reply.I'll look up others tutorials.


--------- 원본 메일 ---------

    
        보낸사람: Julie Plummer <notifications@github.com>
        받는사람: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
        
            참조: YoungSeo-Yoo <moonbye@hanmail.net>, Author <author@noreply.github.com>
        
        날짜: 20.07.27 16:29 GMT +0900
        제목: Re: [SAPDocuments/Tutorials] Maintain a Communication Arrangement for Inbound Communication (#5561)
        
        
    
    
        
Hi YoungSeo-Yoo,
This tutorial can only be performed in the licensed version, not the trial version, as stated in the prerequisites.
Sorry.
Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by YoungSeo-Yoo** [comment]
p{margin-top:0;margin-bottom:0}
    


    Thanks you for your reply.I've been already received the email from Julie Plummer .and I realizes that this tutorial needs the licensed version.thanks.
--------- 원본 메일 ---------

    
        보낸사람: Michael Czadankiewicz <notifications@github.com>
        받는사람: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
        
            참조: YoungSeo-Yoo <moonbye@hanmail.net>, Author <author@noreply.github.com>
        
        날짜: 20.07.27 20:13 GMT +0900
        제목: Re: [SAPDocuments/Tutorials] Maintain a Communication Arrangement for Inbound Communication (#5561)
        
        
    
    
        
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue.
If you still have questions, feel free to reopen the issue.
