### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by shubhchamp** [SAPDocuments/Tutorials#5562]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

Please specify the step you are referring to 2.

Sometime we don't see card to select. This is faced by multiple users. 
In windows this can be resolved by typing "npm i -g @sap/generator-fiori-elements " in terminal. 
This can be added  as troubleshoot.

**Comment by cjbernal** [comment]
Hi shubhchamp,

We're sorry you had this issue. I'm currently working with the tutorial developers to see how we can minimize the frequency of this issue. In the meantime, please see FAQ #2 on this page:  https://help.sap.com/viewer/42532dbd1ebb434a80506113970f96e9/Latest/en-US

Thanks and regards,
Conrad (SAP UX Engineering)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
