### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by michaelnicholls** [SAPDocuments/Tutorials#5563]
Tutorial URL: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html

Is it possible to have the generated HDI container use the SAP HANA Cloud tenant? I am trying to set up an .hdbgrants file in WebIDE so that I can  create a calc view which accceses the HANA cloud database tables through synonyms. I get an error that the #oo user doesn’t exist, which I think is related to the fact that the HDI container is in a different database to the database tables.

**Comment by jung-thomas** [comment]
If you are following this tutorial and using the HANA Cloud Trial, then the HDI container is created in the HANA Cloud instance.  Make sure that you are not accidentally using the older HANA As a Service trial (the HDI Container/Schema marked trial is the old one.  You want the one without the trial name to use the new HANA Cloud Trial).  But if you followed the steps in this tutorial it would all be using the trial.
