### ISSUE TITLE
Debug Your SAPUI5 App with SAP Business Application Studio

### ISSUE THREAD

**Issue by IvoVermeer** [SAPDocuments/Tutorials#5565]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-sapui5-debug.html

Please specify the step you are referring to: Step 3

Step 3 refers to `webapp/webapp/controller/View1.controller.xml`, but that should be `webapp/webapp/controller/View1.controller.js`

**Comment by IObert** [comment]
Good catch, I'll fix right now.
