### ISSUE TITLE
Create an SAPUI5 App from the Command Line

### ISSUE THREAD

**Issue by IvoVermeer** [SAPDocuments/Tutorials#5566]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-sapui5-local.html

Please specify the step you are referring to: Step 2: Inspect the generated code

In the tutorial, there is a `webapp` folder in the root:
![image](https://user-images.githubusercontent.com/5347891/88403336-b318f080-cdcc-11ea-9d29-dc29a0512afc.png)

But the generated code has it sitting in `uimodule`:
![image](https://user-images.githubusercontent.com/5347891/88403244-97ade580-cdcc-11ea-9285-6315d3f2ed3e.png)

It seems the generator was updated, but the tutorial not(yet)

**Comment by IObert** [comment]
Also a good catch. I'll update the screenshot here.
Thanks for reporting this one!
