### ISSUE TITLE
Create an Empty SAPUI5 Project "generator failed"

### ISSUE THREAD

**Issue by chilianubogdan** [SAPDocuments/Tutorials#5568]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-101-create-project.html

Please specify the step you are referring to
Step 3: Create a new project
error: undefined Abort ui5-simple creation
```
fiori-project generator failed. 
name: Error message: Failed to consume services due to: 
undefined Abort ui5-simple creation. 
stack: Error: Failed to consume services due to: 
undefined Abort ui5-simple creation. at 
Ui5SimpleGenerator._abortGenerator (/extbin/generators/ui5-generators/generator-ui5-simple/generators/app/index.js:196:24) 
at _setConsumeServicePrompt.catch 
(/extbin/generators/ui5-generators/generator-ui5-simple/generators/app/index.js:121:75) at process._tickCallback (internal/process/next_tick.js:68:7) 
string: Error: Failed to consume services due to: undefined Abort ui5-simple creation.
```

the generator fails to complete most probably on Northwind Odata connection
![Inked2020-07-24 18_10_40-Greenshot_LI](https://user-images.githubusercontent.com/8693073/88412919-997ea580-cdda-11ea-9d3e-fbe4f3ccb765.jpg)

The Northwind Odata connection responds with 200 from Cloud Platform > Destinations
<img width="947" alt="2020-07-24 18_17_16-🕹 Head Quarter 🎮 - OneNote" src="https://user-images.githubusercontent.com/8693073/88412529-08a7ca00-cdda-11ea-98fd-c2e7ea269404.png">

in this course https://developers.sap.com/tutorials/cp-cf-create-destination.html
we set:

Property Name | Value
-- | --
HTML5.DynamicDestination | true (enter this property manually as it is not available in the dropdown list)
WebIDEEnabled | true
WebIDESystem | Northwind
WebIDEUsage | odata_gen

nothing related to SAP Business Application Studio true... I just assume... 🤔🤨🙄😥😮🥱😴😌😛😊😁😀
I have no idea I am new to SAP and I understood Business Application Studio is a separate thing from Web IDE

**Comment by IObert** [comment]
Hi @chilianubogdan,

I'm sorry to hear that you are facing a problem here. I just tested it in my App Studio instance and it works there. Can you please share a screenshot of the full destination here to troubleshoot the problem?

**Comment by IObert** [comment]
I'll close it, for now. Please reopen if this issue still persists.

**Comment by konrazem** [comment]
I have the same problem

{"message":"fiori-project:app generator failed - env.on(error) Failed to consume services due to: undefined\nAbort ui5-simple creation.","stack":"Error: env.on(error) Failed to consume services due to: undefined\nAbort ui5-simple creation.\n at Ui5SimpleGenerator._abortGenerator (/extbin/generators/ui5-generators/generator-ui5-simple/generators/app/index.js:205:24)\n at /extbin/generators/ui5-generators/generator-ui5-simple/generators/app/index.js:126:26\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}

**Comment by jayekulk** [comment]
It can be solved by adding property HTML5.DynamicDestination in Northwind Destination

**Comment by jayekulk** [comment]
> I have the same problem
> 
> {"message":"fiori-project:app generator failed - env.on(error) Failed to consume services due to: undefined\nAbort ui5-simple creation.","stack":"Error: env.on(error) Failed to consume services due to: undefined\nAbort ui5-simple creation.\n at Ui5SimpleGenerator._abortGenerator (/extbin/generators/ui5-generators/generator-ui5-simple/generators/app/index.js:205:24)\n at /extbin/generators/ui5-generators/generator-ui5-simple/generators/app/index.js:126:26\n at runMicrotasks ()\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}

It can be solved by adding property HTML5.DynamicDestination in Northwind Destination

**Comment by konrazem** [comment]
Thank you, yes that solved my issue
