### ISSUE TITLE
Create an Empty SAPUI5 Project SAP Business Application Studio generator failure Northwind

### ISSUE THREAD

**Issue by chilianubogdan** [SAPDocuments/Tutorials#5569]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-101-create-project.html

Please specify the step you are referring to
Step 3: Create a new project >>> already provided feedback on a different course 
https://github.com/SAPDocuments/Tutorials/issues/5568

**Comment by IObert** [comment]
I'll close this one and followup on the other issue
