### ISSUE TITLE
Feedback on Tutorial: How to create an SAP HANA Developer Edition in the Cloud

### ISSUE THREAD

**Issue by Datronix** [SAPDocuments/Tutorials#557]
Hello there,
I connect to a SAP Hana instance via my AWS account - all good. But if I try to edit or create ABAP/Hana code, at some point I am prompted to enter a SAP Developer Key - a popup appears asking me to log into the SAP marketplace - but this requires an S-id.
Please advise me.

**Comment by ccmehil** [comment]
Are you using the SAP HANA Developer Edition or SAP HANA One? The SAP HANA Developer Edition has not standard connection to an ABAP system so if you are trying to connect to an ABAP system then you will find that you need the developer key.
