### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by choukyou** [SAPDocuments/Tutorials#5571]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

in step 1-8 [ For Consume Services, select the following, and click Next ]
1. i cannot set the parameter [Select a source] for a [ES5_BASIC_AUTH [Catalog]] 
 i can only select [ES5 [Catalog]]
2. i cannot set the parameter [Select a service] for [GWSAMPLE_BASIC]

how should i do, i hope your answer. thanks .

![image](https://user-images.githubusercontent.com/68760773/88444420-fb312500-ce57-11ea-970e-7b42ff35e2d8.png)

**Comment by raz-korn** [comment]
Hi @choukyou ,

please check out issue [5464](https://github.com/SAPDocuments/Tutorials/issues/5464).

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by choukyou** [comment]
Hi @raz-korn 

thanks for your advice,
i have checked out issue  [5464](https://github.com/SAPDocuments/Tutorials/issues/5464).
 i removed the dev space and create a new dev space,but i have the same problem yet .
can you give some help.

Regards
chou
 
> Hi @choukyou ,
> 
> please check out issue [5464](https://github.com/SAPDocuments/Tutorials/issues/5464).
> 
> Regards - Raz

**Comment by raz-korn** [comment]
Hi @choukyou ,

Are you able to access the [ES5 service](https://sapes5.sapdevcenter.com/sap/opu/odata/iwbep/GWSAMPLE_BASIC/$metadata) directly?

Regards - Raz

**Comment by choukyou** [comment]
Hi @raz-korn 

i tried to access the   ES5 service  and get this , is this OK?




![image](https://user-images.githubusercontent.com/68760773/88751911-9b0dec00-d193-11ea-8ddf-a82d20fe974a.png)

Regards
chou

**Comment by raz-korn** [comment]
Hi @choukyou ,

This is perfect. 
I assume that the destination is configured with Basic Authentication. Therefore, I suspect that the user and/or password in the destination are not correct.
One additional thing you can try is the Check Connection in the Destination (Cockpit). Should result in 307. You can find detailed instructions near the end of the following [tutorial](https://developers.sap.com/tutorials/cp-portal-cloud-foundry-gateway-connection.html).

Regards - Raz

**Comment by choukyou** [comment]
Hi @raz-korn 

thanks for your advice!
i checked the connection in the destination ,and i work well .the result is 307.
what should i do next?

![image](https://user-images.githubusercontent.com/68760773/88794735-dcc18580-d1d9-11ea-8a54-1c1299b2fcf5.png)

Regards
chou

**Comment by raz-korn** [comment]
Hi @choukyou ,

Verify that both the User and Password are OK. The ones you used when checking the direct link to the service, which should be the same as those you use to access [SAP Gateway Web GUI](https://sapes5.sapdevcenter.com/). If the destination credentials are OK you should be able to complete the tutorial.

Regards - Raz

**Comment by choukyou** [comment]
Hi @raz-korn 

thank you very much!
You are right, there is problem at SAP Gateway Web GUI , and i reset my password , Now  i can continued the tutorial.

Best Regards
chou
