### ISSUE TITLE
Create Instance of SAP Cloud Platform Enterprise Messaging Service

### ISSUE THREAD

**Issue by jcailan** [SAPDocuments/Tutorials#5574]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html

Please specify the step you are referring to:

There's a bug in Step 1. It will complete the step upon submitting the correct answer, but if I refresh the page to verify that the step 1 was completed, it wasn't completed. See screenshot below:

![image](https://user-images.githubusercontent.com/27951983/88471190-8c77c880-cf38-11ea-98d7-46d94d7c29f1.png)

**Comment by thecodester** [comment]
I am still working on this

**Comment by pfefferf** [comment]
Any update on this? Issue still appears.

**Comment by pradeeppanda-sap** [comment]
this seems to be some editor issue and that's why thecodester has assigned it to himself after our discussion.

**Comment by pfefferf** [comment]
Thanks for the info. Just wanted to comment, because the last activity is already 4 month in the past :)

**Comment by thecodester** [comment]
I have republished to try to fix issue. Can you try again? (Sorry for the delay.)

**Comment by pfefferf** [comment]
Same issue like before (result for 1st step is not persisted; browser cache etc. cleared before of course).

**Comment by thecodester** [comment]
I have created a JIRA ticket internal to deal with this issue ... again sorry for the issues.

**Comment by thecodester** [comment]
@pfefferf @jcailan I know it's been a long time ... can you try again?

**Comment by pfefferf** [comment]
@thecodester Looks/works good now. Thank for fixing it after that long time.
