### ISSUE TITLE
Set Up a Sample Design-to-Operate Business Process

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#5575]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-processvisibility-config-samplescenario.html

Please specify the step you are referring to:

Step 2 -> Import Events

I have used this for the onboard events as well and I receive this message when I try to import the DesigntoOperate.json file. 

![image](https://user-images.githubusercontent.com/38389079/88473748-d6c26f00-cf63-11ea-8879-685bfcaff217.png)

How can I correct this to proceed with the tutorial?

Thanks & Kind Regards
Phil Cooley

**Comment by Deeksha-R** [comment]
@pjcools You would need to delete the events of employee onboarding scenario first. There is a restriction of acquired events to not exceed 3000 in the trial account. Try the procedure after this and do let us know if the issue persists.

Thank you,
Deeksha

**Comment by pjcools** [comment]
Hi Deeksha

Yes, this worked successfully. This can be closed now. 

thankyou!
Phil

**Comment by pjcools** [comment]
Thanks, I completed the mission now. Thankyou for your assistance.
