### ISSUE TITLE
Develop SAP SAPUI5 Application for SAP Cloud Platform on Cloud Foundry

### ISSUE THREAD

**Issue by sprmar** [SAPDocuments/Tutorials#5582]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-fioriapps-create.html

Referring to step 7, I get this error: 

"Deployment of the "mta_FioriDemo" project failed."

Any Advice how to solve this?

**Comment by sprmar** [comment]
11:23:13 (DeploymentToCF) Deployment of the "mta_FioriDemo" project started.
11:23:14 (DeployService) Deployment in progress.
11:23:14 (DeployService) Deploying /mta_FioriDemo/mta_archives/mta_FioriDemo_0.0.1.mtar to endpoint: https://api.cf.eu10.hana.ondemand.com, organization: Test GmbH & Co. KG_em-messaging, space: dev.
11:25:14 (DeployService) Target: https://deploy-service.cfapps.eu10.hana.ondemand.com/slprot/Test%20GmbH%20&%20Co.%20KG_em-messaging/dev/slpPreparing to deploy /mta_FioriDemo/mta_archives/mta_FioriDemo_0.0.1.mtarPrepare deployment filesChecking if there are conflicting processesFound 9 conflicting processesAborting process 4f5892a4-cfe0-11ea-96de-eeee0a92c4fdAborting process 5a977944-cfe8-11ea-b73e-eeee0a803480Aborting process 5f1539d3-cfdd-11ea-b73e-eeee0a803480Aborting process 5fda425c-cfde-11ea-aa2e-eeee0a92285fAborting process 6d32504b-cfdc-11ea-96de-eeee0a92c4fdAborting process 83d4cf0c-cfdf-11ea-96de-eeee0a92c4fdAborting process 993127d3-cfe4-11ea-aa2e-eeee0a92285fAborting process baf6bb59-cfdf-11ea-aa2e-eeee0a92285fAborting process befe2eaa-cfe9-11ea-b73e-eeee0a803480Uploading mtar archiveStarting deploymentDeploying in org "TestGmbH & Co. KG_em-messaging" and space "dev"Detected MTA schema version: "3"Detected deployed MTA with namespace "null", ID "mta_FioriDemo" and version "0.0.1"Detected new MTA version: "0.0.1"Deployed MTA version: "0.0.1"Processing service "mta_FioriDemo_html5_repo_host"...Creating service "mta_FioriDemo_html5_repo_host" from MTA resource "mta_FioriDemo_html5_repo_host"...Processing service "dest_mta_FioriDemo"...Creating service "dest_mta_FioriDemo" from MTA resource "dest_mta_FioriDemo"...Service operation failed: Controller operation failed: 404 Updating service "dest_mta_FioriDemo" failed: Not Found: Error creating service "dest_mta_FioriDemo" from offering "destination" and plan "lite": Service plan lite not found. Processing service "uaa_mta_FioriDemo"...Processing service "mta_FioriDemo_html5_repo_runtime"...To download the process logs, use the "cf dmol -i 023085b9-cfeb-11ea-96de-eeee0a92c4fd" command in the Cloud Foundry CLI directly in your Cloud Foundry space.See https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/e93b231895b64cbc9221a62953563a6f.html.Job failed.
11:25:14 (DeploymentToCF) Deployment of the "mta_FioriDemo" project failed. (Response state is FAILED).

**Comment by Paolaufer** [comment]
Hi,

I will look into this and get back to you soon.

Regards,
Pao

**Comment by avizov** [comment]
Hi,
From the error, it looks that you have a lack of service configuration from type "destination" with plan "lite" in your cf space. 
404 Updating service "dest_mta_FioriDemo" failed: Not Found: Error creating service "dest_mta_FioriDemo" from offering "destination" and plan "lite"
Please configure it and try again. 
Thanks,
Alex

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
