### ISSUE TITLE
Add NativeScript Plugins in an MDK App

### ISSUE THREAD

**Issue by christian60** [SAPDocuments/Tutorials#5583]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-dev-kit-nativescript-geolocation.html

I'm trying this tutorial with an Samsung S9. I've done all the steps but the popup isn't displayed to allow access to the location. Therefore, I allowed it for the app directly in the general settings, but it doesn't have any effect. The screen is blank and I don't even see the toolbar, only the header is visible. Any ideas what the problem could be? I am using the latest MDK version 4.2.6
Many thanks in advance.

Best Regards
Christian

**Comment by jitendrakansal** [comment]
@christian60 do you not see "Logout" in toolbar? Could you share the screenshot ?

**Comment by christian60** [comment]
> 
> 
> @christian60 do you not see "Logout" in toolbar? Could you share the screenshot ?

Correct, I don't see anything.
![screenshot](https://user-images.githubusercontent.com/68847812/88584705-575f9900-d052-11ea-8fc9-c7815580166f.jpg)

**Comment by jitendrakansal** [comment]
> Correct, I don't see anything.
Can you share export of metadata project from WebIDE and also .mdkproject ? I can test it with my Android device.

**Comment by christian60** [comment]
> 
> 
> Can you share export of metadata project from WebIDE and also .mdkproject ? I can test it with my Android device.

Sure, many thanks.
[MDKDemo.zip](https://github.com/SAPDocuments/Tutorials/files/4984162/MDKDemo.zip)
[MDKDemo.mdkproject.zip](https://github.com/SAPDocuments/Tutorials/files/4984163/MDKDemo.mdkproject.zip)

**Comment by jitendrakansal** [comment]
@christian60 i noticed that you have commented GetCordinates.js (entire logic). Please uncomment it, re-deploy , accept changes on device and check if this solves the issue.

![image](https://user-images.githubusercontent.com/31536700/88589667-c7bde880-d059-11ea-9f67-732e81f3c220.png)

**Comment by jitendrakansal** [comment]
i was able to get it working on my Android device (Samsung galaxy Tab) after uncommenting above JS file

**Comment by christian60** [comment]
> 
> 
> i was able to get it working on my Android device (Samsung galaxy Tab) after uncommenting above JS file

Shame on me, sorry for the inconvenience. I've experimented too much as it wasn't running and forgot that part. :/ It's working fine now. Can you answer me one last question, please? Why does this only work in an own build and not in the SAP Mobile Services Client?

**Comment by jitendrakansal** [comment]
We don't by default add such NS plugins in public store generic client (SAP Mobile Services client) hence custom mdk client is needed.
This also gives customers a flexibility to control their MDK client by adding any number of NS plugins as per need.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
