### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform : error adding SAP HANA as a dependancy

### ISSUE THREAD

**Issue by seanpmcn** [SAPDocuments/Tutorials#5584]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

In step 1, when I run `npm add @sap/hana-client --save`, the following error comes up:

![npmerr](https://user-images.githubusercontent.com/46979553/88576585-a934fe80-d013-11ea-8d2a-533f23e1267e.PNG)

I cannot find any resources on how to resolve this. Here is the debug log:
[2020-07-27T14_25_12_670Z-debug.log](https://github.com/SAPDocuments/Tutorials/files/4983751/2020-07-27T14_25_12_670Z-debug.log)

**Comment by iwonahahn** [comment]
Hi,
As I can see in the log file you are using `node@v13.11.0`. As we recommend in the [prerequisites](https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html) in the first tutorial, please use a supported version of Node.js, which is [12.18.3 LTS](https://nodejs.org/en/). Also please refer to the linked troubleshooting guide in section [Check the Node.js version](https://cap.cloud.sap/docs/advanced/troubleshooting#npm-installation) which is linked in the prerequisites of the first tutorial. 

As an improvement, I´ll add the link to the troubleshooting guide also to the second tutorial.

Hope that helps and best regards,
Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
