### ISSUE TITLE
Create a New ABAP Dictionary Structure

### ISSUE THREAD

**Issue by duyvietdo** [SAPDocuments/Tutorials#5585]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-adt-create-new-structure.html

In step 8 "Test yourself", it is said to provide code in a text field. However, there is none. Only a multiple choice question.

**Comment by julieplummer20** [comment]
Hi,
Is this issue resolved for you? If so, we will close the issue. Please feel free to provide further feedback at any time.
BR Julie.
