### ISSUE TITLE
Create an SAP Cloud Platform ABAP Environment Trial User

### ISSUE THREAD

**Issue by DipeshKumar1** [SAPDocuments/Tutorials#5590]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html

Please specify the step you are referring to-

I've performed below steps-
1. I downloaded latest eclipse & ADT from https://tools.hana.ondemand.com/#abap.
2. Go to the below link 
https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html
3. At step 5: Create ABAP cloud project
Select File > New > Other > ABAP Cloud Project and click Next >.
4. Then I'm getting error even though authentication is successful.
5. Please help.
[Errror.docx](https://github.com/SAPDocuments/Tutorials/files/4989602/Errror.docx)

**Comment by julieplummer20** [comment]
Hi Dipesh,
I will pass this on the team, and we will get back to you as soon as possible.

Best wishes,
Julie.

**Comment by mervey45** [comment]
Hi @DipeshKumar1,

which region did you select? Did you also create the service key?

Thank you.

Best regards, 
Merve

**Comment by DipeshKumar1** [comment]
Hi Merve,

Thank you for your email.

I've used the Frankfurt region.

Yes! I've created a service key as well.

Regards,
Dipesh

**Comment by mervey45** [comment]
Hi @DipeshKumar1 ,

can use chrome please and delete your cache again. And try it out?

Thank you.

Best regards,
Merve

**Comment by DipeshKumar1** [comment]
Hi,

Thank you for your email!

I'm using Chrome only.

I'l delete cache and try again.

Could you please confirm which Eclipse shall I use?

Thanks in advance!

Regards,
Dipesh

**Comment by mervey45** [comment]
Hi @DipeshKumar1 ,

please download following: 
https://www.eclipse.org/downloads/

64-bit version for windows.

You also need a java jdk if your are installing Eclipse for the first time.

Best regards, 
Merve

**Comment by DipeshKumar1** [comment]
Hi,

Thanks again for your email.

There are multiple versions available.

Could you please let me which version of Eclipse should I download?

Thanks in advance.

Regards,
Dipesh

**Comment by mervey45** [comment]
Hi @DipeshKumar1 ,

you need to download the latest version of Eclipse, which is following:  Get Eclipse IDE 2020‑06.

You can download it here: https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2020-06/R/eclipse-inst-win64.exe  
Just press on the download button.

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

we can close this ticket.

Best regards, 
Merve

**Comment by DipeshKumar1** [comment]
Hi,

Thank you for your help!

Regards,
Dipesh
