### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by gitbenedict** [SAPDocuments/Tutorials#5591]
Tutorial URL: https://developers.sap.com/tutorials/xsa-create-user-provided-anonymous-service.html

Please specify the step you are referring to: Create a CDS file
I am able to Build successfully until this step. When I try to Build after creating the hdbcds file. I get the following error,

9:41:55 PM (Builder) Build of "/HANA_APP/db" started.
9:41:58 PM (DIBuild) Build of "/HANA_APP/db" in progress.
9:41:58 PM (DIBuild) Service provisioning for module: '/db'
No service instance will be created for the 'cross-container-service-1' resource of the 'org.cloudfoundry.existing-service' type.
Service instance 'XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_db' for resource 'XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_db' already exists, no operation will be performed.
[INFO] Injecting source code into builder...
[INFO] Source code injection finished
[INFO] ------------------------------------------------------------------------
Your module contains a package.json file, it will be used for the build.
9:42:00 PM (DIBuild) up to date in 0.487s

> deploy@ start /hana/shared/HXE/xs/controller_data/executionagent/executionroot/3304bc0a-ae07-4cbb-9512-be499e736958/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-8361731453055440986/db
> node node_modules/@sap/hdi-deploy/deploy.js

@sap/hdi-deploy, version 3.10.0 (mode default), server version 2.00.045.00.1575639312 (2.0.45.0), node version 8.15.1, HDI version 4, container API version 44
Using service replacements from environment variable "SERVICE_REPLACEMENTS" with 1 replacements
No ignore file at /hana/shared/HXE/xs/controller_data/executionagent/executionroot/3304bc0a-ae07-4cbb-9512-be499e736958/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-8361731453055440986/db/.hdiignore.
Collecting files...
No .hdiconfig found in cfg/, using the one in src.
Collecting files... ok (0s 4ms)
3 directories collected
10 files collected
0 reusable modules collected
Target service: XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_db
Session variable APPLICATION is set to "SAP_HDI/development/HANAExpress".
Previous build with request ID 305 finished at 2020-07-28 16:10:58.510160000 with status Finished and message: Make failed (4 errors, 0 warnings): tried to deploy 1 files, undeploy 0 files, redeploy 0 dependent files.
Processing revoke files...
Processing revoke files... ok (0s 0ms)
Processing grants files...
 Processing "cfg/plain.hdbgrants"...
  Using grantor service "ServiceName_1" of type "sql"
 Processing "cfg/plain.hdbgrants"... ok
Processing grants files... ok (0s 52ms)
Preprocessing files...
Preprocessing files... ok (0s 0ms)
Connecting to the container "DB_1"...
Connecting to the container "DB_1"... ok (0s 17ms)
Locking the container "DB_1"...
Locking the container "DB_1"... ok (0s 71ms)
Synchronizing files with the container "DB_1"...
Synchronizing files with the container "DB_1"... ok (0s 311ms)
1 modified or added files are scheduled for deploy based on delta detection
0 deleted files are scheduled for undeploy based on delta detection (filtered by undeploy whitelist)
0 files are scheduled for deploy based on explicit specification
0 files are scheduled for undeploy based on explicit specification
Deploying to the container "DB_1"...
 Starting make in the container "DB_1" with 1 files to deploy, 0 files to undeploy... 
  Disabling table replication for the container schema "DB_1"... 
  Disabling table replication for the container schema "DB_1"... ok  (0s 71ms)
  Migrating libraries... 
  Migrating libraries... ok  (0s 8ms)
  Making... 
   Preparing... 
   Preparing the make transaction... 
   Adding "src/data/segments.hdbcds" for deploy... 
   Adding "src/data/segments.hdbcds" for deploy... ok  (0s 12ms)
   Preparing... ok  (0s 49ms)
   Preparing the make transaction... ok  (0s 70ms)
   Calculating dependencies... 
    Expanding... 
    Expanding... ok  (0s 6ms)
    Precompiling... 
     Precompiling "src/data/segments.hdbcds"... 
     Precompiling "src/data/segments.hdbcds"... ok  (0s 11ms)
    Precompiling... ok  (0s 22ms)
    Merging... 
     Merging "src/data/segments.hdbcds"... 
     Merging "src/data/segments.hdbcds"... ok  (0s 0ms)
     Precompiling "$cds.merge/segments" (merged)... 
      Merged from "src/data/segments.hdbcds" 
     Precompiling "$cds.merge/segments" (merged)... ok  (0s 12ms)
    Merging... ok  (0s 46ms)
    Error: The file requires "db://PRODUCT_SEGMENT" which is not provided by any file [8212001]
      at "src/data/segments.hdbcds" (1:1-36)
    Error: Could not compose a consistent make graph [8212012]
   Error: Calculating dependencies... failed [8212108]
   Make failed (4 errors, 0 warnings): tried to deploy 1 files, undeploy 0 files, redeploy 0 dependent files 
  Error: Making... failed [8211605]
 Error: Starting make in the container "DB_1" with 1 files to deploy, 0 files to undeploy... failed [8214168]
Deployment to container DB_1 failed - error: HDI make failed [Deployment ID: none].
Error: HDI make failed
(1s 331ms)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deploy@ start: `node node_modules/@sap/hdi-deploy/deploy.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deploy@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /hana/shared/HXE/xs/controller_data/executionagent/executionroot/3304bc0a-ae07-4cbb-9512-be499e736958/app/META-INF/cache/node8.15/.npm/_logs/2020-07-28T16_12_00_389Z-debug.log
9:42:01 PM (Builder) Build of /HANA_APP/db failed.
 	

If I try to open the cds file in graphical editor I get this error,
![resolvingObject](https://user-images.githubusercontent.com/14294991/88692682-fbf9dd80-d11b-11ea-980b-309aed6659e8.png)

If I try to add the object, the 'Finish' button is grayed out
![findDatasource](https://user-images.githubusercontent.com/14294991/88692785-1764e880-d11c-11ea-84bf-b14131d4937c.png)

**Comment by jung-thomas** [comment]
In the previous step - Step 7 Add a Synonym, you should have created the synonym PRODUCT_SEGMENTS. This error would indicate that you've either not completed this step or didn't include the work from this previous step in your build. Are you perhaps building in Step 8 just the hdbcds file.  Your log only shows one modified file.  Somehow you are missing the output from Step 7 which is producing this error.

**Comment by gitbenedict** [comment]
You are right Thomas. The synonym folder was ouside of src. Thank You. But now the issue is with privileges on access to PLAIN schema through synonym created.

**BUILDING DB folder after SERVICE CONNECTION:**
9:34:15 PM (Builder) Build of "/HANA_APP/db" started.
9:34:18 PM (DIBuild) Build of "/HANA_APP/db" in progress.
9:34:18 PM (DIBuild) Service provisioning for module: '/db'No service instance will be created for the 'cross-container-service-1' resource of the 'org.cloudfoundry.existing-service' type.Service instance 'XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_db' for resource 'XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_db' already exists, no operation will be performed.[INFO] Injecting source code into builder...[INFO] Source code injection finished[INFO] ------------------------------------------------------------------------Your module contains a package.json file, it will be used for the build.
9:34:21 PM (DIBuild) up to date in 0.449s> deploy@ start /hana/shared/HXE/xs/controller_data/executionagent/executionroot/3304bc0a-ae07-4cbb-9512-be499e736958/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-1177314933364310432/db> node node_modules/@sap/hdi-deploy/deploy.js@sap/hdi-deploy, version 3.10.0 (mode default), server version 2.00.045.00.1575639312 (2.0.45.0), node version 8.15.1, HDI version 4, container API version 44Using service replacements from environment variable "SERVICE_REPLACEMENTS" with 1 replacementsNo ignore file at /hana/shared/HXE/xs/controller_data/executionagent/executionroot/3304bc0a-ae07-4cbb-9512-be499e736958/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-1177314933364310432/db/.hdiignore.Collecting files...No .hdiconfig found in cfg/, using the one in src.Collecting files... ok (0s 4ms)3 directories collected9 files collected0 reusable modules collectedTarget service: XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_dbSession variable APPLICATION is set to "SAP_HDI/development/HANAExpress".Previous build with request ID 415 finished at 2020-07-29 12:00:33.255803000 with status Finished and message: Starting make in the container "DB_1" with 1 files to deploy, 0 files to undeploy... failed.Processing revoke files...Processing revoke files... ok (0s 0ms)Processing grants files... Processing "cfg/plain.hdbgrants"...  Using grantor service "ServiceName_1" of type "sql" Processing "cfg/plain.hdbgrants"... okProcessing grants files... ok (0s 54ms)Preprocessing files...Preprocessing files... ok (0s 0ms)Connecting to the container "DB_1"...Connecting to the container "DB_1"... ok (0s 18ms)Locking the container "DB_1"...Locking the container "DB_1"... ok (0s 220ms)Synchronizing files with the container "DB_1"...Synchronizing files with the container "DB_1"... ok (0s 558ms)
9:34:23 PM (DIBuild) 0 modified or added files are scheduled for deploy based on delta detection0 deleted files are scheduled for undeploy based on delta detection (filtered by undeploy whitelist)0 files are scheduled for deploy based on explicit specification0 files are scheduled for undeploy based on explicit specificationDeploying to the container "DB_1"... Starting make in the container "DB_1" with 0 files to deploy, 0 files to undeploy...   Enabling table replication for the container schema "DB_1"...   Enabling table replication for the container schema "DB_1"... ok  (0s 2ms) Starting make in the container "DB_1" with 0 files to deploy, 0 files to undeploy... ok  (0s 6ms)Deploying to the container "DB_1"... ok (0s 274ms)No default-access-role handling needed; global role "DB_1::access_role" will not be adaptedUnlocking the container "DB_1"...Unlocking the container "DB_1"... ok (0s 1ms)Deployment to container DB_1 done [Deployment ID: none].(1s 799ms)
9:34:23 PM (DIBuild) ********** End of /HANA_APP/db Build Log **********
9:34:23 PM (DIBuild) Build results link: https://hxehost:53075/che/builder/workspacee6q72ye2mqupm5ku/download-all/41576b8a-a6fd-4b6f-9184-f19ea44f3a90?arch=zip
9:34:28 PM (Builder) Build of /HANA_APP/db completed successfully.

**BUILDING DB folder after synonyms file creation:**
9:36:45 PM (Builder) Build of "/HANA_APP/db" started.
9:36:47 PM (DIBuild) Build of "/HANA_APP/db" in progress.
9:36:48 PM (DIBuild) Service provisioning for module: '/db'No service instance will be created for the 'cross-container-service-1' resource of the 'org.cloudfoundry.existing-service' type.Service instance 'XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_db' for resource 'XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_db' already exists, no operation will be performed.[INFO] Injecting source code into builder...[INFO] Source code injection finished[INFO] ------------------------------------------------------------------------Your module contains a package.json file, it will be used for the build.
9:36:50 PM (DIBuild) up to date in 0.516s> deploy@ start /hana/shared/HXE/xs/controller_data/executionagent/executionroot/3304bc0a-ae07-4cbb-9512-be499e736958/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-3552975185607612571/db> node node_modules/@sap/hdi-deploy/deploy.js@sap/hdi-deploy, version 3.10.0 (mode default), server version 2.00.045.00.1575639312 (2.0.45.0), node version 8.15.1, HDI version 4, container API version 44Using service replacements from environment variable "SERVICE_REPLACEMENTS" with 1 replacementsNo ignore file at /hana/shared/HXE/xs/controller_data/executionagent/executionroot/3304bc0a-ae07-4cbb-9512-be499e736958/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-3552975185607612571/db/.hdiignore.Collecting files...No .hdiconfig found in cfg/, using the one in src.Collecting files... ok (0s 5ms)4 directories collected10 files collected0 reusable modules collectedTarget service: XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_dbSession variable APPLICATION is set to "SAP_HDI/development/HANAExpress".Previous build with request ID 423 finished at 2020-07-29 16:04:24.785460000 with status Committed and message: Starting make in the container "DB_1" with 0 files to deploy, 0 files to undeploy... ok.Processing revoke files...Processing revoke files... ok (0s 0ms)Processing grants files... Processing "cfg/plain.hdbgrants"...  Using grantor service "ServiceName_1" of type "sql" Processing "cfg/plain.hdbgrants"... okProcessing grants files... ok (0s 55ms)Preprocessing files...Preprocessing files... ok (0s 0ms)Connecting to the container "DB_1"...Connecting to the container "DB_1"... ok (0s 25ms)Locking the container "DB_1"...Locking the container "DB_1"... ok (0s 75ms)Synchronizing files with the container "DB_1"...Synchronizing files with the container "DB_1"... ok (0s 394ms)
9:36:53 PM (DIBuild) 1 modified or added files are scheduled for deploy based on delta detection0 deleted files are scheduled for undeploy based on delta detection (filtered by undeploy whitelist)0 files are scheduled for deploy based on explicit specification0 files are scheduled for undeploy based on explicit specificationDeploying to the container "DB_1"... Starting make in the container "DB_1" with 1 files to deploy, 0 files to undeploy...   Disabling table replication for the container schema "DB_1"...   Disabling table replication for the container schema "DB_1"... ok  (0s 87ms)  Migrating libraries...   Migrating libraries... ok  (0s 46ms)  Making...    Preparing...    Preparing the make transaction...    Adding "src/synonyms/plain.hdbsynonym" for deploy...    Adding "src/synonyms/plain.hdbsynonym" for deploy... ok  (0s 102ms)   Preparing... ok  (0s 361ms)   Preparing the make transaction... ok  (0s 652ms)   Calculating dependencies...     Expanding...      Expanding "src/synonyms/plain.hdbsynonym"...      Expanding "src/synonyms/plain.hdbsynonym"... ok  (0s 2ms)    Expanding... ok  (0s 70ms)    Precompiling...      Precompiling "src/synonyms/plain.hdbsynonym"...      Precompiling "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"...       Expanded from "src/synonyms/plain.hdbsynonym"      Precompiling "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"... ok  (0s 0ms)     Precompiling "src/synonyms/plain.hdbsynonym"... ok  (0s 2ms)    Precompiling... ok  (0s 12ms)    Merging...      Merging "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"...       Expanded from "src/synonyms/plain.hdbsynonym"      Merging "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"... ok  (0s 0ms)     Precompiling "$synonym.config/PRODUCT_SEGMENT" (merged)...       Merged from "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"      Precompiling "$synonym.config/PRODUCT_SEGMENT" (merged)... ok  (0s 0ms)    Merging... ok  (0s 133ms)   Calculating dependencies... ok  (0s 284ms)   Processing work list...     Deploying "$synonym.config/PRODUCT_SEGMENT"...      Merged from "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"     Deploying "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"...      Expanded from "src/synonyms/plain.hdbsynonym"     Deploying "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"... ok  (0s 0ms)    Deploying "$synonym.config/PRODUCT_SEGMENT"... ok  (0s 15ms)    Deploying "src/synonyms/plain.hdbsynonym"...      **Error: com.sap.hana.di.synonym: The container's object owner "DB_1#OO" is not authorized to access the "PLAIN.PRODUCT_SEGMENT" synonym target. This user needs to be granted "SELECT" ("EXECUTE" for procedures) privileges on the target object.** [8250505]       at "src/synonyms/plain.hdbsynonym" (0:0)    Warning: Worker 1 running the "com.sap.hana.di.synonym" plugin has encountered an error while deploying 1 objects [8212030]    Error: Worker 1 has encountered an error; all remaining jobs will be canceled [8214600]   Error: Processing work list... failed [8212102]   Make failed (4 errors, 1 warnings): tried to deploy 1 files, undeploy 0 files, redeploy 0 dependent files   Error: Making... failed [8211605] Error: Starting make in the container "DB_1" with 1 files to deploy, 0 files to undeploy... failed [8214168]Deployment to container DB_1 failed - error: HDI make failed [Deployment ID: none].Error: HDI make failed(2s 608ms)npm ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! deploy@ start: `node node_modules/@sap/hdi-deploy/deploy.js`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the deploy@ start script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.npm ERR! A complete log of this run can be found in:npm ERR!     /hana/shared/HXE/xs/controller_data/executionagent/executionroot/3304bc0a-ae07-4cbb-9512-be499e736958/app/META-INF/cache/node8.15/.npm/_logs/2020-07-29T16_06_55_552Z-debug.log
9:36:53 PM (Builder) Build of /HANA_APP/db failed.

**dev-tenant is the same space my project is configured**
![serviceConnection](https://user-images.githubusercontent.com/14294991/88831813-852d1500-d1ed-11ea-86d7-1c959b7646fc.jpg)


**SYSTEM user created the schema and table in HXE tenant**
![SYSTEM privileges on PLAIN](https://user-images.githubusercontent.com/14294991/88831982-ba396780-d1ed-11ea-9372-042f0f65a9e4.jpg)

**Comment by jung-thomas** [comment]
This tells me that you hdbgrants from step 6 may not be correct. I can see in the logs that it is processing the hdbrants file:
**Processing "cfg/plain.hdbgrants"... Using grantor service "ServiceName_1" of type "sql" Processing "cfg/plain.hdbgrants"... okProcessing grants files... ok (0s 54ms)Preprocessing files...Preprocessing files... ok**

This is exactly the step that should grant the access to your container user to the foreign schema. Double check the contents of your hdbgrants file.  Are you sure you saved the content?

**Comment by gitbenedict** [comment]
thank you for looking into this. I deleted the synonym and grants file and rebuilt them. I know I am missing something trivial here, but being new to this I am not able to spot it.
Also, I have attached the package here, in case it helps.
[HANA_APP.zip](https://github.com/SAPDocuments/Tutorials/files/5002603/HANA_APP.zip)


**BUILDING DB folder after hdbgrants creation:**
9:34:15 PM (Builder) Build of "/HANA_APP/db" started.
9:34:18 PM (DIBuild) Build of "/HANA_APP/db" in progress.
9:34:18 PM (DIBuild) Service provisioning for module: '/db'No service instance will be created for the 'cross-container-service-1' resource of the 'org.cloudfoundry.existing-service' type.Service instance 'XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_db' for resource 'XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_db' already exists, no operation will be performed.[INFO] Injecting source code into builder...[INFO] Source code injection finished[INFO] ------------------------------------------------------------------------Your module contains a package.json file, it will be used for the build.
9:34:21 PM (DIBuild) up to date in 0.449s> deploy@ start /hana/shared/HXE/xs/controller_data/executionagent/executionroot/3304bc0a-ae07-4cbb-9512-be499e736958/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-1177314933364310432/db> node node_modules/@sap/hdi-deploy/deploy.js@sap/hdi-deploy, version 3.10.0 (mode default), server version 2.00.045.00.1575639312 (2.0.45.0), node version 8.15.1, HDI version 4, container API version 44Using service replacements from environment variable "SERVICE_REPLACEMENTS" with 1 replacementsNo ignore file at /hana/shared/HXE/xs/controller_data/executionagent/executionroot/3304bc0a-ae07-4cbb-9512-be499e736958/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-1177314933364310432/db/.hdiignore.Collecting files...No .hdiconfig found in cfg/, using the one in src.Collecting files... ok (0s 4ms)3 directories collected9 files collected0 reusable modules collectedTarget service: XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_dbSession variable APPLICATION is set to "SAP_HDI/development/HANAExpress".Previous build with request ID 415 finished at 2020-07-29 12:00:33.255803000 with status Finished and message: Starting make in the container "DB_1" with 1 files to deploy, 0 files to undeploy... failed.Processing revoke files...Processing revoke files... ok (0s 0ms)Processing grants files... Processing "cfg/plain.hdbgrants"...  Using grantor service "ServiceName_1" of type "sql" Processing "cfg/plain.hdbgrants"... okProcessing grants files... ok (0s 54ms)Preprocessing files...Preprocessing files... ok (0s 0ms)Connecting to the container "DB_1"...Connecting to the container "DB_1"... ok (0s 18ms)Locking the container "DB_1"...Locking the container "DB_1"... ok (0s 220ms)Synchronizing files with the container "DB_1"...Synchronizing files with the container "DB_1"... ok (0s 558ms)
9:34:23 PM (DIBuild) 0 modified or added files are scheduled for deploy based on delta detection0 deleted files are scheduled for undeploy based on delta detection (filtered by undeploy whitelist)0 files are scheduled for deploy based on explicit specification0 files are scheduled for undeploy based on explicit specificationDeploying to the container "DB_1"... Starting make in the container "DB_1" with 0 files to deploy, 0 files to undeploy...   Enabling table replication for the container schema "DB_1"...   Enabling table replication for the container schema "DB_1"... ok  (0s 2ms) Starting make in the container "DB_1" with 0 files to deploy, 0 files to undeploy... ok  (0s 6ms)Deploying to the container "DB_1"... ok (0s 274ms)No default-access-role handling needed; global role "DB_1::access_role" will not be adaptedUnlocking the container "DB_1"...Unlocking the container "DB_1"... ok (0s 1ms)Deployment to container DB_1 done [Deployment ID: none].(1s 799ms)
9:34:23 PM (DIBuild) ********** End of /HANA_APP/db Build Log **********
9:34:23 PM (DIBuild) Build results link: https://hxehost:53075/che/builder/workspacee6q72ye2mqupm5ku/download-all/41576b8a-a6fd-4b6f-9184-f19ea44f3a90?arch=zip
9:34:28 PM (Builder) Build of /HANA_APP/db completed successfully.

**BUILDING DB folder after synonyms file creation:**
8:21:16 PM (Builder) Build of "/HANA_APP/db" started.
8:21:22 PM (DIBuild) Build of "/HANA_APP/db" in progress.
8:21:23 PM (DIBuild) Service provisioning for module: '/db'No service instance will be created for the 'CROSS_SCHEMA_PRODUCTS' resource of the 'org.cloudfoundry.existing-service' type.Service instance 'XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_db' for resource 'XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_db' already exists, no operation will be performed.[INFO] Injecting source code into builder...[INFO] Source code injection finished[INFO] ------------------------------------------------------------------------Your module contains a package.json file, it will be used for the build.up to date in 0.625s> deploy@ start /hana/shared/HXE/xs/controller_data/executionagent/executionroot/3304bc0a-ae07-4cbb-9512-be499e736958/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-2368462583301604518/db> node node_modules/@sap/hdi-deploy/deploy.js
8:21:25 PM (DIBuild) @sap/hdi-deploy, version 3.10.0 (mode default), server version 2.00.045.00.1575639312 (2.0.45.0), node version 8.15.1, HDI version 4, container API version 44Using service replacements from environment variable "SERVICE_REPLACEMENTS" with 1 replacementsNo ignore file at /hana/shared/HXE/xs/controller_data/executionagent/executionroot/3304bc0a-ae07-4cbb-9512-be499e736958/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-2368462583301604518/db/.hdiignore.Collecting files...No .hdiconfig found in cfg/, using the one in src.Collecting files... ok (0s 5ms)4 directories collected10 files collected0 reusable modules collectedTarget service: XSA_DEV-e6q72ye2mqupm5ku-HANA_APP-hdi_dbSession variable APPLICATION is set to "SAP_HDI/development/HANAExpress".Previous build with request ID 478 finished at 2020-07-30 13:48:00.621086000 with status Finished and message: Make failed (4 errors, 1 warnings): tried to deploy 1 files, undeploy 0 files, redeploy 0 dependent files.Processing revoke files...Processing revoke files... ok (0s 0ms)Processing grants files... Processing "cfg/plain.hdbgrants"...  Using grantor service "ServiceName_1" of type "sql" Processing "cfg/plain.hdbgrants"... okProcessing grants files... ok (0s 71ms)Preprocessing files...Preprocessing files... ok (0s 0ms)Connecting to the container "DB_1"...Connecting to the container "DB_1"... ok (0s 23ms)Locking the container "DB_1"...Locking the container "DB_1"... ok (0s 277ms)Synchronizing files with the container "DB_1"...Synchronizing files with the container "DB_1"... ok (0s 790ms)1 modified or added files are scheduled for deploy based on delta detection0 deleted files are scheduled for undeploy based on delta detection (filtered by undeploy whitelist)0 files are scheduled for deploy based on explicit specification0 files are scheduled for undeploy based on explicit specificationDeploying to the container "DB_1"...
8:21:28 PM (DIBuild)  Starting make in the container "DB_1" with 1 files to deploy, 0 files to undeploy...   Disabling table replication for the container schema "DB_1"...   Disabling table replication for the container schema "DB_1"... ok  (0s 131ms)  Migrating libraries...   Migrating libraries... ok  (0s 40ms)  Making...    Preparing...    Preparing the make transaction...    Adding "src/synonyms/plain.hdbsynonym" for deploy...    Adding "src/synonyms/plain.hdbsynonym" for deploy... ok  (0s 99ms)   Preparing... ok  (0s 338ms)   Preparing the make transaction... ok  (0s 723ms)   Calculating dependencies...     Expanding...      Expanding "src/synonyms/plain.hdbsynonym"...      Expanding "src/synonyms/plain.hdbsynonym"... ok  (0s 2ms)    Expanding... ok  (0s 88ms)    Precompiling...      Precompiling "src/synonyms/plain.hdbsynonym"...      Precompiling "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"...       Expanded from "src/synonyms/plain.hdbsynonym"      Precompiling "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"... ok  (0s 0ms)     Precompiling "src/synonyms/plain.hdbsynonym"... ok  (0s 3ms)    Precompiling... ok  (0s 21ms)    Merging...      Merging "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"...       Expanded from "src/synonyms/plain.hdbsynonym"      Merging "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"... ok  (0s 0ms)     Precompiling "$synonym.config/PRODUCT_SEGMENT" (merged)...       Merged from "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"      Precompiling "$synonym.config/PRODUCT_SEGMENT" (merged)... ok  (0s 0ms)    Merging... ok  (0s 136ms)   Calculating dependencies... ok  (0s 339ms)   Processing work list...     Deploying "$synonym.config/PRODUCT_SEGMENT"...      Merged from "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"     Deploying "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"...      Expanded from "src/synonyms/plain.hdbsynonym"     Deploying "src/synonyms/plain.hdbsynonym$PRODUCT_SEGMENT.defaults"... ok  (0s 0ms)    Deploying "$synonym.config/PRODUCT_SEGMENT"... ok  (0s 19ms)    Deploying "src/synonyms/plain.hdbsynonym"...      Error: com.sap.hana.di.synonym: The container's object owner "DB_1#OO" is not authorized to access the "PLAIN.PRODUCT_SEGMENT" synonym target. This user needs to be granted "SELECT" ("EXECUTE" for procedures) privileges on the target object. [8250505]       at "src/synonyms/plain.hdbsynonym" (0:0)    Warning: Worker 2 running the "com.sap.hana.di.synonym" plugin has encountered an error while deploying 1 objects [8212030]    Error: Worker 2 has encountered an error; all remaining jobs will be canceled [8214600]   Error: Processing work list... failed [8212102]   Make failed (4 errors, 1 warnings): tried to deploy 1 files, undeploy 0 files, redeploy 0 dependent files   Error: Making... failed [8211605] Error: Starting make in the container "DB_1" with 1 files to deploy, 0 files to undeploy... failed [8214168]Deployment to container DB_1 failed - error: HDI make failed [Deployment ID: none].Error: HDI make failed(4s 130ms)npm ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! deploy@ start: `node node_modules/@sap/hdi-deploy/deploy.js`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the deploy@ start script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.npm ERR! A complete log of this run can be found in:npm ERR!     /hana/shared/HXE/xs/controller_data/executionagent/executionroot/3304bc0a-ae07-4cbb-9512-be499e736958/app/META-INF/cache/node8.15/.npm/_logs/2020-07-30T14_51_30_486Z-debug.log
8:21:28 PM (Builder) Build of /HANA_APP/db failed.

**Comment by jung-thomas** [comment]
I imported your project zip into my local system. I manually created the schema and user provided service according to the steps in the tutorial.  I then built the db module and it completed successfully:
![image](https://user-images.githubusercontent.com/12159356/88956813-ebf11380-d26b-11ea-86dd-481cff199209.png)

So everything with the code is fine. Perhaps you still have some mismatch between the tenant your space is working in and the one that you imported the schema.  Its difficult to say as this part is all in your system. But your project is correct as it builds in my system. And the steps in the tutorial are correct as well as I can follow them with your project and it all works.

**Comment by jung-thomas** [comment]
As you have asked this question on the community forum and I can find no defect in the tutorial itself I am closing the issue here in Github. 
Your community Q&A thread: https://answers.sap.com/questions/13106209/authorization-error-accessing-classic-schema-from.html

**Comment by gitbenedict** [comment]
Thanks Thomas for your efforts on this. I will re-import and start from scratch and see if it works
