### ISSUE TITLE
Improve User Experience of the List and Detail Page

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#5594]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-101-improve-user-experience.html

Please specify the step you are referring to 4

My test results don't get filtered and i keep getting the whole list and not 2 "Chef" items as per tutorial. 
Tried running configurations, refreshing the page, but there is no change.

**Comment by IObert** [comment]
Hi,

this is strange, I just double-checked and it works for me. Do you see any errors in the console log?

**Comment by greg2git** [comment]
i can see this in the console:
#2.0#2020 07 30 22:11:35:455#+00:00#WARNING#/Configuration#####kd9cpkfz##########kd9cpkfz#PLAIN##No authentication will be used when accessing backends. Scopes defined in routes will be ignored.#
#2.0#2020 07 30 22:11:35:456#+00:00#INFO#/Configuration#####kd9cpkfz##########kd9cpkfz#PLAIN##Replacing $XSAPPNAME will not take place - 'xsappname' property not found in UAA configuration.#
#2.0#2020 07 30 22:11:35:668#+00:00#WARNING#/Dynamic routing#####kd9cpqp4##########kd9cpqp4#PLAIN##Service Tag favicon is unknown#
#2.0#2020 07 30 22:11:35:670#+00:00#WARNING#/Configuration#####kd9cpkfz##########kd9cpkfz#PLAIN##No authentication will be used when accessing backends. Scopes defined in routes will be ignored.#
#2.0#2020 07 30 22:11:35:671#+00:00#INFO#/Configuration#####kd9cpkfz##########kd9cpkfz#PLAIN##Replacing $XSAPPNAME will not take place - 'xsappname' property not found in UAA configuration.#
#2.0#2020 07 30 22:11:35:674#+00:00#ERROR#/Handler#####d48bd089-7534-4092-96f9-73e46269a75e####IhkDwYU6A_8CXzdzBj18qdadWWUmoAT8######d48bd089-7534-4092-96f9-73e46269a75e#PLAIN##GET request to /favicon.ico completed with status 502 - error while forwarding request to http://localhost:5001/favicon.ico: socket hang up#
#2.0#2020 07 30 22:11:35:702#+00:00#WARNING#/Configuration#####kd9cpkfz##########kd9cpkfz#PLAIN##No authentication will be used when accessing backends. Scopes defined in routes will be ignored.#

but nothing gets written in Chrome when I press the 'magnifying glass' in the search bar.

**Comment by IObert** [comment]
Sorry, I didn't mean the App Studio console (which shows the server log) but the [browser console](https://developers.google.com/web/tools/chrome-devtools/open) (to see the client log)

**Comment by greg2git** [comment]
i don't know how to easily upload images here, but maybe you can view the log in this link: https://wiki.scn.sap.com/wiki/x/FwvwI

**Comment by IObert** [comment]
Thanks. Did you hit enter (or click the magnifying glass) before making the screenshot? I can't see an error that might have caused this in your screenshot.

Btw: You can drag and drop images in the text box to upload them here

**Comment by greg2git** [comment]
thx for the tip about posting images here and i just learned something new about github.

in any case, neither action of enter or magnifying glass seems to produce any log entries:
![image](https://user-images.githubusercontent.com/24355032/89048469-df2cf800-d31d-11ea-9f76-1c9fa5c84d69.png)

**Comment by IObert** [comment]
It seems that the handler is never called 🤔

Can you double-check that the code described in [step 2](https://developers.sap.com/tutorials/sapui5-101-improve-user-experience.html#98279685-e068-4249-9585-81d8fef36b94) matched the code in your project? 
If so, please write `debugger` after line 11 in the controller and test it again. This adds a breakpoint right after the "onSearch" event that should be hit when you search the next time. With this, you can make sure whether the method is actually called.

**Comment by greg2git** [comment]
That was it, my List.controller.js was never overwritten with the new code from that Step. 
it's all good now. tutorial finished and code working as expected. 
thx for the tip and responding to the issue.
