### ISSUE TITLE
Explore the Virtual Data Model with the CDS Browser

### ISSUE THREAD

**Issue by clhberger** [SAPDocuments/Tutorials#5600]
Tutorial URL: https://developers.sap.com/tutorials/s4hana-kut-viewbrowser-virtual-data-model.html
Not able to do the exercise
first step, remote connection, server not available, credentials not available ( pw will be given by instructor!)....

**Comment by MichaelCzcz** [comment]
@D037411 Please respond.

**Comment by D037411** [comment]
Dear Michael,
sorry for replying so late. The  working environment described in this Tutorial was dedicated  specially to TechEd.  I'm sorry for the inconvenience this may have caused. That System is not available any more.

**Comment by thecodester** [comment]
Clsoing issue as tutorials have been removed. Sorry for the confusion.
