### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by Rodfior** [SAPDocuments/Tutorials#5605]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Please specify the step you are referring to: 7

when I try to run the application on FLP Sandbox I got the following error: 
TypeError: t.oCommonUtils.getNavigationHandler is not a function

<img width="431" alt="Capture1" src="https://user-images.githubusercontent.com/33035341/89127083-3f0fd400-d4c1-11ea-8739-567e9d4d6bec.PNG">
<img width="536" alt="Capture3" src="https://user-images.githubusercontent.com/33035341/89127082-3e773d80-d4c1-11ea-87e3-60bdee1aec28.PNG">
<img width="455" alt="Capture2" src="https://user-images.githubusercontent.com/33035341/89127080-3ddea700-d4c1-11ea-9e40-9732560692d0.PNG">

**Comment by mervey45** [comment]
Hi @Rodfior ,

can you check your SAP Cloud Platform trial user and your service key again?
Maybe your trial account is exceeded?

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @thecodester ,

we can close this issue. SAP Web IDE is not available for trial anymore.

Thank you.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
