### ISSUE TITLE
Create an AMDP and Analyze Its Performance

### ISSUE THREAD

**Issue by Faaiez** [SAPDocuments/Tutorials#5610]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-amdp-profiling.html

Please specify the step you are referring to Step 6.

The method call should be   call "ZCL_AMDP_DEMO_XXX=>CONVERT_CURRENCY"( :flights, result );

OR

Change the class name in Step 2 to ZCL_AMDP_XXX.

**Comment by julieplummer20** [comment]
Hi Faaiez,
Thanks a lot. I have now changed this.
BR Julie.
