### ISSUE TITLE
Expose a Standard Core Data Service for ABAP Environment

### ISSUE THREAD

**Issue by markdevries** [SAPDocuments/Tutorials#5611]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-business-service-provisioning.html

Please specify the step you are referring to: Step 1 wording could use some love...and or language editing :)

You need to create an OData service by defining and binding a service based on the corresponding CDS view. As soon as the OData service is published in the local system repository, **it is ready to be consumption using an OData client**, such as a SAP Fiori app. To be able to use this **exposed service and related service binding**, you need to create a published Communication Scenario. This published Communication Scenario will be **assigned in to a** Communication Arrangement.

**Comment by mervey45** [comment]
Hi @markdevries ,

thank you for your feedback. We'll update this step.

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @niloofar-flothkoetter ,

can you update this tutorial?

Thank you.

Best regards, 
Merve

**Comment by thecodester** [comment]
The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
