### ISSUE TITLE
Create an ABAP Core Data Services (CDS) View in SAP NetWeaver 7.5

### ISSUE THREAD

**Issue by Faaiez** [SAPDocuments/Tutorials#5613]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-create-cds-view.html

Please specify the step you are referring to Step 9.

There is a syntax error key TravelID;

**Comment by julieplummer20** [comment]
Hi Faaiez,
I'm not getting a syntax error. Can you post the code of your CDS view. Also, does the error message say anything else?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
