### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by pook31** [SAPDocuments/Tutorials#5621]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html

Please specify the step you are referring to Step 5
Unable to get My Inbox to show new entry.  It is still reporting 0

**Comment by pook31** [comment]
Unable to get My Inbox to show new entry. It is still reporting 0

**Comment by ArchanaShukla** [comment]
This means that you have not set the right assignee while defining the workflow user task. Please enter your email ID in the recipient property of the user task.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
