### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by Faaiez** [SAPDocuments/Tutorials#5623]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Step 4.2

I do not see the abap-trial service when trying to add the service to the app although I do have one.
I've completed everything up to this point.

![image](https://user-images.githubusercontent.com/6542236/89395735-0284e800-d70e-11ea-903e-89556871a448.png)

**Comment by mervey45** [comment]
Hi @Faaiez ,

are you working with the trial: https://cockpit.hanatrial.ondemand.com/cockpit/ ?
Please also check, whether your ABAP instance is still active.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
