### ISSUE TITLE
Set Up SAP Mobile Cards

### ISSUE THREAD

**Issue by kh374** [SAPDocuments/Tutorials#5628]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-setup.html

The QR Code for iOS doesn't seem to be working. I have the SAP Mobile Cards App installed, but when I scan the QR code I get the error "No usable data found"

**Comment by sandeep-tds** [comment]
Hi @kh374, 

Thank you for raising the issue. Can you please uninstall and re-install the app from the app store?

**Comment by kh374** [comment]
I did but it didn't solve the problem. The app doesn't seem to be recognizing the QR code. Nothing dramatic though.

**Comment by sandeep-tds** [comment]
Hi @kh374, 

Can we please discuss the issue over a call? we want to ensure that issue is resolved. 

Can you please comment with a time that is convenient for you? I shall send a Meeting Request accordingly.

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
@kh374 Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
