### ISSUE TITLE
Set up Secure Tunnel between ABAP System and SAP Cloud Platform (CF)

### ISSUE THREAD

**Issue by jrodriguez-rc** [SAPDocuments/Tutorials#5629]
Tutorial URL: https://developers.sap.com/tutorials/cp-connectivity-create-secure-tunnel.html

I don't know if the tutorial is outdated, but follow steps CF trial subaccount can't connect to the backend with cloud connector, throwing error `Could not check at the moment. Please try again later`

For the Neo environment, the connection works.

Maybe some additional steps are necessary.

**Comment by JensHaley** [comment]
This tutorial is part of the following group: [https://developers.sap.com/group.cp-connectivity-odata.html](https://developers.sap.com/group.cp-connectivity-odata.html)

So did you go through the tutorials before and after the one you mention? When is the error thrown?

**Comment by jrodriguez-rc** [comment]
Yes, all steps are done, and I can connect from Neo environment, but not from CF

**Comment by JensHaley** [comment]
Ok, thank you.

Could you please share:
* The release of the ABAP backend you're using (including SP level)
* The version of the cloud connector you're using
* At what step of the tutorial you run into the error

I will then try to reproduce the error.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
