### ISSUE TITLE
Inspect and Test the API Proxy #4631

### ISSUE THREAD

**Issue by bhushanishwarkar1** [SAPDocuments/Tutorials#5630]
I am working on this series and have come across an issue with implementing the app_id and app_code into the API policy.

I have signed up on HERE, and generated the codes for each REST and JS (tried both sets, neither work), however they do not seem to work.

When accessing the API through the browser, the file is returned for …/salesTrackerAPI, …/salesTrackersAPI/BusinessPartnerSet, ...salesTrackerAPI/BusinessPartnerSet?$top=10. However when attempting to get the geocode information from …/salesTrackerAPI/BusinessPartnerSet('0100000003') an error is returned.

" {"fault":{"faultstring":"Execution of ServiceCallout CallGeocodingAPI failed. Reason: ResponseCode 401 is treated as error","detail":{"errorcode":"steps.servicecallout.ExecutionFailed"}}} " is the returned error.

 i am using Tutorial URL: https://developers.sap.com/tutorials/cp-apim-shoppingfresh-inspect-apiproxy.html.

. I have it copied correctly, however still getting this issue. Where is the HERE api called from in the salesTrackerAPI? Also, on the HERE page you get a JS app_id and app_key.

I believe it is an issue when attempting to use the app_id and app_code, but feedback is appreciated. Thank you.

**Comment by shilpavij** [comment]
Dear colleague,

401 is unauthorized. Yes, your app id and app code is not correct.
Can you please check once the spaces and all. You can copy it in notepad and then try to paste.

Regards
Shilpa

**Comment by bhushanishwarkar1** [comment]
*Dear Sir/Madam,*

Hello,

Thank you for your response. I have it copied correctly, however still
getting this issue. Where is the HERE api called from in the
salesTrackerAPI? Also, on the HERE page you get a JS app_id and app_key, is
that they same as app_code?


*Thanking You.*

*Regards,*

*----*
*Bhushan Ishwarkar*

*              SAP-ABAP       Associate Consultant*

**Comment by bhushanishwarkar1** [comment]
Hello,

Thank you for your response. I have it copied correctly, however still getting this issue. Where is the HERE api called from in the salesTrackerAPI? Also, on the HERE page you get a JS app_id and app_key, is that they same as app_code?

**Comment by MichaelCzcz** [comment]
@shilpavij Any Updates?

**Comment by shilpavij** [comment]
Dear Colleague,
There is a naming convention change for App id and app code and the generic comment is adopted in the tutorial.
To answer your question- yes,  JS app_id and app_key, is the same as app_code.

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
