### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Tutorials#5631]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Step1 
        Sub step 2 ----> Screenshot needs to be updated. In tutorial showing "Fiori Project" in real "SAP Fiori Freestyle – Project Generator"
![image](https://user-images.githubusercontent.com/65213299/89539294-36006900-d819-11ea-9333-d2c998cd5962.png)
![image](https://user-images.githubusercontent.com/65213299/89539371-4a446600-d819-11ea-950d-3318f50eb3f9.png)

Step 1 
        Sub step 8
                        Step B ---------> "Select a source	ES5_BASIC_AUTH [Catalog]" in tutorial in real "ES5 [Catalog]"

Step 4
        Sub step 6 ---------------> "ES5_BASIC_AUTH" is mentioned in tutorial in real "ES5"

If this last 2 differences is depend on the name of the destination which we created in the below tutorial link and step details provided, then need to update  "ES5_BASIC_AUTH" to "ES5" in tutorial.
 Step 2 - sub step 3 - Field:Name
 https://developers.sap.com/tutorials/cp-portal-cloud-foundry-gateway-connection.html

**Comment by raz-korn** [comment]
Hi @shivakumar-p-sap ,

Thanks for letting me know.
An update will be available available soon.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
