### ISSUE TITLE
Implement Your First Screen in an iOS App

### ISSUE THREAD

**Issue by jastill** [SAPDocuments/Tutorials#5632]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-scpms-starter-mission-02.html

Please specify the step you are referring to:
Step 5, as per the warning my service does use Offline. The changes required include importing the Offline OData framework and changing the container type.

import SAPOfflineOData

    var dataService: ESPMContainer<OfflineODataProvider>? {
        guard let odataController = OnboardingSessionManager.shared.onboardingSession?.odataControllers[destinations["com.sap.edm.sampleservice.v2"] as! String] as? Comsapedmsampleservicev2OfflineODataController, let dataService = odataController.espmContainer else {
            AlertHelper.displayAlert(with: NSLocalizedString("OData service is not reachable, please onboard again.", comment: ""), error: nil, viewController: self)
            return nil
        }
        return dataService
    }

**Comment by KevinMuessig** [comment]
Hello @jastill ,

thank you for noticing that. Let me put that in the tutorial to make this step more clear.

Thanks,

KM
