### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by hearmonster** [SAPDocuments/Tutorials#5633]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to #2 (select the **Fiori Project** template)
I'm using BAS within Canary ...so I might be ahead of GA.
FYI However, I have three template choices but 'Fiori Project' is no longer one of them.  I selected the **SAP Fiori Freestyle – Project Generator** tile - because it has the same icon as yours.
![image](https://user-images.githubusercontent.com/8210748/89583604-3cceb200-d800-11ea-9edf-9316b60ae567.png)
Appears to work...

**Comment by raz-korn** [comment]
Hi @hearmonster ,

Thanks for letting me know.
An update will be available soon.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
