### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by toddmfisher** [SAPDocuments/Tutorials#5634]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

Step 3, item 2
"cds build" command only generates gen/srv, not gen/db.  No manifest.yaml files are created in gen/srv. 

"cf push -f gen/db" fails since gen/db does not exist
"cf push -f gen/srv --random-route" fails since there is no manifest

@sap/cds: 4.1.5
@sap/cds-compiler: 1.35.0
@sap/cds-dk: 2.0.7
@sap/cds-foss: 2.0.0
@sap/cds-reflect: 2.12.2
@sap/cds-runtime: 2.1.5
@sap/hana-client: 2.5.104
Node.js: v12.16.2

Thank you

**Comment by iwonahahn** [comment]
Sorry for the late reply, I was on vacation for a long time. Could you please try it again with the latest version `@sap/cd-dk: 2.0.8`?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
