### ISSUE TITLE
Set Up SAP Data Intelligence, Trial Edition

### ISSUE THREAD

**Issue by sabarna17** [SAPDocuments/Tutorials#5637]
Tutorial URL: https://developers.sap.com/tutorials/dataintelligence-trial-v2-setup.html

Please specify the step you are referring to

- Using GCP is giving error
![SAP_DI_ERROR](https://github.com/sabarna17/ERROR_SCREENSHOTS/blob/master/dataIntellegenceError.PNG)

Another error for a different GCP Account->
![SAP_DI_ERROR](https://github.com/sabarna17/ERROR_SCREENSHOTS/blob/master/dataIntellegenceError2.PNG)

**Comment by MichaelCzcz** [comment]
@dimvor Please respond.

**Comment by dimvor** [comment]
It appears that the Google service account you provided in SAP CAL does not provide sufficient permissions to deploy the Trial Edition. Please review section 2.1.3 in the Getting Started guide: https://caldocs.hana.ondemand.com/caldocs/help/a318f6b5-aa5a-4dfb-893e-1aac356ca5f8_Getting_Started_Guide_v37.pdf

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
