### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by whitenrock** [SAPDocuments/Tutorials#5639]
When I generate a project and then start it, I get the following error:

> Error [ERR_SOCKET_CLOSED]: Socket is closed
>     at Socket._writeGeneric (net.js:772:8)
>     at Socket._write (net.js:794:8)
>     at doWrite (_stream_writable.js:377:12)
>     at clearBuffer (_stream_writable.js:517:7)
>     at Socket.Writable.uncork (_stream_writable.js:317:7)
>     at ClientRequest._flushOutput (_http_outgoing.js:883:10)
>     at ClientRequest._flush (_http_outgoing.js:852:22)
>     at _http_client.js:323:47
>     at callSocketMethod (_http_client.js:818:7)
>     at ClientRequest.onSocket (_http_client.js:823:7)

It is probably due to the middleware fiori-tools-proxy. Is it possible that the error occurs because of the company proxy? The environment variables http_proxy, https_proxy and no_proxy are already set. 

Thanks and best regards

**Comment by quiggs1001** [comment]
@whitenrock can you please confirm that your proxy is correctly configured and accessible?  

Also, could you please detail how you created your project?  Was it using the Fiori elements Generator?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
