### ISSUE TITLE
Create an Empty SAPUI5 Project

### ISSUE THREAD

**Issue by vjvats** [SAPDocuments/Tutorials#5642]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-101-create-project.html

On Step 5 EXPOSE  & Open step its gives the message "WebSockets request was expected" in new browser tab. I am not sure if i did something wrong.

Thanks 
Vijay

**Comment by IObert** [comment]
Hi,

this could happen if you expose the "wrong" port. Please rerun the web app and make sure to expose a port that starts with 6 (like 6004 or 6006).

**Comment by IObert** [comment]
Close due to inactivity. Please reopen if the issue still persists.
