### ISSUE TITLE
Set Up a Basic Mock S/4HANA Service

### ISSUE THREAD

**Issue by MathiasEichel** [SAPDocuments/Tutorials#5645]
Tutorial URL: https://developers.sap.com/tutorials/cap-cloudsdk-1-mock-service.html

Please specify the step you are referring to:
Running service after installation is causing error because of '**_**' instead of '**.**' at service Entity reference':
actual: API_BUSINESS_PARTNER_A_BusinessPartnerAddressType 
to be: API_BUSINESS_PARTNER.A_BusinessPartnerAddressType
This error is coming in with latest node package "_id": "@sap/cds@4.1.5"  ..... is working with "_id": "@sap/cds@3.34.2"

Error: SQLITE_ERROR: no such table: API_BUSINESS_PARTNER_A_BusinessPartnerAddressType
    at Request.reject (/Users/mathiaseichel/workspace-cap/ws_bupa/node_modules/@sap/cds/lib/srv/core/Request.js:91:25)
    at SQLiteDatabase.onCREATE (/Users/mathiaseichel/workspace-cap/ws_bupa/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:154:11) {
  errno: 1,
  code: 'SQLITE_ERROR',
  query: 'INSERT INTO API_BUSINESS_PARTNER_A_BusinessPartnerAddressType ( BusinessPartner, AddressID, CityName, StreetName ) VALUES ( ?, ?, ?, ? )'
}

**Comment by qmacro** [comment]
Thanks for the detailed report, @MathiasEichel ! Sorry about the delay in replying. Will get onto this change now.

**Comment by MichaelCzcz** [comment]
@qmacro Any updates?

**Comment by MathiasEichel** [comment]
@MichaelCzcz,
it works fine with the node packages from the previous version. I attached it so you can move on with this example.
[@sap--node-module.zip](https://github.com/SAPDocuments/Tutorials/files/5283271/%40sap--node-module.zip)

**Comment by MichaelCzcz** [comment]
@MathiasEichel @qmacro Can I close this issue?

**Comment by MathiasEichel** [comment]
@MichaelCzcz
the main issue has not changed. Only the older version works as a workaround.

**Comment by qmacro** [comment]
Some tutorial migrations are planned, and the work is scheduled. We'll be able to update this issue once complete. Thanks for your patience.

**Comment by qmacro** [comment]
Hello @MichaelCzcz - sorry to be the bearer of more news about delays, but we are working on coming up with a more streamlined way we can produce and support tutorials, using appropriate experts. So while a migration is still planned, I'd like to close this issue as whatever we produce will not be along the same lines as the context of this issue (as the tools and tech have changed and improved) and we don't benefit from keeping it open. Hope that is acceptable for you. Thanks for your patience!

**Comment by MathiasEichel** [comment]
100% agree (Y)
