### ISSUE TITLE
The name of the CSV file should be my.bookshop-Authors.csv

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5648]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

**Step 7: Add initial data**

Here notice in the below screenshot
![image](https://user-images.githubusercontent.com/65999547/89786986-62c6c000-db3a-11ea-8815-fcbb42e8a717.png)

Here the text should be- "create a new folder csv with the file named my.bookshop-Authors.csv".

Please update csv/my.bookshop-Authors.csv to my.bookshop-Authors.csv in the highlighted text.

Best Regards,
Priyanka

**Comment by iwonahahn** [comment]
Thanks, this is fixed and will be published tomorrow.

**Comment by I537413** [comment]
Hi @iwonahahn,

Thanks for the reply. I am closing this Issue since its fixed.

Best Regards,
Priyanka
