### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Tutorials#5649]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

Please specify the step you are referring to

**Step 4**: Provision the capabilities 

In select capabilities page, after selecting desired capabilities & clicking on "Next" button it goes to Cloud Integration Page.

**In cloud Integration page, User has to click "Next" button & goto summary page inorder to activate.**

Please  add above step to document for the better understanding to end user.

Thanks
Mounika

**Comment by Vikramkulkarni01** [comment]
Hi Mounika, 

Thanks for responding back. 

Could you please share me the screenshots or the few seconds recording of those steps. 

This is something, we need to check from our end and adapt the changes accordingly. 

Appreciate your help. 

Regards, 
Vikram Kulkarni

**Comment by mounikat987** [comment]
Hi Vikram,

As discussed over call, please check & add the step for better end user understandability.

Thanks
Mounika

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by mounikat987** [comment]
Hi @Vikramkulkarni01 

This documentation feedback is not available in tutorial. I have retested now & couldn't find any comment/update in documentation.
Please look into it.

Thanks
Mounika

**Comment by Vikramkulkarni01** [comment]
Hi Mounika, 

This has been added in QA. However, this will be released along with the new updates.
