### ISSUE TITLE
Update the screenshot for the folder structure

### ISSUE THREAD

**Issue by I537413** [SAPDocuments/Tutorials#5651]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Step 4: Define your first service

Please update the screenshot for the folder structure, as at that point we would have done the npm install due to which node_modules folder will also be added in the structure as below:
![image](https://user-images.githubusercontent.com/65999547/89857951-0c4d9600-dbbb-11ea-8fec-2fc1f4fad010.png)

Best Regards,
Priyanka

**Comment by iwonahahn** [comment]
Thanks, this is fixed and will be published tomorrow.

**Comment by I537413** [comment]
Hi @iwonahahn,

Thanks for the reply. I am closing this Issue since its fixed.

Best Regards,
Priyanka
