### ISSUE TITLE
Screenshot broken in tutorial for SAP Business Application Studio

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5656]
Open https://developers.sap.com/tutorials/appstudio-devspace-fiori-create.html

Step 2-Create a preconfigured SAP Fiori dev space

Actual- Screenshot of Dev space is broken
![image](https://user-images.githubusercontent.com/7221229/89880511-f7d0c400-dbe1-11ea-955c-cfa79e62e821.png)

Expected- Screenshot should not be broken.

**Comment by raz-korn** [comment]
Hi @Mukesh-50 ,

The screenshot is intentionally broken.
The first time a dev space is created, the dev space manager screen is empty, and the screenshot conveys this message.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
