### ISSUE TITLE
Business Studio Homepage screenshot update required

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5657]
Open https://developers.sap.com/tutorials/appstudio-devspace-fiori-create.html

Step 3: Open the SAP Fiori dev space

Expected
![image](https://user-images.githubusercontent.com/7221229/89860437-12467580-dbc1-11ea-8ac4-0eda611722d3.png)

Actual
![image](https://user-images.githubusercontent.com/7221229/89860445-15d9fc80-dbc1-11ea-8d03-25a501b3e2a1.png)

**Comment by raz-korn** [comment]
Hi @Mukesh-50 ,

Thanks for bringing this to my attention.
I update the tutorial whenever there's a major change, i.e. a change that has high probability to create confusion.
This case seems to be of a minor change, and therefore, will be included in the next update.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
