### ISSUE TITLE
Build Output screenshot update for Business Application using CAP

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5658]
Open https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Step 7- Add initial data

Expected Result-
![image](https://user-images.githubusercontent.com/7221229/89860756-d364ef80-dbc1-11ea-9de7-bc2196998e53.png)

Actual Result-
![image](https://user-images.githubusercontent.com/7221229/89860765-d65fe000-dbc1-11ea-90b6-a119008f8f05.png)

**Comment by iwonahahn** [comment]
Thanks, this is fixed and will be published tomorrow.

**Comment by iwonahahn** [comment]
We can close this, changes were published today.
