### ISSUE TITLE
Subaccount Screenshot page should be updated for CAP for Node.js

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5659]
Open https://developers.sap.com/tutorials/cap-service-deploy.html

Step 2: Identify SAP Cloud Platform Cloud Foundry endpoint

Note- Kindly update the screenshot.

Expected
![image](https://user-images.githubusercontent.com/7221229/89861922-76b70400-dbc4-11ea-8db3-36189e79de0d.png)

Actual
![image](https://user-images.githubusercontent.com/7221229/89861931-7c144e80-dbc4-11ea-81bf-378410e5b408.png)

**Comment by iwonahahn** [comment]
The screenshot for "Expected" should be "Actual", right ;-)? I have updated the screenshots and it will be published tomorrow.

**Comment by iwonahahn** [comment]
We can close this, changes were published today.
