### ISSUE TITLE
Not getting approve or reject button after reload

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5663]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-action.html

Step 7: Subscribe to the card in SAP Mobile Cards

Here when we deploy the latest version of the card. Initially I could not see the approve or reject button even though the version of the card became 1.1(latest)

So I checked the next day (as per the tutorial it is stated that it takes some time to reflect the changes). 
But still I did not see the buttons. Only after I choose to un-subscribe and subscribe to the card again, did I see the buttons.

So please look into this.

Best Regards,
Priyanka

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
