### ISSUE TITLE
Create an SAP Cloud Platform ABAP Environment Trial User

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5664]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html

Please specify the step you are referring to : Step 5: Create ABAP cloud project     
6. Didn’t get login option and logged in automatically.
Expected : 
![image](https://user-images.githubusercontent.com/50734023/89864707-09a66d00-dbca-11ea-9c02-9b6307911c51.png)

Actual:
![image](https://user-images.githubusercontent.com/50734023/89864755-22af1e00-dbca-11ea-8868-677597b09d2e.png)

Regards,
Nidhi

**Comment by mervey45** [comment]
Hi @NidhiMurkute ,

this has been updated. @thecodester I created following pull request: #5702, can you merge it?

Thank you. 

Best regards, 
Merve
