### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5666]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Please specify the step you are referring to : Step 5 - Create HTML module
8. Change the screenshot for template in webide

Expected : 
![image](https://user-images.githubusercontent.com/50734023/89865192-e4fec500-dbca-11ea-9afc-d017beff4fe2.png)

Actual:
![image](https://user-images.githubusercontent.com/50734023/89865237-f8119500-dbca-11ea-9c54-634ab87eb8a6.png)

Regards,
Nidhi

**Comment by mervey45** [comment]
Hi @NidhiMurkute ,

this has been updated. @thecodester  we can close this issue.

Best regards,
Merve
