### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5668]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Please specify the step you are referring to : Step 10: Create SAP Fiori launchpad site module
Add step to SAVE the changes made before deploying to CF. Because it is observed that the while deploying it didn't save the changes, so it is required to add step to save the changes made.

Regards,
Nidhi

**Comment by mervey45** [comment]
Hi @NidhiMurkute ,

this has been updated. @thecodester  we can close this issue.

Best regards,
Merve
