### ISSUE TITLE
Set Up Business Rules for Determining Equipment

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5671]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-businessrules.html

Please specify the step you are referring to : Step 2: Import business rules     
3. Change of screenshot
Expected Date format (MM/DD/YYYY):
![image](https://user-images.githubusercontent.com/50734023/89866225-d0bbc780-dbcc-11ea-83e3-bf23e06ec665.png)

Actual Date format (DD/MM/YYYY) and the **filter** icon is present
![image](https://user-images.githubusercontent.com/50734023/89866374-0791dd80-dbcd-11ea-90bd-a19f9e526454.png)

Also the same issue is observed in 
Step 3: Deploy business rules     
3.Change of screenshot for **Filter** icon and date format

Regards,
Nidhi

**Comment by ArchanaShukla** [comment]
I do not see this change in trial and neither in my Canary or Factory accounts. See the image below. 
<img width="1427" alt="Screenshot 2020-08-18 at 4 39 08 PM" src="https://user-images.githubusercontent.com/34297037/90506109-5e6d5900-e171-11ea-8403-621eeb628104.png">

**Comment by NidhiMurkute** [comment]
When I executed the actual result had **Filter** icon and this format(DD/MM/YYYY) as you can see in screenshot. Not sure why there is change in date format. Also for Filter icon, needs to change tutorial screenshot as the screenshot doesn't have filter icon.

**Comment by MichaelCzcz** [comment]
@ArchanaShukla Do you want to comment on the last reply or shall I close the issue anyway?

**Comment by ArchanaShukla** [comment]
Please close this issue. I do not see any date format issue. @NidhiMurkute - you can setup a call with me and I can explain.
