### ISSUE TITLE
Set Up a Workflow With Extended Employee Onboarding

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5672]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html

Please specify the step you are referring to : Step 2: Import sample application     
Change of screenshot
Expected:
![image](https://user-images.githubusercontent.com/50734023/89867531-f0ec8600-dbce-11ea-8676-4a891d21b687.png)

Actual:
![image](https://user-images.githubusercontent.com/50734023/89867578-ff3aa200-dbce-11ea-8494-493ca78999ba.png)

Regards,
Nidhi

**Comment by ArchanaShukla** [comment]
All the screenshots are now updated to Business Application Studio so this comment stands invalid.

@thecodester - please close the issue
