### ISSUE TITLE
Create an SAP Cloud Platform ABAP Environment Trial User

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#5679]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html

Step 1.4 the screenshot has to be updated.

Expected :
![image](https://user-images.githubusercontent.com/69286515/89875985-9d346980-dbdb-11ea-907d-5f25dcebc414.png)

Actual:
![image](https://user-images.githubusercontent.com/69286515/89876480-55faa880-dbdc-11ea-8e42-6832da73d6b0.png)

**Comment by mervey45** [comment]
Hi @NidhiMurkute ,

this has been updated. @thecodester  we can close this issue.

Best regards,
Merve
