### ISSUE TITLE
Create Table Persistence and Generate Data

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#5680]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-persistence.html

Step 3.6 Just a suggestion if you could guide the user to the database table where it is present then it will make the step more understandable.

**Comment by mervey45** [comment]
Hi @NidhiMurkute ,

this has been updated. @thecodester I created following pull request: #5702, can you merge it?

Thank you. 

Best regards, 
Merve
