### ISSUE TITLE
Add an SAPUI5 App to Your Portal Site

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#5681]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-new-sapui5.html

Step 2.1 Its an observation
After creating the portal site as given in tutorial 2, when we  open content manager as per the step 2.1 in tutorial 3. The content manger might appear empty at first so for that we can refresh the browser for the content to appear in the content manger. We can add this as a note if in case there is no content in content manager.

**Comment by LindsayBert** [comment]
Hi

Ok will check this out and update by the end of the month.

Thanks Lindsay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
