### ISSUE TITLE
Add an SAPUI5 App to Your Portal Site

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#5682]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-new-sapui5.html

Step 4.4  Observation:

In the step its mentioned to 'click the + icon'  but there is no such icon in the screenshot. The screenshot that is attached is after selecting the app. Either the screenshot has to be updated or the sentence.

Expected:
![image](https://user-images.githubusercontent.com/69286515/89883655-10db7400-dbe6-11ea-9058-86cb20023a31.png)

Actual:
![image](https://user-images.githubusercontent.com/69286515/89883840-58620000-dbe6-11ea-8db2-091e8a3c43bf.png)

**Comment by LindsayBert** [comment]
Hi 

Thanks for your feedback. We will be updating the tutorials by the end of the month.  Thanks for your feedback.

Thanks
Lindsay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
