### ISSUE TITLE
Create an SAP Cloud Platform ABAP Environment Trial User

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#5683]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html

Step 4: We don't get the option in windows taskbar as mentioned in the screenshot for ABAP in Eclipse - CAA361.

**Comment by mervey45** [comment]
Hi @AkankshaKullu ,

this option is for TechEd only. It is also described in the step.
@thecodester  we can close this issue.

Best regards, 
Merve

**Comment by thecodester** [comment]
@mervey45 If it's only for TechEd, maybe we should remove?

**Comment by mervey45** [comment]
Hi @thecodester ,

this tutorial is for teched, trial and licensed systems. But step 4 is only for TechEd.
I will remove this

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

we can close this ticket.

Best regards, 
Merve
