### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by lucianalml** [SAPDocuments/Tutorials#5684]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

Please specify the step you are referring to

Error in step 1, item 3: 
command-> npm add @sap/hana-client --save

Fix: set node version to 12 (it was 14 before)

Error in step 3, item 2:

Fix 1: Check the command-specific for the operational system (https://cap.cloud.sap/docs/advanced/deploy-to-cloud#deploy-using-cf-push)

Fix 2: Change both manifest.yml files 
services -> from my-bookshop-db to my-bookshop-db-hdi-container

**Comment by iwonahahn** [comment]
Sorry for the late reply, I was on vacation for a long time. Could you please try it again with the latest version @sap/cd-dk: 2.0.8? We also have updated the deploy part in the tutorial. Let me know if it works now also for you. Regarding the node version, please see the note for step 1.3 with the link to the [troubleshooting guide](https://cap.cloud.sap/docs/advanced/troubleshooting#npm-installation) where we recommend Node.js version 10 or 12.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
