### ISSUE TITLE
Manifest.yml not getting updated with services name for US region

### ISSUE THREAD

**Issue by Mukesh-50** [SAPDocuments/Tutorials#5686]
Open https://developers.sap.com/tutorials/cap-service-deploy.html

Step 3- Deploy using cf push

Execute below command
SET CDS_ENV=production && cds build 
cf push -f gen/db

API endpoint - https://api.cf.us10.hana.ondemand.com

Note- We need to do a workaround in order to execute this scenario. We need to modify Manifest.yml  and manually we need to update my-bookshop-db service name to my-bookshop-db-hdi-container

Actual
![image](https://user-images.githubusercontent.com/7221229/89941433-a56ec200-dc38-11ea-935d-075522d0dcfc.png)

Expected
The application should get pushed

**Comment by iwonahahn** [comment]
Sorry for the late reply, I was on vacation for a long time. Could you please try it again with the latest version @sap/cd-dk: 2.0.8? We also have updated the deploy part in the tutorial. Let me know if it works now also for US region.

**Comment by NidhiMurkute** [comment]
I have verified the above issue in US region and it works as expected.
