### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#5688]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
Step 1.1

We don't get the option 'Build with Cloud MTA Build Tool'. The screenshot has to be updated.

Expected: 
![image](https://user-images.githubusercontent.com/69286515/90002754-b5c28380-dcb0-11ea-8548-d3dcaef626eb.png)

Actual:
<img width="346" alt="12" src="https://user-images.githubusercontent.com/69286515/90003551-de974880-dcb1-11ea-8d23-784f5107bda6.png">

**Comment by mervey45** [comment]
Hi @AkankshaKullu ,

this has been updated. @thecodester we can close this issue.

Best regards,
Merve
