### ISSUE TITLE
Feedback on Tutorial: SAPUI5 - Add a search field

### ISSUE THREAD

**Issue by langerschris** [SAPDocuments/Tutorials#569]
Hi

i really like your tutorial.

Is it possible that there is a mistake in 'add a search field'? (https://go.sap.com/developer/tutorials/sapui5-webide-add-search-field.html)

Your id-attribut is 'List' with a capital but in your controller code line25 you wrote 'byId("list")' all small.

kind regards
Chris

**Comment by jonathanbaker7** [comment]
Fixed.  Thanks for the report!
