### ISSUE TITLE
Open SAP Web IDE Full-Stack

### ISSUE THREAD

**Issue by i861874** [SAPDocuments/Tutorials#5691]
Tutorial URL: https://developers.sap.com/tutorials/webide-multi-cloud.html

Step 1: This refers to the "SAP Web IDE", however this has been replaced by "SAP Business Application Studio". This affects the following step, also.

**Comment by IObert** [comment]
Thanks for reporting the issue. I updated the tutorial according to the latest changes, they should be live within the next 15-20 minutes.
