### ISSUE TITLE
Add Routing to a UI5 Web Components for React Project

### ISSUE THREAD

**Issue by shubhamui5** [SAPDocuments/Tutorials#5693]
Tutorial URL: https://developers.sap.com/tutorials/ui5-webcomponents-react-routing.html

In Step 3, point 2  in the code snippet for MyApp.jsx few details are missing:

1. Import of Avatar
2. Declaration of logo is wrong
`  logo={"reactLogo.png"}` will not work.
     We have to write `logo={<img src="reactLogo.png" />}`

**Comment by Lukas742** [comment]
Hi @shubhamui5 

thanks for noticing. The API of the `ui5-webcomponents-react` has changed in the latest version and I must have missed to also update this snippet. 
I've created a PR that will solve this issue: https://github.com/SAPDocuments/Tutorials/pull/5711

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
