### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by yawkcubevad** [SAPDocuments/Tutorials#5694]
Tutorial URL: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html

Please specify the step you are referring to

Step 6: Create database artifacts
I'm unable to advance beyond the build of the database.

11:17:37 AM (git) Project hana-cf-get-started-trial: Git repository hana-cf-get-started-trial: Clone request completed successfully.
11:18:23 AM (Executor) The "task for hdb build" process started.
11:18:23 AM (Executor) Started the "task for hdb build" provision.
11:18:26 AM (Provision) Service provisioning for module: "/db"
11:18:26 AM (Provision) Service instance 'my-hdi' for resource 'my-hdi' already exists, no operation will be performed.
11:18:29 AM (Executor) Starting process: "cd /projects/hana-cf-get-started-trial/db; export DEVX_MTA_RESOLVED_PLACEHOLDERS="{\"services\":[{\"platformName\":\"my-hdi\",\"resourceName\":\"hdi_db\",\"resourceProperties\":{},\"resourceType\":\"com.sap.xs.hdi-container\",\"serviceKeyName\":\"SharedDevKey\",\"serviceTarget\":{\"endpoint\":\"https://api.cf.us10.hana.ondemand.com\",\"org\":\"18acfc61trial\",\"space\":\"dev\"}}]}"; export CF_HOME=/projects/.webide/cf/f199dfcb4782bfa746c1215befad6a55; export DEVX_MTA_HDI_BUILD_OPTIONS="{\"IsSelectiveBuild\":false,\"SelectedFiles\":[],\"IsSimulateBuild\":false,\"AdditionalOptions\":{\"migrationtable-development-mode\":true}}"; export PROJECT_PATH=/projects/hana-cf-get-started-trial/db; mkdir -p $CF_HOME/.cf/plugins/ && cp -u $CF_PLUGIN_PATH/config.json $CF_HOME/.cf/plugins/config.json 2>/dev/null || :;hdi-space-builder build -f /usr/local/resources/hdi-space-builder/manifest.yaml"
11:18:29 AM (HDB) Executing Build command:
11:18:29 AM (HDB)  HDI BUILDER VERSION:1.1.8-20200610150748
11:18:29 AM (HDB) temp folder created at: /tmp/hdispacebuilder430270593
11:18:29 AM (HDB) Starting pre-hdiBuild operations...
11:18:32 AM (HDB) Creating module zip...
11:18:32 AM (HDB) module directory is: /projects/hana-cf-get-started-trial/db
11:18:32 AM (HDB) executing NPM script at: /projects/hana-cf-get-started-trial/db
11:18:32 AM (HDB) zipping folder..... 
11:18:32 AM (HDB) zip created at: /tmp/hdispacebuilder430270593/db.zip
11:18:35 AM (HDB) connection to hdi deployer passed
11:18:35 AM (HDB) No protocol version provided, using the latest version: 1.0.0
11:18:35 AM (HDB) Log id: b370bfd6864e9c3d36cb1691c4d80b7d21483774
11:18:35 AM (HDB) Using protocol version 1.0.0
11:18:35 AM (HDB) FILE TRANSFER READY
11:18:35 AM (HDB) File transfer completed successfully: Checksums match.
11:18:35 AM (HDB) Requested version of @sap/hdi-deploy is ^3.11, found in package.json.
11:18:35 AM (HDB) WARNING: db module specified version "^3.11". Best match found was version "3.11.10".
11:18:35 AM (HDB) package.json,src
11:18:35 AM (HDB) @sap/hdi-deploy, version 3.11.10 (mode default), server version unknown (0.0.0.0), node version 8.12.0, HDI version -1, container API version -1
11:18:35 AM (HDB) Detection of server version failed; root cause: Connection failed (RTE:[89008] Socket closed by peer (0968be02-a42a-4652-b8c2-8623558b6b97.hana.trial-us10.hanacloud.ondemand.com:443))Detection of container API version failed; root cause: Connection failed (RTE:[89008] Socket closed by peer (0968be02-a42a-4652-b8c2-8623558b6b97.hana.trial-us10.hanacloud.ondemand.com:443))Detection of HDI version failed; root cause: Connection failed (RTE:[89008] Socket closed by peer (0968be02-a42a-4652-b8c2-8623558b6b97.hana.trial-us10.hanacloud.ondemand.com:443))
11:18:35 AM (HDB) The server does not support live updating of make messages. The messages will be displayed, when the make is done.
11:18:35 AM (HDB) No ignore file at /tmp/hdi-space-deploy-43r2agRW4NHqdF-content/.hdiignore.
11:18:35 AM (HDB) Collecting files...
11:18:35 AM (HDB) Collecting files... ok (0s 3ms)
11:18:35 AM (HDB) 1 directories collected2 files collected0 reusable modules collectedTarget service: my-hdi
11:18:35 AM (HDB) Could not check if session variable APPLICATION is set correctly: Connection failed (RTE:[89008] Socket closed by peer (0968be02-a42a-4652-b8c2-8623558b6b97.hana.trial-us10.hanacloud.ondemand.com:443))
11:18:35 AM (HDB) Could not determine status of last build: Connection failed (RTE:[89008] Socket closed by peer (0968be02-a42a-4652-b8c2-8623558b6b97.hana.trial-us10.hanacloud.ondemand.com:443))
11:18:35 AM (HDB) Processing revoke files...
11:18:35 AM (HDB) Processing revoke files... ok (0s 0ms)
11:18:35 AM (HDB) Processing grants files...
11:18:35 AM (HDB) Processing grants files... ok (0s 0ms)
11:18:35 AM (HDB) Preprocessing files...
11:18:35 AM (HDB) Preprocessing files... ok (0s 0ms)
11:18:35 AM (HDB) Connecting to the container "DB_1"...
11:18:35 AM (HDB) Deployment to container DB_1 failed - error: Connection failed (RTE:[89008] Socket closed by peer (0968be02-a42a-4652-b8c2-8623558b6b97.hana.trial-us10.hanacloud.ondemand.com:443)) [depId].
11:18:35 AM (HDB) Error: Connection failed (RTE:[89008] Socket closed by peer (0968be02-a42a-4652-b8c2-8623558b6b97.hana.trial-us10.hanacloud.ondemand.com:443))
11:18:35 AM (HDB) (0s 141ms)
11:18:35 AM (HDB) Deployment failed with exit code: 1
11:18:35 AM (HDB) STRUCTURED LOG CHECKSUM 17fe9e97ae5cb120cc1e6f40c577345fbf7a2f6782034e6b9d947bc778ff04bb
11:18:35 AM (HDB) STRUCTURED LOG SIZE690
11:18:35 AM (HDB) SENDING STRUCTURED LOG
11:18:35 AM (HDB) Ended because of error: Deployment failed with exit code: 1
11:18:35 AM (HDB) Build command failed : hdi-build operation failed: Deployment failed with exit code: 1
11:18:35 AM (HDB) Build of /hana-cf-get-started-trial/db failed due to The "task for hdb build" process finished with code 1.

**Comment by jung-thomas** [comment]
The error message says its unable to communicate with your HANA system:
Connection failed (RTE:[89008] Socket closed by peer (0968be02-a42a-4652-b8c2-8623558b6b97.hana.trial-us10.hanacloud.ondemand.com:443))

Are you sure your HANA instance is running?  Remember the HANA Trial shuts down every night and has to be manually restarted each day.

**Comment by yawkcubevad** [comment]
Stupid user error.  I'm still trying to get used to the HANA Cloud Trial.  Thanks.
