### ISSUE TITLE
SAP HANA XS Advanced, Creating a Simple OData Service

### ISSUE THREAD

**Issue by ahmedkhan29789** [SAPDocuments/Tutorials#5695]
Tutorial URL: https://developers.sap.com/tutorials/xsa-xsodata.html

I have tried the same but end up getting "500 Invalid HANA settings provided. OData services are disabled."
None of the google support helped me, My hana version is HANA 2.0 SPS04

![image](https://user-images.githubusercontent.com/22063881/90315137-a72ed300-df21-11ea-81fb-e435dd6b4fb1.png)

My MTA files look like
![image](https://user-images.githubusercontent.com/22063881/90315162-dfceac80-df21-11ea-8a5b-1ac35914993d.png)

My xsodata code is
service  { 

"XSODATA_TEST_1"."TestXSoData.db::COPA.PT_COPA" as "COPA";     
}

**Comment by jung-thomas** [comment]
The source code you supplied here doesn't have to do with this tutorial.  For general questions please post to the SAP Community Q&A.  This area is only for questions directly related to the content of the tutorials themselves.  I will tell you, however, that your XSODATA definition is not correct. You have a schema reference in there which is not allowed in XSA/HDI. Other than that I can't help you much here as you are clearly not following this particular tutorial. Again I would suggest that you post this question instead to the SAP Community Q&A.

**Comment by ahmedkhan29789** [comment]
Thanks @jung-thomas , Although removing schema reference also gave same error of "500 Invalid HANA settings provided. OData services are disabled."

**### I have posted this question on SCN[https://answers.sap.com/questions/13115428/500-invalid-hana-settings-provided-odata-services.html]**

The problem with XSA is that very few people have blogs and answers of the problems, And i learned creating XSODATA from your blog only so thought to ask it here first, Sorry for the confusion.
