### ISSUE TITLE
Create an SAPUI5 App from the Command Line

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#5697]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-sapui5-local.html

Please specify the step you are referring to

Step:4 

When I enter -> npm run build:mta 

I get the following errors.

Error: could not build the MTA project: could not execute the "make -f Makefile_20200816185652.mta p=cf mtar= strict=true mode=" command: exec: "make": executable file not found in %PATH%
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myUI5App@0.0.1 build:mta: `mbt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myUI5App@0.0.1 build:mta script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I tried in the VS code terminal as well as the command line. 

Please assist.

Kind Regards
Phil Cooley

**Comment by IObert** [comment]
Hi,

it seems like you don't have `make` installed on your machine. Please follow [this guide](https://chocolatey.org/packages/make) to install the tool and then try again.

**Comment by pjcools** [comment]
Hi Marius

Yep, you are right!! I installed and it worked.

thanks!
Phil
