### ISSUE TITLE
Use SAP HANA as the Database for a CAP Java Application

### ISSUE THREAD

**Issue by locoalien** [SAPDocuments/Tutorials#5704]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-hana-db.html

I have problems establishing the connection with the HANA database. when performing the "cds deploy --to hana: bookstore-hana" it shows the following error message:
<img width="1107" alt="error1" src="https://user-images.githubusercontent.com/1004466/90352028-acfee400-e007-11ea-80d9-42b25d00e0a5.png">

When I try to compile, I also get the same error referring to the JDBC connection: 
<img width="550" alt="erro2" src="https://user-images.githubusercontent.com/1004466/90352097-e6375400-e007-11ea-87de-dfb4f0888353.png">
<img width="1110" alt="erro3" src="https://user-images.githubusercontent.com/1004466/90352140-11ba3e80-e008-11ea-8f8e-f5c89c752c29.png">

I have checked if port 443 is wrong:
<img width="1136" alt="erro4" src="https://user-images.githubusercontent.com/1004466/90352216-3e6e5600-e008-11ea-82af-fe807f546812.png">
but I get the same error, changing the port for the one in the image. This recommendation comes from the SAP note https://launchpad.support.sap.com/#/notes/0002501339 without success.

additionally in the configuration of the HANA instance in SAP Cloud Foundry, the configuration must be correct for port 443.
<img width="1362" alt="erro6" src="https://user-images.githubusercontent.com/1004466/90352308-9311d100-e008-11ea-93ed-5a12f8349a36.png">
If anyone has any idea how to fix the problem, I really appreciate it.

**Comment by maxstreifeneder** [comment]
Hey @locoalien this issue system is for problems with tutorial content itself - I'd definitely recommend you use the SAP Community Q&A (answers.sap.com) to ask about this. Sorry and good luck!

**Comment by locoalien** [comment]
> Hey @locoalien this issue system is for problems with tutorial content itself - I'd definitely recommend you use the SAP Community Q&A (answers.sap.com) to ask about this. Sorry and good luck!

Hi @maxstreifeneder
thanks for your answer. I have asked the same question in the sap community, but I have no answer on the solution. I will keep looking for how to fix it.
[](https://answers.sap.com/questions/13112978/cap-cds-deploy-to-hana-hdi-deployment-failed.html)

Thank you very much. 👍

**Comment by kshanth** [comment]
Same issue observed from yesterday.. it was working before.

**Comment by maxstreifeneder** [comment]
@kshanth @locoalien let's continue the discussion over there. Have already replied with 2 possible solutions.
