### ISSUE TITLE
Deploy Your Business Application to Cloud Foundry

### ISSUE THREAD

**Issue by simenlf** [SAPDocuments/Tutorials#5707]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-cap-deploy-app.html

Please specify the step you are referring to 2.3

Hey I don't get any options to connect to any books database. If i choose one of the two I have nothing more happens :/

Apart from that: great stuff

**Comment by liatbor** [comment]
Hi,
The books database is just a HaaS db that we created with that name. In this step you should select any Hana db instance ( Haas or other) you want to bind to, and to use in your application. Then the binding process should start. Can you state if after choosing the instance you were able to bound to it or not?

Thanks,
Liat

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
