### ISSUE TITLE
Secure Your Application on SAP Cloud Platform Cloud Foundry

### ISSUE THREAD

**Issue by prakash13t** [SAPDocuments/Tutorials#5708]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-secure-cloudfoundry.html

Please specify the step you are referring to Step-3

I think this tutorial is outdated, could you please update the tutorial based on SAP Cloud SDK Spring

**Comment by MatKuhr** [comment]
Let's close this and discuss on the original question on https://answers.sap.com/questions/13120133/security-to-cloud-sdk-java-application.html
