### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by MatthiasSchmalz** [SAPDocuments/Tutorials#5709]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

Please specify the step you are referring to
Step 2: Select application template
Unfortunately there are no generators listed. VSCode shows: Could not find any generators. It looks like something is missing.
There is a button Explore and Install Generators, but this returns a long list of unrelated content.

**Comment by cjbernal** [comment]
Hi Matthias,

Sorry you're having an issue. Please take a look at FAQ #2 here and see if that eliminates the issue: https://help.sap.com/viewer/42532dbd1ebb434a80506113970f96e9/Latest/en-US

Kind regards,
Conrad

**Comment by MatthiasSchmalz** [comment]
Thank you that helped. Is that FAQ linked from the tutorial somewhere?

**Comment by MatthiasSchmalz** [comment]
I'd like to mention that the name of the wizard seems to have changed and the guide is not up to data. The only wizard I see is "SAP Fiori elements application". According to the description it seems to be the same.

**Comment by cjbernal** [comment]
Hi Matthias,

Thanks for taking the time to mention that -- we appreciate people keeping their eyes open for things like that :-) We're currently in the process of updating the guide based on user feedback. We'll take that into consideration as well. 

Kind regards,
Conrad

**Comment by cjbernal** [comment]
Sorry, I missed your initial question. No, it was something that cropped up later, hence the mentioned update!

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
