### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by AnuragSahana** [SAPDocuments/Tutorials#5710]
Tutorial URL: https://developers.sap.com/tutorials/xsa-create-user-provided-anonymous-service.html

Please specify the step you are referring to: I am referring to STEP 8 where we add a CDS code to our db module and save and build it.

When I add the CDS code, save and build the db module, the build fails. Could you please help?

![image](https://user-images.githubusercontent.com/23170851/90475188-9dd18080-e144-11ea-9d3b-f29f633031e3.png)

![image](https://user-images.githubusercontent.com/23170851/90475206-ab870600-e144-11ea-9b82-93d0907817b7.png)

**Comment by AnuragSahana** [comment]
I had missed to add this to the original issue description.

![image](https://user-images.githubusercontent.com/23170851/90475838-ed647c00-e145-11ea-8868-882a449f3e2c.png)

**Comment by thecodester** [comment]
@Who is the owner for this tutorial? I can update the author name

**Comment by jung-thomas** [comment]
@thecodester  I'm the maintainer of this tutorial now.

@AnuragSahana  - this error is telling you that the port and therefore the HANA DB tenant that you chose when you created the user provided service doesn't match the space/HANA DB tenant that you are deploying you DB container into.  That is why the grantor doesn't find your container technical user name. Everything must target the same database tenant.
