### ISSUE TITLE
Prepare SAP Web IDE for Cloud Foundry Development

### ISSUE THREAD

**Issue by Ichirusaki** [SAPDocuments/Tutorials#5712]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-webide-open-webide.html

Step 1

The button "Launch SAP Web IDE" is no longer here.

<img width="402" alt="04 - Han quitado el boton para entrar a web ide" src="https://user-images.githubusercontent.com/9393077/90498156-3fa69c80-e148-11ea-9d44-4ad1f71d261d.png">

Since Neo trial accounts will be deleted on November, how do we go now to this service from the Cloud Foundry environment?

**Comment by thecodester** [comment]
@anzeiger  This tutorial is only used for your IoT mission. Will you be upgrading your mission to use SAP Business Application Studio and then we can delete this tutorial?

@Ichirusaki For what task/mission are you using this tutorial for?

**Comment by Ichirusaki** [comment]
@thecodester I was searching how to access SAP Web IDE with cloud foundry environment and ended up on this tutorial.
Since the tutorial talked about preparing the web IDE for cloud foundry development I thought it will be useful for my problem.

Can I assume that Web IDE is only accesible on the Neo environment and that in cloud foundry I have to use SAP Business Application Studio?

**Comment by thecodester** [comment]
SAP Web IDE is available, but really only for SAP HANA scenarios. You can access SAP Web IDE by a link further down the page or by the info in this tutorial. https://developers.sap.com/tutorials/webide-multi-cloud.html

All other scenarios are to use SAP Business Application Studio.

**Comment by Ichirusaki** [comment]
Thank you so much for all the info.

I'll close the Issue now.

**Comment by anzeiger** [comment]
> @anzeiger This tutorial is only used for your IoT mission. Will you be upgrading your mission to use SAP Business Application Studio and then we can delete this tutorial?
> 
> @Ichirusaki For what task/mission are you using this tutorial for?

@thecodester SAP IoT organization has developed several plugins for SAP Web IDE and I am not sure if they are compatible with SAP Business Application Studio.  As a result, I believe we still need to use SAP Web IDE for our tutorials.  I have a queston: Is the tutorial https://developers.sap.com/tutorials/sapui5-webide-open-webide.html obsolete? I believe it still has some information that is useful to customers such as instructions on how to configure the Cloud Foundry setting in SAP Web IDE.  If it is going to be deleted, should we replace it with the tutorial https://developers.sap.com/tutorials/webide-multi-cloud.html?
