### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by whofarted1904** [SAPDocuments/Tutorials#5714]
Tutorial URL: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html

Step 6: Can't make a build:

5:22:58 PM (Executor) The "task for hdb build" process started.
5:22:58 PM (Executor) Started the "task for hdb build" provision.
5:23:01 PM (Provision) Service provisioning for module: "/db"
5:23:01 PM (Provision) Could not create the 'my-hdi' instance of the 'hana' service type for the 'hdi_db' resource. No hdi-shared plan available found in this space.
5:23:01 PM (Provision) Provision fail since one of the provision tasks finished with error.
5:23:01 PM (Executor) The "task for hdb build" provision finished with an error: Provision failed. See console for more details.
5:23:01 PM (HDB) Build of /hana-cf-get-started-trial/db failed due to Provision failed. See console for more details..

**Comment by jung-thomas** [comment]
>No hdi-shared plan available found in this space.

That the key error message here.  It says that hdi-shared isn't available in your space.  So did you configure the workspace in the IDE to point to your trial space as described in Step 4. And also did you configure the entitlements as described in Step 3 and the linked help documentation: https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/5ba357b4fa1e4de4b9fcc4ae771609da.html

For this error you are either not pointing to the Trial space in your project or you don't have the correct entitlement configured in that space.

**Comment by jung-thomas** [comment]
Make sure your entitlements contain both SAP HANA Cloud and SAP HANA Schemas & HDI Containers
![image](https://user-images.githubusercontent.com/12159356/90544816-ada59080-e155-11ea-89ed-1300c1b5df04.png)

**Comment by jung-thomas** [comment]
I've added a step to the tutorial to ask people to double check their entitlement configuration at this point. Hopefully that helps clarify.  If this wasn't the core of your issue or you have follow up question, please re-open the issue.

**Comment by whofarted1904** [comment]
Thanks for help!
