### ISSUE TITLE
Set Up SAP Business Application Studio for CAP Java

### ISSUE THREAD

**Issue by PhuongAnhMannheim** [SAPDocuments/Tutorials#5715]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-app-studio.html

Please specify the step you are referring to
Step 4: Compile model. 
(terminal) mvn clean install -> results in an Error: 
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:npm (cds build) on project products-service: Failed to run task: 'npm run build --https-proxy=http://127.0.0.1:8887 --proxy=http://127.0.0.1:8887' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :products-service

**Comment by maxstreifeneder** [comment]
HI @PhuongAnhMannheim,

could you please provide the complete log in the console of your executed command? 

Thanks in advance, 
Max

**Comment by jung-thomas** [comment]
It has been 23 days since the request for the complete log. No response so we are closing the issue. If you are still having problems and can provide more troubleshooting information, feel free to reopen.
