### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by Faaiez** [SAPDocuments/Tutorials#5716]
Tutorial URL: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html

Step 6 - Build fails

The "task for hdb build" provision finished with an error.

19:06:23 (Provision) Service provisioning for module: "/db"
19:06:23 (Provision) Could not create the 'my-hdi' instance of the 'hana' service type for the 'hdi_db' resource. No hdi-shared plan available found in this space.
19:06:23 (Provision) Provision fail since one of the provision tasks finished with error.
19:06:23 (Executor) The "task for hdb build" provision finished with an error: Provision failed. See console for more details.
19:06:23 (HDB) Build of /hana-cf-get-started-trial/db failed due to Provision failed. See console for more details..

Any idea why this would be?

**Comment by jung-thomas** [comment]
This error says that you have no hdi-shared plan in you space. So either you are not pointing to your Trial space or during the setup step (step 3) you didn't set the correct entitlements.   In the end make sure your entitlements contains contains both SAP HANA Cloud and SAP HANA Schemas & HDI Containers:
![image](https://user-images.githubusercontent.com/12159356/90544677-7b942e80-e155-11ea-8ae2-54d00e9e39e4.png)

**Comment by jung-thomas** [comment]
I've added a step to the tutorial to ask people to double check their entitlement configuration at this point. Hopefully that helps clarify.  If this wasn't the core of your issue or you have follow up question, please re-open the issue.
