### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by BerndReimann** [SAPDocuments/Tutorials#5717]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

- cf create-service hanatrial hdi-shared **my-bookshop-db-hdi-container** ... does not work since the app is looking for service  “**my-bookshop-db**”

- **SET CDS_ENV=production && cds build** .. does not work on MacOS / Linux

**Comment by iwonahahn** [comment]
Hi Bernd,

For the first point: I will get back to you asap, need to test it myself.

For the second point: Did you saw that it is possible to display the code blocks also for macOS / Linux? The commands for the operating systems are shown using different tabs. Please refer to this issue [#5233 (comment)](https://github.com/SAPDocuments/Tutorials/issues/5233#issuecomment-640557562). Does this help you?

Best regards,
Iwona

**Comment by BerndReimann** [comment]
> For the second point: Did you saw that it is possible to display the code blocks also for macOS / Linux?
Hi Iwona, no, I did not notice that. Thank you.

**Comment by iwonahahn** [comment]
For your first point:
Correct for step 3.1 is `cf create-service hanatrial hdi-shared my-bookshop-db`. This has changed with the new `@sap/cd-dk: 2.0.8` release. I have fixed it in the tutorial and will be published today.

**Comment by iwonahahn** [comment]
Changes were published today. Can we close the issue?
