### ISSUE TITLE
Create an ABAP Project in ABAP Development Tools (ADT)

### ISSUE THREAD

**Issue by whofarted1904** [SAPDocuments/Tutorials#5719]
Tutorial URL: https://developers.sap.com/tutorials/abap-create-project.html

Hi! I'm using Eclipse for MacOS, ABAP Development Tools is already installed. I'm trying to create a project, but I can't find H75 System Connection in the list, as described in the tutorial.
![step4-system-connection](https://user-images.githubusercontent.com/45553938/90637823-2891a880-e235-11ea-9d5c-7b81863b649d.png)
Wich one to choose? Or maybe I can choose another system connection instead?
The tutorial doesn't explains what is system connection at all.

**Comment by whofarted1904** [comment]
<img width="977" alt="Screen Shot 2020-08-19 at 16 15 27" src="https://user-images.githubusercontent.com/45553938/90639366-3c3e0e80-e237-11ea-8bc5-24f98bbbc94f.png">
I'm trying to define a new system connection, but I got logon error. This tutorial doesn't explains nothing about logon credentials. I'm trying to use my SAP Learning Portal credentials, am I right?

**Comment by julieplummer20** [comment]
Hi,
I inherited this tutorial. I will change the screenshot - it only provides examples. You need to choose an existing on-premise ABAP 7.xx system connection. If you have already configured system connections in SAP GUI for Java, then these should appear. If not, please let me know, and I'll provide screenshots from my own ADT instance.

BR Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
