### ISSUE TITLE
Feedback on Tutorial: Build an app from an SAP Web IDE template

### ISSUE THREAD

**Issue by garganuj14** [SAPDocuments/Tutorials#572]
Hi 
I am trying to register to sap .I registered with my facebook account but when I try to link a new sap cloud account then i am getting an error message.

**Comment by akula86** [comment]
Please follow the procedure in the tutorial below to create a new HCP Trial account. You will need to register with a valid email account (work or personal), then the registration process will work properly.

http://go.sap.com/developer/tutorials/hcp-create-trial-account.html
