### ISSUE TITLE
SAP HANA, XS Advanced - Access an external HTTP service

### ISSUE THREAD

**Issue by znishan** [SAPDocuments/Tutorials#5720]
Tutorial URL: https://developers.sap.com/tutorials/xsa-xsjs-access-external-service.html

I'm getting the error below after having followed all the steps but trying to access an HTTPS service.  I can successfully access an HTTP service without any issues.

The suggestions I’ve found online include uploading the certificates to the server via Trust Certificates and testing on other browsers, i had no success with either.  I am new to the XSA Web IDE and feel like i'm missing something.

**Browser error message**:
_500 unable to get local issuer certificate (connecting to api.[domain].com:443)
/hana/shared/HD1/xs/ea_data/grskshd100/executionroot/056ad75c-e205-4aa2-9a39-75fe6c1d0529/app/node_modules/@sap/xsjs/node_modules/@sap/fibers/future.js:250
                                    throw error;
                                    ^
Error: unable to get local issuer certificate (connecting to api.[domain].com:443)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1060:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:638:8)_

**Destination file (.xshttpdest)**
_description = "API";
host = "api.[domain].com";
port = 443;
proxyType = none;
useSSL = true;
timeout = 0;
sslHostCheck = false;_

**User-Provided Services** : EXTERNAL_HTTPS
{
            "port": "443",
            "host": "api.[domain].com",
            "tags": [
                        "xshttpdest"
            ]
}

**mta.yaml**

_ID: energyBackFill
_schema-version: '2.1'
version: 0.0.1
modules:
  - name: runBackfill
    type: nodejs
    path: runBackfill
    provides:
      - name: runBackfill_api
        properties:
          url: '${default-url}'
    requires:
      - name: EXTERNAL_HTTPS
      - name: LOC_API
resources:
  - name: EXTERNAL_HTTPS
    type: org.cloudfoundry.existing-service
    parameters:
      service-name: EXTERNAL_HTTPS
    properties:
      EXTERNAL_HTTP_SERVICE: '${service-name}'_

I've also attached the console output.

Thanks in advance for your help.

**Comment by jung-thomas** [comment]
What you are trying isn't within the scope of this tutorial.  This tutorial covers HTTP access not HTTPS.  The switch to security connectivity adds extra complexity by requiring certificates which is not the intention of this tutorial to cover.  For additional question on how to perform tasks not covered by this tutorial, please post your question in the SAP Community Q&A.
