### ISSUE TITLE
Secure a Basic Node.js App with the Authorization and Trust Management Service (XSUAA)

### ISSUE THREAD

**Issue by ceedee666** [SAPDocuments/Tutorials#5722]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-security-xsuaa-create.html

In step 5 there is a small typo in the first snippet:

applications:
# Product List Application
- name: product-list
  instances: 1
  memory: 128M
  routes:
    - route: product-list-ap25.cf.eu10.hana.ondemand.com
  path: myapp
  buildpacks:
    - nodejs_buildpack  
  timeout: 180

Instead of product-list-ap25.cf.eu10.hana.ondemand.com the URI should be product-list-ap25.cfapps.eu10.hana.ondemand.com

Christian

**Comment by nedo-SAP** [comment]
Thx for the info, I'll change this asap.

**Comment by nedo-SAP** [comment]
The typo has been fixed, I think this issue can be closed.
