### ISSUE TITLE
Create Sales Order App with SAP Cloud Platform Rapid Application Development by Mendix

### ISSUE THREAD

**Issue by masahiroo** [SAPDocuments/Tutorials#5726]
Tutorial URL: https://developers.sap.com/tutorials/mendix-salesorders.html

On the upper right of the window, there is a link to the Group site  (https://developers.sap.com/group.mendix-salesorders.html).  But it does not work.  Please find the attached screen shot.

Thanks,
Masahiro

<img width="959" alt="2020-08-21_11-47-28" src="https://user-images.githubusercontent.com/38098340/90846896-344fad00-e3a4-11ea-8568-44da5fa399df.png">

**Comment by Paolaufer** [comment]
@thecodester Hi Daniel,
This is the URL the link should lead to.
https://developers.sap.com/group.mendix-salesorders.html

I can reach it by navigating from the tutorials, but the link does not work.
Could you let me know how to fix it?

Regards,
Pao

**Comment by thecodester** [comment]
Can you tell me which link you mean?

When I click the little "Group" link at upper left or the name of the group in the middle right, I get this page:

![image](https://user-images.githubusercontent.com/11659786/91439312-6d40c380-e875-11ea-936c-94bf5edbb83a.png)

Do you not get that?

**Comment by masahiroo** [comment]
Thank you.  Now it works fine. I get the same page.

**Comment by masahiroo** [comment]
Oh!  It works now!  A few days ago, I couldn’t this page.
I just closed the issue.

Regards, Masahiro
