### ISSUE TITLE
Deploy the Azure Service Broker to Cloud Foundry

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#5731]
Tutorial URL: https://developers.sap.com/tutorials/cp-osba-azure-deploy-service-broker.html

Step 5: Update manifest.yml − Redis Cache information

The command:

`az redis show --name <name-redis-cache> --resource-group SAPTechEd --query [hostName] --output tsv`

should be changed into 

`az redis show --name <name-redis-cache> --resource-group SAPCloudPlatform --query hostName --output tsv`

as this would match the resource group created in the tutorial https://developers.sap.com/tutorials/cp-osba-azure-redis-cache.html and will return the hostName instead of the error message:

`no matches found: [hostName]`

**Comment by maxstreifeneder** [comment]
Thanks @gregorwolf! incosistency while updating the tutorials last time! will let you know once this is done

**Comment by maxstreifeneder** [comment]
Fixed with #5864, thanks again @gregorwolf!
