### ISSUE TITLE
Get Started with SAP Cloud SDK for JavaScript

### ISSUE THREAD

**Issue by vbalko** [SAPDocuments/Tutorials#5732]
Tutorial URL: https://developers.sap.com/tutorials/s4sdkjs-getting-started.html

Please specify the step you are referring to 

Step 1 and Step 2.

When you create cloud SDK project - there is link to sap/npm registry created in .npmrc. As far as I know - public npm registry should be used from august 2020. There should be step to remove that link or update CLI init template.

**Comment by jjtang1985** [comment]
Hi @vbalko , thank you for raising this up. I'm going to remove the unnecessary `.npmrc` for the internal registry. I'll let you know when the adjustment of CLI and the tutorial is done.

**Comment by jjtang1985** [comment]
I released a new version for removing the the `.npmrc` file.
