### ISSUE TITLE
Tour the SAP Community

### ISSUE THREAD

**Issue by marie-bn** [SAPDocuments/Tutorials#5737]
Tutorial URL: https://developers.sap.com/tutorials/community-start.html

Please specify the step you are referring to

I've completed all steps but unfortunately at step 11 when I click on "done" it does not turn the status to completed. I'm afraid if I refresh the page, progress on the other 10 steps will be lost..

**Comment by thecodester** [comment]
@marie-bn I opened the tutorial and was able to do step 11. Can you try again? Also, refresh the tutorial -- once you get the green your status is automatically stored in the backend.

@WorkJerryJanda FYI

**Comment by marie-bn** [comment]
@thecodester I've reopened the tutorial but none of the progress (1-10) was saved, meaning I probably have to tick all off again?

**Comment by marie-bn** [comment]
@thecodester Thanks I tried it again (after laptop reboot and network change) and could finally complete step 11 as well.
