### ISSUE TITLE
Get Started with  SAP Cloud  Platform Business Rules

### ISSUE THREAD

**Issue by kbprasad79** [SAPDocuments/Tutorials#5738]
Mission URL: https://developers.sap.com/mission.cp-rules-get-started.html

Tutorials are not visible
![image](https://user-images.githubusercontent.com/68516379/91170285-91af6b00-e6d0-11ea-8910-e7b68480e1ad.png)

**Comment by thecodester** [comment]
Fixed. Please try again. If OK, please close the ticket. Thanks for letting us know.

**Comment by kbprasad79** [comment]
Thanks. I can see tutorials now.
