### ISSUE TITLE
Prepare to Create Workflows in SAP Cloud Platform

### ISSUE THREAD

**Issue by dsilvahansen** [SAPDocuments/Tutorials#5742]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-1-getting-started-cf.html

Please specify the step you are referring to: Step 2: Create role collection
The process has been changed. 
![image](https://user-images.githubusercontent.com/31363815/91284358-6cdaf680-e7a9-11ea-939b-b58dd8a090c6.png)

Also the Application Identifier in the role collection settings is `workflow!b10150` but in the tutorial it is `workflow!b1774`. Hope that is not an issue.

Please specify the step you are referring to: Step 4: Enable the workflow extension and Cloud Foundry

Webide is no longer accessible from the trial home, instead it is now Business Application Studio
![image](https://user-images.githubusercontent.com/31363815/91284685-e07d0380-e7a9-11ea-836a-c1c0e3b95866.png)

Will the tutorial be updated anytime soon, as I would like to proceed to create this on Business Application Studio?
Or is there any other tutorial for Business Studio?

**Comment by AstridHerbst** [comment]
Hi,
We are currently working on this tutorial. The content has to be adapted to use the SAP Business Application Studio before you can execute it.
Best regards,
Astrid

**Comment by AstridHerbst** [comment]
Hi,

The new tutorial for Trial is available at: https://developers.sap.com/group.cp-workflow-cf.html 

Best regards, Astrid
