### ISSUE TITLE
Prepare the Portal Environment for Creating Sites (Neo)

### ISSUE THREAD

**Issue by Nuube** [SAPDocuments/Tutorials#5750]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-getting-started.html

Please specify the step you are referring to

No,3

"Click the Portal tile to open the service overview page."

There is no service overview page here. Tutorial is a dead end at step 3.

**Comment by thecodester** [comment]
ARe you saying there is no tile or no service page? In my trial, I have such a tile and service page. 

But there is a transition from Neo to Cloud Foundry and some old users still have Neo but new users do not, or may not soon. I suggest you do the tutorial mission https://developers.sap.com/mission.portal-cf.html

@LindsayBert @IrisSasson Can you confirm?

**Comment by IrisSasson** [comment]
Hi

We will be updating the tutorials in the coming days
You can perform the tutorial if you use the Launchpad service instead
Thanks
Iris.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
