### ISSUE TITLE
Create Table Persistence and Generate Data

### ISSUE THREAD

**Issue by Nuube** [SAPDocuments/Tutorials#5753]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-persistence.html

Please specify the step you are referring to: 6

How do I open the database table?

**Comment by thecodester** [comment]
Step 3, substep 6

**Comment by mervey45** [comment]
Hi @Nuube ,

like @thecodester  mentioned you need to press F8 to open the database table, which is described in step 3.6.


Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

we can close this ticket.

Best regards, 
Merve
