### ISSUE TITLE
Maintain a Communication Arrangement for Inbound Communication

### ISSUE THREAD

**Issue by MagPasulke** [SAPDocuments/Tutorials#5754]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

I am referring to step 3 - Create a communication user. 
My Launchpad does not show the Communication Management Catalog. I guess I am missing the business catalog communication management (SAP_CORE_BC_COM). How do I add this to my Abap Cloud Platform Trial user?

Thanks!

**Comment by thecodester** [comment]
@niloofar-flothkoetter  In addition to answering question, your last name starts with lower case letter

**Comment by niloofar-flothkoetter** [comment]
@MagPasulke  
actually you need just SAP_BR_DEVELOPER, SAP_BR_ADMINISTRATOR and BR_DEVELOPER. Do you have all this three Rolles?

Regards
Niloofar

**Comment by MagPasulke** [comment]
Hi,
I guess I don't. How to add/ check my roles?

**Comment by niloofar-flothkoetter** [comment]
If you are not an Admin, you can not add it by yourself, then you need to ask your system admin.
under Maintain Business user click you User name (the blue number), hier you will find your Assigned Business Roles.

**Comment by MagPasulke** [comment]
Since it is a trial account I guess I am the admin somehow. Where do I find the "Maintain Business User" menu?

**Comment by niloofar-flothkoetter** [comment]
what you see in the menu at all? maybe you send me a screenshot.

**Comment by niloofar-flothkoetter** [comment]
in trial account are the connectivity functions not available, then you do not have Comm Arrangements, Software Lifecycle, User Mgmt etc.

**Comment by niloofar-flothkoetter** [comment]
If you are about to use the connectivity tutorials, you need a global account in SAP cloud platform cockpit.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
