### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by Nuube** [SAPDocuments/Tutorials#5755]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-data-model.html

Please specify the step you are referring to: 6

Which credentials need to be used here? I could not log in.

**Comment by mervey45** [comment]
Hi @Nuube ,

in step 4.6 you need to logon with your trial user, which you created earlier in following tutorial: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html 

It needs to be the same user + pw like your SAP Cloud Foundry Trial user.

Best regards,
Merve

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

we can close this ticket.

Best regards, 
Merve
