### ISSUE TITLE
Discover Sales Order API from S/4HANA Cloud System

### ISSUE THREAD

**Issue by nageshwar-reddy** [SAPDocuments/Tutorials#5757]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-api-discover.html

Step 2 (2). When i try to copy the sandbox URL, it gives an error "Unable to copy API : The swagger version of the API proxy is unsupported." Please  check the attached screenshot.

![image](https://user-images.githubusercontent.com/13148363/91629995-7653a100-e9eb-11ea-8715-3fd9e917c098.png)

**Comment by shilpavij** [comment]
Dear Colleague,

We have already identified this issue and team is fixing it.

Regards
shilpa

**Comment by thecodester** [comment]
@shilpavij If you already have an issue open for this problem, you can close this one. Otherwise, keep open until fixed

**Comment by shilpavij** [comment]
We can close this
