### ISSUE TITLE
Set Up Workflow Management in Cloud Cockpit

### ISSUE THREAD

**Issue by mbchiyo** [SAPDocuments/Tutorials#5763]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html

Step 2, number 7:
`HISTFILE= && cf login -a <your trial account API End Point> -u <your trial email ID> -p <your trial user password> -o <your trial organisation name> -s <your trial space name>`

It would be good to have a copy button for the command. The command here is quite long and I always need bit time to get it correctly selected with the mouse.

**Comment by ArchanaShukla** [comment]
This is has changed now. Please check the updated Booster. 
@MichaelCzcz - please close the ticket
