### ISSUE TITLE
Reuse a CAP Java Service

### ISSUE THREAD

**Issue by Sujit3692** [SAPDocuments/Tutorials#5767]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-service-reuse.html

Please specify the step you are referring to

while installing the sqlite it is throwing npm error.

**Comment by maxstreifeneder** [comment]
Hi @Sujit3692, 

could you please provide more context, screenshots, log outputs? Otherwise it's hard to reproduce the issue or identify the root cause. 

Sorry and regards,
Max

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
