### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by luiz-espindola** [SAPDocuments/Tutorials#5768]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

Please specify the step you are referring to
Step 6 at point:
TIP: If you do not see the Process Integration Runtime service in the list, at the subaccount level, choose Entitlements > Configure Entitlements > Add Service Plans. Choose Process Integration Runtime and select the integration-flow service plan checkbox and choose Add 1 Service Plan.
Im not able to add this the cjeckbox is grey.

**Comment by Vikramkulkarni01** [comment]
Hi @luiz-espindola , 

Thanks for reaching out to me. 

If it's greyed out mean the service plan would have selected. 

Could you please delete from the **Entitlements** page and re-add it.

![image](https://user-images.githubusercontent.com/59861880/92196671-6295b800-ee8d-11ea-869c-bcd844276bd4.png)

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
