### ISSUE TITLE
SAP HANA XS Advanced, Creating a Node.js Module

### ISSUE THREAD

**Issue by AndrewFrsc** [SAPDocuments/Tutorials#5769]
Tutorial URL: https://developers.sap.com/tutorials/xsa-xsjs-xsodata.html

Step 6: Execute the xsjs module.

Logs
Application is starting
Running module /HANA_APP/core_xsjs failed. See console logs for more details.

Service provisioning for module: '/core_xsjs'
Service instance 'XSA_DEV-e1i4v3gg18804q2p-HANA_APP-UAA-service' for resource 'XSA_DEV-e1i4v3gg18804q2p-HANA_APP-UAA-service' already exists, no operation will be performed.
Service instance 'XSA_DEV-e1i4v3gg18804q2p-HANA_APP-hdi_db' for resource 'XSA_DEV-e1i4v3gg18804q2p-HANA_APP-hdi_db' already exists, no operation will be performed.
[INFO] Injecting source code into builder...
[INFO] Source code injection finished
[INFO] ------------------------------------------------------------------------
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @sap/xsjs-test@^3.1.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'core_xsjs'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /hana/shared/HXE/xs/controller_data/executionagent/executionroot/52934674-5df4-4ac6-a048-689179ec1339/app/META-INF/cache/node10.17/.npm/_logs/2020-09-04T05_03_13_456Z-debug.log

**Comment by jung-thomas** [comment]
Both 3.1.2 and 3.1.3 of the library is available online: https://www.npmjs.com/package/@sap/xsjs-test
 
Perhaps your system is an older release of HANA Express and doesn't have an upstream link configured or no connection to the internet.  Then you might not have this newer version of the library that is required.  We would recommend that you configure your system with an upstream link to the public npm repository.  That way you can always pull the latest version from the internet.    Do you know if the system you are doing this tutorial on has the upstream link configured?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
