### ISSUE TITLE
Add Automated System Tests to Your CI/CD Pipeline: teched is not found when specified

### ISSUE THREAD

**Issue by Kev-Tri** [SAPDocuments/Tutorials#5770]
Tutorial URL: https://developers.sap.com/tutorials/cp-cicd-sytem-test.html

Please specify the step you are referring to
Step 3: Test the home screen

I followed the steps and prerequisites for starting an automated E2E test with UIveri5. By starting the command 
   uiveri5
in the terminal, the browser opens and closes quickly. The overall test state is FAILED with the following info on the terminal:

`INFO: Suite started: teched
INFO: Spec started: Should validate the home screen
INFO: Expectation FAILED: Failed: Spec with full name: teched not found
INFO: Expectation FAILED: Failed: javascript error: UI5 dependencies are not loaded on this pageError: UI5 dependencies are not loaded on this page
    at findByControl (eval at executeScript (:480:16), <anonymous>:5:13)
    at eval (eval at executeScript (:480:16), <anonymous>:30:6)
    at executeScript (<anonymous>:482:30)
    at <anonymous>:487:24
    at callFunction (<anonymous>:450:22)
    at <anonymous>:464:23
    at <anonymous>:465:3
  (Session info: chrome=85.0.4183.83)
  (Driver info: chromedriver=85.0.4183.87 (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-refs/branch-heads/4183@{#1689}),platform=Windows NT 10.0.17763 x86_64)
INFO: Spec finished: Should validate the home screen with status: FAILED
INFO: Suite finished: teched with status: FAILED for: 0.963s
INFO: Suite specs summary, total: 1, passed: 0, failed: 1, pending: 0, disabled: 0`

Question is: What should be done to make this project work?

**Comment by georgbischoff** [comment]
Hi Kev-Tri,

can you verify if the name of the describe-block is matching the prefix of the JS file name:
describe("**teched**"...
**teched**.spec.js

Regards,
Georg

**Comment by Kev-Tri** [comment]
Hi Georg,

as this is a file used from the Git, it has the same name as required: teched.spec.js

Regards,

Kev-Tri

**Comment by georgbischoff** [comment]
Hi Kev-Tri,

do you have a screenshot of the first screen in the \target\report\screenshots folder. Is it a completely empty screen or do you see an authentification error? How do you pass username and password? Hardcoded in the conf.js or via commandline parameter uiveri5 --param.user=... and --params.pass=...?

Regards,
Georg

**Comment by MichaelCzcz** [comment]
@Kev-Tri Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
