### ISSUE TITLE
Discover Sales Order API from S/4HANA Cloud System

### ISSUE THREAD

**Issue by rvodela** [SAPDocuments/Tutorials#5771]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-api-discover.html

Please specify the step you are referring to Step 2.
I dont find S4HANA cloud in the NEO trial environment and also Cant find the Sales Service Mentioned See the attached
image
![api no s4hana](https://user-images.githubusercontent.com/6215920/92257000-5ad41480-ee89-11ea-8971-eeb35c83d5bb.PNG)
Can you suggest how I can access the same

**Comment by shilpavij** [comment]
Dear Colleague,

Kindly search for S/4HANA package and then sales order API
<img width="416" alt="2020-09-09_10-39-16" src="https://user-images.githubusercontent.com/44152823/92557041-fa7a1400-f288-11ea-8e49-814fea5bfa34.png">

Regards
Shilpa

**Comment by rvodela** [comment]
Thank you very much for this info.  Althou I found this time. I still feel that changes are taking place on the cloud.  On continuing this when I tried to copy the sales order API I got the following error
Swagger version of the API proxy is unsupported
![API Copy error](https://user-images.githubusercontent.com/6215920/92614936-6fd9ea80-f271-11ea-9439-6f9e00117f32.PNG)

**Comment by shilpavij** [comment]
We know this problem and product teams would fix it. Kindly close this
