### ISSUE TITLE
Assign Roles to Users for Managing Business Rules

### ISSUE THREAD

**Issue by rvodela** [SAPDocuments/Tutorials#5772]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules02-assign-roles.html

Please specify the step you are referring to Step 7
The specified Roles are not available in the trial cloud foundry version - Can you please let me know

**Comment by VandanaVasudevan** [comment]
Hi,

There are some changes planned for the tutorials and we will be updating them soon. For now, can you please try enabling the entitlement for Business Rules service? 

Best Regards,
Vandana

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
