### ISSUE TITLE
Create an ABAP Core Data Services (CDS) View in SAP NetWeaver 7.5

### ISSUE THREAD

**Issue by justrockstar** [SAPDocuments/Tutorials#5773]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-create-cds-view.html

The tutorial has been mixed up. The steps require a recent version of ABAP Platform and not NetWeaver 7.5.
Objects like MDE and Service Binding are not available within NetWeaver 7.5.

**Comment by julieplummer20** [comment]
Hi justrockstar,
I do not follow your argument.
The prerequisites are listed here:

You have a valid instance of SAP S/4HANA 1909 or later, on-premise
You have installed ABAP Development Tools, latest version
You have downloaded the ABAP Flight Reference Scenario. To pull this reference scenario from Github, see Downloading the ABAP Flight Reference Scenario

The tag "NetWeaver 7.5" refers to the product. It is is used *in conjunction with* the topic tag, ABAP Development.
Is that clear?
BR Julie.

**Comment by justrockstar** [comment]
Hi Julie,
SAP NetWeaver 7.5 is the pre-predecessor of the ABAP platform used in S4 1909.
Why don’t you remove SAP NetWeaver 7.5 from the title?
People get disappointed, because the solution does not run on NetWeaver 7.5
BR justrockstar

**Comment by julieplummer20** [comment]
Hi justrockstar,
"SAP NetWeaver 7.5 is the pre-predecessor of the ABAP platform used in S4 1909."
This is not strictly true, in that it is not the whole truth.
For that reason, I am sorry, but I cannot implement your suggestion.
Thanks for your feedback.
Best wishes,
Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by justrockstar** [comment]
Dear Julie,

here is a reference for my statement by SAP. Please compare the blog [ABAP Platform – Part 1 – Evolution from SAP Netweaver](https://blogs.sap.com/2020/06/12/abap-platform-part-1-evolution-from-sap-netweaver/)



The given instructions require an ABAP Platform 1909, which is only shipped via S/4. The tutorial does not run with NetWeaver 7.5, as is it stated in the headline-

BR, justrockstar
![SAP-Netweaver](https://user-images.githubusercontent.com/59475370/93560113-a60a1f00-f981-11ea-93db-5efba00e19e8.jpg)

**Comment by julieplummer20** [comment]
Hi justrockstar,
OK, I will change the title to "Create an ABAP Core Data Services (CDS) View, On-Premise".

BR Julie.
