### ISSUE TITLE
Enhance an ABAP Core Data Services (CDS) View in SAP Cloud Platform, ABAP Environment

### ISSUE THREAD

**Issue by justrockstar** [SAPDocuments/Tutorials#5774]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-enhance-cds-view.html

Please specify the step you are referring to:
Step 1:
CDS View /DMO/I_Agency_U does not exist in the current /DMO/FLIGHTS Modell, /DMO/I_Agency work fine.

**Comment by julieplummer20** [comment]
Hi justrockstar,
I have fixed this. The changes should show up in the next 24 hours.
BR Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
