### ISSUE TITLE
Build Your Mobile Development Kit Client Using MDK SDK

### ISSUE THREAD

**Issue by bsingh03** [SAPDocuments/Tutorials#5777]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-dev-kit-build-client.html

Please specify the step you are referring to: Step 5 : Run the MDK Client.
We have followed all the Steps and each one worked fine but while building the mdk client for demoSampleApp from Step 5 we are getting below error saying:

Unable to apply changes on device: ######. Error is: Command gradlew.bat failed with exit code 1.

I have attached screenshot of my Error

![Building MDK client Issue](https://user-images.githubusercontent.com/68890285/92362453-a4cd2c80-f10d-11ea-927b-13b3d8470783.JPG)

**Comment by jitendrakansal** [comment]
Can you add the following param to the tns run command in the command line: 
--logtrace> tns_log.txt 2>&1 

e.g. _tns run android --emulator --logtrace> tns_log.txt 2>&1_ 

The resulting verbose log will be in the **tns_log.txt,** it might give more details on the error.

**Comment by bsingh03** [comment]
I was facing similar issue it has been resolved by using below link:
[https://github.com/SAPDocuments/Tutorials/issues/5783](url)
