### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by bkserawy** [SAPDocuments/Tutorials#5782]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to: Create an SAP Fiori App Using SAP Business Application Studio

The Steps and Screenshots are really old and not really relevant. It couldn't help me, because it does not look the same anymore.

**Comment by raz-korn** [comment]
Hi @bkserawy ,
Thanks for your feedback.
Can you share 2-3 screenshots that do not look the same?
Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
