### ISSUE TITLE
Build Your Mobile Development Kit Client Using MDK SDK

### ISSUE THREAD

**Issue by shubhchamp** [SAPDocuments/Tutorials#5783]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-dev-kit-build-client.html

Hello,

While performing step 4 the create -client command closes unexpectedly after a certain step and I am not able to get "Application ready" Message in step 4.2. Command window closes after following:

![image](https://user-images.githubusercontent.com/26719268/92461973-820f4680-f1e7-11ea-85f3-eb1837510059.png)

After that I can see the project created though I am not sure all the artifacts are generated successfully.

![image](https://user-images.githubusercontent.com/26719268/92462143-b420a880-f1e7-11ea-9919-ef4c8048fc03.png)

If I perform step 5 I get lots of errors and the app is not working on the device. I am thinking it might be because the app is not created successfully. Please let me know if any more information is required. Any help will be appreciated as we need to perform similar steps on Asset manager app.

Thanks,
Shubham

**Comment by jitendrakansal** [comment]
@shubhchamp could you look at this SAP Note and try if this solves your issue? 
https://launchpad.support.sap.com/#/notes/2965176

**Comment by shubhchamp** [comment]
@jitendrakansal Thanks for pointing. This works. Closing this issue.
