### ISSUE TITLE
Build Your Mobile Development Kit Client Using MDK SDK

### ISSUE THREAD

**Issue by NikhilSave14** [SAPDocuments/Tutorials#5786]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-dev-kit-build-client.html

Please specify the step you are referring to - step 1

we are able to install only chocolatey and node.js. All remaining 9 components are in error. could you please guide us for installing remaining components.

![MDK dependencies installer](https://user-images.githubusercontent.com/70974477/92515180-ce32a900-f230-11ea-8cff-2c2e9271634b.PNG)

Regards,
Nikhil Save

**Comment by jitendrakansal** [comment]
@NikhilSave14 those highlighted components need to be installed manually (click i icon in front of each component for details).

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
