### ISSUE TITLE
Connect to HubSpot

### ISSUE THREAD

**Issue by NikhilSave14** [SAPDocuments/Tutorials#5787]
Tutorial URL - https://developers.sap.com/tutorials/cp-apim-openconnectors-connect-hubspot.html

Issue in step 2 - Not able to subscribe open connectors.

![open connectors error](https://user-images.githubusercontent.com/70974477/92519127-15bc3380-f237-11ea-9e19-79dfcf96af7c.PNG)

Regards,
Nikhil Save

**Comment by shilpavij** [comment]
Dear Colleague,

Kindly delete your instance and create it again once. If it still does not work kindly open a BCP ticket for this.

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by NikhilSave14** [comment]
Hi Shilpa,

I am not able to find any instance for open connectors in my trial account. Would you be able to guide me regarding deleting instance in my trial account. 

Regards,
Nikhil Save
