### ISSUE TITLE
Set Up SAP Cloud Platform Launchpad Service

### ISSUE THREAD

**Issue by mrudula1412** [SAPDocuments/Tutorials#5788]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Please specify the step you are referring to - step 1

Point No.5-
Enter Launchpad in the search box and click the Launchpad service tile.

I am not getting Launchpad service tile in Subscriptions in SAP Cloud Platform Cockpit (Trial Account)
Could you please let me know if it is available for Trial Account.

Regards,
Mrudula

**Comment by IrisSasson** [comment]
Hi, please try to delete your trial account and create a new one

This is a bug that it is not available on existing trial acounts

**Comment by mrudula1412** [comment]
Hi Iris,

Thanks for guidance.
I am able to add launchpad subscription from entitlements.

Regards,
Mrudula
