### ISSUE TITLE
Build a Continuous Delivery Pipeline for SAP Cloud Application Programming Model

### ISSUE THREAD

**Issue by joergmann** [SAPDocuments/Tutorials#5790]
Tutorial URL: https://developers.sap.com/tutorials/cloudsdk-cap-pipeline-model.html

All

Please specify the step you are referring to
Step 1, Section 3
* "bookshop" is not supported as feature. If you want to create a sub folder for the project including sample data use
````
cds init bookshop --add java,mta,samples
cd bookshop
````

Step 2, Section 1
"cds add pipeline "
* Add a remark to cd into the project before calling "cds add", or add "pipeline" right away

either
````
cds init bookshop --add java,mta,samples
cd bookshop
cds add pipeline
````
or
````
cds init bookshop --add java,mta,samples,pipeline
cd bookshop
```` 

Regards
Jörg

**Comment by SarahLendle** [comment]
Hi @joergmann,

Thanks for your feedback! We're going to rework this tutorial by the beginning of October.

Best regards,
Sarah

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
