### ISSUE TITLE
Change the text to Create Site

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5795]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-create-sitelaunchpad.html

**Step 1: Create a site**

Here instead of click Create New Site, change the text to click Create Site. 
Form a customer perspective, since there is no button with the text create new site this might lead to confusion.

Best Regards,
Priyanka

**Comment by PriyankaShivakumar** [comment]
Labels to be attached:
Landscape label: trail1, trail2
Sprint Label: SCPTest-2008A
Scenario Labels: SCPTest-psite

Best Regards,
Priyanka

**Comment by MichaelCzcz** [comment]
@LindsayBert Please Respond!

**Comment by LindsayBert** [comment]
Hi

This was fixed ages ago.  The tutorial is correct.

Thanks Lindsay

**Comment by PriyankaShivakumar** [comment]
Hi
This tutorial is fixed so will close this issue.

Best Regards,
Priyanka
