### ISSUE TITLE
Set Up Workflow Management in Cloud Cockpit

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Tutorials#5796]
**Labels** :
Landscape label: trail1, trail2
Sprint Label: SCPTest-2008A
Scenario Labels: SCPTest-eboard

Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html

Please specify the step you are referring to:

**Step 2: Setup Fiori Launchpad**

In tutorial there is a note mentioned as below :- 

SAP Business Application Studio is already enabled in your trial account. This would not be the case in your productive account and you need to enable the Subscription to access the studio.

**Actual Result** : In my trial account  on US region, even after performing boosters step " business application studio" is not enabled/subscribed by default.

Please update this step/note on tutorial.

Thanks
Mounika

**Comment by ArchanaShukla** [comment]
That would not be the case. Using Booster Business Application Studio is enabled. There were some issues with Booster and Cloud Platform Trial which resulted in theses issues. Check again. 

@MichaelCzcz - please close this issue
