### ISSUE TITLE
Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Tutorials#5797]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

In step 4 - sub step 4 ---> In screenshot its showing "**List Report Object Page V2**" but while executing we are getting only "**List Report Object Page**" tile. Please refer below screenshots.

In Tutorial 
![Doc](https://user-images.githubusercontent.com/65213299/92600699-8875ef00-f2c9-11ea-8866-25d6a7d3879e.PNG)

While executing
![Live](https://user-images.githubusercontent.com/65213299/92600777-a17ea000-f2c9-11ea-928d-efb69078ef9f.PNG)

**Comment by mervey45** [comment]
Hi @shivakumar-p-sap ,

I already created following pull request: #5743
It still needs to be merged. @MichaelCzcz  can you merge my changes?

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

we can close this ticket.

Best regards, 
Merve
