### ISSUE TITLE
Screenshot has to be updated at Step 4

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5798]
Tutorial URL: https://developers.sap.com/tutorials/cai-bot-getting-started.html

**Step 4: Fork intent**

Please update the screenshot, Here I don't see the terminal with the curl request.

Tutorial screenshot: 
![image](https://user-images.githubusercontent.com/65999547/92600955-d559c580-f2c9-11ea-99d7-fd6abb1e9928.png)

Actual Screenshot:
![image](https://user-images.githubusercontent.com/65999547/92601021-e9052c00-f2c9-11ea-961f-60d3c2ba5d65.png)

Best Regards,
Priyanka

**Comment by PriyankaShivakumar** [comment]
Labels to be attached:
Landscape label: trail1, trail2
Sprint Label: SCPTest-2008A
Scenario Labels: SCPTest-cai

Best Regards,
Priyanka

**Comment by thecodester** [comment]
I have updated. The requested screenshot is not exactly at the same point as mine. But I removed the Curl script from the screen shot

**Comment by PriyankaShivakumar** [comment]
Hi, 
The second screenshot in the Step 4 still shows the curl script.
![image](https://user-images.githubusercontent.com/65999547/94692606-57c92880-0350-11eb-8150-c2d1aa00b45d.png)

Best Regards,
Priyanka

**Comment by thecodester** [comment]
https://github.com/SAPDocuments/Tutorials/commit/2dfc6bc84d680e5898d0ecb076f1cd53224e0543
