### ISSUE TITLE
Update screenshot for the Intent creation popup

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5799]
Tutorial URL: https://developers.sap.com/tutorials/cai-bot-getting-started.html

**Step 5: Create new intents**

Please update the screenshot for the Intent creation popup

Tutorial screenshot:
![image](https://user-images.githubusercontent.com/65999547/92601458-747ebd00-f2ca-11ea-8c1a-144fcbd0d91e.png)

Actual screenshot:
![image](https://user-images.githubusercontent.com/65999547/92601513-8bbdaa80-f2ca-11ea-9e08-71f14c8c2a7f.png)

Best Regards,
Priyanka

**Comment by PriyankaShivakumar** [comment]
Labels to be attached:
Landscape label: trail1, trail2
Sprint Label: SCPTest-2008A
Scenario Labels: SCPTest-cai

Best Regards,
Priyanka

**Comment by thecodester** [comment]
https://github.com/SAPDocuments/Tutorials/commit/2dfc6bc84d680e5898d0ecb076f1cd53224e0543
