### ISSUE TITLE
Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Tutorials#5800]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

In step 4 - Sub step 7 ---> In screenshot its showing "**Next Button**" but while executing we are getting "**Finish Button**" tile. Please refer below screenshots.

In Tutorial
![DocNExtRealFINISH](https://user-images.githubusercontent.com/65213299/92601613-b0198700-f2ca-11ea-8aa4-f9391507d834.PNG)

While executing
![Doc](https://user-images.githubusercontent.com/65213299/92601733-d0e1dc80-f2ca-11ea-80af-2a6d35f8f1b6.png)

**Comment by mervey45** [comment]
Hi @shivakumar-p-sap ,

These changes are already done, they just need to be merged into production. 
I already created following pull request: #5743
@MichaelCzcz can you merge my changes?

Best regards,
Merve

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

we can close this ticket.

Best regards, 
Merve

**Comment by julieplummer20** [comment]
Hi Michael,
laut Merve können wir diesen Ticket zumachen :-).
VG Julie.
