### ISSUE TITLE
Screenshot and text don't match

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5801]
Tutorial URL: https://developers.sap.com/tutorials/cai-bot-getting-started.html

**Step 9: Create new skill**

Here the screenshot and text don't match. In the text it is given to select **@ask-joke** intent but in the screenshot we are selecting the **@joke** intent. So please update so that the text and the screenshot both refer the same intent

![image](https://user-images.githubusercontent.com/65999547/92601971-1e5e4980-f2cb-11ea-9d1f-13611771d1f7.png)

Best Regards,
Priyanka

**Comment by PriyankaShivakumar** [comment]
Labels to be attached:
Landscape label: trail1, trail2
Sprint Label: SCPTest-2008A
Scenario Labels: SCPTest-cai

Best Regards,
Priyanka

**Comment by thecodester** [comment]
changed ask-joke to joke throughout
