### ISSUE TITLE
What you build part of the tutorial should be after In this tutorial part.

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5802]
Tutorial URL: https://developers.sap.com/tutorials/cai-bot-shipping-1-track-bot.html

Here the "what you build" paragraph has a detailed explanation of the use case, so from a customer perspective, I feel that it would be better if this part is included after the "In this tutorial" part which gives a basic overview of the tutorial.

Best Regards,
Priyanka

**Comment by PriyankaShivakumar** [comment]
Labels to be attached:
Landscape label: trail1, trail2
Sprint Label: SCPTest-2008A
Scenario Labels: SCPTest-cai

Best Regards,
Priyanka

**Comment by thecodester** [comment]
The idea is that this is the first tutorial in the group, so we are telling people what they will build, then we are telling them what part of the overall problem they will create in this tutorial.
