### ISSUE TITLE
Develop an SAP Fiori App Using ABAP

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Tutorials#5803]
Mission URL: https://developers.sap.com/mission.cp-starter-extensions-abap.html

In total time its mentioned as "**1hr. 20mins**" but one tutorial is "**15 mins**" another is "**1hr. 15mins**", so total should be "**1hr. 30mins**". Please refer below screenshot. 
![MainScreen](https://user-images.githubusercontent.com/65213299/92603054-7c3f6100-f2cc-11ea-92aa-fe7a81c53b06.PNG)

**Comment by mervey45** [comment]
Hi @MichaelCzcz , 

can you change this on the overview page?
We needed to update the time on one tutorial.
I'm not able to update it on the mission page.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
@akula86 Can you please make this change? Thank you.

**Comment by thecodester** [comment]
Fixed
