### ISSUE TITLE
Update screenshot for creating an entity

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5804]
Tutorial URL: https://developers.sap.com/tutorials/cai-bot-shipping-1-track-bot.html

**Step 2: Create entity for parcel number**

Here please update the screenshot for creating an entity

Tutorial screenshot:
![image](https://user-images.githubusercontent.com/65999547/92603152-9aa55c80-f2cc-11ea-9cd1-ee820b516909.png)

Actual screenshot:
![image](https://user-images.githubusercontent.com/65999547/92603200-a5f88800-f2cc-11ea-86c1-b350285d1a21.png)

Best Regards,
Priyanka

**Comment by PriyankaShivakumar** [comment]
Labels to be attached:
Landscape label: trail1, trail2
Sprint Label: SCPTest-2008A
Scenario Labels: SCPTest-cai

Best Regards,
Priyanka

**Comment by thecodester** [comment]
I do not think it worthwhile to update this screenshot at this time.
