### ISSUE TITLE
Update screenshot for forking the intent

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5805]
Tutorial URL: https://developers.sap.com/tutorials/cai-bot-shipping-1-track-bot.html

**Step 3: Add intents for yes and no**

Here please update the screenshot for forking the intent

Tutorial screenshot:
![image](https://user-images.githubusercontent.com/65999547/92603568-13a4b400-f2cd-11ea-8884-7dce4088f7f4.png)

Actual screenshot:
![image](https://user-images.githubusercontent.com/65999547/92603624-24edc080-f2cd-11ea-95b2-b159d84d5c37.png)

Best Regards,
Priyanka

**Comment by PriyankaShivakumar** [comment]
Labels to be attached:
Landscape label: trail1, trail2
Sprint Label: SCPTest-2008A
Scenario Labels: SCPTest-cai

Best Regards,
Priyanka

**Comment by thecodester** [comment]
This is a pure UI change and does not seem to change functionality or add functionality. For now, I will not change screenshot.
