### ISSUE TITLE
Add a step in the tutorial to select map enrichments

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5806]
Tutorial URL: https://developers.sap.com/tutorials/cai-bot-shipping-3-price-parcel.html

**Step 1: Create entity for parcel size**

Here after clicking on Enrichment, please add a step in the Tutorial to select map enrichments since I got the below screen after clicking on Enrichment, had to select the map enrichments to proceed forward.
![image](https://user-images.githubusercontent.com/65999547/92604006-9e85ae80-f2cd-11ea-9e85-60a0c63653f4.png)

Best Regards,
Priyanka

**Comment by PriyankaShivakumar** [comment]
Labels to be attached:
Landscape label: trail1, trail2
Sprint Label: SCPTest-2008A
Scenario Labels: SCPTest-cai

Best Regards,
Priyanka

**Comment by thecodester** [comment]
Added that they must select Map Enrichments
