### ISSUE TITLE
Include step to create new card

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5807]
Tutorial URL: https://developers.sap.com/tutorials/cai-bot-shipping-3-price-parcel.html

**Step 4: Add requirements to skill**

While adding the card, click on add card and then click on create new card.
Please include these steps in the tutorial.

Best Regards,
Priyanka

**Comment by PriyankaShivakumar** [comment]
Labels to be attached:
Landscape label: trail1, trail2
Sprint Label: SCPTest-2008A
Scenario Labels: SCPTest-cai

Best Regards,
Priyanka

**Comment by thecodester** [comment]
I do not think someone needs to be told to press the Create New Card button, but I did add instruction to click "Add Card" at the end, otherwise they may forget and it won't be saved.

https://github.com/SAPDocuments/Tutorials/commit/226c4a995ddfcdba40c4bbd1ef9877cb329f8636
