### ISSUE TITLE
Set Up SAP Mobile Cards

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5808]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-setup.html

Please specify the step you are referring to : Step 3: Get familiar with available configurations.
Change of screenshot :  Event Log and Restore options.
Expected result : 
![image](https://user-images.githubusercontent.com/50734023/92607525-dee72b80-f2d1-11ea-9c42-dcc21679a53c.png)

No Event log option
![image](https://user-images.githubusercontent.com/50734023/92607925-62a11800-f2d2-11ea-9a10-ff81f2b7934b.png)

Actual result : No Restore option and Event log option is present.
![image](https://user-images.githubusercontent.com/50734023/92607713-1b1a8c00-f2d2-11ea-9f86-25cbcca4a77a.png)

Labels to be added: trail1 & trail2
Scenario Label : SCPTest-mcard

**Comment by sandeep-tds** [comment]
Thank you for raising the issue.

We are in the process of overhauling our tutorials based on an upcoming release. These changes will be available in the coming weeks.

I will be sure to update the ticket.

Thank you for your patience.

**Comment by i353590** [comment]
hello,

Thanks for the update.
I see the document is still not updated. Could you please let us know the exact dates by when we can expect it to be fixed?

Thanks,
Shubham

**Comment by thecodester** [comment]
@sandeep-tds Can you update us?

**Comment by sandeep-tds** [comment]
Hi @NidhiMurkute 

The updated tutorial has been released, can you please verify the changes and update the ticket?

Thank you so much for your support.

Warm Regards
Sandeep T D S

**Comment by NidhiMurkute** [comment]
I have verified the changes. The tutorial is updated, hence closing the ticket.
