### ISSUE TITLE
Set Up SAP Mobile Cards

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5809]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-setup.html

Please specify the step you are referring to : Step 3: Get familiar with available configurations
Change of screenshot
Expected result: In Mobile connectivity screen under Actions there are two options available
![image](https://user-images.githubusercontent.com/50734023/92608866-7d27c100-f2d3-11ea-824c-6f5cf280805f.png)

Actual result: There are three options
![image](https://user-images.githubusercontent.com/50734023/92608926-8fa1fa80-f2d3-11ea-9d16-04ac007476b2.png)

Landscape label: trail1 & trail2
Scenario label: SCPTest-mcard

**Comment by sandeep-tds** [comment]
Thank you for raising the issue. 

We are in the process of overhauling our tutorials based on an upcoming release. These changes will be available in the coming weeks. 

I will be sure to update the ticket.

Thank you for your patience.

**Comment by MichaelCzcz** [comment]
@sandeep-tds Any updates?

**Comment by sandeep-tds** [comment]
Hi @NidhiMurkute 

The updated tutorial has been released, can you please verify the changes and update the ticket?

Thank you so much for your support.

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
