### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5810]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Please specify the step you are referring to : Step 9: Test generic handlers with Postman
Change of screenshot : 
Expected result: 
![image](https://user-images.githubusercontent.com/50734023/92610100-f378f300-f2d4-11ea-9e44-ab8b0b1836c6.png)

Actual result: In postman after click on Import File get the screen to upload the files and then Import button appears.
![image](https://user-images.githubusercontent.com/50734023/92610146-012e7880-f2d5-11ea-898b-e57fdf2da728.png)

![image](https://user-images.githubusercontent.com/50734023/92610159-055a9600-f2d5-11ea-967a-b0dc8ad1de10.png)

Landscape label: trail1 & trail2
Scenario label: SCPTest-banode

**Comment by iwonahahn** [comment]
The behavior is different for Mac and Windows. I don't see any reason to add more screenshots here, as the user interfaces for both operating systems are self-explanatory. I will extend the sentence and say: `Click on **Choose Files** and select the file that you've saved before or add it per drag & drop  directly.`

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
