### ISSUE TITLE
Build Your First Chatbot with SAP Conversational AI

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5812]
Tutorial URL: https://developers.sap.com/tutorials/cai-bot-getting-started.html

Please specify the step you are referring to : Step 4: Fork intent

4. As mentioned, selected first intent, but there are more than 2 expression.The sentence can be changed accordingly.
Expected:
![image](https://user-images.githubusercontent.com/50734023/92627567-29c06d80-f2e9-11ea-9835-b61a70c4ab1e.png)

Actual: Got more than 2 expression.
![image](https://user-images.githubusercontent.com/50734023/92627910-a9e6d300-f2e9-11ea-9edd-0bf325fdc67d.png)

Scenario label : SCPTest-cai

**Comment by thecodester** [comment]
Mentioned that they may receive additional expressions

**Comment by NidhiMurkute** [comment]
Thank you. Since its resolved I am closing the issue.
