### ISSUE TITLE
Let Customers Ask Chatbot for Shipping Price

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5813]
Tutorial URL: https://developers.sap.com/tutorials/cai-bot-shipping-3-price-parcel.html

Please specify the step you are referring to : Step 5: Call API to show Google map
3.Add a step to click on Back button after webhook configuration.
Actual result:
![image](https://user-images.githubusercontent.com/50734023/92629494-00eda780-f2ec-11ea-8581-c9edef783158.png)

Scenario label : SCPTest-cai

**Comment by thecodester** [comment]
Added instruction to click Back

**Comment by NidhiMurkute** [comment]
Thank you. Since its resolved i am closing the issue.
