### ISSUE TITLE
Let Customers Ask Chatbot for Shipping Price

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5814]
Tutorial URL: https://developers.sap.com/tutorials/cai-bot-shipping-3-price-parcel.html

Please specify the step you are referring to : Step 8: Test the bot
Didn’t  show Cost value
Expected result:
![image](https://user-images.githubusercontent.com/50734023/92629718-5a55d680-f2ec-11ea-860c-c3aec6fcbc41.png)

Actual result:
![image](https://user-images.githubusercontent.com/50734023/92629799-78bbd200-f2ec-11ea-86d6-f5e7324ff4ce.png)

Scenario label : SCPTest-cai

**Comment by thecodester** [comment]
@NidhiMurkute  @MamathaKH I'd have to help you debug your bot -- we can do that if you want. Obviously, on my bot it works and it is possible I forgot something in the tutorial but I tested several times and it is also possible something is amiss in your bot. The UI is a little weird and sometimes does not save things properly.

Please be in touch so we can debug.

**Comment by thecodester** [comment]
I will close this as I haven't heard back from you. Feel free to contact me (offline).
