### ISSUE TITLE
Mention required capabilitites in the tutorial

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5816]
Hello,
landscape label: trial1
Sprint Label: SCPTest-2008A
Scenario Label: SCPTest-cloudin

For scenario: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html#e8ed63b4-fbc0-40e3-86e3-38e0bef214d7

Step 4.3: Now you are directed to the Integration Suite Launchpad. Choose Add Capabilities to activate the capabilities offered by Integration Suite. -> Let’s assume you have made your selection, so you now have to click Next.

Provide required capabilities name instead of "let's assume.." Also update the screenshot of capabilities added, because while referring to the screenshot, user will add just 2 mentioned capabilities and in later steps while adding Roles, he will face issues.

Here we need to add 3 capabilities, including the API one.

Please refer to attachment.
![image](https://user-images.githubusercontent.com/66831161/92681659-dd5a4980-f34b-11ea-89b4-3e50b8c5f669.png)

Thanks,
Shubham

**Comment by Vikramkulkarni01** [comment]
Hi @i353590  (Shubham)

Our intention is to leave the choice of capabilities selection to an end-user itself. 
There are chances of selecting all the capapbilities at a time and it might leads to provisioning issues. 

The reason for selecting open connectors along with CPI is is must while activating the integration suite. 
Our internal team is working towards improving this limitation. 

Regards, 
Vikram Kulkarni

**Comment by i353590** [comment]
Hello Vikram,

thanks for the update.
From the tutorial perspective, it is not mentioned anywhere in the later steps also which all capabilities to be added which needs to be mentioned clearly which all services are required to execute the scenario.

Also, could you please let me know what is the limitation that is there.?

Thanks,
Shubham

**Comment by Vikramkulkarni01** [comment]
Hi Shubham, 

We updated the tutorial with the selection of capability in detail. The screenshot also updated. 

Hence we are closing this issue.
