### ISSUE TITLE
Screenshot update required

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5817]
Hello,

landscape label: both
Sprint Label: SCPTest-2008A
Scenario Label: SCPTest-cloudin

For scenario: https://developers.sap.com/tutorials/cp-starter-integration-cpi-create-iflow.html
Step 2.2: Choose Add > Integration Flow.

update the latest screenshot!

OLD:
![image](https://user-images.githubusercontent.com/66831161/92684775-e51dec00-f353-11ea-8b35-f08d67579e84.png)

NEW:
![image](https://user-images.githubusercontent.com/66831161/92684856-10084000-f354-11ea-85d2-4d87f25c414c.png)

**Comment by Vikramkulkarni01** [comment]
Hi @i353590 (Shubham), 

Thanks for the feedback. 

I have already updated the same in QA and it will be available in production shortly. 

Regards, 
Vikram Kulkarni

**Comment by i353590** [comment]
Hello Vikram,

Thanks for the fix.

Regards,
Shubham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
