### ISSUE TITLE
update tutorial for adding new property

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5818]
Hello,

landscape label: both
Sprint Label: SCPTest-2008A 
Scenario Label: SCPTest-fabap

Scenario URL:
https://developers.sap.com/tutorials/cp-portal-cloud-foundry-gateway-connection.html#a48dd50f-47cb-481c-a796-e00dd6fd1255

Step 2.5: Enter the following Additional Properties depending on your scenario. Click the New Property button each time to add a new property.

while adding new properties in the destination, "sap-platform" will not be there in the list. user needs to manually add this.
Solution: Mention in the tutorial like for the others which are not available and needs to be added manually (Like HTML5.DynamicDestination  (enter this property manually as it is not available in the dropdown list)

please refer to the attchment:
![image](https://user-images.githubusercontent.com/66831161/92685753-02ec5080-f356-11ea-9ed0-cb847fc2aefd.png)

Thanks,
Shubham

**Comment by IrisSasson** [comment]
@LindsayBert  Hi Lindsay - can you add this comment to the tutorial?

Thanks
Iris

**Comment by LindsayBert** [comment]
Updated

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
