### ISSUE TITLE
Screenshot update required & Step numbering not proper

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5820]
Hello,

Landscape label: both
Sprint Label: SCPTest-2008A 
SCPTest-eboard

Scenario URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html#ae14368a-03fb-42fe-841b-e8d94b5dd98e

Step 2.1: Download the WorkflowManagementFLP.tar.zip from GitHub in your local file system and extract the zip.
again next step is Step 1 (In your web browser, open the SAP Cloud Platform Trial cockpit.)

Please update the Step numbers in order.

Also, Step 2.2:Choose SAP Business Application Studio.: Screenshot is outdated, Needs to be updated.!

OLD:
![image](https://user-images.githubusercontent.com/66831161/92689330-75602f00-f35c-11ea-9e66-4859ae6c350e.png)

New:
![image](https://user-images.githubusercontent.com/66831161/92689389-8f017680-f35c-11ea-9d9e-f89f633a7aeb.png)

Thanks,.
Shubham Agarwal

**Comment by ArchanaShukla** [comment]
This tutorial is updated for latest changes
@thecodester - please close the issue
