### ISSUE TITLE
Create a Web Front End with SAPUI5

### ISSUE THREAD

**Issue by vikasgith** [SAPDocuments/Tutorials#5821]
Group URL: https://developers.sap.com/group.cp-frontend-ui5-1.html

Hi,
Thanks for this content.
I have never used Visual Studio, so many menu options in Business Application Studio (BAS) are new for me.
I was using cloud neo WebIDE  trial.
And now I am learning BAS via cloud Foundry trial.
https://cxxxxxedtrial.us10cf.trial.applicationstudio.cloud.sap/index.html
1)	One doubt is in WebIDE to run an app, we used to select index.html file and click run.
Here in BAS, we have run configurations, and have multiple options here.
But what is the significance of Run Configurations.
Why is running an application more complicated in BAS, compared to WebIDE.
What advantages are we getting with these Run Configurations.

2)	If there is a structured documentation similar to https://sapui5.hana.ondemand.com for BAS and Fiori , it will be helpful.

3)	Also if there is an open sap course for BAS with Fiori development, it will be helpful.

4)	Importing Projects zip file  from Local Machine to Business Application Studio Fiori Dev Space

I have downloaded an app folder structure with contents as zip file from WebIDE (Neo trial cloud) to local Machine.Is it possible to import this zip file from Local Machine to BAS Dev Space.

Thanks,
Vikas

**Comment by raz-korn** [comment]
Hi @vikasgith ,

Thanks for your feedback. I'll try to answer your questions:

1. I find that Run Configurations in both products similar. I'm attaching a screenshot of the full run configurations settings from SAP Web IDE and you'll see the similarity. Saying that, user-friendly experience is a key concept in the products we deliver, and we'll see how BAS run configurations can be improved.

![image](https://user-images.githubusercontent.com/6040433/93241844-970f4b00-f78e-11ea-9c25-2f7e86336841.png)

2. A link to [SAP Fiori documentation](https://experience.sap.com/fiori-design/) is available in the link you provided.
BAS documentation will replace (or co-exist) with SAP Web IDE documentation. Specifically within the website you mentioned, you can currently find [SAP Web IDE documentation](https://sapui5.hana.ondemand.com/#/topic/13ced9493472408999143bc99bbb73b9).

3. An [CAP ](https://open.sap.com/courses/cp7)openSAP course was held earlier this year. An [SAP Fiori introductory](https://open.sap.com/courses/fiori3) openSAP course that used BAS was held earlier this year. I expect that a developer focused course will be held next year. Similarly, I expect additional courses per use-case to be held using BAS.

4. For this question, I'd like to point the following:
- We recommend using git source code management.
- One should be aware that there are multiple migration use-cases (Neo > CF, SAP Web IDE > BAS for ABAP runtime, SAP Web IDE > BAS for CF runtime, ...).
- Migration from SAP Web IDE to BAS for ABAP runtime - see blog [here](https://blogs.sap.com/2020/07/08/migrating-fiori-application-from-sap-web-ide-to-sap-business-application-studio/).

Uploading files (or folders) from local machine to BAS is done a bit differently than in SAP Web IDE. There are at least a couple of options:
- Drag & drop a zip file to BAS Explorer pane, then open a terminal in the right folder and use the zip command to unzip it.
- Unzip the project on the local machine and then drag and drop the project to the relevant location on BAS Explorer pane.

I'd like to re-iterate the recommendation to use git SCM.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
