### ISSUE TITLE
Add Missing step in the tutorial

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5822]
Hello,

landscape Label: both
Sprint Label: SCPTest-2008A 
Scenario Label: SCPTest-eboard

Scenario URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-businessrules.html

Step 2.1: Click Design icon and select Import Project from API Business API Hub.->

here, After clicking on Design icon, we first need to click on "import logo" (upload logo) then select "Import Project from API Business API Hub"
Add this step in the document.

thanks,
Shubham

**Comment by ArchanaShukla** [comment]
Changes have been adapted
@thecodester - close the issue
