### ISSUE TITLE
update document for deploying services

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5823]
Hello,

landscape Label: both
Sprint Label: SCPTest-2008A
Scenario Label: SCPTest-eboard

Scenario URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-businessrules.html

Step 3.3: Click Deploy to deploy rule services DetermineEquipmentRuleservice and EquipmentApprovalRuleservice.
the Statement says deploy the two services by clicking on 'deploy' , but we have to do it one-by -one and the next step (select SAP cloud platform) has to be done for both the services.
user may get stuck after clicking on deploy which one to select as he will try to deploy the services first and then look at next step.

Solution: provide better documentation like after clicking on deploy select SAP cloud platform

Thanks,
Shubham

**Comment by ArchanaShukla** [comment]
This is understandable in most the cases that you have to select the service, then the system to deploy. 
Please close this issue.
