### ISSUE TITLE
Create Service Keys for Document Information Extraction

### ISSUE THREAD

**Issue by FarozanFarman** [SAPDocuments/Tutorials#5824]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dox-service-instance-booster.html

Please specify the step you are referring to: 
Step 2: Get service keys:
4. Click Navigate to Service Key:

a) This message can be before the screenshot:
If you have more than one subaccount, the booster will choose automatically the correct subaccount and space, but this will require that you click Next twice and Finish once, before being able to see the Success pop-up box and click Navigate to Service Key.
b) Screenshots can be added to show the above steps:
![Screenshot (548)](https://user-images.githubusercontent.com/71028764/92689960-abea7980-f35d-11ea-85ed-0691eee7c725.png)
![Screenshot (550)](https://user-images.githubusercontent.com/71028764/92689970-b0af2d80-f35d-11ea-8cee-f0f727003661.png)

![Screenshot (551)](https://user-images.githubusercontent.com/71028764/92689989-b73da500-f35d-11ea-8ab0-e5429f25f58c.png)

Labels to be attached:
Landscape label: trail1
Sprint Label: SCPTest-2008A
Scenario Labels: SCPTest-docinfo

Thanks and Regards,
Farozan Farman

**Comment by Juliana-Morais** [comment]
Moved the note up (before Success dialog screenshot), as suggested. This issue can be closed.

**Comment by Juliana-Morais** [comment]
Moved the note up (before Success dialog screenshot), as suggested. This issue can be closed.
