### ISSUE TITLE
Set Up Process Visibility - remove & update screenshots

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5825]
Hello,

landscape Label: both
Sprint Label: SCPTest-2008A
Scenario Label: SCPTest-eboard

Scenario URL:https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-4-visibility.html

in addition to the pre-existing issue: 
https://github.com/SAPDocuments/Tutorials/issues/5673

Step 2.1 & step 2.2:
old screenshot has to be removed (Screenshot in step 2.1 should be removed and replaced with 2.2 since new screenshot is added at step 2.2. Also at step 2.2 attach one screenshot for selecting 'onboard' which has to be selected from pop up)

Solution: remove screenshot at 2.1, put screenshot of 2.2 at 2.1 & attach new screenshot while selecting onboard from pop-up at step 2.2

![image](https://user-images.githubusercontent.com/66831161/92691742-ad697100-f360-11ea-9dde-8c808993540b.png)

thanks,
Shubham Agarwal

**Comment by ArchanaShukla** [comment]
This is already fixed. Check the tutorial! 
@MichaelCzcz - please close this issue
