### ISSUE TITLE
Use Machine Learning to Extract Information from Documents

### ISSUE THREAD

**Issue by FarozanFarman** [SAPDocuments/Tutorials#5826]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dox-swagger-ui.html

Please specify the step you are referring to: 
Step 2: See list of document fields you can extract
2nd Screenshot needs to be updated:
Expected Result:
![image](https://user-images.githubusercontent.com/71028764/92691876-f3bed000-f360-11ea-92ba-5d990833361b.png)
Actual Result:
![image](https://user-images.githubusercontent.com/71028764/92691927-0802cd00-f361-11ea-95e7-d8285becc753.png)

Labels to be attached:
Landscape label: trail1
Sprint Label: SCPTest-2008A
Scenario Labels: SCPTest-docinfo

Thanks and Regards,
Farozan Farman

**Comment by Juliana-Morais** [comment]
The screenshot has been updated. This issue can be closed.

**Comment by Juliana-Morais** [comment]
The screenshot has been updated. This issue can be closed.
