### ISSUE TITLE
Use Machine Learning to Extract Information from Documents

### ISSUE THREAD

**Issue by FarozanFarman** [SAPDocuments/Tutorials#5828]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dox-swagger-ui.html

Please specify the step you are referring to: Step 6: See extracted fields
4.
Enter the clientId you used in the previous step (c_00, for example).

The above step is not there in the actual execution, so it has to be removed.

6. Click Execute.
The screenshot needs to be changed:
Expected Result: 
![image](https://user-images.githubusercontent.com/71028764/92692856-6f6d4c80-f362-11ea-8b7a-131652fe7886.png)
Actual Result:
![image](https://user-images.githubusercontent.com/71028764/92692893-7b590e80-f362-11ea-978d-400bfa99ee20.png)

Labels to be attached:
Landscape label: trail1
Sprint Label: SCPTest-2008A
Scenario Labels: SCPTest-docinfo

Thanks and Regards,
Farozan Farman

**Comment by Juliana-Morais** [comment]
The screenshot has been updated. This issue can be closed.

**Comment by Juliana-Morais** [comment]
The screenshot has been updated. This issue can be closed.
