### ISSUE TITLE
instaces processed - not getting updated

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5829]
Hello,

landscape Label: trail1
Sprint Label: SCPTest-2008A
Scenario Label: SCPTest-eboard

Scenario URL:https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html#427fcc75-2f8b-47f7-b7b5-eddd676e83c0
Step 5.1: In the SAP Fiori launchpad, open Monitor Visibility Scenarios application, click Process Data and Refresh to see the new batch of processed events.
 Instance processed is not getting updated even after completing the 'task' by clicking confirm in previous step.

Screenshots:
![image](https://user-images.githubusercontent.com/66831161/92693029-a4799f00-f362-11ea-8bcb-99020dc5fe40.png)

![image](https://user-images.githubusercontent.com/66831161/92693059-b22f2480-f362-11ea-9324-1b455e0abbe0.png)

thanks,
Shubham

**Comment by ArchanaShukla** [comment]
This issue might occur due to EU10 outage. As it passed in US10 which means there is no problem with the product or the scenario but at times EM fails to send the events to process visibility. This is a known and there is nothing that I can do here. 
@thecodester - please close the issue
