### ISSUE TITLE
Connect SAP Cloud Platform to Your SAP Gateway Demo System Account (ES5)

### ISSUE THREAD

**Issue by FarozanFarman** [SAPDocuments/Tutorials#5830]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-gateway-connection.html

Please specify the step you are referring to:
Step 2: Create destination to SAP Gateway Demo System:
6. Click Save.
The "SAVE" button is missing in the screenshot. Hence screenshot needs to be updated.

Expected Result:
![image](https://user-images.githubusercontent.com/71028764/92695775-99287280-f366-11ea-81f7-6734aca43184.png)

Actual Result:
![image](https://user-images.githubusercontent.com/71028764/92695809-a3e30780-f366-11ea-84ea-e0ba2f25604e.png)

Labels to be attached:
Landscape label: trail1, trail2
Sprint Label: SCPTest-2008A
Scenario Labels: SCPTest-fbizapp

Thanks and Regards,
Farozan Farman

**Comment by IrisSasson** [comment]
@LindsayBert Hi Lindsay - can you replace the screenshot as explained above?

Thanks!

**Comment by LindsayBert** [comment]
Updated

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
