### ISSUE TITLE
Set Up Business Application Studio for Mobile Technologies

### ISSUE THREAD

**Issue by vikasgith** [SAPDocuments/Tutorials#5833]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-bas-setup.html

'' Cloud Foundry Target : entering end point, email id and password"
While setting , Cloud Foundry Target, why do we need to enter 
1)	end point, 
2)	email id and 
3)	password again.
Because the email id and password are used for logging to the system, i.e
https://WORKSPACE.eu10cf.trial.applicationstudio.cloud.sap/index.html
End point is there in this url.
So why do we need to enter the information again, as this information is already with system.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
