### ISSUE TITLE
Create a Service Consumption Model

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#5840]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-create-service-consumption-model.html

The Prerequisites mention this limitation:

> IMPORTANT: This tutorial cannot be completed on a trial account

I would suggest the following solution for this issue: 

I've created a CAP based mock service for the /DMO/API_TRAVEL_U_V2 OData service in this repository: [api-travel-mock](https://github.com/gregorwolf/api-travel-mock). A sample service is reachable at:

https://ba932c42trial-dev-api-travel-mock-srv.cfapps.eu10.hana.ondemand.com/sap/opu/odata/DMO/API_TRAVEL_U_V2/

Maybe the tutorial can be adjusted so that everyone who want to try out can deploy his own mock service or SAP could provide an own mock server or perhaps provide the mock via api.sap.com.

**Comment by julieplummer20** [comment]
Hi Gregor,
That's a nice idea, thanks. The original purpose of the mission was to teach connectivity usingthe Service Consumption Model simply as a means to that end. However, I will discuss this option with the team.
BR Julie.

**Comment by julieplummer20** [comment]
Hi Gregor, 
It occurred to me afterwards: Andre has already written a really thorough blog post about using the service consumption model with the trial version: [How to call a remote OData service from the trial version of SAP Cloud Platform ABAP environment](https://blogs.sap.com/2019/10/20/how-to-call-a-remote-odata-service-from-the-trial-version-of-sap-cloud-platform-abap-environment/). 
Perhaps I could link to it. I can also mention your CAP-based mock service for those who are interested.
BR Julie.

**Comment by gregorwolf** [comment]
Hi @anfisc,

maybe you can reference my mock service in your Blog?

Best regards
Gregor

**Comment by anfisc** [comment]
Which blog 🤔?

------‐-----------------------------------

sent from my mobile...

André Fischer

SAP Champion

Product Manager – SAP Cloud Platform ABAP Environment & SAP Gateway

Technology & Innovation Platform

SAP SE
Dietmar Hopp Allee 16
D-69190 Walldorf
T +49 6227 7-41402
F +49 6227 78-41615
M +49 160 908 19872
mailto:andre.fischer@sap.com
www.sap.com<http://www.sap.com>

________________________________

**Comment by julieplummer20** [comment]
This one: [How to call a remote OData service from the trial version of SAP Cloud Platform ABAP environment.](https://blogs.sap.com/2019/10/20/how-to-call-a-remote-odata-service-from-the-trial-version-of-sap-cloud-platform-abap-environment/). (see above)

**Comment by anfisc** [comment]
There is no need for that.
There are two services available on ES5 with hard coded credentials so that they do not require any authentication.
EPM Products
https://sapes5.sapdevcenter.com/sap/opu/odata/sap/ZPDCDS_SRV/
EPM SalesOrders with Items
https://sapes5.sapdevcenter.com/sap/opu/odata/sap/ZSOCDS_SRV/
Agencies for the flight model
https://sapes5.sapdevcenter.com/sap/opu/odata/sap/ZAGENCYCDS_SRV/
So it would be possible to use those.

**Comment by julieplummer20** [comment]
Hi Gregor,
Thanks for all the feedback. Is it fair to say  that this issue is now closed?
Best wishes,
Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
