### ISSUE TITLE
Create a Remote Client Proxy

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#5841]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-a4c-create-proxy.html

Step 7: Define constants

I would suggest to exchange the screenshot with this one as the constants must be in the PUBIC section:

![Screenshot 2020-09-11 at 18 34 18](https://user-images.githubusercontent.com/2639535/92950744-79c04100-f45d-11ea-9a16-45c0e28a54ca.png)

**Comment by julieplummer20** [comment]
Thanks. Done.
I do check the code, but sometimes, I have to reconstruct the screenshots afterwards.
BR Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
