### ISSUE TITLE
Setup SAP HANA, express edition - Prepare for Machine Learning (AWS / EML)

### ISSUE THREAD

**Issue by AnOffe** [SAPDocuments/Tutorials#5846]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aws-eml-04.html
Step 5

Hello,
I can see the EML Package in my AFL_AREAS but not in AFL_PACKAGES or AFL_FUNCTIONS.
Updating the EML Package says Installation is up-to-date.
What can I do?
I am using HANA Express 2.0 SPS 04 on premise

Regards,

Andre

**Comment by MichaelCzcz** [comment]
@jarjarbentley Please respond.

**Comment by jarjarbentley** [comment]
Have you dowloaded the eml.tgz SAP HANA External Machine Learning Library Package per this: tutorial ((https://user-images.githubusercontent.com/41022600/98599198-9c2dd980-22a9-11eb-8fee-631fdf1b47c3.png)
)

**Comment by MichaelCzcz** [comment]
@AnOffe Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
