### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by rk48** [SAPDocuments/Tutorials#5848]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to
Step 3: Make changes to the UI

There are no Entity Sets

How can I add OData service to a project?

**Comment by raz-korn** [comment]
Hi @rk48 ,

Can you share a screenshot?

Regards - Raz

**Comment by rk48** [comment]
Message: add odata service to the project

![Screenshot_2](https://user-images.githubusercontent.com/10586865/94313432-621da800-ff87-11ea-9c2a-2e225aa88419.png)

How could I do it?
Thank you in advance!

**Comment by raz-korn** [comment]
Hi @rk48 ,

The following is assuming that step 1 of the [tutorial](https://developers.sap.com/tutorials/appstudio-fioriapps-create.html) was followed. See step 1.8 where ES5 is configured as a data source for the application. 

1. It looks like there are two lists in the view. The one with Element ID "item0_160..." should probably be removed. The view should remain with a single list where the Element ID is "item0".

2. See step 3.3 and the description at the top about the breadcrumb to make sure the focus is on the right component, then click the "Bind" icon, and follow the rest of the steps.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by rk48** [comment]
Thank you very much!
