### ISSUE TITLE
Get Started with SAP Cloud Platform Rapid Application Development by Mendix

### ISSUE THREAD

**Issue by roger-lennon** [SAPDocuments/Tutorials#5849]
Tutorial URL: https://developers.sap.com/tutorials/mendix-onboarding.html

Please specify the step you are referring to
Step 2 unable to enable this in trial cloud account.  The documentation is not clear and this is been a bad user experience trying to follow this tutorial.

**Comment by Paolaufer** [comment]
Hi Roger,
Thank you for your feedback.
I will look into why you cannot perform step 2.
Any specific way we could change the documentation to make it clearer/easier?
Regards,
Pao

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
