### ISSUE TITLE
Set Up the Manage Rule Projects Application

### ISSUE THREAD

**Issue by raz-korn** [SAPDocuments/Tutorials#5852]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules03-setup-mrp.html
See question in [SAP Community](https://answers.sap.com/questions/13141516/authorization-issue-1.html)

Please specify the step you are referring to
Step 5

**Comment by VandanaVasudevan** [comment]
Hi,

We are in the process of updating the tutorials as per the new changes. The updated tutorials will be available soon.

Best Regards,
Vandana

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
