### ISSUE TITLE
Develop an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by vikasgith** [SAPDocuments/Tutorials#5856]
Group URL: https://developers.sap.com/group.appstudio-fiori.html
It would have been better, if a simple UI5 application with BAS was shown without database connectivity.
One similar to https://github.com/SAP/openSAP-ui5-course/tree/ui51/w1u5/
After a non DB application, then show a DB connection app.

**Comment by Paolaufer** [comment]
Hi,
We will look into this.
Thank you for the suggestion.

Regards,

Pao

**Comment by Paolaufer** [comment]
Hi,
Thanks for the suggestion. We will put it on our roadmap for future tutorials.

Regards,

Pao

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
