### ISSUE TITLE
Develop a Business App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#5857]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-cap-app.html

Step 1: Create new CAP project

The text was changed from "New project from template" to "Create project from template". Also the Screenshot needs to be changed:

![Screenshot 2020-09-15 at 07 57 26](https://user-images.githubusercontent.com/2639535/93171326-2bdf5d80-f729-11ea-9b86-2ad877432b1c.png)

Also the template name was changed from "CAP Project" to "@sap/cap":

![Screenshot 2020-09-15 at 07 59 49](https://user-images.githubusercontent.com/2639535/93171471-74971680-f729-11ea-84bd-44a8d186eeee.png)

**Comment by Paolaufer** [comment]
HI,
I will update the Welcome page screenshot, but the project is still called CAP Project.
Can you tell me which landscape you are using?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by gregorwolf** [comment]
The Screenshot wasn't changed yet. And as you see in the screenshot the template name is "@sap/cap Project"

**Comment by gregorwolf** [comment]
Hi @Paolaufer,

now I know how to get the template that is named "CAP Project", I have to install the generator @sap/generator-cap-project:

![Screenshot 2020-10-03 at 17 13 28](https://user-images.githubusercontent.com/2639535/94995030-c3530600-059b-11eb-937b-554fb5c5d843.png)

The screenshot I've posted initially is from a freshly started dev space.

Best regards
Gregor
