### ISSUE TITLE
Create a Destination for the Northwind OData Services in the Neo Environment

### ISSUE THREAD

**Issue by mario-fliegner** [SAPDocuments/Tutorials#5858]
Tutorial URL: https://developers.sap.com/tutorials/hcp-create-destination.html

I can't see the "Access Neo Trial" anymore? If I create the Northwind service under the Cloud Foundry, it does not show up later in the select box for "Service URL" in the WebIDE (in this step https://developers.sap.com/tutorials/odata-03-webide-odata-features.html#7fa7cf31-eaf2-4126-9e5f-44a17ce38035).

**Comment by IObert** [comment]
Hi @mario-fliegner,

I'm afraid this tutorial still shows an old way of achieving the result. We are currently in the progress of switching all Web IDE tutorials to the new Business Application Studio. We'll notify you on this issue once the tutorial has been migrated.

**Comment by MichaelCzcz** [comment]
@qmacro What is the status here? Has the tutorial been migrated and can I close this issue?

**Comment by qmacro** [comment]
No. The migration activities are taking a lower priority right now due to other work. Right now we cannot give an indication as to when they will be complete, sorry about that.

**Comment by qmacro** [comment]
I'll close this issue while we work on the new content (which will also allow us to deprecate/archive the tutorial group to which this tutorial belongs). Thanks for your patience!
