### ISSUE TITLE
Use SAP Edge Services to Automate Creation of Work Order Based on IoT Data (part 1, configuration)

### ISSUE THREAD

**Issue by prateekjais** [SAPDocuments/Tutorials#5859]
Tutorial URL: https://developers.sap.com/tutorials/iot-edge-plant-maintenance-1.html

Please specify the step you are referring to 
Prerequisite Edge services on-boarding guide URL not working
![image](https://user-images.githubusercontent.com/37372220/93179893-f439db00-f753-11ea-93ee-cf16c04382af.png)

**Comment by MichaelCzcz** [comment]
URL is working:
![image](https://user-images.githubusercontent.com/57144076/95714993-61fcf800-0c69-11eb-88e5-3f5bdb3861e6.png)
