### ISSUE TITLE
Develop an SAPUI5 App for a Portal Site (Cloud Foundry)

### ISSUE THREAD

**Issue by ssunsband** [SAPDocuments/Tutorials#5870]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-create-app.html

Please specify the step you are referring to

Hi Lindsay Bert
I have been very helpful in your blog.
However, I have one problem that has not been resolved.
Please check the url below.
https://answers.sap.com/questions/13139075/register-app-into-poral-sitecloud-foundry.html
What should I add to the app to run?
I desperately need your help.
Thank you.

**Comment by IrisSasson** [comment]
Hi 
Please follow the Launchpad tutorials instead at: https://developers.sap.com/mission.portal-cf.html

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
