### ISSUE TITLE
Add a Web Dynpro ABAP App to Your SAP Cloud Platform Launchpad Site

### ISSUE THREAD

**Issue by singhmanishekhar** [SAPDocuments/Tutorials#5872]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-webdynpro-app.html

Please specify the step you are referring to
Step 2 
2.
In the PROPERTIES tab.

I set up a destination but It is not visible as a system in the step.
![Issue](https://user-images.githubusercontent.com/7202254/93331870-91713e00-f83e-11ea-94f3-07273b44d0b1.png)

Can you please check and Let me know what is the cause of the issue.

**Comment by IrisSasson** [comment]
Please refresh the browser

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
