### ISSUE TITLE
Deploy Your First SAPUI5 App to Cloud Foundry Step 6

### ISSUE THREAD

**Issue by c64x86** [SAPDocuments/Tutorials#5875]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-sapui5-create.html

Referring to STEP  **6**

App is not starting. => Not Found

Request URL: https://c83b32fbtrial-dev-tutorial-approuter.cfapps.eu10.hana.ondemand.com/
Request Method: GET
Status Code: 404 Not Found

**Comment by IObert** [comment]
Hi,
I just tested it and everything works as expected. Is it possible that you skipped step 4?

**Comment by c64x86** [comment]
I will have look. But 99% I did not skip

**Comment by c64x86** [comment]
Hi,
i checked my actions and i did not skip step4. But i will delete all and do the Toturial again 👍 
I will give Feedback

**Comment by IObert** [comment]
Thanks and sorry for the inconvenience. I'll keep the issue open for now until I hear back from you.

**Comment by c64x86** [comment]
Hi,

I now have done it again. In advance - it was my fault. Here is what was my problem:

In Step 4 i did not change the **tutorial-approuter/xs-app.json**
but the **xs-app.json** from the **webapp folder**.

While repeating the tutorial i noticed my fault.
Thanks for your Support

greetings
Wolfgang

**Comment by IObert** [comment]
Awesome! I'm glad it works now
