### ISSUE TITLE
Maintain a Communication Arrangement for Inbound Communication

### ISSUE THREAD

**Issue by wander-rodrigues** [SAPDocuments/Tutorials#5876]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

Please specify the step you are referring to
Step 3 - Create communication user 

I cannot see the Tile "Maintain Communication User"
System URL:  https://e478ca1c-d502-4b7f-a72b-78a4f5447844.abap.eu10.hana.ondemand.com
![image](https://user-images.githubusercontent.com/19672325/93384648-823cc100-f83b-11ea-9d8d-fdf0a67a09e4.png)

**Comment by mervey45** [comment]
Hi @wander-rodrigues , 

in which system are you trying this out? In trial this won't work, you need to have a licensed user.

Best regards, 
Merve

**Comment by julieplummer20** [comment]
Hi Michael,
Looks as if Merve has already answered this, and that the user is using a Trial version of SAP CP, ABAP Environment.
Can you please unassign me, unless the user comes back to us?

Then I will get on with the open issues.
Thanks Julie.

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

we can close this ticket. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
