### ISSUE TITLE
Enhance Behavior With Action and Validation

### ISSUE THREAD

**Issue by jvasquezm79** [SAPDocuments/Tutorials#5881]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-behavior-action.html

Hi, I have an error in class implementation method "validateCustomer" line:

APPEND VALUE #(  mykey = ls_travel-mykey ) TO failed.

the error is: Description	Resource	Path	Location	Type
"FAILED" is not an internal table. "OCCURS n" specification is missing.

What I can do?

**Comment by julieplummer20** [comment]
Hi jvas,
Can you try simply copying and pasting the code from steps 1.2, 2.2, 4.2, 4.4 once again?
Sometimes that helps.
If that fails, please just let me know. I will then pass this on internally, and get back to you.
BR Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
