### ISSUE TITLE
Integrate SAPUI5 App for a Portal Site (Cloud Foundry) Issue

### ISSUE THREAD

**Issue by ssunsband** [SAPDocuments/Tutorials#5883]
Hi Expert

2 days ago I asked this question.(https://github.com/SAPDocuments/Tutorials/issues/5870)
I got the answer and followed it.(https://developers.sap.com/mission.portal-cf.html)
but I can't add a app. The problem is, the add to my content button doesn't work.
The photo could not be uploaded, so it is replaced with a URL.
https://answers.sap.com/questions/13143548/integrate-sapui5-app-for-a-portal-site-cloud-found.html
Do I have permissions I haven't set up?
Thank you

**Comment by MichaelCzcz** [comment]
@IrisSasson Please respond!

**Comment by IrisSasson** [comment]
Hi

The reason that you don't see the contnet is that you used the "Stand alone app router" and not the "Managed app router".
Please create the app again with Managed app router (the selection of managed app router is done using this tutorial: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html on step 5.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
