### ISSUE TITLE
Send Multiple OData Requests in Batch Mode with SAP Cloud SDK's Virtual Data Model

### ISSUE THREAD

**Issue by prakash13t** [SAPDocuments/Tutorials#5884]
Tutorial URL: https://developers.sap.com/tutorials/cloudsdk-js-odata-batch-changeset.html

Can we have Java version of this tutorial.

Thanks,
Naga

**Comment by Emdee89** [comment]
Please see if this answer helps you a bit: https://answers.sap.com/questions/13143122/odata-batch-with-cloud-sdk-for-java.html?childToView=13147245#answer-13147245

**Comment by MatKuhr** [comment]
Check out [this documentation](https://sap.github.io/cloud-sdk/docs/java/features/odata/use-typed-odata-v2-client-in-sap-cloud-sdk-for-java#batch-requests) that was created in the mean time. Even though it's not a tutorial it should help you further I believe.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
