### ISSUE TITLE
Explore Data Rules and Rulebooks with Metadata Explore in SAP Data Intelligence, Trial Edition

### ISSUE THREAD

**Issue by OneConsutlantsDemo** [SAPDocuments/Tutorials#5885]
Can you please let know where the rules are executed on the SAP Cloud or on the Source DB engine? 
Push down limitation of the rules are not clearly defined in the documentation..

Thanks

**Comment by dimvor** [comment]
Hi, this GitHub is for reporting technical issues with the tutorials found at developers.sap.com for general product related questions please post to https://answers.sap.com/tags/73555000100800000791

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
