### ISSUE TITLE
Install the Cloud Foundry Command Line Interface (CLI)

### ISSUE THREAD

**Issue by miberxx** [SAPDocuments/Tutorials#5887]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-download-cli.html

Please specify the step you are referring to

you need to update the screenshots in your tutorials they are completely outdated

**Comment by IObert** [comment]
You are absolutely right, the screenshots have been outdated for a while now.
The changes should be live within the next few minutes.

 Thanks for letting us know.
