### ISSUE TITLE
Set Up Workflow Management in Cloud Cockpit

### ISSUE THREAD

**Issue by js1972** [SAPDocuments/Tutorials#5888]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html

Please specify the step you are referring to:

This tutorial mission is for Neo. On developers.sap.com I can not find any tutorials for the workflow service on cloud foundry? Can you please point them out - if there are any.

Maybe it would also be possible to mark these tutorials for new-only so that developers can easily tell and filter them out of results.

**Comment by ArchanaShukla** [comment]
@js1972 - The above mentioned tutorial link is for Cloud Foundry. There is soon going be a Workflow tutorial on Cloud Foundry. Stay Tuned! 

@MichaelCzcz - Please close this issue.
