### ISSUE TITLE
Embed an SAP Analytics Cloud Story in a Simple Web App

### ISSUE THREAD

**Issue by JackShepard98** [SAPDocuments/Tutorials#5894]
Tutorial URL: https://developers.sap.com/tutorials/sac-embed-story.html

Please specify the step you are referring to: Step 2 or 3

Hi,

Is there any way to catch an event  or check when the user logs out (from inside the iframe or directly from the sap website in another tab).
This would be useful in order to display a message like "You were logged out, refresh page to log in again".

Thanks

**Comment by mattschwarz-sap** [comment]
Hi @JackShepard98 

the responsibility for this tutorial has changed recently. The new responsible would not be available before first week of October this year. Is it ok for you to postpone this issue until then?

Thanks & Best Regards,
Matthias

**Comment by MichaelCzcz** [comment]
@mattschwarz-sap If you are no longer the tutorial's owner, could you please let me know who the new owner is?

**Comment by mattschwarz-sap** [comment]
Hi @MichaelCzcz , the new owner is Benedikt Michligk. Benedikt owns both of the tutorials listed. However, I assume in the tutorials this is not updated.
https://developers.sap.com/tutorials/sac-embed-story.html
https://developers.sap.com/tutorials/sac-embed-story-display-parameters.html

**Comment by JackShepard98** [comment]
> Hi @JackShepard98
> 
> the responsibility for this tutorial has changed recently. The new responsible would not be available before first week of October this year. Is it ok for you to postpone this issue until then?
> 
> Thanks & Best Regards,
> Matthias

Hi @mattschwarz-sap ,

That's ok. Thanks.

**Comment by maxta2002** [comment]
Hi @JackShepard98 sry for the late response. I want to give you an short update. I am in contact with the Colleagues who own this topic. I can give you an answer within the next week. 

Best Regards,
maxta2002

**Comment by MichaelCzcz** [comment]
@maxta2002 Any updates?

**Comment by maxta2002** [comment]
@JackShepard98 Hi, sorry it took quite longe. Iam sorry but the functionality you asked for is actually not available.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
