### ISSUE TITLE
Connect to HubSpot

### ISSUE THREAD

**Issue by mrudula1412** [SAPDocuments/Tutorials#5895]
Tutorial URL - https://developers.sap.com/tutorials/cp-apim-openconnectors-connect-hubspot.html

Issue in step 2 - Not able to subscribe open connectors in trial account

![image](https://user-images.githubusercontent.com/70740789/93866143-ea305300-fce4-11ea-8420-c0a2fd6cd902.png)

**Comment by shilpavij** [comment]
Dear colleague,

The standalone Open Connectors service has been removed from the trial. Kindly ignore the deletion steps and proceed with the enablement of the Integration Suite. You would get a trial account for OCN as part of it.

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
