### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by bipinm** [SAPDocuments/Tutorials#5896]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html

Please specify the step you are referring to 1.4 (Browse to the downloaded events file location, select the file and click Import)

Step did not work for me, got an error wrt. missing permissions. Had to create a new Role Collection and added below roles as i was not sure which one to use.

PVAdmin	PVAdmin	pvreuseservice!b12353		
PVDeveloper	PVDeveloper	pvreuseservice!b12353		
PVEventSender	PVEventSender	pvreuseservice!b12353		
PVOperator	PVOperator	pvreuseservice!b12353		
PVTenantOperator	PVTenantOperator	pvreuseservice!b12353

After this, it shows message "Events are imported successfully." but when using filter option (Process Definition ID = onboard) as specified in step 1.5, i see no results

**Comment by ArchanaShukla** [comment]
Thanks for letting us know of the missing roles. We will improve the tutorial.

**Comment by ArchanaShukla** [comment]
The new roles have been added in the Workflow Management role collection. 
You should not be getting the issue anymore.

@MichaelCzcz - please close the issue.
