### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by P063978** [SAPDocuments/Tutorials#5897]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

Step 1: Launch Application Generator
When following the instructions and selecting the Application Generator Launch function ig et a Yeoman UI Tab which informs me "Could not fund any generators."

The installed extensions pane clearly shows that the SAP Fiori Extension Pack is installed and enabled. So why does the Application Generator fail to launch?

![image](https://user-images.githubusercontent.com/71743823/93963318-f2ee5b00-fdb0-11ea-9cc1-175b47d7fba8.png)

**Comment by cjbernal** [comment]
Hi there,

Sorry to hear you're having trouble. Would you mind taking a look at FAQ #2 from this document? https://help.sap.com/viewer/42532dbd1ebb434a80506113970f96e9/Latest/en-US

Please let us know if that works or you need something else.

Kind regards,
Conrad

**Comment by P063978** [comment]
Hi,
   This gave me a generator but its the Fiori Elements generator, though that does have a list report objects template. So I am assuming that now we default to the Fiori Elements generator. Thanks for the help :)
