### ISSUE TITLE
Develop an SAPUI5 App for a Portal Site (Cloud Foundry)

### ISSUE THREAD

**Issue by burreo** [SAPDocuments/Tutorials#5898]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-create-app.html

The tutorial seems to be outdated and needs to be updated or replaced.
e.g. For SAP UI5 development we use now Business Application Studio and not WebIDE anymore.
Also there is a SAP managed Approuter now available.
My colleagues just released a new mission about this:
https://discovery-center.cloud.sap/missiondetail/3239/3325

**Comment by IrisSasson** [comment]
Correct
You should follow this mission insteadhttps://developers.sap.com/mission.portal-cf.html
@MichaelCzcz - can you hide this old tutorial?

**Comment by burreo** [comment]
@IrisSasson I guess there is more cleanup needed since the tutorial is also referenced from a mission.
I also contacted Andreas Hirche and he told he is working stepwise on the updates.

**Comment by LindsayBert** [comment]
Hi

Not sure why this is assigned to me.  Iris seems to have replied.

Is there an action item for me?


Thanks
Lindsay

**Comment by MichaelCzcz** [comment]
@LindsayBert It didn't seem to be resolved, yet. Can I close the issue?

**Comment by LindsayBert** [comment]
Hi  - as far as I can see, it can be closed. All tutorials were updated.
