### ISSUE TITLE
Add an Onboarding Flow

### ISSUE THREAD

**Issue by ghost** [SAPDocuments/Tutorials#5900]
Tutorial URL: https://developers.sap.com/tutorials/cp-sdk-android-flows-onboard.html

Please provide a tutorial that uses flowv2. 😒
This is soo frustating to be stuck with no guidance!

**Comment by MichaelCzcz** [comment]
@jarjarbentley Please respond.

**Comment by jarjarbentley** [comment]
@flyingfish162 can you reply?

**Comment by flyingfish162** [comment]
We will publish the tutorials about flowv2 in the next few months.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
