### ISSUE TITLE
Create Behavior and Service in SAP Cloud Platform ABAP Environment

### ISSUE THREAD

**Issue by sagarvss11** [SAPDocuments/Tutorials#5906]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-behavior-definition.html

Please specify the step you are referring to 
Step 2 behavior implementation: 
There are lot of syntax errors while implementing the Class.
 CLASS lcl_handler DEFINITION INHERITING FROM cl_abap_behavior_handler is giving errors!

Please clarify how to implement the class that I created for Behavior Implementation.

**Comment by mervey45** [comment]
Hi @sagarvss11 ,

please use following: 
CTRL + F  inside your coding (for e.g. inside your abap class)-> find XXX and replace with your number -> replace all.

It seems like you didn't replaced all XXXs with your number. Try it out again please. If you still face issues, conctact us again. 

![image](https://user-images.githubusercontent.com/27953324/95579786-8624c300-0a36-11eb-911e-e36a11bd5a4b.png)


Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
