### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by Abi1984** [SAPDocuments/Tutorials#5909]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

Please specify the step you are referring to

Cloud Integration cannot be activated.The following error message is issued:

Error P002: Activation of Cloud Integration capability has failed. Please try again later. If the issue persists, please send your application URL and details of the error message to cpitrialfeedback@sap.com

Asked several times at the e-mail address mentioned, still no response

**Comment by Vikramkulkarni01** [comment]
Hi @Abi1984, 

Thank you for reaching out to me. 

Sorry for the inconvenience caused. 

Could you please unsubscribe the integration suite and resubscribe it back? Please ensure that you have added the correct roles. 

If this doesn't work, please create a new subaccount and subscribe to the Integration suite. 

Please let me know how it works for you?

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
