### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by vbalko** [SAPDocuments/Tutorials#5910]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html

In the first step, when user should import sample events, it fails, because user dont have required roles for that action.
I had to add **PVEventSender** and **PVTenantOperator** roles in order to successfully import example data. 
It should be mentioned, that you have to assign additional roles.

**Comment by ArchanaShukla** [comment]
Thanks for letting us know. We will improve the tutorial

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
