### ISSUE TITLE
Create an API Proxy

### ISSUE THREAD

**Issue by mrudula1412** [SAPDocuments/Tutorials#5911]
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-create-api.html

Please specify the step you are referring to -Step 6: Discover the services

We are getting below error when we click on discover option.
However,credentials are correct and I am able to open gateway system separately from browser with those credentials.
Please check and suggest.

![image](https://user-images.githubusercontent.com/70740789/94372794-7051fc80-011e-11eb-8348-011492a42fe6.png)

**Comment by shilpavij** [comment]
Your credentials are wrong. Check password and User

Regards
shilpa

**Comment by mrudula1412** [comment]
Hi Shilpa,

Thanks for your reply.
I have maintained below details in API Provider and I am able to open SAP gateway demo system in browser with the same credentials which I have maintained here.
Could you please check and suggest if there is anything wrong in below screenshots.

![image](https://user-images.githubusercontent.com/70740789/94411118-d29a1400-0195-11eb-8b6c-7fc15b478d12.png)
![image](https://user-images.githubusercontent.com/70740789/94411318-10973800-0196-11eb-8f58-e0c8bcbec432.png)

**Comment by mrudula1412** [comment]
Hi Shilpa,

I again clicked on discover option and now I am getting GWSAMPLE_BASIC option in next tab.
looks like there is some issue with sap gateway demo system.
Thanks for your support.
