### ISSUE TITLE
Consume the API Proxy in SAP Web IDE

### ISSUE THREAD

**Issue by mrudula1412** [SAPDocuments/Tutorials#5912]
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-webide-int.html

Please specify the step you are referring to: Step 8

In Step 8 it's mentioned with an exclamation mark that we should use the Web IDE and not the full stack version. However in the Demo instance we only have the Full Stack version available.
I proceeded with the Full Stack version and face an issue on stage 13.
what should I do to make it work ?

![image](https://user-images.githubusercontent.com/70740789/94485077-02c7ce00-01fb-11eb-89bb-d46daa8cabfb.png)
The destination which I am using in above screenshot is showing me below response.

![image](https://user-images.githubusercontent.com/70740789/94485324-63efa180-01fb-11eb-827c-c1908bf05227.png)

Also,I have GWSAMPLE_BASIC API and product in API Portal.
![image](https://user-images.githubusercontent.com/70740789/94485724-fe4fe500-01fb-11eb-87fe-011660c54580.png)
![image](https://user-images.githubusercontent.com/70740789/94485894-3b1bdc00-01fc-11eb-9f8a-df5953b7ace7.png)

**Comment by shilpavij** [comment]
Web IDE mission is decommissioned as of now because it's changed to Business Application Studio and waiting for the development teams to confirm that the integration and connections work at APIM side too with the new BAS.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
