### ISSUE TITLE
Set Up SAP Business Application Studio for Development

### ISSUE THREAD

**Issue by renejeglinsky** [SAPDocuments/Tutorials#5913]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-onboarding.html

Hi Raz,

I think the first steps are not needed anymore in trial. One can access the Business Application Studio right from the start from the _Quick Tool Access_ section without subscribing or assigning roles.
Could you check that? It worked for me with a new trial account and I also heard that from others.

Thanks,
René

**Comment by raz-korn** [comment]
Hi @renejeglinsky ,
That's correct. For new trial accounts, BAS setup is automated and the subscription si auto-enabled.
I plan to update the tutorial accordingly.
Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
