### ISSUE TITLE
Set Up SAP Fiori Tools in Your Development Environment

### ISSUE THREAD

**Issue by Hansi60** [SAPDocuments/Tutorials#5914]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-vscode-setup.html

Please specify the step you are referring to:

Visual Studio Code Extension fpr sap fiori tools

Why is this extension not available in Eclipse Open VSX so i can use it in Eclipse Theia.
Not in that repository already ?

**Comment by theStiggySpd** [comment]
Hi @Hansi60  
As the first version, SAP Fiori tools is available in Visual Studio Code and SAP Business Application Studio which is based on Eclipse Theia IDE. You can finish the tutorials using SAP Business Application Studio too. We are currently working to bring more capabilities to our tooling. In the future, we may plan on adding support to other platforms.
Thanks a lot for your feedback

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
