### ISSUE TITLE
View Usage Data of Your Website

### ISSUE THREAD

**Issue by mrudula1412** [SAPDocuments/Tutorials#5916]
Tutorial URL: https://developers.sap.com/tutorials/cp-webanalytics-view-usage-data.html

Please specify the step you are referring to:
step 2-There is no count in any of the tab on dashboard after allowing consent.

![image](https://user-images.githubusercontent.com/70740789/94659827-7c0e1080-0322-11eb-9b5b-0508b3e310fb.png)

**Comment by Karunaharan** [comment]
Hi @mrudula1412 
Can you please give more details about the issue? Usually, if the consent is given then tracking data appears in the dashboard in real time. You can get in touch with me @ karunaharan.v@sap.com

**Comment by Karunaharan** [comment]
Mrudula discussed the issue over emails. I have suggested her a couple of options to resolve. Else, I have requested her to raise a ticket.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
