### ISSUE TITLE
Develop a Business App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by iwonahahn** [SAPDocuments/Tutorials#5917]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-cap-app.html referring to step 5:

@Paolaufer please update the sample code as requested in the [community](https://answers.sap.com/questions/13142868/improvement-for-the-documentation-getting-started.html). 

Thank you,
Iwona

**Comment by Paolaufer** [comment]
The code sample provided in the tutorial is this:

/**
* Implementation for CatalogService defined in ./cat-service.cds
*/
module.exports = (srv) => {

  // Add some discount for overstocked books
  srv.after('READ', 'Books', (each) => {
      if (each.stock > 111) each.title += ' -- 11% discount!'
      })

    }

It does not look like the one in the community.

@raz-korn, do you know which of the 2 we should use?

Regards

**Comment by raz-korn** [comment]
Hi @Paolaufer ,

Both snippets deliver the same functionality.
It's a matter of code readability and best practice.
If @iwonahahn is OK with Gregor's request, I'm OK with it as well.

Regards - Raz

**Comment by iwonahahn** [comment]
HI @raz-korn and @Paolaufer,

As mentioned we were fine with Gregors suggestion and have updated it in our documentation (will be republished soon) and in our cap samples. For consistency, Gregor requested the change also for Paola's tutorila.

Best regards,
Iwona

**Comment by Paolaufer** [comment]
Hi,
I've updated the tutorial with the suggested snippet.
Regards,
Pao

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
