### ISSUE TITLE
Set Up Business Rules for Determining Equipment

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Tutorials#5921]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-businessrules.html

Please specify the step you are referring to - Step 3 - 3, where i get "Bad gateway error" (And after 5 tries i got a mail that my s-user was locked. Have to mention that the connection to APIhub destination works fine)
Br Michael

**Comment by mts2605** [comment]
Hi again
Just fyi. I have tried to delete Workflow management, incl destinations.
But when I press "Import", the error is still there 
![badgateway](https://user-images.githubusercontent.com/43760831/94855333-a1884080-042e-11eb-816d-e8dc918e7b5a.png)

**Comment by mts2605** [comment]
As can be seen here, the connection seems fine
![stepbefore](https://user-images.githubusercontent.com/43760831/94855497-e90ecc80-042e-11eb-9f48-d3c861558947.png)

**Comment by ArchanaShukla** [comment]
There were some issues with the trial. Can you try now and confirm if you still have the issue.

**Comment by mts2605** [comment]
Unfortunately, same error. And after 5 tries i got this mail:

"Dear Michael Toft Schmidt (User ID S..............)
There have been 5 failed attempts to log onto your account. Password log on to your account has been disabled for 1 hours. After 1 hours, you will again be able to log on with your password or click on the link below to set a new password."

**Comment by mts2605** [comment]
Just FYI. Tried also to delete destinations etc. And restart the booster. But no news...:-(

**Comment by ArchanaShukla** [comment]
Hello, the error comes if the username and password does not work. To check, login to api.sap.com and use the same user name and password to create the destination.

**Comment by mts2605** [comment]
Ok, i'll try that. But please notice that destinations have been working since creation.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by mts2605** [comment]
Tried with another account, where I am sure that api.sap.com works with the same user/PW,

Still exactly the same problem.

Please advice. Would so much like to try before buy.

KR Michael
