### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by js1972** [SAPDocuments/Tutorials#5922]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

Please specify the step you are referring to => (1)

In this step you specify a project configuration (in the package.json) to tell the system to use sqlite for development work and hana for production work as per this:
```
"cds": {
    "requires": {
      "db": {
        "kind": "sql"
      }
    }
  }
```

Can I please suggest you also add the following for anyone that will be using HANA Cloud because the above will lead to a successful deployment, but an un-runnable application with the deployer crashing with lots of weird errors that don't point you to the actual problem:
```
"cds": {
    "hana": {
      "deploy-format": "hdbtable"
    },
    "requires": {
      "db": {
        "kind": "sql"
      }
    }
  }
```

Additionally it would be good to add an additional section to this tutorial to cover the (possibly better practice) of deploying with mta's...

**Comment by iwonahahn** [comment]
Thank you for your suggestion. We are still updating the tutorial with the steps to deploy to a SAP HANA Cloud Instance. 

We can not extend the tutorial describing how to deploy using MTA, this would be then a new tutorial. You can find all relevant information in the official CAP documentation [here](https://cap.cloud.sap/docs/advanced/deploy-to-cloud#deploy-using-mta).

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
