### ISSUE TITLE
Create an SAP Fiori App Consuming HubSpot Data

### ISSUE THREAD

**Issue by mrudula1412** [SAPDocuments/Tutorials#5924]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-openconnectors-create-fioriapp.html

Please specify the step you are referring to: step 2.13

I did not get content of open connectors after following all the steps of the tutorials.
Could you please check if you are getting required data in below screen and if yes ,which parameters or part of code I should check again.
![image](https://user-images.githubusercontent.com/70740789/94901791-cde6a000-04b4-11eb-8e33-f5cae64a97ec.png)

**Comment by ludanyikristof** [comment]
Hi,

I think you should check destination's URL on SCP Neo portal, for me it caused the problem.

https://github.com/SAPDocuments/Tutorials/issues/5947

**Comment by mrudula1412** [comment]
> Hi,
> 
> I think you should check destination's URL on SCP Neo portal, for me it caused the problem.
> 
> #5947

Hi Ludanyikristol,

Thanks for your reply,
Could you please guide me where I can get the unique URL on API Portal which I should maintain in destination.

**Comment by ludanyikristof** [comment]
> 
> 
> > Hi,
> > I think you should check destination's URL on SCP Neo portal, for me it caused the problem.
> > #5947
> 
> Hi Ludanyikristol,
> 
> Thanks for your reply,
> Could you please guide me where I can get the unique URL on API Portal which I should maintain in destination.

Hi mrudula1412,

I used this URL to set the destination.

<img width="714" alt="api" src="https://user-images.githubusercontent.com/55134734/95960954-b5f01400-0e04-11eb-87a7-4dc33281cc79.png">

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by mrudula1412** [comment]
Hi Ludanyikristol,

Thanks for your reply,
I am still not getting content after maintaining suggested URL.
