### ISSUE TITLE
Create a Fiori Launchpad App

### ISSUE THREAD

**Issue by js1972** [SAPDocuments/Tutorials#5925]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-fiori-cf-create-project.html

Please specify the step you are referring to: ALL

Hey, this is great tutorial - but I just wanted to know how I can use the easy-ui5 yo generator with a CAP application. Or even a fiori-elements app (from fiori-tools). If I simply navigate into the app folder inside a cap project and run `yo easy-ui5` it generates an app but once I deploy the cap project to cloud foundry it doesn't work. There is some missing link.

Lots of awesome tutorials on CAP and lots on creating fiori-tools and freestyle fiori apps, but none that tie the too together that I can find?

**Comment by IObert** [comment]
Hi,

I agree the tools for UI development and CAP development are not as tightly integrated as they could be (at the moment). The good news is that we are working on this, and it will change in the future.
For now, the best option is to manage the project setup manually. For this, you can also leverage easy-ui5 (which is an Open Source community project and not an SAP product). You can do this by running `yo easy-ui5` from the CAP root (you don't need CAP's `app` folder in this case). I talked about similar topics [here](https://www.youtube.com/watch?v=zUgQQwWVfOU&t=6s) and [here](https://www.youtube.com/watch?v=u7OMkPvJIoU) in case you need some orientation.

I hope this helps for now, and as I said, the official tooling will grow more tightly together in the future :)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
