### ISSUE TITLE
Create Instance of SAP Cloud Platform Enterprise Messaging Service

### ISSUE THREAD

**Issue by bartdp86** [SAPDocuments/Tutorials#5930]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html

Please specify the step you are referring to
Step 1 Create an instance, item 5:
The JSON is wrong, only below items are needed (an error is thrown when providing the original one) as shown by DJ Adams in the hands on demo on SAP Developers Youtube channel
{
"emname": "<yourmessageclientname>",
"options": {
    "management": true,
    "messagingrest": true
}

**Comment by MichaelCzcz** [comment]
@pradeeppanda-sap Please respond!

**Comment by pradeeppanda-sap** [comment]
can you please let me know the error you are getting?
While you can definitely create an instance with that minimalistic information, a publish and subscribe rule is needed for queue and topic, so as to allow you to send and receive messages as per the rule.

**Comment by MichaelCzcz** [comment]
@bartdp86 Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by csramanujan** [comment]
With the JSON below I am able to create the service instance. However, when i open the Event mesh application I dont see the message clients. 
{
"emname": "",
"options": {
"management": true,
"messagingrest": true
}

<img width="802" alt="2021-06-04_12-55-44" src="https://user-images.githubusercontent.com/85331739/120763231-a6107600-c534-11eb-99a1-bf46b7039d30.png">
