### ISSUE TITLE
Integrate Your App into Your Portal Site (Cloud Foundry)

### ISSUE THREAD

**Issue by prakash13t** [SAPDocuments/Tutorials#5931]
Hi Team,

Is this tutorial valid for Fiori Elements based app also, because i followed the same and could not able to integrate Fiori Elements app in Portal?

**Comment by thecodester** [comment]
Which tutorial do you mean? This one? https://developers.sap.com/tutorials/cp-portal-cloud-foundry-sapui5-app.html

**Comment by prakash13t** [comment]
Yes, i followed the steps and not able to integrate Fiori Elements based app in Portal

**Comment by LindsayBert** [comment]
Hi

I noticed you are doing an older version of the tutorials.  Please try the third group of tutorials in this mission.
https://developers.sap.com/mission.portal-cf.html
The Portal service has now been replaced by the Launchpad service. 

Thanks Lindsay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
