### ISSUE TITLE
Install and Instantiate Hyperledger Fabric Chaincode

### ISSUE THREAD

**Issue by BibiAmeena** [SAPDocuments/Tutorials#5934]
Tutorial URL: https://developers.sap.com/tutorials/blockchain-hlf-install-chaincode.html

Please specify the step you are referring to
Unable to install the chaincode though I have specified correct zip folder with chaincode file in main folder.

![image](https://user-images.githubusercontent.com/33142247/95186776-f984c580-07e7-11eb-915a-9bb27de3220e.png)
[error.docx](https://github.com/SAPDocuments/Tutorials/files/5332900/error.docx)

Please help
Also find the attached zip folder.
[com-sap-icn-blockchain-HelloWorld.zip](https://github.com/SAPDocuments/Tutorials/files/5332910/com-sap-icn-blockchain-HelloWorld.zip)

**Comment by greg2git** [comment]
what happens when you rename your GO and YAML files from 'hello-world' to 'HelloWorld'?

**Comment by BibiAmeena** [comment]
[hello_world.zip](https://github.com/SAPDocuments/Tutorials/files/5339091/hello_world.zip)
Hi Greg,
As per your suggestion, I have changed the file names. Still I get the same error.

**Comment by greg2git** [comment]
it should be either 'hello-world' or 'HelloWorld' in all the files and filenames. 

i'm using 'ld6' for my naming convention:

![image](https://user-images.githubusercontent.com/24355032/95323208-cbe16000-086b-11eb-8353-fde7f0b8bdcb.png)
 

not mixed like this:

![image](https://user-images.githubusercontent.com/24355032/95323255-e0255d00-086b-11eb-8556-7d7cecb725b6.png)

**Comment by BibiAmeena** [comment]
Hi Greg,

Request you to please share your .zip folder for the above mentioned files.

Regards,
Ameena

**Comment by greg2git** [comment]
[helloWorld4.zip](https://github.com/SAPDocuments/Tutorials/files/5351348/helloWorld4.zip)

it's only good for another 5 days or so when my trial account expires.
good luck!

**Comment by BibiAmeena** [comment]
Thanks a lot for the zip file. Issue resolved :)
