### ISSUE TITLE
Embed an SAP Analytics Cloud Story in a Simple Web App

### ISSUE THREAD

**Issue by JackShepard98** [SAPDocuments/Tutorials#5941]
Tutorial URL: https://developers.sap.com/tutorials/sac-embed-story.html

Step 3

After the website is embedded some of the charts in the story don't show. More specifically the R-Integrated charts are giving an unauthorized message: 
![image](https://user-images.githubusercontent.com/36894163/95325525-ffdb7600-08a9-11eb-8784-a4e7568b272c.png)

The code used is the one from the tutorial.
Is there any fix to this?

**Comment by maxta2002** [comment]
Hi @JackShepard98,

thank you for open this issue. It seems that this behavior is not a general issue with the APIs or the source code of this tutorial because the R-Integrated charts are only affected. To support you in best way in finding the reason please create a ticket.

**Comment by JackShepard98** [comment]
Hi @maxta2002,

I'm not sure I understand, where should I create a ticket?

**Comment by maxta2002** [comment]
Hi @JackShepard98  please create a BPC ticket with the component LOD-ANA-OEM.
Hope this help you, if not please let me know.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
