### ISSUE TITLE
Use SAP HANA as the Database for a CAP Java Application

### ISSUE THREAD

**Issue by FRESFRANK** [SAPDocuments/Tutorials#5942]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-hana-db.html

**Step 3: Deploy database artifacts to SAP HANA**
This step is not easy to pass as the information is incomplete. I managed it this way on a new productive CF SAP HANA Cloud instance:
 - use @sap/hdi-deploy@3.11.6
 - update deploy format for cds hana in package.json:
  _"cds": {
    "hana": {
        "deploy-format": "hdbtable"
    },_

**Comment by maxstreifeneder** [comment]
Hi @FRESFRANK,

thanks for reaching out. The CAP Java application as a result of this set of tutorials is not using SAP HANA Cloud but SAP HANA as a Service on SAP Cloud Platform. Thus the instructions are right. 

Nonetheless, if you want to deploy the model to SAP HANA Cloud, you are steps are absolutely right. 

Please reopen the issue once you have further questions. 

Regards,
Max
