### ISSUE TITLE
Unable to build test DB in trail account

### ISSUE THREAD

**Issue by shilpa535** [SAPDocuments/Tutorials#5948]
getting below error while building a test DB in trail account.

Build command failed : hdi-build operation failed: Deployment failed with exit code: 1
Build of /hana-cf-get-started-trial/db failed due to The "task for hdb build" process finished with code 1.

**Comment by thecodester** [comment]
@shilpa535 Did you mean to put this here? This is for tutorials and no tutorial is listed in the issue

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
