### ISSUE TITLE
Bug Fix for Tutorial: Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by felix9607** [SAPDocuments/Tutorials#5949]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Please specify the step you are referring to

Step: 6.3.:

I had to change to code like following, else I couldn't send POST-Requests to /Orders.

```
using my.bookshop as my from '../db/data-model';

service CatalogService {
  entity Books @readonly as projection on my.Books;
  entity Authors @readonly as projection on my.Authors;
  @insertonly entity Orders as projection on my.Orders;
}
```

**Comment by iwonahahn** [comment]
Hi,
We have tested it with the latest `cds-dk` release version `3.1.1` and it works as described in the tutorial. Could you please test it again with the new version?

Thanks a lot and best regards,
Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
