### ISSUE TITLE
Create Service Instance for Document Classification with Trial Account

### ISSUE THREAD

**Issue by SCHELLK** [SAPDocuments/Tutorials#5954]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dc-service-instance.html

Please specify the step you are referring to: **Step 2: Check Entitlements**

It says you have to klick on entitlement to see a list of all eligible services. Bit this is not true anymore. Now " Entitlement" has to sub section: 

- Entity Assignments 

- Service Assignments

Therefore the user has to choose " Service Assignments" to find Document Classification Trial. 

Can you adapt this accordingly ? 

Thanks and best regards,
Katharina

**Comment by tobias61** [comment]
Hi @SCHELLK ,

for me, the subsections "Entity Assignment" and "Service Assignment" only show if I'm in my global trial account.
However, once I'm in my subaccount as described in the tutorial "Entitlements" do not have subsections anymore. Please refer to the screenshots attached.

If that is different for you, please let me know. Then something is off on my site.

Best regards,
Tobias

![image](https://user-images.githubusercontent.com/26334221/95722890-cec9bf80-0c74-11eb-958a-57d5c4694774.png)
![image](https://user-images.githubusercontent.com/26334221/95722952-e012cc00-0c74-11eb-8b9f-a0d687a10c60.png)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
