### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by kmurray24** [SAPDocuments/Tutorials#5955]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to

1. Great tutorial, but not enough context along the way.
    What is /BusinessPartnerSet?  Is that a predefined bapi provider?
2. The question about other templates where the answer YEOMAN Templates?  
    I didn't see that information along the tutorial.
Thanks@!

**Comment by MichaelCzcz** [comment]
Identical to https://github.com/SAPDocuments/Tutorials/issues/5956
