### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by kmurray24** [SAPDocuments/Tutorials#5956]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to

1. Great tutorial, but not enough context along the way.
    What is /BusinessPartnerSet?  Is that a predefined bapi provider on ES5?
2. The question about other templates where the answer YEOMAN Templates?  
    I didn't see that information along the tutorial.
Thanks

**Comment by raz-korn** [comment]
Hi @kmurray24 ,

More information that address the topics you mentioned will be available in the next tutorial update.

Regards - Raz

**Comment by MichaelCzcz** [comment]
@raz-korn Can I close this one?

**Comment by raz-korn** [comment]
yes.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
