### ISSUE TITLE
Get Started with SAP Cloud Platform, Kyma runtime

### ISSUE THREAD

**Issue by sedacrivity** [SAPDocuments/Tutorials#5959]
Group URL: https://developers.sap.com/group.cp-kyma-get-started.html

Great group of tutorials. Kyma Trial account worked perfect for this ( not always a given :) ).

Couple of suggestions - I had 'issues' with almost every tutorial as my environment was lacking something, like go environment not properly configured, node runtime to low, etc, etc.  Might be an idea to list out the prerequisites for each tutorial ( or did I miss that somewhere ? ).

The last tutorial worked fine but I had the feeling I was not always sure why or what I was doing. A bit more info might be helpfull.

Thanks for the efforts, looking forward to other tutorials on SAP Kyma.

**Comment by jcawley5** [comment]
Hello Steven,

Each tutorial has a Prerequisites section pointing to what is needed and should work with the newest long term supported of each.  I will look into adding more detail to the last to helpfully make it more clear.  Thanks for the feedback.

Jamie
