### ISSUE TITLE
Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by peterpersiel** [SAPDocuments/Tutorials#5960]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

This tutorial requires the business catalog  SAP_A4C_BC_DEV_UID_PC (Development - UI Deployment) to be assigned to a business role of the developer user. In new systems where the developer business role is created from the provided business role template, this is usually the case. But for existing ABAP systems, the business catalog needs to be added manually to the existing developer business role. Otherwise the UI deployment will error 403.

**Comment by mervey45** [comment]
Hi @peterpersiel ,

we will add this information to this tutorial.

Thank you. 

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @MichaelCzcz 

I created PR: #6017. Can you merge?

Thank you.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
