### ISSUE TITLE
HANA Native, Create Database Artifacts Using Core Data Services (CDS)

### ISSUE THREAD

**Issue by kirrmannpius** [SAPDocuments/Tutorials#5961]
Tutorial URL: https://developers.sap.com/tutorials/xsa-cap-create-database-cds.html
Step 3: db build not successful

Environment: SAP Web IDE for SAP HANA
Version: SAP Web IDE for HANA 2
SPS 04 Patch 6 ( Build 4.4.18 )
(SAP HANA Express)

Hi,
when I try to build the db module, I get the following error: npm ERR! code ELIFECYCLE
The following node runtimes are installed:
hxeadm@hxehost:/usr/sap/HXE/HDB90> xs runtimes | grep node
node10.17             0.0       1    true       true     Node.js 10.17.0 for Linux x86-64               14
node8.15              1.3       2    true       true     Node.js 8.15.1.3 for Linux x86-64              21

In package.json: 
```
"engines": {
    "node": "^10 || ^12"
  },
```
What's going wrong?
Best regards, Pius

**Comment by jung-thomas** [comment]
Can you please share the entire error from the console.  There are usually a lot more details that are necessary after the ELIFECYCLE error.

**Comment by kirrmannpius** [comment]
Thank you for your quick response. Here is the complete console output:
[MyHANAApp-db-build-failed.pdf](https://github.com/SAPDocuments/Tutorials/files/5363003/MyHANAApp-db-build-failed.pdf)

**Comment by jung-thomas** [comment]
You say in your package.json you have the verison:
"engines": {
    "node": "^10 || ^12"
  },

Which package.json is this? In the root or the package.json in the /db folder?  From the log it seems that your DB build is trying to use Node.js 8.x which is no longer supported at the OS level.  It seems the package.json in the DB folder should be updated to target node 10 or 12.  Maybe share the complete package.json of the /db folder.  It could be your module version for the hdi-deployer is also too old.  The wizard should generate a proper package.json for you but if you have any older version of the Web IDE it might not have been patched to include the updated versions and you might need to update the package.json manually.

**Comment by kirrmannpius** [comment]
After adding the engines section to db/package.json

```
{
	"name": "deploy",
	"dependencies": {
		"@sap/hdi-deploy": "^3"
	},
	"scripts": {
		"postinstall": "node .build.js",
		"start": "node node_modules/@sap/hdi-deploy/deploy.js"
	},
	"engines": {
		"node": "^10 || ^12"
	}
}
```
the build succeeded. Thank you very much for your support.

**Comment by jung-thomas** [comment]
You did say earlier that when you run xs runtimes you still have Node version 8.x in the list.  I think that was the issue since at the OS level, Node 8.x isn't supported and the HDI Deployer requires building native modules via node-gyp.  I tested just now on my system and works with the package.json as the wizard generates it, but I also don't have Node version 8.x in my xs runtimes any longer:
![image](https://user-images.githubusercontent.com/12159356/95785767-5975e300-0ca4-11eb-9526-7adcf0b40a4e.png)

I'll add a note for troubleshooting to this step of the tutorial.
