### ISSUE TITLE
Implement A Card With Content-Based Actions

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Tutorials#5965]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-content-actions.html

Landscape label: trail1 & trail2 & ap
Scenario label : SCPTest-mcard
Priority : High-prio

Please specify the step you are referring to 

 **Step 2: Create a new action card**

When creating a action card, when i select "HTML Template manger " as "**sample product template**"   & select "card template "as "**Multi Instance**"  i am getting error popu-up and save is not happening.
![image](https://user-images.githubusercontent.com/33411431/95687378-ed9e6680-0c20-11eb-971c-28b8d936ca7b.png)

As a hit & try i selected  "card template "as "**Single Instance**"  & i am able to create action card successfully.

Please change steps & screenshot related to creation of action cards with correct parameters.

Thanks
Mounika

**Comment by sandeep-tds** [comment]
@mounikat987 Thank you for raising the issue. 

We are in the process of overhauling our tutorials based on an upcoming release. These changes will be available in the coming weeks. 

I will be sure to update the ticket.

Thank you for your patience.

**Comment by thecodester** [comment]
@sandeep-tds  Any update?

**Comment by sandeep-tds** [comment]
Hi @mounikat987 

The updated tutorial has been released, can you please verify the changes and update the ticket?

Thank you so much for your support.

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
