### ISSUE TITLE
Set Up a Workflow With Extended Employee Onboarding

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Tutorials#5966]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html

Labels :
Landscape Labels: trail1 & trail2
SCPTest-eboard: Automate and Extend Employee Onboarding
Priority label :‘High-prio’

Step 2: Import sample application

In Sub step 2 Give steps to create Dev space or provide a prerequisite step to create dev space. Workflow management extension should be included

**Comment by ArchanaShukla** [comment]
Thanks for reporting this. The section have added to create or edit dev space in the tutorial.
@MichaelCzcz  - please close the ticket.
