### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#5967]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

Please specify the step you are referring to

Step 2.4: **Observation**- When I was giving the command 'cf login' it was taking by default an api which I wanted to change. So here we can add a note saying if the api value is taken by default or if we want to change the api value then in that case use ‘cf api <Your end-point>’ to change the api. Then we can proceed with ‘cf login’

Just a suggestion for better execution. 

Labels:
Sprint Label: SCPTest-2009A 
SCPTest-banode 
Landscape Labels: trail1 & trail2
Priority label: High-prio

**Comment by iwonahahn** [comment]
Hi,

This is not an issue with `High-Prio`. We will add a note for better understanding.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
The note was added and published, we can close this issue.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
