### ISSUE TITLE
Workflow service is not available in AP21 Region

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5969]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html

**Step 1: Setup your account using Booster**

Here when we click on Start of **Set up account for Workflow Management booster on AP21 Region**, it fails with the below error:
![image](https://user-images.githubusercontent.com/65999547/95724697-4a873480-0c94-11eb-911d-63a4c60516e8.png)

On checking the entitlements, noticed that **workflow service is not available in the AP21** Region as below:
![image](https://user-images.githubusercontent.com/65999547/95724930-99cd6500-0c94-11eb-82f1-b28bbec83225.png)

Labels to be attached:
Landscape label: trail3
Sprint Label: SCPTest-2009A
Scenario Labels: SCPTest-eboard
Priority: High-Prio

Best Regards,
Priyanka

**Comment by ArchanaShukla** [comment]
It is available now. 
@MichaelCzcz - Please close the ticket.
