### ISSUE TITLE
SAP Business Application Studio subscription issue

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5971]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-onboarding.html

**Step 2: Switch to subscriptions view**

The SAP Business Application Studio was subscribed automatically when the account was created, so this step can be removed.
Else add a text stating that if SAP Business Application Studio is unsubscribed then to subscribed to it.

Labels to be attached:
Landscape label: trail1,trail2, trail3
Sprint Label: SCPTest-2009A
Scenario Labels: SCPTest-fbizapp
Priority: Low-Prio

Best Regards,
Priyanka

**Comment by raz-korn** [comment]
Hi @PriyankaShivakumar ,

This will be available in the next tutorial update.

Regards - Raz

**Comment by MichaelCzcz** [comment]
@raz-korn Can I close this one?

**Comment by raz-korn** [comment]
no

**Comment by thecodester** [comment]
@raz-korn When will this be updated? Can the tutorial be completed currently?

**Comment by raz-korn** [comment]
Hi @PriyankaShivakumar ,

I released an update today.

Regards - Raz

**Comment by PriyankaShivakumar** [comment]
Hi @raz-korn ,

Thanks for the update. The issue is fixed now so will close the ticket.

Best Regards,
Priyanka
