### ISSUE TITLE
Access denied Issue in SAP Business Application Studio for AP21 Region

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5973]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-onboarding.html

**Step 4: Launch SAP Business Application Studio**

Even after logout and login, got access denied in SAP Business Application Studio. I had to manually add the role business app studio developer to my user after which i was able to create the dev space. This step is not mentioned in the tutorial.
This issue is reproducible only in AP21 Region.

Labels to be attached:
Landscape label: trail3
Sprint Label: SCPTest-2009A
Scenario Labels: SCPTest-fbizapp
Priority: Low-Prio

Best Regards,
Priyanka

**Comment by raz-korn** [comment]
Hi @PriyankaShivakumar ,

I was not able to reproduce. 
For new trial accounts everything is pre-configured.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
