### ISSUE TITLE
Screenshot for the create dev space step has to be changed

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5974]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-devspace-fiori-create.html

**Step 2: Create a preconfigured SAP Fiori dev space**

SAP Fiori dev space will be selected by default. Update the screenshot to the latest one where SAP Fiori is the first option and it is selected by default.

**Expected Screenshot:**
![image](https://user-images.githubusercontent.com/65999547/95730757-54149a80-0c9c-11eb-8c2b-bc6b3b14807f.png)

**Actual Screenshot:**
![image](https://user-images.githubusercontent.com/65999547/95730719-44955180-0c9c-11eb-8728-4d4ecbf71d12.png)

Labels to be attached:
Landscape label: trail1,trail2, trail3
Sprint Label: SCPTest-2009A
Scenario Labels: SCPTest-fbizapp
Priority: Low-Prio

Best Regards,
Priyanka

**Comment by raz-korn** [comment]
Hi @PriyankaShivakumar ,

Will be part of the next tutorial update.

Regards - Raz

**Comment by raz-korn** [comment]
@MichaelCzcz  - I pushed an updated screenshot. Can you check why the updated screenshot does not appear in the tutorial?
Thanks - Raz

**Comment by raz-korn** [comment]
Hi @PriyankaShivakumar  ,
An update to the tutorial that addresses you request was released.
Regards - Raz

**Comment by PriyankaShivakumar** [comment]
Hi
Thanks for fixing the screenshot, I will close the Issue.

Best Regards,
Priyanka
