### ISSUE TITLE
Use Machine Learning to Extract Information from Documents with Swagger UI

### ISSUE THREAD

**Issue by FarozanFarman** [SAPDocuments/Tutorials#5976]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dox-swagger-ui.html

Please specify the step you are referring to:
Step 3: Create client:
4. Click Execute.:

Screenshot needs to be updated:
Expected Result:
![image](https://user-images.githubusercontent.com/71028764/95732466-68599700-0c9e-11eb-901c-83e962734c3f.png)
Actual Result:
![image](https://user-images.githubusercontent.com/71028764/95732497-73142c00-0c9e-11eb-85b3-73f770fdac16.png)

Labels to be attached:
Landscape label: trail1, trial2
Sprint Label: SCPTest-2009A
Scenario Labels: SCPTest-docinfo
Priority: Low

Thanks and Regards,
Farozan Farman

**Comment by Juliana-Morais** [comment]
The image has been updated. This issue can be closed.

**Comment by thecodester** [comment]
@Juliana-Morais Just so you know, you can paste the URL of the PR that updated the tutorial -- that is kind of good practice in GitHub (and if set up can automate the closing of the issue).
