### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5977]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

**Step 1: Create new SAP Fiori project**

Here instead of "Create a new SAP Fiori project from a template" rephrase it as "Click on Create project form template".

Labels to be attached:
Landscape label: trail1,trail2, trail3
Sprint Label: SCPTest-2009A
Scenario Labels: SCPTest-fbizapp
Priority: Low-Prio

Best Regards,
Priyanka

**Comment by raz-korn** [comment]
Hi @PriyankaShivakumar ,

Will appear in the next update.

Regards - Raz

**Comment by raz-korn** [comment]
Hi @PriyankaShivakumar  ,
An update to the tutorial that addresses you request was released.
Regards - Raz

**Comment by PriyankaShivakumar** [comment]
Hi,

Thanks for the Fix, I will close the Issue.

Best Regards,
Priyanka
