### ISSUE TITLE
Select BusinessPartners step is mentioned twice.

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#5978]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

**Step 4: Test run the application**

Here a step is mentioned as "Click + and select BusinessPartners" and again in the next step "When “What would you like to run?” question appears, select BusinessPartners." is mentioned which causes a little confusion.

So from a customer perspective, please rephrase line 1 as " Click +" and line 2 as "When “What would you like to run?” question appears, select BusinessPartners."

Labels to be attached:
Landscape label: trail1,trail2, trail3
Sprint Label: SCPTest-2009A
Scenario Labels: SCPTest-fbizapp
Priority: Low-Prio

Best Regards,
Priyanka

**Comment by raz-korn** [comment]
Hi @PriyankaShivakumar ,

Will appear in the next tutorial update.

Regards - Raz

**Comment by raz-korn** [comment]
Hi @PriyankaShivakumar  ,
An update to the tutorial that addresses you requests was released.
Regards - Raz

**Comment by PriyankaShivakumar** [comment]
Hi @raz-korn ,

I still see the Select BusinessPartners step mentioned twice in the Tutorial. I think that the select BusinessPartners in the Step 2 can be removed.
![image](https://user-images.githubusercontent.com/65999547/96401214-54f38200-11f0-11eb-9f9c-1ecec1a3357b.png)

Best Regards,
Priyanka

**Comment by raz-korn** [comment]
Hi @PriyankaShivakumar ,
You are correct.
I pushed an update.
Should be available later this week...perhaps even today.
Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
