### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by FarozanFarman** [SAPDocuments/Tutorials#5980]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Please specify the step you are referring to:
Step 10: Deploy the integration flow:
1.Choose Deploy to deploy the integration flow. Choose Yes in the confirmation dialog for deployment. Once you see the deployment confirmation, choose the Monitor tab to access the monitoring view.

It should be "Save" and then "Deploy". Similarly, it should be marked in the below screenshot:
![image](https://user-images.githubusercontent.com/71028764/95733434-c175fa80-0c9f-11eb-94db-5203babccd60.png)

Labels:
Landscape: trail1, trail2
Label: SCPTest-2009A
Scenario Label: SCPTest-cloudin
Priority: Low

Thanks and Regards,
Farozan

**Comment by Vikramkulkarni01** [comment]
Hi @FarozanFarman , 

Thanks for the feedback. 

Once you click on deploy it automatically ask for confirmation on unsaved changes. hence we have mentioned choosing "YES" so that it saves the integration flow. 
So no need to highlight the saving part here. 

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
