### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by FarozanFarman** [SAPDocuments/Tutorials#5982]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Please specify the step you are referring to:
Step 1: Create service instance and key:
9.Copy the values of clientid and clientsecret parameters. These are the credentials that you use to make a request to your integration flow after you deploy it.

Before substep 9, a step must be added to Select " cloudintegration_trial" to see the "ouath".
The screenshot is given below for your reference.
![image](https://user-images.githubusercontent.com/71028764/95735130-0e5ad080-0ca2-11eb-9034-36de750d8f17.png)

Labels:
Landscape: trail1, trail2
Label: SCPTest-2009A
Scenario Label: SCPTest-cloudin
Priority: Low

Thanks and Regards,
Farozan

**Comment by Vikramkulkarni01** [comment]
Hi @FarozanFarman, 

Thanks for sharing the feedback. 

I have added this step and it will be available in the production shortly. We will be pushing the changes along with the other few updates. 

Planning for the update next week tentatively. 

Regards, 
Vikram Kulkarni

**Comment by Vikramkulkarni01** [comment]
Hi, 

We have accepted your suggestion and it's available in the production now. 

Regards, 
VIkram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
