### ISSUE TITLE
Update tile name, maintain step numbering - SAP MOBILE Cards

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5983]
Hello,
Scenario link: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html
Step 2: Search for Mobile, and click on the SAP Mobile Services tile. -> Tile Name is "Mobile Services', NOT SAP mobile services.
Screenshot is Correct!

Also, please maintain the numbering of sub-steps also. so that steps can be easily identified like other tutorials. It will also be convenient while reporting issues.

Please update the same.

Labels:
priority label: low-prio
landscape labels: trial1, trial2, trial3
Sprint Label: SCPTest-2009A
Scenario Label:SCPTest-mcard

**Comment by sandeep-tds** [comment]
@i353590 Thank you for raising the issue. I believe you were referring to the setup tutorial. 

Changes will be publically accessible by early next week.


Also, thank you so much for suggesting step numbers for each sub-step. I am currently in the process of overhauling the tutorials. I will be sure to update the sub-step numbers then. 

These changes will be publically accessible by end of October.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
