### ISSUE TITLE
SAP Mobile Cards - Tutorial Update

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5984]
Hello,

Scenario link: https://developers.sap.com/tutorials/cp-mobile-cards-action.html#b0de6140-460f-47d5-a7c7-811d29bfe4b4

Step 8: Cross verify status update in the back end ->In the Mobile Services cockpit, click Connectivity under the Features tab. -> 
statement should be "click MOBILE Connectivity" not just Connectivity.

Also, at step : If you   cannot find particular data set, click Entity Properties to select some   properties, then click OK. -> click on "SUBMIT" is there instead of "OK"

Thanks,
Shubham

Landscape label: trail1 & trail2 & trial3
Scenario label : SCPTest-mcard
Priority : Low-prio
Sprint Label: SCPTest-2009A

**Comment by sandeep-tds** [comment]
@i353590 Thank you for raising the issue. I have updated our document.

Changes will be publically accessible by early next week.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
