### ISSUE TITLE
File name change required - SAP Fiori app using ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5985]
Hello,

Scenario link: https://developers.sap.com/tutorials/abap-environment-trial-onboarding.html#abd4c35c-a342-40a1-a0ae-9319e9816dc3

Issue Description: Step 3.4, You can find your service key in your default download folder. Search for ADT.json, select it and click Open. -> here, the downloaded file name is "Default_key.json" NOT ADT. While downloading also, it was not mentioned to save the file with name ADT. PLease update tutorial accordingly. 

Thanks,
Shubham

Labels to be added:
Landscape Labels: trail1, trail2 & trail3
Sprint Label: SCPTest-2009A
Scenario Label:SCPTest-fabap 
priority label: high-prio

**Comment by mervey45** [comment]
Hi @i353590 , 

thank your for your feedback. We updated this tutorial with following PR: #6017.
@MichaelCzcz can you merge?

Thank you.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
