### ISSUE TITLE
add missing step - Click on FINISH - Fiori App using ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5986]
Hello,

Scenario link: https://developers.sap.com/tutorials/abap-environment-persistence.html#7c7762b5-9d33-4196-93a5-253eae683055

Issue Description:
Step 1.3: Select Create new request and enter a request description. -> after this step, need to click on Finish to complete the transport request like everywhere else in the tutorial.
Please add step to click on Finish after this.

thanks,
Shubham

Landscape Labels: trail1, trail2 & trail3
Sprint Label: SCPTest-2009A
Scenario Label:SCPTest-fabap 
priority label: high-prio

**Comment by mervey45** [comment]
Hi @i353590 , 

thank your for your feedback. We updated this tutorial with following PR: #6017.
@MichaelCzcz can you merge?

Thank you.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
