### ISSUE TITLE
Screenshot Update required - Fiori app using ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5987]
Hello,

Scenario URL: https://developers.sap.com/tutorials/abap-environment-behavior.html#b9494c55-3f01-4be3-9dd3-d7e9431b93ca

Issue description: Step 2.7: Refresh your browser and check your result.

Tutorial screenshot:
![image](https://user-images.githubusercontent.com/66831161/95745645-153e0f00-0cb3-11eb-9679-9eeb19edd771.png)

Actual result:
![image](https://user-images.githubusercontent.com/66831161/95745718-330b7400-0cb3-11eb-90ac-2947803c5674.png)

Please notice, Now the create button comes first then Delete button.
Screenshot has to be updated for the same.

Thanks,
Shubham

Landscape Labels: trail1, trail2 & trail3
Sprint Label: SCPTest-2009A
Scenario Label:SCPTest-fabap 
priority label: low-prio

**Comment by mervey45** [comment]
Hi @i353590 , 

thank your for your feedback. We updated this tutorial with following PR: #6017.
@MichaelCzcz can you merge?

Thank you.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
