### ISSUE TITLE
Subscribe - Business App Studio missing - Fioti app using ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5988]
Hello,

Scenario URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Issue Description: Step 1.7: Select Business_Application_Studio_Developer and click Assign Role Collection.
SAP Business Application was not subscribed by default. Add steps to subscribe the application too.
If we have already subscribed the application, it will work smoothly, Otherwise, option to add Business_Application_Studio_Developer role won't appear. Since Subscription of SAP BizApp is not part of bossters.

Thanks,
Shubham

Landscape Labels: trail1, trail2
Sprint Label: SCPTest-2009A
Scenario Label:SCPTest-fabap 
priority label: high-prio

**Comment by mervey45** [comment]
Hi @i353590 , 

thank your for your feedback. We updated this tutorial with following PR: #6017.
@MichaelCzcz can you merge?

Thank you.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
