### ISSUE TITLE
Feedback on Tutorial: Deploy gamified HelpDesk application to SAP HANA Cloud Platform

### ISSUE THREAD

**Issue by jacobtan89** [SAPDocuments/Tutorials#599]
Confusion on Step 6 selection.

Step 6: Setup the Java Web runtime environment in Eclipse
- Instead of selecting Java Web, select SAP HANA Cloud Platform
- Java Web (once deployed) will open up a local runtime user login page instead, not as per tutorial steps
- Once SAP HANA Cloud Platform is selected, it will require User ID & Account Name as per tutorial screenshot.

**Comment by ckraczkowsky** [comment]
Thank you for bring that to our attention. We will adjust the tutorial.

Colin
