### ISSUE TITLE
Incorrect Envirponment name - Fiori using ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5990]
Hello,

Scenario URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
Issue: Step 4.5: Configure data source, system and service -> ABAP Environment: abap-cloud-default_abap-trial :: Environment name is: "default_abap-trial"
Screenshot in the tutorial also confirms that.
please update the screenshot.

Thanks,
Shubham

Landscape Labels: trail1, trail2
Sprint Label: SCPTest-2009A
Scenario Label:SCPTest-fabap 
priority label: high-prio

**Comment by mervey45** [comment]
Hi @i353590 ,

this has been updated. @MichaelCzcz we can close this ticket.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
