### ISSUE TITLE
Add step to navigate to Run-config - fiori app using ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5991]
Hello,
Scenario URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Issue: Step 5.2: Press the run button and select press button for Start ztravel_app_xxx to run your SAP Fiori application. -> Need to navigate to "run-Configurations" tab from left pane. 
Please add this step to navigate, as we will be in "file explorer" after opening workspace.

Landscape Labels: trail1, trail2
Sprint Label: SCPTest-2009A
Scenario Label:SCPTest-fabap 
priority label: high-prio

**Comment by mervey45** [comment]
Hi @i353590 , 

thank your for your feedback. We updated this tutorial with following PR: #6017.
@MichaelCzcz can you merge?

Thank you.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
