### ISSUE TITLE
Incorrect description - fiori using ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5992]
Hello,
Scenario URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Issue: Step 6.4: To add deploy config details enter npx fiori add deploy-config. -> Is this an ABAP Cloud System?: Y
Correct statement is: "Is this an SAP Cloud Platform System?"
please update the same.

Landscape Labels: trail1, trail2
Sprint Label: SCPTest-2009A
Scenario Label:SCPTest-fabap 
priority label: high-prio

**Comment by mervey45** [comment]
Hi @i353590 , 

thank your for your feedback. We updated this tutorial with following PR: #6017.
@MichaelCzcz can you merge?

Thank you.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
