### ISSUE TITLE
Refresh project - add as Note - Fiori app using ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#5993]
Hello,
Scenario URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Issue: Step 7.1: Open Eclipse and check the BSP library and SAP Fiori Launchpad app descriptor item folder in your package ZTRAVEL_APP_XXX : Here, actually the project structure sometimes takes time and doesn't refresh automatically so we might need to refresh the package once to be able to see entire project.

Can you add a note for that saying "you might need to refresh the project if you are not able to see BSP applications under BSP Library" ?

Landscape Labels: trail1, trail2
Sprint Label: SCPTest-2009A
Scenario Label:SCPTest-fabap 
priority label: low-prio

**Comment by mervey45** [comment]
Hi @i353590 , 

thank your for your feedback. We updated this tutorial with following PR: #6017.
@MichaelCzcz can you merge?

Thank you.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
