### ISSUE TITLE
Build and Deploy Your SAP Fiori App to SAP Cloud Platform

### ISSUE THREAD

**Issue by tobiassschlosser** [SAPDocuments/Tutorials#5994]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html

Please specify the step you are referring to

In Step 2.2, we have to login with command "cf login" to cf.
In step 2.3 you wrote:
"When prompted, provide your credentials, select the API endpoint, organization, and space for your project."

I don't know which credentials I have to use here or where I can find them.
Could you please help?

Thanks!

**Comment by raz-korn** [comment]
Hi @tobiassschlosser ,

The credentials you use to access the SAP Cloud Platform account.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
