### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by spullepu** [SAPDocuments/Tutorials#5996]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

Please specify the step you are referring to
SET CDS_ENV=production && cds build

Step above does not seem to create manifest.yml and the gen folder. I tried below steps to address missing gen folder even that does not help. Refered from https://cap.cloud.sap/docs/advanced/deploy-to-cloud#deploy-using-cf-push

"If you don’t see a gen folder, check .cdsrc.json file if it contains a "target" entry. If yes, remove it or set it to: "target": "gen". This will cause deployment files to be written to this folder. Otherwise, the deployment files would be written to the source folders."

Can you include manifest.yml in the article? or help resolve the issue? 
Thanks

**Comment by iwonahahn** [comment]
Hi,

Please do not mix up the different sources of information. You are referring to the CAP documentation where we execute `cf create-service  **hana**  hdi-shared  **bookshop**-db`. In the tutorial we execute `cf create-service **hanatrial** hdi-shared **my-bookshop**-db`. Also, the project names are different. Please follow the tutorial by using the latest `cds-dk`version `3.1.1` (check your version with `cds version`). The tutorial works as described. Please also make sure that you use the correct code samples in step 3 depending on which operating system you are using (Windows or MacOS). You see a tab below the heading of step 3 where you can choose your operating system.

Best regards,
Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
