### ISSUE TITLE
Improve User Experience of the List and Detail Page

### ISSUE THREAD

**Issue by alessandrofior** [SAPDocuments/Tutorials#5997]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-101-improve-user-experience.html

Please specify the step you are referring to controllers/list.controllers.js give a error pheraps binding does not contain values

            // update list binding
            var list = this.getView().byId("list");
            var binding = list.getBinding("items");
            binding.filter(filters);

**Comment by IObert** [comment]
Hi @alessandrofior,

this is strange because the code should work as shown in the tutorial. Can you post a screenshot of the error that you are seeing?

**Comment by alessandrofior** [comment]
i must re try, i only have exception in chrome console and does not view 
no result in list.

Il 14/10/2020 10:06, Marius Obert ha scritto:

**Comment by IObert** [comment]
I'll close the issue for now. Please reopen if you still see the issue again
