### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by IsabellaMasselli** [SAPDocuments/Tutorials#6001]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html

Please specify the step you are referring to:- 

Step 1.4  when trying to Import Employee Onboarding Events JSON file I get the following message of missing permission

![image](https://user-images.githubusercontent.com/72649728/95951469-868ed680-0e07-11eb-8d6a-d4b62eb1db3d.png)

**Comment by ArchanaShukla** [comment]
This was due to the missing role. It has been added in the role collection which is assigned via the Booster. 
@MichaelCzcz - please close the issue.
