### ISSUE TITLE
Add an API Proxy to a Product

### ISSUE THREAD

**Issue by ralphsteurer** [SAPDocuments/Tutorials#6010]
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-create-product.html

Please specify the step you are referring to:

When trying to publish the product I constantly get the error that the developer portal is not properly set up. I tried to assign different roles as described in note https://apps.support.sap.com/sap/support/knowledge/en/2727440 and https://launchpad.support.sap.com/#/notes/2696294. I also logged on and off and tried different browsers. 

thanks
ralph

**Comment by shilpavij** [comment]
Kindly use a different mail id and try. Looks like your trial is not provisioned.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
