### ISSUE TITLE
Deploy a CAP Business Application to SAP Cloud Platform

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#6012]
Tutorial URL: https://developers.sap.com/tutorials/cap-service-deploy.html

Please specify the step you are referring to 1

"cds": {
    "requires": {
      "db": {
        "kind": **"sql"** } } }

this helps with running cds against local environment but in the subsequent step 3.2 the command 
   _SET CDS_ENV=production_  
is failing with this error message: 
   _bash: SET: command not found_

so i had to go back to step one and replace **"sql"** with **"hana"** to allow cds build to generate the required folders. it's a little bit inconsistent but one can recover.

**Comment by iwonahahn** [comment]
Hi,

We have tested it as described in the tutorial and it works. Which Version of `cds-dk`are you using? With the latest reease `3.1.1`it works. Could you please test it again?

Thank you and best regards,
Iwona

**Comment by greg2git** [comment]
i will check as soon as this message is no longer displayed in my browser:
_"Access Denied
You do not have the required permissions to access SAP Business Application Studio. Please contact your administrator to request access.
Read more about managing authorizations for SAP Business Application Studio."_

**Comment by iwonahahn** [comment]
The tutorial is not using Business Application Studio. It uses only Visual Studio Code.

**Comment by greg2git** [comment]
ok, it has worked in incognito mode, in any event, here is my environment:

_cds version
@sap/cds: 4.1.9
@sap/cds-compiler: 1.39.0
@sap/cds-dk: 3.0.0_

how do i upgrade from cds-dk: 3.0.0 to cds-dk: 3.1.1 and what configuration files needs to be updated on top of it?

Thank you,
greg

**Comment by iwonahahn** [comment]
Try `npm install` in the root level of your project.

**Comment by greg2git** [comment]
that did not work. what is my next step?

**Comment by iwonahahn** [comment]
Hi,

Cloud you please share the result of `cds version` please? You’ve installed Node.js. with latest long-term support (LTS) version? In case of problems, see the [Troubleshooting guide](https://cap.cloud.sap/docs/advanced/troubleshooting#npm-installation) for CAP. As mentioned both tutorials work as described, they were tested with the latest release for `cds-dk`. 

Best regards,
Iwona

**Comment by greg2git** [comment]
Hi Iwona,

running **_npm i -g @sap/cds-dk_** has upgraded @sap/cds-dk: 
from 3.0.0 to 3.1.2 
along with some other @sap/cds modules. 

not sure if other files need to be adjusted for those version changes or not, but i'm assuming that they are. as i said before i did recover from the issue but it is hard to keep the tutorial matching the correct versions and maybe the cds-dk version 3.1.1 should be specified in the beginning explicitly as the lowest working one.

Thank you very much for your help.
greg
