### ISSUE TITLE
Install the Cloud Connector in your System Landscape

### ISSUE THREAD

**Issue by NikhilSave14** [SAPDocuments/Tutorials#6019]
Hello Team,

Tutorial URL: https://developers.sap.com/tutorials/cp-connectivity-install-cloud-connector.html

Please specify the step you are referring to
When I am following this tutorial, facing an issue at Step 4: Log on to the Cloud Connector. We are not able to open  https://localhost:8443/. It says "This site can’t provide a secure connection localhost sent an invalid response"

![Error](https://user-images.githubusercontent.com/70974477/96122282-e15f2580-0f0e-11eb-83cf-d3d41cf2e7fc.png)

**Comment by maxstreifeneder** [comment]
Hi @NikhilSave14, 

thanks for your issue. I'll come back as soon as possible! 

Cheers,
Max

**Comment by qmacro** [comment]
Hi @NikhilSave14 - can you please confirm you used the `https` scheme (not `http`) in the URL, i.e. you went to https://localhost:8443 and not http://localhost:8443 ?

**Comment by NikhilSave14** [comment]
> Hi @NikhilSave14 - can you please confirm you used the `https` scheme (not `http`) in the URL, i.e. you went to https://localhost:8443 and not http://localhost:8443 ?

Hello,

Yes, I have used https only.

Regards,
Nikhil

**Comment by qmacro** [comment]
This definitely doesn't sound like any requirement to modify / fix the tutorial content, it feels more like a specific issue you're facing. For that, we'd please recommend you ask on Q&A  - https://community.sap.com/search/?ct=qa&mt=67837800100800004901&q=cloud%20connector&qt=all. Thanks for your understanding.
