### ISSUE TITLE
HANA Native, Create Database Artifacts Using Core Data Services (CDS)

### ISSUE THREAD

**Issue by I027876** [SAPDocuments/Tutorials#6021]
Tutorial URL: https://developers.sap.com/tutorials/xsa-cap-create-database-cds.html

Please specify the step you are referring to
Step 2.

Building the SRV module was successful. Building the DB module fails despite my HANA Cloud instance being up and running in the right subaccount and space.

Below is the Provision error saying there is no database available in space 'dev' within organization 'aadf933ctrial'.
I am logged onto my SCP trial account 'aadf933ctrial'. I can navigate to 'trial' subaccount -> dev space and can see my SAP HANA Cloud instance is up and running and I can open the Cockpit and the Explorer successfully.

2:57:23 PM (Provision) Could not create the 'myHANAapp-myHANAapp-db-hdi-containDoZpZHzOdsGtOGhM' instance of the 'hana' service type for the 'myHANAapp-db-hdi-container' resource. CF-ServiceBrokerRequestRejected(10001): Service broker error: Service broker hana-broker failed with: Can not create service instance 'myHANAapp-myHANAapp-db-hdi-containDoZpZHzOdsGtOGhM': There is no database available. Ensure that you have a database available in space 'dev' within organization 'aadf933ctrial'.
2:57:23 PM (Provision) Provision fail since one of the provision tasks finished with error.
2:57:23 PM (Executor) The "task for hdb build" provision finished with an error: Provision failed. See console for more details.
2:57:23 PM (HDB) Build of /myHANAapp/db failed due to Provision failed. See console for more details..

I also confirmed in the context menu of my project in the Web IDE (Full-Stack) -> project settings, that i have maintained the API Endpoint - https://api.cf.eu10.hana.ondemand.com, Organization - aadf933ctrial and Space - dev.

I deleted and recreated the CAP project to see if this would change behaviour but the error is consistent. 

If this is not the right forum, please let me know if i should go onto the Community forums instead?

**Comment by jung-thomas** [comment]
That error is pretty specific:
There is no database available. Ensure that you have a database available in space 'dev' within organization 'aadf933ctrial'.

I'm a little at a loss as that error is very specific and seems quite certain that you don't have a HANA. Yet clearly it sounds like you do.  Can you should some screenshots perhaps of the space from the cockpit / service instances view. Maybe also share from the mta.yaml the resources section with your HANA service.   Its a long shot but maybe see those will shed some light on the situation.

**Comment by I027876** [comment]
Thanks Thomas, 

I am in the process of recreating my HANA Cloud instance in SCP trial account (it takes some time). I agree, the error is very obvious but i definitely had a HANA Cloud instance running, as I had deployed some table artifacts successfully using Business Application Studio yesterday. Today i am trying the SAP Web IDE tooling as per the exercise. Hopefully, recreating my HANA Cloud instance in my trial account will magically fix the error. In case not i will send the mta.yaml and screenshot from SCP in case you spot something.

Thanks!
Julia

**Comment by jung-thomas** [comment]
Be sure when you create the HANA Cloud trail instance that use the Allow All IP Addresses option.

**Comment by I027876** [comment]
Yes i did that, cheers!

**Comment by I027876** [comment]
It's working now, i could build the DB module and complete the tutorial. 
Thanks for the support earlier, i should have tried recreating the HANA Cloud instance first. Not something you want to have to do everytime though....P.s. the tutorials are great and a lifesaver for learning this new topic area, so thanks a million for putting them together.
