### ISSUE TITLE
Create a Reusable Service

### ISSUE THREAD

**Issue by njgarg22** [SAPDocuments/Tutorials#6029]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html

Please specify the step you are referring to: `Step 5: Deploy the domain model`

I keep getting error on `cds deploy --to sqlite` that `sqlite module not found`.
Tried everything, nothing worked. 

Then, finally, I just installed `sqlite3` globally by `npm install -g --save-dev sqlite3`. It worked!!

Note: I'm not using `SAP Business Application Studio for Development` and I'm using Macbook.

**Comment by beckermarc** [comment]
Which version of `@sap/cds-dk` are you using? 
Can you please provide the output of `cds -v`?
In version `> 3.0.0 & <= 3.1.1` there was a bug, which could have caused this issue. This issue is already fixed with `3.1.2`.

**Comment by njgarg22** [comment]
```
~ % cds -v
@sap/cds: 4.2.4
@sap/cds-compiler: 1.43.0
@sap/cds-dk: 3.1.2
@sap/cds-foss: 2.1.0
@sap/cds-reflect: 2.13.1
@sap/cds-runtime: 2.5.2
Node.js: v12.18.4
home: /Users/i111111/.nvm/versions/node/v12.18.4/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds
```

**Comment by beckermarc** [comment]
Sorry, I forgot to mention that the fix also requires @sap/cds-runtime in version 2.5.3, which was only released today. You seem to be using `2.5.2`.
Can you reinstall the latest version of @sap/cds-dk again, which should automatically update @sap/cds-runtime as well?
You can confirm this using `cds -v`. Afterwards please try to reproduce the issue.

**Comment by njgarg22** [comment]
I installed `@sap/cds-dk` again and used `sqlite3` from ~global~ local: 

```
npm uninstall -g @sap/cds-dk
npm install -g @sap/cds-dk
npm uninstall -g sqlite3
npm install --save-dev sqlite3
cds deploy --to sqlite
```

It's working fine now 👍 💚 .

**Comment by njgarg22** [comment]
As the issue is fixed, I'm closing this issue. Thanks a lot, @beckermarc for the fix.
