### ISSUE TITLE
Reuse a CAP Java Service

### ISSUE THREAD

**Issue by njgarg22** [SAPDocuments/Tutorials#6030]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-service-reuse.html

Please specify the step you are referring to: `Step 4: Define bookstore service`

It's mentioned that: `The entity OrderItems isn’t explicitly listed in the OrdersService`.

But haven't we explicitly defined `OrderItems` in the `OrdersService` by following:

```
service OrdersService {
    entity Orders as projection on db.Orders;
    entity OrderItems as projection on db.OrderItems;
}
```

**Comment by beckermarc** [comment]
Yes, this is true. The OrderItems is explicitly listed, because later on we use some requests which directly target this entity.
If we didn't list the OrderItems entity these requests would not be allowed. @iwonahahn: Can you please remove this misleading sentence from the tutorial?
