### ISSUE TITLE
Secure Your Application on SAP Cloud Platform Cloud Foundry

### ISSUE THREAD

**Issue by sundarvc** [SAPDocuments/Tutorials#6033]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-secure-cloudfoundry.html

Hi , 

I completed till Step 5. The firstapp and approuter are running. The firstapp was working fine without security and also after Step 2. However, once I edited web.xml , the Integration Test was failing with 403 error like below

[ERROR] Failures: 
[ERROR]   HelloWorldServletTest.testService:50 
Expecting:
 <"<!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Access to the requested resource has been denied</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" /><h3>Apache Tomcat/8.5.50</h3></body></html>">
to be equal to:
 <"Hello SCP!">
ignoring case considerations

I commented the Integration Test out and moved to Step 5, then, now I get 401 error in the browser after Step 5 while accessing the app directly or through approuter.

Regards,
Sundar

**Comment by TanviiG** [comment]
Hello,

Thank you for your question.

As I understood you were able to access the app via approver and was successful till step2 of the tutorial. However, after introducing the security step 3 the integration test resulted in 403. 
 This is the intended behaviour as till step3 the user has not been given OAuth Scope "Display". Can you please verify the steps in step4 of the tutorial again? As in my opinion the problem could be that the Display OAuth scope is not assigned correctly to your user. 

Best Regards,
Tanvi

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
