### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by JanWehmeyerSAP** [SAPDocuments/Tutorials#6036]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Step 8, Part3 cds deploy leads to error: "[ERROR] Can’t find module 'sqlite3'"

node.js -version v12.19.0

package.json:
{
  "name": "my-bookshop",
  "version": "1.0.0",
  "description": "A simple CAP project.",
  "repository": "<Add your repository here>",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "@sap/cds": "^4",
    "express": "^4"
  },
  "devDependencies": {
    "sqlite3": "^5.0.0"
  },
  "scripts": {
    "start": "npx cds run"
  }
}

![Issue sqlite3](https://user-images.githubusercontent.com/73106146/96429429-38ac1100-1201-11eb-866b-33bf74dfe65c.PNG)

**Comment by renejeglinsky** [comment]
Hi Jan,

please update @sap/cds-dk to 3.1.2. This contains a fix for this.

```
npm update -g @sap/cds-dk
```

Regards,
René

**Comment by JanWehmeyerSAP** [comment]
![image](https://user-images.githubusercontent.com/73106146/96556471-4f15a380-12b9-11eb-9443-87af3030f23c.png)

as you can see from the package.json i have v4+ from the cds-dk. The update received a newer version. But dosn't fix the error. And the original install was done with:
`npm install -g @sap/cds-dk`

what got me the v4+ version in the first place, not a version v3

**Comment by renejeglinsky** [comment]
Besides @sap/cds v4+ in your project, you have installed the module @sap/cds-dk globally and this one has now version 3.1.2 after having done the update.

Please call `cds -v` to list all components in case the update doesn't give you the desired version.

**Comment by renejeglinsky** [comment]
Here is an example: 

![image](https://user-images.githubusercontent.com/32062331/96558460-fd224d00-12bb-11eb-870b-cc57236e36ff.png)

**Comment by JanWehmeyerSAP** [comment]
> Besides @sap/cds v4+ in your project, you have installed the module @sap/cds-dk globally and this one has now version 3.1.2 after having done the update.
> 
> Please call `cds -v` to list all components in case the update doesn't give you the desired version.

Yeah you got me! There is absolutley a difference between sap/cds and sap/cds-dk.

It's working now! Thanks for the fast fix!
