### ISSUE TITLE
Register SAP Cloud Platform Cloud Foundry Subaccount in Identity Authentication Service

### ISSUE THREAD

**Issue by Pavithra0705** [SAPDocuments/Tutorials#6038]
Tutorial URL: https://developers.sap.com/tutorials/cp-ias-azure-ad-cf.html

Please specify the step you are referring to

Hi , I need help to identify how the groups are being passed from Azure AD to IAS. Currently i added the SAML assertion attributes where I only see groupid as the option. In Cloud foundry i would map the role collection mapping to the group name and not id. The SAML response is returning the groupid of the group in Azure AD. When I access the application i get 403 because of this

**Comment by maxstreifeneder** [comment]
Hi @Pavithra0705,

you are right, it's only the ID coming back from Azure Active Directory which needs to be used for mapping SCP & AD. 

Sorry and regards,
Max
