### ISSUE TITLE
Tour the SAP Community

### ISSUE THREAD

**Issue by DigitalKeri** [SAPDocuments/Tutorials#6040]
Tutorial URL: https://developers.sap.com/tutorials/community-start.html

Please specify the step you are referring to
Step 3 - I was surprised only one other person reported this, though [his report](https://github.com/SAPDocuments/Tutorials/issues/4335) wasn't very clear, so I'll provide more detail.

I selected "New followers" and "Content I was mentioned in" because those are the ONLY TWO choices that were options on my profile (screenshot below) but was notified that was incorrect.  Then I guessed that "Comments and answers on my posts" would also be an option and got the answer correct.

However, as a brand new user (just created my account) "Comments and answers on my posts" is NOT an option for me at the time I am completing the community start steps.  I'm guessing that WILL be an option once I have permission to create posts.

So it's a bit of a catch 22 - I can't see that option until I finish the tour, and I can't finish the tour because I can't see that option.

After my correct guess on step 3, I was able to complete the tutorial.  When I logged back in, I still don't see the notification option for "Comments and answers on my posts" - maybe after I post a question or blog?

Regardless, I made it through the tutorial ... just wanted to make you aware of the issue.

![SAP_CommTutorial_feedback](https://user-images.githubusercontent.com/8096381/96505252-7a49b580-121b-11eb-82e6-ff8baa292cf8.jpg)

**Comment by WorkJerryJanda** [comment]
Thank you for the feedback. We are in the process of revamping, and we'll likely update within a few weeks.
Kind regards,
--Jerry

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
