### ISSUE TITLE
Build and Deploy Your SAP Fiori App to SAP Cloud Platform

### ISSUE THREAD

**Issue by vikasgith** [SAPDocuments/Tutorials#6041]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html

Please specify the step you are referring to
Hi,
In the step 
Under Step 1: Build the application->3. Select the command Build MTA.
The build process creates a multitarget archive (MTAR) file in your project that packages all the project modules for deployment. You can find the MTAR file in the **DemoFiori/mta_**archives folder.

Here Should n't the folder name be FioriDemo ?
I feel DemoFiori is a typo.

Thanks,
Vikas

**Comment by raz-korn** [comment]
Hi @vikasgith ,
Good catch.
I pushed and update. Should be available soon.
Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
