### ISSUE TITLE
Create an Empty SAPUI5 Project

### ISSUE THREAD

**Issue by vikasgith** [SAPDocuments/Tutorials#6044]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-101-create-project.html

Please specify the step you are referring to
Hi Marius,

Under Step 3: Create a new project
Sub Divison Step 8: 
Select My SAP Systems and the source Northwind. Enter /v2/northwind/northwind.svc/ for the path - don’t forget the ending slash. Click Next to create the new project.

Here should n't the path be /v2/Northwind/Northwind.svc/
**'N' in capital letter**

I followed initial steps, then (i.e /v2/northwind/northwind.svc/)
the metadata url was giving error in Debug window.

When changed to /v2/Northwind/Northwind.svc/ it was working fine.
https://bas3d3-workspaces-ws-dgljx-app1.eu10.trial.applicationstudio.cloud.sap/sapcpConnection/Northwind/v2/Northwind/Northwind.svc/$metadata?sap-language=EN

Theoretically web urls are not case sensitive, but here it seems it is case sensistive.
https://services.odata.org/Northwind/Northwind.svc/

This is the URL from odata.org

Thanks,
Vikas

**Comment by IObert** [comment]
Hi Vika,

thanks for opening the issue. That is strange because it shouldn't matter whether the N is capitalized or not - as you mentioned as well.
I just completed the tutorial myself and it works with lowercase letters as well. 

Can you try please try again to complete the tutorial with the lower case URL path?

**Comment by vikasgith** [comment]
Hi Marius,
The ticket can be closed.
I am unable to recreate the problem.
When I followed steps again, it was working fine.
Sorry .
Regards,
Vikas
