### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by toolivei** [SAPDocuments/Tutorials#6045]
https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html

The same error:
https://github.com/SAPDocuments/Tutorials/issues/5694

HANA instance is running!!!!

‎9‎:‎47‎:‎08‎ ‎AM (Executor) The "task for hdb build" process started.

‎9‎:‎47‎:‎08‎ ‎AM (Executor) Started the "task for hdb build" provision.

‎9‎:‎48‎:‎31‎ ‎AM (Provision) Service provisioning for module: "/db"

‎9‎:‎48‎:‎31‎ ‎AM (Provision) Created the 'my-hdi' instance of the 'hana' service type for the 'hdi_db' resource.

‎9‎:‎48‎:‎34‎ ‎AM (Executor) Starting process: "cd /projects/hana-cf-get-started-trial/db; export DEVX_MTA_RESOLVED_PLACEHOLDERS="{\"services\":[{\"platformName\":\"my-hdi\",\"resourceName\":\"hdi_db\",\"resourceProperties\":{},\"resourceType\":\"com.sap.xs.hdi-container\",\"serviceKeyName\":\"SharedDevKey\",\"serviceTarget\":{\"endpoint\":\"https://api.cf.us10.hana.ondemand.com\",\"org\":\"099cd5aftrial\",\"space\":\"dev\"}}]}"; export CF_HOME=/projects/.webide/cf/9e31b2af4913630e185051fa0ba1ad7d; export DEVX_MTA_HDI_BUILD_OPTIONS="{\"IsSelectiveBuild\":false,\"SelectedFiles\":[],\"IsSimulateBuild\":false,\"AdditionalOptions\":{\"migrationtable-development-mode\":true}}"; export PROJECT_PATH=/projects/hana-cf-get-started-trial/db; mkdir -p $CF_HOME/.cf/plugins/ && cp -u $CF_PLUGIN_PATH/config.json $CF_HOME/.cf/plugins/config.json 2>/dev/null || :;hdi-space-builder build -f /usr/local/resources/hdi-space-builder/manifest.yaml"

‎9‎:‎48‎:‎34‎ ‎AM (HDB) Executing Build command:

‎9‎:‎48‎:‎34‎ ‎AM (HDB)  HDI BUILDER VERSION:1.1.8-20200610150748

‎9‎:‎48‎:‎34‎ ‎AM (HDB) temp folder created at: /tmp/hdispacebuilder939425728

‎9‎:‎48‎:‎34‎ ‎AM (HDB) Starting pre-hdiBuild operations...

‎9‎:‎48‎:‎35‎ ‎AM (HDB) Creating module zip...

‎9‎:‎48‎:‎35‎ ‎AM (HDB) module directory is: /projects/hana-cf-get-started-trial/db

‎9‎:‎48‎:‎35‎ ‎AM (HDB) executing NPM script at: /projects/hana-cf-get-started-trial/db

‎9‎:‎48‎:‎35‎ ‎AM (HDB) zipping folder..... 

‎9‎:‎48‎:‎35‎ ‎AM (HDB) zip created at: /tmp/hdispacebuilder939425728/db.zip

‎9‎:‎48‎:‎38‎ ‎AM (HDB) connection to hdi deployer passed

‎9‎:‎48‎:‎38‎ ‎AM (HDB) No protocol version provided, using the latest version: 1.0.0

‎9‎:‎48‎:‎38‎ ‎AM (HDB) Log id: ce586bb70d64715eb6c9a72bbbe43d770b0c3bba

‎9‎:‎48‎:‎38‎ ‎AM (HDB) Using protocol version 1.0.0

‎9‎:‎48‎:‎38‎ ‎AM (HDB) FILE TRANSFER READY

‎9‎:‎48‎:‎38‎ ‎AM (HDB) File transfer completed successfully: Checksums match.

‎9‎:‎48‎:‎38‎ ‎AM (HDB) Requested version of @sap/hdi-deploy is ^3.11, found in package.json.

‎9‎:‎48‎:‎38‎ ‎AM (HDB) WARNING: db module specified version "^3.11". Best match found was version "3.11.10".

‎9‎:‎48‎:‎38‎ ‎AM (HDB) .serviceinfo.log,package.json,src

‎9‎:‎48‎:‎40‎ ‎AM (HDB) @sap/hdi-deploy, version 3.11.10 (mode default), server version unknown (0.0.0.0), node version 8.12.0, HDI version -1, container API version -1

‎9‎:‎48‎:‎40‎ ‎AM (HDB) Detection of server version failed; root cause: Connection failed (RTE:[89008] Socket closed by peer (49c4ae42-170d-4783-acfa-0abb53fe75eb.hana.trial-us10.hanacloud.ondemand.com:443))

‎9‎:‎48‎:‎40‎ ‎AM (HDB) Detection of container API version failed; root cause: Connection failed (RTE:[89008] Socket closed by peer (49c4ae42-170d-4783-acfa-0abb53fe75eb.hana.trial-us10.hanacloud.ondemand.com:443))
Detection of HDI version failed; root cause: Connection failed (RTE:[89008] Socket closed by peer (49c4ae42-170d-4783-acfa-0abb53fe75eb.hana.trial-us10.hanacloud.ondemand.com:443))

‎9‎:‎48‎:‎40‎ ‎AM (HDB) The server does not support live updating of make messages. The messages will be displayed, when the make is done.

‎9‎:‎48‎:‎41‎ ‎AM (HDB) No ignore file at /tmp/hdi-space-deploy-42xnGKX8AMGwMs-content/.hdiignore.

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Collecting files...

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Collecting files... ok (0s 3ms)

‎9‎:‎48‎:‎41‎ ‎AM (HDB) 1 directories collected
2 files collected
0 reusable modules collected
Target service: my-hdi

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Could not check if session variable APPLICATION is set correctly: Connection failed (RTE:[89008] Socket closed by peer (49c4ae42-170d-4783-acfa-0abb53fe75eb.hana.trial-us10.hanacloud.ondemand.com:443))

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Could not determine status of last build: Connection failed (RTE:[89008] Socket closed by peer (49c4ae42-170d-4783-acfa-0abb53fe75eb.hana.trial-us10.hanacloud.ondemand.com:443))

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Processing revoke files...

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Processing revoke files... ok (0s 0ms)

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Processing grants files...

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Processing grants files... ok (0s 0ms)

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Preprocessing files...

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Preprocessing files... ok (0s 0ms)

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Connecting to the container "DB_1"...

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Deployment to container DB_1 failed - error: Connection failed (RTE:[89008] Socket closed by peer (49c4ae42-170d-4783-acfa-0abb53fe75eb.hana.trial-us10.hanacloud.ondemand.com:443)) [depId].

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Error: Connection failed (RTE:[89008] Socket closed by peer (49c4ae42-170d-4783-acfa-0abb53fe75eb.hana.trial-us10.hanacloud.ondemand.com:443))

‎9‎:‎48‎:‎41‎ ‎AM (HDB) (2s 127ms)

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Deployment failed with exit code: 1

‎9‎:‎48‎:‎41‎ ‎AM (HDB) STRUCTURED LOG CHECKSUM f396267cb985ded3e59f92aeb8c9bb8bddcc169e0751e6d40b22a5f42d9d8b01

‎9‎:‎48‎:‎41‎ ‎AM (HDB) STRUCTURED LOG SIZE690

‎9‎:‎48‎:‎41‎ ‎AM (HDB) SENDING STRUCTURED LOG

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Ended because of error: Deployment failed with exit code: 1

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Build command failed : hdi-build operation failed: Deployment failed with exit code: 1

‎9‎:‎48‎:‎41‎ ‎AM (HDB) Build of /hana-cf-get-started-trial/db failed due to The "task for hdb build" process finished with code 1.

Thanks

**Comment by jung-thomas** [comment]
If your HANA instance is running, then also check the allow list and make sure you set it to Allow all IP addresses:
![image](https://user-images.githubusercontent.com/12159356/96589729-2b4f5f00-12b3-11eb-8403-3c9b7403e5c0.png)

**Comment by toolivei** [comment]
Perfect Thomas,

Thanks a lot for the help!!!
