### ISSUE TITLE
 Error C002: Activation of Integration Advisor capability has failed

### ISSUE THREAD

**Issue by mata-r** [SAPDocuments/Tutorials#6047]
I have tested with US and Europe new trial accounts and the Integration Advisor is failing to be provisioned.

Error Message: Error C002: Activation of Integration Advisor capability has failed. Please try again later. If the issue persists, please send your application URL and details of the error message to cpitrialfeedback@sap.com. 
_Note: I have tried everyday for 10 days_

![image](https://user-images.githubusercontent.com/72218379/96605563-f7c50280-12bb-11eb-94e9-6995583c5f22.png)

**Comment by MichaelCzcz** [comment]
@mata-r Please name the name and Step of the tutorial where you have encountered this issue.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
