### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by KatsuoAshimine** [SAPDocuments/Tutorials#6048]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

>For Consume Services, select the following, and click Next.
above point .

I can not select "ES5 [Catalog]".
I see only "ES5 (System URL)".

then
instead of..

I can see
"Enter a path to the OData service (e.g. /sap/opu/odata/sap/SERVICE_NAME)"

what riseed happne?

The following is Similar case
https://answers.sap.com/questions/13042297/es5-catalog-service-not-available.html

maby
I can write to  "ES5 (System URL)" filed
/sap/opu/odata/IWBEP/GWSAMPLE_BASIC/

but project generater get Abort.

{"message":"fiori-project generator failed - Failed to consume services due to: undefined\nAbort ui5-simple creation.","stack":"Error: Failed to consume services due to: undefined\nAbort ui5-simple creation.\n at Ui5SimpleGenerator._abortGenerator (/extbin/generators/ui5-generators/generator-ui5-simple/generators/app/index.js:205:24)\n at /extbin/generators/ui5-generators/generator-ui5-simple/generators/app/index.js:126:26\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"}

i solved!
WebIDEUsage=odata_abap,dev_abap

**Comment by raz-korn** [comment]
Hi @KatsuoAshimine ,

If I understand correctly - issue solved.
My assumption is that the destination was either missing odata_abap or contained odata_gen.

Regards - Raz

**Comment by KatsuoAshimine** [comment]
>missing odata_abap or contained odata_gen
yes,yes lol
That was exactly what happened
thank you for replay.
