### ISSUE TITLE
Integrate Your SAPUI5 App into Your Launchpad Site

### ISSUE THREAD

**Issue by federicopozzoni** [SAPDocuments/Tutorials#6055]
Tutorial URL: https://developers.sap.com/tutorials/cp-launchpad-integrate-sapui5-app.html

After fetching updated content using the Provider Manager as in step 1, in step 2 Content Manager>Content Explorer inside the HTML5 App no data is available (Suppliers is not present)

**Comment by LindsayBert** [comment]
Hi

Did you do all the tutorials in this group:  Integrate a Custom-Developed SAPUI5 App into Your Launchpad Site? https://developers.sap.com/group.portal-cf-add-apps.html 

If you created the **Suppliers** app in the third tutorial in this group, added the navigation properties to it, and then built and deployed the app to SAP Cloud Platform, it should be available in the HTML5 provider after you fetch the content.

Thanks Lindsay

**Comment by federicopozzoni** [comment]
Hi,

I have done again all the previous steps of the tutorials in the group. 
However the Suppliers app is still not available in the HTML5 provider, also after fetching the content.

**Comment by LindsayBert** [comment]
Hi

If you did all the tutorials then it can only be one of the following reasons:
1.	You used a standalone app router when you created the MTA
2.	You didn't add an intent to the app

If it's the first problem, you should delete the app from the space on Cloud platform and develop it again using this tutorial (https://developers.sap.com/tutorials/appstudio-fioriapps-create.html). Make sure you select '**Managed by SAP Cloud Platform**' App Router' (as explained in step 1.5)

Thanks
Lindsay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
