### ISSUE TITLE
Display Data from the Northwind Service

### ISSUE THREAD

**Issue by KatsuoAshimine** [SAPDocuments/Tutorials#6058]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-fiori-cf-display-data.html

Please specify the step you are referring to

I can progress until bellow
>Step 5: Redirect traffic to the data source

but, Products-view  was not appear in the Main-view.
I don't know why does not  appear Products-view.

append info:
http://localhost:1091/V2/Northwind/Northwind.svc/$metadata?sap-language=JA
was a appeared.

this is a my repo
https://github.com/KatsuoAshimine/Display-Data-from-the-Northwind-Servic

--manifest.json--

```
    "routing": {
      "config": {
        "routerClass": "sap.m.routing.Router",
        "viewType": "XML",
        "viewPath": "tutorial.products.view",
        "controlId": "idAppControl",
        "controlAggregation": "pages",
        "async": true
      },
      "routes": [
        {
          "name": "RouteMainView",
          "pattern": "RouteMainView",
          "target": [ 
            "TargetMainView"
          ]
        },
        {
          "name": "Products",
          "pattern": "", 　<-update to blank
          "target": [
            "TargetProducts"
          ]
        }
      ],
```

--MainView--

`<App id="idAppControl"/>`

--ProductsView--

```
  <Page id="Products" title="Available Products">
    <content>
      <List items="{/Products}">
        <StandardListItem type="Active" title="{ProductName}" />
      </List>
    </content>
  </Page>
```

---------------UI5.yaml-----------------
```
server:
  customMiddleware:
    - name: ui5-middleware-livereload
      afterMiddleware: compression
      configuration:
        port: 35729
        path: uimodule/webapp
    - name: ui5-middleware-cfdestination
      afterMiddleware: compression
      configuration:
        debug: true
        port: 1091
        xsappJson: approuter/xs-app.json
        destinations: 
          - name: "Northwind"
            url: "https://services.odata.org/"
```

**Comment by IObert** [comment]
Can you also share a screenshot of the error messages in the console of your browser?

**Comment by KatsuoAshimine** [comment]
@IObert 
this a image.
i have no see "title="Available Products" of Products-view

![image](https://user-images.githubusercontent.com/32809920/96941296-05bd9200-150d-11eb-85f6-ef1f8369d257.png)

**Comment by IObert** [comment]
I found the error. It seems that the generated created an invalid project. Go to the `Products.controller.js` and replace `undefined` with `products`. Then it will work.

The title that should display "Available Products" is above the list once the page has loaded. So the second comment is not an issue.

I hope this helps!

**Comment by KatsuoAshimine** [comment]
@IObert

big thanks.

I dont know way became undefined.
but at all it' all right.

program is working now.
