### ISSUE TITLE
Introductory video mentions an old product name

### ISSUE THREAD

**Issue by slavipande** [SAPDocuments/Tutorials#6059]
The introductory video on the landing page for the SAP Cloud Platform (URL: https://developers.sap.com/topics/cloud-platform.html#details) talks about SAP HANA Cloud Platform, which, as far as I know, is the old name for SAP Cloud Platform.

**Comment by IObert** [comment]
Thanks for pointing me to this! I forwarded it internally. I'll get back to you once I receive a response.

**Comment by IObert** [comment]
We removed the video for now until we have a replacement. Thanks for opening the issue!
