### ISSUE TITLE
Trigger a Microservice with an Event

### ISSUE THREAD

**Issue by cybaspace** [SAPDocuments/Tutorials#6060]
Tutorial URL: https://developers.sap.com/tutorials/cp-kyma-microservice-trigger.html

On step 2 you mention the file internal/api/events.go ... but it's stored unter package/api/ ... no problem with a modern IDE, but perhaps you will correct it.

**Comment by jcawley5** [comment]
Thank you. It will be fixed in the next pushed version of the tutorial.

**Comment by MichaelCzcz** [comment]
@jcawley5 Can I close this issue?

**Comment by jcawley5** [comment]
Yes this was fixed in the sample repo.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
