### ISSUE TITLE
Prepare the Local Development Environment

### ISSUE THREAD

**Issue by JanWehmeyerSAP** [SAPDocuments/Tutorials#6061]
Tutorial URL: https://developers.sap.com/tutorials/cp-prepare-local-dev.html

Step 1: using the string to get the chocolatery installed from the cmd is prevented from the mcafee security guard

**Comment by IObert** [comment]
Can you try another installation step that is referenced [here](https://chocolatey.org/docs/installation)

**Comment by JanWehmeyerSAP** [comment]
@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

This worked then in the powershell

Von: Marius Obert <notifications@github.com>
Gesendet: Donnerstag, 22. Oktober 2020 15:05
An: SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc: Wehmeyer, Jan <j.wehmeyer@sap.com>; Author <author@noreply.github.com>
Betreff: Re: [SAPDocuments/Tutorials] Prepare the Local Development Environment (#6061)


Can you try another installation step that is referenced here<https://chocolatey.org/docs/installation>

**Comment by IObert** [comment]
Nice!
