### ISSUE TITLE
Create and Configure a Process Variant

### ISSUE THREAD

**Issue by pjcools** [SAPDocuments/Tutorials#6063]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-workflowmanagement-configurepv.html

Please specify the step you are referring to
Step:3 Adding CFO approval to the Process variant

I added this according to the instructions however I always get an error when I try and activate. 

![image](https://user-images.githubusercontent.com/38389079/96978625-48fa1e00-156a-11eb-944b-aa06cec106f5.png)

I cannot continue with this tutorial. I notice there is an additional field in the trial environment that is not shown in the tutorials - not sure if that is causing the issue. 

KInd Regards
Phil Cooley

**Comment by Deeksha-R** [comment]
@pjcools the teams are looking into this issue. I suggest you to not spend time trying out these tutorials for now. I will inform you once the activation issue gets resolved.

**Comment by Deeksha-R** [comment]
@pjcools  this issue is now resolved. Please try to reactivate your process variant and test in the trial account.

Sorry for the delayed response.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
