### ISSUE TITLE
Automate and Extend Employee Onboarding

### ISSUE THREAD

**Issue by juanpablotoledo** [SAPDocuments/Tutorials#6064]
Mission URL: https://developers.sap.com/mission.cp-starter-ibpm-employeeonboarding.html

Hi I run again the booster and still having an error when I try to import events:

![image](https://user-images.githubusercontent.com/69924124/97024503-8041de00-151c-11eb-996b-8f96d5eb04e3.png)

![image](https://user-images.githubusercontent.com/69924124/97024549-8df76380-151c-11eb-92ac-9fa77c12ce47.png)

**Comment by ArchanaShukla** [comment]
Sorry for the inconvenience. This a product issue which is under fixture. It will be available anytime this week.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
