### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by YTarchouna** [SAPDocuments/Tutorials#6065]
Tutorial URL: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html

Hi, Thomas, 
once again many thanks for the detailed description in relation to "hana-trial-advanced-analytics
Unfortunately I can't get any further in step 6:
"Step 6: Create database artifacts
After I have selected the file "db" with BUILD , the following error message appears:
The "task for hdb build" process failed.
17:51:52 (HDB) Build command failed : hdi-build operation failed: Deployment failed with exit code: 1
17:51:52 (HDB) Build of /hana-cf-get-started-trial/db failed due to The "task for hdb build" process finished with code 1.

I have looked into the file and debuged all kinds of stuff. It does not know the table "COMMUNITY".

Best regards
Yosri Tarchouna

**Comment by jung-thomas** [comment]
Can you please post more of the build log. That portion only says that there was a failure, but there is much more output in the build log in the console that will give the reason for the failure.

**Comment by jung-thomas** [comment]
@YTarchouna -  Are you able to supply the rest of the log. We really need more details from that error log to be able to assist you.

**Comment by jung-thomas** [comment]
@YTarchouna I'd really like to help you out here with the issue you hit, but I can't really do anything unless you return and provide a little more details from the error log.

**Comment by YTarchouna** [comment]
I sincerely apologize for the delay in receiving an answer and a detailed error description (see Troubleshooting Guide, Chapter 2 to 2.1.2 )from me.

I will be logged in as a P-User with restricted rights instead of an S-User and it explains why several errors can consequently occur with some subscriptions of the SAP-Cloud Cockpit Trial Demo Version.

[Troubleshooting_Guide_EN.pdf](https://github.com/SAPDocuments/Tutorials/files/5506070/Troubleshooting_Guide_EN.pdf)
These errors are documented (See Troubleshooting Guide_EN)

I sincerely apologize for the inconvenience this may have caused. Thank you for your understanding and your patience.

BG,
Yosri Tarchouna

**Comment by YTarchouna** [comment]
I sincerely apologize for the delay in receiving an answer and a detailed error description (see Troubleshooting Guide, Chapter 2 to 2.1.2 )from me.

I will be logged in as a P-User with restricted rights instead of an S-User and it explains why several errors can consequently occur with some subscriptions of the SAP-Cloud Cockpit Trial Demo Version.

These errors are documented (See Troubleshooting Guide_EN  
[Troubleshooting_Guide_EN.pdf](https://github.com/SAPDocuments/Tutorials/files/5506079/Troubleshooting_Guide_EN.pdf)
)

I sincerely apologize for the inconvenience this may have caused. Thank you for your understanding and your patience.

BG,
Yosri Tarchouna

**Comment by YTarchouna** [comment]
for german speaking
[Troubleshooting_Guide_DE.pdf](https://github.com/SAPDocuments/Tutorials/files/5506083/Troubleshooting_Guide_DE.pdf)
