### ISSUE TITLE
Set Up SAP Cloud Platform Launchpad Service

### ISSUE THREAD

**Issue by scdsoft** [SAPDocuments/Tutorials#6066]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Please specify the step you are referring to "You have now been assigned to the **Launchpad_Admin role** and you can access the Launchpad service and carry out all your admin tasks."

The rolename must be a different one: **Portal_Admin**.

Please update your guide to help other developper.

T&BR

**Comment by IrisSasson** [comment]
Hi, the new service is called Launchpad and the tutorial is correct
Can you explain why you thohght the tutorial had a mistake?

**Comment by MichaelCzcz** [comment]
@scdsoft Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
