### ISSUE TITLE
Get Started with the Command-Line Interface for SAP Cloud Platform (sapcp CLI)

### ISSUE THREAD

**Issue by guptaviren** [SAPDocuments/Tutorials#6067]
Tutorial URL: https://developers.sap.com/tutorials/cp-sapcp-getstarted.html

Step 7: Understand the command syntax: options
Question: “Enter one of the two possible command calls to get help on sapcp list accounts/subaccount.”
Issue: I do not see the answer options, it's coming up as white space, hence cannot mark this step as done.
![image](https://user-images.githubusercontent.com/28987446/97105162-ed9d6c80-16de-11eb-8352-8479aa14a119.png)

**Comment by renejeglinsky** [comment]
Hi @guptaviren ,

there are no options to select. You are asked to "Enter one of two..." which means you have to write one of these into the provided textfield and the press "Submit Answer".

Regards,
René

**Comment by annawenger20** [comment]
Hi @guptaviren ,
René is right. You need to enter one of these:
sapcp list accounts/subaccount --help 
or
sapcp --help list accounts/subaccount 

Kind regards,
Anna

**Comment by guptaviren** [comment]
Thank you. didn't realise the answer could be a subjective one :D

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
