### ISSUE TITLE
Set Up a Basic Mock S/4HANA Service

### ISSUE THREAD

**Issue by prakash13t** [SAPDocuments/Tutorials#6070]
Tutorial URL: https://developers.sap.com/tutorials/cap-cloudsdk-1-mock-service.html

Please specify the step you are referring to Step-3
If we have on-premise OData service, how to get the .json format which is used in external/csn folder

Thanks,
Naga

**Comment by thecodester** [comment]
@prakash13t  These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question is more general and likely would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers.

https://answers.sap.com/index.html
https://www.sap.com/community.html
