### ISSUE TITLE
Set Up Business Rules for Determining Equipment

### ISSUE THREAD

**Issue by IsabellaMasselli** [SAPDocuments/Tutorials#6074]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-businessrules.html

Please specify the step you are referring to: Step 3. Importing Business Rules

Now getting BAD GATEWAY ERROR

**Comment by ArchanaShukla** [comment]
Hello Isabella,
Have you updated the password in BUSINESSRULES_APIHUB destination? If yes, can you open the rule application in incognito mode and try login again and do the steps.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
