### ISSUE TITLE
Integrate Your SAPUI5 App into Your Launchpad Site

### ISSUE THREAD

**Issue by juanpablotoledo** [SAPDocuments/Tutorials#6081]
Tutorial URL: https://developers.sap.com/tutorials/cp-launchpad-integrate-sapui5-app.html

Hi.

In the last step in the content manager of the launchpad the app deployed to cloud foundry is not there, I followed all the steps. If I call this url: 
https://5fed8a96trial-dev-fioridemo-approuter.cfapps.eu10.hana.ondemand.com/nsBusinessPartners/index.html

the app is executed ok.

when I go to the content explorer the app is not available. 

could you please assist.

Thank you.

Juan Pablo.
[error.pdf](https://github.com/SAPDocuments/Tutorials/files/5448568/error.pdf)

**Comment by LindsayBert** [comment]
Hi

If you did all the tutorials then it can only be one of the following reasons:

- You used a standalone app router when you created the MTA
- You didn't add an intent to the app

If it's the first problem, you should delete the app from the space on Cloud platform and develop it again using this tutorial (https://developers.sap.com/tutorials/appstudio-fioriapps-create.html). Make sure you select '**Managed by SAP Cloud Platform**' App Router' (as explained in step 1.5)

Thanks
Lindsay

**Comment by juanpablotoledo** [comment]
Thank you.

I am trying to deploy the app again an I am getting this error:

Service key "FioriDemo_ui_deployer-FioriDemo_html_repo_host-credentials" for service "FioriDemo-html5-app-host-service" already exists
Uploading content module "FioriDemo_ui_deployer" in target service "FioriDemo_html_repo_host"...
Deploying content module "FioriDemo_ui_deployer" in target service "FioriDemo_html_repo_host"...
Content deployment error: "[ERROR] Upload application content failed { CODE: '1001' } validation error: Application metadata for application nsBusinessPartners already exists in service instance 01b3a207-5915-496e-bb27-9870c8552fc5"
Content deployment for module "FioriDemo_ui_deployer" failed. Download the logs "FioriDemo_ui_deployer_FioriDemo_html_repo_host" via the dmol command and check them for more information.
A step of the process has failed. Retrying it may solve the issue.


Could you please tell me how to fix it.




Juan Pablo Toledo C.
Platform & Technologies Cloud Ambassador
Carrera 9 No.115-06, Edificio Tierra Firme, piso 24
Bogota, Colombia
M +57 316 7400659

**Comment by juanpablotoledo** [comment]
it worked, thank you.
