### ISSUE TITLE
Create an Application for Producing Messages

### ISSUE THREAD

**Issue by remi-sap** [SAPDocuments/Tutorials#6082]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-nodejs-producing-app.html

The function `setupOptions(tasks, options)` is defined but never used.

**Comment by MichaelCzcz** [comment]
@pradeeppanda-sap Please respond!

**Comment by pradeeppanda-sap** [comment]
yes true.
Checked with the development team. 

Please follow this example 

https://github.com/SAP-samples/enterprise-messaging-client-nodejs-samples/blob/master/xb-msg-amqp-v100-doc/examples/producer.js.

We will correct it.

regards
Pradeep

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
