### ISSUE TITLE
Error when the event is imported in the Events Acquisition tile.

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6090]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html

**Step 1: Set up sample events for workflow ----> Sub step 4.** 
After uploading EmployeeOnboardingEvents.json file getting the error "An error occurred while processing your request. Retry later or contact your service provider". It is also a Blocker.
![image](https://user-images.githubusercontent.com/65999547/97527642-d063e900-19d1-11eb-9d58-beb8830685e9.png)

Labels :
Landscape Labels: trail1, trail2 & trail3
SCPTest-eboard: Automate and Extend Employee Onboarding
Priority label :‘High-prio’

Best Regards,
Priyanka

**Comment by ArchanaShukla** [comment]
This was the bug which is fixed now in the product. Please test again and confirm. 

@MichaelCzcz - close the issue.
