### ISSUE TITLE
Implement Your First Screen in an iOS App

### ISSUE THREAD

**Issue by paisa5599** [SAPDocuments/Tutorials#6095]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-scpms-starter-mission-02.html

Step 5: Load customer and product data

Comsapedmsampleservicev2OnlineODataController 
Error: Cannot find type 'Comsapedmsampleservicev2OnlineODataController' in scope

these lines have an error
/// First retrieve the destinations your app can talk to from the AppParameters.
let destinations = FileConfigurationProvider("AppParameters").provideConfiguration().configuration["Destinations"] as! NSDictionary

/// Create a computed property that uses the OnboardingSessionManager to retrieve the onboarding session and uses the destinations dictionary to pull the correct destination. Of course we only have one destination here. Handle the errors in case the OData controller is nil. We are using the AlertHelper to display an AlertDialogue to the user in case of an error. The AlertHelper is a utils class provided through the iOS Assistant.
var dataService: ESPMContainer<OnlineODataProvider>? {
    guard let odataController = OnboardingSessionManager.shared.onboardingSession?.odataControllers[destinations["com.sap.edm.sampleservice.v2"] as! String] as? Comsapedmsampleservicev2OnlineODataController, let dataService = odataController.espmContainer else {
        AlertHelper.displayAlert(with: NSLocalizedString("OData service is not reachable, please onboard again.", comment: ""), error: nil, viewController: self)
        return nil
    }
    return dataService
}

**Comment by KevinMuessig** [comment]
Hi @paisa5599 ,

the tutorials for the mission just have recently updated. Please try again and see if it works now for you.
I've tested the new snippets and they should work now.

Thank you for your feedback,

KM
