### ISSUE TITLE
Create a Destination for the Northwind OData Services in the Neo Environment

### ISSUE THREAD

**Issue by MikkelJ** [SAPDocuments/Tutorials#6098]
Tutorial URL: https://developers.sap.com/tutorials/hcp-create-destination.html

Please specify the step you are referring to:

Step-5 and Step 6:

I'm getting follwing error when testing connnection 
`
Failure reason: "An error of type SSLHandshake occurred during check connection!"`

**Comment by IObert** [comment]
Hi,

thanks for opening the issue. We are already aware of this problem (SAP-samples/multi-cloud-html5-apps-samples#22 and OData/odataorg.github.io#255) but we need to wait for Microsoft to resolve the original issue.

**Comment by IObert** [comment]
It should be working again. Please check

**Comment by IObert** [comment]
I'll close this now. Please reopen if needed.
