### ISSUE TITLE
Create Data Model and Lock Object in SAP Cloud Platform ABAP Environment

### ISSUE THREAD

**Issue by AlexandreO33** [SAPDocuments/Tutorials#6101]
Same issue than a previous post....

Problem with STEP 5 : use of I_BusinessUser is not permitted => can't activate.

I use SAP cloud plateform trial, and i have an instance with SAP ABAP environment.

Lastest updates for eclipse ADT are installed at this date.

The course can be completed if i remove the association or is it needed for the next steps of the course?

Thanks a lot for your help.

ALexandre

**Comment by mervey45** [comment]
Hi @AlexandreO33 ,

This tutorial is marked with a licensed key on the top left corner., this means, that this tutorial only works for licensed systems. With ABAP trial you are not able to do so.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by AlexandreO33** [comment]
Yes sorry for not answering back.

Have a good day

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________
