### ISSUE TITLE
Create an Account on the Gateway Demo System

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#6102]
Tutorial URL: https://developers.sap.com/tutorials/gateway-demo-signup.html

Please specify the step you are referring to 5:

i would like to confirm access to the same set of data that is being exposed in subsequent steps, like e.g. fiori, however the standard table browser transaction SE16 is throwing an authorization error when browsing the actual data:

_Authorization Obj. S_TABU_DIS Table Maintenance (using standard tools such as SM30)       Authorization Field ACTVT      Activity                                                                03       Authorization Field DICBERCLS  Table Authorization Group                                               &NC&_

how do i obtain the authorization to compare data at the source with the data made later available in Fiori, odata, etc?

**Comment by jung-thomas** [comment]
First this issue doesn't fall within the scope of this tutorial.  For general questions on the usage of trial systems outside the scope of a particular tutorial, you should really ask those on the SAP Community Q&A instead. The ES5 system - Gateway Demo System is a shared environment with limited access to directly support a set of learning materials. The account security is intentionally limited to only the scope of what is necessary to perform those specific tutorials.
