### ISSUE TITLE
Test Hyperledger Fabric Chaincode API - unable to test

### ISSUE THREAD

**Issue by BibiAmeena** [SAPDocuments/Tutorials#6103]
Getting the below error. Though gave correct client_id and client_secret. Please help
![image](https://user-images.githubusercontent.com/33142247/97835832-0d491c00-1d01-11eb-8ecd-ae42066db15c.png)

**Comment by BibiAmeena** [comment]
@MichaelCzcz  / @chrisfries  - Please help.

**Comment by chrisfries** [comment]
Hi @BibiAmeena 
sorry for the late response. Have you tried to copy the credentials from the service key manually to the dialog?
If this does not work maybe try to delete the channel service instance and recreate it. You can delete the instance via the Service Instances tab in the cloud platform.

**Comment by BibiAmeena** [comment]
> Hi @BibiAmeena
> sorry for the late response. Have you tried to copy the credentials from the service key manually to the dialog?
> If this does not work maybe try to delete the channel service instance and recreate it. You can delete the instance via the Service Instances tab in the cloud platform.

Hi Chris,
I have tried all the above mentioned options, nothing is working for me.

**Comment by chrisfries** [comment]
Hi @BibiAmeena 

really hard to help you here since for me everything is working as expected and I don't get this error when authorizing.

I really think theres's some issue with this specific channel service instance. Can you try to create another channel in the hyperledger fabric dashboard and create a channel service instance for the new one?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by BibiAmeena** [comment]
It was the issue with the security software which is installed on my machine. I have made change in the security settings. Now I am able to test the application. Thanks for the help :)
Regards
Ameena
