### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by IsabellaMasselli** [SAPDocuments/Tutorials#6104]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html

Please specify the step you are referring to Step 1 Item 5.

The message stating that the events were imported successfully pops up.  The next step is to select the process id "onboard" from the popup, but it does not exist/was not imported/does not show in the popup???

**Comment by ArchanaShukla** [comment]
Hello Isabella, 
Did you run the exercise 3 & 4 where the workflow was deployed and process visibility scenario was created. If your events were imported successfully, then it should show. Can you refresh the screen and try again.

**Comment by IsabellaMasselli** [comment]
Hi Archana

Unfortunately I could not upload anything at all, so it kept stopping me
from completing anything...

I tried starting again but it did not correct anything, I kept getting the
same problems.

It seems like I did not have enough storage place to upload anything?

Thanks for you help
Regards
Isabella

**Comment by thecodester** [comment]
@IsabellaMasselli Is this still an issue?

@ArchanaShukla Let us know when this is resolved.

**Comment by ArchanaShukla** [comment]
@thecodester - please close the ticket.
@IsabellaMasselli - Please resolve the storage issue, and reopen if you still have issues after storage issue is solved.
