### ISSUE TITLE
Consume the API Proxy in SAP Web IDE

### ISSUE THREAD

**Issue by genejerrell** [SAPDocuments/Tutorials#6110]
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-webide-int.html

Hi,

I have followed the manual on developer.sap.com written by Meredith Hasset “Consume the API Proxy in SAP Web IDE”. I have filled in the information below. 

Name: APIM_DevPortal_Trial
Type: HTTP
Description: Destination to API Developer Portal
URL: https://devportalu34f5b50f-s0000000000trial.hanatrial.ondemand.com/
Proxy Type: Internet
Authentication AppToAppSSO

![image](https://user-images.githubusercontent.com/73936391/98095544-03532480-1e8b-11eb-96e2-30adabe8d4ad.png)

However, I keep getting the message:
Connection to "APIM_Endpoint_Trial" established. **Response returned: "404: Not Found".**

![image](https://user-images.githubusercontent.com/73936391/98095611-17972180-1e8b-11eb-8a15-3ece738d779d.png)

Is this tutorial up to date? Can someone explain to me, what I am doing wrong?

Kind regards,

Gene

**Comment by shilpavij** [comment]
Web IDE tutorial is decommissioned as of today.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
