### ISSUE TITLE
Add a New Entitlement to Your Subaccount

### ISSUE THREAD

**Issue by OlgaWerner** [SAPDocuments/Tutorials#6115]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-entitlements-add.html

Please specify the step you are referring to:

Step 4: Add more entitlements to subaccount

The names of some of the services changed or are not available (at least not on trial).
ABAP trial --> ABAP environment
Connectivity --> not available
Destination --> not available
HTML5 Applications --> not available

**Comment by IObert** [comment]
Good catch, thanks for pointing that out! I updated the tutorial accordingly. The changes should be live soon.
