### ISSUE TITLE
Enable the SAP Translation Hub Service

### ISSUE THREAD

**Issue by OlgaWerner** [SAPDocuments/Tutorials#6116]
Tutorial URL: https://developers.sap.com/tutorials/sth-enable.html

Please specify the step you are referring to:
Step 1: Launch SAP Web IDE

The "Launch SAP Web IDE" button is not available anymore, which makes it difficult to follow the additional steps.

**Comment by beapasch** [comment]
I will work on this topic asap

**Comment by beapasch** [comment]
https://github.com/SAPDocuments/Tutorials/pull/6192

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
