### ISSUE TITLE
Get Started with  SAP Cloud  Platform Business Rules - Tutorials not available

### ISSUE THREAD

**Issue by kbprasad79** [SAPDocuments/Tutorials#6117]
Mission URL: https://developers.sap.com/mission.cp-rules-get-started.html

Tutorials not available

**Comment by MichaelCzcz** [comment]
@VandanaVasudevan all tutorials are available as far as I have seen. Maybe you can find out more.

**Comment by VandanaVasudevan** [comment]
Hi @kbprasad79 ,

I'm able to access the mission and tutorials. Can you try accessing it once again?

Best Regards,
Vandana

**Comment by MichaelCzcz** [comment]
@kbprasad79 Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
