### ISSUE TITLE
Download and Prepare App for Cloud Foundry Deployment

### ISSUE THREAD

**Issue by OlgaWerner** [SAPDocuments/Tutorials#6120]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-dev-01-prepare-app.html

This is related to following tutorial:
https://developers.sap.com/tutorials/cp-cf-dev-02-deploy-app.html
Step 3: Deploy the sample application

But the issues is created in this tutorial:
https://developers.sap.com/tutorials/cp-cf-dev-01-prepare-app.html
Step 5: Add a unique host name to the deployment descriptor

I've added numbers to the host name (as can be seen in the screenshot of the tutorial as well) and had following error message showing up after deploying the app:
**Unable to create route. The route is invalid. Enter a valid Host Name. Please specify a different route.**

I changed the host name, got rid of the numbers, and it worked fine. Maybe this could be tested by someone else to verify if this happens to more users as well.

**Comment by qmacro** [comment]
Hi @OlgaWerner thanks for the note. Routes with hostnames containing numbers are fine, I've just re-tested it now:

```
0 of 1 instances running, 1 starting
1 of 1 instances running

App started


OK

App cf-nodejs was started using this command `npm start`

Showing health and status for app cf-nodejs in org 58f45caftrial / space dev as dj.adams@sap.com...
OK

requested state: started
instances: 1/1
usage: 192M x 1 instances
urls: qmacro-testing123.cfapps.eu10.hana.ondemand.com
last uploaded: Mon Nov 9 07:05:04 UTC 2020
stack: cflinuxfs3
buildpack: nodejs

     state     since                    cpu    memory          disk        details
#0   running   2020-11-09 07:05:34 AM   0.0%   20.2M of 192M   97M of 1G
~/Desktop/cf-sample-app-nodejs-master
$
```

If this issue persists for you, you might want to check out [SAP Community Q&A](https://answers.sap.com) where you can tag your question to have it appear in the appropriate section, and where others will also benefit from your question, and everyone from the answers you receive. Thanks!
