### ISSUE TITLE
Create an ABAP Database Table provided if_oo_adt_classrun~main. is not running

### ISSUE THREAD

**Issue by EwaldStricker** [SAPDocuments/Tutorials#6121]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-create-table.html

Please specify the step you are referring to:
Step 17: Copy code

it seems that the code 

lt_accounts = VALUE #()

    ( client ='100'  ... 
do not run any more  -> throws ERROR: "VALUE #(  )" expected, not "VALUE #()".

while

TYPES: t_accounts TYPE table of ZACCOUNTS_022 WITH DEFAULT KEY.

"read current time stamp
GET TIME STAMP FIELD DATA(zv_tsl).

"fill internal table
DATA(lt_accounts) = VALUE t_accounts(
    ( client ='100' account_number ='00000001' bank_customer_id ='100001' bank_name ='Volksbank' city = 'Gaertringen' balance ='200.00 ' currency ='EUR' account_category ='01' lastchangedat = zv_tsl )
    ( client ='100' account_number ='00000002' bank_customer_id ='200002' bank_name ='Sparkasse' city ='Schwetzingen' balance ='500.00 ' currency ='EUR' account_category ='02' lastchangedat = zv_tsl )
    ( client ='100' account_number ='00000003' bank_customer_id ='200003' bank_name ='Commerzbank' city ='Nuernberg' balance ='150.00 ' currency ='EUR' account_category ='02' lastchangedat = zv_tsl )
).

works for me.
using:

Eclipse IDE for Java Developers (includes Incubating components)
Version: 2020-09 (4.17.0)
Build id: 20200910-1200
OS: Windows 10, v.10.0, x86_64 / win32
Java version: 14.0.2
ABAP Development Tools
Version: 1.113.0
© 2010-2020 SAP SE. All rights reserved.

Do I need an other environment setup? 
Any advise would be appreciated

KR Ewald

**Comment by julieplummer20** [comment]
Hi KR Ewald,
The error "VALUE #( )" expected, not "VALUE #()" usually tells you that you have left out a space character immediately after the first parenthesis and immediately before the second. In this case, there is an extra closing parenthesis. If you change it to "lt_accounts = VALUE #( ", then it should work.
I apologize for the inconvenience. 

"VALUE t_accounts(  )" and "VALUE #(  )" are two different slightly variants of the VALUE statement. See ABAP keyword docu for more information. Apologies if you are aware of this already, but the information may be helpful to others:
[https://help.sap.com/doc/abapdocu_cp_index_htm/CLOUD/en-US/index.htm](https://help.sap.com/doc/abapdocu_cp_index_htm/CLOUD/en-US/index.htm)

Thanks for getting in touch.
Best wishes,
Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
