### ISSUE TITLE
Use Data Attribute Recommendation to Train a Machine Learning Model

### ISSUE THREAD

**Issue by saksham001-crypto** [SAPDocuments/Tutorials#6122]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dar-model.html

Please specify the step you are referring to

it would have been good if with each such tutorial you could provide some information about the business scenario as well. probably in the initial part of the every tutorial, add a section of the business use case story , etc stuff

**Comment by Juliana-Morais** [comment]
Hello,

Thank you for the feedback.
I'll follow up with the service Product Owner and I'll update the tutorial as soon as possible.

Best regards,
Juliana

**Comment by MichaelCzcz** [comment]
@Juliana-Morais Any updates?

**Comment by Juliana-Morais** [comment]
We plan to update the tutorials ASAP in January.

**Comment by Juliana-Morais** [comment]
Business Use Case descriptions are now available. This issue can be closed.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
