### ISSUE TITLE
Get Started with SAP API Management

### ISSUE THREAD

**Issue by adithyak369** [SAPDocuments/Tutorials#6123]
Group URL: https://developers.sap.com/group.cp-apim-code-1.html

Hello Team, I am unable to complete the mission "https://developers.sap.com/group.cp-apim-code-1.html", for the last tutorial i.e., "Consume the API Proxy in SAP Web IDE", because of 2 reasons:

1. Unable to set the destination "Web_IDE_to_APIM_Designtime", because in the trial cloud foundry account, we do not have Authentication type as ApptoAppSSO. If I want try in Neo account, it is not even available for us in trial version.
2. We do not have WebIDE Fullstack now for Cloud foundry, we just have Business Application Studio. I could not find anywhere about how to setup to connect API Proxy with Business Application Studio. 

Can you please recheck this Tutorial and help complete the mission? As a next step, I would like to try to consume Business Rules API as well inside this API Management. If you have any information about that, please share it too.

Thanks in advance

**Comment by adithyak369** [comment]
do we have any update please?

**Comment by adithyak369** [comment]
looks like there is no use of commenting anything here

**Comment by greg2git** [comment]
don't get discouraged, the more specific your issue is the more chances you have it will be addressed. give the assignee some time as they may not have all the information that you are after. i think a lot of Neo services are in the process of being rewritten for the cloud foundry, something that has started about a year ago, but obviously has not been fully transitioned yet.

**Comment by shilpavij** [comment]
Dear All,

Kindly give the engineering teams some time to work on the backlog of integrating SAP WEB IDE now know as Business Application Studio to APIM. This is the transition for the services too when it comes from moving from NEO to CF. The integration points are being worked upon therefore this tutorial is decommissioned as of today. I hope this helps! We will enable it as soon as the integration is developed and tested.

I hope this helps!

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
