### ISSUE TITLE
Set Up Workflow Management in Cloud Cockpit

### ISSUE THREAD

**Issue by adithyak369** [SAPDocuments/Tutorials#6127]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html

Please specify the step you are referring to

![image](https://user-images.githubusercontent.com/4032404/98396754-d8e89f00-2023-11eb-8c14-8ede0edbe9a8.png)

Seeing the issue when clicking the Start button for setting up account for workflow management

**Comment by ArchanaShukla** [comment]
Can you try now, there must be some brief outage in the datacenter.

**Comment by thecodester** [comment]
@adithyak369 Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
