### ISSUE TITLE
Git receive not permitted 

### ISSUE THREAD

**Issue by VigneshYathavan** [SAPDocuments/Tutorials#6130]

**Comment by VigneshYathavan** [comment]
I am getting issue like git receive pack not permitted while pushing code to github

**Comment by thecodester** [comment]
What does this issue relate to? These issues are related to problems with actual published tutorials.

**Comment by VigneshYathavan** [comment]
I tried to to the code to remote git repository from STS and I ak getting this issue

**Comment by thecodester** [comment]
Is this about a tutorial? Is so, which one? Which step are you having an issue with? 

If the problem is more using the system, you should reach out to the community, which has thousands of people monitoring it and can more easily help you.

https://answers.sap.com/index.html

**Comment by VigneshYathavan** [comment]
I am learning java through udemy portal and there i tried to create a new public repository and try to push it from STS IDE while I try to commit and push the code to repository facing this issue.

**Comment by thecodester** [comment]
Can you start from the beginning -- how is this related to SAP? What are you trying to do -- and how ts this related to this repo?
