### ISSUE TITLE
Call API Business Hub API from a SAPUI5 Application

### ISSUE THREAD

**Issue by tristabap** [SAPDocuments/Tutorials#6131]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-api-ui5-app.html

Step 10: Unable to view the data. Getting the following error in the browser dev tools:

Access to XMLHttpRequest at 'https://sandbox.api.sap.com/successfactors/odata/v2/User?_=1604969565017' from origin 'https://pxxxxxxxxxtrial-dev-tutorial-approuter.cfapps.eu10.hana.ondemand.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by IObert** [comment]
Thanks for opening the issue. You are right, the tutorial is currently broken and I'll try to fix it later this week.

For now, please have a look at [this documentation page](https://help.sap.com/viewer/DRAFT/bcbb716c051b427cbe8ec7fe8362c9e5/DEV2/en-US/54ce98a4f9cf454e8b18224623c00aba.html) that explains the correct flow.

**Comment by IObert** [comment]
I just pushed the update. The changes should be live soon. It should work then.
