### ISSUE TITLE
Maintain a Communication Arrangement for Inbound Communication

### ISSUE THREAD

**Issue by Ouarzazate** [SAPDocuments/Tutorials#6132]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

Please specify the step you are referring to

Hi,

In step 3, I cannot find the 'Maintain Communication User' tile and don't know how to assign 'SAP_CORE_BC_COM' to my user.
Please help check this. You can reach me via hui.xie@sap.com

Thank you so much!

**Comment by mervey45** [comment]
Hi @Ouarzazate ,

you need to log in with the administrator in your system and then business catalog SAP_CORE_BC_COM to your business user and then log in with your business user. 

Best regards, 
Merve

**Comment by Ouarzazate** [comment]
Hi Merve,

I am using the trial account, could you advise me how can I login with the administrator account?
Thank you very much.

Kind regards,
Hui

**Comment by mervey45** [comment]
Hi @Ouarzazate ,

you are not able to do this tutorial with the trial account, you need a licensed system. The trial system is limited and not everything can be done there. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
