### ISSUE TITLE
Set Up Workflow Management in Cloud Cockpit

### ISSUE THREAD

**Issue by AnnikaGonnermann** [SAPDocuments/Tutorials#6134]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html

Dear Archana,
I found a tiny typo which I would like to share with you:

"Automated onboarding will be started with pre-configured steps.

It with take 4-5 minutes to complete the entire setup." >> "With" > "Will"

![booster](https://user-images.githubusercontent.com/61680396/98642101-24a18e00-232d-11eb-8e7a-8c29a5c21b47.PNG)

Best
Annika

**Comment by ArchanaShukla** [comment]
Updated the tutorial.

@MichaelCzcz - please close the ticket
