### ISSUE TITLE
Error executing cds deploy -2 hana

### ISSUE THREAD

**Issue by sammok83** [SAPDocuments/Tutorials#6135]
​Based on the sample here:

https://github.com/SAP-samples/cloud-cap-samples/tree/openSAP-week2-unit4567

When i did as per the instructions and deploy, I got the error:
Connecting to the container "3DB18AFD7A924A7E95853D9269B07261"... Deployment to container 3DB18AFD7A924A7E95853D9269B07261 failed - error: Could not connect to any host: [ 9357d90a-4543-497a-a574-d15c2a223feb.hana.trial-us10.hanacloud.ondemand.com:443 - certificate has expired ] [Deployment ID: none]. Error: Could not connect to any host: [ 9357d90a-4543-497a-a574-d15c2a223feb.hana.trial-us10.hanacloud.ondemand.com:443 - certificate has expired ]

Posted here but couldn't get help:
https://answers.sap.com/questions/13182707/error-executing-cds-deploy-2-hana.html?childToView=13182712#answer-13182712

**Comment by MichaelCzcz** [comment]
Sorry, but this channel is only for issues related to tutorials in the SAP Tutorial Navigator.

**Comment by iwonahahn** [comment]
Hi @sammok83, I have forwarded your question in the community to the SAP Business Application Studio colleagues again. They were notified twice, cause you have used the tag for BAS while posting the question. So please be patient.
