### ISSUE TITLE
Deploy the Fiori App to Cloud Foundry

### ISSUE THREAD

**Issue by khan-shahzad** [SAPDocuments/Tutorials#6138]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-fiori-cf-deploy.html

**Step 2: Deploy the built archive**
The "portal" service with "standard" subscription required to deploy the app is not available in SAP Cloud Foundry trial account. How to overcome this problem?

![image](https://user-images.githubusercontent.com/49327510/98753444-3b2d0f80-2429-11eb-9b5a-283b8279f858.png)

**Comment by IObert** [comment]
I'll reach out internally to see what is going on here. Can you confirm that you use region EU10 or US10?

**Comment by khan-shahzad** [comment]
> I'll reach out internally to see what is going on here. Can you confirm that you use region EU10 or US10?

Hi, I'm on EU10.

**Comment by AviadRivlin** [comment]
Please see the comment on the blog: https://blogs.sap.com/2019/07/22/portal-service-available-on-sap-cloud-platform-cloud-foundry-trial-account/ (in short, portal was removed from trial) and replaced by the [SAP Cloud Platform Launchpad](https://blogs.sap.com/2020/09/08/start-your-free-trial-for-sap-cloud-platform-launchpad/).

**Comment by IObert** [comment]
Thanks for confirming @AviadRivlin.

@khan-shahzad This means I need to rework the tutorial. I'll let you know what the next steps are.

**Comment by IObert** [comment]
I just learned that we temporarily added the portal service back to trial. Can you check if this works now?

Nevertheless, I need to update the tutorial.
