### ISSUE TITLE
Add Transactional Behavior to Your Core Data Services

### ISSUE THREAD

**Issue by Ouarzazate** [SAPDocuments/Tutorials#6139]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-transactional-enablement.html

Please specify the step you are referring to 'Step 4: Create behavior implementation'

Hi,

I cannot find the 'New Behavior Implementation' after the behavior definition is created in the Ecliplse ADT. Please check more detail in the attachment. Thank you.

![Step 4 - Create behavior implementation](https://user-images.githubusercontent.com/16385066/98783058-e3e06c80-2433-11eb-81d0-67ab45910342.png)

**Comment by mervey45** [comment]
Hi @Ouarzazate ,

thank you for your feedback. We will update this as soon as possible. Please do following: 
Right-click on your package > select file on your menu > new > other > search for behavior implementation and select it.

Best regards, 
Merve

**Comment by Ouarzazate** [comment]
Hi Merve,

Thank you for your reply, I've just tried it, but cannot find 'Behavior Implementation' in the menu, please see in the attachment. Does it mean I miss some role, maybe?

Kind regards,
Hui
![No_behavior_impl](https://user-images.githubusercontent.com/16385066/99207459-fc1c0700-27f8-11eb-8a53-1f9efd658803.jpg)

**Comment by mervey45** [comment]
Hi @Ouarzazate ,

no, you have the right roles. The UI just changed, we will update this as soon as possible.

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @MichaelCzcz, 

we can close this ticket. 

Best regards, 
Merve
