### ISSUE TITLE
Set Up Workflow Management in Cloud Cockpit

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#6141]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html

Please specify the step you are referring to: Step 2: Set up your account using Booster

In step 2.2 when we are running the booster it is failing at Assigning Service Quotas for workflow entitlement. We get the below error
<img width="293" alt="4" src="https://user-images.githubusercontent.com/69286515/98801952-961a3300-2438-11eb-9446-e5b5f3ee1d9f.png">

 Even though when we try to add it manually we get the below errors
<img width="332" alt="5" src="https://user-images.githubusercontent.com/69286515/98802025-af22e400-2438-11eb-8612-f657c462b591.png">
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/69286515/98802148-d8437480-2438-11eb-9f07-3dd431719d16.png)

Note: Since we were executing the scenario in the trial account we have first removed the workflow entitlement from other subaccount but still facing the issue.

Please tell what can be done.

Landscape Labels: trail3
Sprint Label: SCPTest-2010A 
SCPTest-eboard
Priority label - High-prio

**Comment by ArchanaShukla** [comment]
There were issues last week in workflow service in trial. Please check now, if it is reproducible, reopen the issue. 
@MichaelCzcz - close the ticket

**Comment by AkankshaKullu** [comment]
Thank you the issue has been resolved and I was able to execute the scenario successfully.
