### ISSUE TITLE
Create and expose a custom CDS view

### ISSUE THREAD

**Issue by ekc7us** [SAPDocuments/Tutorials#6142]
Tutorial URL: https://developers.sap.com/tutorials/abap-extensibility-custom-cds.html

General remark:
The tutorial is using the Custom CDS Views To Be Deprecated app which doesn't have anymore the option to create a custom CDS View.

**Comment by mervey45** [comment]
Hi @ekc7us ,

thank you for your feedback. We will process your feedback as soon as possible.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
