### ISSUE TITLE
Use SAP Web IDE OData Features to Create a Simple App

### ISSUE THREAD

**Issue by AlexandreO33** [SAPDocuments/Tutorials#6145]
Tutorial URL: https://developers.sap.com/tutorials/odata-03-webide-odata-features.html

**STEP 4**

Hello,

When creating Project from template with web IDE, i don't have any data available using "Service URL"
![Web IDE - No destination available](https://user-images.githubusercontent.com/73787725/98835974-67ed2100-2441-11eb-8f34-efd15de252cd.png)

Destination to northwind:
![Destination northwind OK](https://user-images.githubusercontent.com/73787725/98836046-85ba8600-2441-11eb-8ce9-c6805257c012.png)

Entitlement web ide
![Entitlement web ide](https://user-images.githubusercontent.com/73787725/98836083-92d77500-2441-11eb-981d-edf54e5392dd.png)

What can i do please?

Regards,
Alexandre

**Comment by thecodester** [comment]
@qmacro How can I help here?

**Comment by AlexandreO33** [comment]
Hello,

I’m at STEP 4 : Specify the Odata Service.

In the tutorial I’m supposed to retrieve the service to northwind that I ve declared in my destination (SAP Cloud foundry)

I did all the config on cloud foundry trial instead of neo trial because I couldn’t create a neo trial account as I have already a cloud foundry account (or I don’t know how to achieve that).

Well, with the screenshots I showed that everything is configured but I can’t get my northwind destination in the web IDE wizard when creation a new project from template (SAP Fiori application worklist).

Any help please?

De : Daniel Wroblewski <notifications@github.com>
Envoyé : jeudi 12 novembre 2020 09:08
À : SAPDocuments/Tutorials <Tutorials@noreply.github.com>
Cc : AlexandreO33 <alexourth@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [SAPDocuments/Tutorials] Use SAP Web IDE OData Features to Create a Simple App (#6145)


@qmacro<https://github.com/qmacro> How can I help here?

**Comment by thecodester** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question is more general and likely would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers.

https://www.sap.com/community.html
https://answers.sap.com/index.html

**Comment by AlexandreO33** [comment]
Well i follow steps of a tutorial, and in one step of this tutorial something is not working soooo i thought it was the good place to Ask. Ok too bad i ll ask the community as you said.

Have a good day

Téléchargez Outlook pour Android<https://aka.ms/ghei36>
________________________________
