### ISSUE TITLE
SAP Mobile Cards - Tutorial Update

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6146]
Hello,

Scenario link: https://developers.sap.com/tutorials/cp-mobile-cards-action.html#b0de6140-460f-47d5-a7c7-811d29bfe4b4

Step 8: Cross verify status update in the back end ->In the Mobile Services cockpit, click Connectivity under the Features tab. ->
statement should be "click MOBILE Connectivity" not just Connectivity.

Also, at step : If you cannot find particular data set, click Entity Properties to select some properties, then click OK. -> click on "SUBMIT" is there instead of "OK"

Thanks,
Shubham

Landscape label: trail1 & trail2 & trial3
Scenario label : SCPTest-mcard
Priority : Low-prio
Sprint Label: SCPTest-2010A

**Comment by sandeep-tds** [comment]
Hi @i353590 

Thank you for raising the issue.

@shahchetali can you please look into the issue?

**Comment by shahchetali** [comment]
Hi,

I will update the issue mentioned.

Thanks,
Chetali

**Comment by thecodester** [comment]
@shahchetali Any updates?

**Comment by shahchetali** [comment]
Hi @thecodester , @i353590 ,

We have modified the tutorial, can you review it once now?

Thanks & Regards,
Chetali Shah

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
