### ISSUE TITLE
SAP Mobile Cards - Template creation failing - US Region

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6147]
Hello,

scenario URL: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html
Step 2:
In the Select Cards tab of the wizard, select the Sample Template Welcome Card and click Next.

Getting this error: API rate limit exceeded for 193.16.224.13. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) Please refer to attachment.

![image](https://user-images.githubusercontent.com/66831161/98894441-c7434380-24ca-11eb-9825-8aaffd7a0112.png)

Labels to be added:
Sprint Label: SCPTest-2010A

Scenario Label:SCPTest-mcard 
Landscape Labels: trial2
prio: high-prio

Thanks,
Shubham

**Comment by sandeep-tds** [comment]
Hi @i353590 

Thank you for raising this issue. 

We will be tracking this issue as a part of this GitHub issue. 
https://github.com/SAPDocuments/Tutorials/issues/6330

@MichaelCzcz Can you please close the ticket?

Warm Regards
Sandeep T D S
