### ISSUE TITLE
Mobile Cards - Cards not loading in Mobile app - US region

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6148]
Hello,

Scenario URL:https://developers.sap.com/tutorials/cp-mobile-cards-action.html

Tap MobileCardsIcon ‘Back’ icon to to see the latest cards downloaded to the device.->
Card not loading in mobile app -> in the app activity log : failed to process card from subscription Content action card

Labels to be added:
Sprint Label: SCPTest-2010A

Scenario Label:SCPTest-mcard 
Landscape Labels: trial2
prio: high-prio

Thanks,
Shubham

**Comment by sandeep-tds** [comment]
Hi @i353590

Thank you for your feedback. I will add the required details.
The changes will be available next week.

Warm Regards
Sandeep T D S

**Comment by thecodester** [comment]
@sandeep-tds Please update this issue when changes are published.

**Comment by sandeep-tds** [comment]
Hi @i353590 

The updated tutorial has been released, can you please verify the changes and update the ticket?

Thank you so much for your support.

Warm Regards
Sandeep T D S

**Comment by i353590** [comment]
Hello @sandeep-tds,
yes, after the new tutorial release, this issue doesn't exist anymore.
You may close the ticket.

Thanks,
Shubham
