### ISSUE TITLE
Mobile Cards: Sub step numbers not maintained 

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6149]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-mobile-cards-setup.html

Already reported: https://github.com/SAPDocuments/Tutorials/issues/5983
Sub-step numbering is not maintained for entire tutorial. Only steps are mentioned, Sub step nos. are not mentioned.
It was mentioned that changes will be available by October, but tutorial is still not updated.
please update the tutorial.

Thanks,
Shubham

Labels to be added:
Sprint Label: SCPTest-2010A
Scenario Label:SCPTest-mcard 
Landscape Labels: trial1, trial2, trial3
prio: low-prio

**Comment by sandeep-tds** [comment]
Hi @i353590

We recently updated the tutorials. These issues have been addressed in the previous release.
Can you please confirm if the issues raised have been resolved?

Warm Regards
Sandeep T D S

**Comment by i353590** [comment]
Hello @sandeep-tds ,

Yes, the tutorial has been updated with Sub-step nos. and I can also see the tutorial also looks updated.
So, the issue has been resolved.
Thanks for the fix.

You may close the ticket now.


Regards,
Shubham
