### ISSUE TITLE
Template name not available - name changed - SAP Mobile Cards

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6150]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-mobile-cards-welcome.html

10. Step   2: In the Select Cards tab of the wizard, select the Sample Template Welcome   Card and click Next. --- Template with given name not available -- all template names are changed in the Mobile Services Portal -- template needs to be selected is "Welcome Card template Single Instance-- Version 2.0.
Please refer to the screenshot:
![image](https://user-images.githubusercontent.com/66831161/98902892-8bb17500-24dc-11eb-8634-5165954de4e7.png)

2). In   the Review tab of   the wizard, review the details you’ve entered and click Finish. -> Screenshot also needs   to be changed here because of different template name now.

3). Step 3:   In the SAP Cloud Platform Mobile Services Cockpit, you will now see the   Booster Welcome Card we have created. -> Screenshot update -> 
OLD Image: 
![image](https://user-images.githubusercontent.com/66831161/98903302-55282a00-24dd-11eb-8dec-5cc4cc6dfe01.png)

New Image:
![image](https://user-images.githubusercontent.com/66831161/98903305-578a8400-24dd-11eb-9552-bc93f47c70b9.png)

Thanks,
Shubham

Labels to be added:
Sprint Label: SCPTest-2010A

Scenario Label:SCPTest-mcard 
Landscape Labels: trial1,trial2,trial3
prio: high-prio

**Comment by sandeep-tds** [comment]
Hi @i353590

We recently updated the tutorials. These issues have been addressed in the previous release.
Can you please confirm if the issues raised have been resolved? 

Warm Regards
Sandeep T D S

**Comment by thecodester** [comment]
Closing the issue since it seems resolved.
