### ISSUE TITLE
Screenshot: Card template: SAP Mobile cards

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6151]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-mobile-cards-automatic-instance-generation.html

Here in the screenshot, instead of card templates, it should be card types.
Step   2: Click the Create Card Template icon. SCREENSHOT Update required.
Old Screenshot:
![image](https://user-images.githubusercontent.com/66831161/98904306-5bb7a100-24df-11eb-9361-98efd28a281e.png)

New Screenshot:
![image](https://user-images.githubusercontent.com/66831161/98903525-cc5dbe00-24dd-11eb-8fac-6e4e08de6bc6.png)

Thanks,
Shubham

Labels to be added:
Sprint Label: SCPTest-2010A

Scenario Label:SCPTest-mcard 
Landscape Labels: trial1, trial2, trial3
prio: low-prio

**Comment by sandeep-tds** [comment]
Hi @i353590 

Thank you for raising the issue.

@shahchetali can you please look into the issue?

**Comment by shahchetali** [comment]
Hi @i353590 ,

I will update the screenshot.

Thanks,
Chetali Shah

**Comment by thecodester** [comment]
@shahchetali Any update?

**Comment by shahchetali** [comment]
Hi @thecodester , @i353590  ,

We will be deleting this tutorial soon.

Thanks & Regards,
Chetali

**Comment by shahchetali** [comment]
Hi @thecodester , @i353590  ,

We will be deleting this tutorial soon.

Thanks & Regards,
Chetali

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
