### ISSUE TITLE
Warning pop up on selecting template - SAP Mobile Cards

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6153]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-mobile-cards-automatic-instance-generation.html

Similar issue: 
https://github.com/SAPDocuments/Tutorials/issues/5964

Step 2:Provide the required information:
 HTML template -> Gives warning message when selecting template

Warning   pop up comes, need to say OK to continue, then it gets selected.

Thanks,
Shubham

Labels to be added:
Sprint Label: SCPTest-2010A

Scenario Label:SCPTest-mcard 
Landscape Labels: trial1, trial2, trial3
prio: high-prio

**Comment by sandeep-tds** [comment]
Hi @i353590 

Thank you for raising the issue.

@shahchetali can you please look into the issue?

**Comment by shahchetali** [comment]
Hi @i353590 ,

Can you please attach a screenshot for the warning? We cannot see any warning, however, a confirmation box do appear.

Thanks,
Chetali Shah

**Comment by i353590** [comment]
Hi Chetali,

i meant that confirmation box only which comes after we select HTML template, which is not mentioned as part of tutorial.
I think it would be better to have it.

Thanks,
Shubham

**Comment by thecodester** [comment]
I am closing this issue because it relates to the functionality of the product and not the tutorial.

@shahchetali Please consider sending this feedback to development, and consider any note that would help the user with this functionality.

**Comment by shahchetali** [comment]
Hi @thecodester , @i353590  ,

We will be deleting this tutorial soon as the Automatic Instance generation template no longer exist. Also, we will be removing the feature to create mobile cards from the cockpit in future, so this issue will be no longer relevant then.

Thanks & Regards,
Chetali
