### ISSUE TITLE
Tap "Back" 2 times - SAP Mobile Cards

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6155]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-mobile-cards-automatic-instance-generation.html

Step 4:   Tap MobileCardsIcon ‘Back’ to to see latest cards downloaded on the device.
Since we are on subscribe page, we need to go back 2 times!
So, Please add a step saying click back 2 times to go to homepage of the app, OR simply say navigate back to the homepage of app to be able to see new cards.
Note: The issue is relevant for entire tutorial whenever we subscribe any cards.

Thanks,
Shubham

Labels to be added:
Sprint Label: SCPTest-2010A

Scenario Label:SCPTest-mcard 
Landscape Labels: trial1, trial2, trial3
prio: low-prio

**Comment by sandeep-tds** [comment]
Hi @i353590 

Thank you for raising the issue.

@shahchetali can you please look into the issue?

**Comment by shahchetali** [comment]
Hi @i353590 ,

I will update the tutorial and rectify this issue.

Thanks,
Chetali

**Comment by thecodester** [comment]
@shahchetali Any update?

**Comment by shahchetali** [comment]
Hi @thecodester , @i353590 ,

We will be deleting this tutorial soon.

Thanks & Regards,
Chetali

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
