### ISSUE TITLE
Step missing: Navigate to URLs tab: SAP Mobile Cards

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6156]
Hello,

Scenario URL: https://developers.sap.com/tutorials/cp-mobile-cards-action.html

Step 4:   Here URL will call the current SalesOrder which the card represents -> 
Here, For this step, need to navigate to URLs tab, not mentioned in the tutorial.
the screenshot in the tutorial is of URLs tab, so need to navigate to the URLs tab for that.

And then, 

Step 5:   Add Reject Action -> If we   navigate to URLs tab, then we need to navigate back to Actions tab to  continue.

Thanks,
Shubham

Labels to be added:
Sprint Label: SCPTest-2010A

Scenario Label:SCPTest-mcard 
Landscape Labels: trial1, trial2, trial3
prio: low-prio

**Comment by sandeep-tds** [comment]
@shahchetali Can you please take a look at this issue?

**Comment by shahchetali** [comment]
Hi @i353590 ,

Thank you for raising the issue.

The details you've mentioned point to a note. It is meant to explain the concept to the student. We do not intend the user to actually follow those steps.
How do you recommend we highlight the same?

Warm Regards,
Chetali

**Comment by i353590** [comment]
Hello Chetali,

Thanks for the update.

In this case, can  we add this as a note saying "Navigate to URL tab to see the parameter values" as user might get confused here and keep looking at the details shown in the  tutorial ?

Thanks,
Shubham

**Comment by thecodester** [comment]
@shahchetali Can you respond to the feedback in this issue (Shubham's last comment)?

**Comment by shahchetali** [comment]
Hi @i353590

The updated tutorial has been released, can you please verify the changes and update the ticket?
Thank you so much for your support.

PS: The step in question may have been deleted due to the update.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
