### ISSUE TITLE
Set Up Account for Document Information Extraction

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#6158]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dox-service-instance-booster.html

Please specify the step you are referring to : Step 2: Get service key

As per given note,the Booster will choose subaccount if we have more than two subaccounts. But it is observed that it selects if only one subaccount exists. The given note can be modified accordingly.
Expected result:
![image](https://user-images.githubusercontent.com/50734023/98914313-86f5bc80-24ee-11eb-8577-166f29cac09d.png)

Actual result : 
![image](https://user-images.githubusercontent.com/50734023/98914445-af7db680-24ee-11eb-9b19-7454042f80f0.png)

Labels to be added:
Landscape label: trail1, trial2
Scenario label: SCPTest-docinfo

**Comment by tobias61** [comment]
This is resolved. @MichaelCzcz please close
