### ISSUE TITLE
Set Up Account for Document Information Extraction

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#6159]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dox-service-instance-booster.html

Please specify the step you are referring to : Step 2: Get service key

Step 4: Screenshot  should be updated for service key info with new UI. Also step can be added to view the service key in SAP CP although we are downloading the service key after Booster creation.
This screenshot need to update in Tutorial 2(Step1) and Tutorial 3(Step1) as well.

Expected result:
![image](https://user-images.githubusercontent.com/50734023/98915604-20719e00-24f0-11eb-807d-7cadc28c0a4a.png)

Actual result:
![image](https://user-images.githubusercontent.com/50734023/98915697-3f703000-24f0-11eb-8690-08fca879fa7a.png)

Labels to be added:
Landscape label: trail1, trial2
Scenario label: SCPTest-docinfo

**Comment by tobias61** [comment]
This is resolved. @MichaelCzcz please close
