### ISSUE TITLE
Use Machine Learning to Extract Information from Documents with Swagger UI

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#6160]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dox-swagger-ui.html

Please specify the step you are referring to: Step 6: See extracted fields
Screenshot   should be updated for parameter values.Since in actual execution got 3 parameter values.

Expected Result:
![image](https://user-images.githubusercontent.com/50734023/98916176-d806b000-24f0-11eb-8b44-c48d27ed4455.png)

Actual Result:
![image](https://user-images.githubusercontent.com/50734023/98916221-e5239f00-24f0-11eb-9bc5-d90c6db29b4d.png)

Labels to be added:
Landscape label: trail1, trial2
Scenario label: SCPTest-docinfo

**Comment by tobias61** [comment]
This is resolved. @MichaelCzcz please close
