### ISSUE TITLE
Set Up Integration Suite Trial Feedback

### ISSUE THREAD

**Issue by IObert** [SAPDocuments/Tutorials#6162]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

Please specify the step you are referring to:

- All: I noticed that the screenshot resolution is too high (I know this sounds weird at first). But the tutorial looks really strange when you look at it on a large screen. I'd would be great if you could make then smaller.

- 4.3 According to the screenshot, the user should only select "Design, Develop, and Operate..." but later we see API Management has been selected. Which is it now?

Thanks

**Comment by Vikramkulkarni01** [comment]
Hi @IObert, 

I tried reducing the resolution of screenshot and you will see the changes shortly. on or after 3rd Dec. 

Regards, 
Vikram

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
