### ISSUE TITLE
Create an API Provider System Feedback

### ISSUE THREAD

**Issue by IObert** [SAPDocuments/Tutorials#6164]
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-create-provider.html

Please specify the step you are referring to

- 2 : The step doesn't cover how to open the API Management from the trial account
- All: Almost all screenshots are outdated and partially also too big

**Comment by IObert** [comment]
FYI I also just created #6162 but when I have a look at the entire tutorial group. I think we need a larger rework. I do realize that this requires some time. Maybe we should sit together internally first. 
@thecodester Looping you in as well. WDYT?

**Comment by shilpavij** [comment]
Dear Michael,

I have not written these tutorials and it was done by Hassett, Meredith <meredith.hassett@sap.com>(but now I think she is not with SAP).
I corrected her set once but I do not own it. Unfortunately, all the requests from then are coming to me. If we do not have any owner for these tutorials kindly decommissioned them.

Regards
Shilpa

**Comment by IObert** [comment]
@Vikramkulkarni01  
Are you also in charge of this issue? I'm wondering because you responded to #6162 as well.

**Comment by Vikramkulkarni01** [comment]
Hi Obert,

No, I am not responsible for the issue reported in #6164.

Regards,
Vikram Kulkarni,

**Comment by Vikramkulkarni01** [comment]
Since there is no action required from me on this, we are closing this issue.
