### ISSUE TITLE
Specify clearly which all capabilities need to be selected

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6165]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

Please specify the step you are referring to : **Step 4: Provision the capabilities**

Please specify clearly which all capabilities need to be selected. Or else ask to select all of them. In further steps, i.e. activating capabilities, assigning roles, and verifying the URLs; these steps are based on the above selections. There is a lot of confusion from an end-user perspective regarding the selection of capabilities as well as all the screenshots provided. So it's better to clarify the statements as well as add screenshots accordingly.

Here If we are to select only one capability, few of the roles that we have to add in the next step will not be available and some of the screenshots should also be changed here.

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2010A
Scenario Label: SCPTest-cloudin
Priority: High

Best Regards,
Priyanka

**Comment by Vikramkulkarni01** [comment]
Hi Priyanka, 

We added the line to select the capability.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
