### ISSUE TITLE
change the screenshot

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6166]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

Step 4: Provision the capabilities

Here in the final screenshot after provisioning the capabilities, the message queue is selected in the screenshot which is not mentioned as a part of the scenario.
Actual:
![image](https://user-images.githubusercontent.com/65999547/98924458-db069e00-24fa-11eb-9392-181112debc30.png)

Expected:
![image](https://user-images.githubusercontent.com/65999547/98924671-1bfeb280-24fb-11eb-8a46-c9725e8d50cb.png)

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2010A
Scenario Label: SCPTest-cloudin
Priority: Low

Best Regards,
Priyanka

**Comment by Vikramkulkarni01** [comment]
Hi Priyanka. 

We changed the screenshot and it will be available in the prod shortly. ( after Dec 3rd)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
