### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6167]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

**Step 5: Assign roles for the capabilities**

The below roles are not available if only the Design, Develop and operate integration Scenarios  capability is selected.
![image](https://user-images.githubusercontent.com/65999547/98925125-a3e4bc80-24fb-11eb-9f1c-0275a0a6e3fa.png)

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2010A
Scenario Label: SCPTest-cloudin
Priority: Low

Best Regards,
Priyanka

**Comment by Vikramkulkarni01** [comment]
Hi Priyanka, 

You are right, this tutorial has been created to showcase only the Integration Suite Scenarion. 

It's ab expected behavior. 

Regards, 
Vikram Kulkarni

**Comment by PriyankaShivakumar** [comment]
Hi Vikram,

If this tutorial has been created to showcase only the Integration Suite Scenario, Please remove these roles as it may cause confusion for the customer.

Best Regards,
Priyanka

**Comment by Vikramkulkarni01** [comment]
Hi Priyanka, 

Our Idea is to inform the availability of all roles. However, I added the screenshot with the role to be selected. 

Hence we are closing this issue.
