### ISSUE TITLE
Set Up Business Rules for Determining Equipment

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#6168]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-businessrules.html

Please specify the step you are referring to-
 
In step- 3.1 the text should be **Import Project from API Business Hub** and not Import Project from API Business API Hub.
Please update the text.

Labels:
Landscape Labels: trail1, trail2,trail3
Sprint Label: SCPTest-2010A 
Scenario Label: SCPTest-eboard
Priority Label: Low

**Comment by ArchanaShukla** [comment]
Updated the tutorial.

@MichaelCzcz - please close the ticket
