### ISSUE TITLE
No steps Specified to access workspace

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6169]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Step 2: Access your workspace

Here please add the steps to access workspace like click on manage capability and then launch the url.
From a customers perspective, without these steps it is difficult to proceed to the next steps.

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2010A
Scenario Label: SCPTest-cloudin
Priority: High

Best Regards,
Priyanka

**Comment by Vikramkulkarni01** [comment]
Hi Priyanka, 

This has been already specified as a part of the pre-requisite. Mentioning again will be redundant. 

Regards, 
Vikram Kulkarni

**Comment by PriyankaShivakumar** [comment]
Hi Vikram,

I agree that its mentioned in the pre-requisite on how to set up the Integration suite.
But here a line can be added like "Click on the URL in the capability to access the workspace"

Best Regards,
Priyanka

**Comment by Vikramkulkarni01** [comment]
Hi Priyanka, 

Thanks fort the update and we will add that line

**Comment by Vikramkulkarni01** [comment]
Hi, 

We added the line and the tutorial has been updated. 

Hence we are closing this issue.
