### ISSUE TITLE
Steps are repeated

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6170]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Step 4: Edit the integration flow

Access your integration package by choosing Design > (Integration package name).
Access your integration flow by choosing Artifacts > (Integration flow name).

These steps were already executed in the previous part.

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2010A
Scenario Label: SCPTest-cloudin
Priority: Low

Best Regards,
Priyanka

**Comment by Vikramkulkarni01** [comment]
Hi Priyanka, 

These are valid steps. The previous step is just to create an integration package and an integration flow. 

I don't see this as the repetition of the previous step. The flow is correct. 

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
