### ISSUE TITLE
Monitor Tab is called Operations View

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6171]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Step 10: Deploy the integration flow

From an end user's perspective please change the Monitor tab to operations view in order to avoid confusion.

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2010A
Scenario Label: SCPTest-cloudin
Priority: Low

Best Regards,
Priyanka

**Comment by Vikramkulkarni01** [comment]
Hi Priyanka, 

Thanks for the feedback. 

The changes have been incorporated and it will be available in production next week along with other changes. 

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
