### ISSUE TITLE
service instance is not created so client id and secret is unavailable

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6172]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Step 11: Test integration flow using Postman

No idea as from where we have to copy the Client ID and Client Secret as we are not creating any service instances.(worked with trial user name and password)

Please include a step to create a service instance.

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2010A
Scenario Label: SCPTest-cloudin
Priority: High

Best Regards,
Priyanka

**Comment by Vikramkulkarni01** [comment]
Hi Priyanka, 

Thanks for the feedback. 

The concern has been fixed from our end and the tutorial has been updated in the production. 

Could you please close this issue from your end?

Regards, 
Vikram Kulkarni
