### ISSUE TITLE
Total time for the Mission should be 1 hour 15 mins

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6173]
Mission URL: https://developers.sap.com/mission.cp-starter-integration-cpi.html

Here the total time for the Mission should be 1 hour 15 mins

Set Up Integration Suite Trial - 30 mins
Design and Test Your First Integration Flow - 45 mins

Total- 1 hr 15 mins

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2010A
Scenario Label: SCPTest-cloudin
Priority: Low

Best Regards,
Priyanka

**Comment by Vikramkulkarni01** [comment]
Hi @PriyankaShivakumar, 

Thanks for the feedback. 

Hi @thecodester and  @MichaelCzcz , 

Could you please update the mission time to 1 hr 15 mins? 

![image](https://user-images.githubusercontent.com/59861880/98929642-7569e000-2501-11eb-8b30-02c8d0085878.png)

Appreciate your help.

**Comment by Vikramkulkarni01** [comment]
Hi @PriyankaShivakumar , 

The concern has been addressed and updated in the system. 

The issue can be closed now.
