### ISSUE TITLE
Set Up a Workflow With Extended Employee Onboarding

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#6174]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html

Please specify the step you are referring to

In step 2.3 The screenshot needs to be updated. The file WorkflowManagementFLP.tar should not be there.

Expected:
1st screnshot
<img width="1104" alt="1" src="https://user-images.githubusercontent.com/69286515/98926951-f3c48300-24fd-11eb-80e0-7c548b96a418.png">

2nd screenshot
<img width="1389" alt="2" src="https://user-images.githubusercontent.com/69286515/98926976-f9ba6400-24fd-11eb-9c48-9fc412e6fcd2.png">

Actual:
1st screenshot
<img width="696" alt="1_2" src="https://user-images.githubusercontent.com/69286515/98927415-8402c800-24fe-11eb-875e-4836ef28dd39.png">

2nd screenhot
<img width="398" alt="2_2" src="https://user-images.githubusercontent.com/69286515/98927037-0b037080-24fe-11eb-8368-a6f154e2be20.png">

Labels:
Landscape Labels: trail1, trail2,trail3
Sprint Label: SCPTest-2010A
Scenario Label: SCPTest-eboard
Priority Label: Low

**Comment by ArchanaShukla** [comment]
Hello Akansha,
There could be different view of the Business Application workspace for different users. They may or may not have projects in their workspace and so the screenshot will be different. All that matters is they have to drag and drop the unzipped project under "project" node in the pop-up. So,  both the screen shots are correct. No change is needed. 

@MichaelCzcz - please close the ticket.

**Comment by AkankshaKullu** [comment]
Hello @ArchanaShukla,
Noted.
