### ISSUE TITLE
Set Up a Workflow With Extended Employee Onboarding

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#6175]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-3-workflow.html

Please specify the step you are referring to

In step-2.4 The screenshot needs to be updated, change in the project structure.

Expected:
<img width="1395" alt="3" src="https://user-images.githubusercontent.com/69286515/98932767-c7146980-2505-11eb-8bc7-2ebf49af2f6b.png">

Actual:
<img width="960" alt="3_1" src="https://user-images.githubusercontent.com/69286515/98932785-ced40e00-2505-11eb-8e11-b43d605d4662.png">

Suggestion: When the project opens the user won't be able to directly get workflow displayed so we can guide the user to how to open the workflow.
Click on onboarding folder-->Click on workflows folder-->Click on onboard.workflow file

Labels:
Landscape Labels: trail1, trail2,trail3
Sprint Label: SCPTest-2010A
Scenario Label: SCPTest-eboard
Priority Label: Low

**Comment by ArchanaShukla** [comment]
Hello Akansha, 
This is because you would have explicitly selected the package after dragging and dropping the unzipped content into the workspace which is not mentioned as the steps. Please check again and reopen if needed.

@MichaelCzcz - please close the ticket.
