### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#6176]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html

Please specify the step you are referring to

In step 7.1: the tile name is Monitor Visibility Scenario. So the statement should be "In the Workflow Management Fiori launchpad, choose Monitor Visibility Scenario to process the new set of events." and update the screenshot.

Expected:
image

<img width="553" alt="7_2" src="https://user-images.githubusercontent.com/69286515/98938417-dac3ce00-250d-11eb-83e5-67d7466775c8.png">

Actual:
image
<img width="960" alt="7" src="https://user-images.githubusercontent.com/69286515/98938426-deefeb80-250d-11eb-9dbc-9f00ecc4fb20.png">

Labels:
Landscape Labels: trail1, trail2,trail3
Sprint Label: SCPTest-2010A
Scenario Label: SCPTest-eboard
Priority Label: Low

**Comment by ArchanaShukla** [comment]
yeah this was a new change in the UI, will update the tutorial by Jan-end 2021.

**Comment by MichaelCzcz** [comment]
@ArchanaShukla Has the tutorial been updated?

**Comment by ArchanaShukla** [comment]
Tutorial have been updated with new screenshot. 
@MichaelCzcz - please close this ticket
