### ISSUE TITLE
Start Developing ABAP Repository Objects

### ISSUE THREAD

**Issue by xtbirihan** [SAPDocuments/Tutorials#6178]
Group URL: https://developers.sap.com/group.abap-dev-repository-objects.html

Create an Abap Package has not been completed, it stopped as 75% and because of this, i can't complete group and mission. 

Best Regards.

**Comment by julieplummer20** [comment]
Hi,
This sounds like a general problem with your system, not specific to the tutorial.
I may not be able to help, but try:
1. Update ADT to latest version.
2. Are you a customer, partner, or SAP internal?
3. If not, where did you get the system, e.g. download?
4. What release is it?
5. Does the system just hang after 75% or do you get an error message?
6. What step in the wizard are you on when it hangs?
7. Can you create any other type of object in $TMP - e.g. ABAP Class?

BR Julie.

**Comment by xtbirihan** [comment]
Hi, 

I think there is misunderstanding, i was talking about check sign in tutorial web page to get badge ( : to receive "mission completed" checkbox sign , i have to complete all tutorials. It is not big problem maybe it was related cookies.  After few days i revisited web site and completed tutorial from scratch, i gained badge. I don't have any problem in the system (: Thanks for you reply and time.

Best Regards.

**Comment by xtbirihan** [comment]
> Hi,
> This sounds like a general problem with your system, not specific to the tutorial.
> I may not be able to help, but try:
> 
> 1. Update ADT to latest version.
> 2. Are you a customer, partner, or SAP internal?
> 3. If not, where did you get the system, e.g. download?
> 4. What release is it?
> 5. Does the system just hang after 75% or do you get an error message?
> 6. What step in the wizard are you on when it hangs?
> 7. Can you create any other type of object in $TMP - e.g. ABAP Class?
> 
> BR Julie.

Hi,

I think there is misunderstanding, i was talking about check sign in tutorial web page to get badge ( : to receive "mission completed" checkbox sign , i have to complete all tutorials. It is not big problem maybe it was related cookies. After few days i revisited web site and completed tutorial from scratch, i gained badge. I don't have any problem in the system (: Thanks for you reply and time.

Best Regards

**Comment by julieplummer20** [comment]
Good to hear! 
Thanks for letting us know. I will now ask to have this closed. Please feel free to get in touch if there are any other tutorial issues.
Best wishes,
Julie.
