### ISSUE TITLE
Set Up the Manage Rule Projects Application

### ISSUE THREAD

**Issue by kbprasad79** [SAPDocuments/Tutorials#6179]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules03-setup-mrp.html

Please specify the step you are referring to

Can you please provide steps for Business Application Studio?

Thanks

**Comment by ArchanaShukla** [comment]
You do not need Business Application studio for modelling business rules. Business rules have a standalone application called "Manage Rules Application" which is used to model, manage and deploy rules.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
