### ISSUE TITLE
Define a Simple Data Model and OData Service with CDS

### ISSUE THREAD

**Issue by AlexandreO33** [SAPDocuments/Tutorials#6183]
Tutorial URL: https://developers.sap.com/tutorials/odata-05-data-model-service.html

**Step 11 : Create the database**

Hello,

Error messages displayed by the console when trying to "Build" the service.
Here is a screenshot of the console : 
![Console errors](https://user-images.githubusercontent.com/73787725/99078657-0b177500-25bf-11eb-80da-741c00420ef9.png)

What can i do please?

Regards

**Comment by thecodester** [comment]
@AlexandreO33 These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:

https://answers.sap.com/index.html
