### ISSUE TITLE
Set Up SAP Mobile Cards

### ISSUE THREAD

**Issue by AHADI2** [SAPDocuments/Tutorials#6185]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-setup.html

Please specify the step you are referring to
Step 4 
Iam unable to launch the API it is giving the following error message.
"This site can’t be reachedmobilecards’s server IP address could not be found."

**Comment by sandeep-tds** [comment]
Hi @AHADI2, 

Thank you for raising the issue. 

Can you please provide a response to the following questions:

1. Which OS flavour are you running the mobile cards client on? (iOS | Android)
2. Is your mobile device connected to your laptop when doing the demo?
3. Have you tried to uninstall and re-install the app on your device? 

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
