### ISSUE TITLE
Set up Secure Tunnel between ABAP System and SAP Cloud Platform (CF)

### ISSUE THREAD

**Issue by hitesh-parmar** [SAPDocuments/Tutorials#6188]
Tutorial URL: https://developers.sap.com/tutorials/cp-connectivity-create-secure-tunnel.html

Please specify the step you are referring to:

Screenshots on Step 1 are updated.
We known have an information icon to view the details instead of a flip icon.

**Comment by JensHaley** [comment]
Thanks for the feedback - I'll update it and give an update here when I'm done

**Comment by JensHaley** [comment]
[PR 6253](https://github.com/SAPDocuments/Tutorials/pull/6253)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
