### ISSUE TITLE
@sap/cloud-sdk-core move to @sap-cloud-sdk/core?

### ISSUE THREAD

**Issue by KatsuoAshimine** [SAPDocuments/Tutorials#6196]
Tutorial URL: https://developers.sap.com/tutorials/cap-cloudsdk-5-srv-logic.html

I hope this is up to info.
[const { FilterList } = require('@sap/cloud-sdk-core');]  is maybe not exist.

maybe move to 
[const { FilterList } = require('@sap-cloud-sdk/core');].

Please specify the step you are referring to

**Comment by qmacro** [comment]
Thanks for this report, @KatsuoAshimine. The tutorials in this mission are undergoing a rewrite to ensure they reflect the latest changes and additions in this area (CAP, Cloud SDK, service consumption), and as such, we should now start to treat these existing versions as deprecated. Please watch this space for the appearance of new versions in the next month or so. If that's OK with you, I'll close this for now. Thanks.
