### ISSUE TITLE
Add Service Logic to Consume Remote Address Data

### ISSUE THREAD

**Issue by KatsuoAshimine** [SAPDocuments/Tutorials#6197]
Tutorial URL: https://developers.sap.com/tutorials/cap-cloudsdk-5-srv-logic.html

now
 [.flatten()] is OData Services might not support the flattened filter expression.

>return new FilterList(undefined, andFilters).flatten();

**Comment by qmacro** [comment]
Thanks for this report, @KatsuoAshimine. The tutorials in this mission are undergoing a rewrite to ensure they reflect the latest changes and additions in this area (CAP, Cloud SDK, service consumption), and as such, we should now start to treat these existing versions as deprecated. Please watch this space for the appearance of new versions in the next month or so. If that's OK with you, I'll close this for now. Thanks.
