### ISSUE TITLE
Get a Free Trial Account on SAP Cloud Platform

### ISSUE THREAD

**Issue by cemaybe** [SAPDocuments/Tutorials#6198]
Tutorial URL: https://developers.sap.com/tutorials/hcp-create-trial-account.html

Step 8 should probably start with "The service marketplace is where you can **find** all services that **are** available on any of the environments.". Or maybe even better: In the service marketplace you can find all services that are available on any of the environments.

**Comment by IObert** [comment]
Good feedback, thanks! I updated the sentence according to your suggestion - it should be live soon.
