### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by codebude** [SAPDocuments/Tutorials#6204]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

It seems there's a "bug" in this tutorial in some use cases. The tutorial is part of the API management series (https://developers.sap.com/group.cp-apim-code-1.html). When coming from this series, a user wants to setup SAP API management. But in step "Step 4" the tutorial wants the user to activate/provision only the SAP CPI service. The tutorial reads out as folows:

> Let’s assume you have made your selection, you can select any of the capabilities. For this tutorial, select Design, Develop and operate integration Scenarios and click Next.

In addition the screenshot also shows that only the CPI shall be activated. I know that the "Set Up Integration Suite Trial" is a generic tutorial, but in the context of the API management series (https://developers.sap.com/group.cp-apim-code-1.html) it is misleading. So maybe it would be a good idea to specify in step 4 which services to activate/provision in which context.

E.g. "If you come from the API-M series, please activate XYZ. If you come from the CPI series, please activate XYZ..."

**Comment by Vikramkulkarni01** [comment]
Hi @codebude , 

Thanks for your feedback. 

We have revamped the tutorial and one of our updates includes your feedback as well. 

You will see the changes in the production after 3rd Dec. 

We truly appreciate your support and understanding. 

Regards, 
Vikram Kuklarni

**Comment by codebude** [comment]
Hi @Vikramkulkarni01 ,

thanks for reacting that fast. :-) Looking forward to the updated documentation.
