### ISSUE TITLE
Set Up the Manage Rule Projects Application

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Tutorials#6206]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules03-setup-mrp.html

Please specify the step you are referring to - Step 2. 
Maybe I did miss something, but i can't access WEBIDE anymore.
Could it be an idea to change to the procedure for "upload" to BAS?
See attached.
Best, 
Michael
![drag_n_drop](https://user-images.githubusercontent.com/43760831/99544348-7c3a9c00-29b4-11eb-8f0b-6faa419613cd.png)

**Comment by thecodester** [comment]
@mts2605  I believe this tutorial was out of date and we have removed it.

@VandanaVasudevan Can you help where @mts2605 can get the information he needs?

**Comment by VandanaVasudevan** [comment]
Hi,

We are currently working on updating the documents. This tutorial is out of date. 
MRP application is a part of Workflow Management service too. For now, you can run the WM booster to access the application. You can see the following tutorial for the setup:
https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html

Thanks & Regards,
Vandana

**Comment by mts2605** [comment]
Hi,

Thanks for inputs. My comment was just a suggestion. I did get it to work through BAS.
Closed.
BR Michael
