### ISSUE TITLE
Set Up SAP Business Application Studio for Development

### ISSUE THREAD

**Issue by OlgaWerner** [SAPDocuments/Tutorials#6211]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-onboarding.html

Hi,

I'm a UX designer for SCP Cockpit and currently testing various tutorials.
The tutorial **Set Up SAP Business Application Studio for Development** includes sections were the user has to work in the subscriptions page.  
Soon the marketplace will change and services and subscriptions will be moved to one page. You can read more about this topic here: https://jtrack.wdf.sap.corp/browse/SAPCPCFS-18270?src=confmacro

I just wanted to inform you as a heads up, in case you were not aware of this upcoming change :)

Thanks and best regards,
Olga

**Comment by thecodester** [comment]
@raz-korn Please note the changes from @OlgaWerner . I will close the issue -- if you need it open, let me know.

@OlgaWerner  Please note this is a public forum, in case it was not clear.
