### ISSUE TITLE
The list shows 'Drop list items here'

### ISSUE THREAD

**Issue by Auggie9010** [SAPDocuments/Tutorials#6216]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to 
Step4 - 9:Wait for the A service is listening to port 6004 notification and then click the button to open the app.

The article says 'The app is opened in a new tab and a list of suppliers is displayed.'
I created Fiori App as instructed. 
However the application shows 'Drop list items here' and no data is found.

![image](https://user-images.githubusercontent.com/57590680/99764113-b3898400-2b3f-11eb-8ab3-9275aec37dc2.png)

I confirmed that the Gateway Demo System(ES5) properly works and the setting of destination is not wrong.

![image](https://user-images.githubusercontent.com/57590680/99764622-cc466980-2b40-11eb-8a68-f2099a428dfb.png)

![image](https://user-images.githubusercontent.com/57590680/99764306-1da22900-2b40-11eb-8955-c6235831a599.png)

Console of Chrome outputs the following errors

Failed to load resource: the server responded with a status of 431 ()
Failed to load resource: the server responded with a status of 404 ()

![image](https://user-images.githubusercontent.com/57590680/99764377-462a2300-2b40-11eb-8912-fb0b0ecdd7c1.png)

How can I solve this problem?

**Comment by raz-korn** [comment]
Hi @Auggie9010 ,

Please refer to the following [blog](https://blogs.sap.com/2020/10/13/how-to-check-the-connectivity-to-your-backend-system-in-business-application-studio/).
Use the following: curl -v -i "ES5.dest/sap/opu/odata/iwbep/GWSAMPLE_BASIC/BusinessPartnerSet?%24top=1"

Regards - Raz

**Comment by Auggie9010** [comment]
Hi @raz-korn 

Thank you for your reply.

The result follows.

```
user: FioriDemo $ curl -v -i "ES5.dest/sap/opu/odata/iwbep/GWSAMPLE_BASIC/BusinessPartnerSet?%24top=1"
* Expire in 0 ms for 6 (transfer 0x558c66349f50)
* Uses proxy env variable no_proxy == 'localhost,127.0.0.1,github.com,.github.com,.npmjs.org,.yarnpkg.com,npm.sap.com,.maven.apache.org'
* Uses proxy env variable http_proxy == 'http://127.0.0.1:8887'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x558c66349f50)
* Connected to 127.0.0.1 (127.0.0.1) port 8887 (#0)
> GET http://ES5.dest/sap/opu/odata/iwbep/GWSAMPLE_BASIC/BusinessPartnerSet?%24top=1 HTTP/1.1
> Host: ES5.dest
> User-Agent: curl/7.64.0
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Cache-Control: no-store, no-cache
Cache-Control: no-store, no-cache
< Content-Type: application/atom+xml;type=feed; charset=utf-8
Content-Type: application/atom+xml;type=feed; charset=utf-8
< Dataserviceversion: 2.0
Dataserviceversion: 2.0
< Date: Sun, 22 Nov 2020 12:38:30 GMT
Date: Sun, 22 Nov 2020 12:38:30 GMT
< Sap-Metadata-Last-Modified: Sat, 02 Mar 2019 03:01:29 GMT
Sap-Metadata-Last-Modified: Sat, 02 Mar 2019 03:01:29 GMT
< Sap-Processing-Info: ODataBEP=,crp=,st=,MedCacheHub=Table,MedCacheBEP=SHM,codeployed=X,softstate=
Sap-Processing-Info: ODataBEP=,crp=,st=,MedCacheHub=Table,MedCacheBEP=SHM,codeployed=X,softstate=
< Set-Cookie: 

(Omission)

< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload;
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload;
< Vary: Accept-Encoding
Vary: Accept-Encoding
< X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
< X-Request-Id: 1bd54f39-2edf-46d2-522e-2051569546b0
X-Request-Id: 1bd54f39-2edf-46d2-522e-2051569546b0
< X-Vcap-Request-Id: 1bd54f39-2edf-46d2-522e-2051569546b0
X-Vcap-Request-Id: 1bd54f39-2edf-46d2-522e-2051569546b0
< Transfer-Encoding: chunked
Transfer-Encoding: chunked

< 
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xml:base="https://sapes5.sapdevcenter.com/sap/opu/odata/iwbep/GWSAMPLE_BASIC/"><id>https://sapes5.sapdevcenter.com/sap/opu/odata/iwbep/GWSAMPLE_BASIC/BusinessPartnerSet</id><title type="text">BusinessPartnerSet</title><updated>2020-11-22T12:38:30Z</updated><author><name/></author><link href="BusinessPartnerSet" rel="self" title="BusinessPartnerSet"/><entry m:etag="W/&quot;datetime'2020-11-22T03%3A01%3A17.0000000'&quot;"><id>https://sapes5.sapdevcenter.com/sap/opu/odata/iwbep/GWSAMPLE_BASIC/BusinessPartnerSet('0100000000')</id><title type="text">BusinessPartnerSet('0100000000')</title><updated>2020-11-22T12:38:30Z</updated><category term="GWSAMPLE_BASIC.BusinessPartner" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"/><link href="BusinessPartnerSet('0100000000')" rel="edit" title="BusinessPartner"/><link href="BusinessPartnerSet('0100000000')/ToSalesOrders" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/ToSalesOrders" type="application/atom+xml;type=feed" title="ToSalesOrders"/><link href="BusinessPartnerSet('0100000000')/ToContacts" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/ToContacts" type="application/atom+xml;type=feed" title="ToContacts"/><link href="BusinessPartnerSet('0100000000')/ToProducts" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/ToProducts" type="application/atom+xml;type=feed" title="ToProducts"/><content type="application/xml"><m:properties xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices"><d:Address m:type="GWSAMPLE_BASIC.CT_Address"><d:City>Walldorf</d:City><d:PostalCode>69190</d:PostalCode><d:Street>Dietmar-Hopp-Allee</d:Street><d:Building>16</d:Building><d:Country>DE</d:Country><d:AddressType>02</d:AddressType></d:Address><d:BusinessPartnerID>01* Connection #0 to host 127.0.0.1 left intact
00000000</d:BusinessPartnerID><d:CompanyName>SAP</d:CompanyName><d:WebAddress>http://www.sap.com</d:WebAddress><d:EmailAddress>do.not.reply@sap.com</d:EmailAddress><d:PhoneNumber>0622734567</d:PhoneNumber><d:FaxNumber>0622734004</d:FaxNumber><d:LegalForm>SE</d:LegalForm><d:CurrencyCode>EUR</d:CurrencyCode><d:BusinessPartnerRole>01</d:BusinessPartnerRole><d:CreatedAt>2020-11-22T03:01:17.0000000</d:CreatedAt><d:ChangedAt>2020-11-22T03:01:17.0000000</d:ChangedAt></m:properties></content></entry></feed>
```
****

This is same as the result executed in Chrome

![image](https://user-images.githubusercontent.com/57590680/99904277-3ca1e600-2d0d-11eb-9a8a-6f6f3b16f9a1.png)

HTTP is responding "200 OK", which means the destination 'ES5' is available.

Besides I cleared cache with this command.

`curl localhost:8887/reload`

But it didn't help.

Could you give me a help, please?

**Comment by raz-korn** [comment]
Hi @Auggie9010 ,

Can you share a screenshot of how the ES5 destination is configured in the SCP cockcpit?
Can you share the network tab of the browser (you shared the console tab)?

Regards - Raz

**Comment by Auggie9010** [comment]
@raz-korn 

Here it is.
![image](https://user-images.githubusercontent.com/57590680/100349042-2c4e7b80-302b-11eb-8bbe-b7522415a5f6.png)

![image](https://user-images.githubusercontent.com/57590680/100349075-353f4d00-302b-11eb-98c4-2e20bfbb168a.png)

![image](https://user-images.githubusercontent.com/57590680/100349643-19887680-302c-11eb-895a-fe08879e7e0c.png)

**Comment by raz-korn** [comment]
Hi @Auggie9010 ,

First - I'm happy to see that you are able to run the app and proceed with the tutorial.
(I'm also happy to see that nothing is wrong with the tutorial :-))

Second - I searched for this issue, and I believe the [following ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431) provides a hint for the issue: There are probably too many cookies or something related.

Regards - Raz

**Comment by Auggie9010** [comment]
@raz-korn 

As you instructed, after I deleted cookies and cash I confirmed that it works.

![image](https://user-images.githubusercontent.com/57590680/100410987-bc380800-30b3-11eb-862f-00caf2e18652.png)

I deeply appreciate your help!

**Comment by raz-korn** [comment]
Thanks for the update, @Auggie9010 .
Glad that I was able to assist.
