### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by BatoulK** [SAPDocuments/Tutorials#6217]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

Please specify the step you are referring to (Step 3: Configure service for List Report Object Page)

I can't connect to the Odata service, keep becoming "Authentication incorrect!"

![image](https://user-images.githubusercontent.com/74186793/99782092-fe43d580-2b18-11eb-915e-a8a08ac63ecf.png)

**Comment by cjbernal** [comment]
Hi BatoulK,

Sorry to see that you're having an issue. To get started with troubleshooting this, I have one quick question: did you create an account for the gateway demo system, per the prerequisites of the tutorial? If so, the credentials you used to register for access are the ones that you need to use. If you haven't done that, please see the following: https://developers.sap.com/tutorials/gateway-demo-signup.html

If you did request access and you've entered the correct credentials, please let me know and I will try to connect you with someone that can take a look at the issue. 

Thanks and regards,
Conrad (SAP UX Engineering)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
