### ISSUE TITLE
Add a Web Dynpro ABAP App to Your SAP Cloud Platform Launchpad Site

### ISSUE THREAD

**Issue by excepticons** [SAPDocuments/Tutorials#6218]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-webdynpro-app.html

Can't find "Search POs" app in Assingments seach results, on Everyone role:

<img width="1769" alt="capture1" src="https://user-images.githubusercontent.com/15220791/99847213-b8513680-2b45-11eb-9078-254bd4b77cc6.PNG">

**Comment by LindsayBert** [comment]
Hi

Did you click Edit on the screen?  The app won't appear in the results list in view mode.

Thanks
Lindsay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
