### ISSUE TITLE
Create a Simple Database Table for ABAP Environment - Navigations are not working in 'Prev' and 'Next'

### ISSUE THREAD

**Issue by Shanmugapriya916** [SAPDocuments/Tutorials#6220]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-create-table.html

Hello Team, 
Good Day, the navigation of  'Prev' and 'Next' buttons are not working. And also the navigation for the 'Group' and 'Mission' also not working. 
Thankyou.

Best Regards,
Priya.

**Comment by mervey45** [comment]
Hi @Shanmugapriya916 ,

can you try it out again? It is working for me. I can navigate in the mission as well as in both groups.

Thank you.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
