### ISSUE TITLE
Create a Destination within the Cloud Foundry Environment

### ISSUE THREAD

**Issue by VitaliyKim** [SAPDocuments/Tutorials#6221]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-create-destination.html

It says one should log on to answer the questions, but there is no any link to do it:
![image](https://user-images.githubusercontent.com/5039484/99911679-46811480-2d20-11eb-8d38-96bbe8c8631c.png)

On developers.sap.com if Login pressed a message appears saying that the user is authenticated:
![image](https://user-images.githubusercontent.com/5039484/99911801-f5bdeb80-2d20-11eb-8d7b-ea4799071add.png)

but returns to the previous page showing Login button. And I still can't answer the questions.

**Comment by IObert** [comment]
Hi,

thanks for letting us know. You're right, it seems that there's a problem on our side. Please ignore that "login" button stays visible. It is still displayed even though you have been logged in after the first click. Please refresh the tutorial after you clicked the button once.

![2020-11-23_10-35-48](https://user-images.githubusercontent.com/1873245/99947319-1a917d80-2d78-11eb-84c2-2529317af854.gif)

**Comment by VitaliyKim** [comment]
Hello!
Thank you for prompt reply.

When opened for the first time today it showed locked "Done" buttons instead of locked "Answer question". 
But after pressing "Login" on https://developers.sap.com/ and going back to the tutorial and after a couple of refresh, the "Done" buttons became unlocked and I was able to finish the tutorial :)

**Comment by thecodester** [comment]
The issues should be fixed now.
