### ISSUE TITLE
Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by SuuSuu9280** [SAPDocuments/Tutorials#6224]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

STEP9
Run the application, but it shows a blank screen.

**Comment by SuuSuu9280** [comment]
It has been resolved. The Lauchpad Module was not selected when creating the Dev Space.

**Comment by SuuSuu9280** [comment]
I selected the Launchpad module but it didn't show up.

**Comment by mervey45** [comment]
Hi @SuuSuu9280 ,

we have currently an issue with that. The SAP Fiori Launchpad site don't show up right now, but we are working on this issue.
Thank you for your understanding. 

Best regards, 
Merve

**Comment by thecodester** [comment]
@mervey45 I will keep the issue open for now. Do you know when the issue will be resolved, about?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
