### ISSUE TITLE
Add Views and Define Routes to Access Them

### ISSUE THREAD

**Issue by VitaliyKim** [SAPDocuments/Tutorials#6225]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-101-add-routing.html

The "Prev" and "Next" buttons on the screenshot have incorrect links like "https://tutorials/sapui5-101-create-project.html":
![image](https://user-images.githubusercontent.com/5039484/99949329-0f087b80-2da5-11eb-88a2-ce8bf7d58528.png)

**Comment by IObert** [comment]
Thanks for letting us know. @thecodester Are you already aware of this?

**Comment by thecodester** [comment]
Yes, I am painfully aware. We are working to fix ... though in the meantime you can navigate directly to all tutorials from the mission page

**Comment by thecodester** [comment]
I believe everything isa fixed now. If you still have a problem, feel free to reopen the ticket. Sorry for the inconvenience

**Comment by VitaliyKim** [comment]
Yes it's ok now. Thank you! :)
