### ISSUE TITLE
Deploy a Go MSSQL API Endpoint in the Kyma Runtime

### ISSUE THREAD

**Issue by bcschaich** [SAPDocuments/Tutorials#6226]
Tutorial URL: https://developers.sap.com/tutorials/cp-kyma-api-mssql-golang.html

Please specify the step you are referring to

Link to next tutorial at end of page.

This and following in the rest of the tutorial all links miss "developers.sap.com", thus result in an error page.

Regards,
Benny

**Comment by jcawley5** [comment]
@thecodester - Is this something you can resolve?

**Comment by thecodester** [comment]
Yes...we are working on it. Sorry for the bad links.

**Comment by thecodester** [comment]
This has now been resolved. If you still find problems, please reopen the issue. Sorry for the inconvenience.
