### ISSUE TITLE
Tutorial Page cp-ias-azure-ad.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [SAPDocuments/Tutorials#6232]
Tutorial issue found: [https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/cp-ias-azure-ad/cp-ias-azure-ad.md](https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/cp-ias-azure-ad/cp-ias-azure-ad.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- products>sap-cloud-platform-identity-authentication

 Affected server: PROD

**Comment by thecodester** [comment]
I believe this has been solved -- the tag has been changed to products>identity-authentication
