### ISSUE TITLE
Tutorial Page cp-ias-azure-ad-cf.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [SAPDocuments/Tutorials#6233]
Tutorial issue found: [https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/cp-ias-azure-ad-cf/cp-ias-azure-ad-cf.md](https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/cp-ias-azure-ad-cf/cp-ias-azure-ad-cf.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- products>sap-cloud-platform-identity-authentication

 Affected server: PROD

**Comment by MichaelCzcz** [comment]
Identical to https://github.com/SAPDocuments/Tutorials/issues/6232
