### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by taufiqaqmal** [SAPDocuments/Tutorials#6234]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to Step 8 For Consume Services, select the following, and click Next.

There is no Services in Odata, how should I get it?

**Comment by raz-korn** [comment]
Hi @taufiqaqmal ,

This is usually a result of various issues related to credentials for connecting to ES5.
Please refer to issues [5627](https://github.com/SAPDocuments/Tutorials/issues/5627), [5571](https://github.com/SAPDocuments/Tutorials/issues/5571).
I also recommend the following [blog](https://blogs.sap.com/2020/10/13/how-to-check-the-connectivity-to-your-backend-system-in-business-application-studio/).

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
