### ISSUE TITLE
Add Automated System Tests with the SAPUI5 Test Recorder to Your CI/CD Pipeline

### ISSUE THREAD

**Issue by sammok83** [SAPDocuments/Tutorials#6237]
Tutorial URL: https://developers.sap.com/tutorials/cp-cicd-systemtest-recorder.html

Hi, 
Can I please know how do you add jasmine syntax code highlighting in VS Code?

**Comment by MichaelCzcz** [comment]
Hello @sammok83 
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html
