### ISSUE TITLE
API Portal URL not accesible - Starter Scenario CPIS

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6239]
Hello,

Scenario URL: https://developers-qa.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html#84eaf722-548b-4229-a829-6b20c74bb3bd

Step 6: Verify the activated capabilities ->Sub step 2: Click on the URLs of all the activated capabilities and verify if you can successfully access it.

API Portal not accessible - even after doing logout and login, opening in incognito. 
These roles are added in CP trial account for API: 
APIPortal.Administrator | APIManagement.Selfservice.Administrator

Please note: Scenario https://developers-qa.sap.com/tutorials/cp-starter-isuite-api-management.html is also blocked as the link is not accessible.

this is the error on accessing the URL:

![image](https://user-images.githubusercontent.com/66831161/100334740-2b512600-2ffa-11eb-8a62-fd78b265a784.png)

Thanks,
Shubham

labels:
SCP_Isuite_TechEd2020
Assignee: Vikramkulkarni01
prio: High-prio

**Comment by Vikramkulkarni01** [comment]
Hi @i353590 , 

Could you please delete your existing subaccount and recreate it to resolve this issue?

Regards, 
Vikram Kulkarni

**Comment by i353590** [comment]
Hello @Vikramkulkarni01 ,

Thanks for quick reply :)
Sure, I'll check that & update you on the status
Regards,
Shubham

**Comment by i353590** [comment]
Hello @Vikramkulkarni01 ,

tried the same in a different subaccount, it works.

thanks,
Shubham

**Comment by Vikramkulkarni01** [comment]
Thanks for the update @i353590 , 
Please close the issue as soon as it gets resolved. 

Appreciate your support in that so that we can prioritize active cases. 

Thanks for understanding. 

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
