### ISSUE TITLE
Reuse a CAP Java Service

### ISSUE THREAD

**Issue by ramadasupuli** [SAPDocuments/Tutorials#6244]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-service-reuse.html

Please specify the step you are referring to
Not able to perform Step 6 : Here is the error:
user: data $ cd ~/projects/bookstore
user: bookstore $ npm install --save-dev sqlite3
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v10.22.1-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> sqlite3@5.0.0 install /home/user/projects/bookstore/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/home/user/projects/bookstore/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" is installed via remote
+ sqlite3@5.0.0
added 120 packages from 144 contributors and audited 121 packages in 8.923s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

user: bookstore $ cds deploy --to sqlite
[ERROR] srv/services.cds:1:24-33: Artifact "sap.capire.bookstore" has not been found (in using:"db")
[ERROR] srv/services.cds:5:65-73: Element or variable "category" has not been found (in entity:"BooksService.Books"/element:"genre")

Step 6: Deploy bookstore domain model
Let’s deploy the bookstore domain model again to a SQLite database.

First of all install the SQLite node packages to the project. Therefore, open the terminal and go to the root of your project:

Shell/BashCopy
cd ~/projects/bookstore
To install sqlite3 node packages, run:

shell/BashCopy
npm install --save-dev sqlite3
To initialize the bookstore database with the defined domain model and sample data, run:

Shell/BashCopy
cds deploy --to sqlite
This will create a file called sqlite.db in your project root. The name of this database, is defined by an entry in your package.json.

**Comment by iwonahahn** [comment]
Please see the comment in your other [issue](https://github.com/SAPDocuments/Tutorials/issues/6242). Maybe this solves your problems here and you can continue.

**Comment by iwonahahn** [comment]
You have commented in the link issue that the provided solution solved your problem. Can we close this issue here?

**Comment by ramadasupuli** [comment]
Thank you 
Issue resolved by running command  following
unset NODE_PATH
