### ISSUE TITLE
How to deploy to cloud foundry as MTA and use in Launchpad service?

### ISSUE THREAD

**Issue by js1972** [SAPDocuments/Tutorials#6246]
Thanks for this great tutorial. But how would we deploy this as an mta to create and use it in the Launchpad. 
Including this info is highly sort after so that we can see a real-life end to end sample.

**Comment by thecodester** [comment]
@js1972  To which tutorial are you referring?

**Comment by js1972** [comment]
Sorry when clicking feedback from the tutorial I thought it would include that info. 
I'm speaking about the new incident management tutorial :

https://developers.sap.com/group.fiori-tools-odata-v4-incident.html

**Comment by thecodester** [comment]
@js1972 Issues do contain this information but users can delete it, which is what I assume happened here. Go back to a tutorial and click Provide Feedback -- if a link to the tutorial is not included, please let me know.

@jo-fiess Let me know if someone else will handle these issues on these tutorials, and feel free to ask others to join the conversation.

**Comment by jo-fiess** [comment]
Hello Jason,
this tutorial is only meant to show the use of the BAS to create a SAP Fiori elements application and to demonstrate modification via annotation. There is a tuorial in process related to your question. In the meantime, please refer to https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html.
Regards
Joachim

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
