### ISSUE TITLE
Use SAP HANA as the Database for a CAP Java Application

### ISSUE THREAD

**Issue by ramadasupuli** [SAPDocuments/Tutorials#6247]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-hana-db.html

Please specify the step you are referring to
not able to deploy to hand db.  I am getting [ERROR] [cds.deploy] - Service creation failed.
    at Timeout.setTimeout [as _onTimeout] (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds/bin/deploy/to-hana/cfUtil.js:58:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Here are the CLI commands:
user: bookstore $ npm install --save-dev @sap/hdi-deploy
npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v10.22.1-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @sap/hana-client@2.4.202 install /home/user/projects/bookstore/node_modules/@sap/hdi-deploy/node_modules/@sap/hana-client
> node checkbuild.js

+ @sap/hdi-deploy@3.11.15
added 11 packages from 44 contributors, removed 300 packages, moved 8 packages and audited 140 packages in 8.908s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

user: bookstore $ cds deploy --to hana:bookstore-hana
[cds.deploy] - Starting deploy to SAP HANA ...

[cds.deploy] - Creating build tasks
[cds.deploy] - Running build

[cds.deploy] - Using container bookstore-hana

[cds.deploy] - Running 'cf create-service hana hdi-shared bookstore-hana' with options {}
Creating service instance bookstore-hana in org 5dc5a090trial / space dev as rama.dasu.puli.venkata@sap.com...
OK

Create in progress. Use 'cf services' or 'cf service bookstore-hana' to check operation status.
|
Showing info of service bookstore-hana in org 5dc5a090trial / space dev as rama.dasu.puli.venkata@sap.com...

name:             bookstore-hana
service:          hana
tags:             
plan:             hdi-shared
description:      Manage schemas and HDI containers on an existing SAP HANA database.
documentation:    https://help.sap.com/viewer/a36ee1aa073e4e8e840573fb30a72d95/Cloud/en-US/1e9a6cb47e1b44f990a917b4bf8c2e19.html
dashboard:        
service broker:   sm-hana-broker-d9567008-60db-4ec6-b75e-bbabaab4ab13

Showing status of last operation from service bookstore-hana...

status:    create failed
message:   Failed to open connection to the database, because of: Failed to get connection for database '536cb325-ac1b-4e14-8eb4-93eb258d96f3' (536cb325-ac1b-4e14-8eb4-93eb258d96f3.hana.trial-us10.hanacloud.ondemand.com:443), because of: SAP DBTech JDBC: Cannot connect to jdbc:sap://536cb325-ac1b-4e14-8eb4-93eb258d96f3.hana.trial-us10.hanacloud.ondemand.com:443 [Object is closed: com.sap.db.jdbc.SecureChannelSession@6ecff7df 536cb325-ac1b-4e14-8eb4-93eb258d96f3.hana.trial-us10.hanacloud.ondemand.com:443 ConnectionID:0 SessionID:0 on sun.nio.ch.UnixAsynchronousSocketChannelImpl[connected local=/10.140.158.58:35704 remote=536cb325-ac1b-4e14-8eb4-93eb258d96f3.hana.trial-us10.hanacloud.ondemand.com/34.195.80.132:443]].
started:   2020-11-27T22:28:58Z
updated:   2020-11-27T22:28:59Z

There are no bound apps for this service.

Upgrades are not supported by this broker.

[ERROR] [cds.deploy] - Service creation failed.
    at Timeout.setTimeout [as _onTimeout] (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds/bin/deploy/to-hana/cfUtil.js:58:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)

user: bookstore $

**Comment by ramadasupuli** [comment]
I retried, after starting dabase in trial account and I am getting following error:

user: bookstore $ cds deploy --to hana:bookstore-hana
[cds.deploy] - Starting deploy to SAP HANA ...

[cds.deploy] - Creating build tasks
[cds.deploy] - Running build

[cds.deploy] - Using container bookstore-hana

[cds.deploy] - Running 'cf create-service hana hdi-shared bookstore-hana' with options {}
Creating service instance bookstore-hana in org 5dc5a090trial / space dev as rama.dasu.puli.venkata@sap.com...
OK

Service bookstore-hana already exists
[cds.deploy] - Writing /home/user/projects/bookstore/db/default-env.json
[cds.deploy] - Writing /home/user/projects/bookstore/default-env.json
[cds.deploy] - Writing /home/user/projects/bookstore/.cdsrc.json

[cds.deploy] - Deploying to HANA from /home/user/projects/bookstore/db
[cds.deploy] - Using HDI deployer from /home/user/projects/bookstore/node_modules/@sap/hdi-deploy/library.js
@sap/hdi-deploy, version 3.11.15 (mode default), server version 4.00.000.00.1604999660 (4.0.0.0), node version 10.22.1, HDI version 1004, container API version 1003

Using default environment variables from file "default-env.json"

No ignore file at /home/user/projects/bookstore/db/.hdiignore.

Collecting files...

Collecting files... ok (0s 5ms)

3 directories collected
56 files collected
0 reusable modules collected
Target service: bookstore-hana

Session variable APPLICATION is set to "SAP_HDI//".

Previous build with request ID 18 finished at 2020-11-28 02:04:40.025800000 with status Finished and message: Make failed (5 errors, 11 warnings): tried to deploy 56 files, undeploy 0 files, redeploy 0 dependent files.

Processing revoke files...

Processing revoke files... ok (0s 0ms)

Processing grants files...

Processing grants files... ok (0s 0ms)

Preprocessing files...

Preprocessing files... ok (0s 0ms)

Connecting to the container "15BA7139AC8F40B89D06B5E32E7E9B5C"...

Connecting to the container "15BA7139AC8F40B89D06B5E32E7E9B5C"... ok (0s 58ms)

Locking the container "15BA7139AC8F40B89D06B5E32E7E9B5C"...

Locking the container "15BA7139AC8F40B89D06B5E32E7E9B5C"... ok (0s 115ms)

Synchronizing files with the container "15BA7139AC8F40B89D06B5E32E7E9B5C"...
  Deleting files...

  Deleting files... ok

  Writing files...

  Writing files... ok

Synchronizing files with the container "15BA7139AC8F40B89D06B5E32E7E9B5C"... ok (0s 631ms)

56 modified or added files are scheduled for deploy based on delta detection

0 deleted files are scheduled for undeploy based on delta detection (filtered by undeploy whitelist)

0 files are scheduled for deploy based on explicit specification

0 files are scheduled for undeploy based on explicit specification

Deploying to the container "15BA7139AC8F40B89D06B5E32E7E9B5C"...

Polling messages for request id: 23

 Starting make in the container "15BA7139AC8F40B89D06B5E32E7E9B5C" with 56 files to deploy, 0 files to undeploy... 

  Disabling table replication for the container schema "15BA7139AC8F40B89D06B5E32E7E9B5C"... 

  Disabling table replication for the container schema "15BA7139AC8F40B89D06B5E32E7E9B5C"... ok  (0s 74ms)

  Migrating libraries... 
  Migrating libraries... ok  (0s 7ms)
  Making... 
   Preparing... 

   Preparing the make transaction... 
   Deploying the configuration file "src/gen/.hdiconfig"... 
   Warning: Could not find a configured library that contains the "com.sap.hana.di.afllangprocedure" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)
   Warning: Could not find a configured library that contains the "com.sap.hana.di.cds" build plugin [8211539]

     at "src/gen/.hdiconfig" (0:0)
   Warning: Could not find a configured library that contains the "com.sap.hana.di.collection" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)
   Warning: Could not find a configured library that contains the "com.sap.hana.di.fulltextindex" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)
   Warning: Could not find a configured library that contains the "com.sap.hana.di.textconfig" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)
   Warning: Could not find a configured library that contains the "com.sap.hana.di.textdictionary" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)

   Warning: Could not find a configured library that contains the "com.sap.hana.di.textminingconfig" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)
   Warning: Could not find a configured library that contains the "com.sap.hana.di.textrule" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)
   Warning: Could not find a configured library that contains the "com.sap.hana.di.textrule.include" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)
   Warning: Could not find a configured library that contains the "com.sap.hana.di.textrule.lexicon" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)
   Warning: Could not find a configured library that contains the "com.sap.hana.di.virtualfunctionpackage.hadoop" build plugin [8211539]

     at "src/gen/.hdiconfig" (0:0)
   Deploying the configuration file "src/gen/.hdiconfig"... ok  (0s 19ms)
   Deploying the namespace file "src/gen/.hdinamespace"... 
   Deploying the namespace file "src/gen/.hdinamespace"... ok  (0s 5ms)
   Adding "src/gen/ADMINSERVICE_AUTHORS.hdbcds" for deploy... 

   Error: "src/gen/ADMINSERVICE_AUTHORS.hdbcds": could not create a compile unit for the file [8211714]
     at "src/gen/ADMINSERVICE_AUTHORS.hdbcds" (0:0)
   Error: Could not find the "com.sap.hana.di.cds" build plugin [8210501]
   Error: Adding "src/gen/ADMINSERVICE_AUTHORS.hdbcds" for deploy... failed [8211700]
   Error: Preparing... failed [8211602]
   Preparing the make transaction... ok  (0s 73ms)
   Make failed (5 errors, 11 warnings): tried to deploy 56 files, undeploy 0 files, redeploy 0 dependent files 
  Error: Making... failed [8211605]

 Error: Starting make in the container "15BA7139AC8F40B89D06B5E32E7E9B5C" with 56 files to deploy, 0 files to undeploy... failed [8214168]

Deployment to container 15BA7139AC8F40B89D06B5E32E7E9B5C failed - error: HDI make failed [Deployment ID: none].

Error: HDI make failed

(2s 54ms)



[ERROR] [cds.deploy] - HDI deployment failed with exit code 1
    at hdiDeployLib.deploy (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds/bin/deploy/to-hana/hdiDeployUtil.js:92:35)
    at ChildProcess.<anonymous> (/home/user/projects/bookstore/node_modules/@sap/hdi-deploy/library.js:101:14)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)

user: bookstore $

**Comment by iwonahahn** [comment]
Hi @ramadasupuli,

If the issue still exists please provide the full build log by running this command:
`mvn clean install -X > build-output.log`. Please attach the `build-output.log` to this issue for further investigation.

Thank you,
Iwona

**Comment by ramadasupuli** [comment]
Please find attached file for log.

[build-output (1).log](https://github.com/SAPDocuments/Tutorials/files/5619853/build-output.1.log)

**Comment by iwonahahn** [comment]
Thanks. I will need to talk to dev about this. Please give us some time to get back to you.

**Comment by iwonahahn** [comment]
Please try the missing step as described [here](https://github.com/SAPDocuments/Tutorials/pull/6267/files). The tutorial will be updated asap. Hope that helps.

**Comment by ramadasupuli** [comment]
Hi iwonahahn,

After configuring missing steps,  I am getting following error and please find the log [build-output (2).log](https://github.com/SAPDocuments/Tutorials/files/5636931/build-output.2.log)

user: bookstore $ cds deploy --to hana:bookstore-hana
[cds.deploy] - Starting deploy to SAP HANA ...

[cds.deploy] - Creating build tasks
[cds.deploy] - Running build

[cds.deploy] - Using container bookstore-hana

[cds.deploy] - Running 'cf create-service hana hdi-shared bookstore-hana' with options {}
Creating service instance bookstore-hana in org 5dc5a090trial / space dev as rama.dasu.puli.venkata@sap.com...
OK

Service bookstore-hana already exists
[cds.deploy] - Writing /home/user/projects/bookstore/db/default-env.json
[cds.deploy] - Writing /home/user/projects/bookstore/default-env.json
[cds.deploy] - Writing /home/user/projects/bookstore/.cdsrc.json

[cds.deploy] - Deploying to HANA from /home/user/projects/bookstore/db
[cds.deploy] - Using HDI deployer from /home/user/projects/bookstore/node_modules/@sap/hdi-deploy/library.js
@sap/hdi-deploy, version 3.11.15 (mode default), server version 4.00.000.00.1604999660 (4.0.0.0), node version 10.22.1, HDI version 1004, container API version 1003

Using default environment variables from file "default-env.json"

No ignore file at /home/user/projects/bookstore/db/.hdiignore.

Collecting files...

Collecting files... ok (0s 6ms)
3 directories collected

56 files collected
0 reusable modules collected
Target service: bookstore-hana

Session variable APPLICATION is set to "SAP_HDI//".

Previous build with request ID 46 finished at 2020-12-03 14:53:18.815468000 with status Finished and message: Make failed (5 errors, 11 warnings): tried to deploy 56 files, undeploy 0 files, redeploy 0 dependent files.

Processing revoke files...

Processing revoke files... ok (0s 0ms)

Processing grants files...
Processing grants files... ok (0s 0ms)

Preprocessing files...

Preprocessing files... ok (0s 1ms)

Connecting to the container "8569508A5BD54DA8B9342C5F614BCAFC"...

Connecting to the container "8569508A5BD54DA8B9342C5F614BCAFC"... ok (0s 84ms)
Locking the container "8569508A5BD54DA8B9342C5F614BCAFC"...

Locking the container "8569508A5BD54DA8B9342C5F614BCAFC"... ok (0s 159ms)

Synchronizing files with the container "8569508A5BD54DA8B9342C5F614BCAFC"...
  Deleting files...

  Deleting files... ok

  Writing files...

  Writing files... ok

Synchronizing files with the container "8569508A5BD54DA8B9342C5F614BCAFC"... ok (0s 626ms)

56 modified or added files are scheduled for deploy based on delta detection

0 deleted files are scheduled for undeploy based on delta detection (filtered by undeploy whitelist)

0 files are scheduled for deploy based on explicit specification

0 files are scheduled for undeploy based on explicit specification

Deploying to the container "8569508A5BD54DA8B9342C5F614BCAFC"...

Polling messages for request id: 51

 Starting make in the container "8569508A5BD54DA8B9342C5F614BCAFC" with 56 files to deploy, 0 files to undeploy... 

  Disabling table replication for the container schema "8569508A5BD54DA8B9342C5F614BCAFC"... 

  Disabling table replication for the container schema "8569508A5BD54DA8B9342C5F614BCAFC"... ok  (0s 71ms)

  Migrating libraries... 
  Migrating libraries... ok  (0s 8ms)
  Making... 
   Preparing... 

   Preparing the make transaction... 
   Deploying the configuration file "src/gen/.hdiconfig"... 

   Warning: Could not find a configured library that contains the "com.sap.hana.di.afllangprocedure" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)
   Warning: Could not find a configured library that contains the "com.sap.hana.di.cds" build plugin [8211539]

     at "src/gen/.hdiconfig" (0:0)
   Warning: Could not find a configured library that contains the "com.sap.hana.di.collection" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)

   Warning: Could not find a configured library that contains the "com.sap.hana.di.fulltextindex" build plugin [8211539]

     at "src/gen/.hdiconfig" (0:0)
   Warning: Could not find a configured library that contains the "com.sap.hana.di.textconfig" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)

   Warning: Could not find a configured library that contains the "com.sap.hana.di.textdictionary" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)

   Warning: Could not find a configured library that contains the "com.sap.hana.di.textminingconfig" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)

   Warning: Could not find a configured library that contains the "com.sap.hana.di.textrule" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)

   Warning: Could not find a configured library that contains the "com.sap.hana.di.textrule.include" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)

   Warning: Could not find a configured library that contains the "com.sap.hana.di.textrule.lexicon" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)

   Warning: Could not find a configured library that contains the "com.sap.hana.di.virtualfunctionpackage.hadoop" build plugin [8211539]
     at "src/gen/.hdiconfig" (0:0)

   Deploying the configuration file "src/gen/.hdiconfig"... ok  (0s 8ms)
   Deploying the namespace file "src/gen/.hdinamespace"... 
   Deploying the namespace file "src/gen/.hdinamespace"... ok  (0s 5ms)

   Adding "src/gen/ADMINSERVICE_AUTHORS.hdbcds" for deploy... 

   Error: "src/gen/ADMINSERVICE_AUTHORS.hdbcds": could not create a compile unit for the file [8211714]
     at "src/gen/ADMINSERVICE_AUTHORS.hdbcds" (0:0)

   Error: Could not find the "com.sap.hana.di.cds" build plugin [8210501]
   Error: Adding "src/gen/ADMINSERVICE_AUTHORS.hdbcds" for deploy... failed [8211700]

   Error: Preparing... failed [8211602]

   Preparing the make transaction... ok  (0s 57ms)
   Make failed (5 errors, 11 warnings): tried to deploy 56 files, undeploy 0 files, redeploy 0 dependent files 

  Error: Making... failed [8211605]
 Error: Starting make in the container "8569508A5BD54DA8B9342C5F614BCAFC" with 56 files to deploy, 0 files to undeploy... failed [8214168]

Deployment to container 8569508A5BD54DA8B9342C5F614BCAFC failed - error: HDI make failed [Deployment ID: none].

Error: HDI make failed

(2s 288ms)



[ERROR] [cds.deploy] - HDI deployment failed with exit code 1
    at hdiDeployLib.deploy (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/node_modules/@sap/cds/bin/deploy/to-hana/hdiDeployUtil.js:92:35)
    at ChildProcess.<anonymous> (/home/user/projects/bookstore/node_modules/@sap/hdi-deploy/library.js:101:14)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

user: bookstore $

**Comment by iwonahahn** [comment]
@chgeo & @beckermarc Could someone of you please have a look at this issue? Thanks a lot!

**Comment by chgeo** [comment]
@iwonahahn this is likely caused by a glitch in the tutorial in [step 3.3](https://developers.sap.com/tutorials/cp-cap-java-hana-db.html#9757b66e-808a-4b69-830f-604fb790fcb9).  The snippet must be like this
```json
{
    "hana" : { "deploy-format": "hdbtable" }
}
```
i.e. w/o the `cds` block.
Why?  `.cdsrc.json` files do not start with the `cds` block. That is only required for `package.json` config.

**Comment by iwonahahn** [comment]
Will be fixed with #6303.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
