### ISSUE TITLE
Create Decision Table and Text Rules

### ISSUE THREAD

**Issue by kbprasad79** [SAPDocuments/Tutorials#6249]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules06-dt-textrule.html

Please specify the step you are referring to

Hi, Is there a standard formula for sub string? i.e access part of a string and compare with others elements or constants.

Regards

**Comment by ArchanaShukla** [comment]
Yes, you can Functional operators like CONTAINS etc. See [help documentation](https://help.sap.com/viewer/0e4dd38c4e204f47b1ffd09e5684537b/Cloud/en-US/1d3206a8125a440faf2f4a15852dc29c.html)

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
