### ISSUE TITLE
Design and Deploy Your First Integration Flow

### ISSUE THREAD

**Issue by johnma999** [SAPDocuments/Tutorials#6257]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Please specify the step you are referring to how you test the API. Can you provide a sample data to call the interface? What format is it? That would help us to understand your tutorial a lot better.

**Comment by Vikramkulkarni01** [comment]
Hi @johnma999 , 

Thanks for the feedback. 

I will check and get back to you with sample data.  

However, if you wait till Dec 3rd, we are coming with the new enhancements for this tutorial and you can test the sample data using API management. 

Appreciate your support.

Regards, 
Vikram Kulkarni

**Comment by johnma999** [comment]
Thanks, Vikram.
Please provide me with sample data anytime. I found the blog is very confusing as there is no input data structure. My background is from PI/PO development. Hopefully a sample data will help me understand how this interface works.

**Comment by Vikramkulkarni01** [comment]
Hi @johnma999 , 
The tutorial is updated now and you can test the CPI using input data in API portal now.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
