### ISSUE TITLE
Set Up and Generate a New SAP Fiori App Project

### ISSUE THREAD

**Issue by srahemi** [SAPDocuments/Tutorials#6258]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

Please specify the step you are referring to 

hi 
i got this error in step 4 after click finish
I would greatly appreciate it if help me

![1866760-2020-11-30-15-02-36](https://user-images.githubusercontent.com/72384086/100710842-98333a00-33c5-11eb-9bfd-fcd6aacf3c29.png)

**Comment by cjbernal** [comment]
Hi srahemi,

It appears my colleague Ian has responded to your query on answers.sap.com: https://answers.sap.com/questions/13198596/error-during-create-fiori-generator-project-in-vis.html

Could you try his proposed solution and let him know if it works? 

Thanks and regards,
Conrad (SAP UX Engineering)

**Comment by thecodester** [comment]
I will close this issue since it is being dealt with on answers. Let me know if you  need anything else.
