### ISSUE TITLE
Call API Business Hub API from a SAPUI5 Application

### ISSUE THREAD

**Issue by timcashmore** [SAPDocuments/Tutorials#6263]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-api-ui5-app.html

Please specify the step you are referring to
Step 3 - Activity Number 8.

Not sure if it is mandatory, but I couldn't see any APIs after selecting API Business Hub.  Did a quick search and it seems to imply in the online Help that yiu specifically need to set-up a destination for api-business hub.  I did this and it appeared to work. see
https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/7e31a5ad9ff8491d93b039daae5c37e0.html
There is a very useful text import file to create the destination - might be worth including in the tutorial.
[APIIBusinessHubDest.txt](https://github.com/SAPDocuments/Tutorials/files/5628634/APIIBusinessHubDest.txt)
[APIIBusinessHubDest.txt](https://github.com/SAPDocuments/Tutorials/files/5628641/APIIBusinessHubDest.txt)

**Comment by IObert** [comment]
Oh wow, good catch. I totally missed this, thanks for pointing it out!
I added a new step, in the beginning, to make sure everyone has these destinations in place.
