### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by danhenry00** [SAPDocuments/Tutorials#6268]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html

Please specify the step you are referring to 8 

![image](https://user-images.githubusercontent.com/69702325/100899225-9635ad80-348f-11eb-9370-cb3d47907fe6.png)

I'm unable to complete testing of the workflow since I'm getting a 403 - Forbidden response.  I'm not sure how to overcome it. 

Please review and advise.

Thanks,
Dan

**Comment by danhenry00** [comment]
![image](https://user-images.githubusercontent.com/69702325/100899705-1e1bb780-3490-11eb-9f80-9b0050d3881d.png)

Also, I'm not able to access any logs to find out more.

**Comment by gauthamkrishna-sap** [comment]
Hello,
Could you please try accessing your tenant in incognito mode and see if the info message you see still appears? Also, on which landscape are you facing this issue?
Best Regards,
Gautham

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
