### ISSUE TITLE
Reuse a CAP Java Service - Error in cds

### ISSUE THREAD

**Issue by dheffernan-sap** [SAPDocuments/Tutorials#6274]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-service-reuse.html

Please specify the step you are referring to Step 6: Deploy bookstore domain model

user: bookstore $ cds deploy --to sqlite
[ERROR] db/schema.cds:14:56-62: Artifact "sap.capire.bookstore.Books" has no element "author" (in entity:"sap.capire.bookstore.Authors"/element:"books")
[ERROR] db/schema.cds:4:49-71: Cannot find package module '@sap/capire-products'

user: bookstore $ 

The same errors appear in both cds files schema.cds && services.cds

thank you
David

**Comment by iwonahahn** [comment]
Hi David,

Please see the comment in this [issue](https://github.com/SAPDocuments/Tutorials/issues/6242). Maybe this solves your problem and you can continue. Otherwise please get back here.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi @dheffernan-sap,

We haven't heard from you in a while, so we are closing the issue. (@thecodester) 
If you still have questions, feel free to reopen the issue. 

Best regards,
Iwona
