### ISSUE TITLE
Manage Message Processing in Case of Errors

### ISSUE THREAD

**Issue by fc158** [SAPDocuments/Tutorials#6281]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-handle-exceptions.html

Please specify the step you are referring to: Step 6

Dears, 
I've a doubt: was trying to answer the last question 
(What are the different message processing status in SAP Cloud Platform Integration?) 
and possibly input the following answers:

- Completed

- Failed

- Escalated

which is reported as Incorrect; 
tried with other possible solutions, and reported always as Incorrect.

Could you please confirm that the answer checking is correctly working?

Many thanks and sorry for the trouble...
Flavio

**Comment by fc158** [comment]
issue is limited when using a Mac, tried with Win10 and it works; 
personally, the issue is solved;
leaving the thread open, if you want to chek further...

**Comment by thecodester** [comment]
Thanks for reporting. We will check what the issue might be for Mac.
