### ISSUE TITLE
Set Up SAP Cloud Platform Launchpad Service

### ISSUE THREAD

**Issue by alexalmeidabr** [SAPDocuments/Tutorials#6285]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

I followed the steps to configure the Launchpad service but when I go to the application a access denied page is displayed. I have configured the roles correctly.

**Comment by thecodester** [comment]
@IrisSasson Can you respond?

**Comment by IrisSasson** [comment]
Hi, 
Please try again
If this doesn't work - your user probably doesn't have the Launchpad_Admin role. Please follow Step 2 of this tutorial to make sure your user has this role: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Thanks

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
