### ISSUE TITLE
Custom Analytical Queries

### ISSUE THREAD

**Issue by alevit84** [SAPDocuments/Tutorials#6286]
Tutorial URL: https://developers.sap.com/tutorials/abap-custom-analytical-queries.html

I don't have the role "SAP_BCR_CA_ANA_AQD_PC " but i found "SAP_BR_ANALYTICS_SPECIALIST". I don't have the "Custom analitycal Queries" under "Query Design".

**Comment by thecodester** [comment]
@mervey45 Can you respond?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
