### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by mchcn2018** [SAPDocuments/Tutorials#6288]
Tutorial URL: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html

Step 6: Create database artifacts
CF Region: EU10
Error Message: 
7:58:02 (hat) The "mobileservices" destination is not found in your SCP account cockpit. Hide the Mobile submenus.
17:58:03 (hat) Failed to obtain Mobile Service info: 404
17:58:26 (Project Space Builder) canceled
18:00:15 (git) Project hana-cf-get-started-trial: Git repository hana-cf-get-started-trial: Clone request completed successfully.
18:00:53 (Executor) The "task for hdb build" process started.
18:00:53 (Executor) Started the "task for hdb build" provision.
18:00:58 (Provision) Service provisioning for module: "/db"
18:00:58 (Provision) Could not create the 'my-hdi' instance of the 'hana' service type for the 'hdi_db' resource. No hdi-shared plan available found in this space.
18:00:58 (Provision) Provision fail since one of the provision tasks finished with error.
18:00:58 (Executor) The "task for hdb build" provision finished with an error: Provision failed. See console for more details.
18:00:58 (HDB) Build of /hana-cf-get-started-trial/db failed due to Provision failed. See console for more details..

The connection keeps running for hours, but db is not created. Please advise

**Comment by jung-thomas** [comment]
> Could not create the 'my-hdi' instance of the 'hana' service type for the 'hdi_db' resource. No hdi-shared plan available found in this space.

This error message would indicate that the space you are targeting doesn't have a HANA plan in it.  Are you doing this on a trial account? Did you complete the previous steps to setup HANA Cloud in your trial account?  Are you sure your project in the Web IDE is setup to target the same space in which you provisioned the HANA Cloud trial?

**Comment by mchcn2018** [comment]
Thank you for your reply. Please check my answers to your questions.
Are you doing this on a trial account? 
Yes, I did
Did you complete the previous steps to setup HANA Cloud in your trial account? 
In Step 4: Configure SAP Web IDE, SAP Web IDE Full-Stack Subscription is not available, so I had to chose SAP Web IDE for SAP HANA Development instead. Is it the reason for the error message?

**Comment by mchcn2018** [comment]
Are you sure your project in the Web IDE is setup to target the same space in which you provisioned the HANA Cloud trial?
I am not sure, however I followed the configuration for SAP Web IDE Full-Stack in SAP Web IDE for SAP HANA Development, e.g. enabling SAP HANA Database Development Tools in Preference - Extension, define API Endpoint in Preference - Cloud Foundry etc.

**Comment by jung-thomas** [comment]
>In Step 4: Configure SAP Web IDE, SAP Web IDE Full-Stack Subscription is not available, so I had to chose SAP Web IDE for SAP HANA Development instead.

SAP Web IDE for SAP HANA Development is exactly what the tutorial says you should choose at this step:
Then click on Add Service Plans. Search for entitlements with web in the name. Choose **SAP Web IDE for HANA development**

This error says you HANA service plan isn't available.  It doesn't have anything to do with the entitlement for the Web IDE. Its the HANA service plan that is missing in the targeted space. 

The things to double check are have you created the HANA Cloud instance correctly.  In the Web IDE which space are you targeting?  Are you sure its the trial space where you created the HANA Cloud instance?

**Comment by jung-thomas** [comment]
>I am not sure, however I followed the configuration for SAP Web IDE Full-Stack in SAP Web IDE for SAP HANA Development, e.g. enabling SAP HANA Database Development Tools in Preference - Extension, define API Endpoint in Preference - Cloud Foundry etc.

At this step when you configured the API endpoint, org and space - are you sure you are pointed to the trial org and space and that this trial org and space is where you created your HANA Cloud trial instance?  Because this error says that the org/space you are configured does NOT contain a HANA service plan.

**Comment by mchcn2018** [comment]
I just recognized that SAP HANA Cloud instance hasn't start automatically after creating yesterday. so I just started it now, it might be the reason, isn't?

**Comment by thecodester** [comment]
I assume starting the service solved the issue. In any event, we haven't heard back from you so I am closing the issue. If the issue persists, feel free to reopen the issue.
