### ISSUE TITLE
Add a User Task to Your Workflow and Deploy - the deployment aborts with an error

### ISSUE THREAD

**Issue by jankstar** [SAPDocuments/Tutorials#6289]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-3-add-usertask-cf.html

Step 4: Build and deploy
point "1 - Update the mta.yaml file of your onboarding ..."
there is no line 19 to change to "org.cloudfoundry.existing-service" - is line 14 meant here?

point "4 - Right-click the .mtar file, and then select Deploy MTA Archive..."
the deployment aborts with an error:

Detected MTA schema version: "3"
No deployed MTA detected - this is initial deployment
Detected new MTA version: "0.0.1"
Error building content deployment configuration for module: "approvals": Controller operation failed: 404 Not Found: Service instance wm_workflow not found. 
Proceeding with automatic retry... (3 of 3 attempts left)
Error building content deployment configuration for module: "approvals": Controller operation failed: 404 Not Found: Service instance wm_workflow not found. 
Proceeding with automatic retry... (2 of 3 attempts left)
Error building content deployment configuration for module: "approvals": Controller operation failed: 404 Not Found: Service instance wm_workflow not found. 
Proceeding with automatic retry... (1 of 3 attempts left)
Error building content deployment configuration for module: "approvals": Controller operation failed: 404 Not Found: Service instance wm_workflow not found. 
Process failed.

any idea what I can do?
Thanks!

**Comment by AstridHerbst** [comment]
Hi,
Thanks for your feedback!
You are right about the wrong lines for updating the yaml file. These should be:
   In lines 9 and 13, replace workflow_mta with wm_workflow.
   In line 14, replace org.cloudfoundry.managed-service with org.cloudfoundry.existing-service.

Apparently, no wm_workflow instance has been created in your subaccount. Have you executed the prerequisites in the first tutorial, especially, the booster described at: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-1-setup.html?

Best regards,
Astrid

**Comment by jankstar** [comment]
Hi,
Thank you for the information. 
I think that is the problem. In my account, the DESTINATION generation aborts with an error. I have defined a new SPACE in my account and run BOOSTER again - unfortunately the same problem: "... Creation of below destinations faild ... WM_CF_SPACE_PROVIDER ...".  When I call up DESTINATION, only a red bar appears "Could not load list of global accounts: Internal Server Error (500)". 
I could delete the entire account and create a new one and then start all over again?!
best regards
J.K.
