### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by rvodela** [SAPDocuments/Tutorials#6291]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html

When I was trying this I had issues in configuration of Gmail and testing the tutorial'
I wrote the following blog on how to configure gmail for CPI
https://blogs.sap.com/2020/12/06/cloud-platform-integration-gmail-configuration-and-integration-flow/

**Comment by thecodester** [comment]
@gauthamkrishna-sap  Can you respond?

**Comment by gauthamkrishna-sap** [comment]
Hi,

Great that you have written a blog :) 
We also have a new TechEd session where one of the parts is to configure connectivity to GMail account: https://github.com/SAP-samples/teched2020-DEV165/blob/main/exercises/Ex-1.Setting_Up_Connectivty_to_Non_SAP_Systems/Ex.1.4.Set_Up_Gmail_Connectivity.md

Please refer to that. In the meantime, we are working on updating this tutorial. 

Best Regards,
Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
