### ISSUE TITLE
Discover and Import the Live Process Package

### ISSUE THREAD

**Issue by dmanvzla** [SAPDocuments/Tutorials#6292]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-workflowmanagement-discover.html

Hi team, 

I am trying to follow the tutorial to import Live Processes in my SCP trial account but I am not able to complete the step 2 to open the Process Flexibility Cockpit

I got this error message

 
![image](https://user-images.githubusercontent.com/75594211/101301055-3a578580-37fd-11eb-9a26-feda68d787bb.png)

I have double checked the destination to WM_CF_SPACE_PROVIDER and it looks ok, it was automatically created through the booster

It is pointing to the space id of my workflow instance
https://deploy-service.cfapps.us10.hana.ondemand.com/api/v1/spaces/d93201b4-3193-4dae-9f0a-c6a818db7421

![image](https://user-images.githubusercontent.com/75594211/101301087-56f3bd80-37fd-11eb-8c7a-3f93183abcc2.png)

Here is the audit event logs with details about the workflow guid
![image](https://user-images.githubusercontent.com/75594211/101305123-8efffe00-3807-11eb-8bd6-e7f60b9e2b39.png)

When I click on check connection I got this message
![image](https://user-images.githubusercontent.com/75594211/101301114-67a43380-37fd-11eb-82f9-1c5d588c1fe7.png)

Do you have any idea what could be the issue?

**Comment by Deeksha-R** [comment]
Hi, 
Once you are reconfigured your credentials, please try to import a package again.

Regards
Deeksha

**Comment by dmanvzla** [comment]
Hi Deeksha, 

I have tried that, but it did not worked, how can i test the connection?

**Comment by dmanvzla** [comment]
Hi Deeksha, 

I´ve retried everything a couple of times and it finally worked, not sure if it was a momentary issue, but is now working i can now import the live processes

Thanks

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
