### ISSUE TITLE
Develop and Run SAP Fiori Application With SAP Business Application Studio

### ISSUE THREAD

**Issue by AbeDong** [SAPDocuments/Tutorials#6299]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Please specify the step you are referring to
Step 9: Run SAP Fiori application
The Service is the one I created in OpenSAP Restful course. It works when I preview the app in Step 5.  But after step 9, click https://a0cc9ebf-e283-4a63-b412-fab03d712710.abap-web.us10.hana.ondemand.com/sap/bc/ui5_ui5/sap/ztravel_app_abe/index.html 
the ABAP public trail login screen shows, enter the credential, then nothing shows.
![Annotation](https://user-images.githubusercontent.com/34675321/101458976-97c11300-3972-11eb-9914-194ad0db5df6.jpg)

**Comment by mervey45** [comment]
Hi @AbeDong ,

we have currently some issues with the deployment. The SAP Fiori launchpad side don't show up. But we are working on this issue right now.

Thank you for your understanding.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
