### ISSUE TITLE
Tour the SAP Community

### ISSUE THREAD

**Issue by S0002623352** [SAPDocuments/Tutorials#6302]
Tutorial URL: https://developers.sap.com/tutorials/community-start.html

Please specify the step you are referring to

All Done buttons do not turn green, even i performed all the steps as required..

![2020-12-08_11-08-58](https://user-images.githubusercontent.com/75670239/101470259-0f2c7d80-3946-11eb-85c2-077668b0288d.png)
![2020-12-08_11-09-11](https://user-images.githubusercontent.com/75670239/101470284-18b5e580-3946-11eb-90d7-e6f666f6d296.png)

No Feedback is needed.

**Comment by thecodester** [comment]
@S0002623352 What is your community ID?

**Comment by thecodester** [comment]
@S0002623352 Do you get any history on the developers.sap.com when you click the DONE button? What happens?
![image](https://user-images.githubusercontent.com/11659786/102516859-03ecf680-4098-11eb-946c-8ae750c7425e.png)

**Comment by thecodester** [comment]
I will close this since I assume either there was login issue or you did not actually click the buttons -- the tutorial is not automatically updated. Feel free to reopen if the issue persists, and explain exactly what you do and what you expect. Thanks.
