### ISSUE TITLE
Consume the API Proxy in SAP Web IDE

### ISSUE THREAD

**Issue by guyperets** [SAPDocuments/Tutorials#6306]
Tutorial URL: https://developers.sap.com/tutorials/hcp-apim-webide-int.html

Hi,

I've created the destinations in Steps 6 and 7.
I'm having issues viewing the catalog service in the WebIDE.
I'm getting the following error in the WebIDE:
"unable to reach the catalog service. please check the service configuration and connect again"

Please help.
Guy

**Comment by shilpavij** [comment]
Dear Guy,
As of today SAP APIM integration with WebIDE on CF is a limitation. We are working on this to solve it.

Regards
Shilpa

**Comment by guyperets** [comment]
Thanks, I'll be happy to QA it once resolved.
Guy

Best Regards,
Guy Perets
Principal Banking Solution Architect
Global Consulting Delivery
SAP Israel,  14 Eli Hurvitz St.,  43665 Raanana,  Israel
T +972-9-777-5226  |  M +972-54-745-4880  |  F +972-74-760-1226 | E guy.perets@sap.com<mailto:guy.perets@sap.com>

**Comment by thecodester** [comment]
@shilpavij If this is a limitation for this tutorial, you should indicate this in the prerequisites, and close this issue. Thanks.

**Comment by thecodester** [comment]
@shilpavij Can you update us on this tutorial, and my question? If the tutorial won't work, we don't want it 😀

**Comment by MichaelCzcz** [comment]
The tutorial is no longer available.
