### ISSUE TITLE
Install the SAP HANA Client

### ISSUE THREAD

**Issue by RK7-RK** [SAPDocuments/Tutorials#6312]
Tutorial URL: https://developers.sap.com/tutorials/hana-clients-install.html

Hello, 

i have installed the SAP HANA Client, but there is no 32 Bit driver, only the 64-bit driver.
Where can i find the 32-Bit driver?

Best regrads
Robin

**Comment by danielva** [comment]
In the tutorial, under Step 3: Alternate Install Option, the SAP Software Downloads site has a drop down called Items Available to Download.  From there, you can choose the option Windows Server on IA32 32Bit to download a 32 bit version of the SAP HANA client for windows.  

Hope that helps.  I will look into adding a note about that in a future update to the tutorial.

Regards,
Dan v

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
