### ISSUE TITLE
Use Machine Learning to Extract Information from Documents with Document Information Extraction Trial UI

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#6313]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dox-ui.html

Please specify the step you are referring to : Step 2: See and edit extraction results

The names of Header fields and Line items are different than the actual result. Such as Document Number(in screenshot its Invoice number), Receiver Name(Buyer Name) Receiver Address(Buyer Address) etc. as shown in screenshot below
Expected : 
![image](https://user-images.githubusercontent.com/50734023/101620016-06b56f00-3a3a-11eb-9a11-eb4c92c1f7d0.png)

Actual Header field names : 
![image](https://user-images.githubusercontent.com/50734023/101619769-b9d19880-3a39-11eb-8271-c4d3ed4aeed7.png)

Landscape Label name : trail1 & trail2
Scenario Label: SCPTest-docinfo
Sprint Label: SCPTest-2012B
Priority: Low

**Comment by Juliana-Morais** [comment]
Hello,

The screenshots have been updated, as requested (https://github.com/SAPDocuments/Tutorials/pull/6356).

Best regards,
Juliana
