### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by equilibrium999** [SAPDocuments/Tutorials#6318]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html

Please specify the step you are referring to Step 5: Execute API

When I execute, it returns me this error.

`<!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1></body></html>`

**Comment by Vikramkulkarni01** [comment]
Hi @equilibrium999 , 

Thanks for your feedback.

Then error code that you are receiving is a generic one. The server understood the request but is refusing to fulfill it. 

Could you please check the authorization?

Regards, 
Vikram Kulkarni

**Comment by equilibrium999** [comment]
Hi @Vikramkulkarni01 

I've followed the whole tutorial, assign myself roles that are required in the tutorial. 

Regards,

Minh

**Comment by thecodester** [comment]
@Vikramkulkarni01 Can you follow-up and respond? Thanks.

**Comment by Vikramkulkarni01** [comment]
Hi Minh, 

Could you please check now and see if you are still facing the same issue?

Regards, 
Vikram

**Comment by equilibrium999** [comment]
Hi @Vikramkulkarni01 
I still got the error.
However, I'll try with another account.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
