### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Tutorials#6319]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Step 1 -->  Sub step 2 : 
                                      Update screenshot
![1](https://user-images.githubusercontent.com/65213299/101721631-6c533b00-3ace-11eb-92bb-7b9192db4b28.PNG)

Step 1 -->  Sub step 4 : 
                                      Update screenshot
![2](https://user-images.githubusercontent.com/65213299/101722346-08ca0d00-3ad0-11eb-82e0-cf4c05d3f6ca.PNG)

Labels :
Landscape Labels: trail1, trail2, trail3
SCPTest-eboard: Develop an SAP Fiori App Using SAP Business Application Studio
Priority label :‘Low-prio’

Best Regards,
Shivakumar P

**Comment by thecodester** [comment]
@raz-korn Let me know if you will be updating the screenshot. If not, I will close issue.

**Comment by raz-korn** [comment]
Hi @shivakumar-p-sap ,

Many screenshots were update in the tutorial.
Also the flow was changed to use SAP best practice - using managed approuter instead of standalone approuter.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
