### ISSUE TITLE
Build and Deploy Your SAP Fiori App to SAP Cloud Platform

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Tutorials#6320]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html

Step 3 : Last screenshot needs to update

![Last](https://user-images.githubusercontent.com/65213299/101722180-ab35c080-3acf-11eb-81d3-c4ba85593682.PNG)

Labels :
Landscape Labels: trail1, trail2, trail3
SCPTest-eboard: Develop an SAP Fiori App Using SAP Business Application Studio
Priority label :‘Low-prio’

Best Regards,
Shivakumar P

**Comment by raz-korn** [comment]
Hi @shivakumar-p-sap ,

Many screenshots were update in the tutorial.
Also the flow was changed to use SAP best practice - using managed approuter instead of standalone approuter.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
