### ISSUE TITLE
Use Machine Learning to Extract Information from Documents with Document Information Extraction Trial UI

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#6321]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dox-ui.html

Please specify the step you are referring to : Step 1: Upload documents

Region : US, in trial account

Uploaded the given sample invoice in Document Information Extraction Trial UI but it is observed that the upload status will be in pending for longer time and later it fails to upload the document.

![image](https://user-images.githubusercontent.com/50734023/101735285-af6dd800-3ae7-11eb-8fc9-14c11db3b9f1.png)

Note : Uploading document works fine in EU region.

Labels to be added:
Landscape label: trial2
Scenario label: SCPTest-docinfo
Sprint Label: SCPTest-2012B
Priority: High

**Comment by Juliana-Morais** [comment]
I've tested again today and the issue persists. I've opened an internal BCP ticket (https://support.wdf.sap.corp/sap/support/message/2080443362). The team is already following up on this and there's also a new release coming until the end of the week that might solve the issue.

**Comment by Juliana-Morais** [comment]
Hello, I've just tested. The issue has been fixed by the latest release.

**Comment by NidhiMurkute** [comment]
Thanks for the update. Issue is resolved, hence closing the ticket.
