### ISSUE TITLE
Add a step for Login into the Mobile Services Cockpit

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6322]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html

Step 3: Open card in Mobile Services Cockpit

After launching the Mobile Services Cockpit, we get a login screen as below. Include a step for the login operation.

![image](https://user-images.githubusercontent.com/65999547/101756619-3331bf80-3afc-11eb-9d62-357f253f2920.png)

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2011A
Scenario Label: SCPTest-mcard
Priority: Low

Best Regards,
Priyanka

**Comment by sandeep-tds** [comment]
Hi @PriyankaShivakumar,

Thank you for your feedback. I will add the required details.
The changes will be available next week.

Warm Regards
Sandeep T D S

**Comment by sandeep-tds** [comment]
Hi @PriyankaShivakumar 

The updated tutorial has been released, can you please verify the changes and update the ticket? 
Thank you so much for your support.

Warm Regards
Sandeep T D S

PS: The step in question may have been deleted dut to the update.

**Comment by PriyankaShivakumar** [comment]
Hi @sandeep-tds 

Thanks for the update. You are right the step is deleted now.

Best Regards,
Priyanka
