### ISSUE TITLE
Add Steps to close the Mobile cards Advisory popup.

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6323]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html

Step 3: Open card in Mobile Services Cockpit

After login to the Mobile services cockpit, we get a SAP Mobile cards Advisory popup as below. Add steps to close it.
![image](https://user-images.githubusercontent.com/65999547/101756913-8a379480-3afc-11eb-9b8a-53944b5de76b.png)

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2011A
Scenario Label: SCPTest-mcard
Priority: Low

Best Regards,
Priyanka

**Comment by sandeep-tds** [comment]
Hi @PriyankaShivakumar,

Thank you for your feedback. I will add the required details. 
The changes will be available next week.

Warm Regards
Sandeep T D S

**Comment by sandeep-tds** [comment]
Hi @PriyankaShivakumar 

The updated tutorial has been released, can you please verify the changes and update the ticket? 

Thank you so much for your support.

Warm Regards
Sandeep T D S

**Comment by sandeep-tds** [comment]
Hi @PriyankaShivakumar 

The updated tutorial has been released, can you please verify the changes and update the ticket? 
Thank you so much for your support.

Warm Regards
Sandeep T D S

PS: The step in question may have been deleted dut to the update.

**Comment by PriyankaShivakumar** [comment]
Hi @sandeep-tds 

Thanks for the update. You are right the step is deleted now.

Best Regards,
Priyanka
