### ISSUE TITLE
Mobile Services Cockpit: Screenshot has to be changed

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6324]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html

Step 3: Open card in Mobile Services Cockpit

While selecting the supplier card, booster welcome card is also present. Since the previous tutorial is mentioned as a prerequisite for this tutorial, From a customer perspective in order to avoid confusion, Screenshot has to be updated to the one given below.
![image](https://user-images.githubusercontent.com/65999547/101757493-3aa59880-3afd-11eb-8b75-ebaa10c25e48.png)

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2011A
Scenario Label: SCPTest-mcard
Priority: High

Best Regards,
Priyanka

**Comment by sandeep-tds** [comment]
Hi @PriyankaShivakumar, 

As mentioned in the earlier in [this issue](https://github.com/SAPDocuments/Tutorials/issues/6327), we treat each tutorial independently and so provide screenshots that show the result of that tutorial. 

This allows the students to stay focussed and not be confused. 

Thus, can we please close this ticket? 

Warm Regards
Sandeep T D S

**Comment by PriyankaShivakumar** [comment]
Hi Sandeep,
Thanks for the info. I will close this ticket.
Best Regards,
Priyanka
