### ISSUE TITLE
Set Up SAP Cloud Platform Launchpad Service

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#6325]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html

Please specify the step you are referring to:
**In step 2.3** The statement "Click sap.default to select the SAP ID Service." needs to be changed to "Click Default identity provider to select the SAP ID Service." The screenshot also needs to be updated. As it might create confusion for the new user.

**Expected:**
![1-2](https://user-images.githubusercontent.com/69286515/101757549-498c4b00-3afd-11eb-9e67-897b237d132b.png)

**Actual:**
<img width="779" alt="1" src="https://user-images.githubusercontent.com/69286515/101757566-4ee99580-3afd-11eb-86db-c9a90b6290ce.png">

**Label:**
Landscape Labels - trail1,trail2,trail3
Sprint Label: SCPTest-2011A 
Scenario Label: SCPTest-psite
Priority: High

**Comment by LindsayBert** [comment]
Updated - will publish today.

Thanks
Lindsay

**Comment by thecodester** [comment]
@LindsayBert Is this published?
