### ISSUE TITLE
Add steps to re subscribe the card in Android

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6326]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html

Step 4: View card on your mobile device

Add steps to re subscribe the card in Android . It is mentioned for IOS but not for Android. Since re subscription is necessary if the card is not displayed, it is difficult to re subscribe the card in android if the steps are not mentioned.

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2011A
Scenario Label: SCPTest-mcard
Priority: High

Best Regards,
Priyanka

**Comment by sandeep-tds** [comment]
Hi @PriyankaShivakumar,

Thank you for your feedback. I will add the details on how a user can subscribe to a card. 

The changes will be available next week.

Warm Regards
Sandeep T D S

**Comment by sandeep-tds** [comment]
Hi @PriyankaShivakumar 

The updated tutorial has been released, can you please verify the changes and update the ticket? 

Thank you so much for your support.

Warm Regards
Sandeep T D S

**Comment by PriyankaShivakumar** [comment]
Hi @sandeep-tds 

Thanks for the update. 
I have verified the steps and its as expected. I will close the ticket.

Best Regards,
Priyanka
