### ISSUE TITLE
Mobile Cards Application: Screenshot has to be changed

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6327]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html

Step 4: View card on your mobile device

Booster welcome card is also present along with supplier card. Since the previous tutorial is mentioned as a prerequisite for this tutorial, From a customer perspective in order to avoid confusion, Screenshot has to be updated to the one given below.
![image](https://user-images.githubusercontent.com/65999547/101761349-07193d00-3b02-11eb-9566-ca01b76e9f13.png) 
![image](https://user-images.githubusercontent.com/65999547/101761374-1304ff00-3b02-11eb-8fad-565daa55e279.png)

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2011A
Scenario Label: SCPTest-mcard
Priority: High

Best Regards,
Priyanka

**Comment by sandeep-tds** [comment]
Hi @PriyankaShivakumar,

Thank you for raising this issue. 

You are correct, the tutorial points to another tutorial as a pre-requisite. However, in some cases, people may choose to complete only this tutorial. Correspondingly we show the result of this tutorial in our image. 

Thus, would it be ok if we close this ticket? 

Warm Regards
Sandeep T D S

**Comment by PriyankaShivakumar** [comment]
Hi Sandeep,
Thanks for the info. I will close this ticket.
Best Regards,
Priyanka
