### ISSUE TITLE
Create a Launchpad Site

### ISSUE THREAD

**Issue by AkankshaKullu** [SAPDocuments/Tutorials#6328]
Tutorial URL: https://developers.sap.com/tutorials/cp-portal-cloud-foundry-create-sitelaunchpad.html

Please specify the step you are referring to
In step 1.1 Observation: in the left side panel new tool has been added for settings. The screenshot can be updated.

Expected:
![2](https://user-images.githubusercontent.com/69286515/101761698-7abb4a00-3b02-11eb-8b34-c482358bf2cd.png)

Actual:
<img width="960" alt="2-2" src="https://user-images.githubusercontent.com/69286515/101761725-81e25800-3b02-11eb-9ede-ee6ebb18ff21.png">

Label:
Landscape Labels - trail1,trail2,trail3
Sprint Label: SCPTest-2011A
Scenario Label: SCPTest-psite
Priority: Low

**Comment by LindsayBert** [comment]
Updated

Thanks
Lindsay
