### ISSUE TITLE
Error Popup while using Build a micro app for SAP Mobile Cards booster.

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#6330]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-booster-starter.html

Step 2: Create contact card using Boosters

The following error popup is displayed for the booster-**Build a micro app for SAP Mobile Cards.**
This error is displayed when we try to create **more than 3 cards** with the same public ip address.
![image](https://user-images.githubusercontent.com/65999547/101762614-a854c300-3b03-11eb-8d69-9749be25cf98.png)

Also please add the link for the documentation mentioned in the error message.

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2011A
Scenario Label: SCPTest-mcard
Priority: High

Best Regards,
Priyanka

**Comment by sandeep-tds** [comment]
Hi @PriyankaShivakumar,

Thank you for raising the issue.

We have forwarded the error to the development team and will ensure that a solution is provided by the next release. 

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
@sandeep-tds Any updates?

**Comment by sandeep-tds** [comment]
Hi @PriyankaShivakumar

The issue has been addressed. Can you please re-test to confirm the same? 

Thank you so much for your support. 

@MichaelCzcz  thank you for the reminder.

**Comment by PriyankaShivakumar** [comment]
Hi @sandeep-tds 
The issue is fixed now. Thanks.
Best Regards,
Priyanka

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
