### ISSUE TITLE
Add a User Task to Your Workflow and Deploy

### ISSUE THREAD

**Issue by hvolk** [SAPDocuments/Tutorials#6331]
Tutorial URL: https://developers.sap.com/tutorials/cp-workflow-3-add-usertask-cf.html

In step 2.4, I read:
"These expressions refer to the attributes in the JSON file that we have created in the previous step."

However, I don't see any JSON file in the previous step. Can you please advice.

**Comment by thecodester** [comment]
@AstridHerbst Can you respond?

**Comment by AstridHerbst** [comment]
Hi,

Thanks for your feedback. Please excuse the confusion. This sentence indeed makes no sense. The expressions refer to the workflow context. I will update the tutorial.
Thank you!
Best regards, Astrid

**Comment by MichaelCzcz** [comment]
@AstridHerbst Has the tutorial been updated?

**Comment by AstridHerbst** [comment]
Yes.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
