### ISSUE TITLE
Step not clear - Fiori App ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6332]
Hello,

Scenario URL: https://developers.sap.com/tutorials/abap-environment-data-model.html

Step 1.5 & 1.6:
"Define root view for ZI_TRAVEL_M_XXX and database table as source" & "Your result should look like this. Replace your code with following" ->
Step is confusing: First we are asking define root view.. but not asking to write anything in the code, and then next step first we are saying your result should look like this and asking to replace the code!.. where actually we need to replace the code only.

Please update the tutorial.
SAME FOR STEP 2.5 & 2.6:
Steps are not clear. Just mention replace your code with following would do.

Labels to be added:
Sprint Label: SCPTest-2011A
Landscape label: trail1, trail2
Scenario label: SCPTest-fabap
Prio: High-prio

Thanks,
Shubham

**Comment by mervey45** [comment]
Hi @i353590 ,

I created following pull request: #6347 for this issue.
@MichaelCzcz  we can close this ticket.

Best regards,
Merve
