### ISSUE TITLE
Edit Step name to PUBLISH instead of ACTIVATE - Fiori App ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6333]
Hello,

Scenario URL: https://developers.sap.com/tutorials/abap-environment-data-model.html

step 4.4: Activate your service binding.
change step and screenshot:
now we have to PUBLISH, not activate.

Please refer to screenshot:
![image](https://user-images.githubusercontent.com/66831161/101823319-96e5d800-3b50-11eb-9287-3215153a74fb.png)

Labels to be added:
Sprint Label: SCPTest-2011A
Landscape label: trail1, trail2
Scenario label: SCPTest-fabap
Prio: low-prio

Thanks,
Shubham

**Comment by mervey45** [comment]
Hi @i353590 ,

I created following pull request: #6347 for this issue.
@MichaelCzcz  we can close this ticket.

Best regards,
Merve
