### ISSUE TITLE
Step not clear - Fiori App ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6334]
Hello,

Scenario URL: https://developers.sap.com/tutorials/abap-environment-behavior-action.html

Similar to issue:https://github.com/SAPDocuments/Tutorials/issues/6332
Step 1.1 & 1.2:
Step 1.1 doesn't make sense as we are replacing the entire code in 1.2 & also first we are saying result should look like this and then replacing the code which doesn't seem correct.

Please update the tutorial.

Labels to be added:
Sprint Label: SCPTest-2011A
Landscape label: trail1, trail2
Scenario label: SCPTest-fabap
Prio: high-prio

Thanks,
Shubham

**Comment by mervey45** [comment]
Hi @i353590 ,

I created following pull request: #6347 for this issue.
@MichaelCzcz  we can close this ticket.

Best regards,
Merve
