### ISSUE TITLE
Update trust Config. SAP ID name- Fiori app ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6335]
Hello,

Scenario URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html

Step 1.6: Select sap.default.
Now the default name is "default Identity provider"
Please update step and screenshot.

Screenshot:
![image](https://user-images.githubusercontent.com/66831161/101824106-c0ebca00-3b51-11eb-945a-ab02a3dc6ea7.png)

Labels to be added:
Sprint Label: SCPTest-2011A
Landscape label: trail1, trail2
Scenario label: SCPTest-fabap
Prio: low-prio

Thanks,
Shubham

**Comment by mervey45** [comment]
Hi @i353590 ,

I created following pull request: #6347 for this issue.
@MichaelCzcz  we can close this ticket.

Best regards,
Merve
