### ISSUE TITLE
Change in step in create SAP fiori app - Fiori app ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6336]
Hello,

Scenario URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
Step 4.3: Select SAP Fiori elements application and click Next >.

Now we need to click on "Start" instead of "Next"
Please update screenshot and step description

Labels to be added:
Sprint Label: SCPTest-2011A
Landscape label: trail1, trail2
Scenario label: SCPTest-fabap
Prio: low-prio

Thanks,
Shubham

**Comment by mervey45** [comment]
Hi @i353590 ,

I created following pull request: #6347 for this issue.
@MichaelCzcz  we can close this ticket.

Best regards,
Merve
