### ISSUE TITLE
Update Document: System and ABAP env. options changed - Fiori app ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6337]
Hello,

Scenario URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
Step 4.5: Configure data source, system and service

 System: New System -> NO more exist now. we need to select "abap-cloud-default_abap-trial (SCP)" , and ABAP environment we no more need to select. that option itself doesn't come now.

Please refer to the screenshot and update the tutorial as a user might feel blocked here:
![image](https://user-images.githubusercontent.com/66831161/101824869-d44b6500-3b52-11eb-80f9-bfb4878802a9.png)

Labels to be added:
Sprint Label: SCPTest-2011A
Landscape label: trail1, trail2
Scenario label: SCPTest-fabap
Prio: high-prio

Thanks,
Shubham

**Comment by mervey45** [comment]
Hi @i353590 ,

I created following pull request: #6347 for this issue.
@MichaelCzcz  we can close this ticket.

Best regards,
Merve
