### ISSUE TITLE
Click expose and open - Update comment - Fiori app ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6338]
Hello,

Scenario URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
Step 5.3: Click Open in New Tab.
Please mention: "expose and open" instead of "open in new tab" ( You can also check the screenshot provided is correct which says expose and open).
Also, ADD A STEP -  "please press enter to use default port" after clicking expose and open. 
![image](https://user-images.githubusercontent.com/66831161/101825351-8125e200-3b53-11eb-8017-3a4d15e5c0e8.png)

Labels to be added:
Sprint Label: SCPTest-2011A
Landscape label: trail1, trail2
Scenario label: SCPTest-fabap
Prio: low-prio

Thanks,
Shubham

**Comment by mervey45** [comment]
Hi @i353590 ,

I created following pull request: #6347 for this issue.
@MichaelCzcz  we can close this ticket.

Best regards,
Merve
