### ISSUE TITLE
Step missing - Navigate to Business app Studio - Fiori app ABAP

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6339]
Hello,

Scenario URL: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
Step 6.4: To add deploy config details enter npx fiori add deploy-config.
-> before this step, add step to go back to SAP Business App studio as we are navigating to eclipse in last step.
also, can we make statement more meaningful saying execute "npx fiori add deploy-config" from terminal?

Labels to be added:
Sprint Label: SCPTest-2011A
Landscape label: trail1, trail2
Scenario label: SCPTest-fabap
Prio: low-prio

Thanks,
Shubham

**Comment by mervey45** [comment]
Hi @i353590 ,

we have an incident on this: https://github.wdf.sap.corp/ux-engineering/tools-suite/issues/10358.
Unfortunately we have to wait, until is is solved.

Thank you for your understanding.

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @i353590 ,

I created following pull request: #6347 for this issue.
@MichaelCzcz  we can close this ticket.

Best regards,
Merve
