### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by rvencu** [SAPDocuments/Tutorials#6341]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html

Please specify the step you are referring to: Step 13: (Optional) Update Your Docker Image

Trying to run HXECheckUpdate_linux.bin which I only found in /usr/sap/HXE/home/bin/ seems to fail because no JRE is found.

which: no java in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
which: no java in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
/usr/java/sapjvm_8_latest/jre/lib/amd64/server/libjvm.so: cannot open shared object file: No such file or directory
Cannot find 64-bit Java Runtime Environment (JRE) 8 or newer; or the installed JRE is not 64-bit.

Hint: If you have JRE installed in non-default location, set JAVA_HOME environment variable to it.

Maybe this step needs to be clarified a little more.

**Comment by thecodester** [comment]
@JCurrie27 Can you respond?

**Comment by JCurrie27** [comment]
Hi rvencu: Did you see this similar post in the HANA express Q&A? [SAP HANA 2.0 Express Edition - Failed to run Windows Download Manager ](https://answers.sap.com/questions/13006163/sap-hana-20-express-edition-failed-to-run-windows.html). The user is running Windows, but the thread might contain some solutions for you.

Many thanks if you could log your issue on the HANA Express community Q&A page to take advantage of the community support model. The Q&A page receives much more traffic, and other users may be able to provide answers immediately.

To log your questions on the Q&A page:

- Go to [https://answers.sap.com/questions/ask.html](https://answers.sap.com/questions/ask.html)
- Add a **Title**. Enter your GitHub question in the **Fill in the details**... form.
- In **Select Primary Tag**, search for "express". Select **SAP HANA, express edition**.
- Click **Submit your Question**.

**Comment by rvencu** [comment]
Thanks for the heads up... I'll go to the QA page then

**Comment by rvencu** [comment]
https://answers.sap.com/questions/13218224/installing-sap-hana-express-edition-with-docker-st.html

**Comment by draschke** [comment]
The issue is until now not solved for SPS 04 (store/saplabs/hanaexpressxsa 2.00.045.00.20200121.1)
