### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by sagnik9393** [SAPDocuments/Tutorials#6342]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html

The tutorial should also try to include the details of  GMAIL 2 Step Verification to sync up the sender properties.
The password in Security Material should not be Google Email Password ( in case Google SMTP ) is used. But it should refer to the  Gmail Auto Generated Password .

Thanks

**Comment by gauthamkrishna-sap** [comment]
Hello,
We have an exercise in the new TechEd session that you can refer to in the short term: https://github.com/SAP-samples/teched2020-DEV165/blob/main/exercises/Ex-1.Setting_Up_Connectivty_to_Non_SAP_Systems/Ex.1.4.Set_Up_Gmail_Connectivity.md

We will also update this tutorial ASAP.

Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
@gauthamkrishna-sap Has the tutorial been updated?

**Comment by gauthamkrishna-sap** [comment]
Hello,
Thank you for your feedback. We are in the process of updating this tutorial and waiting for a minor fix. We will release a new version shortly and also update you when released. Apologies for the inconvenience caused and thank you for your patience. 
Thanks and Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello,
Due to some issues, it is taking longer to update the tutorials. In the meantime, I can offer this tutorial as an alternative to get hands on experience of Integration Suite: https://github.com/SAP-samples/teched2020-DEV165
Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello,
This tutorial has been deprecated. We will replace it with an updated tutorial in the coming weeks. Please watch out for "Integration Suite tutorials" in the SAP Tutorial Navigator for new updates. 
Thank you.
