### ISSUE TITLE
Update and Maintain Your SAP Profile at people.sap.com

### ISSUE THREAD

**Issue by muratalcal** [SAPDocuments/Tutorials#6343]
Tutorial URL: https://developers.sap.com/tutorials/community-profile.html

Please specify the step you are referring to: "Step 1: Access your profile" does have different selections.
![image](https://user-images.githubusercontent.com/75835609/101889602-a563dc00-3bb0-11eb-84f8-678b48feba57.png)

**Comment by lenastodal** [comment]
Hi @muratalcal - Thanks for pointing that out. The tutorial will be updated shortly. I will keep you posted. 
Cheers, 
Lena

**Comment by lenastodal** [comment]
@muratalcal - the tutorial us updated, the issue should be solved. Thanks!
