### ISSUE TITLE
Create an Application for Producing Messages

### ISSUE THREAD

**Issue by IObert** [SAPDocuments/Tutorials#6344]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-nodejs-producing-app.html

Please specify the step you are referring to 1

The SAP npm registry is not needed anymore and actually causes some [confusion](https://answers.sap.com/questions/13205048/npm-install-of-sap-npm-registry-keeps-failing-on-e.html?childToView=13209134&answerPublished=true#answer-13209134). I'd suggest to [remove it](https://blogs.sap.com/2020/07/02/sap-npm-packages-now-on-npmjs.org/).

**Comment by pradeeppanda-sap** [comment]
Yes.. now its not more needed as the npm packages are now hosted here: https://www.npmjs.com/package/@sap/xb-msg-amqp-v100 

I will update the tutorial. Thanks for the message.

regards
Pradeep

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by IObert** [comment]
It seems that the tutorial is not yet upgraded. Please keep the issue open until the tutorial reflects the change.

**Comment by pradeeppanda-sap** [comment]
closing this as the tutorial has been updated.
Please let me know, should you think otherwise.

**Comment by thecodester** [comment]
@IObert ?

**Comment by IObert** [comment]
Thanks. I still see a reference in the "Prerequisites" section here. Is this maybe a issue with the build system?

**Comment by thecodester** [comment]
@IObert Is this a question to me about the tutorial updating? If so, the PR had no change in prerequisites, and it was merged 9 days ago, and the tutorial seems to have been updated.

**Comment by pradeeppanda-sap** [comment]
Hi Daniel,
 It was to me. I need to make some other minor changes as pointed by @IObert  here.
  I will do and will commit again.
 Please keep this issue OPEN.

regards
Pradeep

**Comment by thecodester** [comment]
@pradeeppanda-sap Any update on this update?

**Comment by pradeeppanda-sap** [comment]
it has been fixed...sorry i forgot the respond.

**Comment by thecodester** [comment]
@IObert I am closing but let us know if there is still something to do. Thanks for the feedback :-)
