### ISSUE TITLE
Create an Application for Receiving Messages

### ISSUE THREAD

**Issue by IObert** [SAPDocuments/Tutorials#6345]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-nodejs-receiving-app.html

Please specify the step you are referring to 1

The SAP npm registry is not needed anymore and actually causes some [confusion](https://answers.sap.com/questions/13205048/npm-install-of-sap-npm-registry-keeps-failing-on-e.html?childToView=13209134&answerPublished=true#answer-13209134). I'd suggest to [remove it](https://blogs.sap.com/2020/07/02/sap-npm-packages-now-on-npmjs.org/).

**Comment by pradeeppanda-sap** [comment]
Yes.. now its not more needed as the npm packages are now hosted here: https://www.npmjs.com/package/@sap/xb-msg-amqp-v100 

I will update the tutorial. Thanks for the message.

regards
Pradeep

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by IObert** [comment]
It seems that the tutorial is not yet upgraded. Please keep the issue open until the tutorial reflects the change.

**Comment by pradeeppanda-sap** [comment]
we can close this issue as the fix has been provided. Please look into the tutorial and reopen it if you think otherwise.

**Comment by thecodester** [comment]
@IObert ?

**Comment by IObert** [comment]
Many thanks, LGTM
