### ISSUE TITLE
Set Up Business Rules for Determining Equipment

### ISSUE THREAD

**Issue by Omrocks** [SAPDocuments/Tutorials#6346]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-businessrules.html

Please specify the step you are referring to
Step-3 While saving records I am getting error as below

"Bad Gateway Error"

![image](https://user-images.githubusercontent.com/19869495/101893775-38aa0b00-3bcb-11eb-8c57-dce0e3c7e343.png)

**Comment by ArchanaShukla** [comment]
@Omrocks - As mentioned in the previous issue as well, Bad Gateway issue occurs if you have user name or password wrongly configured in the destination. If your user has 2FA enabled in your account, then you need to use password+passcode in the destination or else use a user without 2FA.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
