### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by juanpablotoledo** [SAPDocuments/Tutorials#6348]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html

Please specify the step you are referring to
Hi I am in Tutorial 3, Step 5: Execute API and I am getting this error:

LastError           = com.sap.it.rt.adapter.http.api.exception.HttpResponseException: An internal server error occured: Header/Property value not found for the parameter ${header.productIdentifier}.
The MPL ID for the failed message is : AF_TpTE1W-Ocqh-xARI98stREtfB

I attached the error I got.

Thank you.

[MessageLog-Cloud-Integration-Trial-Experience.txt](https://github.com/SAPDocuments/Tutorials/files/5680631/MessageLog-Cloud-Integration-Trial-Experience.txt)

**Comment by Vikramkulkarni01** [comment]
Hi @juanpablotoledo, 

It seems like a temporary error. 

Could you please redeploy the integration flow and execute the API. 

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
