### ISSUE TITLE
Build Your First FAQ Chatbot

### ISSUE THREAD

**Issue by SaravanaKumarVelliyangiri** [SAPDocuments/Tutorials#6349]
Tutorial URL: https://developers.sap.com/tutorials/conversational-ai-faq-chatbot-beginner.html

Please specify the step you are referring to Step 7. Test feature is not working and result in Cannot make request error

**Comment by thecodester** [comment]
I just did the entire tutorial and it works OK.

![image](https://user-images.githubusercontent.com/11659786/102710165-2578f880-42b9-11eb-8e62-2c1f98269ae8.png)

Can you provide more information? Perhaps click on Debug in the Chat Preview or copy and past the JSON for more information.

**Comment by SaravanaKumarVelliyangiri** [comment]
Hi,

I'm getting the below error.

![image](https://user-images.githubusercontent.com/42970328/102852212-baa7f880-4443-11eb-9de1-23af747f3558.png)

Thanks and Regards,
Saravana Kumar V

**Comment by thecodester** [comment]
What action did you take immediately before getting this error? Just opening the test panel?

**Comment by SaravanaKumarVelliyangiri** [comment]
I just typed and sent Hi message

**Comment by thecodester** [comment]
If the bot works, feel free to close the issue

**Comment by SaravanaKumarVelliyangiri** [comment]
Thank you so much for the immediate help !
