### ISSUE TITLE
Set Up Business Rules for Determining Equipment

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#6350]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-2-businessrules.html

Please specify the step you are referring to 2.5&3.2: Importing the project.

The Connection to "BUSINESSRULES_APIHUB" established. Response returned: "200: OK" but when importing the Project I get
"Bad Gateway Error."

There seem to be missing context instructions to provide either:
/sap/opu/odata/sap/RULE_INBOUND_SRV or 
/rules-service/odata/rule_inbound_srv/ or
some other value 

Can someone help?

**Comment by ArchanaShukla** [comment]
@greg2git - You do not have to use any of those options. The screenshot clearly shows that. Bad gateway issue occurs if you have user name or password wrongly configured in the destination. If your user has 2FA enabled in your account, then you need to use password+passcode in the destination or else use a user without 2FA.

**Comment by greg2git** [comment]
not sure if i follow, if the destination does work for the combination of the user+password:

_Connection to "BUSINESSRULES_APIHUB" established. Response returned: "200: OK"_

 there is an additional verification step somewhere outside of the current tutorial to confirm the passcode for 2FA?

**Comment by ArchanaShukla** [comment]
Hello @greg2git ,
This is a standard way to access 2FA based user password. It is difficult to include all the different ways to configure the destination password. The password entered by the user should be based on the kind of security protocols activated for it. A note is therefore included to ensure you are cautioned. Hope that helps! 

@thecodester - please close the issue.
