### ISSUE TITLE
Store sensor data in SAP Vora in SAP Data Hub, developer edition

### ISSUE THREAD

**Issue by DuoBelt** [SAPDocuments/Tutorials#6351]
Tutorial URL: https://developers.sap.com/tutorials/datahub-pipelines-v2-storeinvora.html

Please specify the step you are referring to

> Step 2: Execute the data pipeline and check result in SAP Vora
> _Attention: If no data is stored in SAP Vora, you can add a Terminal operator to the pipeline and connect it with the result out port of the SAP Vora Loader operator. If you see an error message like could not handle api call, failure reason : execution of scheduler plan failed, you might have incorrectly connected the Kafka Consumer2 operator and the ToString Converter operator. Please review the previous tutorial._
> 
> 
> __Please note you need to use the same password for the vora user that you provided when you setup your docker container for datahub. Click on Save. Scroll down in the configuration list and select HDFS as Storage Service (1). Then click on the text box for HDFS Connection (2). Now maintain the following configuration :__

Hello 
I have little problem with  (SAP Vora Loader )
SAP Vora Loader : ->  Status dead

I don't use a password for vora user, after the default installation SAP Data Hub, could this be a problem?
VORA.SENSORDATA has been created but no data is available

Message
.SAP Vora Loader: failed to execute SQL: could not handle api call, failure reason : execution of scheduler plan failed: found error: :-1, CException, Code: 10021 : Runtime category : an std::exception wrapped. read info for path '/tmp/hdfsManager/test_1.txt' failed with message 'No such file or directory'.Next level: read info for path '/tmp/hdfsManager/test_1.txt' failed with message 'No such file or directory'. for node id 27

thx for suport 
Mariusz

**Comment by thecodester** [comment]
@dimvor  Also review your tutorials and republish the ones that do not have your name on them. Add your name in the metadata section.  Thanks.

**Comment by dimvor** [comment]
@DuoBelt What did you choose as a root path when you defined the HDFS connection? Please note that tutorial is being deprecated and removed soon.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
