### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by FarozanFarman** [SAPDocuments/Tutorials#6353]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
Step 3. Define the API:
12.In the editable section on the right part of the screen, change the content as shown in the following.

Change Payload to productIdentifier and add the following row as shown in the following screenshot: example: “HT-2000”:

Screenshot needs to be changed as there should not be any double quotes in the code for **HT-2000**. If double quotes are added as per screentshot, we do not get the data later.
Expected Result:
![image](https://user-images.githubusercontent.com/71028764/102040382-aedc8680-3df2-11eb-8032-73fa99071bea.png)

Actual Result:
![image](https://user-images.githubusercontent.com/71028764/102040415-bef46600-3df2-11eb-88cf-cc20ba88e4e1.png)

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2011A
Scenario Label: SCPTest-cloudin
Priority: Medium

Best Regards,
Farozan

**Comment by Vikramkulkarni01** [comment]
Hi @FarozanFarman , 

Thanks for the feedback. I will get this screenshot updated within the next release cycle. 

Regards, 
Vikram Kulkarni

**Comment by thecodester** [comment]
@Vikramkulkarni01 When is next testing cycle? This is Hi-Prio

**Comment by Karunaharan** [comment]
Hi @FarozanFarman
The screenshot is updated. Will send a pull request today to merge the changes.

@thecodester - please reassign this issue to me. Going forward, I will handle the tutorials for CPI/Integration suite.

**Comment by thecodester** [comment]
https://github.com/SAPDocuments/Tutorials/pull/6388
