### ISSUE TITLE
Set Up Process Visibility to Track Employee Onboarding Workflow

### ISSUE THREAD

**Issue by FarozanFarman** [SAPDocuments/Tutorials#6354]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-4-visibility.html

Step 1. Create a business scenario:
3. Enter Name as Employee Onboarding, any Description of your choice, and click Create.:
Screenshot needs to be changed:
Expected result:
![image](https://user-images.githubusercontent.com/71028764/102041059-75a51600-3df4-11eb-82c7-d7a551051da6.png)
Actual Result:
![image](https://user-images.githubusercontent.com/71028764/102041091-82c20500-3df4-11eb-85f1-d3bd4366ecba.png)

Labels:
Landscape: trail1, trail2, trail3
Label: SCPTest-2011A
Scenario Label: SCPTest-eboard
Priority: Low

Best Regards,
Farozan

**Comment by ArchanaShukla** [comment]
yeah this was a recent new change in the UI, will update the tutorial by Jan-end 2021.

**Comment by MichaelCzcz** [comment]
@ArchanaShukla Has the tutorial been updated?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
