### ISSUE TITLE
Automate and Extend Employee Onboarding

### ISSUE THREAD

**Issue by Omrocks** [SAPDocuments/Tutorials#6355]
Mission URL: https://developers.sap.com/mission.cp-starter-ibpm-employeeonboarding.html

I am getting error "Bad Gatway Error"...no one is providing help ??

**Comment by greg2git** [comment]
no help, but a confirmation that i'm also getting the error.

**Comment by thecodester** [comment]
@Omrocks I have assigned the issue.

- I assume it will help to provide aditional information -- what steps were taken before the error occurred.
- What do you mean "no one is providing help"? You wrote that at the very instant you opened the ticket :-)

**Comment by ArchanaShukla** [comment]
Hello @Omrocks,
This issue occurs if you have user name or password wrong in the destination. If your user has 2FA enabled in your account, then you need to use password+passcode in the destination or else use a user without 2FA.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
