### ISSUE TITLE
Build a Business Application Using CAP for Node.js

### ISSUE THREAD

**Issue by mmartinezfernandez** [SAPDocuments/Tutorials#6359]
Mission URL: https://developers.sap.com/mission.cp-starter-extensions-cap.html

Great tutorial!!

**Comment by iwonahahn** [comment]
Hi,

Thank you for this feedback. You can provide your feedback at the end of each CAP tutorial, cause here is the channel for channel 😅 :

![image](https://user-images.githubusercontent.com/22098308/102084776-f294b780-3e15-11eb-9b95-e9245c4ff646.png)

If you want to learn more, please visit our [community](https://community.sap.com/topics/cloud-application-programming) or try out the [learning journey](https://help.sap.com/doc/221f8f84afef43d29ad37ef2af0c4adf/latest/en-US/972e35035f404685ba6bb54b03f7c167.html). Furthermore you can watch the passed TechEd session [What's New in CAP](https://events.rainfocus.com/widget/sap/sapteched2020/catalog/session/1602555751912001uqld).

Best regards,
Iwona

@thecodester we can close this here, cause it is not an issue 😀 .

**Comment by thecodester** [comment]
Yay! :-)
