### ISSUE TITLE
The reason why sap.app.id in manifest.json must be updated

### ISSUE THREAD

**Issue by Auggie9010** [SAPDocuments/Tutorials#6363]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html

Please specify the step you are referring to
Step 4: Get URL to access the application>4 Locate the sap.app id from the manifest.json file located ~

Could you possibly tell me **the reason why this step is required**, please?

Without changing `sap.app id` in `manifest.json`, the URL `<URL_from_application_overview_page>/<mynamespace><project_name>/index.html` works in browser.

Sincerely

**Comment by thecodester** [comment]
@raz-korn Can you respond?

**Comment by raz-korn** [comment]
@thecodester , @Auggie9010 - 
I apologize for the delayed response - I was on vacation last week and on vacation most of this week.
When I'm back, I'll go over the list of open issues and respond accordingly.

**Comment by Auggie9010** [comment]
@raz-korn 
Thank you for your message.
I'm looking forward to receiving your reply.

**Comment by raz-korn** [comment]
Hi @Auggie9010 ,

The reason for this step is that if in the Cockpit you click on the "Application Route" (in the "Application ... Overview" page), you'll get an empty (Not Found) page. There's a need to concatenate the app id, etc. as mentioned in step 4.

Regards - Raz

**Comment by Auggie9010** [comment]
@raz-korn 
Thank you for your reply!
I understood and let me close this issue.
