### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by danhenry00** [SAPDocuments/Tutorials#6364]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html

I was able to get this tutorial to work by following some additional steps:

1) configure GMail SMTP properly - https://blogs.sap.com/2020/01/15/cpi-gmail-smtp-integration/
2) User Plain User/Password instead of Encrypted.

Kindly suggest updating the tutorial so that others don't also have to figure it out and can focus on the content provided.

**Comment by danhenry00** [comment]
Also, how to assign the Role was not clear, but was able to get help.  The following could be helpful for the next person going through the tutorial.

Goto -> Security -> Roles on your tenant and look for the role it-rt-integration2 and you will see that it has the “MessagingSend” role template. That is the role template we want
Goto -> Security -> Role Collections and click on the “+” to create a new role template
I named my message.sender but you can name it whatever you want
Click in to the role collection you created and hit “Edit”
Search for the application identifier “it-rt-integration2!xxxxx” and add that to the Roles
Then search for your user and add your user
See screenshot below for what it should look like when complete

**Comment by thecodester** [comment]
@gauthamkrishna-sap Please also put your name on the tutorials that you inherited from Meghna. Thanks.

**Comment by MichaelCzcz** [comment]
@gauthamkrishna-sap any updates?

**Comment by gauthamkrishna-sap** [comment]
Hello,
Thank you for your feedback. We are in the process of updating this tutorial and waiting for a minor fix. We will release a new version shortly and also update you when released. Apologies for the inconvenience caused and thank you for your patience. 
Thanks and Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello, 
Due to some issues, it is taking longer to update the tutorials. In the meantime, I can offer this tutorial as an alternative to get hands on experience of Integration Suite: https://github.com/SAP-samples/teched2020-DEV165
Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello,
We are still working on updates for this series. In the meantime, this tutorial from TechEd is a great alternative to continue your integration learning journey: https://github.com/SAP-samples/teched2020-DEV165
Best Regards,
Gautham

**Comment by gauthamkrishna-sap** [comment]
Hello,
This tutorial has been deprecated. We will replace it with an updated tutorial in the coming weeks. Please watch out for "Integration Suite tutorials" in the SAP Tutorial Navigator for new updates. 
Thank you.
