### ISSUE TITLE
Design and Deploy Your First Integration Flow

### ISSUE THREAD

**Issue by danhenry00** [SAPDocuments/Tutorials#6365]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Kindly suggest adding a step to test and validate the deployed service to complete the development.

I found that posting the following Body to the endpoint was sufficient to accomplish it.

{
	"productIdentifier": "HT-1080"
}

**Comment by Vikramkulkarni01** [comment]
Hi @danhenry00 , 

Thanks for reaching out to SAP. 

With reference to your concern, you have deployed an integration flow. 

To test the same, you need to proceed with the next set of tutorial i.e., https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html 

Please complete the whole mission to get a better trial experience. 

Regards, 
Vikram

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
