### ISSUE TITLE
Tour the SAP Community

### ISSUE THREAD

**Issue by tglobalops** [SAPDocuments/Tutorials#6367]
Tutorial URL: https://developers.sap.com/tutorials/community-start.html

Please specify the step you are referring to

Hi Team,
Pls help...
Step 10 in this tutorial has a bug... despite selecting the correct answers & following all the instructions it wont go ahead, here's attaching a screenshot for your refernce.

Regards, 
Taher +918850518284 
![image](https://user-images.githubusercontent.com/59091617/102240784-3f63b580-3f1e-11eb-86ae-ac5954b37e24.png)

**Comment by thecodester** [comment]
This is not a technical issue, since the answers provided are different than what is defined for this question. I'll let @lenastodal  discuss the actual qustion

**Comment by lenastodal** [comment]
Hi @tglobalops - "Standalone videos are not recommended" shouldn't be selected as it's not correct. 
Then the step should work and be validated. 
Thanks and best, 
Lena
