### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by juanse-bcn** [SAPDocuments/Tutorials#6393]
Hi. Karunaharan V

Happy New Year !!!

I have an error when I test the API.

{
  "fault": {
    "faultstring": "**Execution of ServiceCallout getoauthtoken failed.** Reason: ResponseCode 400 is treated as error",
    "detail": {
      "errorcode": "steps.servicecallout.ExecutionFailed"
    }
  }
}

Do you know what is it ?

**Comment by Karunaharan** [comment]
Hi @juanse-bcn 
Happy New Year to you and your beloved ones.

I just got back after vacation.
I'm looking into your issue, will get back to you as soon as possible.

**Comment by juanse-bcn** [comment]
Hi, Karunaharan, good morning

do you have any idea ?

**Comment by Karunaharan** [comment]
Hi @juanse-bcn,
From our initial analysis, it looks like something went wrong in Step 4: Assign policy template …
in https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html 
We will get back as soon as possible.

**Comment by Karunaharan** [comment]
Hi @juanse-bcn 
Looking at the error code,  the most likely culprit would be that either the oauth target URL is incorrect or the payload while copy-pasting has gone corrupt. To identify the issue it would be great if you can share the snippet of the getoauthtoken so that it can be analyzed further.

**Comment by juanse-bcn** [comment]
Hi Karunaharan.

I found the problem. In getoauthtoken the url was wrong.

I like this error because help you be more careful. :)

**Comment by Karunaharan** [comment]
@thecodester - please close the issue.

**Comment by juanse-bcn** [comment]
I found the problem. In getoauthtoken the url was wrong.
