### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by PaulLwrs** [SAPDocuments/Tutorials#6396]
![image](https://user-images.githubusercontent.com/75022508/103761090-6772a000-5016-11eb-96ba-65db4ab6f020.png)
I am trying to add capability 'Cloud Integration' to the Integration Suite. The status remains in progress and progress is 83%.

I tried a couple of times without success. What can I do?

**Comment by Vikramkulkarni01** [comment]
Hi @PaulLwrs , 

Thanks for reaching out to SAP. 

With reference to your concern, could you please check now? Ideally tenant provisioning might take sometime, not more than 20 mins. 
If the same issue persisting, try creating new sub account or delete the existing one and recreate it to check the same. 

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. This channel is for problems with tutorials only, so I am closing the issue. 
If you you are experiencing product related issues, please open a bug ticket.
