### ISSUE TITLE
Use Default plan for Enterprise Messaging Service in trial

### ISSUE THREAD

**Issue by MartinPankraz** [SAPDocuments/Tutorials#6408]
Dear Tutorials team,

I am trying to follow the tutorial on the SAP EMS here: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html with my SCP trial account. 

I verified successfully that the mentioned JSON payloads work in default plan outside of trial. When using the dev plan I need to revert to the legacy management UI and JSON payload as described [here](https://help.sap.com/viewer/bf82e6b26456494cbdd197057c09979f/Cloud/en-US/6f694dcc608c41d390218848873dc6f3.html). 

However, in my trial account I am not able to choose the default plan during provisioning. It shows only Dev despite explicitly assigning the standard (subscription) plan as well.

Could you please verify? Otherwise all current EMS tutorials won't work with trial accounts. And if so it would be great to highlight that on the docs for the community.

KR
Martin

**Comment by pradeeppanda-sap** [comment]
Hi Martin,
  Please note that in Trial landscape default plan is not available. 

regards
Pradeep

**Comment by MartinPankraz** [comment]
Hi Pradeep,

so you are telling me that in SCP trial I cannot work with the Enterprise Messaging Service at all? 

KR
Martin

**Comment by pradeeppanda-sap** [comment]
Hi Martin,
 Yes,  at present the default version is available in factory environment.
regards
Pradeep

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by MartinPankraz** [comment]
@pradeeppanda-sap : what does factory environment mean? Are you talking about anything non-trial?

KR
Martin

**Comment by pradeeppanda-sap** [comment]
hi Martin,
  Yes. it is the productive environment. 
And that's why if you notice, the topic has
_Requires Customer/Partner License_

regards
Pradeep

**Comment by MartinPankraz** [comment]
Thanks for clarifiying. Too bad that there are tutorials, which don't support trial accounts.
