### ISSUE TITLE
Feedback on Tutorial: SAP HANA XS Classic, Develop your first SAP HANA XSC Application

### ISSUE THREAD

**Issue by RFHorn** [SAPDocuments/Tutorials#641]
Hi,
I don't have Databases/Schemas options to start my application.  Did I do something wrong when accessing the cockpit?
I found the Database / Schema - it was under another system - Europe (trial), not the U.S. I don't know if this will present a problem, but I'm going to continue to use the Europe one for now.

**Comment by ccmehil** [comment]
Are you trying under HANA MDC?
