### ISSUE TITLE
Feedback on Tutorial: SAP HANA XS Classic, Develop your first SAP HANA XSC Application

### ISSUE THREAD

**Issue by RFHorn** [SAPDocuments/Tutorials#642]
Going into the SAP HANA cockpit, a logon page appears asking for a userid and password.  Any clues on what to enter?

**Comment by ccmehil** [comment]
If you are using the SAP Developer Edition this should be listed on the landing page of the system.

**Comment by ccmehil** [comment]
If you are using HCP then you have to create your database user which is shown in the tutorial.
