### ISSUE TITLE
Feedback on Tutorial: End-to-End Weather App Scenario Part 10

### ISSUE THREAD

**Issue by ps2cheung** [SAPDocuments/Tutorials#643]
Are we missing a step to configure the security?
Once I deployed the app and test it , I got not response back.

**Comment by jonathanbaker7** [comment]
I've left this note for the authors, and I'll get back to you as soon as they reply...

**Comment by ps2cheung** [comment]
No need anymore,  it is working now

**Comment by jonathanbaker7** [comment]
OK, thank you!
