### ISSUE TITLE
Deploy First SAPUI5 App to Cloud Foundry

### ISSUE THREAD

**Issue by Naresh1243** [SAPDocuments/Tutorials#6470]
Dear Team,

11:47:35 AM (HTML5 application runner) Starting module "/YN_PO_PROJ1/YN_PO_MOD1".
11:47:50 AM (HTML5 application runner) html5_runner_log_cf_push_failure
11:47:50 AM (HTML5 application runner) Could not create the 'YNPOPROJ1-portalresourcesYNPOPROJ1yvpmhVlU+NmLOesg' instance of the 'portal' service type for the 'portal_resources_YN_PO_PROJ1' resource. Service portal does not exist
11:47:50 AM (HTML5 application runner) Cannot read property 'query' of undefined

I'm facing the issue above error , when i ran the HTML5 as SAP Fiori Launchpad. I have done the following activities.

Increased disk-quota to 512M
Parameters:
Disk-quota: 512M
Memory: 512M

Deleted existing instances.
Instances
![image](https://user-images.githubusercontent.com/64578067/106912449-08916b00-6729-11eb-8033-e43d652bab55.png)

Cloud foundry space
cloud_foundry
![image](https://user-images.githubusercontent.com/64578067/106912504-18a94a80-6729-11eb-99f0-026f46b07a8a.png)

Kindly help me with this.

Regards,
Naresh

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html
