### ISSUE TITLE
Not Able to Deploy UI5 Application to Cloud Foundry

### ISSUE THREAD

**Issue by Partha8824** [SAPDocuments/Tutorials#6492]
Hi Experts ,

I have build a list report application and trying to Deploy it to Cloud Foundry. But While trying to deploy it is throwing me the following error:

**Service operation failed: Controller operation failed: 404 Updating service "portal_resources_ZAssignment" failed: Not Found: Error creating service "portal_resources_ZAssignment" _from offering "portal" and plan "standard":_ Service plan standard not found."**

I know that we don't have Portal Subscription in  SAP BTP trail but still I am wondering why error is coming due to that Portal thing. I have subscribed for Launchpad Subscription as well. But still I am not able to deploy my Application. So can you suggest how to overcome this Portal error and deploy my application.

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html
