### ISSUE TITLE
Custom entity - Query class - Differentiate for line item or identification

### ISSUE THREAD

**Issue by mbokkalapalli** [SAPDocuments/Tutorials#6558]
@julieplummer20 - I am trying to achieve clean erp by leveraging abap environment to build extension. As a baseline, i have used the custom entity samples created by you. However I am facing challenges and questions:
1) When custom entity is implemented with query class( QC1) and behavior(BC1) is added:  QC1 is called for over view ( i.e. table display) and also when navigating to detail( identification reference). can we differentiate the call based on an parameter if it is for Overview or details in select method of IF_RAP_QUERY_PROVIDER.

2) As behavior is implemented and have the read method, when will this method be called?

3) Also I implemented association and it suggested to create read by association method? This is not called when i navigate to item details from header.

I searched for documentation around this but no help.

**Comment by julieplummer20** [comment]
Hi, This appears to be a general query, not specific to the tutorial. The tutorial is intended as an introduction. If you want more in-depth instruction, I recommend the relevant openSAP course: [Building Apps with the ABAP RESTful Application Programming Model](https://open.sap.com/courses/cp13), self-paced. 
BR Julie Plummer.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
