### ISSUE TITLE
https://developers.sap.com/tutorials/cap-service-deploy.html#951364b1-b93c-4c19-a290-203ecf51b421 

### ISSUE THREAD

**Issue by RJ1211** [SAPDocuments/Tutorials#6574]
Hi,

I am very new to this CAP and Node.JS codeline, as coming from ABAP background.
I have followed the steps all well, and it has worked.

But in Step 2. 4 - 
the command "cf login" does not work in VS Code command line.

I am getting the error in both CMD and Powershell. Attached the snapshot.  Can anyone help me with this.

Thanks,
Ravi J.

![Powershell error in VS code](https://user-images.githubusercontent.com/80312875/110742849-15601d80-8205-11eb-8360-43991a0f279a.png)
![CMD error in VS Code](https://user-images.githubusercontent.com/80312875/110742869-1e50ef00-8205-11eb-93eb-3604640072e3.png)

**Comment by MichaelCzcz** [comment]
@RJ1211 Please tell me how did you get to this repository?

**Comment by greg2git** [comment]
Hi Ravi,

did you try running your commands in a BAS terminal? it's not the same as VS Code but they should overlap to a large extent.

Cheers and thx,
greg

**Comment by RJ1211** [comment]
> @RJ1211 Please tell me how did you get to this repository?

I am actually in VS Code terminal. Please refer the snapshot. Is this what you meant. The terminal is there on the VS code tool.
Though I observed one thing that when i run this on the Windows command prompt - it asks for login and proceeds further.

Was this expected the same when running via VS code tool terminal as per step 2.4.

![VS code terminal](https://user-images.githubusercontent.com/80312875/110906393-e4055180-82d9-11eb-928c-438edb49e289.png)

**Comment by MichaelCzcz** [comment]
@RJ1211 I was asking, because all issues regarding tutorials should be raised via the link in the respective tutorial. The issues are handled in their own repository. We are planning to deactivate issues in this repository.

**Comment by RJ1211** [comment]
> @RJ1211 I was asking, because all issues regarding tutorials should be raised via the link in the respective tutorial. The issues are handled in their own repository. We are planning to deactivate issues in this repository.

Ah sorry got it. I will check where to post this issue, as even i am new to GITHUB as well. Thanks.

**Comment by MichaelCzcz** [comment]
@RJ1211 
![image](https://user-images.githubusercontent.com/57144076/111144741-c2c98d00-8587-11eb-9a73-16629966b9a0.png)

I'm closing this.
