### ISSUE TITLE
HANA Cloud Trial : Could not get service plan metadata

### ISSUE THREAD

**Issue by ChandraDutt** [SAPDocuments/Tutorials#6630]
Dear Team,

I have an SAP HANA Cloud instance on BTP trial, CF space. But now I am not able to manage SAP HANA Cloud instances after logging into SAP HANA Cloud Central. Kindly check this or help me understand if anything to be done from my side.

I had created HANA Cloud instance few months back and was able to deploy HDI containers. I have recently extended the trial period.

![image](https://user-images.githubusercontent.com/19844350/113383865-6f867580-93a2-11eb-9637-772b07345804.png)

Thanks in Advance.

Regards
Chandra Dutt

**Comment by thecodester** [comment]
Can you open this issue in the https://github.com/SAPDocuments/Issues/issues/ repo?
