### ISSUE TITLE
Branding issues in cp-sapcp-getstarted

### ISSUE THREAD

**Issue by ajmaradiaga** [SAPDocuments/Tutorials#6635]
I just completed the tutorial and there are a few branding issues in the tutorial:
1. **Step 3 - VALIDATE_1** mentions _sapcp CLI_ in the question.

2. [Image in **Step 6 - Usage**](https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/cp-sapcp-getstarted/usage.png) is a screenshot of the old cli tool.

3. The answer for the question part of **Step 7: Understand the command syntax: options** expects the _sapcp_ as the command line tool, not _btp_. 

_Current answer:_ 
```
sapcp list accounts/subaccount --help
sapcp --help list accounts/subaccount
```

**Comment by thecodester** [comment]
The place for issues is the Issues repo ... we can keep this here but next time open it there -- or use the Provide Feedback button from within the tutorial.

**Comment by annawenger20** [comment]
thanks @ajmaradiaga and sorry for the delay. I fixed the issues today and hope to get them through to production tomorrow. 
Cheers, Anna

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
