### ISSUE TITLE
Issue: Connecting to int.sap.eu2.hana.ondemand.come

### ISSUE THREAD

**Issue by Uri-Shapira** [SAPDocuments/Tutorials#6665]
I am trying to add a server in Eclipse (Spring Tool Suite), and am facing the following error:
 
"Cannot reach host [int.sap.eu2.hana.ondemand.com]. Check host name for typing errors and make sure your proxy and network settings are correct."

I saw that someone posted this issue in the past, but I cannot seem to solve it in any way. I am connected to the SAP network, and I am able through the Eclipse inner browser to access "int.sap.eu2.hana.ondemand.com". However, when trying through the New Server tab, this is what I see:

![image](https://user-images.githubusercontent.com/44334504/115522932-39e3f680-a295-11eb-9eb8-d4a087cb37bd.png)

please help!

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html
