### ISSUE TITLE
401 Unauthorized Error while testing Business Rules from API HUB

### ISSUE THREAD

**Issue by deepu-code** [SAPDocuments/Tutorials#6674]
- Response is Bank when I try to invoke the Rules Service from API HUB with response Code 401.

- Same response when trying from Postman. In Postman i am getting the Auth token, but when i use and call teh Rules, i get 401, unauthorized with blank Response. 
- Roles "RuleRepositorySuperUser" & "RuleRuntimeSuperUser" have been assigned to my ID with a custom Role Collection

**Response Headers**
date: Thu,  29 Apr 2021 10:09:28 GMT 
 server: SAP 
 content-length: 0 
 expires: 0 
 x-content-type-options: nosniff 
 x-xss-protection: 1; mode=block 
 x-frame-options: DENY 
 x-vcap-request-id: 69edb75f-c21c-4dbb-4248-9928b0835962 
 www-authenticate: Bearer 
 cache-control: no-cache,  no-store,  max-age=0,  must-revalidate 
 pragma: no-cache 
 strict-transport-security: max-age=31536000; includeSubDomains; preload;

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html

**Comment by deepu-code** [comment]
I got the issue while following the tutorial. Hoped someone would have ecountered

**Comment by MichaelCzcz** [comment]
@deepu-code If you are referring to an issue with a tutorial, please use the "Provide Feedback" function from within the tutorial and please don't remove the link to the tutorial from the Github issue. The github issue will then be posted in the correct channel. Thank you.
