### ISSUE TITLE
SAP Fiori App generator failed

### ISSUE THREAD

**Issue by balajimurugesan2016** [SAPDocuments/Tutorials#6711]
Hi,
Im getting the following error when I try to create a UI5 application via the application generator for Fiori

{"message":"@sap/fiori:app generator failed - env.on(error) spawn /usr/local/lib/node_modules/@sap/generator-fiori/generators/deployment-generator/deploy/bin/mta ENOENT","stack":"Error: env.on(error) spawn /usr/local/lib/node_modules/@sap/generator-fiori/generators/deployment-generator/deploy/bin/mta ENOENT\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)\n\tat onErrorNT (internal/child_process.js:465:16)\n\tat processTicksAndRejections (internal/process/task_queues.js:80:21)"}

Application wizard : v1.2.3

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html
