### ISSUE TITLE
Create Instance of SAP Cloud Platform Enterprise Messaging Service

### ISSUE THREAD

**Issue by csramanujan** [SAPDocuments/Tutorials#6737]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html

@pradeeppanda-sap

With the JSON below I am able to create the service instance with the dev plan in the trial account. However, when I open the Event mesh application I don't see the message clients. If I create the instance with the publish and subscribe rules there is an error. With the trial account there is no default plan. So how do we go about ?

{
"emname": "rc-instance",
"options": {
"management": true,
"messagingrest": true
}

<img width="802" alt="2021-06-04_12-55-44" src="https://user-images.githubusercontent.com/85331739/120891383-07644200-c626-11eb-82aa-55a7ee0477e9.png">

**Comment by thecodester** [comment]
@pradeeppanda-sap Can you update this issue?

**Comment by pradeeppanda-sap** [comment]
Hi,
The management dashboard is for "default" plan which is available in the productive environment.
As you have created the "dev" plan in the trial environment, you will not be able to see any client here.

The tutorial with "default" plan is supposed to be exercised in productive environment. 
![image](https://user-images.githubusercontent.com/51952722/126098977-ad5d119c-556b-45ca-8d8b-34ea25a94f84.png)

As of now, we do not have "default" plan in the trial environment. However, should you intend to try get a feel of event mesh and want to try with "dev" plan, let me know. I will provide you the steps to open the dashboard of "dev" plan. However, "default" plan is the latest and productive plan of Event Mesh.

regards
Pradeep

**Comment by csramanujan** [comment]
Hi Pradeep, I will close this ticket. You had already provided the solution for this earlier.
