### ISSUE TITLE
`test-tool` `global-checker` returns more issues than Atom plugin

### ISSUE THREAD

**Issue by miffels** [SAPDocuments/Tutorials#6758]
Hey,

I noticed that the checker exported from `global-checker.js` reports issues that are not otherwise reported in the Atom plugin, e.g. it will report HTML entities as spelling mistake:

Input:  `&#x2B;`
Output: `{reason: "x2B", kind: "spelling"}`

Seeing that this specific checker hasn't been updated in a while, as opposed to the others, I assume that it is no longer used. Are the other ones "up to date"? If so, which ones are currently used in Atom?

Thanks,
Michael

**Comment by miffels** [comment]
Hey,

Sorry for the late reply. Let me see if I can set up a "public" example of what I mean. I have shared with you the exact code I am seeing this with internally.

Cheers!

**Comment by miffels** [comment]
See https://github.com/miffels/catfood/blob/master/1dx-global-checker/index.js. Note that it assumes `Tutorials-Contribution` is cloned next to `catfood`.

```
Tutorials-Contribution % git log
commit cbe5b99c945b0e9b73b33774c46ca35c9e8a0655 (HEAD -> master, origin/master, origin/HEAD)
...
```
```
1dx-global-checker % node index.js   
{
  "results": [
    {
      "fileName": "btp-app-logging.md",
      "filePath": "../../Tutorials-Contribution/tutorials/btp-app-logging/btp-app-logging.md",
      "linksCount": 0,
      "fileNameCheckResult": null,
      "contentCheckResult": [],
      "tagsCheckResult": null,
      "validationsCheckResult": [],
      "syntaxCheckResult": [],
      "spellCheckResult": [
        {
          "line": "248",
          "reason": "x2B"
        }
      ],
      "linkCheckResult": []
    }
  ],
  "passed": false
}
```

**Comment by thecodester** [comment]
@wecreus Can you respond here? I'd like to remove unneeded code and use single code base for all checks.

**Comment by wecreus** [comment]
Closing the issue since this workflow is not intended for the plugin.
