### ISSUE TITLE
 An error occurred during JWT validiation. The JWT is expired. Therefore please check your local system clock.

### ISSUE THREAD

**Issue by rohan4888** [SAPDocuments/Tutorials#6764]
An error occurred during JWT validiation. The JWT is expired. Therefore please check your local system clock.
Getting Error

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html
