### ISSUE TITLE
SAP HANA XS Advanced - Node service throwing SAP HANA XS Advanced - Modules within Node.js SAP HANA applications 127.0.0.1:50126'

### ISSUE THREAD

**Issue by saket-sahi** [SAPDocuments/Tutorials#6792]
I have created a Node service in my XSA project. When i try to start the service i get the below mentioned error. I have checked my HANA cockpit as well. It is also throwing the same error. Service is not crashing in HANA cockpit. I just get below error.
6/23/21 4:21:43.041 PM [RTR] OUT   10.10.56.103 - - to hana-srvr-03.sidf.gov.sa:51003 "POST /b5d1ddb8-82af-4893-9d5c-5f73dd95a730/softReset HTTP/1.1" 200 sent 34 in 1077 by 00J-15594ada-006d-442e-9318-5d668f53b898
6/23/21 4:21:44.882 PM [APP/5-0] OUT   
6/23/21 4:21:44.882 PM [APP/5-0] OUT   > SIDMain-srv@1.0.0 start /hana/shared/HDC/xs/app_working/hana-srvr-03/executionroot/15594ada-006d-442e-9318-5d668f53b898/app
6/23/21 4:21:44.882 PM [APP/5-0] OUT   > node server.js
6/23/21 4:21:44.882 PM [APP/5-0] OUT   
6/23/21 4:21:44.984 PM [APP/5-0] OUT   /hana/shared/HDC/xs/app_working/hana-srvr-03/executionroot/15594ada-006d-442e-9318-5d668f53b898/app/
6/23/21 4:21:44.985 PM [APP/5-0] OUT   
6/23/21 4:22:11.530 PM [RTR] OUT   10.10.55.124 - - to hana-srvr-03.sidf.gov.sa:51003 "GET / HTTP/1.1" 200 sent 100 in 5 by 00J-15594ada-006d-442e-9318-5d668f53b898
6/23/21 4:22:11.530 PM [APP/5-0] SYS   #2.0#2021 06 23 16:22:11:530#+03:00#ERROR#/AppController/Dispatcher################PLAIN##[ 'Error occurred, Cannot proxy application requests...Error: connect ECONNREFUSED 127.0.0.1:50126' ]#
6/23/21 4:22:11.765 PM [APP/5-0] SYS   #2.0#2021 06 23 16:22:11:764#+03:00#ERROR#/AppController/Dispatcher################PLAIN##[ 'Error occurred, Cannot proxy application requests...Error: connect ECONNREFUSED 127.0.0.1:50126' ]#

**Comment by jung-thomas** [comment]
Which tutorial and step is this?

**Comment by saket-sahi** [comment]
https://developers.sap.com/tutorials/xsa-node-modules.html
Service is running. When i click on the service url, i get an error Please open SAP Web IDE console to view more information about the error. 

6/24/21 6:18:48.563 PM [API] OUT   Updated app 'EM1hjP3gJDjzAtur-SIDMain-srv' [Org 'SIDF_TERMINAL', Space 'DEV'] (state: STOPPED -> STARTED) with entity {'name':'EM1hjP3gJDjzAtur-SIDMain-srv', 'memory':512, 'instances':1, 'disk_quota':-1, 'space_guid':'18e57849-1f88-401a-8dbf-54fbf5a43ace', 'state':'STARTED', 'buildpack':'HOST:51052/git-bp/nodejsappcontroller-buildpack-project', 'health_check_type':'port', 'health_check_http_endpoint':'/', 'http_invocation_timeout':1000, 'start_priority':0}.
6/24/21 6:18:48.567 PM [API] OUT   Starting 1 instance(s) of app 'EM1hjP3gJDjzAtur-SIDMain-srv' [Org 'SIDF_TERMINAL', Space 'DEV']
6/24/21 6:18:48.620 PM [API] OUT   Set droplet with id 1 of app 'EM1hjP3gJDjzAtur-SIDMain-srv' [Org 'SIDF_TERMINAL', Space 'DEV'] created by buildpack 'https://hana-srvr-03.sidf.gov.sa:51052/git-bp/nodejsappcontroller-buildpack-project' as the running droplet.
6/24/21 6:18:48.721 PM [API] OUT   Starting instance [state STARTING, index 0] of droplet [id 1] of app 'EM1hjP3gJDjzAtur-SIDMain-srv' [Org 'SIDF_TERMINAL', Space 'DEV'] at [hana-srvr-03:50577].
6/24/21 6:19:00.209 PM [RTR] OUT   10.10.56.103 - - to HOST:51003 "GET /e6c13fc7-0a7f-4b08-b13d-4d3fd35ebe28/appStatus HTTP/1.1" 200 sent 153 in 1116 by 00J-678712c6-98b9-4e6b-b4c3-5d6991d31c64
6/24/21 6:19:00.582 PM [APP/1-0] OUT   Inside 
6/24/21 6:19:00.583 PM [APP/1-0] OUT   HTTP Server: [object Object]
6/24/21 6:19:03.236 PM [RTR] OUT   10.10.55.124 - - to HOST:51003 "GET /e6c13fc7-0a7f-4b08-b13d-4d3fd35ebe28 HTTP/1.1" 101 sent 0 in 3 by 00J-678712c6-98b9-4e6b-b4c3-5d6991d31c64
18:19:17:122#+03:00#ERROR#/AppController/Dispatcher################PLAIN##[ 'Error occurred, Cannot proxy application requests...Error: connect ECONNREFUSED 127.0.0.1:50578' ]#
6/24/21 6:19:17.127 PM [RTR] OUT   10.10.55.124 - - to HOST:51003 "GET / HTTP/1.1" 200 sent 100 in 21 by 00J-678712c6-98b9-4e6b-b4c3-5d6991d31c64
6/24/21 6:19:17.366 PM [APP/1-0] SYS   #2.0#2021 06 24 18:19:17:361#+03:00#ERROR#/AppController/Dispatcher################PLAIN##[ 'Error occurred, Cannot proxy application requests...Error: connect ECONNREFUSED 127.0.0.1:50578' ]#

**Comment by jung-thomas** [comment]
These issue forum is for problems related to specific tutorials or their steps.  For general system problems you should contact SAP Support or post your question in the Community Q&A.
