### ISSUE TITLE
Retry Message Processing in Case of an Error

### ISSUE THREAD

**Issue by emdac** [SAPDocuments/Tutorials#6799]
Hi

https://developers.sap.com/tutorials/cp-integration-retry-processing.html

Is it possible to update this tutorial to use it with SAP Event Mesh ?

Regards

Emmanuel

**Comment by gauthamkrishna-sap** [comment]
Hello,
We are still working on updates for this series. In the meantime, this tutorial from TechEd is a great alternative to continue your integration learning journey: https://github.com/SAP-samples/teched2020-DEV165
Best Regards,
Gautham

**Comment by emdac** [comment]
Hi Gautham

Thank you for your help.
I have done the series when it was possible to do it.
I will try the teched example soon.

Thank you.

Emmanuel

Emmanuel Da Costa
________________________________
差出人: Gautham Krishna ***@***.***>
送信日時: Wednesday, July 14, 2021 6:01:57 PM
宛先: SAPDocuments/Tutorials ***@***.***>
CC: emdac ***@***.***>; Author ***@***.***>
件名: Re: [SAPDocuments/Tutorials] Retry Message Processing in Case of an Error (#6799)


Hello,
We are still working on updates for this series. In the meantime, this tutorial from TechEd is a great alternative to continue your integration learning journey: https://github.com/SAP-samples/teched2020-DEV165
Best Regards,
Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
