### ISSUE TITLE
Feedback on Tutorial: SAPUI5 - Display List Element Details

### ISSUE THREAD

**Issue by jonathanbaker7** [SAPDocuments/Tutorials#681]
Images say "appDetail", but the correct code is "detail"

**Comment by goubin510** [comment]
this mistake is still on going...

**Comment by thecodester** [comment]
I have updated the images. 

https://github.com/SAPDocuments/Tutorials/commit/6a541d7c69d27488786823e08c21e81f4d59b8d1
