### ISSUE TITLE
SAP HANA XS Advanced, Creating a Node.js Module

### ISSUE THREAD

**Issue by noorshaikh** [SAPDocuments/Tutorials#6902]
The application is throwing error while building the solution. 

Any thoughts to solve the issue. 

![Capture](https://user-images.githubusercontent.com/8439888/128790433-65ebf153-7e05-4a42-b20d-59b8811ed343.PNG)

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html
