### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by MiqueiasMaia** [SAPDocuments/Tutorials#7064]
I'm following the steps from [this](https://developers.sap.com/tutorials/cp-mobile-dev-kit-nativescript-geolocation.html) tutorial to get device coordinates but i I try to test on mobile device simulator, I'm retrieving the following error:

`JS: mdk.trace.app: failure error is 'SyntaxError: Cannot use import statement outside a module'`

How to fix it?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
