### ISSUE TITLE
Create an Application for Producing Messages

### ISSUE THREAD

**Issue by mintert91** [SAPDocuments/Tutorials#7096]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-nodejs-producing-app.html
--------------------------

This tutorial is tagged with "Java" but is a Node.js tutorial.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
