### ISSUE TITLE
Use Redis in the Kyma Runtime to Store and Retrieve Data

### ISSUE THREAD

**Issue by kennylomax** [SAPDocuments/Tutorials#7099]
Tutorials: https://developers.sap.com/tutorials/cp-kyma-redis-function.html
--------------------------

Write here how you think we can improve the tutorial ...
Hi 
the sentences 
"On line three, replace the value < REPLACE WITH GATEWAY_URL > with the GATEWAY_URL found in the Environment Variables below the function code. This value will defer from what is shown in the screenshot."
can be misinterpreted (as it was by me)..

The user needs to replace the entire section to the right of the equals sign, and not just the text < REPLACE WITH GATEWAY_URL > itself.  While it is clear with hindsight, it might be better to say
const COMM_GATEWAY_URL ="< REPLACE WITH GATEWAY_URL > "

Merci!
Ken

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
