### ISSUE TITLE
Use a Cost Function to Calculate Shortest Path

### ISSUE THREAD

**Issue by mohamedyosufdeenjmh** [SAPDocuments/Tutorials#7103]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-smart-multi-model-9.html
--------------------------

In Step 4, point number 5, there is a typo.
Current content: You have wrapped the **_GRPAH_** procedure into a table function which can be called in a SQL SELECT statement.
Expected content: You have wrapped the **_GRAPH_** procedure into a table function which can be called in a SQL SELECT statement.

"GRAPH" is mentioned as "GRPAH".

**Comment by VijayKrishnanSR** [comment]
Hi,
Thank you very much for letting me know. I will update the tutorial with the correction. I hope you found the tutorial helpful.
Regards,
Vijay

**Comment by mohamedyosufdeenjmh** [comment]
Hi Vijay,

You are welcome. Yes, I found the tutorial to be very helpful.

Kind regards
Yosuf

**Comment by VijayKrishnanSR** [comment]
Hi Yosuf,

Thank you for your feedback. I hope that you find the rest of the tutorials also helpful as well.

Regards,
Vijay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by mohamedyosufdeenjmh** [comment]
> Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 
> 
> 
> 
> If you still have questions, feel free to reopen the issue.

You are welcome!
