### ISSUE TITLE
Create Data Model and Lock Object in SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by ceedee666** [SAPDocuments/Tutorials#7105]
Tutorials: https://developers.sap.com/tutorials/abap-environment-lock-object.html
--------------------------
In step 6 of the tutorial contains the CDS source contains in line 9 the following code
```
association [0..1] to I_BusinessUser as _SAPSysAdminDataChangeUser on _SAPSysAdminDataChangeUser.UserID = room.lastchangedbyuser
```
In the current version of the SAP BTP ABAP environment the usage of `I_BusinessUser`is not allowed. Trying to active the CDS view results in the following error message:

Use of element USERID of CDS ENTITY I_BUSINESSUSERBASIC is not permitted.

**Comment by mervey45** [comment]
Hi @ceedee666 ,

in which system did you try this out? This is a tutorial for a licensed system.

Best regards,
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
