### ISSUE TITLE
Monitor a Standalone Data Lake in SAP HANA Cloud

### ISSUE THREAD

**Issue by seVladimirs** [SAPDocuments/Tutorials#7107]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-hdl-getting-started-4.html
--------------------------

I believe the question is wrongly defined, as the answer 'IQMONVIEWS' is not a procedure name, but a view/table.
![image](https://user-images.githubusercontent.com/9819889/139652542-e037421a-54ff-4a6c-9304-38bcb7430776.png)

**Comment by seVladimirs** [comment]
yep! tutorial is very well structured! thanks @VijayKrishnanSR

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
