### ISSUE TITLE
Add a New Entitlement to Your Subaccount

### ISSUE THREAD

**Issue by AmauryVanEspen** [SAPDocuments/Tutorials#7109]
Tutorials: https://developers.sap.com/tutorials/cp-cf-entitlements-add.html
--------------------------

Hello,
It seems i'm not able to get the badge of this activity
however i've got the right answers to step 4.

Could you please check ?
Thank you

Amaury

**Comment by IObert** [comment]
Hi,

can you please provide a screenshot that shows that all steps are marked with green checkmarks. And also add your community ID please.

**Comment by AmauryVanEspen** [comment]
Hello
amauryvanespen
![image](https://user-images.githubusercontent.com/4487041/139821391-a1ebaad0-2dae-410e-808b-1b509a961fa8.png)
Thank you
Amaury

**Comment by IObert** [comment]
Thanks, I just checked and I can confirm that you completed the tutorial. Let me see why the badge hasn't been assigned.

**Comment by AmauryVanEspen** [comment]
Hello Marius,
about the tutorial, it has been fulfilled in January 2020
[image: image.png]
This may interest Daniel

Regards
Amaury

Le mar. 2 nov. 2021 à 14:35, Marius Obert ***@***.***> a
écrit :

**Comment by IObert** [comment]
@thecodester  Could it be that the tutorial was completed so long ago?

**Comment by thecodester** [comment]
We're checking on the backend, but in the meantime we can manually assign the badge. It shouldn't matter it was so long ago, but checking.

**Comment by IObert** [comment]
The badge is now associated to your profile. Thanks for your patience and sorry for the inconvenience :)
