### ISSUE TITLE
Get a Free Account on SAP BTP Trial

### ISSUE THREAD

**Issue by AmauryVanEspen** [SAPDocuments/Tutorials#7110]
Tutorials: https://developers.sap.com/tutorials/hcp-create-trial-account.html
--------------------------

Hello
It seems there is an issue with the badge provide, I've successfully completed the activity and I'm not able to get the related badge
Regards
Amaury

**Comment by IObert** [comment]
Hi,

can you please provide a screenshot that shows that all steps are marked with green checkmarks. And also add your community ID please.

**Comment by AmauryVanEspen** [comment]
Hello
amauryvanespen
![image](https://user-images.githubusercontent.com/4487041/139821499-3e54c14e-f60e-4d27-a69b-0f9836fac673.png)

Thank you
Amaury

**Comment by IObert** [comment]
Thanks, I just checked and I can confirm that you completed the tutorial. Let me see why the badge hasn't been assigned.

**Comment by IObert** [comment]
I see that badge #5DE96D shows in your profile now. Hence, I'll close the issue.

**Comment by thecodester** [comment]
@AmauryVanEspen Can you tell me about when you completed this and the other tutorial for which the badge is missing?

**Comment by AmauryVanEspen** [comment]
Hi Daniel,

find the date below
[image: image.png]
Regards
Amaury

Le jeu. 4 nov. 2021 à 07:16, Daniel Wroblewski ***@***.***> a
écrit :
