### ISSUE TITLE
Create Data Model and Lock Object in SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by Chathia** [SAPDocuments/Tutorials#7111]
Tutorials: https://developers.sap.com/tutorials/abap-environment-lock-object.html
--------------------------
While doing this tutorial, I'm facing an issue in "Step 6: Create data definition" while activating the CDS view: Z_I_ROOM_888.
In the below line of code, there is a syntax error:
**Code:**
 define root view Z_I_ROOM_888 as select from zroom_888 as room
  association [0..1] to I_BusinessUser as _SAPSysAdminDataChangeUser on _SAPSysAdminDataChangeUser.UserID = room.lastchangedbyuser

**Syntax Error:**
Multiple markers at this line:
    - Use of element UserID of CDS Entity I_BUSINESSUSER is not permitted.
    - Use of CDS Entity I_BusinessUser is not permitted.

I'm using the latest IDE and ADT. Version details below.
Eclipse IDE: 2021-09 (4.21.0)
ADT: 3.22.0

Kindly let me know if any fix required to the code.

Regards,
Chathia.

**Comment by mervey45** [comment]
Hi @Chathia , 

in which system did you try this out? This is a tutorial for a licensed system. 

Best regards, 
Merve

**Comment by Chathia** [comment]
Hi Merve,

I tried this in the ABAP on cloud trial account. This tutorial is assigned as part of Devtoberfest.

Regards,
Chathia.

**Comment by mervey45** [comment]
Hi @Chathia ,

unfortunately this tutorial can only be done in a licensed system. The trial system is limited.

Best regards,
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
