### ISSUE TITLE
Deploy a CAP Business Application to SAP Business Technology Platform

### ISSUE THREAD

**Issue by ahmedkhan29789** [SAPDocuments/Tutorials#7114]
Tutorials: https://developers.sap.com/tutorials/cap-service-deploy.html
--------------------------

step2. point number 4 "cf login"  doesn't work in visual studio code terminal, Getting below error

PS C:\Users\Ahmed_Ali_Khan\Music\SAP CAPM Learning\my-bookshop> cf login
cf : The term 'cf' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was   
included, verify that the path is correct and try again.
At line:1 char:1
+ cf login
+ ~~
    + CategoryInfo          : ObjectNotFound: (cf:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by iwonahahn** [comment]
Hi @ahmedkhan29789,

Have you downloaded and installed the cf command line client for Cloud Foundry as described in the prerequisites of the tutorial? You need this to execute `cf ...` commands.

Best regards,
Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
