### ISSUE TITLE
Map Fields Between Open Connectors and HubSpot

### ISSUE THREAD

**Issue by phdaucourt** [SAPDocuments/Tutorials#7115]
Tutorials: https://developers.sap.com/tutorials/cp-apim-openconnectors-common-resources.html
--------------------------

I cannot add new common resources as mentioned in the tutorial. I get the error message: "Failed to retrieve all templates We apologize for the inconvenience". 

![image](https://user-images.githubusercontent.com/13801682/139748144-ee19275b-87a4-4c3f-87a7-b460cc9a45fd.png)

Did I make something wrong in the previous steps? 

Thanks for your help.

**Comment by shilpavij** [comment]
Dear Colleague,

Have you clicked on basic companies? You can do two things:
1. Try to select other template
2. Or try to clear cache and create again.

Regards
shilpa

**Comment by phdaucourt** [comment]
Hi Shilpa,

I cleared my cache and tried again but unfortunately I cannot click on "basic-companies" tile nor select any other templates because my screen is completely empty.

![image](https://user-images.githubusercontent.com/13801682/140775946-7f24a2eb-540f-44d5-b94c-5163bff5cdaa.png)

What should I do to get the missing templates? Would it be an authorization issue?

**Comment by shilpavij** [comment]
Dear Colleague,

I cross-checked and looks like for a new account it doesn't work. Templates are not getting loaded.
This is a bug and will report it. 

Regards
shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by phdaucourt** [comment]
Hi Michael,

I’ve just tried again and unfortunately I’m still stuck with the same problem. My “Common Resources” screen has no tile and get the message “Failed to retrieve all templates We apologize for the inconvenience”.

Could you please reopen the issue?

Thanks.

Ph. Daucourt

**Comment by shilpavij** [comment]
This is a bug with the software and teams are working on it hence closing this issue on the tutorial.
