### ISSUE TITLE
Determine the Distance to a Target POI

### ISSUE THREAD

**Issue by zeitiger** [SAPDocuments/Tutorials#7119]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-smart-multi-model-3.html
--------------------------

Step 2 should give the hint to add a `SET SCHEMA DAT260;` if the query failed, because it could not find `LONDON_POI`

**Comment by VijayKrishnanSR** [comment]
Hi,

Thank you for the feedback.
This tutorial is part of a tutorial group "Smart Multi-Model Data Processing with SAP HANA Cloud". In the first tutorial, it has been mentioned as a note:

<img width="300" alt="2021-11-04_09-46-34" src="https://user-images.githubusercontent.com/84376241/140284506-f301a9b3-f15b-4e5f-96a9-56716aea0710.png">

Here is the link [Step 5, Tutorial [1]](https://developers.sap.com/tutorials/hana-cloud-smart-multi-model-1.html#57e0e948-7e26-45bd-99b5-8855553dcd14)

Hope this makes it clear.

Regards,
Vijay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
