### ISSUE TITLE
Load Data into Standalone Data Lake in SAP HANA Cloud

### ISSUE THREAD

**Issue by draschke** [SAPDocuments/Tutorials#7124]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-hdl-getting-started-3.html
--------------------------

Step 2: Create tables in data lake
Hi, I think it would be better, if you would mention that the user needs to choose the schema to find his tables.

![image](https://user-images.githubusercontent.com/4199123/140060470-dc78ca49-c2b0-4371-9f37-f2cab9773b32.png)

**Comment by draschke** [comment]
Hi Vijay,
yes, as you said, as a validation/check that the tables were created and to know where to look for it.
Best regards, Dirk

**Comment by VijayKrishnanSR** [comment]
Hi Dirk,

I have added the information at the end of Step 2. It will be updated soon. Thank you for you feedback.
I hope you found the tutorial helpful.

Regards,
Vijay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
