### ISSUE TITLE
Train Execution of ML Model (Postman)

### ISSUE THREAD

**Issue by kannankumar** [SAPDocuments/Tutorials#7129]
Tutorials: https://developers.sap.com/tutorials/ai-core-aiapi-postman-train.html
--------------------------

In Step 3: Create training configuration:

The endpoint looks incorrect
POST `{{apiurl}}/v2/lm/executions`

It should be
POST `{{apiurl}}/v2/lm/configurations`

**Comment by LunaticMaestro** [comment]
@kannankumar Thank you for pointing out, we have fixed the same in the latest push.
