### ISSUE TITLE
Create an SAP HANA Graph Workspace

### ISSUE THREAD

**Issue by draschke** [SAPDocuments/Tutorials#7131]
Tutorials: https://developers.sap.com/tutorials/hana-graph-overview-setup.html
--------------------------
Step 11: Add more data
In my case I had to add the schema "SKIING" for the data import . 

--Add lifts down to boarding stations
INSERT INTO "SKIING"."EDGES" VALUES (1061, 1755, '', 2, 1, 'lift', 'open') ;
INSERT INTO "SKIING"."EDGES" VALUES (1060, 2453, '', 5, 4, 'lift', 'open') ;
INSERT INTO "SKIING"."EDGES" VALUES (1070, 1223, '', 13, 14, 'lift', 'open') ;
INSERT INTO "SKIING"."EDGES" VALUES (1071, 1151, '', 14, 15, 'lift', 'open') ;

Regards, Dirk

**Comment by mkemeter** [comment]
Hi Dirk,

many thanks for your feedback! Explicitly adding the schema is only required if your current connection does not use `SKIING` as a default schema. In step 3 of the tutorial and line 3 of the code, you have executed `SET SCHEMA "SKIING"` to make sure that your current connection is using schema `SKIING` per default. The same is (redundantly) happening in step 5, line 1.

It sometimes occurs that your connection gets interrupted and you have to re-establish it. If you haven't rerun `SET SCHEMA "SKIING"` in this case, you can run into the issue that you are facing.

Can you please verify if your code is working when running `SET SCHEMA "SKIING"` like in step 5, line1 and let me know if this solved the issue?

Regards,
Mathias

**Comment by draschke** [comment]
> _SET SCHEMA "SKIING" to make sure that your current connection is using schema SKIING_

Hi Mathias,
sorry, I didn't know that. I tried it and it works.  Thanks for this hint, very good to know.   :)
Regards Dirk
