### ISSUE TITLE
Develop a Vue Application for SAP BTP on Cloud Foundry

### ISSUE THREAD

**Issue by IObert** [SAPDocuments/Tutorials#7136]
Tutorials: https://developers.sap.com/tutorials/appstudio-vue-getting-started.html
--------------------------

Hi Raz,

I'm testing this tutorial for the Devtoberfest which will feature this tutorial next week. While doing so, I found the following issue:

Step 3:
I cannot run `npm run watch` and neither can I run `npm install`. See here for the detailed logs:

<img width="1766" alt="Screenshot 2021-11-04 at 14 25 19" src="https://user-images.githubusercontent.com/1873245/140321732-0f127595-a579-42de-b571-39b803331a07.png">

PS: Can you please take care of this before MO as we expect many participants to complete the tutorial then.

**Comment by raz-korn** [comment]
Hi @IObert ,

Hi Marius, I've just tested the tutorial - run smoothly. No hiccups. 
Make sure that you opened the workspace on this specific project.
When in BAS > Explorer, at the bottom of the pane there's a "NPM SCRIPTS" section. When you expand it do you see that a watch script is available?

Regards - Raz

**Comment by IObert** [comment]
Yes, I see it but it doesn't work there either :(
![Screenshot 2021-11-05 at 09 01 59](https://user-images.githubusercontent.com/1873245/140477802-7639732b-7ea7-4103-a726-9df51493cb4e.png)

I'm running on Trial if that makes a difference and my workspace ID is ws-ckcmg.

**Comment by steven-g** [comment]
I have the exactly same issue with my trial account.

**Comment by raz-korn** [comment]
Hi @IObert , 

Can you share a screenshot of the top of the Explorer pane where the workspace is displayed?
Also the logfile of the run that is mentioned at the bottom of the screenshot you shared?

Regards - Raz

**Comment by IObert** [comment]
Sure thing @raz-korn 
Here are the other details:
`https://hc-test-lnqhafdr.us10cf.trial.applicationstudio.cloud.sap/index.html#ws-ckcmg`

```
 cat  /home/user/.npm/_logs/2021-11-08T08_21_43_273Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/opt/nodejs/node-v14.17.6-linux-x64/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle app@0.1.0~prewatch: app@0.1.0
6 info lifecycle app@0.1.0~watch: app@0.1.0
7 warn lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v14.17.6-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
8 verbose lifecycle app@0.1.0~watch: unsafe-perm in lifecycle true
9 verbose lifecycle app@0.1.0~watch: PATH: /opt/nodejs/node-v14.17.6-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/projects/VueDemo/businesspartners/node_modules/.bin:/home/user/.node_modules_global/bin:/extbin/bin:/extbin/npm/docker/bin:/extbin/npm/globals/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/curl/bin
10 verbose lifecycle app@0.1.0~watch: CWD: /home/user/projects/VueDemo/businesspartners
11 silly lifecycle app@0.1.0~watch: Args: [ '-c', 'vue-cli-service build --watch' ]
12 info lifecycle app@0.1.0~watch: Failed to exec watch script
13 verbose stack Error: app@0.1.0 watch: `vue-cli-service build --watch`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/opt/nodejs/node-v14.17.6-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid app@0.1.0
15 verbose cwd /home/user/projects/VueDemo/businesspartners
16 verbose Linux 5.4.0-6-cloud-amd64
17 verbose argv "/opt/nodejs/node-v14.17.6-linux-x64/bin/node" "/usr/local/bin/npm" "run" "watch"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error syscall spawn
22 error file sh
23 error errno ENOENT
24 error app@0.1.0 watch: `vue-cli-service build --watch`
24 error spawn ENOENT
25 error Failed at the app@0.1.0 watch script.
25 error This is probably not a problem with npm. There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

**Comment by raz-korn** [comment]
I experience the same in a new dev space.
I'm investigating.

**Comment by raz-korn** [comment]
Due to issues with new releases of coa package, there's a need to manually install the latest valid release (2.0.2):

- Open a terminal
- Go to vue module folder
- Run "npm i coa@2.0.2"
- Run "npm i"

Regards - Raz
