### ISSUE TITLE
Identify Relevant Networks in Spatial Data

### ISSUE THREAD

**Issue by seVladimirs** [SAPDocuments/Tutorials#7140]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-smart-multi-model-4.html
--------------------------

Small typo 
![image](https://user-images.githubusercontent.com/9819889/140530909-61650e3b-5258-4a25-8b4b-667b80a36071.png)

**Comment by VijayKrishnanSR** [comment]
Hi,
Thank you for letting us know. This typo will be corrected soon. I hope you found the tutorial helpful.
Regards,
Vijay

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
