### ISSUE TITLE
Get Started with the SAP BTP Command Line Interface (btp CLI) - tips and tricks for btp.exe as btp

### ISSUE THREAD

**Issue by AmauryVanEspen** [SAPDocuments/Tutorials#7142]
Tutorials: https://developers.sap.com/tutorials/cp-sapcp-getstarted.html
--------------------------

Hello
could you provide a tip to alias .\btp.exe as btp in powershell ?
Thank you

![image](https://user-images.githubusercontent.com/4487041/140599610-33d5c386-8cda-4f99-96f7-ae07c8cf0d29.png)

Amaury

**Comment by annawenger20** [comment]
Hi @AmauryVanEspen 
try `new-alias btp <path-to-folder-with-btp.exe>\btp` - hope that'll work! 
Thanks for the feedback - I'll add this info to the tutorial. 
Bonne journée, 
Anna

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
