### ISSUE TITLE
Create an SAP Fiori Elements-Based UI

### ISSUE THREAD

**Issue by jcailan** [SAPDocuments/Tutorials#7145]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-fiori-elements.html
--------------------------

I just run through the tutorial today and below is my finding:

Step 4: Make header info editable > It looks like it is no longer need to put below setting:

```json
"editableHeaderContent": true
```

Actual setting:

```json
                "RisksObjectPage": {
                    "type": "Component",
                    "id": "RisksObjectPage",
                    "name": "sap.fe.templates.ObjectPage",
                    "options": {
                        "settings": {
                            "entitySet": "Risks"
                        }
                    }
                }
```

![image](https://user-images.githubusercontent.com/27951983/140638502-8b82a43f-c1cf-441e-9318-3d7651a6a6cf.png)

**Comment by slavipande** [comment]
Hi @jcailan ,

I tested the steps again, but unfortunately, I was not able to reproduce the behavior at your side. Here's what I got in the `app/risks/webapp/manifest.json`:
![2021-11-10_11-51-37](https://user-images.githubusercontent.com/46915717/141091783-dbcd409a-f4bf-419b-a2ed-8ce5c9758b80.png)

Also, the header info is not visible in the UI when creating a new risk:
![2021-11-10_11-52-49](https://user-images.githubusercontent.com/46915717/141091888-83293da6-18e0-492b-abfd-30778266ffbd.png)

Could you please share what versions of cds, node.js, and the SAP Fiori Tools Extension Pack are you using to make sure we're testing against the same conditions? 
Here's what my versions are:

-  `v1.4.0` of the SAP Fiori Tools Extension Pack
- cds, node.js
![2021-11-10_11-51-01](https://user-images.githubusercontent.com/46915717/141092489-f8afceef-9ad5-4467-9cd5-3e944927a95e.png)

Best regards,
Svetoslav

**Comment by iwonahahn** [comment]
Hi @jcailan,

We haven't heard from you in a while, so we are closing the issue. If you still have questions, feel free to reopen the issue.

Best regards,
Iwona
