### ISSUE TITLE
Introduce Resilience to your Application

### ISSUE THREAD

**Issue by edwin7** [SAPDocuments/Tutorials#7147]
Tutorials: https://developers.sap.com/tutorials/s4sdk-resilience.html
--------------------------

prerequisites?

**Comment by newtork** [comment]
What do we do with this issue?

**Comment by edwin7** [comment]
I think you need to add prerequisites for this tutorial. or at least the sample code to begin with.

**Comment by thecodester** [comment]
Can you provide more detailed information?

**Comment by edwin7** [comment]
STEP 4:
"Now let’s adapt the code in your integration test "
integration-tests/src/test/java/com/sap/cloud/sdk/tutorial/BusinessPartnerServletTest.java:


how can I get that file? 
There is no information about this. In other tutorials, prerequisites are provided.

**Comment by edwin7** [comment]
Are these the prerequisites:

https://developers.sap.com/tutorials/s4sdk-setup.html
https://developers.sap.com/tutorials/s4sdk-cloud-foundry-sample-application.html

**Comment by newtork** [comment]
> how can I get that file?

It's right below the quote of yours:
![image](https://user-images.githubusercontent.com/22489773/140919193-ca6ee211-7af4-44bf-beec-1076968edb39.png)

**Comment by newtork** [comment]
> There is no information about this. In other tutorials, prerequisites are provided.
> Are these the prerequisites: [...]

This tutorial is part of a series and assumes knowledge, certain steps and code blocks already present:
https://developers.sap.com/mission.cloudsdk-cf-app.html

![image](https://user-images.githubusercontent.com/22489773/140919361-3e0372b3-8087-4125-a20f-2fcf019bd358.png)

**Comment by newtork** [comment]
If you are interested in a dedicated documentation towards Resilience with SAP Cloud SDK, please find our official material here:
https://sap.github.io/cloud-sdk/docs/java/features/resilience/resilience

The linked documentation is updated regularly, whereas the tutorial that you work on is almost 3 years old.

**Comment by edwin7** [comment]
not always. depends where you have accessed the tutorial.

If you go to:
https://developers.sap.com/group.cloudsdk-more-features.html


You will not see it as a part of the mission you are mentioned.
We are also in the middle of devtoberfest. In this program, we shouldn't do the mission, just part of the group.
<img width="1231" alt="Screenshot 2021-11-09 at 19 07 45" src="https://user-images.githubusercontent.com/709198/140921954-6ad9ea23-75d6-47a7-ba62-13d88c6c1918.png">
<img width="1665" alt="Screenshot 2021-11-09 at 19 07 27" src="https://user-images.githubusercontent.com/709198/140921971-8994e591-025d-42f8-8532-69f01d972700.png">



> This tutorial is part of a series and assumes knowledge, certain steps and code blocks already present: https://developers.sap.com/mission.cloudsdk-cf-app.html
> 
> ![image](https://user-images.githubusercontent.com/22489773/140919361-3e0372b3-8087-4125-a20f-2fcf019bd358.png)

**Comment by edwin7** [comment]
We are using this tutorial for devtoberfest. 

> If you are interested in a dedicated documentation towards Resilience with SAP Cloud SDK, please find our official material here: https://sap.github.io/cloud-sdk/docs/java/features/resilience/resilience
> 
> The linked documentation is updated regularly, whereas the tutorial that you work on is over 2 years old.

**Comment by edwin7** [comment]
This is not the file. It is just snippet code.

Where can we download the repository?

you miss a part like this: 
<img width="631" alt="Screenshot 2021-11-09 at 19 15 07" src="https://user-images.githubusercontent.com/709198/140922550-bea05c9a-a503-4787-866f-d74df4b577c6.png">


> It's right below the quote of yours: ![image](https://user-images.githubusercontent.com/22489773/140919193-ca6ee211-7af4-44bf-beec-1076968edb39.png)

**Comment by edwin7** [comment]
It is just a suggestion to add it, as any other tutorials.

believe it or not, It helps a lots. Thank you.

This is another example with prerequisites:
<img width="1026" alt="Screenshot 2021-11-09 at 19 20 28" src="https://user-images.githubusercontent.com/709198/140923231-ca590386-c841-4e65-a8c3-8f8abbb884d7.png">
 https://developers.sap.com/tutorials/appgyver-create-application.html

**Comment by newtork** [comment]
> This is not the file. It is just snippet code.

These are the complete contents of the java source file. Do I understand you correctly, that you want to "download" a file and/or a repository instead of "viewing" the relevant contents?

> Where can we download the repository?

Currently there is no repository maintained for the tutorials.

> It is just a suggestion to add it, as any other tutorials. believe it or not, It helps a lots.

I totally agree with you. We'll try to improve this in the future. But please understand our current efforts are focused on documentation. We haven't created/updated tutorials for quite a while.

**Comment by edwin7** [comment]
I mean the whole application code, with pom.xml,etc. In the tutorial there is an instruction "Simply run mvn clean install as in the **previous tutorials** to test and build your application."

It is not clear which one is the previous tutorial. Using only this tutorial, we could not run mvn. There is no reference to the previous tutorial mentioned in this tutorial.

 
> > This is not the file. It is just snippet code.
> 
> These are the complete contents of the java source file. Do I understand you correctly, that you want to "download" a file and/or a repository instead of "viewing" the relevant contents?
> 
> > Where can we download the repository?
> 
> Currently there is no repository maintained for the tutorials.
> 
> > It is just a suggestion to add it, as any other tutorials. believe it or not, It helps a lots.
> 
> I totally agree with you. We'll try to improve this in the future. But please understand our current efforts are focused on documentation. We haven't created/updated tutorials for quite a while.

**Comment by artemkovalyov** [comment]
@edwin7, it's good feedback. We'll consider making tutorials more independent. We also plan to brush up our repository with examples so that we can point at them to avoid confusion. The tutorials were created some time ago and I agree they don't serve the purpose as well as they used to. We've been focusing on our [documentation](https://sap.github.io/cloud-sdk/docs/java/getting-started) in the recent time and our guides there are usually more up to date. If you'll see any issues or have questions about tutorials feel free to raise them here: https://github.com/SAP/cloud-sdk/issues. We'll try to help with them quickly. Quickly fixing the tutorials is not an easy task, unfortunately.

**Comment by edwin7** [comment]
Thank you @artemkovalyov

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
