### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by ASRHARDING** [SAPDocuments/Tutorials#7150]
In the tutorial "Expose Integration Flow Endpoint as API and Test the Flow", Step 2, final action 13, I get the wrong error:
   404 Not Found: 
   Requested route ('f74a39b1trial.it-cpitrial05-rt.cfapps.us10-001.hana.ondemand.com') does not exist.

Instead of expected error code 401:
   {
     "error": "unauthorised",
     "error_description": "An Authentication object was not found in the SecurityContext"
   }

I still get the same 404 error after adding the policy template in Step 4. Please see the attached document for screenshots of the Integration flow endpoint and API RequestProductDetails execution attempts.

Any ideas on why the API can't find the integration flow endpoint?

Many thanks in advance, Andrew

[20-11-07 - Expose Integration Flow Endpoint as API - 404 error.docx](https://github.com/SAPDocuments/Tutorials/files/7492808/20-11-07.-.Expose.Integration.Flow.Endpoint.as.API.-.404.error.docx)
.

**Comment by Karunaharan** [comment]
Hello @ASRHARDING - I checked the scenario and couple of other testers too checked this. We don't see such an issue. Looks like it is working well. Could you please try the scenario again? Please let me know if you need further assistance.

Regards,
Karuna

@MichaelCzcz - please close the issue.

**Comment by ASRHARDING** [comment]
Hi Karuna

The reason for me getting the 404 error was because I omitted the /http/products at the end of the URL in Step 2, task 4.  With that corrected I now get the expected 401 error in Step 2, task 13, but the response body/headers are different to the example shown in the tutorial. This latter deviation doesn't seem to matter since I end up with the same response as the tutorial in Step 5, task 4.

Regards,
Andrew
