### ISSUE TITLE
Explore the ABAP Repository

### ISSUE THREAD

**Issue by muhamadnazimabubakar** [SAPDocuments/Tutorials#7153]
Tutorials: https://developers.sap.com/tutorials/abap-dev-learn-repo.html
--------------------------

I believe the for Step 3,  No 2,  the shortcut key should be Ctrl+Shift+A instead of Alt+Shift+A

**Comment by julieplummer20** [comment]
Hi, Yes, you're right.
Thanks a lot - I'll fix that at once.
Best wishes,
Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
