### ISSUE TITLE
Create Behavior and Service in SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by stevanic** [SAPDocuments/Tutorials#7164]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior-definition.html
--------------------------

Context menu to create New Behavior Implementation has been removed.

Reference:
https://answers.sap.com/questions/13215592/cannot-create-behavior-implementation-eclipse.html

Here is the updated steps to create a new behavior implementation
https://developers.sap.com/tutorials/abap-environment-behavior-action.html

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

I created following PR: #7225 for this issue.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
