### ISSUE TITLE
Set Up Account for Document Information Extraction and Go to Application - Screenshot Update Required

### ISSUE THREAD

**Issue by FarozanFarman** [SAPDocuments/Tutorials#7167]
Hi,

Tutorials: https://developers.sap.com/tutorials/cp-aibus-dox-booster-app.html
--------------------------
At Step 4: Access subscription (optional):
5.Here, you can navigate to the application by clicking Go to Application and also manage the Document Information Extraction Trial UI roles.

Now we have only 3 roles, so the screenshot to check/see the roles can be updated.
Expected Result:
![image](https://user-images.githubusercontent.com/71028764/140882058-162dcf6b-bddf-49ef-8887-3cb2ee1c2f6c.png)

Actual Result:
![image](https://user-images.githubusercontent.com/71028764/140882125-e272c36d-5dbc-444e-8602-6ce83014b1de.png)

Labels :
Landscape Labels: trail2
SCPTest-docinfo | Get Started with Document Information Extraction
Sprint Label: SCPTest-2111A
Priority label : 'Low'

Thanks and regards,
Farozan

**Comment by Juliana-Morais** [comment]
Hi Farozan,

The screenshot has been updated.

Best regards,
Juliana

**Comment by Juliana-Morais** [comment]
@MichaelCzcz: how do I close this issue?

**Comment by FarozanFarman** [comment]
Hi,
The issue is fixed. Hence I am closing this ticket.

Thanks and Regards,
Farozan
