### ISSUE TITLE
Connect GitHub and Docker to SAP AI Core (Client SDK)

### ISSUE THREAD

**Issue by MarcusSchiffer** [SAPDocuments/Tutorials#7169]
Tutorials: https://developers.sap.com/tutorials/ai-core-aiapi-clientsdk-repository.html
--------------------------

Hi, 
submitting the code to github gives
"Failed to post /admin/repositories: Jwt issuer is not configured"

No updates written.

**Comment by LunaticMaestro** [comment]
Hi Markus,
The issue is discovered caused by incorrect provisioning of the SAP AI Core.
Please refer to the official SAP Guide of SAP AI Core.

Thanks & Regards.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
