### ISSUE TITLE
Enhance Behavior With Action and Validation

### ISSUE THREAD

**Issue by VanitaDhanagar** [SAPDocuments/Tutorials#7170]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior-action.html
--------------------------

Step 4 :Enhance behavior implementation

Point 7 : screenshot need to be updated 

Old  : 
![image](https://user-images.githubusercontent.com/80330660/140901837-65ad0c53-1df8-441d-8f03-24d6e17d3ba9.png)

New : 
<img width="924" alt="UI2" src="https://user-images.githubusercontent.com/80330660/140902536-db04f074-4318-4cac-8d6f-603f1fe32bcb.PNG">

Thanks and Regards ,
Vanita

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

I created following PR: #7225 for this issue.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
