### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by VanitaDhanagar** [SAPDocuments/Tutorials#7171]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior.html
--------------------------

Screenshot need to be updated 
step 2 :Create behavior definition for projection view
Point 7:  

Old : 
![image](https://user-images.githubusercontent.com/80330660/140902887-88c4aa31-05b7-4dcd-9359-6d9b19bb0099.png)

New :
<img width="935" alt="UI" src="https://user-images.githubusercontent.com/80330660/140902987-1c257689-777e-44d4-ad90-33aa02f7fead.PNG">

Thanks and Regards,
Vanita

**Comment by mervey45** [comment]
Hi @MichaelCzcz ,

I created following PR: #7225 for this issue.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
