### ISSUE TITLE
Integrate an SAP Fiori App into Your Portal Site – Standalone App Router (Cloud Foundry)

### ISSUE THREAD

**Issue by git-ashish** [SAPDocuments/Tutorials#7176]
Hello @IObert,

We have an advance use case of multi-tenancy. Is there a tutorial or demonstration on how to add a Fiori SAPUI5 app to Launchpad Service portal when using the **Standalone app router** in a multi module MTA app?

I have tried following the [Manual Integration Approach](https://help.sap.com/viewer/8c8e1958338140699bd4811b37b82ece/Cloud/en-US/ddb655ae45e44d499f2fa0ce503a46d9.html) as well as [the tutorial](https://developers.sap.com/tutorials/cp-portal-cloud-foundry-sapui5-app.html) but it doesn't seem to work.

The error that is seen is "Not Found". Strangely, the URL that is being triggered by the Launchpad Service appears to make use of the standalone FLP module in the target MTA app. Or this is what it is assuming. Is that true? 
The URL format looks like below:

`https://xxxx-trial-dev-fioridemostandloneapprouter-router.cfapps.ap21.hana.ondemand.com/cp.portal/ui5appruntime.html?sap-ui-app-id=nsapp.businesspartners&scenario=LAUNCHPAD&sap-startup-params=&sap-shell=FLP&sap-touch=0&sap-ui-versionedLibCss=true&sap-plugins=RTAPluginAgent&sap-theme=sap_fiori_3&sap-locale=en&sap-iframe-hint=UI5`

Please note this path in the above URL:

> /cp.portal/ui5appruntime.html?

![image](https://user-images.githubusercontent.com/2697421/141074682-0fbf7b7c-8b19-403b-8704-4ad149588710.png)

The configuration of the App in the Fiori Launchpad looks like this, making use of the destination:
![image](https://user-images.githubusercontent.com/2697421/141075348-078ecad0-985f-40b2-abd5-78fd3fcb2d9d.png)

While the deployed app is accessible without making use of an FLP module like below:

`https://xxxx-trial-dev-fioridemostandloneapprouter-router.cfapps.ap21.hana.ondemand.com/nsappbusinesspartners/index.html`

Thanks for any pointers!

**Comment by IObert** [comment]
Hi @git-ashish,

I am afraid this is the wrong place for that kind of questions as we only use this org for tutorial-related problem. Your question is probably better suited in the SAP Community <answers.sap.com>. 

I still want to comment your answers (I'm afraid I don't have a real answer): The approach you used in general is right, for MTX apps, you need to leverage standalone approuters and embed the tenant URLs in the Launchpad manually. BUT what confuses me is that you have `cp.portal` in your URL. Does that mean you use the portal service instance in the `mta.yaml` as well? If so, that shouldn't be the case.

**Comment by git-ashish** [comment]
Thanks for a quick response and sharing your thoughts about the issue, @IObert. Sure, I'll post this as a question on the SAP community forum next.

The strange part is that the `mta.yaml` does not have a portal service instance. Here is the `mta.yaml` for your perusal.
I created an MTA app with standalone router and added a Freestyle UI5 module. 

Any thoughts?

Also, is there a tutorial to add a UI5 app which uses standalone router to the Launchpad Service site?

Thanks!

> _schema-version: "3.2"
> ID: FioriDemoStandloneAppRouter
> description: FioriDemo with Standalone App Router
> version: 0.0.1
> modules:
> - name: FioriDemoStandloneAppRouter-router
>   type: approuter.nodejs
>   path: router
>   requires:
>   - name: FioriDemoStandloneAppRouter-html5-repo-runtime
>   - name: FioriDemoStandloneAppRouter-uaa
>   - name: FioriDemoStandloneAppRouter-dest-srv
>     group: destinations
>     properties:
>       forwardAuthToken: false
>       name: ui5
>       url: https://ui5.sap.com
>   - name: FioriDemoStandloneAppRouter-connectivity
>   parameters:
>     disk-quota: 256M
>     memory: 256M
> - name: FioriDemoStandloneAppRouter-app-content
>   type: com.sap.application.content
>   path: .
>   requires:
>   - name: FioriDemoStandloneAppRouter-repo-host
>     parameters:
>       content-target: true
>   build-parameters:
>     build-result: resources
>     requires:
>     - artifacts:
>       - nsappbusinesspartners.zip
>       name: nsappbusinesspartners
>       target-path: resources/
> - name: nsappbusinesspartners
>   type: html5
>   path: businesspartners
>   build-parameters:
>     build-result: dist
>     builder: custom
>     commands:
>     - npm install
>     - npm run build:cf
>     supported-platforms: []
> 
> resources:
> - name: FioriDemoStandloneAppRouter-uaa
>   type: org.cloudfoundry.managed-service
>   parameters:
>     config:
>       tenant-mode: dedicated
>       xsappname: FioriDemoStandloneAppRouter-${space-guid}
>     service: xsuaa
>     service-plan: application
> - name: FioriDemoStandloneAppRouter-html5-repo-runtime
>   type: org.cloudfoundry.managed-service
>   parameters:
>     service: html5-apps-repo
>     service-plan: app-runtime
> - name: FioriDemoStandloneAppRouter-dest-srv
>   type: org.cloudfoundry.managed-service
>   parameters:
>     config:
>       HTML5Runtime_enabled: false
>       init_data:
>         instance:
>           destinations:
>           - Authentication: NoAuthentication
>             Name: ui5
>             ProxyType: Internet
>             Type: HTTP
>             URL: https://ui5.sap.com
>           existing_destinations_policy: update
>       version: 1.0.0
>     service: destination
>     service-name: FioriDemoStandloneAppRouter-dest-srv
>     service-plan: lite
> - name: FioriDemoStandloneAppRouter-connectivity
>   type: org.cloudfoundry.managed-service
>   parameters:
>     service: connectivity
>     service-plan: lite
> - name: FioriDemoStandloneAppRouter-repo-host
>   type: org.cloudfoundry.managed-service
>   parameters:
>     service: html5-apps-repo
>     service-name: FioriDemoStandloneAppRouter-html5-srv
>     service-plan: app-host
> parameters:
>   deploy_mode: html5-repo
>   enable-parallel-deployments: true
> build-parameters:
>   before-all:
>   - builder: custom
>     commands:
>       - npm install
>
