### ISSUE TITLE
Deploy a CAP Business Application to SAP Business Technology Platform

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Tutorials#7177]
Tutorials: https://developers.sap.com/tutorials/cap-service-deploy.html
--------------------------
Step 2: Identify SAP BTP Cloud Foundry endpoint

3.From your subaccount copy the Cloud Foundry Environment API Endpoint value.

**Expected Result :-** 

Please change screenshot as we have an extra tab called "Settings" under "Security" Tab.

![image](https://user-images.githubusercontent.com/33411431/141078873-09cb32ac-fe52-45fd-b5a9-513cfa245f53.png)

Thanks
Mounika

**Comment by iwonahahn** [comment]
We have updated booth screenshots. Thanks for reporting it.
