### ISSUE TITLE
Install Jupyter and Run SAP AI API Client SDK on Python

### ISSUE THREAD

**Issue by MarcusSchiffer** [SAPDocuments/Tutorials#7184]
Tutorials: https://developers.sap.com/tutorials/ai-core-aiapi-clientsdk-setup.html
--------------------------

Hi,

somehow the tutorial did not work for me in the first place, so I deleted the service instance on SAP BTP and created a new ai core service and service key. Without any creation of additional resources I still see the app ( aicore-test-app-m6600) from my old instance when calling 
ai_api_client.rest_client.get(
    path="/admin/applications"
)
ai_api_client.rest_client.get(
    path="/admin/applications"
)
{'count': 1,
 'resources': [{'application_name': 'aicore-test-app-m6600',
   'path': 'workflows',
   'repository_url': 'https://github.com/MarcusSchiffer/aicore-test',
   'revision': 'HEAD'}]}

Also secrets etc seem to be existing also.

How to get rid of these and start from scratch?

Regards
Marcus

**Comment by LunaticMaestro** [comment]
Hi @MarcusSchiffer 

Please follow this guide to properly opt for Service Offboarding of SAP AI Core.
LINK: https://help.sap.com/viewer/2d6c5984063c40a59eda62f4a9135bee/LATEST/en-US/08303fe594ce48768265235323963283.html

Your concern that, you are able to retain the component of you SAP AI Core is answered in the page (link above).

Regards,
Deepak.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
