### ISSUE TITLE
Connect GitHub and Docker to SAP AI Core (Postman)

### ISSUE THREAD

**Issue by SCHELLK** [SAPDocuments/Tutorials#7193]
Tutorials: https://developers.sap.com/tutorials/ai-core-aiapi-postman-repository.html
--------------------------
Step 4: API to connect GitHub SAP AI Core

The response is wrong. As response I receive after creating the repository is :
{
    "message": "Repository has been on-boarded."
}

But maybe there is a difference between canary and production...

**Comment by LunaticMaestro** [comment]
@SCHELLK  Thank you for highlighting the mistake. No there is no difference between the response for the API call of canary and production instances.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
