### ISSUE TITLE
Create a User Interface with CAP (SAP HANA Cloud)

### ISSUE THREAD

**Issue by rohithch21** [SAPDocuments/Tutorials#7194]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-ui.html
--------------------------

On running the template for creating a Fiori based freestyle application. Following are the observed difference from the steps provided in the tutorial.

1. The app "interaction_items" are automatically created within app folder. 
2. index.html is missing in the webapp folder

![image](https://user-images.githubusercontent.com/57070779/141646874-c9b86c90-b746-4651-bc25-fbd141375641.png)

I tried it multiple times. The same behaviour is observed.

Thanks,
Rohith C H

**Comment by jung-thomas** [comment]
Are you sure that you choose SAPUI5 Freestyle as the application type in the first step of the wizard?
_Choose SAPUI5 freestyle as the application type, select SAP Fiori Worklist Application as the floor plan and press Next_

**Comment by rohithch21** [comment]
Yeah, I selected SAP freestyle app and Worklist as the floor plan.

**Comment by jung-thomas** [comment]
Ok - let me run through the tutorial as well later today. There might have been some change to the wizard recently. But this seems like an odd change.  Targeting the /app founder is actually nice but the lack of index.html feels like a step backwards. I might have to check with development.  I'll let you know once I hear back.

**Comment by rohithch21** [comment]
I agree. 😃 
Thank you.

**Comment by jung-thomas** [comment]
I ran through this and the earlier tutorials in the mission. I updated screenshots and adjusted for these changes in the wizard. The source code of the index.html file is now in tutorial with a manual step to create it until I can figure out what the plan is for the wizard and why this feature was removed.

**Comment by rohithch21** [comment]
Thank you for checking it.  😃
