### ISSUE TITLE
Design and Deploy Your First Integration Flow

### ISSUE THREAD

**Issue by JuergenMair** [SAPDocuments/Tutorials#7196]
Tutorials: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
--------------------------
Hello, 

I did the tutorial and got an error "Deployment can only be done for a tenant that this application drives. Tenant: 5d1307bctrial is not driven by this application". I did the tutorial twice (including fresh setup of Trial account and Integration Suite Tenant) and always get the same error. 

I also checked that the Process Integration with integration flow plan is running, which is the case. 

I have no idea what is missing here - I did exactly as decribed in the tutorial. 

![image](https://user-images.githubusercontent.com/64806044/141697824-0c549343-9c76-4fda-9a2c-dd245aa100db.png)

**Comment by Karunaharan** [comment]
Hi @JuergenMair - as discussed over an email, the team is looking into the issue.

**Comment by Karunaharan** [comment]
Hi @JuergenMair 
Kindly provide below details to investigate on this issue further

System ID:
Landscape:
Tenant affected:

**Comment by JuergenMair** [comment]
Hello @Karunaharan
please find the infos for my Trial environment below:

Account ID: 02be363c-91bc-4fc4-b20e-7f34ab357207
Tenant ID: 1712c112-3677-4d1b-855c-fd3dc16192c2
Subaccount ID: 1712c112-3677-4d1b-855c-fd3dc16192c2
Cloud Foundry Environment - Org Name: 5d1307bctrial
Cloud Foundry Environment - Org ID: f1c0609b-1803-4567-80ee-b88405debddc
Process Integration Runtime Instance: default_it-rt_integration-flow

I'm not sure about System ID and Landscape - where do I find this information?

**Comment by Karunaharan** [comment]
Additionally can you provide the subdomain name as well, please? this is available in the subaccount overview page.

**Comment by JuergenMair** [comment]
Sure - Subdomain: 5d1307bctrial

**Comment by Karunaharan** [comment]
Thank you. I'll get back as soon as I have some news.

**Comment by Karunaharan** [comment]
@JuergenMair - The issue is resolved. You should be able to deploy now.

@MichaelCzcz - please close the issue.

**Comment by JuergenMair** [comment]
Ok, just tested it successfully - many thanks for your quick help!
