### ISSUE TITLE
Create a User Interface with CAP (SAP HANA Cloud)

### ISSUE THREAD

**Issue by ShaileshYadav92** [SAPDocuments/Tutorials#7202]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-ui.html
--------------------------

When we try to create a SAP Fiori Worklist Application using Fiori: Open Application Generator, it does not create index.html file in webapp folder.

**Comment by jung-thomas** [comment]
Yes there does appear to have been a change in the wizard very recently. Unfortunately this week I'm 100% consumed supporting SAP TechEd on site in Germany.  I will adjust this tutorial first thing when I return home next week.

**Comment by jung-thomas** [comment]
I ran through this and the earlier tutorials in the mission. I updated screenshots and adjusted for these changes in the wizard. The source code of the index.html file is now in tutorial with a manual step to create it until I can figure out what the plan is for the wizard and why this feature was removed.
