### ISSUE TITLE
Create a CAP-Based Application

### ISSUE THREAD

**Issue by JoseCarlosGZ** [SAPDocuments/Tutorials#7204]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-cap-application.html
--------------------------

This is not actually a bug within the code  but a path misspell in the tutorial:

Since the names of the folders inside 'templates' seems to have been changed, where it says "Copy the file schema.cds from templates/cap/create-service/db to the db folder of your app."  it should say   "Copy the file schema.cds from templates/create-cap-application/db to the db folder of your app."

**Comment by iwonahahn** [comment]
Hi @JoseCarlosGZ,

Thank you for your feedback. An update is already prepared and will be published later today. Once the tutorial was updated I will close this issue here.

Best regards,
Iwona
