### ISSUE TITLE
Prepare for SAP BTP Development

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#7212]
Tutorials: https://developers.sap.com/tutorials/btp-app-prepare-btp.html
--------------------------

Hi @iwonahahn,

the link in step 4 of the tutorial points to https://controlcenter.ondemand.com and there I end up with this error message:

<img width="605" alt="Screenshot 2021-11-16 at 23 17 44" src="https://user-images.githubusercontent.com/2639535/142075050-4ad53d8e-0ee2-4a49-92d8-7e41da282141.png">

> Response has invalid status code urn:oasis:names:tc:SAML:2.0:status:RequestDenied, status message is User is currently not authorized for access

I think https://hana.ondemand.com/ would be the better landing page or?

CU
Gregor

**Comment by iwonahahn** [comment]
Hi @gregorwolf,

For me, the link is working. Could you please check again and get back to me here?

Thank you and best regards,
Iwona

**Comment by gregorwolf** [comment]
Hi Iwona,

when I try in a fresh browser and authenticate via my S-User certificate I get:

![Screenshot 2021-11-19 at 07 50 21](https://user-images.githubusercontent.com/2639535/142578037-d6e03f31-d66c-4b94-bb62-87f66232e11e.png)

I think https://controlcenter.ondemand.com/ is SAP Only or?

Best Regards
Gregor

**Comment by iwonahahn** [comment]
Hi Gregor,

We will check and get back to you asap.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi Gregor,

You are right. We will remove this from the tutorial today. Thank you for reporting it.

Best regards,
Iwona
