### ISSUE TITLE
Connect GitHub and Docker to SAP AI Core (Client SDK)

### ISSUE THREAD

**Issue by MarcusSchiffer** [SAPDocuments/Tutorials#7217]
Tutorials: https://developers.sap.com/tutorials/ai-core-aiapi-clientsdk-repository.html
--------------------------

Hi, 
I Have created everthing new from scratch , New tenant, new service etc.
After that I followed the tutorial once again and when calling the
app_json = setup_json["app"]
response = ai_api_client.rest_client.post(
path="/admin/applications",#
body={
"applicationName": app_json["applicationName"],
"repositoryUrl": app_json["repositoryUrl"],
"revision": app_json["revision"],
"path": app_json["path"]
}
)

with app name "aicore-test-app" i get: already exists although everything was started from scratch.
The list apps shows no entry however.
When using another app name, it creates the app but still the status is showing the above behaviour with the blank entries.

Please advise.

Regards
Marcus

**Comment by LunaticMaestro** [comment]
Hi @MarcusSchiffer ,

The issue must have resolved itself after a while. 
Please let us know if you are still facing the issue in context. 

Regards.
