### ISSUE TITLE
Subscribe to the Low-Code / No-Code Service in SAP BTP

### ISSUE THREAD

**Issue by SMG1985** [SAPDocuments/Tutorials#7221]
Tutorials: https://developers.sap.com/tutorials/appgyver-subscribe-service.html
--------------------------

Hi, experts I have tried to find Low-code services in booster as well as service market place in my free BTP account swetagohil@gmail.com but it does not exists. Does it not available with Free Trial? Please guide.

**Comment by heytombeck** [comment]
Hi @SMG1985 - this service is only available with an active SAP BTP EU10 account with entitlements, as noted in the prerequisites: 

- Access to an SAP BTP account in EU10 with Low-Code / No-Code entitlements

While this means that you can't complete the mission with a free account, you can still create applications (and follow most of the tutorials) by signing up for free at www.appgyver.com. The layout and features in this edition are very similar, though there may be slight changes to the location of buttons and the colour scheme.

**Comment by SMG1985** [comment]
Thank you for your quick response and guidance.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
