### ISSUE TITLE
Update Request for Tutorial: Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by snOm3ad** [SAPDocuments/Tutorials#7233]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

The MTA Deployment Descriptor no longer gets generated when instantiating an SAP UI5 Freestyle application template. You have to select the Multi-Target Application template in order for SAP Business Application Studio to generate the `mta.yaml` file. The tutorial should be updated to reflect this!

**Comment by cjbernal** [comment]
Hi there,

Thank you for bringing this to our attention. I am currently reaching out to product experts to get the procedure updated.

Kind regards,
Conrad (SAP UX Engineering)

**Comment by ianquigley-sap** [comment]
Hi @snOm3ad ,

Thank for your comments above.  I have run through the tutorial and the mta is still getting generated correctly for me as part of this flow.  Please note 2 things:

1. You need to wait until the generator finishes installing all the libraries before the `mta.yaml` file will get created.  This can take a few minutes.
2. There is a bug in the Fiori generator currently that displays an error popup at the end of generation when no data source has been provided.  This does not affect the generated application, and the `mta.yaml` file should still be created.  

Please note, for 2. above we will be releasing a fix later this week.

Please let me know if you are still able to recreate the issue with the `mta.yaml` file not being created?

Thanks again,
Ian

**Comment by snOm3ad** [comment]
@ianquigley-sap It seems I had not realized that you needed to wait for the installer to finish things up before logging into the workspace. Entering the workspace before the installer finishes seems to locks it (?) and terminate the installation process prematurely. After waiting for the finish message the corresponding `mta.yaml` file shows up, thank you for the clarification! I'll go ahead and close the issue.
