### ISSUE TITLE
Start Your MDK Application in the Editor

### ISSUE THREAD

**Issue by JOSEPHSASIKANTHREDDY** [SAPDocuments/Tutorials#7253]
Hi,
I am trying to execute the below tutorial but unable to deploy SAP MDK Mobile app to CF.
[https://developers.sap.com/tutorials/cp-mobile-dev-kit-offline-app.html](https://developers.sap.com/tutorials/cp-mobile-dev-kit-offline-app.html)
But unfortunately I get **Deploy failed. Detail: Failed with response code:404 detail:Not Found** error while build and deploying the Mobile application.

![image](https://user-images.githubusercontent.com/8137364/143718356-b803a484-04e0-40ef-b7d7-d1ffb52d902e.png)

Below are the logs on deploy.

> Executing task: node /tmp/vscode-unpacked/mdk-vsc-wing-1.0.20111119.vsix/extension/res/scripts/bundle-build.js '{"sdkVersion":"","platform":"iOS & Android","application":{"name":"ExtensionApp","basePath":"/home/user/projects/ExtensionApp"},"allAppFullPaths":["/home/user/projects/ExtensionApp/Application.app"],"validator":{"path":"/tmp/vscode-unpacked/mdk-vsc-wing-1.0.20111119.vsix/extension/tools/application-validator/validator-cli.js","logLevel":"error","stopBundleOnValidationError":false},"resultFile":"/home/user/tmp/MDKBundleTarget/ExtensionApp/.diagnostics","referenceApplications":{"/home/user/projects/ExtensionApp/Application.app":[]},"bundler":{"path":"/tmp/vscode-unpacked/mdk-vsc-wing-1.0.20111119.vsix/extension/tools/application-bundler/bundler-cli.js","externals":[],"filters":["/ExtensionApp/Web"],"devtool":"source-map"},"web":false,"targetPath":"/home/user/tmp/MDKBundleTarget/ExtensionApp","workingPath":"/home/user/tmp/MDKBundleFactory/ExtensionApp","appInfoFileName":".appInfo","createUploadBundleZip":true}' <

Validate command line is: node "/tmp/vscode-unpacked/mdk-vsc-wing-1.0.20111119.vsix/extension/tools/application-validator/validator-cli.js" --result-file "/home/user/tmp/MDKBundleTarget/ExtensionApp/.diagnostics" --sdk-version  --platform "iOS & Android" --seam-project "/home/user/projects/ExtensionApp" --log-level "error" --reference-applications '{"/home/user/projects/ExtensionApp/Application.app":[]}' --allAppFullPaths '["/home/user/projects/ExtensionApp/Application.app"]'

[18:39:06] -- validating --
Start validating the application /home/user/projects/ExtensionApp with the metadata schema supported in MDK SDK 
MDK Validator - [MDK] Information: The property Animated is only used on the iOS platform at [(4,4), (4,14)] in /home/user/projects/ExtensionApp/Actions/Service/CloseOfflineFailureMessage.action
MDK Validator - [MDK] Information: The property IsIconHidden is only used on the iOS platform at [(5,4), (5,18)] in /home/user/projects/ExtensionApp/Actions/Service/CloseOfflineFailureMessage.action
MDK Validator - [MDK] Information: The property Animated is only used on the iOS platform at [(4,4), (4,14)] in /home/user/projects/ExtensionApp/Actions/Service/CloseOfflineSuccessMessage.action
MDK Validator - [MDK] Information: The property IsIconHidden is only used on the iOS platform at [(5,4), (5,18)] in /home/user/projects/ExtensionApp/Actions/Service/CloseOfflineSuccessMessage.action
MDK Validator - [MDK] Information: The property Animated is only used on the iOS platform at [(3,4), (3,14)] in /home/user/projects/ExtensionApp/Actions/Service/InitializeOfflineFailureMessage.action
MDK Validator - [MDK] Information: The property Animated is only used on the iOS platform at [(1,4), (1,14)] in /home/user/projects/ExtensionApp/Actions/Service/InitializeOfflineSuccessMessage.action
MDK Validator - [MDK] Information: The property IsIconHidden is only used on the iOS platform at [(4,4), (4,18)] in /home/user/projects/ExtensionApp/Actions/Service/InitializeOfflineSuccessMessage.action
MDK Validator - [MDK] Information: The property Animated is only used on the iOS platform at [(3,4), (3,14)] in /home/user/projects/ExtensionApp/Actions/Service/SyncFailureMessage.action
MDK Validator - [MDK] Information: The property Animated is only used on the iOS platform at [(1,4), (1,14)] in /home/user/projects/ExtensionApp/Actions/Service/SyncSuccessMessage.action
End validation with 0 issue(s) - 0 error(s), 0 warning(s).

Bundle command line is: node "/tmp/vscode-unpacked/mdk-vsc-wing-1.0.20111119.vsix/extension/tools/application-bundler/bundler-cli.js" --nativescript-project "/home/user/tmp/MDKBundleTarget/ExtensionApp/app" --seam-project "/home/user/tmp/MDKBundleFactory/ExtensionApp/ExtensionApp" --externals  --filters /ExtensionApp/Web --devtool source-map --create-bundle
create-bundle was specified, so nativescript-project will be ignored.

[18:39:07] -- cleaning --
(node:873) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:873) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:873) Warning: Accessing non-existent property 'which' of module exports inside circular dependency

[18:39:07] -- building --
MDK Bundler - resolving application @path /home/user/tmp/MDKBundleFactory/ExtensionApp/ExtensionApp
MDK Bundler - found application 'ExtensionApp'
MDK Bundler - reading components @path /home/user/tmp/MDKBundleFactory/ExtensionApp/ExtensionApp
MDK Bundler - using ts2015 target for ts loader
MDK Bundler - copying /home/user/tmp/MDKBundleFactory/ExtensionApp/ExtensionApp to /tmp/vscode-unpacked/mdk-vsc-wing-1.0.20111119.vsix/extension/tools/application-bundler/build.definitions/ExtensionApp
MDK Bundler - compiling build.definitions/ExtensionApp/Styles/
MDK Bundler - reading components @path /home/user/tmp/MDKBundleFactory/ExtensionApp/ExtensionApp
MDK Bundler - using external modules 
MDK Bundler - using external modules 
MDK Bundler - using devtool option source-map
MDK Bundler - creating bundle /tmp/vscode-unpacked/mdk-vsc-wing-1.0.20111119.vsix/extension/tools/application-bundler/bundle.js
MDK Bundler - replacing bundle /home/user/tmp/MDKBundleFactory/ExtensionApp/ExtensionApp
MDK Bundler - reading components @path /home/user/tmp/MDKBundleFactory/ExtensionApp/ExtensionApp

[18:39:08] -- updating definitions --
MDK Bundler - replacing /home/user/tmp/MDKBundleTarget/ExtensionApp/app/bundle.js
MDK Bundler - replacing /home/user/tmp/MDKBundleTarget/ExtensionApp/app/bundle.js.map

[18:39:08] -- creating upload bundle --
MDK Bundler - archived files into /tmp/vscode-unpacked/mdk-vsc-wing-1.0.20111119.vsix/extension/tools/application-bundler/uploadBundle.zip

Terminal will be reused by tasks. 

Thanks.

**Comment by jitendrakansal** [comment]
@JOSEPHSASIKANTHREDDY this 404 error might has caused due to missing a mandatory feature in your app configuration in the mobile services.
Open Mobile services cockpit > you app id > assign "mobile app update" feature > redeploy

When you create an app config in mobile services by selecting app type as "Mobile development kit application" this feature (mobile app update) is assigned as default. This is covered in step 2.4 (https://developers.sap.com/tutorials/cp-mobile-dev-kit-ms-setup.html)

**Comment by JOSEPHSASIKANTHREDDY** [comment]
Hi @jitendrakansal,
Thank you very much.The issue got solved.
But following the same tutorial, in the next tutorial of generating an android/ios installation file through custom client.
I get the below error.

Using C:\Users\JosephSasikanthReddy\Downloads\MDK_SDK_6_0_5_001_Notarized\MDKClient_SDK\DemoSampleApp.mdkproject
Using C:\Users\JosephSasikanthReddy\Downloads\MDK_SDK_6_0_5_001_Notarized\MDKClient_SDK for out directory
Building client for Android
Creating application ExtensionApp
'ns' is not recognized as an internal or external command,
operable program or batch file.

'ns' is not recognized as an internal or external command,
operable program or batch file.

Error: Failed to create application

![image](https://user-images.githubusercontent.com/8137364/143919459-4231edb4-2263-4e13-9f31-d1c9226eb074.png)

Please let me know if I am missing any libraries.

Thanks.

**Comment by JOSEPHSASIKANTHREDDY** [comment]
Thanks @jitendrakansal ,I was able to fix the issue.
