### ISSUE TITLE
Manage Message Processing in Case of Errors

### ISSUE THREAD

**Issue by AmyLi1122** [SAPDocuments/Tutorials#7262]
Tutorials: https://developers.sap.com/tutorials/cp-integration-handle-exceptions.html
--------------------------

The question in Step6, the answer should be Failed, Completed, Escalated. But looks not correct. Please chcek.

**Comment by gauthamkrishna-sap** [comment]
Hello,
This tutorial has been deprecated. We will replace it with an updated tutorial in the coming weeks. Please watch out for "Integration Suite tutorials" in the SAP Tutorial Navigator for new updates. 
Thank you.
