### ISSUE TITLE
Deploy a CAP Business Service to SAP Business Technology Platform

### ISSUE THREAD

**Issue by emildinchev** [SAPDocuments/Tutorials#7286]
Tutorials: https://developers.sap.com/tutorials/cap-service-deploy.html
--------------------------
I followed the tutorial and deployed the application on my trial sub-account. After the deployment I noticed that 2 new applications appear in my space:
- my-bookshop-srv
- my-bookshop-db-deployer

When I try to delete some of them, the corresponding application remains in status STOPPED.
The deletion is not possible neither from BTP Cockpit nor via cf CLI tool.

**Comment by iwonahahn** [comment]
c
