### ISSUE TITLE
Screenshot for Content Modifier should be changed

### ISSUE THREAD

**Issue by PriyankaShivakumar** [SAPDocuments/Tutorials#7306]
Tutorials: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
--------------------------
Step 5: Add and configure content modifier

Here the screenshot for content modifier should be changed. The column names are changed. The Value column is now Source Value and Default is Default Value.

Expected:
![image](https://user-images.githubusercontent.com/65999547/145412697-afe826c6-3961-4d42-ab02-35fd28b66391.png)

In Tutorial:
![image](https://user-images.githubusercontent.com/65999547/145412827-817cc57a-5133-4003-aaee-b60199eff3cf.png)

Best Regards,
Priyanka

**Comment by Karunaharan** [comment]
@PriyankaShivakumar - Thanks for the feedback. Changes are made and pull request sent for the same.

@MichaelCzcz - please close the issue.
