### ISSUE TITLE
Open SAP Web IDE for SAP HANA Development

### ISSUE THREAD

**Issue by steve-guo-dk** [SAPDocuments/Tutorials#7308]
Tutorials: https://developers.sap.com/tutorials/webide-multi-cloud.html
--------------------------

Write here how you think we can improve the tutorial ...

The content of this turorial is not ralvant any more. It will be great if you do some clean up and delete thie tutorial.

**Comment by jung-thomas** [comment]
This tutorial remains for customers that have productive accounts and still use the Web IDE fullstack there.  It is marked as such.
