### ISSUE TITLE
Upload Flat Files and Wrangle Your Data

### ISSUE THREAD

**Issue by adadouche** [SAPDocuments/Tutorials#7316]
Tutorials: https://developers.sap.com/tutorials/data-warehouse-cloud-datapreparation-1-flatfiles.html
--------------------------

Write here how you think we can improve the tutorial ...

Could you provide the example csv file used to capture the screenshots?
This would help improving the user experience by relating the instructions

Thanks and keep up the good work!

**Comment by rashidabdulrahiman** [comment]
Hello @adadouche. Thanks for your input!

It is sadly not possible to provide you with the very same datasets. You can however try with the SAP Data Warehouse Cloud [sample dataset](https://github.com/SAP-samples/data-warehouse-cloud-content).

Additionally, the [Get Ready for Your SAP Data Warehouse Cloud Mission](https://developers.sap.com/tutorials/data-warehouse-cloud-1-begin-trial.html) is a handheld tutorial group that is supposed to guide you through with a provided dataset. You can try that as well.

I hope this helps. Thanks!

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by adadouche** [comment]
Hi @rashidabdulrahiman,

Thanks for getting back to me. 

I use this content as a replacement of the former SAP HANA Journey mission which was removed with my students.

They got confused with the approach of showing screenshot of something they can't do themselves.

I already asked my students to complete the Get Ready for Your SAP Data Warehouse Cloud Mission but wanted to also have a deeper understanding of DWC capabilities.

Can you consider this feedback for future updates and content to avoid confusion from the user perspectives?

Thanks again
