### ISSUE TITLE
Integrate and Monitor Data with SAP Data Warehouse Cloud

### ISSUE THREAD

**Issue by adadouche** [SAPDocuments/Tutorials#7317]
Tutorials: https://developers.sap.com/tutorials/data-warehouse-cloud-datapreparation-2-monitor.html
--------------------------

Write here how you think we can improve the tutorial ...

It would be great to have a link to a tutorial explaining how to setup a remote table so that as a user I could see it in action for "real"

Thanks and keep up the good work!

**Comment by rashidabdulrahiman** [comment]
Hey @adadouche ! Thanks for your input.

Please refer the [SAP Data Warehouse Cloud help document](https://help.sap.com/viewer/9f804b8efa8043539289f42f372c4862/cloud/en-US/4cbf7c7fc64645bfa364332827557267.html) for the same.

Thanks!

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
