### ISSUE TITLE
Feedback on Tutorial: Installing Binary

### ISSUE THREAD

**Issue by mtgran** [SAPDocuments/Tutorials#947]
Hi,

I get an installation error during the installation of the HANA Express edition, here is the log:

https://gist.github.com/mtgran/df3a01576e703b0bd98003a2aae801d3

**Comment by akula86** [comment]
Emailed author, assigned Craig as publisher

**Comment by larshp** [comment]
Hi,
Tutorial http://go.sap.com/developer/tutorials/hxe-ua-installing-binary.html mentions:
"
Prerequisites:
Linux SUSE for SAP in one of the following versions:
SUSE Linux Enterprise Server for SAP 12 SP1
SUSE Linux Enterprise Server for SAP 12
SUSE Linux Enterprise Server for SAP 11.4
"
And it looks like you are running under Ubuntu?

Anyhow, I've also tried on Ubuntu, I had a similar error, and another similar later, run:
`apt-get install libaio1 libltdl7`
to install some of the required libraries

(later my XSA installation also failed, but with some Python encoding errors, did not have time to look into that error)

**Comment by mtgran** [comment]
Thanks a lot, it works!
