### ISSUE TITLE
Feedback on Tutorial: Installing the VM Image

### ISSUE THREAD

**Issue by stealth70mde** [SAPDocuments/Tutorials#955]
Hello guys,

In the documentation/mini-guide to install the HXEDownloadManager it should be mentioned that you need to have a JRE 8 **64bit** version otherwise the program will NOT run. Also maybe a little background on how to set JAVA_HOME and PATH (for Windows users at least).

Cheers.

**Comment by carlsoane** [comment]
Thanks for the comment. We are updating the documentation.
