### ISSUE TITLE
Feedback on Tutorial: SAP HCP predictive services, Visualize your predictive demo data set

### ISSUE THREAD

**Issue by lucamanassero** [SAPDocuments/Tutorials#965]
Hi,

unfortunately after two hours of very careful debugging, I still cannot display the historical data.
When I click the button "Loda Historical Data", all what I get is an error message:

Caught - onLoadData[ajax success] :Cannot read property 'setProperty' of undefined

The OData service works OK (tested with PostMan) and the code under ODataDisplay.controller.js has been cut and pasted from your tutorial. No errors are underlined by the SAP Web IDE.

Any help would be highly appreciated,

Luca

**Comment by adadouche** [comment]
Hi Luca,

Thanks for raising this issue.

I revisited the tutorial content and found out that I missed the model initialization code in the index.html file.

Here the content of the file which will solve the issue you are facing. I have only put the "attachInit" function from the index.html file:

    sap.ui.getCore().attachInit(function() {
      sap.ui.getCore().setModel(new sap.ui.model.json.JSONModel());
      new sap.m.Shell({
        app: new sap.ui.view({
          height : "100%",
          viewName: "demo.view.demo",
          type: sap.ui.core.mvc.ViewType.XML
        })
      }).placeAt("content");
    }); 

Thanks again for you feedback.

@bdel

**Comment by lucamanassero** [comment]
Thank you for the tutorial!
Learning SAP HANA Development is a kind of steep learning curve, but with the help of toutorials like this one things get a bit easier every day ;-)
