### ISSUE TITLE
Cannot import delivery unit /hana/shared/HXE/global/hdb/auto_content/SAP_WATT.tgz

### ISSUE THREAD

**Issue by mtgran** [SAPDocuments/Tutorials#970]
Hi,

I am installing XSC, but I get the following error during the execution of 

`sudo /hana/shared/HXE/global/hdb/install/bin/hdbupdrep --content_directory=/hana/shared/HXE/global/hdb/auto_content`

> Enter Database User Name [SYSTEM]: 
> Enter Database User (SYSTEM) Password: 
> Importing delivery units...
> Importing delivery unit SAPUI5_1
> Importing delivery unit SAP_WATT
> Update Repository failed
>   Cannot import delivery unit /hana/shared/HXE/global/hdb/auto_content/SAP_WATT.tgz
>   Check the log file for SAP HANA Database error messages

Here the full log: https://gist.github.com/mtgran/e911e7c7766819bce3f7f212fb492d65

**Comment by carlsoane** [comment]
Hello mtgran:

The log indicates some traces were written to the following files as well:

-  nameserver_alert_stargate.trc
-  nameserver_stargate.30001.000.trc

Are you able to share those files?
hose files?

Thanks,

Carl

**Comment by carlsoane** [comment]
Hello mtgran:

It appears that you may have run out of system resources per the error from the log file that I've pasted below (see ERROR). The log file also references trace files (see TRACE FILES below) that may be helpful as well.  Can you send them? I've also listed some things to check to see if you are running out of resources:

################################
ERROR
################################
Starting external program /hana/shared/HXE/HDB00/exe/regi
21:15:05.444 - INFO:       Command line is: /hana/shared/HXE/HDB00/exe/regi --verbose --workspace=empty --host=stargate:30013 --user=SYSTEM --readFromStdIn import /hana/shared/HXE/global/hdb/auto_content/SAPUI5_1.tgz
21:15:05.455 - INFO:       Output line 1: Password: 
21:15:09.309 - INFO:       Output line 2: Failed to execute prepared statement: transaction rolled back by an internal error: Allocation failed ; $size$=125267935; $name$=libhdbrepocore.so; $type$=pool; $inuse_count$=772; $allocated_size$=208080

################################
TRACE FILES
################################
21:15:46.148 - INFO:   nameserver_alert_stargate.trc: More than 50 relevant messages found, check file.
21:15:46.177 - INFO:   nameserver_stargate.30001.000.trc: More than 50 relevant messages found, check file.

################################
RESOURCE CHECKS
################################
If you have HANA studio, right click on the system and select Configuration and Monitoring -> Open Administration and check the Overview and Landscape tabs for anything in red.

If you don't have HANA Studio, you can run the following queries in hdbsql to find out resource usage by HANA:

--Detailed information on memory utilization by services
select service_name, round(effective_allocation_limit/1024/1024/1024, 1) as MemLimit, round(total_memory_used_size/1024/1024/1024,1) as MemUsed from m_service_memory;

--Overview of system status including important resource usage information and alerts
select * from m_system_overview;

You can also run the following command at the command line to see free memory:
free -g

free -g will report on free memory in gigabytes. The key number is in the second row (-/+ buffers/cache) in the free column. If this number is low, (e.g 1 GB) you may have run out of memory when importing the Delivery Unit.

You can also run the following command to see if you are running out of disk space on the VM's filesystem:
df -h

When you run df -h, you are interested in the Use% for the /dev/sda1 filesystem. If it is down to just a few GB, you may have run out of disk space while importing the Delivery Unit.

Regards,


Carl

**Comment by mtgran** [comment]
Hi Carl,

here are the logs:

[nameserver_alert_stargate.trc](https://gist.github.com/mtgran/f20ea1f29c5d49bab83c53b41bbc6941)

[nameserver_stargate.30001.000.tr](https://gist.github.com/mtgran/12804b51301ce1e062b2b99886565843)

Regards
mtgran

**Comment by carlsoane** [comment]
The nameserver alert file shows an out of memory error.  Were you able to run any of the other diagnostic information to see what your memory situation is? Thanks

Host: stargate
Executable: hdbnameserver
PID: 5018
Failed to allocate 125267935 byte.
Current callstack:
 **1: 0x00007f247bee339b in MemoryManager::PoolAllocator::notifyOOM(unsigned long, bool) const+0x97 (libhdbbasis.so)**
 2: 0x00007f247bee8156 in MemoryManager::PoolAllocator::oomHandling(unsigned long, unsigned long, unsigned long, bool)+0x72 (libhdbbasis.so)
 3: 0x00007f247bee8a37 in MemoryManager::PoolAllocator::allocateNoThrowImpl(unsigned long, void const*)+0x253 (libhdbbasis.so)

**Comment by mtgran** [comment]
yes, it seems a space issue with memory/hard disk.

[resources - command line](https://gist.github.com/mtgran/ccbe617d3f0ba9aaa7c195bcedca9d79)

A couple of questions:
1.- Which is the recommended buff/cache?
2.- How much space should be available in /dev/sda1? I have it mounted on /boot and the space it is less than 1 GB.

Is there any other recomendation from your side for the installation? There is no much information in the [official website](https://go.sap.com/developer/topics/sap-hana-express.system-features-requirements.html)

**Comment by ccmehil** [comment]
If this is the server only image you need at least 12GB of memory for the import to work and it takes awhile. After the import you can reduce the memory back down.
